### ISSUE TITLE
Creating Accounts 

### ISSUE THREAD

**Issue by DJTrb96** [thedevdojo/voyager#1]
Not so much a issue however to be able to add users without having a image would be cool out of the box. At the moment it spits out a SQL Error. However im guessing its a fairly simple fix of allowing avatar to be null. 

Error: 

" 
QueryException in Connection.php line 763:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'avatar' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `avatar`, `updated_at`, `created_at`) values (Dad, dad@dad.com, $2y$10$jZPJuDv/gyXLwSKVhx7Z7uohCf1/MqUmZv7cNJnIVrcLIEsESgAay, , 2016-10-28 02:33:34, 2016-10-28 02:33:34))
"

**Comment by krugerdavid** [comment]
Hi. A quick fix would be

a) a migration to set nullable the avatar fill

b) change on the DB directly 👍
