### ISSUE TITLE
Postgresql 'SHOW TABLES' support

### ISSUE THREAD

**Issue by ptcarino** [thedevdojo/voyager#10]
I'm currently using postgresql as my database and it seems 'SHOW TABLES' is not supported by it. I saw some workarounds by using google but that would mean I need to alter files in the vendor folder (which I don't like to do as I'll be pushing my app to bluemix).

**Comment by fletch3555** [comment]
Being handled here: https://github.com/the-control-group/voyager/issues/30#issuecomment-257441360

**Comment by marktopper** [comment]
Closing since it seems to be fixed
