### ISSUE TITLE
"Undefined property" when removing select dropdown option

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#1001]
- Laravel Version: 5.4.x
- Voyager Version: 0.11.7
- PHP Version: 7.1.1
- Database Driver & Version: MySQL X

### Description:
When you have a BREAD row using the `Select Dropdown` type, it give problems handling the options when a option is removed.

### Steps To Reproduce:
Make BREAD with a `Select Dropdown` row and the following settings:
```
{
    "default": "Foo",
    "options": {
        "foo": "Foo",
        "bar": "Bar"
    }
}
```
Then create a new row with this set as `Foo`.
Then edit the BREAD settings to:
```
{
    "default": "Bar",
    "options": {
        "bar": "Bar"
    }
}
```
Then go back to the row for that BREAD and it will throw the following error:
```
ErrorException in 1dc0155360549e4cd7aacdfed574eebe6a05f97e.php line 68:
Undefined property: stdClass::$foo (View: /site.dev/vendor/tcg/voyager/resources/views/bread/browse.blade.php)
```

### Solution
My idea for a solution is to show the default option if the option no longer exists.

**Comment by vaggelis2018** [comment]
This happens also when adding more options. It doesn't update correctly in database. If you delete the data entry from data_rows table even if it seems updated and save your bread again it works great. Don't know why yet

**Comment by handiwijoyo** [comment]
Can someone confirm that this already fixed in `1.0` ?

**Comment by yevgenatlanov** [comment]
@handiwijoyo it's not fixed so far.

**Comment by dhonions** [comment]
Duplicating my comment from #1639 in case it helps:

For me this error was solved with the exclusion of a null value on the obj:-
```
/vendor/tcg/voyager/resources/views/bread/browse.blade.php

Line 118
```
```
@unless(empty($options->options->{$data->{$row->field}}))
     {!! $options->options->{$data->{$row->field}} !!}
@endunless
```

*Edit: Let me know if it solves for you and I will submit PR *

**Comment by emptynick** [comment]
Yes that indeed works.  
Alternatively we could use `{!! $options->options->{$data->{$row->field}} or '' !!}`

**Comment by emptynick** [comment]
@dhonions Do you want to submit a PR for this?

**Comment by Golenzovskiy** [comment]
@emptynick Yes, please do.

**Comment by damms005** [comment]
@dhonions Superb work! Issue fixed. PR!

**Comment by d3turnes** [comment]
Hi, for me this error was solved with

{!! $options->options->{$data->{$row->field}} or $data->{$row->field} !!}
![parent_drop_down](https://user-images.githubusercontent.com/32837544/41385337-3054e462-6f7b-11e8-9a7f-4202d93ee203.png)
