### ISSUE TITLE
Change DataTypes seeders to use table prefix

### ISSUE THREAD

**Issue by abdgad** [thedevdojo/voyager#1003]
- Laravel Version: 5.4
- Voyager Version: 0.11.7
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
Right now, the data types seeders use table names without a prefix. This won't work correctly if a database prefix is set in Laravel's config ([more info](https://github.com/the-control-group/voyager/issues/391#issuecomment-289067894)). Need to change the seeders to use the prefix.

**Comment by mpge** [comment]
+1 - I'm having this issue as well. I'm having to manually remove the prefix from tables when adding BREAD which causes Voyager to not recognize that BREAD has already been added that table.

**Comment by thinkdj** [comment]
Also, voyager's tables are kind of polluting the DB view.  Would be great if all Voyager tables had vy_ prefix

**Comment by abdgad** [comment]
We are looking for a way to prefix voyager tables. It will be done in a future update.

**Comment by zkrige** [comment]
any news on when this will be done?

**Comment by dmitrychuba** [comment]
There is I fix that works for me: you need to edit vendor/tcg/voyager/src/Http/Controllers/VoyagerDatabaseController.php: [https://screencast.com/t/o45hYmeUS](url)

**Comment by fletch3555** [comment]
This is definitely not a bug.  We're looking at ways to handle the table name collision between Voyager and other packages, but that's being tracked in another issue.  In short, it's a complicated issue.  I'm going to close this for now.
