### ISSUE TITLE
Seeding fails with `Undefined index: table` during `PostsTableSeeder`

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1005]
- Laravel Version: 5.3.30
- Voyager Version: 0.11.7
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

### Description:

- When running `php artisan voyager:install --with-dummy`, fails at "Seeding data into the database" with `Undefined index: table` during `PostsTableSeeder`
- What am I doing wrong?

### Steps To Reproduce:

- Run `php artisan voyager:install --with-dummy`

**Comment by abdgad** [comment]
I am unable to reproduce this error. Try re-installing from scratch.

**Comment by u01jmg3** [comment]
I am installing from scratch already...

**Comment by u01jmg3** [comment]
Fixed by change in `app/config/auth.php`:

```php
    'providers' => [
        'users' => [
            'driver' => 'database',
            'model'  => App\Models\User::class,
            'table'  => 'users', // **This was missing**
        ],
    ],
```
