### ISSUE TITLE
Question regarding "Specified key was too long error" when using L5.3

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1007]
- Laravel Version: 5.3.30
- Voyager Version: 0.11.7
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

---

## Question

Regarding:

> Troubleshooting: Specified key was too long error. If you see this error message you have an outdated version of MySQL, use the following solution: https://laravel-news.com/laravel-5-4-key-too-long-error

- What happens if you are using Laravel 5.3 (where upgrading to L5.4 is not yet possible)?
  - (`Schema::defaultStringLength()` is not available to use.)

**Comment by abdgad** [comment]
See if [this](https://github.com/the-control-group/voyager/issues/901#issuecomment-287130500) helps.
