### ISSUE TITLE
Multiselect - Creating unnecessary fields in database?

### ISSUE THREAD

**Issue by harpster604** [thedevdojo/voyager#1008]
When setting up a multiple select relationship -

eg:
animals (id, name)
diseases (id, name)
animals_diseases (animal_id, disease_id)

Why must we create an extra field under the 'animals' table called 'diseases' which remains blank and is never used in order to add a multiple select relationship?

Shouldn't we be able to add relationships to a model without adding an extra column since all of the relationship data is stored in the pivot table, not in any of the actual model tables (animals, diseases)? I've used other admin packages before that are now outdated that have had it working correctly (Sleeping Owl v2).

I understand the relationships feature is still somewhat under construction but I just want to ask if this is something you are working towards. Thanks for the great work so far!

**Comment by DODMax** [comment]
+1
I was trying to solve that by playing with the adminFields() method on the model but looks like it's not fully implemented yet either.

**Comment by fletch3555** [comment]
Yes that would be ideal, but hasn't been completed.  If anyone wants to take a stab at it, we're open to Pull Requests.

**Comment by fletch3555** [comment]
This was resolved by the 1.0 release.  Relationships are now created dynamically
