### ISSUE TITLE
Question regarding Media Library and dot files

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1015]
- Laravel Version: 5.3.30
- Voyager Version: 0.11.7
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

---

## Question

- Is there anyway for the Media Library to exclude listing dot files such as `.gitignore`?

**Comment by turtuga** [comment]
Fix https://github.com/the-control-group/voyager/pull/1018
