### ISSUE TITLE
"Undefined index: name"

### ISSUE THREAD

**Issue by Al-Kaiser** [thedevdojo/voyager#1016]
Relationship json code: `{ "relationship": { "key": "id", "label": "name" } }`
i got this error : 
> ErrorException in Collection.php line 1440:
> Undefined index: name

when i try to open **/admincp/series**  display this error but if i try to open **/admincp/series/create** or **edit** work fine and my relationship value work

**Comment by marktopper** [comment]
Please share the relationship table :)

**Comment by wuelcas** [comment]
Glad I'm not the only one with this problem. This happens when the relationship is many to many. The problem is in the BreadRelationshipParser.php trait file in line 104 `$item[$field] = $relation[$relationData->label];`

When the relationship is one to one there's no problem because the `$relation` variable is the model of the table. When is many to many, the `$relation` variable is a collection that holds an array of models. This is what I mean when I dd that variable:

```
Collection {#881 ▼
  #items: array:1 [▼
    0 => TourKeyword {#887 ▶}
  ]
}
```

So when the relationship is many to many, the proper way to get the data in that line is like this: `$item[$field] = $relation[0][$relationData->label];`

**Comment by Al-Kaiser** [comment]
@marktopper 
this is my migrations

**Series** 
```
 <?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSeriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('series', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
			$table->text('desc')->nullable();
            $table->integer('genre')->nullable();
			$table->string('slug')->unique();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('series');
    }
}

```
**genre** 
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGenresTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('genres', function (Blueprint $table) {
            $table->increments('id');
			$table->string('title');
			$table->string('name');
			$table->text('desc')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('genres');
    }
}
```
**and this my relationship** 

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSeriesGenre extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('genre_series', function (Blueprint $table) {
            $table->integer('series_id')->unsigned()->index();
            $table->foreign('series_id')->references('id')->on('series')->onDelete('cascade');

            $table->integer('genre_id')->unsigned()->index();
            $table->foreign('genre_id')->references('id')->on('genres')->onDelete('cascade');

            $table->timestamps();
        });
    
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('genre_series', function (Blueprint $table) {
            //
        });
    }
}

```

and this my models

**Series Model**

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Series extends Model
{
    public function genre(){
    return $this->belongsToMany(Genre::class);
}
}
```

**Genre Model**

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Genre extends Model
{
    
}

```

**Comment by marktopper** [comment]
@Al-Kaiser, sorry for the delay.
The relationship JSON code you have:
```
{
	"relationship": {
		"key": "id",
		"label": "name"
	}
}
```
What BREAD table and column is that for?
Can you share the screenshot of the related BREAD page?

**Comment by Al-Kaiser** [comment]
![bread](https://cloud.githubusercontent.com/assets/20999400/24586529/41ffb46c-17ac-11e7-8ad7-45ff852c6df6.png)

@marktopper

**Comment by ghost** [comment]
Same problem. Just to add:
if table (in this case 'series') is empty - it does work.

**Comment by mitchtechs** [comment]
Hi All, loving this admin framework! has anything been done with this issue as yet? or is there a workaround as i've just experienced the same issue in the latest version of Voyager?

Cheers
Mitch

**Comment by marktopper** [comment]
For the people having this issue, please provide your BREAD settings for the relation that fails along with a screenshot of the database along with the relationship database as well.
This will help us solve the issue.

**Comment by johnmain** [comment]
I am also having the error described on Browse.  If I am on the Add/Edit page there is no issue.

`class ForumCategoryRole extends Model
{
    public function forumCategoryId()
    {
        return $this->hasMany(ForumCategory::class,'id');
    }
   public function roleId()
    {
        return $this->hasMany(Role::class,'id');
    }
    
}
`
![image](https://user-images.githubusercontent.com/2589334/29681435-a591130a-88d5-11e7-8708-e0be52a4230b.png)

![image](https://user-images.githubusercontent.com/2589334/29681560-0e16b2ae-88d6-11e7-95ef-46690aad98b7.png)

**Comment by marktopper** [comment]
What exact error do you get @johnmain?

**Comment by johnmain** [comment]
Undefined index: name
If I take out Browse on role_id then I get 
Undefined index: title
which is the relationship on forum_category_id

**Comment by marktopper** [comment]
I might need to remake this, in order to have more helpful exceptions.
Can you tell me the columns you have for the tables for the Role and ForumCategory models.

**Comment by johnmain** [comment]
I am only trying to use bread on a Pivot table as I have another issue using a Multiselect relationship detailed here https://github.com/the-control-group/voyager/issues/1597#issuecomment-324534792

**Comment by johnmain** [comment]
relevant columns are
roles (built in table from voyager)
id, name
forum_category
id,title
forum_category_role Pivot table 
id,forum_category_id, role_id

**Comment by johnmain** [comment]
Another question I have not related to this issue:

Can you in a Drop down that is populated by a relationship inject a null option? 
EG I have a column where a 0 is valid value.  but I also want to pull a list of ids from another table selectable in a select drop down.  If I add a options:{"0","None"}, to the relationship:
```
options:{"0","None"}, 
"relationship": {
        "key": "id",
        "label": "title"
    }
```
  I get an error. 

Undefined property: stdClass::$Community

**Comment by fletch3555** [comment]
My recommendation would be to fix the multiselect issue and use it that way.

**Comment by johnmain** [comment]
@fletch3555 Yes I would love that.  I have spent hours trying different relationship details, changing the model code.  Even trying to find out how the Options list is being generated.
It is so close to working but just can't seem to get the option values populated with the Role.IDs

**Comment by lancepioch** [comment]
Labels: in progress, bug, help wanted

**Comment by handiwijoyo** [comment]
Voyager `1.0` using new relationship feature.
