### ISSUE TITLE
Dangers Bug ! : super user can add new user with administrator role ! 

### ISSUE THREAD

**Issue by Al-Kaiser** [thedevdojo/voyager#1017]
hello i found something weird 

when i login with user **only have user permissons** (superuser) he can create new user with **full admin panel access** !

**and yes he can edit his account to give him self administrator role or delete any user !** 

how i can close this shit? it's to dangers !

**Comment by turtuga** [comment]
You have this suggestion https://github.com/the-control-group/voyager/pull/911 but you have implement yourself..

**Comment by abdgad** [comment]
`users` is just a BREAD type, so if you give someone access to `users`, he'll be able to do anything on them.
This issue is under discussion. What you can do now is to give `users` permissions only to Administrators.
