### ISSUE TITLE
Error in Saving a Nullable Column...

### ISSUE THREAD

**Issue by g0ld3lux** [thedevdojo/voyager#102]
I try to use the Chatter Package... Works fine...
But is there A Way You Can Specify a Null on the Field...
Coz if its empty it throw this error
```
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'parent_id' at row 1 (SQL: update `chatter_categories` set `parent_id` = , `updated_at` = 2016-11-06 05:03:47 where `id` = 7)
```
Do we Even Have Validation When we Submit Data?

**Comment by handiwijoyo** [comment]
@g0ld3lux you can edit your table using admin > database > edit and change the 'Allow Null' column.

For validation I already create PR #111

**Comment by marktopper** [comment]
Fixed in the latest version.

**Comment by g0ld3lux** [comment]
Nice ill test it asap

**Comment by marktopper** [comment]
👍 Please keep me noticed.
