### ISSUE TITLE
Updated bread permissions in 2 blade templates

### ISSUE THREAD

**Issue by jcanchor** [thedevdojo/voyager#1020]
- Laravel Version: 5.4.16
- Voyager Version: 0.11.7
- PHP Version: 7.0.13
- Database Driver & Version: MySQL 5.7.16

### Description: 

I ran tests after installing BREAD system for the various roles I created across existing admin tables in Voyager. I found that having permission for Browse and Read only still allowed Add and Edit buttons to appear, and in View record instances, there was no button to return to the list.

I copied two templates and put them in my `resources/views/vendor/voyager` folder. These have been working for me, and avoid showing buttons that produce errors for the user on permission check.

### bread/read.blade.php

File: "resources\views\vendor\voyager\bread\read.blade.php"

Here is revised `<h1>` tag in `@section('page_header')` with permission check and return to list button.

        <i class="{{ $dataType->icon }}"></i> Viewing {{ ucfirst($dataType->display_name_singular) }} &nbsp;
        @if (Voyager::can('edit_'.$dataType->name))
            <a href="{{ route('voyager.'.$dataType->slug.'.edit', $dataTypeContent->getKey()) }}" class="btn btn-info">
                <span class="glyphicon glyphicon-pencil"></span>&nbsp;
                Edit
            </a>
        @endif
        <a href="{{ route('voyager.'.$dataType->slug.'.index') }}" class="btn btn-warning">
            <span class="glyphicon glyphicon-list"></span>&nbsp;
            Return to List
        </a>        

### posts/browse.blade.php

File: "resources\views\vendor\voyager\posts\browse.blade.php"

Here is revised `<h1>` tag in `@section('page_header')` with permission check

        <i class="voyager-news"></i> {{ $dataType->display_name_plural }}
        @if (Voyager::can('add_'.$dataType->name))
            <a href="{{ route('voyager.'.$dataType->slug.'.create') }}" class="btn btn-success">
                <i class="voyager-plus"></i> Add New
            </a>
        @endif

Here are the revised show, edit and delete buttons near bottom of dataTable with permission check.

        <td class="no-sort no-click">
            @if (Voyager::can('delete_'.$dataType->name))
                <div class="btn-sm btn-danger pull-right delete" data-id="{{ $data->id }}">
                    <i class="voyager-trash"></i> Delete
                </div>
            @endif
            @if (Voyager::can('edit_'.$dataType->name))
                <a href="{{ route('voyager.'.$dataType->slug.'.edit', $data->id) }}" class="btn-sm btn-primary pull-right edit">
                    <i class="voyager-edit"></i> Edit
                </a>
            @endif
            @if (Voyager::can('read_'.$dataType->name))
                <a href="{{ route('voyager.'.$dataType->slug.'.show', $data->id) }}" class="btn-sm btn-warning pull-right">
                    <i class="voyager-eye"></i> View
                </a>
            @endif
        </td>

Hey Mark, I looked at the permission checks in the `users/browse.blade.php` to get the proper format.

If these updates can be added to an upcoming build, may help other developers and provide for a better user experience. 

This is a very flexible tool for the Laravel community and I appreciate all your work on this. This is a small way I can contribute to improving it.

Thanks!!

**Comment by fletch3555** [comment]
@JCanchor, you're welcome to create the pull request yourself so you can get credit for the changes.

If you're not able/willing/etc to do so, please say so and we'll take care of it for you.

**Comment by jcanchor** [comment]
Hi Eric,
    
    I downloaded the current repository and created the branch, then
    went to push the changes on the branch and received permission
    denied:
    ---
    G:\wamp\www\code\voyager-repo>git checkout -b
    issue-1020-permission-in-blade
    Switched to a new branch 'issue-1020-permission-in-blade'
    
    G:\wamp\www\code\voyager-repo>git push origin
    issue-1020-permission-in-blade
    Username for 'https://github.com': JCanchor
    Password for 'https://JCanchor@github.com':
    remote: Permission to the-control-group/voyager.git denied to
    JCanchor.
    fatal: unable to access
    'https://github.com/the-control-group/voyager.git/': The requested
    URL returned error: 403
    ---
    
    I was following instructions in this tutorial:
    https://yangsu.github.io/pull-request-tutorial/
    
    Can you tell me what I am missing? 
    
    I have not made a contribution on github before. Only worked with
    git on my own site at bitbucket.
    
    Thanks,

**Comment by fletch3555** [comment]
We have permissions to this repository locked down to collaborators only, which is why you can't push your branch.  Github uses a Fork and Pull Request model, meaning you essentially copy the repo under your own account (where you have full permissions), make your changes, then submit a pull request back to the original repo (this one) for us to review.  You can find lots of documentation around it online.  Just include "github" in your searches instead of just "git".  This is a good starting point: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by jcanchor** [comment]
Hey Eric,

Thanks for the link to the post on submitting pull requests. It was very complete and thorough. I just completed a pull request #1027  and will see how it goes!

Thanks again!

**Comment by fletch3555** [comment]
Looks like @marktopper beat me to the Pull Request.  It's merged in now.  Thanks!
