### ISSUE TITLE
Admin panel login clashing with  and landing page login

### ISSUE THREAD

**Issue by GNSubrahmanyam** [thedevdojo/voyager#103]
Hi,
We can login in both ways. This error should be rectified. 

1. Using [http://localhost:8000/admin](http://localhost:8000/admin).
![image](https://cloud.githubusercontent.com/assets/18217008/20036168/258a8dc4-a426-11e6-84a1-b33aa7238bac.png)
  Dashboard
![image](https://cloud.githubusercontent.com/assets/18217008/20036183/acaf98d0-a426-11e6-8e62-22bd02389ee1.png)
panel

2. Using [http://localhost:8000](http://localhost:8000).
![image](https://cloud.githubusercontent.com/assets/18217008/20036175/580cee4a-a426-11e6-9c0a-0a325a098bf3.png)

![image](https://cloud.githubusercontent.com/assets/18217008/20036180/7d1c098c-a426-11e6-9f73-f32392389883.png)

![image](https://cloud.githubusercontent.com/assets/18217008/20036181/83190632-a426-11e6-94b7-558b86363236.png)

Any one please test this on your machine. 
Thanks

**Comment by handiwijoyo** [comment]
Yes, i'm aware of this, since that is laravel default auth pages. You can
remove it if you want.

**Comment by handiwijoyo** [comment]
I think this is intended behavior, since most we need to separate website
visitor login with admin login.

**Comment by GNSubrahmanyam** [comment]
@handiwijoyo Have you tested this on your machine.

**Comment by GNSubrahmanyam** [comment]
@handiwijoyo  I don't want to remove default auth pages. I just want to make another dashboard for my user/clients & admin panel is only for me. In other words I want to prevent admin dashboard accessing by others.

**Comment by handiwijoyo** [comment]
Yes, it's already protected, only user with admin role can access voyager
admin page

**Comment by GNSubrahmanyam** [comment]
@handiwijoyo  Yes, you are right by default it is protected. Only a user who has admin rights only can access admin panel now it's working. Just now I have created 3 Users. 2 of them are normal users & 1 of them is admin. 

One Feature Request: Change User role from dashboard. So that admin can easily change any one's role. For this feature I will make separate post. 

Thank You.
