### ISSUE TITLE
Creating new records with non-nullable timestamps via BREAD.

### ISSUE THREAD

**Issue by sdegoeij** [thedevdojo/voyager#1031]
- Laravel Version: 5.4.16
- Voyager Version: 0.11.8
- PHP Version: 7.1.2
- Database Driver & Version: postgresql 9.5.2

### Description:
There seems to be an issue when creating BREAD records containing timestamps.
I have a Round model, containing 2 non-nullable timestamp columns, called _start_date_ and _end_date_.

![screen shot 2017-03-29 at 11 47 52](https://cloud.githubusercontent.com/assets/32384/24448816/90f73d68-1475-11e7-82d8-dc2dc47a646a.png)

BREAD for this model is set up as follows:
![screen shot 2017-03-29 at 11 45 39](https://cloud.githubusercontent.com/assets/32384/24448700/494461a8-1475-11e7-8cad-12616c2ed5db.png)

Updating an existing record using the javascript datepickers to edit the timestamps works fine, it's when creating a new record, I get an exception:

![screen shot 2017-03-29 at 11 48 36](https://cloud.githubusercontent.com/assets/32384/24448853/ac2e4f54-1475-11e7-907e-fc798214e7df.png)

Looking at *TCG\Voyager\Http\Controllers\Controller*, in function _getContentBasedOnType_, line 279, there is a check on `$request->isMethod('PUT')`. 

Since this is a create, the request method is a POST, meaning the $content will be NULL. If I change the line to

`if ($request->isMethod('PUT') || $request->isMethod('POST'))`

creating new records works fine.

What's the intended behavior here? Why is the check on PUT methods in this function? I can't find anything in the documentation about this.

**Comment by abdgad** [comment]
I am not sure what the intent was for checking the request method. I think that check should be removed completely.
ping @marktopper

**Comment by fletch3555** [comment]
I haven't seen any further issues on this, so I'm assuming it's been resolved.  Closing for now.  We can reopen this later if it's still an issue

**Comment by u01jmg3** [comment]
- I am running into this issue using `timestamp()` - create results in `null`, update works as expected.
- As per @sdegoeij's suggestion, the code change `if ($request->isMethod('PUT') || $request->isMethod('POST'))` fixes the issue
