### ISSUE TITLE
Change timestamp

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#1035]
- Laravel Version: 5.4
- Voyager Version: New
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
Where i may change timestamp ?

**Comment by fletch3555** [comment]
Please provide more details on your question/issue for us to be able to help

**Comment by Rishats** [comment]
I try to change auto time in column created_at and updated_at

**Comment by abdgad** [comment]
Still don't understand your question. If you mean `auto increment`, then you can't set that on timestamps. If you mean setting `CURRENT_TIMESTAMP`, that is currently not supported.
