### ISSUE TITLE
How can I show thumbnails of multiple images field on browse template?

### ISSUE THREAD

**Issue by xotik** [thedevdojo/voyager#1036]
- Laravel Version: Latest
- Voyager Version: Latest
- PHP Version:
- Database Driver & Version:

### Description:
When you're editing a form that has the multiple images field, all images appear as thumbnails, but when browsing I get the value stored in the database, eg: 

`["tarefas\/March2017\/NMjnsAHjJ2EFnnwZ8WGx.png","tarefas\/March2017\/ax4bwZkf5j3VBjRnx1RD.png","tarefas\/March2017\/y4bVJ9jYbNXFeN0XrGoB.png"]`

I've edited the browse.blade.php file and added:

`@elseif($row->type == 'multiple_images')`

Which I´m guessing it was missing, and it works just fine. My struggle is how do I iterate over the images to create `<img>` tags?
I´ve tried `explode(',', $data->{$row->field})` to get an array from that string, but it gives me the error:

`htmlspecialchars() expects parameter 1 to be string, array given.`

Any ideas?
Thanks in advance!

**Comment by sarath-c-sandwich** [comment]
Because Voyager store multiple images as array of string, use 
```
$image_collection = json_decode($object->images);
```
it will return in array

**Comment by xotik** [comment]
@uchsarath You're correct, it works!

If anyone's interested, here's what I ended up adding to browse.blade.php:

`@elseif($row->type == 'multiple_images' && $data->{$row->field})`
`      @foreach(json_decode($data->{$row->field}) as $item)`
`                <a href="{{ url('storage/' . $item) }}" target="_blank" title="See image"><img src="{{ url('storage/' . $item) }}" style="max-width: 50px;max-height:50px;border:1px solid #d2d2d2;margin-bottom: 1px;"/></a>`
`       @endforeach`

Thank you very much!

**Comment by jamsewalliam09** [comment]
You can add thumbnail navigation to create the landing of the page with images which links to others pages. This facilitates visitors a visual image to search content on your site from one place.
Some templates support raster index pages, which automatically create a navigation based on the page thumbnails. In each template, you can create a similar effect by using a regular page and a Grid Gallery block with click-through URLs.
