### ISSUE TITLE
Cant create new bread

### ISSUE THREAD

**Issue by lefajardo2** [thedevdojo/voyager#1037]
- Laravel Version: 5.4.16
- Voyager Version: 0.11.8
- PHP Version: 7.0.16

### Description:
After clicking the "Add bread to this table" the bread form show the input type dropdown with checkbox value for all the fields including the primary key, and the controllername box is empty, and the optional details field looks weird.  After selecting "text" for all input types, and click the submit button, i see a red popup with the message "Saving field exeption: undefined index: field_require_name" and nothing is saved.

### Steps To Reproduce:
Create the Locations table as specified in the table.png, then click the "add new bread" button
![bottompart](https://cloud.githubusercontent.com/assets/20405094/24533074/7aa87d66-1582-11e7-9e94-9b7338b90c63.PNG)
![createbread](https://cloud.githubusercontent.com/assets/20405094/24533073/7aa513ce-1582-11e7-8aa4-a9883b2028a7.PNG)
![err](https://cloud.githubusercontent.com/assets/20405094/24533072/7aa4e070-1582-11e7-9f22-13f7455541ea.PNG)
![table](https://cloud.githubusercontent.com/assets/20405094/24533071/7aa481d4-1582-11e7-90c1-4794535616d0.PNG)

**Comment by abdgad** [comment]
Thanks for reporting the bug.

**Comment by lefajardo2** [comment]
Hey abgad, can you clarify what you mean ?

**Comment by abdgad** [comment]
This issue has been fixed in #1041. It will be available in the next update.
A quick fix for you now is to use lower case field names.
