### ISSUE TITLE
[Feature Request] Setting groups

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#104]
Would it be possible to have group settings instead of having all settings showing on the `Settings` page.

Then `Settings` could be a dropdown with setting categories?

I am more than willing to pull this out in a pull request.

**Comment by fletch3555** [comment]
I think it would be better to just paginate them and add a search box to the page.  Grouping them doesn't really seem like it adds much functionality outside of Voyager, which is the purpose of Settings

**Comment by marktopper** [comment]
@fletch3555: What if it came with an option, to categorize it or not.

**Comment by marktopper** [comment]
@fletch3555: Also search option could be done.

**Comment by fletch3555** [comment]
This has been implemented for 1.0 in #1544
