### ISSUE TITLE
Use voyager Laravel DB :: connect to fail

### ISSUE THREAD

**Issue by feikai2012** [thedevdojo/voyager#1046]
- Laravel Version: 5.3.0
- Voyager Version: 0.10.10
- PHP Version:7
- Database Driver & Version:mysql 5.7

### Description:

Can only connect to the use of the default database, can not use the laravel comes with db :: connection, the error can not find the specified table

### Steps To Reproduce:
Locating the problem location here
        try {
            foreach (\TCG\Voyager\Models\DataType::all() as $dataTypes) {
                Route::resource($dataTypes->slug, $namespacePrefix.'VoyagerBreadController');
            }
        } catch (\InvalidArgumentException $e) {
            throw new \InvalidArgumentException("Custom routes hasn't been configured because: ".$e->getMessage(), 1);
        } catch (\Exception $e) {
            // do nothing, might just be because table not yet migrated.
        }

**Comment by abdgad** [comment]
We dropped support for `v0.10`. We highly encourage you to upgrade to `v0.11`. You can follow [this guide](https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading) to perform the upgrade.

**Comment by feikai2012** [comment]
@abdgad Thank you.I still have problems after I try

**Comment by abdgad** [comment]
Please create a new issue describing the problem in `v0.11`. Include as many details as possible.
