### ISSUE TITLE
HasMany relationships

### ISSUE THREAD

**Issue by dotWaldemar** [thedevdojo/voyager#1048]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.1

Hello!
How i Can create images for products hasMany relationships?

First table `products` second table `images`

`products`
id
title
preview
body
price

`images`
id
path
product_id

How i can use in one page? add product and images in one page

**Comment by fletch3555** [comment]
You can override the views.  Currently we have no documentation around this process, so we can't provide step-by-step instructions.  If you have specific questions, you're welcome to join our slack group and ask there.
