### ISSUE TITLE
Multiple select saves non-numerical ID incorrectly in join table

### ISSUE THREAD

**Issue by harpster604** [thedevdojo/voyager#1049]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.7
- PHP Version: 7.1

Multiple select doesn't work as intended for join table that has a non-numeric ID for one of the columns.

I have two tables. One is a list of items (id, name, ...) and another is a list of zones (id, name). The zone IDs are non-numerical. They are 1a, 1b, 2a, 2b, etc.

The join table items_zones is a standard Laravel join table with both IDs and timestamps.

I have added a multiselect to the BREAD for "Items" with the relationship to the zones. When I edit an item, it displays the zones properly and I can add new ones into the multiselect but when the data is saved to the join table, it is saved incorrectly. The zone ID is saved as an integer, and the proceeding letter is stripped off. For example adding zone ID '10a' saves '10' to the join table, adding '12b' saves '12', etc.

item_id | zone_id
------------ | -------------
1 | 10a // how it should be
1 | 10 // how it is being saved

I tried looking at the form data that is being posted and it seems like it might be a front end issue with the actual multiselect. It seems to only pass the number 10 when posting.

`
Content-Disposition: form-data; name="zones[]"
10
`

**Comment by md3e** [comment]
still waiting advanced tuts for #616

**Comment by harpster604** [comment]
@ferrywae I looked at the advanced features but I'm not sure if that helps my case. I am not trying to update additional pivot table fields.

items table

id | name
------------ | -------------
1 | Computer
2 | Television

zones table

id | name
------------ | -------------
1a | Danger Zone
1b | Fun Zone
2a | Hot Zone

items_zones table

item_id | zone_id
------------ | -------------
1 | 1 //should be 1b
1 | 2 //should be 2a

The actual pivot IDs are being saved incorrectly by the multiple select input when a non-integer ID is used as one of the pivots.

**Comment by harpster604** [comment]
Found the issue!

Fixed it by adding the following to my Zone model:
`
public $incrementing = false;
`
