### ISSUE TITLE
Bread is not exist in the admin panel !

### ISSUE THREAD

**Issue by MaisaZaro** [thedevdojo/voyager#1053]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version:7.1.1
- Database Driver & Version:MySQL

### Description:
when I added a bread to a database table  I can reach it from link correctly but it didn't appear in the admin menu and the dash-bored ! 

![bread](https://cloud.githubusercontent.com/assets/26180592/24607455/8b11bb5e-187a-11e7-8d22-92368c41af89.JPG)

**Comment by wuelcas** [comment]
You have to manually add the link in the Menu Builder if you want to see it in the dashboard menu

**Comment by MaisaZaro** [comment]
Thank You !
