### ISSUE TITLE
using the same table but with global scope

### ISSUE THREAD

**Issue by Mohmdthabet** [thedevdojo/voyager#1054]
- Laravel Version: 5.3.31
- Voyager Version: 0.10.16
- PHP Version: 5.6
- Database Driver & Version:

### Steps To Reproduce:  

```
class Events extends Model {
	protected $table = 'posts';
	protected $guarded = [];
	protected static function boot() {
		parent::boot();
		static::addGlobalScope(new EventScope);
	}
}
```

```
class Post extends Model {
	protected static function boot() {
        	parent::boot();
        	static::addGlobalScope(new PostScope);
	}
}
```
```

namespace App\GlobalScopes;

	use Illuminate\Database\Eloquent\Scope;
	use Illuminate\Database\Eloquent\Model;
	use Illuminate\Database\Eloquent\Builder;

	class EventScope implements Scope
	{
		/**
		 * Apply the scope to a given Eloquent query builder.
		 *
		 * @param  \Illuminate\Database\Eloquent\Builder  $builder
		 * @param  \Illuminate\Database\Eloquent\Model  $model
		 * @return void
		 */
		public function apply(Builder $builder, Model $model)
		{
			$builder->where('type', '=', 'event');
		}
	}
```

is it possible to use the datatype table or the model to add bread?

**Comment by fletch3555** [comment]
Please explain your reasoning for doing it this way.  I see no benefits to the way your models are set up

**Comment by Mohmdthabet** [comment]
I use global scopes to query the same table for different posts based on their type because the table structure will be the same for about ten post types. so instead of creating more tables in order to add bread, i want to use the base table and add bread based on models or datatype table.

If you thing there is a better way to do it, I am open to any suggestions.

**Comment by fletch3555** [comment]
Apologies for the delay in response.  I was saying that I don't understand why "Posts" and "Events" should live in the same table.  It seems like an odd way to do it

**Comment by lancepioch** [comment]
Labels: open for suggestions, enhancement

**Comment by handiwijoyo** [comment]
I don't recommend to do this. You can filter event type by using something like category. Close this due inactivity.
