### ISSUE TITLE
How do add upload field for audio files?

### ISSUE THREAD

**Issue by jasminetracey** [thedevdojo/voyager#1057]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:
How do add upload field for audio files?
for example mp3

**Comment by davodavodavo3** [comment]
You need to update html structure  in vendor\tcg\voyager\resources\views\formfields\file.blade.php"

Example if isset option accpet{from json} 

Json:
{
    "accept": ".mp3,audio/*"
}

<input type="file" name="{{ $row->field }}" accept="{{ ($options->accept)? $options->accept:''}}" >

**Comment by davodavodavo3** [comment]
This is not a perfect solution.

**Comment by jasminetracey** [comment]
i don't understand what you mean. where does that json go?

**Comment by ghost** [comment]
Your html code: 

<form action="{{ route('savesong') }}" method="GET">
<input type="file" name="song">
</form

your web.php code:

<?php

Route::get('/save', 'SaveSongController@savesong')->name('savesong');

your controller code:

//create a controller
public function savesong(Request $request)
{
$validator = Validator::make($request->all(), [
     'song' => 'required|mime:mp3'
]);
}

**Comment by lancepioch** [comment]
Labels: invalid, question

Close (answer provided)
