### ISSUE TITLE
i have issue in adding laravel bread

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1058]
[-]([url](`url`)) Laravel Version: 5.4
- Voyager Version: latest
- PHP Version:
- Database Driver & Version:

### Description:
when i want to add bread it give me error 
# 
**Saving Failed Exception: Undefined index: field_required_name**
kindly help me

**Comment by abdgad** [comment]
This is a bug, which will be fixed in the next update.
A quick fix for now is to rename the columns in your table in lowercase. So instead of `Name`, call it `name`.

**Comment by aamirkhan37557** [comment]
thanks issue is solved
