### ISSUE TITLE
how to display storage content in laravel 5.3 from storage folder

### ISSUE THREAD

**Issue by JDamour** [thedevdojo/voyager#1059]
- Laravel Version: 5.3.30
- Voyager Version: #.#.#
- PHP Version:5.6
- Database Driver & Version:MySQL 5.6

### Description:
i can't display image or playing mp3 file ,i have been struggling for this issue for hours on my localhost all files images,mp3 works fine in symbolic link at public/storage when i moved to the share hosting can't work this is sample code for image tag

 tag img  src="{{asset($track->image)}}"  alt="{{$track->Name}}" data-toggle="tooltip" data-placement="bottom" title="{{$track->Name}}"

the value of $track->image
is a path :storage/images/avatars/artists/f9dc92344b57ec6b0bcb3ce601f9d‌​134.jpeg 
### Steps To Reproduce:
NotReadableException in AbstractDecoder.php line 335:
Image source not readable

**Comment by jasminetracey** [comment]
how did you get it to upload mp3?

**Comment by fletch3555** [comment]
@JDamour, I'm sure you've moved on from this at some point in the last 3 months, but the issue is likely because you pushed the storage symlink (`/public/storage`) to the server.  Symlinks are specific to the file system they were created in, so you would need to delete it and recreate it on the remote server.

**Comment by navalevivek** [comment]
@fletch3555 

Hi,

Can you please elaborate more on this, how to re-create  it on remote server, you mean deleting the storage folder and create new one or what?

**Comment by fletch3555** [comment]
This issue has been closed for 10 months and was for a much older version. If you need assistance beyond what is already mentioned here, please open your own issue or ask in our slack group.
