### ISSUE TITLE
Decimal type of column in database builder with fixed point?

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1061]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version: 7.0
- Database Driver & Version: MySQL-5.7-x64

### Qestion::
How to set decimal type of column in database builder with fixed point?

**Comment by abdgad** [comment]
This is currently not supported. It will be added in a future update.
If you really need to set that, then I suggest you create a migration for it.

**Comment by fletch3555** [comment]
A recent pull request added the ability to submit floating point numbers in the bread using the "number" type.  If you have composer pointing to "dev-master" as the version, then just run a composer update.  If not, you can either wait for the next release, or change it to dev-master

**Comment by abdgad** [comment]
@fletch3555 this issue is related the database column type not to the input type.

**Comment by fletch3555** [comment]
No, that's not how I read it.  He's asking about the database builder, which is within voyager, not within the database itself.  The "number" type within voyager can be stored in many different field types within mysql (and other DBMS), including `INT` and `DECIMAL`

**Comment by abdgad** [comment]
@fletch3555 I believe [this is](https://dev.mysql.com/doc/refman/5.7/en/fixed-point-types.html) what he means. Currently it can't be set within the database builder.

**Comment by fletch3555** [comment]
I think I see what the misunderstanding is. I'm thinking of the Bread editor fields, where you're thinking the table editor fields.

I don't think we can support anything that's specific to any one DBMS (like MySQLs JSON type).  How do you do the DECIMAL type with eloquent?

**Comment by abdgad** [comment]
We use `Doctrine DBAL`, and it supports `scale` and `precision` options for Decimal columns. No need to worry about Eloquent.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please create a new issue
