### ISSUE TITLE
Use voyager Laravel DB :: connect to fail

### ISSUE THREAD

**Issue by feikai2012** [thedevdojo/voyager#1064]
- Laravel Version: 5.3.0
- Voyager Version: 0.11.*
- PHP Version:7
- Database Driver & Version:mysql 5.7

### Description:

Can only connect to the use of the default database, can not use the laravel comes with db :: connection, the error can not find the specified table

### Steps To Reproduce:
Locating the problem location here
          try {
            foreach (DataType::all() as $dataType) {
                $breadController = $dataType->controller
                                 ? $dataType->controller
                                 : $namespacePrefix.'VoyagerBreadController';
                Route::resource($dataType->slug, $breadController);
            }
        } catch (\InvalidArgumentException $e) {
            throw new \InvalidArgumentException("Custom routes hasn't been configured because: ".$e->getMessage(), 1);
        } catch (\Exception $e) {
            // do nothing, might just be because table not yet migrated.
        }

**Comment by abdgad** [comment]
Can you please explain in more details. What exactly do you mean by:

> can not use the laravel comes with db :: connection

?
Also, please include a screenshot of the error.

**Comment by feikai2012** [comment]
@abdgad 
According to your upgrade process is not open, I use the latest version of the problem solved！thank you
