### ISSUE TITLE
Unable to install for Laravel 5.3

### ISSUE THREAD

**Issue by petersowah** [thedevdojo/voyager#1065]
- Laravel Version: 5.3
- Voyager Version: 0.11.8
- PHP Version: 7.0.8
- Database Driver & Version:
mysql
### Description:
When I run `php artisan voyager:install` I get this exception thrown `[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'App\User' not found`

**Comment by harpster604** [comment]
I had this issue as well when installing. It tries to look for App/User (default Laravel user model) when installing, but I had a different User model in a different namespace. You can temporarily put the Laravel User model back into it's original spot and install Voyager, then remove it and set up your proper User model in the Voyager config file.

**Comment by fletch3555** [comment]
As a workaround, you can either do what @harpster604 suggested, or do the following:

1. run `php artisan vendor:publish` to create `config/voyager.php`
2. edit `config/voyager.php` and set the user model configuration to the correct namespace
3. run `php artisan voyager:install` and continue following the Voyager install directions in the documentation.

**Comment by fletch3555** [comment]
Closing as suggestions have been provided
