### ISSUE TITLE
Issue with laravel 5.4

### ISSUE THREAD

**Issue by lednhatkhanh** [thedevdojo/voyager#1070]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version: 7.1.1
- Database Driver & Version: Don't know

### Description:

Hello, I noticed a few errors when using with laravel 5.4:

- [ ] I can't change the icons of what is displayed on the dashboard, it always show the `voyager-group` icon:

![image](https://cloud.githubusercontent.com/assets/9303093/24732583/f44cc992-1a9b-11e7-825f-23ac2cfaa83e.png) 

- [X] There is are no view published in the `resources/views folder` ()

- [x] The is no validation error message when I try to create a new post with the empty title, while I already set the rules like this: (There is already a PR here #1071 )

![image](https://cloud.githubusercontent.com/assets/9303093/24732628/4da3aa56-1a9c-11e7-93c7-afa21f33841b.png)

### Steps To Reproduce:

- Create a new laravel 5.4 project by running this: `laravel new sample`
- Install voyager `composer require tcg/voyager` and install with dummy data

**Comment by davodavodavo3** [comment]
@lednhatkhanh yes there is a error with validation on posts

**Comment by davodavodavo3** [comment]
For validation on page of posts paste this in 
\vendor\tcg\voyager\resources\views\posts\edit-add.blade.php
```
@if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
```

Maybe programmers forget?)))))

**Comment by lednhatkhanh** [comment]
I think there should be a PR for this :)

**Comment by davodavodavo3** [comment]
Yes you are right friend. I open PR

**Comment by davodavodavo3** [comment]
for widgets there will be (must be) other structure.Now the icons and other options are hard coded in 
\vendor\tcg\voyager\src\Widgets files.Config for them doesn't work((((

**Comment by lednhatkhanh** [comment]
Yeah, I saw that too, they must be forgot to load the config file...

**Comment by AdrianKuriata** [comment]
Hi, do someone problem like that?

[http://i.imgur.com/satMZTv.png](http://i.imgur.com/satMZTv.png)

When i try add validation for the field i getting error with undefined index, check pic.

**Comment by davodavodavo3** [comment]
@AdrianKuriata can you paste validation json?

**Comment by AdrianKuriata** [comment]
@davodavodavo3 I just copied for test validation JSON from docs

```
{
    "validation": {
        "rule": "required|max:12"
    }
}
```

**Comment by davodavodavo3** [comment]
maybe there is a solution for you
https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=undefined%20index

**Comment by davodavodavo3** [comment]
name of you table order is in lowercase(order) or uppercase(Order)?

**Comment by AdrianKuriata** [comment]
@davodavodavo3 I tryied do validation for Categories from the Voyager categories table and i got this issue, probably this is bug and will be fix in the next soon update. 

Default tables do not have a validations for this creations i hope Voyager will be hard developed because is awesome.

**Comment by davodavodavo3** [comment]
yes @AdrianKuriata you are right.
I found the PR https://github.com/the-control-group/voyager/pull/1041 where problem is resolved

**Comment by AdrianKuriata** [comment]
@davodavodavo3 Thanks for your help, i will try it on the weekend, i have a question to you. I never helped with projects on github. When i will do something for change, improve with voyager and update code, is possible they update it for the master branch?

**Comment by davodavodavo3** [comment]
Yes you are creating a new PR for updates and the project manager(programmers or company) can approve it or decline.You can also fork the project and make changes for you

**Comment by lednhatkhanh** [comment]
Hello, I think the settings to publish the view resource is very important, it should be fixed/added soon!

**Comment by fletch3555** [comment]
We made a conscious choice to no longer publish the views, and that's not going to change (and therefore isn't a bug).  Published views are dangerous because they don't get updated if you update Voyager.  If you're forced to manually copy the view file to override it, then that's a conscious choice that you make as a developer, and therefore it's on you to make sure it's updated.

**Comment by williamn** [comment]
@fletch3555 I agree. Perhaps you should update the documentation [here](https://laravelvoyager.com/docs/0.11/#customization-overriding-views) as well as it is still states

> By default a couple posts views have been published to your resources/views/vendor/voyager folder. So those 2 view files will be located at resources/views/vendor/voyager/posts/browse.blade.php and resources/views/vendor/voyager/posts/edit-add.blade.php.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please open a new issue.

**Comment by farookhridoy** [comment]
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_voyeger.settings' doesn't exist (SQL: select * from `settings`) (View: C:\xampp\htdocs\5.5\vendor\tcg\voyager\resources\views\login.blade.php)

Please anyone hear?? to soloed my db problem??
please suggestion ,how do i do now??

**Comment by fletch3555** [comment]
@gmfaruk, please either open your own issue or post in our Slack group.  Commenting on closed issues should be avoided.
