### ISSUE TITLE
Post page langauge issue

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1072]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
On post page language switcher does not appear(browse and create or edit pages).
In my \Post\edit-add.blade.php or browse.blade.php the 
`@include('voyager::multilingual.language-selector')` is not there . Also i think that this script must be there to 

```
@if($isModelTranslatable)
     <script src="{{ voyager_asset('js/multilingual.js') }}"></script>
@endif
```
In other pages all work fine. I have two languages default is ru and suported are en & ru

How can the post languages work without
`@include('voyager::multilingual.input-hidden-bread-edit-add')`

**Comment by akazorg** [comment]
I just checked and you're right, that's missing.
I'll send a PR ASAP.

**Comment by akazorg** [comment]
Sending PR for this.

**Comment by fletch3555** [comment]
Closing issue as PR has been merged.
