### ISSUE TITLE
validation rules: error in docs

### ISSUE THREAD

**Issue by webber-ch** [thedevdojo/voyager#1078]
- Laravel Version: 5.4
- Voyager Version: 0.11.8

### Description:
As indicated in the voyager docs https://the-control-group.github.io/voyager/docs/0.11/#core-concepts-bread-validation under "Validation" rules can be declared like this:

`{
    "validation": {
        "rules": [
            "required",
            "max:12"
        ]
    }
}`

IMO it only works with the singular "rule" instead of "rules":

`{
    "validation": {
        "rule": [
            "required",
            "max:12"
        ]
    }
}`

This can be verified under Controller.php starting at line 45.

**Comment by fletch3555** [comment]
This has since been resolved.

**Comment by Kylegabriel** [comment]
how to validatate number
