### ISSUE TITLE
[Feature Request] Use views for menu builder

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#108]
Would it be possible in future to use views for the menu builder.

That makes it way more customizable.

__EDIT__: If approved, then I do not mind making it into a pull request.

**Comment by fletch3555** [comment]
What do you mean by "use views"?

**Comment by marktopper** [comment]
@fletch3555: https://laravel.com/docs/5.3/views

**Comment by tomicakorac** [comment]
@marktopper I think what @fletch3555 asked means what did you mean by "use views for the menu builder". How do you want to use views in the menu builder? Can you please explain your question to us?

**Comment by marktopper** [comment]
I will try to make a pull request this weekend to show what I mean.

It's like Laravel's Pagination template moved to using views.
[Read how it works now](https://laravel.com/docs/5.3/pagination#customizing-the-pagination-view).

**Comment by marktopper** [comment]
I also just noticed another small issue with the current way that the menus are builded.

There are no eager loading, so it could take a while to load for sites having many menus with many sub menus.

**Comment by marktopper** [comment]
First implement have been done at #154.
Currently only for the menu of `admin_menu`-type.
What do you think?
