### ISSUE TITLE
Image intervention in voyager

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1080]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
How can I apply image intervention and add water mark and resize the image in voyager
And my second question is to how I resize every individual image according to my desire size if I have three image column I'n same table or in one table

**Comment by fletch3555** [comment]
Please read the docs.  Go to the "Image" section under here: https://the-control-group.github.io/voyager/docs/0.11/#core-concepts-bread-additional-field-options
