### ISSUE TITLE
Issue with laravel voyager rich text editor

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1081]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I have selected rich text editor for my one of column in database and I have inserted the record successfully from rich text editor into database my issue is that when I display that column that it also display the paragraph tag <p><\p> as well as other tags can some body help me that how can I describe that data without any tag into my front end page of my website

**Comment by fletch3555** [comment]
Can you show us the contents of one of those values directly from the database? I'm guessing the RTE value is being html_encoded when storing, and you're not decoding it before displaying it.

**Comment by waiaitch** [comment]
Try to display your data through {!! !!} brackets.
Example:  `{!! $post->body !!}`

**Comment by abdgad** [comment]
You can try what @waiaitch said. More info [here](https://laravel.com/docs/5.4/blade#displaying-data).
