### ISSUE TITLE
Json options doesnt work in bread

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1086]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:
Json options doesnt work in bread?
Update from 0.11.8 to 0.11.9 with compose update , without vendors publish

### Steps To Reproduce:
Check it maybe i'am wrong.Or how to update from 0.11.8 to 0.11.9 without lost anithing?

**Comment by davodavodavo3** [comment]
Ha)))) I got it . Json otpion columns in bread  doesnt work if multilingual is true))))))

EVEN IF multilingual is OFF Json options does not update if set it to empty.

**Comment by akazorg** [comment]
Please, let's clear this out :)
BREAD JSON options only work on insert, with or without the multilingual enabled?
Do you think this is related to the multilingual?

**Comment by davodavodavo3** [comment]
1. BREAD JSON doesn't work when multilang is enabled.
 I think 'Yes' it's related to the multilang because if you disable it all works fine.

2. If in BREAD JSON we had inserted options before , we can't remove all of them(does not matter multilang ).

# Example for issue 2
We insert 
```
{
    "default": 1
} 
```
and save the BREAD(does not matter field type). Then open same BREAD and remove all from JSON column.You cant remove because there is condition
```
if (textarea.val()) {
                    _session.setValue(JSON.stringify(JSON.parse(textarea.val()), null, 4));
                } 
```
and on update he put old value ( "default": 1 ) from session

**Comment by davodavodavo3** [comment]
For multilang issue I added class "add-edit" to submit button and  change
`textarea.closest('form').on('submit', function (ev) {`
to
`$('.add-edit').on('click', function (ev) {`

Apparently there is antoher form maybe when multilang is enabled and on form submit jS functionality doesnt work. But with my way everything works fine))))

**Comment by AdrianKuriata** [comment]
Yea, i confirming this issue, if you add validation or something else, save it is ok. But if you want delete this validation, after save with empty field bread is not update.

**Comment by davodavodavo3** [comment]
You can update if set JSON to a empty object {} but it is not a solution.

**Comment by akazorg** [comment]
I'm not sure this is entirely related to the Multilingual, but I'll check that when I fix Posts.

If you're in a hurry, fell free to send a PR! (:

**Comment by davodavodavo3** [comment]
@akazorg i dont know is it from Multilingual, yes check it, maybe I'am wrong
I have create PR)))Merge if it's helpful.

**Comment by akazorg** [comment]
Is this fixed @davodavodavo3? Thanks

**Comment by davodavodavo3** [comment]
I dont know @akazorg , for now I dont use Voyager no more, i will close this issue

**Comment by fletch3555** [comment]
@davodavodavo3, why did you reopen this after 4 months..? Please open a new issue if it's still a problem.  Also, please try `dev-master` to confirm the issue hasn't already been fixed but not released.

**Comment by davodavodavo3** [comment]
ok
