### ISSUE TITLE
Left side menu issue.

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1090]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:
Newly created BREAD-s are displayed in the menu for users who do not have rights(permissions) to view them.

I write menu issue because they see the page in menu but they can't open it.

**Comment by davodavodavo3** [comment]
Oh no sorry!! Menu links must be with slash like this /admin/products
If you save without slash on start , then that menu link will be shown to user who do not have permissions.

And how to be with dropdown element that doesnt have an url like /admin/products ?
I tried with only /admin/ but it doesnt work normal, user see that.

**Comment by xotik** [comment]
Hi @davodavodavo3, I solved that issue with JS.

Add the following to app.js in public\vendor\tcg\voyager\assets\js\:

`$('.side-menu > nav > .navbar-nav li.dropdown').each(function () {`
`    if ($(this).children('.collapse').children('.panel-body').children('ul').children('li').length == 0) {`
`        $(this).remove();`
`    }`
`});`

What it does is, on page load, loop through all parents and if it finds any parent without children, removes it.
Hope it helps.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please create a new issue
