### ISSUE TITLE
Production state?

### ISSUE THREAD

**Issue by lednhatkhanh** [thedevdojo/voyager#1092]
Hello, I want to ask that is this package ready for production use? Thank you.

**Comment by AdrianKuriata** [comment]
In my opinion better way is wait for more updates, but if you good developer you can use it in production, but if you find some issues, you will need fix it.

**Comment by sarath-c-sandwich** [comment]
I use it in production; last couple months it was quite hard as we have to wait couple days for help, but version 0.11.9 is quite stable to use. http://camsolar-energy.com/

**Comment by abdgad** [comment]
Voyager is still in `alpha` stage. So we can't guarantee stability, and breaking changes may be introduced.

**Comment by fletch3555** [comment]
Answers have been provided. Closing
