### ISSUE TITLE
Can't update anything in bread

### ISSUE THREAD

**Issue by Xoshbin** [thedevdojo/voyager#1093]
- Laravel Version: 5.4
- Voyager Version: latest
- PHP Version:
- Database Driver & Version:

### Description:
After updating voyager to the latest version every field in bread is changed to checkbox and it affected my entire admin panel that I can't do anything. And when trying to change the fields and update the bread I have this error and I don't know what it is:

> Update Failed Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'controller' in 'field list' (SQL: update `data_types` set `description` = , `updated_at` = 2017-04-08 12:38:01, `controller` = where `id` = 1)

**Comment by abdgad** [comment]
If you upgraded from `v0.10`, you can follow [this guide](https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading).

Otherwise, execute these commands:
`php artisan vendor:publish`
`php artisan migrate`
