### ISSUE TITLE
Destroing whole framework after add parameters to menu item.

### ISSUE THREAD

**Issue by AdrianKuriata** [thedevdojo/voyager#1094]
- Laravel Version: 5.6
- Voyager Version:0.11.9
- PHP Version: 7.1
- Database Driver & Version: i dont remember

### Description:
Hi, i found i problem or i don't know how to use this. I mean when you want add new item or update item with Dynamic Route and you put some data like in placeholder to parameters you get error, this issue destroing whole page and must be delete item which you edited from database for start working page.

Here is message error, i check it in the database and sure, parameters is saved like a object, not a string or i bad inserting data : [Error](http://i.imgur.com/vmIWAlq.png)

```
{
"post" : 1
}
```
I did it like that or simillar.

**Comment by fletch3555** [comment]
I'm sorry, I don't understand the issue as written.  I'm going to close it since it's been so long.  If this is still an issue for you, let me know and we can reopen it.

**Comment by AdrianKuriata** [comment]
@fletch3555 so maybe turn on your voyager and try add menu item with parameter?
