### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 179:

### ISSUE THREAD

**Issue by roipatrick** [thedevdojo/voyager#1095]
I just know that I'm using laravel 5.4

Now in menu builder I create a group menu and done it successfully. After that, I reload the page and it shows in the menu but when I clicked it i encountered this error.

NotFoundHttpException in RouteCollection.php line 179:

Sorry, the page you are looking for could not be found.

I'm new to voyager.

Thanks for the help in advance....

**Comment by AdrianKuriata** [comment]
I don't understand, you created new menu and this is ok, but when you try get into builder for created menu you getting error?

**Comment by roipatrick** [comment]
No. I create a menu in the builder. Then the menu link in the side menu shows up. But when I try clicking it it redirects to an error

**Comment by davodavodavo3** [comment]
Set permissions for your user to to see that page
Or what URL you create for it?
Must be /admin/something

**Comment by roipatrick** [comment]
how

**Comment by roipatrick** [comment]
I create a database groups in the database creator of voyager then create a menu. The menu link shows up but when i click it errors are seen.

**Comment by AdrianKuriata** [comment]
Go to roles and set for Administrator permissions for your pages.

**Comment by endrureza** [comment]
@roipatrick what's the url of the menu you just add ? i'm afraid, he set wrong url, not using `/admin/menu-name`

**Comment by omaraligit** [comment]
i had the same problem
it's a rout not found error that cannot be displayed 
if you get this error just double check your routs and the link you use 
like if you have route::get('/admin','YourContoller@funct');
and you use this in a <a></a> make sure the link you use in the href is the same as the rout
and sorry for my bad english

**Comment by josefenado** [comment]
am having the same issue

**Comment by RyanAtregenio8** [comment]
I having same issue , when i add a new menu item in menu builder(admin) as title  Reservation and the url path /admin/reservation

when i click on side bar.

`
(1/1) NotFoundHttpException
--
in RouteCollection.php (line 179)
etc..
`

im new too in voyager and im trying to find out what is the problem , please help thank you

**Comment by RyanAtregenio8** [comment]
I having same issue , when i add a new menu item in menu builder(admin) as title  Reservation and the url path /admin/reservation

when i click on side bar.

`
(1/1) NotFoundHttpException
--
in RouteCollection.php (line 179)
etc..
`

im new too in voyager and im trying to find out what is the problem , please help thank you

**Comment by RyanAtregenio8** [comment]
Also i go too admin permission but no reservation here, what can i do? needed to add a database first to have a permissions?

**Comment by fletch3555** [comment]
@RyanAtregenio8, please read the Laravel and Voyager documentation if you're new.  Laracasts is also a good resource for learning.

As for your issue, is `reservation` a BREAD type? Meaning, if you go to Tools > Database (in the left menu), do you see a `reservations` table listed? If so, do you see a button in that row that says `Add BREAD` or one that says `Edit BREAD`?  If it says `Add BREAD`, then you need to do that, and it will create the model/permissions/etc for you depending on what options you choose.  Then your menu link will start to work.

**Comment by naseem1amjad** [comment]
A tip from me. Try to use 'slug' in url instead of table name. Like if your table name is "my_products" then use url/admin/my-product/

**Comment by lancepioch** [comment]
Labels: question

Close (solution provided)

**Comment by emptynick** [comment]
This can be closed
