### ISSUE TITLE
LaravelUser assumes App\User namespace

### ISSUE THREAD

**Issue by theshanergy** [thedevdojo/voyager#11]
Class 'App\User' is not found if the app User model has been moved (in my case to App\Models\User). There appears to be a namespace config already for the service provider, however App\User is hard coded in the User model as well as the index view. Is it possible to use the config in both of those files as well, or even just the Auth config?

**Comment by tnylea** [comment]
@theshanergy Thanks! Actually didn't even need to use the \App\User in the Voyager\User class so I removed that. All other references will refer to the Voyager User or they will refer to the user namespace in the config.

Thanks for pointing that out.
