### ISSUE TITLE
[Feature Request] Change user role using Admin Panel

### ISSUE THREAD

**Issue by GNSubrahmanyam** [thedevdojo/voyager#110]
Hi,

It is good if an admin can change other users role. That could be very using to change users role.

Thank you in advance.

**Comment by handiwijoyo** [comment]
Hi, i've created this feature on my own fork. You can find it here https://github.com/handiwijoyo/voyager/commit/2135d450fbc92a8ec374f949766ccedc1b7e5c9b 

You can use it if you want or wait for official release for this

**Comment by Frondor** [comment]
It would be really useful to create "sub-admins" with different roles and permissions, so they use only the parts of the admin panel they are allowed to.

**Comment by marktopper** [comment]
I think it would be best if the user was able to create roles with different permission themself within the Voyager panel.

**Comment by handiwijoyo** [comment]
@Frondor i've created this feature too. See it here https://github.com/handiwijoyo/voyager/commit/4e62651dba4648ed64951df33f4982dcbbd4f1fa

It will add developer column to user.

**Comment by fletch3555** [comment]
This is now possible in v0.10
