### ISSUE TITLE
voyager alter table problem

### ISSUE THREAD

**Issue by vikranth-94** [thedevdojo/voyager#1100]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by AdrianKuriata** [comment]
Did you check bread for your users table? You need to browse fields.

**Comment by vikranth-94** [comment]
yes..all are ticked

**Comment by vikranth-94** [comment]
actually i can add columns to table manually.but while receiving the form value and storing it in database,the added column value will no t be stored in database

**Comment by AdrianKuriata** [comment]
Ok this won't work because this is not a created bread(?) and view is builded manually for users add-edit.

In documentation you can check how create new view for bread and everything views in Voyager, check it and create manually view for edit-add users with your custom fields.

**Comment by vikranth-94** [comment]
what is the solution for this

**Comment by AdrianKuriata** [comment]
https://the-control-group.github.io/voyager/docs/0.11/#customization-overriding-views - here is how you can edit views.

https://github.com/the-control-group/voyager/blob/master/resources/views/users/edit-add.blade.php - here is a view for add-edit users, copy this in your new file and add your new fields.

**Comment by vikranth-94** [comment]
thank u so much

**Comment by AdrianKuriata** [comment]
It's my pleasure.

**Comment by vikranth-94** [comment]
when i tried to add uname column am getting this error


QueryException in Connection.php line 647:
SQLSTATE[HY000]: General error: 1364 Field 'uname' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `avatar`, `role_id`, `updated_at`, `created_at`) values (ereeee, jnnn@ga, $2y$10$LnlfTUWmU4NLBxeHndp61OnKo9UOshht3GDNIeeLSxuc8X1bEzquC, users/April2017/tH4R573WCMTZGi1DDQIT.jpeg, 1, 2017-04-09 10:47:59, 2017-04-09 10:47:59))

**Comment by AdrianKuriata** [comment]
You need set some value for this field, can't be empty, create new migration and set for this column nullable().

**Comment by vikranth-94** [comment]
actually i gave a value

**Comment by vikranth-94** [comment]
but it is not inserting

**Comment by vikranth-94** [comment]
insert into users (name, email, password, avatar, role_id, updated_at, created_at)

check this it is not treating uname as a column itself

**Comment by AdrianKuriata** [comment]
Maybe add this field to $fillable variable in User Model and try again?

**Comment by vikranth-94** [comment]
all done

**Comment by vikranth-94** [comment]
but no use

**Comment by AdrianKuriata** [comment]
Did you set the same name for field in database and view?

**Comment by vikranth-94** [comment]
yes

**Comment by AdrianKuriata** [comment]
I did on my project custom field and everything working, i don't have idea, you did something wrong.

**Comment by vikranth-94** [comment]
please send me the steps

**Comment by AdrianKuriata** [comment]
Ohh. 
1. Check in Bread your fields has all checked option and change type field for you want.
2. Add field to the add-edit view with the same name attribute field like field in your database.

**Comment by vikranth-94** [comment]
or documents which u reffered

**Comment by vikranth-94** [comment]
its working

**Comment by moetanahy** [comment]
hi @AdrianKuriata I'm trying the link you shared but can't find it.

https://github.com/the-control-group/voyager/blob/master/resources/views/users/edit-add.blade.php 

Can you kindly share it again, I'm trying to fix the same issue on Users.

For me, the User table doesn't even show roles.

**Comment by AdrianKuriata** [comment]
@bc-moe Hi, I'm not working on voyager anymore, this package changed from my last contribution but i think this is a file what you want: https://github.com/the-control-group/voyager/blob/1.1/resources/views/users/edit-add.blade.php

**Comment by fletch3555** [comment]
This issue has been closed for over a year now.  If you're having issues, please open your own issue or ask on our Slack group.
