### ISSUE TITLE
[Off Topic] What is the purpose of the pages table

### ISSUE THREAD

**Issue by lednhatkhanh** [thedevdojo/voyager#1102]
Hello, this question is a little bit off topic, but what is the purpose of the pages table, what is it used for? Thank you 💯. If the question is not allowed here, please let me know so I will close the issue right away.

**Comment by adriangordon1231** [comment]
I use it to store meta data about static pages on my website(s).

**Comment by abdgad** [comment]
`Posts`, `Pages` and `Categories` are there as demo data. You can use them if you want, however, they will not be supported. They will be removed from Voyager and included as separate packages in the future.
