### ISSUE TITLE
Changing admin path URL opens new difficulties.

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1108]
### Description:
Feature request: change admin URL structure.
After we change admin path(from routes - Advice: make it from voyager config ) to something like backend , whe need to rename all menu URL's and other(i dont know what other is there with admin url).
Yes, user can set admin path in start of project , but for future security reason he change path to something else and

# ARMAGEDDON IS COMING

**Comment by AdrianKuriata** [comment]
@davodavodavo3 Could you give me address e-mail to you? I have some questions and  maybe proposition for you 💃

**Comment by davodavodavo3** [comment]
davo_bidzian@mail.ru

**Comment by fletch3555** [comment]
I'm going to close this for now.  Menu items currently accept named routes, so they are dynamic.
