### ISSUE TITLE
Many To Many add/edit error when multilingual enable

### ISSUE THREAD

**Issue by nick1122** [thedevdojo/voyager#1109]
- Laravel Version: 5.3.#
- Voyager Version: 0.11.9
- PHP Version:7.0
- Database Driver & Version:MYSQL 5.7

### Description:
Table: news / tags / news_tag
news_tag :news_id / tag_id

Tag Model:
```
    public function news(){
    return $this->belongsToMany(News::class, 'news_tag','news_id' , 'tag_id');
}
```
News Model
```
public function tags(){
    return $this->belongsToMany(Tag::class, 'news_tag' ,'news_id','tag_id' );
}
```

I have created a BREAD, but i got an error when add or edit `News` with multilingual is enable.

But when multilingual disable , I dont get any error 
```
`"Array to string conversion (SQL: insert into `news` (`title`, `seo_title`, `excerpt`, `body`, `slug`, `meta_description`, `meta_keywords`, `tags`, `author_id`, `category_id`, `image`, `status`, `featured`, `date`, `updated_at`, `created_at`) values (test title, seo title, ex, <p>body</p>, test-title, 123, 456, 1, 1, 1, news/April2017/8lg6x3M7hP0wTp3jA3AJ.jpg, 0, 1, 2017-12-31, 2017-04-10 15:56:10, 2017-04-10 15:56:10))"`
```
Any idea for this error ? Thanks!
![screenshot12](https://cloud.githubusercontent.com/assets/18350752/24871346/e5b95b3a-1e4b-11e7-8770-98b267ef04fe.png)

**Comment by akazorg** [comment]
Hi @nick1122, I've send the PR #1148, could you please test it out? I'm not sure if it fixes this issue.
Thanks!

**Comment by fletch3555** [comment]
Closing due to age.  Also, PR #1148 has been merged and may fix it.

If this is still a problem on the latest release of Voyager, please open a new issue.
