### ISSUE TITLE
How insert new view?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#1110]
- Laravel Version: 5.4
- Voyager Version: 11
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.4

### Description:
How i may add route, wich should returned view if i authorized in admin panel?

Now i have route like this:
```
Route::get('/admin/needfixfilter', function () {
    return view('needfixfilter');
});

```
All users may used this route, but how i may fix it? :)

**Comment by fletch3555** [comment]
It sounds like you may not fully understand Voyager's purpose.  I'd recommend reading the Voyager documentation (https://the-control-group.github.io/voyager/docs/) and watching @thedevdojo's videos (https://www.youtube.com/playlist?list=PL_UnIDIwT95PEQFNdgXZGo5SYU5V_TQvc).  The videos are a little old/outdated, but should be enough to cover the basics.
