### ISSUE TITLE
Images in posts not responsive

### ISSUE THREAD

**Issue by samlucas92** [thedevdojo/voyager#1117]
First off I think you have done a great job with Voyager! 

I'm wondering if it would be possible to add the img-responsive class to images in the post body. Or failing that if you know where I can add this in so all my images have this class?

**Comment by AdrianKuriata** [comment]
I think this should be do for all images, i will try do this for us.

**Comment by fletch3555** [comment]
Voyager can not be responsible for the styling of content you create with it, especially in reference to how it's displayed on your site.  Closing.

**Comment by samlucas92** [comment]
Pretty easy fix in the end. It's definitely not a voyager issue though. There's something that needs to be set for the editor, I think that it would be beneficial for a lot of people if it were included in a fix. Can't remember off the top of my head what the fix was right now but as soon as I'm at a computer I'll find it and post it here.
