### ISSUE TITLE
Can not Log in to admin panel

### ISSUE THREAD

**Issue by SajaMar** [thedevdojo/voyager#1119]
-Laravel Version: 5.4
-Voyager Version: 0.11.8
-PHP Version:7.1.1
-Database Driver & Version:MySQL
-Description:

### Description:
I can't login to admin panel after i upload my laravel project to a host via c panel 

you can try to login here by any username and password to know what i mean 
(http://www.menacatalyst.org/Salon/admin/login) 
![capture3333](https://cloud.githubusercontent.com/assets/22431376/24955951/2a5980c4-1f8e-11e7-9a93-054e57c629eb.JPG)

### Steps To Reproduce:
I try to clear laravel cache and to change permissions but this doesn't help :(
i think the problem in Voyager cache how  can i delete it ?

**Comment by AdrianKuriata** [comment]
Maybe you changed something in config files like a driver cache or something? DId you try install new clear Laravel and Voyager?

**Comment by fletch3555** [comment]
Please confirm you have a `config/cache.php` file, and you have a configuration for `file` under `stores`.  It should look something like this: https://github.com/laravel/laravel/blob/master/config/cache.php#L47

**Comment by Ivanenko-O** [comment]
maybe someone can help me. I moved a website to hosting, (used a migration) and now cannot see voyager admin panel. when I trying to login - http://myhosting.in.ua/admin/login
I see 4 errors:

ErrorException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from settings where key = title limit 1) (View: /home/nameDB/myhosting.in.ua/laravel/vendor/tcg/voyager/resources/views/login.blade.php)

QueryException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from settings where key = title limit 1)

PDOException in PDOConnection.php line 47:
SQLSTATE[HY000] [2002] Connection timed out

PDOException in PDOConnection.php line 43:
SQLSTATE[HY000] [2002] Connection timed out

looks like does not exist setting table.
