### ISSUE TITLE
No profile dropdown on small device, thus can't logout

### ISSUE THREAD

**Issue by handiwijoyo** [thedevdojo/voyager#112]
![image](https://cloud.githubusercontent.com/assets/4060094/20040914/ef06cd18-a492-11e6-916f-68f63a0eac86.png)

On small device the profile dropdown changed to another icon / button. Nothing happens when click this button in result user can't open the option to logout.

**Comment by GNSubrahmanyam** [comment]
@handiwijoyo In my machine that icon is not showing. 

![image](https://cloud.githubusercontent.com/assets/18217008/20046801/e5f3d8ec-a4d3-11e6-8708-f8bba41c91b1.png)

**Comment by Frondor** [comment]
This is fixed since #670
