### ISSUE TITLE
Could not create missing storage symlink

### ISSUE THREAD

**Issue by ikiru** [thedevdojo/voyager#1120]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version: 7
- Database Driver & Version:

### Description:
We failed to generate the missing symlink for your application. It seems like your hosting provider does not support it.

I got this error after a fresh install.  first login.

**Comment by adriangordon1231** [comment]
On windows you have to run the command as admin

**Comment by ikiru** [comment]
It seems to be having an issue working on a drive that is formatted to exFat.  do you know if this is a known issue?

**Comment by adriangordon1231** [comment]
Sorry, I have never run into this problem. Hopefully someone else reading this thread has.

**Comment by fletch3555** [comment]
Filesystem type shouldn't be a problem.  Are you trying to do this on your local machine? If so, what OS are you using? (Linux? Mac? Windows?)  What does it say if you try running `php artisan storage:link` manually in the terminal?

**Comment by ikiru** [comment]
It was on a windows machine.  I updated windows to the new creator's addition and put it in developers mode and it worked fine.  I was able to fix the link in voyager.  When I ran php artisan storage:link it acted like it worked and then I still got the same error.

**Comment by olko404** [comment]
@ikiru did u fix it?

**Comment by fletch3555** [comment]
@Ivanenko-O, this has been closed for 3 months. If you have an issue, please either post on slack or create your own issue.
