### ISSUE TITLE
After install laravel auth, cannot login to voyager

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#1121]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version:
- Database Driver & Version:

### Description:
I am newer, I have a fresh laravel and voyager install, everything are working ok,but after install laravel auth:
    php artisan make:auth

I can not go to voyager admin panel, I can open http://.../admin/login, after login, always redirect to  /

is it possible, if I login by http://.../admin/login, go to voyager panel, if I login by /home, go to /home ?

**Comment by AdrianKuriata** [comment]
Could you show us your web.php in routes folder?

**Comment by jun283** [comment]
web.php:
---------------------------------------

Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

**Comment by jun283** [comment]
sorry, Is my mistake,wrong login account

**Comment by DarkcoderSe** [comment]
is it ok install laravel make:auth after installation of Voyager ? 
i want to use voyager for admin
make:auth for customers
-ecommerce site.

**Comment by fletch3555** [comment]
Please do not comment on closed issues, especially ones that have been closed for so long.  Instead, you can open your own issue or simply ask in our Slack group.
