### ISSUE TITLE
Upload multiple images, not resized

### ISSUE THREAD

**Issue by celius55** [thedevdojo/voyager#1122]
Image upload (optional details) contain:
{
    "resize": {
        "width": "1000",
        "height": "null"
    }
}
Multiple images upload contains same code

After upload:
1. single image is resized
2. multiple images is not resized

I find in Controller.php
*** IMAGE TYPE *** 
//contain this code:
if (isset($options->resize) && isset($options->resize->width) && isset($options->resize->height)) {
                        $resize_width = $options->resize->width;
                        $resize_height = $options->resize->height;
                    } else {
                        $resize_width = 1800;
                        $resize_height = null;
                    }
//////////////////////////////////
but ****** MULTIPLE IMAGES TYPE ****** not contain this if condition

**Comment by lancepioch** [comment]
Labels: possible bug

Close (pull request merged)

**Comment by azizbekeshonaliyev** [comment]
"resize": {
"width": "1000",
"height": "null"
}
**you should write null with out "":**
"resize": {
"width": "1000",
"height": null
}
