### ISSUE TITLE
Load different view after login based on user role

### ISSUE THREAD

**Issue by xotik** [thedevdojo/voyager#1123]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.6.*

### Description:
I´m trying to implement a way to load different views after successfull login, based on user role.

As an example, I want admins to land in the Dashboard, but I want regular users to land in a Tasks page, which is a custom table with bread enabled.

After looking at voyager's code, I decided that the place to do this is in the `index` method of the VoyagerController.php file. I successfully get the current users role, but my ignorance starts here:

`return view('voyager::index');`

I understand the code above, but how can I change it to return a custom view in voyager, when I don't have a `task` view (I suppose it's using the generic `browse.blade.php` view inside the `bread` folder)?

**Comment by AdrianKuriata** [comment]
`return redirect()->route('your_route')`? I don't exacly know what do you mean.

**Comment by xotik** [comment]
Hi @AdrianKuriata, you´re talking about routes, I was talking about views. But you're problably right, routes is the way to go, not views.
So I tried your example, as expected it returns an error saying that my route is not defined, which is true.

I know that I can go to the routes file and add it, but my question here is how do we proceed with routes that were created with BREAD, since there are no routes created in the routes file for these custom tables, but somehow the code gets there? Should we call route() with any extra parameter, like the slug?

Thanks for helping!

**Comment by AdrianKuriata** [comment]
Try Route::getRoutes(); you will get routes from whole application.

**Comment by xotik** [comment]
Excellent tip @AdrianKuriata, problem solved! Thank you very much.

**Comment by AdrianKuriata** [comment]
I'm happy i can help!

**Comment by fletch3555** [comment]
For future reference, please limit help requests to the #help channel on Slack.  Github issues should be reserved for issues/bugs with the Voyager codebase.

**Comment by xotik** [comment]
Will do @fletch3555!

**Comment by Elshaden** [comment]
Late Answer but for the record:
I used the VoyagerController
Like so

class VoyagerController extends Controller
{
public function index()
{

    if(Auth::user()->role_id == 1){
        return Voyager::view('voyager::index');
    }elseif(Auth::user()->role_id == 3){
        return Redirect::action('XXXXXXXController@index');
    }elseif(Auth::user()->role_id == 4){
        return Redirect::action('YYYYController@index');
   
    }else{

      return  view('voyager::FFFF.VIewPager');
    }


}

**Comment by fletch3555** [comment]
@Eishaden, please don't comment on old issues. They're for completely different versions that likely won't support the fix you're suggesting
