### ISSUE TITLE
what Voyager::canOrFail('') should return ?

### ISSUE THREAD

**Issue by alihbuzaid** [thedevdojo/voyager#1126]
what Voyager::canOrFail('') should return ?

I couldnt understand the documents 
it always return 1

thanks ,,

**Comment by AdrianKuriata** [comment]
Maybe you have permissions for all items in the application and it always return `true`?

**Comment by fletch3555** [comment]
@Sndan, Please feel free to look through the code to find what you're looking for.  Specifically, https://github.com/the-control-group/voyager/blob/master/src/Voyager.php#L181 is where that function is defined.  `canOrFail()` will always return true or an `UnauthorizedHttpException`;
