### ISSUE TITLE
designing user website same as admin panel

### ISSUE THREAD

**Issue by vikranth-94** [thedevdojo/voyager#1127]
can we design user website same as posts pages in admin panel of voyager package.if yes then please provide me the steps to do it

**Comment by vikranth-94** [comment]
i did it but am getting these errors.what changes i need to do

ErrorException in C:\xampp\htdocs\talent\storage\framework\views\2cb1da4e99fadf799940f443d05c25f4c9e3c3b7.php line 1:
Undefined variable: dataType (View: C:\xampp\htdocs\talent\resources\views\talents\browse.blade.php)

**Comment by fletch3555** [comment]
Unfortunately we are unable to support you building the frontend of your site as that is not an issue within Voyager.
