### ISSUE TITLE
variables in Additional Field Options

### ISSUE THREAD

**Issue by alihbuzaid** [thedevdojo/voyager#1129]
can we use variable inside it ?
like 
```
{
    "relationship": {
        "key": "id",
        "label": "name"
        "value": $user->id
    }
}
```
it would be very helpful

**Comment by fletch3555** [comment]
We will not be adding in functionality to parse PHP variables from the JSON field configuration.  We may consider different options like a pseudo-templating language for the JSON configuration that allows you to reference Settings or similar, but that's a long way off.
