### ISSUE TITLE
Cannot login to admin, TokenMismatchException in VerifyCsrfToken.php

### ISSUE THREAD

**Issue by baddwin** [thedevdojo/voyager#113]
I have 2 installations of Laravel version 5.3. The first one is upgraded from 5.2 and I install Voyager without any error in the development. But when I push it to production server (by git hooks), it throws error something like `TokenMismatchException in VerifyCsrfToken.php` when I try to login with default credential. I installed voyager via SSH on production. FYI, the server is backed by Cloudflare.

The second one is a fresh install of version 5.3. I also cannot login to the Voyager in this server. When I try to login with default credential, it throws no error, but it doesn't take me to admin page, and shows the login page instead.

*Edit*: It's likely caused by wrong permissions in the *storage* folder, but I'm not sure what to change. I have set all folders and contents inside `storage` folder to 777.

I have changed the folder permissions and clear cache, dump autoload; the fresh install now works well, but the upgraded one still encounters login error, although I did the same procedure.

**Comment by marktopper** [comment]
Is this still an issue?

**Comment by baddwin** [comment]
Yes, it's still an issue for upgraded Laravel, but now is okay for the fresh install of 5.3
