### ISSUE TITLE
Dropdown Field using Accessor as Label breaks BREAD

### ISSUE THREAD

**Issue by tfmm** [thedevdojo/voyager#1130]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:
When using an accessor as a "label" value for a relationship, BREAD fails to load after adding a record to the database. 

Here's the relationship json:
```
{
    "relationship": {
        "key": "id",
        "label": "fullname_id"
    }
}
```

`fullname_id` is an accessor created in the model:
```
        public function getFullnameIdAttribute($value)
        {
                return $this->id . ' - ' .ucfirst($this->first_name) . ' ' . ucfirst($this->last_name);
        }
```

### Steps To Reproduce:
Create the dropdown with the relationship json as shown above.
Add a record to the database using the dropdown field
Attempt to load the BREAD page to view the table.

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by handiwijoyo** [comment]
Voyager implement new Relationship system in `1.0`. Please check it out.
