### ISSUE TITLE
Menu Item disappears after creating BREAD for table

### ISSUE THREAD

**Issue by newpain01** [thedevdojo/voyager#1131]
- Laravel Version: 5.4
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: sqlite3

### Description:
Menu Item disappears after creating BREAD for table

### Steps To Reproduce:
Add new Menu Item in the Menu Builder.
The new menu item is visible in the admin menu.
Add bread to the table.
The new menu item disappears from the admin menu.

**Comment by AdrianKuriata** [comment]
Did you check in your database this item is delete too?

**Comment by newpain01** [comment]
It's not deleted from the database

**Comment by abdgad** [comment]
Make sure the admin has permissions to view the BREAD item.

**Comment by fletch3555** [comment]
@abdgad's suggestion is likely correct.  When you created the BREAD, it likely had "Create Permissions" set to `true`.  You need to add these permissions to the appropriate `Role` in order to see the menu item.

**Comment by endrureza** [comment]
@newpain01 yeah, it happened to me. you just need to tick the permission and set everything for admin, you will soon see the new menu you just added.

**Comment by newpain01** [comment]
@endrureza thanks! I had to implement a back-end solution fast, so I switched to Backpack, since I didn't have time to debug and find out why. Thanks anyway
