### ISSUE TITLE
Show post & pages

### ISSUE THREAD

**Issue by robertnicjoo** [thedevdojo/voyager#1133]
- Laravel Version: 5.4.18
- Voyager Version: 0.11.9
- PHP Version: 7.1.1
- Database Driver & Version: Mariadb 10.2.3

### Description:
Hi,
I'm totally new in laravel and still trying to learn what is what, I installed Voyager successfully and there's no problem on it, the only issue i have is to show posts & pages in front-end website.
I searched a lot also i read voyager docs but there's no any guide for this in web or a least i couldn't find it. I would be appreciated if someone help me and lead me how to do it.

Thanks.

**Comment by AdrianKuriata** [comment]
You need to use Voyager models to load data same like in Laravel docs.  This can be solution for you #1100

**Comment by fletch3555** [comment]
This is not an issue with Voyager.  For future help/support requests, you're welcome to [join our Slack group](https://voyager-slack-invitation.herokuapp.com/), and post in the #help channel.

Additionally, this is a question better targeted toward the Laravel documentation, as it's not specific to Voyager.

**Comment by robertnicjoo** [comment]
@fletch3555 As I said I'll mention again that i'm new so maybe what i want to say be wrong but i guess it's completely specific to voyager cause to call em in front-end i need their function names and all functions made by voyager so i have no idea what names and codes i have to call to get what i'm looking for.

Anyway thanks for help.

**Comment by hamza-mostafa** [comment]
@robertnicjoo I struggled at first also, Voyager reaaaaally seems like a CMS, i hope you have solved it, this is for other searchers like me:
Voyager is fancy .. very fancy actually .. but it is still a Laravel package ..
so the **quick and dirty solution** just use `\TCG\Voyager\Models\Page::all()`, **or even better** create a model and extend `\TCG\Voyager\Models\Page` or `Post` if that is the case and then `\App\YourModel::all()`

**Comment by robertnicjoo** [comment]
@hamza-mostafa thanks for dusting up this issue :)) when I created this issue, it was my first attempt with voyager and my last. Since then I am creating my own admin panels and queries.

@AdrianKuriata @fletch3555  please close this issue.

Thank you.

**Comment by emptynick** [comment]
It IS closed
