### ISSUE TITLE
Fail to load bg.jpg when not using root path for the project

### ISSUE THREAD

**Issue by dhcmega** [thedevdojo/voyager#1134]
- Laravel Version: 5.4.16
- Voyager Version: 0.11.9
- PHP Version: 7.0.15-1
- Database Driver & Version:

### Description:
Login screen fails to load the bg.jpg background due to the site not being hosted at the URL root path, in my case I am using http://www.example.com/voyager.

### Steps To Reproduce:
Install in a sub dir.
ATM fixed it by changing this route: config('voyager.assets_path') . "/images/bg.jpg" )
If I change the actual route in the config file, it breaks all the asset URLs.

Original line:
            background-image:url('{{ Voyager::image( Voyager::setting("admin_bg_image"), config('voyager.assets_path') . "/images/bg.jpg" ) }}');

Wordaround line:
            background-image:url('{{ Voyager::image( Voyager::setting("admin_bg_image"), voyager_asset('/') . "/images/bg.jpg" ) }}');

**Comment by Msoliman-waleed** [comment]
Hi there,
i was facing the same issue ,i think the best solution that worked for me is configuring a "Virtualhost" directive in apache config file-or the equivalent if you are using NGINX- to refer to your sub directory.
