### ISSUE TITLE
cannot login to voyager

### ISSUE THREAD

**Issue by alexelev** [thedevdojo/voyager#1136]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.5

### Description:
Some screenshots by links.
I'm doing a new installation of Laravel and voyager. I prescribe the provider.  Trying to go into admin panel - [fail](http://prntscr.com/ewy1bc).  [Then I try to create a new admin record](http://prntscr.com/ewy12u). [But dummy-data is here](http://prntscr.com/ewy206). 
![screenshot_144](https://cloud.githubusercontent.com/assets/3392106/25067592/091ebbac-2251-11e7-94c9-7b1464724fa2.jpg)
![screenshot_146](https://cloud.githubusercontent.com/assets/3392106/25067621/b14079a6-2251-11e7-89fb-c7d6ca7109c9.jpg)

**Comment by sarath-c-sandwich** [comment]
how about LV 5.4 ? Does it work? I think community haven't yet worked on 5.5

**Comment by alexelev** [comment]
Ou, so sorry, my mistake. Of cource, it's LV 5.4.

**Comment by fletch3555** [comment]
You mention that "dummy-data is there".  Do you mean the dummy data installed as part of `php artisan voyager:install --with-dummy`?  If so, does the default `admin@admin.com` account work?

**Comment by alexelev** [comment]
Yes, it was installed with '--with-dummy' and no, default admin account doesn't work.

**Comment by fletch3555** [comment]
Please check the database and confirm that a user exists in the users table.  Also, please try creating a new admin user with the `artisan voyager:admin [emailAddress] --create`

**Comment by alexelev** [comment]
![screenshot_154](https://cloud.githubusercontent.com/assets/3392106/25096624/bae2a7dc-23a9-11e7-86fa-369e87d67592.jpg)

**Comment by fletch3555** [comment]
That's a ModelNotFoundException... did you rename or change the package of your User model?  If so, please update the appropriate configuration in `config/voyager.php` with the new fully-qualified package/model.

**Comment by alexelev** [comment]
> did you rename or change the package of your User model?

No, I did not do anything like that
![screenshot_155](https://cloud.githubusercontent.com/assets/3392106/25096947/11e55088-23ab-11e7-8172-24c3f1ffe53a.jpg)

**Comment by sarath-c-sandwich** [comment]
I think you should reinstall Voyager with version 0.11.9 and run the dummy data again

**Comment by anthonyivol** [comment]
![image](https://user-images.githubusercontent.com/19983700/66531608-aa408200-eb0c-11e9-9191-5ad2784363af.png)

**Comment by anthonyivol** [comment]
`php artisan key:generate`
then switching from `php artisan serve` to brew httpd worked for me
