### ISSUE TITLE
Issue with custom model instead regular user model of laravel

### ISSUE THREAD

**Issue by rPr3v0t** [thedevdojo/voyager#1137]
- Laravel Version: 5.3
- Voyager Version: 0.11.9
- PHP Version: 7
- Database Driver & Version: Msql

### Description:
I change in my auth.php with 
`'model' => App\Member::class,`
I change my voyager config with => 

```
'user' => [
        'add_default_role_on_register' => true,
        'default_role'                 => 'user',
        'namespace'                    => App\Member::class,
        'default_avatar'               => 'users/default.png',
    ],
```
But when i create a new console admin user or login in admin, voyager try to find or insert or update in myDBtable.users and not my myDBtable.members

What can i do to always target my Member class and db table members and not the users laravel table ??

![capture-d ecran-2017-04-16-a-12 54 20](https://cloud.githubusercontent.com/assets/9515269/25070648/5ea6733c-22a4-11e7-82c2-ac9937abbd8a.jpg)

**Comment by akazorg** [comment]
Hello. I've sent #1194 for fix this. Thanks for the report!

**Comment by fletch3555** [comment]
I'm going to close this due to age.  If it's still an issue in the v1.x stream, please open a new issue referencing this one.
