### ISSUE TITLE
translate all texts

### ISSUE THREAD

**Issue by AngeloMerlo** [thedevdojo/voyager#1138]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version: 7

### Description:
How do I translate all texts? Is there any way or just opening the files and modifying manually? Sorry, but I did not find out about this in the documentation! Thank you.

**Comment by AdrianKuriata** [comment]
@marktopper

**Comment by akazorg** [comment]
There's work in progress, please check #760 and #1055.
