### ISSUE TITLE
Voyager::image function - Storage::disk( not returning url with port no

### ISSUE THREAD

**Issue by akwatra** [thedevdojo/voyager#1139]
![img-url](https://cloud.githubusercontent.com/assets/8591071/25073395/79769db8-2303-11e7-909b-52b6b3cc819c.png)
- Laravel Version: 5.4..13
- Voyager Version: v0.11.3
- PHP Version: 7
- Database Driver & Version: NA

### Description:

your url method used not getting reference of port no
so all images path broken,
this may also due to Storage::disk(config('voyager.storage.disk'))->url($file);

### Steps To Reproduce:
php artisan server --port=8001

http://127.0.0.1:8001/admin/posts

returning:
http://localhost/storage/posts/7uelXHi85YOfZKsoS6Tq.jpg

so without port in url image broken,
even though image file exits

**Comment by sarath-c-sandwich** [comment]
Can you show me your APP_URL in .env ?
Anyway, I tried different port and that still work in mine.

<img width="1278" alt="screen shot 2017-04-17 at 5 18 54 pm" src="https://cloud.githubusercontent.com/assets/1330852/25086488/3779b37a-2392-11e7-81d7-514bf30c42e6.png">

**Comment by fletch3555** [comment]
APP_URL is likely set incorrectly as @uchsarath mentioned.  Please check this and respond here whether this is resolved.

**Comment by akwatra** [comment]
Its working now. have to explicit 
APP_URL=http://127.0.0.1:8001

**Comment by tamersolieman** [comment]
@uchsarath You just need to restart the server after you change in .env file

**Comment by fletch3555** [comment]
@tamersolieman, this issue has been closed for nearly a year. Your comment adds nothing to it. Please refrain from doing so

**Comment by hooch** [comment]
@tamersolieman thank you for adding your comment, it helped me.

**Comment by adrielwerlich** [comment]
there is no way to make voyager get the current port? Instead of hardcoding it?

**Comment by fletch3555** [comment]
Thats a Laravel limitation(or feature), not specific to Voyager

**Comment by adrielwerlich** [comment]
👍 ..ok

**Comment by hooch** [comment]
If you recently changed the port in .env and are having troubles with the port, maybe all you need to do is kill and restart artisan serve, so laravel can pick up the new port.

**Comment by adrielwerlich** [comment]
my problem is that I´m running on different ports and I´m having to change every time the port in the APP_URL in the .env file... 
so the avatars pictures aren´t showing if I do not change

**Comment by fletch3555** [comment]
What you're describing is a limitation in how Laravel renders asset URLs, and is only tangentially related to Voyager, so I'm going to have to stop the discussion here.  Feel free to discuss all you want in slack or elsewhere if you wish.

I will say, however, that if your port is changing all the time, you need to take a closer look at your deployment process and webserver configuration.  Perhaps you need a proxy layer to provide a consistent endpoint
