### ISSUE TITLE
"Optional Details" Field updates race condition with multilingual

### ISSUE THREAD

**Issue by chrisboustead** [thedevdojo/voyager#1144]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.9
- PHP Version: 7.1.x
- Database Driver & Version: MySQL 5.7.14

### Description:
When multilingual support is enabled, and a user attempts to edit the "Optional Details" fields in the add/edit bread screens, there is a race condition which occurs, and sometimes will not save the "Optional Details" values.

This occurs because the JSON is parsed for validity on form submission, then updated the nearby textarea element.  When multilingual support is also enabled, the jQuery plugin transforms the translations into JSON for the nearby hidden inputs of each field, then immediately submits the form.

So the form is usually submitted by multilingual plugin when the "Optional Details" JSON has not yet been fully processed.

### Steps To Reproduce:
* Enable Bread translations in `app/voyager.php`
* Edit Bread for any translatable schema in `Tools > Database`
* Add some JSON to the "Optional Details" field for one column
* Submit the form.
* The JSON added to "Optional Details" was not saved.

**Comment by akazorg** [comment]
Hi @chrisboustead, 

In fact it's kind of tricky because we need to update all hidden inputs (containing each translation), before submitting the form, otherwise the latest form changes would not be affected.

I will check this.

**Comment by chrisboustead** [comment]
Agreed, I think the best solve to avoid future issues would potentially be adding a validation library to all forms.  Obviously a heavy lift for what is only a small issue right now. 

For now maybe removing the `submit` event from multilingual.js and manually calling `prepareData` from the javascript section of each multilingual view with a form.

**Comment by chrisboustead** [comment]
If there is a validation library you've identified as a good candidate for voyager, I'd be happy to lead the effort in incorporating into the project.

**Comment by akazorg** [comment]
On the multilingual.js, we can define a optional callback function to take care of this issue (and future ones). I have to check that and see what's happening.

About the validation it sounds a great idea, but I can't say much because I haven't work with that, however, I've seen some activity with this topic.

**Comment by chrisboustead** [comment]
Submitted a quick pull request which fixes the issue, though I do think a better long-term solution is reusable validation library which can be hooked by multilingual, ace editor, etc. 

https://github.com/the-control-group/voyager/pull/1147

**Comment by akazorg** [comment]
@chrisboustead join us on slack channel! :)
