### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by SUPERNOVI** [thedevdojo/voyager#1145]
- Laravel Version: 5.4.18
- Voyager Version: 0.11.9
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.2.3

### Description:

Hi,

I really love this project but I'm finding the documentation a little lacking.

As an example, if I create a custom view for the BREAD for an add and edit page and I'd like to use one of the Voyager generated inputs like Multi select there is no documentation on how to call it within the blade template manually.
So could someone give me an idea where I need to look to figure this out or even tell me?

I apologise if this isn't a suitable place to ask, but I really struggled to find any means of contact other than GitHub.

Much appreciated,
Tim

**Comment by SUPERNOVI** [comment]
Has anyone at Voyager read this?

**Comment by fletch3555** [comment]
I recommend you join our slack chat and ask there. The #help channel would be a good place to start with questions like this.

We know the documentation is lacking, and I promise it's something we're working on.

**Comment by sarath-c-sandwich** [comment]
Agree with @fletch3555  just join the Slack, and it's easier to get supported by community.

**Comment by adriangordon1231** [comment]
I don't think that "just join slack" is a good solution to this problem. The docs should be updated with the relevant information.

**Comment by akazorg** [comment]
You're absolutely right @adriangordon1231, documentation requires update. You are free to contribute by sending a PR - that will help us.

In case you need help, then slack is available for support.

**Comment by SUPERNOVI** [comment]
@akazorg bit passive aggressive there. 

I'd happily contribute some of the stuff I've learnt but I'm 90% sure the way I've done things is not **the voyager** way.

I have to agree also, "Just join Slack" whilst helpful should not be considered the norm. Slack whilst popular is not something everyone uses, I had to sign up just for this purpose.

**Comment by fletch3555** [comment]
@SUPERNOVI, his comment was not passive-aggressive in my eyes.  We always welcome and encourage pull requests if you find something missing or wrong.  The worst we'll say is "no sorry, this is wrong, could you please do it [this way] instead?"

As for slack, the way it works is that everyone has to sign up to use it.  Each slack group has unique authentication, meaning you would have 4 unique accounts for 4 different slack groups.  We encourage users to join us there to minimize the "how do I do this?" issues here.  That helps us get to actual issues faster.

**Comment by akazorg** [comment]
@SUPERNOVI, I don't know what happen on your side of the communication, but my message was intended to help.

Please keep in mind this is an open source project, created with love, for free, from all of us. 

If something is missing, let's work together on that!

Slack is a great support channel, you can get real time response.

Happy coding :)

(Close this issue?)

**Comment by akazorg** [comment]
@SUPERNOVI I was thinking, did you checked VoyagerPostController? maybe it can help you to figure out how to create custom controllers.
I hope it helps.

**Comment by adriangordon1231** [comment]
@akazorg Wish I could, however I am facing similar issues to the OP

**Comment by akazorg** [comment]
@adriangordon1231, sorry, OP?

**Comment by adriangordon1231** [comment]
@akazorg "Original Poster" ... of the issue. Sorry.

**Comment by akazorg** [comment]
The documentation?
All help is grateful, for instance, what do you miss on docs @SUPERNOVI @adriangordon1231?

Maybe we can create a list of missing topics and work from there?

**Comment by akazorg** [comment]
closed due to inactivity
