### ISSUE TITLE
Admin theme html

### ISSUE THREAD

**Issue by bonucci** [thedevdojo/voyager#1146]
Was this admin panel theme was designed from scratch or is using a admin template?

**Comment by fletch3555** [comment]
@thedevdojo did the original design and development, so I'll let him answer this one.

**Comment by fletch3555** [comment]
@tnylea? Would you mind answering the question above? (sorry, had the wrong user tagged before)

**Comment by handiwijoyo** [comment]
You can add additional css / js files to voyager config. See: https://voyager.readme.io/docs/additional-css-and-js-theming
