### ISSUE TITLE
how to create a dynamic page and display it according to menu 

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1149]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description
i have create a menu dynamicaly but don,t know to create a page and display this page according to the menu

**Comment by fletch3555** [comment]
Help requests are better served through our Slack group.  I recommend joining that (link is in our README), and asking in the #help channel.
