### ISSUE TITLE
Auto populate BREAD fields from Table Name

### ISSUE THREAD

**Issue by fishmad** [thedevdojo/voyager#115]
use jquery or some other script to dynamically populate the newley created BREAD slug, name and model fields etc:

- products
- Product
- products
- App/Products

Manually entering *product* 4 times is overkill, make it auto and a person can by-choice overide names by manual data entry if they dont like defaults.

**Comment by tahq69** [comment]
I may try to implement this one :)

**Comment by tnylea** [comment]
This has been added to master will have a new version release with this fix out later today.

Thanks @tahq69
