### ISSUE TITLE
Roles: Editor cannot edit his own profile?

### ISSUE THREAD

**Issue by nalorim** [thedevdojo/voyager#1150]
- Laravel Version: 5.4.19
- Voyager Version: 0.11
- PHP Version: 7.1.3
- Database Driver & Version: Mysql

Description:

I think this is not really an issue, but something to be aware of.

I created an editor role that does not have access to edit user profile.

However, I think it should be allowed to edit its own profile.

If you have time, please check on this.

Best Regards

**Comment by akazorg** [comment]
Thanks for the note @nalorim.
