### ISSUE TITLE
Error on add new menu item

### ISSUE THREAD

**Issue by endrureza** [thedevdojo/voyager#1151]
- Laravel Version: 5.4.19
- Voyager Version: 0.11.9
- PHP Version: 5.6
- Database Driver & Version: Mysql & 5.5.5-10.0.29-MariaDB-0ubuntu0.16.04.1

### Description:
everytime i wanna to add new menu item, it appears there is a field which makes error on adding one, here is dd of `$request->all()` inside VoyagerMenuController@add_item whenever i add new menu item :

```
array:13 [▼
  "_method" => "POST"
  "_token" => "z70g827825FyRlDwkNi01hlWFjF05lqTNCtHLgyr"
  "title" => "Home"
  "type" => "url"
  "url" => "/"
  "route" => null
  "parameters" => null
  "icon_class" => "fa fa-home"
  "color" => "#000000"
  "target" => "_self"
  "menu_id" => "2"
  "id" => null
  "/admin/menus/2/item" => null
]
```

what's exactly the last one ?

### Steps To Reproduce:
Remove this unnecessary field.

**Comment by akazorg** [comment]
Hi @endrureza, can you please provide the error message?
It doesn't seam you're using the multilingual system, can you also confirm this?
Thanks!

**Comment by endrureza** [comment]
This is the error

**PDOException in PDOConnection.php line 77:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '/admin/menus/1/item' in 'field list'**

I don't deal with multilingual system, all i did only install the system fresh and add the menu item

@akazorg 

for current solution i add this inside add_item method in VoyagerMenuController 

```
$data = $this->prepareParameters(
        $request->all()
);

end($data); <----
unset($data[key($data)]); <----

unset($data['id']);
$data['order'] = 1;
```

**Comment by akazorg** [comment]
Hello @endrureza, I just test it out and everything works fine.
Are you sure you haven't change something on your setup?
Anyone else experiencing errors with this?

**Comment by endrureza** [comment]
@akazorg Nope, like i said, after doing 

```
php artisan voyager:install --with-dummy 
```

all i did was login into admin and then add menu item, and that's the error appear. Here's my setting in case you need it

https://gist.github.com/endrureza/47b1e6f0ab514045ee67c2fd84626b19

**Comment by akazorg** [comment]
You're not using the latest version, because I remember changing something in the config that doesn't match your file, however, this issue doesn't seam related to that.

Have you tried publishing vendor assets?

I have no idea what could be happening in here, because it seams to be working with everyone. But let's find out!!

**Comment by endrureza** [comment]
@akazorg nope, i don't seem to recall doin' anything with vendor assets. It's pure installation like i said. But thanks for responding to this bug. :+1:

**Comment by akazorg** [comment]
Did you sort that out?

**Comment by endrureza** [comment]
@akazorg problem stays dude. It's not fixed yet, i just figured it out about why it happens, 

when i'm using localhost:8000 to serve the web, it works. Adding new menu item is succesful, but when it comes to virtual host like test.dev it doesn't work. Any idea bout' this ?

**Comment by akazorg** [comment]
Did you change the .env file parameter `APP_URL=http://test.dev`?

**Comment by endrureza** [comment]
@akazorg yupz, i did that the first time i install the package

**Comment by varbark** [comment]
Hi @endrureza ,  I also encounter the same problem. Work fine in localhost, but not work in other domain.  Does anyone solve this issue yet?

**Comment by dmeijboom** [comment]
We had the same kind of error. Our problem was that in our nginx config we specified 'try_files $uri $uri/ index.php?q=$uri' so on every page there is a query-string parameter containing the full URL. Somehow this is added into the SQL query (in our case we got an exception stating that column 'q' was not found).

**Comment by endrureza** [comment]
the latest update, fix this problem

**Comment by monim67** [comment]
Just encountered this error, everything on voyager is working just as fine, but cannot add new menu item because of the error.

**Comment by emptynick** [comment]
This issue is more than one and a half year old and for a much much older version.
Please open your own issue if you think you found a bug.
