### ISSUE TITLE
how to work with image intervention

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1152]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

how to work with image inetervention how to customize an image and apply water mark on it in using laravel voyager bluid in controller used for crud

**Comment by fletch3555** [comment]
This is not an issue with Voyager.  Please review the Laravel and [Intervention](http://image.intervention.io/) documentation.  If you still have issues or need help, please feel free to join our Slack group and ask in the #help channel
