### ISSUE TITLE
How to disable access without authorization?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#1156]
**Laravel Version: 5.4
Voyager Version: 11
PHP Version: 7.1
Database Driver & Version: MySQL 5.4
Description:**

Now i have route like this:

**web.php**
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::get('needfixfilter','IndexController@index');

});

```
xxx/admin/needfixfilter 
All users may used this route, but how i may fix it? :)
If users don't have access in admin panel, the should be redirect to xxx/admin ^)

**In doc. i didn't find it... Help me plz ^)**

**Comment by fletch3555** [comment]
Your controller needs to check for a permission. You can choose/create a custom one, or use an existing one (default for access to Voyager is `browse_admin`)
