### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by kjdion84** [thedevdojo/voyager#1158]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:
Receiving the following errors in console when attempting to install Voyager:

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `translations` add unique `translations_table_name_column_name_foreign_key_locale_unique`(`table_name`, `column_name`, `forei
  gn_key`, `locale`))

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### Steps To Reproduce:
php artisan voyager:install

I have also tried adding Schema::defaultStringLength(191); to AppServiceProvider::boot(), which did not correct the issue.

**Comment by kjdion84** [comment]
This is the only solution that worked: https://github.com/the-control-group/voyager/issues/901#issuecomment-291470960

**Comment by kjdion84** [comment]
Scratch that, all you have to do is set the mysql engine to `InnoDB ROW_FORMAT=DYNAMIC`

**Comment by vidhi041** [comment]
After adding Schema::defaultStringLength(191); to AppServiceProvider::boot(), You need to change  
'engine' => 'InnoDB', in config/database.php in mysql.

It is working for me !

**Comment by fletch3555** [comment]
Please don't common on very old closed issues.
