### ISSUE TITLE
How to creat Drop down selections in BREAD form maker

### ISSUE THREAD

**Issue by fishmad** [thedevdojo/voyager#116]
Cant see any instructions on how to create selection items for dropdowns in the form maker, would it be safe to assume we would enter these as JSON code into the empty text field on far right?

**Comment by handiwijoyo** [comment]
@fishmad the examples how to use additional field options are on the docs https://the-control-group.github.io/voyager/docs/#voyager-docs-database-tools-additional-field-options

For dropdown can use something like:

```
{
    "default" : "option1",
    "options" : {
        "option1": "Option 1 Text",
        "option2": "Option 2 Text"
    }
}
```

**Comment by fishmad** [comment]
Great thank you, clearly had a 'mans look' when trying to find the documentation first time.
