### ISSUE TITLE
SQLSTATE[22007]: Invalid datetime format: 

### ISSUE THREAD

**Issue by ikiru** [thedevdojo/voyager#1161]
Laravel Version: 5.4
Voyager Version: 0.11.9
PHP Version: 7

### Description:
Received the same error when trying to enter data into four different new tables.  I include screen shots from one of them.

### Steps To Reproduce:
![image](https://cloud.githubusercontent.com/assets/6228244/25281451/0c0243d6-2673-11e7-9d4a-0ce4b7229765.png)
![image](https://cloud.githubusercontent.com/assets/6228244/25281562/633973ae-2673-11e7-9d5f-458d5cac446f.png)
![image](https://cloud.githubusercontent.com/assets/6228244/25281621/880bb520-2673-11e7-90f6-62276ec44990.png)

**Comment by abdgad** [comment]
You need to change `name` type from `INTEGER` to `VARCHAR`.
