### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by unabomber87** [thedevdojo/voyager#1162]
- Laravel Version: 5.4.19
- Voyager Version: v0.11.9
- PHP Version: 7.0.15
- Database Driver & Version: Mysql

### Description:
on a fresh install when trying to upload a file
there's an exception
ErrorException in VoyagerMediaController.php line 186:
Undefined variable: path

### Steps To Reproduce:
try to upload file

**Comment by adishardis** [comment]
This happened to me as well with the same configuration. However it was only the largest file that failed to upload. Could there be som kind of size limit for uploads?

**Comment by sarath-c-sandwich** [comment]
Can you check your .env file again? and change to
APP_URL = http://localhost:8000  
my computer, I use http://127.0.0.1:8000

or based on your default port.

**Comment by adishardis** [comment]
my .env app_url has my domain name and if I change it, no images are shown.

Howerver, today the file upload works??!! Not sure what I did wrong yesterday but it's now  working for me!

Thanks for your help anyway!! 

Cheers
/Adam

**Comment by unabomber87** [comment]
It's was a problem of permission thanks for your help :)

**Comment by itupdate119** [comment]
@unabomber87 : I have same problem. Can you tell me how to fix permission problem?
My server: Windows server 2012; IIS 8.5; 

Thanks

**Comment by unabomber87** [comment]
@itupdate119 check storage folder permission

**Comment by itupdate119** [comment]
@unabomber87 : I assigned permission for folder "storage" with full permission for "Everyone" and "Users". But I still get error as above. Can you help me what's else?

Thanks!

**Comment by unabomber87** [comment]
@itupdate119 check also permission for storage/app/public

**Comment by itupdate119** [comment]
@unabomber87 : I check permission for storage/app/public. It has the same permission as "storage" folder.
I still get error above. Can you help me how to debug about this permission?

Thanks!

**Comment by unabomber87** [comment]
@itupdate119 
in vendor/tcg/voyager/src/Http/Controllers/VoyagerMediaController.php
add this line  `dd($request->upload_path);` on line 177 just on the top of the upload function
try to reproduce the upload tell me what do you have as a result

**Comment by itupdate119** [comment]
@unabomber87 : "/admin/media/upload" response of upload when use `dd($request->upload_path)` is 
`<script> Sfdump = window.Sfdump || (function (doc) { var refStyle = doc.createElement('style'), rxEsc = /([.*+?^${}()|\[\]\/\\])/g, idRx = /\bsf-dump-\d+-ref[012]\w+\b/, keyHint = 0 <= navigator.platform.toUpperCase().indexOf('MAC') ? 'Cmd' : 'Ctrl', addEventListener = function (e, n, cb) { e.addEventListener(n, cb, false); }; (doc.documentElement.firstElementChild || doc.documentElement.children[0]).appendChild(refStyle); if (!doc.addEventListener) { addEventListener = function (element, eventName, callback) { element.attachEvent('on' + eventName, function (e) { e.preventDefault = function () {e.returnValue = false;}; e.target = e.srcElement; callback(e); }); }; } function toggle(a, recursive) { var s = a.nextSibling || {}, oldClass = s.className, arrow, newClass; if ('sf-dump-compact' == oldClass) { arrow = '&#9660;'; newClass = 'sf-dump-expanded'; } else if ('sf-dump-expanded' == oldClass) { arrow = '&#9654;'; newClass = 'sf-dump-compact'; } else { return false; } a.lastChild.innerHTML = arrow; s.className = newClass; if (recursive) { try { a = s.querySelectorAll('.'+oldClass); for (s = 0; s < a.length; ++s) { if (a[s].className !== newClass) { a[s].className = newClass; a[s].previousSibling.lastChild.innerHTML = arrow; } } } catch (e) { } } return true; }; return function (root, x) { root = doc.getElementById(root); var indentRx = new RegExp('^('+(root.getAttribute('data-indent-pad') || ' ').replace(rxEsc, '\\$1')+')+', 'm'), options = {"maxDepth":1,"maxStringLength":160,"fileLinkFormat":false}, elt = root.getElementsByTagName('A'), len = elt.length, i = 0, s, h, t = []; while (i < len) t.push(elt[i++]); for (i in x) { options[i] = x[i]; } function a(e, f) { addEventListener(root, e, function (e) { if ('A' == e.target.tagName) { f(e.target, e); } else if ('A' == e.target.parentNode.tagName) { f(e.target.parentNode, e); } else if (e.target.nextElementSibling && 'A' == e.target.nextElementSibling.tagName) { f(e.target.nextElementSibling, e, true); } }); }; function isCtrlKey(e) { return e.ctrlKey || e.metaKey; } addEventListener(root, 'mouseover', function (e) { if ('' != refStyle.innerHTML) { refStyle.innerHTML = ''; } }); a('mouseover', function (a, e, c) { if (c) { e.target.style.cursor = "pointer"; } else if (a = idRx.exec(a.className)) { try { refStyle.innerHTML = 'pre.sf-dump .'+a[0]+'{background-color: #B729D9; color: #FFF !important; border-radius: 2px}'; } catch (e) { } } }); a('click', function (a, e, c) { if (/\bsf-dump-toggle\b/.test(a.className)) { e.preventDefault(); if (!toggle(a, isCtrlKey(e))) { var r = doc.getElementById(a.getAttribute('href').substr(1)), s = r.previousSibling, f = r.parentNode, t = a.parentNode; t.replaceChild(r, a); f.replaceChild(a, s); t.insertBefore(s, r); f = f.firstChild.nodeValue.match(indentRx); t = t.firstChild.nodeValue.match(indentRx); if (f && t && f[0] !== t[0]) { r.innerHTML = r.innerHTML.replace(new RegExp('^'+f[0].replace(rxEsc, '\\$1'), 'mg'), t[0]); } if ('sf-dump-compact' == r.className) { toggle(s, isCtrlKey(e)); } } if (c) { } else if (doc.getSelection) { try { doc.getSelection().removeAllRanges(); } catch (e) { doc.getSelection().empty(); } } else { doc.selection.empty(); } } else if (/\bsf-dump-str-toggle\b/.test(a.className)) { e.preventDefault(); e = a.parentNode.parentNode; e.className = e.className.replace(/sf-dump-str-(expand|collapse)/, a.parentNode.className); } }); elt = root.getElementsByTagName('SAMP'); len = elt.length; i = 0; while (i < len) t.push(elt[i++]); len = t.length; for (i = 0; i < len; ++i) { elt = t[i]; if ('SAMP' == elt.tagName) { elt.className = 'sf-dump-expanded'; a = elt.previousSibling || {}; if ('A' != a.tagName) { a = doc.createElement('A'); a.className = 'sf-dump-ref'; elt.parentNode.insertBefore(a, elt); } else { a.innerHTML += ' '; } a.title = (a.title ? a.title+'\n[' : '[')+keyHint+'+click] Expand all children'; a.innerHTML += '<span>&#9660;</span>'; a.className += ' sf-dump-toggle'; x = 1; if ('sf-dump' != elt.parentNode.className) { x += elt.parentNode.getAttribute('data-depth')/1; } elt.setAttribute('data-depth', x); if (x > options.maxDepth) { toggle(a); } } else if ('sf-dump-ref' == elt.className && (a = elt.getAttribute('href'))) { a = a.substr(1); elt.className += ' '+a; if (/[\[{]$/.test(elt.previousSibling.nodeValue)) { a = a != elt.nextSibling.id && doc.getElementById(a); try { s = a.nextSibling; elt.appendChild(a); s.parentNode.insertBefore(a, s); if (/^[@#]/.test(elt.innerHTML)) { elt.innerHTML += ' <span>&#9654;</span>'; } else { elt.innerHTML = '<span>&#9654;</span>'; elt.className = 'sf-dump-ref'; } elt.className += ' sf-dump-toggle'; } catch (e) { if ('&' == elt.innerHTML.charAt(0)) { elt.innerHTML = '&hellip;'; elt.className = 'sf-dump-ref'; } } } } } if (0 >= options.maxStringLength) { return; } try { elt = root.querySelectorAll('.sf-dump-str'); len = elt.length; i = 0; t = []; while (i < len) t.push(elt[i++]); len = t.length; for (i = 0; i < len; ++i) { elt = t[i]; s = elt.innerText || elt.textContent; x = s.length - options.maxStringLength; if (0 < x) { h = elt.innerHTML; elt[elt.innerText ? 'innerText' : 'textContent'] = s.substring(0, options.maxStringLength); elt.className += ' sf-dump-str-collapse'; elt.innerHTML = '<span class=sf-dump-str-collapse>'+h+'<a class="sf-dump-ref sf-dump-str-toggle" title="Collapse"> &#9664;</a></span>'+ '<span class=sf-dump-str-expand>'+elt.innerHTML+'<a class="sf-dump-ref sf-dump-str-toggle" title="'+x+' remaining characters"> &#9654;</a></span>'; } } } catch (e) { } }; })(document); </script><style> pre.sf-dump { display: block; white-space: pre; padding: 5px; } pre.sf-dump span { display: inline; } pre.sf-dump .sf-dump-compact { display: none; } pre.sf-dump abbr { text-decoration: none; border: none; cursor: help; } pre.sf-dump a { text-decoration: none; cursor: pointer; border: 0; outline: none; color: inherit; } pre.sf-dump .sf-dump-ellipsis { display: inline-block; overflow: visible; text-overflow: ellipsis; max-width: 5em; white-space: nowrap; overflow: hidden; vertical-align: top; } pre.sf-dump code { display:inline; padding:0; background:none; } .sf-dump-str-collapse .sf-dump-str-collapse { display: none; } .sf-dump-str-expand .sf-dump-str-expand { display: none; }pre.sf-dump, pre.sf-dump .sf-dump-default{background-color:#fff; color:#222; line-height:1.2em; font-weight:normal; font:12px Monaco, Consolas, monospace; word-wrap: break-word; white-space: pre-wrap; position:relative; z-index:100000}pre.sf-dump .sf-dump-num{color:#a71d5d}pre.sf-dump .sf-dump-const{color:#795da3}pre.sf-dump .sf-dump-str{color:#df5000}pre.sf-dump .sf-dump-cchr{color:#222}pre.sf-dump .sf-dump-note{color:#a71d5d}pre.sf-dump .sf-dump-ref{color:#a0a0a0}pre.sf-dump .sf-dump-public{color:#795da3}pre.sf-dump .sf-dump-protected{color:#795da3}pre.sf-dump .sf-dump-private{color:#795da3}pre.sf-dump .sf-dump-meta{color:#b729d9}pre.sf-dump .sf-dump-key{color:#df5000}pre.sf-dump .sf-dump-index{color:#a71d5d}</style><pre class=sf-dump id=sf-dump-1113542092 data-indent-pad="  ">"<span class=sf-dump-str title="6 characters">/pages</span>"
</pre><script>Sfdump("sf-dump-1113542092")</script>`

**Comment by unabomber87** [comment]
@itupdate119 so you must create /admin/media/upload under public folder

**Comment by itupdate119** [comment]
@unabomber87 : /admin/media/upload is url upload image. It's not folder that I want to upload image.
When upload image, I turn developer tool on, I see url response error 500 and message:
"ErrorException in VoyagerMediaController.php line 187:
Undefined variable: path".

**Comment by unabomber87** [comment]
@itupdate119 /admin/media/upload is the result of `$request->upload_path`
this result is passed to the function `$request->file->store($path, $options = [])`
wich store file on the specified path so you must have on your project this path or an Exception will occurs

**Comment by itupdate119** [comment]
@unabomber87 : Result of above comment is '/pages'.  /admin/media/upload is not folder. It is CONTROLLER. 'pages' folder has already exists at "storage/app/public/pages"

**Comment by unabomber87** [comment]
@itupdate119 i see and when you upload a file do you have an ajax response?

**Comment by itupdate119** [comment]
@unabomber87 
in vendor/tcg/voyager/src/Http/Controllers/VoyagerMediaController.php
add this line `dd($request->upload_path); `on line 177
Response is "/pages".
If not use `dd($request->upload_path); `. Response is error 500 and message:
`ErrorException in VoyagerMediaController.php line 187:
Undefined variable: path`

**Comment by unabomber87** [comment]
@itupdate119 sorry i don't know how to help you
