### ISSUE TITLE
I can't login  to voyager admin panel

### ISSUE THREAD

**Issue by ohana88** [thedevdojo/voyager#1164]
- Laravel Version: 5.3.#
- Voyager Version: v0.10.11
- PHP Version:5.6.4
- Database Driver & Version: mySql
 
#  Description :

I can not go to voyager admin panel, I can open http://.../admin/login, after login, always redirect to /

_my routes (web.php)_

Route::get('/', function () {  
return view('home');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Auth::routes();

**Comment by fletch3555** [comment]
sounds like your user is missing permissions (or doesn't have the correct role).

First, Voyager v0.10.* is outdated and no longer supported, so I recommend upgrading to v0.11.*.  There's a migration guide in our documentation that should be followed as there were a few backwards-incompatible changes.
Second, you can run the `php artisan voyager:admin` command to make sure the admin role exists, is associated with your role, and has all the correct permissions.

**Comment by ohana88** [comment]
@fletch3555  Thank you for help.

but I'm run the php  artisan voyager:admin  command it show this...

[Illuminate\Database\Eloquent\ModelNotFoundException]
  No query results for model [App\User].

**Comment by endrureza** [comment]
@fletch3555 i believe the command is not only `php artisan voyager:admin` but rather you add like this

```
php artisan voyager:admin you@email.com
```

or if you wish to create new account you might use this command

```
php artisan voyager:admin you@email.com --create
```

you may read the documentation here [Voyager Doc](https://the-control-group.github.io/voyager/docs/0.11/)

**Comment by olko404** [comment]
maybe someone can help me. I moved a website to hosting, (used a migration) and now cannot see voyager admin panel. when I trying to login - http://myhosting.in.ua/admin/login
I see 4 errors:

ErrorException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from `settings` where `key` = title limit 1) (View: /home/nameDB/myhosting.in.ua/laravel/vendor/tcg/voyager/resources/views/login.blade.php)

QueryException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from `settings` where `key` = title limit 1)

PDOException in PDOConnection.php line 47:
SQLSTATE[HY000] [2002] Connection timed out

PDOException in PDOConnection.php line 43:
SQLSTATE[HY000] [2002] Connection timed out

looks like does not exist setting table.

**Comment by fletch3555** [comment]
@endrureza, you're correct, that is the full usage of that command.  I was being intentionally generic with my directions in the hopes that others reading this would know enough to add `--help` and figure out what parameters they need to add.

**Comment by fletch3555** [comment]
@Ivanenko-O, yoyr issue is unrelated to this one.  In the future, please create your own issue when asking for help.

In this case, it looks like your database connection isn't set up properly.  Please check your .env to make sure it's correct for the remote host. I would recommend joining our slack group and posting in the #help channel for further support.

**Comment by Ivanenko-O** [comment]
@fletch3555 sorry me.  of course. #1170 - my issues
yes. it`s .env file. but can't understand which setting there should be. 
now its looks: 

APP_URL=http://localhost:8000

DB_CONNECTION=mysql
DB_HOST=127.0.0.1 
DB_PORT=3306
DB_DATABASE=tridentd_db
DB_USERNAME=tridentd_db
DB_PASSWORD=password

my database.php looks:

    'default' => env('DB_CONNECTION', 'mysql'),
 
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
//          'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'tridentd_db'),
            'username' => env('DB_USERNAME', 'tridentd_db'),
            'password' => env('DB_PASSWORD', 'password'),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],

**Comment by fletch3555** [comment]
Please join the slack chat or create your own issue to further support this.

**Comment by ohana88** [comment]
Thank you everyone for help !!
Now I create new Laravel project with Voyager last version and move file blade ,plugin,etc
it's work for me :)

**Comment by endrureza** [comment]
@fletch3555 then we closed this issue

**Comment by mrdulal** [comment]
I can't go on admin login section 

http://localhost/w/admin

I have install voyager according to the document exact. but when i go through above link 

`Sorry, the page you are looking for could not be found.
1/1
NotFoundHttpException in RouteCollection.php line 179:` 

Please someone help me.

**Comment by fletch3555** [comment]
@WordPressArt, this issue is closed. Please either open your own issue or (preferably) join the slack group to ask for help. We try to reserve github issues for actual bugs in the platform.

**Comment by minionsgomz** [comment]
adding a user but they can't login..what can i do?

**Comment by mrdulal** [comment]
@minionsgomz , this issue is closed. Please either open your own issue or (preferably) join the slack group to ask for help.

**Comment by OmidAhmadyani** [comment]
hi @ohana88 

i read all of your comments that have an isuue.

you cant see admin page in host.

but you solved it!

please help me to solve it too...

thank's...

**Comment by fletch3555** [comment]
As other comments already state, this issue is closed and has been for 8 months now. Please open your own issue if you're still having issues.
