### ISSUE TITLE
 how I get Google Analytics integrated on my website?

### ISSUE THREAD

**Issue by alihassan161820** [thedevdojo/voyager#1166]
![screenshot from 2017-04-23 16-55-55](https://cloud.githubusercontent.com/assets/22984580/25314870/01b8bbf0-284c-11e7-864e-62c41eed080a.png)
![screenshot from 2017-04-23 16-56-23](https://cloud.githubusercontent.com/assets/22984580/25314868/014ce380-284c-11e7-86da-91c97becdf6b.png)
![screenshot from 2017-04-23 16-58-50](https://cloud.githubusercontent.com/assets/22984580/25314869/015b5eec-284c-11e7-8c5f-dba30b2e33ba.png)

- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version:7
- Database Driver & Version:

### Description:
 how I get Google Analytics integrated on my website?
i made every thing in https://webman.io/blog/post/setup-google-analytics-for-laravel-voyager
but it doesn't appear

**Comment by alihassan161820** [comment]
![screenshot from 2017-04-23 16-55-55](https://cloud.githubusercontent.com/assets/22984580/25314543/8e680b06-2846-11e7-9d1c-2c782b568b15.png)
![screenshot from 2017-04-23 16-56-23](https://cloud.githubusercontent.com/assets/22984580/25314544/8e6df3c2-2846-11e7-9e5d-9f0f028e080f.png)
![screenshot from 2017-04-23 16-58-50](https://cloud.githubusercontent.com/assets/22984580/25314545/8e74203a-2846-11e7-8c9e-f93f859da41a.png)

**Comment by alihassan161820** [comment]
@marktopper any help ??

**Comment by endrureza** [comment]
@marktopper what website you registered in google analytics ?

**Comment by marktopper** [comment]
I don't use localhost. I registered my website on their. For example `https://webman.io`.

**Comment by marktopper** [comment]
I however bet that it should be `http://127.0.0.1`

**Comment by marktopper** [comment]
Also please open the Chrome Console and check out any errors there, thanks.

**Comment by endrureza** [comment]
@marktopper well, in my case i'm using a virtual host like http://awesome.dev, it works actually. I wonder why this one didn't work.

**Comment by marktopper** [comment]
Please open the Chrome Console and check out any errors there, thanks.

**Comment by alihassan161820** [comment]
![screenshot from 2017-04-24 13-29-21](https://cloud.githubusercontent.com/assets/22984580/25335158/1566c920-28f2-11e7-8e65-73fea2a968cf.png)
i got this error in chrome console what should i do ?

**Comment by marktopper** [comment]
That has nothing to do with either Google Analytics or Voyager.
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document
