### ISSUE TITLE
Blog post save/update is down, when using multilingual

### ISSUE THREAD

**Issue by d3n4** [thedevdojo/voyager#1167]
- Laravel Version: 5.4.19
- Voyager Version: 0.11.9
- PHP Version: 5.6-x64
- Database Driver & Version: MySQL 5.7-x64

### Description:
Got exception when trying to save blog post:

> Argument 2 passed to TCG\Voyager\Models\Post::setAttributeTranslations() must be of the type array, null given, called in E:\Projects\syteg.com\vendor\tcg\voyager\src\Traits\Translatable.php on line 308 and defined

### Steps To Reproduce:

1.  Turn on multilingual support in **config/voyager.php** on line **101**
`'bread' => false,` => `'bread' => true,`

2. Edit/Create any blog post:

> http://voyager.dev/admin/posts/2

3. Press **SAVE**

**Comment by akazorg** [comment]
Hi @d3n4, can you try the latest version? I've test it and it's working.
Also publish vendor assets, views and the **config** that was also updated.

I hope this works for you. Good luck!

**Comment by d3n4** [comment]
after update, works fine!

**Comment by akazorg** [comment]
Great! :)
