### ISSUE TITLE
New menu error

### ISSUE THREAD

**Issue by lukzpogi** [thedevdojo/voyager#117]
ErrorException in VoyagerBreadController.php line 45:
Undefined variable: dataTypeContent

I created a new menu under admin, and then after click the new menu this came out. Thanks in advance

**Comment by handiwijoyo** [comment]
@lukzpogi make sure you already created the BREAD at database page, and input URL menu match with the BREAD slug that you've created.

Say you've created `products` BREAD  and has slug named `products`, then in menu you could input `/admin/products` as menu URL to access the page.
