### ISSUE TITLE
can not login to admin panel on hosting 

### ISSUE THREAD

**Issue by olko404** [thedevdojo/voyager#1170]
- Laravel Version: 5.4.
- Voyager Version: 0.11.9
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.4

### Description:
 I moved a website to hosting, (used a migration) and now cannot see voyager admin panel. when I trying to login - http://myhosting.in.ua/admin/login
I see 4 errors:

ErrorException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from settings where key = title limit 1) (View: /home/nameDB/myhosting.in.ua/laravel/vendor/tcg/voyager/resources/views/login.blade.php)

QueryException in Connection.php line 647:
SQLSTATE[HY000] [2002] Connection timed out (SQL: select * from settings where key = title limit 1)

PDOException in PDOConnection.php line 47:
SQLSTATE[HY000] [2002] Connection timed out

PDOException in PDOConnection.php line 43:
SQLSTATE[HY000] [2002] Connection timed out
### Steps To Reproduce:
in a local development was another name of DB, user, password - I changed it in .env file. import of DB was successful.

**Comment by endrureza** [comment]
@Ivanenko-O it states connection timed out, which means perhaps your hosting database not good enough. Your local and your hosting have different settings i guess. You might want to take a look at your mysql version or its spec.

**Comment by olko404** [comment]
Thks. everything that I need - change  .env file at hosting.
instead
DB_HOST=127.0.0.1
to 
DB_HOST= "real host of my provider."
