### ISSUE TITLE
How to remove image uploaded (Edit function)

### ISSUE THREAD

**Issue by ohana88** [thedevdojo/voyager#1174]
- Laravel Version: 5.3.*
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version: mySql

### Description:

How to remove image uploaded when i want to edit
![55](https://cloud.githubusercontent.com/assets/17563661/25374171/8b385b1c-29c6-11e7-8ef5-e286ca24c592.PNG)

**Comment by endrureza** [comment]
@ohana88 what exactly you want to edit ? posts ? pages ? users ? and why you want to remove on edit, just choose another image and it will be replaced.

**Comment by ohana88** [comment]
@endrureza  I don't want to replace. but I want remove image

**Comment by endrureza** [comment]
@ohana88 in that case, you have to modify the code on edit. or you might want to remove manually from storage and then remove it from database.

**Comment by ohana88** [comment]
@endrureza  ok Thank you :)
