### ISSUE TITLE
Issue extending Page model

### ISSUE THREAD

**Issue by thestudio4** [thedevdojo/voyager#1175]
- Laravel Version: 5.4 
- Voyager Version: 0.11.9
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
I'm trying to extend the Page Model so I can add an additional relationship for pages (with Brand). However I get the error:
> Call to undefined relationship [brandId] on model [TCG\Voyager\Models\Page].

### Steps To Reproduce:
Add this to Page.php in the App folder:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends \TCG\Voyager\Models\Page
{
    //

    public function brandId()
    {
	    return $this->belongsTo('App\Brand');
	 }

}
```

And this in the Boot() section on the AppServiceProvider.php:
`Voyager::useModel('Page', Page::class);`

**Comment by akazorg** [comment]
Hi @thestudio4,

Did you updated BREAD and placed `App\Page` in the model name?
I'm not sure you need that entry of `Voyager::useModel('Page', Page::class)`.
