### ISSUE TITLE
Images Not working online

### ISSUE THREAD

**Issue by mohammed-elattar** [thedevdojo/voyager#1177]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
All images working fine on local
after i upload the images which were uploaded on local working fine 
but the online uploaded one not working and all images save only in the storage/app/public/
not in the public/storage

please help , i know it may be that symlink but how can i make it online however it's working fine local

**Comment by SUPERNOVI** [comment]
Hi,

It's almost certainly the symlink.

What you need to do is delete the shortcut or symlink in public folder and then run `php artisan storage:link`

That should fix it.

**Comment by ohana88** [comment]
same problem please help me 

@SUPERNOVI yes ! that work for run project on localhost but up to server online not work

**Comment by mohammed-elattar** [comment]
@SUPERNOVI  Yes, how can i run this command on shared hosting like bluehost ?

**Comment by SUPERNOVI** [comment]
@mohammed-elattar That's a good question. In your control panel can you see any reference to SSH? Maybe an java applet that lets you connect. If not you'd have to ask your hosting provider how you can gain access to do this. I suspect you'll be needing this kind of access for artisan and composer.

@ohana88 I saw your other issue regarding this, it looks to me to be a permission issue not a problem with the storage link. As you're seeing the 1KB files, it must be linking to the correct folder okay.

**Comment by fletch3555** [comment]
Voyager can create the symlink for you.  Just delete the existing file at `public/storage`, then log into voyager.  You should see a banner saying the symlink is broken (or something similar) with a button labeled "Fix It".  Clicking this button will either work, or will tell you that your host has `symlink()` disabled.  If the latter, your only option is to research how to create symlinks with your host (either by a google search or by contacting them directly and asking).  There is nothing Voyager can do  to help at that point.

I'll leave this open for now while you test my suggestions.

**Comment by SUPERNOVI** [comment]
@fletch3555 is right, I didn't consider that. Although you have to make sure you delete it first. I found that the fix button caused an error if one already existed.

I'm guessing you have the exact same thing I had, a windows shortcut on your local but need a symlink on the server.

**Comment by mohammed-elattar** [comment]
I already asked them for help regarding this issue and they told me that they can't help me
I tried to run command to make this symlink from cronjob but with no luck 
Please advice

**Comment by SUPERNOVI** [comment]
@mohammed-elattar did you read the latest replies RE using the button in admin alert.

**Comment by mohammed-elattar** [comment]
Ok i will try then tell you what happened .

**Comment by ohana88** [comment]
How to ...?
on server public/storage not symlink.
 Can i up symlink folder to ftp ?

**Comment by mohammed-elattar** [comment]
Thank you very much for the extra help you gave me so I could pass my issue . I really appreciated the time you spent with me.

**Comment by SUPERNOVI** [comment]
@ohana88  Hi, as far as I'm aware you can't upload a symlink. As said though if it's missing the admin will present you with a button to create it. However I'm not convinced this is your issue but by all means try it.

@mohammed-elattar You're welcome.

**Comment by ohana88** [comment]
@SUPERNOVI  my first project develop by voyager I can upload a symlink folder on server
but next project can't upload. I don't know why? 
![jghj](https://cloud.githubusercontent.com/assets/17563661/25466257/709e9a48-2b31-11e7-8d54-1ad14826444c.PNG)


Can I contact for chat with you? I'm from Thailand :)

**Comment by SUPERNOVI** [comment]
@ohana88 I'm pretty sure you are using Windows, as such your local version will be using a windows shortcut, this is not compatible with Linux. Linux uses symbolic links or symlinks.

I'm pretty sure that if you delete that windows shortcut via FTP and then visit your Voyager admin, you will be prompted with a button to re-create the storage link. If you press that button it should create a symbolic link the Linux way!

Hope that solves the issue for you.

**Comment by ohana88** [comment]
@SUPERNOVI  Thank you :)  
now I can solves the issue .. 
I delete folder public/storage and login to Voyager admin
I find button Fix it  when I click button fix it! on admin panel it work for me

**Comment by SUPERNOVI** [comment]
@ohana88 No problem, happy to help.
