### ISSUE TITLE
BelongsTo Order not working

### ISSUE THREAD

**Issue by nunomsh** [thedevdojo/voyager#1178]
- Laravel Version: 5.4
- Voyager Version: 0.11.7
- PHP Version: 7
- Database Driver & Version:

### Description:
Passing the orderBy to the relationship, does not order the list, keeps showing the order by id

### Steps To Reproduce:
I have relation books to Lists, so in the Books Model I have:
```
public function lista()
{
	return $this->belongsTo('App\lista')->orderBy('title');
}
```
But in the books view always shows the list dropdown order by ID.

**Comment by fletch3555** [comment]
I believe the issue you're having has to do with this line: https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/select_dropdown.blade.php#L32.

I'm guessing you don't have a `listaList()` method. I don't remember this being added, and it definitely isn't documented.  @marktopper, do you have any idea when this requirement was added, and why it doesn't just use the existing relationship method?

Edit: It was added with PR #1052.

**Comment by hotsaucejake** [comment]
Could we get brief documentation on the PR listed above?  @marktopper @DODMax 

I tried implementing myBlahIdList() with an orderBy and it results in a blank dropdown list.  I'm looking to order my dropdown values.

**Comment by DODMax** [comment]
So the basic is that you need to implement the fieldNameList function on your model and it will be used instead of Model::all() when rendering the dropdown.

For example, on a model with the `member_id` field:
```
public function memberIdList()
{
    return Member::where('active', 1)->orderBy('created_at')->get();
}
```

Note: I'm writing this in a rush and haven't really tested the example above.

**Comment by fletch3555** [comment]
Closing this as the question has been answered.  I believe this `*List` method still needs documentation.

**Comment by DODMax** [comment]
Added PR for the doc: https://github.com/the-control-group/voyager-site/pull/4

**Comment by fletch3555** [comment]
Perfect, thank you for that!

**Comment by StoneyEagle** [comment]
Add this to your model.
`use Illuminate\Database\Eloquent\Builder;`
```
protected static function boot()
    {
        parent::boot();
        static::addGlobalScope('order', function (Builder $builder) {
            $builder->orderBy('name', 'asc');
        });
}
```

**Comment by fletch3555** [comment]
This has been closed for 18 months... please don't comment on old issues
