### ISSUE TITLE
Relationship is not present during browse and read

### ISSUE THREAD

**Issue by Victor-emil** [thedevdojo/voyager#1179]
- Laravel Version: 5.4.19
- Voyager Version: 0.11.9
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.14

### Description:

I see that this problem has been addressed previously and was fixed. However I am still facing this issue. It works perfectly when I am creating or editing a new custom model, but during browse and read the integer from the database is shown. 
I am on the latest version of Laravel and Voyager (as of today). After upgrading I made sure to run the view:clear command. It did not work and the issue is still there. I am not overriding anything. I am using Laravel Voyager out of the box. Is there something I am doing wrong or is it a bug? It should be noted that I have been using Voyager since the beginning of 11 and upgraded a few times by just following the official guide. Is there anything I manually have to do in addition to what I already described? My admin role has all permissions for every model and every action.

**During Browse**

![during browse](https://cloud.githubusercontent.com/assets/8555068/25428272/a594bf32-2a75-11e7-9170-eefbf3a26b7c.png)

**During Read**

![during read](https://cloud.githubusercontent.com/assets/8555068/25428285/ad088f46-2a75-11e7-8aa8-f7f918c44a98.png)

**During Create**

![during create](https://cloud.githubusercontent.com/assets/8555068/25428290/b1a2f596-2a75-11e7-94e2-f1355bcefdcb.png)

**JSON data**

![json](https://cloud.githubusercontent.com/assets/8555068/25428435/22176f64-2a76-11e7-95ca-c27c74c6eeaf.png)

**Type**

![dropdown](https://cloud.githubusercontent.com/assets/8555068/25428458/371e1624-2a76-11e7-97ec-1b543685bc91.png)

**Relationship php**

![relationship](https://cloud.githubusercontent.com/assets/8555068/25428449/2eb8fc42-2a76-11e7-834d-6e8bcc708e81.png)

**Comment by DODMax** [comment]
I think this is Laravel returning the attribute value instead of the relationship because they have the same name. Maybe try renaming your column in DB?

**Comment by Victor-emil** [comment]
Thank you for the reply. Much appreciated. I just tried renaming the column from name to company_name to avoid conflicts. I also changed the JSON to reflect the change. Unfortunately It did not fix the problem and I'm still seeing the ID instead of the company name.

![db](https://cloud.githubusercontent.com/assets/8555068/25563523/c4382160-2d9d-11e7-9bee-dd2a821a8576.png)

![attributes](https://cloud.githubusercontent.com/assets/8555068/25563531/e2e7ab4e-2d9d-11e7-8cf8-71aadf58e7ca.png)


![company_name](https://cloud.githubusercontent.com/assets/8555068/25563475/34db23f0-2d9d-11e7-8ffc-9659cf185b03.png)

**Comment by hotsaucejake** [comment]
I fixed this by adding the key in my relationship.  

````
public function companyId()
{
   $this->belongsTo(Company::class, 'company_id');
}
````

**Comment by fletch3555** [comment]
Please use what @hotsaucejake suggests.  Adding a second parameter to your relationship call does seem to fix this.

**Comment by Victor-emil** [comment]
It did the trick. Thank you very much for the help.

**Comment by itelmenko** [comment]
Please, can you add it in documentation?
