### ISSUE TITLE
logged in going to admin/login

### ISSUE THREAD

**Issue by Domeman** [thedevdojo/voyager#118]
I was logged in as a normal user. While still logged in I tried to go to /admin/login and got route not found.

**Comment by handiwijoyo** [comment]
Only user with admin role can visit /admin page

**Comment by ghost** [comment]
@handiwijoyo if you are logged in as a default user and go to admin/login you can see the login page.

**Comment by kevinjon27** [comment]
How I can set normal user redirect to specific route?

**Comment by marktopper** [comment]
@kevinjon27: Seems unrelated to this issue. Please create another.
