### ISSUE TITLE
can't upload image on server

### ISSUE THREAD

**Issue by ohana88** [thedevdojo/voyager#1180]
- Laravel Version: 5.3.#
- Voyager Version:v0.11.9
- PHP Version: 5.6.4
- Database Driver & Version:mySql

### Description:

can't up folder ..public/storage to FTP .
 I try created public/storage and copy all folder,file image
But can't upload image on server >> www.xxxx.com/admin
![5tf](https://cloud.githubusercontent.com/assets/17563661/25432622/5a1f4c9a-2aaf-11e7-82e9-8e0f09090282.PNG)

one image upload in localhost but 3 image can't upload on server.

Please help me

**Comment by fletch3555** [comment]
Your versions are quite a bit out of date.  Voyager is up to v0.11.9 now.  Your issue may have been fixed between then and now.  Additionally, we recommend upgrading to Laravel 5.4 and PHP version 7 (or 7.1), but that's not necessarily required.

Once you've upgraded your Voyager version (please use the [migration guide](https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading-version-010-to-011)), please test again and let us know.  If you're still having issues, we can try a few other things.

**Comment by ohana88** [comment]
@fletch3555 oh I'm sorry I fotget. Voyager has been last version aleady :) 0.11.9

**Comment by AurelDragut** [comment]
@ohana88, you can do as i did:

i modified the public disk in the filesystems config.

`'public' => [
            'driver' => 'local',
            'root' => public_path('/storage'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],`

(i am not quite a fan of saving things into the /storage folder)

**Comment by endrureza** [comment]
@AurelDragut technically speaking, i totally agree with your way.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please create a new issue

**Comment by rewindthetrend** [comment]
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ], 
**this was the error for me
i check the file manager and changed the path config->filesystems**  
           'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage/app/public',
            'visibility' => 'public',
        ],
        **it works for me on godaddy server**
