### ISSUE TITLE
make table error !

### ISSUE THREAD

**Issue by Benyaminrmb** [thedevdojo/voyager#1182]
- Laravel Version: 5.4
- Voyager Version: 0.11.9
- PHP Version:7.0.10
- Database Driver & Version: 

### Description: Make Table 

i want to make a database like "Posts" in voyager .. but when i created and do options (Add BREAD to this table)

and open `/admin/["Name Of Table"]` -- i got this error ->
 `Sorry, the page you are looking for could not be found. !
`

How Can I Fix It ?

### Steps To Reproduce: Make Table

**Comment by endrureza** [comment]
@Benyaminrmb make sure the url is correct

**Comment by Benyaminrmb** [comment]
@endrureza .. Yes .. problem`s from url .. Thanks
