### ISSUE TITLE
[Feature]Add option not to rename uploaded files

### ISSUE THREAD

**Issue by taiwanleaftea** [thedevdojo/voyager#1184]
Now the voyager renames uploaded images as slug/monthyear/random.ext, which isn't useful. It would be nice to add any option or some way to customize what to do with such names.

BTW. If I want to change this behavior, should I edit Controller.php and ViyagerController.php?

**Comment by akazorg** [comment]
You need to extend `Controller.php` and maybe `VoyagerMediaController.php`.

**Comment by lancepioch** [comment]
Labels: feature

Close (pull request merged)
