### ISSUE TITLE
The images are shown broken

### ISSUE THREAD

**Issue by zkmark** [thedevdojo/voyager#1185]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.9
- PHP Version:7
- Database Driver & Version:

### Description:
The images are shown broken

### Steps To Reproduce:
After of te instalation with dummy

**Comment by endrureza** [comment]
@ztvMark make sure APP_URL in your .env is the same with the url you use right now.

**Comment by zkmark** [comment]
Yes work
Laravel development server started: <http://127.0.0.1:8000>

.env 
APP_URL=http://127.0.0.1:8000

**Comment by fletch3555** [comment]
@ztvMark, are you saying that this is now working correctly for you?  If so, please close the issue.
