### ISSUE TITLE
Upload image => can not read file from public directory

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#1187]
- Laravel Version: 5.4.
- Voyager Version: 0.11.10
- PHP Version: 5.4
- Database Driver & Version: MariaDB

### Description:
After upgrade to V.0.11.10 then I tried to upload the image, it does not allow me to read file from **public** directory.

### Step to produce:
In the uploading form, when I click save the information.

<img width="1243" alt="screen shot 2017-04-27 at 5 48 10 pm" src="https://cloud.githubusercontent.com/assets/1330852/25480183/e8fe57f4-2b71-11e7-9dd0-dbd64dccea86.png">

I tried again, then it show this message

<img width="1249" alt="screen shot 2017-04-27 at 5 52 32 pm" src="https://cloud.githubusercontent.com/assets/1330852/25480280/55f901ba-2b72-11e7-84fd-1a29a8c1fa7d.png">

**Comment by fletch3555** [comment]
Closing due to age.  There have been significant updates since v0.11.10.  If this is still an issue after the 1.0 release, please create a new issue
