### ISSUE TITLE
symlink in public, but not using public

### ISSUE THREAD

**Issue by michealmueller** [thedevdojo/voyager#1189]
- Laravel Version: 5.4
- Voyager Version: .11.10
- PHP Version:5.6
- Database Driver & Version:

### Description:
voyager auto creates a symlink in laravel/public/ , however with my installation my structure is this
public_html
|---laravel
|---index.php

the contents of my public folder are in the web root, not in the laravel folder, 

when the symlink is created on voyager:install it creates a laravel/public folder and puts the symlink there, what file do i have to change to make voyager understand that i need the symlink in the root outside of the laravel folder.

### Steps To Reproduce:
setup directory structure as described above and install voyager.

**Comment by fletch3555** [comment]
Your laravel install is non-standard and insecure (please try visiting `http://your.domain.com/laravel/.env` for proof).  Please look into "how to install laravel in shared hosting" for suggestions and best practices.
