### ISSUE TITLE
How to fix Font Awesome missing icon 

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#119]
The icon on breadcrumbs doesnt show, how can i fix it?
Thanks

**Comment by tahq69** [comment]
- have the same problem

**Comment by tnylea** [comment]
Thanks guys, added fix here: https://github.com/the-control-group/voyager/pull/56

Make sure to update your version of voyager and publish your assets again :)
https://the-control-group.github.io/voyager/docs/#voyager-docs-upgrade

**Comment by JuanVillagran** [comment]
Thanks @tnylea
