### ISSUE TITLE
Database->Create "Create migration for this table?" disabled

### ISSUE THREAD

**Issue by maximaexchen** [thedevdojo/voyager#1193]
- Laravel Version: 5.4
- Voyager Version: 0.11.9 
- PHP Version: 5.6.30
- Database Driver & Version: mysql 5.0.11

### Description:
By default. "Create migration for this table?" is set to disabled?

If I remove "disabled"in:
vendor/tcg/voyager/resources/views/tools/database/vue-components/database-table-editor.blade.php
Line 28
Then I am good to go to migrate.
Missed I something?

### Steps To Reproduce:
Fresh install

Regards from germany

**Comment by abdgad** [comment]
That option currently only generates a partial migration which is not useful. So it's disabled by default.
