### ISSUE TITLE
voyager:install throws 'TCG\Voyager\VoyagerServiceProvider' not found

### ISSUE THREAD

**Issue by evelop** [thedevdojo/voyager#12]
I followed the installation instructions for Laravel from https://laravel.com/docs/5.3 and created a new project by `composer create-project --prefer-dist laravel/laravel blog`

Inside the project folder I installed voyager as stated in the docs by requiring voyager `composer require tcg/voyager` and then adding voyager service provider and Image Intervention service provider to the config/app.php file in the `'providers' => [ array`

When I try to perform `php artisan voyager:install` I get `Class 'TCG\Voyager\VoyagerServiceProvider' not found`

**Comment by twmbx** [comment]
@evelop are you sure that you asked composer to install voyager? Check your `vendor` folder. for `tcg/voyager`

**Comment by Jeroen-G** [comment]
`composer du` might help.

**Comment by tnylea** [comment]
@evelop Yeah, it sounds like you may need to run `composer dump` and then try again. `voyager:install` should run that command but it may not have been able to do it all at once. Go ahead and try that and if it doesn't work let me know and I can assist further 👍 

Thanks!

**Comment by evelop** [comment]
@twoSeats the folder `tcg/voyager` exists inside the vendor folder

@Jeroen-G @tnylea When i run `composer dump` I get `Bus error` at the end. I missed that up to now.

I tried to run `composer update -vvv` but it also terminates with `Bus error` without any more hints (last output is the bus error). I am running this command inside an Homestead vagrant (on Windows) environment. I have no problems with composer in other projects.

I just tried it without Homestead on OSX with PHP7 installed and it was working without problems.

This problem seems unrelated to voyager, but any idea why composer wouldnt work in Homestead (on windows)?

Many thanks for the help!!!

**Comment by tnylea** [comment]
@evelop I've experienced something similar and I might try and make sure that you have the latest version of composer on your computer, perhaps `composer self-update` will resolve that.

But glad you got it to work inside of Homestead and thanks for submitting an issue 👍

**Comment by maxholy** [comment]
Hi dear.
you must enable execution file in php server. after that try again.
1)composer require tcg/voyager.
2)DB config
3)php artisan voyager:install --with-dummy
Good luck dear.

**Comment by abrhambas01** [comment]
How about when i remove the tcg voyager ? It says something like this error

**Comment by fletch3555** [comment]
@abrhambas01, this issue has been closed for nearly 5 months.  Please open a new issue with as much detail as you can provide.

**Comment by fuadrock** [comment]
same problem occurs to me but it happens because i run this `composer require tcg/voyager` outside of the project

**Comment by smartcoder01** [comment]
Probably happened many times, but please explain, I beg you.

Class 'TCG \ Voyager \ VoyagerServiceProvider' not found

I have the / vendor folder in the root, and I have a folder with in the laravel project which is in /public_html/site.сom/vendor.

There is an installation in / vendor to the root.

How to install a voyager in the c / laravel folder

thanks
