### ISSUE TITLE
Make number field configurable in BREAD

### ISSUE THREAD

**Issue by fletch3555** [thedevdojo/voyager#1200]
#1190 allows for `input type="number"` fields to accept decimals.  We should make this configurable in the BREAD config.

**Comment by handiwijoyo** [comment]
After testing on the latest Chrome (63.0.3239.132) and Firefox (57.0.4), it looks like the number field already accept decimals without step attribute.

Chrome:
![image](https://user-images.githubusercontent.com/4060094/34790760-5d2514d2-f675-11e7-863f-f0ff5f23f798.png)

Firefox
![image](https://user-images.githubusercontent.com/4060094/34790783-7766cb92-f675-11e7-8ce3-9f757f0bfdc8.png)


If this is an issue for you, try to update your browser.
