### ISSUE TITLE
Multiple user roles

### ISSUE THREAD

**Issue by dakala** [thedevdojo/voyager#1201]
- Laravel Version: 5.4.20
- Voyager Version: 0.11.10
- PHP Version: 5.6.30
- Database Driver & Version: 10.1.22-MariaDB 

### Description:

I've just discovered Voyager and I'm interested in using it. However, I'm having issues with multiple user roles. My existing application allows for a user to have multiple roles (implemented with Entrust - https://github.com/Zizaco/entrust) but it doesn't seem to be possible with Voyager as a "role_id" is stored against a user in the database.

I've noticed that the controllers that come with Voyager can be overridden in the config/voyager.php configuration file. Is there a way of doing a similar thing with existing models such as User and Role?

**Comment by fletch3555** [comment]
Voyager currently only supports Users belonging to a single Role.  You're welcome to try to override this by overriding the VoyagerUserController, User model, and Voyager's User view(s).  You may also need to try to override (or not use) other parts of voyager, including the authorization system and `can*()` helper methods, as they currently expect a single role.

Models are determined through Voyager's BREAD configuration.  If you "Add Bread" to a model though the Database editor within Voyager, it will show you a field where you can set the model (defaults to `App\[TableName]`).  Voyager's Controllers can also be overridden this way.

For further help, we recommend you join our Slack group (instructions in the Readme file).  There are a number of helpful and knowledgeable people on there, and many are willing to help.  One note though, please limit "help" requests to the #help channel.

**Comment by jamestylerpatton** [comment]
@dakala Were you able to get Voyager to install on top of your existing application with entrust?

**Comment by dakala** [comment]
Hi @jamestylerpatton. I didn't succeed and I couldn't make up my mind to refactor my application to use single role. Most importantly I haven't got time to make it work with multiple user roles. 

Is that (i.e. multiple user roles) something you're considering?

**Comment by jamestylerpatton** [comment]
No, I really only use one role per user anyways. I'm just trying to figure out what it's going to take for me to install Voyager on top of my existing app, and was wondering if someone else was able to make it work (easily) without removing entrust.

**Comment by spmsupun** [comment]
You can rename entrust table/model via config file, but still there are few errors
