### ISSUE TITLE
[Question] Installing Voyager on Laravel Spark?

### ISSUE THREAD

**Issue by ux-engineer** [thedevdojo/voyager#1202]
Does anyone have experience on using Voyager with Laravel Spark?

Or any thoughts on what needs to modified (if any) or possible problems?

One possible problem that came up when browsing this repo's issues was that Voyager doesn't yet seem to use Vue2. And no Laravel 5.4 support yet either. But for those I could use an earlier version of Spark for the time being.

Decided to post this here as I'm sure other people are and will be interested on this topic. I've already asked this question yesterday on Voyager's Slack group's help channel and Laravel's Slack group's spark channel – no answers yet. I'll keep this issue updated on my progress.

**Comment by ux-engineer** [comment]
So far the only minor problem that I've encountered has been that Voyager's migrations are dated since the beginning of 2016 where as Spark dates it's migrations at the time it was installed via Spark installer. Need to manually rename Spark migrations' times to predate Voyager's.

That is, if you did not run Spark's migrations before installing Voyager.

**Comment by ux-engineer** [comment]
No other issues encountered! Just need to add _use VoyagerUser;_ trait to User model, and modify/implement roles/permissions as needed by your project.

**Comment by vijaythecoder** [comment]
@envision I have a problem adding the trait. After adding the trait, I still have an error 
![image](https://user-images.githubusercontent.com/1809727/30900671-7e194c44-a382-11e7-9677-7f33d6d14e29.png)
it works fine if I try to extend the User in spark/src from voyagerUser but I will loose sparkUser properties. 
any help would be appreciated.

**Comment by fletch3555** [comment]
@vijaythecoder, this issue has been closed for 4 months.  Please open your own issue or ask in our Slack group if you need help.

**Comment by vijaythecoder** [comment]
sure thanks @fletch3555
