### ISSUE TITLE
Route not defined

### ISSUE THREAD

**Issue by jebog** [thedevdojo/voyager#1203]
- Laravel Version: 5.4.20
- Voyager Version: 0.11.10
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
Route [voyager.posts.index] not defined.  

### Steps To Reproduce:
php artisan voyager:install

**Comment by fletch3555** [comment]
Did you receive any kind of error when running `php artisan voyager:install`?

Please provide the contents of your `routes/web.xml` file, or the output of `php artisan route:list`

**Comment by jebog** [comment]
I receive the message only when running `php artisan voyager:install`
 i faked a route with required name to and run again the artisan, no error appeared

**Comment by AdrianKuriata** [comment]
You can try debug `Route::getRoutes()` and check exacly route name, what you are searching.

**Comment by fletch3555** [comment]
Closing since you seem to have it working and nobody else has reported the same behavior.

**Comment by hojgr** [comment]
I have just encountered the same issue. Created new application, required Voyager, added provider, added `\Schema::defaultStringLength(191);` to AppServiceProvider (because of my old database) and ran `php artisan voyager:install --with-dummy` and ended up with the error above.

    Dumping the autoloaded files and reloading all new files
    Adding Voyager routes to routes/web.php
    Seeding data into the database

                                            
      [InvalidArgumentException]                
      Route [voyager.posts.index] not defined.  

I re-ran the command again and there was no error and it finished successfuly.

**Comment by Aplear** [comment]
Maybe the prefix of the database is cause, if you have changed something there

**Comment by fletch3555** [comment]
@Aplear, this issue has been closed for nearly 2 months now.

**Comment by hojgr** [comment]
Still not fixed though. Clear Laravel install, add Voager and poof - error is there. Re-running it doesnt display/fixes it. But it's quite discouraging first impression.

I've tried to look for a fix to send a pull request but was not successful.

**Comment by num3thod** [comment]
Same issue here. Same versions. I'll take a shot at fixing it and report back.

**Comment by fletch3555** [comment]
@num3thod, you should first update to the most recent version to make sure this is still an issue there. Ideally, you would start a fresh project and use dev-master (or the 1.0 pre-release branch) for the Voyager version to make sure it hasn't already been fixed and not released yet.

**Comment by zzdjk6** [comment]
If you remove the `Post BREAD`, this issue appears. Re-run `php artisan voyager:install` fix it for me.

**Comment by bgiorgi** [comment]
For it was because routes have been cached.
`php artisan route:clear` fixed the issue

**Comment by alkhachatryan** [comment]
Sometimes you can have this issue by adding new bread.
As @bgiorgi mentioned - clear route cache or clear ALL cache
`php artisan optimize`
