### ISSUE TITLE
Data Type for Multi Select

### ISSUE THREAD

**Issue by adriangordon1231** [thedevdojo/voyager#1204]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.9
- PHP Version:
- Database Driver & Version: Mysql

### Description:

This is more of a question than an issue.

What data type should typically be used for storing values from multi select fields. I notice that the value of these fields are returned as an array, so I figured that JSON would be the correct fit. Unfortunately however, I am getting an "Array to string conversion" error when attempting to use it.

What approach should I take to store this kind of information in my database? Do I first need to convert the array to a JSON object via a mutator?

**Comment by adriangordon1231** [comment]
Ok, so I came up with my own solution. What I did was convert the data to a JSON string before saving it using a mutator. When reading the data however, I used an accessor to convert the JSON string to an array (so that It can be read in BREAD). 

This works, but I am not sure if it is the ideal approach. If it is, I would like to add it to the documentation as I am sure that there are other users struggling with this.  

Soo.. yea, someone let me know.

**Comment by fletch3555** [comment]
The select and multiselect fields were originally created to be used for relations, so an eloquent relation would be the best way to store that data. However, that's really dependant on what you're trying to store.

**Comment by adriangordon1231** [comment]
@fletch3555 The field does not seem to work with the JSON data type by default, and is not actually able to store multiple values without some massaging ... even for relations (hence the conversions that I had to make). What I am trying to figure out is what data type was the field intended to work with. 

e.g. obviously the number field is intended to work with integers and floats ... etc

**Comment by fletch3555** [comment]
Please review the docs on how many-to-many relations should work within voyager.  That is how it should be configured.

**Comment by adriangordon1231** [comment]
@fletch3555 I do not think you are understanding my question. The docs make no mention of the data type that should be used for the field (in the part where many to many relationships are discussed). It is ok though. I'll just close this issue since I have found my solution.
