### ISSUE TITLE
Error while trying BREAD my own table

### ISSUE THREAD

**Issue by abolinhas** [thedevdojo/voyager#1205]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version: Postgres

### Description:
I'm trying bread my custom table but i'm getting this error
```
DBALException in AbstractPlatform.php line 423:
Unknown database type geometry requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
in /home/betafile/public_html/gips/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php line 423
at AbstractPlatform->getDoctrineTypeMapping('geometry') in /home/betafile/public_html/gips/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php line 349
at PostgreSqlSchemaManager->_getPortableTableColumnDefinition(array('attnum' => 35, 'field' => 'the_geom', 'type' => 'geometry', 'complete_type' => 'geometry', 'domain_type' => null, 'domain_complete_type' => null, 'isnotnull' => false, 'pri' => null, 'default' => null, 'comment' => null)) in AbstractSchemaManager.php line 820
```

Seams that BREAD don't support geometry columns.
How can I fix it?

**Comment by akazorg** [comment]
We have support on MySql but not on Postgres. We need to create that data type.
Check [MySql example](https://github.com/the-control-group/voyager/tree/master/src/Database/Types/Mysql).

**Comment by abdgad** [comment]
I have checked Postgres [documentation](https://www.postgresql.org/docs/9.6/static/datatype-geometric.html), and I didn't see a `geometry` type. Can you please tell us the exact type of that column?

**Comment by abolinhas** [comment]
Geometry is like geography columns but more robust and is added by the postgis extension. 
https://postgis.net/docs/AddGeometryColumn.html

**Comment by abdgad** [comment]
For testing purposes, please go to: `/vendor/tcg/voyager/src/Database/Types/Postgresql/` and create a new file called `GeometryType.php`:
```php
<?php

namespace TCG\Voyager\Database\Types\Postgresql;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use TCG\Voyager\Database\Types\Type;

class GeometryType extends Type
{
    const NAME = 'geometry';

    public function getSQLDeclaration(array $field, AbstractPlatform $platform)
    {
        return 'geometry';
    }
}

```
Then go to the database manager, and try creating a new table with `geometry` column and tell us if that works.

**Comment by abolinhas** [comment]
Yes, it works
Thanks

**Comment by akazorg** [comment]
Great @abolinhas. :)

**Comment by akazorg** [comment]
I'll reopen this issue because it requires a PR for fixing this.
@abdgad @abolinhas any of you will submit it? Thanks
