### ISSUE TITLE
voyager maps

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1206]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
can we create a dynamic maps in laravel voyager admin panel from which we can send the latitute and longtitue and address of specific location into database and then display it on my website from data base can some body help me?

**Comment by fletch3555** [comment]
Yes you can, using the features voyager provides, as well as some basic laravel functionality.  I can't walk you through doing it completely, and doing so would be an improper use of the issues feature of github.

Please look through the documentation of laravel and voyager and try to figure it out.  If you have specific questions along the way, you're welcome to join our slack group and ask in the #help channel.

**Comment by aamirkhan37557** [comment]
can you send me the link of voyager maps step by step?

**Comment by aamirkhan37557** [comment]
there is no option for any types of maps in voyager package
