### ISSUE TITLE
voyager maps

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#1209]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
how to create maps in laravel voyager admin and then how to display it on my website there is no option for maps in voayger docs

**Comment by fletch3555** [comment]
Please do not open duplicate issues (reference: #1206). Instead, you should follow my suggestions in your other issue.
