### ISSUE TITLE
[Improvement] Consider removing "eval" calls on VoyagerBreadController

### ISSUE THREAD

**Issue by agustindidiego** [thedevdojo/voyager#121]
Please consider removing "eval" calls like:
```php
eval('$dataTypeContent = ' . $dataType->model_name . '::find(' . $id . ');');
```
with the use of "class_exists" and "call_user_func", ex:
```php
$dataTypeContent = "";
if(class_exists($dataType->model_name)) {
        $dataTypeContent = call_user_func(array($dataType->model_name, 'find'), $id);
}
```
or creating a new instance of the model:
```php
$model = new $dataType->model_name;
$dataTypeContent = $model::find($id);
```

**Comment by maiorano84** [comment]
I had PR #60 sitting for six days that addressed this issue without any indication of the change ever being implemented. By that point, the branch had gone stale and I closed the issue. I can reopen, or redo the branch (there weren't many changes).

Would any maintainer/author comment on this? I cannot think of any compelling reason why Eval should be used anywhere in this codebase. Its use is entirely avoidable, and unless there's something I'm missing, we should consider its use to be a security hole.

**Comment by fletch3555** [comment]
@maiorano84 I recommend reopening it.  I know @tnylea has been pretty busy.

I'd say this issue can be closed as a dupe of PR #60

**Comment by maiorano84** [comment]
I'm in the process of creating a new branch. PR #60 was pretty deeply flawed, in that the database evaluations being performed were being chained together. While calling single methods from a variable or `call_user_func` is easy enough, the closed PR did not take into account the chained calls and was erroring out in the database side. I'll follow up once I have this addressed.

**Comment by agustindidiego** [comment]
Great! I wasn't aware of PR#60
Closing as a dupe of #60
