### ISSUE TITLE
Error making BREAD

### ISSUE THREAD

**Issue by ikiru** [thedevdojo/voyager#1212]
Laravel Version: 5.4.20
Voyager Version: 0.11.10
PHP Version: 7.1
Database Driver & Version:

### Description:
just started to get this error

Saving Failed Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'order clause' (SQL: select * from `data_rows` where `data_rows`.`data_type_id` = 53 and `data_rows`.`data_type_id` is not null and (`field` = id) order by `order` asc limit 1)

### Steps To Reproduce:
Everytime I try to create a BREAD

**Comment by akazorg** [comment]
Hi. The `order` field is missing on `data_types` table.

Please run the following commands in order to add the new order column to your existing application.
```
php artisan vendor:publish --tag=migrations --provider='TCG\Voyager\VoyagerServiceProvider'
php artisan migrate
```
Notes from [Release 0.11.10](https://github.com/the-control-group/voyager/releases).

**Comment by ikiru** [comment]
Thank you

**Comment by wqqas1** [comment]
This error is still there. I just installed and this was never merged to the master branch

**Comment by akazorg** [comment]
@wqqas1 make sure you have run the migrations.

**Comment by kvlknctk** [comment]
I like this. Its Completed.
