### ISSUE TITLE
[ReflectionException] Class TCG\Voyager\FormFields\imageHandler does not exist 

### ISSUE THREAD

**Issue by karpuzkan** [thedevdojo/voyager#1215]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.10
- PHP Version: 7.0.15
- Database Driver & Version:

Hi,
I got 
ReflectionException 
Class TCG\Voyager\FormFields\imageHandler does not exist  

error when i try `voyager:install` or anything related with artisan. 
Already `composer dump-autoload && php artisan cache:clear && php artisan optimize` command tried...
its a clean laravel install and everything seems work well.

hope to use ur package soon.

**Comment by murat** [comment]
Same issue is here. I can't found imageHandler class(with case sensitive) anywhere. Could it be a composer script bug?

**Comment by fletch3555** [comment]
It should exist at `vendor/tcg/voyager/src/FormFields/ImageHandler.php`.  Does it not?  If not, please delete the `vendor/tcg/voyager` directory and run `composer update`.

If it does exist, please run `composer dump-autoload` and try again.

**Comment by karpuzkan** [comment]
Hello again,
I tried ur suggestions before and tried again now but no luck. 
Now i changed uppercase i's with lowercases in "image" word as;

TCG\Voyager\FormFields\ImageHandler -> TCG\Voyager\FormFields\imageHandler
TCG\Voyager\FormFields\MultipleImagesHandler -> TCG\Voyager\FormFields\MultipleimagesHandler

and now it works. Is there any other solution?

**Comment by fletch3555** [comment]
Are you on windows?  I'm guessing yes.

Windows doesn't care about case.  I'm willing to bet that by switching to lowercase, you somehow tricked php into finding the class(es).  If this is the case, then a `composer dump-autoload` should work as well.

**Comment by karpuzkan** [comment]
I'm on Ubuntu 16.04.

One thing i see now is muratbsts has same issue and we both Turkish. We have 4 "i" letter in turkish keyboard as "i", "İ", "ı" and "I". Maybe our system language cause this error?

**Comment by fletch3555** [comment]
Hmm... that's possible.  The files are named with the capitalized roman "i" (ASCII character # 73, or 0x49, for reference).  You should make sure you're using that character.

**Comment by murat** [comment]
Hi @karpuzkan @fletch3555 . I've using two different OS as macOs and Fedora. My project was made on macOS, and I'm developing on Fedora currently. I think there is a bug related to composer dump-auto and case sensitivity. macOs and Fedora has different file systems.

**Comment by karpuzkan** [comment]
Hello again,
Since you remind me that problem, I gave a second chance to Voyager and voila! No problem or error! As u mentioned maybe its composer maybe not... Anyway happy coding.

**Comment by fletch3555** [comment]
@muratbsts, if it's a composer problem, it's not a Voyager problem.  Also, it's likely unrelated to this issue, but you'd need to provide much more detail than that for help.  If you still have an issue, please either create your own issue or join our Slack group.

**Comment by murat** [comment]
@fletch3555 yep. It's not a Voyager problem. You can close this issue if you want. Best regards...

**Comment by yanekyuk** [comment]
It's not an issue with Voyager, it's caused by Turkish locale where there is ```i```, ```I``` and ```İ``` and ```ı```. Can be fixed simply by renaming the files ```ImageHandler.php``` and ```MultipleImagesHandler.php``` to ```imageHandler.php``` and ```MultipleimagesHandler.php``` in ```vendor/tcg/voyager/src/FormFields/```

**Comment by uurtech** [comment]
in linux change system lang to english is easy for future problems
