### ISSUE TITLE
I can't browse admin section or any section

### ISSUE THREAD

**Issue by allaghi** [thedevdojo/voyager#1217]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.10
- PHP Version:
- Database Driver & Version:

I did all steps to install voyager , the only thing that I can browse is login page even when I added 
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

if I try to browse different page it gives me the welcome page, which is laravel default page ?

**Comment by fletch3555** [comment]
Did you add the "admin" role to your user?  You can do so with `php artisan voyager:admin [user's email]`

**Comment by allaghi** [comment]
You mean in role table ? yes I did but nothing new same story and issue

**Comment by Neogene** [comment]
Me too, same problem it redirects to the welcome page, user was granted (i checked roles table too).

Update: 

Adding into web.php : Auth::routes();
Running: php artisan make:auth
Logged again, seems to be the correct way to procede.

I managed to access to http://localhost:8000/home now which shows 'you are log in'. but still not able to go to the backend.

Update: uninstalled, reinstalled, working!
Update again, not working anymore!!!

**Comment by Neogene** [comment]
Ok seems that if add a model/migration i have to do again the command `php artisan voyager:install` after that it works, but WORKING: it LOSTS ALL THE CONFIGURATIONS. 

Before re-installing voyager after model adding, not working:
[https://gist.github.com/Neogene/f187cdff248205ea1600e0d4bab2be8e](url)

After (working):
[https://gist.github.com/Neogene/07113a7c72575ce838c5f0383099279a](url)

**Comment by allaghi** [comment]
Did you solve the issue  @Neogene ?

**Comment by Neogene** [comment]
The only solution i found after a day is to create a gulp file which refreshes the whole project rollbacking all and starting the migration again and doing again the php artisan voyager:install.

**Comment by donmbelembe** [comment]
after **php artisan voyager:install** if you get this error **The process "composer dump-autoload" exceeded the timeout of 60 seconds.** then your installation is not complete.
i couldn't not also access my dashboard until i run **php artisan optimize** then **php artisan voyager:install** now everything work fine. hope it help

**Comment by fletch3555** [comment]
Closing for now due to age.  If this is still an issue after the 1.0 release, please open a new issue
