### ISSUE TITLE
Question - Categorie slug is not translable ?

### ISSUE THREAD

**Issue by YannikFirre** [thedevdojo/voyager#1218]
Hello,

i test this tool but i note that the slug is not a translable fields ? 

It's planned to do that ?

**Comment by akazorg** [comment]
Hi @InfinityWebMe.
At the moment is not translatable, but I will make it. I'll ping your nick when it's up.

**Comment by YannikFirre** [comment]
Thanks 👍

**Comment by YannikFirre** [comment]
@akazorg  A another question, when i create a new bread. How i define which fields is translatable ?

**Comment by akazorg** [comment]
Hi @InfinityWebMe, translatable fields are defined at Model, check out [Page Model](https://github.com/the-control-group/voyager/blob/master/src/Models/Page.php#L13).

**Comment by YannikFirre** [comment]
Thanks again :D

**Comment by akazorg** [comment]
You're welcome! :)

**Comment by akazorg** [comment]
Ping @InfinityWebMe. 
PR #1282.
