### ISSUE TITLE
Dev question regarding authentication 

### ISSUE THREAD

**Issue by mgreiner28** [thedevdojo/voyager#1220]
- Laravel Version: 5
- Voyager Version: 
- PHP Version:
- Database Driver & 

Hello, dev question..

Is there a way to allow to restrict access to CRUD entries to only the user that created this entries??

Thank you

**Comment by fletch3555** [comment]
Only if you override the controller(s) and add that functionality yourself.  Voyager's permissions system currently does not allow such fine-grained control.
