### ISSUE TITLE
updated by

### ISSUE THREAD

**Issue by abolinhas** [thedevdojo/voyager#1221]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version: Postgres

Hi,
In my table I have a column called updated_at (timestamp) and every time that I made any change in any record of this table the column updated_at is automatically updated with the current time.

Now I want create the same behavior but with the name of user that update the record, I create a column named updated_by (text), now how can I make this procedure, to update this column with the name of user every time that change a record?

Best regards

**Comment by fletch3555** [comment]
That functionality is built into laravel, not voyager.  Help like this is best suited for the #help channel of our slack group (instructions to join exist in our readme)
