### ISSUE TITLE
ERROR !! > installing it with the dummy data run

### ISSUE THREAD

**Issue by ohana88** [thedevdojo/voyager#1222]
- Laravel Version: 5.3
- Voyager Version: 0.11.10
- PHP Version: 5.6.4
- Database Driver & Version: Mysql
-local server :Apache /Wamp

### Description:

I'm run  php artisan voyager:install --with-dummy
have error

![id](https://cloud.githubusercontent.com/assets/17563661/25650806/974306b6-3009-11e7-954e-709d8106db6e.PNG)

can't create migration

**Comment by sarath-c-sandwich** [comment]
@ohana88  that is the issue of Laravel 5.4, check it out. This could fix the problem
https://laravel-news.com/laravel-5-4-key-too-long-error

If you're using MySQL v5.7.7 or higher, there is no problem happen :)

**Comment by Dmarthaller** [comment]
I have encountered the same problem. I'm running MySQL v5.7.14 and I have tried changing the default string length as outline in the link mentioned above and now I run into the same problem while migrating the translations tables while creating the index translations_table_name_column_name_foreight_key_local_unique with the following fields table_name column_name foreign_key locale

**Comment by Dmarthaller** [comment]
I realized that my default database engine was MyISAM, when I changed this to INNODB the problem went away.

**Comment by ohana88** [comment]
@uchsarath I using laravel 5.3  and mysql 5.7.14
I tried fix and follow the issue off laravel 5.4  it's not work
I think I use laravel 5.3 not 5.4

**Comment by fletch3555** [comment]
This has been covered in numerous other issues.  Closing for now.
