### ISSUE TITLE
how can i choose which migrations voyager create when i install it because i have existing database which include users and category table 

### ISSUE THREAD

**Issue by alihassan161820** [thedevdojo/voyager#1225]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version:7
- Database Driver & Version:

**Comment by fletch3555** [comment]
You can "choose" them by doing a `artisan vendor:publish --tag=migrations`, then deleting/modifying the ones you need to, prior to `artisan voyager:install`

**Comment by akazorg** [comment]
For using a different table name other then `users` it's complicated because Voyager have references to that table name.
This will be fixed meanwhile with table_prefixes update.

**Comment by lancepioch** [comment]
Labels: in progress, feature

**Comment by fletch3555** [comment]
Voyager 1.0 provides a method to make Voyager work with an existing User model (docs in progress).  Closing.
