### ISSUE TITLE
ErrorException in Controller.php line 178: Undefined variable: resize_width

### ISSUE THREAD

**Issue by nunoarmada** [thedevdojo/voyager#1226]
- Laravel Version: 5.4.21
- Voyager Version: 0.11.10
- PHP Version: 7.0

### Description:
After create a BREAD,  when i try to insert something i get this error:

<img width="1001" alt="screen shot 2017-05-04 at 17 54 38" src="https://cloud.githubusercontent.com/assets/9868137/25715937/354a09e0-30f5-11e7-93f6-d58aa0d8a693.png">

**Comment by siryur** [comment]
Hi @raidenn this is a bug from the new version of Voyager (0.11.10)

When inserting multiple_images type, there is a bug on the code where, at least, the $resize_width and the $resize_height variables are not declared.

Wait for the "bug correction version", use custom code or use a previous version...

in my case I added the following code before that specific line:
```
if (isset($options->resize) && isset($options->resize->width) && isset($options->resize->height)) {
          $resize_width = $options->resize->width;
          $resize_height = $options->resize->height;
} else {
          $resize_width = 1800;
          $resize_height = null;
}
```

**Comment by sarath-c-sandwich** [comment]
The style for thumbnail is also broken in dashboard. Images show in large size.

**Comment by imknight** [comment]
I have send in pull request #1214  for this and it still pending

**Comment by fredhy** [comment]
Exactly @siryur this my alternative solution: [ HERE ](https://github.com/the-control-group/voyager/issues/1264)
Thanks @siryur :+1:

**Comment by laravelish** [comment]
Ok i just wasted 24 hours on this bullshit voyager, there's too much bugs... i will never buy or use anything from devdojo anymore

**Comment by ghost** [comment]
@siryur so you edited the vendor file ? `vendor/tcg/voyager/src/Http/Controllers/Controller.php`

**Comment by idchlife** [comment]
Is there a fix yet? 0.11.14 version

Without multiple_images details field error exists, also with resize width and height null - also exists.

**Comment by fletch3555** [comment]
Yes, the fix was merged into master a while back. We haven't released it yet for a number of reasons, but it will be included in v1.0.  I caution you against running dev-master right now as it's unstable while we prepare for 1.0

**Comment by lancepioch** [comment]
Labels: bug

Close (bug no longer occurs in 1.0)

**Comment by emptynick** [comment]
Can be closed
