### ISSUE TITLE
Multiple Images, delete 1st image & update - then store data stdClass Object

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#1227]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.10
- Database Driver & Version: Postgre

### Description:
Create new item, images store as array of String,
<img width="1032" alt="screen shot 2017-05-05 at 10 36 21 am" src="https://cloud.githubusercontent.com/assets/1330852/25732956/f5e348cc-317e-11e7-886a-7e6f1874a42a.png">

After delete the 1st image from the multiple image field -> it stores data as JSON with Key Value Pair.
<img width="798" alt="screen shot 2017-05-05 at 10 37 36 am" src="https://cloud.githubusercontent.com/assets/1330852/25732961/007c3f8c-317f-11e7-9b5e-649e7d79d435.png">

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by fletch3555** [comment]
Please test in 1.0 and reopen if necessary
