### ISSUE TITLE
Class 'TCG\Voyager\VoyagerServiceProvider' not found

### ISSUE THREAD

**Issue by gonzalovidal** [thedevdojo/voyager#1235]
- Laravel Version: v5.4.22
- Voyager Version: "tcg/voyager": "^0.11.10"
- PHP Version: 5.6.30
- Database Driver & Version: MySQL Server 5.1

### Description: I got lot head pain with voyager installation guys, i am new on voyager and laravel and Y try to install by console, but when i go to execute this lines " php artisan voyager:install --with-dummy
" or without dummy, i got the same bug....

 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'TCG\Voyager\VoyagerServiceProvider' not found

### Steps To Reproduce: I did insert the provider::Class 
        /*
         * Package Service Providers...
         */
        TCG\Voyager\VoyagerServiceProvider::class,
        Laravel\Tinker\TinkerServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,        
        /*
I also dia I "clean cache" but nothing, Now i do not what else to do... i where looking for forum but 
nothing happen jet...
thanks a lot for your kind reply guys, by the way you´r genius-.. 

Gonzalo

**Comment by fletch3555** [comment]
This may sound like a stupid questions, but did you do `composer require tcg/voyager` first?  If so, please make sure it succeeded (you can check for the presence of `/vendor/tcg/voyager/src/VoyagerServiceProvider.php`).  If the file exists, then please try running `php composer dump-autoload` and trying again.

**Comment by zeroiszero** [comment]
@fletch3555 , i got the error too......with laravel 5.4...

VoyagerServiceProvider.php file exist.

Voyager service provider added to the config/app.php


UPDATE:
reinstall laravel fix the issue

**Comment by nanadjei** [comment]
Am getting the same error after a fresh laravel 5.5 installation

**Comment by lancepioch** [comment]
Labels: invalid

Close (user error)

**Comment by emptynick** [comment]
This can be closed

**Comment by vaibhawW** [comment]
I also faced the same issue, resolved it by removing voyager from User.php
replaced 
`class User extends \TCG\Voyager\Models\User`
with 
`class User extends Authenticatable`
If possible please correct this on removing voyager

**Comment by smartcoder01** [comment]
Probably happened many times, but please explain, I beg you.

Class 'TCG \ Voyager \ VoyagerServiceProvider' not found

I have the / vendor folder in the root, and I have a folder with in the laravel project which is in /public_html/site.сom/vendor.

There is an installation in / vendor to the root.

How to install a voyager in the c / laravel folder

thanks

**Comment by fletch3555** [comment]
@smartcoder01 your issue sounds more like a laravel install problem than anything to do with Voyager. Please don't comment on closed issues, especially when they've been closed for so long (over 18 months in this case).

Please ask for help on slack.
