### ISSUE TITLE
There is an error message when upload other format files, eg .doc, .pdf

### ISSUE THREAD

**Issue by minhphuc429** [thedevdojo/voyager#1236]
- Laravel Version: 5.4.22
- Voyager Version: 0.11.10
- PHP Version: 7.1
- Database Driver & Version:

### Description:
http://i.imgur.com/RyZIs35.png

**Comment by fletch3555** [comment]
The media upload tool currently only supports image types (JPG, PNG, etc).  This is a desired feature, so it's definitely on our radar.

**Comment by lancepioch** [comment]
Labels: feature

**Comment by davodavodavo3** [comment]
Close this issue. Media manager upload everything
