### ISSUE TITLE
Update documentation to include warning for HTTPS users

### ISSUE THREAD

**Issue by fletch3555** [thedevdojo/voyager#1239]
**Symptom:**
When visiting your site with HTTPS, images within Voyager fail to load.

**Cause:**
Images urls are generated by Voyager using `Storage::disk(config('voyager.storage.disk'))->url($file)`.  If `voyager.storage.disk` is set to `public`, and the `public` disk is the default from Laravel, then the `url` property in the disk configuation is set to `'url' => env('APP_URL').'/storage',`, which uses the non-HTTPS `APP_URL` value to build an absolute url to the image.

**Solution:**
If you remove `env('APP_URL').` from the `public` disk configuration, then it will render a domain-relative url, which will always use the current domain and protocol.

As an aside, if you need a fully-qualified URL, you could wrap the call to `Voyager::image('...')` with `asset()`, so it would be `asset(Voyager::image('...'))`.  This will return a the current protocol, domain, and correct path to that image

**Comment by sourcecube** [comment]
Should this live in https://github.com/the-control-group/voyager-site/tree/master/docs/0.11 ?

**Comment by tnylea** [comment]
@fletch3555 Thanks man. Feel free to ping me privately on slack if you need me to update anything else in the docs.

I've added this to the docs in a troubleshooting section down at the bottom: https://laravelvoyager.com/docs/0.11/#troubleshooting

Thanks again 👍
