### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Nagendra1421** [thedevdojo/voyager#124]
I created a new laravel 5.3 project and follows the same step for installing this package but when i go to my browser and tried to login it says Sorry, the page you are looking for could not be found. 
I also checked the route file there was no routes for login or register page.
![sketch](https://cloud.githubusercontent.com/assets/10511483/20089348/509bae58-a5ac-11e6-8f44-ebea0a38db1c.png)

**Comment by fletch3555** [comment]
Did you add the service providers to your app config?  Looks like it's not sourcing the routes.

**Comment by Nagendra1421** [comment]
@fletch3555  Yes i did but when i opened routes file there was only one route for homecontroller and nothing else. 13 tables are migrated into the database. I am installing this package in laravel 5.3. Please tell me what to do for installing this project.

**Comment by ThinkDevStudios** [comment]
I am also having problems. It does not seem to seed the database. When i log in to the admin area. admin@admin.com and password is not working. Checked the database and found out that there is not user on the database

**Comment by marktopper** [comment]
Is this still a issue, I might want to dig into it.

**Comment by Nagendra1421** [comment]
problem solved working fine now
