### ISSUE TITLE
Save Thumbnails in Database

### ISSUE THREAD

**Issue by emptynick** [thedevdojo/voyager#1241]
The filenames of generated thumbnails are currently not stored in the database,
and are only accessible by rewriting the filename.
This is somewhat suboptimal.
If we could save the names in a json-style in the database we could access them like `$image['small']`.
Another advantage is that we could use another filename for each thumbnail so the user can't access the original "high-resolution" image by just removing the -small part.
Also this would be useful if there was a watermark-feature which would keep the original non-watermarked version.

**Comment by lancepioch** [comment]
Labels: feature
