### ISSUE TITLE
General User unable to edit their profile

### ISSUE THREAD

**Issue by matt-shirey** [thedevdojo/voyager#1243]
- Laravel Version: 5.4 (latest)
- Voyager Version: 0.11.10
- PHP Version: 7.0.15
- Database Driver & Version: MySQL

### Description:
I've noticed that a user can not edit their own profile.  I tried giving them Edit Users rights but when I do that, they can change he user id in the URL and edit anyone's profile.

### Steps To Reproduce:
1.  Assign default user role and then login as user.  You can view their profile but not edit.
2. Add the 'Edit Users' permission to the user role and then login as that user again.

**Comment by fletch3555** [comment]
This has been reported on multiple occasions.  It's admittedly low on our priority list for a couple reasons.  Primarily, Voyager is **not** intended to be a CMS, and therefore not intended for use by general members of your site.  If you want users to be able to do that, then you will need to add custom functionality.  Specifically, you can add a new controller/view with logic to test the permissions however you'd like.

**Comment by matt-shirey** [comment]
Not a problem.  I will fork the repo and add this functionality to it.

**Comment by fletch3555** [comment]
You shouldn't need to fork voyager to do that.  Just override the view and/or controller, and add the functionality yourself. in your project.  Forking Voyager to update it yourself would make it very difficult to update later on.

**Comment by matt-shirey** [comment]
I was only going to fork it so that anyone else looking for the functionality could already have it.

**Comment by matt-shirey** [comment]
I actually just ended up modifying the config/voyager.php file to remove the profile entirely.  Thanks for the help.
