### ISSUE TITLE
File manager/gallery with CKEditor and TinyMCE support.

### ISSUE THREAD

**Issue by minhphuc429** [thedevdojo/voyager#1245]
### Description:
Can't select images from file manager in CKEditor and TinyMCE

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by handiwijoyo** [comment]
I can confirm this is working in `1.0`

![image](https://user-images.githubusercontent.com/4060094/34669227-50a65ad2-f4a3-11e7-8240-958ac19dd5d4.png)
