### ISSUE TITLE
FatalThrowableError in VoyagerServiceProvider.php line 64

### ISSUE THREAD

**Issue by alvaropeso97** [thedevdojo/voyager#1248]
- Laravel Version: 2.3
- Voyager Version: Latest
- PHP Version: 7.0.1
- Database Driver & Version: Mysql

### Description:
FatalThrowableError in VoyagerServiceProvider.php line 64:
Class 'App\User' not found

### Steps To Reproduce:
I installed voyager and when i try to enter my web it displays that error

**Comment by emptynick** [comment]
Is the Authentication installed in Laravel?
If not use `php artisan make:auth` and `php artisan migrate`.
https://laravel.com/docs/5.4/authentication

**Comment by fletch3555** [comment]
You don't even really NEED to run `artisan make:auth`.  All you need is to create a User model file.

**Comment by ariews** [comment]
Hi, I'm facing same issue with @alvaropeso97 , I don't have `App\User`, this model moved to `App\Models\User`. Manually copy `vendor/tcg/voyager/publishable/config/voyager.php` to `config/voyager.php` and set user.namespace to `'namespace' => App\Models\User::class`,  resolved this issue

**Comment by fletch3555** [comment]
Closing due to age. If this is still an issue after the 1.0 release, please create a new issue
