### ISSUE TITLE
There are no commands defined

### ISSUE THREAD

**Issue by zAbdelAziz** [thedevdojo/voyager#1253]
- Laravel Version: 5.4.23
- Voyager Version: 0.11.10
- PHP Version: 7.1.1
- Database Driver & Version: MySQL, 4.6.5.2

### Description:
In the last step for Installation of Voyager, while running
`php artisan voyager:install` or `php artisan voyager:install --with-dummy`
an error occurs
'  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "voyager" namespace.'

I've tried most of the solutions provided before, nothing seems to work as a solution, also to cut is short, I've already added a provider, ran on a clear cache, autodumped, and nothing seems to help.

**Comment by fletch3555** [comment]
Have you tried `composer dump-autoload`? It should be run automatically when doing a `composer update` or `composer install`.  If that doesn't help, please verify that your providers array has `TCG\Voyager\VoyagerServiceProvider::class,` per the [documentation](https://laravelvoyager.com/docs/0.11/#getting-started-installation)

**Comment by zAbdelAziz** [comment]
I tried both of dump-autoload and I added the provider before I run the installer n sorrowfully it doesn't work.

**Comment by antisect** [comment]
Try
 php artisan config:clear

**Comment by fletch3555** [comment]
@YuriZakaria, have you resolved this issue? If not, please try `artisan config:clear` as suggested.  Something is holding onto that configuration.

**Comment by FireLustre** [comment]
I also have this kind of problem
`There are no commands defined in the "voyager" namespace.'`

run `php artisan config:clear`, but it doesn't work.

**Comment by fletch3555** [comment]
@FireLustre, this has been closed for 6 months.  If you have an problem that you suspect is a bug in the code, please open a new issue and reference the old one.  If you need help with implementation of Voyager, or just general questions, it would be better asked in our Slack group.
