### ISSUE TITLE
Setting select dropdown for user role

### ISSUE THREAD

**Issue by horstleung** [thedevdojo/voyager#1258]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.10
- PHP Version: 7.0.9
- Database Driver & Version: Mysql, mysql  Ver 14.14 Distrib 5.7.13

### Description:
It crashes when viewing User.

> ErrorException in 7a27a2877faf3d0c4462021c01b0d5e07a167569.php line 47:
> Trying to get property of non-object (View: /var/www/html/app/vendor/tcg/voyager/resources/views/users/read.blade.php)

### Steps To Reproduce:
After installing voyager, I tried to change the edit field of role_id from text to select dropdown.
I followed the document and added this JSON to Optional Details of User 
```
{
    "relationship": {
        "key": "id",
        "label": "display_name"
    }
}
```

and this function to User.php
```
public function roleId(){
    return $this->belongsTo(Role::class);
  }
```

and it crashes at read.blade.php
the crashed line: 
`{{$dataTypeContent->role->display_name}}
`

then I dd the $dataTypeContent, it got the role_id correctly.
<img width="681" alt="what i got" src="https://cloud.githubusercontent.com/assets/1083049/26103499/613b6b72-3a6c-11e7-97ab-ffb8b25b4ec8.png">

for now, I created a custom read.blade.php for users and changed the crashing line to
```
<?php $role = TCG\Voyager\Models\Role::where('id', $dataTypeContent->role_id)->first(); ?>
                          {{$role->display_name}}
```

Am I adding the relations wrongly for this case? Or I missed some steps?

**Comment by hotsaucejake** [comment]
Your line in your read.blade should be

`<?php $role = \TCG\Voyager\Models\Role::where('id', $dataTypeContent->role_id)->first(); ?>`

Notice the leading slash in front of TCG

**Comment by hotsaucejake** [comment]
Also this function should be:

````
public function roleId(){
    return $this->belongsTo(Role::class, 'role_id');
  }
````

**Comment by horstleung** [comment]
My read.blade is for by passing the crash, it works well. What I want is solving the crash and use the default view.

**Comment by fletch3555** [comment]
In order for `{{$dataTypeContent->role->display_name}}` to work, your relationship method MUST be `role()`, not `roleId()`.

Closing for now due to age.  If this is still an issue after the 1.0 release, please open a new issue

**Comment by devenrdayadav99** [comment]
i have same issue i can not update avatar and role_id of user
