### ISSUE TITLE
Change the language

### ISSUE THREAD

**Issue by Rostom22** [thedevdojo/voyager#1259]
- Laravel Version: 5.4.23
- Voyager Version: 0.11.10
- PHP Version: 7.0.10
- Database Driver & Version: mysql 5.7.14

### Description: 

Hi, i would like to have the voyage admin panel in french, i tried to change it in the core but i know it's not recommended so is there a solution to do that ? thanks and sorry for my bad english.

**Comment by koltyakov** [comment]
Voting for this too. Got to have a localization of the Voyager on one of the projects soon. It would be great to have interface text elements as strings from the localization files or a translator table.
At the moment, as far as I know, interface language is mostly or completely hardcoded in the views.

UPD: Have found a [discussion](https://github.com/the-control-group/voyager/pull/731) about the feature.

**Comment by akazorg** [comment]
I'll close this since it's related to work in progress, and asked many times.
