### ISSUE TITLE
[feature request] select2 in bread input type

### ISSUE THREAD

**Issue by blomdahldaniel** [thedevdojo/voyager#126]
Support for select2 as a bread input type? Seems lite it is just to ad the `.select2` class to a `<select>` element. But json support for changing settings for the select2 is not there yet?

**Comment by marktopper** [comment]
I'm open for pull requests.

**Comment by fletch3555** [comment]
I'm going to close this for now since it's so old.  We may revisit this after the 1.0 release.  In the meantime, if anyone wants to tackle it, we're certainly open to pull requests as @marktopper said
