### ISSUE TITLE
Base table not found in installation

### ISSUE THREAD

**Issue by stefano-maglione** [thedevdojo/voyager#1262]
After executed php artisan voyager:install I got the error below

[PDOException]                                                               
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'backoffice.users  
  ' doesn't exist

**Comment by simoebenhida** [comment]
did you resolve the error if not can you give the screen when you type the command php artisan voyager:install

**Comment by akazorg** [comment]
@FELPONE you seem to have changed the users table name to `backoffice.users`?

Voyager doesn't work if you use another table other then Users. You can make it work, but there are references on the code to the users table, that require a updated.

We are working on prefixing Voyager tables, that might sort your issue.

**Comment by springerin** [comment]
it should be specified in the documentations so we don't lose time till we find this issue

**Comment by akazorg** [comment]
Hi @springerin you're right. Please, fell free to send a PR updating docs section.

**Comment by fletch3555** [comment]
@akazorg and @springerin, please note that the docs were moved to here https://github.com/the-control-group/voyager-site/tree/master/docs by @tnylea.
