### ISSUE TITLE
Change role

### ISSUE THREAD

**Issue by jiac0911** [thedevdojo/voyager#1263]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I have a table called tipo_usuarios that is  equivalent to roles table, so I need to change the model and the migration so they work with tipo_usuario

**Comment by nunomsh** [comment]
Is this a question? 
Read it 4x, but I can't understand if it's a question, bug, new feature...

**Comment by fletch3555** [comment]
Closing due to not enough information and lack of response.  Please reply with further information identifying your question or issue, and we may reopen it.
