### ISSUE TITLE
Error while selecting multiple image as the field type 

### ISSUE THREAD

**Issue by pranjalkumar** [thedevdojo/voyager#1264]
- Laravel Version: 5.4
- Voyager Version: #.#.#
- PHP Version: 7+
- Database Driver & Version:
All things to do date
### Description:
While selecting the multiple image upload option. The error occurs- undefined variable resize width in line 178.  Also option variable is not defined.

**Comment by fredhy** [comment]
My alternative solution is:
**- Step 1:** Reference: [HERE](https://github.com/the-control-group/voyager/issues/1226)
"..\vendor\tcg\voyager\src\Http\Controllers\Controller.php" 
_before line 178 type this code:_ 
` if (isset($options->resize) && isset($options->resize->width) && isset($options->resize->height)) {
                            $resize_width = $options->resize->width;
                            $resize_height = $options->resize->height;
                        } else {
                            $resize_width = 1800;
                            $resize_height = null;
                        }`
**- Step 2:**
"..\vendor\tcg\voyager\resources\views\bread\browse.blade.php"
_before @if($row->type == 'image')  put this code:_
 
`@if($row->type == "multiple_images")
                                
                                            @php $valor = json_decode($data->{$row->field}); @endphp
                                                
                                                @foreach($valor as $item)
                                                    <img style="width:100px"
                                                         src="{{Voyager::image($item)}}">
                                                @endforeach
                                            @elseif($row->type == 'image')`
**- Finally:**
"..\vendor\tcg\voyager\resources\views\bread\read.blade.php"
_before @if($row->type == "image")  put this code:_

` @if($row->type == "multiple_images")
                                
                            @php $valor = json_decode($dataTypeContent->{$row->field}); @endphp
                                
                                @foreach($valor as $item)
                                    <img class="img-responsive"
                                     src="{{Voyager::image($item)}}">
                                @endforeach`
Enjoy  :+1: 

PD: You can also add a Bootstrap carousel ;)

**Comment by ghost** [comment]
@fredhy why not creating a pull request ?

**Comment by ghost** [comment]
@fredhy and editing the vendor file is not a solution

**Comment by lancepioch** [comment]
Labels: bug, bugfix

**Comment by fletch3555** [comment]
Issue should be fixed in 1.0.  Please verify and reopen if necessary
