### ISSUE TITLE
Images 404 error. Changing upload path

### ISSUE THREAD

**Issue by kfjlol** [thedevdojo/voyager#1265]
- Laravel Version: 5.3
- Voyager Version: ^0.10.13
- PHP Version: 5.6.4
- Database Driver & Version: MySQL

### Description:
I have a problem with showing up uoloaded images. All downloaded pictures are not displayed and give out a 404 error.
I tried to found a problem and test uploading and showing up proccess. As a result, the problem is that the image is uploaded into the /storage/app/public/ , but the Voyager show up image by wrong link - /public/storage/
I need to solve that issue, maybe i can change upload folder?

voyager.php setting:
```
'storage' => [
        'subfolder' => 'public/', // include trailing slash, like 'my_folder/'
    ],
```
filesystem.php setting:
```
'default' => 'local',
 'cloud' => 's3',
'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
            'url' => env('APP_URL').'/storage',
        ],
        's3' => [
            'driver' => 's3',
            'key' => 'your-key',
            'secret' => 'your-secret',
            'region' => 'your-region',
            'bucket' => 'your-bucket',
        ],
    ],
```

**Comment by fletch3555** [comment]
Voyager is NOT using the wrong link.  You need to run `php artisan storage:link` to have a symbolic link called `storage` in your `/public/` directory, pointing at `/storage/app/public`.  This should be created automatically when running `php artisan voyager:install`, but sometimes errors happen and it doesn't get run.

**Comment by kfjlol** [comment]
Unfortunately, not everything is so simple and `php artisan storage:link` does not help. I'm already have the storage symlink in /../public/ , but files doesn't update. Maybe i must delete this symlink and rewrite `php artisan storage:link`?

**Comment by flipmode85** [comment]
same here! 
`php artisan storage:link ` didn't help.

**Comment by sarath-c-sandwich** [comment]
check your .env
Make sure is

`APP_URL=http://localhost:8000`  or
`APP_URL=http://127.0.0.1:8000`

<img width="326" alt="screen shot 2017-05-29 at 11 06 50 am" src="https://cloud.githubusercontent.com/assets/1330852/26536199/f7c2db88-445e-11e7-8bb9-f255dc369563.png">

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by emptynick** [comment]
Seems like this is not a problem anymore?

**Comment by fletch3555** [comment]
This is a very old issue on a horribly outdated version.  If it's still an issue on 1.0.*, please open a new issue.
