### ISSUE TITLE
Unknown column 'order' in 'order clause'

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#1266]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.10
- PHP Version: 7.1.2
- Database Driver & Version: 10.1.21-MariaDB Homebrew

### Description:
The admin for every model works fine in voyager 0.11.9. Upgrade to 0.11.10 and every admin list view returns an error of:
QLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'order clause' (SQL: select * from `data_rows` where `data_rows`.`data_type_id` = 1 and `data_rows`.`data_type_id` is not null and `browse` = 1 order by `order` asc)

### Steps To Reproduce:
from version 0.11.9 use voyager to create a table and then a BREAD for that table. Check admin works. Then upgrade to 0.11.10 and the admin will return the above errors.

Force composer to use 0.11.9 and then run composer update and it works again. I havent found any migrations or documentation about breaking changes between these versions?

**Comment by akazorg** [comment]
Please check #1212.
