### ISSUE TITLE
Sometimes I do not need the standard CRUD

### ISSUE THREAD

**Issue by jiac0911** [thedevdojo/voyager#1270]
- Laravel Version: 5.4

### Description:
I got this problems with two kind of "special crud":
1. When I need just one create/edit view to store in two tables, like when I create a new contact I need to store its adress and phone in other tables.

2. I am using a map api because I need to know the ubication and draw a perimeter of farms, how can I edit the create/edit view so it can have this map?

**Comment by akazorg** [comment]
Hi @jiac0911, you will need to create a custom View and Controller.

Have you checked [documentation](https://laravelvoyager.com/docs/0.11/#customization-overriding-views)? take a look into Post example, it's using a custom view. The controller can be define on BREAD, or by setting a custom route.
Good luck.

**Comment by jiac0911** [comment]
@akazorg can you help me with the controller? I define the namespace in config/voyager.php and then run php artisan voyager:controllers, but the console throw this error: "The controllers namespace must start with your application namespace: App</error>"

**Comment by akazorg** [comment]
Hello.
The namespace at config `voyager.php` should be something like:
```
'controllers' => [
    'namespace' => 'App\\Http\\Controllers\\Voyager',
],
```

Check the namespace of the Controllers to follow the current location, such as:
```
<?php

namespace App\Http\Controllers\Voyager;
```

I'm not sure if you need to run `composer dump-autoload`.

**Comment by jiac0911** [comment]
@akazorg  I am sorry but I am really new, the documentation says that the controller would be created after I run the command:

`php artisan voyager:controllers`

I do not know if maybe I did not have it rigth, but do I need to create the controller on that path by myself? let me explain better, I change the namespace in config/voyager.php I put exactly what you and the documentation say , that is all I did, then I run the command. am I missing something? I do not get that error: 
`The controllers namespace must start with your application namespace: App`

**Comment by akazorg** [comment]
Hi @jiac0911, it's ok, we have all started somewhere.
If you are new to Laravel, I suggest you to play around with it first, and then create custom Voyager views, controllers, etc.. Voyager is basically Laravel.

I didn't understand what is your issue now.
There are no errors anymore?
Did you had a custom Controller?

Perhaps it's easier if you join us on the Slack channel.

**Comment by jiac0911** [comment]
@akazorg  I already know laravel, but my problem is creating the custom controller for this admin panel because when I run the command nothing happen it doesn't create the controller so I can modify it, that is all need, how to make my own controllers and views but still using this panel. it is the problem with the namespace that it is killing me, i do not know what should be.

By the way, thank you for your answer, I will be happyof join you in Slack channel so would be easier

**Comment by akazorg** [comment]
Check the namespace of your files and verify the config voyager.php.
Have you tried a `composer dump-autoload`?

**Comment by jiac0911** [comment]
@akazorg I already run `composer dump-autoload` but stil not working, this is the namespace:
`    'controllers' => [
        'namespace' => 'App\\Http\\Controllers\\Voyager',
    ],`

and this error is thrown:

```
  [ErrorException]
  file_put_contents(C:\Sioma\Pruebas interfaz admin\voyagerAdmin\app\Http/Controllers/Controllers\Controller.php): failed to open stream: No such file or directory
```

**Comment by akazorg** [comment]
Hello @jiac0911, the namespace you posted is correct.

The error report is suspicious, you see the `Controllers/Controllers` appearing twice? It could be related to some `\` or `/` missing or added somewhere?

I would really love to see this working, but I'm running out of ideas here :(

I suggest you to test on a fresh install, follow Voyager docs, this should work OOTB.

Good luck

**Comment by fletch3555** [comment]
Closing for now due to age.  If this is still an issue after the 1.0 release, please open a new issue
