### ISSUE TITLE
Open Browse very slow only 3k rows 

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#1271]
- Laravel Version: 5.4
- Voyager Version: 0.11.8
- PHP Version:
- Database Driver & Version:mysql

### Description:
When I open browse a 3k table, need more then 1 minute. If I use Server-side Pagination = on, then very fast. 

I test 2, 300 rows,it is ok.

Hardware and MySql are very fast.

**Comment by fletch3555** [comment]
I'm Sorry, is there an issue or question here? Sounds like it's functioning exactly as expected

**Comment by jun283** [comment]
I think if open a page need more then 1 minute, this function is unacceptable, so I must be use Server-side Pagination = on, but use Server-side Pagination, not search function.

is it possible use Server-side Pagination, and have search function?

**Comment by AdrianKuriata** [comment]
Probably dataTables not working with loading data by Server Side loading so all 3k rows is loaded, with server side pagination just only as many rows is load as you set how much items should be loaded with pagination.

**Comment by akazorg** [comment]
@jun283 Search is not implemented with server side pagination, I also miss that feature :(
See PR #937.
