### ISSUE TITLE
Radio Button in BROWSE and READ pages only show the value

### ISSUE THREAD

**Issue by rushairer** [thedevdojo/voyager#1272]
- Laravel Version: 5.4.*
- Voyager Version: v0.11.10
- PHP Version: 7.1.3
- Database Driver & Version: mysql:latest

### Description:

In RREAD.
When I use a Radio Button just like:
```
{
    "default" : "1",
    "options" : {
        "1": "XXX",
        "2": "YYY"
    }
}
```
In the ADD and EDIR pages, it will show me the "Radio Button" UI.
But in the BROWSE and READ pages, it just show me "1" or "2" (the values).

I haven't found some issues like that in the issues list.
Can i have another way to make it beautiful?

Thanks.

**Comment by fletch3555** [comment]
There have been many similar issues regarding the `Browse` and `Read` views.  I believe they've been fixed in `master` in preparation for the 1.0 release.  If this is still an issue after the 1.0 release, please create a new issue
