### ISSUE TITLE
[Discussion] Allow to group fields in categories

### ISSUE THREAD

**Issue by DODMax** [thedevdojo/voyager#1273]
Hi,

I would like to work on a feature that allow users to group fields into categories (for large forms).
For example on the *edit-add* and *read* views, I would like to see:

Member info |
---------------|
First Name
Last Name
...
**Contact Info**
Email
Phone
...

Other than readability the problem is that I sometime need to display just part of a form and it's not really flexible to have to write `$dataType->editRows->whereIn('field', [...`

So as I see it I would add a button on the Database BREAD Edit interface that adds a *Category* DataRow of type `category`, plus a `scopeCategory` function on the DataRow model that does something like:
```
function scopeCategory($query, $category)
{
    $cat_query = clone $query;
    $categories = $cat_query->where('type', 'category)->get();
    $cat_from = $categories->where('field', $category)[0]->order;
    $cat_to = $categories->where('order', '>' , $cat_from)[0]->order;

    return $query->where('order', '>=', $cat_from)->where('order', '<', $cat_to);
}
```

This should allow to do `$dataType->editRows()->category('contact_info')->get()` ... I think..

Any thoughts on the usefulness of such feature and the proposed implementation?

Cheers!

**Comment by akazorg** [comment]
This is an interesting feature indeed.

I have some comments on your propose.
1. fields would be related to one category only (we can sort this using a tree);
2. insert/update will not work, unless you include all required fields in that group;

This system could also be used for creating Micro UI Components, working with AJAX calls. We could then have a single page with multiple BREAD's.

IMHO we should implement a tree system, maybe a preorder traversal tree will work great for most of the scenarios, such as Groups, ParentID and Trees (like the menu). So, having a unique tree system that could be hooked on any table, the same way we add timestamps to the BREAD.

Please, let me know your thoughts.
ping @marktopper @fletch3555 @abdgad @tnylea

**Comment by fletch3555** [comment]
You're free to override the views to add this functionality yourself.  I don't believe Voyager needs it in it's core.
