### ISSUE TITLE
Missing storage symlink. symlink() has been disabled for security reasons

### ISSUE THREAD

**Issue by ferywijaya** [thedevdojo/voyager#1274]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.10
- PHP Version: 5.6
- Database Driver & Version: Mysql

### Description:
sorry for my bad english.

Please help. I get into trouble while hosting my project. There are problems with symlinks and storage. Files or images stored on storage can not be read, even though the url gets the time to upload the file. What can i do to justify this problem?

symlink error and cannot display image
![image](https://cloud.githubusercontent.com/assets/9111355/26345253/8d7ddcd2-3fcc-11e7-8d76-b1d67707a41d.png)
![image](https://cloud.githubusercontent.com/assets/9111355/26345273/9dd398ba-3fcc-11e7-9f5b-e799746da06b.png)

directory structure like this

![image](https://cloud.githubusercontent.com/assets/9111355/26345501/4b013f38-3fcd-11e7-9df8-a0ae33634bbf.png)

![image](https://cloud.githubusercontent.com/assets/9111355/26345481/3c7ec3cc-3fcd-11e7-82f3-8d4af9371a95.png)

![image](https://cloud.githubusercontent.com/assets/9111355/26345459/2b963388-3fcd-11e7-8cdf-8610ca00970e.png)

**Comment by olko404** [comment]
the same problem. does anyone know how to fix it?

**Comment by sarath-c-sandwich** [comment]
Mostly problem happen on Window environment. Hmmm ...

**Comment by olko404** [comment]
no, its on server. I have this problem only on server

**Comment by ferywijaya** [comment]
Is there any other way if symlinks can not be used? Such as changing the directory to upload the file or its image?

**Comment by ferywijaya** [comment]
i try this and work like champ.. change the root
'public' => [
            'driver' => 'local',
            'root' => public_path('storage'),
            'visibility' => 'public',
        ],

**Comment by sunalz** [comment]
Options +FollowSymLinks
add this line on ur .htaccess file if this does not work,
Options +SymLinksIfOwnerMatch.
replace it with this line.

hope this works for someone :)

**Comment by ismaeljoseph** [comment]
Hello Everyone I have this issue and solve it this way. 
On linux/debian : 
1- go the public folder and remove storage folder 
2- re-create the symlink : php artisan storage:link

On windows : 
1- install git for widows and with  git-bach 
2-  go the public folder and remove storage folder 
3-  re-create the symlink : php artisan storage:link

And it solve all problem 

Alternatively for windows , you can just remove the storage folder and use windows commande to recreate the symbolic link.  exemple ( Mklink /d  ...path\public\storage\  ...path\storage\app\public\ ).
But i never try this out. 

god bless you all.

**Comment by radiumrasheed** [comment]
**@ferywijaya what file is that ?**

**Comment by radiumrasheed** [comment]
oh yeah, figured it out..
`config/filesystems.php`

**Comment by babakmomeni** [comment]
I had the same problem. Thanks to @ferywijaya and @radiumrasheed for the solution

**Comment by anandmainali** [comment]
Just change in `config/filesystems.php`
` 'root' => storage_path('app/public'),
`

to,
`
            'root' => public_path('storage'),
`
