### ISSUE TITLE
Dropdown field showing id in browse/view

### ISSUE THREAD

**Issue by seiki** [thedevdojo/voyager#1276]
- Laravel Version: v5.4.23
- Voyager Version: v0.11.10
- PHP Version: 7.1.3-3
- Database Driver & Version:

### Description:
the select dropdown is working fine in edit/create but in browse/view it shows the id instead of the name of the object
![screenshot from 2017-05-24 20 50 41](https://cloud.githubusercontent.com/assets/862944/26430357/0390f372-40c3-11e7-810c-9aaafdbdd513.png)

**Comment by akazorg** [comment]
Hi @seiki,

Check BREAD optional details relationship. That is working fine here.
```
{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
```
The `label` should be the field name from the foreign table.

**Comment by nunomsh** [comment]
Add the field in the Model
**return $this->belongsTo('App\YOUR_MODEL', 'name_of_field');**

**Comment by seiki** [comment]
I did those things, that's why the relationship is working fine in the edit/create pages, but is not in the browse/view.

**Comment by SerjoA** [comment]
same problem here, did those things and working fine on create and edit pages, but sometimes shows fine on browse and some rows shows the id insted of name

**Comment by Dynamo6Dev** [comment]
Same here. Edit page works perfectly but Browse page just shows an ID not a text value

**Comment by reficul** [comment]
I've the same problem

**Comment by gileswells** [comment]
Does this continue on the latest versions? Have you customized the browse/read views since your latest updates?
I have these type of relationships in my own install and I get the proper output.

**Comment by reficul** [comment]
Confirmed on v0.11.12, then yes.

**Comment by fletch3555** [comment]
As @nunomsh mentioned, please make sure the 2nd argument to the relation method exists and is correct. It needs to be the foreign key (i.e. `post_id`, not just `id`)

**Comment by Dynamo6Dev** [comment]
@fletch3555 OK, that fixed it for me. I've updated the belongsTo call 2nd param with the foreign key field name from the main class **not** the actual field name from the referenced class (e.g. User->subscription_id **not** Subscription->name). Thanks for your help!

**Comment by fletch3555** [comment]
Perfect, glad it worked for you.

**Comment by seiki** [comment]
I didn't see that 2nd arg. That fixed it. Thanks!

**Comment by reficul** [comment]
Sorry, I really need help here, because I'm lost.
I've a table name playerstats with a field (player) that join to users table (id)
Something like: playerstats.player = users.id

In my playerstats model I've:
`	public function player(){
    	return $this->belongsTo(User::class, 'id');
	}`

and in the bread editor:
`{
    "relationship": {
        "key": "id",
        "label": "name",
        "page_slug": "admin/users"
    }
}`

What wrong here? I got: **Trying to get property of non-object**
Sorry if I'm asking again.

**Comment by Dynamo6Dev** [comment]
@seiki Yeah, the second arg is missing from the documentation at the moment.

@reficul I think you have it the wrong way round. Try
`public function player(){ return $this->belongsTo(User::class, 'player'); }`
inside your PlayerStats class.

Then in the BREAD for the PlayerStats class, in Optional Details on the player row you need 
`{
    "relationship": {
        "key": "id",
        "label": "field_name_to_display_from_user_class"
    }
}`

**Comment by reficul** [comment]
![schermata 2017-06-23 alle 10 04 11](https://user-images.githubusercontent.com/1073883/27472420-89459410-57fb-11e7-9b8d-16b0d85ef44d.png)

![schermata 2017-06-23 alle 10 05 58](https://user-images.githubusercontent.com/1073883/27472433-950052ae-57fb-11e7-9365-09f98d424aa3.png)

**Comment by Dynamo6Dev** [comment]
Hmmm. Are the values in PlayerStats->player field numerical IDs?

**Comment by reficul** [comment]
@Dynamo6 yes.

![schermata 2017-06-23 alle 10 14 07](https://user-images.githubusercontent.com/1073883/27472742-d5c6da64-57fc-11e7-8f4b-0f28941d21da.png)

![schermata 2017-06-23 alle 10 14 39](https://user-images.githubusercontent.com/1073883/27472759-df9df310-57fc-11e7-8388-43937721b818.png)

**Comment by Dynamo6Dev** [comment]
I'm out of ideas I'm afraid. Thats the same setup I have. The only other thing to try is a `composer update` -> i'm running v0.11.14

**Comment by reficul** [comment]
Thanks anyway, I tried to update, but it did not work. 
I'm waiting for @fletch3555 @akazorg or some other collaborators or someone that can give me an help.

**Comment by reficul** [comment]
Fixed... There is another field that give problem.
Thanks to all.

**Comment by PSDeora** [comment]
i searching lot but cant find solution for why browse showing id instead of name even edit and create bread showing drop down with name correctly
my relation is like this :

public function userId() : BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    } 

finally i got a solution by simply adding  BREAD accessors to my model like 

    public function getUserIdBrowseAttribute()
    {
        return $this->usertId->name;
    }

this replace id with name in browse bread

use for refrence https://voyager-docs.devdojo.com/customization/bread-accessors

**Comment by fletch3555** [comment]
@PSDeora, please don't comment on old closed issues.  This has been closed for nearly 3 years now and was for a much MUCH older version of Voyager
