### ISSUE TITLE
Editing a post sets the id to 0 

### ISSUE THREAD

**Issue by cadmicro** [thedevdojo/voyager#1277]
- Laravel Version: Latest
- Voyager Version:  v0.11.12
### Description:

Everytime I update a a post, the value of the ID changes to 0 no matter what...

This only happens when updating a post, it doesnt have on any of the other edit pages....

**Comment by akazorg** [comment]
I've just tested and Post update is working fine.

This seems related to your Post view, you probably changed it?!
Please compare it with the [Voyager Post view](https://github.com/the-control-group/voyager/blob/master/resources/views/posts/edit-add.blade.php).

Good luck.
