### ISSUE TITLE
Not able to save BREAD model with required image

### ISSUE THREAD

**Issue by adriangordon1231** [thedevdojo/voyager#1278]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.8
- PHP Version: 7.0
- Database Driver & Version: MySQL 14.14

### Description:
I am noticing that If I set the image field in my BREAD model to required, I am not actually able to update the model in the voyager interface without also uploading a  brand new image. When I try to do it, I get the following error message:

 
![image field required](https://cloud.githubusercontent.com/assets/7938253/26459645/27b2d14e-4145-11e7-8174-ca834fc1f918.png)

### Steps To Reproduce:

1. Create a model with an image field
2. Add a new model instance to the database (in my case, I created 10 models using a seed)
3. Make the image field required in BREAD using the validation rule specified in the voyager docs ("rule" : "required").
4. Attempt to update one of the models on the 'edit' page in the voyager admin interface.

**Comment by akazorg** [comment]
I understand, this happens because the field is required and we are posting an empty file input.
We need a workaround for this.
Thanks for reporting that!

**Comment by adriangordon1231** [comment]
I see, as I suspected. Looks like I am gonna have to come up with a fix for this. I will let you know when/if I do.

**Comment by akazorg** [comment]
Yes, do it please! :)
Thanks Adrian

**Comment by nunomsh** [comment]
As suggestion you can turn off validation for the the image, if editing the item. If the field is require, means that if you're editing then you already have an image.
Another idea could be some hidden field with the image value/path. If this field not empty, then it means you have an image

**Comment by adriangordon1231** [comment]
@nunomsh  How do you turn off validation only for editing.

**Comment by nunomsh** [comment]
@adriangordon1231  voyager validates if you're editing or adding a new. It checks the field ID if is set, then you're editing. 
In the edit-add.php  when loading the foreach cicle, you can look for the image
```

@foreach($dataTypeRows as $row)
@if($row->field=='your_field')
<label for="name">IMAGEM</label>
 <input name="image" id="upload_file" type="file">
@endif
@endforeach
```
This is just a idea how you could avoid the validation when editing and if the field matches the image field.
If that doesn't work you can also try to set a hidden field with the value of the image, so the POST will check the field if it's not empy wont show error
`<input type="hidden" class="form-control" name="your_image" value="@if(isset($dataTypeContent->your_image)){{ $dataTypeContent->your_image }}@endif">`

This are just ideas, haven't tested any of them, if that doesn't work we need to wait for a patch to fix it

**Comment by akazorg** [comment]
Hi guys.

There is also a missing feature for delete BREAD images, this is somehow related and maybe could be handled at the same time.

I can work on a solution later.

**Comment by jayeshk123** [comment]
In laravel, we can turn off validation by using following method :

  ````
public function update(Request $request, $id)
{
    $this->validate($request, [
        'code' => 'required|max:20|unique:tech_modules,code,'.$request->id,
        'name' => 'required'
    ]);

     $data = array('code' => $request->code,
         'name' => $request->name
         'is_active' => $request->is_active
      );

     $edit = tech_modules::find($id)->update($data);      
}

**Comment by davodavodavo3** [comment]
close this issue
