### ISSUE TITLE
Failed to extend voyager controllers

### ISSUE THREAD

**Issue by nunomsh** [thedevdojo/voyager#1287]
- Laravel Version: 5.4.
- Voyager Version: 0.11.12
- PHP Version: 7

### Description:
Voyager custom controllers fails to create the new controllers in the namespace.

### Steps To Reproduce:
1- Set the namespace   'namespace' => 'App\\Http\\Controllers\\Voyager',
2- run php artisan voyager:controllers

Returns error  [ErrorException]
file_put_contents(C:\xampp\htdocs\voyager\app\Http/Controllers/Voyager/Controllers\Controller.php): failed to open stream: No such file or directory

The folder is created, but the controllers are not generated.
I've check folder permissions, but same result. In previous voyager versions, it works fines

**Comment by akazorg** [comment]
I've test it out and it's working with the latest version.

Try using:
```
    'controllers' => [
        'namespace' => 'App\\Http\\Controllers\\Voyager',
    ],
```

**Comment by latipun7** [comment]
I have the same issue. And solution from @akazorg still not resolved.
![Image of Yaktocat](https://puu.sh/w9mSe.png)

well, the path seems weird too, with / and \ mixed up.

**Comment by latipun7** [comment]
Update: this problem is resolved by latest dev-master.
@nunomsh , try update your voyager with "dev-master" version. If it's resolved your problem, case closed :)

I guess you are using windows too, that's the problem, and now it's fixed.

**Comment by vaggelis2018** [comment]
Same problem on clean install. How to update to dev-master?

**Comment by marktopper** [comment]
```composer require tcg/voyager:dev-master```
