### ISSUE TITLE
Model boot events not working in editor

### ISSUE THREAD

**Issue by WolandV** [thedevdojo/voyager#1288]
- Laravel Version: 5.4
- Voyager Version: 0.11.12
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7.17

### Description:
Voyager ignoring result of work `boot()` method of `Model`. Method `boot()` can cancel saving model, but Voyager showing success popup anyway.

### Steps To Reproduce:
1. Make new table (`article` for example)
2. Make model (App\...\Article.php)
3. Make `bread` for that table.
4. In model make boot() method with event saving, which can return false and cancel update row:
```
...
class Article extends Model
{
        public static function boot()
        {
                static::saving(function ($article) {
                        return false; # <--- required in some cases, only false for example
                });

                parent::boot();
        }
        ...
}
```
5. Go to create or edit screen (/admin/article/create || /admin/article/update).
6. Try to set new values and `Save`.
7. Expected result: changes does not applied, Voyager show `Error popup`
Outcome result: changes does not applied, Voyager show **SUCCESS POPUP**.

Hope, you'll decypher my English.

**Comment by fletch3555** [comment]
I don't believe this is an issue with the boot method.  Instead, I think Voyager is just failing to display the correct message.

Since this is quite old and from an old version, I'm going to close it for now.  If this is still an issue after the 1.0 release, please open a new issue.
