### ISSUE TITLE
RTL-feature

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#1289]
hello 
how can we use your rtl version now 
because it is not merged still and views are not that rewritable

**Comment by kenshimokak** [comment]
trying this blowe code in your `composer.json` file. and then run `composer update` command

```
	"require": {
		"php": ">=5.6.4",
		"laravel/framework": "5.4.",
		"laravel/tinker": "~1.0",
		"tcg/voyager": "dev-feature/rtl-support"
	},
```

**Comment by faghihi** [comment]
thanks
