### ISSUE TITLE
without installling laravel/framework

### ISSUE THREAD

**Issue by johnss** [thedevdojo/voyager#1290]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.12
- PHP Version: 7.0
- Database Driver & Version:

Is it possible to install voyager without installing full laravel/framework?
In composer.json it only requires illuminate/support not the full blown laravel/framework. 
If possible, how to do it? There are many articles in Google results showing how to create using only illuminate/support, but none of them is tcg/voyager specific.

**Comment by akazorg** [comment]
Short answer: No.

Voyager works on top of a Laravel installation, so it's required.

**Comment by johnss** [comment]
@akazorg Please explain why the composer.json only requires `illuminate/support` or is it a bug?

**Comment by akazorg** [comment]
Hi @johnss, you do have a point on that.
We don't need `illuminate/support` at the composer file because Voyager requires a Laravel installation, so this lib is already at system,

I've sent PR #1299 with a revision.
Thanks :)
