### ISSUE TITLE
How to update all migration file?

### ISSUE THREAD

**Issue by vanloc0301** [thedevdojo/voyager#1292]
- Laravel Version: 5.4
- Voyager Version: v0.11.12
- PHP Version: 7.1.5

### Description:

When I created a new table like `Products` with Tool > Database in Voyager.

I want to create a migration file sync with this.

Because when I copy source to another computer. I must run the command: `php artisan voyager:install --with-dummy`.

It does not create table `Products` because don't have migration file in the folder: `database/migrations/....`.

Thanks.

**Comment by akazorg** [comment]
Hi @vanloc0301 

You have to create your own migration files in order to accomplish that, Voyager is not generating the migration at the moment :(

**Comment by vanloc0301** [comment]
Thanks @akazorg

**Comment by longuyvinh** [comment]
You can use https://github.com/Xethron/migrations-generator to generate database ;)
