### ISSUE TITLE
Can not upload images with large size

### ISSUE THREAD

**Issue by nirojadhikary** [thedevdojo/voyager#1296]
Laravel Version: 5.4.
Voyager Version: 0.11.12
PHP Version: 7
Description:
i can upload images with small size but not the large size images. While uploading it from media i can upload small size image but while uploading large size images it says undefined variable path.

While uploading from datatypes it returns null value in place of image name.

If i upload small image during adding data and try to upload large size image during edit it shows success message but image was never uploading.

**Comment by fletch3555** [comment]
Please be more specific. How big is "large size"? Are you referring to image dimensions or file size?

Voyager doesn't really care about specifics of the image, but if you're using the config to create thumbnails for the image, it may delay processing, but that would likely require the images be MASSIVE.

More likely, the issue is your php or webserver configuration reaching the request timeout.

**Comment by nirojadhikary** [comment]
I am referring to file size which is  more than 3MB / 4MB.
Its not showing any timeout messase and server setting value are configured as necessity.
I can upload images with upto 2MB size.
When i upload images with large MB it displays success message but image is not there on folder.

**Comment by gileswells** [comment]
2MB is the default php.ini max_upload_size setting. I'd suggest checking your server setup and raising that limit. That should get you going. As for there not being a proper error message that seems like the proper bug/enhancement to tackle on this issue.

**Comment by ainvention** [comment]
1. Upload max file size:
Upload max file size is concerned with your php.ini setting where "upload_max_filesize=   ".
Default is 2M bytes. you can change it.

2. Uploaded File directory:
Check your file directory under "public/storage/***"
If you saved any file like setting, post, page or use data, then all of that files posited under "public/storage/***"

Enjoy Voyager:)

**Comment by fletch3555** [comment]
This has been answered multiple times now.  If it continues to be a problem after following the suggestions above, please reply here again.
