### ISSUE TITLE
Issue - Can't be used in sub-directory (routes & assets)

### ISSUE THREAD

**Issue by Thiktak** [thedevdojo/voyager#130]
Hello,

I tried to install this awersome tools in a subdirectory ... but I got some issues. Indeed, i found:
 - some form action using absolutes paths (impossile to login, for example because there is a `action="/admin/login"`).
Maybe add names to routes or using action()/route() methods on the blade templates ?
 - Identical issue with images/css and all assets. I used the asset() function.
ex: `{{ asset(config('voyager.assets_path')) }}`
 - Idem for avatars `<img src="{{ asset($user_avatar) }}" />`

**Comment by maiorano84** [comment]
I think part of this might be corrected in yesterday's PR #120 

In this, I had removed all static references to the /admin route, and created a configuration option to prefix Voyager routes with whatever you like. Let me know if this helps.

**Comment by Thiktak** [comment]
I downloaded your fork :)

Still some issues:
- Missing somes route for <form />: /admin/database/delete_bread, href="/admin/database/..." (ex: src/views/tools/database/index.blade.php)
  I used Notepadd++ and search on all files > **Search "/admin" (9 hits in 6 files)**

But yeah ! Good job :p

**Comment by maiorano84** [comment]
Funny you should mention, I actually just found those on my own myself. My search was even more generic (searched on "admin"), so some of the leftover urls got lost in the noise. You should be good now.

Note that searching for "/admin" will yield two results:

One is a default value in the media uploader Javascript that is to be overridden by an object passed into its constructor

The other is a part of the README

**Comment by Thiktak** [comment]
Ok, thanks :) I will test.
Do you want to fix assets too ? I already did it. I can request a PR to this repo or yours, if you want to include all on one package.

**Comment by Thiktak** [comment]
Yeah ! Yes, I see the javascript's one.

I think there is an issue.
If you clear your view's cache (`php artisan view:clear`), you will have a `Route [users.index] not defined.`. Same for posts & cie.
By default, there is no route for them.

**Comment by maiorano84** [comment]
Interesting. I'll look into that.

Though, I'm wondering how that can be triggered from a view:clear command. Those routes should all be declared as resources, so - provided the database entries under the data_types table are there - those routes should be valid.

**Comment by maiorano84** [comment]
I've run `php artisan view:clear` under a fresh Homestead installation. Unfortunately, I'm not able to replicate your issue.

If you could, can you detail out how to replicate the problem either on PR #120 or in my fork? That would certainly help narrow things down.

**Comment by Thiktak** [comment]
Ok. I will restart an fresh installation. Maybe the instllation part shold make some magic :)

Issue - Route [voyager.database.store_bread] not defined.

**Comment by maiorano84** [comment]
Ah, no, you're right about that one. I didn't alias the store_bread route. New commit is ready.

**Comment by Thiktak** [comment]
Yeah ! fixed ! I think some magic happened during installation :)

BUT, yes, there is a but ... 
- on the Ariane navigaton/Breadcrumb all link refers directly to  "admin". I think this should be an "/" explode between the dashboard link and the current one. (from /admin/menus/2/builder)

**Comment by maiorano84** [comment]
Breadcrumbs appear to be pointing fine on my side. Do you mean the links that are generated in the menu itself?

Those come from the built-in seeder. The following commit corrects that issue, but there's a caveat:

https://github.com/the-control-group/voyager/pull/120/commits/ffa59e7c34deae5c40a391ee20adf25b2d157a2f

In order for those links to be generated with the correct prefix, the config value needs to be set _before_ running the installer. You can test this yourself by creating a fresh installation, setting the `voyager.routes.prefix` config value, and then running the installation process. The links will be seeded properly then.

Otherwise, seeding the database with the wrong prefix will necessitate changing each route in each menu item.

Provided my PR is accepted, I can probably work on making this an interactive part of the installation process (ie: User is presented with a prompt to set the route prefix during the voyager:install process)

**Comment by Thiktak** [comment]
Hi,

Indeed. It's working :)

On my side, the breadcrumbs still not working.
I edited the **master.blade.php** view add changing line 82 : `<li class="active"><a href="{{ route('voyager.dashboard') . '/..' . $breadcrumb_url }}">`

**Comment by ChrisThompsonTLDR** [comment]
I recommend moving to using a [route namespace](https://laravel.com/docs/5.3/routing#route-group-namespaces) to silo all the routes related to voyager.

Also, a [route prefix](https://laravel.com/docs/5.3/routing#route-group-prefixes) would be nice.  I have routes from Voyager colliding with existing routes now.  I see a prefix being applied in VoyagerServiceProvider.php.  Is there a reason it's not in the routes.php file?

**Comment by ChrisThompsonTLDR** [comment]
`src/views/tools/database/edit-add-bread.blade.php` line 27 doesn't respect the route prefix.  It's still hardcoded to `/admin/`.

**Comment by ChrisThompsonTLDR** [comment]
None of the menu_items appear to respect the `voyager.routes.prefix` config param.

**Comment by maiorano84** [comment]
In my branch, it did:

https://github.com/maiorano84/voyager/blob/route-prefix/src/views/tools/database/edit-add-bread.blade.php

It appears the author incorrectly merged another piece of functionality that affected this:

https://github.com/the-control-group/voyager/blob/master/src/views/tools/database/edit-add-bread.blade.php

**Comment by maiorano84** [comment]
@tnylea Are you able to remediate?

**Comment by tnylea** [comment]
Thanks @maiorano84  :) I've just merged your PR and will update the latest version within  a few hours. I'll be writing more tests as well to prevent these from happening :)

Thanks.

**Comment by maiorano84** [comment]
Anytime, brotato chip. Keep up the great work! It's still a young project, but it's showing a lot of promise!
