### ISSUE TITLE
Nested admin menus - unable to open 2nd level

### ISSUE THREAD

**Issue by markwillis82** [thedevdojo/voyager#1300]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.12
- PHP Version: 7.0
- Database Driver & Version: Mysql

### Description:
Create 2 nested menus and place one inside the other. Upon reload the menus look correct within the sidebar but you are unable to open the inner dropdown.

**Comment by akazorg** [comment]
Hi @markwillis82.
At the moment Voyager just supports 2nd level menus.
We are planning a solution for this.
