### ISSUE TITLE
invalide datetime format

### ISSUE THREAD

**Issue by Rostom22** [thedevdojo/voyager#1301]
- Laravel Version: 5.4.24
- Voyager Version: 0.11.12
- PHP Version:7.0.10
- Database Driver & Version: mysql

Hi, i have an event model with start_date, end_date and i'm using the bread system, when i'm adding an event and selecting a date with the datetimepicker it's select the time and (PM or AM) and when i submit i've got a queryexception related to invalid datetime. how can i set the datetimepicker to choose date only ? Thanks.

**Comment by Philwn** [comment]
I have a similar issue.

Using Chrome i get a datepicker d-m-Y which works fine. Using safari or Firefox though the datepicker is formatted m-d-Y with timestamp and it errors on insert.

**Comment by Rostom22** [comment]
Hi, i fixed my problem by adding this in the edit-add bread view : 

```
$('.form-group input[type=date]').each(function (idx, elt) {
    if (elt.type != 'date' || elt.hasAttribute('data-datepicker')) {
        elt.type = 'text';
        $(elt).datetimepicker({format : 'YYYY/MM/DD'},
            $(elt).data('datepicker')
        );
    }
});
```

**Comment by Philwn** [comment]
Can we get this added as a fix, I have replicated your fix and it works. This needs adding to the package!

**Comment by doatta** [comment]
Hi! As I see you have also added calendar to your voyager

Can you  please help me with my issue? 
https://github.com/the-control-group/voyager/issues/1706

**Comment by emilvaliyev** [comment]
in the voyager\src\Http\Controllers\Controller.php add after case 'timestamp':

if ($request->isMethod('POST')) { $content = gmdate('Y-m-d H:i:s', strtotime($request->input($row->field))); }

**Comment by lancepioch** [comment]
Labels: bug

**Comment by doatta** [comment]
Thanks emilvaliyev! It works!

**Comment by handiwijoyo** [comment]
Close due to old voyager version.

**Comment by tommiekn** [comment]
@handiwijoyo seems problem is there still. 
Unable to set datetime SQL alike format, hour is always show in AM/PM.
