### ISSUE TITLE
relationship with details 

### ISSUE THREAD

**Issue by joefreire** [thedevdojo/voyager#1302]
How can I add a related field that has one more detail, for example:

table_os
->id,nome
table_itens
->id,nome
table_os_item
->os_id,item_id,amount

I usually use jquery to create the inputs dynamically, but I wanted to use the bread

**Comment by fletch3555** [comment]
You're looking for the `hasManyThrough` relation.  Voyager doesn't currently support this in its UI(and there's no easy way to make it), but you're free to add the relation to your models for the purposes of your site's front-end.  Please refer to the laravel docs for further information on its usage.
