### ISSUE TITLE
Translating voyager to Arabic and Turkish

### ISSUE THREAD

**Issue by mustafa-ramax** [thedevdojo/voyager#1305]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.12
- PHP Version: 5.6.4
- Database Driver & Version:

### Description:
First of all I want to say that I really love Voyager is really amazing, very useful and easy to use, thanks for everyone who worked so hard to bring us this unbelievable invention, and I hope to help with making voyager bigger and better so I'm ready to translate it to Arabic and Turkish but I dont know how and where to start, so how can I start?

**Comment by ghost** [comment]
-1 for arabic

**Comment by mustafa-ramax** [comment]
any advice guys, @marktopper @akazorg , actually I'm free for about 10 days so I want to start translate it

**Comment by akazorg** [comment]
hi @Steve-sy, there's been some discussion about Voyager translations, I think that we will come up with something soon.
All translations are helpful, thanks.

**Comment by marktopper** [comment]
@Steve-sy, we have decided to go with the original translation method for Laravel and not the JSON translations.
If you wish to start on this you are more than welcome 👍

**Comment by akazorg** [comment]
@marktopper maybe we use this PR #1234? It's recent, perhaps with less code conflicts.

**Comment by marktopper** [comment]
Good call @akazorg. Will fix the tests and the merge conflicts and then merge it in.

**Comment by lancepioch** [comment]
Labels: locale, feature, in progress

**Comment by fletch3555** [comment]
Closing for now.  If translations get complete, please open a PR for them
