### ISSUE TITLE
RTL feature

### ISSUE THREAD

**Issue by mustafa-ramax** [thedevdojo/voyager#1308]
- Laravel Version: 5.4
- Voyager Version: 0.11.12
- PHP Version: 5.6.4
- Database Driver & Version: mysql

### Description:
Here is what I got after applying RTL I added this code Voyager::rtl(); , in VoyagerAdminMiddleware.php in the handle function, 

as you can see in the screenshot the navbar still at the left side and the view is not so clear.
https://ibb.co/i1H48F
https://ibb.co/maq2vv

**Comment by lancepioch** [comment]
Labels: design, bug

**Comment by emptynick** [comment]
Is this still an issuen in 1.0.*?

**Comment by fletch3555** [comment]
@Steve-sy, If you can, please re-test on v1.0 and let us know if you're still having issues.  We've made a number of changes since v0.11.12 that affect design and rtl appearance
