### ISSUE TITLE
how can get resized images post in storage/posts ?

### ISSUE THREAD

**Issue by kenshimokak** [thedevdojo/voyager#1310]
Hi
I know that this way can get images : `$model->image` but how can I access to other resized image? 
for example :` img-cropped.jpg` ?

I meant is how can add `[cropped, medium, small ]` into `$model->image` and then showing it in `<img>` tag in view blade ?

Thanks guys

**Comment by kenshimokak** [comment]
I found the solution : 
```
             $img = '.'.pathinfo('storage/'.$model->image, PATHINFO_EXTENSION);
             $imgName = str_replace($img,'', $model->image);
             $img = $imgName.'-cropped'.$img;
```

> and then you can using it in `blade` view like this :  `<img src="{{$img}}" >`

 I hope to help to someone else that have got this problem.

**Comment by fletch3555** [comment]
There either is or should be a helper method for this.  @marktopper / @tnylea  / @akazorg, any thoughts?

**Comment by marktopper** [comment]
We should properly make a helper for this yes.
Any idea for a good helper method name?

**Comment by victorlap** [comment]
Maybe call the helper `voyager_image($path, $modifier = 'default')`

Then have it output a different path based on the modifier?

In this case that would be `voyager_image($model->image, 'cropped')`

**Comment by marktopper** [comment]
Sounds good with me, I am open for pull requests to do this.

**Comment by lancepioch** [comment]
Labels: question, enhancement

**Comment by RavivCohen-BWEBI** [comment]
Is this functionality available?
and if it does how can i interact with it directly from blade?

**Comment by handiwijoyo** [comment]
Voyager `1.0.11` implement Resizable Trait. See: #2422
