### ISSUE TITLE
Unable to access Admin URI in an existing Multi auth project.

### ISSUE THREAD

**Issue by philipmoses1998** [thedevdojo/voyager#1312]
- Laravel Version: 5.4
- Voyager Version: 0.11.12
- PHP Version:7.1.1
- Database Driver & Version:

### Description:
I've added voyager to an exixting multi auth laravel 5.4 project which has sellers and users, guard is used to manage the multi auth. After I installed voyager into the project, when I login into the admin login page, it redirects me to the pages with users permission and does not allow me to access admin URL. Kindly help.

**Comment by fletch3555** [comment]
Sounds like your auth system is set up weird.  I'm going to close this for now since it's fairly old and from and old release of Voyager.  1.0 is a complete rewrite of the auth system, so please try that once it's released and feel free to open a new issue if it's still a problem for you!
