### ISSUE TITLE
How to use bread translate

### ISSUE THREAD

**Issue by sparkosis** [thedevdojo/voyager#1314]
- Laravel Version: 5.4.*
- Voyager Version: LAST
- PHP Version: 7
- Database Driver & Version: last too

### Description:
I would like to know how im suppose to use bread to translate admin area, thanks

**Comment by akazorg** [comment]
Hi @sparkosis, 
Admin translations are not supported at the moment, we are working on that. See #760.

**Comment by sparkosis** [comment]
Hey,

Thank u for ur reply, then im waiting.

When does it coming ? approximately.

i can help to do french translation if needed

**Comment by akazorg** [comment]
Hello, hopefully this week I'll work on that and will let you know.
Thanks for the help.

**Comment by sparkosis** [comment]
Good news then. I have to déploy voyager for my company
