### ISSUE TITLE
Edit BREAD for User not causing changes

### ISSUE THREAD

**Issue by mmickelson** [thedevdojo/voyager#1317]
- Laravel Version: 5.4.24
- Voyager Version: 0.11.12
- PHP Version: 7.0.6
- Database Driver & Version: MySQL

### Description:
Changes made in the BREAD editor UI are not taking effect.

### Steps To Reproduce:
I have added a column "vendor_id" to my User table through migrations (not through the database builder UI) and then extended the User model to include a vendorId function. I then set the Model Name in the BREAD edit UI to use App\User. I don't get any errors when I go to the /users page. I know it is at least looking at what I configured in the edit BREAD UI because if I set a bad value such as a misspelled property name, in the Optional Details field, I will get an error when I try to view /users.

My App\User class extends Voyager's User class like this:
`class User extends \TCG\Voyager\Models\User`

Is there another location to make a change?

**Comment by gileswells** [comment]
This BREAD is one of the few that are already extended for you. Look in resources/views/vendor/voyager/users for the few blade templates. If you wish to stick to the standard add-edit.blade.php you should be able to delete that blade from that folder.

**Comment by mmickelson** [comment]
I see blade templates in vendor/tcg/voyager/resources/views/users. Are you saying I should cut/paste those to resources/views/vendor/voyager/users to customize?

**Comment by gileswells** [comment]
Yes. Sorry I had already done that so I gave slightly bad info. Do that and then you should be good to go. If you want you should be able to grab the default add-edit.blade.php out of the source folder. I think it's under bread but I'm not at my desk right now and that should give you the regular setup to use edit bread and make all your changes.

**Comment by fletch3555** [comment]
Question answered.  Closing
