### ISSUE TITLE
Images cannot be displayed

### ISSUE THREAD

**Issue by rudiroed** [thedevdojo/voyager#1318]
- Laravel Version: 5.4.24
- Voyager Version: 0.11
- PHP Version: 7.1.1
- Database Driver & Version: MySQL 15.1

### Description:
I have an issue about image that cannot be displayed in all the admin panel.
I have tried change `APP_URL = http://localhost:8000` and rebuild symlink with this command `php artisan storage:link` but doesn't work at all.
Can you guys help me???

**Comment by fletch3555** [comment]
We'll need more information before we can help.

1. What is the path shown in your browser when trying to render the images? (open up dev tools and/or view source for the page and find the `href` for the image that's broken)
2. What environment are you working in? Linux vs Windows? local vs remote? if remote, do you have SSH access?
3. You mention you (re)created the symlink.  Can you please show a screenshot of the directory listing (`dir` or `ls -al`) for your `public` folder?

Also, you may get a faster response through our Slack group if you'd like to join.  Instructions can be found in the project Readme

**Comment by karllo** [comment]
@fletch3555 
i have the same error

in windows is ok ,but when i  git clone from github  and in centos7 it went wrong
here are 2 errors:

1.![image](https://user-images.githubusercontent.com/9446682/26962903-fe18b9ce-4d1b-11e7-82c6-141826881527.png)

2. and https didn't work
![image](https://user-images.githubusercontent.com/9446682/26962934-3aa6d006-4d1c-11e7-8766-920a32c1c258.png)
![image](https://user-images.githubusercontent.com/9446682/26962940-492586ae-4d1c-11e7-8783-b97ffb6a1c36.png)

**Comment by fletch3555** [comment]
@karllo that doesn't appear to be the same issue as described above.

@rudiroed, please answer my questions above.
