### ISSUE TITLE
Column not found - v0.11.8 => v0.11.12

### ISSUE THREAD

**Issue by packytagliaferro** [thedevdojo/voyager#1322]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I recently ran `composer update` which ran  `tcg/voyager (v0.11.8 => v0.11.12)` and now my admin panel is broken when I click on pages. I get his error. Looking at the db that did work there is no Order in the data_rows table. Do I need to run some migrations to update?

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'order' in 'order clause' (SQL: select * from `data_rows` where `data_rows`.`data_type_id` = 2 and `data_rows`.`data_type_id` is not null and `browse` = 1 order by `order` asc)
```

**Comment by akazorg** [comment]
Hi @packytagliaferro, check [Release v0.11.10](https://github.com/the-control-group/voyager/releases/tag/v0.11.10).

**Comment by packytagliaferro** [comment]
@akazorg perfect. Forgot to check the release notes

**Comment by akazorg** [comment]
Happy coding :)
