### ISSUE TITLE
i am using voyager admin panel when after sometime i am click on logout  i getting verify csrf token mismatch ,please suggest !!! 

### ISSUE THREAD

**Issue by subodhrawat3344** [thedevdojo/voyager#1323]
- Laravel Version: 5.3
- Voyager Version: ^0.11.12
- PHP Version:
- Database Driver & Version: mysql

### Description:
i am using voyager admin panel when after sometime i am click on logout logout i getting verify csrf token mismatch ,please suggest !!!

**Comment by ghost** [comment]
that's normal if you stay on the same page for a long time and then clicking logout will get you that warning

**Comment by subodhrawat3344** [comment]
@laravelish  how i can remove this warning ?

**Comment by ghost** [comment]
@ritu4455 https://laravel.com/docs/5.4/csrf
read it

**Comment by subodhrawat3344** [comment]
not working .

**Comment by ghost** [comment]
read it again

**Comment by sarath-c-sandwich** [comment]
Check your APP_URL in .env

Make sure the path is http://localhost:8000 or 127.0.0.1:8000

**Comment by lancepioch** [comment]
Labels: invalid
