### ISSUE TITLE
BREAD Search functionality not available for Created BREAD for table

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#1325]
- Laravel Version: 5.4.*
- Voyager Version: dev-master
- PHP Version: 7.0.10
- Database Driver & Version: Mysql 5.7.14

### Description:

BREAD Search functionality available only for Role and User.

### Steps To Reproduce:

would like to have Search functionality on all breads

**Comment by akazorg** [comment]
Hi @donmbelembe, currently the search is only supported when server side pagination is disabled.
We are working on a solution.
Thank you.
