### ISSUE TITLE
List of available settings ?

### ISSUE THREAD

**Issue by chaaban** [thedevdojo/voyager#1326]
- Laravel Version: 5.4
- Voyager Version: 0.11.12
- PHP Version: 7
- Database Driver & Version: mysql

### Description:
Where can i find the full list of admin setting that i can add ?
Currently i found those : admin_title , admin_description , admin_icon_image ,  admin_bg_image, google analytics ?

**Comment by afontcu** [comment]
There is no difference between "admin" and "regular" settings. The `admin_` settings are used by the package developers to set some properties and to allow us to customize them.

You can add as much settings as you want and add them to your public or admin views, but you already found all the available "admin settings".

**Comment by chaaban** [comment]
right , i just thought a list was already available instead of looking into the code and extracting them to modify the backend as i wanted .

Thanks !
