### ISSUE TITLE
Probleme with new Widget in dashboard

### ISSUE THREAD

**Issue by chaaban** [thedevdojo/voyager#1327]
- Laravel Version: 5.4
- Voyager Version: 
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
I'm trying to add a new widget "Customer" in the dashboard , i registered it inside the config/voyager.php and 
`  [
            'name'  => 'Customer',
            'icon'  => 'voyager-news',
            'model' => TCG\Voyager\Models\Customer::class,
            'url'   => 'admin/customers',
            'image' => '/images/widget-backgrounds/03.png',
        ],
`
And : 

`
        'widgets' => [
            'TCG\\Voyager\\Widgets\\UserDimmer',
            'TCG\\Voyager\\Widgets\\CustomerDimmer',
            //'TCG\\Voyager\\Widgets\\PageDimmer',
        ],
`

Also added the file "CustomerDimmer.php" inside **vendor/tcg/voyager/src/Widgets**

Is there something I'm missing ? 

I get this error : 

> (3/3) ErrorException
Undefined index: Customer (View: /var/www/html/vendor/tcg/voyager/resources/views/dimmers.blade.php) (View: /var/www/html/vendor/tcg/voyager/resources/views/dimmers.blade.php)

**Comment by alihassan161820** [comment]
did u find a solution ?
