### ISSUE TITLE
upsize image not working

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#1328]
- Laravel Version: 5.4.*
- Voyager Version: dev-master
- PHP Version: 7.0.10
- Database Driver & Version: Mysql 5.7.14

### Description:
When uploading image with upsize set to true, if the image is greather than my resize limit the image while be resized without any problem but when the image size is less than the resize option the upsize is not doing anything

**Comment by lancepioch** [comment]
Labels: possible bug
