### ISSUE TITLE
Rich text editor doesn't allow all content to be deleted.

### ISSUE THREAD

**Issue by gavinj1999** [thedevdojo/voyager#1331]
- Laravel Version: 5.4.25
- Voyager Version: 0.11.12
- PHP Version:5.6.3
- Database Driver & Version: 10.0.30-MariaDB,

Rich text editor won't save empty content

### Steps To Reproduce:

Created database table
Added Bread
configured form fields

I have a form with a rich text editor, I can add / edit the content but, if I delete all the content and save, the content remains.

Any idea?

Thanks

**Comment by akazorg** [comment]
Hi @gavinj1999,
That is a known bug.

**Comment by gavinj1999** [comment]
thanks for the reply, any workarounds?

**Comment by AdrianKuriata** [comment]
Try to set validation for this field with sometimes and nullable parameters. "sometimes|nullable"

**Comment by akazorg** [comment]
Does that work @AdrianKuriata?
I don't know any workaround atm @gavinj1999 :/ Please let us know if Adrian solution worked out.

**Comment by AdrianKuriata** [comment]
@akazorg i hope it will work, i doing it in laravel when i want save null for any field. When you try save empty field with laravel, into $request this field will not figure so he cant save empty field. When you add sometimes and nullable, sometimes will be present and can be empty and will be only validating when you put something into field. You can set present, this will let you be empty but if ypu add parameter something like min:3 this will be validate so better solution is set sometimes|nullable if your field is not required. Check laravel docs. 

[present](https://laravel.com/docs/5.4/validation#rule-present)
[sometimes](https://laravel.com/docs/5.4/validation#conditionally-adding-rules)

Better check documentation, i bad explained solution, but i did in my projects same i explained. If you want save null, you have to add nullable attribute.

**Comment by akazorg** [comment]
Thank's Andrian, will check that PR asap.
