### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by shahidkarimi** [thedevdojo/voyager#1333]
- Laravel Version: 5.4
- Voyager Version: Latest
- PHP Version: 5.6.x
- Database Driver & Version:
 MySQL 5.7.11
### Description:
Event I put the following code in service provider root() function.

` Schema::defaultStringLength(191);
`

**Comment by AdrianKuriata** [comment]
Do you using homestead?

**Comment by saranshdhingra** [comment]
I can vouch, I am getting the error even after adding the lines:
`Schema::defaultStringLength(191);`

and `use Illuminate\Support\Facades\Schema;`

in `app\Providers\AppServiceProvider.php`


PHP Version: **5.6.19(from WAMP package)**
Laravel Version: **5.4**
Voyager: **^0.11.12**
MySQL Version: **5.7.11(from WAMP package)**

**Comment by AdrianKuriata** [comment]
This solution is for i dont remember exacly but for error 768 bytes? Maybe try set defaultString on 200 or more, i don't have idea...

**Comment by user0018** [comment]
This code `Schema::defaultStringLength(191);` is not working with _1000 bytes_ 
so you need to Alter your table Collation to `utf8_general_ci ` or alter the database Collation to it.

then try to  migrate again

**Comment by saranshdhingra** [comment]
Was reading a discussion on [Laracasts](https://laracasts.com/discuss/channels/general-discussion/syntax-error-or-access-violation-1071-specified-key-was-too-long?page=1)

A user suggested to change the `'engine' => null',` to `'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',` in `config/database.php`

I tried it and nothing else and it worked fine. Maybe others can give it a shot?

**Comment by Tommixoft** [comment]
@supernova13892 IT FUCKING WORKS! thanks. laravel team created post how to fix it based on idea that laravel uses InoDB, while it uses MyISAM hence the fix doesnt work, and when we change to INNODB it works.

**Comment by rmazarei** [comment]
@supernova13892 solution worked for me too.

**Comment by handiwijoyo** [comment]
When you import sql file to older mysql version without run the migrations, you need to change `utf8mb4` to `utf8` and `utf8mb4_unicode_ci` to `utf8_unicode_ci`

**Comment by Lord-Gown** [comment]
its alive!! thanks for that solution to change the database.php file
