### ISSUE TITLE
Date not save in creation

### ISSUE THREAD

**Issue by Maghraby** [thedevdojo/voyager#1334]
- Laravel Version: 5.4.25
- Voyager Version: 0.11.12
- PHP Version: 7.1.5
- Database Driver MySQL & Version: 5.6.32

### Description:
Trying to use BREAD and create record with date, date not saving , but it saved in edit.

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by fletch3555** [comment]
@Maghraby, now that 1.0 has been released, could you please retest?

**Comment by Maghraby** [comment]
@fletch3555 will retest it today.

**Comment by fletch3555** [comment]
Thank you

**Comment by handiwijoyo** [comment]
Close due inactivity
