### ISSUE TITLE
Master Child Form

### ISSUE THREAD

**Issue by Muhammadinaam** [thedevdojo/voyager#1337]
Feature Request:

Please add feature for entering master-child forms (Sale Order Form etc)

Please see the image below for reference:

https://docs.oracle.com/cd/E11882_01/appdev.112/e11945/img/pdf_report_details.gif

**Comment by Muhammadinaam** [comment]
Hello??? will this feature be added in voyager???

**Comment by fletch3555** [comment]
The image you provided doesn't include any context.  "master-child form" is not a term I'm familiar with.

**Comment by Muhammadinaam** [comment]
This is like one entity is master and other entity is child or detail, like in sale order form:

**sale_orders (master table)**
id, date_of_order, customer_id, date_of_delivery.

**sale_order_details (child/detail table)**
id, **sale_order_id**, item_id, qty, rate, amount.

Then form for above two tables is like this:

![image](https://user-images.githubusercontent.com/22542738/28350597-7bbacfd2-6c63-11e7-9fc1-b512205961c3.png)

**Comment by fletch3555** [comment]
So you're requesting that Voyager support a 2 forms on the same page for models that have a relationship between each other?

How would you propose we accomplish this? What use-case does it serve? How do you suggest the UI work?

Voyager already supports relations and customizing views. We have no way of knowing what your data will look like, and leave the view functionality up to the view, so there likely won't be any functionality added to control the layout/appearance of BREAD views.

**Comment by Muhammadinaam** [comment]
@fletch3555 , I thought it were possible to add this feature to voyager as another voyager like package (not as popular as voyagar) has this feature. Please check this link below:

https://github.com/crocodic-studio/crudbooster/blob/master/docs/en/how-to-make-a-child-form.md

By the way, thanks for working on such a nice package like Voyager

**Comment by fletch3555** [comment]
I understand that other package has this feature, but you didn't answer my questions.  What use-case does this solve?

**Comment by Muhammadinaam** [comment]
I wanted to make a simple accounting application. And all forms in accounting application are master child:

1. Sale Invoice
    - Master table / Form will have date of sale invoice and customer id.
    - Detail table / Form will have one or **more** inventory items sold (item, qty, rate, total_amount).

2. Purchase
    - Master table / Form will have date of purchase and supplier id.
    - Detail table / Form will have one or **more** inventory items purchased (item, qty, rate, total_amount).

Sale Order, Quotation, Expense Voucher and so on... There are so many use cases.

**Comment by fletch3555** [comment]
I don't have any plan to add this functionality in the near future as I can't see how we would implement it.  You're more than welcome to override your own views and make it work locally for your project.  If you get it working well, and in an extensible way, I would be open to seeing a pull request for it.
