### ISSUE TITLE
redirect to browse

### ISSUE THREAD

**Issue by joefreire** [thedevdojo/voyager#1339]
how i can do a redirect to browse
i try with
            return redirect()
            ->route("voyager.{$dataType->slug}")
            ->with([
                'message'    => "Successfully Updated {$dataType->display_name_singular}",
                'alert-type' => 'success',
                ]);

but uncessefull

**Comment by akazorg** [comment]
Hey, you didn't provided much information, but I guess that's what you need?

```
->route("voyager.{$dataType->slug}.index")
...
```

This is a Laravel question, not Voyager related.
Closing issue.
