### ISSUE TITLE
Issue-User avatar image is not working on the admin page

### ISSUE THREAD

**Issue by CollinPWindesheim** [thedevdojo/voyager#134]
admin page can't find the image of the user avatar. i don't know what is causing this and i don't know how to fix this.

**Comment by artifexrefercio** [comment]
Not only avatar. I have same problem with all files which i uploaded (admin/media) I can't use this media files in project((

**Comment by crrack** [comment]
I have some problem.

**Comment by taimaiduc** [comment]
Me too

**Comment by marktopper** [comment]
Please let me know the following informations:

1. What Laravel version are you guys using? (You can get it calling `php artisan --version`)
2. Are the avatar located in `storage/app/public/users/`?
3. Are the avatar located in `public/storage/users/`?

This will help me figure out what to do to help you guys.

**Comment by handiwijoyo** [comment]
You need to create symbolic link from "public/storage" to "storage/app/public"

Try run this command:
```
php artisan storage:link
```

**Comment by cotiga** [comment]
Hi
Same problem
Laravel 5.3.23
In public, i don't have storage folder
Thank

**Comment by marktopper** [comment]
@COTIGA: Have you tried what @handiwijoyo said

> Try run this command:
> 
> ```php artisan storage:link```

**Comment by cotiga** [comment]
It's OK
After change the hosting, the installation path was no longer the same, so I first remove the storage symlink in public.
Then the command:
`php artisan storage:link`
has restored everything
Thank you

**Comment by marktopper** [comment]
No problem, just glad it helped.
