### ISSUE TITLE
Where should be the generated controllers?

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [thedevdojo/voyager#1348]
I can't see them on the Controllers folder and I don't see any folder on vendor name "TCG" - Am I doing something wrong or this files would be always hidden?

**Comment by user0018** [comment]
@BrunoMCTeixeira 
the best way is to use the composer `composer require tcg/voyager` _(the best choice)_
(Or clone it and add TCG folder inside vendor folder).

you'll find Controller then in this path `/vendor/tcg/voyager/src/Http/Controllers`

and anything is insinde `vendor/tcg/voyager` path

**Comment by tzs007** [comment]
Try to run on CLI this: `php artisan voyager:controllers` then you can see voyager controllers in Http/Controllers/Voyager which are the clones of vendor and you can hook your own scripts.

If you generated a new database with model you can run this: `php artisan make:controller WhateversController --model=Whatever --resource` Laravel will generate controller based on your generated Model...

**Comment by fletch3555** [comment]
@tzs007, please don't recommend `artisan voyager:controllers` except to override ALL controllers.  Individual controllers can be overridden by changing the controller field in the BREAD.

@BrunoMCTeixeira, Voyager doesn't generate controllers.  Routes created by Voyager's BREAD are handled by Voyager's `VoyagerBreadController`.  If you need custom functionality, you can subclass that Controller class and change the controller setting within the BREAD configuration.
