### ISSUE TITLE
How can I list just the active elements in Pages menu

### ISSUE THREAD

**Issue by frankw1** [thedevdojo/voyager#1350]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.12
- PHP Version: 7
- Database Driver & Version: mariadb

### Description:
When I click on the Pages menu I want to list those items where status is active (Just the actives).
Is it possible? What is the solution?

**Comment by user0018** [comment]
**You can write Active in the search field it will automatically filter the result...
Or you can add dropdown  menu contains (Active and Inactive)
and there's a scope function `scopeActive() `return Active Pages.. you can use it when you chose Active from dropdown**

**Comment by frankw1** [comment]
public function scopeActive($query)
    {
        return $query->where('status', '=', 1);
    }

select class="active-select" id="active-select">
  option value="1">Active</option
  option value="2">Inactive</option
/select>

How can I return with items?

**Comment by user0018** [comment]
that functionality doesn't currently exist in Voyager, 
So you have to create  a `PageController ` and copy the **`index()`** function from **`BreadController`**, and modify it with your code like so This is a `PageController` class

```
> use Illuminate\Http\Request;
> use Illuminate\Support\Facades\DB;
> use TCG\Voyager\Facades\Voyager;
> use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;
> 
> public function index()
>     {
>         /$dataType = Voyager::model('DataType')->whereSlug('pages')->first();
> 
> 
>         // Check permission
>         Voyager::canOrFail('browse_'.$dataType->name);
> 
>         $getter = $dataType->server_side ? 'paginate' : 'get';
> 
>         // Next Get or Paginate the actual content from the MODEL that corresponds to the slug DataType
>         if (strlen($dataType->model_name) != 0) {
>             $model = app($dataType->model_name);
> 
>             $requestlationships = $this->getRelationships($dataType);
> 
>             $dataTypeContent = call_user_func([
>                     $model->with($relationships)->active()->orderBy($model->getKeyName(), 'DESC'),
>                     $getter,
>                 ]);
> 
>             //Replace relationships' keys for labels and create READ links if a slug is provided.
>             $dataTypeContent = $this->resolveRelations($dataTypeContent, $dataType);
>         } else {
>             // If Model doesn't exist, get data from table name
>             $dataTypeContent = call_user_func([DB::table($dataType->name)->active(), $getter]);
>             $model = false;
>         }
> 
>         // Check if BREAD is Translatable
>         $isModelTranslatable = is_bread_translatable($model);
> 
>         $view = 'voyager::bread.browse';
> 
>         if (view()->exists("voyager::$slug.browse")) {
>             $view = "voyager::$slug.browse";
>         }
> 
> 
>         return view($view, compact('dataType', 'dataTypeContent', 'isModelTranslatable'));
>     }
```
define a route for it
Call the function by using Ajax .. or put the dropdown | CheckBox | RadioButton, ... into form to make an request to the action

**Comment by frankw1** [comment]
I created PageController.php that you mentioned and put App\Http\Controllers.
I add these lines plus in php:

><?php
>
>namespace App\Http\Controllers;
>
>use Illuminate\Http\Request;
>use Illuminate\Support\Facades\DB;
>use TCG\Voyager\Facades\Voyager;
>use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;

>class PageController extends Controller
>{
>
>public function index()
> .....
>}

If I create an Active and Inactive posts menu item below Posts instead of dropdown ajax, how can I use this PageControllers.php?

Posts
 - Active Posts /admin/posts
 - Inactive Posts /admin/posts

How can I change the routes? I have to add PageController to bread -> Controller Name section?

**Comment by frankw1** [comment]
Thanks!
