### ISSUE TITLE
blank after admin login

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1351]
- Laravel Version: 5.4
- Voyager Version: 0.10.12
- PHP Version: 7
- Database Driver & Version:

### Description:
i installed voyager clean on laravel now when i log in the screen goes blank and shows Error 500

can anyone help ?

**Comment by user0018** [comment]
the best way is install voyager via Composer.. 

Are you running your Server ? ` php artisan serve`

**Comment by fletch3555** [comment]
@versatilegurung, did you check the laravel or php logs?

**Comment by wzulfikar** [comment]
did you check if `storage` folder is writeable? if not, try execute `sudo chmod -R a+w storage` in your voyager dir

**Comment by nhymxu** [comment]
blank with me too

**Comment by fletch3555** [comment]
We cannot help without more details.  Once the requested details have been provided, we can reopen this to further troubleshoot.
