### ISSUE TITLE
Allow NULL in select dropdown for relation

### ISSUE THREAD

**Issue by knoufal** [thedevdojo/voyager#1353]
- Laravel Version: 5.4
- Voyager Version: v0.11.12
- PHP Version: 7
- Database Driver & Version:

### Description:
I am forced to select a value for foreign key even if it is nullable, first value from parent table always selected in relation select dropdown ...

Regards,

**Comment by knoufal** [comment]
This worked :)

```
{
    "relationship": {
        "key": "id",
        "label": "name"
    },
    "default": "",
    "null": "",
    "options": {
        "": "-- None --"
    }
}
```

**Comment by ateresi** [comment]
## tgc/voyager v1.0.6

The problem persists.

**Comment by fletch3555** [comment]
@ateresi, please open your own issue instead of commenting on ones that have been closed for months.

**Comment by harunthuo** [comment]
@KhalidNoufal how do you use that json?
