### ISSUE TITLE
many to many relationship

### ISSUE THREAD

**Issue by mohammed-elattar** [thedevdojo/voyager#1354]
- Laravel Version: 5.3
- Voyager Version: ^0.11.9
- PHP Version: 5.6.30

I made all steps like in the documentation but i can't get multiple select field and these is the steps in pics , please help me to sort it out

![voyager5](https://user-images.githubusercontent.com/16066732/27251282-23d93188-5344-11e7-9b54-13d2bad3bb13.PNG)
![voyager1](https://user-images.githubusercontent.com/16066732/27251285-23db233a-5344-11e7-846f-916d6d6ef0fa.PNG)
![voyager2](https://user-images.githubusercontent.com/16066732/27251283-23d96806-5344-11e7-957d-70fb6e7f50a0.PNG)
![voyager3](https://user-images.githubusercontent.com/16066732/27251284-23db006c-5344-11e7-8455-5ffc82926d19.PNG)
![voyager4](https://user-images.githubusercontent.com/16066732/27251286-23efd67c-5344-11e7-86bb-4ff1a34796fa.PNG)

**Comment by nunomsh** [comment]
the function name must match the field name
```
public function categoryId()
{
    return $this->belongsToMany(Category::class);
}

```
From documentation: _**"Note: the method used for this relationship, must match the camelCase version of the row from the pages table. "**_

plus you don't need the "image_category" in the model. This is used to relationship 1-to-1, not 1-to-N (I think...) 
Voyager will store the relation in a pivot table, that will relate both tables, and it's usually the name of both tables combined (singular)
So try to create a table with the name **categorie_image** with 2 columns only: 
image_id and category_id

**Comment by lancepioch** [comment]
Labels: question
