### ISSUE TITLE
multilingual and custom controller

### ISSUE THREAD

**Issue by pjeutr** [thedevdojo/voyager#1358]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version:5.6.30

### Description:
I wrote a custom controller and edit-add.blade and everything is working fine, except for translation.
Things go wrong in multilingual.js I debugged the javascript and for some reason `$_val = undefined` when submitting. Posting the translation array with a missing translation `'question1_i18n' => '{"nl":"zon","de":"zon"}',` resulting in an `Undefined index: en ` at the server side.
After some debugging I see things go wrong in de following piece of code at multilingual.js:188
```
            updateInputCache: function(inp) {
                var _this  = this,
                    inpUsr = inp.data('inpUsr'),
                    $_val  = $(inpUsr).val(),
                    $_data = {};  // Create new data
```
I'm not sure where inpUsr is coming from. Maybe I'm missing some magic somewhere. I stripped a lot of the stuff used in the bread controller and am using plain eloquent instead of the dataTypeContent way of passing stuff. Is that a problem?
Can somebody kick me in the right direction?

**Comment by akazorg** [comment]
Hello.

You did hit a bug, if you choose a default language other then `en`, system will break.
There's a missing feature for setting up the default language, we will write a Command for that.

#### Important note
Let's suppose your default language is `nl` for the next examples.

Multilingual will save the default language data at the main table, so, using `pages` table as an example, system will write `nl` records at `pages` table, and the `de` at the `translations` table, respectively.


#### Workaround
1. at [`voyager` config](https://github.com/the-control-group/voyager/blob/master/publishable/config/voyager.php#L117), make sure you have the default language setup to `nl`.

2. open the `translations` table, you should only see the `de` records, if you don't find them, try using the system updating a record and watch for changes, it should work.


If none of this helps, I suggest you to add the `en` language back to the system, and wait for a update that will fix that.

Happy coding!

**Comment by pjeutr** [comment]
Thanks, for looking into it. But that's not the problem. I have `en` as default language and when I use the breadcontroller things work fine.
It's only when I use my own controller, when debugging I got stuck at `inp.data('inpUsr')` I guess the data attribute should be written in the DOM by something, but I can't discover what.

**Comment by akazorg** [comment]
If you have 2 languages available `nl` and `de`, then `en` should not be the default language for the multilingual system. Anyway, it's strange if it works :D
I suggest you to follow the `Post.blade`, it's using a custom view and you can follow the logic.
Good luck.

**Comment by pjeutr** [comment]
Just to set it straight I **have** 3 languages and `en` is the default. The problem was that the selected language was not submitted. So instead of `{"en":"sun", "nl":"zon", "de":"zon"}` this was submitted `{"nl":"zon","de":"zon"}`  

Just found the problem, I had the label between the hidden translation fields and the input fields
And now I see `inpUsr.data` is filled in the refresh function, dunno how I missed that...
Anyway it's working now I moved the label out of the way like this (same as it is used in the Post.blade)

```
<label for="name">Question</label>
@include('voyager::multilingual.input-hidden', [
    '_field_name'  => 'question1',
    '_field_trans' => get_field_translations($question, 'question1')
])
<input type="text" class="form-control" id="question1" name="question1" placeholder="question" 
    value="@if(isset($question->question1)){{ $question->question1 }}@endif">

```

**Comment by akazorg** [comment]
Closing issue since its fixed.
