### ISSUE TITLE
Server-side Pagination On/Off - maybe a BUG

### ISSUE THREAD

**Issue by frankw1** [thedevdojo/voyager#1361]
- Laravel Version: 5.3
- Voyager Version: 0.11.12
- PHP Version: 5.6
- Database Driver & Version: MariaDB

### Description:
When I change the Server-side Pagination status ON and after that I want to turn Off, it's not working because the `data_types`.`server_side` row value still ="1".
If I change this value to 0 everything is OK and the search filed appear.

**Comment by d3n4** [comment]
same issue, not only with server-side pagination
same in all models (if field is empty, value rolled back from previous)

**Comment by akazorg** [comment]
When Server Side pagination is enabled, the search feature is disabled (because it's not implemented yet).

**Comment by frankw1** [comment]
I know this feature. But my problem with the button, when I switch On everything is OK the search field is gone, but I want to turn Off and I want to enable the search feature back it is not possible because the server_side row value doesn't change. 
I have to change it by hand in db.

**Comment by akazorg** [comment]
I see. That must be a bug then.
Thanks for reporting :)

**Comment by akazorg** [comment]
I confirm this an issue.
Preparing PR.
