### ISSUE TITLE
bug report - Undefined property:stdClass::$xxxxx_page_slug

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#1366]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.12
- PHP Version: 7
- Database Driver & Version: x

### Description:
FILE:   /voyager/resources/views/bread/read.blade.php    line 55

@if($item->{$row->field . '_page_slug'}) 
         throw err  Undefined property:stdClass::$xxxxx_page_slug

Below is right .
@if(property_exists($item, $row->field . '_page_slug'))

**Comment by qoalu** [comment]
has this problem just now. Fix tested and works.

**Comment by fletch3555** [comment]
Please open a pull request with this change.
