### ISSUE TITLE
Richtext - tinymce - bug

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#1367]
- Laravel Version: 5.4.26
- Voyager Version: 0.11.12
- PHP Version: 7.1
- Database Driver & Version: MariaDB

### Description:
I am trying to create a new post with image or video but tinymce saves only text and nothing more. I upload an image with tinymce and from firefox i get this error : 
IndexSizeError: Index or size is negative or greater than the allowed amount
and from chrome i get this error:
Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.
    at c.setRng (xxxxxxxxxx/vendor/tcg/voyager/assets/lib/js/tinymce/tinymce.min.js:6:20957)
    at c.select (xxxxxxxxxx/vendor/tcg/voyager/assets/lib/js/tinymce/tinymce.min.js:6:18686)
    at n (xxxxxxxxxx/vendor/tcg/voyager/assets/lib/js/tinymce/plugins/image/plugin.min.js:1:1160)
    at HTMLImageElement.t.onload (xxxxxxxxxx/vendor/tcg/voyager/assets/lib/js/tinymce/plugins/image/plugin.min.js:1:1290)
setRng @ tinymce.min.js:6
select @ tinymce.min.js:6
n @ plugin.min.js:1
t.onload @ plugin.min.js:1

Tried to update tiny mce but nothing happend.
I found out that the image path is in database but it in not shown when there are more than one language active. Translating rich text messes up everything and the fallback in getTranslatedAttributed sometimes work and other not.

### Steps To Reproduce:
Just try to create an new post with image or video

where xxxxx is my domain.

**Comment by d3n4** [comment]
same issue

**Comment by vaggelis2018** [comment]
Images are uploaded but no image path saved.

**Comment by vaggelis2018** [comment]
I found out that the image path is in database but it in not shown when there are more than one language active. Translating rich text messes up everything and the fallback in getTranslatedAttributed sometimes work and other not.

**Comment by vaggelis2018** [comment]
anyone knows whats going on?

**Comment by vaggelis2018** [comment]
The problem was the true flag on  get_field_translations($dataTypeContent, 'body', 'rich_text_box',true). True is for removing html tags but if you remove tags you can't bring it and display it. As a solution i removed true and left it with the default value which is false. The javascript errors never gone (Those errors where on some older versions of tinymce so maybe there is no connection with voyager.) but it look to work great.
@marktopper if you want you can test it and add it to the next version
