### ISSUE TITLE
No default.png found in repo

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [thedevdojo/voyager#137]
`voyager/publishable/database/migrations/2016_01_01_000000_add_user_avatar.php` sets the default avatar for a user, but I didn't actually find default.png in the repo.  Am I missing something?

**Comment by tnylea** [comment]
@ChrisThompsonTLDR Should be in /publishable/demo_content/users/default.png, do you not see an avatar when you login? This actually gets published to your storage directory. Let me know :)

**Comment by ChrisThompsonTLDR** [comment]
So I think the issue will be that we don't utilize the .htaccess files on the server, we do everything in apache configs, so this

```
$this->info("Adding the storage symlink to your public folder");
Artisan::call('storage:link');
```

isn't going to work for us.

**Comment by tnylea** [comment]
`php artisan storage:link` actually creates a symlink from the public folder to your storage folder. It doesn't use .htaccess. Where is your storage folder located or where do you store all your images in your app?

**Comment by ChrisThompsonTLDR** [comment]
`storage` would be where we would store images if we had any.  I'm going to setup a fresh install of Laravel 5.3 and the dev-master of Voyager to make sure I just don't have something out of whack.

**Comment by tnylea** [comment]
Ok, keep me posted :)

Thanks.

**Comment by omer-jan** [comment]
so what is solution  ? i have the same problem

**Comment by fletch3555** [comment]
I doubt its the same problem. This issue was resolved and closex 18 months and 3 fairly significant versions ago.
