### ISSUE TITLE
Lot of problem after install new v0.11.13 🇺🇸

### ISSUE THREAD

**Issue by IProSoft** [thedevdojo/voyager#1373]
- Laravel Version: 5.4
- Voyager Version: v0.11.13 🇺🇸
- PHP Version: 7.0
- Database Driver & Version: X

### Description:
Fresh install and errors with styles and JS
http://scr.hu/3k8r/qypbw
http://scr.hu/3k8r/jhkm1
Font-awesome is not loaded etc. 

### Steps To Reproduce:
Fresha laravel install + voyager install

**Comment by akazorg** [comment]
That's a bug indeed. It's related to another commit.
Will be fixed.
Thanks for reporting that!

**Comment by akazorg** [comment]
Sorry for the confusion, but after publishing vendor files, it's all working ok in here.
I did experienced that bug before, but not now. 
Can you confirm that please?

**Comment by fernandonicacio** [comment]
I was able to solve a problem similar using "php artisan vendor:publish --tag=voyager_assets --force"

**Comment by IProSoft** [comment]
@akazorg fresh install with the same problems
@fernandonicacio unfortunately no change

Example: in app.css we can find require for file
 .../fonts/bootstrap/glyphicons-halflings-regular.woff2
it should be 
.../fonts/glyphicons-halflings-regular.woff2
https://github.com/the-control-group/voyager/blob/master/publishable/assets/css/app.css#L299

**Comment by fernandonicacio** [comment]
@IProSoft I sent the correction in #1376

**Comment by IProSoft** [comment]
Great, thanks!
Another problems:
In compiled file app.css You did not attached assets/css/login.css and login form don't have style like before.

In resources\views\login.blade.php You used script
`document.getElementById('email').focus();`
But email input don't have ID, and I thin it looks better without focus at page enter, but it's only my opinion :-)

**Comment by vaggelis2018** [comment]
1) Problem is that error when you try to add or update a post 
TypeError: n.parser is undefined[Learn More]  app.js:97365:66
It erase title and slug when you move to another language.
and this 
TypeError: e is undefined[Learn More]  app.js:97365:154

2) Second problem is that when you create a new column etc for posts table this column does not shown in edit bread section.

**Comment by akazorg** [comment]
After all, I'm still experiencing this bug.
Thanks for the PR @fernandonicacio, will test it right away.
@vaggelis2018 I confirm point 2. Sollution: delete the BREAD and create a new one, or, in alternative, open the table and add the missing fields.
Will test point 1.

Thank you all :zap:

**Comment by fernandonicacio** [comment]
I have already corrected the problems mentioned by @IProSoft on the login page, I am in doubt if I send the PR or wait a little longer. @akazorg What do you think?

**Comment by akazorg** [comment]
Hi @fernandonicacio, yes please :)

**Comment by fletch3555** [comment]
Some changes were released prematurely in v0.11.13.  v0.11.14 has been released to revert v0.11.13 until it can be resolved permanently.  Please update to v0.11.14 and wait patiently for the next release.  Thank you.
