### ISSUE TITLE
Missing folder "bootstrap" in assets/fonts

### ISSUE THREAD

**Issue by fernandonicacio** [thedevdojo/voyager#1375]
- Laravel Version: 5.4
- Voyager Version: v0.11.13 :us:
- PHP Version: 5.6.28
- Database Driver & Version: MariaDB 10.1.19

### Description:
https://prnt.sc/fmgna6

### Steps To Reproduce:
https://prnt.sc/fmgoo5

**Comment by fletch3555** [comment]
Some changes were released prematurely in v0.11.13. v0.11.14 has been released to revert v0.11.13 until it can be resolved permanently. Please update to v0.11.14 and wait patiently for the next release. Thank you.
