### ISSUE TITLE
External Storage

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#1382]
Hi all, 
i was curious if we were able to store our media to an external storage such as google, and then call them from there. Is it hard to implement this feature? Are there any suggestion or solutions you have to propose?

**Comment by fletch3555** [comment]
It's already possible using [Laravel's filesystems](https://laravel.com/docs/5.4/filesystem).  Just configure the filesystem as you'd like, then change the `storage` key in `config/voyager.php` to use it.

**Comment by vaggelis2018** [comment]
Thanks you very much!
