### ISSUE TITLE
Problem with displaying photos on the server

### ISSUE THREAD

**Issue by SergeyHrulev** [thedevdojo/voyager#1388]
- Laravel Version: 5.4.25
- Voyager Version: 0.11.14
- PHP Version: 
- Database Driver & Version:

### Description:
Then I load photos with new user via admin panel everything is good. I see photo in preview in Users folder and in Media/Users. But then I've published project on server at first time then I've sign in admin panel I saw notification "Lost Simylink" so I've fixed it by submiting notification. After that I tried to sing up a new user but photo is not loaded. In Media/User I saw two photo was uploaded the first one is good an I saw it but the second was damaged and this one was in  `<img src="">`.

Could any body help with it?

**Comment by lancepioch** [comment]
Labels: help wanted, question

**Comment by handiwijoyo** [comment]
Close this due inactivity and older version of Voyager.
