### ISSUE TITLE
Voyager image uploader 

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1390]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7
- Database Driver & Version: MARIA DB 10

### Description:
I need an advice in how to use voyager upload function on the frontend.
It's possible or I need to add intervention/image in composer?

**Comment by AdrianKuriata** [comment]
Try to use asset() function to get a picture link.

**Comment by reficul** [comment]
I don't need picture link, I need to upload images in the front end.

**Comment by fletch3555** [comment]
This is outside the scope and purpose of Voyager.  Voyager is an Admin tool for configuring and adding/editing data related to your site.  It provides a few helpers that make working with it a little easier on the front-end, but does not do the work for you.  For example, there is a `menu()` helper, but you still have to customize the markup/styling for your site.  There may be ways to do it, and you're welcome to ask for help in our Slack group, but we cannot officially support this functionality right now.
