### ISSUE TITLE
the user is keeps logout randomly 

### ISSUE THREAD

**Issue by HassanOumar** [thedevdojo/voyager#1391]
- Laravel Version: 5.4.27
- Voyager Version: 0.11.14
- PHP Version:7
- Database Driver & Version:
mysql
### Description:

When i login to admin panel with the default user "admin@admin.com", it logs in but and shows the dashboard no problem so far, it keeps logout without me login out some times it logs out the very second i request another page from the menu and some times it goes with me for some times (maybe 1 or 2 minutes top) and logs out.

this thing is annoying i have to login every one or two minutes.

**Comment by fletch3555** [comment]
Voyager relies on the built-in Laravel Auth functionality.  Please review the auth configuration and compare against Laravel documentation to make sure you don't have any weird settings.  Associated to this, the auth functionality relies on session cookies, so make sure your browser isn't set to clear it's cookies too often.
