### ISSUE TITLE
Problem images load in Admin panel adter update Voyager

### ISSUE THREAD

**Issue by acidcrash2005** [thedevdojo/voyager#1396]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.0
- Database Driver & Version: MySql 5.5

### Description:
Hello!

I update Voyager Version from 10 to 11. It's all work perfect but I have a problem with images in Admin panel.

In official Voyager document, I read added `APP_URL=localhost:8000` but it does not help and `php artisan storage:link` it does not help too.

In HTML i have Empty `src=""` when in browse.blade.php `<img src="@if( strpos($data->{$row->field}, 'http://') === false && strpos($data->{$row->field}, 'https://') === false){{ Voyager::image( $data->{$row->field} ) }}@else{{ $data->{$row->field} }}@endif" style="width:100px">`

That my admin screenshot! 
![mo_image](https://user-images.githubusercontent.com/11617578/27532230-3804cc8c-5a68-11e7-86b0-4ec5158739d2.png)

Please help me, somebody!

**Comment by fletch3555** [comment]
What is the contents of that field within the database (i.e. through phpMyAdmin)?

**Comment by acidcrash2005** [comment]
`vebinars/April2017/nbrgycyTRrODu2JF4VrY.png` and `vebinars/June2017/58j64ERRLmRbX0MpAAc3.png` but it is not see all images in admin panel, logo, avatars and e.t.

![all vebinars - google chrome 2017-06-27 08 24 39](https://user-images.githubusercontent.com/11617578/27572008-18a82a28-5b12-11e7-8d4f-91460b6628ad.png)

**Comment by acidcrash2005** [comment]
Function `Voyager::image( $data->{$row->field})` return empty in Voyager `browse.blade.php`

**Comment by acidcrash2005** [comment]
I founded!
Function `Voyager::image` use `config('voyager.storage.disk')` but in my ` \config\voyager.php` was 
```
'storage' => [
        'subfolder' => 'public/', // include trailing slash, like 'my_folder/'
],
```
after added ` 'disk' => 'public',` all function done!

```
'storage' => [
        'subfolder' => 'public/', // include trailing slash, like 'my_folder/'
        'disk' => 'public', // include trailing slash, like 'my_folder/'
],
```
