### ISSUE TITLE
Avatar is not working, showing broken images

### ISSUE THREAD

**Issue by Baumgarten2** [thedevdojo/voyager#1397]
- Laravel Version: 5.4.#
- Voyager Version: 0.11.#
- PHP Version: 7.1
- Database Driver & Version:

### Description:
![issue1](https://user-images.githubusercontent.com/24491527/27533541-9e72c704-5a6c-11e7-989a-0938b4f8005b.png)
![issue2](https://user-images.githubusercontent.com/24491527/27533542-9ea5e0e4-5a6c-11e7-8147-563e97f79df3.png)

I've just installed Voyager. And all images do not work. 
### Steps To Reproduce:
I updated .env file:
APP_URL=http://localhost:8000 and tried to change APP_URL run this php artisan storage:link but still not working.

**Comment by jccpdev** [comment]
I ran into the same problem. What I had to do was go and delete the symlink in public/storage and make it again and it worked fine I have had to do that a few times. Next time it happens again ill pay more attention to see why it happens. Hope that works for you.

**Comment by san3jaya** [comment]
I had the same problem. I have to change the APP_URL and clear config cache(`php artisan config:cache`). It works for me

**Comment by Baumgarten2** [comment]
I tried to delete the symlink in public/storage and make it again, change the APP_URL, but it still does not work

**Comment by jccpdev** [comment]
Based on the problem I have, which is similar. I think the issue is on the server config maybe something with file permissions. what are you using to run the laravel project? Vagrant? Docker? Everything installed locally?  Maybe try putting it on a server see if you get the same issue. For me it works locally all the time. But after I do a git pull on the server where I host the site it stops working and I have to delete and re link the file.

**Comment by fletch3555** [comment]
@jccpdev, with your issue, do you have the symlink committed to git?  linux symlinks are specific to the environment they were created, so you shouldn't have them committed to source control,

**Comment by jccpdev** [comment]
@fletch3555 that is probably my problem, I will try that out tonight.

**Comment by JKChen** [comment]
Suppose you are using `la.adminlte.app` as your `ServerName` in your `httpd-vhosts.conf` file like I do, then remember change the value of `APP_URL` from `http://localhost` to `http://la.adminlte.app` in your `.env` file. The real avatar path is actually `public\storage\users\default.png`.
![image](https://user-images.githubusercontent.com/7858123/27911517-deb026d2-628b-11e7-9d15-a7760f6f9fd7.png)

**Comment by max-bertinetti** [comment]
APP_URL must point to your real host:

@Baumgarten2 = laravel.local for you NOT localhost:8000.
@wipflash @jccpdev find your real APP.URL

I have had the same problem using valet: it point do <project.name>.dev in my case...

Hope this is usefull

**Comment by fletch3555** [comment]
@Baumgarten2, I'm assuming your issue was resolved by one of the above comments.  If not, please let me know and we can get this reopened.

**Comment by MN-dev** [comment]
try to use
APP_URL=http://127.0.0.1:8000
instead of
APP_URL=http://localhost:8888

**Comment by omer-jan** [comment]
i have the some problem.changed APP_URL form http://localhost:8888 to http://127.0.0.1:8000 in .env file work for me

**Comment by emptynick** [comment]
That is basically what our README says, yes.

**Comment by ravigunz** [comment]
I have solved this issue on MAMP server.
changed the .env file as
APP_URL=http://localhost:8888/voyager
(voyager is my app name)

**Comment by nanadjei** [comment]
Am having the same problem. am using laravel valet. My url is https://myAppName.app
The application is opening but the images are not showing

**Comment by nanadjei** [comment]
I found my solution. I was including '/public' when calling my images. like so `{{ asset('/public/storage/'.$post->image) }}`

instead of;
`{{ asset('/storage/'.$post->image) }}`

**Comment by Jihun0109** [comment]
1.     delete storage short-link in public directory if it exists.
2.     remake a new link with artisan command (php artisan storage:link)
3.     confirm that the APP_URL={your domain}
4.     php artisan config:cache
5.     re-run the server

It worked for me.
