### ISSUE TITLE
Dashboard Widget Problem

### ISSUE THREAD

**Issue by rttolipas** [thedevdojo/voyager#1399]
- Laravel Version: 5.4.24
- Voyager Version: 0.11.14
- PHP Version:5.6.8
- Database Driver & Version:

I tried to add a **widget on dashboard**. It says in config\voyager.php
 
![dimmer](https://user-images.githubusercontent.com/25500525/27536183-a47aed32-5aa0-11e7-89fb-ec388585f8a8.png)

I paste it in just to add new widget. However, nothing appears neither error message.
I'll appreciate your help. Thank you!

**Comment by fernandonicacio** [comment]
Did you add in the dashboard settings too?

![sdgsdfasfd](https://user-images.githubusercontent.com/1557615/27537312-aff0efe2-5a49-11e7-9240-13ec56a47290.JPG)
![dfghdsf](https://user-images.githubusercontent.com/1557615/27537319-bc43da0c-5a49-11e7-86f4-3e0af8336370.JPG)

**Comment by rttolipas** [comment]
Hi fernandonicacio, yes I added it. But I got this error.

![dimmer2](https://user-images.githubusercontent.com/25500525/27538562-2c6442f2-5aab-11e7-92ab-f9aca7ea1c26.png)

![dimmer3](https://user-images.githubusercontent.com/25500525/27538554-263c0bd0-5aab-11e7-809f-cc0b45ca9630.png)

I don't know if I still need to do some complicated things to make my new widget appears.

**Comment by fernandonicacio** [comment]
You need to create a custom widgets, example: (I created a copy of PageDimmer and it worked correctly)

![fgsdafasd](https://user-images.githubusercontent.com/1557615/27539772-22bbee00-5a54-11e7-8072-45e9b8b82d54.JPG)

**Comment by rttolipas** [comment]
Thank you bro! I'll try this first!

**Comment by rttolipas** [comment]
Sorry bro still not working... tried to copy PostDimmer.php to app\Widgets\ then alter it to TravelDimmer.php, then I also changed the Post names. 
![dimmer7](https://user-images.githubusercontent.com/25500525/27542002-82c6e976-5ab8-11e7-8ceb-bd72cc078f73.png)

Unfortunately, still got this error.

![dimmer5](https://user-images.githubusercontent.com/25500525/27542049-9e4e3956-5ab8-11e7-8244-a25f816d9557.png)

I'm a positive thinker. I believe I'm almost there, maybe I just miss some parts. lol

**Comment by mhuijser** [comment]
Use the 'eloquent way' to do the counting for your model:

Instead of: 

`$count = Voyager::model('Travel')->count();`

You probably need to do:

`$count = Travel::count();`

**Comment by rttolipas** [comment]
![dimmer10](https://user-images.githubusercontent.com/25500525/28103816-62cb0824-670a-11e7-8734-5b807189a508.png)

@mhuijser  just want to know, should I place the Travel.php inside the widget folder?

Still have an error here..

![dimmer11](https://user-images.githubusercontent.com/25500525/28103821-6980f6d8-670a-11e7-8775-6cf649e450f8.png)

**Comment by mhuijser** [comment]
No, Your "Travel" class (Travel.php) should exists in  the App-folder. I think it's enough to add `use App\Travel;` at the top of your TravelWidget.php, just below the namespace-declaration.

**Comment by niyobobo** [comment]
As i think Voyager may be something that is missing is to go into Voyager\src\widget and then create the layout of that TraverDimmer.php where the dimmers from layout will count the number of widget into that directory (src\widget) then create its widget on dashboard

**Comment by lancepioch** [comment]
Labels: help wanted, invalid
