### ISSUE TITLE
Add table parameter when building models while creating database tables

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#140]
I suggest add table name to model when build Bread 

 protected $table = 'xxxxx';

**Comment by marktopper** [comment]
Agreed, since building a model using the database system to create a new table, then it will not work if the table name was for example in singular expression like `post`, then it would try to locate the table at `posts`.

**Comment by marktopper** [comment]
Here is a problem however, it does not seems to be possible using the artisan command to create a model with a defined table.

**Comment by marktopper** [comment]
I have opened an issue at https://github.com/laravel/framework/issues/16561, once that have been fixed I can fix this issue.

**Comment by marktopper** [comment]
Just added a pull request for this on the framework (https://github.com/laravel/framework/pull/16571), hopes it gets merged.
Then merged I will make this a part of Voyager by default.

**Comment by tnylea** [comment]
Closing this issue for now to clean up the v1.0 pre-release milestone. Please feel free to re-open at anytime.
