### ISSUE TITLE
Does Voyager support Laravel 5.5 ?

### ISSUE THREAD

**Issue by pboethig** [thedevdojo/voyager#1401]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by pboethig** [comment]
A feedback would be great. Do have tested it already?

**Comment by fletch3555** [comment]
No, Voyager does not currently support the pre-release version of Laravel 5.5, but that testing is currently in progress.

**Comment by Bonobomagno** [comment]
So there are some plan to pass to 5.5 when it will be out?

**Comment by sonynlaw** [comment]
Yes Voyager 0.11 is support in Laravel 5.5, after fresh installation of Laravel 5.5 then not use this code: composer require tcg/voyager
just use this: composer require tcg/voyager dev-master

**Comment by yabasha** [comment]
What about Voyager v.1.0?

**Comment by fletch3555** [comment]
Voyager 0.11.* supports Laravel 5.3 and 5.4

Voyager 1.0.* supports Laravel 5.4 and 5.5

**Comment by sonynlaw** [comment]
now in Voyager v.1.0, after fresh installation of laravel you have to just follow their github instruction but it has still now some database query 1071 error 
the solution is - go to the `_App > Providers > AppServiceProvider.php_` and set this code

```
_use Illuminate\Support\Facades\Schema;

	public function boot()
{
    Schema::defaultStringLength(191);
}_
```
now erase or set new database table and again use the voyager dammy data by this code
_`php artisan voyager:install --with-dummy`_
thats it, happy coding

**Comment by fletch3555** [comment]
@sonynlaw, that has nothing to do with this issue.  Please try to stay on topic.  Also, this issue is closed, so there shouldn't be any further comments.

**Comment by sonynlaw** [comment]
voyager 1.0 is our long expectation and finally we got it, thanks "the-control-group" and its all member, now we have one last expectation from them, that is a complete tutorial, that will help us (new comer) to solve many issue, thanks
