### ISSUE TITLE
Impossible to update to null Edit BREAD

### ISSUE THREAD

**Issue by guil182** [thedevdojo/voyager#1402]
- Laravel Version: 5.4.23
- Voyager Version: 0.11.14
- PHP Version: 7.0.15
- Database Driver & Version: mysql 5.6.35

### Description:
Impossible to update to null Edit BREAD

### Steps To Reproduce:
I created a bread on a new table with a varchar(50) type field. I put "xxx" and save. All is ok.
I make a mistake and want to update the field to null. So i edit the table bread and erase the field entry and save.
But after saving, the field is always with the old value !

Best regards

**Comment by MonstreX** [comment]
You can make some trick:
1) Find code line in \vendor\tcg\voyager\src\Http\Controllers\Controller.php:
if (is_null($request->input($row->field)) && isset($data->{$row->field})) { ....
2) Modify "if" case like this:
                if (is_null($request->input($row->field)) && isset($data->{$row->field})) {
                    if(!isset($options->default) || !empty($options->default)) {
                        $content = $data->{$row->field};
                    }
                }
3) Add to BREAD field options json code: {"default": ""}

It won't return old value if default json option is present.

**Comment by guil182** [comment]
Perfect !
Thank you very much

**Comment by fletch3555** [comment]
This happens because of a new middleware that ships with Laravel 5.4 (`\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull`).  Disabling that middleware will get you the behavior you're looking for.  There is nothing Voyager can reasonably do about it.

**Comment by froasiooneloop** [comment]
Hi, I removed the middleware from Kernel.php, but it didn't work. Should I do something else?

**Comment by xaviqv** [comment]
Hi @froasiooneloop If you still have this unsolved, notice it is resolved in PR #2377 although it's not yet merged. It is actually a bug in Voyager src/Http/Controllers/Controller.php . I explained it in a own PR #2908 that is in fact a duplicate of the first one.
