### ISSUE TITLE
Dropdown not relation voyager

### ISSUE THREAD

**Issue by guil182** [thedevdojo/voyager#1403]
Laravel Version: 5.4.23
    Voyager Version: 0.11.14
    PHP Version: 7.0.15
    Database Driver & Version: mysql 5.6.35

### Description:
i want to update the table with a dropdown not related to a database table, a simple list (ex : little, normal, big)  how to do this ?

2 - i would like a countries dropdown link to the Symfony\Component\Intl\Intl
$countries = Intl::getRegionBundle()->getCountryNames();

how to do this ?

thank you for your help.

Best regards

**Comment by akazorg** [comment]
I think you want to accomplish something like the [post/edit-add.blade.php](https://github.com/the-control-group/voyager/blob/master/resources/views/posts/edit-add.blade.php#L169).

You can have a Country Model without having a table, and then you can use:
```
@foreach(App\Models\Country::all() as $country)
    <option value="{{ $country->id }}">{{ $country->name }}</option>
@endforeach
```
Good luck!

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please open a new issue.
