### ISSUE TITLE
Absolute path menu builder

### ISSUE THREAD

**Issue by guil182** [thedevdojo/voyager#1406]
Laravel Version: 5.4.23
Voyager Version: 0.11.14
PHP Version: 7.0.15
Database Driver & Version: mysql 5.6.35

### Description:
The path in the menu builder is link to the server root and not to the laravel installation folder

### Steps To Reproduce:
in my .env : 
APP_URL=http://localhost:8888/wineos/public

I created a new menu with the URL for the menu item : /

And the link created is http://localhost:8888 and not http://localhost:8888/wineos/public   :/

regards

**Comment by guil182** [comment]
Solve .

Don't begin the URL with / and the relative path is ok !

**Comment by RyanAtregenio8** [comment]
what relative path means ? in 0.11.14 update?
