### ISSUE TITLE
Change datepicker locale

### ISSUE THREAD

**Issue by mhemrg** [thedevdojo/voyager#1407]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
How can I change locale option of the datepicker that has been used in Voyager?

**Comment by akazorg** [comment]
Hi @mhemrg.

We need to work on that, and for any other JS component requiring i18n.

We have to edit each blade where JS components are initialized, and set the locale.
This should be easy task.
Fell free to send a PR for this! :)

Thank You.

**Comment by emptynick** [comment]
Added in #1199
Use with a format as in [strftime](http://www.php.net/strftime)

**Comment by akazorg** [comment]
Thanks @emptynick . 
Closing issue.
