### ISSUE TITLE
altered json string format after removing image from multiple image type field

### ISSUE THREAD

**Issue by webber-ch** [thedevdojo/voyager#1414]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1

The remove function in VoyagerMediaController.php at line 283 should invoke the array_values function after flipping the fieldData array in order to avoid an indexed json string as a result. However, this does not provoke instant misfunctional behaviour. But after having removed an image from a multiple image field type the result is no more a single dimensional json-string but an indexed json-string which may lead to problems depending on how the multiple images json string is used in a front end application.

Thus, I would suggest changing line 283 accordingly:

`$data->{$field} = json_encode(array_values(array_flip($fieldData)));`

**Comment by fletch3555** [comment]
@tschmidiger, you're welcome to create a PR for this.

**Comment by lancepioch** [comment]
Labels: bugfix, bug, discussion, in progress
