### ISSUE TITLE
error trying to create tags module

### ISSUE THREAD

**Issue by david-dacruz** [thedevdojo/voyager#1419]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version: xampp & mysql

### Description:

Whoops, looks like something went wrong.
(1/1) FatalErrorException
Cannot access empty property
in 6435810b05c9b352b45d0a6204502fb752e4083b.php (line 65)

### Steps To Reproduce:

I wanted to create tags that acted like the categories module i voyager so i reproduced the bread from categories and i could create one tag then i couldn't go back to /admin/tags i get this FatalErrorException

Can someone shed some light thanks ahead.

**Comment by mansi-addweb** [comment]
![screenshot from 2017-08-10 13-53-50](https://user-images.githubusercontent.com/29626626/29161751-efe70e94-7da6-11e7-8934-e55da31cd014.png)

**Comment by david-dacruz** [comment]
Thanks I will try !

**Comment by lancepioch** [comment]
Labels: in progress

Close (no more user issues reported)
