### ISSUE TITLE
Custom Controller

### ISSUE THREAD

**Issue by rodrigoweber** [thedevdojo/voyager#1420]
- Laravel Version: 5.4
- Voyager Version: last
- PHP Version: 7
- Database Driver & Version: MYSQL

### Description:
I can edit controller of some bread?

For example, i want create order_by or show date by some colum of my table...
I try create with voyager:controllers but i dont understand  the error: "namespace must start with application namespace.." What is application? My folder of laravel?

Thanks...

**Comment by zietbukuel** [comment]
Inside `config/voyager.php` I changed this:

```php
'controllers' => [
    'namespace' => 'TCG\\Voyager\\Http\\Controllers',
],
```

To this:
```php
'controllers' => [
    'namespace' => 'App\\Http\\Controllers\\Voyager',
],
```

Then I ran:
`php artisan voyager:controllers`

And it worked just fine.

**Comment by fletch3555** [comment]
Please don't run `artisan voyager:controllers` unless you NEED to override ALL controllers.  Instead, you should subclass the controller and override only what you NEED to, then change the controller through the BREAD configuration.

**Comment by zietbukuel** [comment]
That should be mentioned in the documentation.

**Comment by fletch3555** [comment]
I agree completely @zietbukuel.  We're always open to pull requests.

**Comment by rodrigoweber** [comment]
Thanks guys.

**Comment by desarrollo-fimlm** [comment]
A complete example of this please

**Comment by ljfreelancer88** [comment]
Hi, I have a multiple input(checkbox) with the same name in array, but voyager saved only the first value on the input. I want to overwrite only the save and update methods in Controller but I don't know what is the best approach to do. I red the documentation, but it seems incomplete.

**Comment by lancepioch** [comment]
Labels: documentation, discussion, question, help wanted, open for suggestions

**Comment by vonec** [comment]
php artisan voyager:controllers copies all base controllers to whatever namespace provided, re running is not unlinking old files, need more documentation and commands for it

**Comment by fletch3555** [comment]
We recommend against using that command for that very reason.  Yes, The docs need to be updated.

**Comment by wadleo** [comment]
What if you want to override the VoyagerAuthController? How can one go about this?

**Comment by fletch3555** [comment]
I would like to know why you'd want to do that.  Off the top of my head, I'm not sure how you'd do that, but I'm sure there's a way (likely just extending it with your own, then overriding the appropriate route(s))

**Comment by wadleo** [comment]
okay, thanks @fletch3555  for the lead, I want to extend the Voyager AuthController and override some methods.

**Comment by fletch3555** [comment]
Yes I understood that much.  But what functionality are you looking to override?  I ask because there may be an easier way.

**Comment by wadleo** [comment]
@fletch3555 I want to override the postLogin and register methods, from one of your replies above, I was able to do that yesterday, thanks for the help.

**Comment by lpcastrov** [comment]
Go to
vendor/tcg/voyager/src/Commands/ControllersCommand.php

And comment 

//        if (!starts_with($namespace, $appNamespace)) {
//            return $this->error('The controllers namespace must start with your application namespace: '.$appNamespace);
//        }

them change
$location = str_replace('\\', DIRECTORY_SEPARATOR, substr($namespace, strlen($appNamespace)));

to

$location = '\Http\Controllers\Voyager';

After that run the command

artisan voyager:controllers

Finally change de Namespace correctly in all the new child controllers to

namespace App\Http\Controllers\Voyager;

**Comment by fletch3555** [comment]
Please don't recommend people change files under vendor.

Also, this has been closed for over a year and was for a MUCH older version that's no longer supported.  Please avoid commenting on old/closed issues.
