### ISSUE TITLE
Js errors in Safari

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [thedevdojo/voyager#1422]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 5.6.4
- Database Driver & Version: MYSQL
- Mac OS Version: 10.5.9
- Safari Version: 9.1.3

### Description:

All CRUD commands with content don't work in Safari (Mac OS). After clicking  Add, Edit etc -  the empty screen. BREAD editing in Safari is ok, as well CRUD in Chrome and FF. 

JS-console show errors like "SyntaxError: Unexpected identifier 'compositeColumns'", "SyntaxError: Unexpected identifier 'newName'" etc

Thanks

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by handiwijoyo** [comment]
I run Voyager `1.0` and Safari `11.0` and working fine. Please open new issue if you still have this problem.

**Comment by hooch** [comment]
@handiwijoyo The current version of Voyager is 1.1, not 1.0.  Version 1.1 still doesn't work in Safari or Edge, even though fixes have been committed and PRs accepted months ago.

**Comment by fletch3555** [comment]
@hooch, that comment is a year old... Please open a new issue if that's still a problem
