### ISSUE TITLE
Users BREAD page doesn't update

### ISSUE THREAD

**Issue by vanvanni** [thedevdojo/voyager#1427]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 7.1.6
- Database Driver & Version: MySQL

### Description:
Where you can edit and add a user to the system the field I updated into the table via the Database manager in Voyager doesn't show up.  I tried to re-create the BREAD but that only fixed that the field show up in the table at the users page.

By trying to add or edit a user I do not see my new created fields while they do show up when I press 'View'.

**Comment by akazorg** [comment]
Check the permissions.

**Comment by fletch3555** [comment]
`Users` has custom views: https://github.com/the-control-group/voyager/tree/master/resources/views/users

You will need to override the views (check docs for help) to display the new field(s)

**Comment by vanvanni** [comment]
@fletch3555 Is there anyway to override it like the other tables. So it will automaticly updates? So I do not need to do it everytime manually

**Comment by fletch3555** [comment]
@xJoeyv, if you override a view, you will always need to confirm that it still works after updating.  Unfortunately, there's no (easy) way to partially "extend" a view in a manner similar to php classes.
