### ISSUE TITLE
[BUG] Cannot create new Post

### ISSUE THREAD

**Issue by roquie** [thedevdojo/voyager#1428]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version: sqlite3

### Description:

I cannot to create post after voyager installation, if I did not fill following fields: `title`, `excerpt`, `meta_keywords`, `meta_description`. After push the "create post" button, I got database error, with message "field :name cannot be null".

![screen shot 2017-07-02 at 15 31 19](https://user-images.githubusercontent.com/3214290/27769803-d16ca29c-5f3a-11e7-9b91-2e957a3cb6f5.png)

### Steps To Reproduce:

For reproduce needs to install package use default instruction, but you should use sqlite database as driver:

1. `laravel new test-bug && cd test-bug`
2. `composer require tcg/voyager`
3. `touch database/database.sqlite`
4. `.env` file:
```
DB_CONNECTION=sqlite
DB_HOST=localhost
#DB_DATABASE=homestead
DB_USERNAME=homestead
DB_PASSWORD=secret
```
5. After add Voyager service provider inside `config/app.php`, run `php artisan voyager:install --with-dummy`
6. `php artisan serve` and then go to admin page -> posts -> create new post, type `lorem ipsum dolar sit amet` to the post body.
7. You got error.

### How to fix:

1. Create new migration and updates database fields to use nullable option (`->nullable()`).
2. Validation of post create request, if fields require to the fill it.

**Comment by azatTemirbek** [comment]
excert is null give some content to it or change not null to fase in admin/database/post or in sql table

**Comment by lancepioch** [comment]
Labels: invalid
