### ISSUE TITLE
How to add default value to relationship dropdown menu

### ISSUE THREAD

**Issue by leonelngande** [thedevdojo/voyager#1429]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I have tried
{
    "default": "",
    "null": "",
    "options": {
        "": "-- None --"
    },
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
 as done in the categories bread but i get an error message when i try to access the route of the resource

**Comment by lancepioch** [comment]
Labels: invalid

Close (not enough information)

**Comment by fletch3555** [comment]
@leonelngande, all fields are required.  Please fill them out and test in v1.0 then reopen if necessary
