### ISSUE TITLE
Translating Voyager to Russian 

### ISSUE THREAD

**Issue by EvgeniyPolyakov** [thedevdojo/voyager#1430]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 5.6.10
- Database Driver & Version: mysql

### Description:

Thanks a lot for the great work! I will be happy to translate Voyager to Russian. Just let me know when to start :) Best wishes

**Comment by akazorg** [comment]
Hi @EvgeniyPolyakov,

Please follow the instructions in #1364.
I'm looking forward to merge Russian translations.

Thank you!

**Comment by marco-solare** [comment]
@EvgeniyPolyakov yes, great, do it! :)
I did the german one it is big fun to see more and more languages comin' in, a couple of weeks ago it was only english now we already have en/es/de/pt/pt_br
