### ISSUE TITLE
Cannot change stuffs under "Edit" via "Edit BREAD"

### ISSUE THREAD

**Issue by nudgetman** [thedevdojo/voyager#1432]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 5.6.30
- Database Driver & Version: MariaDB

### Description:

I cannot edit any BREAD and see the changes in "Edit" view. I can go into "Tools" > "Database" and click "Edit BREAD" and edit the stuffs there but I can't see the changes when I go to the specific "Edit" view in the menu. For example, if I were to edit "Posts" and change the Display Name of "excerpt" to "Description" and from "Text Area" to "Rich Text Box", I would still see it in the "Edit" page as "excerpt" and not "Description" and it would still be Text Area and not Rich Text Box.

However, the settings are saved because if I were to save it and move elsewhere and reedit the bread, I can see the changes I made. I can also see it in the list view when I'm browsing. So the "browse" section works, the saving bit works but I cannot change anything within the "Edit" view.

Is this normal or am I doing something wrong?

Thanks guys! 😄

**Comment by fletch3555** [comment]
It's perfectly normal.  You're editing fields through the BREAD editor, which are then used in the associated view.  Voyager will try to find a view specific to the type and action you're visiting (i.e. `posts/edit-add.blade.php` or `users/browse.blade.php`).  In the absence of this type-specific view, it will load the generic BREAD action view (i.e. `bread/browse.blade.php`).  For the example you provided, Voyager includes a "custom" type-specific view, which isn't fully making use of the BREAD configuration (https://github.com/the-control-group/voyager/blob/master/resources/views/posts/edit-add.blade.php), so you will need to override this view and include your change.

**Comment by nudgetman** [comment]
Thank you! 😄
