### ISSUE TITLE
Upload image at post image doesn't work

### ISSUE THREAD

**Issue by dker92** [thedevdojo/voyager#1436]
- Laravel Version: 5.4.10
- Voyager Version: : 0.11.14
- PHP Version: 7.0
 
 
The upload image at the edit post  doesn't work , it give me a HTTP ERROR 500 ,  when i change the input type of image to multiples images it doesn't give me an error but it didn't upload and write in the database under image "[]" 
I can upload images in media . I try to unlink the symslink of public/storage and run php artisan storage:link to no avail.
The insert/edit image from the post content not working either 
 Any help ?

**Comment by ghost** [comment]
@davidker92 have you found any solution?

**Comment by dker92** [comment]
@salvisb No

**Comment by ghost** [comment]
I had similar issue (Laravel 5.5, Voyager 1.0.6, PHP 7).
I could upload image in media, but not when insert / edit posts or pages.

`composer update` ( Voyager got updated from 1.0.6 => 1.0.7)  solved this for me, but I didn't quite understand what was the real cause.
