### ISSUE TITLE
Renaming Tables

### ISSUE THREAD

**Issue by Reaper45** [thedevdojo/voyager#1439]
- Laravel Version: 5.4
- Voyager Version: #.#.#

### Description:

I think its  a good idea to rename the voyager table, probably add a prefix `voyager_` to every table name.
I tried installing to an existing project and i had conflicts with some of the table names e.g `posts` which already existed in my project.

**Comment by fletch3555** [comment]
This has already been discussed and will likely be included in a 1.0 release.  We can't include it any sooner as it would introduce backwards-incompatible/breaking changes.

**Comment by AlexStack** [comment]
I think add a prefix voyager_ is a very good idea, +1

**Comment by OGProgrammer** [comment]
+2

**Comment by wardloockx** [comment]
+3, any news when it will arrive?
