### ISSUE TITLE
Language selector not showing!

### ISSUE THREAD

**Issue by mustafa-ramax** [thedevdojo/voyager#1440]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 5.6
- Database Driver & Version:

### Description:
I've activated the mutlilanguges option from the voyager.php like the following: 

    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'ar',
        ],
    ],``

Also I've activated multilanguage in app.php like the following:

`
    'locale' => 'en','ar',`

### Steps To Reproduce:
Should I do anything else?

**Comment by akazorg** [comment]
Hi @Steve-sy,

I believe the `locale` accepts a string and not an array. So, you should use `'locale' => 'ar',` or `'locale' => 'ar',`.
After enabling multilingual we should see the language selector. By default, Voyager has multilingual support on Menu, Posts, Pages and Categories.

Maybe try to clear your views from cache: `php artisan view:clear`.

I hope this help you.

**Comment by mustafa-ramax** [comment]
Unfortunately nothing happened! still without no multilingual support, I have a project that I'm working on it using voyager, Please help me @akazorg  I dont know what to do to bring that language switcher!

**Comment by akazorg** [comment]
Hey @Steve-sy, try to reach me at Slack channel, I will help you.

**Comment by akazorg** [comment]
Hi @Steve-sy, did you got it to work?

**Comment by akazorg** [comment]
I'm closing the issue since this feature is working. Feel free to reopen it.

**Comment by almokhtarbr** [comment]
hey guys , what the solutions for 
Language selector not showing! #1440 ?

**Comment by fletch3555** [comment]
@almokhtarbr, this has been closed for nearly a year and was for a much older version.  Please open your own issue or ask on our Slack group if you're still having issues.
