### ISSUE TITLE
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by JKChen** [thedevdojo/voyager#1442]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version:7.1.6
- Database Driver & Version:mysql  Ver 14.14 Distrib 5.7.12, for Win32 (AMD64)

### Description:
`Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` in console of almost every admin page.
e.g  Dashboard
![image](https://user-images.githubusercontent.com/7858123/27907648-21b667ea-627b-11e7-9c29-117fbd646dc1.png)

### Steps To Reproduce:
Follow all steps in document of [getting-started-installation](https://laravelvoyager.com/docs/0.11/#getting-started-installation).

**Comment by fletch3555** [comment]
Those are keywords specific to ES2015+.  We had a number of changes sneak into a release prematurely.  Please try setting up webpack and running `npm run dev` to compile the scripts down to a valid version.

**Comment by JKChen** [comment]
Thank you for your reply. I'll try later.
