### ISSUE TITLE
How can I get custom data from the relation?

### ISSUE THREAD

**Issue by alexelev** [thedevdojo/voyager#1443]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
I want the Category cell to display the category title of the post. But instead I get the id. How can I fix that? 
The example-data are generated when installed `--with-dummy` flag.  

This is my "Browse" window
![01](https://user-images.githubusercontent.com/3392106/27922465-c9d24932-6283-11e7-8eef-bfa753e53d72.jpg)
And this is my post's BREAD window
![02](https://user-images.githubusercontent.com/3392106/27922481-d7c31f44-6283-11e7-814f-b33bc3ccc992.jpg)

**Comment by sokeno** [comment]
This was addressed #941 and i was helped too

**Comment by alexelev** [comment]
Thank you, this solution is really effective - the problem is solved. Surprised that this is not written in the documentation.
![screenshot_238](https://user-images.githubusercontent.com/3392106/27934741-d0b9a584-62af-11e7-9a54-1f3ea2c65feb.jpg)
