### ISSUE TITLE
Report bug: when add action, throw undefined property

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#1445]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 7.0.2
- Database Driver & Version:

### Description:
table article         $this->belongsTo(Category::class, "categoryid", "id")
table category

> $relationshipClass = $dataTypeContent->{camel_case($row->field)}()->getRelated();
>                 if (isset($options->relationship->where)) {
>                     $relationshipOptions = $relationshipClass::where(
>                         $options->relationship->where[0],
>                         $options->relationship->where[1]
>                     )->get();
>                 } else {
>                     $relationshipOptions = $relationshipClass::all();
>                 }

All action(read, update, delete) is ok, except add . when first add an article,  select_dropdown  is error,   $dataTypeContent not contain categoryid,   so can not find a fit relationship .

when I define categoryList in Class Article , everything is ok.  But this is another way. i want to know
how to get relationship when first add.

**Comment by OliverVin** [comment]
### throw err -  select_dropdown.blade.php
> @if(isSet($dataTypeContent->{$row->field}) && !is_null(old($row->field, $dataTypeContent->{$row->field})))

### below is ok. !!!
> @if(property_exists($dataTypeContent, $row->field) && !is_null(old($row->field, $dataTypeContent->{$row->field})))

is PHP7 diffent ?

**Comment by OliverVin** [comment]
Yeah, I found what happend . 
I add this code into model , everything is ok.

>     public function __get($key)
>     {
>         if (isset($this->attributes[$key])) {
>             return $this->attributes[$key];
>         }
>     }
> 
>     public function __isset($key)
>     {
>         if (isset($this->attributes[$key])) {
>             return true;
>         }
>         return false;
>     }

Maybe, 

PHP 7 has fixed a bug with __isset which affects both the 
native isset and empty methods. This causes specific issues 
with checking isset or empty on relations in Eloquent. In 
PHP 7 checking if a property exists on an unloaded relation, 
for example isset($this->relation->id) is always 
returning false because unlike PHP 5.6, PHP 7 is now 
checking the offset of each attribute before chaining to 
the next one. In PHP 5.6 it would eager load the relation 
without checking the offset. This change brings back the 
intended behavior of the core Eloquent model __isset method 
for PHP 7 so it works like it did in PHP 5.6.

For reference, please check the following link, 
specifically Nikita Popov's comment (core PHP dev) - 
https://bugs.php.net/bug.php?id=69659

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please open a new issue.
