### ISSUE TITLE
Bug : Voyager + TinyMCE codesample Plugin

### ISSUE THREAD

**Issue by fjourdren** [thedevdojo/voyager#1446]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 5.6.24
- Database Driver & Version: Mysql 10.1.16-MariaDB

### Description:
I installed the CodeSample plugin to publish some posts about development but when I use "?>" in my content, Voyager don't show the code in edit post page. In spite of "pre" and "code" balises, php code looks to be interpreted.

### Steps To Reproduce:
- Install codesample plugin in TinyMCE (plugins: [
        'advlist autolink lists link image charmap print preview hr anchor pagebreak',
        'searchreplace wordcount visualblocks visualchars code fullscreen',
        'insertdatetime media nonbreaking save table contextmenu directionality',
        'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc'
    ],).
- Create a new post and insert this code in a sample code `<?php
echo "test";
?>`
- Save post
- The code will be save in database but is not show in edit post

**Comment by apiaget** [comment]
I encounter the same problem. I also tested with TinyMCE 4.6.4 and the problem is still here.

**Comment by apiaget** [comment]
It appeared that the content is escaped, and, by one way or another, tinyMCE removes the code. For a temporary fix, I edited the voyager view for the rich text box and used the function `htmlentities` around my text :
File I modified : `my_laravel_project/vendor/tcg/voyager/resources/views/formfields/rich_text_box.blade.php`
```
<textarea class="form-control richTextBox" name="{{ $row->field }}" id="richtext{{ $row->field }}">
    @if(isset($dataTypeContent->{$row->field}))
        {!! htmlentities(old($row->field, $dataTypeContent->{$row->field})) !!}
    @else
        {{old($row->field)}}
    @endif
</textarea>
```
I may add that this is maybe not the best answer, but as a temporary fix, maybe it can help you. And if anybody else has something better to propose, I will appreciate it.

**Comment by fjourdren** [comment]
@apiaget Your temporary fix do not work for me. Nice try :confused:

**Comment by lancepioch** [comment]
Labels: possible bug, help wanted

**Comment by emptynick** [comment]
It is now possible to customize TinyMCE with Voyager `1.1.x` 
https://voyager.readme.io/docs/tinymce

**Comment by nicat-eliyev** [comment]
Guys please help me how to fix this problem ??? when I use "?>" in my content, Voyager don't show the code in edit post page.
Create a new post and insert this code in a sample code <?php echo "test"; ?>
Save post
The code will be save in database but is not show in edit post and client side. please help how to fix it ???

**Comment by nicat-eliyev** [comment]
some variables and javascript code not showing in client side too what is happening ? terrible framework !!! why developers dont fix it ?  what a problem ???

**Comment by emptynick** [comment]
This issue is very old. Please open your own if you think you found a bug.
Also your issue is unrelated to this issue.
