### ISSUE TITLE
automatically pick the current user and not pick from the dropdown

### ISSUE THREAD

**Issue by sokeno** [thedevdojo/voyager#1449]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version:

### Description:
Hi all, i would like the controller to pick the current user automatically other than the normal way where you specify a relationship and add option on the select dropdown.Kindly help

**Comment by fletch3555** [comment]
You would need to override part of Voyager (Controller? View(s)? not sure) to do this.  This is likely not something we will be supporting in Voyager Core any time soon.
