### ISSUE TITLE
Filed type: multiple_images is missing some code

### ISSUE THREAD

**Issue by BakuDev** [thedevdojo/voyager#1453]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
File: voyager/src/Http/Controllers/Controller.php 
Line: 178 (after $filePath variable)
Add code:

```
$options = json_decode($row->details);

                        if (isset($options->resize) && isset($options->resize->width) && isset($options->resize->height)) {
                            $resize_width = $options->resize->width;
                            $resize_height = $options->resize->height;
                        } else {
                            $resize_width = 1800;
                            $resize_height = null;
                        }
```

### Steps To Reproduce:

Otherwise, it will not process resizing and any other options defined in "Optional details" like:

```
{
    "resize": {
        "width": "800",
        "height": "600"
    },
    "quality": "85%",
    "upsize": true,
    "thumbnails": [
        {
            "name": "medium",
            "scale": "50%"
        },
        {
            "name": "small",
            "scale": "25%"
        },
        {
            "name": "thumb",
            "crop": {
                "width": "250",
                "height": "250"
            }
        }
    ]
}
```

**Comment by fletch3555** [comment]
For future reference, code changes are better suited as pull requests, not issues.

For this instance, I believe this has already been fixed in an unreleased version.  Please test using `dev-master` as the Voyager version in composer.json

**Comment by lancepioch** [comment]
Labels: enhancement

Close (issue resolved)
