### ISSUE TITLE
Multiple_images input type garbage collection

### ISSUE THREAD

**Issue by BakuDev** [thedevdojo/voyager#1454]
- Laravel Version: #.#.#
5.4
- Voyager Version: #.#.#
0.11.14
- PHP Version:
5.7
- Database Driver & Version:
MySQL 5.7
### Description:
Try after fixing #1453
After multiple images has been uploaded, if you start deleting 'em in editor they will remain in the folder with uploaded files as well as their thumbnails.

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by fletch3555** [comment]
@BakuDev, please test in the newly released v1.0 and reopen if necessary
