### ISSUE TITLE
No vendor folder created under resources/views folder

### ISSUE THREAD

**Issue by neilworley** [thedevdojo/voyager#1455]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.*
- PHP Version: 5.6.30
- Database Driver & Version: mySQL 10.1.21-MariaDB

### Description:
I wanted to override the built in views and followed instructions however there was no vendor directory under resources/views. 
Overriding Views

You can override any of the BREAD views by creating a new folder in resources/views/vendor/voyager/slug-name and slug-name will be the slug that you have assigned for that table. There are 2 files that you will include in each which will be:

    browse.blade.php
    edit-add.blade.php

By default a couple posts views have been published to your resources/views/vendor/voyager folder. So those 2 view files will be located at resources/views/vendor/voyager/posts/browse.blade.php and resources/views/vendor/voyager/posts/edit-add.blade.php.

**Comment by fletch3555** [comment]
Apologies. That part of the documentation is out of date. We no longer publish those views since it was causing issues for people when updating.  You're welcome to create the `vendor` directory yourself. There's nothing special about it.
