### ISSUE TITLE
Voyager/Eloquent relationships are conflicting

### ISSUE THREAD

**Issue by mdelally** [thedevdojo/voyager#1459]
- Laravel Version: 5.4.27
- Voyager Version: 0.11.14
- PHP Version: 7.1.2
- Database Driver & Version: MySQL 5.7.17

### Description:
Voyager and Eloquent mix up the field name/attribute with the relationship method. 

Calling `$model->relationship` will return `null` because the field in the `$model`'s database is the same name as relationship method. However, calling `$model->relationship()->get()` will return the expected relationship, because we're accessing *relationship* as a method and not a property. 

The method cannot be renamed as Voyager expects the relationship method **and** the field referencing it to be identical. To workaround this, I've created a duplicate relationship method with a different name. This yields expected results without breaking the Voyager relationship.

### Steps To Reproduce:

1. Create a new model, Parent, with schema
2. Give that model a *children* field (type doesn't matter)
3. Make a Child model and table and write schema for a pivot table (*parent_children*) with *model_id* and *child_id* as fields
4. Migrate and set up relationship in BREAD in Voyager
5. Add `belongsToMany` relationship method to Parent model using the custom field arguments:
```
public function children()
{
    return $this->belongsToMany(Child::class, 'parent_children', 'parent_id', 'child_id');
}
```

Calling `$parent->children`, eager loaded or not, will return `null`.

Duplicating `children()` to `fooChildren()` and calling `$parent->fooChildren` will return the array of related data, as expected.

----

This workaround should be noted in the documentation, or a better system built for relating Eloquent relationships with the field Voyager uses to establish its own BREAD relationships.

**Comment by lancepioch** [comment]
Labels: bug

**Comment by fletch3555** [comment]
v1.0 includes a rewrite for how relationships are handled.  Please test and reopen if necessary.
