### ISSUE TITLE
How to set default bread validation in custom controller?

### ISSUE THREAD

**Issue by Miri92** [thedevdojo/voyager#1460]
- Laravel Version: 5.3
- Voyager Version: v0.11.14

### Description:
Is it possible? Or  can it be done from the panel only

**Comment by lancepioch** [comment]
Labels: question

**Comment by handiwijoyo** [comment]
You can use this inside your controller.
```$val = $this->validateBread($request->all(), $dataType->editRows);```

See: https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/VoyagerBreadController.php#L228
