### ISSUE TITLE
Voyager Multiple Upload

### ISSUE THREAD

**Issue by radhuwebcastle** [thedevdojo/voyager#1461]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Hi, Am using voyager 0.10.11, How can i upload multiple images from admin side.

### Steps To Reproduce:
I created bread for a table. How could i post a image gallery via voyager backend. There only 2 file types. 'File' and 'Image'.

**Comment by fletch3555** [comment]
Version 0.10.* is very much out of date.  Please update to v0.11.* (follow directions in the documentation).  It may be more worthwhile to completely remove voyager and start fresh with v0.11.* instead.
