### ISSUE TITLE
Delete Menu Item

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#1462]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Deletion The item menu does not work correctly.
If we cancel the deletion of the item menu, then we must clear the action form
But we do not do this, and if we want to delete another menu item. That will remove the menu that was selected and canceled when deleting
  $('#delete_form')[0].action = $('#delete_form')[0].action.replace("__id",id);   <--hard))

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please open a new issue.
