### ISSUE TITLE
many to many relationship : Undefined index

### ISSUE THREAD

**Issue by Ahmed-Aboud** [thedevdojo/voyager#1465]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.3
- PHP Version: 7.1
- Database Driver & Version:

### Description:
so this is my Tag.php model relationship
    public function posts()
    {
    	return $this->belongsToMany(Post::class,'post_tag);
    }
and this is my Post.php model relationship
    public function tags()
    {
        return $this->belongsToMany(Tag::class,'post_tag');
    }

here is my tags bread
![tagsbread](https://user-images.githubusercontent.com/25877831/28218347-8e25f060-68b8-11e7-9ad5-3bbd27dd08f3.jpg)

here is my tags table
![tagstable](https://user-images.githubusercontent.com/25877831/28218433-ca72c0e8-68b8-11e7-87dc-267133252865.jpg)

here is my posts bread
![postsbread](https://user-images.githubusercontent.com/25877831/28218519-0e9cd8d0-68b9-11e7-8f1e-d3647c45634c.jpg)

here is my posts table

![poststable](https://user-images.githubusercontent.com/25877831/28218594-54c74eee-68b9-11e7-8dc9-e25541083f43.jpg)

and here is the post_tag table
![post_tag](https://user-images.githubusercontent.com/25877831/28218672-8789807c-68b9-11e7-865b-794fc581cc17.jpg)

if i select the tags as number it gets me 

(1/1) ErrorExceptionUndefined index: name
--

and if i select it as select multiple it gets me 
htmlspecialchars() expects parameter 1 to be string, array given (View: E:\Xampp\htdocs\Laravel\blog\vendor\tcg\voyager\resources\views\posts\browse.blade.php)

how to fix it ?

**Comment by nunomsh** [comment]
You're calling the post_tag column, and in the table you have name. If you want to relate tags with posts, create a column tag_id in posts table.
then posts Model: 
```
public function tagId()
{
    return $this->belongsToMany(Tags::class,'tag_id');
}

```

In posts bread, in the tag_id field  set it to multiple, and the json:

```
{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
```

**Comment by Ahmed-Aboud** [comment]
how will this works its many to many to i will have post-1 and the tag_id = 2 for example and i will have to re make post-1 for the tag_id = 3 ??

**Comment by nunomsh** [comment]
You can do the same for tags. The example is for posts with many tags, you can do the same for tags with many posts.
I think you can also use something like hasMany() in the posts model

**Comment by fletch3555** [comment]
Assisted on slack.  Documentation needs updating.

**Comment by paigemey779** [comment]
Once you choose hope anything will be possible. 

Are you going through any kind of spiritual attack or affliction or you want to get your ex husband or wife back? Dr. GURILARICO GURU THE GREAT is a traditional herbal and spiritual doctor that can help you out for free. Contact him to help you solve your problem for you free of charge. He is based in US. And here is his contact details
Call :+1(832) 263-7128, +1(832) 730-7296.
Contact: dr.gurilarico@priest.com
He is always ready to help for free.
