### ISSUE TITLE
Format option does not work on timestamp type fields

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1469]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 7.1.3
- Database Driver & Version: Mysql 5.7.17

### Description:
When a data row's type is set to 'timestamp', the format option has no effect on how it is displayed in the 'browse' or 'read' blade templates. It seems to only work for 'date' types.

### Steps To Reproduce:
Edit the Bread on any table that has columns of the `TIMESTAMP` type (e.g. the created_at and update_at columns). Add a custom format option to the json details, and then check the boxes for the column to displayed for Browse and Read. 
<img width="1165" alt="screen shot 2017-07-15 at 4 54 33 pm" src="https://user-images.githubusercontent.com/22035191/28243443-6a9491a8-697e-11e7-9715-a348ccf39872.png">

Then after navigating to the Browse or Read page for that table, the custom format will be ignored, and the timestamp will be displayed as its default, which for mysql will be in "Y-m-d G:i:s"
<img width="239" alt="screen shot 2017-07-15 at 4 54 59 pm" src="https://user-images.githubusercontent.com/22035191/28243447-7ada6eb6-697e-11e7-82b8-57c07ae82481.png">

**Comment by lancepioch** [comment]
Labels: possible bug
