### ISSUE TITLE
image cropper request

### ISSUE THREAD

**Issue by azatTemirbek** [thedevdojo/voyager#1474]
- Laravel Version: #.#.#5
- Voyager Version: #.#.#11
- PHP Version:5.6
- Database Driver & Version:5.6

### Description:
need cropper for an image. might be a good idea to make plugin database and control them from admin panel. or add to bread section

**Comment by fletch3555** [comment]
What do you mean by "image cropper"?

**Comment by azatTemirbek** [comment]
like croping from admin/post, (inside image uploader gui with modal ).
not defining from database with json as usual

**Comment by fletch3555** [comment]
Okay.  This would be all new functionality then.  Likely not going to happen anytime soon, but we're open to pull requests if anyone wants to tackle this.

**Comment by akazorg** [comment]
Image cropping is quite useful.
Maybe we can create a hook for this?

**Comment by akazorg** [comment]
Feature implemented.
