### ISSUE TITLE
Upon editing a row i have to re-upload any file or image from scratch

### ISSUE THREAD

**Issue by basmaseyam** [thedevdojo/voyager#1476]
- Laravel Version: 5
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

When i edit a row in a table i have to re- upload any file or image from scratch or an error appears.
Here's a screenshot of the table
![screenshot-1](https://user-images.githubusercontent.com/17016909/28274155-f9fba524-6ac4-11e7-80a6-90fdbb2e13ee.png)
And when i enter the submit button an error message occurs:
![error-message](https://user-images.githubusercontent.com/17016909/28274182-0b9801d8-6ac5-11e7-9aee-a091cf758e7b.png)

I have to re-upload the file/image each time i make an update. I want to know if there's any way i can to keep the file saved. 
Note: when i created the table i made the image field : not required

Thanks in advance

**Comment by fletch3555** [comment]
There is a current known bug with file/image upload fields being required.  It doesn't detect that the field already has a value.  You should be able to change the validation on the field so it's no longer required

**Comment by lancepioch** [comment]
Labels: bug

**Comment by emptynick** [comment]
This problem _should_ be solved (sorry, can't find a commit right now)
