### ISSUE TITLE
How will I create migrations for the admin tables at the same time when I use voyager admin to create tables (I mean the database tab)? 

### ISSUE THREAD

**Issue by adityabanerjee992** [thedevdojo/voyager#1477]
- Laravel Version: 5.4.16
- Voyager Version: 0.11.9
- PHP Version: 7.1.2
- Database Driver & Version:

### Description:
Hi I have an issue I am creating the tables for the admin panel using the database tab in the voyager but I notice that migrations have not been created for the tables. Please assist me how will I create migrations at the same time when I create table using the voyager admin panel. 

Now the issue is when I store the project on git and some one takes the clone he does not get the migrations for the admin panel as it was not created. Please assist , thank you.

**Comment by fletch3555** [comment]
Voyager does not currently support creating migrations.  It's a feature we're working on.  For now, you'll have to create the migrations manually.
