### ISSUE TITLE
Use keyName instead of assuming it is id

### ISSUE THREAD

**Issue by edmandiesamonte** [thedevdojo/voyager#1482]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version: 

### Description:
On the generic `browse.blade.php` inside `bread`, there's a lot of usage to `$data->id`. This scenario assumes that the primary key is `id`. To support non-`id` primary keys, replace it with
`$data->{$data->getKeyName()}`

This might also be applicable to other templates.

### Steps To Reproduce:
1. Create a table with non-`id` primary key
2. Add a BREAD. Primarily on browse.

**Comment by fletch3555** [comment]
You're correct, `$data->id` is used a lot in there.  I know this is something we fixed in a few other places.  I do have one concern though.  Many of these usages are related to route parameters.  What happens if the ID doesn't match the route?

**Comment by edmandiesamonte** [comment]
In my case, I also changed the routes to something like this
`route('voyager.'.$dataType->slug.'.edit', $data->{$data->getKeyName()})`

As far as I know, as long as you set your Model into something like this:
```
    /*
     | Model Configuration
     */
    protected $primaryKey = 'code';
    public $incrementing = false;
```
... the default BreadController should work

**Comment by victorlap** [comment]
Maybe it would be best to just use ```$model->getKey()```

See also https://laravel.com/api/5.4/Illuminate/Database/Eloquent/Model.html#method_getKey

**Comment by edmandiesamonte** [comment]
Oh, you're right @victorlap. That's much better.

**Comment by fletch3555** [comment]
I'm okay with this change if implemented correctly.  @edmandiesamonte, would you like to make the change and open a pull request for this?  The only changes needed should be to update views and routes to use `$model->getKey`

**Comment by edmandiesamonte** [comment]
I could. I'll try to do it over the weekend.

**Comment by edmandiesamonte** [comment]
Done. https://github.com/the-control-group/voyager/pull/1488

**Comment by fletch3555** [comment]
Perfect, thank you.  I'll close this now.
