### ISSUE TITLE
how can i display images without using voyager::image??

### ISSUE THREAD

**Issue by saldanac** [thedevdojo/voyager#1483]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

pls help

**Comment by fletch3555** [comment]
Your question is best asked in the Slack group.  Github issues are more suited for issues related to code (new features and bugs), which is why the prompt has fields for you to type in version numbers and describe the steps to reproduce your issue.
