### ISSUE TITLE
Add a field for attachment of files

### ISSUE THREAD

**Issue by CodeByViktor** [thedevdojo/voyager#1484]
- Laravel Version: 5.4.#
- Voyager Version: 0.14.11
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7

Hi.
Add please a field for attachment of files.

Very much "Voyager" was pleasant, but for my website an opportunity to attach files for example to articles is necessary.
In my opinion the excellent idea for increase in a functionality of the project.

I will be grateful. :-)

Example:
"blueimp" plugin jQuery

**Comment by azatTemirbek** [comment]
good idea color picker, image cropper, file up loader(zip(secure),doc,txt,pdf(not secure)) so it might be good idea to zip upload content

**Comment by lancepioch** [comment]
Labels: feature

**Comment by handiwijoyo** [comment]
Voyager is supported for file upload.
