### ISSUE TITLE
edit bread index error

### ISSUE THREAD

**Issue by abdullraahmaan** [thedevdojo/voyager#1485]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version:Mysql

### Description:
when i tried to add bread , i always get this error

**"Update Failed Exception: Undefined index:"**

### Steps To Reproduce:
1.create a table column
2.edit its bread

**Comment by fletch3555** [comment]
We need more information before we can help.  Please attach a screenshot of your table schema (either through Voyager or through whatever DB editor you prefer.. phpMyAdmin, MySqlWorkbench, etc) and BREAD configuration (through Voyager).  Also, please identify what the changes are.  "edit its bread" is not descriptive enough.

**Comment by abdullraahmaan** [comment]
![untitled](https://user-images.githubusercontent.com/30316051/28499011-1eacf4ae-6fac-11e7-9be8-de6cd9f4f1cc.png)
[localhost _ 127.0.0.1 _ zabat _ pages _ phpMyAdmin 4.7.pdf](https://github.com/the-control-group/voyager/files/1168043/localhost._.127.0.0.1._.zabat._.pages._.phpMyAdmin.4.7.pdf)

here you are , i tried to change the max input vars in php.ini and htaccses but it doesnt work unfortunately

**Comment by lancepioch** [comment]
Labels: possible bug

Close (need actual error report)

**Comment by fletch3555** [comment]
@abdullraahmaan, please test again now that 1.0 has been released and reopen if necessary.
