### ISSUE TITLE
Add TFA (2FA) Feature

### ISSUE THREAD

**Issue by edmandiesamonte** [thedevdojo/voyager#1487]
I think it is a good idea to have a 2FA feature since this is most likely to be used as admin side for operations. We don't want people to get hacked easily.

I will try to create a pull request on this.

**Comment by fletch3555** [comment]
While I don't disagree, we simply make use of the existing Laravel Auth functionality.  This will definitely be taken under consideration, but likely as part of a larger rewrite of the auth system Voyager uses.  I don't see this being merged in for v1.0

**Comment by handiwijoyo** [comment]
I don't think we need this feature since this is an optional. You could add this feature via Voyager Hook.
