### ISSUE TITLE
Discussion Channel Needed

### ISSUE THREAD

**Issue by edmandiesamonte** [thedevdojo/voyager#1489]
Is there any discussion channel for Voyager? I would love to join. We're currently using this package as our admin interface and we love how clean it is and how friendly and flexible the code is. 

Any chance people could hop in and discuss?

**Comment by victorpierredev** [comment]
You can join the [Voyager Slack chat](https://voyager-slack-invitation.herokuapp.com/). People are very active there.

**Comment by handiwijoyo** [comment]
Closed due Slack Chat already in readme
