### ISSUE TITLE
erro on add with select dropdown relashionship

### ISSUE THREAD

**Issue by joefreire** [thedevdojo/voyager#1492]
- Laravel Version:5.4

### Description:
I have a select dropdown with a problem

my relashionship is

{"relationship":
{"key":"id",
"label":"nome",
"page_slug": "admin/tipo-servicos"}
}

my \APP\TipoServico

	public function tipo_sub_servicos_id()
	{
		return $this->hasMany(\App\TipoSubServico::class);
	}	
my \APP\TipoSubServico

	public function tipo_servicos_id()
	{
		return $this->belongsTo(\App\TipoServico::class,'tipo_servicos_id','id');
	}	

and shows this error on add a new

Undefined property: App\TipoSubServico::$tipo_servicos_id (View: C:\xampp\htdocs\voyager\vendor\tcg\voyager\resources\views\formfields\select_dropdown.blade.php) (View: C:\xampp\htdocs\voyager\vendor\tcg\voyager\resources\views\formfields\select_dropdown.blade.php)

**Comment by sattip** [comment]
After https://github.com/the-control-group/voyager/pull/638 they changed from `snake_case` to  `camelCase`
Hope it helps

**Comment by azatTemirbek** [comment]
i had same problem, and i have changed id to int and any_id to varchar it worked in my case
re bread it also

**Comment by lancepioch** [comment]
Labels: possible bug

Close (solution posted)
