### ISSUE TITLE
request for color picker input

### ISSUE THREAD

**Issue by azatTemirbek** [thedevdojo/voyager#1493]
- Laravel Version:5.3 
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version:5.6

### Description:
it will  be nice to make color picker in bread  
### Steps To Reproduce:
http://angularjs.jqueryrain.com/demo/color-picker/
here is some examples

**Comment by akazorg** [comment]
Duplicated, it has been requested here #619.

**Comment by fletch3555** [comment]
Closing as duplicate.  Please track this under #619

**Comment by akazorg** [comment]
Here, PR sent: https://github.com/the-control-group/voyager/pull/1494
Can you please take care it @fletch3555?
