### ISSUE TITLE
Separate media manager from core

### ISSUE THREAD

**Issue by MehediDracula** [thedevdojo/voyager#1495]
Voyager's media manager is really cool. it would be great if it can separate from the core and use it as a package on other laravel apps

**Comment by akazorg** [comment]
@ctf0 has created a package inspired on Voyager Media: https://github.com/ctf0/Laravel-Media-Manager. Give it a try.

**Comment by MehediDracula** [comment]
Hmm... this one is pretty nice

**Comment by akazorg** [comment]
Closing this since it's not a Voyager issue.
