### ISSUE TITLE
Sidebar menu doesn't work on the media page

### ISSUE THREAD

**Issue by gileswells** [thedevdojo/voyager#1497]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.14
- PHP Version: 7.1.3
- Database Driver & Version: mysql 5.7.17

### Description:
When on the media page only the first clicked dropdown in the side menu will work

### Steps To Reproduce:
Have a menu with multiple dropdowns in it.
Visit the Media page.
Click to expand any dropdown (first click will work).
Click to close the opened dropdown OR click to open a new dropdown (this fails).
You'll observe on the failed click event that the url now includes a hash similar to this. `/admin/media#tools-dropdown-element`

**Comment by gileswells** [comment]
This could be the same fix required to resolve #1076 but this requires less conditions to reproduce.

**Comment by gileswells** [comment]
Issue persists on `dev-master`

**Comment by lancepioch** [comment]
Labels: bug, design

**Comment by fletch3555** [comment]
Please test on v1.0 and reopen if necessary
