### ISSUE TITLE
Best way to override Voyager\Models\User?

### ISSUE THREAD

**Issue by giang-nghg** [thedevdojo/voyager#1498]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 5.7
- Database Driver & Version: PDO & MySQL 5.7 

### Description:
I want to use `user_id` instead of `id` for querying users. In `VoyagerAdminMiddleware.php`, line 22, Voyager query for the user as `Voyager::model('User')`, which resolves to `TCG\Voyager\Models\User` in `TCG\Voyager.php`, line 52, in the protected `$models` array. Is there a way to dynamically define which User model I want Voyager to use or which primary key to use for Voyager's `User` model? What is the `user.namespace` config in `config/voyager.php` do in this case, since it points to `App\User`?

**Comment by fletch3555** [comment]
I believe `user.namespace` is legacy, as I'm not sure what it's doing currently (if anything).

What you're looking for is `Voyager::useModel()`.  It's apparently missing from our documentation.  There are examples of it's use in a few places within the Voyager codebase.  Please reference those.

One thing to note.  Please make sure your `App\User` model is extending Voyager's User model.

**Comment by giang-nghg** [comment]
@fletch3555 Thanks. Actually there's no example code, but I figured out how to use it. Hope to see the docs updated soon.

**Comment by warkior** [comment]
Could this maybe be documented briefly here as well, so that people like me googling for a solution could find it? You discuss that it's possible, but there's not actual description of how to do it here. :)

**Comment by giang-nghg** [comment]
@warkior you can set `protected $primaryKey = 'your_key_name';` in your model. As for specifying which User model to use, I don't think Voyager has supported that yet.

**Comment by giang-nghg** [comment]
@fletch3555 oops, sorry. I'm an idiot
