### ISSUE TITLE
Bug report: validate images fail !

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#1501]
### Description:
  validate pics field =>  multiple images ! 
  below is config json :
{
    "validation": {
        "rule": "image|max:8000"
    },
    "resize": {
        "width": "1000",
        "height": "null"
    }
}

maybe pics is an array , not image, so fail !!! 

$validator = Validator::make($request->all(), [
    'person.*.email' => 'email|unique:users',
]);

Like this,  how to config  ?        * is supported / foreach in array ???

**Comment by fletch3555** [comment]
Your issue description is not clear.  Please limit issues to a single concern/question.

The "Multiple Images" field stores paths to images as a JSON array.  Validation rules regarding images will not work as currently implemented.  This definitely needs to be cleaned up/refactored.

**Comment by OliverVin** [comment]
Yes, need expland definitely to support JSON array !     * can be used .
