### ISSUE TITLE
Issue with the path to download links

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1504]
- Laravel Version: 5.4.29
- Voyager Version: 0.11.14
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

### Description:

- Similar to #1029, the download links provided in [`browse.blade.php`](https://github.com/the-control-group/voyager/blob/master/resources/views/bread/browse.blade.php#L90) and [`file.blade.php`](https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/file.blade.php#L2) do not take into account a set up such as `localhost/path/to/voyager/` (as opposed to `localhost/voyager/`)
- Fix is to [prepend `url('')`](https://github.com/the-control-group/voyager/commit/700e0211f24a265cef8fba0576de9da4d720438a) to the `href` just like with the breadcrumbs

**Comment by fletch3555** [comment]
I agree that it's a problem, but I don't like the `url('')` solution.

**Comment by u01jmg3** [comment]
- `url('')` was the solution @DODMax chose so I was keeping in line with that - I would usually use `Request::root()`.
- I'll leave it to you to decide on a solution you do like.
- It might also be worth evaluating other places where a change like this is required.

**Comment by DODMax** [comment]
Indeed the `url()` was just a quickfix, I'm sure there is dozen of better solutions.
I think I solved the file download issue by changing line 57 of `config/voyager.php` to:
```
'assets_path' => env('APP_URL', 'http://localhost') . '/vendor/tcg/voyager/assets',
```
Or at least it works for `Voyager::image() & Voyager::asset()`
But again not perfect as it require to configure the application URL

Not sure if there is other fixes needed, maybe some assets missing the `Voyager::asset()` function..

**Comment by lancepioch** [comment]
Labels: possible bug, discussion

**Comment by handiwijoyo** [comment]
Was this issue fixed in `1.0`?

**Comment by u01jmg3** [comment]
Looks like it was fixed in [45e2e31](https://github.com/the-control-group/voyager/commit/45e2e31a1ae9c2cf0d64462473f72227b637507c#diff-2a61adb3924b23f02ff9728976af7ef8) which is in `1.0`

Are issues not referenced in commits so you don't have to go back in time to determine if the problem is fixed?

**Comment by fletch3555** [comment]
There were so many duplicate issues that we missed a few when merging PRs. We haven't been very diligent about requiring issue references when reviewing PRs

**Comment by u01jmg3** [comment]
No worries - I know it can be difficult.
