### ISSUE TITLE
Plupload ?

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#1505]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.7

I often work in Africa where internet speed is bad (especially in upload).
The system integrated to Voyageur is then unsuitable when I want to send a lot of pictures with BREAD.
On olds projects, I used PLUPLOAD which resizes and optimizes pictures client side. This greatly reduces the upload time.
I think it would be interesting to use it in Voyager.

Tell me if this can be of interest to the community.
I will work on it when the time permits.

**Comment by lancepioch** [comment]
Labels: feature, question

**Comment by fletch3555** [comment]
I haven't seen a lot of interest in this.  If that changes, I'm certainly happy to reopen this.
