### ISSUE TITLE
Bug image save

### ISSUE THREAD

**Issue by secondnetwork** [thedevdojo/voyager#1508]
- Laravel Version: 5.4
- Voyager Version: dev-master
- PHP Version: 7.0
- Database Driver & Version: 5.6

If I make at post change and click save, the image deleted (in the Datebase)

**Comment by fletch3555** [comment]
Does this occur if you use v0.11.14 instead of dev-master?

**Comment by secondnetwork** [comment]
Only with the dev-master is the bug. In the v0.11.14 everything is normal

**Comment by secondnetwork** [comment]
Is fixed by tnylea
