### ISSUE TITLE
Column not found: 1054 Unknown column 'cd_id' in 'field list' (SQL: select `cd_id` from `track_cd` where `teck_list_id` = 5)

### ISSUE THREAD

**Issue by kiranpalkathait** [thedevdojo/voyager#1510]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by fletch3555** [comment]
Please fill out all parts of the request.  Without it, we will be unable to help you.

**Comment by kiranpalkathait** [comment]
i am trying to create many to many relation between two table (cd and track) using pivot(track_cd) table. but it's showing unknown column in pivot table.

**Comment by kiranpalkathait** [comment]
unknown column cd_id in pivot table
