### ISSUE TITLE
Is there a way to cache common database calls?

### ISSUE THREAD

**Issue by victorlap** [thedevdojo/voyager#1511]
- Laravel Version: 5.4
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version mariadb 10

### Description:
Is there a way to cache some of the database calls using the laravel cache abstraction?

I could not find any documentation related to this.

### Steps To Reproduce:
N/A

**Comment by lancepioch** [comment]
Labels: question

**Comment by handiwijoyo** [comment]
We already have a cache functionality for the settings data. Could you please provide what kind of cache that you need other than that?

**Comment by fletch3555** [comment]
The database query count has been significantly reduced by changes included in recent releases.  If this is still a problem, please create a new issue with specific suggestions on where we can further improve.
