### ISSUE TITLE
Strtolower($string)

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1512]
- Laravel Version: 5.4
- Voyager Version: dev-master
- PHP Version: 7
- Database Driver & Version:

### Description:
Need to use mb_strtolower instead of strlower for Unicode in widgets.

Russian lang example.
strlower = ������������
mb_strlower = Пользователь

And nedd to change alert get messages way for menu builder
From voyager.menu.builder_successfully_deleted to voyager.menu_builder.successfully_deleted

**Comment by davodavodavo3** [comment]
issue is fixed

**Comment by lancepioch** [comment]
Labels: locale, bug

**Comment by fletch3555** [comment]
Resolved by #1743
