### ISSUE TITLE
Tony Lea

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1516]
Hi Tony you forget to give me the hacker bage on devdojo for issue with subscribe video lessons)))))

# Reproduce
https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/3608/8/218040025/755884869.mp4?token=1501508598-0x8dae589b22213f92edeff89a78546aa1d764dedb

**Comment by fletch3555** [comment]
This is not an issue with Voyager.  If you need to reach out to Tony, he can be reached through his profile on here or on slack
