### ISSUE TITLE
image field Bug

### ISSUE THREAD

**Issue by secondnetwork** [thedevdojo/voyager#1517]
- Laravel Version: 5.4
- Voyager Version: dev-master
- PHP Version: 7.0
- Database Driver & Version: 5.6

### Description:
Tanylea has Fixing this image field.
![img2](https://user-images.githubusercontent.com/13808106/28777762-c408bc3e-75fc-11e7-854b-2a797435ec83.png)

But when I use the image Field in the database a different name to imagelogo, the input field has a different id in the field, and Change the text and click save, the image deleted (in the Datebase)

![img](https://user-images.githubusercontent.com/13808106/28777520-c3364412-75fb-11e7-9ce5-f932a278e74e.png)

**Comment by lancepioch** [comment]
Labels: possible bug
