### ISSUE TITLE
Check for permission and other issues maybe

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1518]
- Laravel Version: 5.4
- Voyager Version: dev-master
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Hi everyone @akazorg @marktopper 
When I update Settings i get Error Permission does not exist.
Permission 'visit_settings'!!!!!
All works fine in old version))) 
Guys if you know about this problem then close issue.

### Code from Voyager.php where this issue lives)))
```
// Check if permission exist
$exist = $this->permissions->where('key', $permission)->first();
$exsit is null because there is no permission visit_settings
// Permission not found
if (!$exist) {
    throw new \Exception('Permission does not exist', 400);
}
```

**Comment by fletch3555** [comment]
dev-master is being prepped for a v1.0 release and is currently considered unstable. However, I don't believe your issue is related to any change we've done.  You're simply missing a permission in the database (`visit_settings` to be specific).  Add that back and it will start working.  As for why it's missing, you can check the seeders.

**Comment by davodavodavo3** [comment]
let me check

**Comment by davodavodavo3** [comment]
what permission need to be in seeder for make changes in Settings? visit_settings?
Do you see anywere in seeders that permission?
In my permission table seeder i have browse_settings, nothing else I do not have(visit_settings).
Believe me @fletch3555  ))))
Have these issue on fresh install of voyager dev-master))

**Comment by davodavodavo3** [comment]
1.Also maybe need to remove 
```
<script src="{{ voyager_asset('lib/js/tinymce/tinymce.min.js') }}"></script>
<script src="{{ voyager_asset('js/voyager_tinymce.js') }}"></script>
```
from Users edit-add.blade.php
from Roles edit-add.blade.php

2.Translation doesnt work on edit-add  Posts, there is rich text box that cause issue
3.Tinymce(rich text box) multilang doesnt work 
4 displayAlerts is not defined in Database  on bread update.
5. When user is loged in he can browse login page.(need redirect for that page when user is loged in)

I understand that the master branch is unstable  I describe problems that you might not notice

**Comment by lancepioch** [comment]
Labels: discussion, possible bug
