### ISSUE TITLE
[Feature request] Export data button

### ISSUE THREAD

**Issue by alexandrelozano** [thedevdojo/voyager#1523]
In the CRUD view page add a button to export to PDF,XLSX,CSV. (See CRUDBooster for sample).
Thx.

**Comment by lancepioch** [comment]
Labels: feature

**Comment by handiwijoyo** [comment]
@alexandrelozano Do you mean on the `Browse` view?

**Comment by alexandrelozano** [comment]
@handiwijoyo yes, it would be very useful for all

**Comment by fletch3555** [comment]
I'm open to this, but won't be building it myself.  If someone from the community wishes to build it and submit a PR, I'll gladly review it.

**Comment by emptynick** [comment]
Custom buttons were introduced with https://github.com/the-control-group/voyager/pull/2678
And will be available in `1.1`
