### ISSUE TITLE
Token Mismatch Exception after Login

### ISSUE THREAD

**Issue by gka-jundolor** [thedevdojo/voyager#1536]
- Laravel Version: 5.3.31
- Voyager Version: v0.11.14
- PHP Version: v7.0.20
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.18

### Description:
The login page on our site http://somesite.com/admin/login displays the error _TokenMismatchException in VerifyCsrfToken.php_ line 68 after username and password was submitted. On local site, i.e. http://localhost/somesite.com/admin/login, the login works and we get the dashboard upon verification of username and password.

Here's the screenshot of the error.
![image](https://user-images.githubusercontent.com/30709798/28951813-e2ffa9da-78ff-11e7-8c8d-8157cbcabe4e.png)

### Steps To Reproduce:
On local, upon submission of a valid username and password, the dashboard is displayed. No codes were altered. The site is deployed on an AWS instance.

**Comment by fletch3555** [comment]
Do you have your APP_URL set correctly in your .env file?

**Comment by lancepioch** [comment]
Labels: possible bug

Close (user didn't respond)
