### ISSUE TITLE
Token Mismatch Exception on adding/updating menu builder 

### ISSUE THREAD

**Issue by chaitalipatil** [thedevdojo/voyager#1538]
- Laravel Version: 5.4
- Voyager Version: ^0.11.14
- PHP Version: 5.6.25
- Database Driver & Version: MySQL 5.7.14

### Description:
When I add new menu item or updates existing menu item to 'Menu Builder (admin) ' , after filling up all the details in form on submitting form it gives TokenMismatchException

![image](https://user-images.githubusercontent.com/16894779/28955293-4d2df278-7903-11e7-8721-bc8f2400b917.png)

### Steps To Reproduce:
1. From sidebar Tools->Menu Builder->admin click on 'Builder' button.
1. Then Select 'New Menu Item' and fill all form fields.
1. On click of 'Submit' button it shows the Token MismatchException
1. And it also **logout from admin panel continuously**

Please help me, I am new to this.

**Comment by fletch3555** [comment]
@chaitalipatil, is this still an issue for you? My guess is it's a configuration issue in how you have your site set up locally.  We would have to troubleshoot the issue, so it's best suited as a discussion in the help channel in our slack group

**Comment by lancepioch** [comment]
Labels: possible bug

Close (user didn't respond)
