### ISSUE TITLE
empty meta description in post leads to sql error

### ISSUE THREAD

**Issue by demosglok** [thedevdojo/voyager#1540]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 5.6
- Database Driver & Version: mysql 5.5

### Description:
Once i'm trying to create post without metadescription i got sql error
 Integrity constraint violation: 1048 Column 'meta_description' cannot be null (SQL: insert into `posts` (`category_id`, `title`, `excerpt`, `body`, `image`, `slug`, `meta_description`, `meta_keywords`, `status`, `seo_title`, `featured`, `author_id`, `updated_at`, `created_at`) values (1, post title, excerpt, <p>post content</p>, , post-title, , , PUBLISHED, , 0, 1, 2017-08-05 19:27:14, 2017-08-05 19:27:14))

i think this Metadescription should be either marked as required or DB structure should be changed a bit to allow nulls or have meta_description default value of ''

### Steps To Reproduce:
make fresh install of voyager on laravel 5.4 and mysql 5.5 and try to add new post

**Comment by azatTemirbek** [comment]
maybe u r making it required field in sql

**Comment by fletch3555** [comment]
This has been a known issue for a while, but just hasn't been fixed yet.  Does the view identify the field as required? If not, I'm thinking we can just add a migration to allow the field to be null.

If you'd like to make that change, give it a quick test, then open a PR for it, we'd appreciate it.  If not, I'll take care of it later.

**Comment by demosglok** [comment]
thanks for reaction. i'll be happy to make a PR on next week, once i'll return to my hometown

**Comment by lancepioch** [comment]
Labels: in progress, bug

**Comment by handiwijoyo** [comment]
@demosglok Do you still up on this?

**Comment by handiwijoyo** [comment]
After check on the current version seems this was fixed: https://github.com/the-control-group/voyager/blob/1.0/publishable/database/migrations/2017_04_11_000000_alter_post_nullable_fields_table.php

**Comment by demosglok** [comment]
@handiwijoyo sorry, i haven't managed to check yet. but if it works now, great news then. thanks a log. i'll check a bit later how it works for me
