### ISSUE TITLE
How to encrypt/decrypt values in tables

### ISSUE THREAD

**Issue by mattonik** [thedevdojo/voyager#1541]
- Laravel Version: 5.4.32
- Voyager Version: 0.11.14
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
How to setup BREAD to use Laravel Encrypt/Descrypt to securely store data in DB?

**Comment by lancepioch** [comment]
Labels: question, feature

**Comment by gavinkalika** [comment]
encryption is typically one way. what are you trying to decrypt?

**Comment by fletch3555** [comment]
No, encryption is bidirectional (thus the word decryption exists).  Hashing is unidirectional and non-reversible

**Comment by handiwijoyo** [comment]
@mattonik What kind of encryption do you need to use?

**Comment by mattonik** [comment]
@handiwijoyo hey, thanks for answer, but I already figured out a way by running the encryption/decryption before sending to the model
