### ISSUE TITLE
Issue with visibility of Tools menu option

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1542]
- Laravel Version: 5.4.29
- Voyager Version: 0.11.14
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

### Description:

- When a Voyager User is under a Role that only has permission to 'browse the Admin', the Tools menu remains in the sidebar even though no options exist under it.
- I would expect that this menu option would not be visible if the User does not have access to either the 'Menu Builder' or 'Database'.

**Comment by reficul** [comment]
I confirm this issue.

**Comment by lancepioch** [comment]
Labels: bug, design

**Comment by fletch3555** [comment]
I believe this has been fixed in a more recent version.  Please confirm.  We'll reopen this issue if that's not the case.

**Comment by u01jmg3** [comment]
Is there a commit to reference? That would confirm the fix

**Comment by fletch3555** [comment]
Unfortunately, no.  However, we've had 12 releases since this issue was created.  At least one of them included an admin_menu rewrite.  There was no commit that fixes this specifically.

**Comment by u01jmg3** [comment]
Looks good on my end
