### ISSUE TITLE
when i go /admin, redirected to /

### ISSUE THREAD

**Issue by trollsk1n** [thedevdojo/voyager#1543]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1.1
- Database Driver & Version: mysql

### Description:
i install clear laravel & voyager, register user with `php artisan voyager:admin admin@ekopen.uz ` set admin name and password, then create laravel auth with `php artisan make:auth` 
after i go to /admin/login, write my login and password, but after browser sends to url '/', if i go to '/home', i see message 'You are logged in!'
'/admin' not worked, but in routes/web.php i see `Route::group(['prefix' => 'admin'], function () {
	Voyager::routes();
});`

**Comment by Ahmed-Aboud** [comment]
php artisan voyager:admin your@email.com --create

**Comment by trollsk1n** [comment]
i have a admin user in database, I can't get to the admin panel, just go straight to the main page

**Comment by emptynick** [comment]
Check issue #1217 and #1164 as it seems to be the same.

**Comment by fletch3555** [comment]
@trollsk1n, if you have direct access to your DB, please confirm that your user is in the "admin" role (likely `id = 1`).  Also, please confirm that that role has the `browse_admin` permission set.

**Comment by trollsk1n** [comment]
I entered the command `php artisan voyager:admin [myadmin]` and get the answer `The user now has full access to your site.`. 
In database in table users i have the only user with `role_id=1` and in the table `roles` the only record with `id=1` and `name=admin`, other tables likely `permissions, permissions_group, permission_role` is empty

**Comment by trollsk1n** [comment]
I found a solution, if u use `MariaDB` or old version of `MySQL` go to the `app\Providers\AppServiceProvider.php` and add to `boot` function string `Schema::defaultStringLength(191);` after enter the command `php artisan voyager:install`.

**Comment by fletch3555** [comment]
Yes that's certainly required per the laravel 5.4 docs due to an issue with the collation type used and a change in newer MySQL versions.

Rerunning `artisan voyager:install` is what fixed the symptoms you were describing. It ran the permissions seeder, which added the "browse_admin" permission and then added it to the admin role, which gave you access.
