### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#1545]
How and in which branches i can push some fixes for updates with unique type and some other fixes?

**Comment by fletch3555** [comment]
We're currently working on the master branch to prepare it for a 1.0 release.  Depending on what the fixes are, that's where they would go.  We would prefer the changes each be their own pull request (assuming they're not related) so we have the option of approving/declining them individually.

Also, this type of question is much better suited for slack.  You can ping one of the maintainers  (@marktopper, @tnylea, or myself) there and we'll get back to you as soon as we can.
