### ISSUE TITLE
 Can't access to the dashboard. Seems to stay in the same view.

### ISSUE THREAD

**Issue by ejbogantes** [thedevdojo/voyager#1547]
- Laravel Version:    5.4.32
- Voyager Version:  0.11.14
- PHP Version:         5.6.30
- Database Driver & Version: PDO PostgreSQL 9.3.14 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

### Description:
 Can't access to the dashboard. Seems to stay in the same view.

### Steps To Reproduce:

1. Install Voyager as usual with dummy data
2. Go to the browser: localhost/admin
3. Login page will show up as usual
4. Enter the credentials and push the Login button 
5. The page reloads, no errors are shown 
6. Login page is the only view I can see

**Comment by marktopper** [comment]
This sounds like an issue with your application setup and your sessions.
I believe that if you try using Laravels login method to do something on your end, then that would fail as well and log you out just like this.
Can you please confirm this.

**Comment by lancepioch** [comment]
Labels: invalid

Close (no user response)

**Comment by marktopper** [comment]
Closed due to missing user response (thanks @lancepioch)
