### ISSUE TITLE
Voyager Settings Assets Path Wrong

### ISSUE THREAD

**Issue by jeremyhart** [thedevdojo/voyager#1548]
- Laravel Version: 5.4
- Voyager Version:0.11.14
- PHP Version:
- Database Driver & Version:

### Description:
When adding an image as a voyager setting, rendering it on the page inside a img tag has the wrong url, it is just setting/month/asset name etc where as when voyager saves the image upon upload, it stores it in public/storage/setting etc.

**Comment by jeremyhart** [comment]
I have tried changing 'url' => env('APP_URL').'/public/storage', but it still doesn't work

**Comment by fuzzyjared** [comment]
I had to update the url to the '/storage' for it to work for me in my review.

'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => '/storage',
            'visibility' => 'public',
        ],

**Comment by marktopper** [comment]
Did it work doing what @fuzzyjared did?

**Comment by fuzzyjared** [comment]
I just had to move my project form a MAMP development environemtn into a Laradock environment. As I am using this project as an evaluation I decided not to migrate my existing databse and run "php artisan voyager:install --with-dummy".

This installed everything just fine but resulted int a symlink error.

I had not changed the filesystem config from my earlier post but did have to remove the created symlink and then run the symlink correction tool. Once this was saved the images were loading again without a symlink error.

I am only mentioning this as it would appear that this setting worked in two different development environment if not completely different systems.

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by ElioTohm** [comment]
i don't think this is a voyager bug after some digging found a temporary fix from the following issue:[https://github.com/laravel/framework/pull/21037](url)
so in MySqlProcessor.php change column_name to COLUMN_NAME

**Comment by fletch3555** [comment]
@ElioTohm, I don't see how that's related to this issue.  Can you please elaborate?

**Comment by ElioTohm** [comment]
@fletch3555  i am terribly sry i commented on the wrg issue i will remove it

**Comment by jatin52** [comment]
In config/voyager.php
'assets_path' => url('/public/vendor/tcg/voyager/assets')  ==> did not worked while doing "php artisan"
'assets_path' => env('APP_URL').'/public/vendor/tcg/voyager/assets' ==> this is working :)

**Comment by handiwijoyo** [comment]
I believe you can use `Voyager::image(setting('site.logo'))` in last version. Please let me know if that doesn't work.

**Comment by rathod4rathod** [comment]
Thanx jatin its working for me.. :)


In config/voyager.php
'assets_path' => url('/public/vendor/tcg/voyager/assets') ==> did not worked while doing "php artisan"
'assets_path' => env('APP_URL').'/public/vendor/tcg/voyager/assets' ==> this is working :)
