### ISSUE TITLE
Multiple guards problem

### ISSUE THREAD

**Issue by fiter92** [thedevdojo/voyager#1550]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1

### Description:
I'm using multiple authorization. I have 'web' guard and 'admin' guard. When I'm trying to login to Voyager  I'm getting an infinite redirects from admin to admin/login and back:  VoyagerAdminMiddleware `Auth::guest()` returns true and redirects me to admin/login where RedirectIfAuthenticated redirects me to admin dashboard page. 
How can I let `Auth::guest()` to know that it needs to check 'admin' guard?
And `Voyager::model('User')->find(Auth::guard('admin')->id())` returns an empty user witch returns an error on `$user->hasPermission('browse_admin')`. If replace it with `$user = Auth::guard('admin')->user()` it works, but in this case I'll get a ton of errors in every `Auth::user()` of Voyager code.
So can you tell me all files where I should set an admin guard and model instead of default user?

**Comment by fletch3555** [comment]
Unfortunately, my answer is going to have to be "either hack something together, or wait a few weeks". Voyager does not currently make use of guards/policies, but that's something we're changing for v1.0, set to be released sometime at the end of the month along with laravel 5.5.

What kinds of restrictions are you adding to your admin guard?

**Comment by avengerweb** [comment]
you can try to create custom middleware and set default guard for specified url, like
```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class SetDefaultGuard
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Str::startsWith($request->getRequestUri(), '/voyager'))
        {
                Auth::shouldUse('admin');
        }

        return $next($request);
    }
}
```

**Comment by lancepioch** [comment]
Labels: enhancement, possible bug

**Comment by sachin** [comment]
I had the same issue please look at the solution 
https://github.com/the-control-group/voyager/issues/1580#issuecomment-342727200

Hope it is helpful.

**Comment by handiwijoyo** [comment]
Close due solution in #1580. We need to add that to documentation tho.
