### ISSUE TITLE
 Specified key was too long

### ISSUE THREAD

**Issue by vikey09** [thedevdojo/voyager#1552]
I want to migrate my laravel-voyager project to my live-cpanel-server and host it there. But when I export the DB from my localhost phpmyadmin and import it to my cpanel phpmyadmin, im getting this error '#1071 - Specified key was too long; max key length is 767 bytes' SNAPSHOT ATTACHED. 

Has anyone come across this error? Or if anyone can help me with this, it will be of great help.
![capture](https://user-images.githubusercontent.com/3805941/29239101-c14c497a-7f66-11e7-9654-afcd9efe2f22.JPG)

**Comment by emptynick** [comment]
Yes this is a common problem, and has its own point in the readme:
`Troubleshooting: Specified key was too long error. If you see this error message you have an outdated version of MySQL, use the following solution: https://laravel-news.com/laravel-5-4-key-too-long-error`

**Comment by vikey09** [comment]
I tried this many times. Still same. I even asked my hosting support team to upgrade the MYSQL version, still not working. Anyways, I will try again. Many thanks, Nick.

**Comment by fletch3555** [comment]
Try splitting your `ALTER TABLE` into multiple queries to see which one is failing.  I'm willing to bet the issue is with the slug field being too long, but that's just a guess.  There are numerous solutions to this, including simply upgrading your mysql version or changing to mariadb.

**Comment by vikey09** [comment]
@fletch3555 I upgraded my MYSQL version to 5.7.7 and it solved the issue. Thank you for your suggestion.
