### ISSUE TITLE
Problem with the internet explorer 11 and tinymce

### ISSUE THREAD

**Issue by secondnetwork** [thedevdojo/voyager#1557]
file uploaded to change text
- Laravel Version: 5.4
- Voyager Version: dev-master
- PHP Version: 7.0
- Database Driver & Version: mySQL 5.6

### Description:
**The rich text box editor don't show in internet explorer 11.**

![bildschirmfoto 2017-08-14 um 16 11 18](https://user-images.githubusercontent.com/13808106/29275443-65090ba2-810b-11e7-975e-29313ad31fb9.png)

**Comment by marktopper** [comment]
Does it work here: https://www.tinymce.com/

**Comment by secondnetwork** [comment]
No, have try latest version from tinymce.
The problem must be in the **app.js** file, but is compressed. 
With i use together **app.js** and [Summernote editor](http://summernote.org/), it goes.

**Comment by marktopper** [comment]
But if TinyMCE does not work at https://www.tinymce.com/ either, then it must be a issue with them not supporting Internet Explorer 11 correctly.

**Comment by secondnetwork** [comment]
Sorry, i mean yes on https://www.tinymce.com/ it goes Internet Explorer 11.
but not together with app.js in Voyager.

**Comment by davodavodavo3** [comment]
A lot of things do not work in ie 11
Media Manager
Compas page
Dashboard with google analitics and maybe other futured pages will not work
You cant get all this stuff with ie 11 use Microsoft Edge instead of or other modern browser.
Maybe need documentation for Browser Compatibility
