### ISSUE TITLE
TinyMCE - Missing Image click handling

### ISSUE THREAD

**Issue by fuzzyjared** [thedevdojo/voyager#1558]
- Laravel Version: 5.4.32
- Voyager Version: 0.11.42
- PHP Version:
- Database Driver & Version:

### Description:

Working off of a fresh install there is a missing image within the content of Page ID 1 ( /admin/pages/1/edit ). Clicking on the image fires a console error.

This error has been identified within TinyMCE and noted as fixed with update to 4.5.6.

https://github.com/tinymce/tinymce/issues/3611#issuecomment-298427206

tinymce.min.js:10 Uncaught DOMException: Failed to execute 'setBaseAndExtent' on 'Selection': There is no child at offset 1.

Currently Voyager is using 4.5.3. Is there a reason TinyMCE is not at 4.5.6?

### Steps To Reproduce:

Create content with image in the body. Remove the image from the server without removing it from the body of the content. Edit the content, click on the missing image.

**Comment by fletch3555** [comment]
> Currently Voyager is using 4.5.3. Is there a reason TinyMCE is not at 4.5.6?

Yes, because nobody has updated (and tested) it yet

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by handiwijoyo** [comment]
Duplicate #1245
