### ISSUE TITLE
Table view loading 1 200 000 cities from my database

### ISSUE THREAD

**Issue by alexdanielyan** [thedevdojo/voyager#156]
Table view loading 1 200 000 cities from my database. Thanks.

**Comment by ChadTaljaardt** [comment]
Whats the issue?

**Comment by maiorano84** [comment]
@team5ru What are you even asking?

**Comment by alexdanielyan** [comment]
I thought it was obvious, the browser dies.

**Comment by alexdanielyan** [comment]
Here is example of using datatables in right way https://datatables.net/extensions/scroller/examples/initialisation/server-side_processing.html

**Comment by alexdanielyan** [comment]
There was solution, but it's a little bit complicated #81

**Comment by marktopper** [comment]
Im open for pull requests on this one.

**Comment by tnylea** [comment]
This has been fixed in the latest version `0.10.6` see the following PR that has resolved this: https://github.com/the-control-group/voyager/pull/446

Thanks 👍
