### ISSUE TITLE
Let us create our own Page structures

### ISSUE THREAD

**Issue by patlecat** [thedevdojo/voyager#1561]
It would be nice not to be tied to what you defined to be a page but to create our own pages with our own structure and content, but still to be able to manage them in Voyager. This in a submenu would make it very compact in the sidebar-menu.
Then Voyager would be more versatile than just for creating small blogs.

**Comment by fletch3555** [comment]
Voyager is certainly not bound to "small blogs".  Voyager is also certainly not intended to be a CMS.  You're free to customize it as much as you wish, but overriding views, customizing models or controllers, etc.  Voyager is intended to be an admin tool that you can use to manage your site.

If you have specific issues, we're more than happy to work on them.  If you wish to discuss large-scale rewrites of features, that would be much better suited for our Slack group.

**Comment by patlecat** [comment]
@fletch3555  Okay then I suggest you write some more extensive documentation inside and outside of the application. If you think it's not an issue then I may not have understood how you intend Voyager to be used. It should offer much more than just being a more comfortable phpmyadmin in my view.
