### ISSUE TITLE
Need to add page to admin and authenticate

### ISSUE THREAD

**Issue by mjmarcell** [thedevdojo/voyager#1570]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version:
- Database Driver & Version:

### Description:
I would like to add my own custom routes to the admin panel and ensure the user is logged in before they have access. These views have functionality that doesn't fit the scope of what Voyager can do, so I built my own, I'm trying to make them act like they are part of the admin panel. I almost have this accomplished, but I can't figure out how to implement the authentication used for voyager routes. Any help on this would be appreciated.

### Steps To Reproduce:

1. Create a standard Laravel Route
2. ???

**Comment by fletch3555** [comment]
Add the route right after `Voyager::routes();`. and add the `admin.user` middleware to it

**Comment by mjmarcell** [comment]
Perfect! Worked like a charm! Thanks!
