### ISSUE TITLE
Settings page is not showing options for updating settings like logo, title etc.

### ISSUE THREAD

**Issue by kdpisda** [thedevdojo/voyager#1571]
- Laravel Version: 5.4.#
- Voyager Version: 0.11.14
- PHP Version: 7.x
- Database Driver & Version: Mysql 5.7

### Description:
I installed voyager in my laravel project but I am not getting the options to change logo, images, title etc in settings page.
![screenshot from 2017-08-17 20-47-57](https://user-images.githubusercontent.com/22424149/29419702-6719dab4-838d-11e7-96f0-f8f37de82560.png)

**Comment by emptynick** [comment]
What do you mean? If you change the data and click "Save Settings" it will not save?

**Comment by kdpisda** [comment]
No I had seen options for changing logo, loader, title, background etc in my previous installation. But now I am not getting so.

**Comment by marktopper** [comment]
This can be because that your installation failed partially, and the seeding of settings was never ran.
This can be fixed running `php artisan db:seed --class=VoyagerDatabaseSeeder`.

**Comment by buckhornmktg** [comment]
I did not install the dummy data, so this didn't work for me. I had to use: 

`php artisan db:seed --class=SettingsTableSeeder`
