### ISSUE TITLE
base table or view not found

### ISSUE THREAD

**Issue by avajbt** [thedevdojo/voyager#1575]
- Laravel Version: 5.4.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version: phpmyadmin 127.0.01

### Description:

QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.create_new_projects' doesn't exist (SQL: select * from `create_new_projects` order by `created_at` desc)

### Steps To Reproduce:

i just created a new database and make bread.

after I type in the url the admin/createnewfolder (which is the url typed in bread).

then it shows the error above.

**Comment by fletch3555** [comment]
What is the table name you've created? Given the phrasing you're using, I'm inclined to believe you may be misusing the functionality.

**Comment by TetoraK** [comment]
PHP: 7.1.7
Laravel: 5.4
Voyager: 0.11.14
DB: MySQL 5.7.19 
Other: Laragon

Getting the same issue. 
Voyager Database "Create New Table" function doesn't seem to create a table in the database, even though a "succeess" alert popped up.

**Comment by marktopper** [comment]
Please include the Voyager version number when reporting an issue

**Comment by TetoraK** [comment]
Corrected it. Meant Voyager and not Laravel 0.11.14

**Comment by marktopper** [comment]
What is the name of the table you have created?

**Comment by marktopper** [comment]
Can you try to describe the exact steps you have done to get this issue, then I will try to recreate it in a moment.

**Comment by TetoraK** [comment]
"article". Also tried various other names like test, news, post. 

- Voyager Admin -> Tools -> Database -> Create new Table
- Insert table name, some columns and press "Create New Table". (Tried with / without model and additional columns)
- Getting message that creating the table was successfully done
- Create BREAD
- Go to Admin role and give permission to everything 
- Go to projectname.dev/admin/databasename
- Error:

> (3/3) QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'news.articles' doesn't exist (SQL: select * from `articles` order by `created_at` desc)

It appears in the database list of voyager, but nothing in my actual database. Also tried without model.

![tcz1ylv](https://user-images.githubusercontent.com/28731989/29519448-ce9ea3d4-867d-11e7-98b7-5ef39b3d6493.png)

**Comment by marktopper** [comment]
Well, you will have to either call you table `articles` or setting you model `Article` to have:
```
protected $table = 'article';
```

This is because the table names by default are gonna be the plural mode of the model name.

**Comment by rocketdf** [comment]
@marktopper Thx for information and tutorial

**Comment by sshindeBB** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'Proficiency.t_indicator_proficiency_levels' doesn't exist

I got same error
For that I add new missing table to test database but it was fine for first time(only for single execution ) after that it gives me same error. can anybody help me out from this?

**Comment by fletch3555** [comment]
This issue has been closed for over 9 months now.  Please open your own or ask for help on our slack group.
