### ISSUE TITLE
Soft Delete in Voyager

### ISSUE THREAD

**Issue by vitormicillo** [thedevdojo/voyager#1577]
- Laravel Version: 5.4
- Voyager Version: v0.11.14
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
I'm not sure if it's a problem or if I'm doing something wrong.
I created a new table with the voyager management and included the Soft Deletes option, then I created the BREAD normally as usual.
I believed that by removing an item from the registry by CRUD created by BREAD it would not be actually deleted but just inserted the date in the field deleted_at in the database and the item would still be listed normally, but with the status of deleted or awaiting final deletion

1. https://nimbus.everhelper.me/client/notes/share/1073447/zkq00p9wbm3lhg8udlbh
2. https://nimbus.everhelper.me/client/notes/share/1073449/z8cnqc25ye988ehupl5y
3. https://nimbus.everhelper.me/client/notes/share/1073450/bre9z3ndcmy2frltb3bn

### Steps To Reproduce:
1. Create a new table with Soft Delete
2. Create a BREAD for this new table
3. Register some items
4. Delete one of these items

**Comment by marktopper** [comment]
Talked with Victor on our chat. And he was missing the `SoftDeletes` trait.

I think it will be a good idea to mention in the database builder when adding the `deleted_at` field that they will have to add this trait for it to work.
