### ISSUE TITLE
Restful API

### ISSUE THREAD

**Issue by mimrank** [thedevdojo/voyager#158]
is it support multi-language functionality? Are you have any plan to provide this functionality? and also Rest full API as well.

**Comment by marktopper** [comment]
Multi-language functionally will comes once we move to Laravel 5.4, but properly not before that.
Also there are already multiple issues about that, so I am changing the name for your issue to be only about the restfull API.

However a restfull API would be interesting.

**Comment by edmeehan-tcg** [comment]
What would be some use cases for an API with voyager?
Would it be just for the routes and controls used by voyager?

**Comment by handiwijoyo** [comment]
API can be useful to retrieve and save BREAD data. But, I'm not sure we need to add that to core functionality of Voyager because we will need to implement different Auth method such as OAuth2 using Laravel Passport or JWT. Another approach will be an extension package to support this API.

**Comment by fletch3555** [comment]
I agree. I think API functionality can be a "plugin" for voyager and should be viewed as it's own project.

**Comment by sidis405** [comment]
@mimrank Api with Passport should not be much of a problem to do.
Could you provide a use case for the API?
Would you plan to use Voyager through api and perhaps code a client in Vue/React/Angular or something of the like?

**Comment by gpolitog** [comment]
Any plans/news on REST API?  
It would be great to generate and administer a backend with Voyager, and then consume it with a mobile app via the REST API.

I have seen several admin packages, but haven't found one yet that has this feature.

**Comment by fletch3555** [comment]
You likely haven't seen that feature in an Admin package because it generally goes beyond the scope of an admin package.  An admin tool simply provides one means of accessing/editing data associated with your site.  Your site is another means of accessing/displaying this data.  An API may be a 3rd, but is not directly associated with the Admin view.

**Comment by fletch3555** [comment]
I'm closing this for now since nobody has been able to provide a valid use-case for this.  We may revisit the idea if a use-case manifests itself.

**Comment by ventouris** [comment]
I search all the issues and I saw that there were cases asked about a REST Full API feature. I use to work with Laravel API + Angular or Ionic for websites and mobile apps. Most of the times, I have to build an admin as well to add/edit users and edit data from the models. This was so time consuming, that I had second thoughts about using Laravel. Is there anyone who has worked on a plugin to include JWT and API resources? Or has done it manually on Voyager and can share his code?

**Comment by fletch3555** [comment]
@ventouris, this issue has been closed for 5 months now.  If you have an issue, you should create your own instead of commenting on one that has been closed for so long.  Also, your comment is a question, not an issue, so it would be best asked in our Slack group or other means.  Github issues should be reserved for issues with the Voyager code, not questions about implementation.

**Comment by karneaud** [comment]
+1 for @ventouris  comment

It would be nice for Voyager to be RESTful to provide easier means of managing a mobile apps content which uses API

**Comment by fletch3555** [comment]
@karneaud, please read my previous comment.

Voyager does not need an API, since it interacts with the database. If your app needs an API for mobile purposes, then build one. It'll pull from the same database, so Voyager is still managing the data.  Voyager is an admin tool, not a CMS

**Comment by icoco** [comment]
API first... although it only a tool but also can use for many other purpose , eg, manage site from mobile then the RESTful API will be very usefully
