### ISSUE TITLE
Users table changed auth (multi auth issue)

### ISSUE THREAD

**Issue by Chathula** [thedevdojo/voyager#1580]
- Laravel Version: 5.4.x
- Voyager Version: latest
- PHP Version: 7.0
- Database Driver & Version: mariadb

### Description:
i tried to install this for another table called "admins", i set all the configurations according to the doc.i changed the migrations for also for admins instead of users table. but i couldn't get this done. after i set admin as web default gaurd. i logged in i think, but it shows an error in dashboard view files. i tried everything. but couldn't.. is there any way to setup this for another table/model.

Thank You....

**Comment by lancepioch** [comment]
Labels: possible bug or invalid

**Comment by sachin** [comment]
hi Chathula,

I have the same requirements and the solution as follows.

**Problem 1:**
Actually, Voyager has a tight coupling with the user table. If you look into the code of Voyager user model in the source code (vendor/tcg/voyager/src/Models/User.php), database connection table is not configurable. It will always connect to the users table.

**Solution:** We have to override the class and assign and add the protected $tablename to the table we want to bind. I create a new class in config folder thats look like
```
<?php

namespace TCG\Voyager\Models;

use Carbon\Carbon;
use Illuminate\Foundation\Auth\User as Authenticatable;
use TCG\Voyager\Contracts\User as UserContract;
use TCG\Voyager\Traits\VoyagerUser;

class User extends Authenticatable implements UserContract
{
    use VoyagerUser;

    protected $guarded = [];

    protected $table = 'admins';

    public function getAvatarAttribute($value)
    {
        if (is_null($value)) {
            return config('voyager.user.default_avatar', 'users/default.png');
        }

        return $value;
    }

    public function setCreatedAtAttribute($value)
    {
        $this->attributes['created_at'] = Carbon::parse($value)->format('Y-m-d H:i:s');
    }
}
```



Actually, i copied the Voyager user model and just add the 
```
protected $table = 'admins';
```

**NOTE:** Don't change any namespace.

**Problem2** Authentication. Voyager uses Auth for login. Voyager uses default guard. Which tries to authenticate from the users table, But are admin's records saved in admins table.

**Solution:** We need to create a new guard and change the default guard under auth.php under config folder. My code looks like
```
'defaults' => [
        'guard' => 'web_admin',
        'passwords' => 'web_admin',
    ]
```

Change the default guard.
```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],

        'api' => [
            'driver' => 'passport',
            'provider' => 'users',
        ],

        'web_admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],
    ],
```
```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],

        'admins' => [
            'driver' => 'eloquent',
            'model' => App\Admin::class,
            'table' => 'admins',
        ],

        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```
```
'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],

        'admins' => [
            'provider' => 'admins',
            'table' => 'password_resets',
            'expire' => 60,
        ],
    ],
```

I hope this will help
[VoyagerChanges.zip](https://github.com/the-control-group/voyager/files/1452833/VoyagerChanges.zip)

**Comment by Chathula** [comment]
@sachin  Thank you for help.. will give a try in the future :D

**Comment by riyas1012** [comment]
@sachin did you just add 
**protected $table = 'admins';**
in TCG\Voyager\Models\User.php , Or you create a new class?

**Comment by fletch3555** [comment]
@riyas1012, this has been closed for well over a year and is for a MUCH older version.  Please don't comment on old/closed issues
