### ISSUE TITLE
Can't view when multiple-select

### ISSUE THREAD

**Issue by doatta** [thedevdojo/voyager#1593]
- Laravel Version: 5.4.32
- Voyager Version: 0.11.*
- PHP Version: 5.6.30
- Database Driver & Version: MySQL InnoDB

### Description:
I've configured multi select and now when I press "View" i get error "Invalid argument supplied for foreach() (View /path/to/read.blade.php)
The issue looks like issue #984  but It's ok when I save, only get error when try to view. When I edit, I can see saved items. 

### Steps To Reproduce:

Main form:

```
class Form1s extends Model
{
        public function problems()
        {
                return $this->belongsToMany(Problemler::class, 'form1_and_problems', 'form1_id', 'problem_id');
        }
}
```

Model Problemler

```
class Problemler extends Model
{
        protected $primaryKey = 'p_id';
}
```

As I say, everything shows and saves without problem, the only problem with read.blade.php...

![1](https://user-images.githubusercontent.com/22026996/29622344-3aae6a0c-8834-11e7-8ad4-2fb35febd699.png)

**Comment by doatta** [comment]
Btw, Is it possible to have multi select without creating relationship? Like with Select Dropdown, you can add JSON options. Error I get - array to string conversion.

**Comment by adriangordon1231** [comment]
I am experiencing the same issue as well

**Comment by ashraful88** [comment]
I found a temporary solution to view multi select items. I just get it from edit form.
add this to read.blade.php right after`@elseif($row->type == 'select_multiple')`
this will load multi-select but disabled just to show

``` @elseif($row->type == 'select_multiple')
                                @if(property_exists($rowDetails, 'relationship'))
                                <select disabled class="form-control select2" name="{{ $row->field }}[]" multiple>
                                            <?php $options = $rowDetails;
                                            $selected_values = isset($dataTypeContent) ? $dataTypeContent->{camel_case($row->field)}()->pluck($options->relationship->key)->all() : array(); ?>
                                            <?php
                                            $relationshipListMethod = camel_case($row->field) . 'List';
                                            if (isset($dataTypeContent) && method_exists($dataTypeContent, $relationshipListMethod)) {
                                                $relationshipOptions = $dataTypeContent->$relationshipListMethod();
                                            } else {
                                                $relationshipClass = get_class(app($dataType->model_name)->{camel_case($row->field)}()->getRelated());
                                                $relationshipOptions = $relationshipClass::all();
                                            }
                                            ?>
                                            @foreach($relationshipOptions as $relationshipOption)
                                                <option value="{{ $relationshipOption->{$options->relationship->key} }}" @if(in_array($relationshipOption->{$options->relationship->key}, $selected_values)){{ 'selected="selected"' }}@endif>{{ $relationshipOption->{$options->relationship->label} }}</option>
                                            @endforeach

                                </select> ```

**Comment by doatta** [comment]
I'm still facing problem with multiple select... Can anyone help to make array to sting conversion (not to use "relationship", but to use "options"

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by handiwijoyo** [comment]
Voyager `1.0` using new relationship feature. Please try using it and open new issue if the problem still exist.
