### ISSUE TITLE
Missing CSS in flat-green.css (as opposed to flat-blue.css)

### ISSUE THREAD

**Issue by xotik** [thedevdojo/voyager#1594]
- Laravel Version: 5.3
- Voyager Version: 0.11.14
- PHP Version:
- Database Driver & Version:

### Description:
Hi everyone!

Just noticed a missing declaration in the green theme css file, as opposed to the blue theme.

On the blue one you have:
```
.flat-blue .app-footer {
    opacity: 0.7;
    color: #353d47;
    width: 100%;
    text-align: right;
    padding: 10px 0;
    background: #fff;
    left: 0px;
}
```
While on the green:

```
.flat-green .app-footer {
    opacity: 0.7;
    color: #353d47;
}
```

That's it!

**Comment by lancepioch** [comment]
Labels: design, bug

**Comment by emptynick** [comment]
I think this is not valid anymore?

**Comment by handiwijoyo** [comment]
Can someone confirm this issue?

**Comment by cyrildewit** [comment]
I can't find these files (`flat-green.css` and `flat-blue.css`) anywhere in the source code, so it's probably not an issue anymore.
