### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by fiter92** [thedevdojo/voyager#1595]
- Laravel Version: 5.4
- Voyager Version:  0.11.14
- PHP Version: 7.1

### Description:
I have a simple users with Zizaco\Entrust roles, I installed Voyager for admins and now I have a few questions:
1) Is it ok that simple users whith doesn't have any voyager roles can log in using /admin/login form? Is there way to disable log in for simple users using this form?
2) When a simple user whith doesn't have any voyager roles open an /admin page he gets an error:
```
Call to a member function relationLoaded() on null
in VoyagerUser.php (line 53) at User->hasPermission('browse_admin') in VoyagerAdminMiddleware.php (line 24)
```
How can I redirect user to homepage instead of this error?

**Comment by fletch3555** [comment]
Voyager does not currently function in parallel to Entrust.  Voyager requires the built-in Laravel Auth scaffolding to manage it's authentication.  This is an open-source package, so you're more than welcome to hack away at it to make it work (we'd certainly be interested in seeing a working version, but it would have to support built-in Auth as well).  Just keep in mind that we'll be unable to support you with any local changes you make to the package, and you will be on your own with version upgrades.
