### ISSUE TITLE
Is there a plan to support multiple languages? I need other language packs

### ISSUE THREAD

**Issue by maximus-1024** [thedevdojo/voyager#1599]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by marco-solare** [comment]
have a look into:
https://github.com/the-control-group/voyager/tree/master/publishable/lang

 	ar 	Removed unnecessary files 	23 hours ago
	de 	StyleCI fixes (three spaces at end of line) 	2 months ago
	en 	Add error message if key already exists 	14 days ago
	es 	Update voyager.php 	2 months ago
	fr 	Add french translation (#1479) 	a month ago
	pt 	Merging master branch into 1.0-pre-release 	a month ago
	pt_br 	Adds missing translated strings and fix formatting 	2 months ago
	ru 	fixes for styleci and codeclimate 

which language are you interested in having supported?
Is it in the list?

**Comment by litchii** [comment]
@marco-solare    how i translate to french or arabic !!!

**Comment by akazorg** [comment]
Hi @litchii, French and Arabic is already supported.
Check out [this thread](https://github.com/the-control-group/voyager/issues/1364).

**Comment by fletch3555** [comment]
Closing as an answer has already been provided.
