### ISSUE TITLE
POST is always triggered twice

### ISSUE THREAD

**Issue by qprotex** [thedevdojo/voyager#1600]
- Laravel Version: 5.4.28
- Voyager Version: 0.11.14
- PHP Version: 7.1.3-3
- Database Driver & Version: MySQL

### Description:
After some weird behavior on some breads I found out using a Proxy that every POST request is always triggered twice for some reason. For most scenario that does not matter but in some cases it duplicates data or execute the logic two times.

![image](https://user-images.githubusercontent.com/13024779/29692355-8a31873e-88fd-11e7-8d60-ee9f0754baaf.png)

![image](https://user-images.githubusercontent.com/13024779/29692369-9e338d9a-88fd-11e7-907f-4a9f11dc8713.png)

![image](https://user-images.githubusercontent.com/13024779/29692474-416b6136-88fe-11e7-8d37-54e330d189cf.png)

The difference is that the first it has the header X-Requested-With: XMLHttpRequest and the response is 200. The second time is executed it does not have X-Requested-With: XMLHttpRequest and the response is 302 but sometimes is 200 also.

### Steps To Reproduce:

1. Open a web proxy or Network tab in Chome
2. Execute a BREAD save
3. Two POST are triggered, one with XHR and one without it.

**Comment by fletch3555** [comment]
Sounds like we have some JS that might need "PreventDefault".... @tnylea, it sounds like a JS change, mind seeing if you can track it down?

**Comment by AdrianKuriata** [comment]
First request is a checking your form has a validation errors, if has you will get a message with your fields errors(first request), if doesn't have errors form is unbind from submit and submiting form without errors to controller(second request). This is not saving twice your bread, just first request is checking for your form has validations errors.

**Comment by qprotex** [comment]
Got it. I was missing if (!$request->ajax())  in my custom controller to ignore the validation call.
