### ISSUE TITLE
QueryException SQLSTATE[23000]: Column cannot be null 

### ISSUE THREAD

**Issue by JMultimidia** [thedevdojo/voyager#1605]
- Laravel Version: Laravel Framework 5.4.33
- Voyager Version: 0.11.14
- PHP Version: 5.6.16
- Database Driver & Version: MySQL 5.7.9

**Description:**

I created a Table "produtos"  and the Bread normally.
However in the form when trying to eg register the non-null field, the following message appears:

3/3) QueryException
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'titulo' cannot be null (SQL: insert into `produtos` (`titulo`, `palavras_chave`, `resumo`, `texto`, `imagem`, `status`, `visitas`, `updated_at`, `created_at`) values (, , , , , 0, , 2017-08-26 22:39:20, 2017-08-26 22:39:20))
```

How do I validate form data and avoid displaying this error page?

PORTUGUÊS-BR
Eu criei a "Tabela" e a "Bread" normalmente. 
Porém no formulário ao tentar por exemplo cadastrar o campo não nulo, aparece a seguinte mensagem:

Como faço para validar os dados do formulário e evitar exibir esta página de erro.

**Comment by gausam** [comment]
https://voyager.readme.io/docs/validation & https://voyager-cheatsheet.ulties.com/#rules are your friend.

**Comment by lancepioch** [comment]
Labels: invalid

Close (no user response)
