### ISSUE TITLE
Rich text editor view

### ISSUE THREAD

**Issue by doatta** [thedevdojo/voyager#1606]
- Laravel Version: #.#.#
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version:

### Description:
Hi!

I'm not programmer, but had problem with Rich Text Box. I edited text successfully, but in view I only see text without any format. So I tried to fix it by myself and in read.blade.php changed string
` <p>{{ strip_tags($dataTypeContent->{$row->field}, '<b><i>') }}</p> `

to 

`        <p>{!! ($dataTypeContent->{$row->field}) !!}</p> `

And now I see formatted text in View! 
Don't sure is it fix or not...

**Comment by tnylea** [comment]
Thanks @doatta,

This will be updated in version 1.0 👍  I've just pushed a fix for this.
