### ISSUE TITLE
Slugify for voyager not support vietnammese

### ISSUE THREAD

**Issue by nguyentrongthanh** [thedevdojo/voyager#1607]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.14
- PHP Version: 5.6.30
- Database Driver & Version: MySQL 5.6.35

### Description: Slugify for voyager not support vietnammese
**title**: tiếng việt
**slug**: ti-ng-vi-t

**Comment by lancepioch** [comment]
Labels: locale

**Comment by fletch3555** [comment]
I believe a fix for this has been submitted by @vanloc0301.  Please try v1.0 and reopen if necessary
