### ISSUE TITLE
Create a few BREADs for a table

### ISSUE THREAD

**Issue by fiter92** [thedevdojo/voyager#1609]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1

### Description:
Is there any way to create a few BREADs for one table?
Example: 
1) Admins - users with admin permissions only
2) Active users - users with field 'active' = true
3) Inactive users - users with field 'active' = false

**Comment by fletch3555** [comment]
No, not currently, and likely will not be in the future.  That specific use-case would be better served by a single BREAD with filters on the page.  We may implement filters in the future, but it's also not currently supported.

**Comment by doatta** [comment]
I'm doing it via Models. 
So you create few tables, add create breads for all of them, but in Bread configuration use the same Model. Main table needs to include all fields, but other tables can include only required fields (field names need to be the same as on main table).

**Comment by lancepioch** [comment]
Labels: invalid, feature

Close (not going to happen)
