### ISSUE TITLE
one to many data not showing

### ISSUE THREAD

**Issue by amburadudulz** [thedevdojo/voyager#1611]
#- Laravel Version: 5.4.#
- Voyager Version: last
- PHP Version: 7.1.7
- Database Driver & Version: mysql

### Description:
sorry for my bad english before.
I have problem with showing list "network" data from "about"  

### Steps To Reproduce:
this is my detail
1.data not show
<a href="https://ibb.co/fmNC1k"><img src="https://thumb.ibb.co/fmNC1k/1.png" alt="1" border="0"></a> 
2. relationship
<a href="https://ibb.co/dqrSZ5"><img src="https://thumb.ibb.co/dqrSZ5/2.png" alt="2" border="0"></a>
3.tabel
<a href="https://ibb.co/dz71u5"><img src="https://thumb.ibb.co/dz71u5/3.png" alt="3" border="0"></a>
4.model network
<a href="https://ibb.co/ef1i7Q"><img src="https://thumb.ibb.co/ef1i7Q/4.png" alt="4" border="0"></a>
5. model about
```
 public function networkId()
		{

   return $this->hasMany(Network::class);
		}

```
`
no giving an error but i don't know where the problem.
thanks

**Comment by ashraful88** [comment]
try create method for networkId() not aboutId()

**Comment by amburadudulz** [comment]
@ashraful88 my wrong sir, that capture from "network" model not "about" model.. i also make a function in about model

```
public function networkId()
{
    return $this->hasMany(Network::class);
}
```
and the result is same, not giving value
sorry for my bad english

**Comment by ashraful88** [comment]
as per documentation says :
"Using a multi select dropdown we can create a belongsToMany relationship. This adds a Many-to-Many relationship between 2 tables using a pivot table." 

multi select may be not currently supports One-to-Many. use Many-to-many with multi select (you have to create pivot table)

**Comment by amburadudulz** [comment]
@ashraful88 sir, can u give me example how to make one - many relationship from type data until model because i try use another type data but fail when i want to show from one to many but success when data from many to one
<a href="https://ibb.co/gV35P5"><img src="https://thumb.ibb.co/gV35P5/6.png" alt="6" border="0"></a>

**Comment by lancepioch** [comment]
Labels: invalid

Close (did not rtm)
