### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1614]
The next release will be for Laravel 5.5, or for both versions 5.4 & 5.5?
And please dont forget that many dependencies doesn't support Laravel 5.5(If you suggest migrating from 5.4 to 5.5) for now and dont forget your old users of Voyager to have new cool stuf

**Comment by fletch3555** [comment]
The new version of Voyager (1.0) will support Laravel 5.3, 5.4, and 5.5.  It will not require any specific version to run, so it will not affect your project or its other dependencies.

**Comment by davodavodavo3** [comment]
Super @fletch3555 why did not write earlier)))))))
