### ISSUE TITLE
not seeing a menu and  view for newly created bread

### ISSUE THREAD

**Issue by mazeeblanke** [thedevdojo/voyager#1616]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
i can not see a menu and  view for newly created bread, is this an error ? if not please help future users and i to appreciate this package better by providing good documentation. thanks

**Comment by doatta** [comment]
Have you give your current role permissions to new bread? It's done in "Roles"

**Comment by mazeeblanke** [comment]
i think i have figured it out thanks, i watched the youtube explanation
