### ISSUE TITLE
Too many queries

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1618]
- Laravel Version: 5.4
- Voyager Version: master
- PHP Version: 7.1

Too many queries on the page, only 36 mysql queries on dashborad page.
With multilingual disabled there is 24 queries again a lot.

**Comment by lancepioch** [comment]
Labels: enhancement, help wanted

**Comment by fletch3555** [comment]
I don't believe we will be merging the lock screen feature.  Also, please try to maintain 1 topic per issue.

I agree that the query count is too high.  We should work to improve that.

**Comment by emptynick** [comment]
We significantly decreased the query amount in https://github.com/the-control-group/voyager/pull/2812 and https://github.com/the-control-group/voyager/pull/2832
