### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by wowcut** [thedevdojo/voyager#1621]
There is no information about Laravel 5.5 compatibility and features. The Beta for 5.5 was available for quite some time, are you as developers working on a version that would allow for simpler installation process e.g. or use other Laravel 5.5 features?

**Comment by imabug** [comment]
just attempted the Laravel 5.5 upgrade and got

>   Problem 1
>    - tcg/voyager v0.11.14 requires illuminate/support ~5.3.0|~5.4.0 -> satisfiable by laravel/framework[v5.4.35], illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
>    - tcg/voyager v0.11.12 requires illuminate/support ~5.3.0|~5.4.0 -> satisfiable by laravel/framework[v5.4.35], illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
>    - tcg/voyager v0.11.14 requires illuminate/support ~5.3.0|~5.4.0 -> satisfiable by laravel/framework[v5.4.35], illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

**Comment by davodavodavo3** [comment]
the master branch is for Laravel 5.5 as far as I know

**Comment by akazorg** [comment]
Hey guys, like @davodavodavo3 mentioned, use the master branch for the Laravel 5.5 version.
We are working on the release of Voyager 1.0 that will support all the new features of L 5.5.

If you find any issue, please let us know.
Happy coding ^^

**Comment by aescasio** [comment]
@akazorg 

Great, please mentioned me when released. I'm excited to use this on my next project since I planning to use the latest laravel.
