### ISSUE TITLE
fire got renamed into handle (laravel 5.5)

### ISSUE THREAD

**Issue by greut** [thedevdojo/voyager#1624]
- Laravel Version: 5.5.0
- Voyager Version: dev-master
- PHP Version: 7.1.6
- Database Driver & Version:

### Description:

The some voyager commands are failing when used with Laravel 5.5.

> ### The `fire` Method
>
> Any `fire` methods present on your Artisan commands should be renamed to `handle`.
>
> https://laravel.com/docs/master/upgrade

### Steps To Reproduce:

    $ php artisan voyager:admin me@example.org
        [ReflectionException]                                                                                          
        Method TCG\Voyager\Commands\AdminCommand::handle() does not exist

**Comment by greut** [comment]
relevant PR.. https://github.com/laravel/framework/pull/20024

**Comment by akazorg** [comment]
Thanks @greut, there is work in progress on branch [backward-support](https://github.com/the-control-group/voyager/blob/backward-support/src/Commands/AdminCommand.php#L36). Soon will be released.

**Comment by greut** [comment]
I'll test `dev-backward-support` then. Cheers,

**Comment by fletch3555** [comment]
This has been fixed in backwards-support as mentioned.  Closing.
