### ISSUE TITLE
Unable to install Voyager

### ISSUE THREAD

**Issue by mergederg** [thedevdojo/voyager#1625]
- Laravel Version: Current (whatever 'laravel new' gives me)
- Voyager Version: Current (whatever 'composer require tcg/voyager' should give me)
- PHP Version: 7.0.9
- Database Driver & Version: Doesn't get far enough to matter

### Description:
In attempting to install voyager, getting this as an error:

```
D:\Laravel Sites\voyager> composer require tcg/voyager
Using version ^0.11.14 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tcg/voyager ^0.11.14 -> satisfiable by tcg/voyager[v0.11.14].
    - Conclusion: remove laravel/framework v5.5.0
    - Conclusion: don't install laravel/framework v5.5.0
    - tcg/voyager v0.11.14 requires illuminate/support ~5.3.0|~5.4.0 -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.5.0
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.5.0
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0].
```

No 'tcg' folder is generated/populated in 'vendor' as a result of this, so the next suggested step of `php artisan voyager:install` always fails:

```
D:\Laravel Sites\voyager> php artisan voyager:install
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'TCG\Voyager\VoyagerServiceProvider' not found
```

### Steps To Reproduce:
Run `laravel new voyager`, then within the new voyager directory, attempt `composer require tcg/voyager`.  Lastly, attempt `php artisan voyager:install`.

**Comment by tnylea** [comment]
Laravel 5.5 just got released today :) We are still working on version 1.0 and I will make sure to add 5.5 to the list of dependencies on version 0.11.

Talking with a few of the other members to get this updated.

If you want to use it right now you can use Laravel 5.4 or you can use Laravel dev version with:

`laravel new folder --dev` and then when you include voyager you will write:

`composer require tcg/voyager dev-master`

Thanks :) We'll get 1.0 released here very soon :)

**Comment by davodavodavo3** [comment]
@tnylea are you here?

**Comment by mergederg** [comment]
Ah.  Guess I'm just getting it at a bad time, heh.

Using --dev and dev-master is working out fine for now, thanks.  :)

**Comment by tnylea** [comment]
for sure. @davodavodavo3 I'm here. What's up?

1.0 will be releasing real soon 👍

**Comment by davodavodavo3** [comment]
How are you? 
Do you remember me? 
I warned you  that customer can watch the video without subsription on DevDOJO))))But the question is different
make sure to add 5.5 to the list of dependencies on version 0.11???????????????????????????????
There are many dependencies like LaravelColective and other that doesnt support Laravel 5.5 for now.
Dont do that , 
You suspend the projects of others. Has it been 7 months since 5.4 came out and you want to kill these projects?

**Comment by davodavodavo3** [comment]
I open an issue titled Question? you can answer there)))

**Comment by fletch3555** [comment]
@davodavodavo3, Voyager v0.11.* will not support Laravel 5.5.  You will need to upgrade to Voyager v1.0 when it's released (coming soon).

**Comment by fletch3555** [comment]
Closing this issue as the original question has been answered

**Comment by davodavodavo3** [comment]
I understand this, I'm not talking about this, I want to understand whether we get updates for older versions of Voyager v0.11.*
I open an issue titled Question? you can answer there)))

**Comment by alibenali** [comment]
I have the same problem how to resolve it ?

I have LARAVEL 5.8.17 And i am trying to install voyager 
this is the error:

 composer require  tcg/voyager
Using version ^1.2 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager 1.2.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager 1.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.0 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.1 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.2 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.3 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.4 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.5 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.6 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - intervention/image 2.4.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.5.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.3 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for tcg/voyager ^1.2 -> satisfiable by tcg/voyager[1.2.x-dev, 1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /opt/alt/php71/etc/php.ini
    - /opt/alt/php71/link/conf/alt_php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
[cocknoti@server231 myapp]$ Installation failed, reverting ./composer.json to its original content.
-bash: Installation: command not found
[cocknoti@server231 myapp]$ ^C
[cocknoti@server231 myapp]$ ^C
[cocknoti@server231 myapp]$
login as: cocknoti
cocknoti@khadamat.ml's password:
[cocknoti@server231 ~]$ cd khadamat.ml
[cocknoti@server231 khadamat.ml]$ cd myapp
[cocknoti@server231 myapp]$ composer require tcg/voyager

Using version ^1.2 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager 1.2.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager 1.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.0 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.1 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.2 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.3 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.4 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.5 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - tcg/voyager v1.2.6 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.4.x-dev].
    - intervention/image 2.4.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.5.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.3 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for tcg/voyager ^1.2 -> satisfiable by tcg/voyager[1.2.x-dev, 1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /opt/alt/php71/etc/php.ini
    - /opt/alt/php71/link/conf/alt_php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by fletch3555** [comment]
@alibenali it's not the same problem since you're on a MUCH newer version.  Please don't comment on closed issues, especially when they've been closed for nearly 2 years.

The answer to your problem is toward the bottom of that message.  If you need further help interpreting it, you can ask on slack (or larachat slack, laravel discord, laracasts forums, etc. Because it's not specific to voyager)
