### ISSUE TITLE
issue with laravel voyager rich text editor, when i insert youtube video it does not behave responsive.

### ISSUE THREAD

**Issue by ishubhagarwal** [thedevdojo/voyager#1627]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I am using voyager admin for my backend when I insert youtube video in from rich text editor it does not behave responsively. how to make it responsive for all the devices.

**Comment by tnylea** [comment]
This will need to be something that gets implemented on the front-end when it is displayed for the user. I would recommend using [http://fitvidsjs.com/](http://fitvidsjs.com/) It works with Youtube vimeo, and many other video embeds.

Let me know if that makes sense :)

Thanks.

**Comment by ishubhagarwal** [comment]
Thanks tnylea for the reply but can we implement this with Laravel voyager admin panel?
