### ISSUE TITLE
Sentence

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1641]
Can we add admin prefix in admin_menu_blade.php like this 

`$linkAttributes =  'href="' . url(config('voyager.prefix').'/'.$item->link()) .'"';`

to prevent writing prefix(/admin) on every menu-item creation?
This solution will add admin prefix automatically on every menu-item.
Maybe only for admin menu and for Static URL!!!!
Of Course then external URL-s will not work, but do wee need external URL in admin panel?))))hmmmm
Or maybe create new Link type like External URL for that solution?

**Comment by fletch3555** [comment]
No, we want the Menu items to be as flexible as possible.  We recommend using dynamic links and using the route name (i.e. `voyager.users.index`) to get the prefix appended automatically.
