### ISSUE TITLE
Resize to exact given dimension

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1643]
Hello how can i resize a picture to the exact given size ?

for test i have added this to my bread

```
{
    "resize": {
        "width": "384",
        "height": "216"
    }
}
```
when i upload a image from a dimension of
640px witdh & 480px height

it creates a image of 288 witdh x 216 height dimension

so why does it not creates a exact given dimension ?

**Comment by davodavodavo3** [comment]
In Voyager controller on upload image there is 
```
// constrain aspect ratio
$constraint->aspectRatio();

// prevent possible upsizing
$constraint->upsize();
```

probably for proportion preservation

**Comment by lancepioch** [comment]
Labels: question

Close (solution provided)
