### ISSUE TITLE
Method handle() doesnt exist using artisan voyager:controllers

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1645]
- Laravel Version: 5.5.1
- Voyager Version: dev-master

### Description:
when running `artisan voyager:controllers` 
anyone that runs laravel 5.5.* will get this error
```
[ReflectionException]
Method TCG\Voyager\Commands\ControllersCommand::handle() does not exist
```

### Steps To Reproduce:

Rename every `fire()` method to` handle()`

please see #1644

**Comment by tnylea** [comment]
Just merged in your PR 👍 

Thanks!
