### ISSUE TITLE
got an error with enabled multilingual on fresh installed admin panel

### ISSUE THREAD

**Issue by vshapovalov** [thedevdojo/voyager#1646]
- Laravel Version: 5.5.x-dev 7166315
- Voyager Version: dev-master 0fa753f
- PHP Version: 7.1.7
- Database Driver & Version: 

### Description:

i've got an error with enabled multilingual on fresh installed admin panel

### Steps To Reproduce:

1. install fresh dev laravel, 
2. require tcg/voyager dev with dummy data
3. enable multilingual in config/voyager.php
4. login by default admin
5. go to posts - /admin/posts

LogicException thrown with message "TCG\Voyager\Models\Post::translatable must return a relationship instance."
[Stacktrace.txt](https://github.com/the-control-group/voyager/files/1271960/Stacktrace.txt)

in HasAttributes->getAttribute() $this object has no attributes

After adding mutator in voyager Post model, i can browse posts :) 
public function getTranslatableAttribute(){
    return $this->translatable;
}

but the translation does not work when editing the post and switching locales in UI

thanks

**Comment by vaggelis2018** [comment]
Same here on every translatable model. Menu and other. And on pages it throws not found error

**Comment by vshapovalov** [comment]
i have tried laravel 5.5.0, same problem

**Comment by vaggelis2018** [comment]
Maybe because it is still on development v.1.0 . We have to wait and see.

**Comment by Kleindberg** [comment]
I guess it's because Voayger not updating the translations table in database (is still on development?).

I have the same problem: laravel 5.5.0

**Comment by vaggelis2018** [comment]
Does anyone solved it?

**Comment by akazorg** [comment]
Hello guys, sorry for the delay, will take a look on that.

**Comment by vaggelis2018** [comment]
Thank you man
