### ISSUE TITLE
Double relationship to the same table issue

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1647]
- Laravel Version: 5.4
- Voyager Version: 11.14
- PHP Version: 5.6
- Database Driver & Version:

### Description:
when you have two fields with a relationship to the same table in browse view the slug show the first selection also in the second field. 

### Steps To Reproduce:
Es.
Table Groups (id, admin, moderator...)
admin -> hasOne(User::class, 'id');
moderator -> hasOne(User::class, 'id');

I select "Tom" for admin and "Bob" for moderator
In browse view I see "tom" in admin and in moderator field.
It works in edit view.

**Comment by reficul** [comment]
![schermata 2017-09-09 alle 08 44 09](https://user-images.githubusercontent.com/1073883/30237839-281b7c0e-953b-11e7-8699-92e063814f0b.png)
![schermata 2017-09-09 alle 08 43 27](https://user-images.githubusercontent.com/1073883/30237841-284aa0c4-953b-11e7-9edf-3e8950c1dbe3.png)
![schermata 2017-09-09 alle 08 43 16](https://user-images.githubusercontent.com/1073883/30237840-28462cb0-953b-11e7-824d-78c1e755a3c7.png)

Screenshots example

**Comment by fletch3555** [comment]
Fixed by #1875
