### ISSUE TITLE
NotFoundHttpException in RouteCollection.php line 161:

### ISSUE THREAD

**Issue by jaasaria** [thedevdojo/voyager#165]
after creating database and menu builder , it give me this error. please kindly suggest how to solve this issues?

**Comment by dreamtime** [comment]
This error appears to be logged 4 times for every admin page that is loaded. Laravel 5.3, PHP 5.6.4, testing on Homestead. Voyager was added to an existing project in my case

**Comment by marktopper** [comment]
This should have been solved in a newer version.
