### ISSUE TITLE
Will it support Laravel 5.5?

### ISSUE THREAD

**Issue by zzpwestlife** [thedevdojo/voyager#1651]
- Laravel Version: 5.5.1
- Voyager Version: 0.11.14
- PHP Version: 7.1.8
- Database Driver & Version:

### Description:
tcg/voyager v0.11.14 requires illuminate/support ~5.3.0|~5.4.0 -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].

**Comment by davodavodavo3** [comment]
Want to try out the latest version with Laravel 5.5? Be sure to use composer require tcg/voyager dev-master

**Comment by tnylea** [comment]
We don't have plans to make version 0.11 compatible with 5.5, but we will have upgrade guides to 1.0 and 1.0 will support 5.4 and 5.5 👍 

Working on some bugs and fixes as we speak to release 1.0 soon.

Thanks.
