### ISSUE TITLE
Media Upload Random Name

### ISSUE THREAD

**Issue by dfxs91** [thedevdojo/voyager#1655]
- Laravel Version: 5.4.38
- Voyager Version: 0.11

Hi,
I am developing an website that will need to upload images to the server, and the media, out-of-the-box, is awesome. But one requirement is to keep the names of the images the same, not the 20 chars random.

Can anyone help me?

Thanks in advance.

**Comment by adriangordon1231** [comment]
Interested to see an answer for this problem as well. What I usually do is rename the file before I trigger the download for the user.

**Comment by marco-solare** [comment]
Hey guys, very good point.
However I suggest to have the behaviour (if it will be changed / enhanced) configurable through voyager config as I suppose that there are a lot of people who want to have it exactly as it is right now.
One thing to think about:
Some web servers had problems to serve files with spaces in their file names in former times.
Maybe these times are over now but I still feels totally weird (to me) to let people upload files with spaces.
Remedy: replace by _ or - for example

**Comment by fletch3555** [comment]
Out of curiosity, why do you have that requirement? Would it be acceptable to have the names stored in the database instead? This would allow you to GET `/storage/images/2017/july/image.jpg` and have it return `/storage/images/2d08e3f6a01a826b4c0f.jpg` (or similar).

If this isn't acceptable for your needs, could you please explain why?

**Comment by marco-solare** [comment]
I assume that some people want to have "natural names" for their images because of SEO optimazations. Example:
 "this-cool-product-brand-whatever.jpg" might be indexed by search engines and found in searches whereas 2d08e3f6a01a826b4c0f.jpg might be harder to find

**Comment by dfxs91** [comment]
Hi all,
marco-solare, not exactly my goal but i need to keep the name of the images original.
To explain the requirement, i have products store in a database with an reference. And I need to show one image per product. The name of the image is the reference of a product, because all images are treated and they name the image with the reference. This way I know wich image corresponds to a product.

**Comment by marco-solare** [comment]
hmm, ok.
I guess that @fletch3555 's suggestion might help you then?

**Comment by dfxs91** [comment]
Yes @fletch3555 's suggestion works but i can't get the original name. I already try to overwrite the file VoyagerMediaController.php to get it but i coudn't.

**Comment by fletch3555** [comment]
My suggestion wasn't one that you can use currently (at least not without significant customization).  It was a suggestion of a way we could potentially rewrite Voyager's functionality.  I was simply wondering if doing it that way would meet your needs.

**Comment by Kleindberg** [comment]
Voyager doesn't rename uploaded files so I got some troubles if file name contains spaces or non-latic characts. Need to rename all uploadings automatically.

**Comment by lancepioch** [comment]
Labels: enhancement, discussion

**Comment by yakuter** [comment]
I need exactly the same thing that I don't want my uploaded file's name changed. I cloudn't find whic lines of code in vendor voyager files change the name of uploaded file. Can anybodu show me the lines?

**Comment by reeslo** [comment]
There is a way for override this ?

**Comment by juliencap** [comment]
Hello, maybe could be named by a slug on the picture name. On my case I have a lot of pictures about players and now I have to check thumbnails, it's take time but it's not a big deal of course, the media galerie is cool :)

**Comment by jeancarlosnovaes** [comment]
Edit the method upload in `/vendor/tcg/voyager/src/Http/Controllers/VoyagerMediaController.php`


Add the following code

`$originalName = $request->file->getClientOriginalName();`
`$nameWithoutSpace = preg_replace('/\s+/', '-', $originalName);`

before this line `$file = $request->file->store($request->upload_path, $this->filesystem);`

rename the method `store` to `storeAs` and add the variable `$nameWithoutSpace` like that
`$file = $request->file->storeAs($request->upload_path, $nameWithoutSpace, $this->filesystem);`

**Comment by BetaFold3** [comment]
@jeancarlosnovaes Big minds think alike.
I've been using the same config in my system.
I also made a configuration so it's up to the system to decide where the upload should pick a random name or keep the original name. A PR is available here: https://github.com/the-control-group/voyager/pull/3378

Feel free to upvote it if that's what you want.

**Comment by isDOSe** [comment]
Any idea to get renamed image file with the post (or whatever) slugged input field value (like title)... For example. "This is an amazing post" title. My image automatically uploaded like this this-is-an-amazing-post.jpg??? This is for SEO purposes.. Sorry for my english :(

**Comment by emptynick** [comment]
Closing as #3860 was merged (into 1.x, to be released in a future 1.2 release)

**Comment by juliencap** [comment]
thanks a lot :) the title update directly into the cards, is great too!
A little thing: Image just keep the name now but there is no slug on the name (if a user forget a space or something on the name for example). but I will do that on my side, it's enough like you did.
