### ISSUE TITLE
posting null value in case of  multiple select option for many to many relationship 

### ISSUE THREAD

**Issue by dipanjan24** [thedevdojo/voyager#1657]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 5.6.4
- Database Driver & Version: Mysql

 **Description:**
 When I create bread using voyager many to many relationship (multiple select) using pivot table the drop down options are coming but when trying to post it to add into table those selected value's id is showing null. 

**Steps To Reproduce:**
**table** : 1. books  (creating bread for this table)
                2. authors
                3. authorbook (book_id,author_id)
 **model** : 
     public function authors()
     {
         return $this->belongsToMany('App\Entities\Author', 'authorbook','book_id','author_id');
     }
      this is inside my book model.
**relationship in book create bread**:
  {
    "relationship": {
        "key": "authors.id",
        "label": "name",
        "page_slug": "admin/Author"
    }
} 

couldn't make
 {
    "relationship": {
        "key": "id",
        "label": "name",
        "page_slug": "admin/Author"
    }
} 
as its showing error that id field is ambiguous.
**values for two author selection after submit** 
                        "authors" => array:2 [▼
                          0 => null
                          1 => null

So now I am not getting  those multiple authors selective value inside controller . Please help.

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by emptynick** [comment]
Closing as this issue is for a much older Voyager version.
