### ISSUE TITLE
Login/Logout custom redirect

### ISSUE THREAD

**Issue by Codebreaker101** [thedevdojo/voyager#1658]
- Laravel Version: 5.4.24
- Voyager Version:  0.11.12
- PHP Version: 7.0.22
- Database Driver & Version: MySql 14.14

### Description:

After admin logs in I would like him to be redirected to the home page. Is overriding login and logout routes to a custom controller the only way of redirecting? I would usually do this with RedirectIfAuthenticated middleware.

**Comment by fletch3555** [comment]
The Voyager login page (`/admin/login`) is intended for logging into Voyager, not for your site's front-end.  You can use the Laravel Auth scaffolding for logging into your own site.  We may add the ability to change the login redirect in a future release, but it will not be added with the intention of using it as you've described.

**Comment by Codebreaker101** [comment]
Thank you for the response. I just wish to clarify a bit. I do have multi-auth set up ( 'regular' users and voyager admin). Posts, widgets and the rest are managed through the voyager, BUT basic editing functionality (like editing the post title) can also be managed in the front-end with ajax. Most of the time I'm editing grammatical mistakes and I have to go to voyager and either go to posts page and look for a post there or go back to home page and search for the post. To increase efficiency I would like to reduce the steps and redirection after login would do it.

**Comment by fletch3555** [comment]
I don't understand what multi-auth has to do with this.  In a default laravel install with voyager added, and after running `artisan make:auth`, you will have 2 login pages `/login` and `/admin/login`.  Both of these will accept users logging in.  The only difference is that the `/admin/login` one will redirect to the `/admin` if the user has the correct permissions, and `/` if the user does not.

**Comment by Codebreaker101** [comment]
Voyager was installed on an existing website. I had authentication already setup (all the tables were prefixed) and the site fully functional. When installing voyager new tables were created (users, roles, etc). So, for logging in i have two users tables, two guards, two controllers. Which is great for planed expandability for 'regular' users, meaning I don't have to touch voyager admin users and roles. And this works great. The front-end is managed mostly through voyager's BREAD. Since some basic editing functionality is available through the front-end I wish to redirect voyager admin of a certain role back to where he came from. But for starters I wish to redirect to another url and I was wondering is that possible without overriding voyager's `VoyagerAuthController`.

**Comment by fletch3555** [comment]
As I mentioned before, that is currently not supported by Voyager, so you would have to override/customize Voyager's code to make it work.
