### ISSUE TITLE
no views after fresh install

### ISSUE THREAD

**Issue by liftSpindle** [thedevdojo/voyager#1663]
- Laravel Version: 5.3
- Voyager Version: .11
- PHP Version: 7
- Database Driver & Version: mysqli 5.0.12

### Description: 

My welcome page is showing but I get a 404 when i access: 

[http://racktest.co/laravel_apps/blog/public/admin](http://racktest.co/laravel_apps/blog/public/admin)
and
[http://racktest.co/laravel_apps/blog/public/admin/login](http://racktest.co/laravel_apps/blog/public/admin/login)

My php info is at [http://racktest.co/phpinfo.php](http://racktest.co/phpinfo.php)

I am trying to set up a couple of projects in a folder in racktest.co. I am using AWS. Will laravel only work if i install it at the top of the domain? 

### Steps To Reproduce:

install laravel with composer
install voyager with composer
edit .env and config/app
install voyager with artisan

**Comment by liftSpindle** [comment]
i solved my problem. I had to enable mod_rewrite.

**Comment by fletch3555** [comment]
I STRONGLY advise against setting up your site that way... Instead, you should use separate vhosts and point them at your app's `public` directory.  If you need further explanation of why what you currently have is bad, please see here: http://racktest.co/laravel_apps/blog/.env

**Comment by liftSpindle** [comment]
yeah it didn't really "work". I wanted to show my boss some existing options for panels. I'm just fiddling with one app at a time right now. Thank you.
