### ISSUE TITLE
Undefined variable in bread browse.blade

### ISSUE THREAD

**Issue by tanysheng** [thedevdojo/voyager#1666]
- Laravel Version: 5.4.36
- Voyager Version: 0.11.14
- PHP Version: 7.0
- Database Driver & Version: MYSQL 5.7.9

### Description:
Undefined variable error in TCG/Voyager/resources/views/bread/browse.blade.php line 45. Is it better to do it like `@if(isset($item->{$row->field . '_page_slug'})` instead of current one `@if($item->{$row->field . '_page_slug'})`

**Comment by lancepioch** [comment]
Labels: question, possible bug

**Comment by fletch3555** [comment]
We're always open to pull requests as long as you can justify the reason for the change
