### ISSUE TITLE
Web address change from www.root/admin to www.root/folder/admin

### ISSUE THREAD

**Issue by naseem1amjad** [thedevdojo/voyager#1668]
- Laravel Version: 5.4.35
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version:

### Description:
I am deploying Voyager on a shared hosting, my question is that is there any way to change the url from www.mywebsite.com/admin to www.mywebsite.com/newfolder/admin ?

### Steps To Reproduce:
Can this be achieved using .htaccess , if yes, how ?

**Comment by fletch3555** [comment]
Why would you need to? It's recommended to configure a vhost to have your domain point at the public folder, which would leave the url as `domain.com/admin`

To answer your question, it depends on your needs.  If you're moving the entire laravel install to `newfolder`, then it should work fine, just make sure you update `APP_URL` in your .env file.  If you're looking to leave laravel at the root and only move voyager's routes, then you can just add a `Route::group()` around `Voyager::routes()`

**Comment by lancepioch** [comment]
Labels: question, invalid

Close (not related)
