### ISSUE TITLE
Setting model can not update

### ISSUE THREAD

**Issue by JesonCkon** [thedevdojo/voyager#1669]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.0
- Database Driver & Version: mysql5.6

### Description:

`/vendor/tcg/voyager/src/Http/Controllers/VoyagerSettingsController.php`
when i call the update function laravel $request post content 'admin_title' but `getContentBasedOnType` get $request input by the settings->key 'admin.title' so always return null....
### Steps To Reproduce:
`
if($content === null){
     $content = $request->input(str_replace('.','_',$setting->key));
}`

**Comment by erayusta** [comment]
Maybe this is a better solution

$content = $this->getContentBasedOnType($request, 'settings', (object) [
               'type'    => $setting->type, 
                **'field'   => str_replace('.','_',$setting->key),**
                 'details' => $setting->details,
                'group'   => $setting->group,
            ]);

**Comment by erayusta** [comment]
This is working code VoyagerSettingsController.php  (starting from line 86)

$content = $this->getContentBasedOnType($request, **'public/settings'**, (object) [
                'type'    => $setting->type,
                **'field'   => str_replace('.','_',$setting->key),**
                'details' => $setting->details,
                'group'   => $setting->group,
            ]);

**Comment by megaket4up** [comment]
Also sqlite, pgsql, mysql not work. I can not save anything.

php: 7.1
laravel/framework: 5.5.*
tcg/voyager: dev-master

**Comment by vshapovalov** [comment]
Hi all, 
php replace 'dot' with underscore ('admin.title' -> 'admin_title') in form field names. 

simple replacing may be incorrert with 2 different keys, for example:
user added colors.main and colors_main as setting keys :], when settings will be saved, both of them will have one value.

**Comment by lancepioch** [comment]
Labels: invalid

Close (PR merged + dev-master is not stable)
