### ISSUE TITLE
VoyagerServiceProvider.php (line 115)

### ISSUE THREAD

**Issue by misterblacker** [thedevdojo/voyager#1670]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

When I go to the address site.com/any-link/ , it produces the following error:

```
(1/1) FatalErrorExceptionCall to a member function getAction() on null
--
in VoyagerServiceProvider.php (line 115)
```

I understand that 404 pages do not exist for a voyager?

**Comment by fletch3555** [comment]
When submitting an issue, you need to include ALL of the requested information (specifically, you left out versions.  Please update that and we'll reopen the issue.
