### ISSUE TITLE
i18n not working on Posts

### ISSUE THREAD

**Issue by AndCymru** [thedevdojo/voyager#1676]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 7.*
- Database Driver & Version: MySQL 5.6.35

### Description:
Editing whatever content becomes impossible whenever multilingual function is enabled in voyager config.
One notice: MENUS are working perfect whether multilingual function is enabled or not.

I made a fresh laravel 5.4 install, and fresh voyager 0.11.14 install over it with dummy data specifically to test everything.
In /config/voyager.php I put 'multilingual' to true, and add second (also tried it with 3 and 4 languages with the same result) language.
Immediately editing content goes broken.
In admin section I try to edit any post with dummy data. All the content goes scrambled into one big paragraph with opening and closing html paragraph tags at the beginning and in the end.
Whatever I do, it does not allow formatting.
As soon as I put 'multilingual' to 'false' without doing anything else, everything comes back to normal.

Note: l13n works well, no problems with that.

### Steps To Reproduce:
Setup Voyager (populate dummy data for convenience), set 'multilingual' to true, add second (or any number of) language.
Go to admin, and try editing any post. All paragraphs will get crammed together, with one block of text between opening and closing paragraph tags.
Go to /config/voyager.php and turn 'multilingual' to false. Immediately everything will work correctly.

Once again: menus work perfect both in multilingual mode and single-lingually. As well as l13n - no problems with that.

**Comment by lancepioch** [comment]
Labels: locale, possible bug fix

**Comment by AndCymru** [comment]
a short notice that in voyager v1 the problem persists: all html gets wiped out with all content placed between opening and closing paragraph tags.
this puts down the drain all the efforts to make voyager multilingual

**Comment by akazorg** [comment]
Hi @AndCymru, thanks for the report. Multilingual was working, something must had changed for that error.
Will check this ASAP.

**Comment by AndCymru** [comment]
latest comment on this issue.

looks like it has been solved somewhere down the line.

i just did full composer update, and now i can see 2 things:
1. everything is saved to the database correctly, including all the tags, everythng.
2. tinymce won't show any html tags despite they are present in the database, so on the - for example - post editing page you see post body with all tags stripped out (i'm talking about default installation without any custom code).

might be a problem with tinymce or something.

in any case it is confusing for the users to install voyager and come over html tags being stripped out.

imho, this deserves resolving.

**Comment by akazorg** [comment]
I confirm the issue at `posts/edit-add.blade`, HTML is disappearing.

**Comment by akazorg** [comment]
I've sent a PR fixing this. Thanks for the report.
Closing issue now.

**Comment by AlaaMJaddou** [comment]
Guys i was facing this issue and i searched a lot finally i tryied to solve ib by turning around. 
the solution or lets say the problem here is in this file 

> posts/add-edit.blade.php

and if you remove it the bread will work perfectly with default template for posts add-edit.
i think this will help a little but i don't know why this issue appear.
