### ISSUE TITLE
Turorial video Custom Controller and Views

### ISSUE THREAD

**Issue by pedami** [thedevdojo/voyager#1677]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: last

### Suggestions:
Hi, it would be great to create a tutorial or video for the custom process of a model, for example table posts
How to perform the controller with all its methods, index, update, create, delete, etc ...
Custom browse.blade.php
Custom edit-add.blade.php with the possibility of including several columns as they have already developed in the bread that comes by default with Voyager.

Does anyone else think this would be interesting?

In addition, I think it is essential to finish using the module with unlimited productivity, to be able to include statistical graphics in the Dashboard, as well as being able to create a bread master-detail, for example for orders, invoices, etc.
I do not know if it's too much to ask, but it would be incredible.

Thank you.

**Comment by fletch3555** [comment]
I'm not entirely sure what the question is.  Customizing views from packages is covered in the laravel documentation (and ours for convenience).  Customizing controllers is as simple as extending the class and adding a single line to a service provider, which I believe is covered in our docs as well.

As for the dashboard, we can't possibly support every possible use-case, but we may add some built-in flexibility in a future release.  For now, if you can code it, you can do it, just override the view and add what you need.

**Comment by pedami** [comment]
Thanks, solvent.
