### ISSUE TITLE
Form with tabs

### ISSUE THREAD

**Issue by cerelli** [thedevdojo/voyager#1679]
- Laravel Version: 5.5.0
- Voyager Version: dev-master
- PHP Version: 7.1
- Database Driver & Version: mariadb

### Description:
Hi, i want to reproduce with crudbooster a form like this in image:
![crm](https://user-images.githubusercontent.com/6558535/30167083-90ebbaa2-93e5-11e7-9b92-c8f17e1fc59b.png)

In form, add tabs with details subform. In subform panel and button to modify or delete.

is it possible with voyager ?

**Comment by fletch3555** [comment]
That's not possible with Voyager.  You could add it yourself with significant customization.
