### ISSUE TITLE
Install fail Class 'App\User' not found

### ISSUE THREAD

**Issue by Hanoldery** [thedevdojo/voyager#1680]
- Laravel Version: 5.3.31
- Voyager Version: 0.11.14
- PHP Version: 5.6

### Description:
Got an error like this after adding the TCG Voyager in the providers (Nothing AT ALL is working after that, laravel is blocked on this).
![capture d ecran 2017-09-07 a 19 26 28](https://user-images.githubusercontent.com/15785124/30175641-90e43646-93ff-11e7-8b88-96fd8408fe8d.png)

PHP Fatal error:  Class 'App\User' not found in /home/vagrant/Code/vendor/tcg/voyager/src/VoyagerServiceProvider.php on line 64

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'App\User' not found

### Steps To Reproduce:
User your own version of User unnder App\Models\User.

Follow the install steps.

**Comment by Hanoldery** [comment]
Issue can be closed, just had to change it in the config file, should precise it on install notes.

**Comment by bobur1** [comment]
@Hanoldery, I have a question. I do not fully understand what should I do, I have changed the default namespace of the project from 'App' to -> 'Corp' (do not ask why... I cannot understand too) ) so now my 'App/Use' in the 'Corp/User'. Here is config/auth.php
```

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => Corp\User::class,
        ],
```
I still have an error 
P/S it starts after the installation step: '$ php artisan voyager:install'

**Comment by fletch3555** [comment]
@bobur1, please create your own issue for things like this so we can better track it.

You should just have to update the model namespace in `config/voyager.php`
