### ISSUE TITLE
'Class App\Role not found' on registration

### ISSUE THREAD

**Issue by troix1** [thedevdojo/voyager#1681]
- Laravel Version: 5.3.30
- Voyager Version: 0.11.12
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
When a new user tries to register it does add him to the database but it gives error:
```
FatalErrorException in compiled.php line 10689:
Class 'App\Role' not found
```

### Steps To Reproduce:
I have added custom fields to users table (http://prntscr.com/gik59h)
and this is my RegisterController when creating a new user:

`        return User::create([
            'name' => $data['name'],
            'surname' => $data['surname'],
            'address' => $data['address'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);`

The error doesn't give me much to go on, I don't know where to look at, I don't know exactly if this is voyager issue but please help me out.

**Comment by fletch3555** [comment]
Your `User` model needs to extend `TCG\Voyager\Models\User`
