### ISSUE TITLE
Crop image feature in media

### ISSUE THREAD

**Issue by shingo0620** [thedevdojo/voyager#1685]
I just made a cropping feature for media, not sure is it a feature that worth create PR?

![image](https://user-images.githubusercontent.com/359648/30207157-21f5325e-94c1-11e7-9e03-20fe7d998e6a.png)

![image](https://user-images.githubusercontent.com/359648/30207185-3b1dcd18-94c1-11e7-8c55-12cd39a805b9.png)

**Comment by fletch3555** [comment]
Does it overwrite the existing image, or create a copy at the cropped size?

Very cool though! What version of Laravel and Voyager did you build this for? If it was built off of our master branch (the soon-to-be 1.0 release), we'd love to see a PR for it!

**Comment by AdrianKuriata** [comment]
What you used? Cropper?

**Comment by shingo0620** [comment]
It would overwrite the existing, but I think I can let user choose save a new image or overwrite it

I used Cropper and Image
https://fengyuanchen.github.io/cropperjs/
https://packagist.org/packages/intervention/image

**Comment by marco-solare** [comment]
pretty cool! If it is selectable I'm pretty sure it will be taken ;)

**Comment by fletch3555** [comment]
If you add the ability for users to save as a new image, that would be awesome!  Please make sure to test against dev-master and make sure it all works, then we'll be more than happy to review a pull request for this!

**Comment by AdrianKuriata** [comment]
Did you saving image for possibility to image has transparent background? Maybe add something like saving as with changing file extension? I mean i uploaded png file with transparent background, but after change size picture and saving as new file i wanna save it jpeg file.

**Comment by shingo0620** [comment]
Just finish the first drop. It's built with laravel 5.5 and fork from the master branch of voyager

Github: https://github.com/shingo0620/voyager
Demo: http://test-voyager.shingo.pw/admin/media
>**email:** `admin@admin.com`   
>**password:** `password`

Known issue:
Transparent  https://github.com/Intervention/image/issues/457

About changing file extension, I think it should implement with the rename function, not within the cropping process.

Open to suggestions.

**Comment by lancepioch** [comment]
Labels: feature, discussion

**Comment by akazorg** [comment]
Feature implemented. Closing.

**Comment by stephanedemotte** [comment]
Uncaught ReferenceError: Cropper is not defined

**Comment by aozen** [comment]
Is cropper implemented?
