### ISSUE TITLE
No Vendor is publish for view on the current latest release of voyager

### ISSUE THREAD

**Issue by codeitlikemiley** [thedevdojo/voyager#1687]
I dont know if the author, has already added a vendor publish for view assets
coz as ive use it on laravel 5.5, the only thing that was publish was
```
Copied Directory [\vendor\tcg\voyager\publishable\assets] To [\public\vendor\tcg\voyager\assets]
Copied Directory [\vendor\tcg\voyager\publishable\database\migrations] To [\database\migrations]
Copied Directory [\vendor\tcg\voyager\publishable\database\seeds] To [\database\seeds]
Copied Directory [\vendor\tcg\voyager\publishable\demo_content] To [\storage\app\public]
Copied Directory [\vendor\tcg\voyager\publishable\lang] To [\resources\lang]
```
hope you can add this...  thanks

**Comment by codeitlikemiley** [comment]
what i did was just copy and paste all the views in vendor to the resources/views/vendor/voyager

**Comment by AndCymru** [comment]
it's not an issue with the voyager.
you would do that only if you want to override some default voyager dashboard views.
otherwise, you don't have to copy anything, just use defaults as is.

**Comment by fletch3555** [comment]
We haven't published views in quite a few minor releases.  You shouldn't publish all views, as you won't be able to see changes when you update.  You should only override views (by copying them to your app's `resources/views/vendor/` folder) if you NEED to modify that one particular view for your own purposes.
