### ISSUE TITLE
Bug in rename DB table

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1688]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 5.6
- Database Driver & Version:

### Description:
I add a table with a wrong name, with first letter in uppercase (ex: Mytable).
I try to rename to "mytable" but I got "Table already exist", no way to change it from voyager.
I used phpmyadmin to do the job.

**Comment by marcelosantos89** [comment]
I have that same problem but in MySQL Workbench the error is the same .. you can rename it to Mytable2 and then mytable

**Comment by lancepioch** [comment]
Labels: invalid

**Comment by fletch3555** [comment]
Not a voyager issue.  The "issue" is with the mysql driver used
