### ISSUE TITLE
Relational DropDown Button with 2 atributes in the field label 

### ISSUE THREAD

**Issue by daniqh** [thedevdojo/voyager#1691]
- Laravel Version: 5.4
- Voyager Version:0.11.14

### Description:
Hi there,
I created a drop down button with a relationship between students and incriptions.

I want to show in this button the name and surname from each student. The problem it is when I write the JSON, the validation throw a code format exception. How I can set the label with these attributes name and surname? 

My JSON:
```

{
    "relationship": {
        "key": "id",
        "label": "name"+" first_surname"
    }
}
```

https://imgur.com/a/PbdW1
Regards

**Comment by fletch3555** [comment]
I would make that a dynamic field (an accessor method that combines the values for you) instead.  I don't plan to add this type of functionality to the JSON config (not to mention, the syntax you use with the `+` isn't valid JSON)

**Comment by PSDeora** [comment]
its very easy 
use Custom relationship attributes
https://voyager-docs.devdojo.com/customization/custom-realtionship-attributes

in bread 
"relationship": {
        "key": "id",
        "label": "TitleWithLocation"
    }
in model
    public function getTitleWithLocationAttribute()
    {
        return "{$this->project_title} ( {$this->location} )";
    }
