### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#1692]
- Laravel Version: 5.5.3
- Voyager Version: 0.11.14
- PHP Version: 7.0.23

There is a problem when I tried to install voyager. Some issue with creating SQL databases I think.
http://i.imgur.com/L4DcEF5.png

And, here are some difficulties, but if I understand well, it is still well done.
http://i.imgur.com/PjA9IDk.png

**Comment by marcelosantos89** [comment]
You can't use Laravel 5.5.3 with Voyager 0.11.4. Install dev-master with Laravel 5.5.*

**Comment by fletch3555** [comment]
@orien2k, if you check the images, they're using dev-master.  @CRooY3, please make sure you use the appropriate version in your issue description.

The issue shows that you don't have git installed in your system.  Doesn't seem to be affecting the install, but if you install that you should be all set.

**Comment by ghost** [comment]
I have installed git, there is no problem.

I have problem with the last comand.
`php artisan voyager:install`

some issue with MySQL

>   [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `translations` add unique `translations_table_name_column_name_foreign_key_locale_unique`(`table_na
  me`, `column_name`, `foreign_key`, `locale`))

>   [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

>   [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

I made this: https://laravel-news.com/laravel-5-4-key-too-long-error, but issue is still here.

my MySQL version je 5.7.19

**Comment by marcelosantos89** [comment]
@fletch3555 sorry i haven't checked the images since the description was wrong at the start 👍

**Comment by fletch3555** [comment]
@CRooY3, that issue has been covered in issues here many many times.  Please search and see if any of those help.  I would rather not reiterate them here.
