### ISSUE TITLE
5.5 Installation failure 

### ISSUE THREAD

**Issue by fengerwoo** [thedevdojo/voyager#1701]
- Laravel Version: 5.5.3
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by VictorAvelar** [comment]
Are you using this????

```bash
$ composer require tcg/voyager dev-master
```

**Comment by fletch3555** [comment]
Voyager's current release does not support 5.5, but the upcoming 1.0 release will.  For now, you can do what was already suggested, use `dev-master` for the version
