### ISSUE TITLE
Generate a Custom Controller after adding BREAD

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#1704]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:
I love the idea of BREAD for most scenarios but there are times where you need a custom controller. I know in Voyager you can create BREAD and then point to a custom Controller but it would be cool if you could create your entire BREAD with all your fields and then have it generate the Controller in Http\Controllers so that you could add your custom scripts on top. It would have all the add, edit, update, destroy, ect functions. 

Love Voyager, saves a lot of time for your basic backend

**Comment by Jasperrr91** [comment]
This would be a great feature. Could also help as a temporary work around for: https://github.com/the-control-group/voyager/issues/1705

**Comment by lancepioch** [comment]
Labels: feature

**Comment by fletch3555** [comment]
I'm going to close this since it's been so long.  There doesn't appear to be much interest in having this OOTB, and it can already be done manually
