### ISSUE TITLE
Conditional BREAD

### ISSUE THREAD

**Issue by Jasperrr91** [thedevdojo/voyager#1705]
Laravel Version: 5.4
Voyager Version: 0.11.14
PHP Version: 7.0
Database Driver & Version: MySQL 5.6

### Description:
I haven't been able to find it so far, but is it possible to create conditional BREAD views? For example, I have groups that users can subscribe to. And each group has one or more moderators.

Now, I want a Bread view were moderators can see the users in groups that they moderator. So they can Approve/Disapprove registration requests. Doesn't seem to be possible yet but this is a crucial function for most back-end systems.

**Comment by lancepioch** [comment]
Labels: question, enhancement

**Comment by marktopper** [comment]
You can customize the BREAD views to matches those needs.
Doc: https://voyager.readme.io/docs/overriding-views
