### ISSUE TITLE
Timestamp not saving

### ISSUE THREAD

**Issue by doatta** [thedevdojo/voyager#1706]
- Laravel Version: #.#.#
- Voyager Version: 0.11.#
- PHP Version:
- Database Driver & Version:

### Description:
Hi!

I've integrated Fullcalendar(fullcalendar.io) with Laravel Voyager , but faced this problem.
To save date and time for calendar, I've chosen timestamp format and "timestamp" in bread . But when I create task, every first time timestamp doesn't save date and time. It saves null or current timestamp (If I choose CURRENT_TIMESTAMP in default value of row in database). When I edit, it saves new date and time without problem. So as I understand, the main problem with edit-add.blade.php or with Controller. 
In ./vendor/tcg/voyager/resources/views/tools/database/edit-add-bread.blade.php I've found some differences in adding/editing timestamp, but didn't find any problem with them. 
The only row which looks like causing problem in Controller

` case 'timestamp':
                if ($request->isMethod('PUT')) {
                    if (empty($request->input($row->field))) {
                     $content = null;
} else {
                        $content = gmdate('Y-m-d H:i:s', strtotime($request->input($row->field)));
                    }
                }
` 
I tried to comment 
`if (empty($request->input($row->field))) {
                     $content = null;
} else {`
or even change
`           $content = null;`
to 
`                        $content = gmdate('Y-m-d H:i:s', strtotime($request->input($row->field)));
`

but nothing changed... 

Can you please help me?

**Comment by doatta** [comment]
In post request  I see that date and time have been sent to server

**Comment by doatta** [comment]
User emilvaliyev helped! 

in the voyager\src\Http\Controllers\Controller.php add after case 'timestamp':

if ($request->isMethod('POST')) { $content = gmdate('Y-m-d H:i:s', strtotime($request->input($row->field))); }

**Comment by lancepioch** [comment]
Labels: possible bug

**Comment by marktopper** [comment]
Fixed in #1773
