### ISSUE TITLE
Override dropdown "optgroup" label

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#1707]
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7
- Database Driver & Version: MySQL 5.6

### Description:
When adding a one to one relationship for dropdowns can you override the optgroup label. Currently it says "Relationship" in my browser view.

`<optgroup label="Relationship">
`

**Comment by lancepioch** [comment]
Labels: question, enhancement

**Comment by marktopper** [comment]
We will add this to the language files.

Reference: https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/select_dropdown.blade.php#L52

**Comment by emptynick** [comment]
This was fixed in #2794
