### ISSUE TITLE
i want to add a watermark to an image uploaded by bread controller

### ISSUE THREAD

**Issue by ahmedemad2051** [thedevdojo/voyager#1708]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 7+
- Database Driver & Version: 5+

### Description:
I created a bread to upload an image but I want to add a watermark to that image before upload it
it should resolve by intervention but i don't know how

**Comment by fletch3555** [comment]
All fields are required.  Additionally, "i18n" is not a valid voyager version.  Please fill out the rest of the requested information and we'll reopen the issue.

**Comment by ahmedemad2051** [comment]
@fletch3555 
i filled all details

**Comment by lancepioch** [comment]
Labels: question, feature

**Comment by muradzulfugarov** [comment]
Any progress?

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/1241 (same topic)
