### ISSUE TITLE
Can't access admin panel

### ISSUE THREAD

**Issue by Kazuto** [thedevdojo/voyager#1709]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
I can't access the /admin route. It always tells me 404 not found.

I've installed it as the DevDojo has done it.

**Comment by fletch3555** [comment]
404 implies that the route doesn't exist.  Please check `php artisan route:list` for a list of Voyager routes (all starting with `/admin/`).  If they're there, the it's likely that your laravel install isn't correct.  That's not something we'll be able to troubleshoot on here, but you're welcome to join our slack group and ask there.

**Comment by Kazuto** [comment]
All routes are perfectly fine.

![image](https://user-images.githubusercontent.com/25435034/30398364-62b4b5d6-98d0-11e7-98a8-6d0c20770f51.png)

http://voyager.devel.kazuto.de/admin/

**Comment by fletch3555** [comment]
Your web root (nginx base directory) is not set up correctly.

What is the path to your laravel install directory?  What is the document root path (usually `/var/www`, but could easily be something else)?

**Comment by fletch3555** [comment]
Nevermind, I found it (http://voyager.devel.kazuto.de/public/).  You have laravel set up incorrectly.  You've installed it  so the public folder is `/var/www/public` (or whatever the document root is set to).   You should move laravel outside of the document root (so [things like this](http://voyager.devel.kazuto.de/.env) can't happen), then configure nginx to point the document root at your `public` folder.

This is not an issue with Voyager, so I'm going to close this issue now.  If you would like further help setting up your environment, you may get it on one of the Laravel-focused slack groups (LaraChat or ours), or you can post the question in a forum (like laracasts) for further assistance.
