### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by maktibab** [thedevdojo/voyager#1711]
- Laravel Version: 5.5.4
- Voyager Version: dev-master
- PHP Version: 7.0.10
- Database Driver & Version: MySQL

### Description:
on a fresh install when trying to upload a file there's an exception:
ErrorException in VoyagerMediaController.php line 186:
Undefined variable: path

### Steps To Reproduce:
try to upload file...

**Comment by maktibab** [comment]
I have try:
dd($request->upload_path , $this->filesystem)

Result:
null
"public"

=> The null value for upload_path is normal??

**Comment by lancepioch** [comment]
Labels: invalid

Close (dev-master is not stable)

**Comment by marktopper** [comment]
Please update to latest version, if this still happens please provide steps on how to reproduce.

**Comment by maktibab** [comment]
After updates, it still happens again.

Step to reproduce:
- go to media menu
- click on download button
- choose a file
- wait the ajax finish

Response of the ajax call:
`{"success":false,"message":"The file \"\" does not exist","path":""}`

**Comment by maktibab** [comment]
I have update my files again... same issue as #1822

**Comment by emptynick** [comment]
Closing as this issue is for a much older Voyager version.
