### ISSUE TITLE
Options migrations disabled

### ISSUE THREAD

**Issue by oscarnascimento** [thedevdojo/voyager#1712]
- Laravel Version: 5.3
- Voyager Version: v0.11.14
- PHP Version:
- Database Driver & Version:

### Description:
Hi, the options for generate MIGRATIONS are disabled for me. How can I enable it?

**Comment by fletch3555** [comment]
That file was intentionally disabled (never actually worked), and has been removed in the upcoming release.  We will revisit the feature when we can come up with a good way to implement it.

**Comment by oscarnascimento** [comment]
Thanks!

And how approach can you suggest to configure the project to be saved and/or replicated to other server? Migrations?

**Comment by fletch3555** [comment]
Yes, you can either manually create migrations, or you can do a database backup and restore.  There are a number of options

**Comment by hojgr** [comment]
I would like to start a discussion to reopen this. Currently it is very difficult to develop a project with more people and more environments as you either have to write tedious seeders for BREADs or just send sql dumps around. @fletch3555

**Comment by fletch3555** [comment]
@hojgr no need for a discussion on this.  I never said this was functionality we wouldn't add.  I just said there are a couple options you could do currently.  We will add the feature when we have the time to do so, or when someone from the community opens a pull request for it.

**Comment by hojgr** [comment]
Yes, I understand that. Could we perhaps create a ticket to talk about it?
I will try to come up with some way to do that.

Wanted to reopen the discussion with the message I sent since the 1.0 has
been released and this feature is missing the most for me.
