### ISSUE TITLE
Issues deleting the default tables (pages and posts)

### ISSUE THREAD

**Issue by raf202** [thedevdojo/voyager#1715]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version: 7
- Database Driver & Version:

### Description:
After deleting the BREAD and the table for pages, I go back to the main dashboard and I get this error:

Route [voyager.pages.index] not defined. (View: D:\Projects\v2\vendor\tcg\voyager\resources\views\dimmers.blade.php) (View: D:\Projects\v2\vendor\tcg\voyager\resources\views\dimmers.blade.php)

### Steps To Reproduce:
Install Voyager
Delete Bread from the Pages Table
Delete the Pages Table
Go to main dashboard

**Comment by davodavodavo3** [comment]
Remove 
`'TCG\\Voyager\\Widgets\\PageDimmer',`
from config voyager widgets.
Maybe it will help.

**Comment by fletch3555** [comment]
@davodavodavo3 is correct.  There may be other code you'll need to remove, but what he suggested should fix your immediate concern

**Comment by rajanish93** [comment]
@davodavodavo3 is true answer
