### ISSUE TITLE
Error in Voyager 1.0

### ISSUE THREAD

**Issue by vitormicillo** [thedevdojo/voyager#1720]
- Laravel Version: 5.5.4
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: mysql server 5.7

### Description:
Error with users when enabling multilanguage

### My changed model:
`
namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use \TCG\Voyager\Traits\Translatable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;
    use Translatable;

    protected $tables = ['translations'];

    protected $fillable = [
        'name', 'email', 'password',
    ];

     protected $hidden = [
        'password', 'remember_token',
    ];
}
`
![image](https://user-images.githubusercontent.com/1921806/30483545-8fd81212-9a27-11e7-9ebb-571bc228dd7e.png)

**Comment by vaggelis2018** [comment]
Did u added more columns to user table or role table?

**Comment by vitormicillo** [comment]
problem solved with this command
composer require tcg/voyager:dev-fix-1719
Thanks @marktopper
