### ISSUE TITLE
Error in User View on SAVE

### ISSUE THREAD

**Issue by vitormicillo** [thedevdojo/voyager#1722]
- Laravel Version: 5.5.4
- Voyager Version: 1.0
- PHP Version: 7.0

### Description:
if you edit the profile of the administrator and do not want to change the password, when saving it asks for the required password field.

@marktopper

**Comment by davodavodavo3** [comment]
Here is solution for now.
Make user id to show only in edit page with disabled atribute maybe.
Second add validation to password field
```
{
    "validation": {
        "rule": "required_without:id"
    }
}
```
I.e when you create user there is not an id created yet and password field will be required.
When you update user the id will be there and password field will not be required.
I am Juggler ))))))
Hope I help.

**Comment by lancepioch** [comment]
Labels: possible bug

Close (workaround provided)

**Comment by marktopper** [comment]
Closed since this is not an issue on a clean install and seems to have been resolved
