### ISSUE TITLE
Roles - Different types of Admin

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/voyager#1723]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
This might not be an issue but I just want you to enlighten me. I created a new role "Admin Assistant".... I want this role to do BREAD on the Users table except to the "Admin" role... How to do this? Is this possible? Btw, I'm waiting for the release of v 1 this Sept 18. Thank you

**Comment by rexdarel** [comment]
I realize that it is completely possible to do this but I need steps if there are any. I don't want to mess my project.

**Comment by davodavodavo3** [comment]
I thin you need to create your own controller that extends voyager and do check for that Role(Admin Assistant) and prevent actions to Admin role

**Comment by fletch3555** [comment]
Depends what you want the role to be able to do.  Odds are you can simply override the view and add logic there.  Even better would be to make use of the new auth system in 1.0 (with Policies)

**Comment by lancepioch** [comment]
Labels: question, enhancement

**Comment by marktopper** [comment]
This can be done using Policies in v1.0 as @fletch3555 said.
I created a short guide on how to use the Policies in Voyager.
https://webman.io/blog/post/using-policies-in-laravel-voyager

**Comment by rexdarel** [comment]
Wow thank you!

**Comment by prashantUpstur** [comment]
> This can be done using Policies in v1.0 as @fletch3555 said.
> I created a short guide on how to use the Policies in Voyager.
> https://webman.io/blog/post/using-policies-in-laravel-voyager

Can you explain me this please I am begineer using laravel and voyager

**Comment by ghost** [comment]
Hi #rexdarel I want to implement the same you asked for, can you please help me what steps you followed?

**Comment by fletch3555** [comment]
@prashantUpstur, please don't comment on closed issues, especially ones that are 18 months old and for a much older version
