### ISSUE TITLE
how to edit dimmer?

### ISSUE THREAD

**Issue by akuma605** [thedevdojo/voyager#1725]
- Laravel Version: latest
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

### Description:
Can we change dimmer on the dashboard? I have a table "Games" and I want to show it in the dashboard like the 'Posts' and 'Users' tables.

**Comment by berkayoztunc** [comment]
Yes you can , there is `DimmerClass` in voyager you can make your own dimmer class like this
[https://github.com/the-control-group/voyager/blob/master/src/Widgets/PageDimmer.php](url)
after edit `config/voyager.php` widgets section
```
'widgets' =>
 [
   'TCG\\Voyager\\Widgets\\UserDimmer',
   'TCG\\Voyager\\Widgets\\PostDimmer',
    App\Widgets\MyCustomDimmer::class,
],
```

**Comment by akuma605** [comment]
thank you for the reply but I can't access your link, error 404.

**Comment by akuma605** [comment]
thank you for reply, I made the changement and I got this error:

Class "TCG\Voyager\Widgets\GameDimmer" must extend "Arrilot\Widgets\AbstractWidget" 

but my GameDimmer already extends AbstractWidget

**Comment by akuma605** [comment]
found solution there:
http://karac.ch/blog/voyager-le-panneau-d-administration-laravel_partie3_pour-aller-plus-loin#widgets

**Comment by fletch3555** [comment]
Solution found. Closing

**Comment by rajanish93** [comment]
berkayoztunc thank it's helpful answer
