### ISSUE TITLE
image required field

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#1727]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0
- Database Driver & Version:

### Description:
there is a problem with not  nullable columns of type image 
when we set it with options to be required and don't give it new value on edit it gives error and this hasn't to be because we gave the picture before

**Comment by davodavodavo3** [comment]
Guys I have solution for #1278 and this issue.
## 1 First add this row in image formfield
`<input type="hidden" name="image_exists" value="{{ Voyager::image($dataTypeContent->{$row->field}) ? 1 : 0 }}">`

## 2 Validate with this on image input
```
{
    "validation": {
        "rule": "required_if:image_exists,0"
    }
}
```
## Now if you are creating new post with image or user with avatar and not upload image you will get validation error, on update in hidden input will be value( 1 ) and you will not get validation errors.
## What do you think?

**Comment by faghihi** [comment]
@davodavodavo3 I think its ok but I hope i will be fixed for the new version coming soon

**Comment by lancepioch** [comment]
Labels: invalid

Close (solution provided)

**Comment by SoundousBahri** [comment]
> 1 First add this row in image formfield

I don't understand where am I supposed to add it

**Comment by MrCrayon** [comment]
This issue is almost three years old for Voyager version 0.11.

If you have a question please ask in Voyager slack chat. 
https://github.com/the-control-group/voyager/blob/1.3/README.md
