### ISSUE TITLE
No route & Admin redirect to home page after login

### ISSUE THREAD

**Issue by GlobSolutions** [thedevdojo/voyager#1729]
- Laravel Version: 5.4.x
- Voyager Version:0.11
- PHP Version:5.6.x
- Database Driver & Version:

### Description:
first i got error in login page it was clear that routing issue, in my web.php no rout, i added the :+1: 

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

and it work, then after login it redirect to home page, cant see admin panel, i read alll similar issues here but didnt find solution , please don't mention any as i read most of similar issues and nothing works

**Comment by davodavodavo3** [comment]
This is Voyager Admin middleware
```
if (!Auth::guest()) {
   $user = Voyager::model('User')->find(Auth::id());

   return $user->hasPermission('browse_admin') ? $next($request) : redirect('/');
}
```
If the user you are using for log in to admin side has not permissions to browse it will be redirect you to home page. Please check do you have permissions and write here again))))

**Comment by GlobSolutions** [comment]
thank you @davodavodavo3 ,
yes it is a permission issue, after creating admin i got message that admin have full access, but there were no permissions,  what i did next is reinstall ( artisan voyager:install ) ... and everything works fine...

**Comment by davodavodavo3** [comment]
If all work please close the question.

**Comment by GlobSolutions** [comment]
thanks

**Comment by mgevorg** [comment]
> This is Voyager Admin middleware
> 
> ```
> if (!Auth::guest()) {
>    $user = Voyager::model('User')->find(Auth::id());
> 
>    return $user->hasPermission('browse_admin') ? $next($request) : redirect('/');
> }
> ```
> 
> If the user you are using for log in to admin side has not permissions to browse it will be redirect you to home page. Please check do you have permissions and write here again))))

Could you help me to give access to voyager admin panel user with another role('moderator' for example)?
