### ISSUE TITLE
Fix Cancele Delete Settings Field

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#1731]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.14
- PHP Version: 5.6.4
- Database Driver & Version:

### Description:
```
<form action="http://laravel/admin/settings/???" <- id not updating id="delete_form" method="POST">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="Rj0CIfoJOVPHmiV9n8eZ5CUj3jiBf4tD8b7GBgkY">
                        <input type="submit" class="btn btn-danger pull-right delete-confirm" value="Yes, Delete This Setting">
                    </form>
```
### Steps To Reproduce:
1.Cancele Delete Setting Item
2.Select Next setting field and delete
3. Id  of the deleted field is not updated

**Comment by davodavodavo3** [comment]
Agree there is issue

**Comment by davodavodavo3** [comment]
Also when modal is open click on trash icon in modal header and booooom. There is another bug

**Comment by lancepioch** [comment]
Labels: possible bug
