### ISSUE TITLE
Add padding to form-group

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1735]
### Description:
Guys add padding to form-group to prevent non-equality width when adding width to rows
## Now
![now](https://user-images.githubusercontent.com/10462563/30521947-2762f7aa-9bd1-11e7-8b0b-a8dfca159bff.jpg)

### With padding
![with-padding](https://user-images.githubusercontent.com/10462563/30521952-3d08d20a-9bd1-11e7-8833-1ae9dcfa4de6.jpg)

Also increase Save Edit button padding to 10px 25px.

**Comment by davodavodavo3** [comment]
And change position of << Leave empty to keep the same >> descrition for password field at the same line or make it like other descriptions(on mouse hover).
Because it broke field positions like this
![fields](https://user-images.githubusercontent.com/10462563/30569835-d393f24e-9ce5-11e7-8f25-7e861d1d9f47.jpg)

**Comment by lancepioch** [comment]
Labels: design

**Comment by tnylea** [comment]
Yep, I like it. @davodavodavo3 you know how to build the assets, right?

**Comment by davodavodavo3** [comment]
yes

**Comment by davodavodavo3** [comment]
Tony you only need to add 
padding: 0 10px; to form-group classes and put bread save buttons in to div class form-group 
And Tony can we move decription tooltip at the right of the inuts labels ?

![field](https://user-images.githubusercontent.com/10462563/30769883-c87cacd2-a02a-11e7-8510-3891f59c1fe5.jpg)

this gives us more space and less scrolling

**Comment by davodavodavo3** [comment]
in my opinion this is not the best way, it is better to add div class row but that is inpossible

**Comment by fletch3555** [comment]
Closing due to age.
