### ISSUE TITLE
Menu sort order not working in custom blade

### ISSUE THREAD

**Issue by bjornfant** [thedevdojo/voyager#1737]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0.8
- Database Driver & Version:

### Description:
I created a menu in Voyager admin and added three items. I sorted them in another order. 

When I create a blade to build my own custom markup, the sort order if the items is wrong. I can't see a logical pattern to how it is sorted. 

The blade only contains the default code from: https://voyager.readme.io/docs/menus
```
<ul>
    @foreach($items as $menu_item)
        <li><a href="{{ $menu_item->url }}">{{ $menu_item->title }}</a></li>
    @endforeach
</ul>
```

Looking at the content of $items `<?=$items?>`
 the "order" key is correctly set, but the list is not sorted by it.

### Steps To Reproduce:

see above

**Comment by davodavodavo3** [comment]
Can you test this solution

```
<ul>
    @foreach($items->sortBy('order') as $menu_item)
        <li><a href="{{ $menu_item->url }}">{{ $menu_item->title }}</a></li>
    @endforeach
</ul>
```

**Comment by davodavodavo3** [comment]
**# `Don't worry if it doesn't work right. If everything did, you'd be out of a job.`**
_Mosher's Law of Software Engineering_

**Comment by bjornfant** [comment]
Thanks! Don't have the time now but will later today!

**Comment by bjornfant** [comment]
It's working! Thanks. how do we get the documentation updated on the voyager website?

**Comment by fletch3555** [comment]
I'd prefer to fix this in code rather than document a workaround (which turns out it was the actual way of doing it..).  I've opened #1741 to fix this.  @bjornfant, can you run `composer require tcg/voyager dev-bugfix/fix-1737` and test again?
