### ISSUE TITLE
How to add custom thumbnail setting?

### ISSUE THREAD

**Issue by vanloc0301** [thedevdojo/voyager#1739]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.1.8
- Database Driver & Version: MySQL

### Description:

I create a sidebar have list article, each article have 1 image is thumbnail with size: 64px * 64px (edited)

But I upload `Post Image`  in Voyager admin have size about 900px*400px

I found in `/storage/app/public/posts/Angust2017` have four type image: `source`, `-cropped`, `-medium`, `-small`.

I want to get `-custom` image to show list article with thumbnails on my frontend page.

I found:

                    'thumbnails' => [
                        [
                            'name'  => 'medium',
                            'scale' => '50%',
                        ],
                        [
                            'name'  => 'small',
                            'scale' => '25%',
                        ],
                        [
                            'name' => 'cropped',
                            'crop' => [
                                'width'  => '300',
                                'height' => '250',
                            ],
                        ],
                    ],

How to add custom setting for `thumbnails`?

Like:
```
[
     'name' => 'crop64',
     'crop'   => [
           'width' => '64',
           'height' => '64',
     ],
]
```

**Comment by lancepioch** [comment]
Labels: question, enhancement

**Comment by emptynick** [comment]
This is possible with Voyager 1.0
See https://voyager.readme.io/docs/additional-field-options#section-image
