### ISSUE TITLE
Please Help me in the installation

### ISSUE THREAD

**Issue by Nagendra1421** [thedevdojo/voyager#174]
I tried to install this package more than twice but every time i got same issue. I installed this in 
**"php": ">=5.6.4",
"laravel/framework": "5.3.*",**
I am installing this package in a fresh project. I followed same steps as they are mentioned. Database table successfully seeded into the database. I followed these steps:
1). First created a fresh project:- **composer create-project --prefer-dist laravel/laravel blog**
2). Then:- **composer require tcg/voyager**
3). then i configured my .env file for database connection,
4). Then added these points in app/config.php file under Laravel framework service provider : **TCG\Voyager\VoyagerServiceProvider::class,
Intervention\Image\ImageServiceProvider::class,**
5). Then at last: php artisan voyager:install

Please Help me in Installing this pacakge.

![voyager2](https://cloud.githubusercontent.com/assets/10511483/20306493/93a35ea8-ab60-11e6-845b-4672948d05e9.png)
![voyager3](https://cloud.githubusercontent.com/assets/10511483/20306494/93a49a0c-ab60-11e6-9e46-ff8a2c79f64c.png)
![voyager4](https://cloud.githubusercontent.com/assets/10511483/20306495/93a65c52-ab60-11e6-8310-d76810ba2f38.png)
![voyager](https://cloud.githubusercontent.com/assets/10511483/20306563/e98610a4-ab60-11e6-948c-e362460cec71.png)
![voyager5](https://cloud.githubusercontent.com/assets/10511483/20306588/07b91490-ab61-11e6-8689-f972efee6743.png)

**Comment by fergthh** [comment]
You need visit yourdomain.com/admin to login into voyager.

**Comment by Nagendra1421** [comment]
@fergthh Thanks
