### ISSUE TITLE
Role's Display name dose not show under edit user instead it shows Role name.

### ISSUE THREAD

**Issue by DaKe-Zhang** [thedevdojo/voyager#1742]
- Laravel Version: 5.5.4
- Voyager Version: dev-master
- PHP Version:
- Database Driver & Version:

### Description:
Role's Display name dose not show under edit user, instead it shows Role name.

**Comment by chadpriddle** [comment]
I just upgraded to 1.0 and I ended up adding a relationship on the user BREAD and added "belongs to" to roles and then mapped the id to the display name field. Seems like this should be included in a migration automatically

**Comment by lancepioch** [comment]
Labels: design, possible bug

**Comment by emptynick** [comment]
Fixed in #2837
