### ISSUE TITLE
Upgrade to 1.0 - Language translation broken

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#1746]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:
Followed the upgrade instructions to a tee. Looks like the language translation is broken. The en file is still in publishable and I have the default settings in config file. 

### Steps To Reproduce:
The top breadcrumb says "voyager.generic.dashboard" instead of Dashboard. If I go to setting it says "voyager.generic.settings" as the page title instead of Settings.
Something is going on with the language renderer

**Comment by Bayasgalan** [comment]
yea me too. login page also.
"voyager.generic.email" instead of email
"voyager.generic.password" instead of password.
and other buttons.
...., etc
https://imgur.com/a/ueq8O

**Comment by marktopper** [comment]
You need to republish the Voyager service provider's language assets.

**Comment by chadpriddle** [comment]
Found it. Thanks

`php artisan vendor:publish --tag=lang --force
`

**Comment by BOLYAC** [comment]
dosn't work for me

**Comment by fletch3555** [comment]
@BOLYAC, please do not comment on closed issues, especially when they've been closed for ~9 months...  If you have an issue, please open your own issue or ask for assistance in our Slack group
