### ISSUE TITLE
Can't find blade file for users

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/voyager#1763]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

I want to add column for users in the database and display it to the users table in blade.. but I can't find the blade file for users.

**Comment by fletch3555** [comment]
For future reference, we require version information be provided for all issues.  It helps us with troubleshooting reported issues.

For your issue, any BREAD type that doesn't have an associated folder will use the `bread` views by default: https://github.com/the-control-group/voyager/tree/master/resources/views/bread
