### ISSUE TITLE
Many to Many Relationship Problem

### ISSUE THREAD

**Issue by adddz** [thedevdojo/voyager#1765]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7

### Description:

I have a Many to Many relationship `Store` <-> `Item`. Trying to set up the relationship inside `Store` with `Belongs to Many` but when I try to edit the store, I get this error:

`ErrorException (E_ERROR)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id` from `items` inner join `item_store` on `items`.`id` = `item_store`.`item_id` where `item_store`.`store_id` = 51) `

@marktopper 

### Steps To Reproduce:

```
class Item extends Model
{

   public function stores()
   {
      return $this->belongsToMany(Store::class);
   }

}
```

```
class Store extends Model
{

   protected $fillable = ['name', 'address'];

   public function items()
   {
      return $this->belongsToMany(Item::class);
   }

}
```

**Comment by marius-tverijonas** [comment]
I bet you have `id` column in your pivot table (item_store) ? You should use another primary key, for example [`item`, `store`]

**Comment by adddz** [comment]
Actually I have this in the pivot table.

```
Schema::create('item_store', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('item_id');
            $table->integer('store_id');
        });
```

**Comment by marius-tverijonas** [comment]
Just change primary key as I recommended. Should be ok then.

**Comment by adddz** [comment]
@marius-tverijonas How to change? And also, I will need also to choose stores from an Item and viceversa.

**Comment by marius-tverijonas** [comment]
Drop your primary key index and add composite primary key. 
More info https://laravel.com/docs/5.5/migrations#indexes

**Comment by adddz** [comment]
Is this what I need? `$table->index(['store_id', 'item_id']);`

**Comment by marius-tverijonas** [comment]
You should use $table->primary(['store_id', 'item_id']); But before make sure you delete existing primary key.

**Comment by adddz** [comment]
To remove the existing primary key, I just need to remove the `$table->increments('id');` from the migration class, right?

**Comment by marius-tverijonas** [comment]
No, you must use $table->dropPrimary();
https://laravel.com/docs/5.1/migrations#dropping-indexes

**Comment by adddz** [comment]
Even if I just `migrate:refresh`?

**Comment by marius-tverijonas** [comment]
If you do migrate:refresh you just need to change 
$table->increments('id');  
to 
$table->primary(['store_id', 'item_id']);

**Comment by marktopper** [comment]
This seems to have been solved by adding the primary keys.

**Comment by mattkoch614** [comment]
Just wondering why this is necessary. What if we want the primary key to be auto-incrementing, but also want the foreign keys with a unique constraint on them at the same time?

**Comment by rastapezzolo** [comment]
Same question here. Why is it necessary? 
Wouldn't <pivot_table_name>.<primary_key> in join select solve the issue without make mandatory having a different primary key?

**Comment by fletch3555** [comment]
This is precisely why we discourage commenting on old/closed issues.  The solution you're proposing was merged in and released already.

**Comment by rastapezzolo** [comment]
Ok, _really sorry_ for commenting an old issue but it didn't seem to me to be closed. I was writing my situation then i found that the relations.blade.php was overridden by some of my colleagues starting from 1.0.13 rev.

Sorry again.

**Comment by fletch3555** [comment]
No need to apologize.  Just calling out the problem.
