### ISSUE TITLE
Advance / Multiple Column Search in BREAD

### ISSUE THREAD

**Issue by sah-anshu** [thedevdojo/voyager#1767]
Hi

The bread is responsible to show Only 1 Column Search. How Can we extend this. 

Thanks in advance. 
Anshu

**Comment by anselmobattisti** [comment]
Man, that is the big problem of almost all tools.

Make a greate grid with search in backend with multiples columns is not easy.

I think, the soluction is to make your own datagrid when it is needed :(

**Comment by sradesign** [comment]
actually with datatables is easy to make but the way that Voyager feed the datatables I can not add potions to it.

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/4216
