### ISSUE TITLE
Image Profile Upload Error

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1768]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:  7.1.8
- Database Driver & Version: Php My admin 4.7.0

### Description:

In Fresh Install of Laravel 5.5 LTS, i want to upload my admin photo profile but didnt show anything like this
![error](https://user-images.githubusercontent.com/26824873/30636686-6247a176-9e20-11e7-99b5-dfbb7dcc451c.png)

**Comment by marktopper** [comment]
This happens when you are missing a symlink.
You should run `php artisan storage:link`

**Comment by gizburdt** [comment]
I also have this problem, even after running `php artisan storage:link`

**Comment by fletch3555** [comment]
@gizburdt, we prefer you don't comment on closed issues.  Please open your own or ask on the Slack group
