### ISSUE TITLE
Custom Layout 

### ISSUE THREAD

**Issue by 123payal** [thedevdojo/voyager#1769]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

How can we use default post bread layout in custom bread

**Comment by marktopper** [comment]
You may reuse this blade file for your own BREAD.
https://github.com/the-control-group/voyager/blob/master/resources/views/posts/edit-add.blade.php

**Comment by 123payal** [comment]
Thanks 

 But where will get the view file of custom bread

**Comment by marktopper** [comment]
You can read about it [here](https://voyager.readme.io/docs/overriding-views).
