### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found:

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/voyager#1770]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I deleted the posts, categories, and pages tables and the menus of it. And got an error when trying to access the dashboard. 

ErrorException (E_ERROR)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'circle.posts' doesn't exist (SQL: select count(*) as aggregate from `posts`) (View: C:\laragon\www\circle\vendor\tcg\voyager\resources\views\dimmers.blade.php) (View: C:\laragon\www\circle\vendor\tcg\voyager\resources\views\dimmers.blade.php)

I know it is because I deleted the tables and they can't find it but I'm having a hard time finding where is the code of it to just delete it. I think it is from the dashboard view where how many users, posts, being displayed.

**Comment by rexdarel** [comment]
Sorry for posting this useless question. I found the answer in the issues.

**Comment by deepkumar23** [comment]
I am facing the same problem can u please tell me the solution for it... @rexdarel

**Comment by fletch3555** [comment]
This issue is 4 months old now, and I doubt your issue is the exact same.  Just create a new issue and reference this one saying you think it's the same.  Reviving old closed issues is not appreciated here.
