### ISSUE TITLE
Relationship problems

### ISSUE THREAD

**Issue by pontInformat** [thedevdojo/voyager#1771]
- Laravel Version: 5.5.4
- Voyager Version: 1.0.0
- PHP Version: 7.1.8
- Database Driver & Version: 

### Description:
I try to do one relationship between two models created. I create Model 1 like this:
![image](https://user-images.githubusercontent.com/32131312/30643681-2a32576e-9e10-11e7-825a-e892921d6712.png)

Model 2:
![image](https://user-images.githubusercontent.com/32131312/30643704-3f0bf5d2-9e10-11e7-8449-e2ae9cd8ac2f.png)

In Voyager admin menu -> Tools -> Database -> Create New Table, I have created 2 tables (Seguro and Aseguradora) like this:
Seguro:
![image](https://user-images.githubusercontent.com/32131312/30643837-b80067e8-9e10-11e7-9bb9-1752fadff924.png)

Aseguradora:
![image](https://user-images.githubusercontent.com/32131312/30643876-d1fd18ee-9e10-11e7-939b-ce4392519ab1.png)

Then, I have created one bread for Seguro and other for Aseguradora:

Seguro:
![image](https://user-images.githubusercontent.com/32131312/30644049-64fee398-9e11-11e7-8caf-893b9093387a.png)

Aseguradora:
![image](https://user-images.githubusercontent.com/32131312/30644010-3d5a77bc-9e11-11e7-8bcc-cf65b2cbfe86.png)

If I try to do one relationship ManyToOne between Aseguradora->Seguro not found. For example in bread Aseguradora if I select the button "Create a Relationship", I only can select the table, all other fields are "No results Found". I can't select the colum for relationship, but I can save the relation
![image](https://user-images.githubusercontent.com/32131312/30644259-1e7e883c-9e12-11e7-9380-65e4bf2e739b.png)

If I select submit the bread I receive this error message :
![image](https://user-images.githubusercontent.com/32131312/30644664-6bc3700c-9e13-11e7-8e91-697939f24cf9.png)

I don't know what appends. Have I configured something wrong?
can anybody help me?
Thanks!

**Comment by fletch3555** [comment]
Please run `composer require tcg/voyager dev-master` and test again.  We've merged a fix for a similar issue and I think it may fix yours as well.

**Comment by sah-anshu** [comment]
No its doesn't help my driver is Postgresql here

**Comment by fletch3555** [comment]
@sah-anshu, @pontInformat closed the issue as it fixed his.  If you have another problem, please open your own issue so we can track it appropriately.
