### ISSUE TITLE
Prefix can't work in configure file.

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#1772]
- Laravel Version: 5.5
- Voyager Version: New
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
https://voyager.readme.io/docs/configurations#section-prefix-config
I try to do it. But it's can't change prefix. 
Maybe i need change more configure files?

**Comment by davodavodavo3** [comment]
What kind of error do you get?

**Comment by Rishats** [comment]
I open voyager.php and write my own prefix in line 108. And try to open admin panel with my prefix. 
And...
Sorry, the page you are looking for could not be found.

But if i use old prefix which was admin, it's work.

**Comment by davodavodavo3** [comment]
Go to your routes and change prefix for Voayer routes
```
Route::group(['prefix' => 'yourprefix'], function () {
    Voyager::routes();
});
```

**Comment by davodavodavo3** [comment]
Next will need to change all admin side menu url's in Menu Builder

**Comment by Rishats** [comment]
Thanks you ^)

**Comment by davodavodavo3** [comment]
Best solution is to change from
```
Route::group(['prefix' => 'yourprefix'], function () {
    Voyager::routes();
});
```
to
```
Route::group(['prefix' => config('voyager.prefix')], function () {
    Voyager::routes();
});
```

**Comment by davodavodavo3** [comment]
@Rishats if you solve this problem please close this question

**Comment by fletch3555** [comment]
We're removing the `voyager.prefix` config in a future release since it's not actually used anywhere, so I wouldn't rely on it.  Instead, you can just change the Route prefix as @davodavodavo3 suggested.  Everything in Voyager should be using named routes, so there shouldn't be any issues with doing this.
