### ISSUE TITLE
"Class 'App\User' not found" Error During Installation

### ISSUE THREAD

**Issue by isaacdagel** [thedevdojo/voyager#1776]
- Laravel Version: 5.5.9
- Voyager Version: 1.0.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I receive the following error when I try to install Voyager:

<img width="642" alt="error" src="https://user-images.githubusercontent.com/4097420/30655557-798cd4c8-9dee-11e7-9982-508ffc40a785.png">

I am attempting to install Voyager into an existing project with a custom namespace. As far as I can tell the project has been properly updated to use the custom namespace.

### Steps To Reproduce:

Run 'composer require tcg/voyager'

**Comment by fletch3555** [comment]
Voyager is built with the expectation that it will be installed on a fresh install of Laravel (or at least one with minimal changes from the defaults).  Doing anything else may require some changes to the process.

In your case, you've moved the `User` model from `\App` to (I presume) `\App\Models`.  You will need to publish the voyager config file (run `artisan vendor:publish` then select `VoyagerServiceProvider`), change the user model config to the appropriate namespace, then run `artisan voyager:install` again.
