### ISSUE TITLE
Relationship builder confused when voyager.prefix config is empty.

### ISSUE THREAD

**Issue by gausam** [thedevdojo/voyager#1777]
- Laravel Version: 5.5.8
- Voyager Version: 1.0.0
- PHP Version: 7.1.9
- Database Driver & Version: MariaDB 10.2.7

### Description:
An empty (`null` or `''`) value for `voyager.prefix` confuses the relationship builder, resulting in a "No Results" value in the Selection Details dropdowns. This is due to [this line of code](https://github.com/the-control-group/voyager/pull/1603/files#diff-8fa57d0f1a808810b460b59a7647eed5R469) generating a // url, as @fletch3555 [found out](https://laravel-voyager.slack.com/archives/C36H9MY2C/p1505924649000284).

### Steps To Reproduce:
Set `prefix` to / or '' or null in `config.voyager`.

**Comment by asharekh** [comment]
i have the same issue, is there a workaround for this?

but : 
'prefix' => 'admin',

**Comment by fletch3555** [comment]
@asharekh, please open your own issue or ask for help in our Slack group.  Commenting on closed issues is not encouraged.
