### ISSUE TITLE
Password required when updating user

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#1782]
- Laravel Version: 5.4
- Voyager Version: 1.0.1
- PHP Version: 7
- Database Driver & Version: MySQL 5.6

### Description:
"Please fill out this field" pops up when editing a user on the password field.

### Steps To Reproduce:
Go to users, click edit, modify name field, click save, forces you to type in the password to save changes instead of keeping current password

**Comment by davodavodavo3** [comment]
Are you add custom validation for that field?
i.e to password field
```
{
    "validation": {
        "rule": "required"
    }
}
```
if yes it will be required always

**Comment by davodavodavo3** [comment]
You need other validation logic for require password field or create your own controller.
If you dont want to create custom controller then you need validation like this
First: check to show user id in edit bread with disabled atribute if you want.
Second: validation for password field will be 
```
{
    "validation": {
        "rule": "required_without:id"
    }
}
```
ie. If you create user there is no user id and password filed will be required , if you edit user password field is not required(already have a password in the database)

**Comment by chadpriddle** [comment]
I'm using the stock User model. It should work out of the box

**Comment by davodavodavo3** [comment]
Hmmm in stock user databse there is no required password field.
I see that in database/seeds/DataRowsTableSeeder.php
```
$dataRow = $this->dataRow($userDataType, 'password');
        if (!$dataRow->exists) {
            $dataRow->fill([
                'type'         => 'password',
                'display_name' => 'password',
                'required'     => 0, //PASSWORD NOT REUIRED
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details'      => '',
                'order'        => 4,
            ])->save();
        }
```

**Comment by chadpriddle** [comment]
It should be required when adding a new user but not when updating the user

**Comment by fletch3555** [comment]
As @davodavodavo3 said, the BREAD configuration will apply to ALL pages/forms within Voyager.

At this point, I'm comfortable saying this is an issue with validation in your app, not one with Voyager.  If you need further assistance, please consider joining the Voyager or LaraChat Slack groups.
