### ISSUE TITLE
Issue with admin side dropdown menu in other language

### ISSUE THREAD

**Issue by davodavodavo3** [thedevdojo/voyager#1787]
- Laravel Version: 5.4
- Voyager Version: 1.0.1

### Description:
str_slug($originalItem->title, '-')
str_slug($item->title, '-')

Guys did you see difference?

### Steps To Reproduce:
Create multi language site. Lets say in Russian and English.
Enable multi language for Voyager. Select default language en, and languages that are supported en ,ru
Add translation for example to Tools Menu. In Russian it will be Инструменты,
in English str_slug($item->title, '-') = tools
in Russian str_slug($item->title, '-') = instrumenty
Now if your deafult language is English for Voayager your $originalItem->title will be tools
Change site language to Russian( App::setLocale('ru')) and dropdown will not expand because 

$item->title = instrumenty
`<a href="{{ str_slug($item->title, '-') }}-dropdown-element"" target="{{ $item->target }}">Инструменты</a>`

and dropdwon class is 

$originalItem->title = tools
`<div id="{{ str_slug($originalItem->title, '-') }}-dropdown-element"`

**Comment by Mikisbell** [comment]
could you explain me in detail please

**Comment by davodavodavo3** [comment]
explain in more detail I cant)))))

**Comment by fletch3555** [comment]
I just rewrote the admin in #1813, which may or may not resolve this.  Once it's merged in, you can test there and reopen this if necessary, preferably with a clearer explanation of what's actually not working.
