### ISSUE TITLE
Error when use Post Page

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1788]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: phpmyadmin 4.7.0

### Description:
I want to make a blog site , but when i insert {{ post->body }} inside my show.blade.php 
it generate <p></p> but without html mark up detect like this
![error1](https://user-images.githubusercontent.com/26824873/30679650-110d7ba0-9ec5-11e7-8d00-e2c30a62d0ad.png)

![error2](https://user-images.githubusercontent.com/26824873/30679652-1499ba4a-9ec5-11e7-9eed-657420edb32a.png)

**Comment by hailwood** [comment]
@mlazuardy 

> By default, Blade {{ }} statements are automatically sent through PHP's htmlspecialchars function to prevent XSS attacks. If you do not want your data to be escaped, you may use the following syntax:

```
Hello, {!! $name !!}.
```

**Comment by davodavodavo3** [comment]
As @hailwood said, use right  syntax {!! post->body !!}

**Comment by mlazuardy** [comment]
what exactly i must Write in my show.blade.php sir? Sorry i dont know about XSS, i use {{ $post->body }} but it generate the HTML markup as string . sorry sir bad english and bad logic

**Comment by davodavodavo3** [comment]
no need for an apology)))
You need to add {!! $post->body !!} in your show.blade.php

**Comment by mlazuardy** [comment]
@davodavodavo3  Really Thank you sir for your help , it work.

**Comment by davodavodavo3** [comment]
if all works please close issue

**Comment by nanadjei** [comment]
What about pages. I tried to add a page using voyager but am getting the same error.

**Comment by fletch3555** [comment]
@nanadjei2, this issue has been closed for 4 months now.  If you still have a problem, please open your own issue.
