### ISSUE TITLE
Relationship shows incorrect Model and "None results"

### ISSUE THREAD

**Issue by scottybo** [thedevdojo/voyager#1790]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
When I add a Relationship to a BREAD table it allows me to select whichever table has the relationship. 

However, there are two major issues:
1) When I go to edit the Relationship it now shows the incorrect table. Where it says "Websites" in the image below is incorrect - I chose a different table when creating the relationship
![edit bread for twitter_user_platform_lookup table](https://user-images.githubusercontent.com/11498904/30683346-0544a96c-9ea5-11e7-83c9-43c64baef6b5.png)
2) When viewing the BREAD the column says "None results" when there definitey should be results
![viewing twitter user platform lookups](https://user-images.githubusercontent.com/11498904/30683402-4318da74-9ea5-11e7-9eef-7aa81ff6fb42.png)

### Steps To Reproduce:
1) Edit a BREAD
2) Add a Relationship as you normally would
3) Save
4) Go back to the BREAD edit screen and modify your newly created Relationship
5) It will (probably) show the table which is last in your table list

**Comment by marktopper** [comment]
Please share your BREAD settings for that table.

**Comment by amitn322** [comment]
I am having the same Issue.

**Comment by quanttsm** [comment]
I am having the same Issue, please fix asap.

**Comment by fletch3555** [comment]
Will someone who is having this issue please provide more information as @marktopper requested?

Specifically, it would be very helpful to see the BREAD settings (model name especially) for both sides of the relationship, the full relationship editor view (only half is shown above), and (if possible) the actual query being run (found through [laravel-debugbar](https://github.com/barryvdh/laravel-debugbar)) to produce the "None results"

**Comment by emptynick** [comment]
The first problem was fixed in https://github.com/the-control-group/voyager/pull/2155
The second seems to be like https://github.com/the-control-group/voyager/issues/2342

If any of the problems still remain, please open a new issue
