### ISSUE TITLE
Mobile: Can't view table

### ISSUE THREAD

**Issue by scottybo** [thedevdojo/voyager#1791]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
When viewing a Browse screen for a table on mobile the table gets chopped off with no ability to swipe left/right to view the "hidden" columns

![viewing twitter user platform lookups 1](https://user-images.githubusercontent.com/11498904/30683863-e878cd0c-9ea6-11e7-9dd7-775716508885.png)

**Comment by fletch3555** [comment]
That SHOULD be scrollable.... Unfortunately, there's no good way to display that much data in a table on a mobile screen, but we're always open to suggestions.

For the fix, we likely need a CSS change to allow scrolling.  If you'd like to figure it out, we'd welcome a pull request for it!  Otherwise we'll take a look.  Thanks!

**Comment by scottybo** [comment]
On the container div you could have overflow: auto;

**Comment by vaggelis2018** [comment]
@fletch3555 i have the same problem and i agree with you that this only can fixed with scroll. @scottybo i think this is the solution for making it scrollable

**Comment by fletch3555** [comment]
If someone wants to open a pull request for it, I'd appreciate it

**Comment by vaggelis2018** [comment]
@fletch3555 no need for pr. The one who created the layout is using DataTables. which can take the option 'scrollX' => true in json format . The one who created them was so smart who predicted that someone may want to pass his own options so he added a json encode with some standard option and left this: config('voyager.dashboard.data_tables', []) with array merge. So everyone who want to make tables scrollable have the ability to simply passe 'data_tables' =>[  'scrollX' => true ], in config/voyager.php in 'dashboard' section.

Note: In firefox android it doesn't work

**Comment by nosolosoft** [comment]
It's seem it works also in firefox android. Already tested.
