### ISSUE TITLE
Media Manager per folder Roles/Permissions?

### ISSUE THREAD

**Issue by marcreichel** [thedevdojo/voyager#1792]
Hi there,

is it possible to set roles/permission on folders in the media manager? So that can have different folders and in each folder only certain roles can upload files (and also only these roles can see the folder)?

Example:
Role 1 can see folder "summer party" and can upload files into this folder.
Role 2 can see folder "christmas" and can upload files into this folder. But Role 1 could not see the "christmas"-folder and cannot upload files into this folder (and vice versa).

So something like Policies (where you can define that a user must be in Role 1 to see/edit/delete a Post for example) for the CRUD/BREAD part. But for the Media Manager.

I hope it's clear what I want to accomplish?

**Comment by fletch3555** [comment]
That's not currently possible, and is somewhat difficult to build with how the media manager is currently built.  It uses physical directories on the host as the directories in media manager, so we would need a whole new way of tracking the folders.

We'll look into it (and are open to pull requests if you wish to give it a try yourself!), but it likely won't get merged in until a new major/minor release (depending on implementation) as it would likely require breaking changes

**Comment by emptynick** [comment]
This will be possible in version 1.2 (https://github.com/the-control-group/voyager/pull/3889).
It allows you to change the `base_path` during runtime.
