### ISSUE TITLE
BREAD Need Help

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#1793]
- Laravel Version: 5.5
- Voyager Version: 1.0.1
- PHP Version:7.1.7 
- Database Driver & Version:10.1.25-MariaDB 

Hi
I Have created a BREAD
http://localhost/admin/countries

its working great but i was wondering if its possible to access http://localhost/countries  directly  without admin directory for normal user  or i must create a custom blade and controller  for this 

Thank you

**Comment by fletch3555** [comment]
That would be part of your site, not part of voyager, so you would have to build it yourself (new route/controller/view/etc).
