### ISSUE TITLE
Array to string conversion (Multiple select)

### ISSUE THREAD

**Issue by NicolaeCasir** [thedevdojo/voyager#1795]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version: 7.1.8
- Database Driver & Version: MySQL  Ver 15.1 Distrib 10.2.6-MariaDB

### Description:
[Screenshot of my error](https://i.imgur.com/dN2Jh2J.png)
I cant save Multiple select item .
My options: 
`{
    "options": {
        "Bedside table": "Bedside table",
        "Satellite TV": "Satellite TV",
        "Shower cabin": "Shower cabin",
        "Mini Bar": "Mini Bar"
    }
}`

**Comment by fletch3555** [comment]
Please provide the full stacktrace

**Comment by NicolaeCasir** [comment]
[error.txt](https://github.com/the-control-group/voyager/files/1322284/error.txt)
@fletch3555 
From Log.

**Comment by NicolaeCasir** [comment]
I solved it!!...

**Comment by samanmohamadi** [comment]
I Have The Same Problem

**Comment by fletch3555** [comment]
Please update to the latest version (v1.0.6) and try again.  I feel this may have been resolved.

**Comment by samanmohamadi** [comment]
Yes, it has been resolved.

**Comment by fletch3555** [comment]
Okay, thanks!

**Comment by neverfan** [comment]
This is an erroneous decision, it breaks browse bread view, where "select_multiple" filed used as array https://github.com/the-control-group/voyager/blob/master/resources/views/bread/browse.blade.php#L91

And this broke using models casts for fields used as select_multiple in admin, I think need use Eloquent "getOriginal()" method some like this:

$dataTypeContent->{$row->field} = json_decode($dataTypeContent->getOriginal()->{$row->field})

the model property should not always be expected as a string

**Comment by neverfan** [comment]
And when use filed as "select_multiple" if data of filed is PostgreSQL array like "{some_value_1,some_value_2}" that code can't work. 

I think you need to enable each developer to decide how to prepare the data for the array.
