### ISSUE TITLE
Class 'App\User' not found if not using default 'App' namespace

### ISSUE THREAD

**Issue by peyobr** [thedevdojo/voyager#1796]
- Laravel Version: 5.5.5
- Voyager Version: 1.0.0
- PHP Version: PHP 7.0.22
- Database Driver & Version: Mysql 5.7.19

### Description:

Class 'App\User' not found generating optimized autoload files if not using default 'App' namespace

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

                                                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'App\User' not found                               
                                                           

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.
```

### Steps To Reproduce:

1) create L5.5 new fresh project

2) php artisan app:name MyNamespace

3) composer require tcg/voyager

**Comment by CodeBradley** [comment]
This can be updated by editing the config, here is a relevant line of code from the AdminCommand.php file.

https://github.com/the-control-group/voyager/blob/2c0f2713a34d1503a447ab50119e4515f25b0ad0/src/Commands/AdminCommand.php#L114

Below is the configuration documentation.

https://voyager.readme.io/docs/configurations

**Comment by marktopper** [comment]
Change the setting like @CodeBradley said

**Comment by runoncedev** [comment]
Isn't it possible for Voyager to get the User model class from `config/auth.php`?

**Comment by fletch3555** [comment]
Yes, and we may choose to change that at some point, but for now @CodeBradley's comment is correct.
