### ISSUE TITLE
BREAD BUILDER ERROR

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1797]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: PhpMyadmin 4.7.0

### Description:
I want to make "Event" Pages, I start create_events_table and Copy the $table like Posts Table.
then i create Event Model on http and Create BREAD on my admin pages
Everything goes work but when i start to browse the Event BREAD. and i get whoops like this  
![events](https://user-images.githubusercontent.com/26824873/30697593-c2a3dbf4-9f09-11e7-8dac-50445dcd4e52.png)

Please Help me and sorry for bad logic and bad english

**Comment by scottybo** [comment]
You need to go to Roles and choose the role you're trying to access with (e.g. admin) and make sure that the role has permission to view this Model.

Took a while for me to figure this one out too!

**Comment by marktopper** [comment]
In addition, you can also run those commands:

```
php artisan db:seed --class=PermissionsTableSeeder
php artisan voyager:admin YOUR@EMAIL.COM
```

Also make sure that your BREAD settings `Model` does not start with a leading backslash `\`.

**Comment by fletch3555** [comment]
@scottybo is likely correct.  @marktopper's suggestion will also do this, and will likely do it faster
