### ISSUE TITLE
User Profile image not not showing

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#1798]
Laravel Version: 5.5
    Voyager Version: 1.0.1
    PHP Version:7.1.7
    Database Driver & Version:10.1.25-MariaDB

### Description:
User Profile image not not showing .. i uploaded the profile image but its not showing in user profile . In Media folder file is created but the image is broken

**Comment by marktopper** [comment]
This is always a misconfiguration.
Please share the `APP_ENV` environment and the URL for your Voyager Admin Panel (you may replace your domain with `example.com` if you wish) and then the URL it tries to show the image at.

**Comment by marktopper** [comment]
Please include that information if you wish me to reopen.

**Comment by rddewan** [comment]
thanks i got it ..

**Comment by anselmobattisti** [comment]
By default the end of your url must be without / example: http://myexample.com and not  http://myexample.com/ that was my fault!
