### ISSUE TITLE
Settings menu item displayed when permission is not set

### ISSUE THREAD

**Issue by lucalategola** [thedevdojo/voyager#1800]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.19

### Description:
When deselect permission of "Settings" for a role and then you login with user with this role you see the Settings menu item. If you click you get the AccessDeniedHttpException: This action is unauthorized.

### Steps To Reproduce:
With Admin Role go to Roles -> Edit User Role: Deselect all "Settings" options.
Logout and login with a user that have User Role.
Now you see the Settings Menu Item. If you click you get the AccessDeniedHttpException: This action is unauthorized.

**Comment by scottybo** [comment]
I'm also experiencing this issue

**Comment by fletch3555** [comment]
The admin menu needs a rewrite.  We'll be working on that soon.

**Comment by fletch3555** [comment]
I actually rewrote the admin menu a few weeks ago.  This should be closed.
