### ISSUE TITLE
Artisan from Voyager fails when spaces in directory.

### ISSUE THREAD

**Issue by bbredewold** [thedevdojo/voyager#1801]
### Description:
When a space is present in a directoryname, the Artisan command fails.
(I'm using a Mac, behaviour on windows is unknown.)

### Steps To Reproduce:
Put a space into a directoryname.

`Artisan Command Output:
The command "cd /Users/bert/Documents/0 Projects/test-project && php artisan help" failed.

Exit Code: 1(General error)

Working directory: /Users/bert/Documents/0 Projects/test-project/public

Error Output:
sh: line 0: cd: /Users/bert/Documents/0: No such file or directory`

**Comment by marktopper** [comment]
Use this
```
cd "/Users/bert/Documents/0 Projects/test-project" && php artisan help
```

**Comment by fletch3555** [comment]
It would be beneficial to include the command you ran.

Also, we require all version numbers be present.
