### ISSUE TITLE
[ASK] How To Change Url 

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1805]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: php my admin 4.7.0

### Description:
I wanna change the url oh my blog post from localhost:8000/blog/1  
to localhost:8000/blog/slug-name e.g localhost:8000/blog/the-control-group

Can somebody teach me please :)

**Comment by ibourgeois** [comment]
You could accomplish this by adding the following method to your model and change `slug` to whatever column you wish to use in your URL

```php
public function getRouteKeyName()
{
    return 'slug';
}
```

You can checkout the Laravel documentation for more details and options https://laravel.com/docs/5.5/routing#route-model-binding
