### ISSUE TITLE
Would you accept a PR that removes template logic?

### ISSUE THREAD

**Issue by hailwood** [thedevdojo/voyager#1812]
Specifically I'm talking about things like the logic in 

- [resources/views/formfields/relationship.blade.php](https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/relationship.blade.php)
- [resources/views/formfields/select_dropdown.blade.php](https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/select_dropdown.blade.php)
- etc

That logic really should be contained within a [view composer](https://laravel.com/docs/5.5/views#view-composers), but I don't want to waste my time tidying this up if it's not going to be accepted.

**Comment by fletch3555** [comment]
I'm certainly open to PRs.  I can't guarantee it would be merged in, but I'm always in favor of refactoring code to be cleaner.

**Comment by fletch3555** [comment]
I'm going to close this as there's nothing actionable on our side.  Please feel free to submit the PR.  Thanks!
