### ISSUE TITLE
[ASK] multiply Route

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1819]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: phpmyadmin 4.7.0

### Description:
Sorry sir, if is not about Laravel Voyager, but i have a question. I Already Make Blog Page on localhost:8000/blog where have list of my blog
the question is, i want to make List of my blog too in my homepage at localhost:8000/home for  3 "newest article" of my blog
what exactly i must to do? please help me

**Comment by fletch3555** [comment]
This is not an issue with Voyager. Please seek help through a more generic laravel forum such as the laracasts forum or larachat slack group
