### ISSUE TITLE
JQuery not recognized 

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#1820]
- Laravel Version: 5.5.11
- Voyager Version: 1.0.2
- PHP Version: 7.1.8
- Database Driver & Version: Maria DB 10.1

### Description:
I get this error ReferenceError: $ is not defined when i try to write jquery in blades. 

### Steps To Reproduce:
More specific
if i write 

```
<script type="text/javascript">
      $('document').ready(function ()  {
                 $('#scheduler').datetimepicker({
                           format:"YYYY-MM-DD HH:mm:ss",
                            sideBySide:true
                });

$('#schedule_at').val("@if(isset($dataTypeContent->schedule_at)){{ $dataTypeContent->schedule_at }}@endif");
   });
 </script>
```

@marktopper it is the issue we talked about in slack also it may related with issue  #1806. It maybe the order of scripts loading

**Comment by davodavodavo3** [comment]
I am using 
Laravel: 5.4
Voyaegr: 1.0.2
Browser: Gooooogle Chrome
I crate datetime field in database and set fieald type in Voyager to date
Picker is show normal, no javascript errors, tried with custom user view.
@vaggelis2018 where to put that javascript to check that issue?

**Comment by vaggelis2018** [comment]
@davodavodavo3  right after the field where i had it in version 1.0.1 also tried on bottom of the page but i get more errors.

**Comment by vaggelis2018** [comment]
I added datepicker and moment.js with locales, putted code on bottom and issue fixed. I think it misses some npm packages or just js files. It wasn't a jquery issue in the end.
