### ISSUE TITLE
Media Manager, Unable to upload files

### ISSUE THREAD

**Issue by vanvanni** [thedevdojo/voyager#1822]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.6
- Database Driver & Version: 10.1.24-MariaDB - mariadb.org binary distribution

### Description:
After reporting on #1786 and updating Voyager and having the Fix I got a error alert and nothing in the log.

**Whoopsie!**
The file "" does not exist

_Yes, I did select a file (PNG) _

**Comment by davodavodavo3** [comment]
it seems like only you have such an issue.
Update Voyager to version 1.0.2. I see you are use Voyager Version: 1.0.
And whether that issue can be due to your xampp local server?

**Comment by maktibab** [comment]
I have the same issue, see #1711

**Comment by vanvanni** [comment]
@davodavodavo3 I updated Voyager that updated to 1.0.2 that gave me this issue.

**Comment by fletch3555** [comment]
Closing in favor of #1711.

**Comment by EmilBelas2015** [comment]
I had same issue and same error "text" my version is voyager 1.0.14 but problem was in filesize limit in php.ini not in voyager. Hope it helps

**Comment by ivanfretes** [comment]
Update the environment variable **APP_URL=http://localhost:8000** in the .env files

**Comment by fletch3555** [comment]
@ivanfretes, that has nothing to do with this issue. Not to mention it's been closed for months.
