### ISSUE TITLE
dropdown list no results found

### ISSUE THREAD

**Issue by saldanac** [thedevdojo/voyager#1826]
- Laravel Version: 5.3
- Voyager Version: 0.11.14
- PHP Version: 5.6.4

### Description:

No results found on dropdown list. here my code

help please

### Steps To Reproduce:

`public function idTipBgi()
    {
        return $this->belongsTo('App\T000tipbgi');
    }`

`public function t000bgimgPages()
    {
    	return $this->hasMany('App\T000bgimgPage');
    }`

`{
    "Elegir": {
        "key": "id",
        "label": "nom_tip"
    }
}`

**Comment by saldanac** [comment]
![1](https://user-images.githubusercontent.com/21126731/30748414-3d1da76a-9f7e-11e7-88f0-56b489d6ccbd.JPG)

**Comment by fletch3555** [comment]
Please upgrade to 1.0. The relationship builder works so much better.

**Comment by saldanac** [comment]
changed
```
{
    "Elegir": {
        "key": "id",
        "label": "nom_tip"
    }
}
```
to 
```
{
    "relationship": {
        "key": "id",
        "label": "nom_tip"
    }
}
```
and works fine now 👍
