### ISSUE TITLE
Menu with 2+ levels doesn't works

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1830]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7

### Description:
I try to put all items of the default voyager menu in a parent category named "Voyager". After that I notice that menu doesn't work on 2+ level of nested items. 

In my example I can't able to expand 'tools' because inside 'voyager' item.

**Comment by fletch3555** [comment]
I'm not really sure why you would do that, but I can definitely see how having 3 or more levels would be useful.  Unfortunately that's a known problem that we'll be working to fix.  It's a JS issue, so if you'd like to try fixing it, please feel free to do so and submit a pull request.
