### ISSUE TITLE
HTTPS errors on assets

### ISSUE THREAD

**Issue by ysads** [thedevdojo/voyager#1833]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I have a problem with my admin configuration. Since my server runs under HTTPS connection, Voyager assets are blocked and, consequently, can't be loaded by the pages. Does anybody knows a simple way to fix that?

**Comment by fletch3555** [comment]
Voyager's assets should all be loaded using relative URLs, so that should be a non-issue.  Can you please provide some examples?  This is the first I've heard of anyone having this issue.

**Comment by anselmobattisti** [comment]
https://voyager.readme.io/docs/using-https-on-your-site probably your answer is here

**Comment by vaggelis2018** [comment]
i already have voyager with https on production and i have no problem with that

**Comment by gnovaro** [comment]
I have the same issue. In a production env with cloudflare HTTPS certificate.

**Comment by gnovaro** [comment]
If you add this in your web.php in routes first solve this isssue.

if (App::environment('production', 'staging')) {
    URL::forceScheme('https');
}

**Comment by fletch3555** [comment]
I'm going to close this.  @anselmobattisti's link should be adequate at resolving this.

**Comment by CaddyDz** [comment]
The link didn't help
@gnovaro answer did

**Comment by DrudgeRajen** [comment]
To Use HTTPS, in `config/voyager.php` use `secure_asset()`

`'assets_path' => secure_asset('/vendor/tcg/voyager/assets'),`

**Comment by chihebnabil** [comment]
@ysads you can update the APP_URL in your env file and pull an https URL

**Comment by CaddyDz** [comment]
Euw this is still alive after Laravel Nova release?

**Comment by digitalcoaster** [comment]
@gnovaro answer solved this for me
