### ISSUE TITLE
Returning JSON for DB tables

### ISSUE THREAD

**Issue by ankitjain28may** [thedevdojo/voyager#1834]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.0
- Database Driver & Version: mysql

### Description:
When i am trying to access tables in database by this route (http://localhost:8000/admin/databse/table_name) its returning me json.

### Steps To Reproduce:
1. Login to admin account.
2. click on database from setting from sidebar.
3. Click on any table, a modal appears, Its fine.
4. Click on edit option of any table.
5. From directory path at the top, click on table name, It returns json of the table schema models.

**Comment by davodavodavo3** [comment]
I confirm , breadcrumbs need refactoring. Or disable click breadcrumb if you are in database builder
