### ISSUE TITLE
expression is not assignable: silence expression

### ISSUE THREAD

**Issue by abdullahessam** [thedevdojo/voyager#1835]
- Laravel Version: 5.4
- Voyager Version: 1
- PHP Version: 7
- Database Driver & Version: mysql 5.7

### Description:
hi when i open  /vendor/tcg/voyager/src/Voyager.php
this error shown expression is not assignable: silence expression
as pic 
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/24545226/30764128-e4d62c14-9fe9-11e7-8a86-97a937022da5.png)

**Comment by fletch3555** [comment]
That's just an issue within PHPStorm.  The code still runs without error as far as I'm aware.

**Comment by ricardosaracino** [comment]
Same issue for me too, its just annoying 

IntelliJ IDEA 2019.1.2 (Ultimate Edition)
Build #IU-191.7141.44, built on May 7, 2019
Licensed to Ricardo Saracino
You have a perpetual fallback license for this version
Subscription is active until August 10, 2020
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

![image](https://user-images.githubusercontent.com/759253/62825974-2e64a080-bb82-11e9-8cbe-82be124d2aaf.png)
