### ISSUE TITLE
Dynamic dropdown list

### ISSUE THREAD

**Issue by alexandru-core** [thedevdojo/voyager#1839]
Laravel Version: 5.5.*
Voyager Version: ^1.0
PHP Version: 7.1.1

### Question

Is the scenario below possible via voyager BREAD editor

I have 3 tables Category Items and Sales

In Sales I have created relationships for category and Items.

How can I make the 2 dropdowns dynamic when I select a category only the items from that specific category to show up in the second dropdown.

And as a for items when I select a specific item I would like to add the default price for that item in the Price field.

**Comment by fletch3555** [comment]
I'm sorry if I've misunderstood what you're asking, but It sounds like you need a better understanding of [Eloquent relationships](https://laravel.com/docs/5.5/eloquent-relationships).  Once you fully understand this topic, please watch the videos at https://laravelvoyager.com/academy/ (specifically this one: https://laravelvoyager.com/academy/relationships/).  If you still need assistance, we'll be glad to help walk you through it in our Slack group.

**Comment by doubleprincez** [comment]
I think what he is trying to explain is how can someone populate the items for the dropdown from a table in the database. Without voyager, I can populate the category items and display them in the dropdown but how do you use voyager to generate the dynamic dropdown items?

**Comment by lee-van-oetz** [comment]
You can create your own custom field where you can load anything you need into options:
```
<?php

namespace App\Foo\VoyagerFormFields;


use App\Foo\LenderRulesetRule;
use App\Foo\LenderRuleTypes;
use TCG\Voyager\FormFields\AbstractHandler;

class RuleType extends AbstractHandler
{
    protected $codename = 'rule_type';

    public function createContent($row, $dataType, $dataTypeContent, $options)
    {
        $options->options = LenderRulesetRule::TYPES;  # This to load from static list
//        $options->options = LenderRuleTypes::pluck('name', 'id'); # or this to load using model

        return view('voyager::formfields.select_dropdown', [
            'row'             => $row,
            'options'         => $options,
            'dataType'        => $dataType,
            'dataTypeContent' => $dataTypeContent,
        ]);
    }
}

```

**Comment by rjtubera** [comment]
hi @lee-van-oetz, can you explain further how to implement this? as I cannot find it on the docs

**Comment by fletch3555** [comment]
This has been closed for well over a year now and is for a much older version.  Please don't necro old issues.  Questions can be asked in slack
