### ISSUE TITLE
Table Columns Not Populated While Editing BREAD Relationships When voyager.prefix is set to ''

### ISSUE THREAD

**Issue by Funso-Popoola** [thedevdojo/voyager#1841]
- Laravel Version: 5.4.*
- Voyager Version: 1.0.0
- PHP Version: 7.1.*
- Database Driver & Version:
Mysql
### Description:
Due to a preference of the use of subdomain (e.g. admin.*) to prefix (e.g. site/admin), I set the voyager.prefix in voyager config to '' (empty string) and have done the same in my routes. So, my route(voyager.database.index), for instance, corresponds to '/database' and not '/admin/database' as default in voyager.

Because of the route change, the JS script that loads table columns from table while editing a relationship between BREADs tries reaching out to the wrong url: '/admin/database/{table_name}'

### Steps To Reproduce:
- Set the domain of your routes to 'admin' instead of using prefix 'admin'
- Set your 'prefix' in `config/voyager` to '' (empty string)
- Try adding a relationship to one of your BREADs

**Comment by fletch3555** [comment]
Odd... we shouldn't be using voyager.prefix anymore... Can you please try updating to the latest (v1.0.2) and test again?  If that still fails, please make sure you don't have a local copy of that view (under `resources/views/vendor`), or if you do, that it's updated appropriately.
