### ISSUE TITLE
No Allowance For `BelongsToMany` Pivot Table In Relationships Form Field

### ISSUE THREAD

**Issue by Funso-Popoola** [thedevdojo/voyager#1842]
- Laravel Version: 5.4.*
- Voyager Version: 1.0.0
- PHP Version: 7.1
- Database Driver & Version:
MySql
### Description:
The failure to pass in the pivot table registered with the `BelongsToMany` relationship while trying to browse, read or edit a data type with the said `BelongsToMany` relationship. This causes laravel to assume a pivot table which might not be correct, hence, an error.

### Steps To Reproduce:
- Create a `BelongsToMany` relationship that requires a pivot table for one of your DataTypes
- Try viewing the index of the DataType to browse the list of items

**Comment by Funso-Popoola** [comment]
I was able to fix this by overriding the `formfields/relationship.blade.php` view and changing the occurrences of this call

`$dataTypeContent->belongsToMany($options->model)`

under the `@elseif($options->type == 'belongsToMany')` check

to 

`$dataTypeContent->belongsToMany($options->model, $options->pivot_table)`

**Comment by Funso-Popoola** [comment]
I suppose this could be fixed with a PR, right? Or am I missing something?

**Comment by marktopper** [comment]
Solved in #1892
