### ISSUE TITLE
Can't create a Many to Many Relationship

### ISSUE THREAD

**Issue by marcio-machado-k** [thedevdojo/voyager#1843]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: 
Mysql 5.7.19

### Description:
Can't establish a Many to Many relationship using the interface.

### Steps To Reproduce:
1. Create the tables with the model option set to YES.
2. Create the breads.
When I go and try to create a BELONGS TO MANY relationship, I get:

"Model Class does not exist. Please create model, before creating the relationship."

What am I missing?

I can setup the schema and the models on a Many to Many relationship. 

Would that help?
Will Voyager know about this database and model setup? Or do I still need to create the relationship in Voyager?

Thank you so much.

**Comment by evrend** [comment]
You can watch this video. You must create model manually.
https://www.youtube.com/watch?v=gnSJ0Z2Fmso

**Comment by marcio-machado-k** [comment]
Brilliant! Thank you so much.

While I did had the Model created, I wasn't put in the namespace properly.
The video did should that I had to add App\ and that seems to work.

Now, when I click Browse Bread (to be able to add records) I get:

SQLSTATE[42S02]: Base table or view not found: 1146 Table
'uxkit.kit_elements' doesn't exist (SQL: select * from `kit_elements` order
by `created_at` desc)


Interesting, because, somehow, it seems to look for table 'kit_elements'
(with an s at the end), however, the table name is 'kit_element' (no s at
the end). I had a look into the code, here and there, and I don't find
where did I put that s.

Perhaps it's an easy and quick suspicion for you?

Of course, I reckon this is taking much of your time than what it should,
so it's ok, if you don't have the time to look specifically into my case.

Thank you, again, for your time.
Marcio

**Comment by marcio-machado-k** [comment]
I think I find it.
I'm fairly new to Laravel. And it seems to be a framework behaviour.

https://stackoverflow.com/questions/23943663/how-does-laravel-find-plural-of-models

Cheers,
Marcio

**Comment by marcio-machado-k** [comment]
Hm.
Now when I go to create, after the relationship is setup, I get the table name appearing twice...

> ...table or view not found: 1146 Table 'uxkit.kit_element_kit_element' 

"kit_element" appears twice.

**Comment by marcio-machado-k** [comment]
Found the issue.
Apparently, some name conventions should be in place.
You relationship table name should have a specific structure. And the same goes for their fields.

Would be nice to validate those, or, hint those somehow.

Thanks for the feedback @evrend .

Really appreciated. ;)

Cheers,
Marcio

**Comment by evrend** [comment]
@marcio-machado-k  you're welcome. :) You can change table name in your model file. Laravel can detect table name automatically but if you use laravel with other languages(not english), you must change it with hand.

> protected $table = 'my_special_table_name';

**Comment by fletch3555** [comment]
I couldn't (quickly) find the reference in the official docs, but I know it's there.  Instead I present to you this summary guide of [laravel best practices](http://www.laravelbestpractices.com).  I reference it all the time
