### ISSUE TITLE
can't see images from storage folder

### ISSUE THREAD

**Issue by abdulrahman19** [thedevdojo/voyager#1844]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7.19

### Description:
Can't see images from storage folder

### Steps To Reproduce:
just make new installation.
![screenshot from 2017-09-23 23-50-28](https://user-images.githubusercontent.com/22733622/30777441-d2214f00-a0ba-11e7-8e50-88efc31079c0.png)

**Comment by evrend** [comment]
Check your APP_URL parameter in .env file. 
``
APP_URL=http://127.0.0.1:8000
``

**Comment by evrend** [comment]
And make sure you can run the following code
``
php artisan storage:link
``

**Comment by abdulrahman19** [comment]
yes, sir 
working so fine now, thanks for your time <3

**Comment by evrend** [comment]
@abdulrahman19  You're welcome. :)
