### ISSUE TITLE
The file `resources/assets/js/slugify.js` is not include in `app.js`?

### ISSUE THREAD

**Issue by vanloc0301** [thedevdojo/voyager#1845]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.1.8
- Database Driver & Version: MySQL

### Description:

I have created a pull request for this file to fix error with the slug in Vietnamese country.

Link to pull request: https://github.com/the-control-group/voyager/pull/1699

I check in `webpack.mix.js` file, it using folder `publishable/assets/js` to generate `app.js` file.

I find on `app.js`, but don't have any a code I was committed.

Example:
have `this._map_latvian(),` at line 121. don't have the line `_map_vietnam()` at line 120.

Have any method to quick fix that? I updated for Voyager 0.9.x to 1..0.2. And lost my JS for to config for my language because Voyager using Mix to compile resource.

**Comment by fletch3555** [comment]
PR has been merged.  Please make sure to add a comment like "fix [issue number]" in the PR when opening it, so it will automatically close these related issues)
