### ISSUE TITLE
Unable to browse the bread

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#1846]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9

### Description:
I created a new bread but when I try to browse it, I get this error: http://prntscr.com/gox5wv . I already have created the model for that bread and slug is also ok. But still not able to browse. Please help urgent.

**Comment by davodavodavo3** [comment]
Need to generate permissions, go to roles admin and check Institute checkboxes

**Comment by MohsinNadeem** [comment]
Thanks Bro, Issue resolved.
