### ISSUE TITLE
Mark down editor does not work on the edit form

### ISSUE THREAD

**Issue by cristianmatos** [thedevdojo/voyager#1847]
- Laravel Version: 5.5
- Voyager Version: 1.0.0
- PHP Version:7.1
- Database Driver & Version: 5.1

### Description:
The markdown editor is not working on the edit form, it shows only a Textarea field.

### Steps To Reproduce:
1. Create a bread.
2. Set a field as Markdown.
3. Browse the bread and create a new registry, see that the markdown editor is shown.
4. Then, edit the registry and see that the markdown editor is not shown.

**Comment by cadmicro** [comment]
I have the exact same problem!

**Comment by nicolaszanghi** [comment]
Do you have any errors in the console ?
I had an error "Cannot read property 'addClass' of undefined" due to the created_at input. I remove this field from the edit view (in BREAD configuration) and the Markdown editor is shown now.

**Comment by marktopper** [comment]
I can confirm this is an issue, but only for the `posts` table since that has a custom `view`.
