### ISSUE TITLE
After updating bread 'Multiple images' field is empty

### ISSUE THREAD

**Issue by vshapovalov** [thedevdojo/voyager#1849]
- Laravel Version: 5.5.x-dev
- Voyager Version: dev-master 9919dec
- PHP Version: 7.1.7
- Database Driver & Version:

### Description:
I have bread 'products' with field 'images' of 'Multiple images' type.
we can set some images to field and save bread, it's ok. 
when i edit bread again and not set new images to field, after saving bread field is empty, 
because form input value is empty.

### Steps To Reproduce:

1. create bread with Multiple images field
2. create bread entity and set field value with some images
3. edit bread entity and not set new images to field, then save
4. check bread entity - field is empty

in case, when i add some new images in second step, it works(so merge is working)

**Comment by lucabartoli** [comment]
Same issue here.
I add that also adding an image in editing is ok.
Only if the file selection is empty, all previous images are lost.

**Comment by zolotykh** [comment]
Same issue too.

**Comment by ashrafmoselay** [comment]
To Fix this problem you should overwrite  function insertUpdateData in  VoyagerBreadController  Line 59

            if ($row->type == 'multiple_images' && !is_null($content)) {
                if (isset($data->{$row->field})) {
                    $ex_files = json_decode($data->{$row->field}, true);
                    if (!is_null($ex_files)) {
                        $content = json_encode(array_merge($ex_files, json_decode($content)));
                    }
                }
            }elseif ($row->type == 'multiple_images' && is_null($content)) {
            	$content = $data->{$row->field};
            }

**Comment by fletch3555** [comment]
@ashrafmoselay, we're open to Pull Requests

**Comment by darit** [comment]
looks like it's fixed with PR #2003

**Comment by Vishal-Deshpande** [comment]
Nope. #1867 did the trick. Now merged.
