### ISSUE TITLE
Is there a contribution guide / style guide ?

### ISSUE THREAD

**Issue by nacimux** [thedevdojo/voyager#1850]
- Laravel Version: 5.5
- Voyager Version: 1
- PHP Version: 7.0.11
- Database Driver & Version: 

### Description:

I would like to contribute to the Voyager project, but i dont find any contribution guide.

**Comment by fletch3555** [comment]
We're working on putting one together.  For now, you are free to ask questions as they come up.  The slack group is the easiest way to reach us.

We follow the usual github fork/branch/pull request workflow.  The purposes of the main branches(develop and master) is touched on in `Versioning.md`.  We would prefer discussion prior to implementation of large new features, mostly to save your time and effort.
