### ISSUE TITLE
unable to browse bread

### ISSUE THREAD

**Issue by kolep8** [thedevdojo/voyager#1851]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:
Cant open page (Browse BREAD) any database I create and convert to bread. Always receive error
"This action is unauthorized." on this link

**Comment by alexandru-core** [comment]
Did u go to Roles and add permisions for that database to admin user ?

**Comment by brai18** [comment]
Have the same problem. But i've already addedpermisions for that DB.
Only with one particular table...I have no idea...
Any suggest?

Thanks

**Comment by fletch3555** [comment]
@brai18, please open your own issue or ask in our Slack group for individualized assistance

**Comment by nille** [comment]
I'm experiencing the same issue. @kolep8 or @brai18  - did you solve it?

Edit: I solved it. My problem was that I added a back slash before the model name.

**Comment by sambornpen** [comment]
Hi,
I have problem the same when I try create bread with voyager.Who can help me.
