### ISSUE TITLE
User without any rights can no longer go to /admin

### ISSUE THREAD

**Issue by mace015** [thedevdojo/voyager#1852]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7.17

### Description:
When a user has NO rights to any of the modules, they are automatically redirected to '/'.
Because of this, this user can no longer logout + this is very confusing for a user.

### Steps To Reproduce:
Create a user with a role that has NO rights. Login as said user.

**Comment by fletch3555** [comment]
This is expected.  Voyager uses Laravel's built-in Auth scaffolding, so it should be the same auth (and therefore logout) functionality as your site.
