### ISSUE TITLE
voyager admin  relationship error 

### ISSUE THREAD

**Issue by 123payal** [thedevdojo/voyager#1856]
Error:  Update Failed generic.exception: Undefined index: relationship_key_user_belongsto_role_relationship

Also Display
![index](https://user-images.githubusercontent.com/31500639/30793554-754e9176-a1e0-11e7-8668-de737716d6e8.png)
 value is not visible

**Comment by fletch3555** [comment]
All fields are required (https://github.com/the-control-group/voyager/blob/master/ISSUE_TEMPLATE).  Please update the issue and we'll reopen this.
