### ISSUE TITLE
The images are broken

### ISSUE THREAD

**Issue by ezatla** [thedevdojo/voyager#1857]
- Laravel Version: 5.5
- Voyager Version: 1
- PHP Version:7

![capture](https://user-images.githubusercontent.com/23254048/30794633-39831962-a17e-11e7-8976-98adfd5fa6c1.JPG)

Hi I have recently installed Voyager and I run it on a server but the images are not loading any solution for this?

**Comment by evrend** [comment]
https://github.com/the-control-group/voyager/issues/1844 Plz check this issue. You can close this issue.
