### ISSUE TITLE
Voyager Does Not Exist

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1859]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: PhpMyAdmin

### Description:
i want to update the laravel voyager to 1.0.*
i insert the latest version inside my composer.json and run
```
composer update
```
but it show  D:\XAMPP\htdocs\pro1\vendor/tcg/voyager does not exist and could not be created.

**Comment by evrend** [comment]
This error is not voyager problem. You must run composer as administrator. Your error related to composer.

**Comment by fletch3555** [comment]
@evrend is likely correct. Please do as be suggested.
