### ISSUE TITLE
Bulk delete not working

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#1860]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.2
- PHP Version: 7.1.8
- Database Driver & Version: Maria DB 10.1

### Description:
Bulk delete doesn't work. It redirects to /admin/posts/0  which is an error 404. Also nothing is being deleted.

### Steps To Reproduce:
Just try to delete with bulk.

**Comment by vaggelis2018** [comment]
@fletch3555 it is not a bug. It was my fault. I am closing it and sorry for the wrong alarm.

**Comment by u01jmg3** [comment]
@vaggelis2018: what was your fix?

**Comment by vaggelis2018** [comment]
Sorry @u01jmg3 . It was not a fix it was my fault but i can't remember what was wrong. I think i had a custom view from an older version and this was the reason but i can't remember exactly.

**Comment by u01jmg3** [comment]
I have a custom BREAD and everything works except the bulk delete option - I get a 405 saying method not allowed. I am not sure what I am missing although I have been working with Voyager for a while now so would like to think I am reasonably familiar with how it works.

Thanks anyway
