### ISSUE TITLE
how can i export admin bread configurations made on my local machine to remote machine

### ISSUE THREAD

**Issue by mazeeblanke** [thedevdojo/voyager#1862]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
i have followed all the steps in the documentation and have successfully created breads for the neccessary tables but after pushing my project to the remote machine, i cant see those configurations anymore.

**Comment by alloyking** [comment]
mazeeblanke I think you make a valid point even if you do not understand why your configuration and bread no longer show up.

I see this was marked as Invalid and I'm sorta surprised as to why.  One of the amazing features built into Laravel is migrations.  I can work work locally, with a team, and push to production all while keeping the DB intact.  Why oh why does Voyager throw this functionality out the door?

**Comment by fletch3555** [comment]
This was marked invalid because there was no question or issue clearly identified, the version information was not provided, and it was closed the same day by the same user who opened it

**Comment by elgamine-dev** [comment]
If you stumble on this issue, there is a package to create seeders from the database : https://github.com/orangehill/iseed 
Hope it helps
