### ISSUE TITLE
BREAD creates singular table name but uses plural

### ISSUE THREAD

**Issue by kolep8** [thedevdojo/voyager#1864]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.1

### Description:
If I create table with singular name, I cant open it for browsing

### Steps To Reproduce:
Create new database with name "ket"
Add BREAD to it
open "/admin/ket"

you will get error "Base table or view not found: 1146 Table 'intr.kets' doesn't exist (SQL: select * from `kets` order by `created_at` desc)"

But in database its saved as "ket" not "kets"

**Comment by fletch3555** [comment]
https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions should answer your question.  If you create a table that doesn't follow Laravel conventions, you will need to modify the model class manually to make it work.

This is not a Voyager issue.

**Comment by AsyncPiMaker** [comment]
Would it be reasonable to add a flash warning about doing this? 
Or prevent poor naming unless you request a model file be created?
