### ISSUE TITLE
Relations does not show text in drop down

### ISSUE THREAD

**Issue by kolep8** [thedevdojo/voyager#1865]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.1

### Description:
Relation does not shows text in drop down.
I created table subusers, and added relation role_id like in dummy data users, but I dont see any text in drop down, I see that it has 2 items in drop down, but text is not displayed ( admin, user)

![issue1](https://user-images.githubusercontent.com/26900651/30828317-f1250e3c-a245-11e7-94eb-fe0632a69fa6.png)

**Comment by fletch3555** [comment]
My guess is that you created the relation incorrectly.  If this is still an issue, please let us know and we'll try to help you out.
