### ISSUE TITLE
When saving an entity containing a HasOne relationship, Voyager tries to write the related id into the wrong table. 

### ISSUE THREAD

**Issue by artifacts** [thedevdojo/voyager#1866]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.0
- PHP Version: 7.1
- Database Driver & Version: mysql, utf8mb4, utf8mb4_unicode_ci

### Description:

The entity cannot be saved since voyager is complaining about a missing field. That field is supposed to be looked up in the db table of the **related**, not the source object.

Example:

An **Event** has one **Agenda**. The agenda has a db column named **event_id**.

The Model classes are as follows:

**App\Event.php**
```
class Event extends Model
{
  public function agenda()
  {
    return $this->hasOne(Agenda::class);
  }
}
```

**App\Agenda.php**

```
class Agenda extends Model
{

  public function event()
  {
    return $this->belongsTo(Event::class);
  }

}
````

DB table for **agendas**:

<img width="1173" alt="screen shot 2017-09-25 at 22 32 10" src="https://user-images.githubusercontent.com/25325/30829567-6d65b0d2-a241-11e7-82f7-ddb991ac93dd.png">

DB table for **events**:
<img width="1176" alt="screen shot 2017-09-25 at 22 32 21" src="https://user-images.githubusercontent.com/25325/30829579-76e5ae1e-a241-11e7-9bdf-9de1358046f5.png">

The BREAD config of Event looks like this:

<img width="1150" alt="screen shot 2017-09-25 at 21 57 53" src="https://user-images.githubusercontent.com/25325/30828394-e6db246e-a23d-11e7-8062-4f5b90335229.png">

**Problem 1:**
No dropdown is rendered (see screenshot)

<img width="537" alt="screen shot 2017-09-25 at 22 26 17" src="https://user-images.githubusercontent.com/25325/30829244-9bb480a4-a240-11e7-9989-6bb173146416.png">

**Problem 2:**
When trying to create a new event, an error is thrown:

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'event_id' in 'field list' (SQL: insert into `events` (`title`, `event_id`, `updated_at`, `created_at`) v ▶"`

**Problem 3:**
The text describing the relation is wrong:

<img width="1150" alt="screen shot 2017-09-25 at 21 57 53" src="https://user-images.githubusercontent.com/25325/30829665-c03e9346-a241-11e7-8528-703f8aff49d6.png">

### Steps To Reproduce:

Extract and run the attached project. The DB dump is inside the app's root folder. It is populated with three _Agenda_ Entities. Go to _Events_ in the Menu on the left and try to create a new one.

**Expected result:** The Form renders a dropdown, allowing the user to select an _Agenda_.

**Actual result:** "Agenda 1" - the name of the first _Agenda_ Entity is rendered as plain text instead of a dropdown. When trying to save the _Event_ an Exception is thrown.

<img width="804" alt="screen shot 2017-09-25 at 22 27 13" src="https://user-images.githubusercontent.com/25325/30829302-b611a3aa-a240-11e7-8dc1-581799824eef.png">

**Test Project:**

[voyager-relations-test.zip](https://github.com/the-control-group/voyager/files/1330828/voyager-relations-test.zip)

**Comment by alonweinstein** [comment]
vendor/tcg/voyager/src/Http/Controllers/Controller.php:

change:

`          if ($row->type == 'relationship') {
                $row->field = @$options->column;
            }
`

to:
`
            if ($row->type == 'relationship') {
              if ($options->type == 'hasMany')  {
                break;
              } else {
                $row->field = @$options->column;
              }
            }
`

Skips hasMany relationship fields. Not sure if there's a use-case where some update actually needs to happen on the related rows.

**Comment by StevenKTurnerLuna** [comment]
Running into the same issue, currently setting up these relationships without Edit, Add and Delete options, which avoids the issue.

**Comment by webspilka** [comment]
@alonweinstein problem not in hasMany.
I and @artifacts have same problem with hasOne.
When add simple belongsTo - all works:
![belongsto](https://user-images.githubusercontent.com/1138069/32970783-0c168f3c-cbf3-11e7-9424-529157cd1109.png)

but if after that add hasOne:
![hasone](https://user-images.githubusercontent.com/1138069/32970845-4448553e-cbf3-11e7-91af-8cf7bb845d52.png)

After saving the user I get an error similar to the one above
```sql
Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id' in 'field list' 
(SQL: update `users` set `password` = XXXXXXXXX, `updated_at` = 2017-11-17 22:06:16,
 `user_id` = where `id` = 1)
```

**Comment by emptynick** [comment]
1 is just not supported, 3 was fixed in https://github.com/the-control-group/voyager/pull/2155.
If 2 is still a problem in the current Voyager version, please open a new issue as there were a lot fixes related to relationships.
