### ISSUE TITLE
relationship add/edit in edit-add.blade.php

### ISSUE THREAD

**Issue by longhuo** [thedevdojo/voyager#1868]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.4
- Database Driver & Version:

### Description:
Hi Guys,

First, thank you for provide this wonderful package.

I would like to ask for the usage of $options->relationship->editablePivotFields in relationship-edit-add.blade.php.

Can anyone provide a json example for editablePivotFields? and where to put the json block.

Thanks

**Comment by emptynick** [comment]
The reference to this file was removed in https://github.com/the-control-group/voyager/commit/a5dcc7c23ad65dcf0b2206b22f48e19f2664eee0#diff-36bd69ef7ba5df2912a70baf254a067bL182

Thats why I marked this as `fixes` in #2794
