### ISSUE TITLE
Duplicate entry 'test' for key 'menus_name_unique'

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#187]
If you go ahead and make a menu called `test`, and then create it once again.

Then it comes up with this exception page, however shouldn't it be a friendly error message instead saying that name is taken?

### Exception
```
QueryException in Connection.php line 769:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'test' for key 'menus_name_unique' (SQL: insert into `menus` (`name`, `updated_at`, `created_at`) values (test, 2016-11-22 08:05:04, 2016-11-22 08:05:04))
```
Made from `VoyagerBreadController.php line 254`

**Comment by handiwijoyo** [comment]
Fixed in #518
