### ISSUE TITLE
Tools Dropdown Menu doesn't show after installation

### ISSUE THREAD

**Issue by Kenneth058** [thedevdojo/voyager#1870]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version: 7.0.22
- Database Driver & Version: mysql 14.14

### Description:
After installing Voyager, the Tools Dropdown menu is not in the sidebar.

### Steps To Reproduce:
1. Install Voyager
2. Log in in the admin section.

**Comment by fletch3555** [comment]
Just pushed a fix for that in v1.0.4.  Please make sure you're on that version
