### ISSUE TITLE
bread browser  is not created  error , doing everything like in the video but it gives error . very strange but the error at the end of the s in the sql query.

### ISSUE THREAD

**Issue by sergeyBreslavets** [thedevdojo/voyager#1873]
- Laravel Version: 5.4
- Voyager Version: 1
- PHP Version: 7
- Database Driver & Version: MySQL

**Comment by fletch3555** [comment]
Please do not put the entire complaint in the title. It makes it very hard to read.  Also, you need to fill out the "steps to reproduce".  Including the actual error message is certainly not a bad idea either.

Once this has been updated, we'll reopen the issue.
