### ISSUE TITLE
Voyager en español | I can do material in Spanish, somebody interested? 

### ISSUE THREAD

**Issue by Mikisbell** [thedevdojo/voyager#1874]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- PHP Version: 7.1
- Database Driver & Version:

### Descripción:

With the little knowledge I have about voyager, I can do material in Spanish, somebody interested?
Con lo poco que aprendí sobre voyager en este tiempo  he aprendido algunas cosas que podría servirles me gustaría saber si hay hispanos que siguen esta hermosa herramienta. y poder compartir conocimientos

![captura](https://user-images.githubusercontent.com/6835999/30847091-d6ecaa6a-a25f-11e7-840a-fb1b8cb5d42f.PNG)

**Comment by davodavodavo3** [comment]
I think many people in the future will be intrested about Voyager, and Spanish language will be great idea if you can add PR

**Comment by fletch3555** [comment]
We don't already have spanish....? O.o

**Comment by davodavodavo3** [comment]
I did not even notice, it looks like we have,  @Mikisbell what kind of material you whant to do?

**Comment by davodavodavo3** [comment]
Material design, google?

**Comment by Mikisbell** [comment]
To start, video tutorials on installation, configuration, relationships, menus, basic things, since my English is not very good.

**Comment by davodavodavo3** [comment]
@fletch3555 ?

**Comment by roman08** [comment]
un hispano por aqui, que tal amigo, estoy un poco confundido con voyager no se como realizar una relacion muchos a muchos desde el panel... tendras información sobre el tema?... saludos...

**Comment by fletch3555** [comment]
@roman08,

Abre tu propio problema o únete a nuestro grupo Slack para recibir ayuda, por favor

**Comment by fletch3555** [comment]
@Mikisbell,

Ah, so you wish to make videos and such in the spanish language? Please feel free.  That's the benefit of an open source project.  Anyone can make a blog and post about whatever topics they would like.

**Comment by backendfirst** [comment]
Claro, muy interesado en tu aportación.
