### ISSUE TITLE
Media Manager not loading View after update

### ISSUE THREAD

**Issue by psmedia90** [thedevdojo/voyager#1876]
- Laravel Version: 5.4
- Voyager Version: 1.0.4
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I did a composer update to update to Voyager v1.0.4 from 1.0.2 and the media manager is not loading the view. the page only shows MEDIA on the page

### Steps To Reproduce:
1. run composer update
(updating Voyager version 1.0.4 from 1.0.2)
2. login to voyager
3. got to Media Manager 
(it will show the title of the page "MEDIA" put will not load the rest of the views)

![6](https://user-images.githubusercontent.com/2933523/30847384-35192a88-a250-11e7-9d38-2e2d9f6d0b1b.PNG)

**Comment by vaggelis2018** [comment]
Delete public/vendor and republish with 
php artisan vendor:publish --tag=voyager_assets --force
then 
php artisan view:clear
then ctrl+F5 to reload page

**Comment by fletch3555** [comment]
@psmedia90, I'm assuming this is the issue I was helping you with on slack last night.  Please see my comment there.  The `public` symlink you have at `storage/app/public/public` is broken and unnecessary, and is what's breaking the rendering of the page.  Please delete it and this should start working.

If that doesn't fix this, please report back and we'll reopen this.

**Comment by psmedia90** [comment]
@fletch3555 no that was not the issue from the last nite you fixed that one for me thank you

@vaggelis2018 that did the trick thank you

**Comment by fletch3555** [comment]
Okay cool. Glad you got it working

**Comment by dam62500** [comment]
J'ai le même problème, mais rien ne corrige mon problème.
![sans titre](https://user-images.githubusercontent.com/6084748/30907508-216eab76-a37b-11e7-95f0-aa283027bd42.png)

**Comment by ValerieYeltman** [comment]
@vaggelis2018 is there a way to run the artisan command to only update the media manager?

**Comment by vaggelis2018** [comment]
@ValerieYeltman I don't think that there is a command to do something like this. If you have custom css or js it is better to use another directory and declare it to voyager config file. This command is just to publish the assets that are shipped with voyager app and needed to be on public folder.

https://voyager.readme.io/v1.0/docs/additional-css-and-js-theming
