### ISSUE TITLE
[Feature request] Upload images via media manager

### ISSUE THREAD

**Issue by taiwanleaftea** [thedevdojo/voyager#1877]
Now when I add images in BREAD, the image is uploaded to the server, renamed and stored somewhere in month year folder. It's could be good for blogs or news sites, but not convenient in other cases.
I would suggest two features:
1. Add additional field option how and where store images.
2. Add the functionality to upload images via media manager.

**Comment by emptynick** [comment]
This will be possible in version 1.2.
See (https://github.com/the-control-group/voyager/pull/3889).
