### ISSUE TITLE
GD library is used instead of configured Imagic

### ISSUE THREAD

**Issue by Buenoru** [thedevdojo/voyager#1880]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- PHP Version: 7.1.9
- Database Driver & Version: postgresql 9.6

### Description:
when set "imagick" driver in config/image.php, adding image alerts:
> Whoopsie!
> GD Library extension not available with this PHP installation.

### Steps To Reproduce:
1. go admin panel
2. go Media
3. click "Upload"
4. add any image

### Solution
change 
`use Intervention\Image\ImageManagerStatic as Image;`
to
`use Intervention\Image\Facades\Image;`
in
vendor/tcg/voyager/src/Http/Controllers/VoyagerMediaController.php

**Comment by fletch3555** [comment]
@Buenoru, would you like to open a PR for this change? If not, I can do it myself.

**Comment by Buenoru** [comment]
As honesty, i don't have enough time and knowledge to make PR. So, it would be better if you did it.

PS. Forgot to say, that this case affects only if no GD lib installed. But whatever, it uses default instead confugured.
