### ISSUE TITLE
Blank page when you navigate to admin/media route

### ISSUE THREAD

**Issue by dukenst2006** [thedevdojo/voyager#1882]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- PHP Version: 7.1.5
- Database Driver & Version: MySQL 5.7.18

### Description:
Blank page when you navigate to admin/media route after fresh installation.
Considered the screenshot below !

![media_route](https://user-images.githubusercontent.com/7965394/30868085-47a10baa-a2a3-11e7-9846-59524bddd638.jpg)

### Steps To Reproduce:

**Comment by davodavodavo3** [comment]
Delete public/vendor and republish with
php artisan vendor:publish --tag=voyager_assets --force
then
php artisan view:clear
then ctrl+F5 to reload page

**Comment by fletch3555** [comment]
Same as #1876
