### ISSUE TITLE
Edit BREAD Relationship Issue

### ISSUE THREAD

**Issue by longhuo** [thedevdojo/voyager#1883]
- Laravel Version: 5.5
- Voyager Version: 1.0.4
- PHP Version: 7.1.4
- Database Driver & Version:

### Description:
Add mode
![popup_version](https://user-images.githubusercontent.com/16767005/30868299-3523a66e-a2ac-11e7-869c-eb78c9d6bcd3.png)
Edit Mode
![edit_version](https://user-images.githubusercontent.com/16767005/30868298-3505dee0-a2ac-11e7-878c-a8112c6c76f7.png)

When I try to edit the relationship, and the text description **always** says "Which column from the **User** is used to reference the Course". No Matter which Model you select.
It should be "Which column from the **Course** is used to reference the Lesson"

**Comment by 123payal** [comment]
This Issue only comes when we install in sub-directory. Pl recheck and let me know.

**Comment by emptynick** [comment]
This was fixed in https://github.com/the-control-group/voyager/pull/2155
