### ISSUE TITLE
Bread delete feature layout is broken when Server Side Processing

### ISSUE THREAD

**Issue by peyobr** [thedevdojo/voyager#1884]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.4
- PHP Version: 70.
- Database Driver & Version: Mysql 5.7.19

### Description:

Bread delete feature layout is broken when Server Side Processing

![screenshot at 2017-09-26 17-15-02](https://user-images.githubusercontent.com/7716146/30868655-8ab89c0a-a2df-11e7-8b3e-7ab366213ebf.png)

### Steps To Reproduce:

1) Create bread for users table with server side option

2) Try to delete a user

**Comment by davodavodavo3** [comment]
Confirm

**Comment by fletch3555** [comment]
What's the error you get?

**Comment by davodavodavo3** [comment]
It's a design issue ,not program

**Comment by emptynick** [comment]
This was fixed in https://github.com/the-control-group/voyager/pull/2801 and will be included in `1.1`
