### ISSUE TITLE
How to change the default title?

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#1887]
- Laravel Version: 5.5
- Voyager Version: dev
- PHP Version: 7.1

### Description:
Where is the dashboard's index page? I wants to change the default title "voyager" to my project's title. How can I do that?

**Comment by fletch3555** [comment]
The page title is managed by Voyager Settings (`/admin/settings`): https://github.com/the-control-group/voyager/blob/master/resources/views/master.blade.php#L4
