### ISSUE TITLE
Unable to load Voyager

### ISSUE THREAD

**Issue by henrydiazlds123** [thedevdojo/voyager#1888]
- Laravel Version: 5.5
- Voyager Version:1.0.4
- PHP Version:
- Database Driver & Version:

### Description:
I run a new laravle instalation and, after I installed Voyager.
Look like everything was right, but when I got to the control panel, the voyager logo just spin all time and never stop.
When inspecting the page, there is an error with jquery. Uncaught ReferenceError: $ is not defined?

**Comment by fletch3555** [comment]
You need to publish assets (`artisan vendor:publish --provider=VoyagerServiceProvider`)

**Comment by aqualaguna** [comment]
the compiled app.js and app.css does not contain the dependency hence the error popup.
its not compiled thoroughly btw here the import ::
berfore importing app.js at master.blade.php
```
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/perfect-scrollbar.jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/readmore.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.matchHeight-min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/bootstrap-toggle.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/ace/ace.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/ga-embed/moment.min.js')}}"></script>
<script src="{{ voyager_asset('js/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
```

and before app.css import::
`<link rel="stylesheet" href="{{ voyager_asset('lib/css/bootstrap.min.css') }}">`
