### ISSUE TITLE
Issue with the Admin menu being visible in the Menu Builder

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1894]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.4
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.7.11

### Description:

- I have two types of users setup in Voyager; an admin user and a normal user. The admin users sees everything. The normal user sees only the Dashboard, Pages and the Menu Builder. This is to allow a normal user to change the menu on their site by adding or removing pages.

  This is achieved with:

  ```php
  Permission::whereIn('table_name', ['menus', 'pages'])
            ->orWhere('key', 'browse_admin');
  ```

- The problem is as access is given to the Menu Builder, a normal user can see the builder for the 'admin' menu. This is obviously not ideal.
- Is there anyway of limiting the menus that can be seen in the Menu Builder?

**Comment by fletch3555** [comment]
@u01jmg3, I'm not sure what you're getting at with that code snippet.  Why aren't you just using permissions through the Voyager UI? Menu item visibility is already tied to that.

As for access to specific menus, you would need to override the controller and/or view and add a check there.  I recommend adding a new permission (i.e. `edit_admin_menu`), then adding a check with `$this->authorize('edit_admin', $menu)` (for controller) or `@can('edit_admin', $menu)` (for view).  As long as the permission ends with the BREAD `name` (as stored in the `data_types` table), it should work automatically.  Then you can just assign that permission to the "admin" role and not in the "user" role

**Comment by u01jmg3** [comment]
Thanks - got it working
