### ISSUE TITLE
Spinning Voyager Logo never Stop when accessing admin page

### ISSUE THREAD

**Issue by henrydiazlds123** [thedevdojo/voyager#1895]
- Laravel Version: 5.5
- Voyager Version: 1.0.4
-

### Description:
I installed a fresh copy of Laravel and Voyager. Everything was great, except when I try to login in, the only thing I see is the Voyager logo spinning. 

<img width="866" alt="screenshot 2017-09-27 at 9 46 39 pm" src="https://user-images.githubusercontent.com/7217533/30945906-d8cdf526-a3ce-11e7-85c5-b370a960e200.png">

### Steps To Reproduce:
Looks like we have a problem with jquery.

**Comment by fletch3555** [comment]
You need to republish assets.  Voyager now includes jquery in app.js, which is compiled with laravel mix.  You can do this with something along the line of `php artisan vendor:publish --force --provider=TCG/Voyager/VoyagerServiceProvider`

**Comment by samuelA1** [comment]
i tried everything but it doesn't work for me
