### ISSUE TITLE
Enable default value in Relationship Dropdown

### ISSUE THREAD

**Issue by ssatz** [thedevdojo/voyager#1897]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version: MYSQL

### Description:

How to Enable default value in Relationship? 
For Example in Category Model, Parent Id's default value is Null. 
If we want to create a category as a Parent category , how it should be done in relationship

**Comment by fletch3555** [comment]
This is not currently possible.  It has been requested numerous times since 1.0 was released.  We're open for suggestions if anyone wants to open a PR

**Comment by pontInformat** [comment]
I've resolved this bug. How can I upload the changes?

**Comment by fletch3555** [comment]
Submit a pull request @pontInformat

**Comment by tnylea** [comment]
@pontInformat I will create a video soon showing users how to do a PR, in the meantime if you wanted to post your solution here I can submit the PR 👍

**Comment by oliverquynh** [comment]
@tnylea 
With the "BelongsTo" relationship such as a product belongs to a user, I don't want to use a dropdown list of users to choose. I really want to match the authenticated user'id to the new product and never change it on updating. Is it possible now? I can't find a solution.

**Comment by tjmckenzie** [comment]
I noticed that when setting a BelongsTo relationship on a nullable/not-required field, it was impossible to set it as null. Have a small PR to solve this solution for my use case, but it may be able to be expanded to others.
https://github.com/the-control-group/voyager/pull/3170

**Comment by emptynick** [comment]
This will be possible with https://github.com/the-control-group/voyager/pull/3856 which will be released with v1.2.
Closing
