### ISSUE TITLE
Fix menu builder messages

### ISSUE THREAD

**Issue by viktormaar** [thedevdojo/voyager#1898]
Mistyped names in VoyagerMenuController.php
 `#34` -> voyager.menu_builder.successfully_deleted
 `#77` -> voyager.menu_builder.successfully_created
 `#105` -> voyager.menu_builder.successfully_updated

**Comment by fletch3555** [comment]
You're welcome to submit a PR for this.  Otherwise I'm sure someone else will get to it soon

**Comment by viktormaar** [comment]
#1927 PR pushed

**Comment by emptynick** [comment]
This was fixed in #1927
