### ISSUE TITLE
Admin media screen displaying blank. 

### ISSUE THREAD

**Issue by VictorAvelar** [thedevdojo/voyager#1902]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.3
- PHP Version: 7.1.17
- Database Driver & Version: mysql

### Description:
The page that is supposed to be shown when you visit the admin/media URL is displaying just blank screen.
### Steps To Reproduce:
- Fresh laravel installation using laravel lhomestead
- Require voyager
- install voyager with-dummy data
- Login -> click on media
- Here is where everything goes weird
- Install laravel debugbar
- This will allow you to see that in the beginning, everything works properly, but the 2 post ajax requests are triggered in the background.

![voyager-error-request1](https://user-images.githubusercontent.com/7926849/30987432-46457cf0-a497-11e7-9c8b-aa46e417fb69.png)
![voyager-ajax-request-1-route-view](https://user-images.githubusercontent.com/7926849/30987433-4648038a-a497-11e7-8654-9ef79da8923e.png)
![voyager-ajax-request-2-route-view](https://user-images.githubusercontent.com/7926849/30987431-46442b16-a497-11e7-97ad-ee62b4f5f27c.png)
![voyager-error-console-output](https://user-images.githubusercontent.com/7926849/30987430-464400f0-a497-11e7-9eca-8ce5925adb16.png)

**Comment by cadmicro** [comment]
It is also blank for me... the code is just saying

"MediaManager();"

**Comment by lablushah** [comment]
It is also blank for me

**Comment by vanloc0301** [comment]
I have same issues.

**Comment by Funso-Popoola** [comment]
Same issue here guys

**Comment by fletch3555** [comment]
Okay guys, we get it, it's a common issue for people.  I haven't been able to reproduce it yet, so I can't fix it without first figuring out what the issue is.  If anyone can provide that, we'd appreciate it.

**Comment by VictorAvelar** [comment]
I solved it by reinstalling voyager, perhaps that works for the others.

**Comment by lablushah** [comment]
Delete public/vendor and republish with
php artisan vendor:publish --tag=voyager_assets --force
then
php artisan view:clear
then ctrl+F5 to reload page

**Comment by fletch3555** [comment]
Perfect, thank you both for coming back and posting what you did to solve it.
