### ISSUE TITLE
 help please, how to generate reports of new views created?

### ISSUE THREAD

**Issue by Mikisbell** [thedevdojo/voyager#1904]
- Laravel Version: 5.5.12
- Voyager Version: 1.0.3
- PHP Version:
- Database Driver & Version:

### Description:

I hope you can help me, I need to modify and create PDF reports of the new views created

### Steps To Reproduce:
![captura de pantalla 18](https://user-images.githubusercontent.com/6835999/30994828-f25fc82c-a47b-11e7-81d8-29cd94d25752.png)

**Comment by fletch3555** [comment]
You're free to override the views and add this yourself.  I don't think Voyager needs this added in as core functionality.
