### ISSUE TITLE
Possible to show only the records login user 

### ISSUE THREAD

**Issue by 123payal** [thedevdojo/voyager#1905]
Laravel Version: Latest
Voyager Version: Latest
Database :postgresql

i  want them to see the record of only login user 

Is this possible with voyager or it calls for custom code?

Thanks

**Comment by VictorAvelar** [comment]
I'm assuming you're talking about posts.

```php
// App\Post model extends Voyager\Post model <- do whats needed

public function scopeOwned(Builder $query) {
    return $query->where(auth()->id(), '=', 'author_id');
}
```
Then in your controller or somewhere else you can do the following;

```php
$myPosts = Post::owned()->get();

return view('some.view', compact('myPosts'));
```

**Comment by 123payal** [comment]
Hello sir ,

I crated a custom bread i need to show only login user data in that


-

Regards

पायल
*Payal Jhamta *

Ls Multiplesystem Networks (P) Ltd

SCF-56  LEVEL-2  Phase-6 Mohali(Pb.)-IN


*Mobile: (+91) 7011753809*

**Comment by fletch3555** [comment]
@123payal, as I've told you on your other issues, all fields are required.  `Latest` is not a valid version number
