### ISSUE TITLE
Media Browser & Menu Builder problem with TokenMismatch and making the session expire

### ISSUE THREAD

**Issue by SamuelRiveraC** [thedevdojo/voyager#1909]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 5.6.20

### Description:
This is the problem, I'm assuming it is the Javascript.  The problem is that Media browser and Menu Builder if used in a fast manner, makes the session crash. Sorry if I don't explain myself, I'll try to be descriptive as possible.

For example, I'm in the Menu builder, I move the items many times, you can see the green notifications of operation made correctly, and when enough operations are reached or you reorder the menu fast since the last operation, the notifications stop to show off and the menu builder stops to work because the tokens mismatch and the session "crash" so if you refresh the website or you click another link,  the application makes you log in again. 

Same with Media browser, you enter and exit many times different folders and this error may happen again. I theorize that every action has/generates a CSRF, So if the user does an action faster than it generates, the session expires. I am probably wrong about this, but it's the only explanation I can imagine without looking the source code because of lack of time.

### Steps To Reproduce:
I believe the problem happens mostly in Menu Builder but it may happen in Media browser too
1 Enter Menu builder
2 Fastly move the menu items (do it in an erratically and very fast  manner to trigger it)
3 When the green notifications have stop showing, the problem should've triggered, so refresh the website and you will be logged out
Same with Media Browser
1 Enter Menu builder
2 Fastly enter in the folders and exit them, repetitively, This one is harder to trigger, maybe renaming some files fast can trigger it too.
3 The Media browser will freeze with the Ship's Wheel rotating, the problem should've triggered, so refresh the website and you will be logged out

Of course, I know I'm saying to do it erratically, but the problem can trigger anyways in a normal situation, this is the fast way to trigger it. I have done it in a cleanly installed project btw.  I annex an image 

Image 1 File about media crashing, the Ship wheel kept rotating and this is what the JS console was showing.
![image](https://user-images.githubusercontent.com/16765928/31017499-ade7feb4-a4f6-11e7-9bae-066d8d0ccea3.png)

Image 2 File about menu builder crashing, the operations stopped working
![image](https://user-images.githubusercontent.com/16765928/31017765-aa717d36-a4f7-11e7-8c84-846d8c9135f5.png)

**Comment by davodavodavo3** [comment]
Confirm issue on media manager in fastly enter in the folders

**Comment by SamuelRiveraC** [comment]
It seems that is a problem with AJAX requests and the session, somehow the AJAX requests are so fast in a local environment that makes the sessions expire, I really don't know how to look what is exactly causing this.

I only know that when the ajax request breaks the session it sends this Request:

```
URL:http://localhost:8000/admin/menus/1/order
Request Method:POST
**Status Code:302 Found**
Remote Address:127.0.0.1:8000
Referrer Policy:no-referrer-when-downgrade
Response Headers
**Location:http://localhost:8000/admin/login**
```

and when it does work fine it sends this:
```
URL:http://localhost:8000/admin/menus/1/order
Request Method:POST
**Status Code:200 OK**
Remote Address:127.0.0.1:8000
Referrer Policy:no-referrer-when-downgrade
Response Headers
```
so when the status code is 200, the response header location is not being sent

I will soon upload a webpage with Voyager and test it out

**Comment by emptynick** [comment]
This should be fixed in https://github.com/the-control-group/voyager/pull/3838
It waits until the current request is finished and only then allows to process a new one.
If it is not fixed please let us know so we can reopen it.
