### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#191]
It would be really nice if Voyager had multilingual support.

This however would require a lot of modifications in the current system:

- [ ] Language Switcher on front-end
- [x] Language Switcher on admin panel
- [ ] Enable/Disable Language Switcher from the front-end/admin panel
- [x] The current views should use language translations
- [ ] We should be able to select which languages can be used
- [x] Menu builder should support multilingual, in that way that it should be possible to add other strings/urls for different menu items
- [x] The current page system should support multilingual, in that way that the fields can be translated
- [ ] Configuration for defining language routes, some people might want the routes to be the same like (example.com/about-me should be the same url for all languages, however it translate the language according to a language set for that user somehow) or prefixed with the language code like (example.com/en/about-me and example.com/XX/about-me).
- [x] Categories should support multilingual for fields
- [x] Posts should support multilingual for fields

**Comment by setzer17** [comment]
I think we should wait for Laravel 5.4 because it will have better localization features:
http://themsaid.com/laravel-54-localization-json-20161117/

**Comment by marktopper** [comment]
@setzer17: Looks awesome! Let's wait for Laravel 5.4.

Then we can focus on something else until that.

**Comment by akazorg** [comment]
I will be implementing some of this topics on a project I'm working at the moment, I can share with you later.
I'll be using JSON data type for the translated fields. Do you like this approach?

**Comment by marktopper** [comment]
@akaZorg, you mean for the Eloquent?

**Comment by akazorg** [comment]
Yes, something like the guys from Spatie created: https://github.com/spatie/laravel-translatable.
Do you consider on using dependencies like this one?

**Comment by marktopper** [comment]
I think that the codebase may lay on that dependency. However only for developers using the translation system. So I think it should make a `translate: boolean` to the Voyager config, which leaves every bit of track that a translation system exists from the UI, and nether require that dependency. So users that wish to use translations can enable translations and add the dependency easy using `composer require spatie/laravel-translatable`.

**Comment by marktopper** [comment]
However that might not be 100% possible just like that, since the [package](https://github.com/spatie/laravel-translatable) uses a trait that have to be implemented.

Any ideas?

**Comment by akazorg** [comment]
I have no ideas about that trait, need to dive into it... I've been busy with other stuff, will catch you later.

**Comment by victorpierredev** [comment]
Laravel 5.4 is [officially released](https://laravel-news.com/laravel-5-4).

**Comment by Dpentest** [comment]
It is a good idea to support multilingual and im ready to contribute on that. I can translate to Arabic langauage when you are ready.

**Comment by marktopper** [comment]
Im currently working on making the BREAD translatable #561

**Comment by marcoocram** [comment]
+1

**Comment by lucacalcaterra** [comment]
+1

**Comment by jandever** [comment]
+1

**Comment by hojabbr** [comment]
I can contribute to the Persian (fa-ir) translation and also help in fully implementing RTL support for the UI. Please let me know when and how I could contribute on this.

**Comment by marktopper** [comment]
@hosseinhkj: Please join #789

**Comment by daimiao** [comment]
I can contribute to the Persian (zh_CN) translation

**Comment by daimiao** [comment]
'Admin Login' => '后台登陆',
    'Login' => '登陆',
    'Sign In' => '登陆',
    'Sign in below' => '登陆以下',
    'Logging in...' => '登陆中...',
    'The given credentials dont match with an user registered' => '给定的凭据与注册的用户不匹配',



    'dashboard' => '控制台',
    'media' => '媒体',
    'password' => '密码',
    'Logout' => '退出',
    'email address' => 'Email地址',
    'View All' => '显示全部',
    'You have' => '您有',
    'in your database. Click on button below to view all' => '在您的数据库. 点击下面按钮查看全部信息',
    'To view analytics you\'ll need to get a google analytics client id and add it to your settings for the key <code>google_analytics_client_id</code>. Get your key in your Google developer console:'
        => '要查看分析数据，您需要获取Google Analytics（分析）客户端ID，并将其添加到密钥<code> google_analytics_client_id </code>在设置中。 在Google开发人员控制台中取得您的密钥：',
    'Make sure to setup the appropriate relationship in the' => '确保在中设置适当的关系',
    'method of the' => '方法',
    'class' => '类',



    'Relationship' => '关系',
    'Custom' => '定制',



    'Add New' => '新建',
    'New' => '新建',
    'Cancel' => '取消',
    'View' => '查看',
    'Edit' => '编辑',
    'Delete' => '删除',
    'Rename' => '改名',
    'Viewing' => '显示',
    'published' => '发表',
    'draft' => '草稿',
    'pending' => '待定',

if someone need ，call me

**Comment by Fbahashwan** [comment]
Is there any new about languages ?

**Comment by Donny5300** [comment]
When you want Dutch support, feel free to message me!

**Comment by 4mon** [comment]
I can contribute to the Spanish LA (es_la) translation

**Comment by joefreire** [comment]
I can contribute to the Brazilian Portuguese translation (pt-br)

**Comment by faghihi** [comment]
I can help on persian (fa) language 
but I don't know exactly how to contribute

**Comment by mbdwey** [comment]
Hello @marktopper
Am using your package to generate admin panel for mobile API
and I will translate the admin panel to Arabic, Please share more information about contribution guidelines.
I will start merging i18n and feature/rtl-support and test or improve them.

**Comment by warlight** [comment]
Hi @marktopper
I can also translate it to Russian
@mbdwey how do you use Voyager admin for RTL? You also need menu in right, no?

**Comment by marktopper** [comment]
@warlight, wonderful, we already have the translation files for you to start on.

And we have the RTL branch with RTL support, however, there are still a few issues on it that we will have to resolve before it makes it into a release.

**Comment by marktopper** [comment]
@mbdwey Yes please test the RTL branch, I do not use RTL myself, so its hard for me to tell if everything is fine.

Also here you can see the English translation file: https://github.com/the-control-group/voyager/blob/master/publishable/lang/en/voyager.php

**Comment by warlight** [comment]
@marktopper I also can start translating to Hebrew. But I don't know it well) And I don't understand if everything is ok with RTL.


'Admin Login' => 'Войти под администратором',
'Login' => 'Войти',
'Sign In' => 'Зарегистрироваться',
'Sign in below' => '',//where can I find it?
'Logging in...' => 'Авторизация...',
'The given credentials dont match with an user registered' => 'Не верный логин или пароль',

'dashboard' => 'Панель управления',
'media' => 'Медиа',
'password' => 'Пароль',
'Logout' => 'Выйти',
'email address' => 'Email адрес',
'View All' => 'Все',
'You have' => 'У Вас',
'To view analytics you\'ll need to get a google analytics client id and add it to your settings for the key <code>google_analytics_client_id</code>. Get your key in your Google developer console:'
    => 'Чтобы подключить Google Analytics, Вам следует получить id клиента и добавить его в настройки для <code> google_analytics_client_id </code>. Получите ключ в панели разработчика Google',
'in your database. Click on button below to view all' => 'в вашей базе данных. Нажмите на кнопку внизу, чтобы увидеть все',
'Make sure to setup the appropriate relationship in the' => '',//where can I find it?
'method of the' => 'Метод',
'class' => 'Класс',

'Relationship' => 'Связь',
'Custom' => 'Особенный',//where can I find it?

'Add New' => 'Добавить',
'New' => 'Новый',
'Cancel' => 'Отмена',
'View' => 'Показать',
'Edit' => 'Редактировать',
'Delete' => 'Удалить',
'Rename' => 'Переименовать',
'Viewing' => '',//where can I find it?
'published' => 'Опубликовано',
'draft' => 'Черновик',
'pending' => '',//where can I find it?

**Comment by warlight** [comment]
@marktopper, you already have russian support)))
https://github.com/the-control-group/voyager/blob/master/publishable/lang/ru/voyager.php

**Comment by marktopper** [comment]
@warlight I see 😄

**Comment by GeorgeGhiottone** [comment]
Is possible to use the translations also for the file? For example save a audio guide for different languages. Thank you.

**Comment by akazorg** [comment]
@asolagmbh great point! 
Voyager doesn't support "file translation" and we should work on that. Please open an issue requesting this feature. Thanks.

This is easy to implemented.

**Comment by handiwijoyo** [comment]
Voyager `1.0` already support for multilangual

**Comment by gesticode** [comment]
Hello!
I can contribute with Spanish translation (es_ES).
Great package!!!! Thank you!

**Comment by amminvention** [comment]
can anyone tell me how to translate relationships in voyager??
