### ISSUE TITLE
add feature Recomendation dot env editor

### ISSUE THREAD

**Issue by aqualaguna** [thedevdojo/voyager#1912]
its very cool editing env file without using nano on terminal when server is in production mode.
also if it can do artisan command in voyager its amazing.
[https://ibb.co/d5oTDw](url)

**Comment by marktopper** [comment]
This is more suitable as a hook, since then people can just install that hook if they want the .env editor.

**Comment by fletch3555** [comment]
Production servers should be using system environment variables, not `.env` file(s).

I second @marktopper's suggestion to make this into a Hook instead of adding it to the core.
