### ISSUE TITLE
[pull request] change variable visibility in VoyagerMediaController

### ISSUE THREAD

**Issue by maktibab** [thedevdojo/voyager#1913]
- Laravel Version: 5.5.13
- Voyager Version: dev-master
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
Can you change some variable visibility in the VoyagerMediaController ("private" to "protected").
As we can extend this controller, i think it's important to access this variables from the child class.

`class VoyagerMediaController extends Controller
{
    protected $filesystem;
    protected $directory = '';
`

Do you agree?

**Comment by fletch3555** [comment]
You're welcome to make the change and open a pull request for it
