### ISSUE TITLE
Error on composer update from 1.0.2 to 1.0.4

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1914]
- Laravel Version: 5.5
- Voyager Version: 1.02
- PHP Version: 7

### Description:
I got an error when I try to run "composer update" from voyager 1.0.2 to 1.0.4

![schermata 2017-09-30 alle 17 43 57](https://user-images.githubusercontent.com/1073883/31047675-29033a00-a60f-11e7-8efb-56b90f6b2121.png)

**Comment by farookhridoy** [comment]
You can try this command .i think it's would be work........     ‘composer dump-autoload’

**Comment by reficul** [comment]
same error

**Comment by fletch3555** [comment]
@reficul, how is your database configured?

If sqlite, make sure the sqlite db file already exists and is writable by the user php is running as (likely something similar to `www-data` or `apache`.

If mysql, make sure it's set up correctly.  If PDO is unable to connect to the database, or can log in but the schema doesn't exist, it can give weird issues like this.

**Comment by reficul** [comment]
This issue is not resolved for me but it's something related to environment configuration (cpanel+composer).

**Comment by emptynick** [comment]
Closing as the issue seems unrelated to Voyager (?)
