### ISSUE TITLE
access create view getting error after create relationship 

### ISSUE THREAD

**Issue by seeyeong** [thedevdojo/voyager#1918]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.*
- PHP Version: 7.0
- Database Driver & Version: mysql

I getting error when go into create view , before I reference relationship everything is fine but after added relationship table the error prompt out, I try to check on the \vendor\tcg\voyager\resources\views\formfields\relationship.blade.php and I found the error come from 
app($options->model), please help thanks :)

I have do `composer update` to latest source

			@if(isset($view) && ($view == 'browse' || $view == 'read'))

				@php
					$relationshipData = (isset($data)) ? $data : $dataTypeContent;
					$model = app($options->model);
            		$query = $model::find($relationshipData->{$options->column});
            	@endphp

            	@if(isset($query))
					<p>{{ $query->{$options->label} }}</p>
				@else
					<p>No results</p>
				@endif

			@else

![image](https://user-images.githubusercontent.com/7313564/31054944-5fb19b24-a6ef-11e7-9d89-300312585fd0.png)

![image](https://user-images.githubusercontent.com/7313564/31054931-138beef2-a6ef-11e7-8657-1f29be73366f.png)

**Comment by fletch3555** [comment]
Your relationship needs to use the full model class path, not just the namespace.  If you change `App` to `App\Customer` (or whatever the namespace for that model is), it should work fine.  That's an issue with the field hint (currently `Namespace`), and we have another issue open to handle that.
