### ISSUE TITLE
Slack Chat?

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#192]
Should we create a slack chat for talking in general about this package?

__EDIT:__ A Slack Channel have been added. https://voyager-slack-invitation.herokuapp.com/

**Comment by akazorg** [comment]
Great idea, it would be awesome to chat with you.

**Comment by fletch3555** [comment]
Also interested!

**Comment by vanloc0301** [comment]
This package contains feature like `Query Builder, ` or `Database`  is awesome.

But this package contains many problems like:

  - SQL Injection
  - Broken UI
  - Bugs
  - Clean code (I read code in the package, it have any function not pretty).

Any feature like:
  - A REST API interface to communicate with front-end page or mobile application
  - Integration with Vue.js
  - An option to enable/disable function like `Query Builder`, `Database` in `Config` menu, etc.,...

I think this feature fascinating.
But I see future of this package will grow up to big package for a developer to create a custom admin.
I think @the-control-group should be continues developed with more time. I open graph of a commit in Github and found this project does not update regularly.

**Comment by marktopper** [comment]
@vanloc0301, this is not related to wether or not we should have a slack chat.

However, I have asked @tnylea if he needs help managing this package, since he is not on here as much as we would hope.

However the package is managede by a lot of active contributors.

Bugs is a normal part of the development game, and therefor we haven't even released a v1.x yet, still on a v0.x. Once we release a v1.x, you might see it more stable. The best you can do is to report them or even make a pull request to fix it.

A Rest API can be made quite easily, but should of-cause be a part of the Voyager system, optional however. I might work on this sometime soon.

The clean code problem will be fixed by contributors, however I personally prefer adding [StyleCI Automation](https://styleci.io/) to this package. So how about we all ping @tnylea, saying we want StyleCI Automation 😂

SQL Injections should not be a problem, however if you find a place that can be SQL injected, please let me know at mark@ulties.com and I will fix it right away.

Disabling functions can be easily done, and I might work on it soon. However I prefer the functions to be separated into components, so if you do not use ex. the `Menu Builder` you can completely remove it. Also requested at #147.

Vue is also requested at #195, but might need a quite bigger pull request in order to get fixed. However I hope it will come by.

**Comment by vanloc0301** [comment]
Good answered. 

Sorry about a problem of SQL Injection.

I follow[ this topic in Reddit](https://www.reddit.com/r/PHP/comments/5ae8qz/voyager_the_missing_laravel_admin/) since the week. At top comment, I saw his mention with many bugs relative SQL Injection. I found in Voyager repository and confirm that.

Currently, all SQL Injection removed. I find in all commit at the first time, but not found any commit like `fix SQL Injection`.

From @marktopper 👍 
> Disabling functions can be easily done, and I might work on it soon. However I prefer the functions to be separated into components, so if you do not use ex. the Menu Builder you can completely remove it. Also requested at #147.

**Comment by marktopper** [comment]
@vanloc0301: Then SQL injections they are talking about was from the old code and have already been fixed.

As you see the SQL injection was possible [here](https://github.com/the-control-group/voyager/blob/v0.9.1/src/Controllers/VoyagerDatabaseController.php#L93), however this was from the first version (v0.9.1) uploaded to Github by @tnylea 29 days ago, and we are now on v0.9.27 (26 versions later). As you can see the [issue have been fixed](https://github.com/the-control-group/voyager/blob/master/src/Controllers/VoyagerDatabaseController.php#L91) by contributors all over the world.

**Comment by handiwijoyo** [comment]
@marktopper there are still a lot work to do before we can release a v1.x. 

Yes, we need the discussion board to discuss about feature we want to add. We also need something like list of feature or milestone so we can keep it on track. If we have this list on hand, then ppl can contribute to work on it.

I got many feature i want to add, but i never know that i will be accepted or not, instead just blindly doing pull request.

**Comment by marktopper** [comment]
@handiwijoyo, there are many things that must be done before releasing v1.x.

However @tnylea haven't had the time to do that much maintaining of Voyager, luckily I just got granted access to help maintaining the project.
I will go through everything and try to get closed/merged every pull request and issue the next couple of days.
I will try to create a v1.x milestone here at Github which can be used to hold together all the many features that might be wanted, the issues that must be fixed and tests that must be written.
About the Slack chat, I have just added a link in the [readme](https://github.com/the-control-group/voyager/blob/master/README.md) to where you can signup, and I will be there to answer all of your questions, hopefully @tnylea will join as well when he got the time.

**Comment by marktopper** [comment]
Closing since this have been added.

**Comment by marktopper** [comment]
@handiwijoyo, just created the milestone for v1.x, still collecting the strings of issues and pull requests into it.

https://github.com/the-control-group/voyager/milestone/1
