### ISSUE TITLE
multiple bread for Single table / Condition in Browse data

### ISSUE THREAD

**Issue by sah-anshu** [thedevdojo/voyager#1926]
- Laravel Version: 5.5
- Voyager Version: 1.0.4
- PHP Version: 7.1
- Database Driver & Version: PGSQL

### Description:
Can we add multiple breads for SIngle DB table & Apply diff conditions for browse.  Sometime we need to show* some diff data from single table with some diff. conditions.

### Steps To Reproduce:
> MENU > Tools > Database

Anshu.

**Comment by akazorg** [comment]
Absolutely. I think this is missing too. I'm up for implementing it.

**Comment by robbydooo** [comment]
I believe I am having the same issue.

 Are you suggesting that you require different fields visible to different groups of users (admin, moderators or similar, etc) for the same table?

I would also need this for the edit view as well as browse. For example to approve a post would require admin vs non admin.

If so then its a plus 1 from me for this also.

Thanks,
Rob

**Comment by akazorg** [comment]
Hi @robbydooo, yes, that scenario is applied in here.

**Comment by robbydooo** [comment]
Excellent, let me know if I can be of use building this out.

**Comment by fletch3555** [comment]
For that scenario @robbydooo, I would strongly encourage you to create permissions and add them to the views.  Creating distinct but otherwise identical pages just to distinguish between roles feels like bad design to me.

**Comment by robbydooo** [comment]
@fletch3555 thanks for your advice, I am still familiarising myself with voyager. 

I agree it does sound overkill to have multiple breads for the same model just to show/hide different fields.

I am curious though, how would you create permissions for the ability to edit specific attributes in a model? 

It would feel like bad design to me to have to create a permission for every field that you want to show and hide to a given role.

Maybe the better way to do it would be to have views for each role? (Admin, moderator etc.).
If you have better suggesting I appreciate them.

Thanks,
Rob

**Comment by akazorg** [comment]
MultBREAD is not for dealing with permissions, but for having different views for the same table - this is impossible at the moment.

**Comment by fletch3555** [comment]
Yes, but I was responding directly to his question, which WAS about permissions.

**Comment by laraveladminpanel** [comment]
[Removed: advertising]

**Comment by fletch3555** [comment]
Respectfully, please do not advertise on our repo.

**Comment by akazorg** [comment]
LOL @fletch3555 **advertising**

**Comment by mko-tapptic** [comment]
No updates on this for 2 years? :/

**Comment by fletch3555** [comment]
Yes, because it's a feature request that were not ready to act on, and nobody from the community has submitted the feature either

**Comment by MrCrayon** [comment]
This feature will be available in V2
