### ISSUE TITLE
unable to browse bread

### ISSUE THREAD

**Issue by andrewxx** [thedevdojo/voyager#1928]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: PHP 5.6
- Database Driver & Version: MySQL 5.5

### Description:
unable to browse bread

### Steps To Reproduce:
1. Create database table
2. make model
3. add bread
4. Edit roles
5. try to browse bread

Got error
(1/1) HttpExceptionThis action is unauthorized.
--
in Handler.php (line 133)

Any idea?

**Comment by andrewxx** [comment]
Just try to repeat steps with Products described in Voyager Academy 7-8

**Comment by andrewxx** [comment]
Seems like a problem is in capital letter of model.

use 
class Product extends Model
instead
class product extends Model

**Comment by fletch3555** [comment]
@andrewxx, nice catch.  Did you create the model manually, or did Voyager create it for you?
