### ISSUE TITLE
Issue with using the file input type in a BREAD now that it is forced as multiple

### ISSUE THREAD

**Issue by u01jmg3** [thedevdojo/voyager#1930]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.4
- PHP Version: 5.6.31
- Database Driver & Version: MySQL 5.7.19

### Description:

- The view [`file.blade.php`](https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/file.blade.php#L10) has been updated to have the `name` suffixed with `[]` and set as accepting multiple files.
- However, the [JS validation](https://github.com/the-control-group/voyager/blob/master/resources/assets/js/app.js#L149) has not been updated to match this. This results in a JavaScript compilation error because, for example, when `name` is `example` it cannot be matched to `name=example[]` (addition of `[]`).
- There also seem to be other issues using the File input type now that it has been permanently set as accepting multiple files (error messages do not show, etc.).
  - When creating a BREAD, 'Images' and 'Multiple Images' exist as input types; should this not mean 'File' and 'Multiple Files' should exist as choices (rather than forcing the file input type to always be multiple)?

**Comment by u01jmg3** [comment]
This is still an issue and even more so now that the assets are pulled directly from the package.

Previously I could fix this issue by modifying my own version of the following file:

- [`resources\views\formfields\file.blade.php`](https://github.com/the-control-group/voyager/blob/1.2/resources/views/formfields/file.blade.php#L24)

```diff
- <input @if($row->required == 1 && !isset($dataTypeContent->{$row->field})) required @endif type="file" name="{{ $row->field }}[]" multiple="multiple">
+ <input @if($row->required == 1 && !isset($dataTypeContent->{$row->field})) required @endif type="file" name="{{ $row->field }}">
```

- Without this change uploading a valid `*.pdf` file against my custom BREAD field fails validation.
  - This is my data row:

```sql
INSERT INTO `data_rows` (`data_type_id`, `field`, `type`, `display_name`, `required`, `browse`, `read`, `edit`, `add`, `delete`, `details`, `order`) VALUES
(8, 'attachment', 'file', 'Attachment', 1, 1, 1, 1, 1, 1, '{"validation":{"rule":"required_without:_method|mimes:pdf","messages":{}}}', 4);
```

This is because I am unable to use `attachment.*` to cope with file data posted as an array (which is what `name="{{ $row->field }}[]" multiple="multiple"` causes).

**Comment by emptynick** [comment]
The JS validation stuff was removed completely, this shouldn't be a problem anymore.
Also, formfields are still overridable as before.

**Comment by u01jmg3** [comment]
> _The JS validation stuff was removed completely, this shouldn't be a problem anymore._

Yep, no longer having that specific issue but now my server-side validation (`mimes:pdf`) prevents a valid PDF from being uploaded due to the presence of `[]" multiple="multiple"`.

> _Also, formfields are still overridable as before._

Can you point me to the docs on how to do this or provide an example? I only wish to have a custom view for `file.blade.php`.

**Comment by emptynick** [comment]
https://laravel.com/docs/5.8/packages#views

**Comment by u01jmg3** [comment]
> _I only wish to have a custom view for `file.blade.php`._

Thanks. Am I correct in thinking I would need to have a copy of all the view files for Voyager in order to remove just `[]" multiple="multiple"` from `file.blade.php`?

Will Voyager ever support [the `.*` syntax](https://laravel.com/docs/5.8/validation#working-with-error-messages) in its custom validation (so that I could use `attachment.*` to cope with data posted as an array)?

**Comment by emptynick** [comment]
You just need to duplicate
`vendor/tcg/voyager/resources/views/formfields/file.blade.php`
to
`resources/views/vendor/voyager/formfields/file.blade.php`
and make your changes.
Validation rules just get passed to laravels native methods.
Is there any specific problem you have with wildcards/arrays?

**Comment by u01jmg3** [comment]
Thanks for that, worked perfectly.

The last thing I was struggling with achieving was:

```php
public static $rules = [
    'attachment.*' => 'required_without:_method|file|mimes:pdf',
];
```

This is my data row but it is missing the `.*` array syntax but I don't know how to incorporate it:

```sql
INSERT INTO `data_rows` (`data_type_id`, `field`, `type`, `display_name`, `required`, `browse`, `read`, `edit`, `add`, `delete`, `details`, `order`) VALUES
(8, 'attachment', 'file', 'Attachment', 1, 1, 1, 1, 1, 1, '{"validation":{"rule":"required_without:_method|mimes:pdf","messages":{}}}', 4);
```
