### ISSUE TITLE
symlink(): No such file or directory

### ISSUE THREAD

**Issue by gizburdt** [thedevdojo/voyager#1932]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.4
- PHP Version: 7.1.9
- Database Driver & Version: MariaDB 10.1.28 (latest homestead)

### Description:
I wanted to upload an avatar, but nothing happened. So I clicked the Fix it button on the dashboard, to fix it, but then I get this error: `symlink(): No such file or directory`

### Steps To Reproduce:
- Install Voyager and click "Fix it" on dashboard

**Comment by Codebreaker101** [comment]
Make sure your application has write access to /public directory. If it doesn't, run these commands:
`sudo chown -R www-data:www-data ./public`
`sudo chmod 755 ./public`

**Comment by gizburdt** [comment]
I get this for the first command: chown: www-data: illegal group name

**Comment by Codebreaker101** [comment]
On my Ubuntu server `www-data` is the webserver (apache2) user.  Change the \<user>:\<group> to apply to your system configuration. If you want you can exclude group from the command. 

EDIT: Now I see that you are using homestead. For that configuration is a bit different. You need to set permissions in your Vagrant configuration file. I haven't used Vagrant so wait until someone more knowledgeable comes.

**Comment by fletch3555** [comment]
I don't think it's a permissions issue.  Since homestead essentially mounts your project directory into the VM, it shares the file system with the host.  Please make sure you don't have anything (e.g. windows will create NTFS junctions which linux can't read) at the path `[project root]/public/storage` (i.e. `storage` should NOT exist).  If it does exist, just delete it, then try clicking "Fix it" again.

**Comment by gizburdt** [comment]
Thanks :)

**Comment by php-wmt-sujal** [comment]
try to delete existing storage symbolic link and then try `php artisan storage:link` command

**Comment by fletch3555** [comment]
@sujalpatel022, please don't comment on old closed issues. This one has been closed for months
