### ISSUE TITLE
How to make tag with Bread

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#1933]
- Laravel Version: 5.5
- Voyager Version: 1.0 *
- PHP Version: 7
- Database Driver & Version: PhpMyAdmin 4.7.0

### Description:
How to make a tag and inserting into the BREAD BUILDER?

**Comment by fletch3555** [comment]
I don't quite understand the question, but please watch the [Voyager Academy](https://laravelvoyager.com/academy/) videos and read through the documentation.
