### ISSUE TITLE
 Array to string conversion in bread post.

### ISSUE THREAD

**Issue by chrisifm** [thedevdojo/voyager#1936]
- Laravel Version: 5.5.14
- Voyager Version: ^1.0
- PHP Version:7.1.8
- Database Driver & Version: 10.2.9-MariaDB

### Description:
When the store sends an error. Array to string conversion. In the bread of post.

### Steps To Reproduce:

When a column is added to the bread "post" type "tags">"longtext" and is assigned a "select multiple" with a json field example:

```
{
    "default": "MA",
    "options": {
        "MA": "Marketing",
        "DE": "Desarrollo",
        "CU": "Cuentas"
    }
}
```
<img width="1653" alt="captura de pantalla 2017-10-05 a la s 01 04 34" src="https://user-images.githubusercontent.com/1562002/31212931-3ea912b4-a969-11e7-995b-905035eb4e5b.png">

And then you edit any post.

**Comment by Banquo1** [comment]
Got the same error.

**Comment by fletch3555** [comment]
Please provide the full stacktrace.

**Comment by ghost** [comment]
I had the same problem with manually created MySQL tables. When I created tables via Voyager admin panel, everything works fine.

**Comment by neverfan** [comment]
I think this connected with that cause https://github.com/the-control-group/voyager/issues/2207
