### ISSUE TITLE
Unable to detect application namespace for dimmers.blade.php

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#1938]
- Laravel Version: 5.4.30
- Voyager Version: 1.0.5
- PHP Version: 7.0
- Database Driver & Version: 5.7.14

### Description: 
Unable to detect application namespace for 

> vendor\tcg\voyager\resources\views\dimmers.blade.php

### Steps To Reproduce:
 I finished the installation, I get this error when I login to admin panel
<img src="https://i.hizliresim.com/nJmdzg.png">

**Comment by fletch3555** [comment]
Please provide the full stacktrace.
