### ISSUE TITLE
Unable to login from other user except admin 

### ISSUE THREAD

**Issue by sawattoo** [thedevdojo/voyager#1939]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Unable to login from other user except admin 

### Steps To Reproduce:
1-Sign in from admin account
2-create a user
3-logout from admin account
4-sign in with new created user
5- unable to login ( page not found error)

**Comment by jrgmonsalve** [comment]
You need assign permission the read in the user role for the menu

**Comment by sawattoo** [comment]
yes i already done it. in menu i select some features which i wanna show on user. but. unfortunately....

**Comment by fletch3555** [comment]
The only requirement to log into Voyager is that the user's Role must have the `browse_admin` permission
