### ISSUE TITLE
Tinker automatically quits after fresh installation

### ISSUE THREAD

**Issue by peterson-umoke** [thedevdojo/voyager#1940]
- Laravel Version: 5.5
- Voyager Version: 1.0.0
- PHP Version:7.1.9
- Database Driver & Version:
mysql
### Description:
Tinker automatically quits and displays a ctrl + d, can't use tinker

### Steps To Reproduce:
simply install a new laravel installation file
install voyager
run php artisan voyager:install

**Comment by peterson-umoke** [comment]
after installing this about five times, if i run php artisan tinker, it will able abort, please i need help with this.

**Comment by fletch3555** [comment]
It is very unlikely that this is an issue with Voyager.  You would have better luck seeking support through a more generic laravel medium, such as the laracasts forum or larachat slack group

**Comment by peterson-umoke** [comment]
i dont suppose so, cause this only happened AFTER I installed voyager

**Comment by peterson-umoke** [comment]
closed the-control-group/voyager#1940

**Comment by fletch3555** [comment]
@peterson-umoke, I'm assuming your comment was intended to close this issue?

**Comment by peterson-umoke** [comment]
yes
