### ISSUE TITLE
Multiple Image and Thumbnail Options -> Disvision by Zero Error

### ISSUE THREAD

**Issue by Banquo1** [thedevdojo/voyager#1941]
- Laravel Version: 5.5
- Voyager Version: 1
- PHP Version: 7
- Database Driver & Version:

### Description:
After saving Bread you get a Division by Zero Error from Intervention Plugin

### Steps To Reproduce:
Set Field Type to multiple image AND add options field like this:
`{
    "resize": {
        "width": "1000",
        "height": "null"
    },
    "quality": "70%",
    "upsize": true,
    "thumbnails": [
        {
            "name": "medium",
            "scale": "50%"
        },
        {
            "name": "small",
            "scale": "25%"
        },
        {
            "name": "cropped",
            "crop": {
                "width": "300",
                "height": "250"
            }
        }
    ]
}
`

Shouldn't the Controller Part in row 225 be the same as for the single Image (check for NULL Value)?

**Comment by fletch3555** [comment]
> Shouldn't the Controller Part in row 225 be the same as for the single Image (check for NULL Value)?

This question doesn't make any sense, as you haven't referenced any code or said what "row 225" is.

**Comment by Banquo1** [comment]
Oh, sorry, youre right. Here the code that  I refer to:
 voyager/src/Http/Controllers/Controller.php

Single Image Thumbnail creation checks resize width/height also as null-String, multiple not.

>/** SINGLE MAGE**
>if ($thumb_resize_width != null && $thumb_resize_width != 'null') {
> $thumb_resize_width = intval($thumb_resize_width * $scale);
>}
>
>if ($thumb_resize_height != null && $thumb_resize_height != 'null') {
>  $thumb_resize_height = intval($thumb_resize_height * $scale);
>}
>		
>/** MULTIPLE **/
>if ($thumb_resize_width != null ) {
>   $thumb_resize_width = intval($thumb_resize_width * $scale);
>}
>if ($thumb_resize_height != null) {
>  $thumb_resize_height = intval($thumb_resize_height * $scale);
>}

**Comment by lfbittencourt** [comment]
Maybe it's something related to that `"height": "null"` part. Try removing the quotes around the value.

**Comment by fletch3555** [comment]
Agreed, the quotes definitely shouldn't be there.  I feel like someone "fixed" the single image code so it will handle the quoted null value instead of fixing the quoted null value.

**Comment by cyrildewit** [comment]
@Banquo1 do you still encounter this issue?

**Comment by fletch3555** [comment]
This has gone unreported by anyone else for 6 months now, so I think it got fixed, though I can't state where exactly.  If this is still an problem, please open a new issue with updated information.

**Comment by sineld** [comment]
> Maybe it's something related to that `"height": "null"` part. Try removing the quotes around the value.

Absolutely. Worked for me. Thanks.
