### ISSUE TITLE
Default directory voyager media

### ISSUE THREAD

**Issue by yoan1005** [thedevdojo/voyager#1942]
hi, 
My question is simple,how can i change the default directory in voyager media ?
by default when we arrive on media page, we see the public/storage folder content, it's possible to by default to show public/storage/galery ?

Thank you

**Comment by Eliepse** [comment]
Hoy !

By default, the media point to Laravel's "public" disk, which leads to `/storage/app/public/`. You can change the root folder by doing the following:

1. Create a new disk inside `config/filesystems.php` with the wanted path.
2. Change disk name into `config/voyager.php`

I don't know if it's what you want !
Do you need to have the possibility to go the parent directory of your "galery" folder ?
