### ISSUE TITLE
Media Manager different behaviour from Post/Page upload

### ISSUE THREAD

**Issue by calder12** [thedevdojo/voyager#1944]
- Laravel Version: 1.0.5
- Voyager Version: 5.5.14
- PHP Version: 7.1.7
- Database Driver & Version: postgres 9.5.7

### Description:
Uploading a .jpg that is originally 1,749kb  coverts the file to a .jpeg that is now 3,958kb 

This is counter intuitive for a media manager. Why is it changing the file type? Why is it making the file larger rather than applying some sort of compression? Is there a way I can modify this behaviour?

Question 2 - Why are you hashing the file name? File names matter for SEO, I understand I can change it afterwards, but again, counter intuitive and something I'd have to train my users to do. 

This only happens when working with the Media Manager upload itself. Uploading via a Post or Page significantly reduces the image size and does not change the file name.

### Steps To Reproduce:

Upload a .jpg file through the Media Manager (not through a Post or Page interface)

**Comment by emptynick** [comment]
This will be possible in version 1.2.
See (https://github.com/the-control-group/voyager/pull/3889).
