### ISSUE TITLE
Customizing tinyMce under Voyager 1.x

### ISSUE THREAD

**Issue by sysmesh** [thedevdojo/voyager#1945]
- Laravel Version: 5.5.1
- Voyager Version: 1.1.0
- PHP Version: 7.1.9
- Database Driver & Version:

### Description:
I am trying to change the tinyMce init settings as I need some stuff added to it.
I've copied the voyager_tinymce.js from the vendor folder to: public/vendor/tcg/voyager/assets/js/voyager_tinymce.js
I've applied changes and cleared the cache+views yet I'm not seeing any change in the actual text editor on the admin.
I even tried editing the original file location under /vendor/tcg/voyager.... with no effect.

Do I need to run/clear something else to see the changes?
How do I apply my own init settings to the Voyager rich text editor?
(read the docs but found no information on how to do this).

**Comment by calder12** [comment]
Did you try running `composer dump-autoload` ?

**Comment by sysmesh** [comment]
Hi, thanks for helping.
Yes - I just gave it a try now but it still fails to show the changes.
Maybe I'm not doing them in the right file location?

**Comment by jwheat** [comment]
When I did this last week, I edited the original file (which is causing issues with my versioning deployments, but that's a different issue)

`/vendor/tcg/voyager/publishable/assets/js/voyager_tinymce.js`

- I added paste to the plugins line 19 like this:

`plugins: 'link, paste, image, code, youtube, giphy, table, textcolor',`

- I added paste to the toolbar line

`toolbar: 'styleselect paste bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table youtube giphy | code',`

- at the bottom I added a , after the image_title setting and then added paste_word_valied_elements

```
    image_title: true,
    paste_word_valid_elements: "p,b,strong,i,em,u,h1,h2,h3,h4,ol,ul,li"
```


to keep some Word formatting

If any of the syntax is incorrect it won't work.

To check to see if its actually updated the file and isn't cached, view the script source on the page it should be working on -

view-source:http://[yourdoman]/vendor/tcg/voyager/assets/js/voyager_tinymce.js 

You should see your changes.

**Comment by sysmesh** [comment]
Thanks!
So I took a look and it seems there's no such js under: /vendor/tcg/voyager/publishable/assets/js/voyager_tinymce.js in laravel 5.5 

Your advice did help as I did find out that the editor loads /vendor/tcg/voyager/js/app.js which holds the compressed init call.
What I did is I switch the compressed init call with my own custom one (not compressed) and now it seems to be loading it.
A bit of a strange solution but seems to work (for now).

**Comment by jwheat** [comment]
Thanks back @sysmesh! 
I didn't realize I could place the changes in public/vendor/tcg/voyager/assets/js/voyager_tinymce.js, so I did and now my versioned deploy works every time.

I'll have to update eventually to 5.5 and latest Voyager, but for the time being its all working quite well.

**Comment by fletch3555** [comment]
@sysmesh / @jwheat.  Is this issue resolved? Can we close it?

**Comment by sysmesh** [comment]
On Laravel 5.5 it's still not resolved (for me anyway) as placing a modified file under: /vendor/tcg/voyager/publishable/assets/js/voyager_tinymce.js  does NOT seem to do the trick.

I am forced to edit the app.js file (which is uglified) manually. 
I'd love to know the formal way of doing it properly.

**Comment by apsg** [comment]
I have exactly the same problem. I even tried to extend existing editors using tinymce.AddonManager, but with no luck.

**Comment by abhinavverma** [comment]
Any solution to above issue ? i need to add quite a few plugins to TinyMCE editor.

**Comment by apsg** [comment]
@fletch3555 any progress on this issue?

**Comment by heyhihellobro** [comment]
You can try this. Its exactly what I did with my project:

1. open voyager vendor folder `/vendor/tcg/voyager` & run `npm update`
2. change tinyMCE settings in `/vendor/tcg/voyager/resources/assets/js/voyager_tinymce.js`
3. run `npm run production`

After compiling everything into `/publishable` folder you have to vendor:publish this.

4. so just open the root folder of your laravel application and run `php artisan vendor:publish`

Hope this will help you.

**Comment by niels-numbers** [comment]
I also made the changes inside the compressed code of the `app.js` file but its really tricky and annoying to make changes:

![image](https://user-images.githubusercontent.com/1765602/37566779-faaa6514-2abd-11e8-8519-d6e4ce27c334.png)

Also I have another problem, that he cannot find the initial plugin.js if I add something:

![image](https://user-images.githubusercontent.com/1765602/37566792-158cdf88-2abe-11e8-9408-c22a531496b3.png)

This is because he is looking for `plugin.js` but in the folder is only the file `plugin_min.js` so I have to rename it in order to get it working.. A bit strange

![image](https://user-images.githubusercontent.com/1765602/37566796-36769324-2abe-11e8-8609-4e458c36960c.png)

**Comment by apsg** [comment]
@iwasherefirst2 I had similar problem - you need to navigate to the directory and change the plugin's filename from `plugin.min.js` to `plugin.js`.

But still, it's not the elegant solution

**Comment by ux-engineer** [comment]
Could someone make TinyMCE editor configurable directly from Voyager config file, please? :) There seem to be many people needing this.

It's a real problem with sites that are having many people as editors, that these text processor apps like Word paste ugly code which breaks content styling.

**Comment by juliencap** [comment]
I agree, it should be great to customize that (maybe in Parameters front)?
On my side, I look to change the space 

`<p>&nbsp</p> with <br />` to not have empty paragraph and also margins on that.

Params like this I mean: https://www.tinymce.com/docs-3x/reference/configuration/Configuration3x@force_br_newlines/

I thought to a json possibility too (on bread json | on Rich Text Box), but we will have to repeat this parameters every time.

I hope some news here :)

**Comment by ranjitWBS** [comment]
I tried this: `php artisan vendor:publish --tag=voyager_assets --force` but it is only doing this: `Copied Directory [\vendor\tcg\voyager\publishable\assets] To [\public\vendor\tcg
\voyager\assets]` But I have made changes in this:`\vendor\tcg\voyager\resources\assets\js\voyager_tinymce.js`
How do we publish and minify `resources\assets` to `publishable\assets` ?

**Comment by fletch3555** [comment]
Don't change files under vendor...

**Comment by romanzpolski** [comment]
yes this is quite a pain, adding bootstrap class to img in edit screen has to happen manually.
Cant be fixed by tinymice.init to add/pick class on element creation.
Only with dirty tricks, like changing compiled app.js file....

Did any one has a solution for this ?
if so please share.

**Comment by emptynick** [comment]
It is now possible to customize TinyMCE with Voyager `1.1.x` 
https://voyager.readme.io/docs/tinymce

**Comment by juliencap** [comment]
Hello, great news to see we can customize that, thanks! I am looking the way to customize the "tinymce.init" things adding browser_spellcheck option for example or remove empty <p> can someone help me please? 

I had a look on the [doc](https://www.tinymce.com/docs/api/tinymce/tinymce.editor/) and I can use this for example:
tinymce.activeEditor.dom.addClass(tinymce.activeEditor.dom.select('p'), 'someclass');

but I didnt find a way to customize the init part.

Cheers!

**Comment by jetrodn** [comment]
@juliencap I had the same issue. I tried to use `tinymce_init_callback` function and all the methods available for `tinymce.Editor` but hasn't found any good solution to change init settings. 

You can try another way I did. I needed to customize init settings for `textarea` on Posts page. I did following:
- I created [(overrided view)](https://voyager.readme.io/docs/overriding-views) `resources/views/vendor/voyager/posts/edit-add.blade.php` file and copied code from here: [edit-add.blade.php](https://github.com/the-control-group/voyager/blob/1.1/resources/views/posts/edit-add.blade.php) 
- At the bottom inside `<script></script>` section you can call `tinymce.init({ //your custom settings });` (copy the original `tinymce.init()` [tinyMCE voyager settings](https://github.com/the-control-group/voyager/blob/1.1/resources/assets/js/voyager_tinymce.js) and edit in the way you need)

I am not sure how accurate my way is, but it worked for me.

**Comment by juliencap** [comment]
@heyhihellobro thanks, I will try that solution, good way until new updates here!

**Comment by niels-numbers** [comment]
@emptynick should this issue maybe get reopend? As far as I see it, its not possible to add a plugin with `tinymce_init_callback`. So if you want to add a plugin to TinyMCE, and I guess thats what most people here want to do, then you still have to modify the minified app.js.

**Comment by emptynick** [comment]
Nope.
You can try https://github.com/the-control-group/voyager/pull/3145 until it gets merged.

**Comment by ghost** [comment]
This is my solution:

```
function tinymce_init_callback(editor)
{
      editor.remove();
      editor = null;

      tinymce.init({
        selector: 'textarea.richTextBox',
        skin: 'voyager',
        min_height: 600,
        resize: 'vertical',
        plugins: 'print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor insertdatetime advlist lists textcolor wordcount imagetools contextmenu colorpicker textpattern',
        extended_valid_elements: 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
        file_browser_callback: function (field_name, url, type, win) {
            if (type == 'image') {
                $('#upload_file').trigger('click');
            }
        },
        toolbar: 'styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table youtube giphy | codesample code',
        convert_urls: false,
        image_caption: true,
        image_title: true
    });
}
```
First I remove the existing instance of TinyMce editor, created by Voyager and later I create a new one with the plugins and parameters I want. 

When the page loads and the new instance is created, TinyMce searches for plugins in 'public/vendor/tcg/voyager/assets/js/plugins'. TinyMce searches plugin js file by name 'plugin.js' but many of these plugin files are named 'plugin.min.js', this causes many error that disables the editor. One solution for this inconvenience is to rename all the plugin files to 'plugin.js'.

**Comment by tonnikrava** [comment]
Thanks decimvs - this is the only thing that helped

I took and simply turned off the TinyMCE editor by creating a file, as recommended by the fresh documentation for the Voyager

https://voyager.readme.io/docs/tinymce

function tinymce_init_callback(editor)
{
    editor.remove();
    editor = null;
}

**Comment by phantom8805** [comment]
The onchange_callback setting (3.x branch) seems to have been removed.

This is my solution:
override view https://voyager.readme.io/docs/overriding-views
formfields\rich_text_box.blade.php change class name example:  from richTextBox to richTextBoxCustom.
add you custom js to config:
https://voyager.readme.io/docs/additional-css-and-js-theming
example:  richTextBoxCustom.js
end in your js file init TinyMCE as you with.
https://www.tiny.cloud/docs/configure/editor-appearance/
example: 
`$(document).ready(function () {
    tinymce.init({
        selector: 'textarea.richTextBoxCustom',
        skin: 'voyager',
        min_height: 600,
        resize: 'vertical',
        plugins: 'link, image, code, youtube, giphy, table, textcolor, lists',
        extended_valid_elements: 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
        file_browser_callback: function (field_name, url, type, win) {
            if (type === 'image') {
                $('#upload_file').trigger('click');
            }
        },
        toolbar: 'styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table youtube giphy | code | fontsizeselect | fontselect',
        convert_urls: false,
        image_caption: true,
        image_title: true
    });
});`

**Comment by trippo** [comment]
You can also include the plugins urls on voyager additional_js
