### ISSUE TITLE
Artisan command not working 

### ISSUE THREAD

**Issue by nanadjei** [thedevdojo/voyager#1947]
After executing `php artisan down` form the compass `php artisan up` does not work.  Still get *Be right back*.

**Comment by davodavodavo3** [comment]
@nanadjei2 you want to bring alive application from compass?
Or you run php artisan up from console and it doesnt remove down file from Laravel storage path?

**Comment by nanadjei** [comment]
@davodavodavo3 I wanted to bring the app alive from compass but it did not work until I run `php artisan up`  from the terminal.

**Comment by fletch3555** [comment]
That actually makes sense, since Voyager is part of the application you just took down... We'll need to find a way to allow it anyway, provide some kind of notification to users, or just remove those commands from Compass... @tnylea, any thoughts?

**Comment by fletch3555** [comment]
Closing due to age and because this is behaving as expected.
