### ISSUE TITLE
Modal wrong action routing

### ISSUE THREAD

**Issue by ivanmaxlogiudice** [thedevdojo/voyager#1949]
https://github.com/the-control-group/voyager/blob/0b11c4c09d494ca72497ec0fc2e66dd21fa457d6/resources/views/menus/browse.blade.php#L111

Should be:
```
$('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.index') }}/' + id;
```

Because if not, it's appending the id of the menu constantly.

Steps:
1) Click delete in any menu
2) Click cancel on the modal.
3) Click delete in the same menu or any other.

Result, sometime like that: http://voyager.dev/admin/menus/3/1/3

**Comment by Gennnji** [comment]
I'll try!

**Comment by sidis405** [comment]
Pr submitted.
