### ISSUE TITLE
[Feature] Ship with Vue2 

### ISSUE THREAD

**Issue by joshuaajones** [thedevdojo/voyager#195]
Since Voyager is "made for Laravel 5.3" and L5.3 ships with Vue2, can we get Voyager to ship with Vue2 implementation - to avoid code conflicts and keep folks from having to learn both versions?

**Comment by marktopper** [comment]
That might be quite a big project to do, however I am open to pull requests.

**Comment by fletch3555** [comment]
I'm going to close this for now since it's so old.  We already have a few features that have been rewritten in VueJS.  We may revisit this after the 1.0 release.  In the meantime, if anyone wants to tackle it, we're certainly open to pull requests as @marktopper said
