### ISSUE TITLE
Large Image Uploads Being Scaled 

### ISSUE THREAD

**Issue by gibbs** [thedevdojo/voyager#1950]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.5
- PHP Version: 7.1.5
- Database Driver & Version:

### Description:

Large images that are uploaded are being scaled to have a width of 1800px. Is it possible to disable this? I am scaling very large images and it is degrading the quality considerably. In my opinion uploaded images should be left *as is*.

I've tried to disable it by setting `width` to null with;

```
{
	"quality": "100%",
	"resize": {
		"width": null,
		"height": null
	},
	"thumbnails": [
		{
			"name": "thumbnail",
			"crop": {
				"width": 200,
				"height": 40
			}
		}
	],
	"display": {
		"width": 6
	}
}
``` 

which doesn't work...

### Steps To Reproduce:

Upload a large image

**Comment by Neutronas** [comment]
The same problem. Couldn't find an easy way to disable / change max width.

**Comment by kalenjohnson** [comment]
The Voyager Controller runs a check with `isset()` on the resize width and height: https://github.com/the-control-group/voyager/blob/v1.0.14/src/Http/Controllers/Controller.php#L334

`isset()` will return false if the value is `null` as well. So set the width and height to `false`, or a large number, and that should get you by.

**Comment by fletch3555** [comment]
Also, there's an open PR that should fix this.
