### ISSUE TITLE
Edition of generate permissions not working.

### ISSUE THREAD

**Issue by chrisifm** [thedevdojo/voyager#1951]
Laravel Version: 5.5.14
Voyager Version: ^1.0
PHP Version:7.1.8
Database Driver & Version: 10.2.9-MariaDB

### Description:
When I edit a bread and disable "generate permissions", If it shows the change in this view, but in the view of "roles" remains bread...

**Comment by fletch3555** [comment]
That's not expected to work, which is why it's termed "generate" permissions.  If you need to delete the permissions, you can do so manually through the permissions BREAD pages or manually through the database
