### ISSUE TITLE
My Site images 404 failed

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#1952]
- Laravel Version: 5.4.*
- Voyager Version: "tcg/voyager": "^1.0"
- PHP Version: "php": ">=5.6.4",
- Database Driver & Version:

### Description:

My web site is: yonetim.tufangokmenler.com
Can i create sliders table and bread, i can add 2 image and showing for front-end (home page), my site 404 failed for images (all image), but I do not have any problems when I run it locally.

**Comment by tufkan** [comment]
Help me please! Show this image;
<img src="https://i.hizliresim.com/nJLp2l.png">

**Comment by fletch3555** [comment]
You're missing the symlink at `public/storage`

**Comment by tufkan** [comment]
sorry i am new yet how can i add picture to this way: 

`@php($a=0)
        @foreach($sliders as $slider)
            <div class="item @if($a == 0) active @endif">
                @if($slider->link)
                <a href="{{$slider->link}}">
                    <img src="{{ Voyager::image( $slider->image ) }}" style="width:100%">
                </a>
                @else
                <img src="{{ Voyager::image( $slider->image ) }}" style="width:100%">
                @endif
            </div>
            @php($a++)
        @endforeach`

**Comment by tufkan** [comment]
<img src="{{ Voyager::image( $slider->image ) }}" style="width:100%">

**Comment by tufkan** [comment]
`<img src="{{ Voyager::image( $slider->image ) }}" style="width:100%">`

**Comment by tufkan** [comment]
can edit filesystems.php for this:

`'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],`
to
`'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage/app/public',
            'visibility' => 'public',
        ],`

And not work too :(

**Comment by tufkan** [comment]
Thanks can i use `'url' => env('APP_URL').'/storage/app/public',` to `'url' => env('APP_URL').'./storage/app/public',`
