### ISSUE TITLE
Override default behavior

### ISSUE THREAD

**Issue by slavarazum** [thedevdojo/voyager#1953]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

### Description:

There are no way to flexible change default RBAC system. What if I want to use some 3rd party package like _spatie/laravel-permission_. I ran into tons of problems with implementing this behavior.
There is really no way to override *voyager* service with IoC. It's singleton and setup of this service processes in `VoyagerServiceProvider` and stores in `$resolvedInstance`. If I will override an implementation in `AppServiceProvider` by
```php
$this->app->singleton('voyager', function () {
    return new App\Services\Voyager();
});
```
When we use `Voyager` facade, it will call old instance from `$resolvedInstance`.
If I will made `\TCG\Voyager\Facades\Voyager::clearResolvedInstance('voyager')`, setup of service will be reset (for example form fields registration). So we can't correctly override `voyager` service and integrate own RBAC system with no pain.

**Comment by fletch3555** [comment]
We've designed Voyager around Laravel's built-in auth scaffolding.  We can't possibly build it in a way that can support any package you wish to add, especially if your package changes core functionality.  Voyager is intended to be a standalone add-on to your site, not BE your site.

With that said, we're always open to Pull Requests, so if you see something you think could be designed/architected better, feel free to make changes and submit it with your justification for the change.  We're pretty reasonable people.
