### ISSUE TITLE
$this->authorize in controllers fail if the table has not beedn "BREAD'ed"

### ISSUE THREAD

**Issue by JapSeyz** [thedevdojo/voyager#1960]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version: 7.1
- Database Driver & Version: MySql 5.6

### Description:
When using the native $this->authorize in a controller, the Voyager permissions does not work unless the table has been "added to bread" from the admin panel.
If I add some tables to the `PermissionsTableSeeder` and seed them, they can't actually be used until the table i specified in the seeder has been "added to bread" from the admin-panel under "Database" even though it generates no new permissions, and simply uses the ones I already generated via the seeder.

### Steps To Reproduce:
 - Manually generate permissions for a table
 - Try to use that, eg. `$this->authorize('browse', app(Event::class))`

**Comment by Eliepse** [comment]
Hi !

I guess you didn't add the Event type to your database. You can make it manually (yeah, annoying and not persistent) or inside the `DataTypesTableSeeder`. Don't forget to configure also the rows and relationships of your model inside `DataRowsTableSeeder` to make it "bread".

I think Voyager could add seeds to documentation, they are very essentials to commit configurations ! :)

Hope it helped.

**Comment by fletch3555** [comment]
That is correct.  Adding BREAD to a table creates a row in the `data_types` table.  VoyagerServiceProvider loops over the rows that table and does the necessary mapping between Models and Policies.  Essentially, if you plan to add permissions manually without adding BREAD, you will need to also manually do a few other steps, specifically adding the Model -> Policy mapping per the Laravel Auth docs.  If you plan to use the default BREAD tests, you can just point your `Event` model at [BasePolicy](https://github.com/the-control-group/voyager/blob/master/src/Policies/BasePolicy.php).  If you need to customize it, you can extend `BasePolicy` in your own Policy class and use that instead.

**Comment by JapSeyz** [comment]
Alright, I was looking for the ability to call `$this->authorize('browse_events')` with the permissions from the voyager table, but this won't be possible without extending the BasePolicy, or writing my own I suppose.

Thanks for the quick response!

**Comment by fletch3555** [comment]
`authorize()` is a method provided by Laravel, so we can't (and shouldn't) override that to allow for calling the permission directly.  If you NEED to be able to do that, you can call `->hasPermission('browse_events')` on the user object, but for your case, I would just use the Policy class.  You don't need to extend BasePolicy unless you're adding methods with custom functionality.  It will already work with any permission you want (not just browse/read/edit/add/delete) as long as the desired functionality is to simply check if the user's role has that permission

**Comment by JapSeyz** [comment]
@fletch3555 Alright, thanks. I'll look into that.
