### ISSUE TITLE
Validation scroll to first error not work

### ISSUE THREAD

**Issue by mohamedothman91** [thedevdojo/voyager#1963]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version:7.1

### Description:
Validation scroll to first error not work if input file type image multiple  / select_dropdown multiple because name have [] like  name="age[]" 
//Scroll to first error
                                        if (Object.keys(d.errors).indexOf(key) === 0) {
                                            $('html, body').animate({
                                                scrollTop: $("[name='"+key+"']").parent().offset().top
                                                        - $('nav.navbar').height() + 'px'
                                            }, 'fast');
                                        }

### Steps To Reproduce:
f

**Comment by blitux** [comment]
I can confirm it still happens on Voyager 1.0.7. 

Also, where are the source files of app.js?
