### ISSUE TITLE
drop down multiple Bug

### ISSUE THREAD

**Issue by mohamedothman91** [thedevdojo/voyager#1964]
- Laravel Version:  5.5.14
- Voyager Version: 1.0.5
- PHP Version:7
- Database Driver & Version:

### Description:
After Update To last version 
show error json_decode() expects parameter 1 to be string, array given 
![screenshot](https://user-images.githubusercontent.com/16158464/31339941-c7990d60-ad04-11e7-8b4a-458bfaf7df7a.png)

**Comment by neverfan** [comment]
+1
https://github.com/the-control-group/voyager/issues/2207

**Comment by emptynick** [comment]
Closing in favor of #2207
