### ISSUE TITLE
Problem adding a coordinate field.

### ISSUE THREAD

**Issue by chrisifm** [thedevdojo/voyager#1965]
- Laravel Version: 5.5.14
- Voyager Version: ^1.0
- PHP Version: 7.1.8
- Database Driver & Version: 10.2.9-MariaDB

### Description:
When you try to add an element of type coordinates and edit content, appear a class not found error.

Apparently this required class appears in voyager/src/Traits/Spatial

Is this normal? How do I add support for a field coordinates?

**Comment by fletch3555** [comment]
Are.... you going to say what the missing class is...?

When reporting error messages, please report the full message as well as the full stacktrace.  Otherwise we'll likely just be guessing what the problem is.

**Comment by emptynick** [comment]
I tried coordinates a while ago, and also heard of other people working with it without problems.
I think this can be closed for now.

**Comment by emptynick** [comment]
If this is still a problem or you need more help, join our [Slack workspace](https://voyager-slack-invitation.herokuapp.com/)
