### ISSUE TITLE
Support Soft Deleting Models

### ISSUE THREAD

**Issue by Hiroki111** [thedevdojo/voyager#197]
I've been trying to do this, but apparently just adding deleted_at column isn't enough.
It'll be necessary to put "use SoftDeletes" in the model class, but I can't find any of the predefined class, such as posts an pages.

Could I have some advice?

**Comment by fletch3555** [comment]
Predefined Models (Posts, Pages, etc) exist in the package under the vendor directory.  New models you create will be created under App (at the path you configure when creating it).

**Comment by marktopper** [comment]
I recommend that we make the predefined models configurable, so if I want to overwrite something in the `Page` model, I could modify the configuration to use another model, which might simple extend the original `Page` model.

Then the SoftDeletes trait could be added to any model quite easy along with other customization.

I might make a pull request for this soon.

**Comment by Hiroki111** [comment]
Okay. Apparently they were under vendor/tcg/voyager/src/Models. Thanks!
