### ISSUE TITLE
How To Change Default Image Upload Folder?

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#1970]
my config/filesystem.php is:
`'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage/app/public',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],

    ],`

my site folder is /public default, my image uploading /stroage/app/public/......./image.png
 how to change is /public/storage/app/public/......./image.png is default?

Please Help ME!

**Comment by htet-htet-ag** [comment]
I think , .env file  in APP_URL=http://localhost:8000. thanks you.

**Comment by tufkan** [comment]
i did this before

`APP_NAME=Laravel
APP_ENV=local
APP_KEY=*************
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://*******.com`

**Comment by tufkan** [comment]
my default directory from cpanel this image:
<img src="https://i.hizliresim.com/5G7qbz.png">

**Comment by tufkan** [comment]
I can see the images when I move the stroage folder to the public folder

**Comment by htet-htet-ag** [comment]
I think, you will be change under ...

How to change the custom domain name in xampp


   -

   Hosts (  /c/Windows/System32/drivers/etc )


- # localhost name resolution is handled within DNS itself.

127.0.0.1     instead (https:// yourdomain)

::1            (your domain)



   -

   Httpd-vhosts (  /c/xampp/apache/conf/extra )



<VirtualHost *:80>

  DocumentRoot "C:/xampp/htdocs/cms/public"

  ServerName  (yourdomain)



  <Directory "C:/xampp/htdocs/cms/public">

    Options Indexes FollowSymLinks Includes ExecCGI

     AllowOverride All

     Require all granted

</Directory>

</VirtualHost>


   -

   Httpd ( /c/xampp/apache/conf )


<VirtualHost *:80>

  DocumentRoot "C:/xampp/htdocs/cms/public"

  ServerName  (your domain)

  <Directory "C:/xampp/htdocs/cms/public">

    Options Indexes FollowSymLinks Includes ExecCGI

     AllowOverride All

     Require all granted

</Directory>

</VirtualHost>

**Comment by tufkan** [comment]
my site is not locally, my site is hosting installed

**Comment by tufkan** [comment]
@Roffy9 My site is not locally, site is hosting installed

**Comment by tufkan** [comment]
I solved:
`'root' => storage_path('../public/storage/app/public'),`

**Comment by fletch3555** [comment]
@tufkan, I'm concerned for your server setup.  Having `public/` UNDER the webroot, means that your `.env` file will be accessible (anything done to hide this specific file is a bandaid fix at best).  Your images are indeed uploaded to `storage/app/public/`, which should be accessible as `public/storage/` as well.  `public/storage/app/public` tells me that either your laravel install is set up REALLY weird, or your symlink is done incorrectly.  Either way, doing the fix you posted in your last comment is also a bandaid fix at best.
