### ISSUE TITLE
Adding new item to admin menu not working.

### ISSUE THREAD

**Issue by imranicp** [thedevdojo/voyager#1971]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: 5.0.12

### Description:
I am trying to add a new item to existing admin_menu, i added the item through menu builder, but its not displaying in the menu on the side bar. the menu item is saved in the database, and is retrieved from the database on the backend. but its not displaying on the front-end/admin-panel.

### Steps To Reproduce:
Go to menu builder in the admin panel
add new item to admin menu.

**Comment by Roffy9** [comment]
to pay the role permission in role menu . thanks you

**Comment by imranicp** [comment]
my user has all the permissions from the roles link. all the permission are selected for this user(which in this case is the default admin user), i tried with another user also but same.

**Comment by Roffy9** [comment]
php artisan voyager:admin your@email.com --create

**Comment by imranicp** [comment]
if you read my question above you will understand as to what i am trying to explain. i already have a user. i tried with custom user as well as with the admin user with all the permission given to the user through Roles page. i tried adding new menu items, the items are stored in the database, but its not being displayed in the admin menu. hope this makes it clear.

**Comment by Eliepse** [comment]
Hi !

I think you have the same issue as me. I recommand you to check it here : #1907

**Comment by fletch3555** [comment]
I agree with @Eliepse.  Closing as duplicate
