### ISSUE TITLE
adding a publisher browse in breads

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#1972]
- Laravel Version:5.5
- Voyager Version: 1.1
- PHP Version:7.0
- Database Driver & Version:

### Description:
I think it would be necessary for some tables that only the author of the db row can change its content or to browse it like WordPress admin page or something like that 
may be some conditions on users who can browse or edit specific rows at least

**Comment by fletch3555** [comment]
You're free to add your own permissions and add logic to check them via Laravel's default auth scaffolding (Policy class(es), `@can`, `$this->authorize()`, etc).

If there are specific things in core that you believe should be limited this way, I'm willing to entertain pull requests, and will review them on a case-by-case basis.
