### ISSUE TITLE
Drag And Drop Builder For New Database Table?

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#1974]
I created the sliders table, how do I drag and drop the menu builder like for sorting?

**Comment by mdelally** [comment]
The Javascript functionality for the menu builder is inherent to that feature of Voyager. You would have to implement that functionality in a custom view in order to have that sort of sorting available to that model/DB table.

**Comment by tufkan** [comment]
How can use it?

**Comment by fletch3555** [comment]
@tufkan, @mdelally is right. This is functionality specific to the menu builder. If you want similar functionality for something you're building, you'll have to either isolate the JavaScript for the menu builder and fit it into yours, or implement it from scratch (choosing whatever library you wish to use).

In either case, this is not a Voyager issue.  You're welcome to post on larachat or in the laracasts forum for further assistance.  You can post in our slack group as well, but you'll likely have better luck with one of the others.
