### ISSUE TITLE
Edit BREAD - Relationship information displays wrong table

### ISSUE THREAD

**Issue by StevenKTurnerLuna** [thedevdojo/voyager#1976]
- Laravel Version: 5.5
- Voyager Version: 1.0.5
- PHP Version: 7.1
- Database Driver & Version: Postgres

### Description:
When adding relationships to custom tables, the table information seems to get corrupted.  For example, I have an Addresses table and a Businesses table.  A business has one address, but an address can refer to many businesses.  When I attempt to add the relation to the Address, it seems to save okay, but when I then view the address details, the labels for the forms refer to the wrong table; a pivot table that I haven't added any BREAD to.

![image](https://user-images.githubusercontent.com/19938898/31398297-17524296-adae-11e7-84be-ac6ed5ec809d.png)

When peeking at the database values, this table is mentioned nowhere.

### Steps To Reproduce:
Install Laravel
Build out tables for laravel's database migrations
Install Voyager
Add Bread to existing models
Add Relationships to existing models

**Comment by whyayala** [comment]
I have also had this problem when trying to create a relationship on a model to itself.

- Laravel Version: 5.5
- Voyager Version: 1.0.3
- PHP Version: 7.0
- Database Driver & Version: Mysql

![screen shot 2017-10-13 at 9 28 38 am](https://user-images.githubusercontent.com/7398790/31551049-0584e012-aff9-11e7-87ec-4c61dbe6d05e.png)

**Comment by darit** [comment]
Fixed on PR #2007
