### ISSUE TITLE
Product Eloquent Model Locale

### ISSUE THREAD

**Issue by pieinn** [thedevdojo/voyager#1977]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.5
- PHP Version: 7.0.22
- Database Driver & Version: Mysql 5.7.19

### Description:  Product Model not Appear Language Switcher 

![1](https://user-images.githubusercontent.com/29000827/31400059-1d0db636-ae10-11e7-804e-d0ca8e6dcf50.jpg)
![2](https://user-images.githubusercontent.com/29000827/31400069-25a55d30-ae10-11e7-987c-9ec82120c70f.jpg)

### Steps To Reproduce:

**Comment by Sebastiangperez** [comment]
Maybe you need to implement the trait Translatable and set the Translatable fields on the model ..

**Comment by fletch3555** [comment]
.I'm inclined to agree, though I certainly don't have much experience with the translation functionality

**Comment by fletch3555** [comment]
I'm going to close as "question answered".  If this still exists as an issue after following @Sebastiangperez's suggestion, we can reopen this.
