### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by sonynlaw** [thedevdojo/voyager#1978]
- Laravel Version: 5.5
- Voyager Version: 1.0

- PHP Version:
- Database Driver & Version:

### Description:
In voyager admin panel > settings
here in the bellow, new setting option area/ section's css has broken

**Comment by fletch3555** [comment]
All fields are required when submitting issues, with very few exceptions.  Additionally, since you're mentioning CSS, it would likely be helpful to submit screenshots of the issue.

When you've updated the issue, we can reopen it.

**Comment by sonynlaw** [comment]
Dear Eric Fletcher, here the screenshots of the issue.

Regards




*Md Khurrum Jha Murad (Sony)AdvocateSupreme Court of Bangladesh*
*Email: sonynlaw@gmail.com <sonynlaw@gmail.com>*
*Contact: +880 1737 484802 <+880%201737-484802>*
*Website: www.sonyscript.com <http://www.sonyscript.com>*
