### ISSUE TITLE
[Need some Infos] Rules in voyager

### ISSUE THREAD

**Issue by dimitri-dolle** [thedevdojo/voyager#198]
Hi,

I want too add rules to my Bread. But when i look the VoyagerBreadController.php, i only saw the "InsertUpdateData" function to make rules for my custom bread.

They have only one way to make rules in voyager or i miss something ?

Thanks.

**Comment by handiwijoyo** [comment]
@dimitri-dolle  to use it, add rule option to **Additional Field Options** JSON when creating BREAD. 

Example:
```
{
    "rule": "required|min:20"
}
```

![image](https://cloud.githubusercontent.com/assets/4060094/20638510/a9e50580-b3db-11e6-8d7f-4fa69a3bc697.png)

**Comment by dimitri-dolle** [comment]
Thanks for the answer !
