### ISSUE TITLE
Media stop show and load the media.js file.

### ISSUE THREAD

**Issue by Sebastiangperez** [thedevdojo/voyager#1982]
- Laravel Version: 5.4.36
- Voyager Version: latest
- PHP Version: 5.6.21
- Database Driver & Version: Mysql 5.6

### Description:
Suddenly the media module stop working , and the view doesnt load the media.js file . 
I installed the debugbar for laravel.

**Comment by emptynick** [comment]
Closing due to age.
Please let us know if this is still a problem.
