### ISSUE TITLE
Issue with relationship fields in new voyager

### ISSUE THREAD

**Issue by pirocoptero** [thedevdojo/voyager#1985]
- Laravel Version: 5.5.12
- Voyager Version: 1.0.2
- PHP Version: 7.0.20
- Database Driver & Version: Mysql 5.7.19

### Description:

I need help to create a relationship from my tables.

I have a table called compras, i need this table call your related table called compra_detalhes. I followed the tutorial in documentation, but no success.
Nothing happened. 

How can I relate the tables and display the fields of the related table in the view?

### Steps To Reproduce:

![captura de tela 2017-10-11 as 23 04 09](https://user-images.githubusercontent.com/4484855/31475692-a3b1a4c2-aed8-11e7-97ff-0dd99a9d2404.png)

![captura de tela 2017-10-11 as 16 55 53](https://user-images.githubusercontent.com/4484855/31475694-a699a734-aed8-11e7-8e7f-94a1686735c5.png)

Look, compra_detalhes is empty, i need the fields of this related table called compra_detalhes. Please help me =/

**Comment by fletch3555** [comment]
I believe this is the issue I helped you with the other day.  Is this still an issue, or can it be closed?

**Comment by pirocoptero** [comment]
hey @fletch3555 thanks for your reply. Is an issue. Where is the fields of compra_detalhes?? =/ 
How can i show all fields of the related table? Please help me.

**Comment by MrCrayon** [comment]
Only one fied of the related table is shown, in your case id.

If you still need help with this after reading documentation you might ask in Voyager Slack group.
