### ISSUE TITLE
Jquery not found

### ISSUE THREAD

**Issue by aqualaguna** [thedevdojo/voyager#1986]
- Laravel Version: 5.4
- Voyager Version: 1.0.0
- PHP Version: 7.1
- Database Driver & Version: mysql 

### Description:
when I'm upgrading from 0.11 to 1.00 i got this error

Uncaught ReferenceError: $ is not defined
    at app.js:1

### Steps To Reproduce:
php artisan vendor:publish
php artisan voyager:install

**Comment by touqeer-gt** [comment]
Yup i have got the same problem can you guys please share a workaround.

**Comment by fletch3555** [comment]
There have been numerous issues with the same issue, and a nearly identical subject line, following the upgrade.  You have outdated assets.  Please run `php artisan vendor:publish --force --provider=TCG/Voyager/VoyagerServiceProvider`

**Comment by aqualaguna** [comment]
the compiled app.js and app.css does not contain the dependency hence the error popup.
its not compiled thoroughly btw here the import ::
berfore importing app.js at master.blade.php
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/perfect-scrollbar.jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/readmore.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.matchHeight-min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/bootstrap-toggle.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/ace/ace.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/ga-embed/moment.min.js')}}"></script>
<script src="{{ voyager_asset('js/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>

and before app.css import::
<link rel="stylesheet" href="{{ voyager_asset('lib/css/bootstrap.min.css') }}">
