### ISSUE TITLE
Pre-populates incorrect data using password manager LastPass

### ISSUE THREAD

**Issue by stevencook** [thedevdojo/voyager#1993]
- Laravel Version: 5.5.*
- Voyager Version: ^1.0
- PHP Version: 7.1
- Database Driver & Version: mySQL 5.7

### Description:
Both the admin login form and the Users forms (create/edit) have email fields (named "email") and password fields (named "password").  When using password managers such as LastPass, if the login credentials are saved from the login page, that email and password will auto-populate in every User create/edit form in the Voyager admin.  This could be prevented by simply making it so the "name" attribute for the email and password on the login page are different than the email and password field names in the User admin area.

### Steps To Reproduce:
1) Log into the admin using admin@admin.com and password
2) Save the login credentials to LastPass
3) Click on Users
4) Click on Add New or Edit

The user form loads with the login email and password auto-populated into the email and password fields.

I literally have a client that is making us change our admin software because of this behavior in Voyager.  They are concerned that users, while editing other users, will accidentally overwrite the email/password fields thanks to LastPass auto-fill.

Again, all that needs to happen to prevent this is to rename the "name" attribute for either the email/password fields on the login page, or to rename all the rest of the email/password fields throughout the admin.

Thank you

**Comment by gausam** [comment]
Ah yes this is a biting one. Bit me (and I'm guessing a number of users) in bad ways. Not sure what the maintainers will pick as the best resolve, so that we can maintain the password managers' mechanisms to pick up password updates.

**Comment by Victor-emil** [comment]
I am facing the exact same issue as stevencook when editing and creating users. Our client is currently reviewing an application that we built with Voyager and this is one of their critiques.

**Comment by calder12** [comment]
This is a pretty critical fix in my opinion, had issues in an application I'm building today where I didn't notice it had done that and messed up one of my users.

**Comment by akazorg** [comment]
Thanks for the report and the detailed explanation @stevencook.
This will be handled.

**Comment by gausam** [comment]
@akazorg What can we do to improve issue triage, I'm seeing truly critical and useful issues & PRs can sometimes fall by the wayside.

**Comment by akazorg** [comment]
Guys, I tried to fix the issue but didn't work as expected, and honestly it's a bit hacky.

Renaming names happens not to work on my system, can any of you please test this [fix-attempt](https://github.com/akazorg/voyager/tree/fix-1993).
@samtheson @stevencook .
Thanks.

**Comment by victorlap** [comment]
Maybe put the form of the password reset in a separate modal? Then the fields will only be present if you want to change them.

**Comment by gausam** [comment]
@akazorg Sorry I didn't get the notification for this. Will try your fix out and see what I can add :+1:

**Comment by akazorg** [comment]
@victorlap I didn't follow you, sorry.
Thanks @samtheson, fix that, please :D

**Comment by Victor-emil** [comment]
Any news on this?

**Comment by fletch3555** [comment]
We're open to PRs if someone wants to make the change.

**Comment by gausam** [comment]
I'll take a look again at [your attempt](https://github.com/akazorg/voyager/tree/fix-1993) @akazorg

**Comment by akazorg** [comment]
Thanks @samtheson, that would be great! :)

**Comment by emptynick** [comment]
This was fixed in #3000 [here](https://github.com/the-control-group/voyager/pull/3000/files#diff-7bd8034abb2d9bf22d0356ac14e1a73f)
