### ISSUE TITLE
It's just a request regarding Changelog.md

### ISSUE THREAD

**Issue by touqeer-gt** [thedevdojo/voyager#1996]
Can you guys please add changelog, then it will become easier us when should we update voyager.

**Comment by fletch3555** [comment]
You're free to look at the release notes between versions (https://github.com/the-control-group/voyager/releases).  We're not perfect at updating it, but it's a good starting point.  If you ACTUALLY need to see all the changes, we're open source, so you're free to just run `git diff tag1 tag2` (https://stackoverflow.com/questions/3211809/git-diff-between-given-two-tags)
