### ISSUE TITLE
Required password field in Users Edit

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/voyager#1999]
- Laravel Version: 5.5 #.#.#
- Voyager Version: 1.0 #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

I don't know what I did but the password field in the Users edit is now required to be filled in. It is supposed to be okay to leave it blank. How to fix this?

**Comment by gausam** [comment]
Can confirm I [experienced this issue (Slack)](https://laravel-voyager.slack.com/archives/C36H9MY2C/p1507916260000351), and someone else [asked about it (Slack](https://laravel-voyager.slack.com/archives/C36H9MY2C/p1507919263000049?thread_ts=1507917482.000477&cid=C36H9MY2C).
