### ISSUE TITLE
Can't update user information

### ISSUE THREAD

**Issue by Fusion86** [thedevdojo/voyager#2]
Whenever I try to edit an user I receive an `InvalidArgumentException in Carbon.php line 425`.

This probably is because Voyager/Laravel saves the created_at differently than expected, as indicated by `at Carbon::createFromFormat('Y-m-d H:i:s', 'January 28th, 2016 11:20 AM')` and `at Model->__set('created_at', 'January 28th, 2016 11:20 AM') in VoyagerBreadController.php line 220`

**Comment by ferdikam** [comment]
I have also the same error

**Comment by tnylea** [comment]
Should be fixed now. There was an accessor that was changing the format of the date and I added a mutator to change it back. 

Looking at it again the 'created_at' should not have even been available when editing the user table so it has been updated in the seed file. To update that on your end, simply go into the Tools->Database, then click on the 'Edit Bread' for the users table.

Uncheck the 'Edit' checkbox in the 'created_at' row and then update the BREAD. After that you should be good to go. Screenshot attached.

![screenshot](https://cloud.githubusercontent.com/assets/601261/19812652/4dbe77fc-9ceb-11e6-9cfa-2f8fab877463.png)

Thanks for checking this out and letting me know. I appreciate it.
