### ISSUE TITLE
Fields should be extracted to their own class for easy extensibility

### ISSUE THREAD

**Issue by joshuatf** [thedevdojo/voyager#200]
Currently fields (text, textarea, select, etc.) are somewhat hard-coded directly in the view.  getContentBasedOnType() also runs through an if/else soup of mutators for various field types.  Instead, why don't we create a class per field that has getter, setter, and view methods.

This would clean up legibility and allow users to create custom fields without overriding entire model views.

**Comment by fletch3555** [comment]
I actually love this idea. I can get started on it when I get some free time, but it may take a little while. If someone else has more free time, feel free to jump in and take it.

**Comment by brandonferens** [comment]
Perhaps we can use a presenter or hook into the Laravel Collective's Forms & HTML package, or both, for this functionality?

**Comment by fletch3555** [comment]
This has been added into the v0.11 branch, and will be released with v0.11.0 when we get to it.

**Comment by igorjacauna** [comment]
I didn't find documentation about create custom field for bread form... Sorry for comment after closed issue.

**Comment by happyplayer1991** [comment]
Hello @igorjacauna 
So have you added custom class to field?

**Comment by emptynick** [comment]
https://docs.laravelvoyager.com/customization/adding-custom-formfields
