### ISSUE TITLE
tcg/voyager removed when running php artisan hook:install voyager-themes

### ISSUE THREAD

**Issue by vortechron** [thedevdojo/voyager#2012]
### Description:

this is my first time installing hook using 'php artisan hook:install voyager-themes' command.. 
then suddenly when i try to browse my admin panel, class voyager was not found, it turns out my tcg/voyager dependencies were removed when i run php artisan hook:install voyager-themes, is anyone know what the reason this issue happen?

**Comment by fletch3555** [comment]
I can't think of any reason why this would happen... However, issues with Hooks should be tracked under the [voyager-hooks](https://github.com/larapack/voyager-hooks/) repo.
