### ISSUE TITLE
BREAD browse page hangs with 700+ data rows

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#2015]
- Laravel Version: 5.5
- Voyager Version: 1.0.4
- PHP Version: 7.0
- Database Driver & Version: MySQL 6.0

### Description:
I have 700+ rows in a bread table. When I view the browse datatable I get the loading icon and that spins and the page is trying to load and ultimately crashes and can't display the data. There are only 4 columns of data, doesn't seem like a ton. Any recommendations? Is this a voyager issue or a datatable plugin issue?

**Comment by kjdion84** [comment]
You didn't select "server side pagination" when creating the BREAD.

**Comment by chadpriddle** [comment]
Much appreciated. I feel like an idiot haha
