### ISSUE TITLE
Can't add record

### ISSUE THREAD

**Issue by KoziaikinDmitriy** [thedevdojo/voyager#2018]
- Laravel Version: 5.5
- Voyager Version: 1.0.#
- PHP Version: 7.1
- Database Driver & Version: mysql

When I click Add in BREAD, app redirect to '/admin/slug/{id}', but it should redirect to '/admin/slug/create'.
If in routes update to Route::resource($dataType->slug, $breadController)->except(['index']), create page work.

**Comment by cyrildewit** [comment]
@KoziaikinDmitriy do you still encounter this issue? Otherwise this issue can be closed.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still a problem, please provide more context and indicate that you've tested in the most recent version as well.
