### ISSUE TITLE
Remove "edit" button for specific BREAD

### ISSUE THREAD

**Issue by kjdion84** [thedevdojo/voyager#2019]
Is there a simple way to remove the "edit" button for a specific BREAD?

For example, I don't need the edit functionality for a particular model whatsoever.

Should I just keep "edit' unchecked in the role permissions, or is there a better way?

**Comment by chadpriddle** [comment]
Currently yes that is the best way using the role permissions

**Comment by fletch3555** [comment]
Yes, permissions is the recommended means of accomplishing this.
