### ISSUE TITLE
problem permission add

### ISSUE THREAD

**Issue by seguce92** [thedevdojo/voyager#2027]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Solved: fix the error this way
$this->authorize('edit', app($dataType->model_name));
to
$this->authorize('add', app($dataType->model_name));
in TCG\Voyager\Http\Controllers\VoyagerBreadController.php line 286

**Comment by fletch3555** [comment]
All fields are required (versions, a description of the issue, and steps to reproduce the issue).  It seems you've provided only a description of the solution, not the issue.

Please update the issue appropriately and we'll reopen this.
