### ISSUE TITLE
Newbie - Create BREAD succeed but  when BROWSE BREAD give error This action is unauthorized.

### ISSUE THREAD

**Issue by Dian1y** [thedevdojo/voyager#2028]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version: 7
- Database Driver & Version:

### Description:

Error when click browse in tools->database menu voyager

error : Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized.

### Steps To Reproduce:
1. create new table
2. Add Bread to this table
3. submit
4. click Browse BREAD
 
error : Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized.

Please help me solve this issue.

Thanks & Regards,

Dian

**Comment by bedoz** [comment]
Hi Dean,
have you tried adding on roles permissions to new bread?

**Comment by Dian1y** [comment]
Hi Bedoz,

You right! I forget to add roles for admin. Thanks a lot!

Regards,
Dian

**Comment by levend18** [comment]
i added and. it throws same error
