### ISSUE TITLE
ErrorException (E_ERROR) SQLSTATE[HY000] [2002] Connection refused (View: /var/www/vendor/tcg/voyager/resources/views/login.blade.php)

### ISSUE THREAD

**Issue by TPRAsh** [thedevdojo/voyager#2029]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1.9
- Database Driver & Version: mysql:8.0.2 - 5.7 and 5.6 also tested.

### Description:
I have a fresh install of Laravel 5.5 and I am following the Voyager install steps in the docs.

### Steps To Reproduce:
When I go to /admin I am redirected to /admin/login with the following error:

ErrorException (E_ERROR)
SQLSTATE[HY000] [2002] Connection refused (View: /var/www/vendor/tcg/voyager/resources/views/login.blade.php)

ErrorException 
…/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php47

**Comment by gausam** [comment]
I faced this issue at one time, came out of nowhere for me. After all else failed, it went away after I ran `sudo apt get update && sudo apt-get upgrade`.

Hmm actually no, mine was different, although it was along the same lines.
Are your DB settings set up properly in `.env`?

**Comment by TPRAsh** [comment]
Hey Samtheson, thanks for your reply. 

Yeah, my DB settings are correct as I can connect to the DB etc. I am on windows running Docker which is not my first choice, but I do have a Mac laptop which is doing the exact same thing.

I am a bit confused why this is happening.

**Comment by gausam** [comment]
Usually when DBs are failing I just try and connect to the DB via plain php within Laravel's `public/index.php` file. At least that way I can find out if it's something deeper that's causing the problem.

**Comment by TPRAsh** [comment]
Ok I thought I would try something random and use Mamp mysql (system) rather than the Docker mysql image and it it working. So there must be something along the way wrong with the mysql image I am using. A little random.
