### ISSUE TITLE
Install in laravel 5.3

### ISSUE THREAD

**Issue by angela-25** [thedevdojo/voyager#2030]
- Laravel Version: 5.3.31
- PHP Version:5.6.3

### Description:
I want to install voyager in my laravel project, but it installed fail.
It always return error message: Installation failed, reverting ./composer.json to its original content.
How do I do?

**Comment by pirupius** [comment]
@devil19891025 this package is for only compatible with Laravel 5.4 and above. There's even a note before the installation steps that clearly says so. 

`**Laravel Admin & BREAD System (Browse, Read, Edit, Add, & Delete), supporting Laravel 5.4 and newer!**`
