### ISSUE TITLE
404 on ajax request and bg.jpg (fix)

### ISSUE THREAD

**Issue by Rct567** [thedevdojo/voyager#2038]
### Description:

In 'vendor\tcg\voyager\resources\views\tools\database\edit-add.blade.php' line 479 an ajax call is made with a relative url (pointing to the domain, not the project folder), which causes a 404 with my current setup.

404: http://127.0.0.1/admin/database/table
should be http://127.0.0.1/projectname/public/admin/database/table

### Steps To Reproduce:

Laravel in : http://127.0.0.1/projectname/
APP_URL=http://127.0.0.1/projectname/public
Accessing panel: http://127.0.0.1/projectname/public/admin/database/table/bread/edit

### Fix

Replace route('voyager.database.index', [], false)  with route('voyager.database.index')  in 'vendor\tcg\voyager\resources\views\tools\database\edit-add.blade.php' line 479 

^ false as third argument prevents creating an absolute URL

edit: Same fix goes for 'menus\builder.blade.php:95' and 'database\edit-add-bread.blade.php:91'. If you search for "[], false" you will find a couple more, but i have not verified they actually produce any problems.

## bg.jpg

A 404 is caused by 'vendor\tcg\voyager\resources\views\dashboard\sidebar.blade.php at line 19. 

fix:
replace: config('voyager.assets_path') . '/images/bg.jpg' 
with: url(config('voyager.assets_path') . '/images/bg.jpg'));

**Comment by Luc45** [comment]
Exact same issue here.

When the project is hosted in a subfolder, all AJAX calls while editing a BREAD, for example, gets 404's.

Replacing `route('voyager.database.index', [], false)` with `route('voyager.database.index')` in  `tcg/voyager/resources/views/tools/database/edit-add-bread.blade.php` in lines 91 and 478 as you suggested solved the problem on the BREAD page.

**Comment by fletch3555** [comment]
@Luc45, that specific fix was merged in 3 months ago via #1821.  If you're still having that problem, can you please tell us specifically what version of Voyager you're running?

**Comment by emptynick** [comment]
Can be closed as #1821 was merged
