### ISSUE TITLE
using the latest update on voyager

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#2045]
- Laravel Version: 5.5
- Voyager Version: 1
- PHP Version:7
- Database Driver & Version:

### Description:
how can I have the latest version on voyager in github on my project? 
because there is plenty bugs like the image required with is resolved in the github but not updated the version of it in composer

**Comment by fletch3555** [comment]
You can set your version in composer.json to `dev-master`, however I don't recommend doing this.  We're releasing much more frequently than before, so any bugfixes you may be missing will usually be released within a week or so of being merged in.
