### ISSUE TITLE
Can't browse media library folders.

### ISSUE THREAD

**Issue by UrosHCS** [thedevdojo/voyager#2046]
- Laravel Version: 5.5.16
- Voyager Version: 1.0.5
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.19

### Description:
Fresh laravel app with fresh voyager package is trying to access images through a link of this format:
http://<domain.name>/admin/<domain.name>/storage/users/default.png.

Because of this admin avatar is not loaded and i can't browse media library (404 not found)

I have made the following change in the filesystems.php: 'disks' => 'public' =>
'url' => env('APP_URL').'/storage',   <- I've changed this
'url' => '/storage',   <- to this.

Now the admin avatar is loaded but I still can't browse media library. When I click on a, for example, users folder, 2 GET requests happen to http://<domain.name>/storage/users.
The first one has status code 301 Moved Permanently (from disk cache).
The second one has status code 403 Forbidden.

### Steps To Reproduce:
1) Install a new laravel app
2) install voyager with dummy data or add a user manually
3) change filesystems.php: 'disks' => 'public' => 'url' from env('APP_URL').'/storage' to '/storage' (optional)
4) try to browse media library

**Comment by adriangordon1231** [comment]
Try running 'php artisan storage:link'

**Comment by fletch3555** [comment]
@UrosHCS, sounds like your APP_URL isn't set properly.  Please make sure it has `http://` prefixing the domain you're using to access your site.

**Comment by fletch3555** [comment]
@UrosHCS, I'm going to assume this is resolved since it's been nearly 3 weeks.  If not, please let me know and we can reopen this.
