### ISSUE TITLE
Bug in Menu Builder ?

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#2049]
![01](https://user-images.githubusercontent.com/13164167/31716671-7fcebb9a-b43b-11e7-9811-56d2a2263079.jpg)
    Laravel Version: 5.5.14
    Voyager Version: 1.0.5 (dev-master)
    PHP Version: 7.1.9

### Description:
I installed voyager in many demo project just to test menu builder its seems it has bug 

{!! menu('main', 'admin_menu') !!}

no menu is displayed if set as {!! menu('main') !!} it shows the menu list without any style just raw menu list

**Comment by fletch3555** [comment]
The second argument (`'admin_menu'`) is required for the main menu in Voyager, so I don't recommend removing it, even for testing, as you'll see exactly what you've reported (no styles).

For the actual issue... you say the menu doesn't show up? Do you mean the whole menu, or just certain menu entries? Can you provide a screenshot of this behavior?

**Comment by rddewan** [comment]
if i set {!! menu('main', 'admin_menu') !!} i don't see any menu link
![02](https://user-images.githubusercontent.com/13164167/31828376-a50a4cbe-b5ec-11e7-924d-44e27bef91d2.jpg)

**Comment by fletch3555** [comment]
@rijudewan, are you still having this issue? I haven't seen it reported by anyone else, so it must be something you're doing, and not an actual issue with Voyager.

If you're still having this issue, please provide more information (code samples, etc) and we'll reopen this.  More likely, you'll be better suited asking for help on Slack.  Thank you.
