### ISSUE TITLE
Problem with coordinates field

### ISSUE THREAD

**Issue by iboved** [thedevdojo/voyager#2050]
- Laravel Version: 5.5.14
- Voyager Version: ^1.0
- PHP Version: 7.1.9 
- Database Driver & Version: 10.1.26-MariaDB

### Description:
When you add "coordinates" field type in the BRAD and try to create new record you get an error. When you edit the record, there is no error. But when you add a new record, you get an error "Trying to get property of non-object". The problem in the "[getLocation](https://github.com/the-control-group/voyager/blob/master/src/Traits/Spatial.php#L18-L21)" function in \TCG\Voyager\Traits\Spatial trait.
The method looks like this:
```
    public function getLocation($column)
    {
        return self::select(DB::Raw('ST_AsText('.$column.') AS '.$column))
            ->where('id', $this->id)
            ->first()
            ->$column;
    }
```
When you are on the model creation page, the method "getLocation" is called from template. This piece of the function returns "null" (because the model has not yet been created):
```
self::select(DB::Raw('ST_AsText('.$column.') AS '.$column))
        ->where('id', $this->id)
        ->first()
```
And then you chaining:

`->$column;`

Therefore, we get an error "Trying to get property of non-object".

**Comment by iboved** [comment]
Here is a screenshot of the error:
![screen](https://user-images.githubusercontent.com/9253603/31731262-218ca266-b43d-11e7-9694-2ddcbf4f94c1.PNG)

**Comment by iboved** [comment]
I have created a Pull Request #2060

**Comment by mohd-aidi** [comment]
hi, can anyone help me on this one problem.

i get this error mentioning about ST_AsText does not exist when i try to go to the pages listing that have coordinate field.

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION mydb.ST_AsText does not exist (SQL: select ST_AsText(location) AS location from `pages` where `id` = 1 limit 1) (View: mypath/resources/views/vendor/voyager/partials/coordinates-static-image.blade.php) (View: mypath/resources/views/vendor/voyager/partials/coordinates-static-image.blade.php)
