### ISSUE TITLE
Usecase question 

### ISSUE THREAD

**Issue by CptMeatball** [thedevdojo/voyager#2051]
First of all I'm absolutely love the built in richeditors, mediamanagers, ACL and so much more. Voyager is an awesome starting point for lots of scenarios, but I'm trying to determine if Voyager is the right starting point for what I'm trying to achieve. 

I'm trying to use Voyager as a bootstrap for a SaAS mvp (most viable product), and at first hand it looked like a match made in heaven, but when further exploring I'm running into a lack of documentation / tutorials. 

For example;  I want to filter the Browse list per `user_id` (Many to Many); or make custom views combining data from different BREAD models. All into the admin view that is provided by Voyager. 

I'm having trouble fully understanding the BREAD models, as there is no scaffold performed in the traditional Laravel way, but all through `dataType` attributes from BREAD models. 

I just really like the interface, with all CRUD generation, with Select2 and RichEditor support, but I'm not really fan of the BREAD set up, by using a sort of Dynamic Model generation. Apart from that, do you think Voyager is a good starting point for what I'm trying to achieve, or should I start from a more basic (traditional) way and try to find other more front-end scoped packages.

In anyway, big thumbs up for the work you guys provided!

**Comment by fletch3555** [comment]
You haven't REALLY explained what you're trying to do, or what you're having issues with.  This type of question is best asked in our Slack group as there will be many questions and it's very individualized.  I would encourage you to join and post there.
