### ISSUE TITLE
Coordinates field - Problem with map center

### ISSUE THREAD

**Issue by iboved** [thedevdojo/voyager#2052]
- Laravel Version: 5.5.14
- Voyager Version: ^1.0
- PHP Version: 7.1.9
- Database Driver & Version: 10.1.26-MariaDB

### Description:
On the edit page (Edit), the map center is adjusted correctly. We have a marker in the center. But on the "Read" page (when you press the "View" button), the center is set to the default coordinates:
```
GOOGLE_MAPS_DEFAULT_CENTER_LAT=
GOOGLE_MAPS_DEFAULT_CENTER_LNG=
GOOGLE_MAPS_DEFAULT_ZOOM=
```
So the marker is in one place of the map, and we see quite a different place. And so we need to look for a marker across the map.

All this because in the Edit page we have [correct settings](https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/coordinates.blade.php#L17-L21) of the center:
```
        @forelse($dataTypeContent->getCoordinates() as $point)
            var center = {lat: {{ $point['lat'] }}, lng: {{ $point['lng'] }}};
        @empty
            var center = {lat: {{ config('voyager.googlemaps.center.lat') }}, lng: {{ config('voyager.googlemaps.center.lng') }}};
        @endforelse
```
But on the Read page we have incorrect [default settings](https://github.com/the-control-group/voyager/blob/master/resources/views/partials/coordinates.blade.php#L10) of the center:
`var center = {lat: {{ config('voyager.googlemaps.center.lat') }}, lng: {{ config('voyager.googlemaps.center.lng') }}};`

To fix this you need in the "voyager/resources/views/partials/coordinates.blade.php" change this:
`var center = {lat: {{ config('voyager.googlemaps.center.lat') }}, lng: {{ config('voyager.googlemaps.center.lng') }}};`
To this:
```
        @forelse($dataTypeContent->getCoordinates() as $point)
            var center = {lat: {{ $point['lat'] }}, lng: {{ $point['lng'] }}};
        @empty
            var center = {lat: {{ config('voyager.googlemaps.center.lat') }}, lng: {{ config('voyager.googlemaps.center.lng') }}};
        @endforelse
```

**Comment by fletch3555** [comment]
Instead of suggesting code changes in issues, please create a pull request with the changes made.  It's much easier for us to understand what you're trying to do, and allows us to simply accept/merge it.

**Comment by iboved** [comment]
Ok. I have created a Pull Request #2059
