### ISSUE TITLE
SSR together with search/filtering raises exception

### ISSUE THREAD

**Issue by mpenna** [thedevdojo/voyager#2054]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.5
- PHP Version: 7.1.0
- Database Driver & Version: mysql 5.7.16-0ubuntu0.16.04.1

### Description:
Server side pagination works fine. Searching / filtering also works fine. Problem arises when trying to use both - or at least when trying to paginate when any remnants of a previous search are still lingering around on the query string.  At least that's what the problem looks like it is.

### Steps To Reproduce:
When browsing a BREAD, once you try to paginate having previously searched for anything (even if the search has already been cleared out), an exception is raised at the Illuminate/Support/helpers.php (line 547) saying that htmlspecialchars() expects parameter 1 to be string, array given. 

The query string giving this error looks like the following: 

/admin/users?s%5Bkey%5D=invitation_id&s%5Bfilter%5D=equals&page=2

Note: inviation_id is a field on my users table and the searching functionality is working OK on this and other fields.

**Comment by fletch3555** [comment]
Voyager does not currently support search with server-side pagination enabled.  This is something we're looking to rectify.  There have been a number of issues requesting it.
