### ISSUE TITLE
Voyager is great ! Do you have a plan to support multi database?

### ISSUE THREAD

**Issue by kideny** [thedevdojo/voyager#2055]
- Laravel Version: 5.5.13
- Voyager Version: 1.0.5
- PHP Version: 7.1
- Database Driver & Version: mysql5.7

### Description:

I use voyager to create a admin. but my other database can't use bread builder. 

i hope voyager to support multi database and mongodb.

**Comment by fletch3555** [comment]
Supporting multiple databases is a fairly complex task, but it's something we're looking into.

MongoDB will likely not be supported anytime soon (unless someone from the community builds it).  It's not officially supported by Laravel, and none of the Voyager maintainers have significant experience with Mongo.

**Comment by kideny** [comment]
Thank your very much !
