### ISSUE TITLE
menu or button name dispaly abnormal

### ISSUE THREAD

**Issue by tinywinds** [thedevdojo/voyager#2056]
- Laravel Version: 5..4
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

### Description:

After I upgrade from version 0.11 to version 1.0, all the menu or button name become abnormal , such as "voyager.dimmer.user_link_text" , "1 voyager.dimmer.user" .  I removed the voyager and reinstall again, problem is still there.

**Comment by fletch3555** [comment]
Voyager 1.0 ships with significant CSS/JS changes (e.g. they're all compiled by mix instead of being included individually).  You'll need to force-publish voyager's assets (`artisan vendor:publish --force --provider=TCG/Voyager/VoyagerServiceProvider`)

**Comment by tinywinds** [comment]
@fletch3555  Thanks for your reply , but your solution does not work for me.

**Comment by tinywinds** [comment]
@fletch3555  , I started a new project based laravel 5.4 , with the voyager 1.0 installed,  then compare with the old project and I found the old project do not have some folder and files in the path:  /resource/lang.   I copied them from the new project , menu name is ok now.

**Comment by fletch3555** [comment]
That path should have been published with the command I provided previously.  I'm not sure why it didn't work.
