### ISSUE TITLE
How to override function on TCG\Voyager\Http\Controllers\Controller.php

### ISSUE THREAD

**Issue by riquemuramoto** [thedevdojo/voyager#2058]
- Laravel Version: 5.4
- Voyager Version: 1.0.5
- PHP Version: 7.1.7

### Description:
I trying to add a option when uploading an image.
I want to detect if the uploading image is an .png, then convert that image and create a .jpg. Like the funcionality to make a thumbnail.
I want to know if there's a way to override only the function getContentBasedOnType on TCG\Voyager\Http\Controllers\Controller.php.

Also, while i was looking on this function, i found some issues:
- The "quality" option, that i can put on Additional Field Options in the Bread Builder for an image attribute, is not working when upload a .jpg image. It's hardcoded the value "75".
- When i not set a "resize" option in the same Additional Field Options for an image attribute and i put the "thumbnails" option with "scale" option, it's scaling the image based on a width of 1800px, not based on the original image width.
*Ex: if i not set the "resize" option, upload an image of 1000x1000, with an option to make a thumbnail with scale of 50%, it will create an image with dimensions 900x900, when it's supposed to make an 500x500 image.

**Comment by fletch3555** [comment]
You could extend that class and override the function, but you'll have to also override all other controllers to point to the new extended controller,  Instead, I would just override that method in the controller you need it in. Once you've extended the controller, you can make Voyager use it by updating the value in the BREAD editor.

**Comment by riquemuramoto** [comment]
@fletch3555 Great idea man, that works.

I set the bread table to use a custom controller and make that controller extends the VoyagerBreadController, now i can override the getContentBasedOnType function.

Nice and clean solution, thanks!
