### ISSUE TITLE
Menu title display error

### ISSUE THREAD

**Issue by tinywinds** [thedevdojo/voyager#2061]
- Laravel Version: 5..4
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

### Description:

After I upgrade from version 0.11 to version 1.0, all the menu or button name become abnormal , such as "voyager.dimmer.user_link_text" , "1 voyager.dimmer.user" .  I removed the voyager and reinstall again, problem is still there.

**Comment by fletch3555** [comment]
Please don't duplicate issues.  We can just reopen your other one.
