### ISSUE TITLE
Proper way: JSON string

### ISSUE THREAD

**Issue by rexdarel** [thedevdojo/voyager#2063]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
I needed to add a select dropdown for my gender and civil status in users table. I do not know what is the proper way to add a JSON. I want the first choice to be "Select gender" and empty value which prompts the user to select "Male" or "Female" what I did so far.

`{
    "default": "",
    "options": {
        "": "",
        "Male": "Male",
        "Female": "Female"
    }
}`

**Comment by masumonline** [comment]
try this

 {
    "default" : "option1",
    "options" : {
        "option1": "Option 1 Text",
        "option2": "Option 2 Text"
    }
}

for null value

{
    "null": "Nothing"
}

**Comment by emptynick** [comment]
The question was answered. Moreover its described in our [docs](https://voyager.readme.io/docs/additional-field-options#section-drop-down)
To force the user to select a value, use [validation](https://voyager.readme.io/docs/validation)
