### ISSUE TITLE
Is there a way to get the current login user name in JSON. 

### ISSUE THREAD

**Issue by masumonline** [thedevdojo/voyager#2067]
- Laravel Version: 5.5.18
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
Is there a way to to add current loin user name on text field. so when a user fill a form there user name can add on the filed automatic. 

I know on laravel i can use Auth::user()->name to get current user but how can i use it in brade options.

This is a Question.

**Comment by rppudo** [comment]
{{Auth::user()->name}}

**Comment by fletch3555** [comment]
I'm not sure what this has to do with Voyager.  Are you looking to have certain fields pre-fill with the user's name? If so, That's not something Voyager currently supports, and it's very unlikely we'll merge that into Voyager, but you're free to make it work for your own project.

Also, "how do I..." questions are best asked on our slack group.  It's a lot easier to hold discussions there.
