### ISSUE TITLE
multiple filters for BREAD

### ISSUE THREAD

**Issue by hick** [thedevdojo/voyager#2073]
- Laravel Version: 5.5.18
- Voyager Version: 1.0.5
- PHP Version: 7.0.12
- Database Driver & Version: mysql 5.7.12

### Description:

I found single field filter in the current BREAD index page, we often need to filter the data table with serveral fields,   like the python project flask-admin doing :  http://examples.flask-admin.org/sqla/simple/admin/post/

Is there any plan for this function?   thx

**Comment by gdevdeiv** [comment]
That would be handy.. something like the one in Adminer Editor would be cool. But with just JS, without having to hit the "Select" button each time.

https://gyazo.com/fe8c396935ac42d5324def0e7f075881

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/4216
