### ISSUE TITLE
Pagination link error

### ISSUE THREAD

**Issue by tinywinds** [thedevdojo/voyager#2079]
- Laravel Version: 5.4.*
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version: mysql 5.6

### Description:

The default page(page 1) is ok. but something went wrong when clicking the other page link. 
error shows : 
htmlspecialchars() expects parameter 1 to be string, array given .....

### Steps To Reproduce:

the pagination link shows like "/admin/myproduct?s[value]=/admin/myproduct/page=2",   I type the link "/admin/myproduct/page=2" , page shows as expectation.

**Comment by emptynick** [comment]
This was fixed in #2246
