### ISSUE TITLE
run "composer require tcg/voyager" killed

### ISSUE THREAD

**Issue by SimonWang2014** [thedevdojo/voyager#2080]
- Laravel Version: 5.5.18
- Voyager Version: v1.0
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.7.20

### Description:

when run `composer require tcg/voyager`, it shows :
```
$ composer require tcg/voyager
Using version ^1.0 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
```
and it also `killed` when run with `sudo ` .

Then I run `php artisan voyager:install` , it shows
```
$ php artisan voyager:install
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "voyager" namespace.
```

**Comment by gdevdeiv** [comment]
Your process is just being killed by the system. That used to happen to me in an old Virtualmin/Webmin server, it was just a setting I could change.

Can you give us more details about your current server setup?

**Comment by SimonWang2014** [comment]
My server is Amazon EC2. The System is Ubuntu 16.04.3 LTS.

```
$ df -i
Filesystem     Inodes  IUsed  IFree IUse% Mounted on
udev           125312    429 124883    1% /dev
tmpfs          126801    498 126303    1% /run
/dev/xvda1     983040 183092 799948   19% /
tmpfs          126801      1 126800    1% /dev/shm
tmpfs          126801      3 126798    1% /run/lock
tmpfs          126801     16 126785    1% /sys/fs/cgroup
tmpfs          126806      4 126802    1% /run/user/1000
```

**Comment by gdevdeiv** [comment]
Okay, what about the software on it? Are you using any specific control panel? Are you using a custom shell?

**Comment by fletch3555** [comment]
This is most likely not an issue with Voyager, but with your system or composer.  Unfortunately, we won't be much help on that.  I would encourage you to ask on larachat, the laracasts forums, or any composer-
 or laravel-specific community
