### ISSUE TITLE
Upgrading to voyager 1.* everything has voyager. prepended!

### ISSUE THREAD

**Issue by cadmicro** [thedevdojo/voyager#2083]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.6
- PHP Version: 7.0

### Description:
I just upgraded to the latest voyager version from a 0.11 version and I followed the instructions however, after the ugprade all of the buttons and titles look like:

![untitled](https://user-images.githubusercontent.com/24463380/32012573-491b8376-b986-11e7-84dc-c7f1493e1491.png)

**Comment by akazorg** [comment]
@cadmicro you have to publish voyager assets, or maybe if you have custom views, verify your code.

**Comment by fletch3555** [comment]
The command you want is: `artisan vendor:publish --force --provider=TCG/Voyager/VoyagerServiceProvider --tag=lang`

Some people have reported issues when publishing the language assets.  A workaround for this is to manually copy the lang folder (`vendor/tcg/voyager/publishable/lang`) to your app (resources/lang).

This should resolve your issue
