### ISSUE TITLE
[ERROR] Undefined variable: output

### ISSUE THREAD

**Issue by FlorisBoom** [thedevdojo/voyager#2084]
- Laravel Version: 5.4.*
- Voyager Version: 1.0
- PHP Version: 5.6.4
- Database Driver: MySQL

So did a clean install of laravel with voyager and when trying to create a admin I get the following error when trying to fill in a password 

![voyager error](https://user-images.githubusercontent.com/33102308/32019597-0b557ebe-b9ce-11e7-91de-2c1dc0e10abd.png)

Any idea why?

**Comment by fletch3555** [comment]
I don't think we have a variable named output in that command... seems really odd, but might be an issue with laravel. If anyone else has time to dig into this, I'd appreciate it

**Comment by SAM-AEL** [comment]
do a clean install of laravel 5.5 and install voyager after a composer update. if you facing error still.try to load dummy data instead

**Comment by FlorisBoom** [comment]
Did another clean install and loaded it in with dummy data which worked fine, but running php artisan voyager:admin .... --create still causes the same undefined variable error at password.

I also tried it on a different windows PC, mac machine and different CLI's but no luck.

**Comment by SAM-AEL** [comment]
@FlorisBoom im using the latest of laravel and voyager and i just tried it out.. i get no error like that. i have no idea about that output variable.. could be some issue on your end.

**Comment by vaggelis2018** [comment]
@SamSolomon0611 Laravel 5.5 need php 7.0.0 .
https://laravel.com/docs/5.5
Can you try it with newer php version?
Also check if you are meeting all the requirements.

**Comment by FlorisBoom** [comment]
@vaggelis2018 
So I just tried doing it locally using laravel 5,4 instead of doing it on the shared hosting server and everything went fine. So the problem has to be related with the shared hosting I guess.

**Comment by vaggelis2018** [comment]
@FlorisBoom Ask your host provider if all requirements are referenced in the link i sent you in the previous commemt are met

**Comment by FlorisBoom** [comment]
@vaggelis2018  All of the requirements for laravel 5.4 are met, since I'm using the shared hosting provided by my school I can't change the php version so using laravel 5.5 wont work. So it's basically out of my reach. Ill just have to work around it by exporting and importing databases from my localhost to the shared hosting.

Thx for the help anyways, and uhmm I don't know how to close issues yet so if someone would be so kind to... :D
