### ISSUE TITLE
Datatable view

### ISSUE THREAD

**Issue by mohammed-elattar** [thedevdojo/voyager#2085]
I created a new model with around 16 column , i don't want to add all of them i the view of the datatable ,
i.e i just want to show 5 columns in the datatable view .
Could you please help me ??

**Comment by gdevdeiv** [comment]
You can control which fields will be shown in the Datatables. First, go to the "Database" menu (on the left navigation bar), find your model BREAD, click on Edit BREAD, and there you can see the list of fields you have. Each one has checkboxes (Browse, Read, Edit, etc). The BROWSE checkbox is the want you are looking for.

ON -> Will be shown in the table
OFF -> Won't

:)

**Comment by akazorg** [comment]
Great answer @gdevdeiv thanks. Closing issue.

**Comment by mohammed-elattar** [comment]
Thanks for your support
