### ISSUE TITLE
Image, File fields in BREAD don't work.

### ISSUE THREAD

**Issue by sergbbb** [thedevdojo/voyager#2090]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.6
- PHP Version: 7.1
- Database Driver & Version:

Ufter update from Voyager 1.0.5 , Image, File fields in BREAD don't work. They just NULL in database.  And there are no files in storage

**Comment by sergbbb** [comment]
To fix file upload:

src/Http/Controllers/Controller.php:57

`if (!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox') {`

**Comment by sergbbb** [comment]
Also 
vendor/tcg/voyager/resources/views/bread/browse.blade.php:143

`<a href="{{ Storage::disk(config('voyager.storage.disk'))->url($file->download_link) ?: '' }}" target="_blank">`

There was 'or' instead ?: , and returned bool


vendor/tcg/voyager/resources/views/bread/browse.blade.php:144
`{{ $file->original_name }}`

**Comment by sergbbb** [comment]
vendor/tcg/voyager/resources/views/formfields/file.blade.php:4

`<br/><a class="fileType" target="_blank" href="{{ Storage::disk(config('voyager.storage.disk'))->url($file->download_link) ?: '' }}"> {{ $file->original_name ?: '' }} </a>`

**Comment by fletch3555** [comment]
@sergbbb, if you have a solution, please open a pull request with the changes.
