### ISSUE TITLE
"Model Class does not exist. Please create Model before creating relationship." on creating relationships.

### ISSUE THREAD

**Issue by matheuscandido** [thedevdojo/voyager#2091]
Hey,
I'm geting a "Model Class does not exist. Please create Model before creating relationship." error on a red alert every time I try to create a relationship, on both ways of it.

I've already created the tables and breads for both entities, and the models are created on the app folder.

What could be missing or wrong?

**Comment by fletch3555** [comment]
Resolved via slack.  Model class namespace was missing.

**Comment by adeguk** [comment]
I have the same error and my model class namespace is not missing

**Comment by fletch3555** [comment]
@adeguk, please open your own issue or comment in Slack looking for help.

**Comment by Siva-8990** [comment]
Hey,
I'm geting a "Model Class does not exist. Please create Model before creating relationship." error on a red alert every time I try to create a relationship, on both ways of it.

I've already created the tables and breads for both entities, and the models are created on the app folder.

What could be missing or wrong?

**Comment by fletch3555** [comment]
Please read my previous comment

**Comment by adeguk** [comment]
@Siva-8990 that error occurs when you try to create a relationship between tables without specifying the model class for the other table. If you carefully looked at the form inputs, one of the asked for the model

**Comment by acromeu** [comment]
Got the same problem, recommendations here help. Just don't forget to put the namespace in front of the model in the field, meaning: instead of putting the name of the model "Model", put "App\Model".

**Comment by liboub** [comment]
I got the same problem , I try to add a relationship, voyager say the model don't exist but he exist in real .
I don't understand , i make foreign key in database and it still the same.

**Comment by adeviss2** [comment]
It happened to me as well but the problem was that instead of putting App\Model, I used App/Model and this is wrong... the correct way is with "\" backslash not forward slash. Thanks

**Comment by masoma123** [comment]
Convert the name of the table into a plural form.

**Comment by petryca95** [comment]
To solve this problem, you need to add full path of Model(there is a field which tells you "Full qualified model name...". :)

**Comment by fletch3555** [comment]
Please don't comment on really old closed issues. This was for a much older version and has been closed for 18 months now
