### ISSUE TITLE
Need some help 

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#2095]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.6
- PHP Version: 7.1
- Database Driver & Version:

How to add style to menu ? any help appreciated ..

![error](https://user-images.githubusercontent.com/13164167/32092541-a225dd76-bb2b-11e7-8cca-cd64c1a27f74.jpg)

**Comment by akazorg** [comment]
Hi, try updating assets:
`php artisan vendor:publish --tag='voyager_assets' --provider='TCG\Voyager\VoyagerServiceProvider' --force`

**Comment by rddewan** [comment]
Hi
Thanks for your reply after i run your command i get Publishing complete. but nothing change on my UI
F:\xampp\htdocs\GenesisFMS>php artisan vendor:publish --tag='voyager_assets' --provider='TCG\Voyager\VoyagerServiceProvider' --force
Publishing complete.

Below is my code

> <div class="side-menu sidebar-inverse">
    <nav class="navbar navbar-default" role="navigation">
        <div class="side-menu-container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ route('voyager.dashboard') }}">
                    <div class="logo-icon-container">
                        <?php $admin_logo_img = Voyager::setting('admin.icon_image', ''); ?>
                        @if($admin_logo_img == '')
                            <img src="{{ voyager_asset('images/logo-icon-light.png') }}" alt="Logo Icon">
                        @else
                            <img src="{{ Voyager::image($admin_logo_img) }}" alt="Logo Icon">
                        @endif
                    </div>
                    <div class="title">{{Voyager::setting('admin.title', 'VOYAGER')}}</div>
                </a>
            </div>

            <div class="panel widget center bgimage"
                 style="background-image:url({{ Voyager::image( Voyager::setting('admin.bg_image'), config('voyager.assets_path') . '/images/bg.jpg' ) }}); background-size: cover; background-position: 0px;">
                <div class="dimmer"></div>
                <div class="panel-content">
                    <img src="{{ $user_avatar }}" class="avatar" alt="{{ Auth::user()->name }} avatar">
                    <h4>{{ ucwords(Auth::user()->name) }}</h4>
                    <p>{{ Auth::user()->email }}</p>

                    <a href="{{ route('voyager.profile') }}" class="btn btn-primary">{{ __('voyager.generic.profile') }}</a>
                    <div style="clear:both"></div>
                </div>
            </div>

        </div>

        {!! menu('main')!!}
    </nav>
</div>

**Comment by fletch3555** [comment]
Wait, what file is that code in?  Are you overriding the `admin_menu` view...? Why? Why not just add your entries to it? All styling is specific to the menu, so you'll need to handle that yourself if you're not using the voyager admin menu

**Comment by fletch3555** [comment]
I just realized this is a duplicate of #2049.  Please don't open duplicate issues.
