### ISSUE TITLE
Can't Input role_id when create/update Users

### ISSUE THREAD

**Issue by detlab** [thedevdojo/voyager#2096]
- Laravel Version: 5.5
- Voyager Version: ^1.0
- PHP Version: 7.0.13
- Database Driver & Version: MySQL

When create/update users, role_id can't be added into database.
Then in browse users table, the "role" column display "no results"

![norole](https://user-images.githubusercontent.com/33146715/32092895-86565b68-bb24-11e7-98cf-91817559b12c.JPG)

sorry for bad english

**Comment by FulgerX2007** [comment]
Hey.
I have the same problem.
Not only roles. But in all the fields where the relationship is not updated is used.

![sketch](https://user-images.githubusercontent.com/2111375/32124550-d91ed8f6-bb70-11e7-8485-5ed624b00b06.png)

![sketch2](https://user-images.githubusercontent.com/2111375/32124562-e3f743c6-bb70-11e7-9439-87923a44ef14.png)

![sketch3](https://user-images.githubusercontent.com/2111375/32124569-e903f328-bb70-11e7-9e76-fa60e92c532c.png)

**Comment by devenrdayadav99** [comment]
yes i also have same issue please help someone

**Comment by leonardyhuang** [comment]
Hi All,

I managed to "hack" function `insertUpdateData` in `TCG\Voyager\Http\Controllers\Controller.php`:
```php
if ($row->type === 'relationship' && $options->type !== 'belongsToMany') {
    $field = $row->field;
    $row->field = @$options->column;

    $request->request->add([
        $row->field => $request->get($field)
    ]);
}
```
Original code:
```php
if ($row->type == 'relationship' && $options->type != 'belongsToMany') {
    $row->field = @$options->column;
}
```

Now, i'm able to create and update users with the roles correctly:
![2017-10-29 14_45_51-viewing users](https://user-images.githubusercontent.com/22125998/32141313-378353fc-bcb8-11e7-8f58-40c58703c4d3.png)

Advise by the team is still needed though.

**Comment by detlab** [comment]
Hi @leonardyhuang, your "hack" code work for me. Thank you

**Comment by OliverVin** [comment]
I have the same bug .

**Comment by OliverVin** [comment]
hi @leonardyhuang , your code work partly, update successfully, but show has bug . Always show first item If select other item .

**Comment by leonardyhuang** [comment]
@OliverVin , I believe that this is a different "issue".
The function that I hacked is only used when saving (insert or update) data.
You can try even without the "hack", it always chooses the first role (`admin` in my case).

**Comment by OliverVin** [comment]
@leonardyhuang  ,yeah you are right, it is another bug . @fletch3555    Edit Mode ,  always show first item whatever choose which .

**Comment by varbark** [comment]
I found  this commit make this error happen
https://github.com/the-control-group/voyager/commit/b9fa2a2abf55d3192db09b1510076b19ff9b0416#diff-c154b0a3fe00aa82b0eef7312625cecd
so, the temporary way to fix it , is to publish a relationship in your `resources/views/vendor/voyager/formfields/relationship.blade.php` , 
and put the code back, which is : 

`@php $relationshipField = (@$options->type=="belongsToMany" ? $row->field : @$options->column) @endphp`

**Comment by OliverVin** [comment]
@varbark Perfect , it works .

**Comment by leonardyhuang** [comment]
Solution by @varbark is a better solution 👍
But, is there any impact on the _belongsToMany relationship functionality_?
Maybe @tnylea can advise us.

**Comment by OliverVin** [comment]
@leonardyhuang do you know, new relationship setting mode , how to use default value ?
{
    "default": "0",
    "options": {
        "0": "--- None ---"
    }
}

**Comment by leonardyhuang** [comment]
@OliverVin , i'm not sure about this, sorry.
I'm new to Voyager, still learning how to use it.
Maybe others can answer your question.

**Comment by OliverVin** [comment]
ok， but thanks . 😁 @leonardyhuang

**Comment by InnerRam** [comment]
the problem was given in vcg version 1.0.6, with 1.0.5 it was not happening, thank you very much for the "hack" Leo, works fine. Regards!

**Comment by nicolabavaro** [comment]
@varbark Thanks, it works!

**Comment by marktopper** [comment]
Are people still having issues with this or can I close this?

**Comment by fletch3555** [comment]
Given its age, I'm thinking close.
