### ISSUE TITLE
Cannot update BREAD

### ISSUE THREAD

**Issue by NicolaeCasir** [thedevdojo/voyager#2099]
- Laravel Version: 5.4.*
- Voyager Version: 1.0.6
- PHP Version: 7.0.22
- Database Driver & Version: 10.0.31-MariaDB

### Description:
I want to update some data and get 
`Argument 3 passed to TCG\Voyager\Events\BreadDataChanged::__construct() must be an instance of TCG\Voyager\Events\string, string given`

Deleted tcg folder from vendor, reinstalled... nothing((
Screen of error: https://i.imgur.com/iIWaqNR.png

**Comment by sergbbb** [comment]
Same with PHP 5.6. Try PHP 7.1

**Comment by NicolaeCasir** [comment]
And Media is blank page(((

**Comment by kozguven** [comment]
i get same erro. can you fix this?  what can i do?

**Comment by NicolaeCasir** [comment]
I got this error wfter update to the latest version from github.. solved my problem by restoring to the previous version :)))

**Comment by akazorg** [comment]
Closing since it's solved.

**Comment by fletch3555** [comment]
Reverting to the previous version is not a solution. Reopening
