### ISSUE TITLE
Error when starting the app

### ISSUE THREAD

**Issue by willmkt** [thedevdojo/voyager#21]
Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /Applications/MAMP/htdocs/voyager/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 62 and defined in /Applications/MAMP/htdocs/voyager/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 103

**Comment by afsardo** [comment]
Pull request #19 solves this ^^

**Comment by joekrump** [comment]
The pull request #19 fixed the issue for me. Thanks afsardo!

**Comment by tnylea** [comment]
Just merged this into the latest version. Thanks @afsardo !

Going to write some tests today to prevent this from happening again.
