### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by kirtangajjar** [thedevdojo/voyager#210]
More documentation on how to customize the package would be appreciated. 

Also, behaviour of menu and how to call them i.e. using `Menu::display('name')` should be documented

**Comment by marktopper** [comment]
Indeed, I will work on this once I get the time. However I'm still open for pull requests to the [documentation](https://github.com/the-control-group/voyager/blob/gh-pages/docs/Readme.md).

**Comment by hugosvent** [comment]
@kirtangajjar https://voyager-cheatsheet.ulties.com/
maybe this can help

**Comment by marktopper** [comment]
@hugosvent I need to set some time off to remake that for `v0.11`.

**Comment by marktopper** [comment]
Btw, closing this since the menu section have been documented.
