### ISSUE TITLE
Creation migration file when I add a field in a table using database manager

### ISSUE THREAD

**Issue by Kenneth058** [thedevdojo/voyager#2102]
- Laravel Version: 5.513
- Voyager Version: 1.0.4
- PHP Version: 7.0.22
- Database Driver & Version: MySql 14.14

### Description:

When I add a new field in a table using database manager, voyager doesn't create the migration field with the change description. So when I try to download my files to other computer to continue with the development, it fails because when I run my migrations files, it doesn't find the migration with the new field.

### Steps To Reproduce:

Add a new field in a table using database manager.

**Comment by akazorg** [comment]
hi @Kenneth058, this is a known issue that we have to sort out.
Generating a migration file for every DB change requires some work, so at the moment this feature is disabled.

Thanks for your post.
