### ISSUE TITLE
How to use voyager slugify in my models

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#2104]
- Laravel Version: 5.5
- Voyager Version: 1.0

I would like to use the slugify helper of voyager inside my model, how can i use it?

**Comment by akazorg** [comment]
The slugify component of Voyager works on JS. What are you trying to do?

**Comment by donmbelembe** [comment]
my clients will be able to post an article on a page that i have created myself (outside of voyager admin) and i want to slugify the title.

I was thinking instead of installing another package I could use the one used by voyager

**Comment by akazorg** [comment]
You can follow [Posts View](https://github.com/the-control-group/voyager/blob/master/resources/views/posts/edit-add.blade.php#L157) as an example. Apply the same logic.
