### ISSUE TITLE
settings saved error

### ISSUE THREAD

**Issue by jouniikaheimo** [thedevdojo/voyager#2106]
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Saved setting got error
https://screenshots.firefox.com/OhxtqPjr953u8cVR/tuki.netstreet.org that screen shot tell more..

**Comment by fletch3555** [comment]
That's a permissions error.  Please verify that you've updated to the latest version (looks like you're a few minor versions back), and that you've published all assets (using `artisan vendor:publish`).  Settings now make use of the full suite of BREAD permissions (`browse_setting`, `read_setting`, `edit_setting`, `add_setting`, `delete_setting`), so if you don't have all of those, you will need to create them and add them to your role.

If this doesn't work for you, please let me know and we'll reopen the issue.
