### ISSUE TITLE
i have issue on live server on voyager 

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#2112]
- Laravel Version: #.#.#     5.3 and 5.4
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
i have used laravel voyager as admin it works perfect at localhost while on live server when i upload image it give me the error which is given below... kindly help me
MissingDependencyException in ImageManager.php line 133:
PHP Fileinfo extension must be installed/enabled to use Intervention Image.

**Comment by fletch3555** [comment]
That error tells you exactly what's wrong and how to fix it, PHP on your remote server is missing the `fileinfo` extension.  This is not an issue with Voyager.  You'll have to work with your hosting provider to get the extension installed if you don't have access to do so yourself.
