### ISSUE TITLE
Failed to load voyager.js

### ISSUE THREAD

**Issue by cncal** [thedevdojo/voyager#2118]
Laravel Version: 5.4.33
Voyager Version: latest
PHP Version: 7.0.4
Database Driver & Version: Mysql 5.7
Description:
I can not load voyager.js which is on [s3.amazonaws.com](https://s3.amazonaws.com/laravelvoyager/voyager.js). Could anybody download and send it to me with email (my email address: flycalvin@qq.com)? I would much appreciate it.

**Comment by fletch3555** [comment]
You're going to have to provide more information... What do you mean by voyager.js? We don't host anything on s3, so I'm not sure what you're referring to.

**Comment by cncal** [comment]
I think code is [here](https://github.com/the-control-group/voyager/blob/master/resources/assets/js/load-remote.js) and everytime I reload my site, the error as following shows up.  

> Request URL:https://s3.amazonaws.com/laravelvoyager/voyager.js   
Request Method:GET   
Status Code:404 Not Found

**Comment by r21gh** [comment]
this [url](https://s3.amazonaws.com/laravelvoyager/voyager.js) is just responsible for showing welcome to Voyager message in console.

**Comment by cncal** [comment]
Ok, I get it. Thanks@RezaGhanbari.
