### ISSUE TITLE
New Roles doesn't get assigned to user( role_id in users table set to null)

### ISSUE THREAD

**Issue by DrudgeRajen** [thedevdojo/voyager#2119]
- Laravel Version: 5.5.19
- Voyager Version: 1.0^
- PHP Version: 7.0.22
- Database Driver & Version: Mysql & 14.14

### Description:
I create a new role and tried to assign to the new user , it works perfectly but when i tried to do login with the new user credentials i got logged in but i got error. Please check the screenshot
![voyager](https://user-images.githubusercontent.com/4613510/32159801-0ccab8d4-bd77-11e7-856d-380244247a96.png)

### Steps To Reproduce:
1) Login with your admin credentials
2) Make a new role
3) Make a new user and assign the role that you have created in step 2
4) Logout and Login again with the new user credentials.

**Comment by marciio14** [comment]
The same problem here :(

**Comment by rexdarel** [comment]
Same problem here... Value in role_id in users table is set to NULL

**Comment by aleex1848** [comment]
Same issue here, but also with existing roles. Did a fresh install yesterday, added new User with admin role. But role_id was null in users table.

Maybe this is somehow related with this:
https://github.com/the-control-group/voyager/issues/2123
?
Seems like similar symptoms.

**Comment by sylmz** [comment]
If the attiribute(role_id) of data is set then probably your problem will be solved. because request does not have role_id parameter when posted. it has user_belgonsto_role_relationship instead of role_id.
Changes in vendor/tcg/voyager/src/Http/Controllers/Controller.php
```
if ($row->type == 'relationship' && $options->type != 'belongsToMany') {

                $field_value=$request->input($row->field);
                $row->field = @$options->column;
                $data->{$row->field} = $field_value; //for updating user: $data->role_id  = $request->input('user_belgonsto_role_relationship');
            }
```

**Comment by DrudgeRajen** [comment]
@sylmz  I don't think that's a good way to do this . @marktopper Would you please guide us on this ?

**Comment by DrudgeRajen** [comment]
#2141

**Comment by solstyc** [comment]
it works in version 1.0.5.. i'm just using that version till the bug is fixed

**Comment by DrudgeRajen** [comment]
@solmel  the bug is fixed in this #2141 pull request. I hope it will me merged soon.

**Comment by solstyc** [comment]
@DrudgeRajen thanks worked for me

**Comment by fletch3555** [comment]
#2141 has been merged.  Closing
