### ISSUE TITLE
require tcg/voyager problem

### ISSUE THREAD

**Issue by omerogluberke** [thedevdojo/voyager#212]
- Laravel Version: 5.3.#

### Description: Problem 1: - İntervention/image 2.3.8 requires ext-fileinfo -> the request PHP extension fileinfo is missing  from your system
İntervention/image 2.3.7...
İntervention/image 2.3.6...
...
..
.
İnstallation failed reverting ./composer.json to its original content.
How I can solve this problem ?

**Comment by marktopper** [comment]
You will have to add `fileinfo` PHP component to your PHP environment.

If your on a Windows machine you can open up your `php.ini` and locate `;extension=php_fileinfo.dll`, then remove the starting `;`.
After that save and restart PHP (and Apache if used)

**Comment by omerogluberke** [comment]
Thanks its done.
