### ISSUE TITLE
Some issues about image typ or multiple image type

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#2122]
- Laravel Version: #.#.#
- Voyager Version: 1.0.6
- PHP Version:
- Database Driver & Version:

### Description:
1. multiple images type, if delete one image, the disk not delete !
2. image type, if replace one image, the disk old not delete !
3. the name of image uploaded maybe not right .   If i upload one image named test.jpg,  right name should link Me6pROzIAAB41i7JVKEU.jpg , but now name still is test.jpg !

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3240
