### ISSUE TITLE
BREAD and belongsTo relationship not working on Save

### ISSUE THREAD

**Issue by jperazzo** [thedevdojo/voyager#2123]
- Laravel Version: 5.5.*
- Voyager Version: ^1.0
- PHP Version: 7.1.9
- Database Driver & Version: MySQL

### Description:
When I create a belongsTo relationship in BREAD and I try to create a new record and hit SAVE, i get this error
![captura de pantalla 2017-10-30 a la s 13 08 35](https://user-images.githubusercontent.com/1021032/32181613-8c6b6510-bd73-11e7-808c-9615a5b433b4.png)

This my **Anteojo** Model

![captura de pantalla 2017-10-30 a la s 13 18 31](https://user-images.githubusercontent.com/1021032/32182218-ee4de0d6-bd74-11e7-88e1-9b05ae0f42ba.png)

### Steps To Reproduce:
1. Create a **belongsTo** relationship like _B > belongsTo > A_
![captura de pantalla 2017-10-30 a la s 13 02 16](https://user-images.githubusercontent.com/1021032/32181256-ae026652-bd72-11e7-86cc-65cdafd57362.png)

2. Try to add a new **B** record
![captura de pantalla 2017-10-30 a la s 13 02 49](https://user-images.githubusercontent.com/1021032/32181255-adc2f684-bd72-11e7-9a95-8a6b82354cb5.png)

3. Get the error!

**Comment by fletch3555** [comment]
That issue is in your database.  Your modelo_id field needs to either be nullable or have a default value set.

**Comment by quantumass** [comment]
no the problem is not in the database it's in voyager

**Comment by quantumass** [comment]
modelo_id is not included in the query

**Comment by jperazzo** [comment]
it was working OK in a previous version of voyager @fletch3555 @quantumass

**Comment by quantumass** [comment]
I re-installed the whole package and the problem now not only in the foreign keys it is also in the image fields 
if I change the type of the column to text or number ... it will work  @jperazzo

**Comment by jperazzo** [comment]
So I should change the type of the "modelo_id" column or something else?

**Comment by jperazzo** [comment]
@quantumass if I edit one created from tinker, it's working OK. The thing is when I create a new one.

**Comment by aleex1848** [comment]
I just had the same issue.
My Models were still blank, i just used voyager to make the tables, models and BREAD. Nothing else.
When saving a belongsTo relationship i got the same error as @jperazzo 
The foreign key value was not part of the sql insert.

Then i changed my models, added the relationships and added the fillable array. The fillable array has any fields used in the create form.
Now it's working.

Edit:
Well, it saves.
But value is always 0. I does not save the value selected from select field.

**Comment by dennis-fransen** [comment]
I just had the same issue, and can confirm it is introduced in 1.0.6. 
There was an update to the controller.php, to skip fields not in the request. 
Relationship fields are not in the request, making the controller skip this fields.

**Comment by quantumass** [comment]
Guys please how can I solve the problem now ? I have to give the project to my teacher

**Comment by dennis-fransen** [comment]
@quantumass, lock version to 1.0.5, that seems to be working for me

**Comment by jperazzo** [comment]
@quantumass there is another workaround, by using the option details when you edit de BREAD.
![captura de pantalla 2017-11-01 a la s 12 05 50](https://user-images.githubusercontent.com/1021032/32281376-6a32d380-befd-11e7-8aa5-d2cbb405968b.png)


You must change the name of the field in the model to match camelcase the name of that field.
In my case the field I'm using to save the id of the other model is _modelo_id_ so the function should be **modeloId**.
![captura de pantalla 2017-11-01 a la s 12 08 07](https://user-images.githubusercontent.com/1021032/32281366-63a1c350-befd-11e7-94f5-b88ac2896363.png)

**Comment by bbredewold** [comment]
This is a major bug! Spend a couple of hours debugging, and finally found it's a bug as described here...

Looks like this change in relationship.blade.php makes the problem:
https://github.com/the-control-group/voyager/pull/2033/files#diff-c154b0a3fe00aa82b0eef7312625cecd

It changes the relationship field in my app from:
`<select class="form-control select2" name="text_group_id">`
to
`<select class="form-control select2" name="text_belongsto_text_group_relationship">`
And this goes totally wrong, and get stripped out of the code.

@marktopper Could this be the origin of the problem?

**Comment by DrudgeRajen** [comment]
#2141

**Comment by fletch3555** [comment]
#2141 has been merged. Closing

**Comment by AlterwebStudio** [comment]
As was written before, the problem is database in my opinion. After db update you can meet this issue, the only thing you have to do is allow nullable to all table columns that potencialy could receive null values - yes, Voyager doesn't fill empty select option values any more if they are not set by user. So it's actually not the Voyager issue, but just a property of new versions of db.

**Comment by iuliusx** [comment]
same problem here in version 1.4.1. 
when click on dropdown menu to select the user for author_id it is empty.
same as in academy/relationships video doesnt work. second install with diferent mysql versions.
how can it be solved ?
