### ISSUE TITLE
Multilevel menu drop down bugs

### ISSUE THREAD

**Issue by kristiantokarim** [thedevdojo/voyager#2125]
- Laravel Version: 5.5.*
- Voyager Version: dev-master
- PHP Version: 7.1.8-1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.26-MariaDB

### Description:
The drop down for sidebar menu only works for 2 levels menu. I tried to create 3 levels menu, but when I click the 2nd level drop down it close the 1st level dropdown. 

### Steps To Reproduce:
1. Go to Menu Builder
2. Click Builder button
3. Create New Menu Item (Menu 1)
4. Create New Menu Item (Menu 2)
5. Arrange them so that it become 3 level menu
e.g
Menu 1 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Menu 2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dashboard
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Database
![screenshot from 2017-10-31 03-03-06](https://user-images.githubusercontent.com/12123712/32192891-1ebd3974-bde8-11e7-8fa6-ab035dd30e73.png)
![Uploading Screenshot from 2017-10-31 03-04-01.png…]()

**Comment by fletch3555** [comment]
Voyager's nav menu only supports 2 levels (I feel like it's mentioned in the docs somewhere...).  We're open to PRs to make it support more, but will likely not implement that ourselves due to other priorities.

Other menus will support as many as you'd like, because the CSS/JS will be up to you to implement.

**Comment by f0reclone** [comment]
Here is a quick fix for this problem:
`    $('.panel-collapse').on('hide.bs.collapse', function(e) {
        if($(event.target).parent().hasClass('collapsed')) {
            e.stopPropagation();
            e.preventDefault();
        }
    });`
I simply catched the hide event and checked if there was another closed dropdown where the user clicked. If yes the event is not further propagated.

`.app-container .content-container .side-menu .navbar-nav li.dropdown li.dropdown div > ul > li > a {
            padding: 0 2.0em;
        }`
This is some additional space at the left of the third level submenu.

**Comment by fletch3555** [comment]
We're open for pull requests

**Comment by SteamWind** [comment]
Why don't we just let the user open and close the parents as he want ?

**Comment by ta-tikoma** [comment]
For work when you click on arrow:

```js
$('.panel-collapse').on('hide.bs.collapse', function(e) {
    var target = $(event.target);
    if (!target.is('a')) {
        target = target.parent();
    }
    if (!target.hasClass('collapsed')) {
        return;
    }
    e.stopPropagation();
    e.preventDefault();
});
```

**Comment by SteamWind** [comment]
@ta-tikoma do you have a screen of the result?

**Comment by ta-tikoma** [comment]
![default](https://user-images.githubusercontent.com/2934128/46592196-d2e90280-cad9-11e8-8e2d-4fbcb6101df4.PNG)

**Comment by SteamWind** [comment]
Nice, you could make a pull request :)

**Comment by emptynick** [comment]
Original problem fixed in https://github.com/the-control-group/voyager/pull/3620
#3810 discusses another problem.
