### ISSUE TITLE
No add Roles

### ISSUE THREAD

**Issue by zkmark** [thedevdojo/voyager#2130]
- Laravel Version: 5.5
- Voyager Version: 1.0.6
- PHP Version: 7
- Database Driver & Version: phpmyadmin

### Description:
When I try to add a role, it does not add
In the database users the role_id appears NULL

Then, in the navigation user table, the "role" column shows "no results"

https://user-images.githubusercontent.com/33146715/32092895-86565b68-bb24-11e7-98cf-91817559b12c.JPG

**Comment by fletch3555** [comment]
This is definitely an issue, but has already been reported a few times.

**Comment by devatens** [comment]
Logro solucionar ese error ?
