### ISSUE TITLE
Issue on upload image on version 1.0.6

### ISSUE THREAD

**Issue by tanysheng** [thedevdojo/voyager#2131]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.6
- PHP Version: 7.0.10
- Database Driver & Version: MYSQL 5.7.9

### Description:
Not sure it is a mistake or intended, the code in `Controller.php` under vendor/tcg/.../Controllers at line 57-59 doesn't check for `$request->hasFile(...)` which make upload image not working anymore. Here is the current code

`
if (!$request->has($row->field) && $row->type !== 'checkbox') {
        continue;
}
`

**Comment by fletch3555** [comment]
Bugfixes are best submitted as pull requests.  If you'd like to submit one, we'll be glad to review it.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/2113
