### ISSUE TITLE
How to move bread settings from dev server to production server?

### ISSUE THREAD

**Issue by magnum-ferox** [thedevdojo/voyager#2132]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: latest
- Database Driver & Version: Posgres 10

Hello. I configure 10+ BREADS and menu items on my dev server.
And now I need to transfer all of these settings to production server.

SQL dump does not solve the problem but creates new problems.
For example: merge current production settings with new settings, another id sequences etc.

I believe that settings should be able to be reliably transferred, versioned, stored in repository, merged. Think about this question!

**Comment by fletch3555** [comment]
This has been requested numerous times, but we haven't come up with a reasonable solution yet.

For now, SQL dumps or manual replication are the only solutions unless you implement your own migration/seed generator.
