### ISSUE TITLE
Unable to make API Resource for Post Model

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2135]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1

### Description:

I have 2 different models. One is my own and other is default Post Model of Voyager. I am making API Resources for both. API for my own model worked fine but when I tried with Post Model, It is showing this error : http://prntscr.com/h4juo3

### Steps To Reproduce:

1) php artisan make:resource Post

2) Add this in route file.
```
use App\Post;
use App\Http\Resources\Post as PostResource;
```
3) Make Route:
```
Route::get('/json', function () {
    return new PostResource(Post::find(1));
});
```
4) Now Access route

**Comment by victorlap** [comment]
That means there is no post with id 1..  You can use `Post::findOrFail(1)` to automatically generate a 404 when this is the case.
