### ISSUE TITLE
PHPUnit duplicates the output, first one is terminated

### ISSUE THREAD

**Issue by kszcode** [thedevdojo/voyager#2138]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.6
- PHP Version: 7.1.5
- Database Driver & Version:

### Description:
PHPUnit behaves weird both in command line and in PHPStorm.

### Steps To Reproduce:
1. Install clean Laravel project.
1.1. run `phpunit` output is fine
```
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 603 ms, Memory: 12.00MB
```
2. run `composer require tcg/voyager`
3. run `phpunit`, output is doubled
```
PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

PHPUnit 6.4.3 by Sebastian Bergmann and contributors.

..                                                                  2 / 2 (100%)

Time: 318 ms, Memory: 14.00MB

OK (2 tests, 2 assertions)
```

## Solution: 

It turns out that when Larapack\Hooks\Hooks object is constructed it's doing a 
```
        $xdebug = new XdebugHandler($output);
        $xdebug->check();
```
During the check function it calls the exit() function, when the environment is in a certain state.

Not sure yet why this is happening, however if anyone needs to investigate this further, now you have a lead on it.

**Comment by fletch3555** [comment]
Good find.  We'll need to look a little deeper for the actual solution, but this is definitely a solid start.  Might be an issue for the Larapack\Hooks repo though.

**Comment by blong14** [comment]
This also kills code coverage. I added this in my environment and things seem to work but not sure what its actually doing:

```export COMPOSER_ALLOW_XDEBUG=1```

**Comment by MrCrayon** [comment]
This was fixed in https://github.com/larapack/hooks/pull/26
