### ISSUE TITLE
Force HTTPS Schema

### ISSUE THREAD

**Issue by felipeandres254** [thedevdojo/voyager#2139]
- Laravel Version: 5.5
- Voyager Version: 1.0.6
- PHP Version: 
- Database Driver & Version: 

### Description:
When deploying to a HTTPS server, most of Voyager resources are broken. You can force HTTPS schema by putting the following line into the `boot` function of your `AppServiceProvider.php` file:

```php
\URL::forceScheme('https');
```

**Comment by fletch3555** [comment]
This is something you can do in your own app, not something Voyager needs to concern itself with.

**Comment by felipeandres254** [comment]
Yes, this is not a request. But I don't know how to put it as a collaboration.
