### ISSUE TITLE
Relashionship's not working on custom tables

### ISSUE THREAD

**Issue by darana07** [thedevdojo/voyager#2144]
- Laravel Version: 5.5
- Voyager Version: 1.0.6
- PHP Version:7.7
- Database Driver & Version:MYQSL

### Description:
Hi, im working on a personal project and trying to use relationships in custom tables, i follow the steps that the tutorial said and everything works fine, until the moment i save the data, cause the data is never saved and always shows "No Results"

![fireshot capture 79 - - - http___localhost_8000_admin_database_types_edit](https://user-images.githubusercontent.com/19784904/32331730-49d76e6e-bfa9-11e7-8a62-425172178f1c.png)
![fireshot capture 80 - - - http___localhost_8000_admin_database_rooms_edit](https://user-images.githubusercontent.com/19784904/32331741-4e458ab2-bfa9-11e7-8063-2fe4474a11bd.png)
![roombread](https://user-images.githubusercontent.com/19784904/32331754-54e2c218-bfa9-11e7-9695-a8f92055c8bb.png)
![fireshot capture 82 - add room - http___localhost_8000_admin_rooms_create](https://user-images.githubusercontent.com/19784904/32331762-5e38d2c6-bfa9-11e7-8ac1-8c10d40cae26.png)
![makmeats](https://user-images.githubusercontent.com/19784904/32331786-691f3fe0-bfa9-11e7-921b-64e78f1b747f.png)

**Comment by paulchiu** [comment]
There are a couple of PRs for this already. See #2121 and #2141.

**Comment by fletch3555** [comment]
Related PRs are merged.  Closing
