### ISSUE TITLE
bug report: always can't set required to zero

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#2145]
- Laravel Version: #.#.#
- Voyager Version: 1.0.6
- PHP Version:
- Database Driver & Version:

### Description:
![d32f4592-31cd-4375-b67e-62d2b4fa1d0b](https://user-images.githubusercontent.com/20222136/32336509-73fb966c-c02a-11e7-8120-b012b2bdf07a.png)

**Comment by fletch3555** [comment]
Bugfixes are best submitted as pull requests, not issues.  If you'd like to submit it yourself, please feel free.  If not, say so and someone else will get to it.

**Comment by cyrildewit** [comment]
@OliverVin is right. Both `"required": true` and `"required": false` gives me `"1"`. I will send a pull request soon!
