### ISSUE TITLE
bug report: menu can't support chinese .etc 

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#2148]
- Laravel Version: #.#.#
- Voyager Version: 1.0.6
- PHP Version:
- Database Driver & Version:

### Description:
![a917f660-df8b-4f56-9ce6-95cfc3825c1b](https://user-images.githubusercontent.com/20222136/32364106-eddb1376-c0ad-11e7-9c0e-641afd8c57de.png)

str_slug(md5($item->id), '-')     suggest md5 convert .

**Comment by fletch3555** [comment]
Why is this a problem?

**Comment by csuhan** [comment]
the same with me! laravel's str_slug can't support chinese

**Comment by fletch3555** [comment]
Still waiting on a response to my previous question.  Specifically why does that method not work for chinese? I'm certainly not an expert on the spoken or written chinese language, so please enlighten me.

**Comment by OliverVin** [comment]
str_slug can not support chinese , Now use id is better .

**Comment by fletch3555** [comment]
@OliverVin, my question was WHY it doesn't support chinese.  Until I have that answer, I cannot continue with this

**Comment by lovevisss** [comment]
Let me try to explain. When I type in the title in Chinese, the slug will not be generated automatically. But this works when I use titles in English.
