### ISSUE TITLE
Bread datatables look;s

### ISSUE THREAD

**Issue by emeren** [thedevdojo/voyager#2149]
I do not know why the new bread looks different than bread posts. I mean the top table.

![zrzut ekranu 2017-11-03 o 10 26 33](https://user-images.githubusercontent.com/22492778/32367188-8d25158a-c081-11e7-9fff-fabc6acf3ebe.png)

![zrzut ekranu 2017-11-03 o 10 33 41](https://user-images.githubusercontent.com/22492778/32367471-7f2c283c-c082-11e7-8517-b6f7618a5a57.png)

Can u help me ?

**Comment by sylmz** [comment]
I think, it is because of you selected server side pagination when bread edited

**Comment by emeren** [comment]
Yes :) Thanks!
