### ISSUE TITLE
How to change admin route?

### ISSUE THREAD

**Issue by EquiBajo** [thedevdojo/voyager#215]
I need change the route admin for example: administrator or backoffice.

How to change this?

Many thanks
Equi

**Comment by fletch3555** [comment]
@EquiBajo You can change the route prefix in [config/voyager.php](https://github.com/the-control-group/voyager/blob/master/publishable/config/voyager.php) (line ~31)

**Comment by EquiBajo** [comment]
on vendor really?. Thanks

**Comment by marktopper** [comment]
Just publish the config

**Comment by EquiBajo** [comment]
This isn't working maybe I' m forgetting something ??

**Comment by marktopper** [comment]
Please let me know the following:

1. What have you changed the route prefix to in your `/config/voyager.php`-file?
2. What comes out when running `php artisan route:list`
3. Have you been caching the routes, if so please recache it by running `php artisan route:cache`

**Comment by marktopper** [comment]
OBS: Also a config cache could have been done, in that case recache it using `php artisan config:cache`.

**Comment by EquiBajo** [comment]
I'm sorry but not.

Look!. VoyagerServicesProvider.php (line ~ 61) 

if I change this line work it fine

**Comment by marktopper** [comment]
You mean this line: https://github.com/the-control-group/voyager/blob/6b2a614d773ab2b052047a65d06ceedfe7c80b79/src/VoyagerServiceProvider.php#L61

Then there is something up with your configuration. Do you have the config file `config/voyager.php` in your application?

**Comment by EquiBajo** [comment]
oh!! I'm dumb, I'm really sorry, 

**MY APP/config/voyager.php** ->change config here! 

pff!!, I've changed on vendor my mistake

Many thanks

**Comment by marktopper** [comment]
Glad it worked out.

/closing
