### ISSUE TITLE
***Urgent. Can't access admin on AWS SERVER - How to Deploy?

### ISSUE THREAD

**Issue by pirocoptero** [thedevdojo/voyager#2150]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0.20
- Database Driver & Version: Mysql 5.7.19

### Description:
I can't access the admin page after to deploy my application to AWS SERVER. 

SQLSTATE[HY000] [1045] Access denied for user 'akarootuser'@'MYIPADDREESS' (using password: YES) (SQL: select * from `settings`) (View: /var/app/current/vendor/tcg/voyager/resources/views/login.blade.php)

**Comment by akazorg** [comment]
Hi @pirocopterom, verify 2 things:
- SQL credentials
- database seeds were run

**Comment by mpge** [comment]
This is most likely a server related issue. Verify the password you are using (for your mysql user) is the correct password.

**Comment by fletch3555** [comment]
Agreed with the other 2 posts.  There's no way Voyager can cause you to get that error.  It's a SQL Auth failure.  Please verify that your database host/user/password env values are correct.

**Comment by martinartaza** [comment]
I have the same problem In my local machine I can access to admin with site/admin/login but in my AWS I access to
http://www.martinartaza.com.ar/index.php/admin/login
suppose that setting problem, when I have time I will fix.
