### ISSUE TITLE
Publish lang when upgrading from 0.11.* to 1.0.*

### ISSUE THREAD

**Issue by DomPich** [thedevdojo/voyager#2151]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.1.8
- Database Driver & Version: mysql 5.7.19

### Description:

Had a problem while upgrading from 0.11.* to 1.0.* 

The language files where missing. Had to call `php artisan vendor:publish --tag=lang` so that all localization strings were displayed correctly instead of the keys.

I followed all necessary steps of the upgrading guide.

**Comment by blitux** [comment]
I had this problem too. The solution is to run ``php artisan vendor:publish --tag=lang --force`` to overwrite the lang files.

**Comment by emptynick** [comment]
This is (now) mentioned in the [upgrade guide](https://voyager.readme.io/docs/011-to-1)
This can be closed
