### ISSUE TITLE
Time to display... very long

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#2154]
- Laravel Version: Latest
- Voyager Version: Latest
- PHP Version: 7.0.22-0ubuntu0.16.04.1
- Database Driver & Version: MySQL 5.7

### Description:
Hello
When I display my products table, it takes a lot of time.
And I have a lot of requests and views (more than 400 for a table of 120 products)
How to improve this?

[Screenshot 1](https://www.cotiga-world.com/images/screenshot/product-bread-01.jpg)
[Screenshot 2](https://www.cotiga-world.com/images/screenshot/product-bread-02.jpg)
[Screenshot 3](https://www.cotiga-world.com/images/screenshot/product-bread-03.jpg)

**Comment by dattz** [comment]
@COTIGA Are you using Server Side Pagination for this Bread?

**Comment by cotiga** [comment]
No.
I passed the site in "debug = false" mode
And put the default language on: EN (FR before)
The display is now at 25 seconds against 36 before, but I still find it much too long!

**Comment by dattz** [comment]
How many rows are in your products table?

**Comment by cotiga** [comment]
135 now

**Comment by Rhymond** [comment]
Check how long does it take to connect to database, I guess problem is not with Voyager. 
Sometimes playing with DB host (localhost or 127.0.0.1) helps

**Comment by Nolween** [comment]
@COTIGA I've the same issue, with 450 elements in my table. It takes 53 seconds to load, so weird ! have you found the solution? 
I've changed DB host with 127.0.0.1 or localhost, it always so loud to load.

Edit: Ok,  I've tried  Server Side Pagination on BREAD, it works like a charm !Thank You !

**Comment by cotiga** [comment]
No, no solution yet.
I have another Laravel project, but not with Voyager, with jeremykenedy/laravel-auth.
On this project I have 1300 users, and the "Users" loading time is also very long.
I think we must therefore focus research at Laravel level.

**Comment by Nolween** [comment]
@COTIGA  Have you tried Server Side Pagination on BREAD? it worked for me!

**Comment by cotiga** [comment]
Yes, it works much better
Yet I had already tried, without result.
Thank you for making me try again.
I closed the issue
