### ISSUE TITLE
Documentation for Dropdown

### ISSUE THREAD

**Issue by lloy0076** [thedevdojo/voyager#2158]
- Laravel Version: Irrelevant

- Voyager Version: 0.11
- PHP Version: Irrelevant
- Database Driver & Version: Irrelevant

#### Broken Version

Docs claim that dropdowns are setup like:

```
{
    "default": "",
    "options": {
        "m": "Male",
        "f": "Female"
    }
}
```

Notice the word **options** [sic].

#### Fixed Version

It should be **option** - notice the _missing letter **s**_:

```
{
    "default": "",
    "option": {
        "m": "Male",
        "f": "Female"
    }
}
```

### Steps To Reproduce:

1. Make a dropdown field called "gender" or whatever;
2. Insert the first one or even just copy/paste from the docs;
3. Watch the horrid exception;
4. Remove the 's';
5. Watch everything work.

**Comment by fletch3555** [comment]
Why should it be `option`? Looking at the code (both the tagged `v0.11.14` and `master` branch.. see links below), it's looking for `options` with the 's'.

v0.11.14: https://github.com/the-control-group/voyager/blob/v0.11.14/resources/views/formfields/select_dropdown.blade.php#L18
master: https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/select_dropdown.blade.php#L18

**Comment by lloy0076** [comment]
```
(2/2) ErrorException

Undefined property: stdClass::$ (View: C:\laragon\webroots\playhq\attendence-laravel\vendor\tcg\voyager\resources\views\bread\browse.blade.php)
```

![image](https://user-images.githubusercontent.com/1174532/32438722-897e1366-c2b9-11e7-8e95-4abb8287ad21.png)

I agree - `options` should work but it's not (at least for me).

**Comment by lloy0076** [comment]
@fletch3555 - all I know is that changing it from `options` to just `option` fixes it all.

**Comment by lloy0076** [comment]
This might be an issue but I don't see how this would affect it.

[BreadRelationshipParser.zip](https://github.com/the-control-group/voyager/files/1445999/BreadRelationshipParser.zip)

**Comment by lloy0076** [comment]
More information - on the `edit` view, no dropdown is created when the word `option` (no `s`) is used, so @fletch3555:

1. The column/list view (the thing that just a plain slug goes to) has the issue;
2. The code "ignores" a JSON `option` option in the `edit` view and renders it as an empty relation

**Comment by fletch3555** [comment]
Yeah, seems `options` is perfectly correct, but is manifesting as the problem, hiding the real problem.  This is going to take a bit more digging to figure out.  I haven't had much time lately, and haven't been able to reproduce it locally, so if someone else can, please feel free to take lead on troubleshooting

**Comment by Bingde** [comment]
I change it to option, then In the dropdown is empty. the solution is to changes to options. then it works well

**Comment by prezmix** [comment]
Just wanted to comment that I have the same issue. Using `options`:

`Undefined property: stdClass::$Lobby (View: /var/www/zoomrec/vendor/tcg/voyager/resources/views/bread/browse.blade.php)`

Changing to `option` results in the same bug as described by @lloy0076 above with no dropdown generated when editing.

**Comment by emptynick** [comment]
Is this still a problem?
Looking at the code `options` is the correct key.

**Comment by kvlknctk** [comment]
> Why should it be `option`? Looking at the code (both the tagged `v0.11.14` and `master` branch.. see links below), it's looking for `options` with the 's'.
> 
> v0.11.14: https://github.com/the-control-group/voyager/blob/v0.11.14/resources/views/formfields/select_dropdown.blade.php#L18
> master: https://github.com/the-control-group/voyager/blob/master/resources/views/formfields/select_dropdown.blade.php#L18

link broken

**Comment by fletch3555** [comment]
Likely because 0.11.14 was released like 2+ years ago and we pruned away most of the pre-1.0 tags.  You're quoting a comment from 2.5+ years ago, and related to a MUCH older version, so it's not likely to be relevant anyway
