### ISSUE TITLE
What theme is used in Voyager?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#216]
Just curious to know what is the theme used in Voyager. It looks great and I would like to use it in my laravel application.

**Comment by ChadTaljaardt** [comment]
custom theme : https://github.com/the-control-group/voyager/blob/master/publishable/assets/css/voyager.css

**Comment by ghost** [comment]
Am I free to use the theme?

**Comment by handiwijoyo** [comment]
@yeshwanthvshenoy I think you can, Voyager has MIT license

**Comment by ghost** [comment]
Thanks! 👍

**Comment by fletch3555** [comment]
For reference, here's an outline of what the MIT license allows/restricts: http://choosealicense.com/licenses/mit/
