### ISSUE TITLE
Images don't show up in views (front-end pages)

### ISSUE THREAD

**Issue by devKhairul** [thedevdojo/voyager#2160]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0.10
- Database Driver & Version: MySQL 5.7.14

### Description:
Image in views not working. I can see the image in the back-end when I browse the BREAD. However when I'm trying to display the image in my views it's not working even though the image link seems to be pointing to the correct directory. Following is the image URI - 
http://localhost:8000/public/storage/about/November2017/about-1.jpg

I tried creating symlink but it still didn't work. 

This is how my filesystems.php looks like - 

```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_KEY'),
            'secret' => env('AWS_SECRET'),
            'region' => env('AWS_REGION'),
            'bucket' => env('AWS_BUCKET'),
        ],
```

Things already tried: created symlink, changed url in filesystems.php, visibility set to public

Working for a University project assignment. This is sort of urgent. 

### Steps To Reproduce:
1) Upload image
2) Try to display image in view (front end pages)

**Comment by emptynick** [comment]
Are you using `Voyager::image($item->image)` ?
Your path looks wrong because theres still the public directory (if you remove it, it should be fine)

**Comment by devKhairul** [comment]
I'm fetching all the data from the table like so -

`$posts = DB::table('about')->get(); `

Then echoing the image `{{ $p->images }}`

**Comment by devKhairul** [comment]
Fantastic. It works after removing the public directory. How stupid of me. Thanks a lot!! :)

**Comment by emptynick** [comment]
`$p->images` is an array?
And try `{{ Voyager::image($p->image) }}`

**Comment by devKhairul** [comment]
Your first solution worked. Thanks a lot buddy. :)
