### ISSUE TITLE
BREAD, Multiple Images can't delete one image

### ISSUE THREAD

**Issue by nguyentrongthanh** [thedevdojo/voyager#2163]
- Laravel Version: 5.5.14
- Voyager Version: 1.0.3
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.6.37

### Description:
BREAD, Multiple Images can't delete one image

### Steps To Reproduce:
1. Services entity has a multiple images field (in Bread)
2. Add images
3. Save & View (so large)
4. Delete one image
5. Can't touch

**Comment by handiwijoyo** [comment]
Did you mean that in edit view the images size are too big?

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3240
