### ISSUE TITLE
Laravel 5.5 , Error key length 

### ISSUE THREAD

**Issue by nghoangthanh121296** [thedevdojo/voyager#2164]
- Laravel Version: 5.5
- Voyager Version: Newest
- PHP Version: 7.1.9
- Database Driver & Version: MySQL 5.7.19

### Description:
![image](https://user-images.githubusercontent.com/32502784/32429707-6765aea2-c2fe-11e7-9171-3433f487d206.png)

![image](https://user-images.githubusercontent.com/32502784/32429729-800a5886-c2fe-11e7-9f7c-3907fdda9634.png)

![image](https://user-images.githubusercontent.com/32502784/32429736-8dafde0c-c2fe-11e7-9254-b474059c63bf.png)
![image](https://user-images.githubusercontent.com/32502784/32429759-a533450a-c2fe-11e7-8fe6-90ee55a50a24.png)

**Comment by secondnetwork** [comment]
go to config/database.php file and change the line to.
            **'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',**
  
 is the best solution for me
 

     'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

**Comment by nghoangthanh121296** [comment]
![image](https://user-images.githubusercontent.com/32502784/32527837-6f4397e6-c462-11e7-988f-b5b15c0889cf.png)
i try but not working @@
![image](https://user-images.githubusercontent.com/32502784/32527862-94ee2510-c462-11e7-95b2-18033f8b9911.png)

**Comment by wangxiaolong100** [comment]
@nghoangthanh121296 This maybe your database default storage engine not InnoDB， run
 `SELECT @@default_storage_engine`
to check.
If not, set or insert
`default-storage-engine=innodb`
in my.ini, then delete all table and rerun install.

**Comment by nghoangthanh121296** [comment]
thank, fixed success 👍

**Comment by fletch3555** [comment]
Closing since this has been identified as fixed.
