### ISSUE TITLE
Soft delete Admin

### ISSUE THREAD

**Issue by wael986** [thedevdojo/voyager#2165]
- Laravel Version: 5.5.*
- Voyager Version: the last one
- PHP Version:7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Database Driver & Version: mysql

### Description:

Hi thank you it was really simple to get the soft delete working
the problem is that i cannot load the deleted items in the admin panel!!
i need to restore some items or edit them!!
<img src="https://image.ibb.co/iQGFhb/deleted.png" />

as u can see the table is empty but in the DB i already have some deleted products!

**Comment by fletch3555** [comment]
Voyager doesn't add `withTrashed()` to it's queries.  We need to add a UI element to allow toggling that.  I'm open for Pull Requests if anyone else wants to take a stab at it.

**Comment by mattrabe** [comment]
I can jump on this.

I'm thinking of a "View Deleted" bootstrap toggle near the existing Add New / Bulk Delete / Order buttons at the top of the browse view. This would appear only for models that use `SoftDeletes`. Clicking the toggle will redirect the user to ?withTrashed or similar and reload the page. When the page loads, if the toggle is on, the controller query will use `->withTrashed()`, if it is off it will not.

Should I branch off of 1.1?

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3758, merged into 1.x
