### ISSUE TITLE
Multilanguage not working

### ISSUE THREAD

**Issue by abacram** [thedevdojo/voyager#2167]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.7
- PHP Version:
- Database Driver & Version:
MySQL
### Description:
I just installed a fresh Laravel with Voyager. Once all is well and i can enter to /admin, i change:

'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'es',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'es',
            'en',
            'fr'
        ],
    ],

But the dashboard and pages remains in english, and i cannot see the lang selector, it only appears in pages and cats sections.

I also tried to clear config and view caches ;)

Some help would be appreciated! Thanks!

### Steps To Reproduce:
Install Laravel with Voyager
Change multilingual in voyager.php
See if selector and texts/captions changes to another lang

**Comment by abacram** [comment]
If i can help with more info... it's strange, because if i change for example 'prefix' => 'panel', in voyager.php, it doesn't work when i try to access to /panel instead of /admin... Even when i stop the php artisan serve command, clear all caches and run it again...

**Comment by cotiga** [comment]
IN
`/config/app.php`
SET
`'locale' => 'es',`

**Comment by abacram** [comment]
Sorry for that obvious issue! Today is really not my day.
Thanks @COTIGA !!!
