### ISSUE TITLE
Keep original media filename after upload

### ISSUE THREAD

**Issue by Luc45** [thedevdojo/voyager#2173]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.15
- PHP Version: 7.2

### Description:

Voyager media manager uses store() method from Laravel to save uploaded files.

The store() method encrypts the filename in a md5 hash with a random number from 0-999, thus generating a unique filename.

However, I would like to upload the file while preserving it's name.

I'm opening this issue to request an option on Voyager config for that. :)

Changing:
```
if (in_array($request->file->getMimeType(), $allowedImageMimeTypes)) {
    $file = $request->file->store($request->upload_path, $this->filesystem);

    $image = Image::make($realPath.$file);

    if ($request->file->getClientOriginalExtension() == 'gif') {
        copy($request->file->getRealPath(), $realPath.$file);
    } else {
        $image->orientate()->save($realPath.$file);
    }
} else {
    $file = $request->file->move($realPath, $request->file->getClientOriginalName());
}
```
To 
`$file = $request->file->move($realPath, $request->file->getClientOriginalName());`

In the upload method, at:
voyager/src/Http/Controllers/VoyagerMediaControler.php:176

Uploads the file while preserving it's name

**Comment by fletch3555** [comment]
All fields are required when opening issues: https://github.com/the-control-group/voyager/blob/master/ISSUE_TEMPLATE

Please update your issue description with the missing data and we'll reopen this

**Comment by Luc45** [comment]
@fletch3555 Sorry, I haven't seem your answer. Issue updated with version details.

**Comment by fletch3555** [comment]
This issue is almost 8 months old... are you still having the same problem with the same version....?

**Comment by baljitkaur19** [comment]
Just add the below line in the field under Tools->Database->edit bread field name options
{
    "preserveFileUploadName": "yes"
}
