### ISSUE TITLE
Upgrade guide missing browse_compass permission seeding

### ISSUE THREAD

**Issue by ux-engineer** [thedevdojo/voyager#2177]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.7

I started using Voyager on this project from version 0.11.10 and recently upgraded to 1.0.7.

Now I've noticed that _browse_compass_ permission is missing from permissions table and the upgrade guide has no mention on changes to default seeded dataset. Is there something missing also?

**Comment by ux-engineer** [comment]
Here: https://github.com/the-control-group/voyager/compare/v0.11.10...master

Choose Files changed (892). Use browser's search for 'seeder'. There are 14 matches for modified seeder files.

**Comment by ux-engineer** [comment]
Also noticed _config/voyager.php_ has these new additions also missing from the upgrade guide:

	/*
	|--------------------------------------------------------------------------
	| Automatic Procedures
	|--------------------------------------------------------------------------
	|
	| When a change happens on Voyager, we can automate some routines.
	|
	*/
	// When a BREAD is added, create the Menu item using the BREAD properties.
    'add_bread_menu_item' => true,
	// When a BREAD is added, create the related Permission.
    'add_bread_permission' => true,


    'googlemaps' => [
	    'key'    => env('GOOGLE_MAPS_KEY', ''),
	    'center' => [
		    'lat' => env('GOOGLE_MAPS_DEFAULT_CENTER_LAT', '32.715738'),
		    'lng' => env('GOOGLE_MAPS_DEFAULT_CENTER_LNG', '-117.161084'),
	    ],
	    'zoom' => env('GOOGLE_MAPS_DEFAULT_ZOOM', 11),
    ],

**Comment by fletch3555** [comment]
The upgrade guide is not written with the intention of walking you through every new line you need to write to your config files.  I personally think it should be common sense that published config files may have new entries you'll need to get, but I also completely understand the argument that those entries aren't documented anywhere.

Our docs allow submission of suggested changes.  You're welcome to type up any necessary changes you find and submit them there.  We'll be glad to review them there.
