### ISSUE TITLE
Validation fails when display name and field name of a BREAD field don't match

### ISSUE THREAD

**Issue by blitux** [thedevdojo/voyager#2179]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.7
- PHP Version: 7.1.*
- Database Driver & Version: N/A

### Description:

On editing a BREAD resource, when using different field display name and field name, validation rules don't apply and get errors on fields where the conditions are met.

### Steps To Reproduce:

1. Fresh Voyager Install
2. Create a minimum table using Database Administration, with 'id' and 'sometext' fields.
3. Add BREAD to the resource
4. On the display label for 'sometext' field, set something different from 'sometext', like 'texto' and save
5. Create a new resource and set a value for the field 'sometext' labelled 'texto'
6. Press submit. No error will be shown, and there will be javascript errors because can't find the field with selector "[name=texto]" (which actually doesn't exist, as the name attribute for the field is 'somefield')

### Related issues: 

#1963 Validation scroll to first error not work

**Comment by gausam** [comment]
Can confirm the same. This is a blocking issue.

**Comment by ratt** [comment]
This commit https://github.com/the-control-group/voyager/commit/214992a5dce073df4bc84ce9c5bdc3ac5a146932 seems to be the cause. 
The name fields are name="{{ $row->field }}"  but the validation is using $rules[$row->display_name] and this is casuing issues where  title !== Title etc.

**Comment by blitux** [comment]
I'm working on a patch for this issue. I will send the PR later today.

**Comment by gausam** [comment]
Awesome :+1:

**Comment by gausam** [comment]
@ratt Yeah that whole PR is overkill. It was an excellent effort by the author though.

@blitux I think we're better off not patching this. We simply have to lose it all and use a better approach. What do you think?

@marktopper @fletch3555 I propose that we reverse the PR, completely. At least to get the BREAD mechanism in a working state again.

**Why?**

Besides breaking Voyager for several people, the author's intended functionality can be implemented so so simply out the box with Laravel.

**How?**

Laravel has the [setCustomAttributes](https://github.com/laravel/framework/blob/5.5/src/Illuminate/Validation/Validator.php#L954) function built in. We can use that to map column names (used also as input names, before this PR) to the corresponding display name. Some discussion of it is [in this thread here on SO](https://stackoverflow.com/a/20633014/946175).

We simply add the call to our [validateBread](https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L144) function and achieve the same thing with maybe 10 or so lines of code and only one file changed.

**Comment by gausam** [comment]
*Update*: Reversed the changes from the PR that caused this, and implemented the simpler approach above (two lines of code). PR :point_right: #2190.
