### ISSUE TITLE
change parent_id from 0 to NULL 

### ISSUE THREAD

**Issue by wxs77577** [thedevdojo/voyager#218]
Reference key should allow NULL so we should set NULL. 0 means there is an object which has a primary key 0

**Comment by fletch3555** [comment]
Can you please provide some context? Is there a particular class you're referencing?

**Comment by wxs77577** [comment]
![image](https://cloud.githubusercontent.com/assets/1990059/20697383/cd880d84-b633-11e6-8e46-7590d77a0217.png)

**Comment by wxs77577** [comment]
If you choose `0` ,that you cannot define a  foreign key constraint in mysql, because there is no record has a primary key `0`.
So you should change `0` to `NULL`
