### ISSUE TITLE
unread table ID as  link

### ISSUE THREAD

**Issue by jaysonclaros** [thedevdojo/voyager#2180]
-The Control Group - v1.0.6

i connot edit  or view the branch after i created,

   http://service.dev/admin/branches//edit

Messing field id
Thanks
Jyson Claros

**Comment by fletch3555** [comment]
All fields are required when submitting issues: https://github.com/the-control-group/voyager/blob/master/ISSUE_TEMPLATE

Please update your issue description and we'll reopen it.
