### ISSUE TITLE
How Can Use Drag And Drop

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#2184]
How can use this?

Please help me my voyager is latest version
https://github.com/the-control-group/voyager/pull/1165/

**Comment by emptynick** [comment]
Can you be a little bit more exact?
What do you want to drag and drop?
The BREAD-fields?

**Comment by tufkan** [comment]
I created the sliders database and BREAD. I added two sliders and I want to arrange them with drag and drop.

**Comment by fletch3555** [comment]
All fields are required when submitting issues: https://github.com/the-control-group/voyager/blob/master/ISSUE_TEMPLATE

Please update your issue description and we'll reopen it.
