### ISSUE TITLE
multilingual.js not found

### ISSUE THREAD

**Issue by hquangthien** [thedevdojo/voyager#2188]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.*
- PHP Version: 7.1.*
- Database Driver & Version: 

Description:
 When I use multi languaue feature of voyager packages, I get this error: GET http://voyager.dev/vendor/tcg/voyager/assets/js/multilingual.js net::ERR_ABORTED

I have published vendor: php artisan vendor:publish --tag='voyager_assets' --force but it still not working.

**Comment by akazorg** [comment]
Hey @hquangthien.
Have you tried to run just `php artisan vendor:publish` and select voyager assets?

If it doesn't work, copy `tcg/voyager/publishable/assets/js/app.js` and place it at `public/vendor/tcg/voyager/assets/js/app.js`.

**Comment by marktopper** [comment]
Closed due to inactivity.
