### ISSUE TITLE
How Can Use Drag And Drop in Backend

### ISSUE THREAD

**Issue by tufkan** [thedevdojo/voyager#2189]
- Laravel Version: 5.4.*
- Voyager Version: ^1.0
- PHP Version: >=5.6.4
### Steps To Reproduce:
How can use this?

Please help me my voyager is latest version

https://github.com/the-control-group/voyager/pull/1165
<hr />

I created the sliders database and BREAD. I added two sliders and I want to arrange them with drag and drop.
https://github.com/the-control-group/voyager/pull/1165

**Comment by vFire** [comment]
Dig into the view of menu, it's only frontend issues, I think maybe you should do by your own hands.

**Comment by fletch3555** [comment]
Voyager doesn't provide an automatic mechanism to do this, so you'll have to do it yourself.  We've implemented it for at least one of the views that ships with Voyager (menus), so you could look at that and attempt to reproduce the functionality, like @vFire suggested.

**Comment by ghost** [comment]
Hi!

I created BREAD model with ordered field. 
How I can set initial value automatically for this field, when I create new model record?

Thank u!

**Comment by emptynick** [comment]
That's basic Laravel knowledge and is also unrelated to this issue, which has been closed for nearly 2 years.
