### ISSUE TITLE
Support for custom views out of Voyager vendor folder

### ISSUE THREAD

**Issue by abacram** [thedevdojo/voyager#2194]
I think it could be very great edit the core and add support to custom views, but instead of the actual placement of the views inside the voyager vendor folder, edit VoyagerBreadController and add support for views inside the root resources/views folder inside the project:

if (view()->exists($slug.".edit-add")) {
      $view = $slug.".edit-add";
}

This will prevent the loss of custom views when upgrading voyager in our customized projects. What do you think?

**Comment by fletch3555** [comment]
This is already possible and covered in both Laravel (https://laravel.com/docs/5.5/packages#views) and Voyager (https://voyager.readme.io/docs/overriding-views) documentation.

**Comment by abacram** [comment]
Sorry and thanks for the link (https://laravel.com/docs/5.5/packages#views), i didn't know also vendor views can be overrided.
