### ISSUE TITLE
Date form type shows format instead of value

### ISSUE THREAD

**Issue by leonardyhuang** [thedevdojo/voyager#2197]
- Laravel Version: 5.5.20
- Voyager Version: 1.0.7
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 5.7.19

### Description:
`Date` form type shows the format instead of the value.

### Screenshots:
![2017-11-09 00_51_39-edit bread for events table](https://user-images.githubusercontent.com/22125998/32562238-16bb8ee4-c4e9-11e7-9f8d-ed9287e2f5d9.png)

![2017-11-09 00_52_55-viewing events](https://user-images.githubusercontent.com/22125998/32562237-1644efb4-c4e9-11e7-94e4-ff151f103749.png)

![2017-11-09 00_53_46-view event](https://user-images.githubusercontent.com/22125998/32562235-15f0bd0e-c4e9-11e7-88e8-e0c039e0e96d.png)

**Comment by emptynick** [comment]
Voyager uses the formatLocalized method from Carbon.
You need to use a different format as described [here](http://carbon.nesbot.com/docs/#api-localization) and in detail [here](http://php.net/manual/en/function.strftime.php)

**Comment by leonardyhuang** [comment]
Thanks @emptynick !

But in the date picker's format does not follow the set format:
![2017-11-09 02_23_29-viewing events](https://user-images.githubusercontent.com/22125998/32567404-1ee23fa2-c4f6-11e7-9522-7e6e924ff20b.png)

![2017-11-09 02_25_25-edit event](https://user-images.githubusercontent.com/22125998/32567402-1e923bec-c4f6-11e7-81cc-7484c42c0752.png)

Maybe this can be added as a feature in the future.

**Comment by leonardyhuang** [comment]
Thanks @emptynick !

But in the date picker's format does not follow the set format:
![2017-11-09 02_23_29-viewing events](https://user-images.githubusercontent.com/22125998/32567404-1ee23fa2-c4f6-11e7-9522-7e6e924ff20b.png)

![2017-11-09 02_25_25-edit event](https://user-images.githubusercontent.com/22125998/32567402-1e923bec-c4f6-11e7-81cc-7484c42c0752.png)

Maybe this can be added as a feature in the future.

**Comment by leonardyhuang** [comment]
Thanks @emptynick !

But in the date picker's format does not follow the set format:
![2017-11-09 02_23_29-viewing events](https://user-images.githubusercontent.com/22125998/32567404-1ee23fa2-c4f6-11e7-9522-7e6e924ff20b.png)

![2017-11-09 02_25_25-edit event](https://user-images.githubusercontent.com/22125998/32567402-1e923bec-c4f6-11e7-81cc-7484c42c0752.png)

Maybe this can be added as a feature in the future.

**Comment by fletch3555** [comment]
Sounds like a documentation change is needed.
