### ISSUE TITLE
Suggestion: Move some seeders to migration

### ISSUE THREAD

**Issue by zagreusinoz** [thedevdojo/voyager#2199]
### Description:
Seeders are intended for test data, however in this project they are a mixture of test and setup data.  My suggestion is to move the setup data (e.g. data types) into the migration for that table and then when setting up a production or staging instance we can have the default data without the generated test data from the seeders.

**Comment by fletch3555** [comment]
No, seeders are intended for seeding tables.  It could be for test OR setup data.  We chose to use it for setup data.

Migrations are intended for database structure only, which is what we're using it for.

**Comment by zagreusinoz** [comment]
Ok, I understand your position.  Just a quick quote from the Laravel documentation though (emphasis mine):

> Laravel includes a simple method of seeding your database with **test data** using seed classes.

**Comment by fletch3555** [comment]
I interpret that comment to mean that it CAN be used for test data, not that it SHOULD ONLY be used for test data.
