### ISSUE TITLE
Multi-Bread needed

### ISSUE THREAD

**Issue by vFire** [thedevdojo/voyager#2200]
When I use another own building CRUD system, building multi-Bread on one table is very common.

e.g. I have a table contain all "messages", I want to build a private message BREAD also base on the same table, I want to build another ADMIN ALL messages BREAD, Multi-Bread will be very simple to handle of it.

Hope it could be considered in the future release.

Amazing Product! Move on...

**Comment by vFire** [comment]
Sorry for misleading, I just found multi-bread is naturally supported in Voyager, only without a direct link.

**Comment by akazorg** [comment]
Hi @vFire, I don't know how you handled to have a Multi BREAD system, perhaps you're referring to a different feature.

The Multi BREAD is on our to do list, and it consists of having multiple entries on tables `data_types` and `data_rows`.

Thanks for your message. Closing this issue now.

**Comment by laraveladminpanel** [comment]
[Removed: advertising]
