### ISSUE TITLE
Sorry, the page you are looking for could not be found.

### ISSUE THREAD

**Issue by nikay05** [thedevdojo/voyager#2202]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:
![voyager](https://user-images.githubusercontent.com/32151252/32601443-980d2d24-c57d-11e7-9fa7-70518fb0c8de.png)

**Comment by fletch3555** [comment]
All fields are required when opening issues.  Please update your issue's description with the missing information and we'll reopen your issue for review.
