### ISSUE TITLE
Menu items not showing if permissions not added

### ISSUE THREAD

**Issue by neverfan** [thedevdojo/voyager#2203]
- Laravel Version: v5.4.36
- Voyager Version: 1.0.7 (upd from 0.11.29)
- PHP Version: 5.6.30
- Database Driver & Version:

### Description:
Main admin menu for added bread models not showed becouse have not permissions for it in `permissions` table. But in before version  0.11.29, menu normaly showed without added permissions. And why table `data_types` needs field `generate_permissions:boolean` if that not used when check permissions? 

I mean, you do not need to deny access if no policies are added. In the previous version it was like this. If this has changed, add this to the update instruction.

### Steps To Reproduce:
1. Add some breads for tables in 0.11.29 without permission
2. Menu in 0.11.29 is showed normaly 
3. Upd voyager to 1.0.* (with all instructions)
4. Menu for added bread not showed becouse have not permissions

**Comment by neverfan** [comment]
I found some solution for me:
```
1. Add migration with run seeder with code some like this:

$data_types = TCG\Voyager\Models\DataType::all();

foreach ($data_types as $type) {
    Permission::generateFor($type->name);
}

$role = Role::where('name', 'admin')->firstOrFail();

$permissions = Permission::all();

$role->permissions()->sync(
    $permissions->pluck('id')->all()
);
```

**Comment by fletch3555** [comment]
We already have a PermissionsTableSeeder which does the first part of that.  Adding the permissions to your role has always been a manual task.

Glad you found your solution
