### ISSUE TITLE
[ASK] How to publish all vendor inside the voyager to our project

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#2204]
Can We Publish all the needed vendor like Model, Controller and anything we needed from voyager to store in our Project?

**Comment by fletch3555** [comment]
Why would you want/need to...?  We already provide mechanisms to override this functionality.

**Comment by mlazuardy** [comment]
im just forget, when composer update, all the entire of my vendor its being updated including voyager, in the voyager post.php i write some relationship, and when the composer update. my RL its resetting to default configuration of voyager post.php

**Comment by fletch3555** [comment]
You should never edit files under vendor for that reason.  Instead, you should use OOP practices and the various mechanisms that Laravel and Voyager provide.  If you need to add functionality to the `Post` model, then create a Post model in your project (not vendor) that extends the Voyager one, and change the BREAD settings to point at yours.  Same with controllers.  If you need to change a view, that's thoroughly documented in both our documentation (see "Overriding views") and Laravel's views.
