### ISSUE TITLE
Roles and Users belongstomany

### ISSUE THREAD

**Issue by rlarreasanchez** [thedevdojo/voyager#2206]
- Laravel Version: 5.5.20
- Voyager Version: 1.0.0
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.7.20

### Description:
How can I establish the relationship of belonsToMany between roles and users? I tried to do it through the graphical interface, but when I delete the role_id field from the users table, it throw an error because of the role() method of the trait Voyageruser.

**Comment by fletch3555** [comment]
Voyager does not currently support users having multiple views.  You're free to try to make this work on your own, but we won't be able to help much as it's an unsupported feature.  Perhaps someone on the Slack group could help.

This has been requested a few times, and is something we plan to add in at some point, so if you get it working in an elegant way, please feel free to open a PR for us to review.
