### ISSUE TITLE
can't create migration file

### ISSUE THREAD

**Issue by ReactFan23** [thedevdojo/voyager#2208]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
when i generate new table , i can't find migration file , where can i find it ?

**Comment by fletch3555** [comment]
Voyager doesn't generate migration files.  It's a feature we're looking at implementing in a future version

**Comment by ReactFan23** [comment]
and how can i move project to other server and get same database structure how it is on local ?

**Comment by guizoxxv** [comment]
Strange. In this video from devdojo there is an option to create a migration for the table. It does not appear on mine.
https://youtu.be/ML_lS-rmTfk?t=1m39s

**Comment by fletch3555** [comment]
That video is dated nearly 1 year ago (Jan 2017), and was for a much older version.  That option only created a shell file (available for you to fill in, but containing no actual commands, equivalent to running `artisan make:migration`), so it was removed to avoid confusion.
