### ISSUE TITLE
`Select All` not present in Custom Table Page

### ISSUE THREAD

**Issue by AxDSan** [thedevdojo/voyager#2210]
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7.1.10
- Database Driver & Version: MariaDB 10.1.28

### Description:
As the title says, a `Select All` option is not present when I'm in a view more specifically, in a `Messages` page where I can have thousands of messages, the option to `Bulk Delete` is shown but not `Select All` making me click each checkbox one by one and it's a tedious task...

### Steps To Reproduce:

Create a new Table, assign data to it, you will have to select it all by yourself by ticking the checkboxes one by one.

Reference Picture:
![](https://i.imgur.com/KuBM9qr.png)

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3000
