### ISSUE TITLE
Voyager Migrations

### ISSUE THREAD

**Issue by ReactFan23** [thedevdojo/voyager#2211]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
hello how people say me voyager doesn't generate migration file , so how can i move voyager project to other server and migrate? get same structure how it is on my local machine ?

**Comment by marktopper** [comment]
It does not at the moment, it is on our todo list.

**Comment by ReactFan23** [comment]
very bad , i can't use some other package for this ? There no way?

**Comment by akazorg** [comment]
Some options:
1. create migrations using artisan commands (or just write them) and then deploy on server
2. backup your database and restore on server

I hope this helps.

**Comment by imediasun** [comment]
And How we need to merge 4 databases? :)))

**Comment by fletch3555** [comment]
@imediasun, this issue has been closed for 2 months.  If you have an problem, please open your own issue on github.  If you just have a "how do I..?" question, please join our Slack group (link in the project's readme file) and ask there.

**Comment by bryanjuanico** [comment]
@marktopper Just wanna know what's the update on this one? I kinda waiting for this feature for our website. We're using voyager on our admin panel side.
