### ISSUE TITLE
[Media] page is blank

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#2212]
- Laravel Version: 5.5
- Voyager Version:  1.0.7
- PHP Version: 7.1.8
- Database Driver & Version: phpmyadmin 4.7.0

### Description:
in localhost/admin/media there is no media listed on my page. what wrong with it?

**Comment by akazorg** [comment]
Check your storage permissions, symbolic link. Have you changed anything on the installation?

Is Voyager displaying any photos? like Posts, Pages, ...

**Comment by mlazuardy** [comment]
no sir, event i reinstall the Voyager its not display anything in my folder file

**Comment by marktopper** [comment]
Do you still have this issue?
In that case, please share a screenshot and the output of the console log.

**Comment by fletch3555** [comment]
Closing for now. This is almost certainly the result of a misconfiguration or something else in your app.  If the response to @marktopper's questions proves otherwise, we can reopen it.
