### ISSUE TITLE
App\User not found

### ISSUE THREAD

**Issue by wondergitluda** [thedevdojo/voyager#2213]
- Laravel Version: 5.5.20
- Voyager Version: 1.0.7
- PHP Version: 7.0.25
- Database Driver & Version:

### Description:

Error on → composer require tcg/voyager
Throw me to this error

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'App\User' not found

Searching on log this is the explanation error:

local.ERROR: Class 'App\User' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'App\\User' not found at /var/www/mytest.local/vendor/tcg/voyager/src/VoyagerServiceProvider.php:87) 

My local User.php model file is inside this folder app/Models/ with this namespace App\Models
and I already changed the auth.php config

    'providers' => [

        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

Of course, login works fine.

What can I do?

**Comment by akazorg** [comment]
Have you changed `user.namespace` at `config\voyager.php` file?
Confirm that. It should work.

**Comment by wondergitluda** [comment]
GREAT!

**Comment by OmarRobinson** [comment]
I have the same issue. But no **config\voyager.php** file was created after running `composer require tcg/voyager`. `php artisan voyager:install` also has the same issue. Do I need to create the file manually?

**Comment by syclone** [comment]
I have the same issue. But no **config\voyager.php** file was created after running `composer require tcg/voyager`. `php artisan voyager:install` also has the same issue. Do I need to create the file manually?

**Error Message**
```
In VoyagerServiceProvider.php line 87:
  Class 'App\User' not found
```

**Comment by fletch3555** [comment]
This issue has been closed for 3-4 months.  Please refrain from commenting on closed issues, and instead open your own or ask on our Slack group
