### ISSUE TITLE
how can i use voyager with existing database with table users that have different fields

### ISSUE THREAD

**Issue by mustafaabduljalil** [thedevdojo/voyager#2218]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I have database that have many tables and one of these tables is users table that have different fields how can i do override on users table of voyager  ?

**Comment by fletch3555** [comment]
You're free to use whatever table/model you want for users, existing or new, but you may need to customize a few things to get it to work.

Whichever model you choose, for it to work with Voyager, it needs to either implement [TCG\Voyager\Contracts\User](https://github.com/the-control-group/voyager/blob/master/src/Contracts/User.php) and use [TCG\Voyager\Traits\VoyagerUser](https://github.com/the-control-group/voyager/blob/master/src/Traits/VoyagerUser.php) OR simply extend [TCG\Voyager\Models\User](https://github.com/the-control-group/voyager/blob/master/src/Models/User.php).  Additionally, you'll have to make sure both Laravel (`config/app.php`) and Voyager (`config/voyager.php`) configs know what model to use.
