### ISSUE TITLE
redirecting issue

### ISSUE THREAD

**Issue by mohammed-elattar** [thedevdojo/voyager#2219]
Every time i am trying to open admin directly it redirects me to the home page then /public/index.php.
but if i opened the site then opened admin it is working fine ,
how to remove redirecting /public/index.php

**Comment by fletch3555** [comment]
That's not Voyager doing that.  The initial redirect from `/admin` to `/` is Voyager, and is due to not being logged in (or otherwise not having permissions).  I'm guessing the direct from `/` to `/public` is from your webserver, but it's certainly not Voyager.

**Comment by mohammed-elattar** [comment]
Thanks for your decent support
