### ISSUE TITLE
Sorry it appears there may have been a problem creating this bread

### ISSUE THREAD

**Issue by BenDunlop** [thedevdojo/voyager#222]
Since updating I have been unable to successfully 'Add BREAD to this table'.  If I edit existing breads like Posts / Pages etc it works successful.  But creating my own will not allow it to work..

**Comment by marktopper** [comment]
What version of Voyager are you on?

**Comment by bassem00** [comment]
same problem i'm using voyager v 0.9.32.

**Comment by youssef-lr** [comment]
same here with latest version.

**Comment by marktopper** [comment]
Looking into it right away.

**Comment by marktopper** [comment]
Fixed in `v0.9.33`.

**Comment by BenDunlop** [comment]
thanks mate!
