### ISSUE TITLE
Breads Not Showing Properly, After Pushing to Production

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2220]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9

### Description:
I recently pushed my project to production server. And unable to see the breads views. See the screenshot for understanding. 
Users Page: http://prntscr.com/ha7hrp
Individual User Page: http://prntscr.com/ha7i09
Posts and other bread pages that I created are showing same like users. 

PS: DB is working fine and have posts and users in it. Also I am able to fetch them at front-end.

**Comment by fletch3555** [comment]
It looks like you copied the `data_types` table, but forget the `data_rows` table

**Comment by MohsinNadeem** [comment]
ok, fletch3555. I just dropped my data_rows table and imported it again. And now my default posts page showing fine. but other users, categories etc pages are still empty like above screenshot. Can you plz help me fix them too ?

**Comment by fletch3555** [comment]
Can you get to the database BREAD editor? Please verify that everything matches correctly there.

**Comment by MohsinNadeem** [comment]
Hey fletch3555, I checked and bread editor has different settings. So I changed them manually and everything working fine. Thanks for your help. 👍 Also I have another [issue](https://github.com/the-control-group/voyager/issues/2221) , it would be great if you can help me on that one too.
