### ISSUE TITLE
no se carga voyager

### ISSUE THREAD

**Issue by rictnt** [thedevdojo/voyager#2227]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

### Description:
trabajo en mac os x mamp, envio los comandos para crear el proyecto se crea solamente los archivos y la base de datos pero nada mas
![screen shot 2017-11-14 at 11 24 18 pm](https://user-images.githubusercontent.com/30360430/32818742-fbd2451a-c992-11e7-8ec3-014749f6b89d.png)

**Comment by abacram** [comment]
Has lanzado composer install imagino al ver la carpeta vendor en tu proyecto.
¿Revisaste las configuraciones globales en app.php y voyager.php dentro la carpeta config?
¿Has ejecutado php artisan serve?

Creo que deberías aportar más información, no queda claro cuál es exactamente tu problema, por ejemplo: abro localhost:8000/admin y me sale XXXX. Sería de agradecer para poder ayudarte ;)

Un saludo!

**Comment by rictnt** [comment]
Gracias Anthony he seguido las instrucciones del manual para instalar es
decir

1.- creo el proyecto

composer create-project laravel/laravel dunamis53voyager "5.3.*"

2.- instalo voyager

$ composer require tcg/voyager

3.-creo la base de datos y configuro .env:

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=dunamis53voyager
DB_USERNAME=dunamis53
DB_PASSWORD=a1b2c3d4

4.- sigo con el comando de instaalcion

php artisan voyager:install --with-dummy

5.- y obtengo una carpeta asi anexo de imagen adjunta

6.- deberia ingresar pero no ingreso adjunto imagen del navegador

**Comment by fletch3555** [comment]
En inglés por favor

**Comment by fletch3555** [comment]
Also, Voyager 1.0 dropped support for Laravel 5.3, so you're likely getting v0.11.14, which is not supported anymore.  Why not use Laravel 5.4 or 5.5?

**Comment by rictnt** [comment]
use la version 5.3 ya que en el tutorial que estaba sigueindo usaba esa
version voy a usar en la version 5.5
gracias por tu atencion

2017-11-15 9:33 GMT-05:00 Eric Fletcher <notifications@github.com>:

**Comment by fletch3555** [comment]
De nada.

I'm going to close this for now.  If you have further issues or specific questions, please feel free to open a new issue or ask for help on our Slack group.
