### ISSUE TITLE
Cannot Crop Image on new installation

### ISSUE THREAD

**Issue by lablushah** [thedevdojo/voyager#2230]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.1.7
- Database Driver & Version: mysql 

### Description:
On a new installation of Laravel and Voyager, I cannot crop images; however, my other installation 2 months before, cropping was fine. 

### Steps To Reproduce:
New installation
![cannotcrop-voyager-media](https://user-images.githubusercontent.com/9640836/32837192-94691334-c9da-11e7-9f03-1b52848fe56f.PNG)

**Comment by Tropicalista** [comment]
Same here. Also I want to add this error in console:

> app.js:42 Uncaught ReferenceError: Cropper is not defined
    at HTMLDivElement.<anonymous> (app.js:42)
    at HTMLDivElement.dispatch (app.js:24)
    at HTMLDivElement.m.handle (app.js:24)
    at Object.trigger (app.js:24)
    at HTMLDivElement.<anonymous> (app.js:24)
    at Function.each (app.js:14)
    at ye.fn.init.each (app.js:14)
    at ye.fn.init.trigger (app.js:24)
    at HTMLDivElement.<anonymous> (app.js:85)
    at HTMLDivElement.r (app.js:14)

**Comment by fletch3555** [comment]
Can you guys try to force republish the voyager assets (specifically `app.js`)? Should be something to the effect of `artisan vendor:publish --tag="voyager_assets" --force`.  Also, please clear your browser cache to make sure it's not cached somewhere.

**Comment by Tropicalista** [comment]
I have republished and cancelled the cache without success.

**Comment by cadmicro** [comment]
I have the same issue!
Voyager  v1.0.7
Laravel   5.5 (latest)
php 7.0

**Comment by Janghou** [comment]
same problem:
`ReferenceError: Cropper is not defined app.js:42:12284`

new install today v1.09
using server.php

**Comment by grzeee** [comment]
On my app ( v1.0.7 ) it doesn't work since i had install this version of voyager, it is probably some bug.

**Comment by joinerleal** [comment]
I am facing the same issue on v1.0.10, I did what @fletch3555 mentioned and the problem persist.

I've found a turnaround by manually copy&paste the content from [https://github.com/fengyuanchen/cropperjs/blob/master/dist/cropper.min.js](url) at the begining of the public/vendor/tcg/voyager/assets/js/app.js

![imagen](https://user-images.githubusercontent.com/11859858/34317467-c0b14c86-e785-11e7-9779-5eaade5b1712.png)

Maybe app.js is getting corrupted?

**Comment by quaidesbalises** [comment]
Same problem as well on fresh install !

**Comment by aqualaguna** [comment]
the compiled app.js and app.css does not contain the dependency hence the error popup.
its not compiled thoroughly btw here the import ::
berfore importing app.js at master.blade.php
```
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/perfect-scrollbar.jquery.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/readmore.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/select2/select2.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.matchHeight-min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/bootstrap-toggle.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('lib/js/ace/ace.js')}}"></script>
<script type="text/javascript" src="{{ voyager_asset('js/ga-embed/moment.min.js')}}"></script>
<script src="{{ voyager_asset('js/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
```

and before app.css import::
`<link rel="stylesheet" href="{{ voyager_asset('lib/css/bootstrap.min.css') }}">`

**Comment by MYSEY** [comment]
efs
