### ISSUE TITLE
generic route issue outsite admin

### ISSUE THREAD

**Issue by jouniikaheimo** [thedevdojo/voyager#2231]
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7.0
- Database Driver & Version:

### Description:
issue is generic route 
// public routes
Route::any('/{controller}/{method}/{param}', function ($controller, $method, $param) {
    return call_user_func_array($controller . '::' . $method, $param);
});

if that in web.php /admin stuck in loadin icon spinner.. someone any idea how i can that fixed

**Comment by fletch3555** [comment]
The order of your routes matter.  By adding that, you're overriding some of Voyager's routes, which is causing AJAX calls to fail.  You need to move that route to whatever location works (can't remember if it needs to be first or last)
