### ISSUE TITLE
I make changes but then I lose them

### ISSUE THREAD

**Issue by jhoysner** [thedevdojo/voyager#2238]
- Laravel Version: 5.5.
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:

I make changes but then I lose them, when I throw a refresh to the database, or when I commit and my partner drops the project the changes in the builder and database are lost, that is, the graphical changes like Server Server side-Pagination , example relize a view custom and controller but when I upload to the repository and my partner part of there has to configure everything equal togregister the menu and everything.

![image](https://user-images.githubusercontent.com/6835168/32866209-d73681bc-ca3c-11e7-8d11-fa3f0442463c.png)

**Comment by fletch3555** [comment]
I'm sorry, I don't quite understand your problem... What exactly are you losing, and what exactly are you doing when it happens?
