### ISSUE TITLE
Use components and slots in pages and posts

### ISSUE THREAD

**Issue by AsyncPiMaker** [thedevdojo/voyager#2239]
- Laravel Version: 5.5
- Voyager Version: 1.0.7

### Description:
Is there a way to do components and slots or something similar for reusable HTML?

### Steps To Reproduce:
Tried components and slots in project views, project views/partials and vendor folders.

**Comment by fletch3555** [comment]
I don't follow... Where did you get the idea that Voyager supports that? Are you following some tutorial?  What exactly are you trying to do?

**Comment by AsyncPiMaker** [comment]
Sorry, I saw that these features are supported as of Laravel 5.4 and can make it work for pages in file folders. So, I thought it might be supported in the posts and pages. 

I hope no offense has been caused as Voyager is a wonderful package.

**Comment by AsyncPiMaker** [comment]
Sorry, I didn’t completely reply. 

What I am trying to achieve is reusable HTML snippets across posts and pages.

**Comment by fletch3555** [comment]
Then you're welcome to build that.  Voyager doesn't provide such functionality.  If Laravel does, then it's in the Blade view functionality, which Voyager uses, but Voyager does not provide any kind of UI for this.
