### ISSUE TITLE
voyager 1.07 icon in bread not display properly. 

### ISSUE THREAD

**Issue by DaKe-Zhang** [thedevdojo/voyager#2240]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description
after upgrad to 1.07, the icon in BREAD is not right. please see the pic for detail
![image](https://user-images.githubusercontent.com/16347790/32873087-cc032026-ca4f-11e7-8f4c-625a8646d0cc.png)

**Comment by Victor-emil** [comment]
The browse_bread translation can be fixed by running the following command to republish the language files:
php artisan vendor:publish --tag=lang --force

Also make sure to run to publish the css, js and icon assets to the public directory.
php artisan vendor:publish --tag=voyager_assets --force

**Comment by fletch3555** [comment]
Exactly what @Victor-emil said.  If that doesn't work, please delete the `resources/lang` directory and run it again.

**Comment by DaKe-Zhang** [comment]
@Victor-emil Thank you so much! that works perfectly!
