### ISSUE TITLE
Error when trying to save something to table

### ISSUE THREAD

**Issue by medobelk** [thedevdojo/voyager#2243]
- Laravel Version: 5.5
- Voyager Version: 1.0

### Description:
When i am trying to save/edit data to table click on the "save" button throws error to console 

![error](https://user-images.githubusercontent.com/26491206/32891851-e501c77a-cadc-11e7-84bc-e15ca0fa2293.png)

**Comment by fletch3555** [comment]
"data to table"... what table?  Please be more specific.

**Comment by medobelk** [comment]
okay sorry (i am new to programming). to my own self created table. i have created new project then installed voyager and after all started to import tables via phpmyadmin then set up BREAD and when i decided to test all i ran into error.

**Comment by fletch3555** [comment]
So the error happens AFTER you've created the table, AFTER you've created the BREAD, and WHILE you're using the BREAD pages (add/edit) for your type (i.e. pages, posts, users, etc.), correct?

**Comment by medobelk** [comment]
yes. there are two small bugs too on one of my menu items not showing icon and when i open it's page on browse there are no bulk delete button. :_(

**Comment by cyrildewit** [comment]
@medobelk do you still encounter this issue?

**Comment by fletch3555** [comment]
Closing due to age.  @medobelk, if this is still an issue, please open a new issue with updated information
