### ISSUE TITLE
Override widgets upon user's role

### ISSUE THREAD

**Issue by Himhotep** [thedevdojo/voyager#2248]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.1.10
- Database Driver & Version:

### Description:

How (and where) can I set that?
\Config::set('voyager.dashboard.widgets', getWidgets() );

**Comment by fletch3555** [comment]
I don't understand the question... Please provide more detail in your question

Widgets are defined at the bottom of `config/voyager.php`

**Comment by Hujjat** [comment]
@fletch3555 I think he means, we should display widgets based on user rules. 

For instance, if the user is an admin, it should display some widget, if the user is a standard user, it should display some other widget no none. 

@Himhotep 

Here is how you do that. 
1. First, learn how to create a custom widget. Watch [this video](https://laravelvoyager.com/academy/widgets/) for that. 
2. You can set permission inside run function in your custom widget. 

`

    public function run()
    {
        // Return true if auth user can read post
        $canViewPost = Auth::user()->can('read', $post);
        // If true, show the widget
        if ($canViewPost) {
            $count = Voyager::model('User')->count();
            $string = trans_choice('voyager.dimmer.user', $count);

            return view('voyager::dimmer', array_merge($this->config, [
                'icon'   => 'voyager-group',
                'title'  => "{$count} {$string}",
                'text'   => __('voyager.dimmer.user_text', ['count' => $count, 'string' => Str::lower($string)]),
                'button' => [
                    'text' => __('voyager.dimmer.user_link_text'),
                    'link' => route('voyager.users.index'),
                ],
                'image' => voyager_asset('images/widget-backgrounds/01.jpg'),
            ]));           
        }else{
            // something else
        }

    }

`

You can adjust the code for yourself. 

Hope it helps you.

**Comment by Himhotep** [comment]
Thanks, @Hujjat, but I think that doesn't work right.

You have to replace "something else" for what? 
You have to return content to display (a crash if you don't) and then you'll have a white <div class="col...

At the moment, waiting roles for widgets (as for menus) I'm editing /resources/views/vendor/voyager/dimmers.blade.php:
```
@php
    $dimmers = \Arrilot\Widgets\Facade::group('voyager::dimmers');

    if(!Voyager::can('browse_associate')){
        $dimmers->removeByName('App\\Widgets\\AssociatesDimmer');
    }
...

**Comment by marktopper** [comment]
You can remove dimmers dynamically.
More information at: https://github.com/arrilot/laravel-widgets
