### ISSUE TITLE
Image does not upload properly

### ISSUE THREAD

**Issue by deep88** [thedevdojo/voyager#225]
- Laravel Version: #5.3.#.#
- Voyager Version: #.#.#
- PHP Version: 7.0
- Database Driver & Version: Mysql on xamp (windows)

### Steps To Reproduce:
images uploads into framework dtorage directory instead of within public_path 

G:\Dropbox\websites\voyager\storage\app\public\pages

however it should be something like 
G:\Dropbox\websites\voyager\public\storage\pages

**Comment by handiwijoyo** [comment]
@deep88 try run this command to create symbolic link from "public/storage" to "storage/app/public":

```
php artisan storage:link
```

**Comment by deep88** [comment]
thanks solved..

when i try to creat bread for any model this error appears

http://prntscr.com/dd6tig

**Comment by deep88** [comment]
whereas model has only one field title (varchar)   

http://prntscr.com/dd6xsf

**Comment by fletch3555** [comment]
@deep88, that appears to be a unique issue, unrelated to the issue described here.  ~~Could you please open a new issue identifying your BREAD creation difficulties?~~ Ninjedit: Looks like #226 already discusses this

I'm going to close this one as the problem as been resolved.

Thanks!
