### ISSUE TITLE
Image upsize and quality settings are ignored

### ISSUE THREAD

**Issue by lfbittencourt** [thedevdojo/voyager#2250]
- Laravel Version: 5.5.20
- Voyager Version: 1.0.7
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7.20

### Description:

Voyager ignores any upsize and quality settings on image and multiple image uploads. Controller code (https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L221-L228) uses the same constraints and quality (75) no matter what you've defined on the BREAD.

### Steps To Reproduce:

1. Add the following extra options to your field:

```
{
    "resize": {
        "width": 200,
        "height": 200
    },
    "quality": "100%",
    "upsize": true
}
```

2. Upload a rectangular image
3. Resulting image will be rectangular (not a 200x200px squared image) with 75% of quality (not 100%)

PS: maybe it's related to #1328.

**Comment by dam62500** [comment]
upsize still doesn't work with fix #2381

**Comment by fletch3555** [comment]
There hasn't been a release containing that fix yet.  How do you know it's not working?

**Comment by andrey-helldar** [comment]
Today is the 19th of April. The current stable version is [v1.2.3](https://github.com/the-control-group/voyager/releases/tag/v1.2.3).
Upsize doesn't work 😔

UPD: founded a temporary solution:
```json
{
    "resize": {
        "width": "1920",
        "height": "1080"
    },
    "quality": "90%",
    "thumbnails": [
        {
            "name": "big",
            "crop": {
                "width": "1920",
                "height": "1080"
            }
        }
    ]
}
```
