### ISSUE TITLE
Bread EDIT is creating new entry

### ISSUE THREAD

**Issue by amitn322** [thedevdojo/voyager#2252]
- Laravel Version: 5.4.1
- Voyager Version: 1.0
- PHP Version:5.4
- Database Driver & Version: MYSQL 

### Description:
When editing an item with bread , it is not updating , but creating a new entry in the database.

### Steps To Reproduce:
Go to BREAD , edit and save changes, the item will be duplicated.

**Comment by dfk7677** [comment]
I cannot even install 5.4.1 to test. Maybe update to the latest 5.4 version of Laravel?

**Comment by handiwijoyo** [comment]
Can someone confirm this issue still persist in the latest Voyager version?

**Comment by adrie-tc** [comment]
Yes, using an alternate primary key will do just the above.
Something like the following in a custom Model:

`protected $primaryKey = 'md5_combined_key';`

Issue was reported before: #1861 
And quite possibly: #1961

**Comment by emptynick** [comment]
This was likely fixed in #2690
