### ISSUE TITLE
Add Multiple Category to a post and save in pivot table

### ISSUE THREAD

**Issue by annapurnasid** [thedevdojo/voyager#2253]
- Laravel Version: 5.4.36
- Voyager Version: 1.0
- PHP Version: 5.6
- Database Driver & Version: MYSQL

### Description: 
I have added a custom table PostCategories. Now I want a belongsToMany relation for Post and Category, since one post can have multiple categories and single category may belong to many posts. I want a pivot table to have the data stored with fields post_id and category_id. How do I do this?

**Comment by VizuaaLOG** [comment]
If I understand you correctly, you will need to edit the BREAD options for the post table adding a new relation and setting the options in there. Your edit/add form will then either need to be modified to include the new field how you like, or it may appear under the 'extra fields' section on the form you get out of the box.

**Comment by annapurnasid** [comment]
yep..i got it working.
Thanks :)

**Comment by vFire** [comment]
Is it possible to copy paste the related code? I have no idea how to modify the view to show it and how to store into the model. Thanks.
