### ISSUE TITLE
Insert image from media library

### ISSUE THREAD

**Issue by annapurnasid** [thedevdojo/voyager#2254]
- Laravel Version: 5.4.36
- Voyager Version: 1.0
- PHP Version: 5.6
- Database Driver & Version: MYSQL

### Description:
How do I choose images from the media library instead of uploading single image multiple times?
Clicking on the image button in the HTML editor for posts, It gives the option to upload an image, but not to chose one from the existing library.

**Comment by fletch3555** [comment]
That functionality is not currently possible out of the box with Voyager, but has been requested a few times.  It's just waiting on implementation.

**Comment by nabbs** [comment]
when will this be implemented?

**Comment by ynizon** [comment]
I have done an article to explain "how" (but it's in french)
I hope , it will help you.
https://www.gameandme.fr/creation-web/ajouter-des-medias-directement-dans-ses-articles-depuis-le-cms-voyager/
