### ISSUE TITLE
Preview Post before Publishing

### ISSUE THREAD

**Issue by annapurnasid** [thedevdojo/voyager#2255]
- Laravel Version: 5.4.36
- Voyager Version: 1.0
- PHP Version: 5.6
- Database Driver & Version: MYSQL

### Description:
How can i change the link for "VIEW" button across each post. It gives me the post with the form. I want to preview my post, to see how it would look in my frontend.

Should I add a custom preview button? if yes, how? or should I try changing the href attr for **view** button?

**Comment by fletch3555** [comment]
You would need to override the post view to change the href.

Issues should be reserved for bugs and other code issues.  Implementation questions should be asked on our Slack group, forums, or other media, where you can get more individualized support.
