### ISSUE TITLE
Documentation and other text parts of website unreadable because of low contrast

### ISSUE THREAD

**Issue by COLABORATI** [thedevdojo/voyager#2256]
Hi, I really like your project, this is why I am taking this problematic role of trying to make you aware of the fact that parts of your website are not clearly readable because of low contrast - especially the left navigational part of the documentation, which is very good otherwise, is unnecessarily vilified with this desease. Please also read http://contrastrebellion.com/ to understand why contrast is important. Thanks!

**Comment by fletch3555** [comment]
Thank you.  We're content with the design as-is for now, but will certainly keep that in mind next time we look at a redesign.
