### ISSUE TITLE
Can't create new Breads

### ISSUE THREAD

**Issue by garposmack** [thedevdojo/voyager#226]
- Laravel Version: 5.3
- Voyager Version: 0.9.31
- PHP Version: 5.6
- Database Driver & Version: MySql 5.6.30

Can't create any BREAD. When i try to create a BREAD a get the following message:
"Sorry it appears there may have been a problem creating this bread"
I'm able to create tables and to edit existing BREAD, but can't create new ones.

Steps To Reproduce:
- Login
- Go to Settings -> Database
- Click on the Add Bread for this table
- Complete the form o leave as it is
- Click the Submit button
- The error message appears on the top rigth of the screen.
![screen shot 2016-11-29 at 11 06 34 am](https://cloud.githubusercontent.com/assets/744310/20712680/ef098b00-b623-11e6-8d0c-bc78253c883e.png)

**Comment by bassem00** [comment]
same problem, it doesn't even create models.

**Comment by garposmack** [comment]
In my case the models are created, and also the database tables are created.

**Comment by fletch3555** [comment]
Do you see any errors in the laravel logs?

**Comment by fletch3555** [comment]
Same as #222.  Should be fixed in #229
