### ISSUE TITLE
An Issue in deleting the item 

### ISSUE THREAD

**Issue by Hujjat** [thedevdojo/voyager#2261]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.
- PHP Version: 7.1
- Database Driver & Version:

### Description:

I have created a product bread like the academy video. When I delete the product. It shows the search form above delete modal. 

![capture](https://user-images.githubusercontent.com/5115878/33057903-d63e129a-ceae-11e7-92a6-0aa6c34d5def.PNG)

The problem is with CSS class. As you can see.

**Comment by fletch3555** [comment]
I thought we fixed this... Might be in a PR that hasn't been merged yet.

**Comment by emptynick** [comment]
No problem anymore.
Fixed in #2076 
Republish your assets with
`php artisan vendor:publish --tag=voyager_assets --force`

**Comment by Hujjat** [comment]
@emptynick Thank's :)
