### ISSUE TITLE
Custom item on Sidebar Admin Menu won't show.

### ISSUE THREAD

**Issue by bimo13** [thedevdojo/voyager#2262]
- Laravel Version: 5.4.0
- Voyager Version: 1.0
- PHP Version: 7.0.24-1 on Ubuntu 14.04
- Database Driver & Version: MySQL 5.6.37

### Description:
Hi everyone, I'm currently developing an admin-room with Voyager. What I'm trying to do is : I want to create a custom menu (custom form-page) in it, without any BREAD or database table related to the form. I've tried to create a menu using the "Menu Builder" feature, yet it is not displayed on the sidebar menu. Would it be possible ? maybe I'm missing something while I'm creating the menu. I've created the routes also the controller for the menu, and also I already be able to access the page by typing the URL manually in the address bar.

Screenshot 1 : http://prntscr.com/hd8moa
Screenshot 2 : http://prntscr.com/hd8n07

The custom item is the "**Affiliate Users**"

### Steps To Reproduce:
Create a menu using the "Menu Builder", put the custom routes/URL in it and save it. Manage the order on the "Menu Builder" drag-and-drop ordering page. The menu still not showing in the sidebar menu.

**Comment by bedoz** [comment]
Same here, custom route on routes.php in menu the voice don't show (menu created with creator).
Maybe same issue as [https://github.com/the-control-group/voyager/issues/2241](2241)

**Comment by fletch3555** [comment]
Yes, same issue as #2241.  See my response here: https://github.com/the-control-group/voyager/issues/2241#issuecomment-344951270

**Comment by yarob55** [comment]
when will this problem be solved ? it's very frustrating !
