### ISSUE TITLE
use of the voyager admin panel as the home page of the web app?

### ISSUE THREAD

**Issue by rajaee-rad** [thedevdojo/voyager#2267]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1.10
- Database Driver & Version: mysql

### Description:
i want create a web app with main dashboard which any user(admin-normal user) after login redirected to this.just like voyager admin panel.is it the right way if use just voyager admin panel for main page of web app?

**Comment by maxkrasnov** [comment]
Of course, in you project /routes/web.php 
change it
```
Route::group(['prefix' => 'admin'], function () {
     Voyager::routes()
});
```
on
```
Voyager::routes();
```

**Comment by fletch3555** [comment]
Voyager is intended to be an admin tool, not a generic dashboard for your site.  I'm not saying it can't be used that way, but we can't walk you through it.  If you have specific questions, we suggest you join our Slack group and ask there.
