### ISSUE TITLE
Call to undefined method getCoordinates()

### ISSUE THREAD

**Issue by amirhilal** [thedevdojo/voyager#2268]
- Laravel Version: 5.5.21
- Voyager Version: ^1.0
- PHP Version: 7.1.11
- Database Driver & Version: 

### Description:
Using Coordinates throws out an undefined method getCoordinates()

Call to undefined method Illuminate\Database\Query\Builder::getCoordinates() (View: \vendor\tcg\voyager\resources\views\partials\coordinates-static-image.blade.php) (View: \vendor\tcg\voyager\resources\views\partials\coordinates-static-image.blade.php)

### Steps To Reproduce:
Use a varchar (255) and name it anything and use Coordinates from BREAD

**Comment by fletch3555** [comment]
`getCoordinates()` is defined in the [Spatial trait](https://github.com/the-control-group/voyager/blob/bb25c3f7369eb324e0a1b012458326e8c08fc942/src/Traits/Spatial.php).  I don't remember exactly where that gets added, but I believe you have to use a specific field type (likely called Spatial), not just `varchar(255)`

**Comment by amirhilal** [comment]
I tried all spatial types, I think point should be the one to work but it didn't ... they all give the same error

**Comment by Rhymond** [comment]
I have same issue

**Comment by Rhymond** [comment]
You need to use Spatial Trait
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Spatial;

class YouModel extends Model
{
    use Spatial;
    //
}
```

**Comment by grzeee** [comment]
I have same issue in voyager admin panel, please help !
In database i have use POINT type on column and the error is the same.
I have set the api key in my config file.

**Comment by fletch3555** [comment]
@grzeee, does the model class for your table use the `Spacial` trait like @Rhymond's comment says?

**Comment by grzeee** [comment]
@fletch3555 thank you for your for patience ;) it is worked.
It worth to describe this bread type in documentation.

Voyager is awesome !

**Comment by fletch3555** [comment]
Agreed.  Also, the documentation is open for suggestions directly through readme.io, so feel free to suggest changes there.

**Comment by fletch3555** [comment]
@Rhymond's comment provides the correct solution.  Closing
