### ISSUE TITLE
Where are newly created Models?

### ISSUE THREAD

**Issue by mankowitz** [thedevdojo/voyager#2269]
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7.0.22
- Database Driver & Version: mysql 6.7.20

### Description:
When creating tables and models with voyager, I can't tell where the relationships are. For example. App\Note BelongsTo App\User. When I use the admin panel, I can see the relationship and use the dropdown to pick appropriate links. However, the model in /app/User.php remains unmodified. Is there a modified model that I can use for logic in the rest of the site?

**Comment by fletch3555** [comment]
To answer the question as asked: When you create a new BREAD, with the "generate model" option checked, the model class is put into the appropriate folder based on the namespace you give it.  For example, `App\Foobar` will be created as `app/Foobar.php`.

To answer the question I believe you intended to ask: When adding a relationship to a BREAD, Voyager does not add the relationship methods to your models, so you will not see an updated model.  These relationships are for Voyager's use only (currently).  If you want the same relationship for your own use, you will need to write that method yourself.
