### ISSUE TITLE
Chronological order of migrations doesn't work

### ISSUE THREAD

**Issue by Jakobud** [thedevdojo/voyager#2270]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 7.x
- Database Driver & Version: MySQL 14.14

I'm trying to get Voyager installed. I just created a new Laravel app. When I install Voyager, it creates the following migrations:

```
2016_01_01_000000_add_voyager_user_fields.php
2016_01_01_000000_create_data_types_table.php
2016_01_01_000000_create_pages_table.php
2016_01_01_000000_create_posts_table.php
2016_02_15_204651_create_categories_table.php
2016_05_19_173453_create_menu_table.php
2016_10_21_190000_create_roles_table.php
2016_10_21_190000_create_settings_table.php
2016_11_30_135954_create_permission_table.php
2016_11_30_141208_create_permission_role_table.php
2016_12_26_201236_data_types__add__server_side.php
2017_01_13_000000_add_route_to_menu_items_table.php
2017_01_14_005015_create_translations_table.php
2017_01_15_000000_add_permission_group_id_to_permissions_table.php
2017_01_15_000000_create_permission_groups_table.php
2017_01_15_000000_make_table_name_nullable_in_permissions_table.php
2017_03_06_000000_add_controller_to_data_types_table.php
2017_04_11_000000_alter_post_nullable_fields_table.php
2017_04_21_000000_add_order_to_data_rows_table.php
2017_07_05_210000_add_policyname_to_data_types_table.php
2017_08_05_000000_add_group_to_settings_table.php
```

So, this doesn't work with my installation because of the chronological order that the migrations run. My users table migration is `2017_11_21_000000_create_users_table.php`. So this messes up the migrations since the users table needs to be one of the first migrations to run and not the last.

How do you get around this problem? Are users really expected to rename migration files?

**Comment by fletch3555** [comment]
The date stamp is there for the sole purpose of ordering, so yes, if they're out of order, you're expected to reorder them.  That's a laravel thing, not a voyager thing.

Now, Why do you have an 11/21/2017 migration for the users table? I thought Laravel shipped with one dated much older, not one dated the date you install it.

**Comment by Jakobud** [comment]
I had to create my own Users table migration from scratch.

**Comment by fletch3555** [comment]
Then yes, I would rename that one to be prior to Voyager's migrations (likely a good idea to just set it to the date used by laravel's user table migration.

Out of curiousity, any reason you couldn't just modify the one laravel gives you?

**Comment by Jakobud** [comment]
Well renaming a file is easy but if you have already run migrations then the migrations database table has those file names stored in them. Now you have to hack db tables to make it work. Just seems kind of hacky. How come you guys don't generate migration files using timestamps of the time/date of installation? Seems better to do something like that then asking people to go back and rename project files to make it work. I dunno.

**Comment by fletch3555** [comment]
We don't ask people to go back and rename it.  Voyager requires Laravel's default auth framework, which includes migrations.  You've chosen not to use those migrations and to create your own instead.  That's not Voyager's fault.
