### ISSUE TITLE
Question: Is there an easy way to remove Posts / Categories / Pages?

### ISSUE THREAD

**Issue by shaneparsons** [thedevdojo/voyager#2272]
- Laravel Version: latest
- Voyager Version: latest

### Question:
Is there an easy way to remove Posts, Categories and Pages?

Having the option to exclude them in the first place (e.g. a flag on the install command) would be great.

**Comment by fletch3555** [comment]
Installing without `--with-dummy` will prevent the tables from being populated, but will not prevent the tables from being created.  You'll need to delete the migrations, remove the entries from the MenuItemsSeeder, and remove the widget configuration from `config/voyager.php`.  That SHOULD be all you have to do (though I likely missed a step somewhere)
