### ISSUE TITLE
Dashboard shows things that shouldn't be available to Role

### ISSUE THREAD

**Issue by Jakobud** [thedevdojo/voyager#2275]
- Laravel Version: 5.5.21
- Voyager Version: 1.0
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 14.14

I have a role that only should allow access to Posts. But I have to also allow the role to be able to "Browse Admin". So when that user logs in to the dashboard they see this:

<img width="1628" alt="screen shot 2017-11-22 at 2 54 10 pm" src="https://user-images.githubusercontent.com/87356/33149731-638db852-cf96-11e7-9a38-bbf4852fb2c5.png">

They shouldn't see the Users or Pages section at all. It doesn't seem like the dashboard is respecting the role privileges. If either of those is clicked, they get this:

<img width="1282" alt="screen shot 2017-11-22 at 2 54 01 pm" src="https://user-images.githubusercontent.com/87356/33149763-809a9a8c-cf96-11e7-9569-957dc9f09ef2.png">

**Comment by fletch3555** [comment]
Those widgets don't currently respect permissions.  You're welcome to submit a PR to change that.

**Comment by Jakobud** [comment]
Okay. Is it possible to hide certain widgets?

**Comment by akazorg** [comment]
@Jakobud try the `config/voyager.php`.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3058
