### ISSUE TITLE
Delete BREAD instead of TABLE

### ISSUE THREAD

**Issue by mankowitz** [thedevdojo/voyager#2276]
### Description:

When deleting a table, the prompt asks if you want to delete BREAD

### Steps To Reproduce:

Go to databases > delete table

### Fix

replace line 117 in index.blade.php
`                    <h4 class="modal-title"><i class="voyager-trash"></i> {!! __('voyager.database.delete_table_bread_quest', ['table' => '<span id="delete_table_name"></span>']) !!}</h4>`
with
`                    <h4 class="modal-title"><i class="voyager-trash"></i> {!! __('voyager.database.delete_table_question', ['table' => '<span id="delete_table_name"></span>']) !!}</h4>`

PS: I suspect that this should have been done with a pull request, but I'm not sure how to do that. If there's a step-by-step tutorial, I'd be glad to do that in the future.

**Comment by akazorg** [comment]
Hi @mankowitz, thanks for the report.

For collaboration, (short answer), you have to:
1. fork voyager repository
2. create a branch for this issue (example `fix-2276-delete-bread-typo`)
3. do your change
4. submit the Pull Request

**Comment by cyrildewit** [comment]
Is this still an issue? Otherwise I can take a look at it.

**Comment by cyrildewit** [comment]
I looked at the code in the `v1.x-dev` and it looks fine to me. The current behavior when clicking on the **delete** table  button at _/admin/database_ is:

If table contains `bread` -> ask user to remove the bread first (notification message: _Please make sure to remove the BREAD on this table before deleting the table._).

If not -> ask user if he's sure about the deletion of the _xxx_ table (confirmation message: _Are you sure you want to delete the lorem ipsum table?_).

Should I check the `1.0` branch too? If not, then this issue can be closed.

**Comment by temikeezy** [comment]
Yeah, my Delete BREAD button isn't working at all. Clicking it does nothing at all

**Comment by cyrildewit** [comment]
What version of Voyager do you have installed?

````winbatch
composer show -i
````

**Comment by temikeezy** [comment]
I'm using voyager v1.1.0. Also tried in both Chrome and Firefox. Same thing, **Delete BREAD** button does nothing.
