### ISSUE TITLE
users can add the settings section even though they do not have permissions. and this is causing a error

### ISSUE THREAD

**Issue by tanerincode** [thedevdojo/voyager#2277]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1

### I don't know if this problem is just for me. users can add the settings section even though they do not have permissions. and this is causing a error. I add error images

![1](https://user-images.githubusercontent.com/12814082/33189757-fb187902-d0b6-11e7-9831-87ef46355eec.png)
![2](https://user-images.githubusercontent.com/12814082/33189758-fb390956-d0b6-11e7-9c9c-03be4e838d28.png)

**Comment by tanerincode** [comment]
I solved the problem this way:

`@if( \Illuminate\Support\Facades\Auth::user()->role_id == 1 ) .... @endif `

**Comment by fletch3555** [comment]
@taner-in-code, a better solution would be to just use Laravel's built-in auth functionality, which Voyager has implemented Policies to hook into.  Instead of checking the `role_id` directly, you should check for the appropriate permission with `@can()`

**Comment by tanerincode** [comment]
thank you for the information, I needed a momentary solution. I made a correction as you said later. @fletch3555
