### ISSUE TITLE
Breadcrumbs shows multiple subpaths

### ISSUE THREAD

**Issue by SAM-AEL** [thedevdojo/voyager#2279]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.0.22
- Database Driver & Version: MariaDB & 10.1.25

### Description:

set the admin route path on routes.php and voyager.php. it consists of two subpaths,
'admin/sVp7JAnBNg2ZGUMLGmY/xxZD60XCNTCLyZZ5NVa'. like in screenshots.

![ewrew](https://user-images.githubusercontent.com/14927758/33208216-b991a366-d136-11e7-95ff-3bd874e3c30d.PNG)
![fdgdfgd](https://user-images.githubusercontent.com/14927758/33208217-b9c74886-d136-11e7-8f27-4ea327501099.PNG)

even after this the breadcrumbs shows wrong paths with 2 wrong paths. it should be just one root path

![3333](https://user-images.githubusercontent.com/14927758/33208407-668af5f4-d137-11e7-97df-c89770f0f245.PNG)

**Comment by maxkrasnov** [comment]
#2301 fix, and prefix admin change on config file

**Comment by fletch3555** [comment]
#2307's fix caused new issues, so it has been reverted.  Reopening this one.

**Comment by emptynick** [comment]
Closing as #3850 was merged (into 1.x, to be released in a future 1.2 release)
