### ISSUE TITLE
Error creating model with BelongsTo

### ISSUE THREAD

**Issue by ashraj98** [thedevdojo/voyager#2280]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.6
- PHP Version: 7.1.11
- Database Driver & Version: MariaDB 10.2.10

I am not able to configure Voyager to create a model for me, with two BelongsTo relationships.
A belongs to B and A belongs to C.
I made the bread for A, B, and C, and added both the relationships to A. This works fine. Then I create sample data for B and C, and this also works fine.
Then I try to create a row for A. This does not work. I get the error 'Column does not have a default value' for the b_id column in A. I have also tried making b_id and c_id nullable in the migration, but then it simply doesn't attach anything. Once, I also got an error that the foreign key constraint was failing because the script was inputting a value of 0 for b_id and c_id, which obviously is not a valid value for an ID.

I shouldn't have to put nullable on the column for this to work. I want to constrain it so A must be attached to a model of B and a model of C.

**Comment by cyrildewit** [comment]
@ashraj98 do you still encounter this issue?
