### ISSUE TITLE
[Request] tags column in the admin panel

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#2281]
- Laravel Version: 5.5
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: 4.7.1  php my admin

### Description:
the only things that need to put in laravel voyager is tags, can i request the column for tags?
or it can be overwritten? please give me some short tutorials

**Comment by fletch3555** [comment]
You're free to add tags in your own project if you wish.

**Comment by mlazuardy** [comment]
thank you sir :) i give the star for this awesome Package . really helpful
