### ISSUE TITLE
Question: Select2

### ISSUE THREAD

**Issue by mateushackfaccat** [thedevdojo/voyager#2284]
- Laravel Version: 5.5
- Voyager Version: 
- PHP Version: 7.1
- Database Driver & Version: PSQL

### Description:

I would like to know if the Voyager with integration with Select2 manual without being of form.

**Comment by fletch3555** [comment]
Sorry, but I don't understand the question.

**Comment by mateushackfaccat** [comment]
I need to use Select2 in a form. Does the voyager have any resources for this, or do I need to use this feature externally and install Select2 (select2.org) manually?

**Comment by fletch3555** [comment]
When you say "in a form", are you referring to a form within Voyager (for use with Voyager's BREAD functionality), or something you are creating for your site (i.e. a "contact us" form)?

**Comment by mateushackfaccat** [comment]
I'm referring to using it within a BREAD functionality. Using relationships for this. With other tests of other CRUD's was easy to implement, however with Voyager I'm having difficulties. Such a robust system not having such functionality is almost a sin.

**Comment by mateushackfaccat** [comment]
I have seen that there is an option in creating BREAD of Select Multiple, but in the documentation there is nothing about it or how to use it. Has anyone had any experience with Select multiple to share?

**Comment by emptynick** [comment]
It is basically the same as [Dropdown](https://voyager.readme.io/docs/additional-field-options#section-drop-down)
