### ISSUE TITLE
Multiple column search

### ISSUE THREAD

**Issue by ichtrojan** [thedevdojo/voyager#2286]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
How can i make every column have a search bar for the bread browse view 

### Steps To Reproduce:
i need something like this 
![screen shot 2017-11-28 at 7 00 16 pm](https://user-images.githubusercontent.com/5338836/33335829-7b8438a0-d46e-11e7-98ab-d15b84759e31.png)

**Comment by mateushackfaccat** [comment]
With select2, but I'm not getting it to work. I saw that Voyager has a multiple select function, but it has nothing in the documentation that specifies its use.

**Comment by ichtrojan** [comment]
Any Ideas on how to make it work that way? @mateushackfaccat

**Comment by mateushackfaccat** [comment]
I'm manually using Select2 -> select2.org/getting-started

But Select2 has this built-in functionality, but I did not find anywhere in the documentation how its implementation would be.

**Comment by ichtrojan** [comment]
ok would check it out

**Comment by ichtrojan** [comment]
not helpful @mateushackfaccat

**Comment by mateushackfaccat** [comment]
The logic is the same. You type parts of a string and it queries for equivalences in the database.
Of course you would have to adapt it for your use.
Here I am using it to search for registered addresses in new registrations.

**Comment by emptynick** [comment]
Using Select2 would require to preload each and every single field from the model.
Taken from your screenshot:
In this case you have 5 columns and 58k entries. Would make 290k additional lines of code (for each option in the select) + browser resources and so on.

**Comment by ichtrojan** [comment]
@emptynick any other suggestion?

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/4216
