### ISSUE TITLE
Cover Image Upload Field Accepts Non-Image Filetypes

### ISSUE THREAD

**Issue by ux-engineer** [thedevdojo/voyager#2287]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.1.9

### Description:

Voyager default Pages datatype's image field (perhaps others) accepts PDF file as chosen by the file picker. But upload ends with an error page:

```Unsupported image type. GD driver is only able to decode JPG, PNG, GIF or WebP files.```

### Suggestion:

Image file input element should have [_accept_ attribute](https://stackoverflow.com/questions/3828554/how-to-allow-input-type-file-to-accept-only-image-files) defined for restricting the user to being able to choose only image files.

**Comment by fletch3555** [comment]
Agreed.  We're open for pull requests
