### ISSUE TITLE
Can't save new multilingual page

### ISSUE THREAD

**Issue by def-media** [thedevdojo/voyager#2288]
- Laravel Version: 5.5.21
- Voyager Version: 1.0.7
- PHP Version: 7.0
- Database Driver & Version: MySQL 10.1.24-MariaDB-cll-lve

### Description:
Can't save new multilingual page.
The Developer Tools console shows error: "An invalid form control with name='body' is not focusable."
There is a hidden textarea element (name="body", id="richtextbody") with the "required" attribute.
When I press "Save" this textarea element does not pass validation and the form cannot be submitted.
![Voyager bug](https://www.cyclolika.com/img/voyager_cant_save_new_page.jpg)
This error does not occur when editing existing multilingual page, only when saving a new multilingual page.

### Steps To Reproduce:
Enable multilanguage.
Create new multilingual page (fill out the form).
Pres the "Save" button.

**Comment by luckosracerfish** [comment]
"An invalid form control with name='body' is not focusable." still is shown in latest master branch.

Also, why is meta description and keywords required? I would like to decide for myself about this stuff especially that keywords are not used much anymore.

**Comment by baciualexandru** [comment]
Try to change in BREAD, where you have Input body...change with something else like body_new. Hope it helps.

**Comment by def-media** [comment]
Thank you for your answer, but it seems like this problem is solved.
- Laravel Framework 5.5.28
- Voyager v1.0.13
- Linux Ubuntu 16.04
- Google Chrome Version 64.0.3282.119 (Official Build) (64-bit)

In this environment, I can't reproduce this problem.
Somewhere I read that it was a bug in the Google Chrome browser.
