### ISSUE TITLE
No code coverage driver is available

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2289]
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7.1.4
- PHPUnit : 6.4.4
- Xdebug : 2.5.5

Hey guys, 

As soon as I install voyager following these steps (https://voyager.readme.io/docs/installation) my code coverage doesn't work anymore. I basically thought my app was broken somewhere so I tried uninstalling everything that was not "by default" on Laravel but the issue is still there... unless I finally remove Voyager.

I'm working with Laradock (mongo, mysql, nginx and php-fpm), default configuration, trying to keep it as simple as possible to find out what is happening!

`docker://docker_workspace:latest/php -dxdebug.coverage_enable=1 /opt/project/vendor/phpunit/phpunit/phpunit --coverage-clover /opt/phpstorm-coverage/testproject$ExampleTest.coverage --configuration /opt/project/phpunit.xml Tests\Unit\ExampleTest /opt/project/tests/Unit/ExampleTest.php --teamcity
Testing started at 09:14 ...
PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

PHPUnit 6.4.4 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

Time: 3.03 seconds, Memory: 12.00MB

OK (1 test, 1 assertion)

Process finished with exit code 0`

This command used to work before I installed Voyager so guys, do u have any idea on how to fix it please? :)

Thx a lot,
Baptiste

Edit : this issue was confirmed by two fresh installs on two other mac

**Comment by fletch3555** [comment]
This occurs due to the phpunit configuration, not because Voyager is broken.  You can safely ignore it for now.  It occurs in our tests as well: https://travis-ci.org/the-control-group/voyager/jobs/308912110#L908

**Comment by ghost** [comment]
Yep, i could safely ignore this error.. if it wasn't blocking code coverage for every single file in my tests dir.

Basically, as long as Voyager is installed, I can't work anymore on that project. Do you have any idea when / how this is going to be fixed pls?

**Comment by ghost** [comment]
Up ?

**Comment by fletch3555** [comment]
Your app doesn't need to run Voyager's phpunit tests.  Just run your own.  We run ours and make sure it's all green before merging anything
