### ISSUE TITLE
Delete posts table breaks admin panel

### ISSUE THREAD

**Issue by EspieNL** [thedevdojo/voyager#2291]
- Laravel Version: 5.5.22
- Voyager Version: 1.0.7
- PHP Version: 7.1.7
- Database Driver & Version:

### Description:
Deleting post table will break the admin panel dashboard

### Steps To Reproduce:
- Go to tools -> database
- Delete posts bread and delete posts

Probably the dimmers are hardcoded and not checked for existence 
Deleting the page table will probably result in the same error

**Comment by fletch3555** [comment]
The dimmers are configured in `config/voyager.php`.  Just delete the reference there and you shouldn't have any further issues

**Comment by EspieNL** [comment]
Ok thanks for the update. 

Perhaps it would be nice to check in the dimmer for the existence of the model. If the user does something wrong the dashboard won't break.

**Comment by fletch3555** [comment]
Very low priority for us, but we're always open to PRs from the community
