### ISSUE TITLE
Accessing a bread-table creates 10x the row-count of queries

### ISSUE THREAD

**Issue by JapSeyz** [thedevdojo/voyager#2292]
I have 300 users in my users-table, when trying to access /users

It creates over 3000 queries, 2974 of which are duplicates.
The databtable should fetch new rows on demand, but it seems it loads every single one of them as soon as I try to access the page.

![screenshot from 2017-11-29 21 46 02](https://user-images.githubusercontent.com/2234034/33398442-41ca52ac-d54f-11e7-950c-1324ed2355ee.png)

**Comment by JapSeyz** [comment]
The query actually took about 2 minutes, not two seconds as Debugbar seems to think

**Comment by JapSeyz** [comment]
Even though I have translations turned off, it seems at least 80% of the calls is this single query, ofc with every key being different:

```sql
select * from `ltm_translations` where (`locale` = 'da' and `group` = 'voyager' and `key` = 'generic.bulk_delete') limit 1
```

**Comment by JapSeyz** [comment]
commenting out

```php
if (($isModelTranslatable = is_bread_translatable($model))) {
    $dataTypeContent->load('translations');
}
```

In the BreadController didn't help. I'm investigation further

**Comment by JapSeyz** [comment]
I managed to tune it down to only 4x the amount of row-count as queries.

The 1600 of the calls was Laravel Translation Manager, trying to reach the generic.error translation in the database instead of the fallback language. **Not Voyagers fault**.

![screenshot from 2017-11-29 22 09 48](https://user-images.githubusercontent.com/2234034/33399279-57370aba-d552-11e7-9772-3d5e8b813a48.png)

![screenshot from 2017-11-29 22 10 07](https://user-images.githubusercontent.com/2234034/33399286-5b658792-d552-11e7-83fd-3c93df0ca236.png)

![screenshot from 2017-11-29 22 09 40](https://user-images.githubusercontent.com/2234034/33399297-669bb4e2-d552-11e7-9f45-3946f558575b.png)

![screenshot from 2017-11-29 22 09 23](https://user-images.githubusercontent.com/2234034/33399308-71dba2a4-d552-11e7-92dc-7f7d2d5d866f.png)

**Comment by JapSeyz** [comment]
Still 1.1k queries that's not unique

**Comment by JapSeyz** [comment]
Albeit, not pretty, adding this in basePolicy takes it down to 330 queries:

```php
if (! isset(self::$datatypes[get_class($model)])) {
            $dataType = Voyager::model('DataType');
            self::$datatypes[get_class($model)] = $dataType->where('model_name', get_class($model))->first();
        }

        $dataType = self::$datatypes[get_class($model)];
```

Of course, remember to add ` protected static $datatypes = [];` to the top

**Comment by JapSeyz** [comment]
Adding this to `Role.php`

```php
public static function getRelationship(int $id)
    {
        if (! isset(self::$relationships[$id])) {
            self::$relationships[$id] = self::find($id);
        }

        return self::$relationships[$id];
    }
```

Takes it down to 36 queries

**Comment by JapSeyz** [comment]
It seems the worst wait is still having to wait for the Javascript to paginate all 300 rows of users, as the page is completely unresponsive for a good while when doing this. Why is it fetching all rows at once?

**Comment by JapSeyz** [comment]
Adding this to Role.php

```php
public static function getRelationship(int $id)
    {
        if (! isset(self::$relationships[$id])) {
            self::$relationships[$id] = self::find($id);
        }

        return self::$relationships[$id];
    }
```
and replacing

```php
$query = $model::find($relationshipData->{$options->column});
```
with

```php
$query = $model::getRelationship($relationshipData->{$options->column});
```

in formfields/relationship.blade.php

Takes it down to 36 queries

**Comment by JapSeyz** [comment]
It's still incredibly slow, as to just handling 300 rows, but that's because it's running 900 gate queries, and loading 1100 views.

I'm not sure why you opted for datatables if you're gonna load ALL the content in the database with every request anyways, I am guessing it's a bug?

**Comment by JapSeyz** [comment]
In `VoyagerAdminMiddleware`

Changing

```php
if (!Auth::guest()) {
    $user = Voyager::model('User')->find(Auth::id());

    return $user->hasPermission('browse_admin') ? $next($request) : redirect('/');
}
```

to

```php
if (!Auth::guest()) {
  auth()->user()->hasPermission('browse_admin') ? $next($request) : redirect('/');
}
```

Removes 3 additional duplicates

**Comment by JapSeyz** [comment]
Doing the same to MenuItemPolicy as the BasePolicy saves you a few extra queries. We're now at 32.

That's where I'll stop for now. We took it from 1218 down to 32.

**Comment by JapSeyz** [comment]
Ps. why do you check every single user for edit permissions. Voyager only comes builtin with the general "edit users" permission, not "edit this specific user". I know you support it, but that's a manual implementation.

**Comment by fletch3555** [comment]
Well... you've been busy....

Short answer: we know there are plenty of opportunities for fine tuning.  We're open to PRs for any changes (but request that you keep only related changes in each PR. so your BasePolicy change can be one PR, your VoyagerAdminMiddleware change can be one, etc).

**Comment by JapSeyz** [comment]
@fletch3555 I should get time to copy it into a PR during the weekend.

I wanted to keep it all in a single issue, but some of the things aren't directly related, thus making multiple comments as I found them, would hopefully help you guys understand what I did.

**Comment by JapSeyz** [comment]
The "load the entire database into the webpage and transform it into a datatable instead of doing ajax requests" approach, I am still not entirely sure of, as it kills the page for a solid few seconds, after all these changes, when you go about 200-300 records.

**Comment by fletch3555** [comment]
We currently provide 2 options for users.  Either you enable server-side pagination and you get "X" results per page (and a much faster page load), or you disable it and you get ALL data returned but can search them through datatables.  I agree it's far from perfect, but changing that is a considerable undertaking

**Comment by fletch3555** [comment]
@JapSeyz, would you care to open a PR with the optimizations you've suggested here?

**Comment by JapSeyz** [comment]
@fletch3555 Done: #2337
