### ISSUE TITLE
How to customize a dropdown in a BREAD

### ISSUE THREAD

**Issue by haantje91** [thedevdojo/voyager#2294]
- Laravel Version: 5.5.22
- Voyager Version: 1.0.7
- PHP Version: 7.1
- Database Driver & Version: SQL 5.7.19

### Description:
I have Posts and Categories models, which are related. 
In the 'add new' BREAD for Posts i have a dropdown. 

How can I make this dropdown show only categories with a certain id?

### Steps To Reproduce:
Make Posts model
Make Categories model
Make Posts belong to Category
Make Category has many Posts
Make BREAD for Posts include a dropdown to select according category

**Comment by BoChao-Hsu** [comment]
https://voyager.readme.io/v0.11/docs/relationships

You can refer to this.

**Comment by emptynick** [comment]
Closing due to age.
Please feel free to ask question in our Slack group.
