### ISSUE TITLE
/config/voyager.php not refreshed 

### ISSUE THREAD

**Issue by Nolween** [thedevdojo/voyager#2295]
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7.1.11 
- Database Driver & Version:

### Description:

Hi all, 

I just discovered this  awesome project, I'm absolutely stunned  by its comfort. Wow  !

I've seen all the tutorials i could, official or not, not to forget anything, but I got an issue.

All is well setup, except my config/voyager.php file. I tried to edit it to fit it in my project, by changing prefix, enabling multilingual and adding some languages, or changing primary_color. 
For example i changed admin to backend  prefix, but admin is still working and not backend.

But whatever I do, nothing changes when I reload. I also tried to run a php artisan config:clear command, but it's all the same. 

### Steps To Reproduce:

- Edit and save the config/voyager.php file and refresh the dashboard

Would be so kind to help me to find why :)

**Comment by emptynick** [comment]
Changing the admin prefix also requires you to edit your routes/web.php from
`Route::group(['prefix' => 'admin'], function () {`
to
`Route::group(['prefix' => 'backend'], function () {`
Multi-language is well described [here](https://github.com/the-control-group/voyager/pull/561)

**Comment by Nolween** [comment]
Ok, i'll change it tonight, but even without changing the prefix, just the other parameters, nothing changes.

I keep you informed about it, thank you :)

**Comment by Nolween** [comment]
As expected, after changing the route to backend. It works for it, but for the rest of the config/voyager.php, neither the translations, nor the primary color has changed :(

Here is a part of my config : 

```
    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'fr',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'fr',
            'en'
            //'pt',
        ],
    ],

    'primary_color' => '#C5D961',

    'show_dev_tips' => true, // Show development tip "How To Use:" in Menu and Settings

    // Here you can specify additional assets you would like to be included in the master.blade
    'additional_css' => [
        //'css/custom.css',
    ],

    'additional_js' => [
        //'js/custom.js',
    ],
```

**Comment by Nolween** [comment]
Tried to change widgets,  but nothing happens to change the language. So weird :(

**Comment by emptynick** [comment]
You mean the backend language?
If so, this is a laravel configuration.
Check your app/config.php and change `'locale' => 'en'` to your prefered language

**Comment by Nolween** [comment]
Oh... ok you're right, i confused.

Thank you so much for your help !

**Comment by reeslo** [comment]
Hi,
This is possible translate "Settings" ?

**Comment by fletch3555** [comment]
@reeslo, this issue has been closed for nearly 2 months and is unrelated to your question.  Please open your own issue or post in Slack instead of reviving old issues.

**Comment by muhammetakkus** [comment]
I have same issue now. I want to add/delete widget but when i change widgets key on config/voyager.php anything doesn't change. What is the problem i am so confused..
