### ISSUE TITLE
one question about bread

### ISSUE THREAD

**Issue by jouniikaheimo** [thedevdojo/voyager#2296]
- Laravel Version: 5.5
- Voyager Version: 1.0.6
- PHP Version: 7
- Database Driver & Version: 

### Description:

can i make bread where  browser list would only show status = 1 row

**Comment by rizalio** [comment]
Yes you can by overriding the BREAD browse views,,  and display only `status = 1` records.

**Comment by marktopper** [comment]
You can also just do a policy: https://webman.io/blog/post/using-policies-in-laravel-voyager
