### ISSUE TITLE
PHP 7.2 Strict Exception

### ISSUE THREAD

**Issue by itsjustk** [thedevdojo/voyager#2297]
- Laravel Version: 5.5.22
- Voyager Version: 1.0.7
- PHP Version: 7.2
- Database Driver & Version: Not sure

### Description:
Hi there! I guess I should have taken care before upgrading my server to PHP 7.2 but I didnt and upgraded anyway hehe! 

Now because of strict trait checking I get this error on any page: 

Illuminate\Database\Eloquent\Model and Illuminate\Database\Eloquent\Concerns\HasRelationships define the same property ($manyMethods) in the composition of App\User. However, the definition differs and is considered incompatible. Class was composed

I'll either downgrade the server, which would be a shame because 7.2 seems lightning fast, or have a mess with the core voyager code to temporarily get around this issue.

Just a heads up! 

Thanks :)

### Steps To Reproduce:
Use PHP 7.2

**Comment by itsjustk** [comment]
Looking closer at the error, its actually nothing to do with Voyager? I apologise on behalf of my cold addled brain! I'll leave it open just incase, but obviously please feel free to close it! *slaps wrist*

**Comment by fletch3555** [comment]
No worries, glad you caught it! Definitely seems to be a Laravel issue, not a Voyager one.  Might be worth posting in [laravel/internals](https://github.com/laravel/internals) or on larachat
