### ISSUE TITLE
Unhandled error with bad AWS S3 key/secret/region/bucket - infinite loading animation.

### ISSUE THREAD

**Issue by prdgymx** [thedevdojo/voyager#2298]
- Laravel Version: v5.5.22
- Voyager Version: 1.0.7
- PHP Version: 7.0.25
- Database Driver & Version: mysql  Ver 15.1 Distrib   ##5.5.56-MariaDB
- Additional package used: 
	- league/flysystem [1.0.41]
	- league/flysystem-aws-s3-v3 [1.0.18]

### Description:

When using the Flysystem driver for AWS S3 storage, if an invalid AWS key/secret pair is provided, the **admin/media** route will continually show the "LOADING YOUR MEDIA FILES" loading animation with no visible error unless viewed in console - which shows the routes **admin/media/files** and **admin/media/directories**  returning 500 errors with JSON data.

Full error response: https://gist.github.com/prdgymx/8dc95c80ea51c91cb8763e60256482ef

### Steps To Reproduce:

* Fresh install of Laravel 5.5 + Voyager (using dummy data)
* `composer require league/flysystem-aws-s3-v3`
* Update `.env` or `config/filesystems.php` with (bad) AWS S3 key/secret/bucket/region
* Update storage/disk from 'public' to 's3' in `config/voyager.php`
* Load the **/admin/media** route.

### Possible Fix From a Novice

For my own project I simply added a try/catch to the `getFiles()` function in `/src/Http/Controllers/VoyagerMediaController.php` & return an array with `status`, `files` and `message` keys.

The `files()` function does a check, then provides the JSON file list & 200 status or an error & 500, for the ajax error function to show a toastr popup.

There are probably many, more efficient ways to resolve this which is why I'm not submitting anything but my suggestions. Hope this helps and you can add it to the updates to the media manager planned.

**Comment by fletch3555** [comment]
I'm not sure this is even something we need to concern ourselves with.  I think it's fairly well understood that an invalid configuration will cause things to not function properly

**Comment by prdgymx** [comment]
+1

Understood and I don't disagree, it's on the PEBKAC end of things but looking at the functions in the controller and seeing try/catch error handling throughout, except on the getFiles() function made me think it may have just been an oversight.

**Comment by fletch3555** [comment]
That's entirely possible as well haha.

I'm open to PRs for this.

**Comment by marktopper** [comment]
Closing this since it is not really an issue but a misconfiguration.
However, we are open to a PR.
