### ISSUE TITLE
Uploading large images throws size too large exception

### ISSUE THREAD

**Issue by pseudoanime** [thedevdojo/voyager#2300]
- Laravel Version: 5.5.22
- Voyager Version: 1.07
- PHP Version: 7.1.9
- Database Driver & Version: mysql 5.7.13

### Description:
Uploading large files on cover images throws a PostTooLargeException

### Steps To Reproduce: 
Upload a large file

**Comment by emptynick** [comment]
This is not a Voyager problem.
All you have to do is to edit your php.ini's `post_max_size`
