### ISSUE TITLE
Bug with paths after installation

### ISSUE THREAD

**Issue by andriihorpenko** [thedevdojo/voyager#2305]
- Laravel Version: 5.4.22
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7
- OS: CentOS 7

Description: After installation there are huge problems. I am running a server on CentOS 7. And I've installed fresh Laravel and did this commands: php artisan make:auth and php artisan migrate. After I've created an account and installed your Voyager. When I enter _/admin_ I can see a page with no styles. Then I looked into the Source tab in Chrome. It showed me this path:
_/vendor/tcg/voyager/assets_
But when I enter this path - no assets folder. It is in publishable folder with another files, like scripts, etc. Also the default user picture(according to Source tab) has to be in _/storage/users/default.png_. But instead of this it is in _/storage/app/public/users/default.png_. WTF?

**Comment by emptynick** [comment]
Sounds like you didnt run
`php artisan voyager:install`
this publishes the assets and sets the proper storage link

**Comment by andriihorpenko** [comment]
Maybe you won't believe me, but I HAVE installed it. As a confirm: 
![image](https://user-images.githubusercontent.com/13716167/33528429-39ac7864-d871-11e7-983d-058d4719b474.png)

**Comment by andriihorpenko** [comment]
Oh ye, here is one more detail: if I do ALL of this on Windows 10, it works just fine!

**Comment by fletch3555** [comment]
~~What were you using the first time?~~ Nevermind, I see CentOS above.

This is almost 100% a misconfiguration in your setup if you're having these issues.  There is nothing about Voyager that is OS-dependent, so your 2 installs differ in some way.

**Comment by andriihorpenko** [comment]
Okey, I will install again on Windows and CentOS. Then I will post results, ok?

**Comment by andriihorpenko** [comment]
Well, as it was expected. Fresh Laravel install, added build-in auth and installed Voyager. No errors while installation, but also no correct styles. Try it by your self.

**Comment by andriihorpenko** [comment]
Old stuff, closing.
