### ISSUE TITLE
Cannot add BREAD to Voyager created table

### ISSUE THREAD

**Issue by sdevid** [thedevdojo/voyager#231]
- Laravel Version: 5.3.*
- Voyager Version: 0.9.33
- PHP Version: 5.6.16
- Database Driver & Version: MySQL (10.1.9)

### Description:
When i click to Add BREAD to this table I got the message: _Method [getNamespace] does not exist. (vendor\laravel\framework\src\Illuminate\Routing\Controller.php line 82)_
### Steps To Reproduce:
http://awesomescreenshot.com/0a066ydua5

**Comment by deep88** [comment]
same problem with me

**Comment by fletch3555** [comment]
This one was completely my fault! Sorry guys! Fixed through #237
