### ISSUE TITLE
Can we increase the backstage function of the mall?

### ISSUE THREAD

**Issue by boneasia** [thedevdojo/voyager#2311]
Can we increase the backstage function of the mall?
I hope that the author will increase this function, thank you!

**Comment by fletch3555** [comment]
Uhh... I'm sorry, I have no idea what you're asking for... Please clarify your request

**Comment by boneasia** [comment]
Shopping Mall Meuns and programs.

**Comment by fletch3555** [comment]
That doesn't help. Please try again. What are you asking for?

**Comment by boneasia** [comment]
I'm going to be the admin of the mall.
