### ISSUE TITLE
The selects of the "Create Relationship" modal are broken

### ISSUE THREAD

**Issue by hidalgofdz** [thedevdojo/voyager#2314]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.12
- Database Driver & Version: mysql

### Description:

The selects of the "Create Relationship" modal are broken

### Steps To Reproduce:

1. Enter to any "edit bread"
1. Select "Create relationship"
1. Click any select
1. The options are not displayed (or al displayed under the moda.

Screenshots: 

<img width="871" alt="screen shot 2017-12-06 at 22 56 12" src="https://user-images.githubusercontent.com/5541077/33699584-a322dd50-dad9-11e7-87c7-bc9e0c4b72cc.png">
<img width="837" alt="screen shot 2017-12-06 at 22 57 11" src="https://user-images.githubusercontent.com/5541077/33699585-a335b204-dad9-11e7-8a6a-e2f7c10d28dd.png">
<img width="720" alt="screen shot 2017-12-06 at 22 57 20" src="https://user-images.githubusercontent.com/5541077/33699586-a346b720-dad9-11e7-80b7-2f5cb055d564.png">

**Comment by emptynick** [comment]
The Select2 is a bit buggy.
There were a lot fixes, and now we have a lot CSS rules, but I think that makes it worse.
I will submit an emergency fix in an hour or so.
But in the end this needs a whole rewrite on the CSS side

**Comment by emptynick** [comment]
The PR causing this is #2076
As this PR is not a bugfix, I think its safe to revert it.
@fletch3555 any thoughts?

**Comment by fletch3555** [comment]
@emptynick, [reverted in master](https://github.com/the-control-group/voyager/commit/e93ddc877d4b6bd55e46701280a562e474cd96ad), please do a `git pull` on master and try to reproduce it.
