### ISSUE TITLE
Relationship drop downs are not listing anything

### ISSUE THREAD

**Issue by d0773d** [thedevdojo/voyager#2315]
- Laravel Version: 5.5
- Voyager Version: 1.0 Beta
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.7.20

### Description:
Relationship issues. None of the drop-downs on the Relationship window are listing anything. I uploaded a demo to youtube to better explain what exactly is going on. Video can be found [here:](https://youtu.be/_As9xRYO9s4)

**Comment by emptynick** [comment]
See #2314
