### ISSUE TITLE
Help required with a module.

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2316]
- Laravel Version: 5.5
- Voyager Version: Dev-master
- PHP Version: 7.1.9

### Description:

I want to make a module in voyager but don't know how can I do that. Please guide me on this one.
So I want to make a functionality, which will allow a user to submit one post. User should be able to add/edit/update that post. And admin should approve it to publish. Is it possible to make this thing from voyager dashboard ? What should I do to make this thing.

**Comment by fletch3555** [comment]
We strongly recommend you start here: https://laravelvoyager.com/academy/

Once familiar with Voyager and it's capabilities, you just need to realize that, at it's core, it's just Laravel, so you can do anything you want.  After coming to this realization, make an attempt at building what you need.  Then join our Slack group and we'll be happy to answer any specific questions you may have.
