### ISSUE TITLE
Improving support for special chars

### ISSUE THREAD

**Issue by xotik** [thedevdojo/voyager#2317]
Hello everyone,

Today I stumbled against the following (I'm not using version 1.0 yet, it might have changed by now):

In the browse.blade.php view of BREAD, when the field is of type 'text' or 'textarea', text gets trimmed if larger than 200 chars, right?

Then I started seeing some fields, not all, appearing blank in the table. After some debugging, I found out that when the max char in strlen() is a special char, substr() can't handle it very nice.

Luckily, there's an easy fix: just use mb_substr() instead.

Is it a good idea to update all Voyager code to use mb_substr() instead of substr()? I´ll leave it up to you :)

Cheers!

**Comment by emptynick** [comment]
I see your point.
`strlen` does not count chars, but bytes.
Definitely worth considering!

**Comment by xotik** [comment]
Glad I could help!

**Comment by fletch3555** [comment]
Open to pull requests.
