### ISSUE TITLE
Server side pagination not working.

### ISSUE THREAD

**Issue by dazzcreations** [thedevdojo/voyager#2319]
- Laravel Version: 5.5.24
- Voyager Version: 1.0.9
- PHP Version: 7.0.26
- Database Driver & Version: MySQL
Server version: 5.6.23-cll-lve - MySQL Community Server 

I have created a bread and checked Server pagination as an option. Now while browsing the records if I search no result comes up but the URL changes same is the case with ordering the results.

**Comment by emptynick** [comment]
Can you please post  the search URL + an element which should match the Query?

**Comment by dazzcreations** [comment]
Search URL
admin/states?sort_order=asc&order_by=state_name
What do you mean by the element here?

**Comment by emptynick** [comment]
Ah, so when you try to sort the results, there are none?
Also no Exception?

**Comment by dazzcreations** [comment]
The results are there without any change. For example if the default dataset is a,b,c,d. then even after sorting them in descending order they remain a,b,c,d

Also if I try to use search to search the result with the following url
admin/states?key=state_name&filter=contains&s=Avignon
The data remain unchanged.

**Comment by dazzcreations** [comment]
Any update?

**Comment by emptynick** [comment]
Its not reproducible for me.
There was a PR lately #2246 which actually should fix those problems.

**Comment by emptynick** [comment]
I think this was fixed by #2246
