### ISSUE TITLE
Editor problem ! When i write some php codes into post body fronted and backend crashed

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#2322]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version:
- Database Driver & Version:

### Description:

for example when i post 
`<?php
$a = date("d.m.Y"); /* Tarixi formalaşdırır */
$url = 'https://www.cbar.az/currencies/' .$a. '.xml'; /* Linki yaradır */
$xml = simplexml_load_file($url); /* Verilmiş linkdəki xml-dən məlumatları parsinq edir */
if ($xml !== FALSE) {
$Rate = $xml->ValType[1]->Valute[44]->Value;
$Rate2 = $xml->ValType[1]->Valute[38]->Value;
$Rate3 = $xml->ValType[1]->Valute[4]->Value;
/* Əgər yeni məlumat yoxdursa heçnə dəyişilmir. Yeni məlumat varsa ABŞ dolları, Evro və Rus rublunun məzənnəsini götürərək Rate, Rate2, Rate3-ə mənimsədir */
$d=$Rate;
$e=$Rate2;
$r=$Rate3;
$v="<b>AZN məzənnəsi:</b> </br>";
print ($v);
print($xml->attributes()->Date); /* Linkdən tarixi götürüb çap edir */
print "</br>tarixdən etibarən</br>";
print "1 USD &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$d</br>";
print "1 EUR &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$e</br>";
print "1 RUB &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$r";
}
?>`
this texts get some errors front and backend... this exchange code display live currency in websites...
but i cannot share this post .please fix it or help

**Comment by nicat-eliyev** [comment]
`<?php
$a = date("d.m.Y"); /* Tarixi formalaşdırır */
$url = 'https://www.cbar.az/currencies/' .$a. '.xml'; /* Linki yaradır */
$xml = simplexml_load_file($url); /* Verilmiş linkdəki xml-dən məlumatları parsinq edir */
if ($xml !== FALSE) {
$Rate = $xml->ValType[1]->Valute[44]->Value;
$Rate2 = $xml->ValType[1]->Valute[38]->Value;
$Rate3 = $xml->ValType[1]->Valute[4]->Value;
/* Əgər yeni məlumat yoxdursa heçnə dəyişilmir. Yeni məlumat varsa ABŞ dolları, Evro və Rus rublunun məzənnəsini götürərək Rate, Rate2, Rate3-ə mənimsədir */
$d=$Rate;
$e=$Rate2;
$r=$Rate3;
$v="<b>AZN məzənnəsi:</b> </br>";
print ($v);
print($xml->attributes()->Date); /* Linkdən tarixi götürüb çap edir */
print "</br>tarixdən etibarən</br>";
print "1 USD &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$d</br>";
print "1 EUR &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$e</br>";
print "1 RUB &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
print "$r";
}
?>`

**Comment by nicat-eliyev** [comment]
when i back to edit this post from admin panel first "<?php" tag do not showing or removed or something.

**Comment by fletch3555** [comment]
You definitely shouldn't be saving php code to the Post body field... Best-case scenario, it would get treated as plain text, stored in the database, and rendered verbatim when viewing the page in your front-end.  Worst-case scenario, Voyager `eval`'s the code and it's a HUGE security vulnerability.

With that said, I have no idea what you're trying to do, but I can confidently say this isn't the right way to do it.

**Comment by nicat-eliyev** [comment]
another problem too... when display post {{!! str_limit($post->body) !!}} fronted page css  crashed .! Why ? 
alternativli $post->expcerpt is good but it is a problem i think
str_limit() function confilict with voyager

**Comment by emptynick** [comment]
If you use str_limit for example on
`<p>Your awesome content</p>`
And limit it to X chars, it will maybe just remove the last `</p>`.
So of course it will break your layout.
But thats definitely not a Voyager problem.

**Comment by calder12** [comment]
Your first problem is trying to write PHP functionality into a post rather than handling that on the front end where you should be, or in the Controller for displaying posts.

Your second problem is exactly what @emptynick said. str_limit is just cutting off the post wherever you tell it, it has no idea about tags or elements so you are almost for sure going to have broken elements which in turn break the rest of your layout.

There are two solutions, first is to actually use the Excerpt functionality, because that is exactly why it exists. The second is to strip the tags from the body when using str_limit  {{!! str_limit(strip_tags($post->body)) !!}} which means you'll just get the text and won't have the broken tag issue.

Neither of these are Voyager issues.

**Comment by nicat-eliyev** [comment]
calder12 perfect reply! thanks.
