### ISSUE TITLE
Multiple user - sidebar

### ISSUE THREAD

**Issue by azkaafiq** [thedevdojo/voyager#2324]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql 5.7

### Description:
How can i make other user's can use the button on the sidebar?

### Steps To Reproduce:
When i load the user page, all the link on the side bar can route to their path.
<img width="1279" alt="screen shot 2017-12-10 at 1 44 14 am" src="https://user-images.githubusercontent.com/32008595/33798012-62323f3c-dd4c-11e7-961c-5ae7ed12f0d6.png">

**Comment by fletch3555** [comment]
I'm not sure I understand the question.  Are you saying you have menu items that you expect to show up but don't see them?

**Comment by azkaafiq** [comment]
My bad, sorry. Yes, when i login into normal user there is no appeared when i click it

**Comment by calder12** [comment]
Permissions. This is the point of the multiple roles, some will only have access to certain things.

Log into your Admin account and click Roles.
Click Edit on the User role.

Here you can add/remove permissions for each role. Note that you have to give View permission on something you want them to have access to. For example giving edit permissions on Posts will only allow them direct access to a post edit screen, they won't see the list to select a post without View.

Hope that makes sense.
