### ISSUE TITLE
Need help . How to display Posts via the Category

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#2325]
- Laravel Version: v5.5.22
- Voyager Version: v1.0.7
- PHP Version: native(5.6)
- Database Driver & Version: 5.6.38 - MySQL Community Server (GPL)

### Description:
Please anyone can help me ? How to display Posts via the Category within Voyager? I cannot find correct source

**Comment by fletch3555** [comment]
Display where?  In your site, or within Voyager?

Also, all version fields are required when submitting issues.  They help us identify whether your problem is related to a specific version and whether updating will solve it.  "latest" is NOT a version number.  If you have questions that you don't believe should require some or all of these fields, then odds are your question is better asked on our Slack chat instead.

**Comment by nicat-eliyev** [comment]
Hi fletch3555 i updated post versions .need within Voyager. I m using Voyager admin panel.

my current routes/web.php

Route::get('/', function () {
	$posts = App\Post::all();
	$pages = App\Page::all();
    return view('start',compact('posts','pages'));
});
Route::get('/blog', function () {
	$posts = App\Post::paginate(10);
	$pages = App\Page::all();
	$categories = App\Category::all();
    return view('blog',compact('posts','pages','categories'));
});
Route::get('post/{slug}', function($slug){
	$post = App\Post::where('slug', '=', $slug)->firstOrFail();
	$pages = App\Page::all();
	return view('post', compact('post','pages'));
});
Route::get('page/{slug}', function($slug){
	$page = App\Page::where('slug', '=', $slug)->firstOrFail();
	$pages = App\Page::all();
	return view('page', compact('page','pages'));
});

**Comment by fletch3555** [comment]
So the answer to my question is your site.  That's completely up to you, and is basic Laravel functionality.  Voyager is only a means of populating your database.  When you build your site, you pull data out and make use of it however you please.  We try to make Voyager as unopinionated as possible with respect to how you use the content it helps you create.

For further implementation questions, I suggest joining our Slack group and posting there.  There may be a delay in response at certain times of the day, but there are numerous knowledgeable devs that will be more than happy to assist you.
