### ISSUE TITLE
BREAD Post Form not submitted

### ISSUE THREAD

**Issue by rizalio** [thedevdojo/voyager#2326]
- Laravel Version: Laravel Framework 5.5.22
- Voyager Version: 1.0
- PHP Version: 7.1.12
- Database Driver & Version: MySQL & 5.7.20-log

### Description:

I'm creating a `product bread` that have a relation to `brand` & `category` table, It's working perfectly until I changed the `product images` data type to `multiple images` and it's resulted form not submitted after pressing the Save Button.

And it's show on the browser console:

![console](https://user-images.githubusercontent.com/22221916/33800150-5314fef6-dd6d-11e7-85bf-750d61032ffc.png)

**Comment by rizalio** [comment]
Solved by removing `validation` json from BREAD? is this a bugs??

**Comment by fletch3555** [comment]
If you think it's a bug, why would you close the issue? Finding a workaround does not mean you found a solution.

**Comment by rizalio** [comment]
I have no idea why the `validation` JSON causing the error, but it's documented that mean has been tested by contributor,, so I closing the issue because this is not clear.

**Comment by emptynick** [comment]
#2191 and #2198 fix this problem.
