### ISSUE TITLE
Markdown editor inner layout

### ISSUE THREAD

**Issue by vtmx** [thedevdojo/voyager#2328]
- Laravel Version: 5.5.0
- Voyager Version: 1.0.0
- PHP Version: 7.1

### Description:
Markdown inner layout in side by side or fullscreen:

![Screenshot](https://user-images.githubusercontent.com/8462885/33802107-cc6ea462-dd56-11e7-8b94-b09d09cfebb2.PNG)

**Comment by fletch3555** [comment]
Are you actually on v1.0.0, or have you updated since then? v1.0.9 is our most current release.

Do you have any errors in your browser console? This looks like a CSS error or something, and isn't something anyone else has reported, so it's very likely something specific to your install.

**Comment by ivanryndyuk** [comment]
￼Hi there! I have the similar problem you can see it in image below. Long text is out of table layout with rich text box. I don't know if I should open another issue. But I suppose the reason could be the same.

Voyager v1.0.9

<img width="1269" alt="screen shot 2017-12-10 at 10 14 57 am" src="https://user-images.githubusercontent.com/13752737/33802912-e3a0e0d6-dd93-11e7-975e-019c6694744c.png">

**Comment by vtmx** [comment]
Where I can see version of my Voyager?

**Comment by fletch3555** [comment]
@vtmx It's on the dashboard page.  Can't remember offhand if it's at the bottom of the left menu or the bottom-right corner in the footer.

**Comment by unikapps** [comment]
@vtmx you can get package details with `composer show tcg/voyager`
