### ISSUE TITLE
Custom fields not backed by DB column in BREAD

### ISSUE THREAD

**Issue by atrauzzi** [thedevdojo/voyager#2329]
Does the BREAD back-end generator allow for custom fields/inputs that aren't backed by a database column, but are handled separately in the controller?  Say for example, I have a model that I want to also include a file upload for, but I don't want to save the binary data to a blob in my DB, I want to send it to storage by doing a little custom handling...

**Comment by fletch3555** [comment]
Voyager doesn't save blobs to the database.  It uploads files to the server filesystem and stores the path in the database.

But to answer your question more directly, no, Voyager does not currently support custom non-database-backed fields.

**Comment by atrauzzi** [comment]
Thanks!
