### ISSUE TITLE
Adding Voyager to existing project

### ISSUE THREAD

**Issue by rahimlis** [thedevdojo/voyager#2334]
- Laravel Version: 5.5
- Voyager Version: ^1.0
- PHP Version: 7.0.0
- Database Driver & Version:

### Description:
The main problem is that  post/category/ tables that are included into library should be allowed to be disabled. I don't need them in the project and it causes a trouble when adding to existing project. 
### Steps To Reproduce:
 I have an existing project and table with name categories. When i do `php artisan voyager:install` it stops with error (the table categories already exists) . I know that with changing the name of migration we can solve the problem, but if we follow the simplicity and clearness of Laravel, you should also make it adjustable.

**Comment by chadidi** [comment]
#1863

**Comment by rahimlis** [comment]
@chadidi Yes I saw that issue, however if they change that from core that would be awesome. The admin panel is really perfect and makes Laravel even more amazing. Let's see if we can get results

**Comment by fletch3555** [comment]
https://github.com/the-control-group/voyager/issues/1863#issuecomment-350759467
