### ISSUE TITLE
How can I add custom controller and templates?

### ISSUE THREAD

**Issue by EmelyanovMax** [thedevdojo/voyager#2335]
- Laravel Version: 5.4
- Voyager Version: 1.0.9
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
How can I add custom controller and templates? I installed Voyager to existing project. I tried to use documentation, but I have an error like “class MyController does not exist”.

**Comment by fletch3555** [comment]
What did you try?

**Comment by EmelyanovMax** [comment]
I used this one https://voyager.readme.io/docs/using-custom-http-controllers
But I have no changes

**Comment by fletch3555** [comment]
Try this.  Change the controller to non-sense characters.  If it doesn't break, php doesn't know about your new class yet. Run`composer du`.

Once you get it to break with non-sense characters, change it to your new controller and try again.  If it still breaks with the same error, then run the composer command again.  If it starts working, great.  If it's a different error, then you'll have to start debugging that instead, but it won't be a Voyager problem at that point.

**Comment by EmelyanovMax** [comment]
Thanks a lot for answer. I reinstall package and it works fine. It seems an error occurred during installation
