### ISSUE TITLE
'Prefix' setting in Voyager config will never work?

### ISSUE THREAD

**Issue by xotik** [thedevdojo/voyager#2338]
- Laravel Version: Latest
- Voyager Version: Latest

### Description:
Hey everyone,

On a fresh Voyager installation, if I go to /config/voyager.php I can change my prefix from the default 'admin' to something else, but then if I look inside /routes/web.php 'admin' is hard coded as the prefix, so it doesn't matter what I put in the config because it will never work right? Or am I missing something?

### My own fix:

In /routes/web.php, instead of:

`Route::group(['prefix' => 'admin'], function () {`

put this:

`Route::group(['prefix' => config('voyager.prefix','admin')], function () {`

**Comment by emptynick** [comment]
See #2306

**Comment by xotik** [comment]
Ah yes, it's a big issue if upgrading, totally agree.

Maybe this helps someone stuck in the future :)

Close this if you wish @emptynick , and thanks for the information.
