### ISSUE TITLE
Slugify allows non URL characters.

### ISSUE THREAD

**Issue by calder12** [thedevdojo/voyager#2347]
- Laravel Version: 5.5.25
- Voyager Version: 1.0.9
- PHP Version:7.1

### Description:
When entering a title in a post or page, the slugify function allows non URL characters. Things like ' or ! which can break the URL. Trying to add the "remove" option in the BREAD for the post creates invalid JSON error and won't save.

This is sort of a big deal, I don't want to have to override all the CRUD pages and I don't want users to have to create their own slugs manually.

### Steps To Reproduce:
Create a post, type isn't! into the title.

**Comment by handiwijoyo** [comment]
I will try to look into this

**Comment by emptynick** [comment]
Fixed in #2830
