### ISSUE TITLE
App.js Errors when edit in the sub-directory.

### ISSUE THREAD

**Issue by spencerchang** [thedevdojo/voyager#2349]
- Laravel Version: 5.4.30
- Voyager Version: 1.0.9
- PHP Version: 5.6.30
- Database Driver & Version: Mysql 5.6.35

### Description:
I tried serveral times to put laravel-voyager to sub-directory like:
http://localhost/laravel_5.4_voyager
and always got some path errors from Chrome Console.

----------------------error here-------------------------
http://localhost/storage/users/default.png 404 (Not Found)
http://localhost/public/vendor/tcg/voyager/assets/images/bg.jpg 404 (Not Found)

Three times some errors as below. Look like come from app.js.
http://localhost/admin/database/categories 404 (Not Found) 
http://localhost/admin/database/categories 404 (Not Found)
http://localhost/admin/database/categories 404 (Not Found)
----------------------error here-------------------------

I set up the laravel rewrite to public/index.php.
And i also try editing filesystem.php the disk array ->public->url but can't solve.

The users/default.png error is easy to solve.
But other 4 errors are hard to debug.
I have no idea for this problem.

### Steps To Reproduce:
1. Create a laravel_5.4_voyager folder and composer install laravel and voyager.
2. Set up laravel_5.4_voyager rewrite to their public folder.
3. Follow the GETTING STARTED and use the dummy data.
4. Change 'assets_path' from '/vendor/tcg/voyager/assets', to '/public/vendor/tcg/voyager/assets'.
5. Enter database editing BREAD posts from dummy data. Just like below url.
http://localhost/laravel_5.4_voyager/admin/database/posts/bread/edit
6. Get errors.

**Comment by MrCrayon** [comment]
I'm closing this issue since it reference a very old Voyager version and similar questions have been asked many times.

If you are still encontering this issue please update and then you can ask in Voyager SLack group.
