### ISSUE TITLE
how to use Font Icon class for the Menu Item

### ISSUE THREAD

**Issue by jorge3dves** [thedevdojo/voyager#2351]
- Laravel Version: 5.5.#
- Voyager Version: 1.0.9
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
Hi, a have a small question.
How do I use the voyager Font Icon class that I set in the menu builder in my code?
I mean, to put this image instead of the text?
Thank you

**Comment by fletch3555** [comment]
The fonts are defined [here](https://github.com/the-control-group/voyager/tree/1.0/publishable/assets/fonts) and exist as CSS classes [here](https://github.com/the-control-group/voyager/blob/1.0/resources/assets/sass/fonts.css).  You need to have these included in your site's CSS
