### ISSUE TITLE
rename users table to admin_users

### ISSUE THREAD

**Issue by ooooak** [thedevdojo/voyager#2354]
- Laravel Version: 5.4.36
- Voyager Version: ^1.0
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:

I am using Voyager as a backend for web service. I want admin users in `admin_users` table, for our primary users, I want to use `users` . 

I am installing Voyager with dummy data. I have updated seeds, migrations and `App\Users`  to use `admin_users` table.  but it's not working properly. 

The only way it works when I add  `protected $table =  'admin_users';` to `TCG\Voyager\Models\User`. 

is there any better way to extend `TCG\Voyager\Models\User` model to use `admin_users` table.

Error:

I get this error when I access `admin/database` or `admin/media`
![Error](https://i.imgur.com/AZy5Nms.png)

`AppServiceProvider.php`

    use TCG\Voyager\Facades\Voyager;

    class AppServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            Voyager::useModel('User', \App\User::class);
        }
    }

`User.php`

    namespace App;

    use Illuminate\Notifications\Notifiable;
    use Illuminate\Foundation\Auth\User as Authenticatable;

    class User extends \TCG\Voyager\Models\User
    {
        use Notifiable;
        protected $table = 'admin_users';
    }

**Comment by fletch3555** [comment]
That.. ***should*** work... Can you share the entire stacktrace?

**Comment by ooooak** [comment]
stacktrace (html): https://gist.github.com/ooooak/c5a154c9b03cf2783ba9f2944dd73e71

in `\tcg\voyager\src\Voyager.php`  at 321 `$this->users` is empty. after that `TCG\Voyager\Models\User::find($id)` is called. any time TCG's User model is called (even in seeds) it gives me error.

**Comment by fletch3555** [comment]
Ah okay, I see.  The issue is the direct usage of Voyager's model class, which means it won't use the `$table` override you did.

Fix in #2362
