### ISSUE TITLE
Upload path issue

### ISSUE THREAD

**Issue by Mat-Moo** [thedevdojo/voyager#2356]
- Laravel Version: 5.4
- Voyager Version: 1.0.9
- PHP Version: 5.6.19
- Database Driver & Version: MySql

### Description:
Uploads are going into the root folder unless they are an image type

### Steps To Reproduce:
Upload any file (non image, e.g. pdf) in a subfolder - file ends up in root.

### Fix?
VoyagerMediaController.php - line 201, add the upload_path in:
`               $file = $request->file->move($realPath . $request->upload_path, $request->file->getClientOriginalName());`

**Comment by fletch3555** [comment]
You likely have a misconfiguration somewhere... The `move()` call isn't the correct solution.

What do your filesystem and voyager config files look like?

**Comment by Mat-Moo** [comment]
move(... is currently there, all I've added in is the upload_path which IMO is missing/bug.

**Comment by fletch3555** [comment]
Still not convinced that's the correct solution, but there definitely seems to be a bug there.  I don't understand why we have different logic for imaged vs files.  At the very least, I think the call to `store()` ([ref](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/VoyagerMediaController.php#L190)) should be pulled out above the `if`, and the `else` and `move()` can be deleted.

Would you like to make these changes and test it? We'd love a PR to fix this if you have the time.

**Comment by phillipesouza** [comment]
Hi doing guys, I have a similar problem, but in my case, in a fresh instalation of voyager, any file or image uploaded via media manager, or even the images loaded by the dummy data, were all not found, they are there, in the plublic storage folder, but the voyger can't open or render them. What can I do?

**Comment by fletch3555** [comment]
@phillipesouza, that's a different issue.  Please either open your own issue or ask for help on Slack.

**Comment by phillipesouza** [comment]
Thanks!

**Comment by Mat-Moo** [comment]
@fletch3555 Happy to look at a PR, time is a bit poor at the moment as I've been all consumed with Christmas lights :) https://141.rocks ! :) Donations welcome, lol
In terms of code, there is some additional manipulations on the image to fix orientation, so I think it's stored temp, adjusted and moved, hence why the two branches. Although why it should check for GIF then ignore gif is not as logical...

**Comment by BlakeBeus** [comment]
@fletch3555 I took a quick stab at this one.  Seems to work great.  Let me know if I should make any adjustments.

**Comment by emptynick** [comment]
Closing as #2524 was merged.
