### ISSUE TITLE
the nested menu bug

### ISSUE THREAD

**Issue by tanerincode** [thedevdojo/voyager#2357]
- Laravel Version: 5.5.6
- Voyager Version: 1.0
- PHP Version: 7.1

### Description:
hi, In the nested menu, we have a menu error when we create a dropdown menu. watch the video

### Steps To Reproduce:
https://www.useloom.com/share/fdecf7a5bb5246479bf1cb39efd1e858

**Comment by fletch3555** [comment]
Voyager's menu currently only supports one level of nesting.  You're welcome to fix the JS and submit a PR.  We'd really appreciate that.

**Comment by tanerincode** [comment]
I will let you know when I make the corrections.
