### ISSUE TITLE
can change url redirect to same url edit page instead index page

### ISSUE THREAD

**Issue by silasakk** [thedevdojo/voyager#2358]
can change url redirect to same url edit page instead index page

**Comment by fletch3555** [comment]
All [template fields](https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE) are required when submitting issues.  Please update your issue and we'll reopen this for review.

Also, please expand on your question.  You provide no detail at all, which makes it exceptionally difficult to know what issue you're trying to solve.
