### ISSUE TITLE
Filesystem not showing images

### ISSUE THREAD

**Issue by phillipesouza** [thedevdojo/voyager#2359]
- Laravel Version: 5.5.2
- Voyager Version: 1.0
- PHP Version:7
- Database Driver & Version:mysql

### Description:

Hi  doing guys, I have a problem with the file system, in a fresh  installation of voyager, any file or image uploaded via media manager, or  even the images loaded by the dummy data, were all not found, they are  there, in the public storage folder, but the voyager can't open or  render them. What can I do?

### Steps To Reproduce:

Just install the voyager following the docs.

**Comment by fletch3555** [comment]
Please provide a URL to the page where the broken image appears, and a URL to the broken image itself (accessible through your browser's dev tools).  Please feel free to use "example.com" or some other anonymous domain for privacy if you need to, however, please don't change anything else about the URL (protocol(http vs https), port, or path).

**Comment by phillipesouza** [comment]
through the media manager it appears in: media library >> users >> December2017 >> image.jpg;
Phisically the image is in: voyager base folder: public/storage/users/December2017/image.jpg;
but when I click at the link to see the image or via devtools, then comes this link: http://127.0.0.1/storage/users/December2017/DolHXnKnWTtGos4eyj01b8D08zZCNyRe5SH1NqlN.jpeg

And this happen with the dummy images too. They are not visible with the system running

Obs: I notice that any image uploaded the voyager changes it name to some hash and if it is jpg it changes to jpeg instead

**Comment by phillipesouza** [comment]
Right out of the box it comes like this:

![captura de tela de 2017-12-13 18-26-43](https://user-images.githubusercontent.com/512946/33963295-409ec068-e033-11e7-9f3b-0aa5210e128f.png)
![captura de tela de 2017-12-13 18-26-47](https://user-images.githubusercontent.com/512946/33963297-40e17ed0-e033-11e7-9430-91d850b0e9ed.png)

**Comment by fletch3555** [comment]
Okay, a few things.

First, your APP_URL isn't set correctly (needs the port number added).  That's why your images aren't working correctly.  We have an open issue to change them to domain-agnostic absolute URLs (i.e. `/path/to/image.jpg`), but I don't think anyone has picked it up yet.

Second, yes your observation is correct, Voyager does hash the image names to avoid collisions.  Not really sure why jpg -> jpeg though.

**Comment by phillipesouza** [comment]
Many Thanks!

Searching for the jpeg -> jpg
