### ISSUE TITLE
Relationship Modal - Options box low z-index

### ISSUE THREAD

**Issue by vinescarlan** [thedevdojo/voyager#2360]
- Laravel Version: 5.5.23
- Voyager Version: 1.0.8
- PHP Version: 7.1.11
- Database Driver & Version: 10.1.28-MariaDB Apache/2.4.29 (Win32) OpenSSL/1.0.2

### Description:

When opening the Relationship Modal by adding a new relationship, `.modal-open .select2-container` has a `z-index` of `auto` which makes it hidden or behind the back the modal itself. Can be fixed by adding a higher integer for its `z-index`

### Steps To Reproduce:

![1](https://user-images.githubusercontent.com/12904459/33968201-d1714cb4-e0a1-11e7-8323-2b2936980c80.png)

Click on the **Has One** dropdown, the options box will not show.

![2](https://user-images.githubusercontent.com/12904459/33968307-46dcab60-e0a2-11e7-9a6c-6bd69546bbc7.png)

Change the value of `z-index` property.

**Comment by fletch3555** [comment]
Please update to `v1.0.9`.  There was a bad CSS change that got into `v1.0.8`, and has since been reverted.
