### ISSUE TITLE
Can't edit if primary column of the table is not called id

### ISSUE THREAD

**Issue by Nolween** [thedevdojo/voyager#2361]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:
Hi everyone,

I've decided to rename primary column of my tables according to a certain way. For exemple, if my table is called products, my primary column, which is called id usually, will be renamed pro_ID. 
Unfortunately, on the products list, when I want to edit one of the existing poducts, the id is not found. The href is wrong : admin/products//edit  >>> id number is not found.

Are we stucked with this column name? 

### Steps To Reproduce:

- Create a new table with a primary key different name  from id >> ex : pro_ID
- Go to the product list and try to edit, or just see the href edit link.

Thank You !

**Comment by fletch3555** [comment]
Did you set `$primaryKey = 'pro_ID';` on your model?  See 'Primary Keys' under https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions

**Comment by Nolween** [comment]
Ok, that was the problem, I hadn't modified the  Model as expected. Thank you and sorry, i'm beginner with Laravel :)
