### ISSUE TITLE
Duplicate key name error when updating a table with unique columns

### ISSUE THREAD

**Issue by grzeee** [thedevdojo/voyager#2363]
- Laravel Version: 5.5.2
- Voyager Version: 1.0.9
- PHP Version: 7.1
- Database Driver & Version: mysql

### Description:
I have tried to update post or pages which have unique slug in database, i using the rule in bread:
`{
    "slugify": {
        "origin": "title",
        "forceUpdate": true
    },
    "validation": {
        "rule": "unique:pages,slug"
    }
}`
and i can't save the editing post becouse have error with Duplicate slug but it is the same slug and no other rows with this slug.

### Steps To Reproduce:
1. add the   "validation": {
        "rule": "unique:pages,slug"
    } 
to the pages option
2. edit any page like contact and during i have tried save, the form show error with duplicate slug

**Comment by grzeee** [comment]
Someone can check this issue, please ?

**Comment by emptynick** [comment]
Sorry for answering so late.
I can not confirm what you describe.
Maybe this was also fixed in #2660 ?
If this is not fixed for you please open a new issue!
