### ISSUE TITLE
Hooks not working

### ISSUE THREAD

**Issue by phillipesouza** [thedevdojo/voyager#2364]
- Laravel Version: lastest
- Voyager Version: lastest
- PHP Version: 7
- Database Driver & Version: Mysql

### Description:
The Hooks link in the menu doesn't appear, into the menu builder it is there, but not in the actual menu, and I cannot access the hooks or exist other way to access them?  

### Steps To Reproduce:
Just fresh install of voyager

note: I dit add provider for larapack hooks and larapack voyager hook, and nothing changed.

**Comment by fletch3555** [comment]
This is a problem with the voyager-hooks package, not with voyager itself.  It's been reported a few times previously: https://github.com/the-control-group/voyager/issues/2251

**Comment by handiwijoyo** [comment]
@phillipesouza I added a PR #2402 for quick fix for this
