### ISSUE TITLE
ASK [what's mean order in posts table]

### ISSUE THREAD

**Issue by mlazuardy** [thedevdojo/voyager#2368]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:

my question has been describe at title

**Comment by fletch3555** [comment]
It's just a field.  You can use it however you'd like, or delete it.  My guess is it was added there for drag-and-drop ordering of posts somewhere

**Comment by mlazuardy** [comment]
sorry for late reply, Thank you for your information sir @fletch3555
