### ISSUE TITLE
Laravel Timezone Ignored by BREADs

### ISSUE THREAD

**Issue by dattz** [thedevdojo/voyager#2369]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.7
- PHP Version: 7.0.22
- Database Driver & Version: MySQL 5.7.20

### Description:
Bread's timestamp fields are converted to GMT even when laravel's timezone is set to something else.

### Steps To Reproduce:
1. Change Laravel Timezone from GMT to anything else (config/app.php)
2. Create a new BREAD with a timestamp field.
3. Add an entry to that bread. Note the value of the timestamp field you add.
4. The date is converted to GMT and stored in the database ignoring the Laravel's timezone settings.

### Possible Cause:
As also mentioned by @emptynick in the Slack's help Channel, the cause of this exists in the following files that use the [gmdate](http://php.net/manual/en/function.gmdate.php) method:
1. In the timestamp formfield view
2. and in the Controller.php

**Comment by marktopper** [comment]
This has been fixed in `v1.x-dev` which will be released as `v1.1` sometime soon.
