### ISSUE TITLE
User define destination path

### ISSUE THREAD

**Issue by P9Q** [thedevdojo/voyager#2371]
Could you please add this feature:

`TABLE_NAME` : is a const always refers to the current BREAD table name.
`DATE('FY')` :  will be translated into `date('FY')`.
`ID`: is a field name of the current BREAD table
 
for example:

`"path" : "/{ TABLE_NAME }/{ DATE('FY') }/{ ID }/covers/"`

will be translated into:

`"path":"/posts/December2017/55/covers/`

![voyager](http://ninamind.com/Untitled-1.jpg)

**Comment by marktopper** [comment]
We are open to pull requests.

**Comment by emptynick** [comment]
This is possible with the media-picker.
