### ISSUE TITLE
More build-in field types and custom field type supported.

### ISSUE THREAD

**Issue by gantoday** [thedevdojo/voyager#2372]

**Comment by fletch3555** [comment]
Requests need to be more specific than that.  WHAT KIND of field types are you requesting? What does it do that others can't? How does this benefit our user-base?

**Comment by gantoday** [comment]
Such as icon select.
My requests is hope to add custom field type supported.

**Comment by fletch3555** [comment]
Adding your own custom field types is already supported (just poorly documented)

**Comment by gantoday** [comment]
@fletch3555 How？More tips，please.

**Comment by theduke** [comment]
@fletch3555 any info on how to add custom field types would be much appreciated!
