### ISSUE TITLE
Custom page for Admin

### ISSUE THREAD

**Issue by EmelyanovMax** [thedevdojo/voyager#2374]
- Laravel Version: 5.4
- Voyager Version: 1.0.1
- PHP Version: 7.0
- Database Driver & Version:
mySql 5.7
### Description:
I have a custom page for Admin and I need to implement this page in Voyger menu and show content of this page inside your template. How can I do that?
this is an image for illustration https://prnt.sc/hozzj2

**Comment by mateushackfaccat** [comment]
Hello @EmelyanovMax, you need to create a new blade file and a new route.
In this file, you need to add the voyager menu in this BLADE file, which is `@extends ('voyager :: master')`.
And to add in the menu, you need to create a new menu in the "Tools" and "Menu Builder" tab and add this route that you have created.
I hope have help you!

**Comment by EmelyanovMax** [comment]
Thanks for fast answer. 
I create a blade in /resources/views.
After adding this string "@extends ('voyager :: master')" I have an error "No hint path defined for [Voyager ]."
Should I change any settings in config file or something else?

**Comment by EmelyanovMax** [comment]
thank you for fast answer.
I created new item in admin menu and don't see my link. As I read https://github.com/the-control-group/voyager/issues/2241 there is no way to implement custom link to admin menu, right? 
So, I can create another one menu, could you tell me how can I show this menu in admin panel?

**Comment by mateushackfaccat** [comment]
So, from what I read, there is a permissions-related bug. I do not know if this is your case.
From what I understand, do you want to add the link of the new page route that you just created correct?
If this is it, just add it by the BUILDER MENU.
Be careful to verify that the user will have permissions to view.

**Comment by EmelyanovMax** [comment]
yes, I created a custom route programmatically and custom template. I added this route by admin builder, but I don't see this menu item in menu. I tried to change admin_menu template like this https://github.com/the-control-group/voyager/issues/2241#issuecomment-346542735 and my menu item is showed

**Comment by fletch3555** [comment]
Sounds like you are currently affected by the bug preventing non-BREAD routes from being displayed.

**Comment by EmelyanovMax** [comment]
it make sense. I have a custom page, there is no connection with models and DB. So, how can I show my page in menu?

**Comment by niels-numbers** [comment]
Yeah thats the bug  #2241. At the moment you only have 2 choices. Either you hope that the bug will be solved by Santa during Christmas, or you could go to `vendor/tcg/resources/views/menu/admin_menu.blade.php` and uncomment line 54:

```
  if(!Auth::user()->can('browse', $item)) {
                //continue;
  }
```
this has the negative side effect that all permission settings under `Roles` for your BREAD routes are ignored. So this workaround is only feasible if you don't need the permission feature.

I hope that this bug will be fixed soon.

**Comment by citronkaste** [comment]
Exactly same problem here. Its not possible to make simple stand-alone custom links that are not bind to BREAD. Links are manually accessible, but doesn't appear on menu after created through builder. Waiting for fix.

**Comment by rotb4rt** [comment]
Hey, does anybody know if this issue is fixed in the newest release?

**Comment by niels-numbers** [comment]
@rotb4rt Yes it has been fixed since [Release v1.0.13.](https://github.com/the-control-group/voyager/releases/tag/v1.0.13)

**Comment by fletch3555** [comment]
@rotb4rt, if an issue is closed, you can assume it's been resolved.  The only exception is if it was closed due to age or no response from the reporter, in which case it should have a comment stating so

**Comment by rotb4rt** [comment]
Ok thanks @fletch3555, I am new here :). Is someone of you Voyager pro's interested in developing on my Voyager project? It's a Affiliate Management System for fair made products?

**Comment by alxkos** [comment]
Hey
Just made a clean install.
Added new menu within a builder. (/admin/test)
Made views/vendor/voyager/test/browse.blade.php simple page
On click on the test from admin menu, getting page not found
If I'm changing the link to categories (with custom browse.blade.php) I can see the custom page.
Please advice.
And big thanks for great work!!


update:
tried to add manually browse_test, still nothing
