### ISSUE TITLE
Change core js/css

### ISSUE THREAD

**Issue by afagard** [thedevdojo/voyager#2379]
I want to be able to modify some of the core javascript in app.js but the entire file is minified and hard to read. Is there any "normal" versions of it? I can't seem to find it.

**Comment by travisneids** [comment]
@afagard The best way to add your own styles and js is by following the documentation here: https://voyager.readme.io/docs/additional-css-and-js-theming

Simply create a new stylesheet in public/css or script in public/js and then add it to your voyager.php config.

If you'd like to see what is going on in app.js, take a look at /vendor/tcg/voyager/resources/assets/js/app.js

**Comment by afagard** [comment]
Yup. I forgot to look there! Doh...
