### ISSUE TITLE
Can't create/update tables

### ISSUE THREAD

**Issue by Snu7z** [thedevdojo/voyager#238]
- Laravel Version: 5.3.25
- Voyager Version: 0.9.33
- PHP Version: I tried both 5.6.10 and PHP7
- Database Driver & Version:

### Description:
I can't create or update tables. When I try to create I get:

Exception: Missing argument 2 for TCGVoyagerHttpControllersVoyagerDatabaseController::buildQuery(), called in /Users/Inizio/Sites/laravel-booking-app/vendor/tcg/voyager/src/Http/Controllers/VoyagerDatabaseController.php on line 40 and defined

When I try to update I get:

ErrorException in DatabaseUpdate.php line 53: Undefined offset.

### Steps To Reproduce:

I followed the video tutorials.

**Comment by craigharman** [comment]
Same issue here. Can't create a new table due to missing argument.

**Comment by marktopper** [comment]
This is fixed in next release. 👍

**Comment by marktopper** [comment]
Fixed in `v0.9.34`.
