### ISSUE TITLE
post model , the out of box with voyager, there is a fault

### ISSUE THREAD

**Issue by bradapeter** [thedevdojo/voyager#2380]
- Laravel Version: 5.5.26
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: Homestead 5

### Description:

when i study the voyager, I found there is a flaw in the Post (the out of box with the voyager).

in the vendor/tcg/voyager/src/Models/Post.php, line 52,
I think the the post belongsTo category, not the hasOne relationships. 

in the meantime. the same file, the post object has a author child, but I suggest the name should named author, not authorId

Do you think so?

**Comment by fletch3555** [comment]
Code change suggestions are best submitted as pull requests, not issues.

Regardless, I think both will work, but hasOne isn't semantically correct.  I've submitted a PR (#2423) to resolve this.
