### ISSUE TITLE
the upsize set true, there is not effect

### ISSUE THREAD

**Issue by bradapeter** [thedevdojo/voyager#2381]
- Laravel Version: 5.2.26
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
when I insert a picture in the post, although I set the the upsize with true. the small image's width less the 1000pixel. according to the guide. the uploaded the picture has no effect to upsize.

so what's going on?

**Comment by emptynick** [comment]
Looking at the code there is no check if `upsize` is true or false.
This should be done [here](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/Controller.php#L226)
