### ISSUE TITLE
Laravel app with voyager admin failed to deploy to www.herokuapp.com

### ISSUE THREAD

**Issue by Oppong** [thedevdojo/voyager#2385]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
My laravel app failed to deploy to heroku with these error  In PDOConnection.php line 47:
SQLSTATE[HY000] [2002] connection refused

PDOConnection.php line 43:
SQLSTATE[2002] Connection refused

**Comment by fletch3555** [comment]
Sounds like your install is missing it's database configuration (or is otherwise misconfigured).  Not a Voyager issue.
