### ISSUE TITLE
Duplicate entry '1' for key 'PRIMARY

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2386]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9

### Description:
I created a relationship for categories table in my posts table. Just by watching this tutorial
https://www.youtube.com/watch?v=iB0rcphwEf8
Now, it is not allowing me to set the same category to multiple posts. How can I resolve this?
I tried by setting id(primary) of categories table to id(index) but then it shows this error.
http://prntscr.com/hr94c4

### Steps To Reproduce:
1) Create a category.
2) Add relation "Post belongs to Category" in Bread.
3) Assign same category to 2 posts.

**Comment by fletch3555** [comment]
Sounds like your relation might be wrong, and that it's trying to write to the categories table.  Unfortunately, I can't provide anything resembling a helpful response without more information.  A good start would be the actual error message and ideally the stack trace.  Also, a screenshot of the BREAD and relationship configuration would help us understand what you're doing.

**Comment by marktopper** [comment]
Closed due to inactivity
