### ISSUE TITLE
Where could be displayed BREAD description

### ISSUE THREAD

**Issue by pcdotfan** [thedevdojo/voyager#2388]
- Laravel Version: 5.5.22
- Voyager Version: 1.0.10
- PHP Version: 7.2.0
- Database Driver & Version: MySQL 5.7

### Description:
Uh...Sorry for such a silly question.

### Steps To Reproduce:
1. Go to /admin/database/xxx/bread/edit
2. <img width="600" alt="qq20171223-164654 2x" src="https://user-images.githubusercontent.com/3370745/34318382-01e71b56-e801-11e7-8d34-18cfa8b688fa.png">
3. I can't see where it displayed....

**Comment by fletch3555** [comment]
All of these fields would be used within Voyager, not intended to be used in your app outside Voyager.  With that said, a number of the fields are legacy from the original version, and may not actually be used anymore.  I can't say for certain off the top of my head whether this field is used, but if you're going to look, you'll be looking for the `description` field on a `DataType` object
