### ISSUE TITLE
[Error] Pdf upload in voyager

### ISSUE THREAD

**Issue by dimitri-dolle** [thedevdojo/voyager#239]
Hi,

I created a BREAD with some fields and one for upload a pdf. 

In Database -> Field Name = Fiche, DB Type = String

In BREAD ->Input Type = File

Then i created a new edit-add.blade.php  for this BREAD.

In this file, i used a input to insert my file ->  `<input type="file" name="fiche" accept="application/pdf">`

But when i call my pdf in my views in front-end like this : `<a href="/storage/{{ $info->fiche }}" target="_blank">Télécharger la fiche détaillée</a>`

I got this error : Failed to load PDF document. When i look my file in my directory i got the file but with a size of 23Octets .

It's like voyager can't upload pdf. If you have a solution to my error i open to the proposal.

Thanks

**Comment by marktopper** [comment]
I guess you have checked that other files works just fine?

**Comment by dimitri-dolle** [comment]
I make test with file .txt and i got a page with a message like this : C:\wamp\tmp\phpB2CE.tmp

Don't think my wamp have a error in this php cause with the other Framework or CMS all work fine.

**Comment by marktopper** [comment]
Please let us know the exact error you get.

**Comment by dimitri-dolle** [comment]
I want upload pdf on my BREAD but when i try to read it on my front-end with a link. The new page is load but this error appears . 

![pdf](https://cloud.githubusercontent.com/assets/16963394/20830279/2119248a-b880-11e6-884f-3b29174770c8.png)

**Comment by marktopper** [comment]
I meant what error you got when trying to upload the .txt file.

Cause the error that it can not read the PDF can be because of many things.

**Comment by marktopper** [comment]
However that PDF error should not have anything todo with Voyager, since all we do is to take the file and save it.
As long as you selected `file` as input method.

**Comment by dimitri-dolle** [comment]
I have selected file as input method.

When i look into the folder where my file are upload,  the pdf is empty after upload on the back of voyager.

**Comment by marktopper** [comment]
What happened when you tried to upload a text file?

**Comment by dimitri-dolle** [comment]
When i upload it on the back i got the success message but when i tried to load it with a link in the front. The page is load but it is blank with this sentence  `C:\wamp\tmp\phpB2CE.tmp`

**Comment by yoan1005** [comment]
Hey,
I haved same problem, for fix i have change method to store so go to **VoyagerBreadController.php** (/vendor/tcg/voyager/src/controllers) and change **line 318**:
**Storage::put(config('voyager.storage.subfolder') . $full_path, (string)$file, 'public');**
TO
**$request->file($row->field)->storeAs(config('voyager.storage.subfolder') . $path, $filename. '.' . $file->getClientOriginalExtension());**

Sorry for my english, i'm french
bye

**Comment by dimitri-dolle** [comment]
Don't worry me too. I'm gonna try this !

**Comment by marktopper** [comment]
Could be a possible fix for this. Please let us know so we can update our codebase, or fell free to do a pull request.

**Comment by dimitri-dolle** [comment]
Thanks yoan it's work ! 

You can update mark.

**Comment by yoan1005** [comment]
Your welcome ;)

**Comment by yoan1005** [comment]
Re, 
An other fix, when you want update a content with file input and you don't want change file input (just change title for example) you have an error :
**Call to a member function getClientOriginalExtension() on null**

For fix , in VoyagerBreadController, insert condition (like for image input) , **new line in bold** and _line exist in italic_
 
                   ** NEW **if ($request->hasFile($row->field)) {** NEW **
                        ** EXIST ** $file = $request->file($row->field);

                        $filename = str_random(20);
                       
                        $path =  $slug . '/' . date('F') . date('Y') . '/';
                       
                        $full_path = $path . $filename . '.' . $file->getClientOriginalExtension();
                       
                        //Storage::put(config('voyager.storage.subfolder') . $full_path, (string)$file, 'public');
                        
                        $request->file($row->field)->storeAs(config('voyager.storage.subfolder') . $path, $filename. '.' . $file->getClientOriginalExtension()); // FIX bug for storage always same size


                        $content = $full_path; ** EXIST **
                   ** NEW **} else {

                        $content = null;

                    }** NEW **


I'm not too used to Github so if some one can make an action for all people can enjoy to this fix.
Thanks

**Comment by marktopper** [comment]
Fixed in #394
