### ISSUE TITLE
Define many-to-many relationships

### ISSUE THREAD

**Issue by P9Q** [thedevdojo/voyager#2392]
I have three tables:
`posts`: default voyager posts table
`post_tag`: the Post-Tag pivot table 
`tags`: tags table which has only id, name, and timestamp fields

You know each `Post` may have many tags and each `Tag` may have many posts, I wanna add a multi-select field into the create-post view, so the user can select multiple tags for a post. (we already can select a category in the create-post view but can't select multiple categories at a time for a post)

Is this possible to implement this using voyager relationship tool?

**Comment by fletch3555** [comment]
What you're looking for is a standard many-to-many relationship, which it sounds like you're already aware of.  If you've haven't tried yet, why not?  If you have, but are having issues, please describe your issues so we can help answer them.  I also suggest watching the Voyager Academy video on relationships.

**Comment by P9Q** [comment]
@fletch3555, It throws following error when I press edit post:

```ErrorException (E_ERROR)
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous 
(SQL: select `id` from `tags` inner join `post_tag` on `tags`.`id` = `post_tag`.`tag_id` where `post_tag`.`post_id` = 779)
(View: /voyager/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php)
(View: /voyager/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php)

**Comment by P9Q** [comment]
I think you should edit `relationship.blade.php`

Doesn't work:
```sql
select `id` from `tags` inner join `post_tag` on `tags`.`id` = `post_tag`.`tag_id` where `post_tag`.`post_id` = 779
```
Works:
```sql
select `tags`.`id` from `tags` inner join `post_tag` on `tags`.`id` = `post_tag`.`tag_id` where `post_tag`.`post_id` = 779
```

**Comment by P9Q** [comment]
I edited following line:
https://github.com/the-control-group/voyager/blob/98361599ad4f80911a951ab9291fbd9e74bad7a4/resources/views/formfields/relationship.blade.php#L142

Into: 
```php
$selected_values = isset($dataTypeContent) ? $dataTypeContent->belongsToMany($options->model, $options->pivot_table)->pluck($options->table.'.'.$options->key)->all() : array();
```

Now it works

**Comment by fletch3555** [comment]
@P9Q, would you please make a Pull Request with that change?

**Comment by mattrabe** [comment]
I confirm that I was having the same problem and that P9Q's fix above by adding `$options->table.'.'.` solved the problem for me. Looks like the code didn't get merged into the dev branch, though, @P9Q create a new PR?

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/2436
