### ISSUE TITLE
 The page has expired due to inactivity.  Please refresh and try again. in voyager shared host

### ISSUE THREAD

**Issue by OmidAhmadyani** [thedevdojo/voyager#2397]
- Laravel Version:5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:
 Server type: MariaDB
Server version: 10.2.9-MariaDB-log - MariaDB Server 

### Description:
when i run admin page in xampp windows thats path is localhost/admin it be work. but when i run it in shared host it not be working. my site is run but when i go to alooservice.ir/admin its redirect me to alooservice.ir/admin/login. its normal. but when i set my email and pass thats show me this:

"
The page has expired due to inactivity.

Please refresh and try again.
"

i exclude my route in app/Http/Middleware/VerifyCsrfToken.php

 protected $except = [
        '/admin/login'
    ];

"error the page has expired due ... " removel. but! when i go to alooservice.ir/admin/login it redirect me again and again to alooservice.ir/admin/login. and not be going to alooservice.ir/admin to show me admin panel.

I apologize to my english!!

**Comment by fletch3555** [comment]
Sounds like your session configuration is set up incorrectly.  Please share your session configuration.

**Comment by OmidAhmadyani** [comment]
@fletch3555 hi

Which file do you mean?

**Comment by mughu94** [comment]
check on storage session must be chmod 775 . it's works !

**Comment by rokshanuo** [comment]
Laravel Version:5.6
Voyager Version: 1.1
PHP Version:7.1
Database Driver & Version:
Server type: mysql

I have the same problem
session files  created with 600
chmod 755 do not solve the problem

**Comment by mikedutuandu** [comment]
Hi guys,

It the same to me (using docker to setup laravel ), Anyone can help to solve it? 

Thanks

**Comment by MarouaneSH** [comment]
I have the same problem here!! Can anyone fix this?

**Comment by aronquiray** [comment]
same problem to me! it was working before. i didn't do anything. then now. it always returns back to login page when i try to add it to exception. but if it was not added to exception, it expires. very weird

**Comment by Thinnakrit1996** [comment]
**same problem to me 
anyone fix this?**

**Comment by defaultpage** [comment]
Hi all! In my case the problem was through PHP 7.2 (Laravel 5.5). Setting PHP to 7.1 solved the problem.

**Comment by secrethash** [comment]
Do remember when using virtual host you also need to update your `session.domain` and `app.url` configuration to the virtual host address ex: `app.test`

**Comment by MarouaneSH** [comment]
`sudo chgrp -R www-data storage bootstrap/cache
`

**Comment by devdevdenis** [comment]
I have same problem. anyone fix this?

**Comment by devdevdenis** [comment]
I solved this problem by changing the mbstring.func_overload parameter to the value "0" in the server configuration. Some hosting providers allow you to do this. All the rest found the tips did not help.

**Comment by fletch3555** [comment]
Based on all the comments, this has nothing to do with Voyager, and is either a php.ini, webserver, or laravel misconfiguration.  Closing
