### ISSUE TITLE
Add default settings when without using dummy flag

### ISSUE THREAD

**Issue by handiwijoyo** [thedevdojo/voyager#2398]
When install voyager without dummy flag, the settings are empty. It's hard to figure out what key need to add for something like web title and description. Better we leave the default settings included.

![image](https://user-images.githubusercontent.com/4060094/34378233-6fa4534c-eb27-11e7-9070-9b9f41ddb6a9.png)

```The title is empty:```

![image](https://user-images.githubusercontent.com/4060094/34378580-23b772b4-eb29-11e7-979f-c3975542a4dc.png)

I will submit PR for this.

**Comment by fletch3555** [comment]
I think I recommended exactly this when we implemented the `without-dummy` flag...
