### ISSUE TITLE
[Feature]New User-Role-Permission

### ISSUE THREAD

**Issue by handiwijoyo** [thedevdojo/voyager#240]
I'm currently working on new role-permission based user. 

List of changes:

- [x] User can only  have a role. (Please let me know if you need multiple roles on user / use cases).
- [x] Remove role_user table.
- [x] Add admin role to default admin user.
- [x] Add admin_role to config to change default admin role.
- [x] Add permissions & permission_role table.
- [x] Add permissions generator during BREAD creation.
- [x] Manage Role's permissions
- [x] Add role selection to User interface.
- [x] Add permission checker on Bread Controller

Ref #33 #110 

**Generate Permission on BREAD editor**

![image](https://cloud.githubusercontent.com/assets/4060094/20763624/6c658d8a-b75d-11e6-8bb4-f4d69f2efbfa.png)

**Adding Permissions to Role**

![image](https://cloud.githubusercontent.com/assets/4060094/20771488/334c5ef6-b77c-11e6-9455-1065eb5ed7d7.png)

**Select User Role**

![image](https://cloud.githubusercontent.com/assets/4060094/20771633/cc924c10-b77c-11e6-8249-a31e884397a8.png)

**Comment by fishmad** [comment]
Nice, I think multiple roles would be better.

**Comment by handiwijoyo** [comment]
@fishmad could you please give example of use cases for multiple roles?
