### ISSUE TITLE
Laravel tinker does not show prompt, works incorrectly

### ISSUE THREAD

**Issue by blitux** [thedevdojo/voyager#2405]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.10
- PHP Version: 7.1.12-3+ubuntu16.04.1+deb.sury.org+1
- Database Driver & Version: Does not apply

### Description:

After a clean install of laravel and larapack/voyager-hooks:v1.0.4, the command `php artisan tinker` does not show the prompt ">>>" and works incorrectly. Autocompletion doesn't work, arrow keys throws escape characters.

It seems like voyager is interfering with tinker or Psy Shell.

### Steps To Reproduce:

1. Install last version of laravel with `laravel new test`
2. Run `php artisan tinker`. You will see the prompt ">>>"
3. Run `composer require larapack/voyager-hooks:v1.0.4`
4. Run `php artisan tinker`. You will see Psy Shell's welcome message and NOT the prompt ">>>"

**Comment by fletch3555** [comment]
I assure you Voyager does absolutely nothing that can affect the Psy Shell or Laravel Tinker... at least nothing that wouldn't also affect web (e.g. ServiceProvider issues).  From your PHP version, I'm assuming you're on Ubuntu, correct?  Might be better to report this in a more generic Laravel forum like Larachat.

**Comment by blitux** [comment]
That's the conclusion I reached when I started a project from scratch. This doesn't happen with a fresh laravel install, but it does happen after I install voyager. Maybe it's a dependency. Didn't get that far, but will try the dependencies one by one.

**Comment by blitux** [comment]
Found it. It's `larapack/voyager-hooks:v1.0.4`. I've updated the description to reflect that. Will try to debug the issue and I will leave the report on the voyager-hooks repo.

**Comment by fletch3555** [comment]
We'll track this under the `voyager-hooks` repo and close this one.  Ref: larapack/voyager-hooks#15
