### ISSUE TITLE
MySqlSchemaManager  Undefined index: index_type

### ISSUE THREAD

**Issue by gokhanyildiz** [thedevdojo/voyager#2406]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.10
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7.20

### Description:
Setting up the hooks
Hooks are now ready to use! Go ahead and try to "php artisan hook:install test-hook"
Publishing the Voyager assets, database, language, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Copied Directory [/vendor/tcg/voyager/publishable/lang] To [/resources/lang]
Publishing complete.
Publishing complete.
Migrating the database tables into your application
Migration table created successfully.

In MySqlSchemaManager.php line 75:

  Undefined index: index_type

**Comment by fletch3555** [comment]
Hooks are managed separately (the [voyager-hooks repo](https://github.com/larapack/voyager-hooks) is the integration point between Voyager and the Hooks package, and each hook has it's own repo).  This would be better reported in one of those two places, likely the hook itself as a starting point (you don't blame your cabinet maker when your cup is too tall to fit, right?)

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/3336 (more information, same issue)
