### ISSUE TITLE
Avoiding the use of symlink

### ISSUE THREAD

**Issue by belhauss** [thedevdojo/voyager#2408]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:
Mysql
### Description:
Hello,

First of all, thank you for this awesome project.

My question is, is there a way on how use Voyager without the Symlink by only editing config files for example ? or any possible way.

As a work arround on shared hosting I created storage folder in public, and copied all the uploaded files there, but it's not a clean solution.

Thank you guys again.

**Comment by VictorAvelar** [comment]
Most of the shared hosting services provide ssh access the server if you log in using ssh you can manually create the symlink, so that way you do not need a workaround.

**Comment by belhauss** [comment]
Thanks @VictorAvelar but this shared host doesn't have this option, I should pass to N+1 offer to get it..

**Comment by belhauss** [comment]
Hello,
I figured it out finally, the host has this weird naming of their files system, when I did print the file directory with PHP it shows /home/username/public, but the real path was something else, I was looking in the logs looking for an error and the path hit me, it was something like /homz,456/username.

I guess it's a "security" mesure..

Thanks guys
