### ISSUE TITLE
Send Email When Admin Update Model

### ISSUE THREAD

**Issue by ezani92** [thedevdojo/voyager#2409]
Hi, can i send and email if let say, for [MODEL ORDER] when admin update order complete at bread. then send an email to user.

- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 5.6
- Database Driver & Version: mysql

**Comment by fletch3555** [comment]
All version fields are required.

**Comment by ezani92** [comment]
i updated the version on my question.

**Comment by emptynick** [comment]
Yes thats possible with [Events](https://laravel.com/docs/5.6/events#generating-events-and-listeners)
See [here](https://github.com/the-control-group/voyager/tree/1.0/src/Events)
You might want to use the `BreadData...` Events.

**Comment by ezani92** [comment]
Nice. should at this at documentation.
