### ISSUE TITLE
Cannot select multiple images in posts

### ISSUE THREAD

**Issue by greenlevel** [thedevdojo/voyager#2411]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I changed the bread to multiple images in the post section.
However when i tested it i couldn't select multiple images in a post.

I also did this for the page section -> image also and there is no probem selection multiple images

### Steps To Reproduce:
By posts change input type by image to multiple.

**Comment by emptynick** [comment]
This is because posts uses a different view.
Take a look at [this](https://github.com/the-control-group/voyager/blob/1.0/resources/views/posts/edit-add.blade.php#L233)
Pages use the generic bread-view.
