### ISSUE TITLE
Assign role for user while register

### ISSUE THREAD

**Issue by meass** [thedevdojo/voyager#2415]
- Laravel Version: 5.5.25
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
Hello, I need help. I want to create 2 role for user: one is normal user and the other one is Shop owner.
I want to assign role for both user while registration but the result end up always normal user.
Can anyone help me? I really need your help.
And sorry for my bad English.

**Comment by fletch3555** [comment]
The default is normal user because that's the default in your DB. If you want something else set, you either need to set it manually (by overriding some part of the creation, possibly through events), or by changing the default in the DB (only if ALL new accounts should have the same new one).

I'm sure there are other ways as well.  How you do it is ultimately up to you.

**Comment by meass** [comment]
Thank you but can you give me an example.
It is hard for me to understand.

**Comment by meass** [comment]
@fletch3555 What is that event? can you tell me a bit more?

**Comment by emptynick** [comment]
I bet he means [Eloquent Events](https://laravel.com/docs/5.5/eloquent#events) on your user-model.
BTW: did Laravel remove closure-based events in 5.5?

**Comment by meass** [comment]
@emptynick Thank you so much. 
Can you tell me how to override it?

**Comment by meass** [comment]
I'm trying to use this but it doesn't work.
 $role = Role::where('name', 'shop_owner')->firstOrFail();
return User::create([
          'name'     => $data['name'],
          'first_name'     => $data['first_name'],
          'last_name'    => $data['last_name'],
          'email'    => $data['email'],
          'password' => bcrypt($data['password']),
          'role_id'        => $role->id,
        ]);

**Comment by fletch3555** [comment]
@meass, how doesn't that work? Do you get an error? Does it complete, but not set it properly? We need more information if you want help

**Comment by emptynick** [comment]
Closing as solution was provided.
