### ISSUE TITLE
Invalid menu Item dynamic route link for subdomain

### ISSUE THREAD

**Issue by shkhalid** [thedevdojo/voyager#2416]
I am using the following routes. `url($item->link())` is generating invalid link.
it shows invalid link `http://SITE_URL/type/group`. The link should be `http://abc.SITE_URL/type/group`.
```
Route::domain('abc.'.env('SITE_URL'))->group(function()
{
    Route::get('/{type?}/{group?}','AbcController@show')->name('domain.abc.show');
});
```

**Comment by emptynick** [comment]
~Why dont you just name your routes?~
Voyager only uses Laravels route functions, so I dont think there is something wrong about Voyager

**Comment by fletch3555** [comment]
@shahkhalid-me, You probably have a generic route somewhere that is matching before the `abc` subdomain one.

As @emptynick said, this is certainly not a Voyager issue, but a Laravel one.  If you need further assistance, you can join our Slack group (or better yet LaraChat) and ask, or ask elsewhere.
