### ISSUE TITLE
JSON File for settings

### ISSUE THREAD

**Issue by ToshKoevoets** [thedevdojo/voyager#2421]
### Description:
I know it might not be the right place to put this, I find the settings module a nice idea but I don't see how this is functional in a standard deployment process. 

It would be nice to make a config file for the setting so it's easily integrated in source control and deployment process.

Is there anything on the planning for this? Or are you open for PR's for this?

**Comment by fletch3555** [comment]
Settings are intended to provide a UI for configuring your site (or really anything you want to use it for).  You're certainly not required to use them.

With that said, it's stored in the DB and can be migrated easily.  If you prefer to use a config file instead, you're more than welcome to, but we likely won't be changing this functionality anytime soon.

**Comment by ToshKoevoets** [comment]
That's a shame. Since you advice to use the settings(''), the code will be dependent on database configuration. You see this a lot in WordPress and it's very painfull. But anyway good luck!
