### ISSUE TITLE
Interesting TEXT

### ISSUE THREAD

**Issue by a2aliyev** [thedevdojo/voyager#2427]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
![voyager](https://user-images.githubusercontent.com/9583510/34556025-32991b68-f14e-11e7-8f80-b81883ef3fb9.png)

I have successfully installed voyager. However when I opened the voyager somehow I get intersting text styling instead of regular texts. Can anyone point out the problem? any hints would be appreciated.

thanks

**Comment by emptynick** [comment]
The language files didnt publish.
Run `php artisan vendor:publish --tag=lang --force`

**Comment by fletch3555** [comment]
Exactly what @emptynick said.  If that doesn't work, you'll have to delete the resources/lang folder and try again.  We'll likely be changing it in the future so this step isn't needed.

Also, as a side note, all version information at the top of the issue template is required for all issues.  Future issues opened this way may be closed without response until it gets updated.

**Comment by a2aliyev** [comment]
I did what you guys suggested but apparently it did not solve the problem. I have absolutely no clue how to solve the issue? It is very annoying. Everything works fine except texts.


SOLVED:

Problem was that I had changed default lang of the laravel which was not included as subfolder in the voyager's lang folder. Solution is adding the subfolder to the resources/lang named as laravel's current language.

**Comment by fletch3555** [comment]
You must have missed a step somewhere. I assure you that your issue is missing updates to translation files, which is fixed by @emptynick's suggestion above.  Please confirm that you deleted all languages out if the Lang folder, then ran `artisan vendor:publish`

**Comment by a2aliyev** [comment]
I was using different default lang for laravel application before the installation of the voyager. That language was not included in the language folder of voyager.

**Comment by fletch3555** [comment]
That would certainly do it.
