### ISSUE TITLE
How to create a custom admin page?

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#2428]
- Laravel Version: v5.5.27
- Voyager Version: v1.0.10
- PHP Version: 7.1.7-1+ubuntu16.04
- Database Driver & Version: MySQL 5.7.18-0ubuntu0.16.04.1 - (Ubuntu) 

### Question:

How should one create a custom admin page that has nothing to do with a BREAD view (For example a page where I can activate or send emails to a user or something similar).

I am aware of the bug that custom pages are not shown in the menu as stated in #2374 and #2241. 

This is what I tried so far:

1) Added a route in my web.php file:

```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::get('test', function(){
      return view('test');
    })
});
```

2) Created a test.blade.php file in my views directory:

```
@extends('voyager::master')


@section('content')

      <h1>This is awesome!!</h1>

@endsection
```

Now when I am logged in and access my-dobain.dev/admin/test the custom page is shown.

However, if I am not logged in I get an error message:

![image](https://user-images.githubusercontent.com/1765602/34566024-54d7c92c-f15d-11e7-90ee-be9522dfaa8f.png)

How can I add a custom page to the admin area, so that I will be redirected to login if I am not logged in? 

Also is there any documentation about the default CSS that is shipped with VOYAGER ADMIN like buttons and panels? Currently I go to vendor/tcg/voyager/resources/views and steal & hack my own templates together with the elements that I want to use. Is that the proper way?

**Comment by fletch3555** [comment]
You need to add the middleware that Voyager pages use. I believe it's `admin.auth` or something like that.  You can check by seeing what the Voyager routes have listed in `artisan routes:list`, or by checking the route file loaded by Voyager at `vendor/tcg/voyager/routes/voyager.php` (I'm mobile, so apologies if the path is wrong)

**Comment by niels-numbers** [comment]
Thank you. According to the CSS, I guess there is no documentations and it is recommended to use your own custom CSS & JS files?

**Comment by niels-numbers** [comment]
@fletch3555 okay so I found the middleware alias is `admin.user` in the `vendor/tcg/voyager/src/VoyagerServiceProvider.php` file. However if I add the middleware like this:
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
    Route::get('users/register','Admin\ConfirmUserController@index')->middleware('admin.user');
});
```
then the redirect goes to `mypage.com/login` instead of `mypage.com/admin/login` when not logged in.  Why is this redirect not working? For other pages like `mypage.com/admin/users` one is redirected correctly to `mypage.com/admin/login`

**Comment by fletch3555** [comment]
I'm not sure then. You'll have to do a bit of debugging.  Try adding a `dd()` in the middleware and see why it's doing that.  If that doesn't trigger, then it's a different problem.  Check `artisan route:list` to make sure everything about your route matches the other Voyager routes (no extra middleware groups, etc).  I don't know why this would cause your issue, but you could also try moving your route above Voyager::routes()

**Comment by niels-numbers** [comment]
I am sorry - I just realized that I had in the constructor of my controller `$this->middleware('auth')` which caused the redirect to mypage.com/login  ... Whoupsi

**Comment by damms005** [comment]
I believe it will really be helpful if this very important information is added to [the documentation](https://voyager.readme.io/docs/).

This will allow for Voyager to be more easily extended to cater for other admin actions like the OP's case

**Comment by roy-souvik** [comment]
In the file `vendor/tcg/voyager/src/Http/Middleware/VoyagerAdminMiddleware.php` the code says that it will redirect to `return redirect(route('voyager.login'))`. So I think if we can make a custom middleware with the same code but the `redirect` will be different then it can solve the problem.

**Comment by ghost** [comment]
Thanks! it does work with ->middleware('admin.user');
