### ISSUE TITLE
[Bug] Viewing Table Fields

### ISSUE THREAD

**Issue by joshuaajones** [thedevdojo/voyager#243]
- Laravel Version: 5.3.25
- Voyager Version: 0.10 & 0.9.33
- PHP Version: 7.0.4
- Database Driver & Version: MySQL 5.7.11

### Description:

The dialog with the table data shows blank rows.  Addressed in #242 

### Steps To Reproduce:

Click view for any table.

**Comment by furqan99** [comment]
same problem with my  views . do you find any solution ??

**Comment by joshuaajones** [comment]
Yes, it's a simple fix.  Check the PR #242

**Comment by furqan99** [comment]
thank you

**Comment by joshuaajones** [comment]
PR #268
