### ISSUE TITLE
is it possible to change the master layout and dashboard??

### ISSUE THREAD

**Issue by Badreddinee** [thedevdojo/voyager#2430]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.0

### Description:
i want to implement my design into the admin panel, but i don't know is it possible to override tha master layout and how to change the dashboard

**Comment by handiwijoyo** [comment]
We already have the documentation for this https://voyager.readme.io/docs/overriding-views

**Comment by Badreddinee** [comment]
but it doesn't include the master layout 
how to override it, or if i create one how can i display the menu and stuff in it

**Comment by fletch3555** [comment]
I really want to remove that page from the documentation since it only seems to cause confusion....

The view override functionality is a laravel feature, not a Voyager one.  We include it because of the dynamic nature of our BREAD functionality.

So Yes, you can override the master layout in the same way.  Just be careful doing so since it affects nearly every Voyager page.

**Comment by Badreddinee** [comment]
by creating a folder named master or just under the voyager directory ??

**Comment by fletch3555** [comment]
It needs to match the view structure.  I'm mobile at the moment so I cant easily look it up for you, but I believe it should be at the root of the voyager view folder

**Comment by niels-numbers** [comment]
I wanted to do the same, so here is what you can do:

1) If you want to completely change the dashboard page, you probably want to change the controller as well. Take a look at https://voyager.readme.io/docs/using-custom-http-controllers and add a `index` method to `app/Http/Controllers/Voyager/VoyagerController` with the route to your custom blade file.

2) If you want to change the general look of every page, copy the content from the file `vendor/tcg/voyager/resources/master.blade.php` into a new file  `resources/views/vendor/voyager/master.blade.php` and do necessary changes in the latter file.

**Comment by almohajire** [comment]
Thanks iwasherefirst2 Your reply has helped me

**Comment by omept** [comment]
@almohajire  and me too. Thank you iwasherefirst2.
