### ISSUE TITLE
Belongs To relationship.blade.php exception

### ISSUE THREAD

**Issue by vaidotasposkus** [thedevdojo/voyager#2431]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.0
- PHP Version: 7
- Database Driver & Version:

### Description:

Something wrong with my application. When I try to in list i get exception Call to undefined method Illuminate\Database\Query\Builder::getRelationship() (View: C:\Work\shooting_calendar\vendor\tcg\voyager\resources\views\formfields\relationship.blade.php) (View: X:\xx\xx\vendor\tcg\voyager\resources\views\formfields\relationship.blade.php). And don't know why it doesn;t work. Does someone have the same proble?

**Comment by aruberutochan** [comment]
I have the same problem. 

- Laravel Version: 5.5.28
- Voyager Version: 1.0.0
- PHP Version: 7.0
- Database Mariadb

I realised that changing the file /vendor/tcg/voyager/resources/views/formfields/relationship.blade.php to the previous version in the repository It goes well, basically you have to change the line 14:
`
$query = $model::getRelationship($relationshipData->{$options->column});`
by 
`$query = $model::find($relationshipData->{$options->column});`

I am new on voyager and laravel and I don't know what consequences involves that change so i don't want to make a pull request by now.

Maybe if you don't want to modify the code in the tcg/voyager vendor folder, you could temporarily edit your user model adding this to the App\User
```

class User extends \TCG\Voyager\Models\User

{

    // ... More code here

    protected static $relationships = [];

    public static function getRelationship($id)

    {

        if (!isset(self::$relationships[$id])) {

            self::$relationships[$id] = self::find($id);

        }

        return self::$relationships[$id];

    }

    // ... More code here

}

```
It works for me but i am only learning and not making anything in a production app, I hope it will be fixed soon in the master branch

**Comment by joshuadegier** [comment]
@aruberutochan until the fix is merged (I still get the error on a fresh install I did today), you can also create a template under /resources/views/voyager/formfields/relationship.blade.php to override the template that comes with Voyager by default (in stead of changing files in de vendor directory).

**Comment by leonardyhuang** [comment]
I had the same issue, and my workaround is to use this trait below in the models with relationship:

```php
<?php

namespace App\Traits;

trait HasVoyagerRelationship
{
    public static function getRelationship($id)
    {
        return self::find($id);
    }
}
```

**Comment by vitormicillo** [comment]
hi guys, how to solve this problem?

**Comment by 5alvatore** [comment]
I am still getting the error. Not sure if the correct fix was merged.
For now the **temporary fix** is to override the relationship.blade.php file. 

**Step 1 - Create a new blade file -** 
resources\views\vendor\voyager\formfields\relationship.blade.php

**Step 2 - Copy content from -** 
tcg\voyager\resources\views\formfields\relationship.blade.php

**Step 3 - Paste in the newly created blade file and replace line 14th by -**
$query = $model::find($relationshipData->{$options->column});

**Comment by fletch3555** [comment]
The correct fix was merged.  If you have custom models (not ones that ship with Voyager), you'll need to add the `HasRelationships` trait to any model you use Voyager's relationship builder with.

**Comment by priyag597** [comment]
hii ,

i had installed voyager but when i go to click on product nav facing this error can anyone help with this 

![image](https://user-images.githubusercontent.com/46341574/50629018-d537ed00-0f60-11e9-8949-3a973a904e06.png)

**Comment by emptynick** [comment]
Looks like you have something like this in your custom controller:
```
$relationships = $this->getRelationships($dataType);	
...
$query = $model::select('*')->with($relationships);
```
You can safely remove the first line and change to second to
`$query = $model::select('*');`

**Comment by priyag597** [comment]
> Looks like you have something like this in your custom controller:
> 
> ```
> $relationships = $this->getRelationships($dataType);	
> ...
> $query = $model::select('*')->with($relationships);
> ```
> You can safely remove the first line and change to second to
> `$query = $model::select('*');`
custom controller mean in my productController ??

**Comment by emptynick** [comment]
Yes

**Comment by priyag597** [comment]
yes it has

**Comment by priyag597** [comment]
$relationships = $this->getRelationships($dataType); 

this line is der in index and edit function

**Comment by emptynick** [comment]
Yes, remove it as per my previous comment.

**Comment by priyag597** [comment]
> Yes, remove it as per my previous comment.

sorrry but i couldnt understand what i need to do exactly

**Comment by emptynick** [comment]
`$relationships = $this->getRelationships($dataType);` <- remove this line completely
`$query = $model::select('*')->with($relationships);` <- change this line so it is `$query = $model->select('*');`

**Comment by priyag597** [comment]
$query = $model::select('*')->with($relationships); <- change this line so it is $query = $model->select('*'); 

this has alredy chnaged according to you .

**Comment by priyag597** [comment]
public function edit(Request $request, $id)
    {
        $slug = $this->getSlug($request);

        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        // Compatibility with Model binding.
        $id = $id instanceof Model ? $id->{$id->getKeyName()} : $id;

        //$relationships = $this->getRelationships($dataType);

        $dataTypeContent = (strlen($dataType->model_name) != 0)
            ? app($dataType->model_name)->with($relationships)->findOrFail($id)
            : DB::table($dataType->name)->where('id', $id)->first(); // If Model doest exist, get data from table name

 if (strlen($dataType->model_name) != 0) {
            $model = app($dataType->model_name);
            $query = $model::select('*');



 in  index  function 
            //$relationships = $this->getRelationships($dataType);

            // If a column has a relationship associated with it, we do not want to show that field
            $this->removeRelationshipField($dataType, 'browse');

            if ($search->value && $search->key && $search->filter) {
                $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
                $search_value = ($search->filter == 'equals') ? $search->value : '%'.$search->value.'%';
                $query->where($search->key, $search_filter, $search_value);
            }

            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'DESC';
                $dataTypeContent = call_user_func([
                    $query->with($relationships)->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->with($relationships)->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }

**Comment by priyag597** [comment]
ErrorException (E_ERROR)
Too few arguments to function TCG\Voyager\Models\DataRow::sortByUrl(), 0 passed in C:\xampp\htdocs\mfscl_website\storage\framework\views\af0f59f74b7ead321b3661535f5bd10077a2c768.php on line 61 and exactly 2 expected (View: C:\xampp\htdocs\mfscl_website\resources\views\vendor\voyager\products\browse.blade.php)
Previous exceptions
Too few arguments to function TCG\Voyager\Models\DataRow::sortByUrl(), 0 passed in C:\xampp\htdocs\mfscl_website\storage\framework\views\af0f59f74b7ead321b3661535f5bd10077a2c768.php on line 61 and exactly 2 expected (0)

error has been arised

**Comment by priyag597** [comment]
please can any one help me

**Comment by emptynick** [comment]
I have no idea what you are posting here.
Please ask in our Slack group.

**Comment by priyag597** [comment]
i had just posted code where this variable $relationships has used in so many places so definitely i will get error is there any other way to solve ? and ya thanks for putting your effort

**Comment by emptynick** [comment]
In your controller, you have to do the same for all methods (remove the line, change the other).
`sortByUrl` was changed before.
I suggest you look at our "new" [BaseController ](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerBaseController.php)and see whats changed and adapt it.

**Comment by priyag597** [comment]
Too few arguments to function TCG\Voyager\Models\DataRow::sortByUrl(), 0 passed in C:\xampp\htdocs\mfscl_website\storage\framework\views\af0f59f74b7ead321b3661535f5bd10077a2c768.php on line 61 and exactly 2 expected (View: C:\xampp\htdocs\mfscl_website\resources\views\vendor\voyager\products\browse.blade.php) ◀"

@emptynick please help me 
I had changed according to dat  but now getting this error

**Comment by priyag597** [comment]
guys can anyone help me 

Too few arguments to function TCG\Voyager\Models\DataRow::sortByUrl(), 0 passed in C:\xampp\htdocs\mfscl_website\storage\framework\views\af0f59f74b7ead321b3661535f5bd10077a2c768.php on line 61 and exactly 2 expected (View: C:\xampp\htdocs\mfscl_website\resources\views\vendor\voyager\products\browse.blade.php) ◀"
