### ISSUE TITLE
How to get the latest update?

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#2435]
- Laravel Version: v5.5.27
- Voyager Version: v1.0.11
- PHP Version: 7.1.7-1+ubuntu16.04
- Database Driver & Version: MySQL 5.7.18-0ubuntu0.16.04.1 - (Ubuntu) 

I would like to get the newest version of Voyager to get this [bugfix](https://github.com/the-control-group/voyager/commit/c724f9910b6fd475d5baa7a4c068d2c625b1477f ) 

Using `composer update` is not doing any updates to the voyager pacake. In the composer.lock file it states that I have the version v1.0.11, however there have been no changes to the file src/Policies/MenuItemPolicy.php that were commited 13h ago. How can I get these fixes?

I also changed `"tcg/voyager": "^1.0"` in my composer.json file to  `"tcg/voyager": "1.0.x@dev"` but then voyager does not work anymore because I get the error that the column `name` does not exist in the table `permission`. I also did not find a migration file that would add such a column to the `permission`table.

**Comment by emptynick** [comment]
You can simply use:
`"tcg/voyager": "dev-master"`

About the name, I guess it should be `key`
@fletch3555

**Comment by niels-numbers** [comment]
@emptynick Thanks for your help! I changed the version to "dev-master" in my composer.json file but when I try to update I get this error:

![image](https://user-images.githubusercontent.com/1765602/34606616-61387dc0-f210-11e7-92e8-49ba2e87e1f2.png)

Any idea why its not working?

**Comment by emptynick** [comment]
`dev-master` is working fine for me, it resolves it as `1.0.x-dev` probably you can stick to your previous usage.

**Comment by niels-numbers** [comment]
@emptynick do you have updated the latest version?
Because I just created a new Laravel application from scratch, installed Voyager as described at https://github.com/the-control-group/voyager and changed in composer.json `"tcg/voyager": "1.0.x@dev"` and updated with composer.

If I login at mypage.com/admin I get the following error:

![image](https://user-images.githubusercontent.com/1765602/34609301-73be559e-f21c-11e7-96d5-3e573b88747a.png)

Looks like the problem is caused by `whereName` from this [commit](https://github.com/the-control-group/voyager/commit/c724f9910b6fd475d5baa7a4c068d2c625b1477f), since the `permission`table has no `name` colum? Should't it be `where('key','browse_'.$slug)` instead of `whereName('browse_'.$slug)`?

**Comment by emptynick** [comment]
> About the name, I guess it should be key

Jup, I think so. Try changing it!

**Comment by niels-numbers** [comment]
Yes it works! Thank you.

**Comment by fletch3555** [comment]
Couple things...

First, you're on the latest release already. I don't make new releases for every single commit.

Second, dev-master won't work because we don't have a master branch anymore. You'll need dev-1.0 (I think).

Third, with regards to key vs name, youre probably right. I'm sure that's my fault for not checking. If either of you would like to open a PR with that fix (assuming it's the right fix), I'd appreciate it.  I'm just surprised this is the first I've heard of this issue.

**Comment by niels-numbers** [comment]
Alright thanks for that explanation! I will open a PR with that fix!

**Comment by isDOSe** [comment]
> You can simply use:
> `"tcg/voyager": "dev-master"`
> 
> About the name, I guess it should be `key`
> @fletch3555

Is this solution still working at this moment?

**Comment by odion-cloud** [comment]
hello please i am having issue on my admin menus now working fine after i run composer update ,the front end works fine but the back-end menus show class APP\ does not exist i really can not fix this error

**Comment by MrCrayon** [comment]
@odion-cloud please stop commenting on unrelated closed issues, you have already been told to open a new issue or you can ask in Voyager slack group.

**Comment by riwash** [comment]
> > You can simply use:
> > `"tcg/voyager": "dev-master"`
> > About the name, I guess it should be `key`
> > @fletch3555
> 
> Is this solution still working at this moment?

where to use?

**Comment by fletch3555** [comment]
You're quoting a comment from 2 years ago, made for a MUCH older version of Voyager.  If you're having problems, please create your own issue.  If you have questions, please ask in our slack
