### ISSUE TITLE
Relationship other data is not showing

### ISSUE THREAD

**Issue by abhishek003ite** [thedevdojo/voyager#2440]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version: 7.*
- Database Driver & Version: MySql & 5.7

### Description:
I am creating a Relationship using voyager, but when I am selecting display name to "id" it is showing properly but when I am selecting any other field name like "name" or "code" it is not showing into the field. Please try to resolve.

**Comment by handiwijoyo** [comment]
Please make sure your relation field is set to `Text` type

**Comment by abhishek003ite** [comment]
Hi Handiwijoyo,

I made the field to text for relation.

But still when I am selecting "name" still it is coming blank in the dropdown but when I am selecting the "id". It is coming perfect.

Please find the attached shots for the same.

-Abhishek
![screenshot 2018-01-08 21 21 47](https://user-images.githubusercontent.com/6541798/34678992-a6c8b88a-f4ba-11e7-9abb-ef9f8430ac1a.png)
![screenshot 2018-01-08 21 22 12](https://user-images.githubusercontent.com/6541798/34679012-b2fe44a8-f4ba-11e7-8908-ec9f06059411.png)
![screenshot 2018-01-08 21 22 30](https://user-images.githubusercontent.com/6541798/34679013-b33cb698-f4ba-11e7-81a3-96d6641b1134.png)

**Comment by handiwijoyo** [comment]
I see that your dropdown have 2 results, but only the result are empty string.

Can you make sure your districtname filled with data in your districts table?

**Comment by abhishek003ite** [comment]
Yes I have data in my table with the field.

Please find Screenshot.
![screenshot 2018-01-09 00 33 17](https://user-images.githubusercontent.com/6541798/34687457-c9da4e8c-f4d4-11e7-84b5-6c5072ff3c85.png)

**Comment by sertxudev** [comment]
Change districtName to districtname or district_name it doesn't support uppercase letters

**Comment by abhishek003ite** [comment]
Hi Sertxudeveloper,

It works. Thanks for your kind support.

-Abhishek

**Comment by panjitito** [comment]
Almost pull may hair out because of this. And voila, just the matter of uppercase letter.
