### ISSUE TITLE
DOES NOT DISPLAY IMAGES

### ISSUE THREAD

**Issue by a2aliyev** [thedevdojo/voyager#2442]
- Laravel Version: 5.5.1
- Voyager Version: 1.0
- PHP Version:7.1.11
- Database Driver & Version: MariaDB

### Description:
I have recently installed latest version of Voyager. It does not display the avatar and the uploaded images. I have checked couple issues that have already been posted, and tried couple solutions such as 
   1) php artisan storage:link
   2) APP_URL: http://localhost:8000
. None of the proposed solution solved the issue for me apparently.  Could you please propose any alternative solution to the issue.

Thanks in advance.
![screen shot 2018-01-07 at 12 22 34 pm](https://user-images.githubusercontent.com/9583510/34647777-7ae2c1a4-f3a5-11e7-93a8-c4ec0d793b00.png)

**Comment by handiwijoyo** [comment]
APP_URL needs to be http://localhost:8000

**Comment by a2aliyev** [comment]
Hello handiwijoyo,

The solution that you have proposed did not solve the problem.

Thanks.

**Comment by handiwijoyo** [comment]
Can you copy your image url that is broken?

**Comment by belhauss** [comment]
If you're on windows, try execut `php artisan storage:link` via CMD with administrator right.

**Comment by sertxudev** [comment]
It could be if you're developing in a subfolder, for example, http://localhost/project/public, create a virtual host on your computer that points to the *public* folder.

**Comment by handiwijoyo** [comment]
Can you try to use http://127.0.0.1:8000 for APP_URL to see if it works

**Comment by a2aliyev** [comment]
Thank you all for the responses.

SOLVED.

Issue was a wrong path to the folder. After editing APP_URL and config/filesystems file been able to solve the problem.

**Comment by belhauss** [comment]
@a2aliyev Good on you, since it's solved you can close the issue.

**Comment by prasathkarnan** [comment]
> APP_URL needs to be http://localhost:8000

The solution that you have proposed did not solve the problem.

Thanks.

**Comment by prasathkarnan** [comment]
The "public/storage" directory already exists.
Any solution pls help

**Comment by fletch3555** [comment]
This issue has been closed for 9+ months.  If you're having issues, please open your own issue or ask in our Slack group.
