### ISSUE TITLE
The BREAD very slow with big data

### ISSUE THREAD

**Issue by lucastruong** [thedevdojo/voyager#2443]
- Laravel Version: v5.5.28
- Voyager Version: v1.0.10
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:
The BREAD very slow with big data

### Steps To Reproduce:
1. Create a BREAD
2. Import about 5 thousand record
3. Access BREAD
Result: Cannot load page

**Comment by handiwijoyo** [comment]
You can use server side pagination when creating BREAD. Have try it?

**Comment by lucastruong** [comment]
@handiwijoyo 
> You can use server side pagination when creating BREAD. Have try it?

Yeah, I got it. It is work normal.
Thank you :)
