### ISSUE TITLE
Belongs to Relationship Error!

### ISSUE THREAD

**Issue by mohdabbas** [thedevdojo/voyager#2444]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.11
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB

### Description:
Getting the following error, after I create belongsto relationship and then click browse bread:

Call to undefined method Illuminate\Database\Query\Builder::getRelationship() (View: C:\xampp\htdocs\project\vendor\tcg\voyager\resources\views\formfields\relationship.blade.php) (View: C:\xampp\htdocs\project\vendor\tcg\voyager\resources\views\formfields\relationship.blade.php)

![image](https://user-images.githubusercontent.com/10494470/34713153-5b74fd90-f536-11e7-90c0-d324f5e7e9e4.png)

**Comment by fletch3555** [comment]
Same issue: #2431 

Proposed fixes: #2432 #2433
