### ISSUE TITLE
Call to a member function relationLoaded() on null

### ISSUE THREAD

**Issue by nisargshh** [thedevdojo/voyager#2451]
- Laravel Version: 5.5
- Voyager Version: 1.0.0
- PHP Version: 7.1

### Description:
When going to http://localhost:8000/admin I get this error:
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Call to a member function relationLoaded() on null"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in C:\xampp\htdocs\celer\vendor\tcg\voyager\src\Traits\VoyagerUser.php:53

**Comment by namet117** [comment]
@5oClutch 
https://voyager.readme.io/docs/adding-the-service-provider

**Comment by nisargshh** [comment]
@name-T I have done that and I am still getting that error, I have a feeling it is because I have some extra columns for the user table.

**Comment by fletch3555** [comment]
What columns did you add to your users table? Also, please share your user model

**Comment by nisargshh** [comment]
User Model
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends \TCG\Voyager\Models\User
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role', 'server',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

User Migration
```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->string('password');
            $table->string('role')->nullable();
            $table->string('server')->nullable();
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
```

**Comment by nstaff** [comment]
Check and make sure that the users table has a role_id and that the role_id is not null. You will get this warning if the role_id field is null.

This often happens to me when I forget to reload the Voyager data tables after doing a fresh database migration.

**Comment by treb0r** [comment]
Same error here.

Laravel 5.5.32.

PHP 7.0.22-0ubuntu0.16.04.1

tcg/voyager (v1.0.14)

Installed Voyager and dummy data.

Fresh install, new app with no changes.

**Comment by treb0r** [comment]
I had an existing user in the users table.

`php artisan voyager:admin your@email.com`

Fixed it.

**Comment by GGH-Feldtmann** [comment]
removing the $with-attribute in the referenced model fixed this for me

**Comment by vafagh** [comment]
`"call ro a member function relationLoaded() on null"`
Laravel 5.5.33
PHP 7.1.13
Voyager  1.0.14
iPadAir iOS 11.2.1 

Had the same error for one time so far, catch on Safari. Try to repeat it, not doing it any more.
I have `@can('edit', $product)` on search result page. 
It happens on search with post method and keep showing on any URL until browser cache got wiped.
In a same time, same device chrome was able to open any page/login/session/search functionality ,...

**Comment by wwwebgainss** [comment]
It's because the permission tables are empty and there is no relation to permission_role. you have to rollback dummy data of voyager

**Comment by wwwebgainss** [comment]
You have to extend the database/seeds/DatabaseSeeder.php 

```
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->call(UsersTableSeeder::class);
        $this->call(VoyagerDatabaseSeeder::class);
        $this->call(VoyagerDummyDatabaseSeeder::class);
    }
}
```

**Comment by chouyang** [comment]
It's because there is no user with an 'admin' role in your database.
Simply update one of your users' role_id to 1 to become an admin will fix the problem.

**Comment by mtimbs** [comment]
Whenever I try to edit the admin email, profile image etc it automatically overrides the user.role_id to NULL. Does anyone know what is causing this?

**Comment by goldnetonline** [comment]
I know this is old but I made another discovery which I want to share.

If your application already implemented a login system and a user is already logged in, you will have to logout every user on your machine first as voyager will try to login with the logged in user who perhaps at that time you have not set the role_id of the user.

You can always go and logout and come back and login to voyager.

If you dont want to logout (you want to use the same user logged in to your frontend to login to voyager), locate the user in the database and change the role_id from null to 1.

Hope this helps someone.

**Comment by niphor** [comment]
I think
since  `user edit` page can set `Default Role` to `None`

the `loadPermissionsRelations` should check whether `$this->role ` is null or not first.

**Comment by master-saita** [comment]
> I know this is old but I made another discovery which I want to share.
> 
> If your application already implemented a login system and a user is already logged in, you will have to logout every user on your machine first as voyager will try to login with the logged in user who perhaps at that time you have not set the role_id of the user.
> 
> You can always go and logout and come back and login to voyager.
> 
> If you dont want to logout (you want to use the same user logged in to your frontend to login to voyager), locate the user in the database and change the role_id from null to 1.
> 
> Hope this helps someone.

Thank you from Russia! Your advise help me!

**Comment by shabbarabbas** [comment]
I was getting same error after i edit my user profile , after lots of search i find in my database user table `role_id` is set to null when i edit the profile , i just make an edit in PhpMyAdmin and set it to 1 that is administrator and the error goes away

**Comment by shabbarabbas** [comment]
but i do not know why it set my `role_id` to null on editing profile

**Comment by wishbone-productions** [comment]
Same here, after updating the admin user it deletes the user_roles and nulls the role_id. looks like the bug is reintroduced

php: 7.1.2
laravel: 5.8
voyager: 1.2.1

**Comment by raph-ael** [comment]
Same here after update to voyager 1.2.1

i do a quick fix by overwriting the `users/edit-add.blade.php` view and change this

```php
@can('editRoles', $dataTypeContent)
    <div class="form-group">
        <label for="default_role">{{ __('voyager::profile.role_default') }}</label>
        @php
            $dataTypeRows = $dataType->{(isset($dataTypeContent->id) ? 'editRows' : 'addRows' )};

            $row     = $dataTypeRows->where('field', 'user_belongsto_role_relationship')->first();
            $options = $row->details;
        @endphp
        @include('voyager::formfields.relationship')
    </div>
    <div class="form-group">
        <label for="additional_roles">{{ __('voyager::profile.roles_additional') }}</label>
        @php
            $row     = $dataTypeRows->where('field', 'user_belongstomany_role_relationship')->first();
            $options = $row->details;
        @endphp
        @include('voyager::formfields.relationship')
    </div>
@endcan
```

to this:

```php
    <div class="form-group">
        <label for="default_role">{{ __('voyager::profile.role_default') }}</label>
        @php
            $dataTypeRows = $dataType->{(isset($dataTypeContent->id) ? 'editRows' : 'addRows' )};

            $row     = $dataTypeRows->where('field', 'user_belongsto_role_relationship')->first();
            $options = $row->details;
        @endphp
        @include('voyager::formfields.relationship')
    </div>
    <div class="form-group">
        <label for="additional_roles">{{ __('voyager::profile.roles_additional') }}</label>
        @php
            $row     = $dataTypeRows->where('field', 'user_belongstomany_role_relationship')->first();
            $options = $row->details;
        @endphp
        @include('voyager::formfields.relationship')
    </div>

```

But this will only work if the logged in user has write access to roles table i think. So only a quick and dirty fix

**Comment by emptynick** [comment]
Did you follow the upgrade guide?
I think you missed one step there

**Comment by sineld** [comment]
Update your user bread and add **TCG\Voyager\Http\Controllers\VoyagerUserController** as user controller.

**Comment by wishbone-productions** [comment]
Perfect, that did the trick!
Thank you very much.

**Comment by emptynick** [comment]
That's pretty much exactly what's written in the upgrade guide. Please use it, that's why we write it.
