### ISSUE TITLE
Many to many -> Call to undefined method Illuminate\Database\Query\Builder::getRelationship()

### ISSUE THREAD

**Issue by a2aliyev** [thedevdojo/voyager#2453]
- Laravel Version: 5.1
- Voyager Version:1.0
- PHP Version:7.1
- Database Driver & Version: Mysql

### Description:
1) Create Many to many relationship 
2) When I tried to add data I got the erro -> Call to undefined method Illuminate\Database\Query\Builder::getRelationship()

![error](https://user-images.githubusercontent.com/9583510/34760928-2b832682-f5fb-11e7-889a-0c96bd948d01.png)
![relation](https://user-images.githubusercontent.com/9583510/34760929-2ba56350-f5fb-11e7-9b48-7f59aa653b28.png)

Could you please tell me why is this happening?
Could you also suggest solution to this problem?

Thanks in advance!!

**Comment by handiwijoyo** [comment]
Same issue: #2431

Proposed fixes: #2432 #2433

**Comment by a2aliyev** [comment]
Hi,

I have tried to add trait to the model that has many to many relationship. Error is still present. I am getting the same error.
![model](https://user-images.githubusercontent.com/9583510/34768953-baaaca8a-f615-11e7-887d-d5b5bbe6c338.png)
![trait](https://user-images.githubusercontent.com/9583510/34768954-bacd48ee-f615-11e7-97e6-567d461f2244.png)

**Comment by handiwijoyo** [comment]
Yes, there is already a PR for this, please wait for merge

**Comment by a2aliyev** [comment]
thanks

**Comment by a2aliyev** [comment]
tanks for the response

**Comment by sweetiefaithpaculanan** [comment]
Is this already fixed?

**Comment by fletch3555** [comment]
yes, please make sure you're using the latest release (v1.0.13)

**Comment by sweetiefaithpaculanan** [comment]
Finally it works fine now. Thanks @fletch3555!
