### ISSUE TITLE
Breadcrumbs are only working sometimes

### ISSUE THREAD

**Issue by Victor-emil** [thedevdojo/voyager#2456]
- Laravel Version: 5.5
- Voyager Version: 1.0.11
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
/admin/ is not being prepended to breadcrumbs. I see in #2376 that the newest version of Voyager is supposed to fix it. I just upgraded, but the issue remains. If I overwrite the navbar.blade.php code with code from an earlier commit from before the code was introduced it works again.  

### Steps To Reproduce:

Click users -> click edit on any user -> click on users in breadcrumbs.

Newest version of Voyager (1.0.11)

<img width="381" alt="users" src="https://user-images.githubusercontent.com/8555068/34784548-d8c43808-f62e-11e7-818e-43af23d31643.png">

<img width="826" alt="error" src="https://user-images.githubusercontent.com/8555068/34784584-f262d724-f62e-11e7-95c6-a707c99770f9.png">

Commit #2088 

<img width="415" alt="commit" src="https://user-images.githubusercontent.com/8555068/34784706-5384722e-f62f-11e7-80dc-23df36cb2670.png">

Seems like the fix to fix the error did not fix it. Unless I am missing some new configuration thingy.

**Comment by fletch3555** [comment]
What do you mean by "Commit # 2088"?  Are you intentionally linking to that issue, or was that github trying to be smart?

**Comment by Victor-emil** [comment]
Nope, it was just to link to a point in time where it was working. Sorry for the confusion. I can find the specific piece of code, which is of course in the file navbar.blade.php.

**Comment by Victor-emil** [comment]
Working now after I restarted my Mac and rebuilt the project. Sorry for the trouble!
