### ISSUE TITLE
Breads different on Local and Production Server and Seeding problem

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2458]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version:7.1.9

### Description:

Problem 1: 
Whenever I `migrate:refresh` the voyager does not seed complete data, which I have to enter manually every-time. Like `data_rows` and `permission_role` tables.

Problem 2:
If I create breads on my local server and then import db on production server. I have to change breads properties again as they reset to default. 

Any solution for these above problems ?

**Comment by fletch3555** [comment]
Voyager does not create migration or seed files for changes you make through the UI, so you are responsible for doing so (or choosing a different strategy).

Additionally, if you're running `migrate:refresh`, please note that Voyager's seeder is not called by default in the normal DatabaseSeeder class, so you'll need to add that yourself.

We have plans to implement this functionality in a future version, but haven't come up with a good way to do so yet.  For now, as I've said, these tasks will be on you to complete.
