### ISSUE TITLE
[Patch] Add posts thumbnail images to publishable/demo-content

### ISSUE THREAD

**Issue by handiwijoyo** [thedevdojo/voyager#2463]
The posts' BREAD has a Post Image field with additional option JSON.

```
{
    "resize": {
        "width": "1000",
        "height": "null"
    },
    "quality": "70%",
    "upsize": true,
    "thumbnails": [
        {
            "name": "medium",
            "scale": "50%"
        },
        {
            "name": "small",
            "scale": "25%"
        },
        {
            "name": "cropped",
            "crop": {
                "width": "300",
                "height": "250"
            }
        }
    ]
}
```

When trying to get the thumbnails of the dummy posts image, it will return 404, since the dummy posts didn't include thumbnails in demo-content folder. https://github.com/the-control-group/voyager/tree/1.0/publishable/demo_content/posts

**Comment by fletch3555** [comment]
Solution should be to generate the images and add them in as dummy content.  Open for pull requests

**Comment by cyrildewit** [comment]
It looks like this issue was fixed. Can someone confirm this too?

https://github.com/the-control-group/voyager/tree/1.1/publishable/dummy_content/posts

**Comment by emptynick** [comment]
No, those are the original images. But there are no generated thumbnails.

**Comment by cyrildewit** [comment]
Ahh, I'm working on it now.
