### ISSUE TITLE
First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2464]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9

### Description:
I am trying to make relationship between 2 tables. But when I choose drop-down as Input Type from bread settings, then I am unable to browse the bread.
Also I am trying to make a relationship between 2 tables for many hours but facing different errors. And unable to find any good tutorial or guide. Relationships in documentation are explained very brief.

**Comment by fletch3555** [comment]
It would be helpful if you shared the errors (with stacktrace) that you get

**Comment by marktopper** [comment]
Closed due to inactivity.

**Comment by gathuku** [comment]
clunky voyager

**Comment by gathuku** [comment]
am having the same issue
what could be the problem

**Comment by gathuku** [comment]
First parameter must either be an object or the name of an existing class (View: C:\laragon\www\shopnoma\vendor\tcg\voyager\resources\views\bread\browse.blade.php
