### ISSUE TITLE
[DOMAIN-NAME]/admin 302 redirects to [cloudfront origin]/admin/login

### ISSUE THREAD

**Issue by dj21d** [thedevdojo/voyager#2466]
- Laravel Version: 5.5.24
- Voyager Version: 1.0.9
- PHP Version: 7.1
- Database Driver & Version: psql

### Description:
We have deployed our laravel application to ECS and have set up SSL and LB with cloudfront. When we go to `https://domain.com/admin` the browser is redirecting us to `http://[cloudfront-lb-configname].amazonaws.com/admin/login`. I've attempted setting up the `APP_URL` but that is not working.

Is there a setting or variable I'm missing?

### Steps To Reproduce:
Open /admin page in production

**Comment by fletch3555** [comment]
Voyager simply redirects to your `voyager.login` route (ref: https://github.com/the-control-group/voyager/blob/1.0/src/Http/Middleware/VoyagerAdminMiddleware.php#L31)

This means your laravel and/or webserver configuration is incorrect.  Please run `artisan route:list` on the server to verify that the routes are correct (not requiring a specific domain).  Then verify that `APP_URL` is using your public domain and the `url` value in `config/app.php` doesn't have a specific entry (should be using `APP_URL`)

**Comment by dj21d** [comment]
Looks like everything is setup correctly
```
|        | GET|HEAD  | admin/login                                   | voyager.login                              | \TCG\Voyager\Http\Controllers\VoyagerAuthController@login                  | web                                          |
|        | POST      | admin/login                                   | voyager.postlogin                          | \TCG\Voyager\Http\Controllers\VoyagerAuthController@postLogin              | web                                          |
```
From app.config
```
'url' => env('APP_URL', 'http://localhost'),
```
Confirmed we have the following `.env` variable
```
APP_URL=http://testing.com
```

**Comment by dj21d** [comment]
It appears to be using absolute URLs by getting the domain from the http get Host header. Is there any way to make it so it's using relative routing?

**Comment by handiwijoyo** [comment]
Can you give us the detail about `"by getting the domain from the http get Host header"` ?

**Comment by fletch3555** [comment]
Cloudfront is supposed to be able to handle that.  In either case, we're just using laravel's functions to generate the URL, so it's most likely an issue with your webserver or laravel configuration.   It's possible there's something we could tweak, but at this point, I feel the onus is on you to figure out what that may be since this doesn't seem to affect anyone else.  I recommend starting with a Google search along the lines of "laravel behind load balancer incorrect domain"
