### ISSUE TITLE
Second page throws exception when filtering results (Server-side Pagination)

### ISSUE THREAD

**Issue by vstruhar** [thedevdojo/voyager#2468]
- Laravel Version: 5.5.21
- Voyager Version: v1.0.4
- PHP Version: 7.0.15-0ubuntu0.16.04.4
- Database Driver & Version: MySQL - 14.14 Distrib 5.7.17, for Linux (x86_64)

### Description:
When filtering on browse page for some resource and when I open the second page, I'm getting _"htmlspecialchars() expects parameter 1 to be string, array given"_ exception.

After some research, I found that  [$search->value](https://github.com/the-control-group/voyager/blob/e6af9a284d71f77c7e09a9e7bc27fdad69e5fdeb/resources/views/bread/browse.blade.php#L42) returns:
![image](https://user-images.githubusercontent.com/6599021/34823271-121af538-f6ca-11e7-9457-e40b080037db.png)

Here is the url:
../public/admin/schools?s%5Bvalue%5D=lap&s%5Bkey%5D=name&s%5Bfilter%5D=contains&page=2

Decoded get params: s[value]=lap&s[key]=name&s[filter]=contains&page=2

**NOTE:** ~~there is no exception on PHP 7.1.7-Win32-VC14-x64, everything is working as expected.~~ (found out that it worked because I had voyager 1.0.10 on local env)

### Steps To Reproduce:
1. Set "Server-side Pagination" for some resource
2. Browse that resource and search by some field (example set name, contains, "a")
3. Go to the second page
4. Exception is thrown

**Comment by emptynick** [comment]
This has been fixed in [1.0.9](https://github.com/the-control-group/voyager/releases/tag/v1.0.9)

**Comment by vstruhar** [comment]
[Updated](https://voyager.readme.io/docs/1-to-1) to 1.0.12 and it is working now.
Thank you for your quick response.
