### ISSUE TITLE
Add code editor

### ISSUE THREAD

**Issue by P9Q** [thedevdojo/voyager#2469]
It would be great if you add a code editor to voyager, so the user can edit Models, Controllers etc directly from Voyager, following code editors, are open-source and available on Github:

[ACE](https://github.com/ajaxorg/ace)
[CodeSandbox](https://github.com/CompuIves/codesandbox-client)

Many [projects ](https://ace.c9.io/#nav=production)use ACE as their code editors, it also has dark themes.

There is a similar project [LAEditor](https://github.com/dwijitsolutions/laeditor), also watch this  [screenshot](http://laraadmin.com/img/laraadmin/laraadmin-online-code-editor.jpg) and [video](https://www.youtube.com/watch?v=emo9qmS_Q3s)

**Comment by fletch3555** [comment]
I don't see this happening anytime real soon, but I'm open for PRs if someone wants to tackle it.  I make no promises on when it would be merged in

**Comment by MrCrayon** [comment]
There is currently no plan to implement this.
In order to prioritize issues we can act upon we are closing this.
