### ISSUE TITLE
many to many relation

### ISSUE THREAD

**Issue by a2aliyev** [thedevdojo/voyager#2470]
- Laravel Version: 5.5.1
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:mysql

### Description:
I have successfully created many to many relation between image<->gallery. When I try to remove relation between elements in edit mode, voyager does not remove. 

Can some one tell me what is going on with the voyager? 

thanks

**Comment by Light-Studio** [comment]
In many to many relation you have to detach the relation before deleting, 
I've find a solution but i don't know if it's the best way to do it cause i'm kinda new to web development !

Anyway, In my case i use the many to many for making a tags system in my  posts,
First of all I had to change a line in the relationship.blade.php to make it work, you can see how todo it here #2383 

Now for the deletion : 
You'll need to create 2 models one for the posts name 'Post' and an other for the tags name 'Tag'
copy paste the content of the Voyager Post Model in your Post model (/vendor/tcg/voyager/src/Models/Post.php)

and add at the end : 

```
public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }
```

and add to that to the Tag model
```
     public function posts()
    {
        return $this->belongsToMany('App\Post');
        
    }
```
now make a new controller and copy paste the content of the voyager bread controller in it,
there the path to find it  ( /vendor/tcg/voyager/src/Http/Controllers/VoyagerBreadController.php)

Then go in your controller to the line 370 and put that in it

```
if ( $slug == 'tags' ) {
        $tag = Tag::find($id);
        $tag->posts()->detach();}
        
 if ( $slug == 'posts' ) {
        $post = Post::find($id);     
        $post->tags()->detach();}
```

 (I use the slug to verify my condition, if someone find a better way i'll take it ! :P ) 

it should give you something like that : 

```
        $displayName = count($ids) > 1 ? $dataType->display_name_plural : $dataType->display_name_singular;
        
        if ( $slug == 'tags' ) {
        $tag = Tag::find($id);
        $tag->posts()->detach();}
        
         if ( $slug == 'posts' ) {
        $post = Post::find($id);     
        $post->tags()->detach();}
        
        $res = $data->destroy($ids);
        $data = $res
```


after that you have to specified in the voyager bread manager that you want to use the new controller and models for both of the tables, Posts and tags in my case. 
It did the work for me !
Hope this will help you !

**Comment by a2aliyev** [comment]
I have an Image table and Image table have more than one 'belongstoMany' Relation. I do not think that it would solve the problem in my case.

I can add relation easily to the pivot table. when i try to remove it does not remove anything from the pivot table. BTW, pivot table does not have id because it gives conflict error so I removed the id from the pivot table

**Comment by fletch3555** [comment]
Calling `->detach()` is what deletes the entry from the pivot table.  You could also set your foreign key relation in your database as `ON DELETE(CASCADE)`, which should also delete it

**Comment by a2aliyev** [comment]
Thank you guys for the reply. But I used different approach which you can access from this link:
https://github.com/the-control-group/voyager/issues/2355
