### ISSUE TITLE
Custom breadcrumbs

### ISSUE THREAD

**Issue by mmickelson** [thedevdojo/voyager#2471]
- Laravel Version: 5.4.36
- Voyager Version: #.#.#
- PHP Version: 7.0
- Database Driver & Version:

### Description:
The breadcrumbs should be more customizable, allowing for going deeper. An example:
I have an application where I have batches of licenses and would like to handle the heirarchy in the breadcrumbs correctly. Here's the goal: I would like to browse the batches, which would show Dashboard > Batches. I click to View batch 5 so the breadcrumbs would show Dashboard > Batches > 5. Viewing batch 5, I see a list of licenses associated with that batch. I click on license 5IX5I-HCQW9-8Y3UI-XTHU3-B07E9 (id 12) and the breadcrumbs then show Dashboard > Batches > 5 > 5IX5I-HCQW9-8Y3UI-XTHU3-B07E9 or at least Dashboard > Batches > 5 > 12 if it uses ids.

Being able to drill down deeper and also to define what shows in the breadcrumbs is the goal.

I'm able to make routes that will show a license when going to /batches/5/5IX5I-HCQW9-8Y3UI-XTHU3-B07E9 so ideally, the breadcrumbs would just be a copy of the url segments. Editing the license key would be at /batches/5/5IX5I-HCQW9-8Y3UI-XTHU3-B07E9/edit so the breadcrumbs would show Dashboard > Batches > 5 > 5IX5I-HCQW9-8Y3UI-XTHU3-B07E9 > edit.

### Steps To Reproduce:
Create a one-to-many relationship and view the breadcrumbs created when making an admin. In order for it to work, the above example ends up being shown as Dashboard > Licenses > 12, eliminating the Batches parent from the breadcrumbs and implying the user could go to Licenses to see ALL licenses, which is not the case.

**Comment by fletch3555** [comment]
That's too specific of a use-case for Voyager.  You'll need to create that yourself.

**Comment by mmickelson** [comment]
If you're referring to the example I gave, I agree. But cases where there are models and one to many relationships with other models, I would say that happens all the time. I used the example to explain the problem but maybe I should be more generic (and hope it's understood)?

This comes from this forum post: https://devdojo.com/forums/discussion/introductions/custom-breadcrumbs
