### ISSUE TITLE
can't install my voyager,need for assistance

### ISSUE THREAD

**Issue by Uncle11Drew** [thedevdojo/voyager#2473]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
 requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager v1.0.0 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.1 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.10 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.11 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.12 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.2 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.3 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.4 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.5 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.6 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.7 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.8 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - tcg/voyager v1.0.9 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1].
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.4.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by Uncle11Drew** [comment]
How can I fix this problem?..I really need this for project.

**Comment by fletch3555** [comment]
1. We require all version numbers be provided
2. Did you read the error message? Hint: your system is missing something, and it tells you what

**Comment by Uncle11Drew** [comment]
I got it installed sir..thanks for the help..I salute you sir!
