### ISSUE TITLE
Unable to delete last BelongsToMany relation in BREAD

### ISSUE THREAD

**Issue by anbulanov** [thedevdojo/voyager#2476]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.12
- PHP Version: 7.0.23
- Database Driver & Version: Server version: 5.7.18-16 Percona Server (GPL), Release 16, Revision d7301f8

Description:
Bug. It is impossible to delete last BelongsToMany relation between objects using BREAD.
The one row in pivot table always stay.

Steps To Reproduce:
1. Create table Items ( id, name, created_at, updated_at)
2. Create table tags (id, name, created_at, updated_at)
3. Create pivot table  item_tags (item_id, tag_id)
4. Create BREAD for Items
5. Create BelongsToMany relation in items BREAD
6. Add one  item and  add tag to that item 
8. Edit item and try to delete tag

Voyager shows a Sucess result, but - the tag was not remove.

**Comment by nstaff** [comment]
Same issue for me. 

Laravel Version: 5.5.32
Voyager Version: 1.0.14
PHP Version: 7.1.10
Database Driver & Version: MariaDb 10.x

Can delete all but the last one.

**Comment by Smocrate** [comment]
Same issue with manyToMany and pivot_table
Can't delete all tags in fields. When you same with 0 tag pivot_table don't update.

**Comment by vvvkor** [comment]
Same issue. Can not delete the last pivot record.

- Laravel Version: v5.6.28
- Voyager Version: v1.1.3
- PHP Version: 7.1.8
- Database Driver & Version: PostgreSQL 9.2.23

**Comment by emptynick** [comment]
Fixed in #3016.
Merged into 1.x
