### ISSUE TITLE
Viewing of pdf or word view only(no download)

### ISSUE THREAD

**Issue by cmancuyas** [thedevdojo/voyager#2479]
- Laravel Version: 5.5.28
- Voyager Version: 1.0
- PHP Version: 7.1.4
- Database Driver & Version:

Hi guys, how can I get a role wherein a user(not admin) cannot download(but the user can view) the pdf or word that is uploaded in the media?

### Steps To Reproduce:
upload a file in the media then view using any user account

**Comment by fletch3555** [comment]
That won't be possible within Voyager.  Browsers handle the display of files, meaning the file will have already been downloaded to the user's machine.  The browser may choose to open a PDF, or another application can do so.  Word files, however, are almost always opened by Word.  What you'd need is a viewer for those files that loads the file and displays it in a browser iframe or something.  This is much too specific for Voyager to build into its core, but you're certainly welcome to build it yourself (I recommend building it as a Hook so others can benefit from it as well).
