### ISSUE TITLE
Each folder in the media can be assigned to a role

### ISSUE THREAD

**Issue by cmancuyas** [thedevdojo/voyager#2480]
Laravel Version: 5.5.28
Voyager Version: 1.0
PHP Version: 7.1.4
Database Driver & Version:

### Description:
Suggestion: I want other users not to see my folders or I can see the folders of other users

**Comment by fletch3555** [comment]
We're working on a complete rewrite of how the media is handled and will take this request under advisement.

**Comment by emptynick** [comment]
This will be possible in version 1.2.
See (https://github.com/the-control-group/voyager/pull/3889).
