### ISSUE TITLE
belongsToMany - Extra Pivot Column

### ISSUE THREAD

**Issue by belthaZornv** [thedevdojo/voyager#2481]
- Laravel Version: 5.5.*
- Voyager Version: ^1.0
- PHP Version: 7.0.22
- Database Driver & Version: Not relevant

### Description:

I'm not too sure if this is supported or not, I've tried voyager for a few hours now, and it's awesome so thank you for that, it's unbelievable work, congrats. 

back to the issue, I would love to achieve this example scenario:

User:
- id
- name

Country:
- id
- name

Rating:
- id
- name

Now having these three simple models, I would love to reuse a rating that user can relate to a country. - I'd automatically go for something like:

UserCountry:
- user_id
- country_id
- rating_id

This would mean that an intermediate table acts as an intermediate table for more than two tables, yes. - how would you recommend me going about doing this? and would you recommend me doing this in another way? - I would love to have an option so when I select a country, I have an extra field to select the rating etc.

**Comment by vonec** [comment]
im stuck with a similar scenario too .. any luck on this ?

**Comment by belthaZornv** [comment]
@vonec I did extend voyager to do something similar and it works quite well; you can find it here (maybe you can pick certain things from it and make it work properly for yourself) https://github.com/belthaZornv/voyager/tree/with-pivot-relationships

I've continued to add on top of that but it's in a private repo. - The idea behind it is that when you add a belongsToMany relationship you can specify additional options in JSON and say that there's an extra column etc.

**Comment by MrCrayon** [comment]
You only need to customize your view and pass data in the correct format then Voyager will save any extra pivot parameters automatically since it uses sync.
https://laravel.com/docs/7.x/eloquent-relationships#updating-many-to-many-relationships

There is currently a bug on saving fixed in #4937 that will be released with v1.4.2
