### ISSUE TITLE
Unable to store lists in db

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2484]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9
- Database Driver & Version: 10.1.26-MariaDB

### Description:
I want to store a list in my table but when I selected data type as text. Then it shows me Array to string conversion error. 
So I tried to make data type Json but then I faced this error.
Error:
> generic.exception: An exception occurred while executing 'ALTER TABLE institutes CHANGE courses courses json DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json DEFAULT NULL' at line 1

Suggest any fix plz ?

**Comment by emptynick** [comment]
JSON type is only supported from MariaDB version `>= 10.2`
