### ISSUE TITLE
Responsive embed youtube videos in posts

### ISSUE THREAD

**Issue by Light-Studio** [thedevdojo/voyager#2485]
- Laravel Version: 5.5
- Voyager Version: 1.0.13
- PHP Version:7.2

Hi Evreyone,

I'm just sharing a little tweek if you want to have responsive youtube videos in your front-end application:

to do so, go to the /public/vendor/tcg/voyager/assets/js/plugins/youtube/js/youtube.js
file at the line 203 and replace it by 

```ruby 
var sHTML = '<div class="videoiframe"><iframe title="' + sTitle + '" width="' + $('#widthURL').val() + '" height="' + $('#heightURL').val() + '" src="' + sEmbedUrl + '?wmode=opaque&theme=' + $('#skinURL').val() + '" frameborder="0" allowfullscreen></iframe></div>';
```
basically, it just wrap the iframe with a div and a  "videoiframe" class.

now you have to add this to your style sheet :

```ruby
.videoiframe {
float: none;
clear: both;
width: 100%;
position: relative;
padding-bottom: 56.25%;
padding-top: 25px;
height: 0;
}
.videoiframe iframe {
position: absolute;
top: 0;
left: 0;
width: 100%;
height: 100%;
}
```

This will only work on new posts. you'll have to go in the old ones, remove the video and put it again if you want this to work.

Also this will make the height and width sliders useless cause the video will take up all the space it can, I've try to find a solution but it didn't work as attended. If you find a fix please share it :)

Hope it will help some of you !

**Comment by Eduruiz** [comment]
hey @Light-Studio thanks for your idea.
also, there is a missing `;` in the `float: none`.

and you can (if using bootstrap) tweak your suggestion a little to use responsive iframe with aspect ratio from [bootstrap css utilities](https://getbootstrap.com/docs/4.0/utilities/embed/).

**Comment by Light-Studio** [comment]
I did not know about the bootstrap class "embed-responsive" It's even better ! Thanks @Eduruiz
