### ISSUE TITLE
Getting badmethodcallexception

### ISSUE THREAD

**Issue by abhishek003ite** [thedevdojo/voyager#2486]
- Laravel Version: 5.5.x
- Voyager Version: 1.0
- PHP Version: 7.0.0
- Database Driver & Version: mysql & 5.7.x

### Description:
I have created 2 database tables using database tools named countries and states and make a relationship between both of them and I am successfully able to add master table means countries table but when I am trying to add any of the state and make a relation between any of the country it is giving error badmethodcallexception. Please find the below relationship and error shot attached.
The data is getting added into database when I am trying to call create method directly it is getting added into database but when I am trying to access list view for states it is giving this error. Please support.
![screenshot 2018-01-14 20 41 42](https://user-images.githubusercontent.com/6541798/34917379-87d96cf2-f96b-11e7-9990-deb09dbd560f.png)
![screenshot 2018-01-14 20 36 50](https://user-images.githubusercontent.com/6541798/34917383-924f140c-f96b-11e7-9ea6-1355f0231d24.png)
Please suggest any way.

**Comment by fletch3555** [comment]
Specifically what version if Voyager are you on? 1.0.[???]. There was a fix for this in one of the recent releases. Please try updating

**Comment by abhishek003ite** [comment]
Thanks Fletch3555. Resolved.
