### ISSUE TITLE
Question: How to set default style for Table in Rich Text Editor

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#2488]
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1.9

### Description:
How can I set the default style for table in rich text editor ?
Check SS for better understanding: http://prntscr.com/i0fz7i

**Comment by Light-Studio** [comment]
I think you'll have to edit the /public/vendor/tcg/voyager/assets/js/plugins/table/plugin.js
in order to make a default style, 

The rich text editor is called TinyMCE,
here's the documentation on this subject :
https://www.tinymce.com/docs/plugins/table/

good luck in your recherche !
