### ISSUE TITLE
sorting a list in laravel voyager

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2490]
hi im trying to sort my list but i cant get this part of code working

@foreach($fsliders->sortBy('id','desc') as $slide)

all i get is this error 
"asort() expects parameter 2 to be integer, string given"

if their is a manual about queries for laravel voyager please comment the link

thank you

**Comment by emptynick** [comment]
I dont know what you are trying to sort, wether Models or something else.
In both cases its a Laravel thing.
Collections:
https://laravel.com/docs/5.5/collections#method-sortbydesc
Or for eloquent
https://laravel.com/docs/5.5/eloquent#retrieving-models

**Comment by darkhunter32** [comment]
i did the same thing as in this tutorial 
https://devdojo.com/blog/tutorials/working-with-voyager-on-the-front-end
i just replaced posts by another tables and now i need to sort the rows i get by their id

**Comment by ghost** [comment]
thank you it was 
sortByDesc()
