### ISSUE TITLE
Retrieving thumbnails for Multiple Images!

### ISSUE THREAD

**Issue by mohdabbas** [thedevdojo/voyager#2491]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.11
- PHP Version: 7.1.8
- Database Driver & Version: MariaDB

### Description:
I want to display first image from multiple images, but want to display the thumbnail. How can I do that? Here is my code:

```
@foreach($products as $product)

                  <?php $jsonimages = json_decode($product->images, true); ?>
                  <!-- Shop Product -->
                  <div class="col-xs-12 col-sm-6 col-lg-4 mb-30">
                    <div class="shop-product-card">
                      <!-- Image/Slider -->
                      <div class="product-image-wrapper">
                        
                        <!-- Product Main Image -->
                        @foreach($jsonimages as $ji)
                        <div class="shop-p-slider">
                          <a href="{{ $product->id }}"><img src="{{Voyager::image($ji)}}" alt="{{ $product->name }}"></a>
                        </div>
                        @break
                        @endforeach
                      </div>

                      <!-- Product Meta -->
                      <div class="product-meta">
                        <a href="product-detail.html"><h4 class="product-name">{{ $product->name }}</h4></a>
                      </div>

                    </div><!-- / .shop-product-card -->
                  </div><!-- / .col-sm-3 -->
                  @endforeach
```

Model:
```
namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Resizable;

class Product extends Model
{
    use Resizable;
}
```

It's written in voyager documentation to do 

```
@foreach($posts as $post)
    <img src="{{Voyager::image($post->thumbnail('small'))}}" />
@endforeach
```

But that's for single... what's the procedure for multiple images! When I print $product, there is no thumbnail in the output as well!

Kindly help!

**Comment by mohdabbas** [comment]
If i do 
{{$ji->thumbnail('small')}}

I get the error "Call to a member function thumbnail() on string"

**Comment by emptynick** [comment]
As described here:
https://voyager.readme.io/docs/thumbnails-url
You need to implement the Trait in your model

**Comment by fletch3555** [comment]
@emptynick, that won't work.  The thumbnails method works by getting a single field's value, then converting it.  If the field holds an array, such as in this case, it won't work.

**Comment by emptynick** [comment]
True.
I didnt look that close at it to be honest.
In that case the Trait will still show you how its done:
```
// We need to get extension type ( .jpeg , .png ...)
$ext = pathinfo($image, PATHINFO_EXTENSION);

// We remove extension from file name so we can append thumbnail type
$name = rtrim($image, '.'.$ext);

// We merge original name + type + extension
return $name.'-'.$type.'.'.$ext;
```

**Comment by mohdabbas** [comment]
@emptynick Yes I implemented the same way but using explode! 

Trait only works for a single record. Voyager needs to add more info regarding multiple images in the documentation :-)!
