### ISSUE TITLE
Slug has trailing hyphen when title ends in hyphen

### ISSUE THREAD

**Issue by BlakeBeus** [thedevdojo/voyager#2493]
- Laravel Version: 5.5.x
- Voyager Version: 1.0.x
- PHP Version: 7.x
- Database Driver & Version: Not relevant

### Description:
When using slugify to turn a title into a slug, if the title has punctuation at the end they slug will have a trailing `-`

#### Example: 
**Title:** *How much do you know about cryptocurrency?*
**Slug:** *how-much-do-you-know-about-cryptocurrency-*

### Steps To Reproduce:
See above.

**Comment by emptynick** [comment]
Fixed in #2830
