### ISSUE TITLE
Upload multiple images in different registers

### ISSUE THREAD

**Issue by piterog** [thedevdojo/voyager#2498]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: - 

### Description:
I have a 'blogs' and 'blog_photos' tables, there's a way to upload multiple images in a different rows?
If I use Multiple Images choice, the Voyager tries to save all of photos in one register.

Problem Ex:

SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255) (SQL: insert into "blog_photos" ("blog_id", "image", "updated_at", "created_at") values (1, ["blog-photos\/January2018\/GafEp6I5fbUrNWKUHTiy.jpg","blog-photos\/January2018\/PO2JOWQQHxSmVI1fxI1B.jpg","blog-photos\/January2018\/oERW04OPJWOOdG6lwGXT.jpg","blog-photos\/January2018\/bf4uNDguyl2F9P0GrZzU.jpg","blog-photos\/January2018\/Oldcg9PEao9etmi1Fra1.jpg"], 2018-01-17 01:57:19, 2018-01-17 01:57:19) returning "id")

**Comment by emptynick** [comment]
Your problem is, that column `image` is varchar. It should be `text` for multiple images.
And I don't understand your other questions.

**Comment by fletch3555** [comment]
Varchar is perfectly acceptable, but 255 is too short. Change your field length.  Unfortunately, it's difficult (or impossible) to predict how long that data will get, so you'll have to make a reasonable guess or simply make it way bigger than necessary (~~100000 or something crazy~~).

We're planning to completely rewrite how Voyager handles media in a later version, but that project hasn't been started yet.  It will resolve this issue though

Edit: don't use a crazy high number, or just use TEXT instead.  Ref: https://dev.mysql.com/doc/refman/5.7/en/column-count-limit.html
