### ISSUE TITLE
Can't translate "file" and "images"

### ISSUE THREAD

**Issue by francescomugnai** [thedevdojo/voyager#2501]
- Laravel Version: 5.5.x
- Voyager Version: 1.0.13
- PHP Version: 7.x
- Database Driver & Version: Not relevant

### Description:

I can't correctly save multilingual file and images (all the other fields work like a charm).
Let's say you have 3 languages: en, es, it.
If you upload a file on the english page than you will see the same file in all the other languages too.
Then, if you upload another file on the spanish page you will overwrite the english one.
And, yes, i used the Translatable trait.

Please, I really need to fix this problem because i've to ship a new project.

### Steps To Reproduce:

1) Enable multilanguage.
2) Create a new multilingual page and choose to upload a picture or a file
3) That file (or image) will be saved just on the table of the main language but not on the "translations" table.

**Comment by sebastianjung** [comment]
Any solutions to this?

**Comment by fletch3555** [comment]
Voyager does not (currently) support multilingual files and images

**Comment by sebastianjung** [comment]
ok thanks anyway!

**Comment by Akopean** [comment]
@fletch3555 Why do not you want to separate the work with the files from the main form?. And it will be possible to download pictures from the media site and the ability to easily support multilingual functionality
