### ISSUE TITLE
showing field in bread based on the page slug

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2502]
hi 
as the title suggests im looking for a way to show a field based on the page slug 
example i have a field called field_s i want it to appear when im editing page X but i want it hidden when i edit other pages.
thank you in advance

**Comment by fletch3555** [comment]
This is not a supported feature of Voyager.  For individual assistance with custom functionality, please join our Slack group and post in the #help channel.

Also, All fields are required when submitting issues to our repository.  Please use the template as it's intended: https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE
