### ISSUE TITLE
cant upload files 

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2504]
hi 
i have a file filed in my bread but when i try to upload a file i get
"fopen(...\public): failed to open stream: Permission denied"

when i try to upload it from the media manager i get the file does not exist
i already tried chmod 777 on both the public folder the storage and the bootstrap/cache but still it doesnt work

**Comment by fletch3555** [comment]
This is definitely not a Voyager issue.  This is a Laravel and system configuration issue.  I recommend asking for help in the Larachat Slack group.  You could ask in our Slack group's #help channel, but there's no guarantee we'll be able to help there.  Larachat is full of people knowledgeable in laravel and server management, especially in the #servers chat.

Also, please note that all fields are required when submitting issues to our repository.  Please use the template as it's intended: https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE
