### ISSUE TITLE
Nested dropdowns when adding a new record

### ISSUE THREAD

**Issue by douglasroos** [thedevdojo/voyager#2506]
- Laravel Version: 5.5.31
- Voyager Version: 1.0.13
- PHP Version: 7.2.0
- Database Driver & Version: MySQL 5.7.20

### Description:

I have a table named products which contains a INT field named province_id, I also have 3 more tables States, Cities and Provinces, Provinces belongs to Cities and Cities belongs to States.

I want to store the Province ID in the products table but I need to show in the editor the other 2 dropdowns, I mean State dropdown, onchange load a second dropdown with Cities, onchange select a third dropdown with Provinces, this is the one that will be saved in the database.

My question is, can I achieve this using the built in BREAD or do I need to override that view and create that code myself?

**Comment by fletch3555** [comment]
Voyager provides no means for making fields dependent on other fields, so you'll have to make that yourself.  Voyager CAN however populate the dropdowns for any fields that don't depend on the value of another, which should simplify your work a little.
