### ISSUE TITLE
Add/Edit value doesn't update on Relationship Belongs To

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2507]
- Laravel Version: 5.5
- Voyager Version: 1.0.14
- PHP Version: 7.0
- Database Driver & Version: NA

### Description:
When you create a realationship "belong to" and try to edit the record the realation field doesn't update. 

### Steps To Reproduce:
1. Create a realationship belong to
2. Add or Edit a record
3. Change the relation value (on select2)
4. Save 
5. The value doesn't update

**Comment by IProSoft** [comment]
Hi, temporary fix:
https://voyager.readme.io/v0.11/docs/relationships, You must use new and old way of definig relations.

**Comment by nquillet** [comment]
Hi,

I had the same issue today, this worked for me:
You must leave the base field active and select input "Select Dropdown"

Bad : 

![image](https://user-images.githubusercontent.com/31613077/35687959-6398b63c-0770-11e8-8226-a18b6fffce49.png)


Great:

![image](https://user-images.githubusercontent.com/31613077/35687917-441c0b88-0770-11e8-83ab-2952a2429abd.png)

Hope this help

**Comment by bmisanthropy** [comment]
@nquillet thank you.

**Comment by acrevola** [comment]
@nquillet 's solution is fine. It works also for us. Please fix it in next release (or update your documentation)

**Comment by emptynick** [comment]
The default selected type is now text, so this isn't a problem anymore.
Ref https://github.com/the-control-group/voyager/pull/2837 (1.x-dev)

**Comment by poncianodiego** [comment]
Hello @emptynick,

Unfortunately, this is still happening for me. 

Laravel version 5.6
Voyager Version ^1.1
PHP version 7.2 on Laravel Homestead

**Comment by poncianodiego** [comment]
I have tried adding the base relationship field as Text as Select Dropdown and even as number and it is not updating correctly

**Comment by poncianodiego** [comment]
Never mind, I just noticed the base field must be "checked" for read and edit views

**Comment by emptynick** [comment]
That is absolutely correct.

**Comment by ranjitWBS** [comment]
aww @nquillet this is awesome!

**Comment by niklaz** [comment]
@nquillet, this approach worked! Thanks
