### ISSUE TITLE
Unable to change the order of the List in the Group Dropdown while creating Access Code

### ISSUE THREAD

**Issue by venukommu** [thedevdojo/voyager#2508]
- Laravel v5.5.32
- Voyager v1.0.14
- PHP v7.1.11

Hello,
We are trying to change the order of the list in the Group Dropdown while creating the Access Code. We would like to show the values by latest/recently created as first in the Dropdown. We tried to change the relationships in the BREADs. But didn't work as expected. 

Please find the attached screen for more information. Appreciate your quick help. By the way very new with Laravel Voyager.

https://lh3.googleusercontent.com/-KtIRkL7iQHY/WmCV5x2qkRI/AAAAAAAAsfs/MlqXEV7beMI3xKyx8L87f_Mg182l47smQCL0BGAYYCw/h900/2018-01-18.png

![image](https://user-images.githubusercontent.com/31344811/35180725-7182fae4-fddb-11e7-9b34-dad46650f43b.png)

Thanks & Regards
Venu Kommu

**Comment by venukommu** [comment]
I would like to add some more information about the issue we are talking. So that you can understand the issue first. Please find the following attached image.

Here you can find the Dropdown for groups. Values in the Dropdown being displayed in the ascending order of the created date, but we would like display those values as latest first based on created date like descendant order.

We have tried to change the BREAD and views, but didn't work anything.

![image](https://user-images.githubusercontent.com/31344811/35180763-4f9108bc-fddc-11e7-9f27-d4b758265d00.png)

Appreciate your help
Thanks in Advance
Venu Kommu

**Comment by MrCrayon** [comment]
In the last release 1.3.1 you can override relation method in VoyagerBaseController to order that list in a different way.

If you have further question please ask in Voyager Slack group.
