### ISSUE TITLE
How do i get those panels?

### ISSUE THREAD

**Issue by NXDChen** [thedevdojo/voyager#2513]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Need alot of columns so this looked like a good way to sort them. Dont know where i can add them.

![screenshot_8](https://user-images.githubusercontent.com/33622926/35172777-4ac11a20-fd69-11e7-9d5d-c1d56db3a0e2.png)

**Comment by fletch3555** [comment]
https://github.com/the-control-group/voyager/blob/1.0/resources/views/posts/edit-add.blade.php#L179
