### ISSUE TITLE
Edit-add view

### ISSUE THREAD

**Issue by NXDChen** [thedevdojo/voyager#2514]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I'm new at this
Where can i find the edit-add view after creating a BREAD of a specific table?

**Comment by emptynick** [comment]
Theres no special edit-add view generated for your Bread-Type.  
Instead it uses a generic view you can find in `resources/views/bread/edit-add.blade.php`  
If you want to use a custom view see [Overriding Package Views](https://laravel.com/docs/5.5/packages#views)

**Comment by fletch3555** [comment]
@NXDChen, please note that all version numbers are required when submitting issues.  If your question is a general "how do I...?" question, then it's likely better asked in our Slack group's #help channel.
