### ISSUE TITLE
Voyeger BREAD page slow when loading database table with over 130 records

### ISSUE THREAD

**Issue by tunapiq** [thedevdojo/voyager#2515]
- Laravel Version: 5.5.#
- Voyager Version: 1.0.#
- PHP Version: 7
- Database Driver & Version:

### Description:
It takes forever to load a BREAD page with over 130 records. the problem is most likely due to javascript

### Steps To Reproduce:
add over 130 records to your database table and visit the bread page linked to that table

**Comment by tunapiq** [comment]
Never mind I found a button to use server side pagination in the edit BREAD page, that fixed it. Thanks!

**Comment by nguyenhuu1404** [comment]
share for me, please

**Comment by cbascordoba** [comment]
![image](https://user-images.githubusercontent.com/29434321/61224933-2e899180-a6e5-11e9-8cc4-01d422a8b251.png)
