### ISSUE TITLE
Undefined offset: 3

### ISSUE THREAD

**Issue by furqan99** [thedevdojo/voyager#252]
- Laravel Version: 5.3.*
- Voyager Version: 0.9.*
- PHP Version:5.6.24
- Database Driver & Version:libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $

### Description:
i am facing problem during the create table with time stamp  fileds its return error " Undefined offset: 3"

**Comment by marktopper** [comment]
We need to know the specific version of Voyager in order to help, since so many things have been done in `v0.9`.

**Comment by furqan99** [comment]
version of Voyager :0.9.34

**Comment by marktopper** [comment]
Can you please show the full error and stacktrace?

**Comment by furqan99** [comment]
ErrorException {#302 ▼
  #message: "Undefined offset: 2"
  #code: 0
  #file: "C:\Users\hp\Desktop\projects\DramaWebsite\vendor\tcg\voyager\src\Http\Controllers\Traits\DatabaseQueryBuilder.php"
  #line: 136
  #severity: E_NOTICE
  -trace: {▶}
}

**Comment by tomastrusik** [comment]
The same problem. When I add timestamp field I will get error"Undefined offset: "

PHP: 5.6.10
Voyager: 0.9.34

**Comment by allenjd3** [comment]
I think this may be fixed with #258 - it was merged in recently

**Comment by yhif** [comment]
Modify the **edit-add.blade.php** file to line 263 

`$('#' + unique_id).find('.fieldType').val('timestamp').attr('readonly', 'readonly').attr('disabled', 'disabled');`

Remove the disable attribute, replace with

`$('#' + unique_id).find('.fieldType').val('timestamp').attr('readonly', 'readonly');`

**Comment by furqan99** [comment]
@yhif can you please guide  how I fill out select drop down with the other table data??

**Comment by yhif** [comment]
@furqan99 Sorry, I have not tried.

**Comment by allenjd3** [comment]
#258 addresses this
