### ISSUE TITLE
change date before save in database

### ISSUE THREAD

**Issue by aliayoubi** [thedevdojo/voyager#2523]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
hi how can i chage date befor save my date is shamsi i want to convet to miladi befor save to database.
where can i put my convertor code befor saveing 
thank for hellping

**Comment by fletch3555** [comment]
Voyager just uses Laravel functions and Eloquent models.  This question is not specific to Voyager, and is better asked in a more generic medium, such as LaraChat or Laracasts forums.
