### ISSUE TITLE
Create custom Controller, View 

### ISSUE THREAD

**Issue by a2aliyev** [thedevdojo/voyager#2529]
- Laravel Version: 5.5
- Voyager Version:latest
- PHP Version: 7.1
- Database Driver & Version:MySql

### Description:
I have **images** table where I store images(path) and **media**, **gallery**, **news**, **brochures** table which hold one or more than images via voyager relationship. I created belongs to many relationship for each of **media**, **gallery**, **news,** **brochures** on images table. When I want add new image I have to go to images table upload image then connect with the appropriate data.

This is totally useless and not user friendly.

 -Is there any way that still hold on to the images table to store images in single place but visually change other tables so that when I open that tab on voyager images appear there and still being able to delete edit and add images???

-Could you please suggest some kind of solution or opinion towards solving the issue?

**Comment by defaultpage** [comment]
Hi! Custom controller we can set in bread settings. If you want to set custom view for your bread (table), you need create file like:
```
./resources/views/vendor/voyager/clients/browse.blade.php
```
where `clients` is the bread, `./` -- project folder. You can change `browse` to `read` or `edit-add` too.
<details>
  <summary>Example</summary>

![resources/views/vendor/voyager/clients/browse.blade.php](https://habrastorage.org/webt/gq/lp/zb/gqlpzbozb-dtuvxmbcadtkxikqw.png)
</details>

**Comment by fletch3555** [comment]
This would all be custom, not directly possible from within voyager, so I can't provide step-by-step instructions.  However, we're planning to do exactly that for a media manager hook to work with a future release, replacing our current media manager implementation
