### ISSUE TITLE
Posts image select

### ISSUE THREAD

**Issue by muharremozdemir** [thedevdojo/voyager#2533]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
How to choose the picture that exists in the posters?

**Comment by shahbaz-dev1** [comment]
Here I want to add detail about this feature. I think he is asking about;

User should be able to attach/insert/link existing media image to a Post. Is it possible and how?

**Comment by muharremozdemir** [comment]
Yes! @wowthemes

**Comment by fletch3555** [comment]
`Post` functionality is just an example of what Voyager can do, much like `Page`.  You're free to build this into your own app, using whatever means you deem suitable.  We plan to remove Pages and Posts from the core in a newer version anyway.

**Comment by muharremozdemir** [comment]
How? @fletch3555

**Comment by muharremozdemir** [comment]
I want to use the images that are installed.

**Comment by fletch3555** [comment]
"How do I do [x]?" questions are best asked in our Slack group.  Github issues should be reserved for problems with Voyager's codebase and functionality.

**Comment by shahbaz-dev1** [comment]
@fletch3555 Thanks for your response. Yes, pages and post should be removed and what about media. I think it should be removed as well. As someone wants to use db based media manager.
