### ISSUE TITLE
issue with command : php artisan voyager:install --with-dummy

### ISSUE THREAD

**Issue by allaghi** [thedevdojo/voyager#2536]
- Laravel Version: 5.5.32
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
Hello everyone, 
I am facing this issue which is displayed in this image. 
Note: I did (following solution: https://laravel-news.com/laravel-5-4-key-too-long-error)
and nothing has changed

![voyager](https://user-images.githubusercontent.com/4201457/35276743-11e730cc-004d-11e8-8f32-aca45ee2bf0a.png)

**Comment by ghost** [comment]
Hi,
If you are using MySQL 5.7 I don't think that the problem is the length of the varchars.
Check that the engine you are using is InnoDB and have a look at this: http://goo.gl/tFKDEh

**Comment by allaghi** [comment]
Nothing changed , it is still same issue @Labrosz ,

**Comment by emptynick** [comment]
If its still the exact same error, you didn't change the engine.
MyISAM maxlength is 1000bytes, InnoDB 767 bytes.
Ref: https://dev.mysql.com/doc/refman/5.7/en/create-index.html
Also check your DB is `utf8mb4`.
Otherwise you will need to change some things in `config/database.php` like `charset` and `collation`

**Comment by fletch3555** [comment]
The best solution is to upgrade your MySQL version, or change to something else such as MariaDB or PostgreSQL.  In lieu of that, there are numerous solutions that have been mentioned here and around the web, all accessible with a simple Google search.

This is a system issue, not a Voyager issue.

**Comment by allaghi** [comment]
![01](https://user-images.githubusercontent.com/4201457/35442219-1ce14af8-02af-11e8-85f3-0d45397eee87.png)

I found the solution by disable default storage engine in my.ini file ( Note I am using wamp ).
