### ISSUE TITLE
How i can use multilingual out of admin route

### ISSUE THREAD

**Issue by jopcode** [thedevdojo/voyager#2543]
- Laravel Version: 5.5
- Voyager Version:1.0
- PHP Version: 7.0
- Database Driver & Version: mysql 5.7

### Description:
how i can to place the language switcher out of voyager admin, for example in a blog place the language switcher and automatically change the content of post spanish/english after make the config of /admin
any idea is aprecited i am newwith voyager .

thanks

**Comment by baciualexandru** [comment]
up

**Comment by fletch3555** [comment]
Please do not add "bump" comments to issues, especially when they're less then a day old.  Instead, you can use the ":+1:" reaction to show support

**Comment by HazemHa** [comment]
come here > #1364

**Comment by jopcode** [comment]
@HazemHa url broken

**Comment by fletch3555** [comment]
@HazemHa, just type `#` and the issue/PR number, no need to manually link within github.  I updated your link

**Comment by fletch3555** [comment]
@jopcode, how you build your site is completely up to you.  We aim to keep Voyager unopinionated with regards to how you design your site/app.

With that said, Voyager has 2 levels of i18n/l10n.  The first is Voyager itself, which simply [uses the configured app locale](https://github.com/the-control-group/voyager/blob/1.0/resources/views/master.blade.php#L2).  The second is the data stored by Voyager, which is stored in the database.  Accessing that data is a bit more complicated, but is handled primarily by a [few helper methods](https://github.com/the-control-group/voyager/blob/1.0/src/Helpers/helperTranslations.php) and a [Translatable trait](https://github.com/the-control-group/voyager/blob/1.0/src/Traits/Translatable.php) on all of your Translated models.  You'll have to write a little code to make that work for your site, but this should be enough to get you started.

By the way, this type of "how to" question is best asked in our Slack group.  We would prefer to save github issues for feature requests and actual bugs within the Voyager codebase.
