### ISSUE TITLE
Controller auto generation when adding bread ?

### ISSUE THREAD

**Issue by mithublue** [thedevdojo/voyager#2544]
- Laravel Version: 5.5.32
- Voyager Version: 1.0
- PHP Version: 7.0.10
- Database Driver & Version: 5.7.14

### Description:
Reffering to the issue ( https://github.com/the-control-group/voyager/issues/1216 )
that was created for version 0.11, I think it could be a nice addition if controller could be auto created when adding bread. Could this feature can be added in future ?

**Comment by fletch3555** [comment]
We prefer to not do this, as Voyager will use [VoyagerBreadController](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/VoyagerBreadController.php) by default.  You're free to create your own class if you wish to override the base functionality, but that won't be needed by everyone.  Doing so automatically will likely complicate the upgrade process for Voyager more than it will be found beneficial.

**Comment by mithublue** [comment]
Ok, What about the views, do I have to create view also manually or they are generated by Voyager ?

**Comment by fletch3555** [comment]
There are also default views that Voyager uses.  You're free to copy and modify them per our documentation if you'd like.

**Comment by amritms** [comment]
It would be great if voyager also  create controller and views as well. Developers would love this :)

**Comment by fletch3555** [comment]
We disagree. Voyager maintains a default controller and view that all BREAD use, and we provide developers the option of extending those as needed
