### ISSUE TITLE
Settings translation

### ISSUE THREAD

**Issue by reeslo** [thedevdojo/voyager#2545]
I havent see docs for translations, I've set multilingual into voyager.php.

It's possible to translate settings fields ?

**Comment by fletch3555** [comment]
All fields are required when opening issues.  Please edit your issue description to include this information: https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE

**Comment by reeslo** [comment]
- Laravel Version: 5.5.32
- Voyager Version: 1.0.14
- PHP Version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Database Driver & Version: Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### Description:
I don't see language tabs into Settings, It is possible to translate it ?

### Steps To Reproduce:
Fresh install using documentation's steps "--with-dummy", and set config/voyager.php 

``` php
    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'fr',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'fr',
        ],
    ],
```

Thanks

**Comment by giorgigigauri** [comment]
Waiting for replay.

**Comment by reeslo** [comment]
Yep

**Comment by NSpehler** [comment]
Same here. Is it possible @fletch3555?

**Comment by marktopper** [comment]
This is not currently possible, we are open to pull requests.

**Comment by amargoCactus** [comment]
any workaround?

**Comment by maobunthon** [comment]
My workaround solution is override setting helper to be 
`if (!function_exists('setting')) {
    function setting($key, $default = null)
    {   
        $key = str_replace('.', '.' . app()->getLocale() . '.', $key);
        return TCG\Voyager\Facades\Voyager::setting($key, $default);
    }
}
`
And make setting keys which you want to translate in this format.

If you got other idea please let me know because i don't know what is the best way to deal with this in this case.

**Comment by alkhachatryan** [comment]
Any news?

**Comment by Mu9tafa-Online** [comment]
+1

**Comment by reeslo** [comment]
💤

**Comment by reovilsayed** [comment]
can I translate setting?

**Comment by reeslo** [comment]
Nope, maybe after 2 more years..
