### ISSUE TITLE
Custom Dashboard

### ISSUE THREAD

**Issue by khaniku** [thedevdojo/voyager#2546]
- Laravel Version: 5.5
- Voyager Version: Latest 
- PHP Version: 7.1.1
- Database Driver & Version: mySQL

How do i edit the admin dashboard and display data from database. Let's say i wanna display some data from a table in the database and i want it to come before the dimmers.
PS. I am still a bit new to laravel and  voyager

**Comment by fletch3555** [comment]
https://voyager.readme.io/docs/overriding-views  How you get the data is up to you.

You're also free to create a completely new page and add whatever you want to it.

If you need further help implementing this, I suggest joining our Slack group and asking there.
