### ISSUE TITLE
Multiple images problem

### ISSUE THREAD

**Issue by trollsk1n** [thedevdojo/voyager#2547]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.13
- PHP Version: 7.1.1
- Database Driver & Version: MySQL

### Description:
multiple images not deleted

### Steps To Reproduce:
I added a custom field in the posts multiple pictures. Download-no problem, but when I want to delete, click the delete icon does nothing
![image 5](https://user-images.githubusercontent.com/13252993/35375202-05427f4e-01c8-11e8-90a5-07645b15b9d4.png)
image from my example, I suspect  some js and css files are needed, in console no errors, and feel this button hasn't a styles

**Comment by f0reclone** [comment]
For me the X appears on the right side of the picture and it works. Uploading multiple images at once doesn't work. You need to save before you can upload another file.

**Comment by cotiga** [comment]
I have the same problem, only **with posts bread**.
Please don't close this issue or reopen the https://github.com/the-control-group/voyager/issues/2935
Thanks

**Comment by emptynick** [comment]
We wont close issues until bugs are fixed or solutions are provided.

**Comment by LukeTowlson** [comment]
the data-field-name is wrong on the parent of image

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3809
