### ISSUE TITLE
Microsoft Edge problem with multilanguage rich text box

### ISSUE THREAD

**Issue by vaidotasposkus** [thedevdojo/voyager#2548]
- Laravel Version: 5.5
- Voyager Version: 1..
- PHP Version: 7.2
- Database Driver & Version: Maria DB

### Description:
Hi I have really big problem with multi language Rich text box. When trying switch language, rich text box doesn't switch in other language and sometimes get Script5 error. This problem appear when working with IE or Microsoft Edge browsers with other browser like Chrome or Firefox everything is fine. And next step when I try to Save I get exception that undefinex default language index. This exception generate in Translatable.php. In setting i set that my default language is lt. And this bug is in the Voyager Core, because when I trying switch language in Post I get the same problem.

**Comment by fletch3555** [comment]
Please provide the actual error/exception/stacktrace

**Comment by vaidotasposkus** [comment]
ErrorException: Undefined index: lt in file /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Traits/Translatable.php on line 303
Stack trace:
  1. ErrorException-&gt;() /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Traits/Translatable.php:303
  2. Illuminate\Foundation\Bootstrap\HandleExceptions-&gt;handleError() /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Traits/Translatable.php:303
  3. App\Event-&gt;prepareTranslations() /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Http/Controllers/Controller.php:45
  4. TCG\Voyager\Http\Controllers\Controller-&gt;insertUpdateData() /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Http/Controllers/VoyagerBreadController.php:235
  5. TCG\Voyager\Http\Controllers\VoyagerBreadController-&gt;update() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  6. call_user_func_array() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
  7. Illuminate\Routing\Controller-&gt;callAction() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
  8. Illuminate\Routing\ControllerDispatcher-&gt;dispatch() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
  9. Illuminate\Routing\Route-&gt;runController() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
 10. Illuminate\Routing\Route-&gt;run() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Router.php:658
 11. Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 12. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/tcg/voyager/src/Http/Middleware/VoyagerAdminMiddleware.php:22
 13. TCG\Voyager\Http\Middleware\VoyagerAdminMiddleware-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 14. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 15. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/app/Http/Middleware/Language.php:27
 16. App\Http\Middleware\Language-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 17. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 18. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
 19. Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 20. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 21. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
 22. Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 23. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 24. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
 25. Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 26. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 27. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
 28. Illuminate\Session\Middleware\StartSession-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 29. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 30. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
 31. Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 32. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 33. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
 34. Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 35. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 36. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 37. Illuminate\Pipeline\Pipeline-&gt;then() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Router.php:660
 38. Illuminate\Routing\Router-&gt;runRouteWithinStack() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
 39. Illuminate\Routing\Router-&gt;runRoute() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Router.php:601
 40. Illuminate\Routing\Router-&gt;dispatchToRoute() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Router.php:590
 41. Illuminate\Routing\Router-&gt;dispatch() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
 42. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
 43. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/fideloper/proxy/src/TrustProxies.php:56
 44. Fideloper\Proxy\TrustProxies-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 45. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 46. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 47. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 48. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 49. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
 50. Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 51. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 52. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
 53. Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 54. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 55. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
 56. Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
 57. Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
 58. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
 59. Illuminate\Pipeline\Pipeline-&gt;then() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
 60. Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter() /home/goshooting/domains/goshooting.lt/goshooting/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
 61. Illuminate\Foundation\Http\Kernel-&gt;handle() /home/goshooting/domains/goshooting.lt/public_html/index.php:56

**Comment by emptynick** [comment]
This should be fixed in https://github.com/the-control-group/voyager/pull/3265
