### ISSUE TITLE
Voyager instalation inside Vagrant Homestead: symlink(): Operation not supported

### ISSUE THREAD

**Issue by AlexRadch** [thedevdojo/voyager#2549]
- OS Version: Windows 10
- Laravel Version: 5.5.32
- Voyager Version: v1.0.14
- PHP Version: 7.2.0-1+ubuntu16.04.1+deb.sury.org+1
- Database Version: MySQL 5.7.20-0ubuntu0.16.04.1 - (Ubuntu)
- Database Driver Version:  libmysql - mysqlnd 5.0.12-dev - 20150407

### Description:

Command `php artisan voyager:install` or `php artisan voyager:install --with-dummy` inside homestead virtual machine return next error:
```
Adding the storage symlink to your public folder

In Filesystem.php line 228:
  symlink(): Operation not supported

``` 

### Steps To Reproduce:
Use Windows.
Create new Laravel project.
Install Homestead for new Laravel project.
Configure Homestead with hyperv provider.
Start Homestead `vagrant up`.
Add Voyager to project `composer require tcg/voyager`
Connect to Homestead virtual machine console `vagrant ssh`.
Inside Homestead virtual machine run `php artisan voyager:install` or `php artisan voyager:install --with-dummy` command.

**Comment by AlexRadch** [comment]
I created link by command `php artisan storage:link` on Windows host computer.
I suggest add `php artisan storage:link` command in voyager installation guide before `php artisan voyager:install`  command because it should be execute on host computer, but `php artisan voyager:install` should be executed on virtual machine and it can not create link.

**Comment by davidcmg** [comment]
You need to start the virtual machine with administrator permissions

**Comment by AlexRadch** [comment]
@davidcmg I can start the virtual machine! Site folder is shared from host computer (where all IDE lives) to virtual machine by SMB. So it is impossible to create links inside virtual machine for shared folders.

Inside virtual machine `sudo php artisan storage:link` return the same error `symlink(): Operation not supported`.

**Comment by fletch3555** [comment]
I assure you it's not impossible.  I personally use docker, which runs in a VM on Windows.  It sounds to me like either the php.ini inside your homestead VM has symlink() disabled, or you don't have the correct permissions (please verify that either your project folder is writable by "Everyone" or at least the user that HyperV runs under, or you can try running Vagrant as admin)

**Comment by davidcmg** [comment]
With Vagrant as admin works correctly. I had the same problem.

**Comment by fletch3555** [comment]
System configuration issue, not a Voyager issue.  Closing.

**Comment by AlexRadch** [comment]
@davidcmg I use Vagrant as admin because Vagrant with hyperv provider does not works as usual user.
