### ISSUE TITLE
custom edit-add.blade doesn't update database

### ISSUE THREAD

**Issue by yevgenatlanov** [thedevdojo/voyager#2554]
[edit-add.blade.php.txt](https://github.com/the-control-group/voyager/files/1668657/edit-add.blade.php.txt)
- Laravel Version: 5.5 latest
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: Mysql  5.7.21

### Description:
I've created Database and BREAD for simple table (services) (kinda title & description & slug). After that i've update this new model to be translatable -> the same like posts. 

after that i created custom view views/vendor/voyager/services/edit-add.blade.php and copied source from vendor/tcg/**/post/edit-add.blade.php to use view design, i've updated routes and tested it .. and i found that it writes only title, image to the db.

what can be wrong? 
### Steps To Reproduce:

1) Simple DB [url](https://www.dropbox.com/s/jq5up8cxevx0vcl/Screenshot%202018-01-26%2019.53.41.png)
2) BREAD [url](https://www.dropbox.com/s/jq5up8cxevx0vcl/Screenshot%202018-01-26%2019.53.41.png)
3) service model 
[Service.php.txt](https://github.com/the-control-group/voyager/files/1668663/Service.php.txt)

4) custom edit-add.blade.php  (attached file 
[edit-add.blade.php.txt](https://github.com/the-control-group/voyager/files/1668659/edit-add.blade.php.txt)
)

what i'm doing wrong? all other combinations that i've done in the same way i described above - works fine.

thanks in advance!

**Comment by fletch3555** [comment]
Please update the URL for the BREAD image, it's the same as the DB image.

**Comment by yevgenatlanov** [comment]
@fletch3555 ok, anyway .. this config can upload image and writes link to the db, but don't write body & slug

**Comment by fletch3555** [comment]
I can't help without understanding the problem.  In order to understand the problem, I need to see the BREAD configuration.  Right now, you have links to the same screenshot in your issue description for both the "Simple DB" and "BREAD" items under "Steps To Reproduce".  Once you update this, we will be able to review the issue

**Comment by yevgenatlanov** [comment]
@fletch3555 wow .. my issue, sorry. Here is the BREAD 1) https://www.dropbox.com/s/k980x7spn8ri0l6/Screenshot%202018-01-26%2019.54.41.png
2) https://www.dropbox.com/s/nvmiyo0jrvw7y7u/Screenshot%202018-01-27%2001.15.46.png

i'll try to describe the problem again. While i use this DB+BREAD+Custom edit-add.blade.php (that i took from ...vendor/tcg/voyager/.../post/edit-add.blade.php) - i have problems with writing information to DB. Only title, image are written correctly. Another field like body / slug are empty. 
When i'm using default view - seems like everything writes correctly 

more screenshots:
[https://www.dropbox.com/s/uvjkv3jtz2nsx1s/Screenshot%202018-01-27%2001.20.33.png?dl=0](view with new info)
[https://www.dropbox.com/s/lwug9nhkvrxa5rq/Screenshot%202018-01-27%2001.20.44.png?dl=0](after i hit save)
[https://www.dropbox.com/s/kcyffqgm3ky4si3/Screenshot%202018-01-27%2001.20.56.png?dl=0](edit service)
[https://www.dropbox.com/s/jumhgqqsj738saz/Screenshot%202018-01-27%2001.21.49.png?dl=0](database)

**Comment by yevgenatlanov** [comment]
no response
seems like project dying

**Comment by fletch3555** [comment]
Inflammatory comments like that aren't constructive.  Your issue has been open for 5 days, and we've responded to it previously.  If this issue had been open for 2 months without a single response, then your comment may be warranted, but in this case I would strongly disagree.  All we ask for is patience.

As for your issue, it's most likely not a Voyager issue, but an issue with your configuration.  I say this not with absolute certainty, but as a reasonable guess as nobody else has had similar complaints.  We're happy to work with you, but it would be easier/faster on our Slack channel, not on here.
