### ISSUE TITLE
how can i get values from pivot table 

### ISSUE THREAD

**Issue by sath26** [thedevdojo/voyager#2556]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

### Description:
i have orders and products table where order_product is pivot table. Order_product also has further pivot columns i.e. total and quantity. Now when i created bread for the pivot table to view the values the error i get is 

> Table 'handicraft.order_products' doesn't exist
so what could be a solution for this?

**Comment by fletch3555** [comment]
Voyager does not currently support displaying values from pivot tables.  If you absolutely need this feature right now, you can create BREAD/model/etc for your pivot table and and access the values that way.  We plan to enhance the relationship functionality in future versions.
