### ISSUE TITLE
Lose views and widgets when updating.

### ISSUE THREAD

**Issue by m-pastuszek** [thedevdojo/voyager#2559]
- Laravel Version: 5.5.32
- Voyager Version: 1.0.14 
- PHP Version: 7.1.11
- Database Driver & Version: MariaDB 10.1.28

### Description:
When **I updated** Voyager by using `composer update` command to latest version **I lose my all views** (edit-add.blade's) and **dashboard widgets** (Dimmers). Repair that issue as soon as possible, because without my backup I could lose my important files for Admin Panel.

### Steps To Reproduce:
Just use `composer update` command.

**Comment by emptynick** [comment]
That is not an issue.
It looks like you edited voyagers view-files which you are not supposed to do.
Follow the Laravel way of [Overriding Package Views](https://laravel.com/docs/5.5/packages#views) and you are safe.

**Comment by frdteknikelektro** [comment]
Should be closed then

**Comment by m-pastuszek** [comment]
Okay, but it isn't a problem with Laravel views, but with Voyager views. I am creating my views with Docs - [Overriding Views](https://voyager.readme.io/docs/overriding-views). So I was created for example the `articles` folder and added the `edit-add.blade.php` file with my creating article view.

And when I was updated the **Voyager**, all my views in `vendor\tcg\voyager\resources\views` have been restored to the default.

**Comment by fletch3555** [comment]
Please read the documentation (ours AND Laravel's as linked to by @emptynick) again.  Files under `vendor` should not be modified.
