### ISSUE TITLE
Insert photo from media into post or page

### ISSUE THREAD

**Issue by allaghi** [thedevdojo/voyager#2564]
Laravel Version: 5.5.32
-Voyager Version: 1.0
PHP Version:
Database Driver & Version:
Description:
How to insert photo from media library into post or page ?

Thanks in advance

**Comment by fletch3555** [comment]
All version number fields are required when creating issues.  Please edit your issue description and provide the missing information.  https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE

**Comment by allaghi** [comment]
Laravel Version: 5.5.32
-Voyager Version: 1.0
PHP Version:
Database Driver & Version:
Description:
How to insert photo from media library into post or page ?

Thanks in advance

**Comment by emptynick** [comment]
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/1877
