### ISSUE TITLE
BREAD - Loading dynamically data to fill fields

### ISSUE THREAD

**Issue by regiszanandrea** [thedevdojo/voyager#2566]
- Laravel Version: 5.5.#
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: MariaDB 

### Description:
Hi, 

I have a field named "Language" of a Product and another field "Category". I would like to loading only categories of that language selected. 

I would like to loading dynamically data to fill others fields. So, what is the best way to do this on Voyager?

### Steps To Reproduce:

Example:
1. Create a new Post
2. Choose English language
3. Loading only english categories.

**Comment by regiszanandrea** [comment]
Can you help me on this @fletch3555  ?

**Comment by fletch3555** [comment]
Voyager does not currently support dynamic field values (field values being dependent on the selected value of another).  You're free to do this, but it would be 100% custom for your application, so we can't really help that much.  I would recommend posting in our slack group and/or larachat if you need assistance figuring it out.
