### ISSUE TITLE
Question: is it possible to define default orderBy

### ISSUE THREAD

**Issue by DiederikvandenB** [thedevdojo/voyager#2567]
- Laravel Version: 5.5.0
- Voyager Version: 1.0.14
- PHP Version: 7.1.0
- Database Driver & Version: MySQL 5.7.21

### Description:
Is it possible to define default orderBy for browsing, other than using [Laravel scopes](https://laravel.com/docs/5.5/eloquent#global-scopes)?

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/3222
