### ISSUE TITLE
Has Many Relationship - Call to undefined method where

### ISSUE THREAD

**Issue by BrunoMCTeixeira** [thedevdojo/voyager#2571]
- Laravel Version: 5.5.0
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
Call to undefined method Illuminate\Foundation\Application::where()  (View: /Users/ ___ /Desktop/code/self/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php)

### Steps To Reproduce:
Add a hasmany relantionship to a table

**Comment by fletch3555** [comment]
Please provide the full stacktrace for the exception, as well as populate the remainder of the version information.  I seriously doubt you're actually running Laravel 5.5.0 and Voyager 1.0.0, but if you are, you should upgrade.

**Comment by BrunoMCTeixeira** [comment]
Exception message: Call to undefined method Illuminate\Foundation\Application::where()
Exception message: Call to undefined method Illuminate\Foundation\Application::where() (View: /Users/____/Desktop/code/self/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php)

--

 Symfony
\Component
\Debug
\Exception
\FatalThrowableError
…
/vendor
/laravel
/framework
/src
/Illuminate
/Support
/Facades
/Facade.php
221 

--

    public static function __callStatic($method, $args)
    {
        $instance = static::getFacadeRoot();
 
        if (! $instance) {
            throw new RuntimeException('A facade root has not been set.');
        }
 
        return $instance->$method(...$args);
    }
}

--

composer:

"require": {

        "laravel/framework": "5.5.*",
        "tcg/voyager": "^1.0"
    },

Composer update says everything up to date

**Comment by fletch3555** [comment]
I bet you have `App` entered in the "model namespace" field of a BREAD relationship.  The model namespace needs to be the fully-qualified model name, not just the namespace (e.g. `App\Thing`, not just `App`)

**Comment by BrunoMCTeixeira** [comment]
Well, that fixed it. The problem is that the UI of the relantioship doesn't exist. 
I just have a title on the selector is supposed to appear

**Comment by fletch3555** [comment]
I don't understand your comment.  Please elaborate.

**Comment by BrunoMCTeixeira** [comment]
This is the relationship UI inside the Bread of the main table.

It wasn't even me relating that record to the main record. I don't have also how to add other related records or how to delete that one. Inside a new record, only the title "solutions" appear

https://imgur.com/a/IDNTb

**Comment by fletch3555** [comment]
I'm sorry, but that image provides zero useful information.  Please provide a larger screenshot indicating what is/isn't working.

**Comment by BrunoMCTeixeira** [comment]
Edit Service: ("Solutions" is a HasMany Relationship)
https://imgur.com/fcR42u8

It has no controls or actions

**Comment by fletch3555** [comment]
Correct.  Voyager does not (currently) have that functionality.  By default, Voyager will simply display the associated value(s) in the BREAD view.  You can, of course, override the view (per our documentation) and add whatever functionality you would like.  But that's up to you to do.

**Comment by BrunoMCTeixeira** [comment]
I think that is really important otherwise the whole CMS is pretty much useless for anything besides simple corporative websites.

**Comment by fletch3555** [comment]
Voyager is an Admin tool, NOT a CMS.  It happens to have very similar features as a CMS (pages/posts/categories), but they're all completely optional.

**Comment by Rivsenn** [comment]
Oke, here we go, this is something that really needs to be fixed. an answer like your Fletch is dump. How in the world you can make an relationship with "has many" if the many can not be selected/choosen ? how does that work in your world.. This is no "has many" future, this is a unsorted list (not even a list, it just picks one) with no interaction at all... 

If there is any developer working on this "Admin Tool" please review this area for the Has many functionality. this function is not functional at all..

And please Fletch, correct me if im wrong but this is not an optional future, this is something that needs to be working in an "has many' action. Without you can't even select or choose the many..

**Comment by fletch3555** [comment]
@iDsigns, you misunderstood my comment.  I was referring directly to @BrunoMCTeixeira's comment about it being a CMS.  My comment states that the "CMS"-like features of Voyager are all completely optional, which is why it's an "admin tool", not a "CMS".  That specific comment had no direct relation to the issue as a whole.

Now, I do give merit to your point that this is an actual issue.  I will apologize and admit when I was wrong.  In this case, I was mistaken when I closed this issue.  I misunderstood the question/issue, and then subsequently mis-interpreted the image that was posted.  For that I apologize.  @BrunoMCTeixeira, you are correct.  The edit view should indeed have some form of edit capability.  Please check the BREAD configuration and verify that your field has a "select multiple" type

**Comment by Rivsenn** [comment]
![schermafbeelding 2018-02-08 om 16 42 04](https://user-images.githubusercontent.com/639783/35982031-0f98368c-0cef-11e8-8cd1-b285689cd50d.png)
This is what I have at the moment. There is no way for me to figure out how to fill in the multiply select..

**Comment by fletch3555** [comment]
Okay, I'm not certain why, but the view is only rendering drop-downs for `belongsTo` and `belongsToMany`.  `hasOne` and `hasMany` both render unordered lists: https://github.com/the-control-group/voyager/blob/1.0/resources/views/formfields/relationship.blade.php#L82

We'll look into this

**Comment by Rivsenn** [comment]
Yea its weird, but very well its came to light! thanks we will be waiting!

**Comment by BrunoMCTeixeira** [comment]
No need to apologize. Maybe I wasn't clear enough but yeah that is indeed the problem. No dropdown or any other element to select the records we want to relate on the UI. I think it is major to make it work.

**Comment by Rivsenn** [comment]
Little side note, when could there be a fix, or is there an quick and easy injection fix for it?

**Comment by fletch3555** [comment]
@iDsigns, it's all in a view file, so you could override that view and provide your own implementation.  It would also be an excellent first contribution if you wish to open a pull request with the change.  Just make sure it's generic enough that everyone can use it.

**Comment by BrunoMCTeixeira** [comment]
Any updates?

**Comment by Rivsenn** [comment]
Hi There @fletch3555 Is this issue being resolved ? looking forward to use it now but I dont know if it works yet. I havent got the time to do a implantation myself though..

**Comment by MrCrayon** [comment]
For anyone wondering the way it works right now is that you set the relationship on the belongsTo side. 
As per original issue Category hasMany Solutions thereof Solution belongsTo Category. 

Having a multiple select in Category might give the impression it's a BelongsToMany relationship.
We would also have to choose if showing all Solutions in the select or all not already associated with other Categories.

 I think Voyager implementation is pretty standard but if someone has ideas on how to implement this in a way that doesn't create ambiguities I'm open for suggestions.

**Comment by MrCrayon** [comment]
Since the original issue was solved and then discussion went out of topic I'm closing this.
If there is someone that wants to implement a different management of hasMany can open a PR or open a feature issue.
