### ISSUE TITLE
Feature Request: Seperating Users from Admins easily.

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#2572]
I think it would be useful, if the Voyager Admin would ship with the option to separate users and admins in different tables.

At the moment, separating users and admins is quite some struggle (https://github.com/the-control-group/voyager/issues/2568).

Here are  some reasons why I think it makes sense to allow easily a separation:

1. A user for the application may have a lot of required fields in the DB without default value. In this case, creating a simple admin user would require to make up some random values for the required fields. Further, the command `php artisan voyager:admin your@email.com --create` will not work.

2. Sometimes its nice to have a "Login as User X" feature in the admin dashboard. If admins and users use the same guard, then you constantly need to relogin as an admin, whenever you wanna login as a user.

3. If Voyager does not offer a solution, then one has to use something like `\Auth()->guard('normal')` instead of `\Auth()` in the whole application because the default guard is already used by Voyager.

I could try to create that feature and make a PR, but before I work on that, I would like to know if you guys would be interested in such a feature or if there is a reason why its not there yet.

**Comment by fletch3555** [comment]
There are at least 2 other open issues, a number of closed ones, and an open PR for this.

**Comment by niels-numbers** [comment]
Well thats awesome! Good news! Sorry that I didn't see the PR, its  only 8 days old https://github.com/the-control-group/voyager/pull/2534

**Comment by fletch3555** [comment]
No worries! Appreciate the suggestion.  Someone else just beat you to it ;)
