### ISSUE TITLE
Resized image won't show in a post

### ISSUE THREAD

**Issue by def-media** [thedevdojo/voyager#2574]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.13
- PHP Version: 7.0
- Database Driver & Version: MySQL 10.1.24-MariaDB-cll-lve

### Description:
I had the next situation:
rtrim('posts/January2018/OLJEeEfdQi4mI7Cgbhae.jpeg', '.jpeg')
which returns: 
'posts/January2018/OLJEeEfdQi4mI7Cgbha' (missing the last "e" character in the string).

It seams like "rtrim" also removes the last character of the file name if that character is present in the file exstension.

I suggest replacing 
"$name = rtrim($image, '.'.$ext);" 
with 
"$name = \Illuminate\Support\Str::replaceLast('.'.$ext, '', $image);"
in the src/Traits/Resizable.php at line 29.

It works in my case.

### Steps To Reproduce:
Create new post and add an image to it.
Save the post and find that image in the storage and rename it so that at the end of its name is one of the letters that is also present in the file extension. (Please see the attached picture.)
On the front end try to load that post with one of the resized images (medium, small or cropped).

![voyager-resizable](https://user-images.githubusercontent.com/2224247/35648062-c514e4c2-06d4-11e8-892e-f196dbdf8c2f.png)

**Comment by fletch3555** [comment]
Code change/bugfix suggestions are best opened as pull requests instead of issues.  Would you like to open the PR?  If you're not comfortable doing it (or simply don't have time), please say so and someone else will.

Thanks!

**Comment by emptynick** [comment]
We already have  https://github.com/the-control-group/voyager/pull/2525

**Comment by def-media** [comment]
Oh, OK then.
I apologize for not seeing it before.

**Comment by fletch3555** [comment]
Thanks @emptynick. I went looking for it and couldn't find it for some reason.
