### ISSUE TITLE
Long loading times and breaking then

### ISSUE THREAD

**Issue by danielsatanik** [thedevdojo/voyager#2575]
- Laravel Version: 5.5.33
- Voyager Version: 1.0.14
- PHP Version: 7.1.7
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.19

### Description:
I don't really know how to describe it. But on most pages, the Voyager admin pages seem to break. But not because of errors, that would be solvable, it just takes forever to load and stays unresponsive.

### Steps To Reproduce:
The pages and actions that produce this issue are
- on dashboard the clicking on users
- updating admin title setting (also gives an error, unique constraint)
- uploading profile image and saving the profile

I haven't explored it a lot yet because it keeps breaking, is this a known issue?

**Comment by fletch3555** [comment]
Certainly not a known problem.  Is this your local machine or a remote server?  Is it a fresh install, or have you added data?  The "browse" pages in Voyager tend to run a little slow if you have a lot of data without enabling server-side pagination, but that shouldn't affect image uploading or saving settings.

**Comment by danielsatanik** [comment]
The instance runs in vagrant on a local machine. Except for voyager everything is really fast though. Further, e.g. I have around 800 users and opening the users-view takes forever and then after some time the page is breaking.
If I could change some settings (e.g. pagination) where would that be?
Apart from that, is there a way to give you some data to get a better understanding of what is not working? how would I produce them?

**Comment by fletch3555** [comment]
Ah... yeah, 800 users will definitely do that.  Server-side pagination can be enabled in the BREAD editor for your table.  I also think your profile image issue is related since you're dealing with users.

Your "admin title" setting issue is probably a different issue, but I'll need to see the specific error being returned to figure that one out.

**Comment by danielsatanik** [comment]
I can send you a screenshot if it helps but it seems to be a database issue, I will enable pagination now and then see if this is solved

**Comment by danielsatanik** [comment]
Here is the screenshot:

![screen shot 2018-02-01 at 13 04 59](https://user-images.githubusercontent.com/2507586/35677594-8afef1b6-0750-11e8-881a-8e04ec479d57.jpeg)

**Comment by fletch3555** [comment]
Sounds like you have a field on your `users` table called `branches` with a type of `JSON`, and you're not passing it JSON data

**Comment by danielsatanik** [comment]
that is true, we have that **but** I'm not passing anything at all in voyager, this is done by voyager's controller somehow
I handle the branches column correctly in our application

also I don't know why but it seems its trying to assign 0 and 1 to every column in the users table, which does not make any sense at all

**Comment by danielsatanik** [comment]
the 1 and 0 seems to come from the checkboxes in the profile

![screen shot 2018-02-01 at 15 05 16](https://user-images.githubusercontent.com/2507586/35682541-57ec8b42-0761-11e8-9825-ded9423bd990.jpeg)

**Comment by emptynick** [comment]
We significantly decreased the query amount in https://github.com/the-control-group/voyager/pull/2812 and https://github.com/the-control-group/voyager/pull/2832
For your last problem, you might want to edit your BREAD-settings for the users-bread.
