### ISSUE TITLE
Loading a package from a VCS repository

### ISSUE THREAD

**Issue by andrey-helldar** [thedevdojo/voyager#2577]
- Laravel Version: 5.4.32
- Voyager Version: 1.0.14
- PHP Version: 5.6.4

### Description:

I need to install the package from the local repository. To do this, the [composer](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) proposes to specify a link to the folder with it in the `repositories` key, but I can not do it because the Voyager has turned it into a different kind:
```json
"repositories": {
    "hooks": {
        "type": "composer",
        "url": "https://larapack.io"
    }
}
```

Need:
```json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/igorw/monolog"
        }
    ],
```

**Comment by emptynick** [comment]
How about
```
"repositories": {
        "monolog": {
            "type": "vcs",
            "url": "https://github.com/igorw/monolog"
        },
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
```

**Comment by fletch3555** [comment]
Not a Voyager problem. Read the composer docs and you'll see that @emptynick's suggestion should work fine.
