### ISSUE TITLE
mysql error 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by vafagh** [thedevdojo/voyager#2583]
- Laravel Version: 5.56
- Voyager Version: last
- PHP Version: 7.1.13
- Database Driver & Version: mariadb 5.5.56
 /*!40100 DEFAULT CHARACTER SET utf8 */ |

### Description:
Error on `php artisan voyager:install`

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is   
  767 bytes (SQL: alter table `data_types` add unique `data_types_name_unique`(`name`))   

### Steps To Reproduce:
install laravel
add voyager 
run `php artisan voyager:install`

I fixed it by adding  `Schema::defaultStringLength(191);` into `database/migrations/2016_01_01_000000_create_data_types_table.php` inside `up` function at the begining.

**Comment by emptynick** [comment]
Please read the manual:
https://github.com/the-control-group/voyager#3-run-the-installer

**Comment by rbkkm** [comment]
https://laravel-news.com/laravel-5-4-key-too-long-error  

won't work .  key is way too long

**Comment by rbkkm** [comment]
Voyager should not make a key so long.

**Comment by fletch3555** [comment]
@rbkkm, as we've told you already, it's not voyager, it's laravel and older versions of MySQL. The instructions on that page, as well as all over the internet, do in fact work.

**Comment by vafagh** [comment]
I have to say my MariaDB version is 10.2.12 and MySQL -v gave me 5.5.56.
It means the problem is not coming from old version of MySQL.
I think this problem shows on all version of MariaDB too.
