### ISSUE TITLE
Model/DB management: Do Thumbnails take an array of objects when editing pages?

### ISSUE THREAD

**Issue by Hiroki111** [thedevdojo/voyager#259]
- Laravel Version: 5.3.0
- Voyager Version: 0.9
- PHP Version: 7.0.2
- Database Driver & Version: mysql  Ver 14.14 Distrib 5.7.10

### Description:
In my "pages" table, there is a column "thumbnail". This column is of "text" type, and supposed to have multiple images as thumbnails.
I thought I could save multiple images to with this column, set the input type "Image" and edited Optional Details, following the documentation. 
Now the Optional Details look like this.

{
    "thumbnails": [
        {
            "name": "medium",
            "scale": "50%"
        },
        {
            "name": "small",
            "scale": "25%"
        },
        {
            "name": "cropped",
            "crop": {
                "width": "300",
                "height": "250"
            }
        }
    ]
}

However, I can save only one image with this column. I tried copy-and-past the template, but it didn't work either.

My goal is to be able to put two or more images with this column and show them on the view as required.
Any advice will be appreciated!

**Comment by handiwijoyo** [comment]
@Hiroki1116 The thumbnails were generated but didn't save into database instead it generate files with suffix of thumbnail name on it. Please check the upload folder to see if the thumbnails were generated.

**Comment by Hiroki111** [comment]
Thanks for your reply. I'd like to confirm one more thing.

Now I can see that there was a thumbnail under the public/storage/pages. Still, however, only one image can be retrieved per page. 
This is because the "thumbnail" column will be updated once you upload a new thumbnail. So, even if there were two or more thumbnails in the folder, the directory will be lost from the DB table if you upload another thumbnail. 
Is that correct?

**Comment by fletch3555** [comment]
I'm going to close this.  There have been significant changes since this was opened.
