### ISSUE TITLE
Remove voyager.js request (https://s3.amazonaws.com/laravelvoyager/voyager.js)

### ISSUE THREAD

**Issue by mihaiconstantin** [thedevdojo/voyager#2594]
- Laravel Version: 5.5.28
- Voyager Version: 1.0.12
- PHP Version: 7.1.3
- Database Driver & Version: SQLite3 & 3.15.1

### Description:
- the following message gets outputted to the browser console from a file named `voyager.js` loaded from `https://s3.amazonaws.com/laravelvoyager/voyager.js`: `Welcome to Voyager 1.0`.
- Is there any way to remove that request? My Voyager installation runs on a machine without access to the internet and that request results in a `net::ERR_NAME_NOT_RESOLVED` error.

### Steps To Reproduce:
- login to your Voyager dashboard and check the console output

**Comment by emptynick** [comment]
Duplicate of https://github.com/the-control-group/voyager/issues/2562

**Comment by mihaiconstantin** [comment]
My apologies. Closing now.
