### ISSUE TITLE
Laravel Impossible to Create Root Directory

### ISSUE THREAD

**Issue by NXDChen** [thedevdojo/voyager#2597]
- Laravel Version: 5.5.33
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
Every picture i try to add goes to /storage/app/public instead of /storage. Everything works fine on localhost but the problem is on my live site.
The problem is something with this in 'config/filesystems.php':
```
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```
When i change the storage_path the voyager media page goes weird.
Anyone knows what to do about this?

### Steps To Reproduce:
Put site online and try to add a picture with the same filesystems.php

**Comment by fletch3555** [comment]
Voyager is functioning exactly as intended. You've misunderstood what that's doing.  The path `'storage/'` is referring to the path under `public`, not from the project directory.  `public/storage` is a symlink that points at `storage/app/public`, and is created by `artisan storage:link`, which is called automatically by `artisan voyager:install`

So your images are going exactly where they should be.  If they're not loading (404s) on your site, then something else is wrong.  Most likely, you're using `artisan serve` and don't have the port in your `APP_URL` (i.e. localhost:8000).
