### ISSUE TITLE
menu builder relationship

### ISSUE THREAD

**Issue by giorgigigauri** [thedevdojo/voyager#2598]
Laravel Version: 5.5.33
Voyager Version: 1.0.14
PHP Version: 7.1
Database Driver & Version: mysql

### Description:
I need to show information from table products_categories to menu under menu item e.g products. can you help me in this case ? 
![Uploading image.png…]()

### Steps To Reproduce:

- 1. I made relationships between products_categories and menu_item. 
- 2. in product category add page shows menu title but not saving in database menuid

**Comment by emptynick** [comment]
Closing due to age.
If you still need help with this, please open a new issue with more information (and a working screenshot)
