### ISSUE TITLE
crash on table without  s at end

### ISSUE THREAD

**Issue by rbkkm** [thedevdojo/voyager#2601]
Laravel Version: 5.5.33
Voyager Version: 1.0.14
PHP Version: 7.1
Database Driver & Version: mysql

### Description:
i made bread on table log. al fine.
browse result fatal error : can't find table logs   

is it me or voyager doing things wrong??

**Comment by fletch3555** [comment]
No, you're not following Laravel convention, nor are following the documented overrides.
