### ISSUE TITLE
Laravel Routing Problem

### ISSUE THREAD

**Issue by LaiqAhmad22** [thedevdojo/voyager#2609]
- Laravel Version: 5.4.36

```
Route::get('/', function () {
    return view('welcome');
});
```

this one is working but when i give anyother name as following its not working

```
Route::get("/i", function(){
    echo "its working";
});
```

I'm new in laravel and its my first project

**Comment by LaiqAhmad22** [comment]
I've been tried 

```
Route::get("i", function(){
    echo "its working";
});
````

but its not working

**Comment by fletch3555** [comment]
This is not a voyager problem. You should read laravel's documentation and ask in a more Laravel-generic forum like laracasts or larachat
