### ISSUE TITLE
Caire implementation

### ISSUE THREAD

**Issue by DiederikvandenB** [thedevdojo/voyager#2611]
Hi,

Recently I came across this repo: https://github.com/esimov/caire. I am planning (long term though) on implementing this in our Voyager setups. I was wondering wether you'd be interesting in implementing this in Voyager by default, because in that case I'll submit a PR after I am finished.

Cheers!

**Comment by fletch3555** [comment]
Seems like a very cool library, but I don't think we need it in Voyager's core.  Feel free to build the integration with Voyager into a hook if you feel it might be useful to others!
