### ISSUE TITLE
Voyager Installation on server is not working

### ISSUE THREAD

**Issue by abhishek003ite** [thedevdojo/voyager#2613]
- Laravel Version: 5.5.x
- Voyager Version: ^1.0
- PHP Version:7.0.22
- Database Driver & Version: MySql & 5.7.x

### Description:
I installed a new laravel project into my production server and after installation of fresh laravel, I installed voyager admin panel with all the given steps into voyager installation guide.

But when I am trying to access the Voyager admin panel it is giving me 404 not found error.

Please find the attached screenshot.
![screenshot 2018-02-05 23 46 39](https://user-images.githubusercontent.com/6541798/35821486-1c664fd8-0acf-11e8-9d5e-5c86c9f50f24.png)
 
Server ip is pointing to project_name/public directory.

Request for you help.

### Steps To Reproduce:
URL is http://139.59.9.122/admin

**Comment by fletch3555** [comment]
Your rewrite config isn't working correctly.  If you add a normal route to `/abc` or whatever, it would likely also fail.  As a test to prove this, you can also try to access the page as `[domain]/index.php/admin`.  This is 100% not a Voyager problem.  If you need further help troubleshooting, feel free to join our Slack group and ask in #help, though you might get better/faster support in a larger/more generic platform like larachat or laracasts.

**Comment by mavrickdeveloper** [comment]
having exactly the same issue

**Comment by rttolipas** [comment]
it happens in my ubuntu 16.04. But it works well in 14.04, i dont know if its related to the issue. any updates?

**Comment by fletch3555** [comment]
No updates because this issue has been closed for 2 months....

**Comment by marcellopato** [comment]
This is a .htaccess problem. Should be AllowOverride All
