### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by Mat-Moo** [thedevdojo/voyager#2614]
- Laravel Version: 5.4
- Voyager Version: 1.0.14
- PHP Version: 5.6.30
- Database Driver & Version: MySql  5.7.17

### Description:
When I save settings via the Admin Settings option I see
Site Title setting('site.title')....
When I save, the database record gets changed, and the screen now shows
Site Title setting('.ite.title')....

Seems to be with the replacements of bits, any ideas?

### Steps To Reproduce:
Update settings in the settings screen.

**Comment by emptynick** [comment]
Theres no problem for me.
Did you only change the value, or also the group?
What does the group dropdown right-side show to you now?

**Comment by Mat-Moo** [comment]
Group on the right side is blank...

**Comment by Mat-Moo** [comment]
Ok, looks like if I add Site/Admin into the group column and update the keys it gets resolved. I guess group was added and I missed an upgrade or something?

**Comment by emptynick** [comment]
Settings grouping was added to version 1.0, depends from which version you upgraded

**Comment by fletch3555** [comment]
Closing as self-resolved.
