### ISSUE TITLE
Specified key was too long error

### ISSUE THREAD

**Issue by CoffeeQuotes** [thedevdojo/voyager#2616]
- Laravel Version: 5.5
- Voyager Version: latest
- PHP Version: 7.1.9
- Database Driver & Version: MySql 5.7.19

### Description:
I am getting this error even after trying the mentioned solution in documentation. Here is code of my App\Providers. 
![capture](https://user-images.githubusercontent.com/17348830/35931500-d0ad7b6a-0c5a-11e8-9013-52d09a08da92.PNG)

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

 It's kind of strange as earlier without using voyager this fixes migration problem. I am first time voyager user. That's not working.  https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by emptynick** [comment]
The fix provided is not for your problem.
Your problem is the engine version of your database (probably MyISAM) while it should be InnoDB

**Comment by CoffeeQuotes** [comment]
How can I alter the database engine? The migration files are either created by laravel or voyager?

**Comment by fletch3555** [comment]
The migration files are published to your `database/migrations` directory and freely editable by you.  Alternatively, you're free to create a new migration to do it.

**Comment by CoffeeQuotes** [comment]
Yeah, I have checked all of my databases and found that actually by default some how all of them not using innodb engine. I removed wamp and install xampp. I haven't yet get time to check it.

**Comment by IvandaNothabeer** [comment]
No need to remove wamp. You just need to edit your MySQL settings in my.ini and set the Default Engine to Inoddb

**Comment by Presii** [comment]
like @IvandaNothabeer says, on your my.ini  just find and replace `default-storage-engine=MYISAM
` to `default-storage-engine=InnoDB` and restart wamp, please close this entry.
