### ISSUE TITLE
Admin Panel Prefix

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#2623]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

Is it possible to have the admin panel prefix go to the root directory? I'd like to have actually use a subdomain for the admin panel.

**Comment by emptynick** [comment]
I have not tested it personally, but you can try
```
Route::domain('admin.domain.com')->group(function () {
    Voyager::routes();
});
```

**Comment by fletch3555** [comment]
I havent tested it, but it should mostly work.  You'll likely have some issues doing that.  Specifically, if you log in with a user that is not granted access to Voyager, it will try to redirect to `/`, likely causing an infinite loop.  Other than that, I think everything should just work.

**Comment by thill0822** [comment]
thanks @emptynick & @fletch3555. Will be testing in the next few days (hopefully) and will comment back on how it works along with any tweaks for future reference.

**Comment by fletch3555** [comment]
Sounds good.  I'll close this for now.  Feel free to open it again if needed

**Comment by QSoto** [comment]
Is it working by now? I want to take voyager to -> sub.mydomain.com/admin instead mydomain.com/admin

Is it possible?

**Comment by SAM-AEL** [comment]
> Is it working by now? I want to take voyager to -> sub.mydomain.com/admin instead mydomain.com/admin
> 
> Is it possible?

Route::group(['domain' => 'sub.mydomain.com', 'prefix' => 'admin '], function () {
Voyager::routes();
});

**Comment by Sanan-84** [comment]
> Is it working by now? I want to take voyager to -> sub.mydomain.com/admin instead mydomain.com/admin
> 
> Is it possible?

i have too, but not working, pleace help
