### ISSUE TITLE
Permissions error when user can add/edit but not browse

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#2625]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
When saving your profile, users who do not have access to Browse Users are returned to the `users/index` view which throws a permissions error. 

### Steps To Reproduce:

- Create a new user with a role of `user`
- Make sure the user role does not have any BREAD permissions for the `users` database
- Login as the new user
- Go to > Profile > Edit My Profile
- Click Save

Error is returned: `AccessDeniedHttpException This action is unauthorized.` which is correct as this user does not have access to Browse users.

### Solution:

Update the `VoyagerBreadController` function `update()` from 

`->route("voyager.{$dataType->slug}.index")`

to 

`->route(Voyager::can('browse_' . $dataType->slug) ? "voyager.{$dataType->slug}.index" : "voyager.dashboard")`

This redirects to the dashboard instead of to the index slug, which should catch the permissions error. 

Is there a better / more elegant way of doing this?

**Comment by fletch3555** [comment]
Why would you want a user to be able to add/edit but not browse...?

**Comment by thill0822** [comment]
@fletch3555 

I have a user who can't add or edit other users, but they can manage posts or pages for example.

When they edit their own profile it uses the users/edit view. 

That's the only example that comes to mind, but also isn't it better to go ahead and close the loop? The system allows you to select Edit Permissions and not Browse Permissions. Without knowing all possible use cases, it may come up again.

**Comment by fletch3555** [comment]
I personally view the BREAD actions as additive.  You need to be able to see(browse/read) before you can modify(edit/add/delete).

**Comment by thill0822** [comment]
For the most part I agree, however in the profile example specifically, I don't want all users to be able to mess with other users at all, but they should be able to update their own profile. And they currently can in Voyager. It just gives an error when they save as it tries to return them to the browse users view.

**Comment by tjmckenzie** [comment]
I agree with @thill0822. I user should be able to update their own profile and/or password without also being able to view all other users. Currently, an error is thrown after profile update if the user does not have view permissions.

**Comment by carlost89** [comment]
The solution to this problem is simple, just changing in VoyagerBaseController.php in line 232:

`return redirect()->route("voyager.{$dataType->slug}.index")`

with:

`return redirect()->back()`

would be enough, so users without browse users permission would be able to edit his own profile.

What do you think?

**Comment by atmediauk** [comment]
Just ran in to this, any chance on a merge for @thill0822 or @carlost89 solutions?

**Comment by emptynick** [comment]
Implemented in https://github.com/the-control-group/voyager/pull/4453 (merged into 1.3)
