### ISSUE TITLE
JS error on Menu Builder `Uncaught SyntaxError: Unexpected end of input`

### ISSUE THREAD

**Issue by swapnilsarwe** [thedevdojo/voyager#2628]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: pdo

### Description:
Unable to re order the Menu Builder or edit the menu links when I use the html minifier package `"renatomarinho/laravel-page-speed": "^1.8"`.

Getting javascript error in console  `Uncaught SyntaxError: Unexpected end of input` on `builder:4`. When I looked in the view-source - which i compress on output by using the package package - i saw the `// the source` comment on line number `210` in the file `vendor/tcg/voyager/resources/views/menus/builder.blade.php` is causing the entire JS to get commented out.

### Steps To Reproduce: 
* Install the package "renatomarinho/laravel-page-speed": "^1.8"
* open the admin and goto menu builder

### Solution
Just need to change the line number `210`
From
```js
var _src = e.relatedTarget.data, // the source
```
to
```js
var _src = e.relatedTarget.data, /* the source */
```

**Comment by swapnilsarwe** [comment]
Not a issue related to voyager, the minifier package should take care of html or js comments while minifying the html output

**Comment by fletch3555** [comment]
Agreed. The minifier is too naive if it can't handle perfectly valid single-line comments in JS
