### ISSUE TITLE
Validation question: regex but not required still required.

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#2633]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

I've set the validation for the user password as follows: 

```
{
    "validation": {
        "rule": "min:8|regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\\d\\X])(?=.*[!$#%]).*$/",
        "messages": {
            "regex": "Your password must contain at least 1 uppercase letter, 1 lowercase letter, 1 number and 1 symbol"
        }
    }
}
```

This is working, however, when I try to edit a user if I leave the password blank, it's still giving me the `regex` error message. I need to have minimum password standards, but I shouldn't have to enter the user's password everytime the account is updated. Am I missing something?

(I know I've put in quite a few requests lately so thanks for the quick responses and bearing with me!)

**Comment by emptynick** [comment]
You _can_ try to use `nullable`.
Something like `nullable|min:8|regex:/^.*(?=.{3,})(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[\\d\\X])(?=.*[!$#%]).*$/`

**Comment by thill0822** [comment]
@emptynick that seems to have fixed it. Thanks for the help!
