### ISSUE TITLE
No options after creating relationship between two tables

### ISSUE THREAD

**Issue by IainX4L** [thedevdojo/voyager#2634]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.14
- PHP Version: 7.1.6
- Database Driver & Version: MySQL

### Description:
I have two tables - Customers & contacts.  I'm trying to setup as below:

One customer can have many contacts.  Contact table record will have drop down to select appropriate customer to link to.

The contacts table has a new row "customer_id" this should store the customer ID so I can see for example contacts #1, #2. #4 relates to customer #1, contact #3 relates to customer #2.

On the contacts BREAD settings I have setup a relationship:

![image](https://user-images.githubusercontent.com/30009928/36054201-fcd06b06-0dec-11e8-9585-8cfa387fb3fd.png)

[EDIT] Interestingly, if i choose ID here rather than customer name it shows the correct ID for the customer i'm trying to link the contact to.

Now I believe this is correct as it sets up a drop down menu called "Customers" on the "Contact" line record, however when I click the drop down there are no selectable options where i would expect to see two (as I have two test customers setup).

![image](https://user-images.githubusercontent.com/30009928/36054243-3766ea38-0ded-11e8-968a-31f24210f51a.png)

Any ideas where I am going wrong or why this dropdown is blank?

Thanks in advance.

### Steps To Reproduce:

As above.

**Comment by fletch3555** [comment]
Hard to tell from the image, but to me, it looks like your dropdown does have 2 entries (please confirm in page source).  If so, that means the display name is incorrect (returning a null or empty string).  Looks like you have `customername` in that field.  What's that field name in the database? Is it perhaps `customer_name` or `customerName`?

**Comment by IainX4L** [comment]
...OK I have fixed it.  Very strange.  The Database field was CompanyName but showing as companyname in the display name dropdown for the relationship.  If i changed the database field name to companyname and updated the relationship it works correctly.  Looks like it doesn't like capitalisation.

**Comment by IainX4L** [comment]
Slightly different issue now however...

**Customers table**
![image](https://user-images.githubusercontent.com/30009928/36061099-45e8dff2-0e4d-11e8-9439-99553aebdbff.png)

**Contacts table**
![image](https://user-images.githubusercontent.com/30009928/36061103-5b3a5282-0e4d-11e8-86da-691ba60b31af.png)

The contacts have defaulted to the customer (company) with ID of 1.  If I go into the contact and choose the customer with ID 2 ("Test Company") and hit save it doesn't update. 

Any ideas?

Thanks

**Comment by fletch3555** [comment]
This is apparently an issue for a few people. Theres an open pull request, but we havent had a chance to test it yet.  https://github.com/the-control-group/voyager/pull/2610

**Comment by IainX4L** [comment]
Hi

I have tested the pull request you posted.  Can confirm resolves the issue.

Issue closed.

Thanks

Iain
