### ISSUE TITLE
Laravel 5.6 Support

### ISSUE THREAD

**Issue by fares-shawa** [thedevdojo/voyager#2637]
On laravel 5.6 (latest release) Voyager doesn't install as it's not properly integrating with the latest updates of laravel 5.6.

**Comment by pieinn** [comment]
Same issue 
Problem 1
    - Conclusion: remove laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.3

**Comment by fletch3555** [comment]
Voyager does not currently support laravel 5.6

**Comment by KarimGeiger** [comment]
Why don't we then leave this issue open until it does?

**Comment by fletch3555** [comment]
Because it does now, but in an unreleased/beta version (the `1.x-dev` branch).

**Comment by KarimGeiger** [comment]
Okay, thanks for clearing that up. I’ll be looking forward to the release then 👍
