### ISSUE TITLE
Rich text and Media Manager. 

### ISSUE THREAD

**Issue by Sebastiangperez** [thedevdojo/voyager#2638]
Enable usign Rich text editor and Media manager linking the files.

**Comment by fletch3555** [comment]
All fields are required when opening issues: https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE

As your issue is simply a feature request, I'll answer it anyway.  We have plans to rebuild the media manager for a future release, including a version of the feature you've requested.
