### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by GrimReaper420** [thedevdojo/voyager#2640]
- Laravel Version: 5.6.1
- Voyager Version: 1.0.15
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:

Voyager table names collide with my table names. Please add prefixes to the voyager table names.

### Steps To Reproduce:
create a table named 'posts'
run 'php artisan voyager:install'

**Comment by fletch3555** [comment]
This is a much more complicated issue, and has been discussed at length in other issues and on our slack group.  We're looking at options on how to proceed, but blindly adding table prefixes is not possible at this point.
