### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by GrimReaper420** [thedevdojo/voyager#2641]
- Laravel Version: 5.6.1
- Voyager Version: 1.0.15
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:

The migration files are cluttered. Can you put all the migrations into one file like laratrust?

**Comment by fletch3555** [comment]
They're not cluttered.  We can't change them without making a major release as it's a breaking change for existing installations.  We may consider this for 2.0, but will not be doing so any time soon
