### ISSUE TITLE
Unknown column 'name' in 'field list' when create admin

### ISSUE THREAD

**Issue by edmoiseenkov** [thedevdojo/voyager#2643]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.15
- PHP Version: 5.6.30
- Database Driver & Version: MySQL 5.7.11

### Description:
Hey guys. I have a problem.
I have User model without "name" field.
"name" i rename to "first_name" and add field "last_name"
when i try to create admin i have error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list'

it's ok. I understand why I get this error.
The question next: how to fix this problem, without "name" filed?

Thanks!

**Comment by emptynick** [comment]
Do you get that when installing with dummy or adding a user through artisan?

Edit: Forget that:
~You can use an [Accessor](https://laravel.com/docs/5.5/eloquent-mutators#defining-an-accessor)~

**Comment by fletch3555** [comment]
Voyager expects a `name` field on your User model, and provides a migration to put it there for you.  If you have other needs, you may need to customize some of the functionality or may not be able to use some.  For example, using the `voyager:admin` Artisan command may not work, so you may need to create your own command that uses your first/last_name fields instead.  You can use Accessor/Mutator methods on your model, but there are likely still ways of bypassing them.  For example, I think using `fill()` may bypass them (honestly not sure, but I know Voyager uses fill in a few places).

In any case, there's no perfect solution, and not much we can do for you.  If you have specific questions while attempting to fix this, feel free to post in our Slack group.  We'll be glad to provide guidance, but can't do it for you.  I'm sure you can appreciate that position.

**Comment by hiren004** [comment]
I've first_name and last_name fields in my DB. How can  handle it to fix this? Anyone have an idea? Please help!!

Thanks,

**Comment by fletch3555** [comment]
@hiren004, please stop commenting in closed issues. You're free to open your own, or ask in our slack group
