### ISSUE TITLE
add supported laravel version to top of README.md

### ISSUE THREAD

**Issue by kitsunekyo** [thedevdojo/voyager#2644]
please add the supported laravel version to the readme.

tried installing on laravel 5.6.3 but composer install failed directly due to version issue.

**Comment by fletch3555** [comment]
It's in there, right above the "Installation Steps" heading

okay okay, fine... you caught me.. I cheated... I just updated it from "and newer" to "and 5.5".

**Comment by kitsunekyo** [comment]
thanks man ;)
