### ISSUE TITLE
is tcg voyager usable with lumen?

### ISSUE THREAD

**Issue by faghihi** [thedevdojo/voyager#2645]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Hi i wanna use tcg voyager with lumen  for admin pannel 
I can create a separate project , but i prefer not to. so can you give me a manual for using voyager inside lumen ?

**Comment by fletch3555** [comment]
I can't give you a manual to do so, because we don't officially support Lumen.  You're welcome to give it a try and report back.
