### ISSUE TITLE
Can't override views for master.blade.php

### ISSUE THREAD

**Issue by traintracr** [thedevdojo/voyager#2647]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I cant override the master.blade.php  view, or any of the views! 

### Steps To Reproduce:
copy  tcg/voyager/resources/views  to resources/views/vendor folder 

I really would like to use this backend you guys made, but if I can't override the admin blades, then it's absolutely useless to me!

**Comment by fletch3555** [comment]
You'll need to provide more information if you want a useful response. 
Specifically, it would be helpful if you provided specifics of what you've done and how you know it's not working.

https://voyager.readme.io/docs/overriding-routes and https://laravel.com/docs/5.5/packages#views (subsection "Overriding package views").

**Comment by traintracr** [comment]
Hi Fletcher,

Sure! 

First thing I did was edited the \vendor\tcg\voyager\src\VoyagerServiceProvider.php

and added, `	    $this->publishes([
		    __DIR__.'/../resources/views' => resource_path('views/vendor/voyager'),
	    ]);`

after `   $this->loadViewsFrom(__DIR__.'/../resources/views', 'voyager');`

around line 96, then I ran 

php artisan vendor:publish 
php artisan view:clear
composer dump-autoload

Then I was reloading the /admin/login  page, 

I thought, that page was using the master.blade.php  and after a closer look, I see the login page does not use the master blade, and has its own blade!!

but the overrides for the views are working! 

Thanks!

**Comment by fletch3555** [comment]
You're asking for a bad time if you edit files under the vendor directory.  Please don't do that.

As for what you're doing, why do you need to publish all of the views? Can't you just copy the specific ones you need? If you truly need to override all of the views, then you'll likely be better off building your own solution instead of using Voyager.  The more you override, the harder it'll be to upgrade.  We come close, but we don't follow semver perfectly.  Breaking changes do make it into patch releases.

**Comment by defaultpage** [comment]
> Please don't do that.

👍 

> @traintracr : copy `tcg/voyager/resources/views` to `resources/views/vendor` folder

Are you sure the file path is correct? Is your path `resources/views/vendor/voyager/`? As said  @fletch3555, you can add only one file... 

Please, read my [comment](https://github.com/the-control-group/voyager/issues/2529#issuecomment-364637638).

**Comment by fletch3555** [comment]
@ArtemMolotov, yes, `voyager` is needed at the end of the path, you're correct.  What do you mean by "can add only one file"?

**Comment by defaultpage** [comment]
@fletch3555, I mean, if we need to override only one file, we "can add only one file" in `resources/views/vendor/voyager/`.
> As for what you're doing, why do you need to publish all of the views? Can't you just copy the specific ones you need?

**Comment by fletch3555** [comment]
Ah okay, sorry, I misunderstood your comment.  Sounded like you were telling me I was wrong, not telling @traintracr that what I said was right.

**Comment by defaultpage** [comment]
I'm sorry too... I must learn to speak more competently :)
