### ISSUE TITLE
image required field

### ISSUE THREAD

**Issue by touilahmedimad** [thedevdojo/voyager#2649]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
there is a problem with not nullable columns of type image
when we set it with options to be required and don't give it new value on edit it gives error and this hasn't to be because we gave the picture before

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/3358
