### ISSUE TITLE
Not installing in Laravel 5.6

### ISSUE THREAD

**Issue by vimalmistry** [thedevdojo/voyager#2650]
- Laravel Version: 5.6.0
- Voyager Version: 1.0
- PHP Version: 7.0

In command line shows.
Your requirements could not be resolved to an installable set of packages.

**Comment by liagkos** [comment]
Same here.

- Laravel 5.6.3
- Voyager 1.0.15
- PHP 7.2

Output:

Problem 1
    - Installation request for tcg/voyager v1.0.15 -> satisfiable by tcg/voyager[v1.0.15].
    - Conclusion: remove laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.3
    - tcg/voyager v1.0.15 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework v5.6.3
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.3
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.6.3
    - Installation request for laravel/framework (locked at v5.6.3, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.3].

**Comment by cyrildewit** [comment]
> "Voyager does not currently support laravel 5.6" - @fletch3555 

Please see #2637

It's also noted in the readme above the **installation steps**. Fletch added this yesterday: https://github.com/the-control-group/voyager/commit/07f0b4133db619d78f672405ed17bd2e80e0443b

**Comment by liagkos** [comment]
Thank you, I tried it last week and decided to open a ticket today. I haven't noticed that in the meantime it was mentioned somewhere else.

**Comment by textoo** [comment]
hello, 
as the 5.6 support was added to the dev branch of voyager you can try this :

`composer require tcg/voyager:dev-1.x-dev`

**this is only meant for test as the dev branch is obviously not stable, use it at your own risk**

**Comment by ekram-syed** [comment]
so whats the latest laravel version that Voyager work good with

**Comment by fletch3555** [comment]
5.5.*

Please note that this is mentioned in our readme file and documentation

**Comment by JonathanPort** [comment]
Hi, any news on the 5.6 support release?

**Comment by FelipeOneHouse** [comment]
if i try install with composer require tcg/voyager:dev-1.x-dev i have this
i thinked that install suposse that colum role_id exist, then i added manually with the same settings that generated in migration for role table , but follow to no working 
 2   PDOException::("SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`ddbb`.`#sql-448_be`, CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`))")
     .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php : 141

**Comment by fletch3555** [comment]
@FelipeOneHouse, this issue has been closed for 2 months. Please open your own or ask in our slack group
