### ISSUE TITLE
Style  crash

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#2651]
Laravel Version: 5.5.*
Voyager Version: 1.0.0
PHP Version: 7.0.*
Database Driver & Version: -

### Description:
If  you have table  widgets, and  you create bread and open bread page or page widgets from admin - style crash

### Steps To Reproduce:
Create table widgets
Create bread
- Open  page:
 -- admin/widgets   -crash
 -- admin/database/widgets/bread/edit  -crash

**Comment by fletch3555** [comment]
All version information is required.  Please update your issue and reopen this issue for support.

**Comment by Akopean** [comment]
Laravel Version: 5.5.*
Voyager Version: 1.0.0
PHP Version: 7.0.*
Database Driver & Version: -
