### ISSUE TITLE
Time frame for 1.x release?

### ISSUE THREAD

**Issue by nickbryan** [thedevdojo/voyager#2653]
Not sure where the best place to ask about his is so thought I would ask here. We are hoping to use the multi role functionality that is pending release soon. Just wondering if you guys have a release date in mind for the 1.x-dev branch?

**Comment by fletch3555** [comment]
Slack would be the best place for these questions.

No release date is planned just yet.  It's mostly feature-complete, but not guaranteed not to change. We have tests and documentation to do.  I doubt it'll be months, but I can't confirm a specific date at this point

**Comment by nickbryan** [comment]
@fletch3555 thanks for the update, will direct future comments like this to slack.
