### ISSUE TITLE
Make relationship between two column of a table

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2654]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I have a table named 'pricelist' with 4 columns 'id, department_id, service_id, amount'. I want to make a relation between 'department_id' and 'service_id' in BREAD. How to do it ?

**Comment by defaultpage** [comment]
You have two tables `departments` and `services`, right? Please, read [there](https://voyager.readme.io/docs/relationships).

**Comment by arafatrahman13** [comment]
@ArtemMolotov .....'pricelist' table has 4 columns 'id, department_id, service_id, amount'.I can create relationship between 'pricelist_tbl id' and 'department_id' or 'pricelist_tbl id' and 'service_id'. But How can I create a relation between department_id and service_id. U got my point?

**Comment by fletch3555** [comment]
You wouldn't...? Why would you want those 2 fields on the same table to be related? What does that gain you? I suspect you misunderstand the purpose of relations.

**Comment by arafatrahman13** [comment]
@fletch3555......I have two tables . 'Department' and 'Service'. There are some services under each department id. Now I have a form in 'price page' where there are two drop down field. One is 'department' and second one is 'service'.... the 'service' drop down list will be changed according to the changes of 'department' table. That's why I want to create a relation between 'department' and 'service' . Clear my friend ?

**Comment by defaultpage** [comment]
I think you can do it with custom view (filter services by ajax)

**Comment by fletch3555** [comment]
You've misspoke.  Relationships are for database table to be related to other database tables.

What you're asking for the values of one field to be dependent on the selected value of another.  This requires javascript and asyncronous/AJAX calls to get the limited data for the other field.

This is not something I plan to add to Voyager, at least not anytime soon.  This feature is just too specific.  Configuration for it would be vastly different from one user to the next.  Of course, you're free to implement it yourself.

**Comment by arafatrahman13** [comment]
@fletch3555 ... Thanks for the specific answer.... :)

**Comment by fletch3555** [comment]
You're welcome.

**Comment by rosorio3px** [comment]
What about recursive relationships?

**Comment by fletch3555** [comment]
This issue has been closed for nearly 2 years now, and was for a much older version.  Please don't comment on such old issues and instead ask in slack or open your own issue
