### ISSUE TITLE
How to edit file path if voyager is installed on another domain

### ISSUE THREAD

**Issue by xsaad67** [thedevdojo/voyager#2663]
- Laravel Version: 5.5
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
How to edit image path if voyager is installed on another domain? I've installed voyager on completely separate domain. How can I change the image path to point my actual domain. like If I install voyager on helloworld.dev but my real domain where images are stored at productiondomain.com How can I point my images to point at productiondomain.com/images/myimage.jpeg?

**Comment by fletch3555** [comment]
Have you tried...?

**Comment by fletch3555** [comment]
Short answer is here: https://laravel.com/docs/5.5/filesystem

Long answer is: Voyager uses Laravel's filesystem configuration.  By default, it uses the `public` disk, but that's configurable in `config/voyager.php`.  You'll have to change the disk (similar to [this](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L51)) to point at your domain for the rendered URL (`url` field in the config), and whatever shared filesystem for writing, however you want to set that up)
