### ISSUE TITLE
Image validation doesn't work in Laravel Voyager

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2667]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I have used validation for image in Laravel Voyager BREAD. But it doesn't work. It takes all dimension of images.
{
"validation": {
    "rule": "dimensions:width=100,height=100",
    "messages": {
        "dimensions": "This :attribute field is a must."
    }
}
}
![capture](https://user-images.githubusercontent.com/22347660/36248356-67a0e7da-1261-11e8-81d2-d6eb37add853.PNG)

**Comment by defaultpage** [comment]
> Basically you just have to lowercase display names (Assuming they are identical) like name/Name order/Order.

#2384 
#2236
#2205
PRs:
#2191
#2660

**Comment by arafatrahman13** [comment]
Ya it's ok now. **I just changed the display name into lower case and the validation is working fine** now.
But it is also an issue @ArtemMolotov that the **display name is looking awkward** now.

**Comment by defaultpage** [comment]
Validation issue (custom display names) fixed in [v.1.0.16](https://github.com/the-control-group/voyager/releases/tag/v1.0.16). You can update `voyager`. Please, close this issue if the problem will disappear.

**Comment by emptynick** [comment]
So is this fixed now?
