### ISSUE TITLE
[Proposal] Create a forum for more general and other questions

### ISSUE THREAD

**Issue by vblinden** [thedevdojo/voyager#2673]
Hello everyone,

I think it's a good idea to apply for the [free Discource ](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/) forum or other software which achives the same thing. Where people can ask more general questions or ask for help. At the moment these questions are asked in the issue section and creates some clutter.

I know we already have a Slack group, but will be a nice add-on.

What do you think?

**Comment by fletch3555** [comment]
I'd prefer to not divide the community further. I have enough issues keeping track of just slack and github
