### ISSUE TITLE
Rich text box don't work

### ISSUE THREAD

**Issue by NicolaeCasir** [thedevdojo/voyager#2674]
- Laravel Version: **5.5.34**
- Voyager Version: **1.0.15**
- PHP Version: **7.2.2**
- Database Driver & Version: **MySQL, 10.0.33-MariaDB-0ubuntu0.16.04.1**

### Description:
Hi. I dont know why... Somenthing like 1 hour ago, I realized that righ text don't work. Console is error free.. I updated Voyager from 1.0.10 to 1.0.15, Laravel from 5.4.36 to 5.5.34 but nothing( Clean Voyager, the same.

[Screenshot](https://i.imgur.com/uff63eG.png)

### Steps To Reproduce:
Try to add a blog post)

**Comment by defaultpage** [comment]
Is the file `laravel.log` empty too?

**Comment by NicolaeCasir** [comment]
@ArtemMolotov, yes... I cleared log, navigate to BREAD, tried to create something, tried to edit (on edit i get simple textarea with HTML code), and log is also empty.

**Comment by fletch3555** [comment]
Did you republish CSS and JS files after upgrading? `artisan vendor:publish`.  You may need to add `--force` or delete the existing files then republish.

**Comment by emptynick** [comment]
Is this maybe related to #1847 and fixed in #2671?

**Comment by NicolaeCasir** [comment]
@fletch3555 , just tried with --force.. nothing

**Comment by alexcode-lab** [comment]
I had similar issue. 
In my case the reason was Cloudflare, specificly **Rocket Loader** option that changed js to improve load speed. Turned off this option and everything start working.
No wonder that it still in beta.

**Comment by NicolaeCasir** [comment]
@a-dorosh I think this is! LOL... I turned it off too but didn't realize that problem was in it..

Let's change to SOLVED!))
