### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by sabiehahmed** [thedevdojo/voyager#2676]
- Laravel Version: 5.6.0
- Voyager Version: 1.0.15
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:
I recently updated my project with laravel 5.6, currently voyager doesn't support laravel 5.6

### Steps To Reproduce:
migrate to laravel 5.6 -> composer install

**Comment by defaultpage** [comment]
Duplicate #2637

**Comment by defaultpage** [comment]
PR #2627

**Comment by fletch3555** [comment]
Voyager 1.1 will support Laravel 5.6, but it's not released yet.
