### ISSUE TITLE
Voyager won't install on Laravel v5.6

### ISSUE THREAD

**Issue by rhomathome** [thedevdojo/voyager#2679]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by defaultpage** [comment]
Please, use search first then create new issue. Can you close this issue?

Duplicate #2676 and #2637 
PR #2627

> @fletch3555: Voyager 1.1 will support Laravel 5.6, but it's not released yet.

**Comment by fletch3555** [comment]
@rhomathome, as @ArtemMolotov mentioned, please search before opening new issues.  You could also ask on our Slack group if you're not sure.

As one other side note, all version information is required when opening issues.  If most/all of the version information/description/steps to reproduce fields don't apply to your questions/issue, then it's likely that you're asking in the wrong place, and should ask in Slack first.
