### ISSUE TITLE
all the images that I upload  increase to 1800 px

### ISSUE THREAD

**Issue by virdignus** [thedevdojo/voyager#2681]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1.12
- Database Driver & Version:MySQL (ver. 8.0.3-rc-log)

### Description:
all the images that i upload  increase to 1800 px

### Steps To Reproduce:
1. Create table;
2. Create BREAD.
3. Select Input type like image.
4. Edit data.
5. Select image with any resolution ( 300x200 for example).
6. Save data.
7. Open saved image and check resolution

**Comment by fletch3555** [comment]
This is a known bug after the last release.  You can set `upsize` to false in your [image config](https://voyager.readme.io/docs/additional-field-options#section-image) as a workaround until we can get a fix out

**Comment by ben182** [comment]
I dont think that this is fixed actually
