### ISSUE TITLE
Translations only work on the first page of the browse table.

### ISSUE THREAD

**Issue by pcable** [thedevdojo/voyager#2682]
- Laravel Version: v5.5.34
- Voyager Version: 1.0.15
- PHP Version:
- Database Driver & Version:

### Description:
Translations only work on the first page of the browse table.

### Steps To Reproduce:
Add enough pages with translations
Browse pages and select the second page. 
Translations don't change

**Comment by pcable** [comment]
When we change page we get a new set of translation boxes so the plugin needs to be reinitialized whenever the page changes.

**Comment by marktopper** [comment]
Solved in #2683
