### ISSUE TITLE
Issue in Image Display after upload

### ISSUE THREAD

**Issue by reach2rahulbharti** [thedevdojo/voyager#2684]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I have Create a Seprate categary page through bread but image not display after upload
Please find the snapshot for the same

![image](https://user-images.githubusercontent.com/36505183/36338505-ec9752be-13d6-11e8-9bda-35e9aa422142.png)

Media Folder

![image](https://user-images.githubusercontent.com/36505183/36338510-07160ffe-13d7-11e8-80d6-812f6d40d648.png)

**Comment by defaultpage** [comment]
What is the image `href`? Can you find the image in `/storage/app/public/` folder? If `yes`, you must create symbolic link `storage` in `/public` to the `/storage/app/public/` folder.

**Comment by reach2rahulbharti** [comment]
image href:  http://localhost:8080/arg/public//storage/rg_category/February2018/fB3S5PNjlWEnRL0xTTUM.png

Yes I find the image in /storage/app/public/ 

Please guide me step by step ...how to create symbolic link

**Comment by defaultpage** [comment]
In command promt (windows): 
```bash
mklink /d "D:\your_project\public\storage" "D:\your_project\storage\app\public"
```

**Comment by ArtemMolotov** [comment]
#575

**Comment by reach2rahulbharti** [comment]
Please guide me in brief..
my project path is C:\xampp\htdocs\arg\

**Comment by defaultpage** [comment]
Run console (Win+R => `cmd.exe` => Enter) and write next:
```bash
mklink /d "C:\xampp\htdocs\arg\public\storage" "C:\xampp\htdocs\arg\storage\app\public"
```
Please, send me output. After that check symlink in `C:\xampp\htdocs\arg\public\` folder:

![](https://habrastorage.org/webt/mi/ch/l8/michl8ivapghzhy0vyx_6cdzd_u.png)

**Comment by reach2rahulbharti** [comment]
It show file already exists ???

**Comment by defaultpage** [comment]
Hmm.. Can you open  C:\xampp\htdocs\\**arg\public**\\storage\rg_category\February2018\ folder?

**Comment by reach2rahulbharti** [comment]
no...its does not exit....,
but file is in C:\xampp\htdocs\arg\storage\app\public\rg_category\February2018

**Comment by defaultpage** [comment]
Send me screenshot from `C:\xampp\htdocs\arg\public`...

**Comment by reach2rahulbharti** [comment]
![image](https://user-images.githubusercontent.com/36505183/36339665-d45a68de-13f0-11e8-85c3-01f745d86255.png)

**Comment by defaultpage** [comment]
Rename `storage` folder to `storage_backup` and run previous command:
```bash
mklink /d "C:\xampp\htdocs\arg\public\storage" "C:\xampp\htdocs\arg\storage\app\public"
```
Be careful with `ftp` or project backups in the future. Your symlinks can become folders.

**Comment by reach2rahulbharti** [comment]
You do not have sufficient privilege to perform this operation.

**Comment by defaultpage** [comment]
Run console (cmd or PowerShell) with administrator privileges (image 1). I think you can create symlink manually (image 2) too.

<details>
<summary>Image 1</summary>

![](https://habrastorage.org/webt/jw/fm/pi/jwfmpiv3iuoud8gykgpgvpximrc.png)
</details>

<details>
<summary>Image 2</summary>

![](https://www.howtogeek.com/wp-content/uploads/2017/02/01_creating_shortcut.png)
</details>

**Comment by reach2rahulbharti** [comment]
mklink : The term 'mklink' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1
+ mklink /d "C:\xampp\htdocs\arg\public\storage" "C:\xampp\htdocs\arg\s ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (mklink:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ArtemMolotov** [comment]
I'm sorry, try next command:
```bash
cmd /c mklink /d "C:\xampp\htdocs\arg\public\storage" "C:\xampp\htdocs\arg\storage\app\public"
```

**Comment by defaultpage** [comment]
I'm sorry, try next command for PowerShell:
```bash
cmd.exe /c mklink /d "C:\xampp\htdocs\arg\public\storage" "C:\xampp\htdocs\arg\storage\app\public"
```

**Comment by reach2rahulbharti** [comment]
Thanks for the support...its work
but i want to use our custome path to store image.....is any method for this

**Comment by defaultpage** [comment]
The same what you want: #2669

Can you close this issue?
