### ISSUE TITLE
Potential bad route for bread

### ISSUE THREAD

**Issue by defaultpage** [thedevdojo/voyager#2685]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
If we create bread that uses a table name with a symbol `_` (e.g. `example_table`), we will can't write `route('voyager.example_table.index')`. Because this will cause an error:
```
Route [voyager.payment_statuses.index] not defined.
```
But `route('voyager.example-table.index')` will work successfully.

Can you please help me with that?

### Steps To Reproduce:
1. Create database table `example_table`
2. Create bread
3. Add `route('voyager.example_table.index')` somewhere (e.g. custom view)
4. Open the page where you added `route('voyager.example_table.index')`.

**Comment by emptynick** [comment]
The routes use the slug as the identifier. See https://github.com/the-control-group/voyager/blob/1.0/routes/voyager.php#L43
And iirc the slug will convert a `_` to `-`

**Comment by defaultpage** [comment]
@emptynick, Thanks. Can you give me a link about `iirc`?

I'm not sure that this has anything to do with the current issue, but...

I create relationship between `payment_statuses` (id) and `payments` (status_id) (image) and if I trying to change `Статус платежа` value... It is always set to 1.

Now I'm debugging `insertUpdateData`...

<details>
<summary>My Payment model</summary>

```php 
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    protected $fillable = [
        'client_id',
        'amount',
        'currency',
        'status_id',
        'shop_id',
        'paid_at',
    ];

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function status()
    {
        return $this->belongsTo(PaymentStatus::class);
    }

}

```
</details>

 
[Link](https://habrastorage.org/webt/wh/hb/gx/whhbgxllq7n_2ut3vxpyb6hgiwo.png)
![](https://habrastorage.org/webt/wh/hb/gx/whhbgxllq7n_2ut3vxpyb6hgiwo.png)

**Comment by emptynick** [comment]
`iirc` only means `if I remember correctly`.
And I can't tell you anything about your other problem, but it's definitely different.

**Comment by defaultpage** [comment]
> @emptynick: `iirc` only means `if I remember correctly`.

Oh... :D 

> but it's definitely different

Yes... I found reason of the error... I forgot change type of the column `status_id` (`checkbox` to `number`)...
