### ISSUE TITLE
how to pass value to menu page

### ISSUE THREAD

**Issue by muhammetakkus** [thedevdojo/voyager#2689]
- Laravel Version: 5.5.6
- Voyager Version: 1.0
- PHP Version: 7.2

### Description:
I want to pass value/variable to menu page. 
Is that possible?
```php
menu('site', 'components/menu', ['style' => 'sub-menu'])
```
what is for the third option?

**Comment by vblinden** [comment]
Yes, you can pass options to a menu. You can access them with the `$options` variable in your menu view.

**Comment by fletch3555** [comment]
As @vblinden said, the third argument is `$options` ([helper](https://github.com/the-control-group/voyager/blob/1.0/src/Helpers/helpers.php#L11), [model](https://github.com/the-control-group/voyager/blob/1.0/src/Models/Menu.php#L39)), and it can be used to pass in whatever you'd like.
