### ISSUE TITLE
Images Upload According To Category

### ISSUE THREAD

**Issue by DASH1986** [thedevdojo/voyager#2691]
- Laravel Version: 5.6.0
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.1

### Description:
I want to upload multiple images to different folders depending on the image category (ex Car / Van). Inside of each image category folder there should be folders for thumbs, medium and cropped. And also the name of the uploaded file should be changed to (category name-timestamp.extension). I googled for this and also looked at videos in youtube without any luck. Can someone help me with this.

**Comment by vblinden** [comment]
This doesn't look like an issue with Voyager. You can read in the Laravel documentation how to put files on the filesystem (https://laravel.com/docs/filesystem). Unfortunately we don't have time to write everything for every use case.

**Comment by fletch3555** [comment]
Voyager uses a single upload directory, and separates files by upload date. There is currently no configuration available to change where files get uploaded to, statically OR dynamically.

If you choose to make this happen yourself, we won't be able to tell you how to do it.  We MAY be able to provide some guidance if something breaks, but don't expect it.  Your best bet is to ask these questions in slack, as github should be reserved for supported issues with the package
