### ISSUE TITLE
How create and use rules in my Controller?

### ISSUE THREAD

**Issue by lucascardial** [thedevdojo/voyager#2692]
- Laravel Version: v5.5.33
- Voyager Version: 1.0.14
- PHP Version: 7.1.12
- Database Driver & Version: MYSQL/5.7.18

### Description:
Hi,
I created my "Module" with specific controllers, models, views and menu, but I don't use any Database to this "Module".
I need use the rules and permissions voyager, but I dont know how.
I inserted manually on table voyager.permissions my permissions description:
`key: "browse phonenumber"`
`table_name: "Phone Module" `
But... as I havent a table, I use de field "table_name" to refer to the module name, and organizacional questions on rules display.
In my controller, I'm verifying if this user have the rule like this:

```
namespace App\Http\Controllers;
use App\Phone;
use Illuminate\Http\Request;

class PhoneModuleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(!Voyager::can('browse phonenumber')){
            echo "You can't";
        }else{
            echo 'Ok, you can';
        }
    }
}

```
There is another way of applying voyager rules to personal controllres?
`Sorry for my english.`

**Comment by vblinden** [comment]
If the model doesn't have a table, you can set it to `null`. You can generate the browse, read, etc. permissions the way we do it in the [PermissionsTableSeeder.php](https://github.com/the-control-group/voyager/blob/1.0/publishable/database/seeds/PermissionsTableSeeder.php).

**Comment by lucascardial** [comment]
@vblinden ,
I need aply the rules and permission in my controller. 
And I do not want to do this check using this:
```
if(!Voyager::can('browse phonenumber')){
         echo "You can't";
else{
         echo 'Ok, you can';
}
```
This code works, but it does not seem right.

**Comment by vblinden** [comment]
You can also use [policies](https://laravel.com/docs/authorization) for that.

**Comment by fletch3555** [comment]
You also can't use spaces (or at least you shouldn't... It's untested)

**Comment by fletch3555** [comment]
Policies are tied to models, but your model doesn't necessarily need to be tied to a database table.

So to do what you're trying to do, you should create a model class but with `$table = null` or something (you can google how to have a table-less model).  You can then use policies normally (create your own policy class, extend `TCG/Voyager/Policies/BasePolicy`, and link it with your model by the directions in the link @vblinden posted).  You'll have to seed a row into the `data_types` table.  Then you can create permissions as you have (`action` is a string of what you want to do (i.e. `browse`), underscore between them, and `name` is the value of the `name` field in your DataType row):
```
key => '[action]_[name]',
table_name => null
```

Once this is done, you can use `$this->authorize('[action]', new [your model class]);` in your controller (or any other method listed here: https://laravel.com/docs/5.6/authorization#authorizing-actions-using-policies).

If you want to make it just a little simpler, you can skip extending `BasePolicy`, and just write your policy methods to manually check against the Voyager permissions table, which means you won't need the `data_types` row.  This is a bit less hacky.

**Comment by fletch3555** [comment]
If you have any further questions, I recommend joining our Slack group and asking there.
