### ISSUE TITLE
Removing the add new string at settings page

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#2695]
- Laravel Version: 5.5
- Voyager Version: latest
- PHP Version: 7.2
- Database Driver & Version:mysql

### Description:
Hi , i was trying to push the final work to could so i want to remove the add new string form in settings page , is there a way to remove it ?

### Steps To Reproduce:
None

**Comment by emptynick** [comment]
There is not currently.
But the `store` method checks for an [add-permission,](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/VoyagerSettingsController.php#L45) so this could be implemented in the view aswell.
Maybe someone wants to make a PR. @vblinden maybe?

**Comment by mavrickdeveloper** [comment]
so should i just removed it from its view to hide it for now ?

i really loved the config option of hiding dev tips , i think another option for hide dev tools in general would help too

**Comment by vblinden** [comment]
I am working on a fix as we speak. And what do you mean with dev tools? Like the database and BREAD sections?
