### ISSUE TITLE
Better way to layout BREAD? (Similar to WordPress' Advanced Custom Fields plugin)

### ISSUE THREAD

**Issue by Luc45** [thedevdojo/voyager#2696]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.15
- PHP Version: 7.2

### Description:
Imagine a Resource with a lot of fields and relationships. Example: A real estate website.

The realty resource is incredibly large, going through presentation banners, texts, interior, exterior, 3D and construction photos, neighborhood, maps, so on and so on...

Currently the only way to make such a large resource on Voyager is to manually create views, but what if we could have some Layout options such as ACF Tabs?

It works like this: You create a new field called "Tab" in the BREAD panel, and everything bellow it will be in that tab, until it finds another tab, where the fields bellow it will be children of that tab instead.

However used ACF will understand this better, it's really nice!

**Comment by fletch3555** [comment]
BREAD is already being redesigned for a future release.  Thanks for the suggestion though.
