### ISSUE TITLE
The search form above the pop-up

### ISSUE THREAD

**Issue by defaultpage** [thedevdojo/voyager#2699]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.1
- Database Driver & Version: MySQL
- **Browser**: Chrome 63.0.3239.132 (dev, 64bit)
- **System**: Windows 10

### Description:
It is not possible to delete a multiple table rows since the button below the search form.

### Steps To Reproduce:
![](https://habrastorage.org/webt/kt/nq/0r/ktnq0r2bhqdijgf5f1rkxbujzgy.gif)

**Comment by defaultpage** [comment]
#2261 
#2076

> @emptynick: Republish your assets with
`php artisan vendor:publish --tag=voyager_assets --force`

I tried, but it doesn't work. Cache is empty. 
The project was created on 14 January 2018 at 11:36 AM.

**Comment by defaultpage** [comment]
#2261 
> The problem is with CSS class. As you can see.

It's all right:

![](https://habrastorage.org/webt/c_/ph/6t/c_ph6tvecxz1jj6vakqiojl1nrq.png)

**Comment by defaultpage** [comment]
> For any value above 100000, the error appears. 
```css
.modal-open .select2-container {
  z-index: 999999 !important;
  width: 100% !important;
}
```

**Comment by vblinden** [comment]
I can't reproduce this issue. Where can I find such a table that looks like yours?

**Comment by emptynick** [comment]
I think its BREAD-browse with serverside-pagination with opened delete-modal.
The search select2 is then on top of everything because its z-index is 99999 or so
