### ISSUE TITLE
image upload resize force to 1800px ?

### ISSUE THREAD

**Issue by Julien-Git1** [thedevdojo/voyager#2702]
- Laravel Version: 5.5.33
- Voyager Version: 1.0.15
- PHP Version: 7.0.5
- Database Driver & Version: MYSQL - 5.7.12

### Description:
When uploading an image (edit profile or post for example), the image is resize to 1800px.. For avatar it seems pretty big :)

Maybe it came from here: #1214 ?

Or a parameter is missing ?

### Steps To Reproduce:
Change your profile image and inspect the result uploaded image.

Regards.

**Comment by vblinden** [comment]
This was fixed in #2693. I guess this will be included in the next release of Voyager.

Thank you for reporting!

**Comment by Julien-Git1** [comment]
Ok nice,
It tried with the fix and i confirme it work.
Thanks !
