### ISSUE TITLE
Voyager relationship with same table (BelongsToMany)

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2703]
- Laravel Version: 5.5.#
- Voyager Version: 1.0.#
- PHP Version: 7.2.1
- Database Driver & Version:

### Description:

I stuck on creating relationship in voyager for same table.
Need one field to belongs to many other from same table.
Here is my First table:

table:products  
-id (auto_increment)  
-name (text)  
-other_products  
-timestamps  

 table:products_pivot  
 -product_id (main row for choosing other products - like similar products)  
 -product_id (storing what i have chosen)  

i can't have 2 columns with same name, but how to create this kind of relationship?
other_products must be multi-select pull down.
thanks.

**Comment by vblinden** [comment]
I don't think this is a Voyager related question. You can use a `parent_id` in your table. Maybe try our Slack group or other forums for your issue.

**Comment by fletch3555** [comment]
@writeritykirpetrov, looks like you might need a better understanding of how many-to-many relationships work (or your explanation just wasn't adequate for me to understand).  In either case, this question would require too much dialogue, so I also recommend asking on Slack (ours or LaraChat), or in one of the many Laravel-focused forums
