### ISSUE TITLE
Run Voyager in Laravel 5.6

### ISSUE THREAD

**Issue by isideas** [thedevdojo/voyager#2704]
- Laravel Version: 5.6.1
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.6

Description:
Voyager does not finish installation in Laravel 5.6

Steps To Reproduce:
1- composer create-project --prefer-dist laravel/laravel blog
2. composer require tcg/voyager

results:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.3

thanks for your help

**Comment by vblinden** [comment]
Laravel 5.6 is not supported at the moment. It will in version 1.1.
