### ISSUE TITLE
In VoyagerServiceProvider.php line 87: Class 'App\User' not found

### ISSUE THREAD

**Issue by OmarRobinson** [thedevdojo/voyager#2705]
- Laravel Version: 5.5
- Voyager Version: 1.0.15
- PHP Version: 7
- Database Driver & Version: MySQL 5.7

### Description:

After adding package I get the following error message. My model is located in a a subfolder Models as identified in side auth.php file

```
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\Models\User::class,
    ],
```

**Error Message**
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In VoyagerServiceProvider.php line 87:
                              
  Class 'App\User' not found  

```

### Steps To Reproduce:

Run `composer require tcg/voyager`

No **config\voyager.php** file was created after running `composer require tcg/voyager`. 

`php artisan voyager:install` also produce the same error message.

**Comment by fletch3555** [comment]
You have to change the user model in `config/voyager.php`, under `user` at `namespace`: https://github.com/the-control-group/voyager/blob/1.0/src/VoyagerServiceProvider.php#L86

`config/voyager.php` is created when running `artisan voyager:install`, not by running composer.  As a temporary solution, you can move the model back or create a new one in the expected location, publish the config file (`artisan vendor:publish --tag=config`: https://github.com/the-control-group/voyager/blob/1.0/src/VoyagerServiceProvider.php#L247), then change it and delete your temporary model.  Once the config is correct, you can run `artisan voyager:install`
