### ISSUE TITLE
The correct way to upgrade an existing voyager installation

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#2707]
- Laravel Version: 5.5.16
- Voyager Version: v1.0.15
- PHP Version: 7.2
- Database Driver & Version: xx

### Description:
Is there a correct way to upgrade my current voyager installation ? or just upload and replace would do , know that i have some views overridden 

### Steps To Reproduce:
upgrade

**Comment by vblinden** [comment]
You can take a look at our [upgrading guide](https://voyager.readme.io/docs/1-to-1). Even though it is not very extensive (we are working on that). If you have overwritten some views, take extra care.

**Comment by fletch3555** [comment]
The correct way is to upgrade it locally, test thoroughly, then push changes through whatever CI process you may have
