### ISSUE TITLE
Bread json not removing 

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2708]
- Laravel Version: 5.5
- Voyager Version: 1.0.15
- PHP Version: 7
- Database Driver & Version: /

### Description:
When i want to remove json code from additional details on bread its not working

**Comment by vblinden** [comment]
You can put `{}` as a workaround for now. We are working on a fix.

Thanks for reporting!

@fletch3555 Can you add label bug?

**Comment by emptynick** [comment]
This was fixed in #2919
