### ISSUE TITLE
php aritisan db::seed is invalid

### ISSUE THREAD

**Issue by tanteng** [thedevdojo/voyager#271]
- Laravel Version: 5.3.*
- Voyager Version: 0.9.34
- PHP Version: HHVM
- Database Driver & Version: MYSQL

### Description:
After installing Voyager, run php artisan db:seed, there is no error but database table have no data.

**Comment by marktopper** [comment]
What about `php artisan db:seed --class=VoyagerDatabaseSeeder`.

**Comment by tanteng** [comment]
Use like php artisan db:seed --class=UsersTableSeeder is OK,But should I run it one by one?
