### ISSUE TITLE
Is it possible to enable Voyager-multilingual BREAD for all custom tables?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2711]
- Laravel Version: 5.5.#
- Voyager Version: 1.0.#
- PHP Version: 7.2.1
- Database Driver & Version:

##
Is it possible to enable Voyager-multilingual BREAD for all custom tables?  
I enable the multilingual in voyager.php and only appears in Posts, Pages & Categories.

**Comment by vblinden** [comment]
You can add the `Translatable` trait to whatever model you want (`use TCG\Voyager\Traits\Translatable;`).

More info can be found here: https://github.com/the-control-group/voyager/pull/561

We are working on updating the documentation.
