### ISSUE TITLE
Table - Migration

### ISSUE THREAD

**Issue by HaroldV** [thedevdojo/voyager#2713]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.16
- PHP Version: 7.2
- Database Driver & Version:mysql

### Description:
When you create a table, this should automatically create the migration.

**Comment by vblinden** [comment]
Thanks for the feature request. It would be awesome if you could create a pull request for this.

**Comment by fletch3555** [comment]
This has been requested numerous times.  There's no good package currently that will build the migration file, and none of us have had the time to put something together.  I'm sure you could imagine it's not a simple task.

Also, I seem to remember someone making something similar to this (or at least starting to) a while ago, but I haven't heard anything about it, so I assume it's not complete.
