### ISSUE TITLE
  No query results for model [App\User] after trying to add new user on a fresh install

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#2715]
- Laravel Version: 5.5.38
- Voyager Version: latest
- PHP Version: 7.1
- Database Driver & Version: 5.6

### Description:
Just installed a fresh laravel 5.5 + latest voyager install but goot this error on terminal after trying to add user

### Steps To Reproduce:
install laravel + voyager and try : php artisan voyager:admin user@example.com

**Comment by fletch3555** [comment]
Do you have a model class at `app/User.php`?

**Comment by mavrickdeveloper** [comment]
<img width="825" alt="screenshot 2018-02-23 18 10 47" src="https://user-images.githubusercontent.com/1163627/36606783-04fdc89a-18c5-11e8-8abf-841b0501d567.png">

**Comment by fletch3555** [comment]
Just tested the same thing on my machine and I'm unable to reproduce it.  Make sure you're in the right directory and try `composer dump-autoload`.

**Comment by gbrits** [comment]
Happened for me when I installed without dummy data. Installing over installation using the `--with-dummy` flag fixes the issue. Steps to reproduce the issue:

1.) Create new Laravel
2.) Require Voyager
3.) Set up .env to DB
4.) Don't migrate
5.) Attempt install (without dummy)
6.) If successful, now try adding admin user, see 7.) if unsuccessful
7.) Rename Laravel migration file dates to earlier years (or at least months) `php artisan migrate:status` will show you that the batch might be too early on some Voyager migrations in reference to core Laravel migrations.

**Comment by patrick-brielmayer** [comment]
Had same issue here, forgot the --create at the end!
`php artisan voyager:admin your@email.com --create`

**Comment by AbouM007** [comment]
> Had same issue here, forgot the --create at the end!
> `php artisan voyager:admin your@email.com --create`

yes. it works :)

**Comment by usafLhb** [comment]
when  i  write the  commande php artisan voyager:admin your@email.com --create
i go t this  error
 Enter the admin name:
 >

  Aborted.

please  help

**Comment by fletch3555** [comment]
This has been closed for 2 years and was for a MUCH older version.  Please ask questions in slack instead
