### ISSUE TITLE
The avatar doesn't show image

### ISSUE THREAD

**Issue by hourdev** [thedevdojo/voyager#2726]
- Laravel Version: 5.5.*
- Voyager Version: ^1.0
- PHP Version: 7.1.3
- Database Driver & Version: MySQL

### Description:
 I have followed all the instruction on the internet already but none of them can solve.
1. php artisan storage:link
2. change the APP_URL: http://localhost:8000 to http://127.0.0.1:8000

Could you please propose any alternative solution to this issue?

**Comment by defaultpage** [comment]
Hi! Can you tell href of image?

**Comment by fletch3555** [comment]
As @ArtemMolotov has requested, please share the URL for your site (I'm guessing `http://localhost:8000/admin/`) and the URL/href for the image that's broken.

**Comment by hourdev** [comment]
Here's my URL for my site: http://127.0.0.1:8000/admin

**Comment by hourdev** [comment]
![screenshot 15](https://user-images.githubusercontent.com/36797315/36640217-1256bacc-1a4d-11e8-89c3-679683da4c7e.png)

**Comment by defaultpage** [comment]
@hourdev Can you open image if you delete `/public` from image `href`?

**Comment by simoebenhida** [comment]
go to `config/filesystem.php` and check if the public url is same as this one.
``` 
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

**Comment by hourdev** [comment]
@ArtemMolotov that works if i delete /public. So, what should I do next?

**Comment by hourdev** [comment]
@simoebenhida already tried but nth has changed

**Comment by simoebenhida** [comment]
can i see your public url on `config/filesystem.php` and your variable APP_ENV on `.env`

**Comment by hourdev** [comment]
![d](https://user-images.githubusercontent.com/36797315/36643544-6846ae24-1a7f-11e8-82cc-f1e78bb9b917.PNG)
![s](https://user-images.githubusercontent.com/36797315/36643545-68896228-1a7f-11e8-99be-3bb285d35fae.PNG)
@simoebenhida

**Comment by simoebenhida** [comment]
yes on your `filesystem.php` public array replace ` 'public' => 'url' ` with this 
``` 'url' => env('APP_URL').'/storage', ``` and it will work

**Comment by hourdev** [comment]
still doesn't work

**Comment by simoebenhida** [comment]
can i see the new `filesystem.php` changements

**Comment by hourdev** [comment]
![s](https://user-images.githubusercontent.com/36797315/36643604-6b1d2316-1a80-11e8-8c9c-8f17827cd1f4.PNG)

**Comment by simoebenhida** [comment]
yes remove public from ` 'local' => 'url'` too

**Comment by simoebenhida** [comment]
or is better to remove it you dont need `url` on your `local` driver its already called on `public` driver.

**Comment by hourdev** [comment]
![screenshot 17](https://user-images.githubusercontent.com/36797315/36643629-ee773990-1a80-11e8-9cdc-cda78ee75388.png)
![screenshot 18](https://user-images.githubusercontent.com/36797315/36643630-eec38aa2-1a80-11e8-8574-5a5a1edb387c.png)
still doesn't work

**Comment by hourdev** [comment]
yes. already removed, but doesn't work

**Comment by simoebenhida** [comment]
did you already run `php artisan config:cache` by any chance ?

**Comment by hourdev** [comment]
didn't.. haha
now, it is working. thanks a lot for your help!

**Comment by psger** [comment]
i meet the same question and i did all you said,however it still doesn't work

**Comment by KobiMontague** [comment]
albeit this is closed, people are still having an issue. the solution for me was to remove the symlink in the public folder, then ensure the URL was correct in the .env file

APP_URL=http://your-app.test

As this constant is used in the config/filesystems.php file

'url' => env('APP_URL').'/storage',

the storage folder is appended the URL, so a forward slash is required before storage

so the url will be http://your-app.test/storage

Then navigate to the voyager dashboard and an alert will be there to fix the symlink, once clicked it worked for me.

**Comment by prasathkarnan** [comment]
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => '/storage',
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

    ],

**Comment by prasathkarnan** [comment]
Dose not working please help

**Comment by arshomashohag** [comment]
After deleting the public/storage ( if any ) folder run the command 
php artisan storage:link
php artisan config:cache

And finally re-run the server .
It works for me .

**Comment by Jihun0109** [comment]
1. php artisan storage:link
2. php artisan config:cache
3. re-run the server 

It worked for me. Thank you @arshomashohag
