### ISSUE TITLE
Relationship display type

### ISSUE THREAD

**Issue by tr0yka** [thedevdojo/voyager#2727]
- Laravel Version: 5.4.30
- Voyager Version: 1.0
- PHP Version: 5.6.31
- Database Driver & Version: MySQL 5.7

How to display relationships as eg image or checkbox?

**Comment by defaultpage** [comment]
~~I think it's impossible now. I trying to add `relationship` option, but in image `href` attribute always inserted `id`... `"key": "imageslug"` doesn't work too...
Please, **wait** for a collaborator.~~
Update: relationships did not work properly before...

![](https://habrastorage.org/webt/mq/ot/s1/mqots1clt9db-5atsbkaboht8mw.png)

**Comment by netdelight** [comment]
Same problem here, is there a way to display the relationship as a text input ?

**Comment by defaultpage** [comment]
@netdelight, Hi! You can create a relationship using the options as in the example above (docs for voyager 0.11). It's work with PR #2871, But do not forget to add a needed `method` in your class! For example -- `parentId` or `parent` (need to add `"method": "parent"` in the options).

@tr0yka, by the described method, I was able to display the `relationship as an image`.

**Comment by emptynick** [comment]
Please don't suggest using legacy code which isn't mentioned anywere.
We can and will remove this without further notification somewhen.
You can override a single formfield and do whatever you want to do with it with v1.2.
Closing
