### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#2732]
Laravel Version: 5.5.*
Voyager Version: 1.0
PHP Version: 7.2
Database Driver & Version: -

### Description:
Not cleaning fields, after update  menu

### Steps To Reproduce:
Open some menu.
Push 'Edit',  some  menu  item
Cancel 'Edit'  menu  item
Create New  Menu  item
Title of the Menu Item  <----  the field is filled with the name of the previous menu

I not  check another field, maby another field  filled of the previous menu
sorry  my english (Google Translate  my friend)

**Comment by webtunel** [comment]
Disable cache in browser, if you use Google Chrome, right click and go to "Inspect", after go to network tab and check disable cache option.

**Comment by emptynick** [comment]
Fixed in #2837
