### ISSUE TITLE
Multiple fields to display other Model in a Relationship

### ISSUE THREAD

**Issue by julienduthoit** [thedevdojo/voyager#2734]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:
I have two models with a belongsTo relationship between them.
Is there an easy way in Voyager to use multiple columns to display the dropdown select second model by editing the first?

I can only chose one column (name) for the moment in the BREAD edition. Let's say I want to display the model with a concatenation of the fields "name"_"value". Is there a way to achieve that in Voyager?

Thanks,

![chrome_2018-02-26_18-41-56](https://user-images.githubusercontent.com/685799/36685837-daf04e76-1b24-11e8-9247-b23a34d80666.png)

**Comment by fletch3555** [comment]
Not really.  You could try a few different things.  Either make a dynamic field in the database and let Voyager use that, or use an `accessor` method for one of the fields.  I can't guarantee Voyager will handle either of these options well, but it's worth a shot.  This is certainly not a supported feature right now.

**Comment by fletch3555** [comment]
If you need help with one of those possible workarounds, feel free to join our Slack group and ask.

**Comment by paulobarcelos18** [comment]
I also need a solution to this problem.

**Comment by emptynick** [comment]
We actually have a way for a few month now and its also mentioned in our Docs.

**Comment by CiaranR** [comment]
@emptynick Do you have a link to the docs where you can display more than one column in the relationship bread?

**Comment by emptynick** [comment]
https://voyager.readme.io/docs/custom-relationship-attributes

**Comment by kashif-saleem** [comment]
How can I create dependent dropdown i have School, Branches and Student Bread, now i want to add student in which if i choose school then branches dropdown will get branches for that particular schools. any help will be appreciated.

**Comment by mm2tmm** [comment]
pls see:
https://voyager-docs.devdojo.com/customization/custom-realtionship-attributes
