### ISSUE TITLE
Undefined variable: dataType

### ISSUE THREAD

**Issue by SturmB** [thedevdojo/voyager#2735]
- Laravel Version: 5.6.5
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.2
- Database Driver & Version: MySQL 5.7.21 Homebrew

### Description:

Relationship creation during BREAD editing throws error message `Undefined variable: dataType`.

### Steps To Reproduce:

1. Create two database tables with a one-to-many relationship. Not sure if defining foreign keys beforehand makes a difference. (Both of my tables use `VARCHAR(45)` for their `id`s.)

#### ---EDIT---
I even tried creating two new simple tables from within Voyager as a test. Both use standard auto-incrementing integers for their primary keys:
```
authors
    id (int, unsigned, auto_increment, primary key)
    name (varchar(250), not null)
    timestamps
books
    id (int, unsigned, auto_increment, primary key)
    title (text, not null)
    author_id (int, unsigned, not null)
    timestamps
```
I did _not_, however, create any foreign key constraints nor any additional indexes on the tables, but I did have Voyager auto-create models for them. I also tried "Create a Relationship" both _before_ and _after_ manually editing their Models to add their respective `hasMany()` and `belongsTo()` methods.

The problem still occurs. Thus, the error occurs even with freshly-made database tables from within Voyager itself.
#### ---END EDIT---

2. Create BREAD for both tables.
3. Attempt to create a BREAD Relationship for one of them.
<img width="612" alt="screen shot 2018-02-26 at 2 12 42 pm" src="https://user-images.githubusercontent.com/6216224/36690244-b65395f2-1aff-11e8-8942-f0c164473ed3.png">
4. Witness error message.
<img width="1231" alt="screen shot 2018-02-26 at 2 12 59 pm" src="https://user-images.githubusercontent.com/6216224/36690282-d11be556-1aff-11e8-9f15-ad867b01a731.png">

(Not sure why `"categories"` is listed as a `relationship_pivot`, as there doesn't need to be a pivot table for this one-to-many relationship, let alone using that Voyager built-in table for one. Also not sure if it's even relevant to this error.)

**Comment by emptynick** [comment]
This was fixed in #2757
