### ISSUE TITLE
Can't create BREAD

### ISSUE THREAD

**Issue by webtunel** [thedevdojo/voyager#2737]
- Laravel Version: 5.5.0
- Voyager Version: #.#.#
- PHP Version: 7.2.0
- Database Driver & Version: 10.1.30-MariaDB

### Description:
BREAD, not create Model and Controller
### Steps To Reproduce:
When i try to make BREAD on some table, e.g movies. BREAD return alert "Saving Failed generic.exception: Class App\Eeee does not exist", when i manulay create Model and Controller, Bread be created but, not work when you click on link in right menu, i get message "Sorry, the page you are looking for could not be found.". Controller and Model are empty after creating bread.

**Comment by picepice** [comment]
Same problem

**Comment by fletch3555** [comment]
This is simply a misunderstanding of how Voyager works.

There is no need to create a controller.  Voyager will handle adding the routes automatically, and they will use a default controller provided by Voyager.  If you NEED to further customize that controller, then you can follow the steps in our documentation (create a new controller extending ours, change the BREAD settings to tell it to use your new controller, then add what you need).

For the model, Voyager will only create it IF you tell it to by toggling the appropriate field ("Generate Model" I believe) when creating the BREAD for your table.  The model class will be created under the configured model namespace (`App\` by default).


Just as a final note, we require all version information be provided as accurately as possible (`1.0.16` is so much better than `1.0`).  Especially the Voyager version.  We're not currently following semver very well, so there are still significant differences between versions.

**Comment by JFOC** [comment]
If the table was created already, can we generate the Model ?

**Comment by emptynick** [comment]
Not from the UI, but you can do it from the console:
`voyager:make:model --name=YourModelName`

**Comment by JFOC** [comment]
`php artisan make:model --name=ModelName` I think

**Comment by thegugaru** [comment]
I hate to necro this thread but I am experiencing the same exact thing. I create the table in voyager, then I go into bread and it get this error (see screenshot link below) and I have tried it all sorts of ways and it does create the table and model but the controller is never once created! Even deleting bread and recreating it does not produce the model.
There does seem to be an issue in the system. I am running the most recent versions of Laravel and Voyager so some direction would be greatly appreciated.
[
![image](https://user-images.githubusercontent.com/31781396/69479826-bb4d0600-0dcf-11ea-98aa-740e7dcd2942.png)
](url)

**Comment by thegugaru** [comment]
As a note the ONLY WAY I can get it to work is to make it use the default BREAD controller and not provide my own controller name as it appears that it does not create the custom controller. This should be looked into and fixed.

**Comment by MrCrayon** [comment]
@thegugaru nowhere while you are creating BREAD it says that is going to generate a Controller and you can find the reason if you read the previous comments.

**Comment by fletch3555** [comment]
Please don't necro threads... especially one that's been closed for nearly 2 years and for a much older version.  Instead, create your own issue and reference this one with a link.  We have an issue template that will prompt you for the appropriate information when submitting it.

**Comment by fletch3555** [comment]
But yes, @MrCrayon is right. Voyager doesn't create a controller for you, nor does it say anywhere that it would.

If you have further questions about this, please ask in slack.
