### ISSUE TITLE
normal user can change to admin user

### ISSUE THREAD

**Issue by foryoufeng** [thedevdojo/voyager#2742]
- Laravel Version: 5.4.30
- Voyager Version:1.0.16
- PHP Version:5.6
### Description:
I found a bug, that is, when I create an normal user in the user table, it can modify its role and upgrade it to the administrator. How can I solve this problem?

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/6702914/36780570-53847422-1cae-11e8-82c1-3bb9eeefe3f7.png)

**Comment by fletch3555** [comment]
Not a bug, this has been reported numerous times in the past.  Voyager is not meant to be a CMS, and therefore doesn't make any assumptions about your data/site.  You're welcome to override the view and add your own check.
