### ISSUE TITLE
tabindex="-1" on database/ select elements

### ISSUE THREAD

**Issue by mattrabe** [thedevdojo/voyager#2744]
- Laravel Version: 5.5.35
- Voyager Version: 1.0.16
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.6.35

### Description:

When creating or editing a database, the select elements for both Type and Index have `tabindex="-1"`. Why? It is slightly annoying to me that I cannot tab through each input and instead have to click into those selects (particularly Type). Is there some reason for this, or is it oversight?

### Steps To Reproduce:

1. Log in to Voyager
1. Go to Tools -> Database
1. Click "+ Create New Table"
1. Click into the input under "Name"
1. Press tab repeatedly and notice that the select elements are skipped in the tab order

**Comment by fletch3555** [comment]
I'm not aware of any reason for that (probably copy/paste), but it's possible there was a reason.  Feel free to edit it under vendor and test.  If it still works fine, I'd be open to a PR for it.
