### ISSUE TITLE
Enhancement Request: utf8mb4 - utf8mb4_unicode_ci as default collation in MySQL

### ISSUE THREAD

**Issue by SturmB** [thedevdojo/voyager#2745]
- Laravel Version: 5.6.5
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.2
- Database Driver & Version: MySQL 5.7.21 Homebrew

### Description:
When using MySQL, it seems that creating a new database table using the Voyager UI does so with a `utf8` character set and `utf8_unicode_ci` collation. This goes against the [Laravel default](https://laravel.com/docs/5.6/migrations#creating-indexes) and has [caused](https://news.ycombinator.com/item?id=14747699) [so](https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql) [many](https://www.eversql.com/mysql-utf8-vs-utf8mb4-whats-the-difference-between-utf8-and-utf8mb4/) [headaches](https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434) for MySQL users (including myself).

I'd like to propose that Voyager creates tables with a default character set of `utf8mb4` and collation of `utf8mb4_unicode_ci` when the database driver is MySQL or one of its variants (MariaDB, PerconaDB, etc.).

**Comment by fletch3555** [comment]
It only goes against the "laravel default" since 5.5.  We still support 5.4 (though 1.1 will likely drop support for 5.4).  I'm open to PRs for this change, though it will need to be for the `1.x-dev` branch

**Comment by emptynick** [comment]
5.4s default charset is `utf8mb4` also.
See [here](https://laravel.com/docs/5.4/migrations#creating-indexes)
