### ISSUE TITLE
Camel Case table name issue

### ISSUE THREAD

**Issue by HeartlandTechie** [thedevdojo/voyager#2748]
- Laravel Version: 5.6
- Voyager Version: 1.0
- PHP Version: PHP 7.1.8-1ubuntu1
- Database Driver & Version: MySQL 5.7.21-0ubuntu0.17.10.1  

### Description:

Camel Case table name produces wrong table name when using BREAD.  

### Steps To Reproduce:

Create table BradTest.  Tables shown in MYSQL database - BradTest.  
Base table or view not found: 1146 Table 'brad_tests' doesn't exist (SQL: select * from `brad_tests` order by `created_at` desc)

**Comment by fletch3555** [comment]
https://laravel.com/docs/5.6/eloquent#eloquent-model-conventions
