### ISSUE TITLE
Unknown column in BREAD read

### ISSUE THREAD

**Issue by HeartlandTechie** [thedevdojo/voyager#2749]
- Laravel Version: 5.6
- Voyager Version: 1.0
- PHP Version: PHP 7.1.8-1ubuntu1
- Database Driver & Version: MySQL 5.7.21-0ubuntu0.17.10.1

### Description:

Added widgets table, no camel case, and error after adding BREAD. "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'order clause' (SQL: select * from `widgets` order by `created_at` desc)"

### Steps To Reproduce:

Create new table widgets. 

Field | Type | Null | Key | Default | Extra
-- | -- | -- | -- | -- | --
id | integer | NO | PRI |   | auto_increment
ModelNumber | integer | YES |   |   |  
ModelName | text | YES |   |   |  
Price | float | YES |   |   |  
Description | text | YES |   |  

Create BREAD.
Browse BREAD.
Get Error Message.

**Comment by fletch3555** [comment]
https://laravel.com/docs/5.6/eloquent#eloquent-model-conventions

**Comment by HeartlandTechie** [comment]
I can see these things as issues, but if this is a general purpose admin area then creating the timestamps might be a default thing for any table being manipulated.  At the very least a "hey you need to add this" on the submit button might be nice.  Just a suggestion.
