### ISSUE TITLE
Voyager compatibility with cviebrock/eloquent-sluggable

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#2752]
- Laravel Version: 5.5
- Voyager Version: 1.0.16
- PHP Version: 7.0
- Database Driver & Version: MariaDB 

### Question:
I need to generate a slug for some of my tables.
I want to know if I need and I can use an external slug package like 
**cviebrock/eloquent-sluggable**?

Thanks.

**Comment by marktopper** [comment]
Well, the package [`cviebrock/eloquent-sluggable`](https://github.com/cviebrock/eloquent-sluggable) inserts the `slug` on save, so you would just need to set that up and remove turn of `add` and `edit` for that column in order to get it working automatically.
