### ISSUE TITLE
Installation problem in Laravel 5.6.7

### ISSUE THREAD

**Issue by sonynlaw** [thedevdojo/voyager#2753]
- Laravel Version: 5.6.7
- Voyager Version: 1.0
- PHP Version:7 .1.12
- Database Driver & Version: mySql 4.7.7

### Description:
- Installation request for laravel/framework (locked at v5.6.7, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.7].
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[1.0.x-dev, v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].
Installation failed, reverting ./composer.json to its original content.

**Comment by fletch3555** [comment]
Voyager 1.0 does not and will not support 5.6.  We have tentative support in the 1.x-dev branch planned for a 1.1 release.

Please use the search feature before opening issues. This has been asked/reported numerous times already.
