### ISSUE TITLE
Error when creating BREAD for table

### ISSUE THREAD

**Issue by NichoTheMan** [thedevdojo/voyager#2758]
- Laravel Version: 5.5.36
- Voyager Version: 1.0.16
- PHP Version: 7.0.25
- Database Driver & Version:MySQL for Linux v14.14 dist 5.7.21

### Description:

When attempting to create BREAD on the table i created through voyager i get an error;
`Saving failed generic.exception: No query results for model [TCG\Voyager\Models\Role].`
![error_1](https://user-images.githubusercontent.com/5790097/36934863-27f42610-1ef0-11e8-9d5b-535dc7bf688a.png)

The table is created, but when i click browse BREAD i get this error;
`AccessDeniedHttpException
This action is unauthorized.`

### Steps To Reproduce:

Create BREAD on a table

**Comment by napestershine** [comment]
You need to make Class by yourself. if this class will not exist it will throw this error.

**Comment by marktopper** [comment]
Please check the `users` table for users with `null` as `role_id`.
I believe that can also be a reason for this.

**Comment by NichoTheMan** [comment]
Another developer on this project accidentally changed the role name of `admin` to his name. He thought he was changing his username.

By changing the Administrators roles name back to `admin` everything worked.
