### ISSUE TITLE
Custom dates format and date.blade.php

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#2760]
- Laravel Version: 5.5
- Voyager Version: 1.0.13
- PHP Version: 7
- Database Driver & Version: MariaDB 5.5

### Description:
If I store my dates in the DB using a non standard format like:
` "format": "%d/%m/%Y"`
When I'm in edit-bread view date fields are not populated (empty).
I need to change date.blade.php (formfields view) to show proper data in 
the form. 

`<input type="date" class="form-control" name="{{ $row->field }}" placeholder="{{ $row->display_name }}" value="@if(isset($dataTypeContent->{$row->field})){{`
 **gmdate('d/m/Y')** 
`,strtotime(old($row->field, $dataTypeContent->{$row->field}))) }}@else{{old($row->field)}}@endif">`

I think that this is an issue.

**Comment by defaultpage** [comment]
Can you try to apply changes from #2370 or/and #2697?

**Comment by cyrildewit** [comment]
Ping @reficul. Did these PR's fixed your issue?

**Comment by fletch3555** [comment]
For the record, both PRs mentioned above were merged and included in the recent v1.1.0 release.  Please try that version and let us know if it's still an issue.
