### ISSUE TITLE
New feature: Display multiple fields for relationships

### ISSUE THREAD

**Issue by banh-gao** [thedevdojo/voyager#2764]
### Description:
I'm trying to allow to display more than just one field for relationships and for lookups in insert and update operations.
I made some progress but i need some help in completing the integration with voyager.
See here:
https://github.com/banh-gao/voyager/tree/feat.multicol-rel-display

**Comment by marktopper** [comment]
This should be made as a pull request.

**Comment by fletch3555** [comment]
This will be possible in a future release. There has been significant progress already made.  Not saying you need to stop your progress, but just don't want you to waste your time.  No expected release date at this time

**Comment by banh-gao** [comment]
Good, but I needed it now :)
Can you give me a reference on where to look and maybe to contribute on it?

**Comment by fletch3555** [comment]
It's part of a major reorganization we're doing for 2.0, so we're keeping a fairly tight leash on it right now.  Once the overall reorg is more concrete and we have documentation in place, we'll open it up for community contribution.

**Comment by banh-gao** [comment]
Ok, I understand. Looking forward for 2.0.
