### ISSUE TITLE
Installation fails with apparent Illuminate/support incompatibility (Laravel 5.6.7)

### ISSUE THREAD

**Issue by larry-tx** [thedevdojo/voyager#2765]
- Laravel Version: 5.6.7
- Voyager Version: ^1.0 (installing with composer require tcg/voyager)
- PHP Version: 7.2.2
- Database Driver & Version:5.7.21

### Description:
Installing with Composer require tcg/voyager fails due to an apparent Illuminate/support incompatibility. See attached file for error message.
[Voyager installation error.txt](https://github.com/the-control-group/voyager/files/1778814/Voyager.installation.error.txt)

### Steps To Reproduce:
Attempt to install with composer require tcg/voyager

**Comment by marktopper** [comment]
Voyager is not fully ready for Laravel 5.6.
However, you can use the `v1.x-dev` branch which is ready for it but not yet released.

**Comment by larry-tx** [comment]
You may be interested to know that v. 1.0.x-dev (couldn't find a 1.x-dev branch) also fails with Illuminate issues (see attached copy of the error messages). Thought you'd want to know as you work on the release. By the way, do you have any timeline on the release day for a 5.6 compatible release?

[Voyager 1.0.x-dev install failure.txt](https://github.com/the-control-group/voyager/files/1782194/Voyager.1.0.x-dev.install.failure.txt)

**Comment by fletch3555** [comment]
`v1.0.*` is the current active release (currently `v1.0.16`), so of course it does.  If you want to use the `1.x-dev` BRANCH (not release), you have to set your Voyager version in composer.json to "dev-[branchName]" (`dev-1.x-dev`).  This is all covered in the composer documentation
