### ISSUE TITLE
BREAD input type set for relationship table affects 

### ISSUE THREAD

**Issue by damms005** [thedevdojo/voyager#2766]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: MariaDB Server version: 10.1.13

### Description: 
In a BelongsTo and HasMany relationship, when the BREAD Input Type is not set to Number for the relationship table, editing/adding the relationship will always set it to th value '1'. If this is intended behaviour, it should be added to documentation, rather than cause the needless wasted work-hours. The Voyager tool is extremely so wonderful for this kind of minor issue!

### Steps To Reproduce:
1. Create `cars` table with all as normal (its bells and whisltes...models, controllers, etc)
2. Create `manufacturers` too
3. Do BREAD for them both, with HasMany defined on `manufacturers` table and BelongsTo relationship efined on the `cars` table
4. Set Input type for the `manufacturer_id` column on `cars` as Checkbox
5. Add a couple manufacturers of cars
6. Try add/edit `cars` BREAD and select one of the manufacturers previously added
This will always result in the manufacturer with `id` = `1` to be set, irrespective of the value of manufacturer selected from the list.

I opine that this should be added to the documentation if it is intended behaviour. More appropriately, such integer values should not countenance the Input type - since the entry data is already the data type expected by the database (Chrome devtools correctly shows that the add/edit BREAD from actually did submit the correct/selected manufacturer)

**Comment by emptynick** [comment]
Each Formfield parses the content, so if it is set to checkbox it will convert to a bool value.
So if you select an element it will convert to true (1) if you dont select an item it will be false (0).
I think this makes perfect sense.
Otherwise it would die trying to write e.g. `2` into a `Tinyint(1)` field

But its a good addition for the `Troubleshooting` section

**Comment by fletch3555** [comment]
Please suggest documentation updates through the readme.io page.  On each page, you'll see a "Suggest Edits" button in the top-right.
