### ISSUE TITLE
Admin/Login not accessible through ssh remote

### ISSUE THREAD

**Issue by Tundrasama** [thedevdojo/voyager#2767]
- Laravel Version: 5.5.36
- Voyager Version: 5.5
- PHP Version: 7.0.25-0ubuntu0.16.04.1
- Database Driver & Version: MySQL

### Description:
Setup a droplet with Digital Ocean, setup LAMP + Laravel, followed instructions for Voyager installation. I can access my laravel app through http://ip/laravelapp/public and http://localhost:8000/laravelapp/public. However, I can only access the voyager admin login if I log into the droplet through digital ocean's console and go to http://localhost:8000/admin/login. I'd like to be able to reach remotely, but haven't been able to.

.env app section:
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:<Key>
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

I've tried changing app_url to a number of different things with no success.

.htaccess:
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

I have a feeling like I've missed something small, but I've already spent a considerable amount of time trying to get it running.

Any help is appreciated.

Thank you.

### Steps To Reproduce:
Fresh Voyager Install
Configured SSH port forwarding in Putty - L8000 localhost:80
Login through putty, navigate to /var/www/public_html/laravelapp -- run php artisan serve

**Comment by fletch3555** [comment]
I have absolutely no idea what you think you're trying to do, but it's definitely not the right way to do it.  Please describe it better and I'll try to give a better answer.

Also, this is almost certainly not a voyager issue

**Comment by Tundrasama** [comment]
Without putty and ssh tunneling, if I wanted to access my laravel app, I use http://droplet-public-ip/laravelapp/public. With putty and ssh tunneling, I can reach the local host of my droplet remotely from my computer and access the same laravelapp at http://localhost:8000/laravelapp/public. I would like to be able to access the admin/login page for voyager in a similar manner. Currently, I can only access it if I login to the droplet's ubuntu desktop and use localhost:8000/admin/login from a browser.

Yeah, I don't believe it is a voyager issue, most likely something I did wrong, but thought this would be the best place to ask to see if anyone had similar difficulties or suggestions.

**Comment by fletch3555** [comment]
First, you really shouldn't be exposing your laravel site under the IP like that, because http://droplet-public-ip/laravelapp/.env is very likely public now.

Now, you say you've set up LAMP, then later say you're running `php artisan serve`.  `artisan serve` should ONLY be used for local development.  Remote servers (regardless of whether it's "production" or not), should have a properly configured webserver (apache or nginx) instead.  Once that's done, you won't have to deal with port 8000 everywhere.  You'll have URL rewrite set up and functional, and your .env will be secure since you'll have vhosts properly configured.

I'm still not sure what your actual problem is, because you haven't really said what is/isn't working.

**Comment by marktopper** [comment]
Closed due to inactivity
