### ISSUE TITLE
Voyager::model not always used

### ISSUE THREAD

**Issue by f0reclone** [thedevdojo/voyager#2769]
- Laravel Version: 5.5
- Voyager Version: 1.0.16
- PHP Version: 7.0
- Database Driver & Version: mysql

### Description:
I wanted to override some models like Permission and Roles so I could use them with hyn/multi-tenant.
Then I discovered that even when I stated Voyager::useModel for the Models in my AppServiceProvider sometimes Voyager didn't use my models (for example in the seeder classes). You can easily verify this by searching usages on a Laravel model and you see that oftentimes the model is directly used instead of being queried with Voyager::model.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3903
