### ISSUE TITLE
Undefined variable dataType

### ISSUE THREAD

**Issue by rishabharyal** [thedevdojo/voyager#2770]
- Laravel Version: 5.6.*
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.0 on Ubuntu 16.04 (Laravel Homestead) running on WIndows 10
- Database Driver & Version: MySQL 5.7.21

### Description:
I wanted to create a relationship from BREAD section, using Voyager of course. Teachers table got user_id as foreign constraint that references id on users tab.e (ran through migration). Now when, I try creating  BREAD from Voyager, I get error like this: 

ErrorException (E_NOTICE)
Undefined variable: dataType.
Its in line #220 on vendor/tcg/voyager/src/Http/Controllers/VoyagerBreadController.php. As i inspected the code, the given variable was not declared.

![capture](https://user-images.githubusercontent.com/26625693/37023983-bdba2a44-214f-11e8-9035-1eb4c5a4e72b.PNG)

### Steps To Reproduce:
I think we need to declare the var first.

**Comment by emptynick** [comment]
This is known, see https://github.com/the-control-group/voyager/issues/2735
And it will be fixed in https://github.com/the-control-group/voyager/pull/2757
