### ISSUE TITLE
Image doesn't show in voyager admin panel after uploading cPanel

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2772]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:
I have uploaded my laravel project in cPanel. Previous images are shown successfully but the newly added images are not showing.

![capture](https://user-images.githubusercontent.com/22347660/37027344-48135ec6-215b-11e8-8b42-4283dac8ff88.PNG)

Here last 2 images are already in the project before uploading in cPanel. After uploading the project successfully in cPanel I have try to upload an image but it is not shown which is first one.

Anybody help ?

**Comment by emptynick** [comment]
Looks like your symlink was "converted" to a normal folder after uploading (with FTP I guess)?
Try running `php artisan storage:link`

**Comment by arafatrahman13** [comment]
This is not running locally ... runnign in cPanle. How do I use this command line there !!!

**Comment by emptynick** [comment]
Through SSH or something.
If you dont have SSH access, go to your `public` folder and rename `storage` to something different.
Then open Voyager and it will ask you to create the storage-symlink.

**Comment by arafatrahman13** [comment]
@emptynick ... I have solved the issues. My image is not saved in the folder where i want. So I have change the image upload path and got my result. For that change the path of storage driver in `config/filesystems.php`. Change the path from `storage_path()` to `public_path()`.

`'public' => [
    'driver' => 'local',
    'root' => public_path('app/public'),
    'url' => env('APP_URL').'/storage',
    'visibility' => 'public',
],`

**Comment by NasirHussainAbbasi** [comment]
its not working for me
![Screenshot_1](https://user-images.githubusercontent.com/54266172/63252014-6ce81280-c288-11e9-85ab-10398347a44f.png)
![Screenshot_2](https://user-images.githubusercontent.com/54266172/63252074-9739d000-c288-11e9-8243-8538dd98df86.png)

**Comment by fletch3555** [comment]
@NasirHussainAbbasi, please don't comment on very old closed issues, especially if a solution has been identified.  Odds are it's from a much older version, so the solution is likely not relevant to your problem.

Instead, you can ask in our Slack group (#help channel) or create your own issue.
