### ISSUE TITLE
VoyagerServiceProvider Class There are some design issues.

### ISSUE THREAD

**Issue by t0rjan** [thedevdojo/voyager#2773]
- Laravel Version: 5.5.36
- Voyager Version: v1.0.16
- PHP Version:7.1.9
- Database Driver & Version:5.6.29

### Description:
vendor/tcg/voyager/src/VoyagerServiceProvider.php:331

`            VoyagerFacade::addFormField("TCG\\Voyager\\FormFields\\{$class}");`
vendor/tcg/voyager/src/VoyagerServiceProvider.php:334

`        VoyagerFacade::addAfterFormField(DescriptionHandler::class);`

There is a small problem you want to submit to voyager.

# register  method of VoyagerServiceProvider Class:
``` 
/**
* Register the application services.
*/
public function register()
{
$this->app->register(VoyagerEventServiceProvider::class);
$this->app->register(ImageServiceProvider::class);
$this->app->register(WidgetServiceProvider::class);
$this->app->register(VoyagerHooksServiceProvider::class);
$this->app->register(DoctrineSupportServiceProvider::class);

    $loader = AliasLoader::getInstance();
    $loader->alias('Voyager', VoyagerFacade::class);

    $this->app->singleton('voyager', function () {
        return new Voyager();
    });

    $this->loadHelpers();

    $this->registerAlertComponents();
    $this->registerFormFields();
    $this->registerWidgets();

    $this->registerConfigs();

    if ($this->app->runningInConsole()) {
        $this->registerPublishableResources();
        $this->registerConsoleCommands();
    }

    if (!$this->app->runningInConsole() || config('app.env') == 'testing') {
        $this->registerAppCommands();
    }
}
``` 

# registerFormFields  method of VoyagerServiceProvider Class:
``` 
protected function registerFormFields()
    {
        $formFields = [
            'checkbox',
            'color',
            'date',
            'file',
            'image',
            'multiple_images',
            'number',
            'password',
            'radio_btn',
            'rich_text_box',
            'code_editor',
            'markdown_editor',
            'select_dropdown',
            'select_multiple',
            'text',
            'text_area',
            'timestamp',
            'hidden',
            'coordinates',
        ];
        foreach ($formFields as $formField) {
            $class = studly_case("{$formField}_handler"); VoyagerFacade::addFormField("TCG\\Voyager\\FormFields\\{$class}");
        }

        VoyagerFacade::addAfterFormField(DescriptionHandler::class);

        event(new FormFieldsRegistered($formFields));
    }
``` 
# Just finished loading, it should be used in registerFormFields inside.
``` 
             $ this-> app-> make ('voyager') -> addFormField ("TCG \\ Voyager \\ FormFields \\ {$ class}");

         $ this-> app-> make ('voyager') -> addAfterFormField (DescriptionHandler :: class);


```

**Comment by t0rjan** [comment]
When we replace VoyagerServiceProvider, the original call addFormField method and addAfterFormField method, they will not take effect.

**Comment by marktopper** [comment]
It could be splitted into multiple methods for easier overwriting.
We are open to pull requests.

**Comment by smartcoder01** [comment]
Probably happened many times, but please explain, I beg you.

Class 'TCG \ Voyager \ VoyagerServiceProvider' not found

I have the / vendor folder in the root, and I have a folder with in the laravel project which is in /public_html/site.сom/vendor.

There is an installation in / vendor to the root.

How to install a voyager in the c / laravel folder

thanks

**Comment by t0rjan** [comment]
@smartcoder01 Sorry, my version at the time was: Voyager Version: v1.0.16

**Comment by t0rjan** [comment]
@smartcoder01 but , u can to install Voyager in your project, u need a document of Voyager.

**Comment by t0rjan** [comment]
@smartcoder01  This is a project I have a long time ago, I think you need to install the latest version of Voyager, you can view its related documentation, this address is: https://docs.laravelvoyager.com/getting-started/installation

**Comment by t0rjan** [comment]
Why you can't find the file, maybe because you didn't execute it: php artisan vendor:publish --provider="TCG\Voyager\VoyagerServiceProvider" @smartcoder01

**Comment by t0rjan** [comment]
I hope this will help you. If you have been unable to solve it, I can provide remote assistance for you. You can communicate with me by email. I hope to promote the ecology of Voyager.
My email address is: 66666r00t@gmail.com 

@smartcoder01

**Comment by fletch3555** [comment]
@t0rjan, can this one be closed? It's quite old and sidetracked by @smartcoder01 posting unrelated questions.

**Comment by t0rjan** [comment]
@fletch3555 Yes, although I hope to help him, it does not matter what I posted.

**Comment by fletch3555** [comment]
Understandable. I'm just trying to keep threads focused, and he posted the same comment on a number of super old issues
