### ISSUE TITLE
Undefined property: Illuminate\Auth\AuthManager::$user

### ISSUE THREAD

**Issue by tamersolieman** [thedevdojo/voyager#2774]
- Laravel Version: 5.6.7
- Voyager Version dev-1.x-dev
- PHP Version:  7.1.7

- Database Driver & Version: MySQL

### Description:
After installation voyager and login to admin, I got this ErrorException Undefined property: Illuminate\Auth\AuthManager::$user

### Steps To Reproduce:

I can't install voyager by the composer require tcg/voyager, so I add  "tcg/voyager": "dev-1.x-dev" to composer.json

**Comment by fletch3555** [comment]
Fixed in #2775 

Also, Voyager version number is required when submitting issues.

**Comment by tamersolieman** [comment]
How can I get Voyager version?

**Comment by cyrildewit** [comment]
@tamersolieman `composer show -i`

[Stackoverflow question](https://stackoverflow.com/questions/15185459/how-to-get-list-of-all-installed-packages-along-with-version-in-composer)

**Comment by tamersolieman** [comment]
Thanks @cyrildewit 

Voyager Version dev-1.x-dev 

@fletch3555

**Comment by hesham14yahia** [comment]
I have the same issue, did you found any solution ??
