### ISSUE TITLE
Multi-select overlapping other multi-select

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#2776]
- Laravel Version: 5.5
- Voyager Version: 1.0.13
- PHP Version: 7

(tested with safari)

### Description:
If you on your form have two multiple-select fields close to each other and you try to select an item on the first dropdown menu you select instead the second multi select field.

**Comment by emptynick** [comment]
I submitted a [fix](https://github.com/the-control-group/voyager/pull/2801) for this.
You can try it out if you want.

**Comment by emptynick** [comment]
This was fixed in #2801
