### ISSUE TITLE
How to upload a voyager admin panel in cPanel?

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2778]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version:

### Description:

I have already uploaded a voyager admin panel like a laravel project. while I am using `myurl.com`...it works but if I use `myurl.com/admin`...it will give error that `Sorry, the page you are looking for could not be found`....Is there any other special way to upload a voyager admin panel in cPanel ?

**Comment by emptynick** [comment]
Try opening `myurl.com/public/admin`.
If that works you have to change your apache/nginx config

**Comment by vblinden** [comment]
Did you add the `Voyager::routes()` to `web.php`?

**Comment by arafatrahman13** [comment]
vblinden....Successfully uploaded voyager admin panel in cPanel. Yes I have added that correctly. Problem is my `document root` is not correctly assigned for subdomain. Now it's alright :)
