### ISSUE TITLE
Adding/Editing Relationships doesn't work

### ISSUE THREAD

**Issue by SebaSOFT** [thedevdojo/voyager#2779]
https://github.com/the-control-group/voyager/blob/aa33a46e667dc65c16bad91ff28450a8e35685e4/src/Http/Controllers/VoyagerBreadController.php#L218

I fixed addin it with 
`$dataType = Voyager::model('DataType')->find($request->data_type_id);`
On the line avobe.

Still fails the next screen after trying to create links to edit/delete relationships, which doesn't exists. see #2756

Sry about creating a bug on a dev branch, but I'm using Laravel 5.6 being almost a month old.

**Comment by emptynick** [comment]
True.
Duplicate of https://github.com/the-control-group/voyager/issues/2735 and https://github.com/the-control-group/voyager/issues/2770
Will be fixed in https://github.com/the-control-group/voyager/pull/2757

**Comment by SebaSOFT** [comment]
I saw that after I created this bug, sry about that, you can safely close this one.
