### ISSUE TITLE
Undefined variable: dataType

### ISSUE THREAD

**Issue by tamersolieman** [thedevdojo/voyager#2782]
- Laravel Version: 5.6.7

- Voyager Version dev-1.x-dev

- PHP Version: 7.1.7

- Database Driver & Version: MySQL:

### Description:

I can't make a relationship between 2 tables.

### Steps To Reproduce:

I need to make a relationship between two tables events and event_categories, the table structure as follows:

<img width="686" alt="screen shot 2018-03-08 at 10 22 41 am" src="https://user-images.githubusercontent.com/283613/37138844-aff9130c-22bc-11e8-8fed-0c5bd0867809.png">

<img width="710" alt="screen shot 2018-03-08 at 10 21 42 am" src="https://user-images.githubusercontent.com/283613/37138696-2d208b18-22bc-11e8-8e31-1c2b678af616.png">

And the relation is 

<img width="588" alt="screen shot 2018-03-08 at 10 23 50 am" src="https://user-images.githubusercontent.com/283613/37138753-54ee73b2-22bc-11e8-97a9-de474c61cf5f.png">

Then I got the error 

<img width="1440" alt="screen shot 2018-03-08 at 10 24 05 am" src="https://user-images.githubusercontent.com/283613/37138764-5fcf5a08-22bc-11e8-887a-7fd75711d150.png">

**Comment by emptynick** [comment]
Update composer. It was fixed yesterday.

**Comment by tamersolieman** [comment]
Fixed, Thanks
