### ISSUE TITLE
Error when saving Coordinates type

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2783]
- Laravel Version: 5.5.37
- Voyager Version: 1.0.16
- PHP Version: 7.0
- Database Driver & Version:
Mysql 5.6

### Description:
I get an error when I try to save a model that has a **coordinates** type

### Steps To Reproduce:

Drag and drop the pin inside de map. 
Click save. 
And I get this error:

SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\xE9\xD3\xA6E@...' for column 'lugar' at row 1 (SQL: update `actividades` set `lugar` = ST_GeomFromText('POINT(48.808805399845 2.4981447499999)'), `updated_at` = 2018-03-08 08:03:01 where `id` = 1)

**Comment by emptynick** [comment]
What is the type of the `lugar` column?

**Comment by ghost** [comment]
tinytext

**Comment by emptynick** [comment]
It has to be [GEOMETRY](https://dev.mysql.com/doc/refman/5.7/en/spatial-type-overview.html)

**Comment by ghost** [comment]
I must have missed than from the docs, my fault .
thanks!
