### ISSUE TITLE
How to make many to many relationship?

### ISSUE THREAD

**Issue by tamersolieman** [thedevdojo/voyager#2785]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I don't find anything in the documentation to describe how to make many to many relationships with the relationship feature.

Please help.

**Comment by emptynick** [comment]
See [here](https://laravelvoyager.com/academy/relationships/)

**Comment by tamersolieman** [comment]
Thanks, @emptynick I already see all the videos in the academy but they are all talk about basics.

I don't find anything to explain how to make many to many relationship

**Comment by emptynick** [comment]
Same way as shown in the video.
You just need to create the pivot table before.

**Comment by tamersolieman** [comment]
If you share a video or some tutorial to help on that, it'll be appreciated

**Comment by fletch3555** [comment]
Please note that all version information is required when opening issues on this project.  This ensures we have the appropriate context to troubleshoot your issue without having to ask too many questions.
