### ISSUE TITLE
when voyager support laravel 5.6?

### ISSUE THREAD

**Issue by dolorain** [thedevdojo/voyager#2791]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by vblinden** [comment]
Voyager 1.0 does not and will not support 5.6. We have tentative support in the 1.x-dev branch planned for a 1.1 release.

Please use the search feature before opening issues. This has been asked/reported numerous times already.

@fletch3555 This is a duplicate and can be closed.
