### ISSUE TITLE
Coordinates are inserted in the database incorrectly

### ISSUE THREAD

**Issue by DiederikvandenB** [thedevdojo/voyager#2795]
- Laravel Version: 5.5.0
- Voyager Version: 1.0.16
- PHP Version: 7.1.13
- Database Driver & Version: MySQL 5.7.21

### Description:
The coordinates field prepares for the coordinates to be inserted in the database [here](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/Controller.php#L475). However, the syntax `ST_GeomFromText(LATITUDE LONGITUDE)` is incorrect and in fact it should be the other way around: `ST_GeomFromText(LONGITUDE LATITUDE)`, as you can see [here](https://dev.mysql.com/doc/refman/5.7/en/gis-class-point.html). X is longitude and Y is latitude.

**Comment by emptynick** [comment]
Take a look at [this](https://github.com/the-control-group/voyager/pull/2425)

**Comment by fletch3555** [comment]
This was taken care of in #2425, and will be included in the upcoming v1.1 release

**Comment by DiederikvandenB** [comment]
Thanks and sorry for missing that thread!
