### ISSUE TITLE
Problems with installing voyager

### ISSUE THREAD

**Issue by Dzale** [thedevdojo/voyager#2799]
Hi there,

i have an existing laravel application and i want to add Voyager admin panel to it. 
Now, the problem is that some of the tables that Voyager tries to add to my database (and migrations) already exists. 

For example Voyager adds table `posts`, which i already have and use in application. 

Is there any way to solve this ? Like add prefix to Voyager tables, or just not install tables that are not necessary ?

Best regards,
Nikola

**Comment by marktopper** [comment]
You can do everything manually if you wish, what running `php artisan voyager:install` does is this:

1. Publishes the assets, configs, migrations and seeders running `php artisan vendor:publish --provider=TCG\Voyager\VoyagerServiceProvider` and `php artisan vendor:publish --provider=Intervention\Image\ImageServiceProviderLaravel5`.
2. Migrates the database running `migrate`, before running this yourself, you can modify any migration file or delete those you might wish to delete.
3. Makes your user model extends `TCG\Voyager\Models\User`.
4. Dumping Composer autoload `composer dump-autoload`.
5. Adding the Voyager routes to `routes/web.php`:
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```
6. Seeds the database by running `php artisan db:seed --class=VoyagerDummyDatabaseSeeder`. Before this step you can modify the seeders to fit your need.
7. Setting up the hook system by running `php artisan hook:setup`.
8. Making the storage symlink by running `php artisan storage:link`.

That is it! Good luck!

Let me know if you have any more issues.

Please note that if you prefix any table, like the `posts`, you might also want to tell the default Voyager Post model to use this table, you can do that by making your own Model extending the default Voyager Post model and setting the prefixed table name. Then you need to tell Voyager to use this Model by adding `Voyager::useModel('Post', YourPostModel::class)` and by modifying the model used under the BREAD settings of the table.

**Comment by Dzale** [comment]
Thanks, ill try to do it that way ;)

**Comment by harveyslash** [comment]
I am getting this error: 
I already have a `user_roles` table.

```
Base table or view already exists: 1050 Table 'user_roles' already exists")
```

When try to manually run migrations: 
php artisan vendor:publish (and select option 17, tag:  dummy_migrations)

There is no migration created in database/migrations mentioning a user_roles table.

**Comment by fletch3555** [comment]
@harveyslash, this has been closed for ~8 months.  Please ask in Slack instead.
