### ISSUE TITLE
install failed in Laravel 5.6.11

### ISSUE THREAD

**Issue by danielin** [thedevdojo/voyager#2802]
- Laravel Version: 5.6.11
- Voyager Version: 1.0.9
- PHP Version:
- Database Driver & Version:

### Description:
vagrant@homestead:~/code1$ composer require tcg/voyager
Using version ^1.0 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.6.11
    - Conclusion: don't install laravel/framework v5.6.11
    - tcg/voyager 1.0.x-dev requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.0 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.1 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.10 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.11 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.12 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.13 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.14 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.15 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.16 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.2 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.3 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.4 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.5 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.6 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.7 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.8 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - tcg/voyager v1.0.9 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[v5.6.11].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.0 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.13 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.17 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.19 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.27 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.36 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.4.9 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v5.6.11].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v5.6.11].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.11
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.6.11
    - Installation request for laravel/framework (locked at v5.6.11, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.11].
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[1.0.x-dev, v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by emptynick** [comment]
[Thats true](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+in%3Atitle+5.6)

**Comment by lotfio** [comment]
voyager does  not support laravel 5.6  so you should stick with 5.5 check there docs https://voyager.readme.io/docs/installation
