### ISSUE TITLE
Error install Voyager

### ISSUE THREAD

**Issue by joaovelozo** [thedevdojo/voyager#2807]
Migrating the database tables into your application
Migration table created successfully.

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))

  at C:\gerenciador\voyager\vendor\laravel\framework\src\Illuminate\Database\Connection.php: 664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      C:\gerenciador\voyager\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php : 107

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
      C:\gerenciador\voyager\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php : 105

  Please use the argument -v to see more details.
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by fletch3555** [comment]
https://github.com/the-control-group/voyager/search?q=1071+Specified+key+was+too+long%3B+max+key+length+is+767+bytes&type=Issues&utf8=%E2%9C%93

http://lmgtfy.com/?q=1071+Specified+key+was+too+long%3B+max+key+length+is+767+bytes

**Comment by jaikangam** [comment]
This happens to me when I tried to install voyager. After few digging I found these two answers which working
try this on the /config/database.php 

'mysql' => [
    ...,
    ...,
    'engine' => null,
 ] 

to 
'mysql' => [
    ...,
    ...,
    'engine' => 'InnoDB',
 ] 

its work for me.
