### ISSUE TITLE
Unable to install fresh release

### ISSUE THREAD

**Issue by antimech** [thedevdojo/voyager#2811]
- Laravel Version: 5.6.11
- Voyager Version: 1.0.16
- PHP Version: 7.2.3-1+ubuntu16.04.1+deb.sury.org+1

### Description:
I can't install fresh release of Laravel + Voyager. I instantly getting `Your requirements could not be resolved to an installable set of packages.`.
```
Problem 1
    - Conclusion: remove laravel/framework v5.6.11
    - Conclusion: don't install laravel/framework v5.6.11
    - tcg/voyager 1.0.x-dev requires illuminate/support ~5.4.0|~5.5.0 .........
```

### Steps To Reproduce:
```
laravel new voyager
cd voyager
composer require tcg/voyager
```

**Comment by emptynick** [comment]
That's true. Voyager does not support [Laravel 5.6](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+in%3Atitle+5.6+)
But will _very soon_
