### ISSUE TITLE
laravel upload in bluehost cPanel

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2813]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I have uploaded my laravel project successfully in my Namecheap cPanel and the website is showing without any error but while uploading in bluehost cPanel and run that website into browser it shows error web.sencare.com.bd is currently unable to handle this request.
HTTP ERROR 500 though I have followed same steps for uplaod my project in bluehost cPanel as I upload in Namecheap cPanel.

Though it is actually a cPanel related question but i ask here because it is a Laravel voyager project. 

I need the solution very badly .... Anyone can help or give any suggestion ?

**Comment by marktopper** [comment]
Ask your hosting provider to enable showing errors.
Then it should show something else than `500 Error`.

Also, closing this since it is not related to Voyager, but is a misconfiguration of your host that makes Laravel breaks.
