### ISSUE TITLE
Installation Error: There are no commands defined in the "voyager" namespace

### ISSUE THREAD

**Issue by csajedi** [thedevdojo/voyager#2816]
- Laravel Version: 5.4.30
- Voyager Version: current
- PHP Version:7.1.13
- Database Driver & Version: defaults

### Description:
I have a new laravel project (v 5.4 because I think 5.6 does not function with voyager) and I used composer to install according to the docs. When I get to step:  
     `$> php artisan voyager:install `

I get this error message...               
   There are no commands defined in the "voyager" namespace.  
                                                             
I ran...
`$> php artisan`

> 
> Laravel Framework 5.4.36
> 
> Usage:
>   command [options] [arguments]
> 
> Options:
>   -h, --help            Display this help message
>   -q, --quiet           Do not output any message
>   -V, --version         Display this application version
>       --ansi            Force ANSI output
>       --no-ansi         Disable ANSI output
>   -n, --no-interaction  Do not ask any interactive question
>       --env[=ENV]       The environment the command should run under
>   -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
> 
> Available commands:
>   clear-compiled       Remove the compiled class file
>   down                 Put the application into maintenance mode
>   env                  Display the current framework environment
>   help                 Displays help for a command
>   inspire              Display an inspiring quote
>   list                 Lists commands
>   migrate              Run the database migrations
>   optimize             Optimize the framework for better performance
>   serve                Serve the application on the PHP development server
>   tinker               Interact with your application
>   up                   Bring the application out of maintenance mode
>  app
>   app:name             Set the application namespace
>  auth
>   auth:clear-resets    Flush expired password reset tokens
>  cache
>   cache:clear          Flush the application cache
>   cache:forget         Remove an item from the cache
>   cache:table          Create a migration for the cache database table
>  config
>   config:cache         Create a cache file for faster configuration loading
>   config:clear         Remove the configuration cache file
>  db
>   db:seed              Seed the database with records
>  event
>   event:generate       Generate the missing events and listeners based on registration
>  key
>   key:generate         Set the application key
>  make
>   make:auth            Scaffold basic login and registration views and routes
>   make:command         Create a new Artisan command
>   make:controller      Create a new controller class
>   make:event           Create a new event class
>   make:job             Create a new job class
>   make:listener        Create a new event listener class
>   make:mail            Create a new email class
>   make:middleware      Create a new middleware class
>   make:migration       Create a new migration file
>   make:model           Create a new Eloquent model class
>   make:notification    Create a new notification class
>   make:policy          Create a new policy class
>   make:provider        Create a new service provider class
>   make:request         Create a new form request class
>   make:seeder          Create a new seeder class
>   make:test            Create a new test class
>  migrate
>   migrate:install      Create the migration repository
>   migrate:refresh      Reset and re-run all migrations
>   migrate:reset        Rollback all database migrations
>   migrate:rollback     Rollback the last database migration
>   migrate:status       Show the status of each migration
>  notifications
>   notifications:table  Create a migration for the notifications table
>  queue
>   queue:failed         List all of the failed queue jobs
>   queue:failed-table   Create a migration for the failed queue jobs database table
>   queue:flush          Flush all of the failed queue jobs
>   queue:forget         Delete a failed queue job
>   queue:listen         Listen to a given queue
>   queue:restart        Restart queue worker daemons after their current job
>   queue:retry          Retry a failed queue job
>   queue:table          Create a migration for the queue jobs database table
>   queue:work           Start processing jobs on the queue as a daemon
>  route
>   route:cache          Create a route cache file for faster route registration
>   route:clear          Remove the route cache file
>   route:list           List all registered routes
>  schedule
>   schedule:run         Run the scheduled commands
>  session
>   session:table        Create a migration for the session database table
>  storage
>   storage:link         Create a symbolic link from "public/storage" to "storage/app/public"
>  vendor
>   vendor:publish       Publish any publishable assets from vendor packages
>  view
>   view:clear           Clear all compiled view files
> 

and no voyager commands are listed.

How can I fix this issue? I am relatively new to the Laravel framework, and a entirely new to the Voyager panel. Any guidance is appreciated!

**Comment by emptynick** [comment]
Take a look at https://github.com/the-control-group/voyager/issues/2714

**Comment by csajedi** [comment]
@emptynick I saw that bug report before I posted this one, which is why I posted it in the format I did. I do not understand how the answer provided is a solution, I just see one line of code highlighted. I am not familiar with the framework enough to understand what it is doing. What action can I take to fix the problem and move forward?

**Comment by fletch3555** [comment]
@csajedi, the problem is because you're on 5.4, which doesn't auto-detect package ServiceProviders. https://voyager.readme.io/docs/adding-the-service-provider

I recommend using Laravel 5.5 instead if you still have the opportunity to switch.  5.5 is the LTS (Long Term Support) release, so it will be directly supported for 2 years.
