### ISSUE TITLE
How to validate a user by Role instead of Permission

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#2819]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

I want to make sure I'm not missing something obvious. Assume I'm starting with sample data for ease of reference.

I want a user to only be able to BREAD their own posts, not posts created by other users. I want admins to be able to BREAD any posts.

It looks like I can modify* the bread controller `index` function here to do this:

     $query = $model::select('*');

So, my question:

- Is there already a way within the out of the box settings to set this up in the permissions?
- Assuming not, what's the best way to check a user's role, not their individual permissions?

*I'm not modifying the bread controller directly, but creating a copy to use as an overwrite for this specific controller.

**Comment by fletch3555** [comment]
Voyager does not currently provide a way of doing this.

There may, however, be a Laravel way of doing this.  If you add a global scope to your models, you can use that to limit what is returned (e.g. `where('user_id', Auth::user()->id)`).  You can wrap that scope in something like `if (!Auth::user()->roles->contains('admin'))`, which will only apply the scope to your non-admin users.

You could also do it by authorization, by setting the Policy method to check for `$user->role == admin` OR `$model->user_id == $user->id`.  This is the route I would suggest.

**Comment by thill0822** [comment]
Thanks for the quick reply. 

That's where I was headed; thanks for confirming there isn't a built-in way to do this.
