### ISSUE TITLE
Replacing or Appending the default Voyager icons

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#2820]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

I need to either extend or replace the icons that are available, but I'd like to keep the easy references in the interface. Is there an easy way to do this?

**Comment by thill0822** [comment]
I guess I can take this as a no?

**Comment by emptynick** [comment]
You can not simply extend or replace the icon.
But you are free to add any other icon-library as you desire through [additional css](https://docs.laravelvoyager.com/customization/additional-css-js).
