### ISSUE TITLE
Getting an Integrity constraint violation: SQLSTATE[23000]

### ISSUE THREAD

**Issue by swissv2** [thedevdojo/voyager#2821]
- Laravel Version: 5.5.0
- Voyager Version: 1.0.0
- PHP Version: 7.1.3
- Database Driver & Version: MySQL 5.7

### Description:
Just thought I would let you guys know that one gets a Query Exception error instead of triggering a validation rule while inserting new user into database with null value for "password".

> "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'password' cannot be null (SQL: insert into `users` (`name`, `email`, `password`, `avatar`, `role_id`, `updated_at`, `created_at`) values (FluffyPanda, fluffy@voyager.oo, , users/March2018/lHBM7WCD3KkcSlR5p3Qj.jpg, 2, 2018-03-15 01:05:06, 2018-03-15 01:05:06))

### Steps To Reproduce:
 
1. Create New User
2. Leave "password" null
3. Get error message! :)

**Comment by emptynick** [comment]
Fixed in #2828
