### ISSUE TITLE
Images not loading in admin panel 

### ISSUE THREAD

**Issue by ca2510fl** [thedevdojo/voyager#2823]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.1
- Database Driver & Version:

### Description:

I have an issue in uploading and viewing images on admin panel. All Images (Logo, Avatar...) or broken in the Admin Panel

in chrome console i get:
```
http://localhost:8888/storage/users/default.png 404 (Not Found)
settings:582 GET 
http://localhost:8888/storage/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png 404 (Not Found)

```
### Steps To Reproduce:

I checked the storage Folder with:
`php artisan storage:link`
i get the message, its already exist

i changed in .env the app_url in
`APP_URL=http://localhost:8888` (yeah 8888 its my mamp port on my device)

**Comment by marktopper** [comment]
Where is the file located? Can you find it somewhere in your applications storage or public path?

**Comment by ca2510fl** [comment]
which file u mean? An File that i upload?

other standard files are also broken, like the standard avatar.

**Comment by marktopper** [comment]
The `March2018/CYSL8EeI1o5QdU8fDHJG.png` file.

**Comment by ca2510fl** [comment]
its located in
`project/storage/app/public/settings/March2018`

**Comment by marktopper** [comment]
Can you access it from the URL at something like those links:
- http://localhost:8888/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png
- http://localhost:8888/storage/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png
- http://localhost:8888/storage/app/public/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png
- http://localhost:8888/project/storage/app/public/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png

**Comment by ca2510fl** [comment]
Yeah the last one is working

**Comment by marktopper** [comment]
Does this work too?
http://localhost:8888/project/public/storage/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png

**Comment by ca2510fl** [comment]
Yes

**Comment by marktopper** [comment]
Your vhost has not been configured correct. It should be configured to have the project path being whats inside the `project/public`.
Which will result in this working: http://localhost:8888/storage/settings/March2018/CYSL8EeI1o5QdU8fDHJG.png

**Comment by ca2510fl** [comment]
For all others, i resolve the Problem with:
`APP_URL=http://localhost:8888`
change to 
`APP_URL=http://localhost:8888/project/public`

**Comment by marktopper** [comment]
Could be a bad idea. You might be able to access your `.env` publicly at `http://localhost:8888/project/.env`
