### ISSUE TITLE
Edit Profile gives ability to change role to admin. How to disable?

### ISSUE THREAD

**Issue by swissv2** [thedevdojo/voyager#2824]
- Laravel Version: 5.5.0
- Voyager Version: 1.0.16

### Description:
Editing one's profile gives the dangerous ability for anyone with any permissions to change role to admin.

How do I temporarily disable this?

### Steps To Reproduce:

1. Edit Profile > Role > Choose "admin" from Role select > Regular user can update role as admin.

**Comment by fletch3555** [comment]
This is already fixed on the 1.x-dev branch (soon to be v1.1).

If you need it changed in this version, you can override the view (see the docs) and add a check around that field

**Comment by ghost** [comment]
> * Laravel Version: 5.5.0
> * Voyager Version: 1.0.16
> 
> ### Description:
> Editing one's profile gives the dangerous ability for anyone with any permissions to change role to admin.
> 
> How do I temporarily disable this?
> 
> ### Steps To Reproduce:
> 1. Edit Profile > Role > Choose "admin" from Role select > Regular user can update role as admin.

Hi #swissv2 how did you solved this can you tel me please?

**Comment by emptynick** [comment]
By upgrading probably

**Comment by ghost** [comment]
> By upgrading probably

@emptynick I am using v1.2.3 I just want to know to know the exact modifications I am completely a beginner please tell me in which model or controller I have to make changes and the line of code too, please I am stucked.
