### ISSUE TITLE
Problem with Overriding Views

### ISSUE THREAD

**Issue by trd-alkein** [thedevdojo/voyager#2825]
i tried to create custom view using overriding views but i got a problem, i can't click the logout button (profile photo with the arrow down) but when i go to other page, it works just in my custom view, the logout won't work.

anyone can help?

**Comment by emptynick** [comment]
Which view did you override, and how?

**Comment by fletch3555** [comment]
Also, all version information is required when opening issues on this repository.  The issue template is there to guide you to providing all the information we need to best help you.

**Comment by trd-alkein** [comment]
@emptynick & @fletch3555  i already fixed it .. thanks for your fast reply
