### ISSUE TITLE
belongsTo Relationship has error

### ISSUE THREAD

**Issue by nourziada** [thedevdojo/voyager#2836]
- Laravel Version: 5.5.*
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
hi all , 
i have a categories and products table , 
i do Relationship to products Braed BelnogTo Categories
when i add product , i select from drop down menu witch category belong to , 
but it store the category id = 1 every time i add product or edit it to another category , still add tha same category id

**Comment by emptynick** [comment]
Please make sure that the `type` of `category_id` is *not* checkbox
https://github.com/the-control-group/voyager/issues/2766

**Comment by nourziada** [comment]
thank you very match , it's work
