### ISSUE TITLE
How to add custom theme end mode for ACE-Editor?

### ISSUE THREAD

**Issue by Ikarushka** [thedevdojo/voyager#2839]
- Laravel Version: 5.5.
- Voyager Version: 1.0.
- PHP Version: 7.2
- Database Driver & Version:

### Description:
I want to use php code highlighting in my custom Voyager view.

### Steps To Reproduce:
I use `editor.getSession().setMode("ace/mode/php");` but it does not work.
I thik only one ace-editor theme available in Voyager. It is json-mode.
It's true? How I can use othere ace-editor modes?

**Comment by Ikarushka** [comment]
When I customase ace-mode by html atrributes. 
Like that: `<div id="editor" class="ace_editor" data-theme="dracula" data-language="php" > `
I get "not found" for two files /admin/theme-dracula.js and /admin/mode-php.js. 
What is true way for add ace-mode in Voyager?

**Comment by MonstreX** [comment]
There are some new issues on the new version of Voyager 1.1
In the version 1.0 worked the methods inside voyager. You could use additional parameters in a Bread editor like this:
```
    "theme": "monokai",
    "language": "html",
```
and add to custom.js line where you store ace lib - like this:
`ace.config.set('basePath', '/vendor/tcg/voyager/assets/js/lib/ace');`

But now this method has been stopped working in 1.1 version.
So I've found the way how to make it works again.
Steps:
1) Add Ace's directory with Themes and Mode wherever you want.
2) Attach you need themes and modes as custom JS in voyager.cfg like this:
```
    'additional_js' => [
        '/vendor/tcg/voyager/assets/js/lib/ace/theme-monokai.js',
        '/vendor/tcg/voyager/assets/js/lib/ace/mode-json.js',
        '/vendor/tcg/voyager/assets/js/custom.js',
    ],
```
3) Copy and modify bread themplates (JS section), for example resources/views/vendor/voyager/bread/edit-add.blade.php adding this JS code after the line         "$('document').ready(function () {":
```
            // Ace Theme and Mode support implementation .START
            @foreach($dataTypeRows as $row)
                @php $options = json_decode($row->details); @endphp
                @if ($options && (isset($options->ace_theme) || isset($options->ace_mode)))
                    var ace_{{ $row->field }} = ace.edit("{{ $row->field }}")
                    @if (isset($options->ace_theme))
                        ace_{{ $row->field }}.setTheme("ace/theme/{{$options->ace_theme}}")
                    @endif
                    @if (isset($options->ace_theme))
                        ace_{{ $row->field }}.getSession().setMode("ace/mode/{{$options->ace_mode}}")
                    @endif
                @endif
            @endforeach
            // Ace Theme and Mode support implementation .END
```
4) Now you can use new options in Bread Editor like this:
```
{
    "ace_theme": "github",
    "ace_mode": "json"
}
```

I hope it'll help you to solve your issues.

**Comment by emptynick** [comment]
Possible solution provided above. Closing

**Comment by sleepless** [comment]
Came across this because I needed to extend tinyMCE with an HTML editor. Just want to help others so I'll add another solution:

Voyager is using brace so add brace to your package.json dependencies:

```
"dependencies": {
    "brace": "^0.10.0"
}
```

Create a new file in your resources/js. For example "voyager-brace.js" and add it to your webpack.mix.js:

`mix.js('resources/js/admin-brace.js', 'public/js')`

In your new admin-brace.js add your desired themes / modes:

```
require('brace/mode/html');
require('brace/theme/monokai');
```

Compile and add the new file to your additional_js of your voyager config.

**Comment by d3turnes** [comment]
A Possible solution

edit [resource/views/vendor/voyager/master.blade.php]

<script type="text/javascript" src="//ajaxorg.github.io/ace-builds/src-noconflict/ace.js"></script>

<script type="text/javascript" src="{{ voyager_asset('js/app.js') }}"></script>
