### ISSUE TITLE
Bug: Routes will invalid when config have been cached.

### ISSUE THREAD

**Issue by tanteng** [thedevdojo/voyager#284]
- Laravel Version: 5.3.*
- Voyager Version: 0.9.34
- PHP Version: PHP 7
- Database Driver & Version:MYSQL

### Description:

Here is not perfect!
Look this the code: 
```
env('DB_CONNECTION')
```

Do you known the value will be null when the config have been cached? I always use php artisan config:cache to cache config, so the route is invalid.
```
    if (env('DB_CONNECTION') !== null && Schema::hasTable('data_types')):
        foreach (TCG\Voyager\Models\DataType::all() as $dataTypes):
            Route::resource($dataTypes->slug, 'VoyagerBreadController');
    endforeach;
    endif;
```

file path:vendor/tcg/voyager/routes/web.php

**Comment by marktopper** [comment]
#289
