### ISSUE TITLE
How to use value stored at Settings in another controller

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#2841]
- Laravel Version: 5.5
- Voyager Version: 1
- PHP Version: 7.2
- Database Driver & Version:

### Description:
First of all guys im really a newbie so sorry if the question is stupid for some ..

So basically i created a new settings field with voyager 
field name : multiplier 
Voyager says that i just need to use setting('site.multiplier') anywhere

but i want to get the value of **setting('site.multiplier')** inside one of my controllers so when i call it using 
**$setting('site.multiplier')** it output : **Undefined variable: setting**

### Steps To Reproduce:
Try to use settings field value in a controller

**Comment by emptynick** [comment]
Take a really close look at your sentence
`but i want to get the value of setting('site.multiplier') inside one of my controllers so when i call it using
$setting('site.multiplier') it output : Undefined variable: setting`
You will find it

**Comment by gladuz** [comment]
You should use settings('site.multiplier') not **$**settings('site.multiplier')
