### ISSUE TITLE
belongs to Many relationship

### ISSUE THREAD

**Issue by NJV19** [thedevdojo/voyager#2845]
- Laravel Version: #5.5#.39#
- Voyager Version: latest
- PHP Version:7.2.1
- Database Driver & Version: xampp / phpmyadmin 

### Description:

I have the following problem in my app,

I have 2 Tables in my database, First table is Hotel (hotel_id-hotel_name) and the second is the roles table (default table integrated in the system). (role_id-role_name, and so on columns).

Basically what I want to design is a *mix-table* called role_hotel from now on, where I can create the following structure.

Role                   Hotel
-------------------------
Admin                X,Y,Z
User                   Z

In this table "role_hotel" role is a dropdown (already created without problems) and Hotel should be a multiple select where you can choose more than one hotels (at least one).

I suppose that I have to create a releationship "BelongToMany" between this role_hotel and hotel but I am really confused. I would like to create it with voyager interface but I am not able at the moment.

Can anybody help me and let me know how to proceed?

**Comment by emptynick** [comment]
You dont make a relationship between `hotel` and `hotel_role`.
Instead you want to do a relationship between `hotel` and `role`, where `hotel_role` is your pivot-table.

To learn more about it, please read the [Laravel docs](https://laravel.com/docs/5.5/eloquent-relationships#many-to-many)

If you have further question, please ask in our [Slack](https://voyager-slack-invitation.herokuapp.com/)
