### ISSUE TITLE
Deleting BREAD displays incorrect button text

### ISSUE THREAD

**Issue by SturmB** [thedevdojo/voyager#2848]
- Laravel Version: 5.6.11
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7.21

### Description:
The language file appears to not be referenced properly in some places, most notably during the popup for deleting a BREAD:

<img width="616" alt="screen shot 2018-03-16 at 1 27 47 pm" src="https://user-images.githubusercontent.com/6216224/37597924-293f725e-2b57-11e8-9031-4032be1eb779.png">

The text for the `Delete` button is clearly incorrect. The button _does_ work, however. Yes, it's a minor issue, but might as well go ahead and document it here so it can be fixed someday.

### Steps To Reproduce:
1. With a fresh (or stale, for that matter) installation of Laravel and Voyager, create a database table and its associated Model.
2. Create BREAD for that table.
3. Attempt to delete said BREAD.
4. Marvel at the incongruously-long `DELETE` button.
5. ???
6. Profit?

…well, okay, perhaps you don't need those last two steps. ;~P

**Comment by emptynick** [comment]
I recently splitted up the language files into groups, but the actually source looks like [this](https://github.com/the-control-group/voyager/blob/1.x-dev/resources/views/tools/bread/index.blade.php#L80)
This should work properly. Check that you dont have any old files!

**Comment by SturmB** [comment]
Okay, I updated Voyager with `composer update` so I should have the latest version now. During that process, it removed the old version of Voyager (and, presumably, all of its files, as far as I could tell). And, indeed, it does seem that the line of code you specified is identical to the one I have. However, the same thing appears, only with a slight change to the text on the button:

<img width="613" alt="screen shot 2018-03-19 at 9 55 08 am" src="https://user-images.githubusercontent.com/6216224/37599763-e027a28a-2b5b-11e8-8d92-5cd4c153c1aa.png">

**Comment by emptynick** [comment]
Okay, now thats a thing. [Ref](https://github.com/the-control-group/voyager/blob/1.x-dev/publishable/lang/en/bread.php#L10)
It should be `voyager::bread.delete_bread_conf`
I will submit a fix to #2837

**Comment by emptynick** [comment]
Fixed in #2837

**Comment by SturmB** [comment]
Confirmed fixed. 🎉
