### ISSUE TITLE
How to modify app.js file?

### ISSUE THREAD

**Issue by Ikarushka** [thedevdojo/voyager#2849]
- Laravel Version: 5.5.#
- Voyager Version: 1.0.#
- PHP Version: 7,2
- Database Driver & Version:

### Description:
When I need to add or remove some code from Voyager app.js file. What is a true way do it?

**Comment by defaultpage** [comment]
Hi! You can add custom js-file in `config/voyager.php`. Or `fork` this repository, change some code in the new branch of your fork, `rebuild assets` and add your repository in `composer.json`.

**Comment by Ikarushka** [comment]
Thanks! Now I see.

**Comment by defaultpage** [comment]
Please, close issue if your problem is solved.
