### ISSUE TITLE
fill out the select drop down

### ISSUE THREAD

**Issue by furqan99** [thedevdojo/voyager#285]
- Laravel Version: 5.3.*
- Voyager Version: 0.9.34
- PHP Version:5.6.*
- Database Driver & Version:5.0.11

### Description:
how to fill out the select drop down with the other table  data.

**Comment by handiwijoyo** [comment]
This feature will coming on the next release `v0.10`

**Comment by furqan99** [comment]
so what i do now??

**Comment by handiwijoyo** [comment]
You can either wait until `v0.10` released or install the unstable version by change composer.json:
```
"tcg/voyager": "dev-release/v0.10"
```
Please remind this release is unstable, things may changed and will break some of `v0.9.*` functionality, it's recommend that you use fresh install of laravel for this.

For how to use relationship on select dropdown, please refer to documentation: https://the-control-group.github.io/voyager/docs/#voyager-docs-database-tools-relationships-only-available-in-v0100

**Comment by furqan99** [comment]
thanks bro

**Comment by furqan99** [comment]
still i am not able fill out the select drop down .
i am add this function in Products.php  but in bread i am not found category_id 
 public function category_id(){
  	return $this->belongsTo(TCG\Voyager\Models\Category::class);
  }

**Comment by tnylea** [comment]
@furqan99 Can you show me a screenshot of the BREAD page and the JSON you are using.

Also, what namespace is the Products.php file in. Is this located in the App namespace? Can you share the Products.php file as well.

Thanks :)

**Comment by furqan99** [comment]
yes it is  located in namespace  App. i am add the this json 
{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}

**Comment by furqan99** [comment]
i am add this function page model its working fine.
public function author_id(){
    return $this->belongsTo(User::class);
}

**Comment by furqan99** [comment]
image of bread 
![capture](https://cloud.githubusercontent.com/assets/18142509/20929135/a6c085ac-bbea-11e6-8496-18d1211743a1.PNG)

**Comment by furqan99** [comment]
when i move Products.php,  in this directory " TCG\Voyager\Models"  then  working fine but in the App directory its not working

**Comment by marktopper** [comment]
@furqan99 So this have been solved?

**Comment by furqan99** [comment]
yes thank you @marktopper

**Comment by saldanac** [comment]
.

**Comment by venukommu** [comment]
It would be great if anyone can help us to fix the following issue.

We are trying to change the orderBy for Groups in Group's Dropdown when creating Access Codes in the BREAD. But it is not working as expected and responding if we write wrong syntax. 

Please find the attached screen for more info in details.
https://lh3.googleusercontent.com/-KtIRkL7iQHY/WmCV5x2qkRI/AAAAAAAAsfs/MlqXEV7beMI3xKyx8L87f_Mg182l47smQCL0BGAYYCw/h900/2018-01-18.png

Could you please help us to fix the change of OrderBy Created_date ?
Appreciate your help.

**Comment by marktopper** [comment]
Please create a new issue instead of bumping an old issue.
