### ISSUE TITLE
More than one label in many2many

### ISSUE THREAD

**Issue by mdenitti** [thedevdojo/voyager#2856]
- Laravel Version: 5.50
- Voyager Version: 1.0.5
- PHP Version: 7.1
- Database Driver & Version: MYSQL 5.4

### Description:
Many2Many, multiple labels

### Steps To Reproduce:
N/A

Is there a quick fix/workaround to add more than one label in the many2many relationships breads?

**Comment by fletch3555** [comment]
I don't quite understand what you mean by "label". Please describe your use-case in more detail.

Also, if you're really on 1.0.5, I recommend updating. There have been numerous bug fixes since then.

**Comment by mdenitti** [comment]
Hi Eric, thx for the quick reply

<img width="498" alt="aantekening" src="https://user-images.githubusercontent.com/14792393/37656139-7a3b52b8-2c47-11e8-9d52-9b78c908f06f.png">

How 2 add another column value to the HasMany field! km... for example

**Comment by emptynick** [comment]
It will be possible after #2885 was merged to 1.x-dev.
For now, this is not possible (without manually editing `data_rows`)

**Comment by mdenitti** [comment]
Thx!!! Bert helpfull
