### ISSUE TITLE
Browse table without model

### ISSUE THREAD

**Issue by blaqdog** [thedevdojo/voyager#2857]
- Laravel Version: 5.5.19
- Voyager Version: 1.0.16
- PHP Version: 7.2.2
- Database Driver & Version: 5.7.21

### Description:

I have the problem to make friends Spatie medialibrary with Voyager adminpanel. When adding BREAD to this table, there is a field called Model Name. If I fill it with model that implements HasMedia, the Bread has created successfully. But when browse 'media' table - this table is empty. If i fill field Model Name with any anothor value, there is error - such class doesnt exist.

Table does have fields, I can see it with php-my-admin

I have added to my model code as it described in documentation https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/preparing-your-model

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

class Game extends Model implements HasMedia
{
    use HasMediaTrait;

    ...
}
```
adjust my model controller, so i can add image

```
 public function store(Request $request)
{
    $newGame = new Game;

    $newGame->name = $request->game_name;
    $newGame->addMediaFromRequest('game_shortcut')->toMediaCollection('shortcut'); // изображение   
    $newGame->save();

    ...
}
```
Now I have uploaded image-file in my filesystem, and image entry in spatie 'media' table related to Game object. http://joxi.ru/Vrwn5pbCKyWJgA

The problem is that I cant view 'media' table in Voyager, because I can not create BREAD properly

Update: if create BREAD without filling Model field, then it fails with

```
Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized
```
error when browsing the table

**Comment by b4dnewz** [comment]
hi @blaqdog try to add `Permission::generateFor('table');` in **PermissionsTableSeeder.php** and see if this solve, I has a similar problem and I realized it was missing the BREAD permissions.

Hope this helps.

**Comment by blaqdog** [comment]
@b4dnewz, add Permission::generateFor('media');
Nothing changed

**Comment by emptynick** [comment]
Because this is more a question I suggest you to ask in our Slack group.
Closing.
