### ISSUE TITLE
Many to many extra pivot columns

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2859]
- Laravel Version: 5.5.39
- Voyager Version: 1.0.0
- PHP Version: 7.2
- Database Driver & Version: MySql

### Description:
I have character  model and item model. Character can have many items. However i need to save amount of every item which character has. But i have no idea how to add extra columns. I guess that I should modify belongs to many relationship setup. And maybe in edit modify multi select to be repeater.
Thanks for any advice or clue for better solution

### Steps To Reproduce:
create character model
create item model
create character_item pivot table
- character_id
- item_id
- amount

**Comment by fletch3555** [comment]
You're free to do this in your model classes directly, for use in your app.  Voyager is intended to be an admin panel, not a general purpose user tool.  Having said that, Voyager does not currently support accessing extra pivot table fields.  It's being discussed/planned for a future release.
