### ISSUE TITLE
how to use alerts in voyager?

### ISSUE THREAD

**Issue by farizree** [thedevdojo/voyager#2866]
- Laravel Version: 5.5.#
- Voyager Version: 1.0
- PHP Version:7.0
- Database Driver & Version:MySQL

### Description:
How to use alerts in voyager? any example? I want to show alert when employeeid submitting with the same employeeid.

### Steps To Reproduce:

![duplicate unique key](https://user-images.githubusercontent.com/25852713/37710820-6932cf8c-2d41-11e8-902f-696969b90f82.PNG)

**Comment by fletch3555** [comment]
https://voyager.readme.io/docs/validation

"How to" questions are best asked on our Slack group.  We prefer to keep github issues specific to package bugs/feature requests

**Comment by Haritsinh** [comment]
@farizree , check unique before inserting it, do form validation, most of laravel form validation rule can be applied in voyager also, i think you want to check unique employee id then apply the same rule of validation in bread see here : [laravel doc unique rule](https://laravel.com/docs/6.x/validation#rule-unique)
while creating bread apply the rule as below:

    {
      "validation": {
          "rule": "unique:employees,employee_id"
      }
    }
