### ISSUE TITLE
Displaying posts with different languages

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#2868]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.5
- PHP Version: 7
- Database Driver & Version: Last

### Description:
Hello awesome peoples.

In my view i want to display my posts in different languages. I am saving my posts with 5 different languages into 2 table. 
For example: 

### PostsTable
**id - title - main - created_at - update_at**

### Translations table
**id - table_name - column_name - foreign_key - locale - value - created_at - update_at**

translations table and poststable are connected foreign_key. But I don't know there is a way to display other 4 language? I just can show poststable values in one language. Other languages are waiting translations. 
I wish i can express myself.

**Comment by emptynick** [comment]
Dont worry about the translation-table and foreign keys.
Just follow the instructions [here](https://github.com/the-control-group/voyager/pull/561)
