### ISSUE TITLE
Adding a file

### ISSUE THREAD

**Issue by NXDChen** [thedevdojo/voyager#2869]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
If i try to add a mp4 file i get: [{"download_link":" <the part i want> ","original_name":"mov_bbb.mp4"}]
i only want the download link part to save to my database so that i can use {{ asset(         ) }}.
How do i do that?

**Comment by fletch3555** [comment]
First, all version information is required.  This provides the information needed to best support you.

Second, we prefer to reserve github issues for feature requests or bugs in the package.  Questions like yours are best asked on our Slack group.

Finally, to answer your question, why not just `json_decode()` it? This is how Voyager stores the data from file upload fields.  Additionally, voyager provides a `voyager_asset` helper method(https://github.com/the-control-group/voyager/blob/1.0/src/Helpers/helpers.php#L17) that will automatically use the configured asset path.  I would recommend doing something like:
```
$data = json_decode($json_string);
{{ voyager_asset($data->download_link) }}
```
