### ISSUE TITLE
Select z-index go up to "delete modal box"

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#2875]
- Laravel Version: 5.5
- Voyager Version: 1.0.16
- PHP Version: 7

### Description:
When you try to remove an image from multi-image field (browse view)
if you have in the form also a select you have the field active below the delete modal box
![schermata 2018-03-22 alle 15 15 32](https://user-images.githubusercontent.com/1073883/37775881-66172052-2de4-11e8-9ded-8623101866a2.png)
.

**Comment by emptynick** [comment]
Thats true. It was fixed in https://github.com/the-control-group/voyager/pull/2801 and will be released with 1.1
