### ISSUE TITLE
Relationship doesn't load after table update

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#2878]
- Laravel Version: 5.5
- Voyager Version:  v1.0.15
- PHP Version: 7.2
- Database Driver & Version: MYSQL

### Description:
Hello so i have a table (transactions) that has a relationship with User , im having a problem after adding columns to the  (transactions) table , gone to the bread updates the new columns ,then after saving i got an error, tried to delete the relationship then re adding it and this is what it displays
<img width="623" alt="screenshot 2018-03-23 04 16 13" src="https://user-images.githubusercontent.com/1163627/37809737-f31b4fe8-2e50-11e8-9982-cb6cc816ea2e.png">

### Steps To Reproduce:
-Add relationship to a table 
- update the table (add new column to it)
- Back to the bread and try to save

**Comment by emptynick** [comment]
Do you have any errors in your dev console?
If yes, can you post them here?

**Comment by mavrickdeveloper** [comment]
`
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.
`

**Comment by emptynick** [comment]
What are the URLs?

**Comment by mavrickdeveloper** [comment]
FIXED the issue , 
turns out that i had an error of HTTPS , installed the correct HTTPS certificate on the subdomain i was working on , updated the APP URL to a HTTPS url , then all is fixed
i hope the VOYAGER dev , try to warn users about this
