### ISSUE TITLE
User can set own role in settings page. Any role

### ISSUE THREAD

**Issue by SwiftAdviser** [thedevdojo/voyager#2879]
- Laravel Version: 5.5
- Voyager Version: 1.0.16
- PHP Version: 7.1
- Database Driver & Version: MariaDB 10.2

### Description:

I have a user that have role with only one permission: to view admin panel.  
Well, he should not be able to see any other pages like menus or settings:

![image](https://user-images.githubusercontent.com/5148967/37812465-d93a41ac-2e68-11e8-8f59-a4f93f2fa6ae.png)

But if I will go to user settings in top right I will be able to set any role that I want, so I can be an admin even I am not (language doesn't matter when we use default UX):

![image](https://user-images.githubusercontent.com/5148967/37812737-3c461914-2e6a-11e8-84c2-79394e4b2075.png)

![image](https://user-images.githubusercontent.com/5148967/37812743-4522eef4-2e6a-11e8-9fe5-f4ce09b82351.png)

![image](https://user-images.githubusercontent.com/5148967/37812614-8975dd88-2e69-11e8-88b3-23eb0cc67a42.png)

I think common sense tells that it is wrong functionality.

**Comment by emptynick** [comment]
That is true for version `1.0.x` but was changed in `1.1` which will soon be released.
Common sense is also to search for issues, like
https://github.com/the-control-group/voyager/issues/2192 and https://github.com/the-control-group/voyager/issues/1723 or https://github.com/the-control-group/voyager/issues/1150
And many more
