### ISSUE TITLE
Adding a new unsupported language in voyager

### ISSUE THREAD

**Issue by kaxterzz** [thedevdojo/voyager#2880]
- Laravel Version: 5.5
- Voyager Version: new
- PHP Version:7.1
- Database Driver & Version: MySQL

### Description:
My language ("Sinhala") is currently not supported in voyager but I've created a folder `(sl)` in `resources/lang` and then copied the `voyager.php` file in `en` to the folder i created in `lang` and modified it to my language. Then also I've configured the voyager config file as well, 

`'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'sl',
        ],
    ],`

Since I'm creating a new language file that is not supported by the voyager yet. Is it possible to make that language work in dashboard ? Basically what i need to do is add the language switcher in dashboard or specific pages then when i switch the language BREAD should be translated and I should be able to add a post or content in my own language. What is the approach for do this ? 

I am trying in this voyager because voyager is super easy and nice ! 

Since I'm new please pardon any mistakes.

**Comment by emptynick** [comment]
The locales you put into the Voyager config are used for BREAD-translations, not for the UI.
To change this language, go to your `config/app.php` and change `locale` to `sl`
Furthermore, in 1.x-dev there is a language-selector for users
