### ISSUE TITLE
Customizing the footer page (app-footer.blade.php)

### ISSUE THREAD

**Issue by sushiljic** [thedevdojo/voyager#2882]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.16
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I have tried changing the theme  of footer by copying the app-footer.blade.php file under public/vendor/voyager/views/partials
But was unable to change the theme(Text ) of footer.
I am amazed with the voyager feature but also would love to add this feature as as being developer we will know what voyager is and can help but as being customer they never want to see those.

**Comment by jeffcdavis** [comment]
To override that file, it should be placed in /resources/views/vendor/voyager/partials/

**Comment by emptynick** [comment]
This is also described in the [Laravel docs](https://laravel.com/docs/5.5/packages#views)

**Comment by sushiljic** [comment]
Thanks,
i got confused :+1: 
But still, i hope there should be some options like as  changing admin title/description/logo
so that we don't even need to override views for just the footer.
Are there any features for this coming up?

**Comment by emptynick** [comment]
Did you take a look at the settings?
There you can set admin title/description and logo.

**Comment by sushiljic** [comment]
I am just giving example of admin title/description.
I would love to see setting for changing footer also.
https://imgur.com/a/X0WRB
