### ISSUE TITLE
Navbar-right overlap

### ISSUE THREAD

**Issue by xaviqv** [thedevdojo/voyager#2883]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 5.6
- Bootstrap version: 3.3.7

### Description:
With bootstrap you can combine multiple .navbar-right elements

In a common bootstrap template it looks like this:
![image](https://user-images.githubusercontent.com/25639840/37830059-a0ab604e-2ea1-11e8-89e7-b1381bf8d868.png)

In Voyager, they look overlapped:
![image](https://user-images.githubusercontent.com/25639840/37830104-c23defd8-2ea1-11e8-8d7d-479b25d1d494.png)

### Steps To Reproduce:

1. Edit the view voyager\dashboard\navbar.blade.php
2. Append the following in div.container-fluid:
```
<ul class="nav navbar-nav navbar-right">
	<li><a href="#">test 1</a></li>
</ul>
<ul class="nav navbar-nav navbar-right">
	<li><a href="#">test 2</a></li>
</ul>
```

**Comment by emptynick** [comment]
I cant replicate what you are describing.
For me it looks like this
![navbar](https://user-images.githubusercontent.com/2482942/37867035-150fb07e-2f93-11e8-9d30-05d29e118e3c.png)
This is what I would expect.
