### ISSUE TITLE
Defining visible rows from result set in relationship-created dropdown with SQL?

### ISSUE THREAD

**Issue by covecove1** [thedevdojo/voyager#2884]
- Laravel Version: 5.5
- Voyager Version:1.0.16

Hello,

how can I limit dropdown which was created by relationship to show only some rows from foreign table. 

For example, if my dropdown references Users; how and where can I put my custom sql statement to show only current user in dropdown or just first ten users by writing SQL with "LIMIT 10" for example. 

Also, can a dropdown show 2 foreign column at the same time like Name || ' ' || Surname?

I'm really new to Voyager, any help is much appreciated :)

Thanks!

**Comment by emptynick** [comment]
You have two options: [Policies](https://laravel.com/docs/5.5/authorization) or [Global Scopes](https://laravel.com/docs/5.5/eloquent#global-scopes)
As for your second problem: this is not possible right now, but will with version 1.1 which is coming soon!
If you have further question, you can join us on Slack where we can answer much faster!
