### ISSUE TITLE
How can i remove the role option in profile??

### ISSUE THREAD

**Issue by anandmainali** [thedevdojo/voyager#2888]
- Laravel Version: "5.5.*",
- Voyager Version: "^1.0"
- PHP Version: ">=7.0.0"
- Database Driver & Version:

### Description:
How can i remove the role option in profile??
I have a three role options (admin, super-admin & sub-admin). Admin can change the roles whatever he wants. But super-admin cannot change the roles to admin but can change it to sub-admin. How can i solve this problem??

**Comment by emptynick** [comment]
The best way right now would be to override the user/edit-add view as described in the  [Laravel docs](https://laravel.com/docs/5.5/packages#views)
Anyway in Version 1.1 - which will be released soon - the user wont be able to change his own roles anymore.
