### ISSUE TITLE
Ask for password confirm on voyager:admin command

### ISSUE THREAD

**Issue by b4dnewz** [thedevdojo/voyager#2896]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2

It's a **suggestion not a bug**.

### Description:
I issued the command: `php artisan voyager:admin your@email.com --create` and misspelled my password for example: "passwordù", than when I tried to login did not worked and I had to remove the account and make it again.

It should ask to retype the password so the user can notice errors before creating the account.

**Comment by fletch3555** [comment]
We're open for PRs on this.

**Comment by swarnava112** [comment]
I have added pull request for this issue. #2922
