### ISSUE TITLE
"Undefined variable: allCategories (View: C:\Users\JeuLun\Desktop\E-commerce\resources\views\vendor\voyager\products\edit-add.blade.php)"

### ISSUE THREAD

**Issue by jeulun** [thedevdojo/voyager#2897]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2.3

Description:
The code associated with the issue:
`<?php $__currentLoopData = $allCategories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>`

Steps To Reproduce:
Whenever I wanted to add/edit a product.

**Comment by emptynick** [comment]
As this is not a Voyager view you have to provide some more information/input like your view-file and what exactly you are trying to do and how
**And** your exact Voyager version (you can see it in the footer)

**Comment by jeulun** [comment]
Ah very sorry for your time taken, its just me forgotten to insert my controller name for the BREAD info....
Thanks for replying instantly.
