### ISSUE TITLE
Access user role from view

### ISSUE THREAD

**Issue by mikeyh98** [thedevdojo/voyager#2898]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.1

### Description:
How can I retrieve a user's role object from a view? Auth::user()->role keeps returning 'admin' object, even when it should be 'user'.

**Comment by emptynick** [comment]
It does not return an `admin` or an `user` object, its a `Role`.
If you do something like `dd(Auth::user()->role->name);` its working perfectly fine.
Also make sure, that you (I assume you are an admin) are not the one who is logged in when calling `Auth::user()`.
