### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by christoffer15** [thedevdojo/voyager#2899]
- Laravel Version: 5.6.*
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.1
- Database Driver & Version: Mysql (MariaDB)

### Description:
Mixed content on `<div class='col-xs-12 col-sm-6 col-md-6'><div class="panel widget center bgimage" style="margin-bottom:0;overflow:hidden;background-image:url('http://domain.tld/vendor/tcg/voyager/assets/images/widget-backgrounds/01.jpg');">`
.env app url set to https.

### Steps To Reproduce:
none

**Comment by emptynick** [comment]
https://voyager.readme.io/docs/using-https-on-your-site

**Comment by christoffer15** [comment]
tried but dident work. so i had to change the code and use direct link insted
