### ISSUE TITLE
How to properly determine a user's permissions?

### ISSUE THREAD

**Issue by JanisE** [thedevdojo/voyager#2901]
- Laravel Version: 5.5.39
- Voyager Version: 1.0.16
- PHP Version: 7.0.28
- Database Driver & Version: mysql, MariaDB 10.0.34

### Description:

In [Voyager documentation](https://voyager.readme.io/docs/permissions) I'm told to use `Voyager::can`, `Voyager::canOrFail` functions to determine the permissions of a user. However, [in the code](https://github.com/the-control-group/voyager/blob/1.0/src/Voyager.php#L194) those methods are deprecated. So, what am I to do?

**Comment by fletch3555** [comment]
If you want a list of the user's permissions, then use `$user->role->permissions`.

If you want to check if a user has a specific permission, then use Policies (https://laravel.com/docs/5.6/authorization), or call `$user->hasPermission('xyz')` directly.  Policies are the recommended approach, and Voyager ships with a [default Policy](https://github.com/the-control-group/voyager/blob/1.0/src/Policies/BasePolicy.php) that automatically applies to all BREAD types.

**Comment by JanisE** [comment]
Thanks for the options! I would recommend you include them also in the documentation. That would be useful, as there is no word on policies there at the moment.
