### ISSUE TITLE
data_types details column

### ISSUE THREAD

**Issue by deepaksp** [thedevdojo/voyager#2905]
- Laravel Version: 5.6
- Voyager Version: 1.dev
- PHP Version: 7.1
- Database Driver & Version:

### Description:
when i am creating new relationship from bread it throwing me error that details column doesnt exist.

so i have created details column in data_types and it worked.
this is the info details column store
{"order_column":null,"order_display_column":null}

### Steps To Reproduce:
i

**Comment by emptynick** [comment]
~~Republish assets and~~ run `php artisan migrate`.
This will definitely fix the problem.
Please be aware that this might happen again and again as you are using a `development` branch.
