### ISSUE TITLE
cannot retrieve image in blade

### ISSUE THREAD

**Issue by manozthapa** [thedevdojo/voyager#2906]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by manozthapa** [comment]
@foreach($homeslides as $homeslide)
  <div><img src="{{$homeslide->cover_image}}" title="">
    <div class="inner-content">
     {{$homeslide->title_white}}</p>
     <h1 class="animated fadeInLeft">{{$homeslide->title_red}}</h1>
     <span>{{$homeslide->description}}</span>
     <div class="donate-box"><span>DONATE NOW</span></div>
    </div>
  </div>
@endforeach
I got all the data expect $homeslide->cover_image. There is no mistake in spellings

**Comment by emptynick** [comment]
Please fill the requested version numbers.
What happens if you debug the attribute like `$homeslide->cover_image` ?

**Comment by manozthapa** [comment]
Thanks for replying. I forgot to add storage/  . Previously it was  img src="{{$homeslide->cover_image}}" . The issue was solve with  img src="storage/{{$homeslide->cover_image}}"

**Comment by emptynick** [comment]
I think you are looking for something like `<img src="{{ Voyager::image($homeslide->cover_image) }}" />`

**Comment by manozthapa** [comment]
Thanks  @emptynick. that worked too & seems better. I'm new to Voyager and starting to love it and its community.

**Comment by emptynick** [comment]
The next time please fill out the version numbers and describe your problem in more detail.
