### ISSUE TITLE
Problem with Relationships not eager loaded

### ISSUE THREAD

**Issue by MrCrayon** [thedevdojo/voyager#2907]
- Laravel Version: 5.5.39
- Voyager Version: 1.0.16
- PHP Version: 7.1.14
- Database Driver & Version: 10.1.30-MariaDB

### Description:
#2871 should solve the problem of relationships defined in details field some times not eager loaded.

Now the problem is that relationships defined with the "Create a relationship" are never eager loaded, or at last I didn't find any way to make it work and I can't find the piece of code that should do it.

I read somewhere that Bread management is being rebuilt so I don't know if it's going to work in the new version since I can't see the code, on 1.x-dev branch I don't see any change.

I'd like this to work in the new version so I'm writing here how I made it work extending VoyagerBreadController and relationship.blade.php.

I added on my class BreadController extends VoyagerBreadController:
```php
        // Check if BREAD is Translatable
        if (($isModelTranslatable = is_bread_translatable($model))) {
            $dataTypeContent->load('translations');
        }

        //Check relationship
        $relationships = [];
        foreach ($dataType->browseRows as $row) {
            if ($row->type == 'relationship') {
                $details = json_decode($row->details);
                $methodName = class_basename($details->model);
                switch ($details->type) {
                    case 'belongsToMany':
                    case 'hasMany':
                        $methodName = str_plural($methodName);
                        break;
                }
                $methodName = camel_case($methodName);
                if (method_exists($dataType->model_name, $methodName)) {
                    $relationships[] = $methodName;
                }
            }
        }
        // Eager load relationships
        if (!empty($relationships)) {
            $dataTypeContent->load($relationships);
        }
```

And I changed how data is taken in relationship.blade.php
for belongTo
```php
                    $method = camel_case(class_basename($options->model));
                    if (isset($relationshipData->{$method})) {
                        $query = $relationshipData->{$method};
                    } else {
                        $model = app($options->model);
                        if (method_exists($model, 'getRelationship')) {
                        	$query = $model::getRelationship($relationshipData->{$options->column});
                        } else {
                        	$query = $model::find($relationshipData->{$options->column});
                        }
                    }
```
for belongsToMany
```php
                @php
                    $relationshipData = (isset($data)) ? $data : $dataTypeContent;
                    $method = camel_case(str_plural(class_basename($options->model)));
                    if (isset($relationshipData->{$method})) {
                        $selected_values = $relationshipData->{$method}->pluck($options->label)->all();
                    } else {
                        $selected_values = isset($relationshipData) ? $relationshipData->belongsToMany($options->model, $options->pivot_table)->pluck($options->label)->all() : array();
                    }
                @endphp
```
etc.

Of course relationship methods need to be defined in model otherwise it will fallback to the old way.
A solution like this should be integrated I think in getRelationships, but if I do it there resolveRelations complains because it tries to find the relationship as a field.
So I don't really know if there was an intent on all this or simply the system was not complete and I have no idea on how all this is going to change in the next version so I'm not going to work in something better integrated.

### Steps To Reproduce:
On bread "Create a relationship"
Browse and log queries
A query for each row will be executed to load relationship

### Expected Beahviour
Relationships should be eager loaded

**Comment by fletch3555** [comment]
Voyager relationships cannot be eager-loaded because they don't exist as methods on a model class.  This will be changing in a future release.

**Comment by MrCrayon** [comment]
I mostly opened this issue to understand the situation of current and future releases about eager loading and also to hopefully help someone else to have a temporary fix.
So thank you for your reply.

Please for the future release consider letting the user override the default behavior: if I manually create a model method to retrieve relationship I probably want that to be used and not the magic one "created" by bread management.

Thanks!

**Comment by osmanzeki** [comment]
We stumbled upon this behaviour as well. For now we will be using `getRawAttributes()` in the initial `Translator`'s model and from there manually load each of its relationships as needed. Is there a better way of doing this with the current implementation?

I would also like to know if we can help with a PR for this in the `Translator` class and/or the `Translatable` trait perhaps.

I'd like to discuss the best approach in regards to performance (since we are working with EAV tables, need caching?, etc). Also, is the current the interface/api for `Translator` sufficient for using this or do we need to add functions to it for resolving the relations as mentioned above?

The original PR for reference :
https://github.com/the-control-group/voyager/pull/561
