### ISSUE TITLE
Multiple Image Option

### ISSUE THREAD

**Issue by manozthapa** [thedevdojo/voyager#2910]
- Laravel Version: 5.5.39
- Voyager Version: 1.0
- PHP Version:7.2.3
- Database Driver & Version:

### Steps To Reproduce:

   with code  in my blade
```
@foreach($gallery` as $galleries)	
<img src="{{Voyager::image($galleries->gallery_images)}}" class="img-responsive img-thumbnail" />
@endforeach

```
It showed One broken Image

**Comment by emptynick** [comment]
I dont understand it.
`@foreach($gallery as $galleries)`
Shouldn't that be vice versa?
`$galleries->gallery_images`
Seems to be an array, so you would to `json_decode` it, foreach through it, and **then** use it in an `<img>` tag

**Comment by fletch3555** [comment]
"Multiple images" stores it's value as a json-encoded array of paths. You need to json_decode the value from the database, then loop over the result, then display it with Voyager::image

**Comment by manozthapa** [comment]
zindagi jhandawa phir bhi ghamandawa .. do baari deciode karna kehena chahiyethaana.. andar andar golmaal karta hein , aur humein kehene sein dartaa hein ,,baklol

**Comment by yevgenatlanov** [comment]
@monazthapa you need to do next:
```
$images = json_decode($dataTypeContent->images); 
    if($images != null)
     @foreach($images as $image)
          <img src="{{ Voyager::image( $image ) }}" data-image="{{ $image }}" data-id="{{ $dataTypeContent->id }}" class="img-responsive">
       @endforeach
    @endif
````

**Comment by emptynick** [comment]
This is now in our [docs](https://docs.laravelvoyager.com/core-concepts/helper-methods).

**Comment by zacheleito** [comment]
@foreach ($galleries as $gallery)
@foreach (json_decode($gallery->gallery_images) as $image)

<img src="{{ Voyager::image($image)}}">

@endforeach
@endforeach

**Comment by zacheleito** [comment]
@foreach ($galleries as $gallery)
    @foreach (json_decode($gallery->gallery_images) as $image)
            <img src="{{ Voyager::image($image)}}">
    @endforeach
@endforeach

**Comment by zacheleito** [comment]
`@foreach ($galleries as $gallery)
@foreach (json_decode($gallery->gallery_images) as $image)
<img src="{{ Voyager::image($image)}}">
@endforeach
@endforeach`

**Comment by letowebdev** [comment]
This should do it
`@foreach ($galleries as $gallery)`
   `@foreach (json_decode($gallery->gallery_images) as $image)`
         `<img src="{{ Voyager::image($image)}}">`
    `@endforeach`
`@endforeach`

**Comment by fletch3555** [comment]
Please don't necro issues like this that have been closed for ~9 months.

**Comment by Sidhartha-dev** [comment]
When json decode then files shows broken image. Can anyone explain
