### ISSUE TITLE
Media Manager failed to load

### ISSUE THREAD

**Issue by lqchinh88** [thedevdojo/voyager#2911]
- Laravel Version: 5.5.28
- Voyager Version: 1.0
- PHP Version: 7.1.14
- Database Driver & Version: MySQL 5.6.35

### Description: 
Not a fresh install of Voyager. I've been working on this for a while. 
Starting few days ago, everytime I access Media Manager, i get this screen
<img width="1617" alt="screen shot 2018-03-29 at 2 17 02 pm" src="https://user-images.githubusercontent.com/4646472/38075252-f368ee3c-335b-11e8-90e6-9add34df1e99.png">

You can see the error log right below. I remember vaguely changing something in config or messing up with symlink  last time trying to fix image not showing problem. Now I can't reverse it. Seems like an extra "/public" was inserted somewhere. Help please.

**Comment by emptynick** [comment]
There seems to be a symlink called `public` in your `storage/app/public` folder. Likely unnecessary, check it and delete it.

**Comment by lqchinh88** [comment]
that solved the problem. Thanks a bunch @emptynick
