### ISSUE TITLE
How do I add a custom date and time input (datetimepicker)?

### ISSUE THREAD

**Issue by larelb** [thedevdojo/voyager#2913]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.*
- PHP Version: 7.2.2
- Database Driver & Version: MySQL 14.14 (5.7.17)

### Description:
I need a reliable input prompt that can gather the date and time.
Since it appears the default datepicker in Chrome doesn't give you the ability to add a time and in other browsers it doesn't show up, how do I add a custom input datepicker?

**Comment by MrCrayon** [comment]
I think what you are trying to do is add a custom formfield, and the way to do it is explained here: https://voyager.readme.io/docs/adding-custom-formfields

**Comment by fletch3555** [comment]
We don't have a built-in way of doing that, but you're free to build this yourself.  You can add it to your app using the instructions at the page @MrCrayon linked to.
