### ISSUE TITLE
Menu Items return (1/1) HttpException This action is unauthorized.

### ISSUE THREAD

**Issue by lukelee36** [thedevdojo/voyager#2917]
- Laravel Version: 5.6.4
- Voyager Version: 1.0
- PHP Version: 7.0.28-1~dotdeb+8.1
- Database Driver & Version: mySQL 5.5.59-0+deb8u1

### Description:
Hello, 
I try to restore website on laravel, I have database which I import into myPhpAdmin. Everithing work good, but now I have problem. I can access to voyager dashboard /admin and /admin/database. Thats all, rest of menu_items didnt work and show me this report  **HttpException This action is unauthorized.** I cant access settings, roles and so on.

**Comment by MrCrayon** [comment]
Are you restoring from an old backup or moving it from one database to another?
Looks like there is something missing in one of these tables:
permission
permission_role
roles
users

**Comment by lukelee36** [comment]
I move from one to another. 
![permission_role](https://user-images.githubusercontent.com/15262273/38135550-193b23ce-3419-11e8-8397-dbeb297e9638.png)
![permissions](https://user-images.githubusercontent.com/15262273/38135552-1b76f4ec-3419-11e8-844e-6782833a37a1.png)
![roles](https://user-images.githubusercontent.com/15262273/38135553-1d332f9e-3419-11e8-9716-b69b0059b463.png)
![users](https://user-images.githubusercontent.com/15262273/38135555-1fcdd7fe-3419-11e8-8a24-607fd786bbf8.png)

I think it could be problem with key between tables **data_types** and **data_rows**, the number does not equel. 
![data_rows](https://user-images.githubusercontent.com/15262273/38135692-dd1767d0-3419-11e8-8604-82efa80ccabd.png)
![data_types](https://user-images.githubusercontent.com/15262273/38135694-df7f6748-3419-11e8-916e-eba52cfb4e4d.png)

**Comment by MrCrayon** [comment]
I don't see anything wrong in the database, Cardinality (the column you highlighted) is ok.
You say:
> Everithing work good, but now I have problem.

So something must have happened, or you meant that everything worked good before the transfer?
If the problem happened after the transfer and you still have a working copy make a diff of files and database, if nothing is different it might be a problem with configuration but I can't imagine why a misconfiguration would lead you to an unauthorized error.

I can suggest you to make sure you didn't touch any file under vendor folder.
After that debug the error, check where exactly happens and which parameters are passed, you could also use [phpdebugbar](https://github.com/barryvdh/laravel-debugbar) to help you find the problem.

**Comment by lukelee36** [comment]
I was installed phpdebugbar as you recommend me. When I try use some menu itemt it show me this error:
_array:4 [
  "ability" => "browse"
  "result" => false
  "user" => 1
  "arguments" => "[0 => Object(App\Tip)]"
]
_
The vendor folder hasn't any change. It stops work when I try repair one of menu item which has this problem. It starts after I by mistake remove bread for this menu item. After I try to reuplouad tables data_types and data_row. And after reuplouad didnt work any menu_items only dashboard and database.

**Comment by MrCrayon** [comment]
I don't know, it looks like you messed up your db, even if I don't really know why menus are showing, since they should also check the ability to browse.
You can try to make a fresh voyager installation with dummy data and look for what is different from your  application database.
I helped you with the tools but you are the one that has to do the debug.
Good luck!

**Comment by lukelee36** [comment]
I find the way, I made new database, use migration and sort tables one after the other without key control. Now is allright, thanks.

**Comment by foRsxs** [comment]
My way was, to check out table permisson_role and ADD manual permissions for my model
