### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Shymoney** [thedevdojo/voyager#2921]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.1
- Database Driver & Version:

**Comment by emptynick** [comment]
Is your root directory set to `public` as described in the [Laravel docs](https://laravel.com/docs/5.5/installation#configuration)?

**Comment by cyrildewit** [comment]
@Shymoney do you still encounter this issue? Otherwise this issue can be closed.

**Comment by fletch3555** [comment]
Closing due to lack of response.

**Comment by hammouda** [comment]
i am having this same problem 
can we reopen the issue ?

**Comment by emptynick** [comment]
You can open your own issue, but - please - with more informations.
