### ISSUE TITLE
Crop and Resize images in default edit-add.blade.php

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#2923]
- Laravel Version: 5.5.*
- Voyager Version: Last Version
- PHP Version: 7
- Database Driver & Version:

### Description:
Resizing images in voyager adding menu. 

### Steps To Reproduce:
I am using default edit-add.blade.php
I need resize and crop images. I can't figure out how to make this. I searched all github/voyager tabs. Anyone help me? Thanks in advance.

**Comment by emptynick** [comment]
Then you didn't read the [docs](https://voyager.readme.io/docs/additional-field-options#section-image)

**Comment by aozen** [comment]
I missed that. I am so sorry for duplicating easy problem. Actually its not a real problem. I am new at voyager. Rookie mistakes. Thanks so much.
