### ISSUE TITLE
translation for pages excerpt field seems not working

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#2924]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1.9
- Database Driver & Version: Mysql 5.7.19

### Description:
I've found that I can use the the translate() method on the the voyager to retrieve the translated Posts or Pages like this example ( $posts[0]->translate()->title ) using the TCG\Voyager\Models\Post model.
everything works fine. but the excerpt field on the pages model is returning the same data for both language (en, fr). could be a possible bug

### Steps To Reproduce:
Enable multi language with voyager, then try create a new pages with different languages and check the excerpt field

**Comment by emptynick** [comment]
The excerpt field is just not translatable ootb.
https://github.com/the-control-group/voyager/blob/cbf4a37cae72bc2594788fb5db785b1a0cc398e5/src/Models/Page.php#L15
If you want, you can create a custom model for pages and add excerpt to the array.
