### ISSUE TITLE
Add extra field in voyager registration page

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2926]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version:

### Description:
How to add extra field in registration page for voyager admin panel and how to know the password encrypted function for password field ?

Add extra field in voyager registration page
![user form](https://user-images.githubusercontent.com/22347660/38231840-449206b2-3736-11e8-9418-9c0415aecef4.PNG)

password encryption function in database
![database](https://user-images.githubusercontent.com/22347660/38231886-7666b8f4-3736-11e8-8692-8de48fd53b9e.PNG)

**Comment by fletch3555** [comment]
It's not a registration page, it's a user creation page.  Registration implies you create your own account.  To change that page, you'll need to override the view and add the field.

The password encryption is the default laravel method, bcrypt.  I recommend reading up on https://laravel.com/docs/5.6/hashing and https://laravel.com/docs/5.6/authentication

As a final note, these kinds of "how to" questions are best asked in our Slack group, so we can reserve Github issues for actual bugs and feature requests for the package.
