### ISSUE TITLE
Display name instead id

### ISSUE THREAD

**Issue by JFOC** [thedevdojo/voyager#2929]
- Laravel Version: 5.4.
- Voyager Version: 1.0.16
- PHP Version: 5.6.32
- Database Driver & Version: MySQL 5.6.38

### Description:
I have product category and product tables. and each product has a category and both already has BREAD. When Adding new product I want to display the category name (varchar) dropdown instead of category id (integer).

Do I need to have special instruction at "Optional Details" ?

### Steps To Reproduce:
1. Go to products
2. Add New
![screen shot 2018-04-04 at 11 36 47](https://user-images.githubusercontent.com/240271/38288957-ee23277a-37fd-11e8-9d69-6dd30894dcbd.png)
![screen shot 2018-04-04 at 11 44 41](https://user-images.githubusercontent.com/240271/38288958-ee598144-37fd-11e8-8cc8-8526dd21c320.png)
![screen shot 2018-04-04 at 11 45 20](https://user-images.githubusercontent.com/240271/38288960-ee96fea2-37fd-11e8-90f2-3179ebefb650.png)
![screen shot 2018-04-04 at 11 47 49](https://user-images.githubusercontent.com/240271/38289010-3d5f346e-37fe-11e8-84e1-e2f4e376426a.png)
![screen shot 2018-04-04 at 11 48 59](https://user-images.githubusercontent.com/240271/38289012-3d9bd266-37fe-11e8-9120-07bdb8eb39f7.png)

**Comment by MrCrayon** [comment]
I hope I won't sound rude but IMHO looks like you need to research a bit more on how relationships work.
I think what you are trying to do is:
Product BelongsTo Category, product should have a field category_id used as foreign key
(this relationship is already defined in the details field, no need for the "Has One")
Category HasMany Product, and category_id is the column used as reference.

Also, as it says in the notice message, you need to set up relationship method in your class, so you'll need to add to Product:
```php
    public function categoryid()
    {
        return $this->belongsTo(Category::class);
    }
```
or if you want to use the more standard method name _category_, you'll need to add it to the details:
```json
{
    "relationship": {
        "key": "id",
        "label": "name",
        "method": "category"
    }
}
```

**Comment by JFOC** [comment]
Hi,
Thank you for the response. I solve it

**Comment by PSDeora** [comment]
i searching lot but cant find solution for why browse showing id instead of name even edit and create bread showing drop down with name correctly
my relation is like this :

public function userId() : BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    } 

finally i got a solution by simply adding  BREAD accessors to my model like 

    public function getUserIdBrowseAttribute()
    {
        return $this->usertId->name;
    }

this replace id with name in browse bread

use for refrence https://voyager-docs.devdojo.com/customization/bread-accessors
