### ISSUE TITLE
css appears in view

### ISSUE THREAD

**Issue by manozthapa** [thedevdojo/voyager#2930]
Laravel Version: 5.5.39
Voyager Version: 1.0
PHP Version:7.2.3

### Description:Why does it shows the css code in my view, but not in the dashboard
``
            <p>{{$blog->description}}</p>
            
        

``
![screenshot 15](https://user-images.githubusercontent.com/33196113/38291297-cf132492-37fe-11e8-91e1-96fd70435acd.png)
![screenshot 16](https://user-images.githubusercontent.com/33196113/38291299-cf44edd8-37fe-11e8-9d6a-acaeff1c9f98.png)

**Comment by emptynick** [comment]
https://laravel.com/docs/5.6/blade#displaying-data

**Comment by manozthapa** [comment]
i was able to display the data but css also appeared in the data

**Comment by emptynick** [comment]
Read the link I posted, especially the part about unescaped data
