### ISSUE TITLE
Column not found: 1054 Unknown column 'guard_name'

### ISSUE THREAD

**Issue by flackovic** [thedevdojo/voyager#2933]
- Laravel Version: 5.6
- Voyager Version: dev.1.x.dev
- PHP Version: 7.2.1
- Database Driver & Version: 10.1.22-MariaDB

### Description:
In proces of seeding, there is an error that column "guard_name" can't be found in roles table.

Error:
`Column not found: 1054 Unknown column 'guard_name' in 'where clause' (SQL: select * from `roles` where `name` = dev and `guard_name` = web limit 1)`

Looking at `create_roles_table` from voyager migrations there is no "guard_name" created in the first place.
Only name, display_name and timestamps are created.

### Steps To Reproduce:
1. composer require tcg/voyager:dev-1.x-dev
2. php artisan voyager:install

**Comment by fletch3555** [comment]
I can't find a single reference to `guard_name` in Voyager's code.  This field is most likely something in your code.
