### ISSUE TITLE
Save settings remove other settings

### ISSUE THREAD

**Issue by trollsk1n** [thedevdojo/voyager#2934]
- Laravel Version: 5.6.15
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.1
- Database Driver & Version: MySQL

### Description:
it is necessary each time to load.

### Steps To Reproduce:
In /admin/settings page I added some new settings for type file. And changed preloader, background for admin.
When I upload a new file, it clears the other fields the same background and the preloader, it is necessary each time to load everything, if you need to change something

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/3059
Fix in https://github.com/the-control-group/voyager/pull/3060

**Comment by shzad63** [comment]
```
public function update(Request $request)
    {
        // Check permission
        $this->authorize('edit', Voyager::model('Setting'));

        $settings = Voyager::model('Setting')->all();

        foreach ($settings as $setting) {
            $content = $this->getContentBasedOnType($request, 'settings', (object) [
                'type'    => $setting->type,
                'field'   => str_replace('.', '_', $setting->key),
                'details' => $setting->details,
                'group'   => $setting->group,
            ]);

            if ($content === null && isset($setting->value)) {
                $content = $setting->value;
            }

            $key = preg_replace('/^'.str_slug($setting->group).'./i', '', $setting->key);

            $setting->group = $request->input(str_replace('.', '_', $setting->key).'_group');
            $setting->key = implode('.', [str_slug($setting->group), $key]);
            $setting->value = $content;
            $setting->save();
        }

        //request()->flashOnly('setting_tab');

        return back()->with([
            'message'    => __('voyager::settings.successfully_saved'),
            'alert-type' => 'success',
        ]);
    }
```

in the
vendor\tcg\voyager\VoyagerSettingsController
replace update function in setting controller with that code 
issue will be solved

**Comment by emptynick** [comment]
@shzad63 thats basically what #3060 does
