### ISSUE TITLE
Can not delete image from multiple-Images in Post Bread

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#2935]
- Laravel Version: 5.5.4
- Voyager Version: 1.0.16
- PHP Version: 7.0.28
- Database Driver & Version: Mysql 5.7

### Description:
I add multiple images in "Additional Fields" in post bread.
Upload and display images are ok.
But i can't delete image.
The "X" link has no effect

### Steps To Reproduce:
IN admin/database/posts/edit :
- Add row type TEXT,  NULL,  named "img_galery"

IN admin/database/posts/bread/edit :
- SET "img_galery" field as Multiple images with JSON {"resize": {"width": "999", "height": "null"}}

**Comment by emptynick** [comment]
Please search before opening a new issue
https://github.com/the-control-group/voyager/issues/2547
