### ISSUE TITLE
Using Bread fields in front end forms.

### ISSUE THREAD

**Issue by ranjitWBS** [thedevdojo/voyager#2937]
- Laravel Version: 5.5.*
- Voyager Version: 1.0.*
- PHP Version: 7.2
- Database Driver & Version: MySQL

-Description: How can I use bread fields in my front end form? For example I want to make a Job Application form for which all the fields should be managed(Add new fields or delete/Update older) by Voyager bread system or something like that?  How can I do that?

**Comment by fletch3555** [comment]
Description field is required.  You shouldn't put the entire question in the title field.

**Comment by ranjitWBS** [comment]
Sorry I am new to GitHub.:-(

**Comment by fletch3555** [comment]
No worries.  Thanks for fixing it.

In short, I think you may have misunderstood the purpose of Voyager.  Voyager is intended to be an admin tool, not a full CMS/form-builder.  There is no (built-in) way to use the dynamic fields outside of Voyager.
