### ISSUE TITLE
I can not keep the coordinates of Google maps in the database mysql

### ISSUE THREAD

**Issue by Simon-Abrahamyan** [thedevdojo/voyager#2939]
- Laravel Version:  5.5.*
- Voyager Version: ^1.0
- PHP Version: >=7.0.0
- Database Driver & Version: >=7.0.0

### Description:
The map shows but I can not change the coordinates and when I synchronize the column in the database remains empty
Column type POINT, Input Type coordinates.

**Comment by fletch3555** [comment]
Please don't open duplicate PRs.  We can reopen the other one now that you've updated it.
