### ISSUE TITLE
Failed: Timestamps on Voyager v1.0.17

### ISSUE THREAD

**Issue by VienLe93** [thedevdojo/voyager#2941]
- Laravel Version: 5.5
- Voyager Version: 1.0.17
- PHP Version: 7.2.3
- Database Driver & Version: 5.5.59-0+deb8u1 - (Debian)

### Description:
- Create table with timestamps get issue. 
![screenshot from 2018-04-06 15-40-05](https://user-images.githubusercontent.com/28533635/38411225-ca5780e8-39b0-11e8-98d3-2b7d3818247f.png)
- I'm add multilanguage, then alert notification don't working.
Help me!

**Comment by Hillnut** [comment]
I have the same error on a fresh install. adding timestamps or changing the table makes an error.
Running on laravel 5.5 and Homestead as latest dev env

**Comment by Braiani** [comment]
Hey. I was having this issue until the package doctrine/dbal have being update.
So, try run a `composer update` and see if the error keeps occurring.
I have the `doctrine/dbal` Version `2.7.1` and I don't have errors any more.

**Comment by Hillnut** [comment]
thanks @Braiani , updating dbal to 2.7.1 did the trick. all id functional now
