### ISSUE TITLE
Multilanguage not working

### ISSUE THREAD

**Issue by nazimcode** [thedevdojo/voyager#2943]
- Laravel Version: 5.5.*
- Voyager Version:1.0.7
- PHP Version:
- Database Driver & Version:

### Description:
I just installed a fresh Laravel with Voyager. Once all is well and i can enter to /admin, i change:

```
  'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'fr',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en','fr',
            //'pt',
        ],
    ],
```
But the dashboard and pages remains in english
### Steps To Reproduce:
Install Laravel with Voyager
Change multilingual in voyager.php

**Comment by nazimcode** [comment]
a little precison when i go in english file in published/lang directory and i delete all the file voyager still work fine

**Comment by cotiga** [comment]
Try
config/app.php
```
return [
    ...
    'locale' => 'fr',
    ....
];

```

**Comment by emptynick** [comment]
Solution provided here and on Slack
