### ISSUE TITLE
how to fetch data automatically in dropdown from database as per selection from dropdown in laravel

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2944]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
I have a two dropdown. how can i get a value from database as per the selection in above dropdown ??
by default i am getting all the data in my dropdown.

**Comment by fletch3555** [comment]
Voyager does not support the ability to populate one field based on the selected value of another.  You can build this yourself if you need it.
