### ISSUE TITLE
Automatic Eager Loading causing index page to fail to load

### ISSUE THREAD

**Issue by whyayala** [thedevdojo/voyager#2946]
- Laravel Version: 5.5
- Voyager Version: 1.0.5
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7

### Steps To Reproduce:
add `public $with = ['relationName'];` to a model, then try and navigate to it's voyager index page.

<img width="1430" alt="screen shot 2018-04-09 at 2 22 16 pm" src="https://user-images.githubusercontent.com/7398790/38518094-a1410122-3c01-11e8-807e-9de905a96e0a.png">

**Comment by emptynick** [comment]
Please search before you open a new issue.
https://github.com/the-control-group/voyager/issues/2561
