### ISSUE TITLE
How to create foreign key relation.

### ISSUE THREAD

**Issue by manozthapa** [thedevdojo/voyager#2948]
- Laravel Version: 5.5.39
- Voyager Version: 1.0
- PHP Version:7.2.3

### Description:I want to create foreign key relation in migration.But I could not find migration. Is there any other alternative.
I need this for showing comment in particular blog.

**Comment by fletch3555** [comment]
I don't quite understand what you mean by "couldn't find migration"... are you looking for one to add it to?

Generally speaking, you shouldn't modify files from a package unless the package explicitly tells you to.  If you modify something, then we change it in a subsequent release, you'll likely lose it when you update.

Instead, you should create a new migration to add what you need

**Comment by manozthapa** [comment]
Thanks,.I assumed voyager creates the migration of model itself. It would have been great to have the option for migration similar like the option to create Model.

**Comment by fletch3555** [comment]
Yes, that has been requested a numerous times. Unfortunately, there's no easy way to build these migrations automatically.  We haven't found a package that does what we want, and none of us have had the time to build it, so we're stuck waiting for the community to contribute it.

I think you'll find it's more complicated than you thought
