### ISSUE TITLE
Custom admin menu giving 404

### ISSUE THREAD

**Issue by alxkos** [thedevdojo/voyager#2949]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.17
- PHP Version:
- Database Driver & Version:

### Description:
Trying to create custom admin menu page, but getting 404.

### Steps To Reproduce:
made exactly like in video:
menu builder -> new testpage with url /admin/testpage
created resources/views/vendor/voyager/testpage/browse.blade.php
and getting 404.

if i make resources/views/vendor/voyager/posts/browse.blade.php and trying to override posts page, it's working.

Didnt find a fix for this. Only found that this is permissions issue.
please advice.
thanks

**Comment by emptynick** [comment]
Which video do you refer to?
You will need to have BREAD defined for `testpage` or a controller method plus a route in the `voyager` group

**Comment by alxkos** [comment]
Should I make separate BREAD for testpage? So how then I will use it in admin menu?

If i'm using route (route::get('test-page', 'HomeController@testpage')->name('test-page')) I need to move the blade file into views. and if i'm trying to use @extends('master:voyager') i'm getting an error.

I didnt find in doc how to make custom menu page in voyager. I'm missing something?
Thanks

**Comment by o0alexela0o** [comment]
Sorry, my bad. controller method working. extends voyager too, but content goes not into the window. but aside?!

**Comment by alxkos** [comment]
And does this mean that overriding views working only for buildin stuff? 
like posts?
https://voyager.readme.io/docs/overriding-views
I cannot use to make custom menu and use this technique?

**Comment by emptynick** [comment]
That is not how Voyager works.
I dont know which video you refer to, but I suggest you to ask in our Slack group so we can help you with this problem.
Closing.
