### ISSUE TITLE
<i> tag get removed on saving page.

### ISSUE THREAD

**Issue by deep12650** [thedevdojo/voyager#2950]
-Laravel Version: 5.6
-Voyager Version: 1.x.dev
-PHP Version: 7.2
-Database Driver & Version: MySQL 5.7

### Description:
<i> tag got removed while saving page from the admin panel. Editor needs update.

### Steps To Reproduce:
Edit any page and add any <i> tag and save page. It will get removed after that. <i> tag is very important, most of theme using font-awesome nowadays.

**Comment by ebelendez** [comment]
This is a bug in TinyMCE HTML editor, but you may use:`<span class="fa fa-bus">&nbsp;</span>`

**Comment by emptynick** [comment]
Closing as a possible suggestion was given.
Maybe TinyMCE solved that issue as well.
