### ISSUE TITLE
Where can I found the documentation for translations?

### ISSUE THREAD

**Issue by PointfullDevelopers** [thedevdojo/voyager#2952]
I don't understand how can I:

1. Use the translations table inside Voyager
2. Select the desired language for the admin panel

Is there any documentation for it?

Thanks

**Comment by emptynick** [comment]
You found https://github.com/the-control-group/voyager/pull/561 but I will answer you here:
1. `When I add ['en' => 'English', 'sv' => 'Swedish'], to the 'locale' on the config it gives error.`
    Thats not the syntax the config expects. Its just `['en', 'sv']`. Both Post and Page Models already define translatable attributes. You dont need to change anything.
2. Is a Laravel configuration. See how to set the app-locale [here](https://laravel.com/docs/5.5/localization#introduction)
3. Please fill out the [issue template](https://github.com/the-control-group/voyager/blob/1.0/ISSUE_TEMPLATE) so we know which versions you are using

**Comment by PointfullDevelopers** [comment]
@emptynick 

Thank you for you reply,

But problem still persists, if I change the array to that I get the following error:
ErrorException (E_ERROR) - Array to string conversion

```
protected function loadPath($path, $locale, $group)
    {
        if ($this->files->exists($full = "{$path}/{$locale}/{$group}.php")) {
            return $this->files->getRequire($full);
        }
 
        return [];
    }
```

I'm using the latest version of Voyager and Laravel 5.5

**Comment by PointfullDevelopers** [comment]
Found it, was changing the default config for laravel and not the voyager config!
