### ISSUE TITLE
Suggestion for 1.x switch edit and view buttons colors

### ISSUE THREAD

**Issue by MrCrayon** [thedevdojo/voyager#2957]
- Laravel Version: #.#.#
- Voyager Version: 1.x
- PHP Version:
- Database Driver & Version:

### Description:
As the title say IMHO the view button should be primary and edit button should be warning, to follow an order from the most safe to most dangerous action: view, edit, delete.

I don't know if there is a reason for the color scheme used and I can't cite right now any external link that can sustain my preference but it makes sense to me.

![schermata da 2018-04-12 07-23-14](https://user-images.githubusercontent.com/6875243/38657833-9a0294ac-3e22-11e8-8e39-2061032bf564.png)

**Comment by emptynick** [comment]
`1.x` uses [Actions](https://github.com/the-control-group/voyager/tree/1.x-dev/src/Actions) for those buttons, so you are free to edit them or add new buttons.

**Comment by MrCrayon** [comment]
Yes I saw that, thanks.
I just pointed it out because it made sense to me for that to be the default scheme color, but that's just my personal opinion.
