### ISSUE TITLE
Can we send email when admin add user?

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#2958]
- Laravel Version: 5.5.*
- Voyager Version: Last v.
- PHP Version: 7.*
- Database Driver & Version: 

### Description: 

**Help Request**

I am trying to send e-mail to user when admin add user. 
For example: Welcome "$user->name", your username is "$user->username" and your password is "$user->password". I tried every thing. But can not send any email. Do we have a way to make this e-mailing system easier? How can i intervene the Userpage in Adminpanel?

**Comment by emptynick** [comment]
You dont want to change the userpage.
You are looking for [Eloquent Events](https://laravel.com/docs/5.5/eloquent#events)

**Comment by JFOC** [comment]
@emptynick  would be great if there is an example integrating into voyager ?

**Comment by emptynick** [comment]
Its this simple:
```
public static function boot() {
    parent::boot();

    static::created(function($user) {
        //Send your mail
    });
}
```

We dont document it as it is Laravel stuff

**Comment by JFOC** [comment]
@emptynick  is this related to  https://github.com/the-control-group/voyager/blob/1.0/src/Events/BreadAdded.php ?

**Comment by emptynick** [comment]
No, my example is native Eloquent. Its simpler, and fits better in this case in my opinion.

**Comment by emptynick** [comment]
Closing as solution was provided.
