### ISSUE TITLE
how can i get a thumbnail in multiple image

### ISSUE THREAD

**Issue by michellhsilveira** [thedevdojo/voyager#2961]
- Laravel Version: 5.5.40
- Voyager Version: 1.0.17
- PHP Version: 7.1
- Database Driver & Version: MYSQL 5.6

### Description:
how can i get a thumbnail in multiple image?
I'm using the code below but only returning the original image
` <img class="img-fluid" src="{{Voyager::image(json_decode($veiculo->thumbnail('small', 'imagem'))[0])}}"   alt="Veiculo">`

**Comment by emptynick** [comment]
This is (now) in our docs:
https://docs.laravelvoyager.com/core-concepts/helper-methods
