### ISSUE TITLE
Package Installation

### ISSUE THREAD

**Issue by navalevivek** [thedevdojo/voyager#2964]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version: 7+
- Database Driver & Version:

### Description:
I  have installed your package from https://github.com/the-control-group/voyager this link.
I followed all steps, but no output in url, neither I am getting to see any admin login page or nothing.

Could you please guide me through the whole proper procedure or do I need to make any code changes in any other file.

Any help would be highly appreciated.

**Comment by fletch3555** [comment]
The docs already outline all of the necessary steps. If that doesn't work for you, then you likely did something wrong.

It would be helpful if you provided the steps you followed, troubleshooting steps attempted, any errors you may have encountered (ideally with screenshots or copy/paste or the error message and stacktrace if available), etc.

My first question is this.  Did the base laravel install, before installing Voyager on top, work?

**Comment by ghost** [comment]
@navalevivek Did you remember to put the /admin at the end of your url?

**Comment by emptynick** [comment]
Closing due to age.
Please provide more informations if this is still a problem.
