### ISSUE TITLE
How to change the multiple image upload flow?

### ISSUE THREAD

**Issue by yevgenatlanov** [thedevdojo/voyager#2968]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7
- Database Driver & Version: 5.7

### Description:

i'm using multiple image uploader with custom view and it works fine. I can write the in json type field in mysql: 
` ["services/folder/image1.jpg", "services/folder/image2.jpg"]`
 and read them easily with foreach. 

I've modified mysql json cell to the next view and need to change the flow how controllers write image links to the next view: 
`{{"alt": "alt", "src": "services/folder/image1.jpg", "title": "title"}, {"alt": "alt", "src": "services/folder/image2.jpg", "title": "title-2"}} `

How can i do it? where i have to look? i'm open for any help. Thanks in advance. 

p.s. Yes, i want to write title and alt for image that i'm uploading.

**Comment by emptynick** [comment]
Closing in favor of #3009
