### ISSUE TITLE
Insert the user's id in the author_id field

### ISSUE THREAD

**Issue by bryanezavala** [thedevdojo/voyager#2969]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: MySQL

I have seen that in the tables "pages" and "posts" the id of the authenticated user is automatically inserted in the field author_id, how can I do the same for other tables?
I'm a novice, I hope you can help me, thank you very much.

**Comment by fletch3555** [comment]
https://github.com/the-control-group/voyager/blob/1.0/src/Models/Page.php#L36

In the future, "how to ..." questions are best asked on our Slack group's #help channel.   We prefer to reserve github issues for actual code issues and feature requests for the package.
