### ISSUE TITLE
Undefined variable: dataType in View

### ISSUE THREAD

**Issue by vasildervenski** [thedevdojo/voyager#2970]
- Laravel Version: 5.4.3
- Voyager Version: 1.0.17
- PHP Version: 7.1
- Database Driver & Version: 5.6

Hi, first want to thank you for the amazing product and your commitment.
### Description:
So I'm trying to direct visitors to different (from dashboard)  view when they log into admin. 

```php
// Main Admin  Route
Route::get('/', ['uses' => 'Voyager\DelegationsController@index',   'as' => 'dashboard']);
```
Created a custom controller that extends VoyagerController, made the index method to show the browse.blade.php view which is in /resources/views/vendor/voyager/delegation.

``` php
<?php

namespace App\Http\Controllers\Voyager;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Constraint;
use Intervention\Image\Facades\Image;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\VoyagerController;

class DelegationsController extends VoyagerController
{
    public function index()
    {
        return Voyager::view('voyager::delegation.browse');
    }

   
}
```
In the database settings I pointed to the customized controller.
![Image of database settings](http://res.cloudinary.com/vasild/image/upload/v1523669792/delegations_sgf9bw.jpg) 

I get the following error:
```
Undefined variable: dataType (View: /home/onedesi/brgfapp/resources/views/vendor/voyager/delegation/browse.blade.php)
--
in 74494d40969d547e469a13af27f6c7dad7b3debc.php (line 1)
at CompilerEngine->handleViewException(object(ErrorException), 0)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/home/onedesi/brgfapp/storage/framework/views/74494d40969d547e469a13af27f6c7dad7b3debc.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'alerts' => array()))in CompilerEngine.php (line 59)
at CompilerEngine->get('/home/onedesi/brgfapp/resources/views/vendor/voyager/delegation/browse.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'alerts' => array()))in View.php (line 137)
```
First line in  74494d40969d547e469a13af27f6c7dad7b3debc.php is
```php
<?php $__env->startSection('page_title', __('voyager.generic.viewing').' '.$dataType->display_name_plural); ?>
```

**Comment by amrnn90** [comment]
If you use the contents of the original `browse.blade.php` view, then you'll also have to create and pass it the variables it needs from the controller method you override.
[See the index method.](https://github.com/the-control-group/voyager/blob/5a4e960a0134d0be1a1d9ee851b12407ef583419/src/Http/Controllers/VoyagerBreadController.php#L99-L109)

**Comment by emptynick** [comment]
I dont really understand what you are trying to do.
You are saying you want to define different dashboards, then you talk about `bread/browse`.
Those are two different things. That might be your problem.

**Comment by vasildervenski** [comment]
Sorry, maybe I'm not very clear. Following is a view of my admin. I just want to show the content of the first menu item, when users log in. It's not that I want different dashboards but more as hiding the dashboard and showing different content.

@amrnn, yes I'm using the original `browse.blade.php`, but I'm overriding different controller method, which is `VouagerController`. And variables you point are from `VoyagerBreadController`

![](https://res.cloudinary.com/vasild/image/upload/c_scale,w_766/v1523719217/adminJPG_gfgy2v.jpg)

**Comment by MrCrayon** [comment]
As @amrnn said you can't call Voyager::view() without passing all the data the view it's expecting.
If the only thing you need to do is change the view you don't need to extend the controller you can override the view creating resources/views/vendor/voyager/delegations/browse.blade.php as explained here: https://voyager.readme.io/docs/overriding-views.
If you need to override the controller than you'll need to have a look at VoyagerBreadController and see what it does before calling Voyager::view()

P.S.
Reading again what you did I think maybe you only needed to change the routing and you were done.
Your mistake is that you are extending VoyagerController to show a bread view that requires data generated by VoyagerControllerBread.

**Comment by vasildervenski** [comment]
Hi, 
Thanks to everyone! 
At the end I just changed the routing using redirect.
I think this thread is ok to be closed.

**Comment by fletch3555** [comment]
Thanks for the follow-up.  Closing.
