### ISSUE TITLE
Voyager support for Laravel 5.6

### ISSUE THREAD

**Issue by JunaidQadirB** [thedevdojo/voyager#2971]
- Laravel Version: 5.6.*
- Voyager Version: 1.0.17
- PHP Version: 7.1.15
- Database Driver & Version:

### Description:
Voyager gives this error when tried to install

`  Problem 1
    - Conclusion: remove laravel/framework v5.6.15
    - Conclusion: don't install laravel/framework v5.6.15
    - tcg/voyager 1.0.x-dev requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev], illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
`
### Steps To Reproduce:
In my laravel app
issued this command:
`composer require tcg/voyager`

**Comment by emptynick** [comment]
Please [search ](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+in%3Atitle+5.6)before opening a new issue

**Comment by JunaidQadirB** [comment]
Oh, I apologize being an idiot.

**Comment by govardhanaaleswara96** [comment]
what is the pros and cons of voyager laravel
