### ISSUE TITLE
Accessing to Hooks view without permission

### ISSUE THREAD

**Issue by carlost89** [thedevdojo/voyager#2972]
- Laravel Version: 5.5.40
- Voyager Version: 1.0.17
- PHP Version: 7.0.28
- Database Driver & Version: MySQL 5.7.21

### Description:

I'm able to access /admin/hooks page even if I don't have permission to do it.

### Steps To Reproduce:

1. Disable Browse Hooks permission from the role you are using and save changes.
2. Access to admin/hooks by typing the URL in the browser.
3. You can still browse, view, create, edit and delete Hooks.

**Comment by MrCrayon** [comment]
It happens also in
- Voyager Version: 1.0.16

**Comment by MrCrayon** [comment]
BTW hooks are not actually part of Voyager, you should check https://github.com/larapack/voyager-hooks and indeed I don't see any permission check in HooksController.

**Comment by carlost89** [comment]
Yes, digging in the code I realized that it belongs to Larapack package and in HooksController there's no permission check even if Voyager has the permission radio option of Hooks added by default.

I just want to have the hooks permissions working.

**Comment by carlost89** [comment]
@MrCrayon Do you think it could be a good idea overriding HooksController and adding the permissions checks by ourselves?

**Comment by MrCrayon** [comment]
If you only need to enable disable access to hooks management I think a cleaner option would be to add a middleware to check authorization like is done in VoyagerAdminMiddleware to check browse_admin permission.

**Comment by fletch3555** [comment]
I would not recommend overriding the controller to make that work... Why don't you just open a PR for that package to add the permissions check?

**Comment by fletch3555** [comment]
Closing as it's not a Voyager issue.

**Comment by MrCrayon** [comment]
PR https://github.com/larapack/voyager-hooks/pull/22
