### ISSUE TITLE
is voyage no compatible with laravel 5.6 ?

### ISSUE THREAD

**Issue by hamzafaouzi** [thedevdojo/voyager#2973]

**Comment by emptynick** [comment]
[Search ](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+in%3Atitle+5.6)before opening a new issue

**Comment by hamzafaouzi** [comment]
@emptynick  thanks for not helping

**Comment by emptynick** [comment]
You're welcome.

**Comment by fletch3555** [comment]
@hamzafaouzi, he did help. He pointed you at the search feature where you can see this has been asked and answered easily 20 times already. Sorry, but I hope you can understand our frustration with these repeated questions. It's really not that hard to search for `5.6` before submitting your issue.
