### ISSUE TITLE
Reporting bug: Normal users can edit their roles to admin

### ISSUE THREAD

**Issue by Xoshbin** [thedevdojo/voyager#2975]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
There's an issue with normal users that I think it's a bug that users when they are in admin panel can edit their roles to admin from profile. and I did try to remove the role field in the edit page I clouldn't find out where it's the file.

### Steps To Reproduce:
1- Login to voyager admin panel.
2- Go to profile in top right.
3- click edit profile
4- change role from user to admin.

**Comment by emptynick** [comment]
This has been discussed various time, and has been changed in `1.x-dev`
See https://github.com/the-control-group/voyager/issues/2824 and https://github.com/the-control-group/voyager/issues/2879
