### ISSUE TITLE
adding voyager to existing laravel application

### ISSUE THREAD

**Issue by robertlight** [thedevdojo/voyager#2976]
- Laravel Version: latest
- PHP Version: 7.0.5
- Database Driver & Version: mysql (using php mysqli)

I have a Twilio based IVR (interactive voice response) system built using Laravel.  I would like to keep all my existing code and add an admin dashboard to the system.

Can I just go to my existing laravel root directory and enter:

   "composer require tcg/voyager"

and have it use my existing database?

is it really that easy?

  - Bob

**Comment by cyberlightdev** [comment]
As near as I can tell voyager does not officially support 5.6 yet, so likely, no. :/

**Comment by robertlight** [comment]
php artisan --version    
Laravel Framework version 5.1.41 (LTS)

I'm running 5.1.41 it seems

**Comment by robertlight** [comment]
I gave it a whirl... here's what I got:

# composer require tcg/voyager
Using version ^1.0 for tcg/voyager
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v5.5.40 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.39 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.37 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.36 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.35 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.34 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.33 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.28 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.2 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.17 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.16 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - illuminate/support v5.5.0 requires php >=7.0 -> your PHP version (5.6.32) does not satisfy that requirement.
    - Conclusion: remove laravel/framework v5.1.41
    - Conclusion: don't install laravel/framework v5.1.41
    - tcg/voyager v1.0.0 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.1 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.10 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.11 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.12 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.13 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.14 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.15 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.16 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.17 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.2 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.3 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.4 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.5 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.6 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.7 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.8 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.9 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.1.41
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.1.41
    - Installation request for laravel/framework (locked at v5.1.41, required as 5.1.*) -> satisfiable by laravel/framework[v5.1.41].
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].


Installation failed, reverting ./composer.json to its original content.


I have php7 available on my hosting account... I set .htaccess in public/ to:

> AddHandler application/x-httpd-php70 .php

and phpInfo() shows php7.0 as the working version.

Any ideas how I fix this?

**Comment by MrCrayon** [comment]
Are you using cPanel?
https://github.com/composer/composer/issues/6918

**Comment by fletch3555** [comment]
Voyager does not support laravel 5.1.* (which also isn't `latest` by the way).  We currently support 5.4 and 5.5.

In order to update to 5.5, you would have to install php 7.0 (per the Composer error message). I see you told apache to use php7 with the public/.htaccess file. Unfortunately, composer doesn't use that, so it won't make a difference. You'll have to research how to tell composer what version to use, but that's beyond the scope of this project.
