### ISSUE TITLE
 I need to validate my form before or after Voyager input.

### ISSUE THREAD

**Issue by yalks** [thedevdojo/voyager#2979]
- Laravel Version:  5.5
- Voyager Version: 1.0 
- PHP Version: 7.2
- Database Driver & Version: mysql 5.7

### Description:

I need to validate my form before or after Voyager input.
### Steps To Reproduce:

I need to validate my form before or after Voyager input.

My first thought is to use the laravel observer saving to use the custom function in the saving method.

May I ask if my idea is feasible?

Or where the code needs to be improved

Create an observer
Use a custom function
![_20180416155946](https://user-images.githubusercontent.com/24969844/38797215-64b43672-4190-11e8-98f0-f814b7627182.png)

Custom function details

![_20180416160123](https://user-images.githubusercontent.com/24969844/38797343-bbc7c6ae-4190-11e8-894e-8866c6407d76.png)

dumpvalidation information
![_20180416160308](https://user-images.githubusercontent.com/24969844/38797367-d0270eac-4190-11e8-8b5f-50035d6ad94c.png)
![_20180416160317](https://user-images.githubusercontent.com/24969844/38797384-dc5a191c-4190-11e8-8702-cbbe76c10251.png)

![_20180416160629](https://user-images.githubusercontent.com/24969844/38797409-ec94447e-4190-11e8-84cb-61c9ba407e0b.png)
![_20180416160617](https://user-images.githubusercontent.com/24969844/38797412-eed3c4e4-4190-11e8-9e14-dbad2ef352f6.png)

Please tell me whether my idea is feasible

If I'm wrong, please tell me how I should do it

Thanks very much

**Comment by fletch3555** [comment]
Why don't you just use the already existing validation functionality.....? https://voyager.readme.io/docs/validation
