### ISSUE TITLE
New module

### ISSUE THREAD

**Issue by navalevivek** [thedevdojo/voyager#2984]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
If I want to create a  new module then how would I do that, is there any basic documentation provided here. Or if I have my my module ready then how do I merge in voyager package and start using it.

**Comment by emptynick** [comment]
What is a `module` in your case?
Also, for questions please join our Slack group.

**Comment by carlost89** [comment]
Can you please share your slack group?

**Comment by cyrildewit** [comment]
https://voyager-slack-invitation.herokuapp.com/

**Comment by navalevivek** [comment]
@emptynick : 

See its very simple question : 

Basically if I want to develop a new module like this voyager package has a 'Post' module, so the same way if I want to build a new module for News or 'Testimonial', then from scratch how do I make it, so that it will have add/edit/delete/view functionality at yoyager admin backend and can easily fetch same on frontend.

So could you please give me steps of it, hope this is very simple question I have asked.

Any help would be greatly appreciated.

**Comment by emptynick** [comment]
Those are the very basics of Voyager.
Please read the [Docs](https://voyager.readme.io/docs) and watch our [Videos](https://laravelvoyager.com/academy/)

**Comment by navalevivek** [comment]
Ok, got it, but if I want to view the pages at frontend then how can I view them at frontend, if suppose I am creating any pages from backend.

**Comment by emptynick** [comment]
You can find infos about this [here](https://devdojo.com/blog/tutorials/working-with-voyager-on-the-front-end)
**But** Voyager is not a CMS and you will have to build those things on your own.
