### ISSUE TITLE
forgot email/password functionality

### ISSUE THREAD

**Issue by jppalmis** [thedevdojo/voyager#2985]
Laravel Version: 5.5.*
Voyager Version: Last v.
PHP Version: 7.*
Database Driver & Version:

Does voyager have forgot email/password functionality especially when the main admin account forgot login credentials. it is good as the whole system is nothing if that happens.

**Comment by simonhunt** [comment]
Am I right in thinking that you still have access to the database through the usual Artisan commands on the command line?

If so, you should be able to change the admin user password this way if you forget it.

**Comment by jppalmis** [comment]
I tried using tinker, but when I insert value in password column, it literally inserted the password. it is not hashed. and I cant logged in using it.

**Comment by simonhunt** [comment]
So, when you update the model in Tinker you need to encrypt the password manually.

This means your command should look something like:

    $user = User::find(1);
    $user->password = bcrypt('newPassword');
    $user->save();

And that should do it.

**Comment by marktopper** [comment]
What @simonhunt said should do it for you.

However, it has been requested multiple times to have the option to allow users to recover their passwords directly on the Voyager login page.
Personally, I don't have time for that now - but we are open to pull requests.

**Comment by andrewnclark** [comment]
Made a start on a PR, hope to get something submitted over the weekend for you all.

**Comment by marijnz0r** [comment]
Hey @andrewnclark,
Did you manage to create a pull request?
If you need some help, let us know.
Kind regards

**Comment by andrewnclark** [comment]
Apologies everyone! I have made a start on something and then work took priority. I'll open a PR with my current WIP this evening and see if I can get it wrapped up over the next few days.

**Comment by andrewnclark** [comment]
@marijnz0r here's the current WIP - https://github.com/andrewnclark/voyager/tree/issue-2985

I'll get it wrapped up over the next few days I hope. I need to implement a voyager password broker so as not interfere with the default Laravel auth functionality but so far so good. Any feedback will be appreciated, but the feature is coming!

**Comment by dexcell** [comment]
Still no love?

**Comment by fletch3555** [comment]
Closing as this was started under #3405
