### ISSUE TITLE
MenuItemPolicy shouldn't use $slug to check browse permission

### ISSUE THREAD

**Issue by MrCrayon** [thedevdojo/voyager#2986]
- Laravel Version: 5.6.*
- Voyager Version: 1.x-dev
- PHP Version: 7.1.16
- Database Driver & Version: mysqlnd 5.0.12-dev

### Description:
When using a model with a composite name like table name _voyager_hooks_ permission is going to be browse_voyager_hooks but permission checked using $slug is going to be browse_voyager-hooks.
This will return true because not found.

```php
        // If permission doesn't exist, we can't check it!
        if (!self::$permissions->contains('key', 'browse_'.$slug)) {
            return true;
        }
```

### Steps To Reproduce:
Create a bread model with a composite name
remove browse permission
Menu item still appears

### Expected result:
Menu Item should not be shown

**Comment by MrCrayon** [comment]
I think bug was introduced with #2832 because this will always fail:
```php
if ($str = self::$datatypes->get($slug)) {
    $slug = $str->name;
}
```
This should solve the problem:

```diff
        if (self::$datatypes == null) {
-            self::$datatypes = DataType::all();
+            self::$datatypes = DataType::all()->keyBy('slug');
        }
```

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/2988
