### ISSUE TITLE
How can I hide menu

### ISSUE THREAD

**Issue by navalevivek** [thedevdojo/voyager#2992]
- Laravel Version: 5.5
- Voyager Version: #.#.#
- PHP Version:

### Description:
How can I hide any menu from admin backend side or if I want to keep it in inactive state?

### Steps To Reproduce:
Voyager Admin side : Menu

**Comment by navalevivek** [comment]
in videos or tutorial, everywhere given to show or create menu but no where about how to keep it in Inactive state or if I dont want to show at admin left side or at frontend, how do i do that?

**Comment by MrCrayon** [comment]
Remove browse permission for related bread and menu item will be automagically hidden.

**Comment by navalevivek** [comment]
thanks a lot for ur help but can u b specific cuz I tried to remove option from 'browse' in checkbox but i am getting diff. error.

so can u tell me exactly from which section "Remove browse permission for related bread and menu item will be automagically hidden."

ny help wld b highly appreciated.

**Comment by MrCrayon** [comment]
Let's say you have Posts in your menu' and you want to hide it, you need to go to Edit Role and remove Browse Posts from the Role you want to hide it for.
I think you already did that.
That should hide item Posts in your menu' also users with that role won't be able to go on /admin/posts anymore since they don't have permission to do so.
Of course I am taking for granted that you have Bread set for Posts (Tools->Database->Add Bread).

Regarding your error if you are not more specific I have no idea.

**Comment by navalevivek** [comment]
Thanks a lot, I did that, and not getting error as well.

Quick help...really appreciated sir.

**Comment by navalevivek** [comment]
Thanks a lot, I did that, and not getting error as well.

Quick help...really appreciated sir.

**Comment by navalevivek** [comment]
Hey,

I have one doubt, is this Voyager Admin Package, is this free to download and integrate in our application.

Would not be there any copyright issue or something, can somebody guide me on this.

Any help would b highly appreciated.

**Comment by fletch3555** [comment]
This package is released with the MIT license, which basically allows you to do whatever you want with it so long as the license and proper attribution is maintained. Both of which are handled automatically by composer (with the license file maintained with the code in the vendor folder)

**Comment by navalevivek** [comment]
thank u for the information

**Comment by navalevivek** [comment]
thank u for the information

**Comment by navalevivek** [comment]
hello,

" Illuminate \ Contracts \ Encryption \ DecryptException
The payload is invalid."

I am getting this error once user login from frontend site.

This user is created by admin side from admin backend side.

Could you please help me on this, any help would be highly appreciated.

Thanks in advance.
