### ISSUE TITLE
What is the password encryption method in voyager admin panel

### ISSUE THREAD

**Issue by arafatrahman13** [thedevdojo/voyager#2995]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version:

### Description:
I have a voyager admin panel. I want to registered and login an user from my frontend. Now my question is what is the password encryption method voyager used in their admin panel thus an user can create or log in

**Comment by cyrildewit** [comment]
Hey @arafatrahman13, maybe looking at the code of the login page that comes with Voyager can help you further.

https://github.com/the-control-group/voyager/blob/1.0/resources/views/login.blade.php#L64

As you see, you just need to have a simple form that's posting the data to {{ route('voyager.login') }}. Include the required fields: email, password and crsf_field and you're good to go.

I don't know if there's a better alternative, but this looks like the best approuch to me.

Regards,
Cyril

**Comment by fletch3555** [comment]
Voyager doesn't do anything specific for password hashing.  We just use Laravel's default auth scaffolding, which (currently) uses `bcrypt` as the hashing algorithm.

If you want auth on your front-end, just add it (`artisan make:auth`), then configure it as-needed per the Laravel documentation.
