### ISSUE TITLE
Compass page does not load

### ISSUE THREAD

**Issue by SturmB** [thedevdojo/voyager#2997]
- Laravel Version: 5.6.17
- Voyager Version: dev-1.x-dev
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7.21

### Description:

Navigating to Voyager's "Compass" page results in an endlessly-spinning wheel, the page never fully loads, and the Chrome tab cannot even be closed. Perhaps I just missed a step when I updated things, since I last touched this project a month ago, but I cannot imagine what it would be.

### Steps To Reproduce:

1. Visit your Laravel/Voyager site + `/admin` and sign in.
2. On the left sidebar, expand "Tools" and click on "Compass".
3. Witness a page that never loads.
4. Get ready to have to either force-quit your web browser or restart your computer altogether, because now that browser tab will never close (at least, in Chrome).

**Comment by fletch3555** [comment]
Can you share whether there are any browser console messages (errors or otherwise)?

I don't understand how it would be able to lock up the browser that way.

**Comment by SturmB** [comment]
Absolutely _nothing_ appears in the browser console at the default level. Looking at all levels, only unimportant (and likely unrelated) items appear:

<img width="572" alt="screen shot 2018-04-19 at 7 34 36 am" src="https://user-images.githubusercontent.com/6216224/38989236-249cfc5c-43a4-11e8-846c-24546a64bae3.png">

**Comment by MrCrayon** [comment]
Since this reference an old Voyager version I'm closing it.

If you are still experiencing this problem you might try to disable browser extensions and update Voyager.
If everything fails feel free to open another issue.
