### ISSUE TITLE
How to install voyager manually without use of command or local to live server

### ISSUE THREAD

**Issue by reach2rahulbharti** [thedevdojo/voyager#2998]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by cyrildewit** [comment]
You can better ask these type of questions in Voyager's Slack group! Or Google for similiar things. You will get your answer much faster!

Here are some posts:
- http://saamaweb.com/2017/05/17/upload-laravel-5-4-project-on-shared-hosting-without-ssh-access/
- https://medium.com/laravel-news/the-simple-guide-to-deploy-laravel-5-application-on-shared-hosting-1a8d0aee923e
- https://laravel.io/forum/03-06-2015-how-to-setup-laravel-5-in-shared-hosting
- http://jafty.com/blog/installing-laravel-without-composer/

I used this Google search link: https://www.google.com/search?q=how+to+upload+laravel+app+to+web+hosting+without+composer

**Comment by fletch3555** [comment]
@cyrildewit's suggestions should help you.

In addition to that, however, we require all version information to be provided in our issues.  If you find yourself in a situation where version information isn't applicable, you're probably in a situation where you're trying to ask a "how to" question, which is best asked on our Slack group
