### ISSUE TITLE
Make only one login/user table for Voyager and Auth

### ISSUE THREAD

**Issue by jojo58fr** [thedevdojo/voyager#2999]
- Laravel Version: 5.6.16
- Voyager Version: voyager:dev-1.x-dev
- PHP Version: 7.2.4
- Database Driver & Version: MySQL 

### Description:

Hello,

I want to make a global login for my website which work like this : 

- If you are admin, redirect to the Voyager Panel
- If you are ....., redirect to ....
-If you are a classic user redirect to the homepage

How to disable http://.../admin/login to simply use only http://.../login,

In my database, i need to setting up only one user table with groups, is there any things about Laravel voyager to know ?

### Steps To Reproduce:

A lasted version of Laravel with Voyager in voyager:dev-1.x-dev installed

**Comment by emptynick** [comment]
You basically can just run `php artisan make:auth`. This will create a login/register page for you.
You just need to implement the redirection to `/admin` and so on.

**Comment by jojo58fr** [comment]
Okay, I wasn't sure if that was the right way to go. I'll check it out :+1:
