### ISSUE TITLE
Problem deleting user

### ISSUE THREAD

**Issue by webinfinita** [thedevdojo/voyager#3]
What I did
1. Install laravel and the package normally following the instructions
2. Create a new user from the frontend (app.dev/register)
3. Then Login to the admin and try to delete that user, and shows me this error:
<img width="1024" alt="screen shot 2016-10-28 at 14 07 03" src="https://cloud.githubusercontent.com/assets/2981203/19819108/b7c9a89c-9d18-11e6-9ea4-44a0a8ec25f9.png">

`Use of undefined constant undefined - assumed 'undefined'`

However, the second time I tried, the user was deleted successfully.

**Comment by marktopper** [comment]
Are you able to reproduce this in the newest version?

I can however can not reproduce this issue.

**Comment by marktopper** [comment]
/closing
> Seems to be resolved in the latest version.

Please ping me if I'm wrong.
