### ISSUE TITLE
[Feature] Forgot password

### ISSUE THREAD

**Issue by handiwijoyo** [thedevdojo/voyager#300]
I'm open to discussion whether we need to include the forgot password form into Voyager. Please give you thought, I can create PR for this.

**Comment by tokkerbaz** [comment]
It would be helpful, also i want to mention the Input Types, there is no date input=)) i know that i can implement ourself... but if voyager have that input , would be great! for example i have birthday column in my users table, and its dbtype is DATE

**Comment by marktopper** [comment]
@tokkerbaz You are more than welcome to make a pull request adding the `date` input type.

**Comment by handiwijoyo** [comment]
Close the issue for now, will reopen the issue if anyone has interest in this.

**Comment by Luc45** [comment]
+1

**Comment by amc123-glitch** [comment]
This would definitely be a nice feature to have. Being as I prior to implementing voyager into my laravel development, I had to create my admin and normal users view from scratch. Both having the standard method and look of the forgot password route. 

While I plan on still keeping normal login and admin login separate, having the form for admin login would be helpful. If not supplying the forgot password form out of the box, maybe highlighting in the docs how to add it in ourselves.

All in all, satisfied with voyager, have noticed some hiccups when logged in on Safari browser but not in Chrome, everything else seems to currently work well with laravel 5.5.

**Comment by jannejava** [comment]
+1
