### ISSUE TITLE
more then one files field issue

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#3002]
- Laravel Version: 5.5
- Voyager Version: 1.0.17
- PHP Version: 7.0

### Description:
(I'm looking/asking on slack and PR but didn't find a solution)
if in a form I put more files fields, the first one seems to work, the other fields store 0, instead of the json referring to the uploaded files, in the db. 

### Steps To Reproduce:
I tested with 3 file fields (fat1, fat2, fat3) in my bread module.

![schermata 2018-04-19 alle 10 51 40](https://user-images.githubusercontent.com/1073883/38992667-be55a0a0-43e1-11e8-8dc7-520dc6a54e69.png)

The files are all uploaded but in the DB only the first field store the right value on the table.

![schermata 2018-04-19 alle 14 57 31](https://user-images.githubusercontent.com/1073883/38992903-69a36b86-43e2-11e8-8502-6df4353c1ca5.png)
![schermata 2018-04-19 alle 15 00 13](https://user-images.githubusercontent.com/1073883/38992915-714a4896-43e2-11e8-98a5-1aed5ecb8223.png)

**Comment by marcelolimaweb** [comment]
Good morning, did you solve it?
I have a similar problem. I have 05 file type fields, however, when I will edit the ones that are filled, the files will disappear and only the one that has been edited will last.

**Comment by MrCrayon** [comment]
I can't reproduce the problem, it was probably fixed sometime in a past release.

If you are still experiencing this problem please open another issue.
