### ISSUE TITLE
File data url incongruence on BREAD manage page

### ISSUE THREAD

**Issue by b4dnewz** [thedevdojo/voyager#3006]
- Laravel Version: 5.5.x
- Voyager Version: 1.0

### Description:
The download url used for "file" data row type is incongruent between pages.

### Steps To Reproduce:
Create a new BREAD with uploadable files, upload something, go to Browse page you can download it, go to Edit page you can download it, go to View page: is not working.

On browse page is: `Storage::disk(config('voyager.storage.disk'))->url($file->download_link)` which is good, while on "View" page is not.

[Good line](https://github.com/the-control-group/voyager/blob/1.0/resources/views/bread/browse.blade.php#L148-L150) vs [Bad line](https://github.com/the-control-group/voyager/blob/1.0/resources/views/bread/read.blade.php#L109-L111) this is much more noticeable if you are using a custom 'disk' or file upload location which is not the default one.

**Comment by cyrildewit** [comment]
**Are you going to send a PR?**

Otherwise I can take a look at it and submit a solution if I have one (probably the one you provided). Asking this because I don't want to steal your contributions 😈

**Comment by b4dnewz** [comment]
thanks @cyrildewit, do it man, I do not have much time even if is small changes :( and no worries, it's not about stealing, it's about make it less buggy lol

**Comment by cyrildewit** [comment]
~@b4dnewz what's your GitHub noreply email? Or can I paste your `xxx@xxx.it` email into the commit?~ Never mind!
