### ISSUE TITLE
columns types turn to boolean when trying to edit a line or add one

### ISSUE THREAD

**Issue by FaouziLakhlifi** [thedevdojo/voyager#3007]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: >= 7.0.0
- Database Driver & Version:

### Description:
I have created 3 new tables through migrations. I can browse, view, delete but when I try to add or edit most of the columns types turn into booean. when I consult the types through voyager database everything looks good.
here's how they look on the database
https://drive.google.com/file/d/1_jgp7zgBQ8zOtUthevsgBsJkRVGk6FL1/view?usp=sharing
here's what I get when trying to edit or add a line
https://drive.google.com/file/d/1H_bsEpJEe0nS0ZQ0ZdbfVjWxUZY5zF2y/view

**Comment by MrCrayon** [comment]
Type showed in edit page depends on input type selected on BREAD, go to Tools->BREAD and edit it from there.

**Comment by FaouziLakhlifi** [comment]
Thank you @MrCrayon
