### ISSUE TITLE
Can't change admin password.

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3010]
- Laravel Version: 5.6.*
- Voyager Version: 1.1
- PHP Version: 7.1.3
- Database Driver & Version: mysql 5.7.21

### Steps To Reproduce:
- setup new laravel project
- composer require
- create database
- setup env to connect database
- voyager install --with-dummy
- login with admin@admin
- click profile
- change password, save.

**Comment by mtimbs** [comment]
Modifying any admin info seems to override the role_id column to NULL in the users table.

Trying to upload a user image has the same affect
