### ISSUE TITLE
Upgrading from 1.0 to 1.1 - "Necessary Migrations" are broken links

### ISSUE THREAD

**Issue by drehimself** [thedevdojo/voyager#3011]
- Laravel Version: 5.5.34
- Voyager Version: 1.0.15
- PHP Version: 7.2.1
- Database Driver & Version: MySQL 5.7.18

### Description:
Trying to upgrade from 1.0 to 1.1. Following the docs: https://voyager.readme.io/docs/10-to-11

These migrations do not exist:
- https://github.com/the-control-group/voyager/blob/1.x-dev/publishable/database/migrations/2017_11_26_013050_add_user_role_relationship.php
- https://github.com/the-control-group/voyager/blob/1.x-dev/publishable/database/migrations/2017_11_26_014010_drop_permission_groups_table.php
- https://github.com/the-control-group/voyager/blob/1.x-dev/publishable/database/migrations/2017_11_26_015000_create_user_roles_table.php

### Temporary Workaround

Found them here: https://github.com/nickbryan/voyager/tree/540d7e37ce4c701c847491247b22589eea5b4231/migrations

**Comment by deepaksp** [comment]
i think VoyagerBreadController also moved to VoyagerBaseController

**Comment by emptynick** [comment]
Fixed, thanks.
@deepakSP Where did you find `VoyagerBreadController `?

**Comment by deepaksp** [comment]
i was extending VoyagerBreadController  to make few additions in posts and it broke after update after checking source code ii understood i need to extend VoyagerBaseController

e.g.

now 

use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class VoyagerPostController extends VoyagerBaseController {
}

before 1.1

use TCG\Voyager\Http\Controllers\VoyagerBreadController as BaseVoyagerBreadController;

class VoyagerPostController extends BaseVoyagerBreadController{
}

i wanted to extend post functionality so i ended up googling and found out here how to do it
https://github.com/the-control-group/voyager/issues/2058

**Comment by emptynick** [comment]
That is true, but this is not mentioned in the docs.
