### ISSUE TITLE
Unique validation exception on BREAD edit

### ISSUE THREAD

**Issue by jpolive** [thedevdojo/voyager#3021]
- Laravel Version: 5.4.36
- Voyager Version: 1.1.0
- PHP Version: 7.2.4
- Database Driver & Version: 5.7.22

### Description:
I have come across some weird behavior when trying to update a BREAD with an unique validation to an attribute.

In this case I was trying to validate a slug with:
`"validation": { "rule": "unique:product_categories,slug" }`
on create it works fine but if I try to edit it will throw an exception:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.product-categories' doesn't exist (SQL: select count(*) as aggregate from product-categories where slug = categoria-1-2 and id <> 5)`
the table in question is **product_categories** but for some reason it is using the url slug for the BREAD **product-categories**

Is this expected behavior? any reason to use the BREAD url slug `$slug` at: `src/Http/Controllers/Controller.php: 165`
```
// Fix Unique validation rule on Edit Mode
if ($is_update) {
    foreach ($rules[$fieldName] as &$fieldRule) {
        if (strpos(strtoupper($fieldRule), 'UNIQUE') !== false) {
            $fieldRule = \Illuminate\Validation\Rule::unique($slug)->ignore($id);
        }
    }
}
```

### Steps To Reproduce:
Unique validation on a BREAD with diferent url slug to table name should trigger it.

**Comment by MrCrayon** [comment]
Now I understand why when I created a custom rule called unique_multiple it was being overridden, I had to change name to make it work.
The use of strpos can't be right there, maybe there should be an explode with :
Also I think the same thing could be obtained setting the right rule in BREAD but I might be wrong.

That piece of code was introduces with PR #2457

**Comment by f0reclone** [comment]
Yeah this piece of code is definitly not right. Tried the same thing as @jpolive and it just ignored the rule input by just creating a new rule.

The following code works for me. Keep in mind that it is nescessary to add field name at the end in the code or database.

```
{
    "validation": {
        "rule": "unique:tenant.users,email",
        "messages": {
            "unique": "Please use an unique email."
        }
    }
}
```


```
foreach ($rules[$fieldName] as &$fieldRule) {
                    if (strpos(strtoupper($fieldRule), 'UNIQUE') !== false) {
                        $fieldRule = $fieldRule . ",$id,id";
                    }
                }
```


Here are some solutions. But the best would be to use the Laravel Parser for this rule or make the Validator and add the ignore afterwards.
https://stackoverflow.com/questions/23587833/laravel-validation-unique-on-update

**Comment by emptynick** [comment]
Looks like this was fixed in https://github.com/the-control-group/voyager/pull/3040.
Please let us know if not.

**Comment by PSDeora** [comment]
Add ".id" , after table_name to ignore current row id when edit / update with unique validation 

"validation": {
        "rule": "required|unique:post.id,post_title",
        "messages": {
            "required": "This :attribute field is a must.",
            "unique": "This: your message"
        }
    }
