### ISSUE TITLE
Use Thumbnail with Translatable Collection

### ISSUE THREAD

**Issue by Terixer** [thedevdojo/voyager#3023]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2

### Description:
I can not use the "thumbnail" function in a photo from the collection which is translated.

#### Controller
``` 
 $posts = App\Post::orderBy('created_at')->limit(3)->get()->translate(App::getLocale());
```
#### Template
````
@foreach($posts as $post)
...
   <img src="{{Voyager::image($post->thumbnail('small'))}}">
...
@endforeach
````
### ErrorException
`Call to undefined method TCG\Voyager\Translator::thumbnail()`

**Comment by emptynick** [comment]
Did you try something like
` $posts = App\Post::orderBy('created_at')->limit(3)->withTranslations(App::getLocale())->get();`
?

**Comment by Terixer** [comment]
Thank you ! It works.

**Comment by imronmaulana007** [comment]
Terixer sorry and what your solution?

**Comment by fletch3555** [comment]
@imronmaulana007, the snippet posted by @emptynick was the solution.

**Comment by h2jose** [comment]
I did get this error using in controller:
$locale = $request->session()->get('locale');
$posts = $posts->translate($locale, 'fallbackLocale');

I don't know if it is the best solution, but i did:

**Controller:**
$posts = Post::all();
return view('demo.home')
			->with('posts', $posts )
			->with('lang', $lang );

**View:**
{{ $property->getTranslatedAttribute('title', $lang, 'fallbackLocale') }}

this works!

**Comment by jimwhiteside** [comment]
For the next one that follows, how to avoid having to continually use `getTranslatedAttribute()` ...

The problem is that the original Model gets wrapped in a Translator model. So, in the template of the original in the OP's code:

```
<img src="{{ Voyager::image( $post->getModel()->thumbnail('small') ) }}">
```
