### ISSUE TITLE
How to change Rich text editor to Markdown editor in voyager V1.1.0

### ISSUE THREAD

**Issue by izhuomine** [thedevdojo/voyager#3025]
- Laravel Version: 5.6.12
- Voyager Version: V1.1.0
- PHP Version:7.2.0
- Database Driver & Version:MySql 5.7

### Description:
I want to change Rich text editor to Markdown editor,，But I don't know how to do it

**Comment by emptynick** [comment]
You can just change the field-type in the Bread-Settings of your model?!

**Comment by izhuomine** [comment]
where and how>I am a beginner！Thank you very much

**Comment by cyrildewit** [comment]
If I'm right:

1. Login with a user that have access to the Database admin page
2. In the left menu under tools, click on Database
3. Search for the desired table and click on edit bread.
4. Scroll down until you see the desired field.
5. Choose markdown from the type list.
6. Save bread

_Typed with mobile phone_

**Comment by emptynick** [comment]
That is absolutely correct.

Also please read the docs and try things first. This is one of the most basic functions of Voyager.
Additionally, if you have further questions, please ask them in our Slack group.

**Comment by izhuomine** [comment]
it is working,i will try things first! Thanks everyone
