### ISSUE TITLE
Slugify for Voyager - Russian map 

### ISSUE THREAD

**Issue by Margo57** [thedevdojo/voyager#3027]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version:

### Description:

In Russian, "ь": "" and "ъ": "", but they are replaced by "-". It is not right!
Печенье = Pechene, not Pechen-e...

**Comment by taiwanleaftea** [comment]
I have the same issue in the latest version of Voyager. 

## Workaround

_map_russian function in resources/assets/js/slugify.js for Russian language contains this for 'ъ', 'ь', 'Ъ', 'Ь':

` _map_russian: function() {
                return {<skipped>
                   'ъ':'', 'ь':'', 
                    'Ъ':'', 'Ь':''
<skipped>
                };
            },`

So **_slug += (this.chars[str.charAt(i)]) ? this.chars[str.charAt(i)] : str.charAt(i)** doesn't replace those letters, and the letters are replaced later for '-' in this regexp **replace(/[^a-z0-9]/g, _sep)**

Adding this regexp **replace(/[ьЬъЪ]/g, "")** solve the problem.
