### ISSUE TITLE
Error on edit user profile, fresh install

### ISSUE THREAD

**Issue by jppalmis** [thedevdojo/voyager#3028]
- Laravel Version: 5.6.17
- Voyager Version: 1.1.*
- PHP Version: 7.2.0

after installing voyager, I logged in with admin@admin.com then I went straight to profile and 
edit the name. (any changes in profile will produce this error. let say you change the profile picture.)
once I click saved/submit, this error prompt.

![capture1](https://user-images.githubusercontent.com/26365137/39084568-b5ae0cec-45aa-11e8-9a08-6d7ae8bf49ff.JPG)

then I looked into phpmyadmin to check if changes were done, it was. but the role_id was also included in updating the user. by default the role_id was set to 1, after updating and receiving an error, it changed to null.

![capture2](https://user-images.githubusercontent.com/26365137/39084549-72cf3716-45aa-11e8-859e-cd7999e8c5ce.JPG)

**Comment by MrCrayon** [comment]
It's a known issue: #3010 #3018.
There are two PR proposed to solve this #3016 and #3020.

**Comment by emptynick** [comment]
Going to close this as it was _halfly_ fixed in #3014 and will be fixed entirely in a future version.

**Comment by miltonardila** [comment]
I would like to comment that to date the problem still remains. But it is only solved with #3020 editing src/Traits/VoyagerUser.php

**Comment by MrCrayon** [comment]
@miltonardila did you try on a fresh install?

**Comment by miltonardila** [comment]
@MrCrayon We are developing the application two months ago, I do not know since when this solution.
