### ISSUE TITLE
Uncaught TypeError: Cropper is not a constructor

### ISSUE THREAD

**Issue by lucentlogix** [thedevdojo/voyager#3036]
- Laravel Version: 5.6.0
- Voyager Version: 1.1.0
- PHP Version: 7.2.4
- Database Driver & Version: Mysql 5.7

### Description:
cropperjs 1.3.1+ brakes cropping functionality
Uncaught TypeError: Cropper is not a constructor
cropperjs 1.3.0 is working fine for me, might be a good idea to lock this version until a fix can be produced. 

### Steps To Reproduce:
cd vendor/tcg/voyager
npm install
npm run dev
cd ../../../
php artisan vendor:publish --tag=voyager_assets --force
Navigate to and select an image in media
Click Crop
Inspect console output

**Comment by emptynick** [comment]
Closing as #3832 was merged (into 1.x, to be released in a future 1.2 release)
