### ISSUE TITLE
Relationship in BREAD shows no results.

### ISSUE THREAD

**Issue by NichoTheMan** [thedevdojo/voyager#3039]
- Laravel Version: 5.6.17
- Voyager Version: 1.1
- PHP Version: 7.2.4
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:

I have a table called Discord Guilds and a table called Discord Messages. A bot i'm writing in Node.JS is storing the data for the Discord Guilds and each message in Discord messages in those tables, and that works without issues.

When i set up a relationship between the _guild_id_ field in Discord Messages to the _guild_id_ field in Discord Guilds it says _No Results_ when i browse the BREAD but when i check manually in the database the data is correct in both tables.

When i edit the row through it does show the correct results through the relationship.

(Sorry in advance if i didnt explain it well enough).

**Discord Guilds Table**
![discord_guilds](https://user-images.githubusercontent.com/5790097/39103283-312f67e4-46aa-11e8-9b50-0920b4cd04f7.png)

**Discord Messages Table**
![discord_messages](https://user-images.githubusercontent.com/5790097/39103292-3afb0814-46aa-11e8-9418-5bbe1c4a07bc.png)

**Relationship Details in Discord Messages**
![relationship](https://user-images.githubusercontent.com/5790097/39103373-abbe93e0-46aa-11e8-8725-4d7adbab8056.png)

**Bread for Discord Messages**
![discord_messages_no_results](https://user-images.githubusercontent.com/5790097/39103327-61533892-46aa-11e8-8a60-6c1bcced6519.png)

**Editing the row in voyager gives me the correct discord guild through the relationship**
![discord_message](https://user-images.githubusercontent.com/5790097/39103331-67498fd0-46aa-11e8-9813-1ce10a77a7d2.png)

**Comment by Azurues24** [comment]
I have the same problem. Im tracing it for 5 hours. negative result. I think versi on 1.0 is more stable than 1.1

**Comment by jppalmis** [comment]
I second the motion. relationship shows no result. @MrCrayon

**Comment by MrCrayon** [comment]
I think the problem is that you are using a BelongsTo relationship connected to guild_id that is not the primary key in DiscordGuild.
Why are you not using id? Or in other words if guild_id it's the primary key what is id?
Also check if you defined the relationship in your models.

**Comment by jppalmis** [comment]
@MrCrayon have you tried it? 
I also get this same problem with version 1.1. 

I'm rolling back to 1.0 and see what  fit best.

**Comment by emptynick** [comment]
@MrCrayon is right, what is `guild_id` supposed to be?
@Azurues24 you can switch versions, but if the relationships are not defined properly, no version will work.

**Comment by MrCrayon** [comment]
In a fresh installed voyager 1.1 with dummy data, add this relationship to pages:
![schermata da 2018-04-23 11-52-06](https://user-images.githubusercontent.com/6875243/39119749-f3bf5552-46ec-11e8-8e97-f8e96f281244.png)
go edit a page, that will add the user as author_id of the page, and then see in the listing user is there.

**Comment by jppalmis** [comment]
@emptynick I have no problem with relationship when Im in 1.0, I just noticed it today that in 1.1 relationship is not kicking in. I did fresh install to double check that it was not my fault that causing the problem, also, i did not use the dummy post table i did my own table. 

I will try again today with fresh install and I'll update you guys, hopefully I find answer @NichoTheMan 's problem.

**Comment by MrCrayon** [comment]
I think the only difference between 1.0.17 and 1.1 regarding relationship in browse is from #2983 
I can't think how that could cause this problem but let us know.

**Comment by NichoTheMan** [comment]
@MrCrayon The guild_id is provided by the Discord API. Discord servers are called "guilds" so that is their unique identifier to discord servers.

Is there a way i can make a relationship between two tables without using the primary key?

I have not defined the relationship in my models, this is not in the docs;
https://voyager.readme.io/docs/relationships

**Comment by Fighix** [comment]
As I recall that’s not the design right now :/

**Comment by NichoTheMan** [comment]
I guess i could change the structure of my tables but this feature should be added in future releases.

**Comment by Fighix** [comment]
Yeah that’d be cool, I faced a similar issue recently (probably dealt with it the wrong way ‘cause time’, ending up creating an extra ID column, having two unique integers in my table, associated with every records and one record being a ‘NULL equivalent’ record)

**Comment by MrCrayon** [comment]
Why not drop id and use guild_id as primary key in Discord Guilds table if that's the actual primary key?
Then in your DIscordGuild model you have to set:
```php
    protected $primaryKey = 'guild_id';
```
if you want to rely on data you are getting this should do it.

**Comment by NichoTheMan** [comment]
@MrCrayon The issue im faced with then is that it does not show the primary key higher than "2147483647", guild ids look like this "430774095940943883".

**BREAD**
![e9842260fa545c67493ca1d24add791f](https://user-images.githubusercontent.com/5790097/39165565-566232c2-4785-11e8-98f7-89f52b376cc3.png)

**PHPMyAdmin**
![551a71bde41a52c87c8011f321b71984](https://user-images.githubusercontent.com/5790097/39165570-5d708a32-4785-11e8-8e67-d6ee7e77b7e1.png)


@Fighix Yea, it's a little hard to work with these restrictions.

**Comment by MrCrayon** [comment]
Why are you using a varchar for guild_id when Discord documentation says it's a snowflake type aka int64?
Try using a bigint field in database, and then also check what's the configuration for that field in your BREAD.

**Comment by NichoTheMan** [comment]
@MrCrayon I'm using bigint for guild_id
![88e5e077facdf458663a4f888c60a574](https://user-images.githubusercontent.com/5790097/39165918-40ad129c-4787-11e8-9016-969dddad493b.png)

**Comment by MrCrayon** [comment]
BTW you can keep your id as primary key in your table and have guild_id set as unique, then you just set guild_id as primaryKey in your model and it works.
Works for me, there must be something you are missing:
```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Author extends Model
{
    protected $primaryKey = 'author_id';
}
```
![schermata da 2018-04-24 06-24-58](https://user-images.githubusercontent.com/6875243/39166219-e65531ba-4788-11e8-9bb2-dde55bd5f36c.png)

![schermata da 2018-04-24 06-31-32](https://user-images.githubusercontent.com/6875243/39166300-314edbf8-4789-11e8-86e7-a7359050fef1.png)

![schermata da 2018-04-24 06-27-10](https://user-images.githubusercontent.com/6875243/39166223-ec23e398-4788-11e8-9eb8-65eb8681a599.png)

![schermata da 2018-04-24 06-27-21](https://user-images.githubusercontent.com/6875243/39166227-f1c88308-4788-11e8-839a-d0a6475d71bf.png)
![schermata da 2018-04-24 06-28-59](https://user-images.githubusercontent.com/6875243/39166231-f7e15e18-4788-11e8-9d93-dd2b32fcf8d2.png)

**Comment by NichoTheMan** [comment]
@MrCrayon Doing it like this works, thank you.

But in the discord guilds table it still outputs 2147483647 even though it is correct in the database.
![e3bc3e1bdbdc88cd50b829e55e042129 1](https://user-images.githubusercontent.com/5790097/39167011-0ba5005e-478d-11e8-8351-2b1d07f1ac7c.png)

![21503eb4378a35c283fc977228037381](https://user-images.githubusercontent.com/5790097/39167037-39d0eb6e-478d-11e8-91bb-fa6c012466e0.png)

![2ec13aa7735cbd68223c5c20d2f0a91e](https://user-images.githubusercontent.com/5790097/39167057-5611d3ba-478d-11e8-850f-31d12ca12a87.png)

**Comment by MrCrayon** [comment]
It probably means that you still have the wrong type somewhere.

**Comment by NichoTheMan** [comment]
@MrCrayon Well, once i remove `protected $primaryKey = 'guild_id';` rom my model it will display the entire ID but then the relationship does not work.

**Comment by NichoTheMan** [comment]
What fixed it was disable incrementing for the primary key in my model.

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;


class DiscordGuild extends Model
{   
    protected $primaryKey = 'guild_id';
    public $incrementing = false;
}

```

I'll close the thread.

**Comment by gamenic-madan-pd** [comment]
try this one:
composer require tcg/voyager dev-master
