### ISSUE TITLE
Empty created_at 

### ISSUE THREAD

**Issue by lucasdcrk** [thedevdojo/voyager#3043]
- Laravel Version: 5.6.17
- Voyager Version: 1.1.0
- PHP Version: 7.2
- Database Driver & Version: SQLITE3

### Description:

When I create a record with the BREAD, the created_at column is null.
I would like it to have the current time

### Steps To Reproduce:

Create a record

**Comment by lucasdcrk** [comment]
![screenshot_95](https://user-images.githubusercontent.com/17224437/39141321-c55dd61c-4727-11e8-80f4-d82b79939f6e.png)

**Comment by emptynick** [comment]
This is nothing Voyager controls, but pure Eloquent behaviour.
https://laravel.com/docs/5.6/eloquent#defining-models
You actually have to define that you **dont** want to use timestamps.
Can you confirm that you dont have `public $timestamps = false;` in your model?

**Comment by lucasdcrk** [comment]
I don't have public `$timestamps = false;` in my model

**Comment by MrCrayon** [comment]
You need to have _add_ unchecked for created_at field in your bread configuration, otherwise you'll need to fill the value manually.
I can't think of anything else.

**Comment by marktopper** [comment]
Can you share your bread settings for that table along with the Model class.

**Comment by lucasdcrk** [comment]
![screenshot_112](https://user-images.githubusercontent.com/17224437/39196824-5b246d3a-47e3-11e8-88b4-66e547a24bff.png)
![screenshot_109](https://user-images.githubusercontent.com/17224437/39196821-59d2ae88-47e3-11e8-8275-92f7d18848ff.png)
![screenshot_110](https://user-images.githubusercontent.com/17224437/39196822-5a0139e2-47e3-11e8-8f0b-43438d37adbc.png)
![screenshot_111](https://user-images.githubusercontent.com/17224437/39196823-5ae7d780-47e3-11e8-9274-6c1d9b49d993.png)

**Comment by lucasdcrk** [comment]
Here is the Model
![screenshot_108](https://user-images.githubusercontent.com/17224437/39196861-729b9952-47e3-11e8-9d56-ee43cc80e7a9.png)

**Comment by MrCrayon** [comment]
@lucasdcrk you have already the solution in my previous comment.
This is the default configuration for timestamps when you create BREAD:

![schermata da 2018-04-24 17-28-37](https://user-images.githubusercontent.com/6875243/39197614-31911188-47e5-11e8-8aa3-d788709da52b.png)

**Comment by lucasdcrk** [comment]
It worked! Thanks!
I changed it by mistake
