### ISSUE TITLE
Issues with Default Numeric Values

### ISSUE THREAD

**Issue by dj21d** [thedevdojo/voyager#3049]
- Laravel Version: 5.5.24
- Voyager Version: v1.0.9
- PHP Version: 7.1.11
- Database Driver & Version: Postgres 10.1

### Description:
This is most likely user error but I'm having issues with setting up a default value for numbers.
I have a default value setup in the DB but if I leave the field blank when creating a team in the bread it is still not using the default value.

Here is my column from my migration
```
$table->decimal('technical_score', 10, 0)->nullable()->default(0);
```

I have also tried added the following to my bread with no luck:
```
{
    "null": ""
}
```

Does anyone have experience with this?

Ideally when a new entry is created and no technical score is inputted the value will default to 0

**Comment by fletch3555** [comment]
This issue isn't specific to Voyager.

Try this: https://stackoverflow.com/questions/37662955/laravel-migration-default-value/37663054
