### ISSUE TITLE
'role_id' send me only default value from form input

### ISSUE THREAD

**Issue by Philword** [thedevdojo/voyager#3050]
- Laravel Version: 5.5
- Voyager Version: latest
- PHP Version: 7.1.16
- Database Driver & Version: MySQL

### Description:
My users can create other users and when I send request to create new user I have issue with "role_id". 
My input send value="8", but it returns voyager default value="2" (user). 

My code: 

method:

```
 $user = User::create([
            'role_id' => request('role_id'),
            'first_name' => request('first_name'),
            'last_name' => request('last_name'),
            'email' =>request('email'),
            'phone' =>request('phone'),
            'skype' => request('skype'),
            'password' => $password
        ]);

```
form: 

```
<form>
     ..... 
     <input type="hidden" name="role_id" id="role_id" value="8">
      <button type="submit">Submit</button>
</form>
```

So method create the user, but only with 'role_id' => '2', but I need 'role_id' => '8'

Any tips.

**Comment by MrCrayon** [comment]
Set in config/voyager.php
```php
    'user' => [
        'add_default_role_on_register' => false,
```

**Comment by marktopper** [comment]
This should not be affecting [here](https://github.com/the-control-group/voyager/blob/1.1/src/VoyagerServiceProvider.php#L86).

**Comment by MrCrayon** [comment]
Yes, that probably means that role_id is not being set in the first place.

I can confirm the problem:
```
Psy Shell v0.9.3 (PHP 7.1.16 — cli) by Justin Hileman
>>> use app\User
>>> User::create(['role_id' => 1, 'name' => 'name', 'email' => 'email@email.com', 'password' => 'password']);
=> App\User {#2633
     name: "name",
     email: "email@email.com",
     updated_at: "2018-04-24 07:57:43",
     created_at: "2018-04-24 07:57:43",
     id: 8,
   }
>>> User::find(8)->role_id
=> 2
```

**Comment by MrCrayon** [comment]
Just to exclude completely created event, with add_default_role_on_register set as false role_id is saved NULL.

**Comment by MrCrayon** [comment]
Need to add in User model:
```php
    protected $fillable = [
        'name', 'email', 'password', 'role_id',
    ];
```
That solves it for me.

@Philword let us know if that works

**Comment by marktopper** [comment]
Makes sense @MrCrayon. I think we should add this to the model in the core.

**Comment by MrCrayon** [comment]
idk I might be wrong but if we set $fillable in TCG\Voyager\Models\User it will be always overridden by the property set from app\User, that I think it comes from standard laravel installation.
So we would need to add role_id instead but it becomes a bit tricky, I'm not sure if it's a common thing to do.

**Comment by marktopper** [comment]
You are right @MrCrayon, my bad.

**Comment by Philword** [comment]
@MrCrayon Thanks man! That really helped me!
