### ISSUE TITLE
how can i use voyager with existing database with table users that have different fields

### ISSUE THREAD

**Issue by betysam55** [thedevdojo/voyager#3053]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by fletch3555** [comment]
All version information is required. Please don't put the full description in the title field. Also, please provide steps to reproduce your issue. This could be as simple as the steps you took leading up to the issue you've encountered. It's also helpful to include screenshots of the issue and any error message or stacktrace that may have appeared.

Additionally, "how to" style questions, are best asked on our Slack group.  We prefer to reserve github issues for feature requests and actual issues with the package.

This will be reopened when you've provided the necessary information.
