### ISSUE TITLE
User hierarchy

### ISSUE THREAD

**Issue by pjeutr** [thedevdojo/voyager#3054]
I'm in need for some kind of user hierarchy

Since the whole role system was turned upside down. I was wondering are there any plans / thoughts of implementing this?

Right now I'm thinking of going easy. By adding a team_id to user (only need one level for now) Or parent_id, so I get a real hierarchy.
Any thoughts or experience of doing this in scope? Right now I'm using https://github.com/HipsterJazzbo/Landlord to give an user their personal content.

**Comment by fletch3555** [comment]
All version information is required. Please follow the [issue template](https://github.com/the-control-group/voyager/blob/1.1/ISSUE_TEMPLATE).

Additionally, "how to" style questions, are best asked on our Slack group. We prefer to reserve github issues for feature requests and actual issues with the package.

This will be reopened when you've provided the necessary information.
