### ISSUE TITLE
I'm using voyager admin package on laravel 5.6 and it's quite a great experience however I'm unable to effect any changes using the config/voyager.php file. Any help would be appreciated.

### ISSUE THREAD

**Issue by francijo-2** [thedevdojo/voyager#3055]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by marktopper** [comment]
Please add the required information and leave the title for a short description and let the rest of the details go to the `description` section of your message.

**Comment by fletch3555** [comment]
All version information is required. Please don't put the full description in the title field.  Also, please provide steps to reproduce your issue.  This could be as simple as the steps you took leading up to the issue you've encountered.  It's also helpful to include screenshots of the issue And any error message or stacktrace that may have appeared.

This will be reopened when you've provided the necessary information.
