### ISSUE TITLE
Allow null values for Belongs To relationship

### ISSUE THREAD

**Issue by sitnikovalex** [thedevdojo/voyager#3056]
- Laravel Version: 5.5.40
- Voyager Version: 1.0.17
- PHP Version: 7.2
- Database Driver & Version: MYSQL 5.7

### Description:
I can not set the null value for the field.

![](http://joxi.ru/p27vRLLC0ye3km.jpg)

On edit page:
![](http://joxi.ru/GrqxYeetNXgNWA.jpg)

**Comment by tjmckenzie** [comment]
I came across this, too. I have a pending PR
https://github.com/the-control-group/voyager/pull/3170

**Comment by sitnikovalex** [comment]
@tjmckenzie thx for solution!

**Comment by emptynick** [comment]
Fixed in #3170
