### ISSUE TITLE
Directives of the config/voyager.php file not working

### ISSUE THREAD

**Issue by francijo-2** [thedevdojo/voyager#3057]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.0
- PHP Version: 7.0.29
- Database Driver & Version:

### Description:
Hi I'm trying to modify the directives in the config/voyager.php but I find that the changes I make do not reflect on the admin page. For instance, I removed the 'migrations and data_rows' as shown in the image below this should've resulted in these tables appearing on the admin panel, however that's not the case
![screen shot 2018-04-24 at 6 41 53 pm](https://user-images.githubusercontent.com/37329274/39190395-24acaa88-47f2-11e8-883f-4d3b24eb5f0f.png)
![screen shot 2018-04-24 at 6 42 38 pm](https://user-images.githubusercontent.com/37329274/39190397-24ec5b06-47f2-11e8-9416-171b82a14155.png)

**Comment by fletch3555** [comment]
My first question would be "why".. shouldn't be any reason to show those tables in Voyager.

In either case, back to your question.  Are your views or config cached? Try running the various `clear` artisan commands.  Also, make sure you're editing the right file (not the one under `vendor`)

**Comment by francijo-2** [comment]
Many thanks for that, it has worked. Like you said I was modifying the voyager.php in the **vendor folder**. In any case I'm a novice and was just trying to familiarize

**Comment by fletch3555** [comment]
No problem. Just remember you should never have to modify anything under vendor

**Comment by francijo-2** [comment]
Thanks again
