### ISSUE TITLE
Saving settings without uploading an image 

### ISSUE THREAD

**Issue by jannejava** [thedevdojo/voyager#3059]
- Laravel Version: 5.6.17
- Voyager Version: 1.1
- PHP Version:7.2
- Database Driver & Version:MySQL

### Description:

I think a may have found a bug in the last release.

Settings of type image in /admin/settings get a NULL-value if no image is uploaded but other values are updated.

Since there is no upload the field for eg site_logo never get posted, and since it's not existing in the request it gets emptied somehow.

Regards,

Jan

### Steps To Reproduce:
1. Upload a site.logo under /admin/settings
2. Click submit
3. When page reloaded, click submit again
4. Uploaded site.logo value has disappeared.

**Comment by bryanezavala** [comment]
**Still does not solve this error?**

**Comment by emptynick** [comment]
This PR is not merged yet, but does certainly fix the problem.

**Comment by jheckizon** [comment]
Same issue with BREAD

When saving the data, the file was always removed if there is no attached to the file upload field.

## Before updating

![save-1](https://user-images.githubusercontent.com/8746166/40155955-1a97f46a-59c9-11e8-9b54-b9a298f1a579.JPG)
![save-2](https://user-images.githubusercontent.com/8746166/40155957-1acacc8c-59c9-11e8-94bb-d5ec9f9dd82f.JPG)

## After updating

![after-update-1](https://user-images.githubusercontent.com/8746166/40155958-1af60e1a-59c9-11e8-818c-9fb54aed586a.JPG)
![after-update-2](https://user-images.githubusercontent.com/8746166/40155959-1b258a5a-59c9-11e8-8704-c752f2aa0aac.JPG)

**Comment by fletch3555** [comment]
Closed in #3060

**Comment by pladgepeople** [comment]
Still does not solve this error?

**Comment by fletch3555** [comment]
If you have issues, please open a new issue or ask in our Slack channel
