### ISSUE TITLE
Permission does not exist

### ISSUE THREAD

**Issue by webspilka** [thedevdojo/voyager#3064]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.0
- PHP Version: 7.1.10
- Database Driver & Version: MySQL 5.7.19-0ubuntu0.16.04.1

### Description:
"**Permission does not exist**"
for all breads:
.../admin/bread/pages/edit
.../admin/bread/menus/edit
...
and some pages:
.../admin/hooks

Tell me please what could have changed in rights Permission or policies?
How can I reset all rights?

### Steps To Reproduce:
after update 
- Voyager from 1.0.7 to 1.1.0
- Laravel from 5.5.21 to 5.5.40

**Comment by emptynick** [comment]
Did you follow the upgrade guide?
Especially the part [BREAD](https://voyager.readme.io/docs/10-to-11#section-bread) ?

**Comment by webspilka** [comment]
Thank you @emptynick 
I really did not understand and missed this item when upgrading.
Now I made changes for BREAD and it fixed problem with it.

Сan tell me what can be the problem with .../admin/hooks ?

**Comment by fletch3555** [comment]
Hooks are provided by another repository, larapack/voyager-hooks.

**Comment by naonak** [comment]
With fresh install of 1.1 I got the same issue.
