### ISSUE TITLE
Ajax Pagination of large number of datas

### ISSUE THREAD

**Issue by marjenitish** [thedevdojo/voyager#3066]
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.0

Hello, I have a table with 7500 rows. It's taking way too much time for browsing the data. The page loads in about 50 seconds. Ajax pagination is really needed for this scenarios. How can I implement AJAX loading pagination in this version of Voyager?

**Comment by Fighix** [comment]
laravel already lets you paginate ressources maybe look into that.

Not sure what/where that table loading you speak of happens hard to be more specific

**Comment by emptynick** [comment]
Alternatively you can just switch on `Server-side pagination` in BREAD-Settings.
Thats what its made for.

**Comment by marjenitish** [comment]
Yes, I was looking for a solution like Server-Side pagination. I am new in this, thanks man.. cheers!!

**Comment by MrCrayon** [comment]
Also check this #2861 and #2862, I'm currently displaying 2K records with no problems.
 
@emptynick should I repropose #2862 for 1.1?
readmore is still there

**Comment by mohamm6d** [comment]
> Alternatively you can just switch on `Server-side pagination` in BREAD-Settings.
> Thats what its made for.

Awesome I was looking for this for a long time
