### ISSUE TITLE
In DataType.php line 186:   syntax error, unexpected '?'  

### ISSUE THREAD

**Issue by joanandreu** [thedevdojo/voyager#3067]
- Laravel Version: v5.4.30
- Voyager Version: 1.1
- PHP Version: 5.6.30
- Database Driver & Version: 5.5.58-cll - MySQL Community Server (GPL)

### Description:
On new install  appear  _DataType.php line 186:   syntax error, unexpected '?'_  
before     _php artisan voyager:install_

### Steps To Reproduce:

install laravel :
composer create-project laravel/laravel laravel
______
in project name:
composer require tcg/voyager
_____
add the Voyager Service Provider 
------
 Update the "config/database.php" for 'mysql'
'engine' => null,
with
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',

-----
Update the "app/Providers/AppServiceProvider.php" with
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Specified key was too long error, Laravel News post:
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

php artisan voyager:install 

and crash

**Comment by fletch3555** [comment]
Looks like you forgot the rest of your issue.

**Comment by cyrildewit** [comment]
I think that your PHP version doesn't  support the new `??` feature.

I've tested it with: http://sandbox.onlinephpfunctions.com/

Release notes: http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op

**Comment by fletch3555** [comment]
Correct, the Null-Coalesce operator (`??`) was added in PHP 7.0, and is [used in that model](https://github.com/the-control-group/voyager/blob/1.1/src/Models/DataType.php#L186).  We either need to change the minimum PHP version, or not use that operator.

**Comment by cyrildewit** [comment]
Introduced here: https://github.com/the-control-group/voyager/commit/fb80eea2df1fcde9ffc3dba2a7347d52cf2305c6

**Comment by fletch3555** [comment]
Yup, I knew what it was as soon as I saw the line it was on...

**Comment by cyrildewit** [comment]
I think this will fix it:

```php
'taggable'    => isset($requestData['relationship_taggable_'.$relationship]) ? $requestData['relationship_taggable_'.$relationship] : '0',
```

Are you going to fix it? Or should I do it?

**Comment by fletch3555** [comment]
Yes it would.  Kludgy, but it'll fix it.  Feel free since you already have it, @cyrildewit
