### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'databasename.data_types' doesn't exist (SQL: select * from `data_types` where (`slug` = users) limit 1)

### ISSUE THREAD

**Issue by hiren004** [thedevdojo/voyager#3069]
- Laravel Version: 5.5
- Voyager Version: ^1.1
- PHP Version:7.2
- Database Driver & Version:MYSQL

### Description:

I've installed voyager using `composer require tcg/voyager` and then change `APP_URL` to my virtualhost. 
Then i use `php artisan voyager:install` command to install voyager and this command gives me error like:

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'databasename.data_types' doesn't exist (SQL: select * from `data_types` where (`slug` = users) limit 1) 

I don't understand why this occurs?? Anyone have an ide?? Please help me!
Thanks,

**Comment by cyrildewit** [comment]
What are the exact version numbers?

`composer show -i`

**Comment by hiren004** [comment]
I got this:

> tcg/voyager                           v1.1.0  A Laravel Admin Package for The Control Group to make your life easier and steer your project in the right direction

**Comment by cyrildewit** [comment]
And Laravel?

**Comment by hiren004** [comment]
Laravel v 5.5

**Comment by cyrildewit** [comment]
There are more versions of 5.5. `v5.5.28` is the latest for example

**Comment by hiren004** [comment]
laravel v 5.5.40

**Comment by cyrildewit** [comment]
Thanks

Edit: how is that possible? 5.5.4 doesn't exists?

**Comment by hiren004** [comment]
I don't understand why this error occurs! As i just installed voyager using composer command and then install it using php artisan voyager:install command. Have you any idea?

**Comment by cyrildewit** [comment]
Did you have installed Voyager on a fresh Laravel installation?

If not, what are your settings for database in Laravel?

**Comment by hiren004** [comment]
Yes! I've only created apis for iOS app and then i want to make admin panel for the client! So i choose voyager and i got this! :)

**Comment by emptynick** [comment]
Looks like its skips the migrations and/or seeds.
Are there any entries in your `migrations` table?

**Comment by hiren004** [comment]
Yes, there's migrations for data_types table also! But i think it not migrate when i run that command!

**Comment by angelom22** [comment]
I am presented the same problem, apparently the application is looking for the name of the table in the plural and for the same reason can not find it. any solution?

**Comment by emptynick** [comment]
https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions

**Comment by Akari1987** [comment]
I had same issue. But solved it. In my case, I install voyager on alerady existing laravel app.
Before php artisan migrate, edit config/voyager.php database configuration from 'autoload_migration' => true to false. 
And execute php artisan migrate, then migrated except voyager migration files.
And restore config/voyager.php to original setting. 
database configuration from 'autoload_migration' => false to true.
And php artisan migrate, then migrated voyager migrations.
Sorry my wrong english.
