### ISSUE TITLE
[Question] Why load the default authentication scaffolding?

### ISSUE THREAD

**Issue by allenjd3** [thedevdojo/voyager#307]
### Question-

Is there an underlying reason why voyager loads the default authentication scaffolding when it is installing? I did a test and removed the following lines from tcg/voyager/Commands/InstallCommand.php

```
         if (!$this->option('existing')) {
             $this->info('Generating the default authentication scaffolding');
             Artisan::call('make:auth');
         }
```
Everything installed fine and runs correctly. Does voyager really need make:auth? It creates two locations to log in from which could be confusing if you aren't familiar with the program.

**Comment by tnylea** [comment]
Actually, this is not going to be included in the latest version 0.10, which should be released here within the next couple days I'm assuming 👍
