### ISSUE TITLE
Multilevel menu not display child items

### ISSUE THREAD

**Issue by hungxinh** [thedevdojo/voyager#3072]
- Laravel Version: 5.5 -> 5.6
- Voyager Version: 1.0.17 -> 1.1.0
- PHP Version: 7.1.14
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:
Collections menu not display child items when click on it.
![screenshot 2018-04-27 13 53 15](https://user-images.githubusercontent.com/23396671/39348825-e08ca1fe-4a22-11e8-8130-0a1192cd9c04.png)

**Comment by fletch3555** [comment]
Voyager's built in menu only supports displaying one level of nesting.  The menu builder let's you add more since you're free to style menus however you'd like
