### ISSUE TITLE
Alternative way to create a custom Voyager controller

### ISSUE THREAD

**Issue by xaviqv** [thedevdojo/voyager#3078]
- Laravel Version: 5.4
- Voyager Version: 1.*

In my environment I customized the Voyager controllers I needed by doing this:

1. Creating a controller in App\Http\Controllers\Voyager with custom_name
2. This custom controller has to extend Voyager http\Controllers\VoyagerBaseController.php (In Voyager 1.0 it was VoyagerBreadController.php)
2. Specify Controller custom_name in Voyager related BREAD

Additionally, I have created a custom intermediate custom controller in my App\http\Controllers\Voyager folder to hold all common code for my BREADs.

This way of configuration is not specified in the docs at https://voyager.readme.io/docs/using-custom-http-controllers but I'm working successfully with it. May it not be recommendable in general or is it worth to include in the docs?

If it has been used by others, I guess it should be also included in the [1.0 to 1.1 upgrade doc](https://voyager.readme.io/docs/10-to-11).

**Comment by fletch3555** [comment]
It's a special case, so it definitely doesn't need to be included in the upgrade guide.  I won't say it's not recommended, but I wouldn't recommend it to everyone.

To me, controllers should be limited to a "wiring" or "routing" role.  They should accept the request, handle any necessary validation or whatever, pass off business logic to service or repository classes, then return the appropriate view.  Controllers should never need to call "common" methods within itself.  For these reasons, I doubt anyone truly NEEDS another "intermediate" controller.

Obviously there are different schools of thought on this topic, so I don't expect everyone to agree.  You're free to build your app as you see fit.  I don't believe this topic necessitates documentation.  Perhaps someone that has done it will write a blog post about it, which can serve as a guide for those who need it.  Adding it to our documentation would indicate that we suggest doing so in certain cases, which I don't.

Thank you for the suggestion though.  We're always open to suggestions from the community!
