### ISSUE TITLE
delete bread does not work

### ISSUE THREAD

**Issue by beausaertm** [thedevdojo/voyager#3079]
- Laravel Version: 5.6.18
- Voyager Version: latest download
- PHP Version: 7.2.1
- Database Driver & Version:

### Description:
Whenever I create a table and  a bread for the table, the button 'delete bread' does nothing.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3038
Until its tag-released, please use `Delete` from the BREAD-page.

**Comment by beausaertm** [comment]
I can't . It won't let me . i get the message : "Please make sure to remove the BREAD on this table before deleting the table." But I can't remove the bread

**Comment by emptynick** [comment]
Thats why I said
`...please use Delete from the BREAD-page.`
**Not** from the database page

**Comment by benjordan** [comment]
I am having the same issue. I may be dense, but what do you mean by using Delete from the BREAD-page?

**Comment by emptynick** [comment]
![bread](https://user-images.githubusercontent.com/2482942/39368440-dd63dbca-4a39-11e8-8d64-812a3eb1f547.png)

**Comment by benjordan** [comment]
I don't have that as an option in my sidebar. What am I missing?
![screen shot 2018-04-27 at 9 42 46 am](https://user-images.githubusercontent.com/508288/39368656-c2fb2eb2-49ff-11e8-86dd-eea92f45c231.png)

**Comment by fletch3555** [comment]
You're missing the `browse_bread` permission.  If it's not available in your `edit role` page, then you missed a step with the upgrade and need to add it manually

**Comment by benjordan** [comment]
Ok. Thanks. Just starting out on Voyager with a fresh install this morning.

**Comment by enricopalazzo** [comment]
Same issue here. 
No link to BREAD page, no `browse_bread ` option on the `edit role `pages. Just installed Laravel and Voyager about 10 minutes ago. 

Laravel Version: 5.6.18
Voyager Version: 1.1.0
PHP Version: 7.1.7

What upgrade step did I miss?

**Comment by beausaertm** [comment]
you can reach the bread page by directly changing the url to : http://yourdomain/admin/bread
