### ISSUE TITLE
DE Translation missing voyager::bread.updated_order

### ISSUE THREAD

**Issue by f0reclone** [thedevdojo/voyager#3086]
- Laravel Version: 5.6.18
- Voyager Version: current 1.1 dev
The following Translation is missing:
\tcg\voyager\publishable\lang\de\bread.php
`'updated_order'          => 'Reihenfolge geändert',`

**Comment by fletch3555** [comment]
This is much better suited as a pull request.  Are you comfortable creating it, or would you rather one of us did it?
