### ISSUE TITLE
'Permission does not exist', 400

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#3088]
- Laravel Version:  5.6.18
- Voyager Version: 1.1.0
- PHP Version:7.1.10
- Database Driver & Version:MySQL 5.7.19

### Description:
I can only brows the default BREAD but cant not edit
I can not Add or Edit the BREAD  for any taable

```
/** @deprecated */
    public function can($permission)
    {
        $this->loadPermissions();
 
        // Check if permission exist
        $exist = $this->permissions->where('key', $permission)->first();
 
        // Permission not found
        if (!$exist) {
            throw new \Exception('Permission does not exist', 400);
        }
 
        $user = $this->getUser();
        if ($user == null || !$user->hasPermission($permission)) {
            return false;
        }
 
        return true;
    }
 
    /** @deprecated */
    public function canOrFail($permission)
```

   "Permission does not exist"

**Comment by fletch3555** [comment]
You'll need to provide more information for us to support you.

What I can say for certain is that you're missing a permission.  I can't tell you what permission or what you have to do to fix it without more information.  This issue can be reopened when you provide the missing info

**Comment by Guerzizeb** [comment]
Same issue here, i have installed voyage without dummy data, when i connect as admin to voyage and i click bread sub-menu under tools menu i get this error

**Comment by kayrules** [comment]
Debug from line 224 (`Voyager.php`), shows it looking for `browse_bread` permission which is not exist in the database. 

```
public function can($permission)
{
    $this->loadPermissions();
    debug($permission); // <-- line 224: browse_bread
    // Check if permission exist
    $exist = $this->permissions->where('key', $permission)->first();

    // Permission not found
    if (!$exist) {
        throw new \Exception('Permission does not exist', 400);
    }

    $user = $this->getUser();
    if ($user == null || !$user->hasPermission($permission)) {
        return false;
    }

    return true;
}
```

* Version: v1.1.1
* Installed voyager without dummy data, and created admin using `--create` flag

**Comment by emptynick** [comment]
Its [here](https://github.com/the-control-group/voyager/blob/1.1/publishable/database/seeds/PermissionsTableSeeder.php#L15)
Seeded from [here](https://github.com/the-control-group/voyager/blob/1.1/publishable/database/seeds/VoyagerDatabaseSeeder.php#L24)
Called from install-command [here](https://github.com/the-control-group/voyager/blob/1.1/src/Commands/InstallCommand.php#L116)
Granted to admins created by `voyager:admin` [here](https://github.com/the-control-group/voyager/blob/1.1/src/Commands/AdminCommand.php#L62-L70)

Also you wont get the `BREAD` menu-item if you dont have permission to `browse_bread`.

**Comment by kayrules** [comment]
Ok got it. I was run composer update previously, and it updates Voyager from version `v1.0.11` to `v1.1.1` without changing the `PermissionsTableSeeder.php`. Fresh install correctly replacing the file and the permission is there.

Thanks.

**Comment by emptynick** [comment]
Yep, it's mentioned in the upgrade guide that you need to manually add `browse_bread` (or do it your way)

**Comment by PointfullDevelopers** [comment]
I got the same, please help. It deleted all of my backoffice

**Comment by fletch3555** [comment]
I sincerely doubt "it" didn't "delete your backoffice".

In either case, this issue has been closed for over a month.  Please open your own or ask on our slack
