### ISSUE TITLE
Voyager sets some fields to null after uploading a profile photo

### ISSUE THREAD

**Issue by andriihorpenko** [thedevdojo/voyager#3090]
- Laravel Version: latest
- Voyager Version: latest
- PHP Version: 7.2
- Database Driver & Version: Mysql 5.7

### Description:
After uploading an image within admin profile page Voyager is trying to set role_id and my own 'lang' field to NULL. After that everything crashes, because Voyager is unable to get 'NULL' role. Fix it please.

### Steps To Reproduce:
Upload any photo and notice this bug.

**Comment by mihaiconstantin** [comment]
I can confirm this potential bug on a fresh install. After you change the avatar image of an user (i.e., with `admin` role in my case) the `role_id` of that user gets set to `NULL`. This is where the error occurs:

![Null role id error](https://i.imgur.com/QUAOrDJ.png)

This appears to be quite problematic. Any help is appreciated.

These are my installation details:
- Laravel Version: 5.6.19
- Voyager Version: 1.1.0
- PHP Version: 7.2.3
- Database Driver & Version: 10.2.13-MariaDB

**Comment by Siarhei-Sudakou** [comment]
Confirm this bug on a fresh install.

**Comment by RoachMech** [comment]
This is a known issue. 2 PRs have been submitted to fix this issue: #3016 #3020 

It has been reported a several times before: #3028 #3010 #3018. Please review other issues before posting new issues.

**Comment by emptynick** [comment]
#3028 is the oldest open issue about this topic.
As this bug is not finally solved, #3028 will stay open.
