### ISSUE TITLE
image src is incorrect

### ISSUE THREAD

**Issue by mohsennaserikish** [thedevdojo/voyager#3092]
- Laravel Version: 5.5.
- Voyager Version: 1.1
- PHP Version:7
- Database Driver & Version: mysql

### Description: hi Dear,
sorry for my bad english, 
I use voyager on localhost(xampp server),
but i have a problem: image url is incorrect and does not show on page.
for example it is my project url : http://localhost:1168/dr_sol/public/ and in config/voyager.php : 'storage' => [
        'disk' => 'public',
    ],
but when page is loaded i see this address for image src : http://localhost/storage/users/April2018/cvwmHaXgq3mdN74WShAD.jpg

it should be something like this : http://localhost:1168/dr_sol/public/storage/users/April2018/cvwmHaXgq3mdN74WShAD.jpg

so how can i edit this path url ?
many thanks.

**Comment by emptynick** [comment]
The first link is absolutely correct, it should **not** contain `/public`.
Also please set your `APP_URL` as described in our readme.
Additionally, also make sure you followed to [Laravel installation guide](https://laravel.com/docs/5.5/installation#configuration).

**Comment by fletch3555** [comment]
As @emptynick mentioned, you should create a vhost in your webserver (xampp's apache config in your case) that points at your app's `public` folder.  This is best practice, and will resolve your problem.

In the case that you can't do that for whatever reason, you'll need to figure out how to do it.  Voyager works perfectly fine with the "best practice" installation, so it's not a bug with Voyager.  You will need to set your APP_URL to include the port number (1168) at the bare minimum, and may need to change the filesystem configuration as well.  Unfortunately, that's as far as we can go on here.  If you need more help, you're welcome to join our Slack and ask, or better yet, ask in a more general Laravel support forum, like the LaraChat slack group.

**Comment by mohsennaserikish** [comment]
Many Thanx. it works perfectly
