### ISSUE TITLE
No query results for model [TCG\Voyager\Models\DataType].

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#3093]
- Laravel Version: 5.5.* (5.6 samething)
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: MySql 5

### Description:
Trying to install voyager on a fresh installation of laravel 5.5 or 5.6 and getting that error.

### Steps To Reproduce: 
php artisan voyager:install --with-dummy

**Comment by emptynick** [comment]
Can you post the whole output of your CLI?

**Comment by donmbelembe** [comment]
on a it worked itself after deleting all tables on the db

**Comment by emptynick** [comment]
So not a fresh install?!

**Comment by donmbelembe** [comment]
of course it was a fresh installation of laravel

**Comment by donmbelembe** [comment]
I'm still getting that error after enabling multilaguage.
inside config/voyager.php i've enabled multi language and run the migration:fresh seed command and again i'm getting the same error.


$ php artisan migrate:fresh --seed
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2016_01_01_000000_add_voyager_user_fields
Migrated:  2016_01_01_000000_add_voyager_user_fields
Migrating: 2016_01_01_000000_create_data_types_table
Migrated:  2016_01_01_000000_create_data_types_table
Migrating: 2016_01_01_000000_create_pages_table
Migrated:  2016_01_01_000000_create_pages_table
Migrating: 2016_01_01_000000_create_posts_table
Migrated:  2016_01_01_000000_create_posts_table
Migrating: 2016_02_15_204651_create_categories_table
Migrated:  2016_02_15_204651_create_categories_table
Migrating: 2016_05_19_173453_create_menu_table
Migrated:  2016_05_19_173453_create_menu_table
Migrating: 2016_10_21_190000_create_roles_table
Migrated:  2016_10_21_190000_create_roles_table
Migrating: 2016_10_21_190000_create_settings_table
Migrated:  2016_10_21_190000_create_settings_table
Migrating: 2016_11_30_135954_create_permission_table
Migrated:  2016_11_30_135954_create_permission_table
Migrating: 2016_11_30_141208_create_permission_role_table
Migrated:  2016_11_30_141208_create_permission_role_table
Migrating: 2016_12_26_201236_data_types__add__server_side
Migrated:  2016_12_26_201236_data_types__add__server_side
Migrating: 2017_01_13_000000_add_route_to_menu_items_table
Migrated:  2017_01_13_000000_add_route_to_menu_items_table
Migrating: 2017_01_14_005015_create_translations_table
Migrated:  2017_01_14_005015_create_translations_table
Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrated:  2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrating: 2017_03_06_000000_add_controller_to_data_types_table
Migrated:  2017_03_06_000000_add_controller_to_data_types_table
Migrating: 2017_04_11_000000_alter_post_nullable_fields_table
Migrated:  2017_04_11_000000_alter_post_nullable_fields_table
Migrating: 2017_04_21_000000_add_order_to_data_rows_table
Migrated:  2017_04_21_000000_add_order_to_data_rows_table
Migrating: 2017_07_05_210000_add_policyname_to_data_types_table
Migrated:  2017_07_05_210000_add_policyname_to_data_types_table
Migrating: 2017_08_05_000000_add_group_to_settings_table
Migrated:  2017_08_05_000000_add_group_to_settings_table
Migrating: 2017_11_26_013050_add_user_role_relationship
Migrated:  2017_11_26_013050_add_user_role_relationship
Migrating: 2017_11_26_015000_create_user_roles_table
Migrated:  2017_11_26_015000_create_user_roles_table
Migrating: 2018_03_11_000000_add_user_settings
Migrated:  2018_03_11_000000_add_user_settings
Migrating: 2018_03_14_000000_add_details_to_data_types_table
Migrated:  2018_03_14_000000_add_details_to_data_types_table
Migrating: 2018_03_16_000000_make_settings_value_nullable
Migrated:  2018_03_16_000000_make_settings_value_nullable
Seeding: VoyagerDatabaseSeeder
Seeding: VoyagerDummyDatabaseSeeder

   Illuminate\Database\Eloquent\ModelNotFoundException  : No query results for model [TCG\Voyager\Models\DataType].

  at C:\wamp64\www\projects\preteacheter\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:416
    412|         if (! is_null($model = $this->first($columns))) {
    413|             return $model;
    414|         }
    415|
  > 416|         throw (new ModelNotFoundException)->setModel(get_class($this->model));
    417|     }
    418|
    419|     /**
    420|      * Execute the query and get the first result or call a callback.

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::firstOrFail()
      C:\wamp64\www\projects\preteacheter\database\seeds\TranslationsTableSeeder.php:57

  2   TranslationsTableSeeder::dataTypesTranslations()
      C:\wamp64\www\projects\preteacheter\database\seeds\TranslationsTableSeeder.php:19

  Please use the argument -v to see more details.

**Comment by emptynick** [comment]
`php artisan migrate:fresh --seed` is not a good idea to run at all.
It will create empty tables and then just seed all seeders it finds in order of appearance.

Despite that:
```
$dtp = DataType::where($_fld, 'Post')->firstOrFail();
if ($dtp->exists) {
 ...
}
```
Is pretty senseless. [ref](https://github.com/the-control-group/voyager/blob/1.1/publishable/database/seeds/TranslationsTableSeeder.php#L57-L60)

**Comment by donmbelembe** [comment]
i'm always using seeding to all of my project, and all of my project i'm using voyager since laravel 5.3 
this problem just came on the last update of voyager

**Comment by donmbelembe** [comment]
so in the version 1.1.0 of voyager here is the dataTypesTableSeeder.php



<?php

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataType;

class DataTypesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        $dataType = $this->dataType('slug', 'users');
        if (!$dataType->exists) {
            $dataType->fill([
                'name'                  => 'users',
                'display_name_singular' => __('voyager::seeders.data_types.user.singular'),
                'display_name_plural'   => __('voyager::seeders.data_types.user.plural'),
                'icon'                  => 'voyager-person',
                'model_name'            => 'TCG\\Voyager\\Models\\User',
                'policy_name'           => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller'            => '',
                'generate_permissions'  => 1,
                'description'           => '',
            ])->save();
        }
....

It uses translations and have a look on my database data types table
![voyager](https://user-images.githubusercontent.com/10473277/39569557-761a498a-4ebd-11e8-80c9-86f93717ff93.PNG)

so in the database, it stores the translation key instead of the translated string and in the TranslationsTableSeeder it's trying to retrieve datatypes in other to translate it but it's not finding any corresponding datatypes

  */
    private function dataTypesTranslations()
    {
        // Adding translations for 'display_name_singular'
        //
        $_fld = 'display_name_singular';
        $_tpl = ['data_types', $_fld];
        $dtp = DataType::where($_fld, 'Post')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Poste');
        }
        $dtp = DataType::where($_fld, 'Page')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Page');
        }
        $dtp = DataType::where($_fld, 'User')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Utilisateur');
        }
        $dtp = DataType::where($_fld, 'Category')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'categorie');
        }
        $dtp = DataType::where($_fld, 'Menu')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Menu');
        }
        $dtp = DataType::where($_fld, 'Role')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Role');
        }

        // Adding translations for 'display_name_plural'
        //
        $_fld = 'display_name_plural';
        $_tpl = ['data_types', $_fld];
        $dtp = DataType::where($_fld, 'Posts')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Postes');
        }
        $dtp = DataType::where($_fld, 'Pages')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Pages');
        }
        $dtp = DataType::where($_fld, 'Users')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Utilisateurs');
        }
        $dtp = DataType::where($_fld, 'Categories')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Categories');
        }
        $dtp = DataType::where($_fld, 'Menus')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Menus');
        }
        $dtp = DataType::where($_fld, 'Roles')->firstOrFail();
        if ($dtp->exists) {
            $this->trans('fr', $this->arr($_tpl, $dtp->id), 'Roles');
        }
    }

**Comment by emptynick** [comment]
Because the Dummy-data were separated from the normal seeds.
Run `php artisan vendor:publish --provider=TCG\Voyager\VoyagerDummyServiceProvider`
and you should be good to go.

But again: `php artisan migrate:fresh --seed` is still not a good idea

**Comment by donmbelembe** [comment]
I'll make you get my problem. I've detected the problem and it's a little bit difficult for me to explain. please follow this step.

1. Install fresh laravel
2. Install voyager with dummy data or not
3. Go to database\seeds\DatabaseSeeder.php and add those two lines : 
$this->call(VoyagerDatabaseSeeder::class);
$this->call(VoyagerDummyDatabaseSeeder::class);
4. now run `php artisan migrate:fresh --seed` (This is how I use to work because i'm always using seeding)
5. now change the `'locale' => 'en',` and `'fallback_locale' => 'en',` to french for example
6. now run again `php artisan migrate:fresh --seed` 
7. You will get that error because : 
- in the moment of seeding the DataTypesTableSeeder.php
- the new version of voyager is using translation and not only string like this
`'display_name_singular' => __('voyager::seeders.data_types.user.singular'),`
`'display_name_plural'   => __('voyager::seeders.data_types.user.plural'),`
- now that there is no a translation that match that translation key, the key itself is stored in the database
- so the TranslationsTableSeeder.php is trying to find a string on the datatype table to translate it. as there is no that string we are getting that error.

### There is two problems that are linked together
- In the TranslationsTableSeeder.php instead of finding a string like this: 
$dtp = DataType::where($_fld, 'Post')->firstOrFail();
It must be like this: 
$dtp = DataType::where($_fld, __('voyager::seeders.data_types.post.singular'))->firstOrFail(); 
- To avoid savind the keys in the database when the locale other then english, the language files must be published in the installation and let us the right to add missing translation

**Comment by emptynick** [comment]
> 2. Install voyager with dummy data or not

Thats not unimportant

> 3. Go to database\seeds\DatabaseSeeder.php and add those two lines : ...

Why would you do that?!

> 6. now run again php artisan migrate:fresh --seed

Why again?

> now that there is no a translation that match that translation key, the key itself is stored in the database
so the TranslationsTableSeeder.php is trying to find a string on the datatype table to translate it. as there is no that string we are getting that error.

That is unrelated. Those translation strings are stored in language-files, not in the Database.

> inside my DataTypesTableSeeder.php I found only three datatypes (users, menus, roles) which is not normal

That is normal. Like I said, Dumma-Data was completely separated from "normal" data.
So if this seeder would seed dummy-data, it would fail for everyone not using dummy-data.

Again, please run `php artisan vendor:publish --provider=TCG\Voyager\VoyagerDummyServiceProvider` which will publish all seeders neccessary for dummy-data ( [here](https://github.com/the-control-group/voyager/tree/1.1/publishable/database/dummy_seeds) ).
Alternatively you could just delete `TranslationsTableSeeder.php`

**Comment by donmbelembe** [comment]
Many part of my project uses seeder. in development sometime I can make big change and I would like to just run this command `php artisan migrate:fresh --seed` that why .
It okey i can solve that problem myself

**Comment by donmbelembe** [comment]
Just try to install voyager on a fresh laravel installation where the locale and the fallback_locale is 'fr'. then you will understand what I'm saying @emptynick 
After installing look at you database and see what it stored on tables like menu_items or datatypes ...

**Comment by emptynick** [comment]
Yes, I know what you mean, but thats unrelated to your original issue.
[This file](https://github.com/the-control-group/voyager/blob/1.1/publishable/lang/en/seeders.php) is just not translated to french, and because you set both `locale` and `fallback_locale` to french it will just be empty (I dont need to try that ;) )

**Comment by donmbelembe** [comment]
Ok My original issue is liked with the TranslationsTableSeeder.php
but I found that so many fr translations are missing maybe i should just submit a PR for that

**Comment by emptynick** [comment]
Its always a good idea to keep the fallback-locale as english, so you have at least _something_ not just plain translation keys.
Looks like your original issue is solved, so I will close this one. If not, please let me know.
