### ISSUE TITLE
Method Illuminate\Database\Query\Builder::hasPermission does not exist.

### ISSUE THREAD

**Issue by sigaev-pro** [thedevdojo/voyager#3101]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.2.4

I'm installing Voyager on existing project. Project before has no User model, so I hade use default Laravel User model and placed it in Models folder (of cause in `auth.php` and `voyager.php` files I had specified correct class `App\Models\User::class`).

Then I created admin user with `php artisan voyager:admin admin@mail.com`

It seems to be okey, but when I try to sign in with admin user I have an `BadMethodCallException`

![image](https://user-images.githubusercontent.com/285154/39434678-e5116210-4ca1-11e8-80e6-a7ee602eda2e.png)

**Comment by emptynick** [comment]
Take [a look](https://github.com/the-control-group/voyager/blob/1.1/src/Commands/InstallCommand.php#L85) at what Voyager does with the user-model when installing.
You will need to do the same with your model.

**Comment by sigaev-pro** [comment]
It works, thank you very much! )

**Comment by AlterwebStudio** [comment]
Works for me, thanks a lot emptynick!
