### ISSUE TITLE
Error after upgrading to v 1.1.0

### ISSUE THREAD

**Issue by hzuluaga** [thedevdojo/voyager#3104]
- Laravel Version: 5.5.37
- Voyager Version:1.1.*
- PHP Version: 7.2.2
- Database Driver & Version:

### Description:
After I upgraded to version 1.1.0 , following the instructions published in the website , I get the following error whenever I try to modify users password, or role , or avatar , or name ..

Any help or hint will be appreciated ...

<img width="2008" alt="screen shot 2018-04-30 at 3 29 07 pm" src="https://user-images.githubusercontent.com/5191016/39448812-b2aa66ac-4c8b-11e8-8497-98927cbebe1e.png">
<img width="1985" alt="screen shot 2018-04-30 at 3 28 51 pm" src="https://user-images.githubusercontent.com/5191016/39448813-b2c576f4-4c8b-11e8-89b9-fddd9775876a.png">

**Comment by emptynick** [comment]
This was fixed in #3014.
