### ISSUE TITLE
Image disappears

### ISSUE THREAD

**Issue by bryanezavala** [thedevdojo/voyager#3105]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2
- Database Driver & Version: MariaDB 10.1

### Description:
When uploading an image this is saved but when I click on save again this image is deleted.

![first](https://user-images.githubusercontent.com/33789256/39454263-effe5e00-4c9f-11e8-8b43-aa4f58ea46f5.jpg)
![second](https://user-images.githubusercontent.com/33789256/39454264-f0255776-4c9f-11e8-8aef-f7b09d174b06.jpg)

**Comment by emptynick** [comment]
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3059
