### ISSUE TITLE
Change path for admin 

### ISSUE THREAD

**Issue by iscisse** [thedevdojo/voyager#3106]
- Laravel Version: 5.6.12
- Voyager Version: 1.1
- PHP Version: 7.1.8
- Database Driver & Version: Mysql

### Description:
I want my admin to be at the root so instead of www.site.com/admin I will do www.site.com. I made some changes to the web.php and voyager.php and I have now a blank screen.

### Steps To Reproduce:
I went to "routes/web.php" and chnage  this :

Route::get('/', function () {
   return view('welcome');
});

to:

Route::get('/', function () {
    Voyager::routes();
});

and to "config/voyager.php" and change

'redirect'                     => '/admin',

to:
 'redirect'                     => '/',

**Comment by emptynick** [comment]
```
Route::get('/', function () {
Voyager::routes();
});
```
Wont work. Just change it to
`Voyager::routes();`

**Comment by iscisse** [comment]
I have made the following changes:
```
Route::get('/', function () {
   
    Voyager::routes();
});
```

now it gives me a blank page. What else do I need to change? Thanks...

**Comment by cyrildewit** [comment]
You shouldn't wrap `Voyager::routes()` with `Route::get('/', function () {` and `});`.

Just:

```php
<?php

// ...

Voyager::routes();

// ...
```

**Comment by iscisse** [comment]
Thank you, it works now.
