### ISSUE TITLE
Bad z-index when opening a delete image modal and there are relationships on the page

### ISSUE THREAD

**Issue by kylemilloy** [thedevdojo/voyager#3108]
- Laravel Version: 5.5.x
- Voyager Version: ^1.0
- PHP Version: 7.2

### Description:
z-index is not correct when opening a delete modal and there are relationship (specifically belongstomany relationships) on the page.

<img width="1673" alt="screen shot 2018-05-01 at 12 05 53 am" src="https://user-images.githubusercontent.com/15757117/39463143-7595b51c-4cd3-11e8-96ca-c7e926d0505b.png">

**Comment by kylemilloy** [comment]
Lemme know if you want a PR...should be an easy fix.

**Comment by hungxinh** [comment]
.modal-open .select2-container {
    z-index: 100000!important;
    width: 100%!important;
}

**Comment by emptynick** [comment]
This should be fixed in 1.1. Please upgrade (dont forget to force-publish your assets and clear browser cache) and let us know if this fixed it.

@hungxinh This part was removed in 1.1

**Comment by kylemilloy** [comment]
Looks good. Thanks guys.
