### ISSUE TITLE
Update of required relationships in bread update

### ISSUE THREAD

**Issue by damms005** [thedevdojo/voyager#3113]
- Laravel Version: 5.7
- Voyager Version: 1.1
- PHP Version: 7.2
- Database Driver & Version: 

### Description:
When add/edit model in the bread, relationships only work for the first-level relationship. E.g. `Car` model belongsTo the `Manufacturer`  model, uses `manufacturer_id` column as the key. `User` model now hasMany `Car`, using pivot table `car_users`. On adding/editing a user, `car_users` get appropriately updated with its user_id and car_id, but `manufacturer_id` for the car does not get inserted

**Comment by fletch3555** [comment]
Just so I understand correctly, you have something like this:
```
User <--[car_users]--> Car -[manufacturer_id]--> Manufacturer
```

In that case, how are you assigning the fields to `Car`?  Voyager doesn't have a way to create a `Car` when attaching it to a `User`, so the `Car` has to already exist.  I don't really understand what you expect it to do.

**Comment by damms005** [comment]
Sorry my mistake. Should be `car_user` and not `car_users`

Thanks
