### ISSUE TITLE
Permission does not exist, when trying add/edit BREAD

### ISSUE THREAD

**Issue by ArditMata** [thedevdojo/voyager#3114]
- Laravel Version: 5.5.*
- Voyager Version: 1.1
- PHP Version: 7.0
- Database Driver & Version: 

 Description:
After Fresh installation of Voyager with dummy data, when i try to add a new BREAD or edit any existing BREAD, like categories, pages etc.  i keep getting the error below even though the user is the admin and all the permissions are checked

![screenshot from 2018-05-01 15-11-39](https://user-images.githubusercontent.com/37873503/39474002-106b652c-4d52-11e8-87c1-29def953b76e.png)

Steps To Reproduce:
1. Installation of Voyager
2. Try creating a BREAD for an existing table
3. Got the error above

**Comment by chaossme** [comment]
Upgrading to 1.1 requires following [these steps](https://voyager.readme.io/docs/10-to-11), but I still get this error after doing them.

**Comment by emptynick** [comment]
There is one very important step [here](https://voyager.readme.io/docs/10-to-11#section-bread) which get overlooked sometimes @chaossme but @ArditMata says its a fresh install.

**Comment by fletch3555** [comment]
@ArditMata, please verify that your database includes a `permissions` table with a row for `browse_bread`.  If not, please make sure you've followed the install steps completely (including migrations/seeders).

VoyagerBreadController:114 is in the `edit` method([ref](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerBreadController.php#L114)), which means the BREAD was created and you're trying to access the edit form.

**Comment by ArditMata** [comment]
@fletch3555 I created a new project and and strictly followed the installation steps. The previous error is fixed, but now i cannot delete any BREAD. The delete button just doesn't seem to do anything

**Comment by emptynick** [comment]
This is known and already [fixed](https://github.com/the-control-group/voyager/pull/3038).
How did you fix it now?

**Comment by samanmohamadi** [comment]
same problem.
v1.1.1

**Comment by emptynick** [comment]
@samanmohamadi Fresh install or upgrade?
If upgrade, please follow [my comment](https://github.com/the-control-group/voyager/issues/3114#issuecomment-385673764)
Or do you mean `clicking delete BREAD does nothing`?

**Comment by samanmohamadi** [comment]
removing all old migrations and a clean install fixed the issue.

**Comment by emptynick** [comment]
Closing this as all issues described here seem to be resolved.

**Comment by tangod0wn** [comment]
Still getting this error, went through all the steps mentioned above

**Comment by tangod0wn** [comment]
Got it working finally!
Needed to edit the PermissionsTableSeeder and add in 
        $keys = [
            'browse_admin',
            **'browse_bread',**
            'browse_database',
            'browse_media',
            'browse_compass',
        ];

**Comment by fletch3555** [comment]
@tangod0wn that's mentioned in the upgrade guide
