### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by navalevivek** [thedevdojo/voyager#3119]
- Laravel Version: 5.5
- Voyager Version: v1.1.0
- PHP Version: 7+
- Database Driver & Version: -

### Description:
Image is not showing, in new custom module.

I have already put default value while doing database table for it.

So if I am viewing View detail page of it at admin side, I am able to see image. Thinking that image path problem there, is there anything do i need to do coding for it please specify.

Can you please suggest me on same please.

**Comment by emptynick** [comment]
If you see the image on a `view` page, everything looks fine.
What is a "custom module"?

**Comment by navalevivek** [comment]
no i am not able to see on view page?

even where is code for view page in this package for particular page of a module?

**Comment by fletch3555** [comment]
It's very difficult to understand what you're saying.  It's clear English isn't your first language.  Can you try using a translation service like tramslate.google.com?  Perhaps the translation will be a little easier for us to understand

**Comment by navalevivek** [comment]
Hi Nick,

I am sorry for wrong English. But I believe and understand, communication really doesn't matter if we are talking on some technical things. What matters is logic or mutual understanding what topic is going on. Moreover in this world everybody has their own primary language, but still everybody tries to speak/write/read English which is required/necessary. Fluency shouldn't be compulsion. hope you didn't mind for this.

Anyways,

I am again explaining my problem as below : 

We have the modules like post, category etc at admin side in voyager package.

Same way if I have created another custom module which contains few basic fields like City, Code and Image.

So on like add/edit this functionality we are blocking for admin user. But admin can see view detail for this module.

So on view detail/page, admin is not able to see the Image for that city.

We are directly adding image, city, code into database table.

So can you please now give me the solution.

Any help would be highly appreciated.

**Comment by navalevivek** [comment]
Hi,

Secondly, whatever new modules I am creating from backend only by creating its database structure and everything properly, I am not able to add/insert the values of it into database through Add New form from backend.

Is there any extra settings I need to do. I have created its module, policy and required files.

So can you please now give me the solution.

Any help would be highly appreciated.

**Comment by Braiani** [comment]
@navalevivek it would be better if you post some pics of your problem! Maybe we can figure out what's going on only seeing the screenshot!

**Comment by navalevivek** [comment]
Sure and thanks for the updates will do soon.

**Comment by navalevivek** [comment]
![erro-2](https://user-images.githubusercontent.com/4848400/39614519-1e39e1cc-4f8e-11e8-9716-1c175f11b611.PNG)
![erro-1](https://user-images.githubusercontent.com/4848400/39614520-1e614776-4f8e-11e8-8391-d8a9ff2f3a19.PNG)


Can you help me out with these 2 errors

**Comment by navalevivek** [comment]
I guess Nick is not happy with my comments I wrote on his post.

Nick I am sorry if that is so.

But could you please help me with above issues.

**Comment by emptynick** [comment]
If you mean me then no, what comments do you mean?
Your second problem: There seems to be some things missing.
The method `getLocales()` is [here](https://github.com/the-control-group/voyager/blob/1.1/src/Voyager.php#L359-L362)

**Comment by navalevivek** [comment]
Ok thanks.

Can you also let me know about the data_row, data_types or settings kind of table :  how do I update them while committing the change son GIT, because whenever I am committing the code, these db-tables are not getting committed and my colleagues are not recieving any lates changes which I am making at admin side specially creating menu, creating any module etc from admin backend side.

**Comment by navalevivek** [comment]
![user_module_error](https://user-images.githubusercontent.com/4848400/39908621-8e775b94-550c-11e8-877c-de8df032856f.PNG)


Hello Nick,

I am getting to see such kind of error at admin panel side when I click on Add new user.

Almost all label in this form, are showing like 
voyager::generic.add User  or 
voyager::generic.email or
oyager::generic.password

etc...

So can you please help me with this. Is it something related to translation or what.

Also on Admin dashboard page, I am getting to see double dimmer. means for Post / User / Page, double boxes I get to see.

Please suggest and any help would be highly appreciated.

**Comment by navalevivek** [comment]
@emptynick  :

Any solution you found on my post?

**Comment by emptynick** [comment]
Looks like you setted your app-locale to an unsupported language.

Closing as off-topic. Please ask other questions in our Slack group.
