### ISSUE TITLE
Add category name to BREAD

### ISSUE THREAD

**Issue by smita153** [thedevdojo/voyager#3120]
- Laravel Version: 5.5.#
- Voyager Version: 1.1.#
- PHP Version: 7.1
- Database Driver & Version:

### Description:
I want to display Post Category on browse page. But if i check browse from BREAD it only display category id not Name.

**Comment by emptynick** [comment]
Looks like you are talking about the `category_id` field.
Why dont you add a relationship and display the `name`?

**Comment by smita153** [comment]
I have added relationship but still it shows  category_id  on brows.
