### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by m-xn** [thedevdojo/voyager#3123]
Hi,
First of all, this thing you call Voyager is so f*k*ng amazing. 
Best admin/crud generator/whatever ever made for Laravel.

This is not an issue but a request for help or advice.

I would like to have a blank template similar to the admin itself instead of the default Laravel home.
I mean the admin panel looks great and it would be good to have the same on the frontend in blank to add views to it and a custom menu.

Does that make sense?

If so, what would be the first step to do that?

I am pretty sure it would be good for most people by the way.

Thanks on any advice on this.

Juan Martín.

**Comment by protected22** [comment]
I know they're making something like that:
https://www.youtube.com/watch?v=q0oWyYa9f7c
But it isn't released yet

**Comment by eddielee394** [comment]
Take a look at:  https://github.com/pvtl/voyager-frontend

**Comment by fletch3555** [comment]
@protected22, Laravel Wave is built using Voyager, but is not built or maintained by us.

**Comment by Jean-PierreGassin** [comment]
Hey @m-xn!

As @eddielee394 has stated, we've currently got a front-end package for Voyager along with a few other packages that you might be interested in over at https://github.com/pvtl - hope that helps 👍

@fletch3555 I'm interested in getting our modules listed on the Voyager docs somewhere, can we chat?

**Comment by emptynick** [comment]
We have [awesome-voyager](https://github.com/larapack/awesome-voyager) which is a good start.

**Comment by emptynick** [comment]
Closing this one.
