### ISSUE TITLE
search select down shows No results found.

### ISSUE THREAD

**Issue by K12f** [thedevdojo/voyager#3126]
- Laravel Version: 5.5.0
- Voyager Version: 1.1.0
- PHP Version: 7.1.9
- Database Driver & Version: mysq5.7.19

### Description:
sorry,Forgive my bad english.

When web_ is added to MySQL prefix in config/database.php,
The list of search terms shows No results found.
When I remove prefix web_, it works.

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/12138140/39562276-5d03ab24-4edd-11e8-9b81-42c0c19c1f2e.png)

![image](https://user-images.githubusercontent.com/12138140/39562492-8592f68e-4ede-11e8-8022-cac449719fda.png)

**Comment by fletch3555** [comment]
This honestly doesn't surprise me at all.  Voyager makes use of a number of DB calls that don't go through Eloquent.  These queries use hardcoded queries that won't respect your "prefix" setting.  Fixing this would require a fairly sizable refactor of Voyager, which we're not prepared to do right this moment.

**Comment by K12f** [comment]
ok,thank you for providing so a cool tools.
