### ISSUE TITLE
Cannot add new user from admin panel 

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#3128]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version:7.1.3
- Database Driver & Version: MariaDB v10.1.26

### Description:
Cannot add new user from admin panel below is the error i am getting 
![user](https://user-images.githubusercontent.com/13164167/39571047-d57f138a-4efc-11e8-9885-f25b30f54a15.jpg)

**Comment by emptynick** [comment]
Looks like you missed something from the upgrade-guide.

**Comment by rddewan** [comment]
i see but i followed the steps correctly 
let me try to fresh install

**Comment by emptynick** [comment]
I mean this:
https://voyager.readme.io/docs/10-to-11#section-multi-roles
Theres the `data_row` which it complains is missing.

**Comment by rddewan** [comment]
@emptynick thank you got resolved
