### ISSUE TITLE
Renaming a table column via Database menu is not updating the data_rows table

### ISSUE THREAD

**Issue by lablushah** [thedevdojo/voyager#3129]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
From the menu Database, I have clicked the Edit button on products table, and changed a column name, from 'featured_image' to 'images'; the column updated in the products table in the database, but when I tried to create a new product, I got an error message, column not found: 'featured_image'. After debuging, I found the the data_rows table still has the column 'featured_image'; I did change the field name to images manually. I think this is a bug.

### Steps To Reproduce:
as mentioned in the Description section.

**Comment by fletch3555** [comment]
All version information is required.  Please update the issue with that information then this issue can be reopened.
