### ISSUE TITLE
mb_strlen() expects parameter 1 to be string, array given 

### ISSUE THREAD

**Issue by shamshadzaheer** [thedevdojo/voyager#3131]
- Laravel Version: 5.6
- Voyager Version: #.#.#
- PHP Version: 7.1
- Database Driver & Version: Mysql

### Description:
After a fresh installation, Logged in successfully. Took the Avatar Browse permission and then I try to browse users section but faced with the following issue, However I grant the permission back, but still having the issue. 

Note: All other sections are working normal.

ErrorException (E_ERROR)
mb_strlen() expects parameter 1 to be string, array given

**Comment by emptynick** [comment]
Please search before opening a new issue.
Duplicate of #3102, #3116 and #3121. Theres a temporary fix in the last issue.
