### ISSUE TITLE
Images cannot be displayed in Voyager Admin Panel

### ISSUE THREAD

**Issue by adillamokhtar** [thedevdojo/voyager#3132]
- Laravel Version: 5.6
- Voyager Version: #.#.#
- PHP Version:7.2.3
- Database Driver & Version:

### Description:
I have an issue about image that cannot be displayed in all the admin panel and avatar image is not working
I have tried change APP_URL = http://localhost:8000 and rebuild symlink with this command php artisan storage:link but doesn't work at all.
Can you guys help me???

**Comment by fletch3555** [comment]
Please share the URL to your site (feel free to use `example.com` to anonymize it if desired), and a link to one of the broken images (the `href` from the page source).  This will help us identify your problem.

Also, ALL version information is required when submitting issues here.  Please update your issue description to include the Voyager and Database version info.

**Comment by JAW-Dev** [comment]
I'm got the same.

There was an error during the install `The "public/storage" directory already exists.`, but the symlink  to the storage directory wasn't created.

I tried three more fresh Laravel and Voyager installs. The first two resulted in the same error and no symlink and the third one installed correctly.

It looks like creating the symlink is intermittently failing.

**Comment by adillamokhtar** [comment]
Database: mysql

how to check the version of voyager?
i couldnt find the href that lead to the image..i only can find when i use inspect..

**Comment by adillamokhtar** [comment]
![voyager](https://user-images.githubusercontent.com/33577143/39684277-44c6cd3a-51ed-11e8-9af5-2e8c843a16a0.JPG)

my admin panel does not show like image above.

my admin show like below.
![voyager2](https://user-images.githubusercontent.com/33577143/39684308-88996766-51ed-11e8-87ac-d82dc10635c8.JPG)

**Comment by fletch3555** [comment]
Widgets are part of `dummy data`, so it would appear as though you did a basic install, not a dummy data install.

The href I mentioned is 100% from the markup, so you're correct that you need to use your browser dev tools.

**Comment by adillamokhtar** [comment]
thank you..my problem is fix :+1:
