### ISSUE TITLE
Voyager Google Analytics is just blank

### ISSUE THREAD

**Issue by baavga** [thedevdojo/voyager#3135]
- Laravel Version: 5.4
- Voyager Version: 1.1
- PHP Version: 5.6.31
- Database Driver & Version: mysql 5.7.19

### Description:
Voyager Google Analytics is not working. It just shows blank i did everyting in this video
https://www.youtube.com/watch?v=Qw5HQiZIehg&index=12&list=PL_UnIDIwT95NureFNedKN9_GA6UOiS2ox
also i enabled analytics.
What is the problem?

### Steps To Reproduce: 
![image](https://user-images.githubusercontent.com/6432142/39661321-1473486e-5082-11e8-8e8d-d2869f96975e.png)

**Comment by emptynick** [comment]
Check your browser's develop console. There might be helpful warnings or errors.

**Comment by baavga** [comment]
This helped me thank you. I had to turn off third party adblock in Chrome . It worked
