### ISSUE TITLE
How to disable deleting file form media library after soft deleting record that contains it?

### ISSUE THREAD

**Issue by Terixer** [thedevdojo/voyager#3138]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.2

### Description:
How to disable deleting file form media library after soft deleting record that contains it?

### Steps To Reproduce:
1. Add new record _tesRecord_ with file.
2. Soft delete _tesRecord_.
3. Change 'deleted_at' at _tesRecord_ on NULL in database
4. Can't enter file (the file does't exist in media library anymore).

**Comment by MrCrayon** [comment]
I think this has been fixed. 

If you are still experiencing the same problem in current Voyager release please open another issue.
