### ISSUE TITLE
BREAD with multiple dates or times field

### ISSUE THREAD

**Issue by zeroiszero** [thedevdojo/voyager#3139]
- Laravel Version: 5.6
- Voyager Version: 1.1

### Description:
How can I customize to have multiple dates or times in BREAD ? 
Example of MultiDatesPicker: http://dubrox.github.io/Multiple-Dates-Picker-for-jQuery-UI/

Use case:  one course can have multiple dates, i want a field in Course BREAD to be able to select multiple dates.

**Comment by salesfg** [comment]
+1

**Comment by MrCrayon** [comment]
You can create a custom formfield:
https://voyager-docs.devdojo.com/customization/adding-custom-formfields
And if you need to manipulate data before saving to db you can check read my suggestion here:
https://github.com/the-control-group/voyager/issues/4585
