### ISSUE TITLE
Post update image not working

### ISSUE THREAD

**Issue by Taerarenai** [thedevdojo/voyager#3141]
Laravel Version: 5.6
Voyager Version: 1.1.1
PHP Version: 7.1
Database Driver & Version: 10.1.31 MariaDB

### Description:
While trying to update a post with a new image it does nothing. The file does not get updated, database doesnt get changed & no error shows up.

Also (if i may) any idea where image sizes are stored? id like to have the full image like the one i upload, not resized.
### Steps To Reproduce:

Go to posts -> edit post -> change image -> update.

**Comment by emptynick** [comment]
Please insert your Voyager version. Otherwise we are not able to help you.

**Comment by Taerarenai** [comment]
Just installed it yesterday, so i guess 1.1.1

**Comment by Taerarenai** [comment]
Found the culprit. I was trying to change the current post image with a 4k one to see how much voyager resizes the images, apparently it didnt like that. I tried a lower res image and it DID update. 
No errors were thrown while trying to upload the 4k image (those should be implemented, it wouldve stopped me from posting this issue XD).

Can anyone please assist me in changing voyager limits on image uploads ? (i suppose its a size limit, i'd like to bypass that and have higher resolution/size images without having them resized in the back-end).

**Comment by emptynick** [comment]
There is no limit.
The only limit is given in your php.ini.
Unfortunately `upload_max_filesize` errors are not thrown from PHP.

**Comment by Taerarenai** [comment]
Totally forgot about that limit, thanks. I'll close this one since it isnt an actual issue.
