### ISSUE TITLE
Locale Data Row is removed from database after updating users table BREAD

### ISSUE THREAD

**Issue by carlost89** [thedevdojo/voyager#3146]
- Laravel Version: 5.5.40
- Voyager Version: 1.1
- PHP Version: 7.0.28
- Database Driver & Version:

### Description:

When I update the users table BREAD, the locale data row is removed from database because this field doesn't exist in the users table. The problem is that when I try to edit the users locale language it doesn't work because the mutator:

`public function setLocaleAttribute($value)
    {
        $this->attributes['settings'] = collect($this->settings)->merge(['locale' => $value]);
    }`

does not trigger for the lack of locale data row.

What can I do to avoid that locale data row is being removed from database?

**Comment by emptynick** [comment]
That doesn't cause any problems as [the locale selection is hardcoded in the view](https://github.com/the-control-group/voyager/blob/1.1/resources/views/users/edit-add.blade.php#L92-L98)
I think the `data_row` in the `DataRowsTableSeeder` is just unnecessary

**Comment by carlost89** [comment]
Yes, you're right. It its hardcoded in the view, but the problem that is causing me is that when I change the locale of the user and save changes, setting isn't being storaged in users settings column. I had to remove the locale selector from the view for that problem.

**Comment by emptynick** [comment]
And after you removed the locale-selector from the view the locale is stored in the users settings-column? Sounds strange.
I just tried it with a locale data-row and without. Both are working perfectly fine.

**Comment by carlost89** [comment]
No, when the locale data-row is removed from database, the locale selected option is not sent in the post request and doesn't update the settings attribute in the users table. When I add the locale datarow in db it works again. The problem is when I update the users bread the locale data-row is removed from db and the problem starts again.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3846 (merged into 1.x)
