### ISSUE TITLE
Uploading an SVG file through Media Manager converts it to an .html file

### ISSUE THREAD

**Issue by eminos** [thedevdojo/voyager#315]
- Laravel Version: 5.3.26
- Voyager Version: 0.9.34
- PHP Version: 7.0
- Database Driver & Version:

### Description:
Uploading an SVG file through Media Manager converts it to an .html file, and changes the file name to some hashed one.

### Steps To Reproduce:
Upload an svg file through the Media Manager.

**Comment by marktopper** [comment]
Sadly `svg` is not supported by [`Intervention Image`](http://image.intervention.io/getting_started/formats).

Currently we threat all images by using Intervention.

**Comment by eminos** [comment]
In that case make an exception for svg files (and others?), so they doesn't go through Intervention Image? How does it work when uploading any other non image file?

**Comment by marktopper** [comment]
@eminos, I just digged into it. And we do not handle any file different in the Media section. There we just upload a file without changing anything. I though you meant the BREAD section.
Sorry for the misunderstanding. However I just tested, and SVG files works great for me.
Tried with this SVG: https://commons.wikimedia.org/wiki/File:Test.svg
Can you please try with that SVG file and let me know if that works?

**Comment by eminos** [comment]
Yep. That one works. But the file name is still not the original file name, it's just a hash. (Actually this seems to be the case with all file types?)
I've tried with some more svg files, and some work and some don't. The ones that don't work get the file type of `text/html` instead of `image/svg+xml`.

**Comment by marktopper** [comment]
Then the problem is with that particular `svg`, since the mimetype is incorrect.

**Comment by eminos** [comment]
It's not one file, it's many files. Normal, minified, svg files, exported from Illustrator. They work just fine in the browser and with other CMS. I guess it's the minification in the Asset/SVG export in Illustrator that changes the file a bit and makes the Manager fail to see it's an svg file.

**Comment by handiwijoyo** [comment]
For the file name, Laravel will automatically generate file name based on MD5 checksum. See https://laravel.com/docs/5.3/filesystem#file-uploads

**Comment by eminos** [comment]
Maybe the hashed file name generation should be an option/setting?
I see many use cases where one would not want the file names to change.

**Comment by marktopper** [comment]
But the mimetype says it a HTML page `text/html`.
And according to [w3](https://www.w3.org/TR/SVG11/mimereg.html) the only valid mimetype for an SVG file is `image/svg+xml`.

**Comment by eminos** [comment]
Yes. It seems the Illustrator svg export, with the Minify option enabled, removes the `<?xml/>` declaration in the beginning of the file and therefore the server, or whatever package is used to get the mimetype, fails to see it's an svg file. For sure not a bug in Voyager, but could still be an issue for the end user.

**Comment by marktopper** [comment]
@eminos, indeed it would be a problem for some users. But it would be impossible to lookup every file and check whether or not the mimetype is correct for that file or not. So in this case we would simply tell users to fix their file.
