### ISSUE TITLE
voyager can't find User class that's not in default location.

### ISSUE THREAD

**Issue by jeffreydwalter** [thedevdojo/voyager#3150]
- Laravel Version: 5.5.x
- Voyager Version: latest
- PHP Version: 7.2.4
- Database Driver & Version: mysql

### Description:

I'm using the laravel auth module and I moved all of my models to /App/Models, and voyager fails in VoyagerServiceProvider.php on line 85 saying: `Class 'App\User' not found` 

Is there a way to tell voyager to use a model directory other than the default?

### Steps To Reproduce:
Install laravel 5.5, install auth, move User.php model to /App/Models/User.php, install voyager.

**Comment by jeffreydwalter** [comment]
Am I supposed to voyager.user.namespace somewhere?

**Comment by jeffreydwalter** [comment]
https://github.com/the-control-group/voyager/issues/2712

**Comment by fletch3555** [comment]
[This line is likely what you need to update](https://github.com/the-control-group/voyager/blob/1.1/publishable/config/voyager.php#L16), but since you haven't provided any useful information (actual error message/stacktrace, what you were doing when this occurred, environment information, etc), I can't know for sure.

**Comment by jeffreydwalter** [comment]
@fletch3555 you're kind of a dickhead... What more do you need to know? I told you that voyager fails to install if you move the User.php model to App/Models/User.php... I think I made that pretty clear. There was NO stack trace, just an error message with line number, which I put in the bug description. I also gave you the environment info asked for. I gave you steps to reproduce, but you obviously can't be bothered to read.

Let me put it here again for you... 
```
Laravel Version: 5.5.x
Voyager Version: latest
PHP Version: 7.2.4
Database Driver & Version: mysql

Description:
I'm using the laravel auth module and I moved all of my models to /App/Models, and voyager fails in VoyagerServiceProvider.php on line 85 saying: Class 'App\User' not found

Is there a way to tell voyager to use a model directory other than the default?

Steps To Reproduce:
Install laravel 5.5, install auth, move User.php model to /App/Models/User.php, install voyager.
```

Don't worry about answering this... I'll find another admin package with a less dickish community.

**Comment by fletch3555** [comment]
Calling a maintainer of a package you're trying to use and obtain support from a "dickhead" shows the utmost of maturity.  I wish you well on your endeavours.
