### ISSUE TITLE
voyager::generic.* everywhere

### ISSUE THREAD

**Issue by KyryloGrygorenko** [thedevdojo/voyager#3154]
- Laravel Version: 5.4.
- Voyager Version: 1.1.
- PHP Version:5.6
- Database Driver & Version: MySql

### Description:
After making relationship voyager::generic.*  appeared everywhere. What is that and how to fix it? Thank you! 
![voyager_generic](https://user-images.githubusercontent.com/25619186/39781345-9a44f630-5317-11e8-9f29-3593fa62bc9c.jpg)

**Comment by emptynick** [comment]
Those are translation string keys.
Cause might be that you set both the app-locale **and** fallback-locale to a not supported one.
You can see all supported languages [here](https://github.com/the-control-group/voyager/tree/1.1/publishable/lang)

**Comment by KyryloGrygorenko** [comment]
I haven't set any of those. I was changing the User TCG\Voyager\Models\User to App\User  and it happened. I already changed it back. But the issue is still here.

**Comment by fletch3555** [comment]
What do you mean by "changing the TCG\Voyager\Models\User to App\User"?

**Comment by KyryloGrygorenko** [comment]
Changing the model in admin/bread/users/edit  
![image](https://user-images.githubusercontent.com/25619186/39782511-19a54d0a-531b-11e8-8b4a-012a8579cd96.png)

**Comment by KyryloGrygorenko** [comment]
I've just rolled back to the earlier version of my site so now it is OK
