### ISSUE TITLE
compass 500error 

### ISSUE THREAD

**Issue by droftage** [thedevdojo/voyager#3155]
- Laravel Version: 5.6
- Voyager Version:1.1
- PHP Version:7.2
- Database Driver & Version: mysql5.7

### Description:
Can't find artisan 

When I run Compass 。

There's always 500 errors.

### Steps To Reproduce:
![tim 20180509104040](https://user-images.githubusercontent.com/31786794/39792927-af376f88-5375-11e8-8d1a-3f00a0187c2b.png)
![tim 20180509104009](https://user-images.githubusercontent.com/31786794/39792933-b6b3deae-5375-11e8-866a-f07379f8321c.png)
![tim 20180509103941](https://user-images.githubusercontent.com/31786794/39793074-68851652-5376-11e8-9498-11487803702f.png)

**Comment by fletch3555** [comment]
We'll need to see the error message/stacktrace from the logs

**Comment by xnzj** [comment]
Same problems here. And the apache log is
 `[Tue Jun 26 00:04:09.949787 2018] [core:error] [pid 57596:tid 2116] [client 127.0.0.1:50365] End of script output before headers: index.php, referer: http://voyager.cc/admin/settings`

**Comment by MrCrayon** [comment]
Since this is for an old version and no logs where provided I'm closing this. 

If you are still experiencing this problem with last Voyager release you can open another issue.
