### ISSUE TITLE
MUST be included the requirements

### ISSUE THREAD

**Issue by jonjie0317** [thedevdojo/voyager#3156]
I reviewed the documentation but I didn't see the requirements for the installation (like laravel have). You must have this part on the installation so developers will know what versions of laravel, php, etc. needed. Thanks!

**Comment by fletch3555** [comment]
Voyager's readme file lists the supported laravel versions, as does our documentation.  However compiser.json is the source of truth for all dependency versions

**Comment by jonjie0317** [comment]
Hi @fletch3555 . Thanks for the response. Can you give me a link for this?

**Comment by Braiani** [comment]
I'll answer for fletch...
Access this page and scroll down until you see the readme text... https://github.com/the-control-group/
If you don't find, access this: https://github.com/the-control-group/voyager/blob/1.1/README.md

**Comment by emptynick** [comment]
Closing as this seems to be solved.
