### ISSUE TITLE
Non-object error when trying to edit a user

### ISSUE THREAD

**Issue by ruudz** [thedevdojo/voyager#3159]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.1
- PHP Version: 7.2
- Database Driver & Version: Mariadb (version: ?)

### Description:
When logged in as an admin, every other user I try to edit results in an error:

```
Trying to get property 'details' of non-object (View: /var/www/project/vendor/tcg/voyager/resources/views/users/edit-add.blade.php)
```

```
<div class="form-group">
    <label for="additional_roles"><?php echo e(__('voyager::profile.roles_additional')); ?></label>
    <?php
        $row     = $dataTypeRows->where('field', 'user_belongstomany_role_relationship')->first();
        $options = json_decode($row->details);
     ?>
     <?php echo $__env->make('voyager::formfields.relationship', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
</div>
```
The logged in user can see the details of other users and delete them. The error only occurs when trying to open the edit view. The only two roles that are available are Administrator and User. 

### Steps To Reproduce:

1. Log in with a user that has the Administrator role.
2. Go to Users overview
3. Select 'Edit' on a user row that is not the currently logged in user.

**Comment by emptynick** [comment]
If you just upgraded: I think you missed something from [here](https://voyager.readme.io/docs/10-to-11)

**Comment by ruudz** [comment]
Also experiencing problems as described in #3071 and #3157. Not sure if that's related.

**Comment by ruudz** [comment]
@emptynick, thanks! Did not know there was a guide, my bad. I'll try and see if this resolves the problem.

**Comment by ruudz** [comment]
Fixed by adding the new data row for user_belongstomany_role_relationship as described in [here](https://voyager.readme.io/docs/10-to-11).

**Comment by huuloc4193** [comment]
Fixed by stes bewlow:

1. Go to phpmyadmin 

2.  find "user_belongsto_role_relationship" && "user_belongstomany_role_relationship" at field column

3. Chang from "0" to "1" in Edit column
