### ISSUE TITLE
body font-size is different on Dashboard page because of ga-embed.css

### ISSUE THREAD

**Issue by eminos** [thedevdojo/voyager#316]
- Laravel Version: 5.3.26
- Voyager Version: 0.9.34
- PHP Version: 7.0
- Database Driver & Version:

### Description:
The body font-size on the Dashboard page is getting inherited from the ga-embed.css file and overwriting the value from voyager.css thus making all the text smaller, including the side menu.

### Steps To Reproduce:
Install Voyager.
Login to Admin.

**Comment by marktopper** [comment]
Fixed in #339
