### ISSUE TITLE
Can't edit user data rows

### ISSUE THREAD

**Issue by b4dnewz** [thedevdojo/voyager#3160]
- Laravel Version: 5.5.x
- Voyager Version: 1.1.x
- PHP Version: 7.1

### Description:
I'm trying to customize the users add/edit page data rows to add custom fields and relationships and I've noticed dataRows declarations are not working or at least not showing.

### Steps To Reproduce:
Go to `app/database/seeds/DataRowsTableSeeder.php` go in the user table section and add something for example:
```php
$dataRow = $this->dataRow($userDataType, 'verified');
    if (!$dataRow->exists) {
        $dataRow->fill([
            'type'         => 'checkbox',
            'display_name' => 'Verified',
            'required'     => 1,
            'browse'       => 1,
            'read'         => 1,
            'edit'         => 1,
            'add'          => 1,
            'delete'       => 0,
            'details'      => '',
            'order'        => 4,
        ])->save();
    } 
```

Run the seed again, go into `admin/users/create` route and see the field is not showing up.
Also I'm trying to create a belongsToMany relationship like "Additional Roles" in the user data row declaration by coping the statement and changing the table names but it still not showing.

As side note on the `admin/bread/users/edit` page the **verified** field and the **user_belongstomany_team_relationship** relationship field are showing up without errors.

**Comment by emptynick** [comment]
Thats kind of wanted behaviour.
The rows you see in the BREAD-editor are actual columns from your database, so if it doesn't exist in your database, it will not be displayed and then removed when saving.
Thats why https://github.com/the-control-group/voyager/issues/3146 is failing.
But I see there's a neccesity for additional attributes like introduced in https://github.com/the-control-group/voyager/pull/2885 (for relationships)

**Comment by b4dnewz** [comment]
But in my case the column **verified** exist and the table and column used for the belongstomany relationship exists too, I've tried to copy the pattern used for Roles
```php
$dataRow = $this->dataRow($tableDataType, 'user_belongstomany_role_relationship');
    if (!$dataRow->exists) {
        $dataRow->fill([
            'type'         => 'relationship',
            'display_name' => 'Roles',
            'required'     => 0,
            'browse'       => 1,
            'read'         => 1,
            'edit'         => 1,
            'add'          => 1,
            'delete'       => 0,
            'details'      => '{"model":"TCG\\\Voyager\\\Models\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
            'order'        => 11,
        ])->save();
    }
```
but with a different relation, the **team_users** table exists and has `team_id, user_id` columns:
```php
$dataRow = $this->dataRow($tableDataType, 'user_belongstomany_team_relationship');
    if (!$dataRow->exists) {
        $dataRow->fill([
            'type'         => 'relationship',
            'display_name' => 'Teams',
            'required'     => 0,
            'browse'       => 1,
            'read'         => 1,
            'edit'         => 1,
            'add'          => 1,
            'delete'       => 0,
            'details'      => '{"model":"App\\\Team","table":"teams","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"team_users","pivot":"1","taggable":"0"}',
            'order'        => 11,
        ])->save();
    }
```
**Edit:** Also in the voyager interface the autocomplete when building relationship works so I'm assuming is just no showing on page.

There is something else to do? Or is just not possible right now?
Many thanks for the quick response.

**Comment by emptynick** [comment]
Whoops, sorry, didnt read that you dont see the field when creating a new user.
Yes, thats because we use a [custom view](https://github.com/the-control-group/voyager/blob/1.1/resources/views/users/edit-add.blade.php) which only shows the fields coded inside.  
What you can do is to [override the overriden view](https://voyager.readme.io/docs/overriding-views) and just put some like
`@extends('voyager::bread.edit-add')`
in it (didn't test that, but _should_ work, or duplicate the view and add your fields)

**Comment by b4dnewz** [comment]
awesome, i'll try later
