### ISSUE TITLE
Route [voyager.posts.index] not defined. 

### ISSUE THREAD

**Issue by nakigami** [thedevdojo/voyager#3161]
- Laravel Version: 5.5.*
- Voyager Version: #.#.#
- PHP Version: 7
- Database Driver & Version:Mysql

### Description:
i've installed voyager and i created an admin account but when i want to conect with i got this error 
Route [voyager.posts.index] not defined.

**Comment by Braiani** [comment]
What version of Voyager are you using? Did the installation show any warning or error? Could you post an image of the error you're having?

**Comment by fletch3555** [comment]
More information is required in order to troubleshoot your issue.  Please answer @Braiani's questions and reopen this issue.
