### ISSUE TITLE
How to add sub-menu to point a specific setting Tab

### ISSUE THREAD

**Issue by YounessTayer** [thedevdojo/voyager#3165]
- Laravel Version: 5.6.20
- Voyager Version: 1.1.1
- PHP Version:7.1
- Database Driver & Version:

### Description:
Hi  Anyone can explain to me how I can point my settings "NewTab" sub-menu directly to a specific settings tab (Site, Admin and my "New_tab" that I want to be automatically selected when I click on NewTab sub-menu)?

**Comment by fletch3555** [comment]
If changing the settings tabs doesn't alter the URL (i.e. add `#tabname` or similar), then this isn't (currently) possible.  If it does add that, then just use that as your link.

**Comment by YounessTayer** [comment]
Hi, I used the menu builder to create my "NewTab", it doesn't alter the URL, so in my current situation I can access my settings tabs only by clicking on the "NewTab" sub-menu that I have created, but my goal is to be able to access separately for each Tab of the my Settings menu by clicking on separate sub-menus (Site, Admin, NewTab1, NewTab2...) Is that possible?  I Thought the menu builder will create automatically the routes for us! 

In advance , thanks for all the support you provide for the community :)
