### ISSUE TITLE
Add controller and view generation

### ISSUE THREAD

**Issue by seoeaa** [thedevdojo/voyager#3166]
You can add it when creating a table in the database, creating a view and controller. Select from several standard views, with editing and adding. You have to clone all hands. Better then change the look and controller.

**Comment by emptynick** [comment]
Also here, what is the actual issue?

**Comment by fletch3555** [comment]
I'm sorry, but this issue description does not make any sense and doesn't follow the required issue template.  Please provide more details and attempt to clarify the feature you're requesting/issue you're reporting.
