### ISSUE TITLE
Site logo path to file

### ISSUE THREAD

**Issue by seoeaa** [thedevdojo/voyager#3168]
- Laravel Version: 5.6.22
- Voyager Version: 1.1
- PHP Version:7.1
- Database Driver & Version:5.6

### Description:
Site logo path to file
{{asset(setting('site.logo'))}}  

http://mydomain.dev/settings\May2018\WpJTM4rYvDzCtrKylizT.png

**Comment by emptynick** [comment]
And what is the issue?

**Comment by Braiani** [comment]
I think is the backslashes @emptynick... See that the link has backslashes after `settings`.

**Comment by emptynick** [comment]
If thats the problem, take a look at [how Voyager does it](https://github.com/the-control-group/voyager/blob/1.1/resources/views/login.blade.php#L17)

**Comment by fletch3555** [comment]
Yes, you need to be using `voyager_asset()` instead of `asset()` for any images managed by Voyager.
