### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by eminos** [thedevdojo/voyager#317]
- Laravel Version: #.#.#
- Voyager Version: 0.9.34
- PHP Version:
- Database Driver & Version:

### Description:
Voyager Admin is not optimized for anything smaller than a laptop screen. I possibly looks OK on "tablet size" (haven't tested) but definitely not on mobile.
Since the Admin displays a lot of tables a solution like FooTables might be good. Or similar for vue.js?
http://fooplugins.github.io/FooTable/

**Comment by marktopper** [comment]
We are open for pull requests

**Comment by emptynick** [comment]
I guess this can be closed

**Comment by fletch3555** [comment]
Agreed, this is ancient.  We'll work on design issues as they come up.
