### ISSUE TITLE
Multilanguage not working. How to add or override language ?

### ISSUE THREAD

**Issue by mrtieutien90** [thedevdojo/voyager#3172]
- Laravel Version: 5.6.*
- Voyager Version: 1.1.1
- PHP Version:7.1.3
- Database Driver & Version:

### Description:
Multilanguage not working  . How to add new or override language ?
I try config files.
config/voyager.php

```
'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'vi',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'vi',
            //'pt',
        ],
    ],
```

and config/app.php 

```
return [
    ...
    'locale' => 'vi',
    ....
];
```

---- 
I created folder lang/vi . see image.
http://www.upsieutoc.com/image/45hwiN

### Steps To Reproduce:
Install Laravel with Voyager
Change multilingual in config/voyager.php
Change locales in config/app.php

**Comment by emptynick** [comment]
This is described in the [Laravel docs](https://laravel.com/docs/5.6/localization#overriding-package-language-files)

**Comment by mrtieutien90** [comment]
Thanks for answer @emptynick ,
But Not working. I can not override it . Maybe  Voyager not accept override language or it error.

**Comment by fletch3555** [comment]
First of all, if you get an error, it's immensely helpful to provide the actual error message and stacktrace.

For your issue, it's likely because you're only adding the translations to your app.  For Voyager to be able to find them, you need to add them to the Voyager namespace (`resources/lang/vendor/voyager/vi/`)

**Comment by mrtieutien90** [comment]
Thanks a lot.
I just want to use Vietnamese.
pls see images : http://www.upsieutoc.com/image/48w8XA 
I have read the voyager's document follow the instructions but it only accepts english language.

Thanks.

**Comment by hungxinh** [comment]
@mrtieutien90,
Nếu bạn chỉ dùng ngôn ngữ Vietnamese (VI), bạn copy vào đường dẫn sau là xong.
Root: /vendor/tcg/voyager/publishable/lang/vi

If you only use the Vietnamese language (VI), you just copy folder VI into the following path is finished:
Root: /vendor/tcg/voyager/publishable/lang/vi

It work fine!!!

![screenshot 2018-05-16 09 01 49](https://user-images.githubusercontent.com/23396671/40092674-b8afb3f4-58e8-11e8-8bc7-038122585425.png)

**Comment by mrtieutien90** [comment]
Thankyou @hungxinh.
This is always add to the packet of voyager. I follow the instructions of @ fletch3555 and @emptynick but not working.

**Comment by chientrinh** [comment]
> Thankyou @hungxinh.
> This is always add to the packet of voyager. I follow the instructions of @ fletch3555 and @emptynick but not working.

You need clear cache.

php artisan config:cache

**Comment by josepcrespo** [comment]
This bug stills happening on year 2020 (version 1.4), clearing the cache as @quocchienit explained makes it work. I will edit de documentation so everybody can avoid this confusion.
