### ISSUE TITLE
BigInteger for the user_id

### ISSUE THREAD

**Issue by marcreichel** [thedevdojo/voyager#3174]
- Laravel Version: 5.6.21
- Voyager Version: 1.1.1
- PHP Version: 7.2.3
- Database Driver & Version: PostgreSQL 10.3

### Description:
I'm using a bigInteger snowflake ID in my users-table. But the voyager migration files are using the default integer. Could I change this behaviour?

### Steps To Reproduce:
Change the `id` in the users-table-migration to bigInteger('id')->unsigned()->primary()

**Comment by fletch3555** [comment]
If you copy the migration files to your project and run them, then the Voyager copies will not run as it'll think it already ran.  Then you can just change it to whatever you need.

**Comment by marcreichel** [comment]
I‘ve tried this and it tried to run both migrations and therefore ran into an error as it tried to create two tables with the same name. It also ran the migrations from the package first and therefore my migrations failed.
