### ISSUE TITLE
Changing default path causes post-login exception (seems related to symlink creation failure when non-default path is used)

### ISSUE THREAD

**Issue by 109digital** [thedevdojo/voyager#3178]
- Laravel Version: 5.6.21
- Voyager Version: 1.1
- PHP Version: 7,2
- Database Driver & Version: MySQL 5.7

### Description:

When I change the default URL, this exception is thrown after login: 

```
Impossible to create the root directory "". (View: /home/forge/app.fssportal.com/vendor/tcg/voyager/resources/views/master.blade.php) (View: /home/forge/app.fssportal.com/vendor/tcg/voyager/resources/views/master.blade.php)
```

This is a fresh install, and everything works without issue if I roll back the two changes described below.

### Steps To Reproduce:

1. Start with a fresh Laravel and Voyager install.

2. Edit `config/voyager.php` to add `prefix` key/value and edit `user.redirect` value:

```
...

    'user' => [
...
        'redirect'                     => '/user',
    ],
    
    'prefix' => 'user',
...

```
(Note: Tried both with and without adding `prefix`, which is mentioned in the 1.1 docs but isn't in the actual config file.)

3. Edit `routes/web.php`:

```
...
Route::group(['prefix' => 'user'], function () {
    Voyager::routes();
});
...
```

4. Run `php artisan migrate`, `php artisan db:seed`, & `php artisan voyager:install`

5. Run `php artisan voyager:admin someuser@domain.com --create`

---

This is not an environment issue.

We have a staging site running on the same server. It works perfectly, and the only difference is these two changes. Everything else is the same, including .env. 

When I roll back those changes and redeploy, everything works. 

I notice that there are symlink issues when I install Voyager using the custom prefix. Ubuntu says that there are "too many levels" of symlinks, even if I manually run `php artisan storage:link` after installing Voyager. There's no such issue with the symlink when I install using the normal "admin" prefix.

**Comment by fletch3555** [comment]
`prefix` in the config file was removed with 1.1, so that's a docs error.  Sorry for the confusion, but it won't do anything.

Can you try changing just the prefix in the route file and not the redirect config? Does that trigger the same error?

Also, what exactly were you doing when the error occurred? Can you share the full stacktrace? (Might have to open the laravel log file if it's not visible in the whoops error page)

The symlink issue is likely a configuration issue with your environment.  I'd need to know a lot more about how you have laravel installed and how you "deploy" it to the server.

**Comment by 109digital** [comment]
Thank you - changing **only** the web.php prefix solved it _[but not really - see update below]_. I now see the dashboard as expected, rather than getting the "impossible to create directory" exception.

As this is a fresh install, I can't yet tell if there are any lingering issues caused by having a mismatch between the `web.php` prefix and the config file's `user.redirect`. So further testing could be needed there.

What's interesting is that when I changed the config `redirect` value to "/user" after successfully logging in just now, then Voyager takes me to /admin upon login and I get a standard 404 error. But if the value is set to "/user" when `php artisan voyager:install` is initially run (or `php artisan storage:link`), then I instead get an exception upon login . I believe something about the `redirect` value is interfering with the symbolic link creation.

If you run some tests locally, you should see the same.

**Comment by 109digital** [comment]
## Update ##

I'm able to reproduce the error again, even if *only* the web.php prefix is edited, simply by running `php artisan storage:link` after the Voyager install.

The exception is definitely related to the storage symlink, which Ubuntu is once again is showing as invalid. This is only happening when a custom path is used.

Here's a screenshot of what happens after login: https://i.gyazo.com/d0822100421b494f53cce13cffd6a4ba.png

[frames.txt](https://github.com/the-control-group/voyager/files/2001551/frames.txt)

If I **do not** run `php artisan storage:link` after installing Voyager, then I am able to log in without getting an exception. But when I try to log out, I get a 404 error because it's trying to return me to /admin rather than /user.

**Comment by MrCrayon** [comment]
Can't reproduce, if you are still experiencing this problem please update and open another issue.
