### ISSUE TITLE
Cannot use Intervention\Image\Facades\Image as Image because the name is already in use

### ISSUE THREAD

**Issue by PinkuChanda** [thedevdojo/voyager#3179]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.0.9
- Database Driver & Version:

### Description:
when i select multiple image in voyager  and then add the voyager show this error: 
"Cannot use Intervention\Image\Facades\Image as Image because the name is already in use".
please let me know what is the problem behind it and how i can fix this..

**Comment by fletch3555** [comment]
Please share the full stacktrace for that error.  It's likely something we have to fix in the package, not something you can fix yourself

**Comment by PinkuChanda** [comment]
![1](https://user-images.githubusercontent.com/20628167/40001228-978ff682-57af-11e8-83e5-57d6b893d3a1.PNG)
![2](https://user-images.githubusercontent.com/20628167/40001235-9906fe84-57af-11e8-9400-ac74dc7ceef9.PNG)

Here are some Screen Shot of this problem. Please take care for this error as soon as possible because we are working on many big projects by the Voyager. 

Thanks 
Kind Regards 
Pinku Chanda

**Comment by emptynick** [comment]
I think it should be the same like [here](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/ContentTypes/Image.php#L8)
Maybe someone wants to create a PR.

**Comment by PinkuChanda** [comment]
@emptynick you did this for Image.php but i have problem in multiple image.. my image works fine.. but the problem is in MultipleImage.php .. multiple image is not working.

**Comment by emptynick** [comment]
Yes, thats why I said it should be the same as in `Image.php` because there it works, and in `MultipleImages` not
