### ISSUE TITLE
Safari support? freezes

### ISSUE THREAD

**Issue by amc123-glitch** [thedevdojo/voyager#3186]
"php": "^7.1.3",
"fideloper/proxy": "^4.0",
"laravel/framework": "5.6.*",
"laravel/tinker": "^1.0",
"tcg/voyager": "^1.1"
Safari Version: 11.1

- Database Driver & Version:

### Description:
I use most browsers to test my code accordingly. I have no issue with chrome, firefox, or even brave. But with Safari I can not create, update or submit any data when logged in on safari. If I log in with both chrome and safari, I can add a post in chrome and save it. If I try to click submit/save when using safari it loading wheel spins endlessly and the data never gets saved.

Not a major issue for me but if I am building for a client who uses safari, it would be a hassle to have to convince them to use another browser

### Steps To Reproduce:
- create new project with dummy data
- login
- access the post 
- enter title, body, etc
- click save and the waiting game begins
- refresh when you give up on waiting and check database to find no new post

**Comment by emptynick** [comment]
This seems really similar to https://github.com/the-control-group/voyager/issues/3001

**Comment by amc123-glitch** [comment]
Yes it seems similar. However, I am experiencing this with everything. In their issue they claimed some bread/data modification works in the dev version, in the stable version I am using there is no working forms. 

But works in firefox, chrome, and brave.

**Comment by jannejava** [comment]
Indeed #3001 - As soon there is an empty file field in a form, it will not work in Safari. Just try to add a file and it will work. 

I am using my own fork and it now works fine with Safari (I have created a pull-request for this). The controller is the same for BREAD, post and pages, I think.

**Comment by emptynick** [comment]
Closing as https://github.com/the-control-group/voyager/pull/3004 was merged.
