### ISSUE TITLE
Scrambled Table 

### ISSUE THREAD

**Issue by anandmainali** [thedevdojo/voyager#3188]
- Laravel Version: 5.5.*
- Voyager Version: 1.0
- PHP Version:
- Database Driver & Version:

### Description:
Text are not in place.. How to solve this problem..
![screenshot_2](https://user-images.githubusercontent.com/34227482/40096460-b42adaf4-58f0-11e8-88b2-4a72d82fba11.jpg)

Tables are always scramled when refresh the page..
![voyager](https://user-images.githubusercontent.com/34227482/40096429-8bf8ca1e-58f0-11e8-8f0b-e08d5b8e0055.jpg)

**Comment by anandmainali** [comment]
@fletch3555  hey anybody here???

**Comment by fletch3555** [comment]
To quote from one of my favorite reads: http://www.catb.org/esr/faqs/smart-questions.html

> We're (largely) volunteers. We take time out of busy lives to answer questions, and at times we're overwhelmed with them.

> If you can't get an answer, please don't take it personally that we don't feel we can help you. Sometimes the members of the asked group may simply not know the answer. No response is not the same as being ignored, though admittedly it's hard to spot the difference from outside.

Please be patient and we'll get to this when we get a chance.

**Comment by MrCrayon** [comment]
That looked like a problem with readmore that has been removed from Voyager. 

If you are still experiencing this problem in current Voyager release please open another issue.
