### ISSUE TITLE
[FIXED Multilanguage] The title of menus item isn't showing

### ISSUE THREAD

**Issue by hungxinh** [thedevdojo/voyager#3189]
- Laravel Version: #.#.#
- Voyager Version: 1.1 -> 1.1.1
- PHP Version:
- Database Driver & Version:

### Description to FIX:
Open menu/admin.blade.php
Change 
htmlspecialchars(json_encode($item->getTranslationsOf('title')))
To
json_encode($item->getTranslationsOf('title'))
Done!

![screenshot 2018-05-16 12 36 51](https://user-images.githubusercontent.com/23396671/40098679-f189d204-5906-11e8-8585-05cec3b17380.png)
![screenshot 2018-05-16 12 44 00](https://user-images.githubusercontent.com/23396671/40098688-f9e6b34a-5906-11e8-9bd1-1bd0ccd96d76.png)

https://github.com/the-control-group/voyager/issues/2731
https://github.com/the-control-group/voyager/issues/3042
https://github.com/the-control-group/voyager/issues/3184

**Comment by emptynick** [comment]
Can you open a PR?

**Comment by fletch3555** [comment]
Agreed, this should be opened as a PR, not an issue.
