### ISSUE TITLE
Change default failed login attempts and lockout time in Voyager Admin login?

### ISSUE THREAD

**Issue by SultanSagi** [thedevdojo/voyager#3190]
- Laravel Version: 5.5.#
- Voyager Version: 1.1.#
- PHP Version:
- Database Driver & Version:

### Description:
I want to change default failed login attempts and lockout time in Voyager Admin login? I try override function hasTooManyLoginAttempts in VoyagerAuthController. But it's not work. Any ideas?

**Comment by ghost** [comment]
Any updates on this issue?

**Comment by MrCrayon** [comment]
Voyager uses standard `Illuminate\Foundation\Auth\AuthenticatesUsers ` so whatever was the problem you can probably find the solution in Laravel documentation / forums.
