### ISSUE TITLE
Forbidden You don't have permission to access file on this server.

### ISSUE THREAD

**Issue by sjayjay005** [thedevdojo/voyager#3191]
- Laravel Version: 5.5.40
- Voyager Version:1.1.0
- PHP Version:
- Database Driver & Version:

### Description: 
Hi I'm new to voyager, So, I am running voyager, great tool on that note, on a shared hosting environment, I did a lot of reading around before I finally decided to ask here. I have my Laravel app, lets call it "cat-app" on the same directory as  my "public_html" folder, and contents of cat-app/public are on the "public_html"  folder, I did also ssh in and symlinked "cat-app/public/storage" to "public_html" I did also check my .env file's APP_URL value and it's pointing to my base domain.  Is there a way of changing the storage pah to something else in voyager. As I am getting a
Forbidden
You don't have permission to access /storage/users/default.png on this server. This happens with all of the files and images, please help.

### Steps To Reproduce:

If I go to any image url. I get Forbidden
You don't have permission to access /storage/users/default.png on this server.

**Comment by fletch3555** [comment]
Couple things....

1. By putting `cat-app` under `public_html`, you're exposing a security risk (`http://example.com/cat-app/.env`).
2. You shouldn't just "move" the contents of your public folder like that.  But if you do, you need to tell laravel how to find the "new" public folder (override `path.public` in the IOC container. If that sounds like gibberish, a Google search on those terms should help)
3. Your symlink is wrong.  Once you fix number 2 above, `artisan storage:link` will make the symlink so you don't have to do it manually.  If you insist on doing it manually, it needs to live in `public`(public_html for you), be called `storage`, and link to `cat-app/storage/app/public`

Just to be clear, none of this is specific to Voyager.

**Comment by sjayjay005** [comment]
@fletch3555 Thank you for the advice, let me try re-explaining this situation that "cat-app" is on the same directory level as 
|__cat-app
|__public_html
     |_ ..
         index.php
         favicon.ico
         vendor
         storage
         js
         css

"public_html" .only has content that was previously on "cat-app" public directory. I have the app working fine and all, I just have a problem with the broken profile images because every time i try to access them i get the forbidden error, this includes the profile image and other bread images excluding the icons. I have updated my APP_ENV. I was thinking maybe it still references the old public folder but it could be something else. Note Storage is symlinked to the correct place because it was generated by voyager.

**Comment by fletch3555** [comment]
Ah okay, that's much better.

However, storage is very likely NOT correct with that setup, even if Voyager generated it.  All Voyager does is call `artisan storage:link`, which requires that laravel know how to find the public directory.  Since you've effectively moved it, laravel will be looking in the wrong place.  The solution is to override `path.public` in the IOC container.  A quick Google search for "installing laravel on shared hosting" should help.  Once that's in place, you'll need to delete/rename anything named "storage" in your public_html directory, then re-run `artisan storage:link`

**Comment by sjayjay005** [comment]
@fletch3555 thank you for pointing me to the right direction. I'm sure I can handle it from here.

**Comment by fletch3555** [comment]
No problem.  If you have further questions, feel free to join our Slack group (link found in our README).
