### ISSUE TITLE
Add New Action to Voyager

### ISSUE THREAD

**Issue by shadihrr** [thedevdojo/voyager#3194]
- Laravel Version: 5.5
- Voyager Version:1.1
- PHP Version: 7
- Database Driver & Version: MySQL 5.6

Hi, Thank you for this great admin panel. I have a question. I noticed that we could add action to the already existing actions (delete, edit and view) via Voyager::addAction. My question is that how can I do that without changing the core code? and how can I make it only for specific path (for example only for /admin/product). Sorry I am newbie and I couldn't find any documentation for this.

**Comment by cyrildewit** [comment]
### > how can I do that without changing the core code?

I can't answer this question with full certainty. I think that the best place to register/add custom actions to Voyager is a service provider. It doesn't matter which one, so for now you could register the action in the `AppServiceProvider`. I believe that the `boot` method is okey.

```php
use Voyager;
use App\Actions\CustomAction;

public function boot()
{
    Voyager::addAction(CustomAction::class);
}
```

### > how can I make it only for specific path

You can add the `getDataType` method to your custom action that returns the data types name. This [method](group/voyager/blob/1.1/src/Actions/AbstractAction.php#L49) checks if the action should only be displayed for a specific data type.

I believe something like this:

```php
// ... class: CustomAction {
public function getDataType()
{
    return 'custom-name';
}
// ... }
```

_I didn't tested the code, so it might not work._ 

I hope this will help you with fixing your issue!

**Comment by Braiani** [comment]
You can, additionally, see this one: https://github.com/the-control-group/voyager/pull/2678

**Comment by fletch3555** [comment]
The above 2 comments should answer your question.  If you have additional questions or need further help with this, please ask on our slack group's #help channel

**Comment by shadihrr** [comment]
Sorry I couldn't login to slack (sanction to my country), I only can ask questions here. The above solution worked. Thank you. But now I want to display this action in the permission lists. I realized that we should create a policy but I don't know what to do after that. Can you help me?

**Comment by JDSHINDE** [comment]
follow this link to add a new custom action
https://docs.laravelvoyager.com/customization/action-buttons

**Comment by fletch3555** [comment]
Please don't comment on old/closed issues. This was for a much older version and has been closed for nearly a year now
