### ISSUE TITLE
correct way to remove BREAD?

### ISSUE THREAD

**Issue by luizpatrocinio** [thedevdojo/voyager#3197]
- Laravel Version: 5.6.22
- Voyager Version: 1.1.1
- PHP Version:
- Database Driver & Version:

### Description:

Correct way to remove BREAD. Direct in database?

**Comment by fletch3555** [comment]
Have you tried the `Delete BREAD` button on the database list (`/admin/database`)?

**Comment by luizpatrocinio** [comment]
Hi,

I have done this deletei by the manager and the error is shown.

 ErrorException (E_ERROR)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voy.pages' doesn't exist (SQL: select count(*) as aggregate from `pages`) (View: C:\www\voy\vendor\tcg\voyager\resources\views\dimmers.blade.php) (View: C:\www\voy\vendor\tcg\voyager\resources\views\dimmers.blade.php)

**Comment by cyrildewit** [comment]
You have remove the `PageDimmer` from your config at `voyager.dashboard.widgets`. Otherwise this widget will be rendered on your dashboard page, which triggers this error.

**Comment by luizpatrocinio** [comment]
Perfect men.

Tks,
