### ISSUE TITLE
Browse view breaks on mobile

### ISSUE THREAD

**Issue by thill0822** [thedevdojo/voyager#3198]
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

On the browse view, the default bread generates a table of entries. It also adds a search and 'show x' functionality. 

Unfortunately, these features break on mobile. The cols are set to `col-md-6` rather than having a `col-xs-12` class that would make that look better. 

I just can't find where this is generated. Can someone please point me in the right direction to fix this?

thanks!

**Comment by fletch3555** [comment]
Voyager never claimed to be mobile-friendly (though we're open to PRs if anyone wants to make the effort).

Voyager uses a fallback system for views.  If a view exists using the BREAD slug (i.e. `users`), it'll use that.  If not, it will use the `bread` view.  Additionally, Laravel will check for overrides in `/resources/views/vendor` first, and fallback to the package's views.  In short, Voyager will look for a `users` `browse` view in the following order:

1. /resources/views/vendor/voyager/users/browse.blade.php
2. /vendor/tcg/voyager/resources/views/users/browse.blade.php
3. /resources/views/vendor/voyager/bread/browse.blade.php
4. /vendor/tcg/voyager/resources/views/bread/browse.blade.php

**Comment by thill0822** [comment]
Thanks for that, however, that doesn't answer my question.

I understand that Voyager doesn't claim to be mobile-friendly, however, I want to fix that for my purposes. 

The two function pieces I'm talking about don't appear to be part of the views or even the source code. It looks like it may be being added via javascript.

I just want to update the classes being added to the code, I just can't find it.
