### ISSUE TITLE
How to do multiple layer for nav bar in front-end?

### ISSUE THREAD

**Issue by adillamokhtar** [thedevdojo/voyager#3200]
- Laravel Version: 5.6
- Voyager Version: v1.1.1
- PHP Version:7.2.3
- Database Driver & Version:mySQL

### Description:
I already success to display all layer from voyager to front-end..but I have problem with the css.

![image](https://user-images.githubusercontent.com/33577143/40155383-026d548c-59c6-11e8-98f4-c515505d8f59.png)

**Comment by fletch3555** [comment]
How you do your front-end is up to you.  Voyager does not prescribe any specific solution to this problem
