### ISSUE TITLE
How to copy tables and its data from database to Git for others to use?

### ISSUE THREAD

**Issue by lohiloki** [thedevdojo/voyager#3202]
- Laravel Version: 5.6
- Voyager Version: 1.1.1
- PHP Version: 7
- Database Driver & Version: MySQL

### Description:
I am creating testing project where me and my co-worker have to work together. I created product tables and added data into my local database. Now, how I can copy tables and its data to my co-workers local database where as soon as he git pulls it, it should load to his system with all my table and its data in voyager dashboard.

I am new to Laravel and Laravel Voyager, help me out in this..

**Comment by MrCrayon** [comment]
You need to create migrations for table structure https://laravel.com/docs/5.6/migrations and seeders for data https://laravel.com/docs/5.6/seeding.
You can have a look at the source code of this project under migrations and publishable.

**Comment by fletch3555** [comment]
@MrCrayon is correct.  Voyager does not (currently) provide a method for exporting these, so you will have to do it yourself (either manually or through another package)

**Comment by lohiloki** [comment]
I am using now migration generator plugin and voyager bread generator hooks for this process. Its really tedious job and its not user friendly. I feel this is the major drawback for voyager framework.

Thanks for the reply @MrCrayon and @fletch3555.

**Comment by moazam1** [comment]
@lohiloki what migration plugin are you using?

**Comment by lohiloki** [comment]
migration generator plugin -> https://github.com/Xethron/migrations-generator
