### ISSUE TITLE
Overriding languages translation files

### ISSUE THREAD

**Issue by mina-thomas** [thedevdojo/voyager#3203]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version:
- Database Driver & Version:

### Description:
I need to override languages translation files for multiple languages

### Steps To Reproduce:
I copied files from Directory [\vendor\tcg\voyager\publishable\lang] To [\resources\lang]
my user custom view still reading translations from old vendor path

**Comment by emptynick** [comment]
This is described in the [Laravel docs](https://laravel.com/docs/5.6/localization#overriding-package-language-files)
