### ISSUE TITLE
Separating content user wise.

### ISSUE THREAD

**Issue by prdpspkt** [thedevdojo/voyager#3206]
I want to separate each user's content. So that one user cannot see content form another user. 
I want to save user_id to database when creating content and filter when bread them. 
Is there any existing idea form panel ? Or in which controller file I can Inject user_id so I can get what I want ?

Thanks 
Pradeep Sapkota

**Comment by emptynick** [comment]
This is what [Policies](https://laravel.com/docs/5.6/authorization#creating-policies) are made for.

**Comment by fletch3555** [comment]
We have an issue template for a reason, and we don't consider it optional.

Also, as @emptynick mentioned, you're looking for Laravel's Authorization system (which Policies are a component of).
