### ISSUE TITLE
JS An invalid form control with name='input_name' is not focusable.

### ISSUE THREAD

**Issue by adrhem** [thedevdojo/voyager#3209]
- Laravel Version: 5.6.2
- Voyager Version: 1.1.1

### Description:
When I use a field **Rich Text Box** in the BREAD I can't submit the form because I get the following error on Javascript Console.
`An invalid form control with name='input_name' is not focusable.`

It works if I fill the hidden input with Inspector Tool or with an script.

### Steps To Reproduce:

1. Add Rich Text Box as Field in BREAD
2. Submit even if the field is not empty

**Comment by emptynick** [comment]
This bug _should_ be fixed since `1.0.16`.
Did you recently upgrade?
If so, please republish Voyagers assets (with force-flag) and try again.

**Comment by adrhem** [comment]
I started the project this week. I'm using Translatable trait on that model if it helps. So I republished the Voyager assets and I get the same error

`An invalid form control with name='name_input' is not focusable.`

**Comment by vaggelis2018** [comment]
Same here.

**Comment by vaggelis2018** [comment]
Quick workaround is to add novalidate to the form

**Comment by farismohammed** [comment]
same problem
`An invalid form control with name='body' is not focusable.`
when using validation in posts

**Comment by jannejava** [comment]
Don't know if I am late to the party. Unfortunately, I have the same problem. The latest version, freshly published assets. Seems to happen in Chrome when TinyMCE that is required, since TinyMCE is hiding the original textarea.

The bug seems to exists. 
https://github.com/tinymce/tinymce/issues/2584.

Which workaround has been tried?

**Comment by ivanmart** [comment]
Same here, fresh update 1.1.3 => 1.1.10, publish assets with -force flag, still have `An invalid form control with name='body' is not focusable.`

**Comment by fletch3555** [comment]
I don't believe any workarounds have been tried yet.  We're open to pull requests though

**Comment by emptynick** [comment]
Can't we just remove the `required` prop?
We dont really need the browser to validate the form, we do it anyway.

**Comment by ivanmart** [comment]
to remove the `required` prop you need either to override the default view or make field NULLable in database, plus change `required` setting in the `data_rows` table

**Comment by emptynick** [comment]
I know. I mean as a "final" solution, as Voyager does not need the required prop at all.

**Comment by alizadehmammadali** [comment]
Just add `document.getElementById("richtextbody").required = false;`  to the end of  `edit-add.blade.php`  script tag and problem solved :+1: 
Here is my `edit-add.blade.php`  file
```
@section('javascript')
    <script>
        $('document').ready(function () {
            $('#slug').slugify();

        @if ($isModelTranslatable)
            $('.side-body').multilingual({"editing": true});
        @endif
        });
        document.getElementById("richtextbody").required = false;
    </script>
@stop
```
