### ISSUE TITLE
Newly created users can't go to the admin (backend) page

### ISSUE THREAD

**Issue by Hiroki111** [thedevdojo/voyager#321]
- Laravel Version: 5.3.0
- Voyager Version: 0.9
- PHP Version: 7.0.2
- Database Driver & Version: mysql Ver 14.14 Distrib 5.7.10

### Description:
I tested creating a new user from the pre-defined page.
However, this newly created user's credential (Its email address and password) leads to the front end page (i.e. welcome.blade.php), instead of the dashboard of the admin page.

I noticed that there wasn't such a folder as "/vendor/tcg/voyager/resources/views/users", unlike media and settings folders. Maybe this is to with this problem.

Could I ask for some help?

**Comment by Hiroki111** [comment]
PS
I noticed that those newly created uses didn't have "remember_token" in the users table, while the default user (whose password is admin@admin.com) has it.

**Comment by fletch3555** [comment]
This is because access to Voyager is restricted to Users with a Role that's been given the `browse_admin` Permission.  With OOTB Voyager, you can simply set the user's role to `admin` to allow access

Please note this answer is as of v0.10, which will be released this week.  Prior to v0.10, users must simply have a role of `admin`

**Comment by Hiroki111** [comment]
Thanks for your reply.
Apparently the given roles can be seen in user_roles table, but wher can the given roles be changed? 

On the edit-bread page for users, I don't see anything related to roles, so I think I'm cheking wrong pages.
Cheers

**Comment by handiwijoyo** [comment]
@Hiroki1116 `v0.9.*` doesn't has role selection on user edit. For the default role, you need to open config/voyager.php and change the `default_role` for new registered user.
