### ISSUE TITLE
Select from `data_types` on each time (VoyagerServiceProvider->registerGates)

### ISSUE THREAD

**Issue by atsimerman** [thedevdojo/voyager#3212]
- Laravel Version: 5.5.39
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:
Each request to application run query to `data_types` table - "select * from `data_types`". Why ?

### Steps To Reproduce:
Add to App\Providers\AppServiceProvider in boot function:
`DB::listen(function ($query) {
                Log::info('QUERY: ', [
                    'sql' => $query->sql,
                ]);
            });` 
Then run application. In storage/logs/laravel.log will be loged all query.

**Comment by cyrildewit** [comment]
We could cache the data types and flush it on every change. Like what Spatie does in there permission package.

I think someone already created a pr for this.

**Comment by fletch3555** [comment]
Not everyone has cache configured in their app, so we can't rely on that.

`registerGates()` is called on every request because it loads all of the data types (BREAD) in order to define and register all of the Auth policies.  This needs to be set for every request.

**Comment by atsimerman** [comment]
If you aren't working with the admin panel, you don't need that select. Maybe in future you can improve this part of package. Thanks for answers.

**Comment by fletch3555** [comment]
@atsimerman, I don't quite understand your comment. What do you mean by "if you're not working with it"?

If you mean "not using Voyager", then you're correct, but you also won't need that table, nor should the package be installed, so the query won't run at all.

If you mean "not changing Voyager's internals", then you're incorrect.  Policies are are dynamically assigned to all the BREAD types, which is a key component to how the permissions/access control system works within Voyager.  We can't hard-code the list, as BREAD can be added by users for any table, and we wish to minimize the amount of manual work required.

If you mean "user not accessing Voyager on this request", then you're partially right.  Some users want Voyager to control permissions for the entire site(like a CMS), which would require policies to be registered.  Again, we're trying to minimize the manual work required.  It won't affect your site unless you add `@can()` (or other auth calls) to explicitly check for access, which is a conscious decision.

**Comment by atsimerman** [comment]
Ok, I think, I understood your point and the purpose of this request.

**Comment by emptynick** [comment]
I think this can be closed
