### ISSUE TITLE
belongsToMany relationship fails with multiple values

### ISSUE THREAD

**Issue by Grabes** [thedevdojo/voyager#3213]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.1
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:
Creating a many-to-many relationship fails when updating model with multiple values. Error message reads:
```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'event_id' at row 1 (SQL: insert into 
`applicant_event` (`applicant_id`, `event_id`) values (2, 6,9))
```

The issue is that `sync()` expects an array with multiple values but is being sent a string, in this example `sync("6,9")`.

### Steps To Reproduce:
Create an events model, an applicants model, and a pivot table applicant_event. 
And add a belongsToMany relationship to the applicant model
When you add several events in the admin
And add multiple events as a relationship to an applicant
Then none of the events are saved as a relationship
And the page returns an error

**Comment by MrCrayon** [comment]
I didn't see anyone else complaining about this problem and it always worked for me, my guess would be it was something related to your integration. 

Anyway many released have passed so I'm closing this. 

If you are still experiencing this problem in the current release please open another issue.
