### ISSUE TITLE
How to added another input in /admin/users/create voyager?

### ISSUE THREAD

**Issue by mehdithemaker** [thedevdojo/voyager#3215]
- Laravel Version: 5.4.#
- Voyager Version: 1.1.1
- PHP Version: 7
- Database Driver & Version: Mysql 5.7.19 / HeidiSql

### Description:
I'm a big beginer with laravel and voyager 
I have already added phone_number column to my users table in my database but I want the admin to create users himself and i want him to set the phone numbers by himself 
any idea how can I added a new input in this page please? /admin/users/create voyager?

**Comment by emptynick** [comment]
Voyager overrides the users/edit-add view, thats why just adding fields through the BREAD-manager isn't enough.
You need to override the view (take [this file](https://github.com/the-control-group/voyager/blob/1.1/resources/views/users/edit-add.blade.php) as reference)
You can find a howto override views in our docs.

Also please dont use `latest` for version fields.

**Comment by mehdithemaker** [comment]
Updated
Thanks for you fast answer

**Comment by piterog** [comment]
I have the "ACTIVE" column in my user table, I have added Active form to edit user view, but when I save, nothing happens, i have the "Successfully Updated User" message, but does not save active status.. What is the my error?

**Comment by isaqueprofeta** [comment]
Same answer of this one right? #1317

In short: copy vendor/tcg/voyager/resources/views/users/edit-add.blade.php to resources/views/vendor/voyager/users/edit-add.blade.php and make the needed changes.

**Comment by emptynick** [comment]
Closing as the question is answered.
