### ISSUE TITLE
Can't reach the documentation page

### ISSUE THREAD

**Issue by foxnorth** [thedevdojo/voyager#3216]
### Description:
Can't reach the documentation page

### Steps To Reproduce:
1. Open https://laravelvoyager.com/docs/ in chrome or safari

**Comment by haffberg** [comment]
What? There are no documentation on https://laravelvoyager.com/docs/
Instead you get a copy of the start page.

**Comment by fletch3555** [comment]
We're aware of the issue and are looking into it

**Comment by Braiani** [comment]
While you guys wait for the Voyager team solve the problem, follow this link: https://voyager.readme.io/docs this is the documentation of Voyager.

**Comment by emptynick** [comment]
This problem has been solved.
