### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by huzaifa50** [thedevdojo/voyager#3217]
- Laravel Version: 5.4.36
- Voyager Version: 1.1
- PHP Version:5.6.28

**Description**
I want to change the language from English to Arabic i have changed the app.php file and put 
'locale'=>'ar'
and also the voyager.php file as shown below 
But it only changes the language on website i-e login page but as soon as you log in to admin panel in only shows English.
Is there any way i can change the admin panel language to Arabic ?

**Steps to reproduce**
'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'ar',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'ar',
        ],
    ],

**Comment by emptynick** [comment]
Yes, by setting the locale in your profile.

**Comment by huzaifa50** [comment]
Thank you, got it

**Comment by vahid-vahid** [comment]
@emptynick  tnx for your fast responses
I Have the same problem
I did every steps as mentioned above
But again some headers etc. remained En(like form labels in Setting page)
![image](https://user-images.githubusercontent.com/18301748/40587882-876a2350-61ea-11e8-9d60-fa1cbd79149c.png)

**Comment by emptynick** [comment]
Thats because those contents are not translated as of yet

**Comment by vahid-vahid** [comment]
@emptynick there were translations in publishable folder of the package for all of these...
But I don't know where are the phrases fetched from

**Comment by emptynick** [comment]
In a file called `seeders.php` which is, like I said, not translated.

**Comment by vahid-vahid** [comment]
![image](https://user-images.githubusercontent.com/18301748/40877495-03ddbcca-6697-11e8-94d0-318bb90eb12f.png)

It has been done!!

**Comment by vahid-vahid** [comment]
But not working

**Comment by emptynick** [comment]
This is definitely not the right place for those file.
Please read the Laravel docs, they tell you where to place them.

**Comment by vahid-vahid** [comment]
This is in the vendor folder of your package
I have not added anything!!
