### ISSUE TITLE
Voyager Customization

### ISSUE THREAD

**Issue by suvrodattamitu** [thedevdojo/voyager#3219]
- Laravel Version: 5.6
- Voyager Version: 1.1

### Description:  Voyager customization edit-add

Is there any changes in customization? it not works as previous persion. if any changes what steps have to follow to do customzation? its important for developers to do customzation . but i can't do that in this version. plsease help me by giving any solution of this version's customization.

**Comment by emptynick** [comment]
There are a million ways customizing Laravel and Voyager.
You have to be more specific on what you want to customize.

**Comment by suvrodattamitu** [comment]
@emptynick Customizing Views and Controllers... it not works like previous version. is there any changes.?

**Comment by emptynick** [comment]
No, there haven't been any changes.
Customizing Views is the same like before.
The only thing that changed is that the main Controller was renamed from `BreadController` to `BaseController`.
https://voyager.readme.io/docs

**Comment by suvrodattamitu** [comment]
Thanks @emptynick  you are always when we face any problem.. thank you brother,, i solved it now..
