### ISSUE TITLE
Trying to post image from multiple image.

### ISSUE THREAD

**Issue by rifuqro** [thedevdojo/voyager#3220]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version:
- Database Driver & Version:

### Description:
Hi everyone. I´m trying to post an image form de database (the type is a multiple image). 
The code I´m using to get is this. I know it´s wrong but I don´t get how to do it.

> @foreach ($products as $product)
> 		img src="{{ Voyager::image($product->pictures) }}" alt="" class="img"
> @endforeach

-----------------------------------
I got this in the page:

> <img src="http://localhost/public/storage/["Products//May2018//Y2QaEFGBngoIAVuTKWBo.jpg","Products//May2018//wkEPCz1i6bW68SJGEUJo.jpg"]" alt="" class="img">

I want to select only the first value and make disapeer this signs [""].

I´m new in this, hope yo can help me. Thanks and have a nice day.

**Comment by cyrildewit** [comment]
Because you are using the multiple image type, the images will be stored in a JSON object. To be able to acces the URLs, you will first have to decode the string with the `json_decode` function.

For example:

```blade
@foreach($products as $product)
    @php $pictures = json_decode($product->pictures); @endphp

    @if (isset($pictures[0]))
        <img src="{{ Voyager::image($pictures[0]) }}" alt="" class="img">
    @endif
@endforeach
```

**Comment by cyrildewit** [comment]
**Edit:** It looks like this is breaking Voyager.

You can also add the `pictures` attribute to the casts property on your model, to automatically cast it to an array.

```php
// Product.php
/**
 * The attributes that should be cast to native types.
 *
 * @var array
 */
protected $casts = [
    'pictures' => 'array',
];
```

Now you can access it like a normal array.

```blade
@foreach($products as $product)
    @if (isset($product->pictures[0]))
        <img src="{{ Voyager::image($product->pictures[0]) }}" alt="" class="img">
    @endif
@endforeach
```

**Comment by emptynick** [comment]
This is now in our [docs](https://docs.laravelvoyager.com/core-concepts/helper-methods).
