### ISSUE TITLE
Feature request: default column to order rows in browse view

### ISSUE THREAD

**Issue by xavibaz** [thedevdojo/voyager#3222]
- Laravel Version: 5.5.*
- Voyager Version: 1.1.*
- PHP Version: 7.2.0
- Database Driver & Version: MariaDB 5.5.

### Description:
When browsing rows of a table, the default order is the _created_at_ field or the key of that table (provided there is no order_by parameter in the request). According to this piece of code (v.1.1.1):

VoyagerBaseController.php (line 64):

```
            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'DESC';
                $dataTypeContent = call_user_func([
                    $query->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }
```

It would be nice to have an option in the BREAD editor to set the default ordering column (besides the existing order_column and order_display_column, which are for a different thing).

![image](https://user-images.githubusercontent.com/34057208/40371069-fb6843de-5de1-11e8-9ee4-3ee01dc3d449.png)

It could be stored in the _details_ field of the _data_types_ table (as the other order details are) and add an extra "elseif" in VoyagerBaseController.

### Workaround by now:

Maybe the easiest way is to modify the links in the menu to add ?order_by=field&sort_order=asc/desc...

**Comment by xciser77** [comment]
I would love this feature also. I would like to sort on a name of the data and not on the created field

**Comment by aldozorzi** [comment]
The easiest way should be adding an else if like this
`else if($model->orderBy && $model->orderDirection){
                $dataTypeContent = call_user_func([$query->orderBy($model->orderBy, $model->orderDirection), $getter]);
            }`
And then in model set
`public $orderBy = 'field';
public $orderDirection = 'ASC';`

**Comment by BernhardK91** [comment]
Upvote from me, and thank you for the workaround!
