### ISSUE TITLE
Overriding user view, doest save new fields

### ISSUE THREAD

**Issue by piterog** [thedevdojo/voyager#3223]
- Laravel Version: 5.4
- Voyager Version: 1.1.1
- PHP Version: 5.6
- Database Driver & Version: Mysql 5.7.19

### Description:
Overriding edit view does not save anymore.

### Steps To Reproduce:
In my USER table, i have thats columns:
![image](https://user-images.githubusercontent.com/6227151/40384292-79e4f788-5dd9-11e8-8fe9-2240070a8494.png)

I have override the edit.user view, and added the "active" field: Just like that:

>                             <div class="form-group">
>                                 <label for="active">Ativo</label>
>                                 <select class="form-control select2" id="active" name="active">
>                                     <option {{ ($dataTypeContent->active == 1 ? 'selected' : '')}} value="1">Sim</option>
>                                     <option {{ ($dataTypeContent->active == 0 ? 'selected' : '')}} value="0">Não</option>
>                                 </select>
>                             </div>

If i edit something like Name, or Email, and click save, everything ok! Saves well.
But when I edit 'active' state, nothing happens..

Thanks.

**Comment by emptynick** [comment]
You will need to save your data from the BREAD-Builder so that it will generate a `data_row` for each field.

**Comment by piterog** [comment]
@emptynick i'm sorry, but I think my data didn't send to controller, can I use my own controller to save my data?
