### ISSUE TITLE
Links via Table

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3226]
- Laravel Version: 5.6
- PHP Version: 7.1
- Database Driver & Version: latest

### Description:

Hi guys, i am trying to add a row in a table and when I add a link it doesn't take as it should be.
The link should be an anchor and doens't matter how i put it just don't take it.
I`ve tried with code editor, markdown editor, html, etc... it's just showing like a plain text.

**Comment by ghost** [comment]
@fletch3555

**Comment by fletch3555** [comment]
Of all the requested version numbers, Voyager is likely the MOST important.... why did you delete it?

**Comment by ghost** [comment]
I don t understand, what do you mean?

**Comment by cyrildewit** [comment]
Which version of  Voyager do you have installed?

```winbatch
composer show -i
```

**Comment by ghost** [comment]
$ composer show -i
You are using the deprecated option "installed". Only installed packages are sho                                                                             wn by default now. The --all option can be used to show all packages.
arrilot/laravel-widgets               3.12    A powerful alternative to view com                                                                             posers. Asynchronous widgets, re...
composer/ca-bundle                    1.1.1   Lets you find a path to the system                                                                              CA bundle, and includes a fallb...
composer/composer                     1.6.5   Composer helps you declare, manage                                                                              and install dependencies of PHP...
composer/semver                       1.4.2   Semver library that offers utiliti                                                                             es, version constraint parsing a...
composer/spdx-licenses                1.4.0   SPDX licenses list and validation                                                                              library.
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base directo                                                                             ry specification for php
doctrine/annotations                  v1.6.0  Docblock Annotations Parser
doctrine/cache                        v1.7.1  Caching library offering an object                                                                             -oriented API for many cache bac...
doctrine/collections                  v1.5.0  Collections Abstraction library
doctrine/common                       v2.8.1  Common Library for Doctrine projec                                                                             ts
doctrine/dbal                         v2.7.1  Database Abstraction Layer
doctrine/inflector                    v1.3.0  Common String Manipulations with r                                                                             egard to casing and singular/plu...
doctrine/instantiator                 1.1.0   A small, lightweight utility to in                                                                             stantiate objects in PHP without...
doctrine/lexer                        v1.0.1  Base library for a lexer that can                                                                              be used in Top-Down, Recursive D...
dragonmantank/cron-expression         v2.1.0  CRON for PHP: Calculate the next o                                                                             r previous run date and determin...
egulias/email-validator               2.1.4   A library for validating emails ag                                                                             ainst several RFCs
erusev/parsedown                      1.7.1   Parser for Markdown.
fideloper/proxy                       4.0.0   Set trusted proxies for Laravel
filp/whoops                           2.1.14  php error handling for cool kids
fzaninotto/faker                      v1.7.1  Faker is a PHP library that genera                                                                             tes fake data for you.
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation that                                                                              also provides common utility met...
hamcrest/hamcrest-php                 v2.0.0  This is the PHP port of Hamcrest M                                                                             atchers
intervention/image                    2.4.1   Image handling and manipulation li                                                                             brary with support for Laravel i...
jakub-onderka/php-console-color       0.1
jakub-onderka/php-console-highlighter v0.3.2
justinrainbow/json-schema             5.2.7   A library to validate a json schem                                                                             a.
larapack/doctrine-support             v0.1.6  Better Doctrine Support with Larav                                                                             el (Support for `enum`)
larapack/hooks                        v1.0.8  A Laravel Hook system
larapack/voyager-hooks                v1.0.8  Hooks integrated in Voyager
laravel/framework                     v5.6.22 The Laravel Framework.
laravel/tinker                        v1.0.7  Powerful REPL for the Laravel fram                                                                             ework.
league/flysystem                      1.0.45  Filesystem abstraction: Many files                                                                             ystems, one API.
mockery/mockery                       1.1.0   Mockery is a simple yet flexible P                                                                             HP mock object framework
monolog/monolog                       1.23.0  Sends your logs to files, sockets,                                                                              inboxes, databases and various ...
myclabs/deep-copy                     1.7.0   Create deep copies (clones) of you                                                                             r objects
nesbot/carbon                         1.25.0  A simple API extension for DateTim                                                                             e.
nikic/php-parser                      v4.0.1  A PHP parser written in PHP
nunomaduro/collision                  v2.0.2  Cli error handling for console/com                                                                             mand-line PHP applications.
paragonie/random_compat               v2.0.12 PHP 5.x polyfill for random_bytes(                                                                             ) and random_int() from PHP 7
phar-io/manifest                      1.0.1   Component for reading phar.io mani                                                                             fest information from a PHP Arch...
phar-io/version                       1.0.1   Library for handling version infor                                                                             mation and constraints
phpdocumentor/reflection-common       1.0.1   Common reflection classes used by                                                                              phpdocumentor to reflect the cod...
phpdocumentor/reflection-docblock     4.3.0   With this component, a library can                                                                              provide support for annotations...
phpdocumentor/type-resolver           0.4.0
phpspec/prophecy                      1.7.6   Highly opinionated mocking framewo                                                                             rk for PHP 5.3+
phpunit/php-code-coverage             6.0.4   Library that provides collection,                                                                              processing, and rendering functi...
phpunit/php-file-iterator             1.4.5   FilterIterator implementation that                                                                              filters files based on a list o...
phpunit/php-text-template             1.2.1   Simple template engine.
phpunit/php-timer                     2.0.0   Utility class for timing
phpunit/php-token-stream              3.0.0   Wrapper around PHP's tokenizer ext                                                                             ension.
phpunit/phpunit                       7.1.5   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          6.1.1   Mock Object library for PHPUnit
psr/container                         1.0.0   Common Container Interface (PHP FI                                                                             G PSR-11)
psr/http-message                      1.0.1   Common interface for HTTP messages
psr/log                               1.0.2   Common interface for logging libra                                                                             ries
psr/simple-cache                      1.0.1   Common interfaces for simple cachi                                                                             ng
psy/psysh                             v0.9.4  An interactive shell for modern PH                                                                             P.
ramsey/uuid                           3.7.3   Formerly rhumsaa/uuid. A PHP 5.4+                                                                              library for generating RFC 4122 ...
sebastian/code-unit-reverse-lookup    1.0.1   Looks up which function or method                                                                              a line of code belongs to
sebastian/comparator                  3.0.0   Provides the functionality to comp                                                                             are PHP values for equality
sebastian/diff                        3.0.0   Diff implementation
sebastian/environment                 3.1.0   Provides functionality to handle H                                                                             HVM/PHP environments
sebastian/exporter                    3.1.0   Provides the functionality to expo                                                                             rt PHP variables for visualization
sebastian/global-state                2.0.0   Snapshotting of global state
sebastian/object-enumerator           3.0.3   Traverses array structures and obj                                                                             ect graphs to enumerate all refe...
sebastian/object-reflector            1.1.1   Allows reflection of object attrib                                                                             utes, including inherited and no...
sebastian/recursion-context           3.0.0   Provides functionality to recursiv                                                                             ely process PHP variables
sebastian/resource-operations         1.0.0   Provides a list of PHP built-in fu                                                                             nctions that operate on resources
sebastian/version                     2.0.1   Library that helps with managing t                                                                             he version number of Git-hosted ...
seld/cli-prompt                       1.0.3   Allows you to prompt for user inpu                                                                             t on the command line, and optio...
seld/jsonlint                         1.7.1   JSON Linter
seld/phar-utils                       1.0.1   PHAR file format utilities, for wh                                                                             en PHP phars you up
swiftmailer/swiftmailer               v6.0.2  Swiftmailer, free feature-rich PHP                                                                              mailer
symfony/console                       v4.0.10 Symfony Console Component
symfony/css-selector                  v4.0.10 Symfony CssSelector Component
symfony/debug                         v4.0.10 Symfony Debug Component
symfony/event-dispatcher              v4.0.10 Symfony EventDispatcher Component
symfony/filesystem                    v4.0.10 Symfony Filesystem Component
symfony/finder                        v4.0.10 Symfony Finder Component
symfony/http-foundation               v4.0.10 Symfony HttpFoundation Component
symfony/http-kernel                   v4.0.10 Symfony HttpKernel Component
symfony/polyfill-ctype                v1.8.0  Symfony polyfill for ctype functio                                                                             ns
symfony/polyfill-mbstring             v1.8.0  Symfony polyfill for the Mbstring                                                                              extension
symfony/polyfill-php72                v1.8.0  Symfony polyfill backporting some                                                                              PHP 7.2+ features to lower PHP v...
symfony/process                       v4.0.10 Symfony Process Component
symfony/routing                       v4.0.10 Symfony Routing Component
symfony/translation                   v4.0.10 Symfony Translation Component
symfony/var-dumper                    v4.0.10 Symfony mechanism for exploring an                                                                             d dumping PHP variables
tcg/voyager                           v1.1.1  A Laravel Admin Package for The Co                                                                             ntrol Group to make your life ea...
theseer/tokenizer                     1.1.0   A small library for converting tok                                                                             enized PHP source code into XML ...
tijsverkoyen/css-to-inline-styles     2.2.1   CssToInlineStyles is a class that                                                                              enables you to convert HTML-page...
vlucas/phpdotenv                      v2.4.0  Loads environment variables from `                                                                             .env` to `getenv()`, `$_ENV` and...
webmozart/assert                      1.3.0   Assertions to validate method inpu                                                                             t/output with nice error messages.

**Comment by emptynick** [comment]
I dont really understand your problem, but I'm pretty positive you will find the solution [here](https://laravel.com/docs/5.6/blade)

**Comment by ghost** [comment]
my issue here ->>>> https://youtu.be/DqSa1vHaTjI

**Comment by ghost** [comment]
@cyrildewit @emptynick @fletch3555  anyone can help me now?

**Comment by emptynick** [comment]
Yes, this is expected behaviour, and I guess it wont change.
Imagine someone puts an iframe or video-tag inside the body.

**Comment by ghost** [comment]
Ok, so how do I modify this to work, for my personal use only ?

**Comment by emptynick** [comment]
Override `bread/browse.blade.php` with a copy of the original and replace `{{  }}` with `{!! !!}` but be careful!

**Comment by emptynick** [comment]
Closing as this is expected behaviour.
Imagine everyone putting headings, iframe and things like this inside there and it would render as HTML when browsing
