### ISSUE TITLE
Security breaches on Voyager Compass

### ISSUE THREAD

**Issue by Ric0sM** [thedevdojo/voyager#3227]
Hi all,

I'm opening this new issue because during a pentest for a customer using Voyager to administrate his Laravel backend, we found two security breaches on Voyager Compass tool.

The first security breach is in Command menu, used normally to execute Laravel commands. But when we put system commands on arguments (example : && cat /etc/passwd), this one is sucessfully executed and send the return in the web page. So, an attacker can take control of server if he has an access to backend. This security breach has a major criticity and CVSS score estimate to 7,2. To mitigate this vulnerability, special characters must be sanitized.

The second security breach is in the Log review menu. It is possible to download or delete system files if the user has system rights. Normally, it is possible to download or delete the log files from the URL https://mywebiste.com/admin/compass?download=bGFyYXZlbC5sb2c=. However, if we decode base64, we get the cleartext laravel.log. If you change the download parameter by an another name file encoded in base64 (for example /etc/passwd => L2V0Yy9wYXNzd2Q=), it is possible to download the file concerned. Similarly, it is possible to delete files using the URL https://mywebiste.com/admin/compass?del=bGFyYXZlbC5sb2c=. This vulnerability has a moderate criticity and a CVSS score estimate to 6,0. To mitigate this one, we recommend restricting access to certain types of log files.

Can you take a look at these problems that we have raised ?

If you need some details, we are at your disposal.

Kind regards.

Ricardo & Margot

**Comment by MrCrayon** [comment]
Compass part is duplicate of #3032.
I think the deleting part is worrysome if there is no warning before deleting (didn't check it yet).
Anyway I think they will consider a PR.

**Comment by jannejava** [comment]
An option to turn this off completely, would it be useful?

**Comment by emptynick** [comment]
I dont think so.
The permission ( [see here](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerCompassController.php#L24) ) does the same.

**Comment by jannejava** [comment]
Thanks, missed that one, good to know!

Made a small patch to escape the arguments, see if you like it.

**Comment by emptynick** [comment]
Starting from 1.2.0 the compass will be automatically disabled when the app is not running `local` (https://github.com/the-control-group/voyager/pull/3823).
This option _can_ be overriden by a config-var tho.
I'm going to close this one. Feel free to let us know if this is not satisfying or if there are other problems.
