### ISSUE TITLE
Error user index [admin view]

### ISSUE THREAD

**Issue by piterog** [thedevdojo/voyager#3229]
- Laravel Version: 5.4
- Voyager Version: 1.1
- PHP Version: 5.6
- Database Driver & Version: MySql

### Description:
I have overriding the USER view and USER CONTROLLER
Now when I enter in /admin/users, I have the BREAD index page
![image](https://user-images.githubusercontent.com/6227151/40516509-4121a018-5f87-11e8-92de-5ce5b45dabf0.png)
instead USER INDEX

### Steps To Reproduce:
-- CONTROLLER:
**COPY** _\vendor\tcg\voyager\src\Http\Controllers\VoyagerBreadController.php_ **to** _\app\Http\Controllers\Voyager\UsersController.php_

-- VIEW:
**COPY** _\vendor\tcg\voyager\resources\views\users\edit-add.blade.php_ **to** _\resources\views\vendor\voyager\users\edit-add.blade.php_

Edit **User Bread** to:
![image](https://user-images.githubusercontent.com/6227151/40516873-0c20fdc6-5f89-11e8-9f5b-cc39e950f2fb.png)

I've made some modifications in UsersController.php:

```
<?php
namespace App\Http\Controllers\Voyager;

use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use TCG\Voyager\Database\Schema\Column;
use TCG\Voyager\Database\Schema\SchemaManager;
use TCG\Voyager\Database\Schema\Table;
use TCG\Voyager\Database\Types\Type;
use TCG\Voyager\Events\BreadAdded;
use TCG\Voyager\Events\BreadDeleted;
use TCG\Voyager\Events\BreadUpdated;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Models\DataRow;
use TCG\Voyager\Models\DataType;
use TCG\Voyager\Models\Permission;
use TCG\Voyager\Http\Controllers\VoyagerBreadController;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;

class UsersController extends VoyagerBreadController
{
    public function index()
    {
        Voyager::canOrFail('browse_bread');

        $dataTypes = Voyager::model('DataType')->select('id', 'name', 'slug')->get()->keyBy('name')-toArray();

        $tables = array_map(function ($table) use ($dataTypes) {
            $table = [
                'name'       => $table,
                 'slug'       => isset($dataTypes[$table]['slug']) ? $dataTypes[$table]['slug'] : null,
                'dataTypeId' => isset($dataTypes[$table]['id']) ? $dataTypes[$table]['id'] : null,
            ];

            return (object) $table;
        }, SchemaManager::listTableNames());
        //return Voyager::view('voyager::tools.bread.index')->with(compact('dataTypes', 'tables'));
        return Voyager::view('voyager::tools.bread.index')->with(compact('dataTypes', 'tables'));
    }
........
```

**Comment by emptynick** [comment]
I dont really wonder that you get **BREAD** actions when overriding with a copy of Voyager**BREAD**Controller
I guess you might want to use the [VoyagerBaseController](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerBaseController.php) ?
