### ISSUE TITLE
Remove last value on belongsToMany relationship

### ISSUE THREAD

**Issue by zedsh** [thedevdojo/voyager#3230]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.1
- PHP Version: 7.0
- Database Driver & Version: mysqli / mysqlnd 5.0.12-dev

### Description:
If you delete all values from the belongToMany field, one of them is not deleted.

### Steps To Reproduce:
Create BelongsToMany Relationship in some Bread.
Add two relations in this entity, save.
Open it, remove relations. Save.
One relations don't removed.

### Cause

vendor/tcg/voyager/src/Http/Controllers/Controller.php, line 62.
`
 if ((isset($options->type) && $options->type !== 'belongsToMany') || $row->field !== 'user_belongsto_role_relationship') `

Because of the second part of the expression, the condition is always true.
remove this
`
 $row->field !== 'user_belongsto_role_relationship'`
from condition - relations work fine.

WTF is this condition here?

**Comment by vblinden** [comment]
#3112

**Comment by emptynick** [comment]
Its an "emergency-fix" otherwise Voyager would break when submitting your user-profile.
Also please watch your words - thats unnecessary

**Comment by zedsh** [comment]
This emergency fix make a big bug.

**Comment by emptynick** [comment]
A smaller bug than the fact that Voyager would break without it.
Also, as @vblinden mentioned, there's a PR waiting to be merged, which completely fixes it

**Comment by emptynick** [comment]
Fixed in #3016.
Merged into 1.x
