### ISSUE TITLE
Can't upload images in ContentTypes Images

### ISSUE THREAD

**Issue by vittm** [thedevdojo/voyager#3231]
- Laravel Version:  5.6
- Voyager Version: v1.1
- PHP Version: 7.2.5
- Database Driver & Version: 4.8.1

### Description:
Although I saw notification success but the images not upload in folder and database, the URL is null and that not upload images in the stogare. When i debug in Controle => ContentTypes => Images then `if ($this->request->hasFile($this->row->field)) ` return result Fasle. I'm use echo `$this->row->field` then result 'image'

### Steps To Reproduce:
![capture](https://user-images.githubusercontent.com/15723750/40537416-0f92529c-6039-11e8-8df5-8eca757ce3ae.PNG)
![capture](https://user-images.githubusercontent.com/15723750/40539222-3288894c-603e-11e8-9145-e51c247fb970.PNG)

**Comment by MrCrayon** [comment]
I didn't see any other report about this, so maybe it was a configuration problem.

Anyway since it reference an old Voyager version I'm closing this one but feel free to open another issue if you are still experiencing this problem after update.
