### ISSUE TITLE
voyager multilingual doesn't work!

### ISSUE THREAD

**Issue by lyongdee** [thedevdojo/voyager#3232]
- Laravel Version: 5.4.36
- Voyager Version: 1.1.1
- PHP Version: 5.6.19
- Database Driver & Version: MySQL 5.6

### Description:
I set voyager's multilingual is 'zh_CN' but the page still be 'en'.
1、app.php
...
'locale' => 'zh_CN'
...

2、voyager.php
    'multilingual' => [
        'enabled' => true,
        'rtl' => false,
        'default' => 'zh_CN',
        'locales' => [
            'zh_CN',
            'en',
        ],
    ],

3、login and media lang
Except the [login](http://127.0.0.1:8000/admin/login) lang is OK.
![login](https://user-images.githubusercontent.com/369124/40538289-e58468c2-6043-11e8-9916-92e7c35381d8.png)

![media](https://user-images.githubusercontent.com/369124/40538297-ec091454-6043-11e8-91d9-a9ccadc2a828.png)

**Comment by emptynick** [comment]
Set the locale on your user-profile.

**Comment by lyongdee** [comment]
Thank you @emptynick, got it.
