### ISSUE TITLE
Renaming default admin menu hides the menu

### ISSUE THREAD

**Issue by jampack** [thedevdojo/voyager#3234]
- Laravel Version: 5.6.21
- Voyager Version: 1.1
- PHP Version: 7.2
- Database Driver & Version: NA

### Description:
Renaming the default menu for admin to something like voyager_admin hides the whole menu, just mentioning this because if anyone face this issue then just go to database itself and rename it back to admin, i only tried to re-login didn't cleared cache or anything so it might not be a major issue but just for information if anyone come across it.

### Steps To Reproduce:
On default voyager installation go to menu builder and rename the "admin" menu to anything and it will hide all the content in left nav

**Comment by fletch3555** [comment]
This is expected behavior, as the menus are referenced by name.  I strongly suggest NOT changing the admin menu's name for precisely that reason.
