### ISSUE TITLE
[Featured] How to add BREAD to Extend Model?

### ISSUE THREAD

**Issue by hungxinh** [thedevdojo/voyager#3235]
- Laravel Version: 5.6.X
- Voyager Version: 1.1 -> 1.1.1
- PHP Version: 7.1
- Database Driver & Version: 

### Description:
class **ProductCategory** extends Category {
   protected $table = 'categories';
   public static function boot(){
        parent::boot();
        static::addGlobalScope(function ($query) {
            $query->where('type', 'PRODUCT');
        });
    }
   public function save(array $options = []){
      if (!$this->type) { $this->type = 'PRODUCT'; }
      parent::save();
    }
   // ...
}

**## How can i add BREAD to ProductCategory model from menu /admin/database ?**

I add it manually in the database (data_types, data_rows, permissions, permission_role).
It work fine, let see:
![screenshot 2018-05-25 21 44 09-share0](https://user-images.githubusercontent.com/23396671/40551967-938f3338-6068-11e8-88d0-9561a6877091.png)
![screenshot 2018-05-25 21 37 11-share1](https://user-images.githubusercontent.com/23396671/40551969-968486b0-6068-11e8-9951-7c0d9b1bd5ae.png)
![screenshot 2018-05-25 21 39 04-share2](https://user-images.githubusercontent.com/23396671/40551977-9b18cbf0-6068-11e8-8cff-3a17bb432a42.png)

**## How can i add BREAD to ProductCategory model from menu /admin/database ?**

**Comment by fletch3555** [comment]
BREAD is added to tables, not models.  BREAD *uses* models, but cannot be created against them.

In short, what you're asking is not currently possible (through the UI at least.  There may be some way to hack it, but we can't walk you though that)
