### ISSUE TITLE
Bug report with default images

### ISSUE THREAD

**Issue by mavrickdeveloper** [thedevdojo/voyager#3236]
- Laravel Version: 5.6
- Voyager Version: 1.1.1
- PHP Version: 7.1
- Database Driver & Version:

### Description:
it seems that there is a bug in changing the admin loader & admin icon & admin background
voyager somehow switch to default voyager images and don't remember the user settings

### Steps To Reproduce:
1- try to upload an images to admin logo & loader & admin background
2 - save
3 - refresh the page
4 - don't change anything
5 - click save again

it seems voyager somehow switch to the default images

**Comment by fletch3555** [comment]
There is currently an issue with saving settings.  Check the open issues.
