### ISSUE TITLE
ManyToMany relationship delete error

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#3237]
- Laravel Version: 5.5.*
- Voyager Version: 1.1
- PHP Version: 7.2

### Description:

I have created manytomany relationship with pivot table. And it works as i expected. But when i try to remove, it brings the error. I check all voyager issues but can't find any solution. I hope you guys help me and others. i have projects table and project_categories table. Also my pivot table is category_product.
It has 2 column. "project_id" and "project_category_id". When i try to remove a line. This error is returning. Thanks in advance.

`SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`my_db`.`category_product`, CONSTRAINT `category_product_project_id_foreign` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)) (SQL: delete from `projects` where `id` = 3)`

**Comment by aozen** [comment]
I found the solution finally. In pivot table i changed project_id and project_category_id as CASCADE. It works now.

**Comment by franciscohanna92** [comment]
@aozen Where do you do this?

> changed project_id and project_category_id as CASCADE

I can't find that option in the database editor, nor the BREAD editor

**Comment by aozen** [comment]
For phpmyadmin, in the structure: there is relation view button. Here is cascade options. But you can also make this using migrate. 
`$table->unsignedInteger('user_id')->nullable()->default(null)->index();
$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');`

**Comment by franciscohanna92** [comment]
@aozen Yes, I changed it trough MySQL Workbench. I thought that this could be done trough Voyager's database editor
