### ISSUE TITLE
Language selector not showing! in new BREAD

### ISSUE THREAD

**Issue by almokhtarbr** [thedevdojo/voyager#3238]
Laravel Version: 5.6
Voyager Version: v1.1
PHP Version: 7.2.5
Database Driver & Version: 4.8.1

## Description 
 i have problem when i add my bread for "books" the language  selector dont showing but he work in posts BREAD

https://drive.google.com/open?id=1qdXodQQyN2fey-w9M0PIROJbzsoa-g8r
https://drive.google.com/open?id=1U5DTLpUsNKUG8aGmE3sZOZ9qaS3k_GpO

**Comment by emptynick** [comment]
The issue template is required when opening an issue.
Especially helpful is the `steps to reproduce` part, because we need to know what you did already to activate translations for your model.

**Comment by Eptech-Danish** [comment]
Hi i have same issue kindly guide how to resolve! 
 The issue is when I create new bread the language selector does not show on add create update... 
Some how default breads (post, pages, categories) language selector are working fine!

@emptynick
