### ISSUE TITLE
video and mp3 ?

### ISSUE THREAD

**Issue by loaiabdalslam** [thedevdojo/voyager#3239]
- Laravel Version: latest version
- Voyager Version: latest version
- PHP Version: latest version 
- Database Driver & Version: mysql latest version

### Description:
i need to upload audio mp3 and video with any type i cant upload any short video or largeone , this is make this error for me

fopen(C:\xampp\htdocs\broker\public): failed to open stream: Permission denied

i try alot but when i try to upload photo it's worked why? and how can i solve it?!

\

**Comment by loaiabdalslam** [comment]
I want to upload mp3 audio files to my site but there is a problem I can not use the mp3 type for upload , not like a file , on click download it , no i want it to be a file preview .. like video playing when i go to its link

**Comment by fletch3555** [comment]
"Latest version" isn't valid. Also, we need more information about the error: stack trace, steps to reproduce, etc.  There's a reason we have the issue template, please use it.

This issue can be reopened when you update it with the necessary information.
