### ISSUE TITLE
Can log into Voyager, but cannot access several routes

### ISSUE THREAD

**Issue by 54656452** [thedevdojo/voyager#324]
- Laravel Version: 5.3.26
- Voyager Version: 0.9.34
- PHP Version: 7.0.8-0ubuntu0.16.04.3
- Database Driver & Version: MySQL

### Description:
On a fresh install I am able to log into at site.com/admin using the default credentials, however /admin/roles, /admin/users, /admin/posts/, /admin/pages, /admin/categories, and /admin/menus are not accessible with NotFoundHttpException in RouteCollection.php line 161 while /admin/settings, /admin/database, and /admin/media function fine.

### Steps To Reproduce:
1. Complete fresh install according to documentation

**Comment by handiwijoyo** [comment]
@54656452 Did you using `.env` file? This issue has been fixed in upcoming `v0.10`

**Comment by craigharman** [comment]
All pages seem to give a NotFoundHTTPException since this commit on v0.10: https://github.com/the-control-group/voyager/blame/efd2db3eac6675bdea0b37649872b3329d317f51/publishable/routes/voyager.php#L13

(No longer an admin prefix in the route)

**Comment by marktopper** [comment]
Whats the output of the command `php artisan route:list`.

**Comment by craigharman** [comment]
+--------+----------+----------+------+---------+--------------+
| Domain | Method   | URI      | Name | Action  | Middleware   |
+--------+----------+----------+------+---------+--------------+
|        | GET|HEAD | /        |      | Closure | web          |
|        | GET|HEAD | api/user |      | Closure | api,auth:api |
+--------+----------+----------+------+---------+--------------+

**Comment by craigharman** [comment]
re-running: php artisan voyager:install did the trick.

**Comment by marktopper** [comment]
For others with same issue, this is because that you now how to add the following piece of code into your `routes/web.php`:

```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```

It's however automatically done when running `php artisan voyager:install`.

**Comment by 54656452** [comment]
@marktopper Unfortunately in my case re-running `php artisan voyager:install` did not change anything. Additionally, when adding the codeblock to `routes/web.php` I recieve the following error:

```
FatalThrowableError in web.php line 23:
Call to undefined method TCG\Voyager\Voyager::routes()
```

The necessary entry has been made inside `config/app.php`

```
         ...

         /*
         * Package Service Providers...
         */

        TCG\Voyager\VoyagerServiceProvider::class,

         /*
         * Application Service Providers...
         */
         ...
```
The output from running php artisan voyager:install:
```
root@monroeco:/var/www/html/monroecoproject# php artisan voyager:install
Generating the default authentication scaffolding
Publishing the Voyager assets, database, and config files
Migrating the database tables into your application
Dumping the autoloaded files and reloading all new files
Seeding data into the database
Adding the storage symlink to your public folder
Successfully installed Voyager! Enjoy :)
```

Is there a specific namespace that needs a `use` line in my routes file?

**Comment by marktopper** [comment]
Hey @54656452, the issue that @craigharman had was with the alpha `v0.10` version. You are on the `v0.9` version. I recommend upgrading to `v0.10` since a lot of issues and new features have been made, however soon there will be a migration guide to help you upgrade, but if this is a new project I recommend just starting over.

**Comment by 54656452** [comment]
@marktopper so then my understanding is that I shouldn't be seeing this issue on 0.9.4 anyways? I'll try spinning up a fresh Laravel install and pull dev-master through composer to see if that gets me up and running.

**Comment by marktopper** [comment]
The error should have been fixed in `dev-master` but also in the next version `dev-release/v0.10`.

If not please let me know, then I will reopen this issue.
