### ISSUE TITLE
Thows Error when proute prefix is changed from admin to anything else.

### ISSUE THREAD

**Issue by rahat1994** [thedevdojo/voyager#3248]
- Laravel Version: **5.6**
- Voyager Version: **1.1**
- PHP Version:**7.1**
- Database Driver & Version: Mysql 5

### Description:
When I change the prefix of the route group in web.php and then I try to login to the dashboard it redirects me to admin. Which throws an error.

**default:**

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

**My Version:**
Route::group(['prefix' => 'welcomeadmin'], function () {
    Voyager::routes();
});
 
Can anyone please tell me where I am going wrong.

**Comment by emptynick** [comment]
Are you going to tell us which error it throws?
I guess its a "Not found exception".
Then you missed changing this value: https://github.com/the-control-group/voyager/blob/1.1/publishable/config/voyager.php#L22

**Comment by rahat1994** [comment]
Yeah...I changed those files in my laravel vendor folder.. !!!... But now I changed it in my main config now it works. Thanks for the response.

But the Doc doesn't indicate anything about this procedure.........!!!

**Comment by fletch3555** [comment]
Don't every change anything under vendor... rule to live by with Laravel.

When the docs tell you to change something, it will NEVER mean a file under vendor.
