### ISSUE TITLE
How can I let login possibility from voyager login page only for users who have admin role ?

### ISSUE THREAD

**Issue by mehdithemaker** [thedevdojo/voyager#3261]
- Laravel Version: 5.4
- Voyager Version: 1.1.
- PHP Version: 7
- Database Driver & Version: HeidiSql MYsql

### Description:
I have noticed that users with normal privilege can login from voyager admin page I want to make login possible only for admin role users how can I do that please sorry for my english.

**Comment by emptynick** [comment]
Just dont grant `Browse Admin` permission to `user` role.

**Comment by mehdithemaker** [comment]
Sorry i'm kinda beginer where should I do that ? in voyager admin/users?

**Comment by almokhtarbr** [comment]
@emptynick  say  Just dont grant Browse Admin permission to user role it mean remove checked from 
Browse Admin like this picture 
https://qph.fs.quoracdn.net/main-qimg-f87cfe418a8486e2abf5756c2725dc7f

**Comment by mehdithemaker** [comment]
I see guys thanks for your help but I think their is a misunderstanding.
I actually noticed that a normal role user can log from voyager/admin/login and I don't want him to do that from here their is a /login page in my website 
So I want to only a user with admin role who can log from voyager/admin/login 
sorry for my bad english I  hope someone understand me

**Comment by almokhtarbr** [comment]
@mehdithemaker xof had video https://youtu.be/9D4Yp5H25KQ

**Comment by emptynick** [comment]
They can login, yes, but they cant access Voyager at all and will be redirected "away" from Voyager

**Comment by mehdithemaker** [comment]
@almokhtarbr l3eez 
@emptynick  yes that's the problem they can login and I don't want that because I have added nexmo for security and when you log from voyager page nexmo doesn't verify who's login

**Comment by MrCrayon** [comment]
@mehdithemaker you can extend  VoyagerAuthController and do something like this:
```php
class VoyagerNewAuthController extends VoyagerAuthController
{

    public function postLogin(Request $request)
    {
        $response = parent::postLogin($request);

        //Only admin users can log in with admin form
        if (!$this->guard()->user()->isAdmin()) {
            Auth::logout();

            return $this->sendFailedLoginResponse($request);
        }
        return $response;
    }
}
```
You need to create isAdmin() method in your User class and set the new route.

This is only to prevent the use of admin/login it's still up to you to check rights to access pages.

**Comment by fletch3555** [comment]
Just some alternative options:

- You can create a [custom guard](https://laravel.com/docs/5.6/authentication#adding-custom-guards) and use that.
- Voyager uses the default guard, so you could make your normal site use a different guard (something specific to nexmo).
- You could override the [VoyagerAuthController](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerAuthController.php#L38) and change the logic or guard used.  If you choose to override the controller, please do so this way instead of how @MrCrayon suggested.  Doing it that way will log your user in then back out, which is bound to eventually cause trouble.

**Comment by emptynick** [comment]
Closing as some suggestions were provided.

**Comment by ghost** [comment]
Hello All, I'm quite new so forgive me if I don't follow the right process but I don't understand why this was closed with the suggestion and not addressed. I just noticed this problem today and even if user won't be able to access the admin it makes much more sense that user is redirected back with error. I don't want users using my admin page to login their user pages. Also that workaround is not very beginner friendly. Thanks in advance for the hard work. :)
