### ISSUE TITLE
Permission does not exist - 400

### ISSUE THREAD

**Issue by PointfullDevelopers** [thedevdojo/voyager#3272]
- Laravel Version: 5.5
- Voyager Version: ^1.0

### Description:
Everything was working perfectly. All of sudden when I try to edit a Bread I get this message. Everything I've found doesn't work

### Steps To Reproduce:
Go to Voyager and add a new table, then click to add bread to the table

**Comment by cyrildewit** [comment]
Could you post the whole error message?

And `"tcg/voyager": "^1.0"` can be three versions: `v1.0.0`, `v1.1.1` and `v1.1.2`. Please update the version number with the one found by executing `composer show tcg/voyager`. The same goes with the Laravel version number.

Thanks!

**Comment by fletch3555** [comment]
> Everything was working perfectly.

If this was the case, and is no longer the case, then something changed.

> All of sudden

Doubtful.  What did you change right before this appeared?

> Everything I've found doesn't work

I'm sorry the prehistoric fossils didn't make the sun revolve around the mood.  Seriously, you need to provide details of what you've tried or we're not going to be able to help.

Please feel free to reopen the issue when you've updated the version numbers and provided MUCH more detail about your issue.
