### ISSUE TITLE
How to deal with published files that I modified when Migrating from v1.1.0 to v1.1.2

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#3276]
- Laravel Version: 5.6
- Voyager Version: 1.1.2

### Description:
There are some published files that I've modified after publishing it. now after comparison between v1.1.0 and v1.1.2 there are some modifications (Not related with my modifications) on those files. what to do ? should I make those modifications manually or force publishing files and make my modifications again ? 
here are the files that have been modified by the releases :
https://github.com/the-control-group/voyager/pull/3085/files
https://github.com/the-control-group/voyager/pull/3122/files
https://github.com/the-control-group/voyager/pull/3192/files

**Comment by fletch3555** [comment]
How you handle that is up to you.  Either are valid options, depending on how many/what kind of changes you've made.

**Comment by donmbelembe** [comment]
so  when I run `composer update` i should be careful with changes ?

**Comment by fletch3555** [comment]
Yes, if you make changes in published files, you will need to remain cognizant of those changes when updating
