### ISSUE TITLE
Guide to the installation

### ISSUE THREAD

**Issue by krehak** [thedevdojo/voyager#3283]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: 10.1.13-MariaDB

### Description:
I'm completely new to laravel and I wanted to start with already created administration, but when I try so, then I get this message:
`Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table 'users' add unique 'users_email_unique'('email'))`

I tried it on completely clean install...

### Steps To Reproduce:
1. created a new folder, opened command line and...
2. `laravel new`
3. changed settings in `env` file according to my database
4. `composer require tcg/voyager`
5. `php artisan voyager:install --with-dummy`
6. `Syntax error or access violation: 1071...`

**Comment by emptynick** [comment]
Please read our [README](https://github.com/the-control-group/voyager/blob/1.1/README.md)
There's a solution for your problem.

**Comment by debute** [comment]
Can you be more specific? Because I literally followed installation steps.

I just edited my issue, because I forget to mention that I used `composer require tcg/voyager`

**Comment by krehak** [comment]
I have put

```
public function boot()
{
    Schema::defaultStringLength(191);
}
```

into `/database/migrations/2014_10_12_000000_create_users_table.php` but same problem. As I said, I'm new to laravel, I never tried it before, but I want to start learn it with administration, that's why I'm here. So, where do I have to put that method?

**Comment by rahat1994** [comment]
Hey Debute,

This is a very common problem for new laravel developers.

go to-> app/Providers.

and replace the appserviceprovider.php.


```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

**Comment by krehak** [comment]
It works now, thanks!
