### ISSUE TITLE
Remove the extra curly braces {{!! ... !!}}

### ISSUE THREAD

**Issue by rhoni** [thedevdojo/voyager#3285]
- Laravel Version: 5.5.*
- Voyager Version: 1.1.0
- PHP Version: 7.1
- Database Driver & Version: *

### Description:
Please, remove the extra curly braces in `\tcg\voyager\resources\views\posts\edit-add.blade.php`

`{{!! isFieldSlugAutoGenerator($dataType, $dataTypeContent, "slug") !!}}`

**Comment by marijnz0r** [comment]
You could help the community out and create a pull request: https://github.com/the-control-group/voyager/pulls

**Comment by SteamWind** [comment]
https://opensource.guide/how-to-contribute/#opening-a-pull-request
