### ISSUE TITLE
Settings not updating.

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#3291]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.2.5
- Database Driver & Version: MariaDB

### Description:
I wanted to write about the logo image which is not saved in settings. After some search i found some related isssues which was referencing that the issue has been fixed. I made a composer update to and tried to check if the issue has been fixed but now i get this error: 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'site.title' for key 'settings_key_unique' (SQL: update `settings` set `key` = site.title, `group` = Site where `id` = 6)

**Comment by SteamWind** [comment]
You tried to change the group of the admin.title to site.title?
I reproduced your error by doing this...

**Comment by vaggelis2018** [comment]
No but i found that a new group without name created. A group named general but without prefix in setting(). After i deleted it everything worked fine.
