### ISSUE TITLE
Bread edit error message 

### ISSUE THREAD

**Issue by YounessTayer** [thedevdojo/voyager#3294]
- Laravel Version: 5.6
- Voyager Version: 1.1.2
- PHP Version: 7.0
- Database Driver & Version: mysql  5.0.12

### Description:
Hi everybody,
I got the following error message when trying to read a bread I just created for my table : 
"Undefined variable: model_name (View: /var/www/voyager.dom/web/vendor/tcg/voyager/resources/views/tools/bread/edit-add.blade.php)".
What I have to define as model_name?

In advance, thank you.

**Comment by marktopper** [comment]
Please enter the `Steps To Reproduce` and share your BREAD settings for that table.

**Comment by tyndouf** [comment]
I followed step by step the video tutorial. Now I have a "This action is unauthorized." error message when I try to open my themes BREAD from a left side menu I have created. this happens even after have been set the access roles to this BREAD for a both normal and admin users.
Any idea from what this error comes?

**Comment by newelement** [comment]
I'm having this same issue

**Comment by imprayas** [comment]
Same issue:
Undefined variable: model_name (View: /vendor/tcg/voyager/resources/views/tools/bread/edit-add.blade.php)

**Comment by prayas-sapkota** [comment]
Having same issue while creating bread without model.
Undefined variable: model_name

**Comment by emptynick** [comment]
"Without model" is the problem

**Comment by prayas-sapkota** [comment]
If I create table with model there is also an issue while creating relationship.

The relationship is not showing on dropdown.

**Comment by emptynick** [comment]
That's not the topic of this issue. And it has been closed for nearly a year now

**Comment by pakistanimoon** [comment]
i had same issue, but it's now solved. I just deleted BREAD and then recreated it from BREAD window.
