### ISSUE TITLE
no value for input tag in edit page

### ISSUE THREAD

**Issue by spfroc** [thedevdojo/voyager#3295]
- Laravel Version: 5.6.20
- Voyager Version: 1.0.8
- PHP Version:7.1.0
- Database Driver & Version:

### Description:
No current value in edit page generated by bread.
There is no value in the input tag which type is image,but it is in the img tag.
like below:
<div class="form-group  col-md-12">
<label for="name">列表图</label>
 <img src="http://pk.cdn.cnwan.com/1528786452_560036.png" style="max-width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:10px;">
<input type="file" name="cover_url" accept="image/*">
</div>

### Steps To Reproduce:
![20180612151214](https://user-images.githubusercontent.com/8610700/41275315-167b8754-6e53-11e8-80b8-5ad3ce5cf23d.png)

**Comment by marktopper** [comment]
Could you try to explain to me again what you want and what seems to be the problem?
Cause I don't quite understand what you are trying to do.

**Comment by spfroc** [comment]
Thank you! 
The problem Solved, my fault.
Sorry for my horrible English.
