### ISSUE TITLE
There is no image browse and save link to database button for already uploaded button

### ISSUE THREAD

**Issue by prdpspkt** [thedevdojo/voyager#3297]
- Laravel Version: 5.6
- Voyager Version: 1.1.6
- PHP Version: 7.1
- Database Driver & Version:

### Description:
There is no media browse button. When I want to upload image or file it is ok. But when I want to browse and link image to any field in my database there is no option. Is there any idea.

### Steps To Reproduce:
This comes under feature a and no pragmatically error producing mechanism.
Thank You

**Comment by SteamWind** [comment]
Screenshots of the view should be Ok to reproduce. It's too vague.

**Comment by prdpspkt** [comment]
Its so simple, It is not a bug. In bread there are lots of input types. But for image or file field I didn't find a way to browse form media manager. I always needs to upload file or image.
![image](https://user-images.githubusercontent.com/8027379/41280347-75a78d68-6e4e-11e8-88fb-b985ac936984.png)

**Comment by emptynick** [comment]
There are a lot discussions about this already.
For example #2564 #2242 or #1877
Its one of our [projects](https://github.com/the-control-group/voyager/projects/3) and theres already an open [PR](https://github.com/the-control-group/voyager/pull/3034)
