### ISSUE TITLE
User Roles Bread builder

### ISSUE THREAD

**Issue by Melcus** [thedevdojo/voyager#33]
I'm having some difficulties grasping how would I add a field in /user/1/edit to add the relationship User - Roles, could you give me an example how I would achieve that?

Awesome package by the way !

**Comment by marktopper** [comment]
From my understanding what @Melcus wish to achieve, is simply a method to assign a user a specific role within the "Edit User"/"Create User" formular.

**Comment by fletch3555** [comment]
Agreed.  There have a few discussions on how to implement relations.  I'm not aware of a consensus yet.

**Comment by fletch3555** [comment]
Relations have been added in v0.10
