### ISSUE TITLE
Multi-select lazy load

### ISSUE THREAD

**Issue by Rogue85** [thedevdojo/voyager#3300]
Relation multi-select box is very slow when data is big. How i can add a lazy load to multi-select box autocomplete?

**Comment by marktopper** [comment]
This would need to be done in the core, we are open to pull requests for this.

**Comment by Rogue85** [comment]
If you add a feature to override concrete UI elements views (Dropdown etc.) like BREAD views, it would be awesome.

**Comment by bnymn** [comment]
This feature would be awesome. It is actually **necessary** for big data.

**Comment by emptynick** [comment]
Introduced in https://github.com/the-control-group/voyager/pull/3586
