### ISSUE TITLE
Own form field "browse view/part"

### ISSUE THREAD

**Issue by ramonleenders** [thedevdojo/voyager#3301]
- Laravel Version: 5.6.24
- Voyager Version: 1.1
- PHP Version: 7.2.5-1

### Description:

In the browse.blade.php, there is a foreach which handles the $row->type of each data. So you'd have image, select_dropdown, checkbox, text and the others. Now, let's say I have my own form field programmed. There is a long elseif now in this view and own form fields would then go to the very laste "else". That currently is this code:

```
@else
     @include('voyager::multilingual.input-hidden-bread-browse')
     <span>{{ $data->{$row->field} }}</span>
@endif
```
However, I don't want to output the database value for each and every form field I custom build. Let's say you save a country code shortcut and want to display the full country name or a URL and you want that URL to be clickable (a href). Now it's all just outputted as found in the database. Is there a smart way we can solve this "issue"? I'm assuming more people have been making form fields by now?

Of course, I don't want to be willing to edit this view and put it in the root /resourses and keep adding else/if. It's not pretty if you have like 10/20/whatever amount of extra form fields added and interferes if other developers decide to make packages with form fields.

**Comment by emptynick** [comment]
This will be possible in version 1.2 (#3909) commit https://github.com/the-control-group/voyager/pull/3909/commits/843e9934bfd74e756f5471cfc9d1875fb874fb80.
