### ISSUE TITLE
Coordinates to settings

### ISSUE THREAD

**Issue by st7art22** [thedevdojo/voyager#3302]
- Laravel Version: 5.5.40
- Voyager Version: 1.1.2
- PHP Version: 7.1.12
- Database Driver & Version: 

### Description:
Add the coordinates type to settings, please.

![Screen](https://downloader.disk.yandex.ru/preview/3f07e7abda777d2855a6cc7a53f087facc972e8de2c51a9fab5539ade23528cf/5b2106ce/RXrWpziS7z47_f_YToj5B0ZhK_gXAxLng2fDiGncyfsNJ8ik_AubLt9BYetZXXC0C_PCN6XuqQqghplLqse87w%3D%3D?uid=0&filename=2018-06-13_14-54-55.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=1920x949)

https://yadi.sk/i/ouWAINsK3Xoxvq

**Comment by sicaboy** [comment]
Image doesn't display
