### ISSUE TITLE
Roles permission error message : "This action is unauthorized."

### ISSUE THREAD

**Issue by YounessTayer** [thedevdojo/voyager#3303]
Laravel Version: 5.6.25
    Voyager Version: 1.1.2
    PHP Version: 7.1.16
    Database Driver & Version: mysql 5.0.12

### Description:

I followed step by step the video tutorial [Tutorial](https://laravelvoyager.com/academy/bread-builder/). Now I have a "This action is unauthorized." error message when I try to open my themes BREAD from a left side menu I have created. this happens even after have been set the access roles to this BREAD for a both normal and admin users.

Any idea from what this error come from?

**Comment by amirmasoud** [comment]
have you set any extra gate/policy on your model? I faced same problem when I had extra policy outside of Voyager.

**Comment by YounessTayer** [comment]
Thank you amimasoud,

No, I did this in a fresh Laravel Voyage install. 

I deleted the Table&BREAD and recreate them several times and still have the same issue, in addition, my left side menu for this BREAD was created automatically while in the video tutorial the menu is created manually after the BREAD creation.
It's really strange for me!

**Comment by YounessTayer** [comment]
My model content : <?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class theme extends Model
{
    //
}

**Comment by fletch3555** [comment]
The video is from an older version and hasn't been updated yet, so I'm not surprised there are a few differences.

**Comment by YounessTayer** [comment]
SOLVED. The solution was to create a new database and install, the problem was solved.
I was pleasantly surprised that the left side menu was created automatically for me :+1:

**Comment by mohamedadel2018** [comment]
How can you solved this error , i am have same this error

**Comment by fletch3555** [comment]
You definitely don't have the same issue.  This issue is from a much older version and has been closed for over a year.  Please ask in slack (preferred) or open a new issue.
