### ISSUE TITLE
RTL webpack

### ISSUE THREAD

**Issue by amirmasoud** [thedevdojo/voyager#3304]
- Laravel Version: 5.6.*
- Voyager Version: 1.1.*
- PHP Version: 7.2.*
- Database Driver & Version: MySQL

### Description:
Does RTL version of css should be compiled through webpack or it's just plain css?

**Comment by fletch3555** [comment]
All version information is required when submitting issues on this repository.  If you're simply asking a question where version information seems unnecessary, that question would likely be better asked on our Slack group instead.

This can be reopened once the version information has been updated.

**Comment by amirmasoud** [comment]
Updated
