### ISSUE TITLE
I want to do a novel website background with this project

### ISSUE THREAD

**Issue by lostmaniac** [thedevdojo/voyager#3309]
- Laravel Version: 5.5
- Voyager Version: 1.1
- PHP Version:7.2
- Database Driver & Version:mariadb 10.2

### Description:
I want to use this project to be a novel website backstage. The novel website needs to have books. There are chapters under the books. How does this association relationship be handled? I have watched the video tutorial without mentioning how this novel class should establish BREAD.

**Comment by SteamWind** [comment]
https://laravel.com/docs/5.6/eloquent-relationships#one-to-many

https://laravelvoyager.com/academy/relationships/

That's not voyager related.

**Comment by lostmaniac** [comment]
Yes, I know this, but how can I configure BREAD to complete the process of clicking on a novel book name, entering a chapter directory, and editing a chapter directory without editing code?

**Comment by lostmaniac** [comment]
Thank you very much for your answer. @SteamWind

**Comment by SteamWind** [comment]
If it's a frontend feature you are speaking about, it's up to you to create it with laravel. You can't create frontend views in Voyager.
The concept of Voyager is to help you create a backend and let you do your frontend by yourself 😉 

https://voyager.readme.io/docs/what-is-voyager

**Comment by lostmaniac** [comment]
Thank you very much for your answer, but may need a tool to automatically generate the front-end, the back-end code is well written, I am very headache front-end page display

**Comment by SteamWind** [comment]
You need a CMS in this case I think...

**Comment by lostmaniac** [comment]
:) There are too many concepts in laravel. Not suitable for developers who are new to learning php.

**Comment by SteamWind** [comment]
You need some PHP basis to learn Laravel yeah, and you need some Laravel basis to use Voyager.

**Comment by lostmaniac** [comment]
Yes, thank you very much for your suggestion.

**Comment by SteamWind** [comment]
Okay, you can now close issue I think 😄 
Have fun in your quest

**Comment by lostmaniac** [comment]
Is there some good laravel introductory tutorial?

**Comment by SteamWind** [comment]
https://laracasts.com/skills/laravel

**Comment by lostmaniac** [comment]
Thanks again
