### ISSUE TITLE
Voyager seems to have troubles with database

### ISSUE THREAD

**Issue by acoudray** [thedevdojo/voyager#3310]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.2.4
- Database Driver & Version: 5.7.21

### Description:
I'm getting these errors even with the "key too long" fix.

```
SQLSTATE[42000]: Syntax error or access violation: 1071 La clé est trop longue. Longueur max imale: 1000 (SQL: alter table `translations` add unique `translations_table_name_column_name_foreign_key_locale_unique`(`table_name`, `column_name`, `foreign_key`, `locale`))
```

```
SQLSTATE[42S01]: Base table or view already exists: 1050 La table 'translations' existe déjà (SQL: create table `translations` (`id` int unsigned not null auto_increment primary key, `table_name` varchar(191) not null, `column_name` varchar(191) not null, `foreign_key` int unsigned not null, `locale` varchar(191) not null, `value` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
```

### Steps To Reproduce:
Install Laravel, include Voyager in composer, change the database informations to your own, and run php artisan voyager:install

**Comment by emptynick** [comment]
Thats a different error-message which was asked a few times before.
For example in #3035, #1840, #901 
There are a few other links and solutions here https://github.com/the-control-group/voyager/issues/2540#issuecomment-360172218

**Comment by acoudray** [comment]
I'm really sorry, I tried to search but obviously I didn't search enough about that. Will try that, thank you a lot

**Comment by acoudray** [comment]
Alright now I have this

```
SQLSTATE[42S01]: Base table or view already exists: 1050 La table 'translations' existe déjà (SQL: create table `translations` (`id` int unsigned not null auto_increment primary key, `table_name` varchar(191) not null, `column_name` varchar(191) not null, `foreign_key` int unsigned not null, `locale` varchar(191) not null, `value` text not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci' engine = InnoDB ROW_FORMAT=DYNAMIC)
```

**Comment by acoudray** [comment]
Sorry for spamming, it looks solved. All I had to do was deleting the translations table. Do you have any idea why the translations table was already here?

**Comment by SteamWind** [comment]
(Next time, use triple ` please)

**Comment by fletch3555** [comment]
@acoudray, @SteamWind is right.  When adding multi-line code blocks (or logs, etc), please use triple-backticks (\`\`\`) before and after the block.

I've updated it for you in this case.

**Comment by jaikangam** [comment]
This happens to me when I tried to install voyager. After few digging I found these two answers which working
try this on the /config/database.php

'mysql' => [
...,
...,
'engine' => null,
]

to
'mysql' => [
...,
...,
'engine' => 'InnoDB',
]

its work for me.
