### ISSUE TITLE
UI elements language

### ISSUE THREAD

**Issue by BOLYAC** [thedevdojo/voyager#3311]
- Laravel Version: 5.6.20
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: 5.7

### Description:
When i creaate new bread i get this
"voyager.generic.delete" instead of Delete
"voyager.generic.edit" instead of Edit.
and other buttons.
...., etc
i use Fr language.

**Comment by SteamWind** [comment]
Don't worry, it will be updated:
https://github.com/the-control-group/voyager/pull/3269

**Comment by emptynick** [comment]
But `generic.edit` is [there](https://github.com/the-control-group/voyager/blob/1.1/publishable/lang/fr/generic.php#L34) same for `delete`.
I wonder that it is `voyager.` as we are using `voyager::`.
Is it an overriden view?
If no, can you share a screenshot?

**Comment by BOLYAC** [comment]
yes it's a overriden view
https://imgur.com/a/v75esBO

**Comment by emptynick** [comment]
We changed the way how we load translations. Take a look [here](https://github.com/the-control-group/voyager/blob/1.1/resources/views/bread/browse.blade.php#L12).
You just need to replace `voyager.x` with `voyager:x`

**Comment by BOLYAC** [comment]
thnx men fix it,  i took an old view from an old version of voyager
Voyager.generic.edit  to Voyager::generic.edit
