### ISSUE TITLE
How to display translatable richtext field html in read view?

### ISSUE THREAD

**Issue by MartynasJanu** [thedevdojo/voyager#3313]
- Laravel Version: 5.5.34
- Voyager Version: v1.0.15
- PHP Version: 7.1.11

I have a field in BREAD object that is of type rich_text_box. The field is translatable. If I go to read view, I can see the contents of the textbox with html stripped out. I have changed the parameter in _input-hidden-bread-read.blade.php_ to _false_ which prevents the html tags from being stripped out, however the text is still html-entity-encoded. The value here
```
@if (is_field_translatable($dataTypeContent, $row))
 <input type="hidden"
           data-i18n="true"
           name="{{ $row->field }}_i18n"
           id="{{ $row->field }}_i18n"
           value="{{ get_field_translations($dataTypeContent, $row->field, $row->type, false) }}">
@endif
```

is proper html with no html entities encoded, however when it's moved to a `<p>` element it becomes html-entity-encoded.

**Comment by emptynick** [comment]
Thats pretty basic [blade-stuff](https://laravel.com/docs/blade#displaying-data).
Also please ask questions in our Slack group as suggested in the issue-template.

**Comment by MartynasJanu** [comment]
> Thats pretty basic [blade-stuff](https://laravel.com/docs/blade#displaying-data).
> Also please ask questions in our Slack group as suggested in the issue-template.

Surely You didn't read my question but thanks anyway :)
