### ISSUE TITLE
How to custom the size of the images or the files uploaded 

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3316]
- Laravel Version: 5.6
- Voyager Version:1.1
- PHP Version: 7.2
- Database Driver & Version: phpmyadmin 
Hey  , i got an issue , whenever i try to upload a file that its size is bigger than 3Mb i found that ,it s not uploaded , please how can i custom the sizes of the files and images i upload .
thank you

**Comment by fletch3555** [comment]
There's a php.ini config limiting the size of uploads. You need to change that.

Nothing to do with Voyager

**Comment by hamzataougar** [comment]
thank you man !
