### ISSUE TITLE
Dynamic drop down list from an array

### ISSUE THREAD

**Issue by d3turnes** [thedevdojo/voyager#3317]
- Laravel Version: 5.5.*
- Voyager Version: 1.1.1
- PHP Version: 7.0.15 +
- Database Driver & Version:

### Description:
Dynamic drop down list from an array

### Steps To Reproduce:
1 - Copy select_dropdwon.blade.php 
form: vendor\tcg\voyager\resources\views\formfields\select_dropdown.blade.php
to: resources\views\vendor\voyager\formfields\select_dropdown.blade.php

2 - edit resources\views\vendor\voyager\formfields\select_dropdown.blade.php
line: 53
```
@foreach($relationshipOptions as $relationshipOption)
                <option value="{{ $relationshipOption->{$options->relationship->key} }}" @if($default == $relationshipOption->{$options->relationship->key} && $selected_value === NULL){{ 'selected="selected"' }}@endif @if($selected_value == $relationshipOption->{$options->relationship->key}){{ 'selected="selected"' }}@endif>{{ $relationshipOption->{$options->relationship->label} }}</option>
            @endforeach
```
--- change ---
```
@if (is_object($relationshipOption))
                <option value="{{ $relationshipOption->{$options->relationship->key} }}" @if($default == $relationshipOption->{$options->relationship->key} && $selected_value === NULL){{ 'selected="selected"' }}@endif @if($selected_value == $relationshipOption->{$options->relationship->key}){{ 'selected="selected"' }}@endif>{{ $relationshipOption->{$options->relationship->label} }}</option>
				@else
				<option value="{{ $relationshipOption[$options->relationship->key] }}" @if($default == $relationshipOption[$options->relationship->key] && $selected_value === NULL){{ 'selected="selected"' }}@endif @if($selected_value == $relationshipOption[$options->relationship->key]){{ 'selected="selected"' }}@endif>{{ $relationshipOption[$options->relationship->label] }}</option>
				@endif
```
3 - edit bread options, for example
Bread: Pages
Type: Select Dropdown
Field: Template or my-field
```
{
  "relationship": {
     "key" => 'key',
     "label" => 'value'
  }
}
```
4 - edit your Model for example: Page

App\Page.php

add
if your filename is template =>

```
public function template() { ... }
```
```
public function templateList() {
        return Collect([
            'key' => 1, 'value' => 'name1',
            'key' => 2, 'value' => 'name2',
            ...
       ]);
}
```
if your fielname is template_id
```
public function templateId() { ... }
```
```
public function templateIdList() { ... }
```
the best is add custom input types

**Comment by emptynick** [comment]
This is better opened as a PR, or even better as a hook so everyone who wants can install it.

**Comment by nafissaNina** [comment]
Thx for sharing,I tried this on my products table, but then when I add a new product it throws an error: Trying to get property 'key' of non-object (View:....\voyager\resources\views\formfields\select_dropdown.blade.php)
