### ISSUE TITLE
Image orientation problem 

### ISSUE THREAD

**Issue by tunapiq** [thedevdojo/voyager#3318]
- Laravel Version: 5.5.*
- Voyager Version: 1.1.2
- PHP Version:7.1
- Database Driver & Version:

### Description: I came across a problem when uploading image files that were taken in landscape mode on mobile devices, the images are rotated to portrait but voyager still uploads them as landscape. I dug through the source codes and figured out where the error was coming from. I can fix it locally but it is better to have it fixed from the source. 

Class path (single image): **TCG\Voyager\Http\Controllers\ContentTypes\Image**
Class path (multiple image): **TCG\Voyager\Http\Controllers\ContentTypes\MultipleImage**
Fix:
changing the following line
$image = InterventionImage::make($file);
to
$image = InterventionImage::make($file) -> orientate();

fixes the problem.

**Comment by fletch3555** [comment]
This would be best opened as a Pull Request.

**Comment by BMCTeixeira** [comment]
It stills happens

**Comment by tunapiq** [comment]
You have to replace, every code that calls `InterventionImage::make($file) to InterventionImage::make($file)->orientate()` in the files, it appears in multiple places in the files. Cheers
