### ISSUE TITLE
Voyager: Image upload not working in admin panel on live server.

### ISSUE THREAD

**Issue by pukarprasai** [thedevdojo/voyager#3319]
The app is fine in localhost but not working in live server(shared hosting). The image is not being uploaded in live server but working fine in localhost.
![image](https://user-images.githubusercontent.com/40302679/41507355-d51c8af4-7250-11e8-9712-8abca084716f.png)

**Comment by fletch3555** [comment]
Short answer: don't use shared hosting.  VPSs are super cheap these days, and you'll have full control over what php functions are enabled.

Long answer: this is common practice for shared hosts and done as a security feature. You MAY be able to get it to work by manually creating the symlink through cpanel or whatever, or contact the host and see if they can do it from you.  This isn't a Voyager problem, but a system/hosting problem.
