### ISSUE TITLE
Image optimization 

### ISSUE THREAD

**Issue by explicit-logic** [thedevdojo/voyager#3320]
- Laravel Version: 5.5
- Voyager Version: 1.1.2
- PHP Version:7+
- Database Driver & Version: mysql

### Description:

After loading an optimized png image into the admin panel, its size becomes larger. 
How to fix it?

https://i.imgur.com/QlZF0vS.png

**Comment by emptynick** [comment]
Please use the [quality prop](https://docs.laravelvoyager.com/core-concepts/bread-builder#image) which will increase/decrease the size of your image accordingly.
