### ISSUE TITLE
Modify browse table

### ISSUE THREAD

**Issue by szanaszabolcs** [thedevdojo/voyager#3325]
- Laravel Version: 5,6
- Voyager Version: 1,1
- PHP Version: 7.2
- Database Driver & Version: MySQL

### Description:

I have a  'Jobs' BREAD with 'id_user' column belongs to 'User' model where store the id and display the name. It's perferct, but i would like to anchor tag to a user name at jobs browse table. Is it possible?

Thank you very much in advance!

**Comment by SteamWind** [comment]
https://github.com/the-control-group/voyager/issues/3315

**Comment by SteamWind** [comment]
Print screen of your relationships please

**Comment by szanaszabolcs** [comment]
![1](https://user-images.githubusercontent.com/6462294/41537381-99e20294-7308-11e8-9249-906d17a6f2ee.PNG)

![2](https://user-images.githubusercontent.com/6462294/41537385-9dd5327c-7308-11e8-97d6-ecb4690fa3e9.PNG)

![3](https://user-images.githubusercontent.com/6462294/41537390-a0791930-7308-11e8-87ce-95b0bbc1ca28.PNG)

**Comment by SteamWind** [comment]
oh a direct link, like an `<a href="...">`
For now it's not possible but someone gave a quick fix for this here: https://github.com/the-control-group/voyager/issues/2826 but it's not stable enough yet...

**Comment by szanaszabolcs** [comment]
i see, unfortunately my client is insists on it :(

**Comment by szanaszabolcs** [comment]
or any other solution for this problem? he want to see the users informations

**Comment by SteamWind** [comment]
Try to implement that, you can use it but for every relations you point, you need a BREAD on it or it will trow an error...
For now, it's the only issue I found.

**Comment by szanaszabolcs** [comment]
thank you!
