### ISSUE TITLE
Trying to get property 'details' of non-object

### ISSUE THREAD

**Issue by AbanoubNassem** [thedevdojo/voyager#3329]
- Laravel Version: 5.6.*
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

it can't parse predefined relationships ? 
![screen shot 2018-06-19 at 9 18 56 am](https://user-images.githubusercontent.com/13698722/41578210-2abbb5b4-73a2-11e8-95d8-b4971e4ca6a9.png)

### Steps To Reproduce:
- Create two models (manually or using artisan)
- Add a relationship between both models (in the model.php not using voyager)
- Go to browse the model in voyager this error will popup

I fixed it by adding this in BreadRelationshipParser.php:

```

                 $bread_data = $dataType->browseRows->where('field', $field)->first();

                + if(!$bread_data) continue;

                $relationData = json_decode($bread_data->details)->relationship;
```

**Comment by fletch3555** [comment]
I'm not sure what you're saying.  Voyager doesn't know anything about relationships in your model class files.  Voyager only knows about relationships defined from within Voyager, due to how it stores/processes the BREAD fields.

In short, if you're trying to access a field that Voyager knows nothing about, then it's going to fail exactly as you've shown.

**Comment by AbanoubNassem** [comment]
@fletch3555 , I'm not trying to , it automatically assumes , that it's a BREAD relationship and fails , what should happen is , if this relation isn't represented in the database , it should ignore it , instead of failing!

**Comment by emptynick** [comment]
Its not the relationship which is missing, but the `data_row`.
Try to set `Browse` to true for that row, that _should_ fix it.

**Comment by AbanoubNassem** [comment]
@emptynick there is no row for it , it's a relationship within the model.php itself not using Voyager BREAD

**Comment by fletch3555** [comment]
Yes, and as I said above, Voyager is (currently) unable to use relationships defined in model classes. The relationship MUST be defined through the Voyager UI for voyager to know it exists

**Comment by AbanoubNassem** [comment]
@fletch3555 I completely understand that, and am not trying to use this relation in voyager , but voyager consider it a relation ship and tries to load it from the db , it should ignore it , if it's not found in the database, otherwise we wont be able to use custom relation in the frontend , since everytime we are going to try to login-in the admin and go to that model it will break , got my point now?

**Comment by fletch3555** [comment]
I understand what you're saying, though it doesn't make sense to me.  Voyager doesn't even attempt to parse relationships defined solely in the model class, so there's absolutely no way it could be causing this.  There has to be another cause

**Comment by AbanoubNassem** [comment]
@fletch3555 please take just 5 minutes to reproduce this :

-make 2 models using artisan , that has relation to each other ,
-in voyager make a bread for those models 
-now go brows any of that models , voyager will break
