### ISSUE TITLE
"no message" error when I try to edit bread on voyager last 1.1 v laravel 5.5

### ISSUE THREAD

**Issue by jonimng** [thedevdojo/voyager#3330]
- Laravel Version: 5.5
- Voyager Version: 1.1
- PHP Version:7.2
- Database Driver & Version:

Description:
no massege error when i try to edit bread after upgrading my voyager

**Comment by jonimng** [comment]
---error description--  



          return false;
        }
 
        return true;
    }
 
    /** @deprecated */
    public function canOrFail($permission)
    {
        if (!$this->can($permission)) {
            throw new UnauthorizedHttpException(null);
        }
 
        return true;
    }
 
    /** @deprecated */
    public function canOrAbort($permission, $statusCode = 403)
    {
        if (!$this->can($permission)) {
            return abort($statusCode);
        }
 
        return true;
    }

**Comment by fletch3555** [comment]
More information is needed, else we won't be able to help you.
