### ISSUE TITLE
Installation Error: Undefined index: index_type

### ISSUE THREAD

**Issue by batuhan-aydin** [thedevdojo/voyager#3336]
- Laravel Version: 5.6.25
- Voyager Version: 1.1
- PHP Version: 7.2.6
- Database Driver & Version: mysql 14.14

### Description:
I was trying to install voyager to my newly created laravel project but i'm getting this error constantly and can't get done installation. When i go to /admin after installation there is nothing.

### Steps To Reproduce:
I create project
`sudo composer create-project --prefer-dist laravel/laravel voyager`
Creating new db and setting up .env
Adding this to AppServiceProvider to avoid another error
`Schema::defaultStringLength(191);`
`composer require tcg/voyager`
I gotta change ImageHandler.php to imageHandler.php and MultipleImagesHandler.php to MultipleimagesHandler to avoid another error.
Then after this
`php artisan voyager:install --with-dummy`
Then i get this. I also use ubuntu.

 ErrorException  : Undefined index: index_type

  at /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:88
    84|                 $v['primary'] = true;
    85|             } else {
    86|                 $v['primary'] = false;
    87|             }
  '>' 88|             if (strpos($v['index_type'], 'FULLTEXT') !== false) {
    89|                 $v['flags'] = ['FULLTEXT'];
    90|             } elseif (strpos($v['index_type'], 'SPATIAL') !== false) {
    91|                 $v['flags'] = ['SPATIAL'];
    92|             }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: index_type", "/home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php", ["permissions"])
      /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:88

  2   Doctrine\DBAL\Schema\MySqlSchemaManager::_getPortableTableIndexesList("permissions")
      /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:204

  Please use the argument -v to see more details.

**Comment by emptynick** [comment]
Can you post the whole output of the installation with installation steps?
I cant think of any point where the installation is calling the SchemaManager right now.

**Comment by batuhan-aydin** [comment]
Following the docs
```
#> composer require tcg/voyager
Using version ^1.1 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 22 installs, 0 updates, 0 removals
  - Installing symfony/filesystem (v4.1.0): Loading from cache
  - Installing seld/phar-utils (1.0.1): Loading from cache
  - Installing seld/jsonlint (1.7.1): Loading from cache
  - Installing justinrainbow/json-schema (5.2.7): Loading from cache
  - Installing composer/spdx-licenses (1.4.0): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing composer/ca-bundle (1.1.1): Loading from cache
  - Installing seld/cli-prompt (1.0.3): Loading from cache
  - Installing composer/composer (1.6.5): Loading from cache
  - Installing larapack/hooks (v1.0.8): Loading from cache
  - Installing larapack/voyager-hooks (v1.0.8): Loading from cache
  - Installing arrilot/laravel-widgets (3.12): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing doctrine/dbal (v2.7.1): Loading from cache
  - Installing larapack/doctrine-support (v0.1.6): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing intervention/image (2.4.2): Loading from cache
  - Installing tcg/voyager (v1.1.2): Loading from cache
composer/composer suggests installing ext-zip (Enabling the zip extension allows you to unzip archives)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
intervention/image suggests installing ext-gd (to use GD library based image processing.)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
Writing lock file
Generating optimized autoload files
'>' Illuminate\Foundation\ComposerScripts::postAutoloadDump
'>' @php artisan package:discover

In Container.php line 767:
                                                            
  Class TCG\Voyager\FormFields\imageHandler does not exist  
                                                            

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
```

After that

```
APP_URL=http://localhost // may be i should do this localhost:8000 not sure. but makes no difference
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=voyager
DB_USERNAME=root
DB_PASSWORD=
```

As you can see it can't find imageHandler but there is ImageHandler. I just change the letter. Same for MultipleimageHandler


```
php artisan voyager:install --with-dummy

Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Publishing complete.
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Publishing complete.
Migrating the database tables into your application

   ErrorException  : Undefined index: index_type

  at /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:88
    84|                 $v['primary'] = true;
    85|             } else {
    86|                 $v['primary'] = false;
    87|             }
  '>' 88|             if (strpos($v['index_type'], 'FULLTEXT') !== false) {
    89|                 $v['flags'] = ['FULLTEXT'];
    90|             } elseif (strpos($v['index_type'], 'SPATIAL') !== false) {
    91|                 $v['flags'] = ['SPATIAL'];
    92|             }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: index_type", "/home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php", ["permissions"])
      /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:88

  2   Doctrine\DBAL\Schema\MySqlSchemaManager::_getPortableTableIndexesList("permissions")
      /home/batuhan/Batuhan/laravelProjects/voyager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php:204

  Please use the argument -v to see more details.
```

And that's all. After them as i see Voyager must be installed. Laravel works but there isn't route for /admin unlike the video i watched at voyager academy.

**Comment by fletch3555** [comment]
This is quite old and has gone unreported in a few versions, so I'm going to close this.  If it continues, please feel free to reopen, or comment and we'll reopen for you.

**Comment by ferhatabd** [comment]
Hello, 
I'm having the same issue exactly as defined by the original poster. 
Currently my setup is:
Laravel 7 & Voyager 1.4.

Everything works properly on the local environment, but when I clone the project to production and run `composer install`, during the autoload dumping I get the output:

>  Illuminate\Contracts\Container\BindingResolutionException 
> 
>   Target class [TCG\Voyager\FormFields\imageHandler] does not exist.
> 
>   at vendor/laravel/framework/src/Illuminate/Container/Container.php:811
>     807| 
>     808|         try {
>     809|             $reflector = new ReflectionClass($concrete);
>     810|         } catch (ReflectionException $e) {
>     811|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
>     812|         }
>     813| 
>     814|         // If the type is not instantiable, the developer is attempting to resolve
>     815|         // an abstract type such as an Interface or Abstract Class and there is
> 
>       +18 vendor frames 
>   19  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Then I rename the ImageHandler -> imageHandler & MultipleImagesHandler -> MultipleimagesHandler, then it seems to proceed. 

After that when it comes to migrating, when "2017_01_15_000000_make_table_name_nullable_in_permissions_table" is being migrated I get the output: 

>   ErrorException 
> 
>   Undefined index: index_type
> 
>   at vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:85
>     81|                 $v['primary'] = true;
>     82|             } else {
>     83|                 $v['primary'] = false;
>     84|             }
>     85|             if (strpos($v['index_type'], 'FULLTEXT') !== false) {
>     86|                 $v['flags'] = ['FULLTEXT'];
>     87|             } elseif (strpos($v['index_type'], 'SPATIAL') !== false) {
>     88|                 $v['flags'] = ['SPATIAL'];
>     89|             }

Interestingly, if I modify the source code here, change the "index_type" to "Index_type" it seems to move on. 
But then eventually it fails again during the migration of "2020_08_18_161214_create_session_table" with the output: 


>    BadMethodCallException 
> 
>   Method Illuminate\Database\Schema\Grammars\MySqlGrammar::typeBigint does not exist.
> 
>   at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
>      99|      */
>     100|     public function __call($method, $parameters)
>     101|     {
>     102|         if (! static::hasMacro($method)) {
>     103|             throw new BadMethodCallException(sprintf(
>     104|                 'Method %s::%s does not exist.', static::class, $method
>     105|             ));
>     106|         }
>     107| 
> 
>   • Bad Method Call: Did you mean Illuminate\Database\Schema\Grammars\MySqlGrammar::typeBigInteger() ? 
> 
>       +9 vendor frames 
>   10  database/migrations/2020_08_18_161214_create_session_table.php:30
>       Illuminate\Support\Facades\Facade::__callStatic("create")
> 
>       +34 vendor frames 
>   45  artisan:37
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> 

But nothing as such happens on the local environment. 

On the production currently I have:
A VPS hosting by Dreamhost running on Apache
PHP v7.3 
MySql v5.7 (with innoDB engine) 

When I compare the local versions, I have MySql v8.0 here on the macOS. Though I'm not sure if that's related.

Just let me know please if there is further information required and I'll be happy to cooperate. 

Have nice sunday & all the best.
