### ISSUE TITLE
Browse Error in the process of making BREAD

### ISSUE THREAD

**Issue by Riversedgedesigns** [thedevdojo/voyager#3337]
- Laravel Version: 5.6.23
- Voyager Version: 1.1.2
- PHP Version: 7.2.4-1 Latest Homestead
- Database Driver & Version:  Latest Homestead MySQL 5.7.22

### Description:
I am trying to make a BREAD for my contracts table. Which _**was**_ called contract. But I had an error where voyager was looking for **contracts** (plural) table instead just **contract**. So it was simple enough I renamed the **contract** table to **contracts** and changed it across my site. Took 1 min. Made BREAD and it generated menu. So I try to browser my new BREAD and boom error:

> Missing required parameters for [Route: voyager.contracts.edit] [URI: mmpadmin/contracts/{contract}/edit]. (View: /home/vagrant/sites/mmp/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) (View: /home/vagrant/sites/mmp/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)

I scroll in error page and find this:

> "voyager.contracts.edit"
> null

Is what is being posted to: 
/vendor/tcg/voyager/src/Actions/EditAction.php 31
```
    public function getDefaultRoute()
    {
        return route('voyager.'.$this->dataType->slug.'.edit', $this->data->{$this->data->getKeyName()});
    }
```
Note that I have had multiple errors in the process of trying to make the BREAD for this table. I didnt think it would come down to me posting an error. Im at a lost and do not have the previous errors details.
Also note that I installed voyager on a in-progress laravel project and was already having and still having issues with voyage, aside from the contracts issue, pertaining to users table. (separate issue that I may post later)
Also... I have already successfully made BREAD for a few other tables that did not have plural table names.

### Steps To Reproduce:
Attempt to make BREAD for a table with no plural such as **contract** when voyager is looking for **contracts**. How that even happened is lost to me.
Then rename database table **contract** to **contracts** and make BREAD for newly renamed table.
Attempt to browse the newly made Menu Item.
And yes I did delete the old menu item that was initially made when I attempted to make the BREAD the first time.

**Comment by Riversedgedesigns** [comment]
Just attempted to make a BREAD for my **billing** table. Same thing. Its looking for **billings**. Why..?

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mmp.billings' doesn't exist (SQL: select count(*) as aggregate from `billings`)

**Comment by emptynick** [comment]
>Attempt to make BREAD for a table with no plural such as contract when voyager is looking for contracts. How that even happened is lost to me.  

Thats a [Laravel convention](http://www.laravelbestpractices.com/#table_and_field_naming) also [see here](https://laravel.com/docs/5.6/eloquent#eloquent-model-conventions)

>"voyager.contracts.edit"
null

Means it cannot find a primary key (what `$this->data->getKeyName()` tries to find)

Do you have a primary key other than `id` ?
If yes, did you tell this to your model (last link above)?

**Comment by Riversedgedesigns** [comment]
That's it. My problem is that I was converting my SQL tables from a none laravel project and so they have unique id names and none plural names. Problem solved.

**Comment by elvecz** [comment]
In my case it was not working (version 1.2) because of => 

`<a href="{{ route('voyager.bread.create', ['name' => $table->name]) }}"` => not working
`<a href="{{ route('voyager.bread.create', $table->name) }}"` => working

file `vendor/tcg/voyager/resources/views/tools/database/index.blade.php`

Solved via override.
