### ISSUE TITLE
Multiselect not displaying all values when reading

### ISSUE THREAD

**Issue by allanfatweb** [thedevdojo/voyager#3338]
- Laravel Version: 5.6
- Voyager Version:  v1.1.2
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:

hi,
I've created a multi select from db so the drop down, when populating the drop down and saving the data it works.
It's saving it as an array i think formatted like ["3","4", "8"] which are id's of another table.
but when i try loading it via edit page its only displaying the first array value.

![image](https://user-images.githubusercontent.com/40446926/41695063-7643d348-7561-11e8-904b-93a6e40a31ca.png)

and on view it doesnt display anything..

### Steps To Reproduce:

I created the database which is colors and gallery
colors are just regular field inputs id, name, code (which is the color bread option from voyager) and slug

on the gallery thats where i did a bread relationship for color_list which is a drop down option like so
```
{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
```
I created a model called Color and made 
```
public function colorsList()
{
    return $this->hasMany(Voyager::modelClass('Color'), 'id', 'colors_list');
}
```
so everything works up until you want to edit the field which just shows 1 entry out of multiple ones selected. and view page it does not show anything..
 Any ideas? or em i missing something else.. thanks.

**Comment by allanfatweb** [comment]
Issue is solved! I was trying to save the value on the current table rather than a pivot table.. thanks

**Comment by fletch3555** [comment]
Glad you got it figured out
