### ISSUE TITLE
Integer input with commas

### ISSUE THREAD

**Issue by lqchinh88** [thedevdojo/voyager#3340]
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version:
- Database Driver & Version:

### Description: Some of my number inputs are BIGINT, reflecting money value. When inputing, I want separating commas to be shown, like "2,344,122" , not just "2344122" which might be wrong if there're many zeroes.
How do I do so ?

**Comment by emptynick** [comment]
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/3326
