### ISSUE TITLE
Datatables Responsive Documentation

### ISSUE THREAD

**Issue by sradesign** [thedevdojo/voyager#3345]
## Description
Datatables Responsive proper documentation and example is missing

**Comment by fletch3555** [comment]
Please provide the appropriate required information when opening an issue.  As this is a request for documentation to be updated, you should follow this template: https://github.com/the-control-group/voyager/blob/1.1/.github/ISSUE_TEMPLATE/documentation-request.md.  Simply claiming something is missing with a single sentence is not adequate.  This can be reopened once the appropriate information has been added.

Please note that readme.io allows you to directly provide suggestions/additions to the documentation.
