### ISSUE TITLE
Upgrade datatables bootstrap to bootstrap 4

### ISSUE THREAD

**Issue by sradesign** [thedevdojo/voyager#3347]
Dear Voyager team please upgrade datatables bootstrap to bootstrap 4

**Comment by emptynick** [comment]
Upgrading to Bootstrap 4 is not possible without some massive changes in our whole Layout.  
It might come in the future, but not too soon.

**Comment by marcellopato** [comment]
Hey guys! Any tips about when does it come to bootstrap 4?

**Comment by emptynick** [comment]
There's no reason to upgrade datatables to bootstrap 4 while Voyager is not using Bootstrap 4 itself.
