### ISSUE TITLE
Not Able to Create Relationships BREAD

### ISSUE THREAD

**Issue by sradesign** [thedevdojo/voyager#3349]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.2
 - PHP: 7.1.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Not Able to Create Relationships BREAD. I created a new table and it's field after that I created the model via Artisan and a BREAD from BREAD Builder I can see the Bread fine in the view then I tried to create relationships via BREAD Builder but as you can see in the attachment the selects are all empty: the belonging select, category select, etc. 

## Screenshots
![image](https://user-images.githubusercontent.com/11314206/41820747-1f395a02-77df-11e8-933e-3cc5cc9738a0.png)

**Comment by emptynick** [comment]
I can not see that the selects are empty. They are just not opened (the arrow would show up if it was open).
Also please fill in your Database version.

**Comment by sradesign** [comment]
They are not opening because there is nothing in them. Even when I inspect the element there is no option created for select.

**Comment by emptynick** [comment]
You wont see any options when inspecting the element as select2 does some magic there (pushing a options-div somewhere before the closing `html` tag an so on).
Your best bet is to look into the source code (Ctrl+U or something) and look for the select there.
And there is an option `id`.
Did you upgrade from an older version? What is your browser?

**Comment by sradesign** [comment]
Ok found out there should be something with my JS codes or CSS codes thanks for your help.

**Comment by sradesign** [comment]
![image](https://user-images.githubusercontent.com/11314206/41821651-c0e33294-77ec-11e8-9318-414697a09404.png)

See even in the edit section of Bread in view my Selects are opening funny in Firefox Latest Version and Chrome Latest Version

**Comment by sradesign** [comment]
By the way, I'm trying to Join Slack and getting Failed! token_revoked

**Comment by emptynick** [comment]
> By the way, I'm trying to Join Slack and getting Failed! token_revoked

Thanks, we will take care of it.

> See even in the edit section of Bread in view my Selects are opening funny in Firefox Latest Version and Chrome Latest Version

Thats why I asked if you upgraded, and what your browser is.
There _were_ some problems with select2 in modals back in version 1.0.x

**Comment by sradesign** [comment]
How can I upgrade it? As you can see in the bottom of the attachment below my version is 1.1.2
![image](https://user-images.githubusercontent.com/11314206/41822348-c6dbb586-77f6-11e8-9e72-81ec907d964e.png)

**Comment by sradesign** [comment]
Any comment on my issue?

**Comment by fletch3555** [comment]
1.1.2 is the latest, so no need to try to upgrade.

Slack link has been fixed, so feel free to try again.

What do you mean by "opening funny"?

**Comment by sradesign** [comment]
As you can see in attachment I provided select open in wrong place and on some select doesn’t open at all

**Comment by MrCrayon** [comment]
As this refer to a quite old version, please update and open another issue if you are still experiencing this problem.
