### ISSUE TITLE
[Bug] Nothing is displayed in "show"

### ISSUE THREAD

**Issue by guillermoprojaslema** [thedevdojo/voyager#3353]
## Version information

 - Laravel: v5.5.40
 - Voyager: v1.1
 - PHP: 7.0.3
 - Database: MySQL Ver 14.14 Distrib 5.7.22,

## Description
I can't view any resource (users, post, pages, etc). But I can access to the "edit" view with the corect data within the inputs. (name: John, lastname: Doe, etc) I can, Create, update, delete, but i can't READ

## Steps To Reproduce
1 Create a new laravel project (5.5.4)
2 Install Voyager with dumy data
3 `php artisan serve`
3 Go to de `localhost:8000/admin/users/1` or go to the dashboard and click on view, on any  new resource that you can create manually o inserting directly on the database.

## Expected behavior
I want to "VIEW" my resources

## Screenshots
[Screenshot](https://ibb.co/iN47X8)

**Comment by fletch3555** [comment]
Sounds like invalid data somewhere, causing it all to blow up, but I'm not sure why whoops isn't showing up.  Do you have debug disabled?  Anything in the Laravel log file?

**Comment by guillermoprojaslema** [comment]
laravel.log shows nothing relevant. Also, I tried `composer update` and `composer cache:clear` and `composer dump-autoload` but nothing (besides the updating packages process) happens. I got a blank page and 200 status response. And yes, it looks like a invalid data.

**Comment by guillermoprojaslema** [comment]
I've just updated to the 1.1.3 version, and this bug is fixed.
