### ISSUE TITLE
Default avatar is broken for new users

### ISSUE THREAD

**Issue by fbnlsr** [thedevdojo/voyager#3354]
## Version information
 - Laravel: v5.6.26
 - Voyager: v1.1
 - PHP: 7.2

## Description
When adding user to voyager, its default avatar is broken.

## Steps To Reproduce
1. Create a new Laravel project
2. Install Voyager *without* dummy data
3. Add authentication scaffolding for Laravel, using `php artisan make:auth`
4. Register new user, say with email `johndoe@example.com`
5. Add admin privileges to this user using `php artisan voyager:admin johndoe@example.com`
6. Go to `/admin` with the user logged in
7. The requested file `/storage/users/default.png` does not exist

## Expected behavior
A default avatar picture should appear

## Screenshots
![voyager](https://user-images.githubusercontent.com/1923346/41918194-2333b1ba-795c-11e8-8c97-cf75fe532050.JPG)

## Additional context
I don't know if it's important but I'm using homestead as my web server.

**Comment by fletch3555** [comment]
Can you verify whether the file exists at `/storage/app/public/users/default.png`?

If so, what about `/public/storage/users/default.png`?

**Comment by fbnlsr** [comment]
None of them exists.

**Comment by tjmckenzie** [comment]
The default user icons are only installed during the `voyager:install --with-dummy` command.

**Comment by guillermoprojaslema** [comment]
Did you change de `.env` file? I've got a similar issue, I wasn't using the Homestead though. I had to change the `APP_URL=localhost` to  `APP_URL=127.0.0.1:8000` like the docs says.

**Comment by SteamWind** [comment]
I experienced the same issue but you better pick an other default avatar on internet or do your own 😄

**Comment by fbnlsr** [comment]
Yeah we really should have a default avatar set even when not using `--with-dummy`.

Maybe use Gravatar as default?

**Comment by SteamWind** [comment]
Gravatar is the devil 😝 
(@fbnlsr This is only a personal appreciation. I just don't like the fact that you share the same image everywhere. I prefer to setup my avatar from case to case...)

**Comment by fbnlsr** [comment]
Why's that?

**Comment by slckym** [comment]
Change the APP_URL in .env file
`APP_URL=http://voyager.test`

**Comment by emptynick** [comment]
@slckym that is just wrong.
The image just doesn't exist, and changing the app-url to `voyager.test` will break everything (at least for him)

**Comment by fbnlsr** [comment]
I did change the URL in the `.env` file when I first set up my app.

I believe this is a problem related to Voyager, not my config.

**Comment by tjmckenzie** [comment]
Without installing with dummy data, you can manually set the path to your own default user icon in `config/voyager.php`
[https://github.com/the-control-group/voyager/blob/1.1/publishable/config/voyager.php#L21](url)

**Comment by bluemmb** [comment]
@fbnlsr, in Laravel any file inside `storage/app/public` folder is considered as dummy files. take a look at [.gitignore](https://github.com/laravel/laravel/blob/master/storage/app/public/.gitignore) in the mentioned path.

So, to me they are not considered as my project main files and it seems reasonable to not create that file with default voyager installation.

**Comment by fbnlsr** [comment]
I hear what you are both saying. But I believe Voyager should provide a default avatar picture when creating users without using the `--with-dummy` flag. If not, what's the point of providing a whole set of icons as well? To me that's an issue that needs to be solved.

**Comment by fletch3555** [comment]
Agreed, and Voyager used to. It was accidentally moved, not intentionally

**Comment by indrawind48** [comment]
> Change the APP_URL in .env file
> `APP_URL=http://voyager.test`

solve my problem. i wonder why other people dont get this issue. haha thanks alot

**Comment by mblaanco** [comment]
> Change the APP_URL in .env file
> `APP_URL=http://voyager.test`

THAAAANK YOU  DUD!

**Comment by mblaanco** [comment]
> Change the APP_URL in .env file
> `APP_URL=http://voyager.test`

THAAAANK YOU  DUD!
