### ISSUE TITLE
Forced to upload image

### ISSUE THREAD

**Issue by aemaddin** [thedevdojo/voyager#3358]
## Version information

 - Laravel: v5.6.0
 - Voyager: v1.1.3
 - PHP: 7.2
 - Database: MySQL 5.6

## Description

After added a new record into a model called "Place", I tried to edit this record into a crud form, But it keep showing me that the "multiple image" file is required.

## Steps To Reproduce
1. Go to 'Tools->Database'
2. Edit any model
3. Add field as String
4. Go to "Tools->BREAD"
5. Edit the same model that you edited in Database
6. Change "input type" to "multiple images"
7. Try to add new record from the form
8. Try to edit this record and change anything without touching the multiple images field

## Expected behavior
Should save the changes without ask me to add another image

## Screenshots
<img width="1192" alt="screen shot 2018-06-27 at 7 59 05 pm" src="https://user-images.githubusercontent.com/11630742/41992152-f1b77b16-7a47-11e8-9e5a-d5ee1e199dc1.png">

**Comment by ghost** [comment]
Same problem here

**Comment by hooch** [comment]
Same problem also happens when editing a user avatar under Edit Profile

**Comment by fletch3555** [comment]
This happens when a file or image field is marked "required".  Short term solution is to simply not mark it as required.

**Comment by minhdanh** [comment]
In my case I don't set the field as required, but it always asks to select a file when editing.

**Comment by DrudgeRajen** [comment]
#3716

**Comment by MrCrayon** [comment]
I think this one has been solved. 

If you are still experiencing this problem please open another issue.
