### ISSUE TITLE
how do i create a custom view and controller?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3362]
## Version information

 - Laravel: v5.6
 - Voyager: Latest
 - PHP: 7.2.6
 - Database: [MySQL] [10.1.33]

## Description of problem

Is there a way to create a custom view and controller? i tried following the documentation here https://voyager.readme.io/docs/using-custom-http-controllers but it is very brief as i am ensure of what i should do.  I have tried creating a resource controller and a blade file in the app\resources\views and added in web.php file but whenever i try to access the url it says "Sorry, the page you are looking for could not be found."

**Comment by fletch3555** [comment]
`Latest` is not a valid version for Voyager.  Please make sure all issues include the appropriate information.

For your issue, our apologies, that documentation is out of date anyway.  If you want a custom controller, then just create it, extending `TCG\Voyager\Http\Controllers\BaseController`.  That controller will automatically try to find the default views under the voyager namespace, so you can override them by custom view files at `resources/views/vendor/voyager/[BREAD slug name]/[action].blade.php`, where `[action]` is either `browse`, `read`, or `edit-add`.  If you need anything more custom, you're free to expand on this with your own.
