### ISSUE TITLE
No access to Bread section after upgrade when using seperate user_admin table

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#3365]
## Version information
 - Laravel: v5.6.26
 - Voyager: v1.1.3
 - PHP: v7.1.7
 - Database: MySQL 5.7.22

## Description
I am using a separate table for voyager admins and my default Laravel users. I asked how to do this here: https://github.com/the-control-group/voyager/issues/2568
I followed the update guidelines. Everythings is working except if I try to access `mypage.com/admin/bread` I get the error 

>  Trying to get property of non-object
![image](https://user-images.githubusercontent.com/1765602/42105994-b2406dee-7bd2-11e8-8dd3-ad4addd5ede9.png)

## Steps To Reproduce
-Install Voyager 1.0
-Create a separate table `voyager_users` for admins as described at https://github.com/the-control-group/voyager/issues/2568
-Follow the guide from https://voyager.readme.io/docs/10-to-11 and make sure to rename `users` into `voyager_users` in the migration files mentioned in the 

## Expected behavior
See bread page

## Additional Stuff
I also have custom voyager controllers. So I cahnged the `VOyagerBreadController` as follows:

```
<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerBreadController;

class VoyagerBreadController extends BaseVoyagerBreadController
{
    //
}
```
as descripded in the upgrade guide. I also had to add a VoyagerBaseController

```
<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerController;

class VoyagerBaseController extends BaseVoyagerController
{
    //
}
```

**Comment by emptynick** [comment]
I dont think that this is related to your users table.
`/bread` should point to the `VoyagerBreadController`, not to the `VoyagerBaseController` (see [here](https://github.com/the-control-group/voyager/blob/1.1/routes/voyager.php#L112))
Do you have overriden controllers and or routes?

**Comment by niels-numbers** [comment]
@emptynick Thank you for your answer. Before I could read your answer I was adding exactly that: how I changed the `VoyagerBaseController` in the OP. Maybe I have done it wrong?

**Comment by fletch3555** [comment]
That's simply stating that VoyagerBaseController is where the exception was thrown, but it's not necessarily where the issue is.  Since it's the index method, this is likely the parent class of whatever controller the route is intended for.  A full stacktrace should identify which controller was intended.  Also, the output of `php artisan route:list` might help as well.

**Comment by niels-numbers** [comment]
@emptynick its stated in the upgrade guide https://voyager.readme.io/docs/10-to-11

> If you have any custom controllers, you will need to update the parent class from VoyagerBreadController to VoyagerBaseController. This change was necessary due to a refactoring of the UI for creating/editing BREAD.

I though this means that I need to have the `VoyagerBaseController` and the `VoyagerBreadController` in my `App\Http\Voyager\` folder and both have the same parent, namley `VoyagerBaseController`? So yes, `/admin/bread`  points to the bread controller, but that controller has the `VoyagerBaseController` as his parent.

@fletch3555 here is the relevant part of the route list:
![image](https://user-images.githubusercontent.com/1765602/42124104-4b8a348c-7c5d-11e8-82f4-20b8482fd8f0.png)

And here is a screenshot with the full stacktrace (?) 
![image](https://user-images.githubusercontent.com/1765602/42124121-7936c7a6-7c5d-11e8-838b-f559ba4ce8a4.png)

It says that I have no permission, but I have set the permission entry in the table for bread:

![image](https://user-images.githubusercontent.com/1765602/42124243-5c49380c-7c5f-11e8-881a-d4308d233d7e.png)


Also I noticed that in the upgrade docs https://voyager.readme.io/docs/10-to-11 it is mentioned:

> The voyager.php configuration file has had a few changes. The prefix key has been removed in favor of the user.redirect key. Please note that the user.redirect key should be prefixed with a slash (/), unlike the original prefix key.

I could not find a `user.redirect` key. Also the `prefix` key was still there on line 109.

**Comment by niels-numbers** [comment]
Alright I figured it out, I forgot to also add an entry to the table `permission_role`

**Comment by fletch3555** [comment]
You certainly don't need VoyagerBaseController or VoyagerBreadController copied to your App/... directory. That step in the upgrade guide is simply saying you need to change any custom controllers to use `extends VoyagerBaseController` instead of `extends VoyagerBreadController` (with the appropriate `use` statement or fully-qualified namespace, of course)
