### ISSUE TITLE
Problem on Custom relationship attribute and relation belongsToMany

### ISSUE THREAD

**Issue by Smocrate** [thedevdojo/voyager#3366]
## Version information

 - Laravel: v5.6.26
 - Voyager: v#.#.#
 - PHP: 7.2
 - Database: MySQL

## Description:
I have 3 tables : civils | vehicules | vehicule_civil
I have relations : 
Civil (HasMany) Vehicule [on vehicules.proprietaire_civil_id]
Vehicule (BelongsTo) Civil [on vehicules.proprietaire_civil_id]
Vehicule (BelongsToMany) Civil [with vehicule_civil table]
That is working find when I display civil->name or civil->firstname

I when to display "NAME Firstname" of user.

On Civil model I added : 
```
    public $additional_attributes = ['full_name'];

    public function getFullNameAttribute()
    {
    	return strtoupper($this->nom)." ".$this->prenom;
    }
```
On Vehicule BREAD I can select full_name on display.
By I have an error message : 
```
ErrorException (E_ERROR)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'field list' (SQL: select `full_name` from `civils` inner join `vehicule_civil` on `civils`.`id` = `vehicule_civil`.`civil_id` where `vehicule_civil`.`vehicule_id` = 15 and `civils`.`deleted_at` is null) (View: /homepages/42/d741429225/htdocs/lspd2/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php) (View: /homepages/42/d741429225/htdocs/lspd2/vendor/tcg/voyager/resources/views/formfields/relationship.blade.php)
```

This method is working find when it's a simple field (BelongsTo) but not with (BelongsToMany)

**Comment by emptynick** [comment]
This will be fixed when https://github.com/the-control-group/voyager/pull/3268 is merged/released.
If you want you can check-out this PR and approve it if it works for you!

**Comment by Smocrate** [comment]
Hello @emptynick 
Thanks for your answer. However, I don't know how to install this new release :x 
Can you tell me the process ?
And if my work won't be delete by this update.

**Comment by emptynick** [comment]
If you didnt change anything in `vendor/tcg/voyager` (which you never should) there wont be any problems.
[Here](https://stackoverflow.com/a/47610532) is how you can checkout a specific commit.
In this case, the commit-key is `#31a7a9643184d5120f7d7696081e5edcc1c3a296`

**Comment by Smocrate** [comment]
I didn't install with git but with composer. Is-it possible to update with it ?

**Comment by Smocrate** [comment]
Ah : ok I understand your previous message.

I have to put this line : 
```
"require": {
...
        "tcg/voyager": "master#31a7a9643184d5120f7d7696081e5edcc1c3a296"
    },
```
correct ?

**Comment by fletch3555** [comment]
Correct.  Also, Voyager version is required when opening issues.

**Comment by markpenaranda** [comment]
Why is this tagged as closed? I still encounter the bug in version 1.1.5

**Comment by maxmadknight** [comment]
I have add additional_attributes and there is no output for them at all, i have fond 1 place of using it it is in database view, and even there it is not presented right

**Comment by moisesh18** [comment]
I still encounter the bug in 1.2...
