### ISSUE TITLE
Saved Or Updated Values Not Reflecting.. Needed To Reload The Page To See It.

### ISSUE THREAD

**Issue by allanfatweb** [thedevdojo/voyager#3369]
I've gotten voyager working fine on my installation.. No issues on the relationships and configurations.
However when I try to enter like a new content for example on the categories or pages once i submit it and it redirects to the browse listing page. It does not reflect it straightaway, I have to reload the pages for me to see my newly entered content.

Has anyone experienced it? Thanks.

**Comment by SteamWind** [comment]
Do you push the navigation back button when you are in the BREADs view?

**Comment by fletch3555** [comment]
Version information is required when opening issues(https://github.com/the-control-group/voyager/blob/1.1/.github/ISSUE_TEMPLATE/bug_report.md).  Without it, we don't know whether we're helping you debug the latest release, or troubleshooting something from the original `0.9.*` release.

This can be reopened when the required information has been provided

**Comment by allanfatweb** [comment]
hi sorry about that.. il provide the version info for laravel and voyager.

Laravel Framework 5.5.40
Voyager 1.1.3

Thanks

**Comment by allanfatweb** [comment]
Hi SteamWind, no im not pressing the back button.. so i update or create an entry and let the process execute.. i think voyager displays a success or error message on the upper right page in this case it is intermittent, sometimes it does and sometimes i needed to reload the page then the message just then displays.. not sure if it has something to do with the hosting provider or something else with voyager. Thanks.
