### ISSUE TITLE
how to change the folder where the files are stored

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3370]
## Description
Laravel 5.6 
Voyager 1.1 
PHP 7.2

## Proposed location for change
Hey , i had an issue whiletrying to display an image from the storage , i don t know how to get it , or just  change the folder where the files are saved .

Would you please tell me how . 
Thanks

**Comment by fletch3555** [comment]
Might I suggest not plugging the hole in the dam by building a second dam?

What's the issue you have with accessing files?

**Comment by hamzataougar** [comment]
I just resolved it . Thank you man !

**Comment by fletch3555** [comment]
No problem
