### ISSUE TITLE
How to display a pdf inserted in voyager laravel in the front-end

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3371]
## Description
laravel 5.6
php version:7.2
voyager 1.1

Hey , i wanted to display a pdf inserted in the admin panel voyager , and didnt know how to display it in the front end , i looked after it in the documentation and didn t find it , if u may help me i d be grateful 
and thank you so much

**Comment by hamzataougar** [comment]
Please if anyone can help me , am still stuck in the problem

**Comment by fletch3555** [comment]
Many modern browsers handle that natively.  I'm not really sure what you're expecting Voyager to do about it.

**Comment by hamzataougar** [comment]
isn t there any tip like for images ({{ Voyager::image( $post->image ) }} ) , that may help displaying pdf in the front end , am really stuck , didn t know how to do it

**Comment by ghost** [comment]
You can close it here too.

Reference [#24756](https://github.com/laravel/framework/issues/24756)
