### ISSUE TITLE
Trying to get property 'role' of non-object (View: /home/vagrant/code/vendor/tcg/voyager/resources/views/dashboard/sidebar.blade.php)

### ISSUE THREAD

**Issue by kawarien** [thedevdojo/voyager#3373]
## Version information

 - Laravel: v 5.6.*
 - Voyager: v 1.1
 - PHP: 7.1.7
 - Database: MySQL v 5.7
-  homestead: v 7.9

## Description:

Hello,

I installed vayager on an existing laravel project. if I try connected I have this error. 

## Additional context
![log](https://user-images.githubusercontent.com/36641497/42280114-5735f426-7f8f-11e8-9ef9-4155281677d0.png)

did I forget something or 
When does this happen ?  

thank you in advance.

**Comment by fletch3555** [comment]
Looks like Laravel Auth is seeing a logged in user, but Voyager is failing to find it, which leaves `$user` null and causes the error to show.  Are you doing anything custom with the user model? Using some other auth package? socialite or something maybe?

**Comment by kawarien** [comment]
at first it worked very well. when I tried to delete a user the error started. and that continuous I even deleted the data base and recreated it always shows me the error.  

I have a question, is it possible to create a user admin  via database? I know that in the doc for creating a user we do `php artisan voyager: admin your@email.com --create`

**Comment by fletch3555** [comment]
Yes, through the table associated with whatever user model you have Voyager configured to use. Only issue would be the password field, which needs to be hashed properly

**Comment by kawarien** [comment]
I was using the hyn package allowing me to automatically create the databases. the problem is that there are records that point to the id of the deleted user. I resolved them by just recreating the main database and making a new migration.

**Comment by mostafa20160424** [comment]
in TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser
replace only the function

    protected function removeRelationshipField(DataType $dataType, $bread_type = 'browse')
    {
        $forget_keys = [];
        foreach ($dataType->{$bread_type.'Rows'} as $key => $row) {
            if ($row->type == 'relationship') {
                 if(is_string($row->details)){
                 $row->details = json_decode($row->details);
                }
                if ($row->details->type == 'belongsTo') {
                    $relationshipField = @$row->details->column;
                    $keyInCollection = key($dataType->{$bread_type.'Rows'}->where('field', '=', $relationshipField)->toArray());
                    array_push($forget_keys, $keyInCollection);
                }
            }
        }

        foreach ($forget_keys as $forget_key) {
            $dataType->{$bread_type.'Rows'}->forget($forget_key);
        }
    }
you will be need also to add this line 
        <?php
         if(is_string($relationshipDetails )){
            $relationshipDetails = json_decode($relationshipDetails);
        } 
        ?>
in vendor\tcg\voyager\resources\views\tools\bread relationship-partial.blade.php on line 53

you will need add also this line
             if(is_string($row->details)){
                $row->details = json_decode($row->details);
            }
in TCG\Voyager\Http\Controllers\Controller on line 66
