### ISSUE TITLE
what is Allow tagging and how to use it ?

### ISSUE THREAD

**Issue by lqchinh88** [thedevdojo/voyager#3376]
## Description
When creating new Belongs to many relationship, there's an option "Allow tagging", what is it and how to use it ? When I try using it and try creating a new item, I got this message: 
`Route [voyager.tags.store] not defined. (View: `
My guess is this is Voyager's inbuilt tagging system, but there's no documentation on how to use it at all. Please provide

## Proposed location for change
A link or description of where, in your opinion, this change would best fit in our current documentation.

## Additional context
Any relevant links or other information to justify this change.

**Comment by emptynick** [comment]
It is now in our docs:
https://docs.laravelvoyager.com/core-concepts/bread-builder#tagging

**Comment by damms005** [comment]
@emptynick the link is broken

**Comment by Braiani** [comment]
@damms005 here's the correct link: https://voyager-docs.devdojo.com/bread/introduction#tagging
