### ISSUE TITLE
How to translate breadcrumb items?

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#3379]
I need to change voyager language. I made it like %99. But can't change breadcrumb items. 
Like "Create, Edit". How can i change breadcrumb items. Its looks like this: 

`@for($i = 1; $i <= count(Request::segments()); $i++)
                        <?php $breadcrumb_url .= '/' . Request::segment($i); ?>
                        @if(Request::segment($i) != ltrim(route('voyager.dashboard', [], false), '/') && !is_numeric(Request::segment($i)))
                            @if($i < count(Request::segments()) & $i > 0 && array_search('database',Request::segments())===false)
                                <li class="active"><a
                                            href="{{ $breadcrumb_url }}">{{ ucwords(str_replace('-', ' ', str_replace('_', ' ', Request::segment($i)))) }}</a>
                                </li>
                            @else
                                <li>{{ ucwords(str_replace('-', ' ', str_replace('_', ' ', Request::segment($i)))) }}</li>
                            @endif
                        @endif
                    @endfor`

create and edit strings are coming from here.
`<li>{{ ucwords(str_replace('-', ' ', str_replace('_', ' ', Request::segment($i)))) }}</li>`

I am trying to change that strings. How can i make that? If anyone can help. I would glad.

**Comment by fletch3555** [comment]
Please follow the [appropriate template](https://github.com/the-control-group/voyager/tree/1.1/.github/ISSUE_TEMPLATE) when submitting issues.
