### ISSUE TITLE
Exception: file_put_contents..........failed to open stream: Permission denied

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#338]
- Laravel Version: 5.2.16
- Voyager Version: 0.9.34
- PHP Version:5.6.28
- Database Driver & Version:

### Description:
Tools->Database->Create New database
Create model for this table? -> yes
..
Click "Create new database" button, then get error message:

Exception: file_put_contents(/var/www/html/......./app/xxx.php): failed to open stream: Permission denied

**Comment by handiwijoyo** [comment]
@jun283 make sure your root project /app folder is writable.

**Comment by jun283** [comment]
yes, I set /app to 777, solved this problem

thanks

**Comment by Mostafakram** [comment]
Laravel Version: 5.5.28
Voyager Version: 1.0.13
PHP Version: 7.1.12


i am having the issue 'storage/framework/views/1e74dd7e54dbd62233314c4a41e7ead7ebc19501.php): failed to open stream: Permission denied' from the file_put_contents method and have changed the permissions to 777 as told but still can't open any thing from the menu neither the database not my breads
