### ISSUE TITLE
Unable to run any artisan commands from compass

### ISSUE THREAD

**Issue by faraztanveer** [thedevdojo/voyager#3380]
## Version information

 - Laravel: v5.6.26
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MYSQL

## Description:
i am unable to run any artisan commands from voyager Compass. i get the following error
Exit Code: 1(General error)

## Additional context
![err](https://user-images.githubusercontent.com/23014681/42390310-e48cf866-8164-11e8-912f-86a1baa9cb38.PNG)

**Comment by fletch3555** [comment]
That's a system issue, not a Voyager one.  Whatever server you have running Laravel (and by association, Voyager), does not have php available on the system path.

**Comment by faraztanveer** [comment]
i can run php artisan commands n console

**Comment by fletch3555** [comment]
The error tells me you're running on Windows, so I can only assume this is your local environment.

What console are you using to run the artisan commands? `cmd`? `powershell`? `cygwin`?

**Comment by faraztanveer** [comment]
i am running this on windows with cmd, and local environment are set correctly. problem only come when i run this via voyager compass.
