### ISSUE TITLE
Additions to User field BREAD not reflected in Edit

### ISSUE THREAD

**Issue by marvz73** [thedevdojo/voyager#3382]
## Version information

 - Laravel: v5.5.40
 - Voyager: v1.1.3
 - PHP: 7.1.6
 - Database: MySQL(v5.6.35)

## Description

After I update my voyager from 1.0 to 1.1 and edit the user BREAD. When I go to user to edit, I didn't show those fields I've added. Even I delete the existing BREAD and create again, still not working.

Same issue with [1132](https://github.com/the-control-group/voyager/issues/1132)

## Screenshots
<img width="1473" alt="screen shot 2018-07-07 at 10 22 36 am" src="https://user-images.githubusercontent.com/3580175/42405875-143e5422-81d0-11e8-8789-27323a61452e.png">
<img width="1360" alt="screen shot 2018-07-07 at 10 23 12 am" src="https://user-images.githubusercontent.com/3580175/42405876-1491f6c2-81d0-11e8-83bf-e6b123e854fe.png">

**Comment by marvz73** [comment]
OK, I found a fix. I [override](https://voyager.readme.io/v0.11/docs/overriding-views) the vendor voyager user view add-edit.blade.php and instead of using the user add-edit.blade.php I use the bread add-edit.blade.php

**Comment by trippo** [comment]
You must do this on resources/views/vendor/voyager/users/edit-add.blade.php.
Because on vendor after composer update you lost changes

**Comment by trippo** [comment]
Consider to add this to your webmix
`.copy('vendor/tcg/voyager/resources/views/bread/edit-add.blade.php', 'resources/views/vendor/voyager/users/edit-add.blade.php')`

**Comment by emptynick** [comment]
Thats not a good idea.
It will override his custom view everytime he runs `npm run X`.
Also this issue is closed for more than a year and he found the proper solution already.
