### ISSUE TITLE
how to fix new users authentification

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3387]
## Description
Laravel 5.6 
PHP 7.2 
Votager 1.1 

Hey ,
I got an issue while i create a new user in laravel voyager , it tells me that it s created and got a role , then right after once i want to connect with the credentials of the new user , it takes me to the index of my front-end .

this picture is for the user created :
![image](https://user-images.githubusercontent.com/21199501/42503744-66543246-8431-11e8-9fa4-e5bf9ae50372.png)

the second one is what i get when i try to connect with the new user : 
![image](https://user-images.githubusercontent.com/21199501/42503800-8b6d38e8-8431-11e8-9fd0-5181c8e82294.png)
 
if someone can help me i d thankful

**Comment by emptynick** [comment]
Does the test-role have the `browse_admin` permission which is required to `browse admin`?

**Comment by hamzataougar** [comment]
I guess that was the issue , how dumb ! 
thaank you a lot man
