### ISSUE TITLE
Relationships 

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3392]
PHP 7.1 
Voyager 1.1 
DATABASE : phpmyadmin (sql)

Hey Community , 
I got a problem while adding relationships to a table , i added 3 relationship to the table created . and they are successfully created : 
![image](https://user-images.githubusercontent.com/21199501/42605098-ff7e4e10-856d-11e8-9d17-a1bd974df068.png)

then when i try to add an item , those foreign keys's select dropdown shows with only none value : 
![image](https://user-images.githubusercontent.com/21199501/42605147-3e2dbe70-856e-11e8-9f8b-c051bea82a29.png)
 
please if someone knows how to fix it , id be thankful

**Comment by emptynick** [comment]
You need to be more precise about what not working and how your relationships look like.
I can see that there are empty options in the select, so maybe you just chose the wrong column?

**Comment by hamzataougar** [comment]
those are my relationships , every"note" belongs to "one commune" and it s the same for the three foreign keys 
![image](https://user-images.githubusercontent.com/21199501/42643930-3952432e-85f2-11e8-9e5c-d284b2cfc5f3.png)

if it shows that i made an error please tell me where it is

**Comment by hamzataougar** [comment]
people i got stuck , is anyone here to help . Thanks
