### ISSUE TITLE
Overriding view by creating vendor is not working, Displays the default page

### ISSUE THREAD

**Issue by shagal-sajid** [thedevdojo/voyager#3402]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.3
 - PHP: 7.2.6
 - Database: MariaDB 10.1.34

## Description

For overriding existing view of both settings and posts, as directed I have created a vendor folder inside the `resources/views` inside the root . then I tried `index.blade.php`, `browse.blade.php`, `edit-add.blade.php`. None of them changed any of the view and later I tried to modify the view from the package forlder. which is inside `vendor/tcg/voyager/resources/setting/index.blade.php`
but that too did not work

It will be much better if you provide more elaborate documentation for both users and contributers

Thank you
## Screenshots
![image](https://user-images.githubusercontent.com/33257942/42736895-5fd57ca0-888b-11e8-96ca-c94c91591627.png)

but
![image](https://user-images.githubusercontent.com/33257942/42736904-7ebe833c-888b-11e8-8fa5-c219f83f9978.png)

**Comment by fletch3555** [comment]
Well first, your path is wrong.  Please re-read the documentation on overriding views.  It should be `..../vendor/voyager/settings/`, not `..../vendor/settings/`

Our documentation is supplementary to the official Laravel docs.  Between the two, I believe there is enough information.  However, the docs provide a means to suggest edits, so you're free to do so if you believe something is truly missing.
