### ISSUE TITLE
can't install and when call admin panel 404

### ISSUE THREAD

**Issue by maungyehtunzaw** [thedevdojo/voyager#3403]
![image](https://user-images.githubusercontent.com/5591177/42804106-f20c6c58-89cd-11e8-9818-3597890ea287.png)

**Comment by emptynick** [comment]
Please [search](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+Mysql+42000) before opening an issue.

Also, all informations from the issue template are required when opening issues.
