### ISSUE TITLE
Point Column in database unencoded text

### ISSUE THREAD

**Issue by khaledafify** [thedevdojo/voyager#3404]
## Version information

 - Laravel: v5.6.27
 - Voyager: v1.1
 - PHP: v7.2.7
 - Database: Mysql v5.7.22

## Description

when i retreive the coordinates column from database i receive unencoded value 
Like :- b"\0\0\0\0\x01\x01\0\0\0tv¬M¬\x11?@o¥H\x0Fa\x1A>@"

DB Column is POINT

## Steps To Reproduce
1. Go to Add New X
2. Select location 
3. Click on save'
4. retreive the inserted item from any controller

## Expected behavior
to retreive a column value POINT(31.20795236073 30.057886617425)

**Comment by fletch3555** [comment]
This is expected, since MySQL doesn't store Spatial data in plain text, which is how you're likely getting it.

Please take a look at how Voyager retrieves that data: https://github.com/the-control-group/voyager/blob/1.1/src/Traits/Spatial.php
