### ISSUE TITLE
how to display multiple images 

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3406]
Php: 7.2 
Voyager: 1.1
How to loop through images in multiple images attribute in database

people , i got an issue while diplaying multiple images , i tried the {{ Voyager::image($sld->image) }} property and it didn t work , is there any other property which it makes looping the array .
![image](https://user-images.githubusercontent.com/21199501/42904453-09fbd4a2-8acd-11e8-8748-d1592b5a5cd6.png)

thanks

**Comment by fletch3555** [comment]
The field holds a JSON-encoded array of paths.  Just `json_decode()` it, loop over the result, and display them individually within the loop.

**Comment by hamzataougar** [comment]
thanks

**Comment by hamzataougar** [comment]
Please , this is the code i used to retrieve those multiple photos but i still get an error : 

![image](https://user-images.githubusercontent.com/21199501/43030750-d703d09c-8c8c-11e8-80e1-47a5f9488de8.png)

and the error i get is this one : 
![image](https://user-images.githubusercontent.com/21199501/43030759-f5a89820-8c8c-11e8-80f0-ea5d5ff03f13.png)

**Comment by emptynick** [comment]
Please read again what @fletch3555 wrote.
You have to `json_decode` everything first, **then** loop through them
