### ISSUE TITLE
Cuztomizing Widget doesn t work 

### ISSUE THREAD

**Issue by hamzataougar** [thedevdojo/voyager#3407]
Hey , 

I watched the video about custom widget , and right when i change in the config/voyager.php nothing changes , if you can help please . 
![image](https://user-images.githubusercontent.com/21199501/42998323-b49659ce-8c11-11e8-8d83-5fcd4db02d13.png)

and yet it s what i get 
![image](https://user-images.githubusercontent.com/21199501/42998349-c26a0b72-8c11-11e8-9d5d-8af6d1e9c7e3.png)

thanks .

**Comment by fletch3555** [comment]
Are your views cached? What about the config?  You can clear that by running the respective artisan commands.

**Comment by hamzataougar** [comment]
it worked , thanks

**Comment by sajjadintel** [comment]
run 
```
php artisan  config:cache 
php artisan view:clear    
```

**Comment by fletch3555** [comment]
Don't comment on closed issues, especially when the last comment indicates it was solved.
