### ISSUE TITLE
How to create a relationship between a new post type like products and categories table as you did with posts ?

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#341]
- Laravel Version: 5.3
- Voyager Version: 0.9.34
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:

How to create a relationship between a new post type like products and categories table as you did with posts ?

I'm trying use your GREAT package to create a simple e-commerce application, so I'm wondering how to link the categories with the "products" table&BREAD I created  as you did with the posts ?

THANKS.

**Comment by marktopper** [comment]
Just released `v0.10` with this feature.

**Comment by hazem1taha** [comment]
GREAT!!
I was waiting for the v0.10 release!
THANKS
