### ISSUE TITLE
After new install dash board is empty

### ISSUE THREAD

**Issue by rddewan** [thedevdojo/voyager#3410]
## Version information

 - Laravel: v5.6.28
 - Voyager: v1.1.3
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
after installing voyager i can see any thing in the dashboard 
![error](https://user-images.githubusercontent.com/13164167/43035991-08115bb6-8d2b-11e8-8e90-77f46f656366.png)

**Comment by fletch3555** [comment]
Looks correct to me. You didn't install with dummy data. The dimmer widgets that are shown in all of the examples are only preconfigured with dummy data.  You're welcome to create your own and add them to the Voyager config file, then they'll show up.
