### ISSUE TITLE
Admin and Accout in same View

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3411]
## Version information

 - Laravel: v5.6.28
 - Voyager: v1.1.0
 - PHP: 7.2
 - Database: mysql

## Description:
Hi, i need this admin view and Account View in one view like login as Privat Person customer
with url = test.us/admin
 test.us/customer

**Comment by fletch3555** [comment]
You're going to have to provide a lot more information before we can even attempt to answer that.  However, it sounds more like you need guidance rather than an issue with the package, so I'm going to close this.  Please ask your question in our Slack group instead
