### ISSUE TITLE
Undefined variable: dataType with overriding routes - Voyager 1.0

### ISSUE THREAD

**Issue by asistemastj** [thedevdojo/voyager#3415]
## Version information

 - Laravel: v5.5.40
 - Voyager: v1.0
 - PHP: 7.0
 - Database: MySQL

## Description
Hi, use overriding route to send data to a bread from voyager.

## Steps To Reproduce

1. My route
![route](https://user-images.githubusercontent.com/29926012/43089956-aceb70d6-8e6b-11e8-92fd-7cdee30157f7.PNG)
2. Controller
![controller](https://user-images.githubusercontent.com/29926012/43090005-ce4b02c8-8e6b-11e8-9bdd-9ded6b5ed775.PNG)

3. Browse
![browse](https://user-images.githubusercontent.com/29926012/43090016-d59f1a50-8e6b-11e8-8ae7-20a368930a39.PNG)

4. Error
![error](https://user-images.githubusercontent.com/29926012/43090057-efa12682-8e6b-11e8-9401-2c13cc04a08d.PNG)

**Comment by emptynick** [comment]
The error message tells you everything you need to know.
`$dataType` is not defined - easy.

**Comment by asistemastj** [comment]
Yes I know, DATATYPE is a variable of voyager. In the route voyager it is defined but when I add my route, the variable is confused.

**Comment by fletch3555** [comment]
You have a custom route, pointing at a custom controller, that renders a custom view... No part of this has to do with Voyager.  If your view tries to use a variable that the controller didn't pass it, you get this error.  That's very basic Laravel functionality.

Now to nitpick your code....

* Please don't use `view('vendor/voyager/.......')`... views should be referenced using their namespace, not path, so you can use `voyager::petroleo.browse` instead.
* Why are you overriding the route if this is a BREAD? Just set the controller namespace in the BREAD config, then all of this will just work.
* Your controller isn't extending Voyager's BaseController, so it's definitely not tied into Voyager at all

**Comment by asistemastj** [comment]
Hola,lo que yo trato de hacer es que en la lista de elementos de petroleo aparezca datos de una consulta sql y no de la base de datos de Voyager.Al igual que cuando creo una nueva lista.Por eso traté de sobreescribir las vistas.

**Comment by asistemastj** [comment]
Hello, what I try to do is that in the list of oil elements appear data from an sql query and not from the Voyage database. As when I created a new list. That's why I tried to overwrite the views.

**Comment by cesarrss** [comment]
@asistemastj  Did you fix it? 
@fletch3555 it´s incorrect or isecure show in a frontend user a BREAD made in voyager/Database
i know that $dataType is not defined, but when you extend other template (voyager::master) came with this variable...(i have a similar error, on wave that have voyager as admin backend)
so, how can i pass a BREAD to user forntend "safe" ???
