### ISSUE TITLE
How to adding a new Route::group with views and new custom Controllers

### ISSUE THREAD

**Issue by Smocrate** [thedevdojo/voyager#3418]
## Description
Nowaday we can customize Controllers and Overrize Views in Voyager.

But I don't find how I can create a new Controllers who used a new Views without any change in admin panel.
I would like to add a new Route::group "intranet" (like "admin") and use new views and customized Controllers.

In finally, we will have admin voyager panel available in /admin
and customized site available in /intranet (or whatever the name)

**Comment by fletch3555** [comment]
That has nothing to do with Voyager.  You want `/intranet...` sitting in parallel to `/admin...`, which means it's not part of laravel.  You're not making use of BREAD either.  Just build the pages per the Laravel docs.
