### ISSUE TITLE
Safari happen to error

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#3419]
Upgrade from 1.0.3 -> 1.1.3

Now, everything work fine.  

Except save content throw error only in Safari . Below is error msg 
**TypeError: r.set is not a function. (In 'r.set("_validate","1")', 'r.set' is undefined)**
![5117211d-86e1-4694-a61a-fafe7b52f61e](https://user-images.githubusercontent.com/20222136/43214405-b1540280-906b-11e8-883e-5ae5ea09dc42.png)

Chrome/Firefox work fine.

**Comment by OliverVin** [comment]
Solved ! 

        // Safari 11.1 Bug
        // Filter out empty file just before the Ajax request
        // https://stackoverflow.com/questions/49672992/ajax-request-fails-when-sending-formdata-including-empty-file-input-in-safari
        for (i = 0; i < this.elements.length; i++) {
            if (this.elements[i].type == 'file') {
                if (this.elements[i].value == '') {
                    continue;
                }
            }
            data.append(this.elements[i].name, this.elements[i].value)
        }
        data.set('_validate', '1');


/// safari not support data.set , change to data.append , it works .  My safari version is 10.1.1

**Comment by emptynick** [comment]
Are you able to create a PR to fix this?

**Comment by hooch** [comment]
I think #3546 should be a more reliable way to fix these problems.

**Comment by emptynick** [comment]
Closing as #3546 was merged.
Please let use know when this does **not** fix your problems (be aware, the PR was merged into 1.x)

**Comment by dportalesr** [comment]
I'm still seeing this issue on Edge `42.17134.1.0` with Voyager `v1.1.10`.
Could it be that the changes got lost [here](https://github.com/the-control-group/voyager/pull/3546/commits/db30728406a7c4d5d282dc000a67f7eee606885a)?

@emptynick 1.x means this fix will be released with voyager 1.2?

**Comment by hooch** [comment]
@dportalesr I believe there is some policy causing the maintainers to refuse to include any fixes that touch app.js until 1.2

**Comment by dportalesr** [comment]
@hooch Yeah, I found out about that on other conversations. Thanks.

Anyways, for what's worth, I was able to [workaround this issue](https://github.com/the-control-group/voyager/issues/3389#issuecomment-451705995).
