### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by liziliang123** [thedevdojo/voyager#3421]
## Version information

 - Laravel: v5.5.*
 - Voyager: v1.1.*
 - PHP: 7.1
 - Database: [MySQL 5.6] 

## Description

can't  save

## Steps To Reproduce
1. Go to 'admin'  ,  edit the posts or other
2. Click on 'save'
3. See error

## Expected behavior
app.js:24 Uncaught TypeError: r.set is not a function

## Additional context
after installed ,can't save page 、posts or other .
then the app.js error :app.js:24 Uncaught TypeError: r.set is not a function

**Comment by emptynick** [comment]
Duplicate of https://github.com/the-control-group/voyager/issues/3419

**Comment by hooch** [comment]
Should be fixed by #3546
