### ISSUE TITLE
Not searching traslations

### ISSUE THREAD

**Issue by borjajimnz** [thedevdojo/voyager#3422]
## Version information
 - Laravel: 5.6.15
 - Voyager: v1.1.3
 - PHP: 7.1.14
 - Database: Mysql

## Description:

I'm trying to search a page by it translated slug but is not working, the row exists in translations table but is not finding nothing...

`$page= Page::withTranslation()->where("slug","=",$slug)->first();`

Im not sure also, if this is the correct way to do this, Ive read the documentation and don't see nothing about...

**Comment by emptynick** [comment]
Thats not supported out-of-the-box, but theres already a PR which will make it possible https://github.com/the-control-group/voyager/pull/3417

**Comment by borjajimnz** [comment]
thankss!
