### ISSUE TITLE
Method total does not exist - pagination

### ISSUE THREAD

**Issue by navalevivek** [thedevdojo/voyager#3423]
## Version information

 - Laravel: v5.5
 - Voyager: v1.1.1
 - PHP: 7.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
I am trying to add some filters into query on 'VoyagerBreadController.php' controller file into '$dataTypeContent' query section, but I am getting method total does not exist error, could anyone please reply on same.

Any help would be highly appreciated.

**Comment by emptynick** [comment]
You have to show us your query, otherwise we can't tell you what you are doing wrong.
Also, questions are better asked in our Slack group.

**Comment by emptynick** [comment]
Closing this for now.
Please provide more informations, or, even better, ask in our Slack group.
