### ISSUE TITLE
Tools dropdown menu not opening

### ISSUE THREAD

**Issue by sam961** [thedevdojo/voyager#3425]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1
 - PHP: 7.1.16
 - Database: MySQL

## Description

I have moved Tools Menu under one section. When I try to open the tools submenu under this section, it closes immediately . See screenshot

## Expected behavior
<img width="1439" alt="screen shot 2018-07-27 at 3 38 17 pm" src="https://user-images.githubusercontent.com/4921874/43320977-215fb554-91b3-11e8-8748-c5dc75d7f199.png">

## Screenshots
<img width="1439" alt="screen shot 2018-07-27 at 3 38 17 pm" src="https://user-images.githubusercontent.com/4921874/43320984-27d246ea-91b3-11e8-8f3e-c20302d71dec.png">

**Comment by fletch3555** [comment]
Voyager's admin menu only supports 1 level of nesting.
