### ISSUE TITLE
Upgrade to 1.1.3 not support image rules

### ISSUE THREAD

**Issue by OliverVin** [thedevdojo/voyager#3427]
{
    "default": "",
    "validation": {
        "rule": "image|max:8000"
    },
    "resize": {
        "width": "1500",
        "height": "null"
    }
}

before upgrade ,it is ok,    rule is image and limit 8M size. But upgrade , not support image, tips "The cover not is an image" !

**Comment by ManojKiranA** [comment]
where i want to add this

**Comment by fletch3555** [comment]
We have issue templates, please use them: https://github.com/the-control-group/voyager/tree/1.1/.github/ISSUE_TEMPLATE
