### ISSUE TITLE
Broken breadcrumb from BREAD management

### ISSUE THREAD

**Issue by dereks** [thedevdojo/voyager#3434]
## Version information
 - Laravel: v5.6.28
 - Voyager: v1.1.3 (Installed 2018-07-31)
 - PHP: 7.2.7
 - Database:  MySQL 5.7.22-0ubuntu18.04.1

## Description
Broken link in the breadcrumbs nav. It throws a Symphony MethodNotAllowedHttpException.

## Steps To Reproduce
Install Voyager with dummy data. Use the GUI to navigate to 

/admin/bread/categories/edit

But don't edit any fields or save any changes. Just go to that page.

Now click on the breadcrumb at the top of the pages that says "Categories". See the exception error.

## Expected behavior
No error.

## Additional context
I'm loving Voyager, thanks! But if you require people to know their Laravel and Voyager version numbers to file bug reports, please tell us how to find the Voyager version number. I couldn't find that info with a quick google or a grep -R.

Also, maybe include a note in the bug intro comments that the Laravel and PHP versions can be obtained with "php -v" and "php artisan --version", and MySQL with "mysql -v".

**Comment by emptynick** [comment]
> But if you require people to know their Laravel and Voyager version numbers to file bug reports, please tell us how to find the Voyager version number.

Its written in the footer ;)

**Comment by dereks** [comment]
> Its written in the footer ;)

Oddly, I cannot see the footer ("Made with love by The Control Group...") unless I manually scroll down any /admin/ page with my mouse. Even if I view it full screen at 1920x1200px, the footer is hidden below the bottom of my screen.

It's like they hid the version number on purpose! :)

**Comment by emptynick** [comment]
Just hiding unnecessary things to have room for stuff that really matters ;)

Just checked what you descibe and see the same error.
