### ISSUE TITLE
Security: Voyager compass commands requires an unsafe Apache installation

### ISSUE THREAD

**Issue by dereks** [thedevdojo/voyager#3437]
## Version information
 - Laravel: v5.6.28
 - Voyager: v1.1.3 (Installed 2018-07-31)
 - PHP: 7.2.7
 - Database:  MySQL 5.7.22-0ubuntu18.04.1

## Description

Under /admin/compass > commands.

Some of the "php artisan ..." commands require write permissions on the filesystem, for example, all of the "php artisan make:..." commands create new PHP files. 

But this is unsafe, against best practices, and presents an attack vector: the web server User ID (like "www-data" on Linux Apache) should not have write permission to any directory under DocumentRoot, aside from the ones listed in the Laravel docs: **./bootstrap/cache** and **./storage**. (Those two special directories are managed by the PHP code and have permission logic.) In contrast, if the web server can write executable PHP files, the webserver can (maybe) be tricked into writing a PHP file that will cat /etc/passwd (or whatever other attack). 

## Expected behavior

Laravel should not offer a GUI feature that requires an unsafe installation by default. If it is necessary to offer "php artisan ..." commands that write PHP files, then those php artisan commands should be restricted in an /etc/sudoers file to run as the user who owns all of Laravel's PHP files (such as user 'laravel' or maybe user 'root' if using a V.M. or appliance O.S.). The Voyager documentation should explain the risks and give clear setup instructions.

However, since creating new PHP files is only something that is done during development, and should never be done on a production Laravel installation, perhaps this feature should only be present when APP_DEBUG=true. That way developers can use these handy commands on their unsafe dev environments (like their VMs), but the feature would disappear once it is on a production server. That's probably better than setting up a hand-crafted sudo environment.

I would either (a) remove the feature or (b) make it only run with APP_DEBUG=true. But if you want to keep it functional as currently designed, please create docs on how to use sudo appropriately and the risk associated with a web server that can write its own PHP files...

## Additional context

Bug #3267

**Comment by fletch3555** [comment]
This package has no control over how you manage your system.  If you want to add those commands to a sudoers file to make it more secure, by all means (Voyager has no possible way of automating this for you).  If you want to restrict write access to the `www-data` user as a security practice, then go ahead, and those commands will simply fail.

Just because we provide a feature, doesn't mean it's 100% secure without manual intervention.

**Comment by dereks** [comment]
> Just because we provide a feature, doesn't mean it's 100% secure without manual intervention.

With respect, I am stunned by this attitude.  This is the opposite of "Secury By Default", and is not what businesses want to hear.

https://en.wikipedia.org/wiki/Secure_by_default

A PHP-based administrator panel, of all things, should put security first.

**Comment by fletch3555** [comment]
I agree that security should be (and is) a concern for this package, however you've essentially suggested that Voyager should manage/configure your server at the OS level by editing `/etc/sudoers`, which is equally ridiculous.  It's not our job to tell you how to harden your system security.  We as a package provide functionality.  If _you_ wish to use that functionality in a production environment, _you_ will need to ensure it's working in a secure manner, i.e. by restricting write access or editing the sudoers file.

I'm not dismissing your concerns.  I'm dismissing your suggested solution.

**Comment by dereks** [comment]
Thanks for the clarification. I'm loving Voyager and I appreciate the time and effort you put into it.

Some quick notes:

> [It is ridiculous that] Voyager should manage/configure your server at the OS level by editing /etc/sudoers

Agreed, Voyager should not edit /etc/sudoers. I meant only that the administrator would use sudo to allow the webserver to run a limited and pre-approved set of commands, as you described. Other PHP apps do this too, to e.g. schedule cron jobs, manage containers, or edit .sieve or .procmailrc files.

>  It's not our job to tell you how to harden your system security. We as a package provide functionality.

It's an admin panel. The Voyager documentation should explain the risks and give clear setup instructions for a secure deployment. It is not reasonable to expect users to read source code to understand what vulnerabilities are introduced by simply installing the package.

This exact example (webserver admin permissions) is even used in the intro to 

https://en.wikipedia.org/wiki/Secure_by_design
