### ISSUE TITLE
different Breads in a table for different users role. ( Is possible? )

### ISSUE THREAD

**Issue by quanticbyte** [thedevdojo/voyager#3442]
## Version information
 - Laravel: v5.6.29
 - Voyager: v1.11
 - PHP: 7.2.7
 - Database: MySQL 5.7.22

## Description:
different Breads in a table for different users role.

## Additional context

Good, I would like to know if it is possible to create different Breads for different user roles, if not, what is the best way to modify the view and the functions for each one?
Thanks in advance

**Comment by emptynick** [comment]
This has been discussed a few times before, for example in #1926 or #1893
Also, questions are better asked in our Slack group.

**Comment by quanticbyte** [comment]
ok, thanks, I wanted to know if there was something new on the topic since the posts are from 2017

**Comment by youssef3wi** [comment]
can i hide column with model when $user->hasRole('user') ?
