### ISSUE TITLE
Missing "editRoles" permission when editing/creating new user!

### ISSUE THREAD

**Issue by putchi** [thedevdojo/voyager#3452]
## Version information

 - Laravel: v5.6.29
 - Voyager: v1.1.3
 - PHP: 7.2.8
 - Database: MySQL 5.7.21

## Description
cannot add/edit Roles for admin user missing editRoles permission!
file: vendor/tcg/voyager/resources/views/users/edit-add.blade.php
line: 63
code: `@can('editRoles', $dataTypeContent)`

## Steps To Reproduce
1. Login as Admin
2. Go to edit user page
3. cannot edit or add any role.

## Expected behavior
admin user should have the ability to edit role!

## Screenshots
![screen shot 2018-08-07 at 15 55 41](https://user-images.githubusercontent.com/10920796/43777146-a036fe5a-9a5a-11e8-823b-552ec7c89836.png)
![screen shot 2018-08-07 at 15 58 16](https://user-images.githubusercontent.com/10920796/43777313-100349dc-9a5b-11e8-8938-61aba398935b.png)
![screen shot 2018-08-07 at 15 59 13](https://user-images.githubusercontent.com/10920796/43777314-10292544-9a5b-11e8-93d6-4a427a79167b.png)

## Additional context
cannot find any permission that was mentioned in the users.edit-add.blade.php

**Comment by emptynick** [comment]
Its [here](https://github.com/the-control-group/voyager/blob/717b31f0368cb3e0cb5468fbca34ca410f8ce0b2/src/Policies/UserPolicy.php#L49).
And its wanted that a user can not edit his own roles.

**Comment by putchi** [comment]
@emptynick maybe edit his own role OK but creating new user should be the option to chose a role for him.

![screen shot 2018-08-07 at 16 10 32](https://user-images.githubusercontent.com/10920796/43777855-af1936fc-9a5c-11e8-838f-b0dd127d5952.png)

**Comment by putchi** [comment]
Solved it by adding "TCG\Voyager\Policies\UserPolicy" to the BREAD for the Users as its policy.
it couldn't find a default policy to use when was left empty.

**Comment by emptynick** [comment]
Then your own role (from the user creating another user) does not have the permission to `edit_users` (only `add_users` maybe)

**Comment by emptynick** [comment]
Thats the [default policy](https://github.com/the-control-group/voyager/blob/1.1/publishable/database/seeds/DataTypesTableSeeder.php#L21) by the way. Maybe dont change it.

**Comment by putchi** [comment]
@emptynick I know it is the default policy, apparently voyager couldn't find the default policy when this field was left empty. 
I had to manually insert this value to the input in order to solve this.

**Comment by fletch3555** [comment]
If you upgraded from an older version, that field may have been blank, but a new install should have it set: https://github.com/the-control-group/voyager/blob/1.1/publishable/database/seeds/DataTypesTableSeeder.php#L21

**Comment by MrCrayon** [comment]
@emptynick
>And its wanted that a user can not edit his own roles.

Let's be more clear: a user can edit it's own role, the choice is only hidden.

I think it's important that people know this so they can fix it on their own if it's a problem on their implementation.

**Comment by emptynick** [comment]
We are working on this, and we know that there are a few open PRs which will resolve this.
Its just a "bad time" as we are all on vacation or (me for example) very very busy at work,
but it will be solved soon.

**Comment by MrCrayon** [comment]
@emptynick 
Thanks for your reply, I'm just trying to keep the issue alive and of course I'll try to help as I can.

**Comment by putchi** [comment]
I'll reopen this issue then...

**Comment by emptynick** [comment]
The issue is solved. The discussion was a bit off-topic

**Comment by huuloc4193** [comment]
that user has been created by manual. So that, you should update user w/ full acess to your site:
`php artisan voyager:admin admin@gmail.com`
*admin@gmail is created by yourself
