### ISSUE TITLE
Overriding Views not working for me

### ISSUE THREAD

**Issue by gopalappu1** [thedevdojo/voyager#3455]
- Laravel: v 5.6
 - Voyager: v1.1
 - PHP: 7.0
 - Database:mysql

## Description:
i am trying to override a view and its not working for me,

as suggested in doc, 
i have created folder as Myproject/resource/views/vendor/voyager/{slug}
created a hello there file in the name of browse.blade.php

when i refresh the page, its not talking... instead refers to tcg/voyage..../browse.blade.php

**Comment by emptynick** [comment]
Please post the full path to the file you have created plus the slug of the bread you want to override.

**Comment by gopalappu1** [comment]
As of now issue is resolved.. 
initaily i created a table and model in the name of product then deleted it.
created with name products.

orverride works with old one product. might be my mistake..
