### ISSUE TITLE
Reporting and Statistics 

### ISSUE THREAD

**Issue by gopalappu1** [thedevdojo/voyager#3459]
Laravel: v5.6.29
Voyager: v1.1.3
PHP: 7.2.8
Database: MySQL 8.0.12

this is not an issue. 

Need suggestion from you. which reporting / statistics package will go smooth with voyager.

i want show some MIS reports like day wise activation , day wise request recieved ...
total activation group by sales person...

**Comment by fletch3555** [comment]
This kind of question is best asked on Slack, not here.

But to answer it, we have not tested any such package, and therefore cannot provide any official recommendations.
