### ISSUE TITLE
Is it possible  to make dependent relationships  ?

### ISSUE THREAD

**Issue by RattleSneyk** [thedevdojo/voyager#3460]
For example, I have a subway model, and when creating an entry, I need to select a metro, but the metro is tied to cities.
How can I make selectbox only those metro stations that are tied to cities?

**Comment by fletch3555** [comment]
[We have templates for a reason, please use them.](https://github.com/the-control-group/voyager/tree/1.1/.github/ISSUE_TEMPLATE)  If you have a question that doesn't neatly fit into one of those templates, then it's probably best asked in Slack instead.

To answer your question, no, Voyager does not directly provide any way of doing this.  It can be done, but would be completely custom.  Others have done it, and may be able to help you, but that would be done through our Slack or some other forum(LaraChat, Laracasts forums, etc), not here.

**Comment by kashif-saleem** [comment]
How can I create dependent dropdown i have Schools, Branches and Students Bread, now i want to add student in which if i choose school then branches dropdown will get branches for that particular schools. How can i do that, I am new in laravel, any help will be appreciated.

**Comment by fletch3555** [comment]
This issue has been closed for a few months. Please open your own issue instead of commenting on closed issues.

In this case, I've already answered that question above.
