### ISSUE TITLE
Voyager bread menu items doesn't delete

### ISSUE THREAD

**Issue by belguinan** [thedevdojo/voyager#3462]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySql 5.7

I just noticed that if you delete a bread, the menu item for this bread still in the database, you have to delete the record manually

**Comment by ntuple** [comment]
Fix #3621

**Comment by emptynick** [comment]
As @ntuple said, fixed in #3621
