### ISSUE TITLE
image broken / not load / not show up because junction point "storage" in folder "public" broken (error : "location not available")

### ISSUE THREAD

**Issue by kitoki** [thedevdojo/voyager#3469]
## Version information

 - Laravel: v5.6.*
 - Voyager: v1.1.#
 - PHP: v7.2.3
 - Database: MariaDB 10.1.31

## Description

i use windows 7 ultimate SP 1

i try APP_URL, filesystems->url, i even check if image source correct with inspect element, but, even after all correct, the image still not show up (avatar and image in users).

and by chance, i open "your_project->public" folder, there is junction point folder with name "storage", it has type "File folder", i just want know what is it, so i click enter, but this show up.

![image](https://user-images.githubusercontent.com/20715218/44066898-1266b8ca-9f9d-11e8-8373-75aeb3478f84.png)

after that, i use command "php artisan storage:link", but still not work, i try remove that something ("storage") and use command again.
and this problem resolved, i am so happy that time i forgot to ask or write my own error documentation.

that is story 1 or 2 week ago, that time i start it in local and use "php artisan serve".

but right now (still in local and use "php artisan serve"), for some reason it happen again, i still don't know what reason this happen again.
i solved it with same i used before, 

> **but what if this happen again? at least i want to know why this happen.**

## Steps To Reproduce
1. Go to 'your_project->public'
2. Click on 'storage' and open / enter.
3. See error.

## Expected behavior
'your_project->public->storage' show folder where photo avaible which same as in
your_project->storage->app->public->...->August2018_or_anything->image_with_name_random.jpg

## Screenshots
![image](https://user-images.githubusercontent.com/20715218/44066898-1266b8ca-9f9d-11e8-8373-75aeb3478f84.png)

**Comment by fletch3555** [comment]
This has nothing to do with the Voyager package.  This question would be much better suited for a more laravel-generic forum, such as LaraChat slack, or Laracasts forums.
