### ISSUE TITLE
How have you generated Voyager's seed files ?

### ISSUE THREAD

**Issue by bluemmb** [thedevdojo/voyager#3470]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: #

## Also mentioned in
- #1030
- #1995
- #1921
- #2014
- #2445

## Description
First of all thanks for your Awesome work. :heart: 

There are many discussions on how to move Voyager data to production (anywhere else). The method that I more prefer is using Seeder files and to generate them automatically from the database, but as I was searching there is no such tools made for Voyager specially. 

And what I am curious about is that in almost all Voyager Seed files there is a comment saying : 

`/**
     * Auto generated seed file.
     */`

So how have you generated Voyager's seed files ? It would be awesome If you could share it.

**Comment by fletch3555** [comment]
We haven't generated those files.  That comment is likely just a remnant from when someone ran `artisan make:seeder`.

**Comment by bluemmb** [comment]
@fletch3555 Oh! Thanks.

**Comment by DrudgeRajen** [comment]
Check this.
A package on top of voyager which listen to BREAD events and generates the seeders for BREAD.

**Comment by fletch3555** [comment]
@drudgerajen, please don't comment on closed issues, especially after so long (8 months in this case). Also, your comment isn't relevant to this issue
