### ISSUE TITLE
belongsToMany relation with accessor

### ISSUE THREAD

**Issue by shingo0620** [thedevdojo/voyager#3471]
## Version information
 - Laravel: v5.6.31
 - Voyager: v1.1.3
 - PHP: 7.0.16
 - Database: MySQL 8.0

## Description
Model A
* id
* first_name
* last_name
* b_id
* accessor: full_name

Model B
* id
* name
* relation: hasMany A

Setup the BREAD for B, but the relation hasMany to get A with A's fullname failed, when browsing the B list it returned with SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'field list' (SQL: select `full_name` from `A` where `B_id` = xxx)

but it work fine if I setup the relation to hasOne instead of hasMany

## Expected behavior
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'field list' (SQL: select `full_name` from `A` where `B_id` = xxx)

**Comment by shingo0620** [comment]
this error only show up with the read view, works fine with edit view

**Comment by emptynick** [comment]
This should be fixed in https://github.com/the-control-group/voyager/pull/3444

**Comment by emptynick** [comment]
Closing as #3444 was merged and will be released in v1.1.8.
Please let us know if it helped.
