### ISSUE TITLE
validation bug with required_if and checkboxes

### ISSUE THREAD

**Issue by webber-ch** [thedevdojo/voyager#3475]
## Version information
 - Laravel: v5.5.*
 - Voyager: v1.1.3
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
In a validation case where e.g. a required_if condition is based on whether a checkbox field is set or not, the validation doesn't work correctly because the checkbox value is always on. This happens because ALL fields are passed with the XHR validation request, even not checked checkboxes.

## Steps To Reproduce
1. Add the following validation to the title field of the posts table:

`{
    "validation": {
        "rule": "required_if:featured,on"
    }
}`

2. Try to save a post with an empty title field. Make sure that the featured checkbox is unchecked.
3. Even though the featured checkbox is off the validation fails.

## Expected behavior
The validation should pass for an empty title field and an unchecked featured checkbox.

## Additional context
See the proposed solution at PR #3474

**Comment by emptynick** [comment]
Closing as #3474 is merged.
