### ISSUE TITLE
BREAD not working when a migration is created

### ISSUE THREAD

**Issue by SoldierCorp** [thedevdojo/voyager#3478]
## Version information

 - Laravel: v5.6.33
 - Voyager: v1.1.3
 - PHP: 7.2.4
 - Database: MariaDB 10.3.8

## Description

Since I realized that if you create a table from Voyager Admin, a migration of that table is not going to be generated so I created a migration for my posts table and I added it BREAD but when I open the url `/admin/posts` is showing a blank page

## Steps To Reproduce
1. Create a migration
2. Run the migration
3. Add bread to that table created from the migration in the admin

## Expected behavior
Show the BREAD like if I created a table directly in the admin

## Screenshots
![image](https://user-images.githubusercontent.com/1775881/44302929-dab9d100-a2f8-11e8-9594-9876523785dc.png)

**Comment by emptynick** [comment]
From your bread-settings I see that you are using a custom controller.
Can you show us this controller as I'm pretty sure its caused by this.

**Comment by SoldierCorp** [comment]
You are right, I forgot to remove that part but now when I click in the Create button I am receiving this:

```
Method Illuminate\Database\Query\Builder::getTranslationsOf does not exist. (View: /Users/myuser/Development/laravel-projects/myproject/vendor/tcg/voyager/resources/views/posts/edit-add.blade.php)

```

**Comment by emptynick** [comment]
Take a look at https://github.com/the-control-group/voyager/issues/2777

**Comment by SoldierCorp** [comment]
Thank you.
