### ISSUE TITLE
Media Preview persists regardless of selected file.

### ISSUE THREAD

**Issue by roblesterjr04** [thedevdojo/voyager#3479]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.3
 - PHP: 7.2

## Description

Media previewer (in this example, just audio, did not test other formats) does not update when you click different files. it only previews the first file in the folder.

## Steps To Reproduce
1. Upload audio files
2. Browse to it in the media area
3. Click different files and try and preview them.
4. The same preview persists.

## Expected behavior
I would expect the previewer to play each different file.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3845 (merged into 1.x)
