### ISSUE TITLE
override select option

### ISSUE THREAD

**Issue by osc2nuke** [thedevdojo/voyager#3482]
In the package view there is a custom Post/edit-add.blade.php
Inside of it there is a call made to:
`                               <select class="form-control" name="category_id">
                                    @foreach(TCG\Voyager\Models\Category::all() as $category)
                                        <option value="{{ $category->id }}"@if(isset($dataTypeContent->category_id) && $dataTypeContent->category_id == $category->id) selected="selected"@endif>{{ $category->name }}</option>
                                    @endforeach
                                </select>
`

I made a custom resources/views/vendor/voyager/categories/browse.blade.php
How can i use the above select option (with a little change):

`
                                <select class="form-control" name="category_id">
                                    @foreach(TCG\Voyager\Models\Category::where('author_id','=', Auth::user()->id) as $category)
                                        <option value="{{ $category->id }}"@if(isset($dataTypeContent->category_id) && $dataTypeContent->category_id == $category->id) selected="selected"@endif>{{ $category->name }}</option>
                                    @endforeach
                                </select>
`
I do have no intention to write a full resources/views/vendor/voyager/categories/edit-add.blade.php

Is it possible to override it in just this specific case (as there will go be more dropdowns what need to be restricted).

Just curious if it is possible or is a trick for.

**Comment by osc2nuke** [comment]
All that voyager needs is a view builder (so can make views like you made for the Posts)
That would be awesome!

**Comment by osc2nuke** [comment]
A button to generate a default 

- browse.blade.php 
- edit-add.blade.php

Would already be cool to get yourself started.

**Comment by emptynick** [comment]
Please use the issue template.
Also please ask questions in our Slack group as suggested in the issue template.
Closing.
