### ISSUE TITLE
Generate views on the fly

### ISSUE THREAD

**Issue by osc2nuke** [thedevdojo/voyager#3483]
A button to generate a default

- browse.blade.php
- edit-add.blade.php

Would already be cool to get yourself started.

**Comment by fletch3555** [comment]
Voyager already has a view fallback system, which will guarantee a matching view is found.  For example, if you create a new BREAD, you need not generate view files for it as it'll use the default views under `vendor/tcg/voyager/resources/views/bread/*.blade.php`.

In short, we see overriding views as an exception, not the rule.  Therefore I don't see the benefit of adding UI elements to generate these files.

**Comment by osc2nuke** [comment]
But you (voyager) did it for the 
-posts.
-users.
-roles.

These are manually written.
Yet i not figured out todo that for my own breads!

**Comment by osc2nuke** [comment]
never mind, i think i got it...........
just copyed the edit-add.blade.php from
`vendor/tcg/voyager/resources/views/bread/edit-add.blade.php.`
to my own view.

**Comment by fletch3555** [comment]
Yes exactly. It's also in our docs: https://voyager.readme.io/docs/overriding-views

**Comment by osc2nuke** [comment]
It is still to complicated building views.
I not expect anything from the voyager team in this.
I already found a bogus bread-template hook.

Keep in mind, you telling it is the missing admin.
What i ask/mention is all admin related.

**Comment by osc2nuke** [comment]
Just make the generate button. (it is optional).
You know how to fetch/catch the generation.
Based on that.
A view could be made very quickly.

Just let it sink a little.

**Comment by osc2nuke** [comment]
Make this tread a challenge instead of a "request"
perhaps someone can HOOK into this ;)

I wished i was more experienced in Laravel ( i just recently started).
But i have a little decades programming skills under the hood.
What you made is FUCKING awesome, but if not extend it, others will go grab the idea and will go do EXACTLY the request i made.

For one simple reason........... it makes sense.
Ask the main dev about this idea.
