### ISSUE TITLE
Create custom setttings tab

### ISSUE THREAD

**Issue by p0ntsNL** [thedevdojo/voyager#3485]
I have not been able to find this in the documentation from the website, how would it be possible to create a new tab on the settings page like "Site" and "Admin"?

Thanks in advance.

**Comment by emptynick** [comment]
Just enter the name of the group. The select-dropdown is not fixed to the existing groups.

**Comment by p0ntsNL** [comment]
I feel so stupid, I am sorry!

Thank you
