### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by p0ntsNL** [thedevdojo/voyager#3486]
I have created a database together with a bread and one item has to be an integer, so upon testing changing this integer into a text I am receiving a error page while I just want to receive a popup "this item should be an integer" or something simmular.

Is this possible?

<img width="467" alt="screen shot 2018-08-23 at 15 03 30" src="https://user-images.githubusercontent.com/25501135/44527051-0ae0e580-a6e6-11e8-9cc6-f8d87fa48b24.png">

**Comment by fletch3555** [comment]
https://voyager.readme.io/docs/validation && https://laravel.com/docs/5.6/validation

**Comment by p0ntsNL** [comment]
nice thank you so much!

Is this kind of data also possible with settings? I would like certain settings to take care of some validation like < 0 and > 15 for example.
