### ISSUE TITLE
Settings validation like bread

### ISSUE THREAD

**Issue by p0ntsNL** [thedevdojo/voyager#3487]
As asked here it would be great to have the same validation currently available for Bread also for Settings, this is because you might have users that have to set a number as a settings but turn on adding invalid characters upon setting their settings.

https://github.com/the-control-group/voyager/issues/3486

**Comment by fletch3555** [comment]
Please update the issue description following the issue template we have provided: https://github.com/the-control-group/voyager/blob/1.1/.github/ISSUE_TEMPLATE/feature_request.md
