### ISSUE TITLE
Hide settings based on check box

### ISSUE THREAD

**Issue by p0ntsNL** [thedevdojo/voyager#3488]
It would be lovely to hide certain settings while a certain check box is not on, and when it turns on new settings turn up.

like this:

first:
<img width="230" alt="screen shot 2018-08-23 at 20 23 07" src="https://user-images.githubusercontent.com/25501135/44544473-8c4e6d00-a712-11e8-8720-cee929cc7758.png">

later:
<img width="297" alt="screen shot 2018-08-23 at 20 23 28" src="https://user-images.githubusercontent.com/25501135/44544483-92444e00-a712-11e8-9153-5feee52a1e15.png">

**Comment by fletch3555** [comment]
Please update the issue description following the issue template we have provided: https://github.com/the-control-group/voyager/blob/1.1/.github/ISSUE_TEMPLATE/feature_request.md
