### ISSUE TITLE
TinyMCE Youtube Plugin license is not open-source

### ISSUE THREAD

**Issue by neurotools** [thedevdojo/voyager#3491]
## Version information
 - Laravel: v5.6.27
 - Voyager: v1.1.3
 - PHP: 7.1
 - Database: MySQL 5.7.20

## Description
Youtube Plugin for TinyMCE used on Voyager is a commercial plugin. It's not open-source.

http://www.cfcms.nl/tinymce-youtube/index.html

The plugin is sold on USD 6 at:

https://codecanyon.net/item/tinymce-4-plugin-youtube-search-and-insert/5495575

Also, it's configured to use a Google API key for the Youtube API, that is hardcoded on the plugin.

## Steps To Reproduce

Read the plugin main js file (plugin.js):

```
/**
 * Youtube search - a TinyMCE youtube search and place plugin
 * youtube/plugin.js
 *
 * This is not free software
 *
 * Plugin info: http://www.cfconsultancy.nl/
 * Author: Ceasar Feijen
 *
 * Version: 2.0 released 14/08/2014
 */
```

## Expected behavior

Plugin should be removed, changed for an open-source one or a licensing agreement made with the author.

API key for the plugin must be configurable through Voyager settings or voyager config file.

**Comment by fletch3555** [comment]
Thank you for bringing this to our attention.  It was certainly an oversight, not an intentional violation by at means.  We've reached out to the creator and will remove it if an agreement cannot be reached.

If it does stay, we'll look into making the API key configurable.

**Comment by emptynick** [comment]
Removed in https://github.com/the-control-group/voyager/pull/3824
