### ISSUE TITLE
Edit/add Bread then version update / Luego de actualizar version

### ISSUE THREAD

**Issue by SacksDamian** [thedevdojo/voyager#3499]
## Version information
 - Laravel: v5.5.42
 - Voyager: v1.1.3
 - PHP: 7.2.7

## Description
Buenas tardes, luego de actualizar de la version 1.0 a 1.1 siguiendo los pasos de https://voyager.readme.io/v1.1/docs/10-to-11
Me encuentro que desde los bread no se tiene permiso para añadir o editar breads ya creados. Revise las migraciones, cree un user tipo admin nuevo (voyager:admin...) y revise otros hilos ya creado con los mismos problemas y sigo sin poder resolverlo.

Agradeceria alguna orientacion al problema. Muchas gracias

[Google Translate]
Good afternoon, after updating from version 1.0 to 1.1 following the steps of https://voyager.readme.io/v1.1/docs/10-to-11
I find that from the bread you do not have permission to add or edit already created breads. Check the migrations, create a new admin type user (voyager: admin ...) and check other threads already created with the same problems and I still can not solve it.

I would appreciate any guidance to the problem. Thank you very much

![imagen](https://user-images.githubusercontent.com/28036945/44622339-eb37f180-a88c-11e8-8a52-b896d65a6b1d.png)

**Comment by emptynick** [comment]
This has been solved in a lot of issues already. For example
https://github.com/the-control-group/voyager/issues/3114, https://github.com/the-control-group/voyager/issues/3088 or https://github.com/the-control-group/voyager/issues/3064
