### ISSUE TITLE
"Publish" Routes

### ISSUE THREAD

**Issue by fletch3555** [thedevdojo/voyager#35]
Similar to Issue #23, would it be possible to restructure how the routes are included so we can have control over where they're included?  I'm working on a multi-tenant setup and only want this admin page available for one of them.

Great project by the way! I'd love to help contribute in some way.

**Comment by marktopper** [comment]
You can now change the route prefix in the configuration for all routes generated by Voyager.

Please ping me if there was anything else you wish to do.

**Comment by fletch3555** [comment]
@marktopper along with the prefix, is there a way to change other route properties, such as subdomain? Simply changing the prefix doesn't really solve my multitenant problem.

Thanks!

**Comment by marktopper** [comment]
Reopened

**Comment by fletch3555** [comment]
Taken care of a different way as part of v0.10
