### ISSUE TITLE
Can't set default number value to adding section

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#3503]
## Version information

 - Laravel: v5.4
 - Voyager: v1.0
 - PHP: 7.0
 - Database: MySql

Hello there, 
I am trying to add default integer value to the adding form. But i can't. If input is string default value is activated successfully, but if input type is integer it doesn't accept default value. How can i solve that? Is this a bug or user error. This is most likely user error but can anyone give me a suggestion? Thanks in advance.

**Comment by fletch3555** [comment]
I'm going to be completely honest, I have absolutely no idea what you're asking about...  Please provide screenshots or something.

1.0 has vast differences between 1.0.0 and 1.0.17 (latest patch release), so please provide the full version string.  Also, 1.0.* is OLD... I strongly recommend upgrading to 1.1.* as many of the 1.0 bugs were fixed in 1.1

**Comment by aozen** [comment]
My english is not good, sorry about that. I am writing slowly right now. 
In the crud, when we are creating data-row, i am filling: name, price, order. 
Name is string, price is integer(number) and order is integer. 
I can't set default integer value to the order. I want to make "999" as default. But i can't. 
But i can set default value to the name column. Because its a string. 

I checked additional fields section in the voyager doc. But can't see anything for integers.

**Comment by emptynick** [comment]
The text-formfield uses the default-value
https://github.com/the-control-group/voyager/blob/b6bdca34139a84266a10fc99f5d4b7fe5f8e62e2/resources/views/formfields/text.blade.php#L4

The number-formfield does not:
https://github.com/the-control-group/voyager/blob/b6bdca34139a84266a10fc99f5d4b7fe5f8e62e2/resources/views/formfields/number.blade.php#L8

You are the first one to request this. If you like you can implement it and open a PR.

**Comment by aozen** [comment]
I just copied and paste from text.blade, same concept but i don't recognize the difference. 
Its working now. Thanks a lot :)

**Comment by emptynick** [comment]
The difference is
`@elseif(isset($options->default)){{ old($row->field, $options->default) }}`

**Comment by emptynick** [comment]
Fixed in #3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/042229998f3045846d37c3885a4a442e13d367f7
