### ISSUE TITLE
Custom controller is not calling constructor?

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#3505]
## Version information

 - Laravel: v5.6.26
 - Voyager: v1.1.3
 - PHP: 7.2.5.
 - Database: MySQL 5.7.22

## Description

I have created a custom `MediaController` as explained in https://voyager.readme.io/docs/using-custom-http-controllers . However, the custom `MediaController` won't call the constructor. Why?

## Steps To Reproduce
1. Change controller namespace on `config/voyager.php` 
```
    'controllers' => [
        'namespace' => 'App\\Http\\Controllers\\Voyager',
    ],
```
2. Call
`php artisan voyager:controllers`
3.  Modify MediaController like this:
```
<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerMediaController as BaseVoyagerMediaController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\ImageManagerStatic as Image;

class VoyagerMediaController extends BaseVoyagerMediaController
{
  public function upload(Request $request)
  {
      try {
          $realPath = Storage::disk($this->filesystem)->getDriver()->getAdapter()->getPathPrefix();

          $allowedImageMimeTypes = [
              'image/jpeg',
              'image/png',
              'image/gif',
              'image/bmp',
              'image/svg+xml',
          ];

          /* ============================================================================
            Start modification here
            Keep original file names
            https://github.com/the-control-group/voyager/issues/1655#issuecomment-383311849
            ============================================================================= */
          $originalName = $request->file->getClientOriginalName();
          $nameWithoutSpace = preg_replace('/\s+/', '-', $originalName);
          $file = $request->file->storeAs($request->upload_path, $nameWithoutSpace, $this->filesystem);
/* =============================================
         End modification
=============================================*/
          if (in_array($request->file->getMimeType(), $allowedImageMimeTypes)) {
              $image = Image::make($realPath.$file);

              if ($request->file->getClientOriginalExtension() == 'gif') {
                  copy($request->file->getRealPath(), $realPath.$file);
              } else {
                  $image->orientate()->save($realPath.$file);
              }
          }

          $success = true;
          $message = __('voyager::media.success_uploaded_file');
          $path = preg_replace('/^public\//', '', $file);
      } catch (Exception $e) {
          $success = false;
          $message = $e->getMessage();
          $path = '';
      }

      return response()->json(compact('success', 'message', 'path'));
  }
}
```
4. Upload a file through media manager

Now the file upload will not work:
![image](https://user-images.githubusercontent.com/1765602/44668953-13eff080-aa1f-11e8-9959-a257cdbe0148.png)

Here is the error from the log files:

> Undefined property: App\Http\Controllers\Voyager\VoyagerMediaController::$filesystem {"userId":1,"email":"","exception":"[object] (ErrorException(code: 0): Undefined property: App\\Http\\Controllers\\Voyager\\VoyagerMediaController::$filesystem at /home/www/memberportal/app/Http/Controllers/Voyager/VoyagerMediaController.php:15) 

## Expected behavior
VoyagerMediaController should know the $filesystem property, because the constructer was not overwritten and the constructor from the parent looks like that:

```
    public function __construct()
    {
        $this->filesystem = config('voyager.storage.disk');
    }
```

**Comment by fletch3555** [comment]
Your symptom is correct, but assumed cause is not.  The issue is that `$filesystem` is private on the parent class, meaning it's not directly accessible by child classes(https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerMediaController.php#L15).

What you're changing isn't possible at the moment, at least not the way you're doing it.

As a "hacky" short-term fix, you can use the config value directly: `config('voyager.storage.disk')`

**Comment by niels-numbers** [comment]
@fletch3555 wow what a quick response! Thank you!

Unfortunately, replacing the two `$this->filesystem` instances with `config('voyager.storage.disk')` still lead to errors. The upload was now working, but I got still an error pop up and I found this in the log files:

> Image source not readable {"userId":1,"email":"","exception":"[object] (Intervention\\Image\\Exception\\NotReadableException(code: 0): Image source not readable at /home/www/memberportal/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:345) 

I was able to fix this by simply copy and pasting the complete `TCG\Voyager\Http\Controllers\VoyagerMediaController` into `App\Http\Controllers\Voyager\VoyagerMediaController` , then changing the upload method and adding `use TCG\Voyager\Http\Controllers\Controller;` at the top of the file.

**Comment by fletch3555** [comment]
Glad you got it working.  Generally speaking, we don't really recommend publishing all controllers like you did, since that makes upgrading difficult.  Overriding the MediaController is really the only exception since it's not managed by BREAD, so there's no other way.  Just something to keep in mind going forward.
