### ISSUE TITLE
Menu Dropdown-elements active on dashboard when not using route groups

### ISSUE THREAD

**Issue by JeremyGuinn** [thedevdojo/voyager#3509]
## Version information

 - Laravel: v5.5.42
 - Voyager: v1.1.3
 - PHP: 7.2.7-0ubuntu0.18.04.2
 - Database: mysql  Ver 14.14 Distrib 5.7.23

## Description

Setting up voyager as the root instead of a subdirectory (e.g. /admin), causes any dropdowns in the menu to automatically be expanded and have the active class.

## Steps To Reproduce
1. Modify config/voyager.php: 
`'redirect' => '/',`
2. Modify routes/web.php:
From: 
```
Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix'=>'admin'], function() {
    Voyager::routes();
});
```
To:
```
Voyager::routes();
```
3. Navigate to the dashboard
4. Look at menu, sub menus are expanded

## Expected behavior
Menu items that have dropdowns are not active unless currently viewing an item in the sub menu.

## Screenshots
![image](https://user-images.githubusercontent.com/9940926/44746501-283ff600-aad0-11e8-95fb-a992b918182f.png)

**Comment by emptynick** [comment]
Closing as #3850 was merged (into 1.x, to be released in a future 1.2 release)
