### ISSUE TITLE
v0.10 BREAD and settings missing from Admin Dashboard

### ISSUE THREAD

**Issue by fishmad** [thedevdojo/voyager#351]
- Laravel Version: 5.3.*
- Voyager Version: 0.10
- PHP Version: 7.0.11
- Database Driver & Version: MySQL MarianDB 10.1.9

### Description:
![image](https://cloud.githubusercontent.com/assets/12012101/21030119/02dc0b06-bdf1-11e6-84da-009f5e360080.png)

### Steps To Reproduce:
Fresh install Laravel with 5.3 Voyager v0.10

Tried both:
php artisan voyager:install
php artisan voyager:install --with-dummy

php artisan vendor:publish --provider="TCG\Voyager\VoyagerServiceProvider" --force

**Comment by fishmad** [comment]
Actually just found this and will retry UPGRADE
https://the-control-group.github.io/voyager/docs/v0.10/

**Comment by fishmad** [comment]
Sorted with this command
php artisan voyager:admin admin@admin.com

**Comment by tokkerbaz** [comment]
I tried too with command:
php artisan voyager:admin admin@admin.com  
The user now has full access to your site... but nothing happens=)))

**Comment by marktopper** [comment]
Did you also republish the database seeders and seeded the menu items seeder?

If you wish to do this only for the menu items, try this:
```
rm database/seeds/MenuItemsTableSeeder.php
php artisan vendor:publish --provider="TCG\Voyager\VoyagerServiceProvider"
php artisan db:seed --class=MenuItemsTableSeeder
```

**Comment by tokkerbaz** [comment]
yes i did =))  in db table menu_items all columns are the same as in MenuItemTableSeeder

**Comment by tokkerbaz** [comment]
may be it is problem with routes? it only shows the pages are in data_type:  pages,users,roles etc.

**Comment by marktopper** [comment]
Can you please share the content of the `menu_items`, `permissions`, `permission_role`, `data_types` and `roles` tables together with the `role_id` for your user.

Then I will figure out exactly what went wrong.

**Comment by marktopper** [comment]
The routes you say, please try share your `routes/web.php` file and the response of `php artisan route:list`.

**Comment by tokkerbaz** [comment]
`route:list` all routes are normal

here my screen to db data_types
![data_types](https://cloud.githubusercontent.com/assets/20562879/21045114/26b14e8c-be29-11e6-872a-d94cc7c996ae.png)
 
menu_items
![menu_items](https://cloud.githubusercontent.com/assets/20562879/21045125/36b7e66a-be29-11e6-9988-b321897fc859.png)

premissions
![permissions](https://cloud.githubusercontent.com/assets/20562879/21045132/42275cb0-be29-11e6-8de1-a3f1c607955c.png)

permission_roles
![permissions_roles](https://cloud.githubusercontent.com/assets/20562879/21045145/4c04cc5e-be29-11e6-9b83-07ab89f678f1.png)

roles
![roles](https://cloud.githubusercontent.com/assets/20562879/21045156/57701468-be29-11e6-8435-3616b101218e.png)

web.php
![route](https://cloud.githubusercontent.com/assets/20562879/21045162/610fe052-be29-11e6-9676-d4ff4df86bdb.png)

**Comment by tokkerbaz** [comment]
i cant open only dashboard...all routes are opening normally in admin

**Comment by marktopper** [comment]
So you can access the url `/admin/settings`? But you can not see it in the admin panel menu?

**Comment by tokkerbaz** [comment]
`/admin `page not found..... but `admin/settings, admin/pages , admin/users` works... only dashboard not found =)) sorry i just noticed this issues main task =))) i cant enter to dashboard it shows 404... all another urls are works  and in dashboard everything ok, anyway anything else dashboard.

Also The issue is when i create bread to my custom table... i cant access to it it shows
`UnauthorizedHttpException in Voyager.php line 104:`

**Comment by fletch3555** [comment]
`/admin` is not found because it's matching your `/{nickname}` route first.

If you look at the output from `php artisan route:list` before and after commenting out the `/{nickname}` route,, I bet it would show this.

Reference: https://laravel.com/docs/5.3/controllers#restful-supplementing-resource-controllers

**Comment by marktopper** [comment]
Please change the route prefix of Voyager then to match something else for your needs, since `/admin` is not found because it matches `/{nickname}` like @fletch3555 figured out.

**Comment by tokkerbaz** [comment]
Thank you=)) I put voyager routes above my route /{nickname} =)) and now works like a charm =)))

**Comment by AbdulWahab007** [comment]
- Laravel Version: #.#.#latest version
- Voyager Version: #.#.#latest version
- PHP Version:5.7
- Database Driver & Version:mysql  Ver 15.1 Distrib 10.1.25-MariaDB, for Win32 (AMD64)

### Description:

After installation of voyager in laravel 5.5 .it shows that there is no view or table found. and when i open resourses .there is noting of voyager 
it shows following issue
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'admin.settings' doesn't exist (SQL: select * from `settings`) (View: D:\xampp\htdocs\voyager\vendor\tcg\voyager\resources\views\login.blade.php)
### Steps To Reproduce:
can anyone help me to solve this.
i am trying from two days.

**Comment by lukelee36** [comment]
Hello, I have several problem. But I can Access to Dasboard lika /admin and /admin/database, another part of menu didn't work and show me this message "(1/1) HttpException
This action is unauthorized." 
Can you help me?

**Comment by emptynick** [comment]
This issue has been closed for over a year.
Please open a new issue if you think you found a bug,
if you have a question please ask in our [Slack](https://voyager-slack-invitation.herokuapp.com/)
