### ISSUE TITLE
Create migrations together with models

### ISSUE THREAD

**Issue by bugzbrown** [thedevdojo/voyager#3510]
## Description of problem

When creating database tables, we can create a model for the table, but there is no migration file created. It would be nice (from a deployment perspective) to create a migration file along with the model.

## Proposed solution
When a table is created, the migration file is created along with it and the migration table is updated to reflect the current migration state.

**Comment by fletch3555** [comment]
This has been discussed numerous times, including roughly a dozen other issues here.  We would love to, but it's a very complex topic.  Unless of course you just want a migration stub (no actual content), but that seems worthless to us.  Until someone builds it, it won't happen.  There's an open pull request (work-in-progress) to add it, but it's not complete.
