### ISSUE TITLE
REST API for mobile apps

### ISSUE THREAD

**Issue by raxan** [thedevdojo/voyager#3512]
I am not sure if you already offer REST API for build mobile apps backend?
THanks

**Comment by fletch3555** [comment]
First of all, we have issue templates for a reason.  If you find that your question doesn't fit one of the templates (like this one for example), it's likely best asked in Slack instead.

Having said that, no, we don't have a REST api built-in, and likely will not be adding that functionality.  Voyager is an admin tool used to view/edit/etc your app's data.  How you build the app itself, including any necessary REST APIs, is completely up to you.
