### ISSUE TITLE
Hello, I would like to put another default image that will be used when the user will be registered. how to proceed?

### ISSUE THREAD

**Issue by PaulinPrize** [thedevdojo/voyager#3515]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
A clear and concise description of what the problem is.  Please also explain why this doesn't fit into the defined issue templates

**Comment by fletch3555** [comment]
Please fill out the template and reopen
