### ISSUE TITLE
BootstrapVue Tabs

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#3518]
## Version information

 - "laravel/framework": "5.6.*",
 -  "tcg/voyager": "^1.1",
 -  "php": "^7.1.3",
 - Database: *

## Description

Not working BootstrapVue Tabs

## Steps To Reproduce
1. Go to Install Bootstrap Vue
2. Add Basic BootstrapVue Tabs
3.Tabs nor working

## Expected behavior
I try see Tabs)

## Screenshots
```
    <div>
    <b-tabs>
        <b-tab title="first" active>
            <br>I'm the first fading tab
        </b-tab>
        <b-tab title="sasecond" >
            <br>I'm the second tab content
        </b-tab>
        <b-tab title="disabled" disabled>
            <br>Disabled tab!
        </b-tab>
    </b-tabs>
    </div>
```
![image](https://user-images.githubusercontent.com/13051822/45001844-7de93680-afd9-11e8-8b96-3cd90a4e6440.png)

## Additional context
Stop use basic  style class name!!!
Plz  add  some  prefix, or not use  basic  style name, its realy  hard coding
If I need to stylize any page, I spend the time to reinstall many of the base classes that are found in any package

**Comment by fletch3555** [comment]
We can't possibly avoid conflicts with all other packages.  If you find a conflict, please feel free to submit a pull request.
