### ISSUE TITLE
Laravel 5.7 support not working

### ISSUE THREAD

**Issue by vbasky** [thedevdojo/voyager#3519]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1.16
 - Database: Maria DB  10.3.8

## Description

 composer update  "laravel/framework": "5.7.*@dev" not working.

Would like to know the plan to support laravel 5.7.

## Steps To Reproduce
1. Go to composer.json 
2. Update Laravel to `"laravel/framework": "5.7.*@dev"`
2. Run composer update
3. See error

` Problem 1
    - tcg/voyager v1.1.3 requires illuminate/support ~5.4.0|~5.5.0|~5.6.0 -> satisfiable by laravel/framework[v5.6.35], illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
`

## Expected behavior
Composer update to happen.

**Comment by fletch3555** [comment]
That is correct.  We have not tested Voyager against 5.7, nor have we updated it's dependency versions and tested those.

**Comment by vbasky** [comment]
Any idea on when you plan to support ?

**Comment by fletch3555** [comment]
No set schedule.  It's dependent on someone (not necessarily one of the maintainers) taking the initiative to update the version strings and test it then open a pull request with the changes.

**Comment by vbasky** [comment]
What's the procedure to do that any docs ?

**Comment by WanderingKazuma** [comment]
Also looking for procedure to update version strings on dependencies or a better understanding of what dependencies and changes need to happen for 5.7 support.

**Comment by cotiga** [comment]
It seems very difficult.
I started, but I give up because of lack of time.
The "Doctrine Support" and "Voyager Hooks" dependencies are blocked in Packagist.
I certainly lack skills, but it seems almost impossible for a non-collaborator.
I hope the TCG team is not discouraged by the arrival of Nova.
Courage, we love to travel ;)

**Comment by goldnetonline** [comment]
Hi all,

Anyone here with any definite time frame... 

I am updating to 5.7 because of the native email verification support.

And I cannot path ways with voyager, if is embedded to the core of our system.

Nova is not a way to go now as we have a lot to cover and we are deep with voyager.

Voyager please.... (On bended knees).

**Comment by spooksie** [comment]
I installed 5.7 for the Auth scaffolding to save time. However, I found it wasn't compatible, so I downgraded to 5.6.* and installed Voyager. However everything works, I can login with my auth. **BUT I CAN'T REGISTER** as its coming up with this error

`"Class Illuminate\Auth\Listeners\SendEmailVerificationNotification does not exist"
`
Hope you get Voyager working with 5.7 as its a killer platform you have going here.

**Comment by spooksie** [comment]
> I installed 5.7 for the Auth scaffolding to save time. However, I found it wasn't compatible, so I downgraded to 5.6.* and installed Voyager. However everything works, I can login with my auth. **BUT I CAN'T REGISTER** as its coming up with this error
> 
> `"Class Illuminate\Auth\Listeners\SendEmailVerificationNotification does not exist"`
> Hope you get Voyager working with 5.7 as its a killer platform you have going here.

Found a quick fix for now. 

Open app>Providers>EventServiceProvider.php
comment out 

`use Illuminate\Auth\Listeners\SendEmailVerificationNotification;
`
&
`SendEmailVerificationNotification::class,`

Once the 5.7 update for Voyager is out, simply undo what I said.

**Comment by syedbilal55** [comment]
encountering same issue here

**Comment by anwar0x09** [comment]
Still waiting for Laravel 5.7 support.

**Comment by emptynick** [comment]
Laravel 5.7 is now supported in Voyager 1.1.4

**Comment by vbasky** [comment]
Great news testing it. Thanks it works I am able to upgrade @emptynick It would be great to share the knowledge on how to add compatibility going forward which will help community to contribute. Any documentation around the same would be greatly appreciated.

**Comment by emptynick** [comment]
There's not the one way on how to make Voyager work with a new Laravel version.
In this case we just needed to update the laravel version-constraint, but some of our required packages, like `doctrine-support`, needed to do the same.
So we have to walk through those packages, and make sure they support 5.7, create PRs in these repos and so on.

**Comment by goldnetonline** [comment]
Hi all,

Today as at Tuesday September 18, 2018, I can confirm Voyager supports Laravel 5.7.

Cheers

**Comment by goldnetonline** [comment]
Guys,

Please fix the use of `or` as opposed to the new laravel `??` used on the framework for users with Laravel 5.7.

Looking at vendor/tcg/voyager/resources/views/bread/edit-add.blade.php on line 65 `col-md-{{ $display_options->width or 12 }}` please replace `or` with `??`.

A quick fix for anyone is to use custom controller and edit `VoyagerBreadController` override the create and edit action from `BaseVoyagerBreadController` which is an alias of `VoyagerBreadController` on the main package.

Hope this helps someone.

**Comment by fletch3555** [comment]
@goldnetonline, if you read up a few comments, you'll see that was taken care of a few days ago.  Please make sure you've updated to 1.1.5
