### ISSUE TITLE
Add/ change fields in Users table

### ISSUE THREAD

**Issue by mateevd** [thedevdojo/voyager#3520]
## Version information
 - Laravel: 5.6
 - Voyager: 1.1
 - PHP: 7.1.3
 - Database: mysql

Hello, so I'm trying to add/ change fields in my User table but Voyager is not accepting them. I already checked similar issues and find out that I have to copy the edit-add.blade.php from the vendor to my resource folder. 
I did that, I can see the new fields but when I try to create new user I get this sql error:

```
"SQLSTATE[HY000]: General error: 1364 Field 'first_name' doesn't have a default value (SQL: insert into `users` (`email`, `password`, `role_id`, `updated_at`, `created_at`) values (test2@gmail.com, $2y$10$soaPPEpZiO9baR1N8xdtVO7LsmPo7DaqNrcvgubW.noDlea9oogjC, 2, 2018-09-04 07:59:20, 2018-09-04 07:59:20)) ◀"
```

I even changed the user BREAD to use the App\User model and not the default tcg model, but still get the same error. I'm missing something pls can anyone help!!!

**Comment by fletch3555** [comment]
Please show the BREAD configuration for your User BREAD, as well as the blade view file you copied

**Comment by mateevd** [comment]
This is my User BREAD

![bread](https://user-images.githubusercontent.com/29518478/45078052-36ed6500-b0ef-11e8-9cb9-e522ebbb42df.png)

And the blade view:

            <div class="row">
                <div class="col-md-8">
                    <div class="panel panel-bordered">
                    {{-- <div class="panel"> --}}
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="panel-body">
                            <div class="form-group">
                                <label for="name">{{ trans('users.Fname') }}</label>
                                <input type="text" class="form-control" id="fname" name="fname" placeholder="{{ __('voyager::generic.name') }}"
                                       value="@if(isset($dataTypeContent->first_name)){{ $dataTypeContent->first_name }}@endif">
                            </div>

                            <div class="form-group">
                                <label for="name">{{ trans('users.Lname') }}</label>
                                <input type="text" class="form-control" id="lname" name="lname" placeholder="{{ __('voyager::generic.name') }}"
                                       value="@if(isset($dataTypeContent->last_name)){{ $dataTypeContent->last_name }}@endif">
                            </div>

                            <div class="form-group">
                                <label for="email">{{ __('voyager::generic.email') }}</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="{{ __('voyager::generic.email') }}"
                                       value="@if(isset($dataTypeContent->email)){{ $dataTypeContent->email }}@endif">
                            </div>

                            <div class="form-group">
                                <label for="password">{{ __('voyager::generic.password') }}</label>
                                @if(isset($dataTypeContent->password))
                                    <br>
                                    <small>{{ __('voyager::profile.password_hint') }}</small>
                                @endif
                                <input type="password" class="form-control" id="password" name="password" value="" autocomplete="new-password">
                            </div>

                            @can('editRoles', $dataTypeContent)
                                <div class="form-group">
                                    <label for="default_role">{{ __('voyager::profile.role_default') }}</label>
                                    @php
                                        $dataTypeRows = $dataType->{(isset($dataTypeContent->id) ? 'editRows' : 'addRows' )};

                                        $row     = $dataTypeRows->where('field', 'user_belongsto_role_relationship')->first();
                                        $options = json_decode($row->details);
                                    @endphp
                                    @include('voyager::formfields.relationship')
                                </div>
                                <div class="form-group">
                                    <label for="additional_roles">{{ __('voyager::profile.roles_additional') }}</label>
                                    @php
                                        $row     = $dataTypeRows->where('field', 'user_belongstomany_role_relationship')->first();
                                        $options = json_decode($row->details);
                                    @endphp
                                    @include('voyager::formfields.relationship')
                                </div>
                            @endcan
                            @php
                            if (isset($dataTypeContent->locale)) {
                                $selected_locale = $dataTypeContent->locale;
                            } else {
                                $selected_locale = config('app.locale', 'en');
                            }

                            @endphp
                            <div class="form-group">
                                <label for="locale">{{ __('voyager::generic.locale') }}</label>
                                <select class="form-control select2" id="locale" name="locale">
                                    @foreach (Voyager::getLocales() as $locale)
                                    <option value="{{ $locale }}"
                                    {{ ($locale == $selected_locale ? 'selected' : '') }}>{{ $locale }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="panel panel panel-bordered panel-warning">
                        <div class="panel-body">
                            <div class="form-group">
                                @if(isset($dataTypeContent->avatar))
                                    <img src="{{ filter_var($dataTypeContent->avatar, FILTER_VALIDATE_URL) ? $dataTypeContent->avatar : Voyager::image( $dataTypeContent->avatar ) }}" style="width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:10px;" />
                                @endif
                                <input type="file" data-name="avatar" name="avatar">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary pull-right save">
                {{ __('voyager::generic.save') }}
            </button>
        </form>

        <iframe id="form_target" name="form_target" style="display:none"></iframe>
        <form id="my_form" action="{{ route('voyager.upload') }}" target="form_target" method="post" enctype="multipart/form-data" style="width:0px;height:0;overflow:hidden">
            {{ csrf_field() }}
            <input name="image" id="upload_file" type="file" onchange="$('#my_form').submit();this.value='';">
            <input type="hidden" name="type_slug" id="type_slug" value="{{ $dataType->slug }}">
        </form>
    </div>

**Comment by fletch3555** [comment]
In your view, you're using the field as `->first_name`, but the input has `name=fname`. The form submission uses the name attribute as the key, so it needs to match the db field name

**Comment by mateevd** [comment]
WOW Thanks!
I didn't think of that. It's working now! 
Closing the issue, have a great day!
