### ISSUE TITLE
extend Menu Items

### ISSUE THREAD

**Issue by nabbs** [thedevdojo/voyager#3522]
## Version information

 - Laravel: v5.6.35
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 8.0

I am trying to extend the menu items table by adding a publish flag.  So in the menu_items table i have added a new field "publish" int. Now what i would like to do is add a checkbox for publish/unpublish the item. How can this be done? 

I dont want to simply delete the item but unpublish it instead.

thanks

Nabi

**Comment by fletch3555** [comment]
I'm not sure I understand the reasoning behind this.  You could just user permissions to choose whether to allow a menu item to appear or not.

**Comment by nabbs** [comment]
@fletch3555 i don't want a menu item to appear on the front end. Sure i can delete that particular item but i would rather unpublish it or hide it. 

see attached image

![menuitem](https://user-images.githubusercontent.com/731264/45118703-1fdf5f00-b151-11e8-8d2d-48b3a788e326.png)

**Comment by fletch3555** [comment]
Ah, I see, it's for your front-end.  I had assumed you were talking about the Voyager sidebar menu.

You would have to configure the view that renders the menu to choose whether to display it or not.  You'd also have to override Voyager's MenuItem edit-add view(and possibly controller) to add in the field.  Honestly, this is sounding like a lot of customization/overrides.  I would love to have it bundled into the package though.  Would you be willing to modify Voyager and submit a pull request to add a "is published"/"active"/etc field (I'll leave it up to you to decide what to call it)?

**Comment by nabbs** [comment]
ive tried doing this but i cannot get access to the menu_item table in the Database. (TOOLS > DATABASE). If i can get access to this then we can easily add the checkbox field.

Ive added the field manually via Sequel Pro. But this is of no use as its not viewable in admin panel.

**Comment by fletch3555** [comment]
Yes, exactly.  That's what I'm saying.  This has nothing to do with the database editor within Voyager, and I wouldn't recommend using that for this change.  You will need to override the Voyager view for the Menu editor in order to add that field, and may need to override the Menu controller as well so it handles it properly.  That's a lot of work for this, which is why I suggested doing it directly to the Voyager source and submitting a pull request.  If you're not comfortable doing that, then I'll open it up for someone else to pick up.

**Comment by nabbs** [comment]
i'll have a look at doing this and let you know if it works.

**Comment by fletch3555** [comment]
Closing this for now.  If you need further help, please let me know.
