### ISSUE TITLE
Voyager Images are not showing on moving project from localhost to server

### ISSUE THREAD

**Issue by Techywizz** [thedevdojo/voyager#3523]
## Version information

 - Laravel: v 5.5.*
 - Voyager: v 1.1
 - PHP: 7.1
 - Database: [MYSQL] [5.6.29-76.2] 

## Description:
Hello Team,
I make my project on localhost in xampp v 3.2.2. It Worked fine on the localhost till now, but when i moved that project to my server. the Images in the voyager admin panel are not showing . I tried all solutions which i found on google.
1. php artisan storage:link
2. Changed the App Url to my domain url (http://domain.com/foldername or http://domain.com/foldername/public)
3. Also, i tried to change 
this storage path to public in filesystem.php but is didn't help me.
'public' => [
            'driver' => 'local',
            'root' => **storage_path**('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

When i checked the url in the admin panel for the image it come to  be http://domain.com/crm/public/storage/users/September2018/p7snWgi6ksalXltGFflD.png. When i checked this folder there is no image in it. Also, when i check this url http://domain.com/crm/storage/app/public/users/September2018/p7snWgi6ksalXltGFflD.png. Image is available here but laravel didn't take this path. Please, help me these is no error i am finding or any cause of this issue.

Thanks and Regards

**Comment by Techywizz** [comment]
I figured it out thanks for the help

**Comment by yucolabjames** [comment]
@Techywizz care to share what you did? we are running into the same problem. Any help would be welcome. Thanks!!

**Comment by Lucife9695** [comment]
can tell how do you solve the problem

**Comment by fletch3555** [comment]
Their laravel install was set up wrong (`/storage/app....` shouldn't be accessible to the web), so whatever was done to fix it is likely not ideal.  This has been posted many times, and answered just as many.
