### ISSUE TITLE
Authorization middleware doesn't work

### ISSUE THREAD

**Issue by ncote** [thedevdojo/voyager#3527]
## Version information
 - Laravel: v5.5.40
 - Voyager: v1.0.17
 - PHP: 7.1
 - Database: mysql  Ver 14.14 Distrib 5.7.23

## Description
The 'can' middleware does not seem to honor Voyager permissions. 

## Steps To Reproduce
Override a Voyager route, changing the middleware, e.g.:

Route::get('/patients', '\App\Http\Controllers\PatientController@index')->name('voyager.patients.index')->middleware('can:add_patients');

This returns an exception:  "This action is unauthorized."  I am accessing it as an admin user, with all permissions.

## Expected behavior
The permission is checked and access is allowed.

**Comment by fletch3555** [comment]
That middleware is from laravel, not Voyager.  It checks a gate.  Voyager provides Policy classes, which require an associated model.

I'm not sure this will be able to work the way you're thinking it will, but I'm willing to dig a little deeper into it

**Comment by ncote** [comment]
Ah, right, I hadn't realized that, for example, $user->can(...) delegates to a model policy class, and that the gate needs to be implemented separately.  I'm considering writing a custom middleware that will just forward the check to Voyager::can(...).

A bit of context: I'm using Voyager to allow non-admins to do certain operations, and I was using permissions checks in route overrides to accomplish that.  I didn't see any built-in way of doing this.

**Comment by fletch3555** [comment]
I would avoid using `Voyager::can()` as it's deprecated in favor of Laravel Policy classes.

**Comment by fletch3555** [comment]
It's worth noting, that permissions checks are already occurring on all Voyager pages.  For example, if you have a `patients` BREAD, it will have routes to view a patient, edit a patient, create a new patient, etc.  Each of these pages will perform a check for the related permission (via the policy class and `$this->authorize(......)`: https://laravel.com/docs/5.6/authorization#authorizing-actions-using-policies).  Using this example, if you try to visit the `add` page, the controller will call `$this->authorize('add', App\Patient::class);, which will check for the `add_patients` permission being attached to the User's current Role.

**Comment by ncote** [comment]
Thank you.  I think writing a middleware module to make the authorize(...) calls would work then.

**Comment by ncote** [comment]
Finally, I tried to use something like the following, which should work since it uses the Gate::authorize mechanism, which relies on Policy classes:

Route::get('/patients', '\App\Http\Controllers\PatientController@index')->name('voyager.patients.index')->middleware('can:browse,App\Patient');

But Gate::resolvePolicyCallback(...) doesn't seem to work well with "generic" policy classes like \TCG\Voyager\Policies\BasePolicy since it strips out the string argument (e.g. 'App\Patient') assuming the Policy class will know which class it's dealing with.  We get the following error from BasePolicy::__call :

InvalidArgumentException  not enough arguments

So, to finish this long story: I'll just remove all guards from the routes that concern me, and rely on the controllers to do permission checks.  But it would have been nice to be able to control access at the route level.

**Comment by pamekar** [comment]
So, I came across this issue while working with voyager. I was able to resolve it, so let me drop this here, as it might help someone. 

In the AuthServiceProvider Class,

```
public function boot()
    {
        $this->registerPolicies();

        $user = Auth::user();
     
        if (! app()->runningInConsole()) {
            $roles = Role::with('permission')->get();

            foreach ($roles as $role) {
                foreach ($role->permission as $permission) {

                    $permissionArray[$permission->title][] = $role->id;
                }
            }

            foreach ($permissionArray as $title => $roles) {
                Gate::define($title, function (User $user) use ($roles) {
                    return count(array_intersect($user->role->pluck('id')->toArray(), $roles));
                });
            }
        }
    }
```

Laravel uses a "title" column to store permissions, while Voyager uses "key" for it's permissions. 

IF you want to use @can in blade and Gate::allows(), change `$permissionArray[$permission->title][] = $role->id;` to `$permissionArray[$permission->key][] = $role->id;`.

That solved the issue for me.

@fletch3555, can we update the "key" column to "title" in Voyager's migrations, and other necessary files to match Laravel's default?

**Comment by fletch3555** [comment]
I'm not 100% sure I follow what you're saying, but I'm certainly open to seeing a PR about it

**Comment by Icrmsoftware** [comment]
I created custom laravel middlewares for every role and solved my problem. Refere to below mentioned link
[https://laravel.com/docs/5.8/middleware](url)

`<?php

namespace App\Http\Middleware;

use Closure;

class venuevendor
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (auth()->user()->role->name = 'Venue Vendor') {
            return $next($request);
        }

        return redirect('/icrm');
        
        
    }
}
`

**Comment by prakhargvp** [comment]
Replacement For `can` middleware
Create a middleware permission: `php artisan make:middleware Permission`

```
<?php

namespace App\Http\Middleware;
use Illuminate\Support\Facades\Auth;

use Closure;

class Permission
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next, $permission)
    {

        if(Auth::user()->hasPermission($permission)) {
            return $next($request);
        }
        return abort(404);
    }
}

```

```
Route::get('/test', function () {
    return view('welcome');
})->middleware(['permission:browse_admin']);
```

**Comment by fletch3555** [comment]
The default can middleware should already do that for BREAD permissions via policies.

Also, please don't comment on closed issues.  This one has been closed for ~9 months now
