### ISSUE TITLE
Image field in edit mode still asking for image as a 'required' field

### ISSUE THREAD

**Issue by harunthuo** [thedevdojo/voyager#3530]
**Version information**

- Laravel: v5.6.28
- Voyager: v1.1.3
- PHP: 7.1.11
- Database: 10.1.28-MariaDB

**Description**

Image field in edit mode still asking for image as a 'required' field.

**Steps To Reproduce**

1.Making image fields as 'required' using below JSON in the BREAD section
{ "validation": { "rule": "required" } }
works well in add mode.

![image_bread](https://user-images.githubusercontent.com/6682734/45170091-c128ec80-b207-11e8-83a3-ad65cf93dff9.png)

2. But in edit mode, it is still asking for an image.

![image_bread-edit](https://user-images.githubusercontent.com/6682734/45170273-2aa8fb00-b208-11e8-95a1-11576b2ecdfc.png)

**Expected behavior**

The image already exists and should therefore not get the 'The Image field is required.' prompt on edit

**Comment by harunthuo** [comment]
anyone?

**Comment by fletch3555** [comment]
I believe this is a known issue that hasn't been fixed yet.  I haven't had a chance to look, but I'm certain there's at least one open issue for this already.

**Comment by alaamebrahim** [comment]
there is an easy fix , use required_if instead of required
`
{
    "validation": {
        "rule": "required_if:id,null",
        "messages": {
            "required": "your message"
        }
    }
}
`
this will make it required in the create page only, or you can customize it as you wish.
required_if [ref](https://laravel.com/docs/5.6/validation#rule-required-if).

**Comment by harunthuo** [comment]
thankyou @alaamebrahim 

that is the actual solution.

i'll close this as resolved

**Comment by maxkopych** [comment]
@alaamebrahim It's not really a solution. Because you can delete image and save without it.
