### ISSUE TITLE
Invalid JSON dropdown

### ISSUE THREAD

**Issue by gintoki05** [thedevdojo/voyager#3531]
## Version information

 - Laravel: v5.6.#
 - Voyager: v1.1.#
 - PHP: 7.2
 - Database: [MYSQL] [version] (e.g. MySQL 8.0)

## Description

I got invalid json [ "SQLSTATE[22032]: <<Unknown error>>: 3140 Invalid JSON text: "Invalid value." at position 1 in value for column 'diagnostics.dtr'. (SQL: insert into `diagnostics` (`nopol`, `model`, `keluhan`, `analisa_penyebab_utama`, `job_instruction`, `kecepatan`, `putaran_mesin`, `beban_kendaraan`, `jumlah_penumpang`, `dtr`, `updated_at`, `created_at`) values (BG 123 ABG, Kapsul, Mogok, Rusak Mesin, Perbaiki, 50, 80, 30, 6, tidak, 2018-09-07 08:45:05, 2018-09-07 08:45:05)) ◀"
]
## Steps To Reproduce
1. Go to 'add data'
2. Click on 'dropdown'
3. See error

## Expected behavior
Data insert to database
## Additional context
Im using this in optional 
{
    "default" : "perlu",
    "options" : {
        "perlu": "Perlu",
        "tidak": "Tidak"
    }
}

**Comment by fletch3555** [comment]
That's a SQL error complaining about JSON format, which implies it's a JSON field you're saving to.  Yet the value you're saving is a string. These are incompatible. You should change your database field type if you want to use the dropdown like that

**Comment by gintoki05** [comment]
im using json type 

![screenshot from 2018-09-07 22-10-37](https://user-images.githubusercontent.com/26396390/45227517-e04c7a80-b2ea-11e8-8c07-b51f86d45443.png)

**Comment by fletch3555** [comment]
Yes, that confirms my previous comment.  The select dropdown is not valid for the json field type.  Voyager actually doesn't support much related to the JSON database field type

**Comment by gintoki05** [comment]
so how to fix it (what must i do), my english so bad so i cant catch the point that you explained. 
im just following this tutorial https://voyager.readme.io/docs/additional-field-options
