### ISSUE TITLE
sending a file from the admin to a user

### ISSUE THREAD

**Issue by fjerbi** [thedevdojo/voyager#3534]
I just wanna ask if it's impossible to make a section in the admin panel that allows him to send files to users.

If it's a yes  someone can help me , Thank You

**Comment by fletch3555** [comment]
First, we have issue templates for a reason, please use them.  If the existing templates don't seem to fit, then your question is likely not directly related to Voyager or is just "how do I do [thing]?", which is best asked in our Slack group.

As for your question, I have no idea what you mean by "send file to user"...

what user? The one logged into Voyager? Another user of your app? Random person elsewhere on the planet?

How are you sending them this file? Email? Teleportation? Download in the browser?

**Comment by fjerbi** [comment]
my question was simple, How can I add a section in the dashboard where the admin can upload and send for example fileslike  (pdf or images or smething else) to a user.
