### ISSUE TITLE
Table showing in the role page but not there in the database

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3535]
- Laravel: v5.6
 - Voyager: v1.1.3
 - PHP: 7.1.7
 - Database: MySQL 5.7.19)

## Description
Hello,
I am having an issue regarding the role page /admin/roles/2/edit. I have a table showing there which has been already deleted(via voyager), I cannot get rid of it. I have checked mysql and the table is not there.

Could you kindly please tell me where are these tables in the UI being pulled from so perhaps I can manually fix the issue by deleting the entry causing the issue.

Here is what I see via this url: /admin/roles/2/edit
https://www.screencast.com/t/GycMxB0vI

In my db I have only the "businesses" table as shown here:
https://www.screencast.com/t/XPbj4JCRF

I would also like to point out that if I do not tick all the boxes from both tables, when I access the page:
/admin/businesses/create

I get this error:
 Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized.

It looks like the scripts is reading the old settings for the roles but the new ones for the route, weird...I am confused.

I have been searching for hours, I cannot get it, where is your script registering this table from as the !menu_items" table only shows this route "voyager.businesses.index" for the table businesses, no other.

Thank you in advance,

**Comment by Benoit1980** [comment]
Ok you can close the issue.
I fixed it by removing the "business" records in the data_rows and data_types tables. Refresh the admin panel and the problematic table went away.
One thing that was weird is that my businesses table has not reset all its field to INT.

**Comment by FreddyCrugger** [comment]
closed

**Comment by Benoit1980** [comment]
closed
