### ISSUE TITLE
Limitation to 1 record

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3537]
It would be nice to allow us to limit a user to 1 record on certain tables.
ie: when the record is added the "add" button is removed.

**Comment by fletch3555** [comment]
This would fall under "business rules".  It would be impossible for Voyager to predict all possible business rules, and an attempt would be futile as the implementation would likely conflict with someone else's needs.

To get this, you will need to customize some parts of Voyager to add in that logic.  This isn't something we can directly support, but if you run into issues, please feel free to ask in our Slack group.
