### ISSUE TITLE
Remove "None" default value on relationship select box

### ISSUE THREAD

**Issue by daniel3303** [thedevdojo/voyager#3538]
It is possible to remove the default value "None" on a select box when the relationship is required?
Could not find any documentation on this.
![sem titulo](https://user-images.githubusercontent.com/36623265/45328094-35d69080-b552-11e8-8534-9a44026c8c58.png)

Thanks.

**Comment by emptynick** [comment]
Please use the issue-template, and for questions it's more easy to use our Slack group.
Whether you get the `None` option or not is determined on the column in your database.
Is it nullable you wont get it, if its not nullable you **have** to select a value.

**Comment by Vlad-Online** [comment]
Hi! I've BelongsToMany relationship, and I want to remove "None" value. All columns in pivot table are not nullable, but I've "None" value first in dropdown. If I select None or nothing, I got a 500 error. So how to remove this value or add validation to relationship?
Thank you!

**Comment by fletch3555** [comment]
Please open your own issue. This one has been closed for months
