### ISSUE TITLE
Can't see the default text for rich text box field.

### ISSUE THREAD

**Issue by miguelangelmagdalena** [thedevdojo/voyager#3540]
## Version information
 - Laravel: v5.6.33
 - Voyager: v1.1
 - PHP: 7.2.6
 - Database: MySql

## Description
I have a Bread with a rich text box field and some default text for this field, When I add a new record, I can't see the default text for this rich text box field.

This field in the database is type text. 

## Steps To Reproduce
1. In a Bread put a field rich text box type
2. Put default text for this in details of the field
{
    "default": "something"
}

Im new in Laravel and Voyager but,
**How can I do for display a default text for rich text box field. ?**

thx.

**Comment by donmbelembe** [comment]
The richtextbox does not support the default value (Maybe they forget)

look at  _vendor\tcg\voyager\resources\views\formfields\rich_text-box.blade.php_

`<textarea @if($row->required == 1) required @endif class="form-control richTextBox" name="{{ $row->field }}" id="richtext{{ $row->field }}">
    @if(isset($dataTypeContent->{$row->field}))
        {{ old($row->field, $dataTypeContent->{$row->field}) }}
    @else
        {{old($row->field)}}
    @endif
</textarea>
`

now compare with another form field for example text_area.blade.php

`<textarea @if($row->required == 1) required @endif class="form-control" name="{{ $row->field }}" rows="{{ $options->display->rows or 5 }}">
    @if(isset($dataTypeContent->{$row->field}))
        {{ old($row->field, $dataTypeContent->{$row->field}) }}
    @elseif(isset($options->default))
        {{ old($row->field, $options->default) }}
    @else
        {{ old($row->field) }}
    @endif
</textarea>
`

has you can see, the rich textbox don't support default value, 
Personally in some case I use to [Override the view](https://voyager.readme.io/docs/overriding-views) but I never tried with formfields

**Comment by miguelangelmagdalena** [comment]
Hmm ok, ok, thanks so much. So I will override the view.

I was confused because in [voyager docs](https://voyager.readme.io/docs/additional-field-options#section-text-text-box-text-area-rich-textbox-and-hidden-)  understanded that rich text box could have default.
