### ISSUE TITLE
Page title on BREAD builder index page is hardcoded

### ISSUE THREAD

**Issue by troyporter** [thedevdojo/voyager#3548]
## Version information

 - Voyager: v1.1

## Description

The page title on BREAD builder index page is hardcoded in the tools/bread/index blade.

## Steps To Reproduce
1. Go to BREAD builder index page

## Expected behavior
Should be able to customise the displayed text (BREAD) using a language key as it is with all the other text.

## Screenshots

![image](https://user-images.githubusercontent.com/1162790/45590560-a68dfc00-b908-11e8-8b92-dd4ba9f1efd1.png)

**Comment by fletch3555** [comment]
BREAD is an acronym, not a word, and therefore we chose not to make it translatable.  I'm not opposed to reviewing a PR to change it, but it's definitely not a priority for us.

**Comment by troyporter** [comment]
No problem.

**Comment by emptynick** [comment]
Fixed in #3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/cd4f8236c03f8fc7284e99af4c50d417d4a2e345
