### ISSUE TITLE
Bug on bulk delete that include columns with files

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3551]
Laravel Framework 5.6.38
Voyager v1.1.3
PHP 7.1.7

Hello,

I have noticed a bug when you create column the type  file in the BREAD
On bulk deletion I receive this error:

 ErrorException (E_WARNING)
Invalid argument supplied for foreach()

```
        // Delete Translations, if present
        if (is_bread_translatable($data)) {
            $data->deleteAttributeTranslations($data->getTranslatableAttributes());
        }
 
        // Delete Images
        $this->deleteBreadImages($data, $dataType->deleteRows->where('type', 'image'));
 
        // Delete Files
        foreach ($dataType->deleteRows->where('type', 'file') as $row) {
            foreach (json_decode($data->{$row->field}) as $file) {
                $this->deleteFileIfExists($file->download_link);
            }
        }
    }
```

But on single deletion everything is fine.

**Comment by emptynick** [comment]
This looks extremly similar: https://github.com/the-control-group/voyager/issues/1855

**Comment by Benoit1980** [comment]
Thanks yes you are right, this is the same issue, I will close this issue.
