### ISSUE TITLE
Media Manager Bugs

### ISSUE THREAD

**Issue by Akopean** [thedevdojo/voyager#3554]
## Version information

        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/psr7": "^1.4",
        "laravel/framework": "5.6.*",
        "laravel/passport": "^7.0",
        "laravel/tinker": "^1.0",
        "okta/jwt-verifier": "^0.2.1",
        "tcg/voyager": "^1.1",

## Description

See the screenshot

## Steps To Reproduce
1. Go to Media Page
2. Click on 'Enter' non stop, many time
3. Open Dev tools

## Screenshots
![image](https://user-images.githubusercontent.com/13051822/45600578-b17b8600-ba07-11e8-9e5e-7cb040084dfe.png)

**Comment by Akopean** [comment]
And some one error  i have, if  i  rebuild assets,  i have error not see  variable newSelected
media.js
![image](https://user-images.githubusercontent.com/13051822/45601298-ae869280-ba13-11e8-9aeb-10e2f9dea32a.png)

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3838 (Merged into 1.x)
