### ISSUE TITLE
What is the point of Media Feature?

### ISSUE THREAD

**Issue by mladenilic66** [thedevdojo/voyager#3555]
- Laravel: v5.4.*
 - Voyager: v1.1.*
 - PHP: 5.6.*
 - Database: MySQL 5.7

## Description of problem
What is the point of Media Feature in _voyager_ if you can't use those media images to update user avatar or post image etc. It's only for viewing and deleting.

## Proposed solution
Remove or Upgrade :)

## Additional context
![alt text](https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2017/01/148399251207.jpeg "Media")

**Comment by fletch3555** [comment]
PRs are welcomed
