### ISSUE TITLE
Licensing clear explanation

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3557]
Hello,

I would like to know if you could show your license in a clear way on your website please as I love your script
Are we allowed to create an admin panel with a front end and resell our work to an unlimited amount of customers? 

Thank you.

**Comment by emptynick** [comment]
Our license is [here](https://github.com/the-control-group/voyager/blob/1.1/license) where it belongs.
Also, please ask questions in our Slack group.
