### ISSUE TITLE
Animated icons needed

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3559]
Hello,

It would have been great to have 2 or 3 animated icons in your icon library so we do not have to download each time font awesome for button loading animations(when using axio or ajax).

Thank you.

**Comment by fletch3555** [comment]
You don't have to download it each time.  It'll be cached in the browser.

I don't really see us adding this

**Comment by Benoit1980** [comment]
Sorry what I meant was downloading a new library upon each installation of Voyager to have this tiny feature (font awesome for example), If this is too much of a problem, no worry, I will close this feature request. 

Thank you.

**Comment by emptynick** [comment]
Closing.
