### ISSUE TITLE
SYmLink() issue when installating Voyager- Laravel in a sub folder

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3560]
Voyager V.1.1.3

I have noticed an issue when you create subdomain and install Laravel the proper way which is below the public_html folder(so the installation core files are not public)
www.laravel.mywebsite.com

ie:
laravel/public_html

I then added my public folder symlink with the storage to:
public_html/storage

I then created my symlink like this:
ln -s /home/username/laravel/storage/app/public/ /home/username/public_html/customer/storage

While Laravel is working perfectly using this method

Voyager is sending me an error about the symlink not being found in the filesystem.php

The only way around this was to recreate a secondary symlink with:
php artisan storage:link

The issue is that this is completely redundant because the actual real used symlink is above the public_html folder.

I think what is needed is a new setting in voyager that allow us to disable the symlink check(true or false) or a way to tell Voyager that the new symlink is somewhere else.
If this setting already exists please let me know and I will close this issue right away.

Thank you.

**Comment by fletch3555** [comment]
It works perfectly fine,. You're just missing a step.

In short, you have to tell Laravel that your `public` directory isn't `public` anymore.  You can do so by overriding `path.public` in the DI container:

```
$app->bind('path.public', function() {
    return realpath(__DIR__.'/../'); // change to whatever your path is, relative to wherever you add this snippet
});
```

**Comment by Benoit1980** [comment]
Thank you so much, yes you are right, while looking at the issue tonight I found this thread:
https://stackoverflow.com/questions/31758901/laravel-5-change-public-path

I will check this out tomorrow morning, good one and thank you for your support.

**Comment by fletch3555** [comment]
@FreddyCrugger, did you confirm this is working? Can we close the issue?
