### ISSUE TITLE
Unable to create or edit Menus and Categories

### ISSUE THREAD

**Issue by mtshikomba** [thedevdojo/voyager#3561]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1.20
 - Database: [MySQL] [5.7.19]

## Description

I just made a fresh installation of the Laravel Framework and installed the Voyager package, the installation was successful. But when ever i try to create or edit pages, categories via the admin panel i get the error in the image below

## Steps To Reproduce
1. Go to the voyager admin panel 
2. Click on 'Pages' in the side navigation menu
3. Click 'Add new' page or 'Edit' an a existing page

## Expected behavior
An ErrorException is rendered 

## Screenshots
![voyager error](https://user-images.githubusercontent.com/10866232/45655830-700bd900-bae2-11e8-970f-3e496790035e.PNG)

## Additional context
The same error also happens when you navigate to Categories in the side navigation menu and do the same actions.

**Comment by shenxn** [comment]
This is caused by the removing of 'or' operator in Laravel 5.7. I've already created a [pull request](https://github.com/the-control-group/voyager/pull/3562) that should fix the problem.

**Comment by mtshikomba** [comment]
Great, Thank you!

When will this be completed and ready for use?

**Comment by anwar0x09** [comment]
I'm also facing samethings
