### ISSUE TITLE
ERROR: duplicate key value violates unique 

### ISSUE THREAD

**Issue by Asahro** [thedevdojo/voyager#3563]
## Version information

 - Laravel: v 5.6.38
 - Voyager: v 1.1.0
 - PHP: 7.0
 - Database: [PostgreSQL] [10.5]

## Description
When I add voyager bread there are a error like this, I follow this totorial

https://www.youtube.com/watch?v=CGALfsrpZb8&index=8&list=PL_UnIDIwT95NureFNedKN9_GA6UOiS2ox

is there any step I miss that make this error

SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "data_types_pkey" DETAIL: Key (id)=(2) already exists. (SQL: insert into "data_types" ("name", "display_name_singular", "display_name_plural", "slug", "icon", "model_name", "controller", "policy_name", "generate_permissions", "details", "description", "server_side", "updated_at", "created_at") values (list_jabatan, List Jabatan, List Jabatans, list-jabatan, , App\ListJabatan, , , 1, {"order_column":null,"order_display_column":null}, , 0, 2018-09-18 06:48:16, 2018-09-18 06:48:16) returning "id")

## Screenshots
![Uploading image.png…]()

**Comment by fletch3555** [comment]
You need to add validation rules to your field in BREAD.  https://voyager.readme.io/docs/validation

Voyager will accept any validation rule that's allowed in Laravel, not just ones mentioned in our documentation.

**Comment by smitpatelx** [comment]
@fletch3555  This was not the fix. I think it happens when you clear cache. Does anyone have any solution regarding this problem? 
```php
SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "data_rows_pkey" DETAIL: Key (id)=(35) already exists. (SQL: insert into "data_rows" ("field", "data_type_id", "browse", "read", "edit", "add", "delete", "required", "type", "details", "display_name", "order") values (email_verified_at, 3, 1, 1, 1, 1, 1, 0, timestamp, {}, Email Verified At, 5) returning "id")
```
It works after send the request many times while the id will increment by 1.
This can possibly happen because of Database SEQUENCE.
```sql
ALTER SEQUENCE product_id_seq RESTART WITH [number to start from];
//for example - ALTER SEQUENCE product_id_seq RESTART WITH 8;
```
You guys need to take this seriously and build inbuild code to adjust autoincrement id.
If you need any help in development, I would like to help you.

**Comment by smitpatelx** [comment]
PgSql statment for fixing these problems.
```sql
SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id),1), false) FROM users;
```
Modify according to your databse structure.
