### ISSUE TITLE
Changing a table name

### ISSUE THREAD

**Issue by brasiqui** [thedevdojo/voyager#3565]
## Version information

 - Laravel: 5.5.43
 - Voyager: v 1.1
 - PHP: 7.2.9
 - Database: MySql 10.1.35-MariaDB

## Description:
If I change the table name, (eg. from bolas to bolos) the model App\Bolas is still there and not my new model name. If I manually change the model name, it's work.

**Comment by fletch3555** [comment]
If you change the table name through the DBMS directly (i.e. phpmyadmin or sequel pro), or through a migration, Voyager has no way of knowing it was changed, and obviously won't be able to react.

If you change it through Voyager's DB editor, Voyager doesn't know if you want to keep the model the same and add `$table = 'newTableName'` or change the model class name.  Adding this information would over-complicate the relatively simple process of changing the table name.

Voyager can't do everything for you, so I doubt we'll be adding any functionality to handle this.  Model classes are meant to be a layer of abstraction from the database, so it makes sense that it wouldn't be automatically changed when changing the table name.

**Comment by ayazdev** [comment]
Is there any way to change the table name in current version ?
