### ISSUE TITLE
Adding Avatar photo upload on registration page

### ISSUE THREAD

**Issue by spooksie** [thedevdojo/voyager#3567]
I've been scratching my head on how to add the avatar photo upload working on the front-end of my app with Voyager. I've checked the documentation and nothing is clear. 

Am I missing something? as I can only upload if I'm in Admin on voyager and want my users to be able to upload the photo.

**Comment by fletch3555** [comment]
We have issue templates for a reason, please use them.  They make our lives so much easier.  https://github.com/the-control-group/voyager/tree/1.1/.github/ISSUE_TEMPLATE

Having said that, all Voyager really does is store values in the database, so you can repeat this process yourself.  Take a look at Voyager's code and it should be fairly self-explanatory.  In short, the avatar field is just a URL path to the avatar image (Usage example: https://github.com/the-control-group/voyager/blob/1.1/resources/views/master.blade.php#L61 && https://github.com/the-control-group/voyager/blob/1.1/resources/views/dashboard/sidebar.blade.php#L22).  If you want to change it, then upload the image, store it somewhere on the filesystem (I recommend using the same `disk` that Voyager is configured to use. `public` by default), then set `$user->avatar = $pathToImageAsString`.  Remember that the path must be relative to the web root (usually the `public` directory).

**Comment by spooksie** [comment]
Thanks for your response, I've managed to get the avatar url and it works great. I want to be able to let my users upload a photo from the registration page. I just can't find the method on how Voyager does it. Like 'browse' image and 'upload'. 

Thanks again

**Comment by fletch3555** [comment]
You don't necessarily NEED to do it how Voyager does it.  It's just an image upload, save the file to `storage/app/public/<path to image>`. then save `<path to image>` in `avatar` field in database

**Comment by fletch3555** [comment]
Did you get this working? If so, please feel free to close this issue.
