### ISSUE TITLE
image not loaded  background-image:url(storage/{{$about->image_about}});

### ISSUE THREAD

**Issue by farizree** [thedevdojo/voyager#3573]
## Version information

 - Laravel: v5.5.*
 - Voyager: v1.1
 - PHP: 7.1.3
 - Database: [MariaDB [10.1.30]

## Description

I have a problem when using `background-image:url(storage/{{$about->image_about}});`
in inspect element ("storage/aboutsSeptember2018VFyOLNy79hB4Cn2liOPo.jpg") 

but not issue if using `<img` src="storage/{{$about->image_about}}">
in inspect element "storage/abouts\September2018\VFyOLNy79hB4Cn2liOPo.jp 

## Screenshots
![image not loaded](https://user-images.githubusercontent.com/25852713/45919997-7f1ace80-bec8-11e8-96f8-2cae0694c23e.png)

![image](https://user-images.githubusercontent.com/25852713/45920005-9954ac80-bec8-11e8-8e2e-cb03d5073728.png)

**Comment by fletch3555** [comment]
You're using a relative URL (`storage/......`).  That will attempt to load the image starting from the current context.  For example, if you're on the Voyager dashboard page (i.e. `example.com/admin/`), it will try to load the image at `example.com/admin/storage/.....`, which won't exist.  Instead, you should use an absolute URL (`/storage/......`), which always starts at the domain root.  This is especially important for image links in CSS files as relative URLs would start from the path of the CSS file (i.e. `/css/storage/.....`).
