### ISSUE TITLE
No funciona el SoftDeletes

### ISSUE THREAD

**Issue by adrian-ub** [thedevdojo/voyager#3574]
## Version information

 - Laravel: v5.7.5
 - Voyager: v1.1.5
 - Database: MySQL 

## Description

Al intentar borrar con SoftDeletes lo borra de la base datos 

## Steps To Reproduce
1. Agrego SoftDeletes al modelo
2. Clic a borrar
3. Se borra de la base de datos

**Comment by fletch3555** [comment]
English please
