### ISSUE TITLE
Add Another button on browse

### ISSUE THREAD

**Issue by Asahro** [thedevdojo/voyager#3577]
Is there any way to add html code (specially a buttom or a link) in this table witchout edit hardcode ?
![image](https://user-images.githubusercontent.com/24727474/45944918-104b8b80-c016-11e8-83c8-8a05be7b3d8f.png)

**Comment by MaTToX3** [comment]
I did it with overriding views. Just copy the original file and add your button or a link.

Check docs: https://voyager.readme.io/docs/overriding-views

**Comment by fletch3555** [comment]
Just add an `Action` class.

You create a class that extends [TCG\Voyager\Actions\AbstractAction](https://github.com/the-control-group/voyager/blob/1.1/src/Actions/AbstractAction.php), then add it to a ServiceProvider like this: `Voyager::addAction(MyNewAction::class)`.  As an example, you can copy the Edit button Action class here: https://github.com/the-control-group/voyager/blob/1.1/src/Actions/EditAction.php

**Comment by Asahro** [comment]
I think itswill be greet if we can add it using html data at the form

**Comment by ikramulmustafa** [comment]
@fletch3555  how can we remove edit action button from any 1 browse page?
