### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by gultyayev** [thedevdojo/voyager#3578]
I've noticed that there is no datepicker built in Safari. Therefore, I ask developers to add some JS datepicker to fields so that Safari and IE users could use these fields without having to write date manually.

**Comment by emptynick** [comment]
This has been reported in various issues (e.g. https://github.com/the-control-group/voyager/issues/1806) and has been fixed on `1.x` in https://github.com/the-control-group/voyager/pull/3334
Also, please use the issue-template.
