### ISSUE TITLE
Autocomplete for big amount of data in relationship

### ISSUE THREAD

**Issue by vince83110** [thedevdojo/voyager#3581]
## Version information
 - Laravel: v5.6
 - Voyager: v1.1.5
 - PHP: 7.2

## Description of problem
I have in one of my relationships a big amount of data to display, the dropdown is filled by more than 30000 options and it makes the navigator crash.

## Proposed solution
Is there any way I missed to use Autocomplete Ajax dropdown for relationships field ?

**Comment by vince83110** [comment]
Ok, I added PR for this problem : https://github.com/the-control-group/voyager/pull/3586

Thanks for your work !

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3586
