### ISSUE TITLE
BREAD not deleting images

### ISSUE THREAD

**Issue by gultyayev** [thedevdojo/voyager#3582]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 5.7.16

## Description
When deleting record created with BREAD the image is not deleted from the storage.

## Steps To Reproduce
1. Create a DB table with column for image (path)
2. Create BREAD for that table and specify `image` on that column
3. Add a record with an image
4. Delete the record
5. See the image in the storage that had to be removed but wasn't

## Expected behavior
Image should be removed from the storage since it belongs to the record.

**Comment by emptynick** [comment]
Please show us a screenshot of your bread-settings for that table

**Comment by gultyayev** [comment]
![screen shot 2018-09-25 at 18 54 24](https://user-images.githubusercontent.com/22374911/46026599-73abeb00-c0f4-11e8-8271-e67114a6e450.png)
![screen shot 2018-09-25 at 18 52 39](https://user-images.githubusercontent.com/22374911/46026527-46f7d380-c0f4-11e8-907c-c858009d7af6.png)

**Comment by MrCrayon** [comment]
This should be fixed in current release, if you are still experiencing the problem please open another issue.
