### ISSUE TITLE
symlink(): Protocol error

### ISSUE THREAD

**Issue by flythenimbus** [thedevdojo/voyager#3585]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.5
 - PHP: 7.2.9
 - Database: MySQL 5.5

## Steps To Reproduce
1. Install Voyager via `php artisan voyager:install --with-dummy`
2. Let it progress and do its thing
4. See error:

```
Adding the storage symlink to your public folder

In Filesystem.php line 228:

symlink(): Protocol error
```

## Expected behavior
I expected it to finish the installation smoothly.

## Additional context
I read that this might be due to the `public` path being different than `public/`, but I never changed it. I run Laravel locally via Homestead (Vagrant and Virtualbox).

**Comment by tnylea** [comment]
That is pretty strange. I usually use Valet.

Just to narrow down the issue... You are SSH'd into your vagrant machine when you run the install command, correct?

Have you installed Valet before? 

I used to use Homestead and after I moved to Valet, I've never looked back 👍

**Comment by flythenimbus** [comment]
Figured it out! So for someone who might need this in the future:

This issue happens when you try to create symlinks from the Ubuntu VM, but the files will reflect on the Windows machine. You don't normally have permissions to create these files on Windows without administrator permissions.

These steps fix the issue:

1. `vagrant halt` the VM if it's running
2. Open Command Prompt or Git Bash with administrator permissions
3. Go to your Homestead directory and `vagrant up`
4. `vagrant ssh` into the VM and `cd` into your project with Voyager
5. Run `php artisan storage:link`

You should get a success message and the error that I got shouldn't appear. 

--------------------------------

@tnylea I'd love to use Valet, but sadly it's unavailable for Windows.

**Comment by ramden** [comment]
Same here, not everybody uses a Mac
