### ISSUE TITLE
Base table or view already exists

### ISSUE THREAD

**Issue by mohsenuss91** [thedevdojo/voyager#3591]
When I run 
`php artisan voyager:install --with-dummy`

I get this error:

 Base table or view already exists
`C:\project\Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 La table 'users' existe déjà")`

I guess that "users" table is already reserved by laravel !

**Comment by DrudgeRajen** [comment]
You need to confirm that you have empty database before running the command. If you will have users table in your database then you will obviously get this error.

**Comment by mohsenuss91** [comment]
@DrudgeRajen  Already done!

**Comment by fletch3555** [comment]
Voyager doesn't provide a migration to create a `users` table.  It simply relies on the default Laravel one to run.  Once you figure out where the extra `users` table creation is coming from, you should be able to re-run the `voyager:install` command.

If you have further questions or need help getting past this, please ask in our Slack group.

**Comment by mohsenuss91** [comment]
@fletch3555 Affirmative.
