### ISSUE TITLE
image hosting does not appear on the voyager laravel admin

### ISSUE THREAD

**Issue by sumantris** [thedevdojo/voyager#3594]
## Version information

 - Laravel: v5.6.*
 - Voyager: v1.1.*
 - PHP: 7.1.*
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

the image does not appear on the website user and admin

## Expected behavior
all I want is running smoothly both user and admin application

## Screenshots
<img width="1280" alt="screen shot 2018-10-01 at 11 57 50" src="https://user-images.githubusercontent.com/7628965/46326937-c96f1e80-c631-11e8-8cc7-ee2b6c3c455f.png">

## Additional context
please help for the problem above, thank you.

**Comment by fletch3555** [comment]
Can you confirm you have a `storage` symlink under `/path/to/laravel/public`?

Can you verify the images actually exist? Path should be `/path/to/laravel/storage/app/public/posts/Octover2018/`

**Comment by sumantris** [comment]
> Can you confirm you have a `storage` symlink under `/path/to/laravel/public`?
> 
> Can you verify the images actually exist? Path should be `/path/to/laravel/storage/app/public/posts/Octover2018/`

I have set the path to app / public / storage but the results are still the same

**Comment by jmmedel** [comment]
.env file APP_URL= 
If the URL is wrong getting wrong path may friend just clone my project we got this error just check you .env file APP_URL the path samer if you are using localhost you need to add the port number to 
http://localhost is different with http://localhost:8000

**Comment by sumantris** [comment]
> .env file APP_URL=
> If the URL is wrong getting wrong path may friend just clone my project we got this error just check you .env file APP_URL the path samer if you are using localhost you need to add the port number to
> http://localhost is different with http://localhost:8000

on localhost it runs normally, but on cpanel hosting that doesn't run normally for the image. please help

**Comment by jmmedel** [comment]
Do TEST
Create Laravel app install only the voyager add some dummy file to see if works or not 
I never test to Deploy  this on hosting site .
Contact the Voyager maintainer how to Fix

**Comment by deyvsonaguiar** [comment]
Really, it's important to verify on .env the APP_URL because the image does not show on display ... In my case, for example, I use the "php artisan serve" that set the port 8000 on localhost, sure I geted the value and pasted to APP_URL

**Comment by sumantris** [comment]
> Really, it's important to verify on .env the APP_URL because the image does not show on display ... In my case, for example, I use the "php artisan serve" that set the port 8000 on localhost, sure I geted the value and pasted to APP_URL

Really, I have done it like that to run on localhost and run well, only when the cpanel hosting image cannot appear in the website.

**Comment by MrCrayon** [comment]
Closed for inactivity. 

If you are still experiencing this problem feel free to open another issue.
