### ISSUE TITLE
Cannot create BREAD for database created in voyager

### ISSUE THREAD

**Issue by samkerzhnerman** [thedevdojo/voyager#3597]
## Version information
 - Laravel: v 5.7.6
 - Voyager: v1.1
 - PHP: 7.1.19
 - Database: MariaDB 10.1.36

## Description
I created database 'news' successfully in voyager admin panel. Model also created successfully. Now I want to create BREAD for it. When I click on the appropriate button, I get the following error (see the screen attached).

![scn-20181002-180436-pyon7](https://user-images.githubusercontent.com/39809841/46357490-a82c2380-c66d-11e8-9b3a-3256ea0328db.png)

**Comment by SirPaulO** [comment]
Same here!

**Comment by jovixv** [comment]
you can update it, https://github.com/the-control-group/voyager/pull/3596

**Comment by samkerzhnerman** [comment]
> you can update it, #3596

Thank you. Sorry for dumb question, but can you please link me to the instruction on how I can update my voyager code to include your fix? I changed the line to "tcg/voyager": "1.x-dev" in my composer.json, then did composer update, it updated, but I still have the error. Probably I use wrong value?

**Comment by fletch3555** [comment]
That would be because it's not merged yet.
