### ISSUE TITLE
Manipulating Edit/Add/Read forms from Laravel Voyager BREAD using col-md

### ISSUE THREAD

**Issue by jasonxsiervo** [thedevdojo/voyager#3598]
- Laravel: 5.6.38
 - Voyager: v1.0.11
 - PHP: 7.2.2
 - Database: Mysql 10.1.30

I wanted to edit the view/add/edit of the form used by voyager since the day I first used it because the space a form takes is almost the whole width of the body. I tried to use col-md to divide the forms in equal parts to save space but the code of voyager is very hard to understand and I don't know which form goes to this place and that. 

Can someone help me understand its blade structure or tell me if its possible to use col-md to organize it?

**Comment by emptynick** [comment]
This is mentioned in our [readme](https://voyager.readme.io/docs/display-options)
Also, please ask questions in our Slack-Group.
