### ISSUE TITLE
Relationship type "Belongs to" doesn't work. 

### ISSUE THREAD

**Issue by samkerzhnerman** [thedevdojo/voyager#3599]
## Version information
    Laravel: v 5.7.6
    Voyager: v1.1
    PHP: 7.1.19
    Database: MariaDB 10.1.36

## Description

Relationship type "Belongs to" doesn't work. 

Assuming I have a comments DB, each comment is related to one User and one News post. I have the following relationships (see the screenshot). 

![scn-20181003-171423-eg18n](https://user-images.githubusercontent.com/39809841/46416259-d1ad8380-c72f-11e8-9f7b-56ca88ca2f92.png)

I add new comment via BREAD and I am able to assign a user and a news post to it. 

![scn-20181003-171608-zwloz](https://user-images.githubusercontent.com/39809841/46416361-0ae5f380-c730-11e8-9e09-87ee13e8fed7.png)

But after I click the Save button, I only see comment text, while related user and news post are not added.

![scn-20181003-171638-2igsa](https://user-images.githubusercontent.com/39809841/46416388-1e915a00-c730-11e8-832f-cbf1986dfd38.png)

I was able to use "Belongs to many" relationship successfully, so I don't think there is a problem with my environment settings.

**Comment by fletch3555** [comment]
Do you see your data in the database (via CLI/PHPMyAdmin/SequelPro/etc)?  Based on what you've shown, the data should be stored in the `user_id` and `news_id` fields on your `comments` table.

**Comment by samkerzhnerman** [comment]
> Do you see your data in the database (via CLI/PHPMyAdmin/SequelPro/etc)? Based on what you've shown, the data should be stored in the `user_id` and `news_id` fields on your `comments` table.

No. They are filled with default values (zero). The comment row added successfully but user_id and news_id are filled with default values.

![scn-20181003-173009-8cc7e](https://user-images.githubusercontent.com/39809841/46417369-25b96780-c732-11e8-80bd-738a104c5fd9.png)

**Comment by emptynick** [comment]
Can you show us a screenshot of the bread settings for that rows (not the relationship details)?
I'm curious what the types are for those fields.

**Comment by samkerzhnerman** [comment]
> Can you show us a screenshot of the bread settings for that rows (not the relationship details)?
> I'm curious what the types are for those fields.

Not sure what do you mean.
My last screenshot was from phpmyadmin, here is the full table (comments):

![scn-20181003-180212-c0mhx](https://user-images.githubusercontent.com/39809841/46419421-7cc13b80-c736-11e8-8018-9e44e8dc45ec.png)

If you mean you want BREAD for comments table, here it is:

![screenshot_2018-10-03 edit bread for comments table](https://user-images.githubusercontent.com/39809841/46419596-e93c3a80-c736-11e8-9c84-7d73d04cdc23.png)

**Comment by emptynick** [comment]
Both `user_id` and `news_id` are not addable or editable.
Make sure to check the checkboxes.

**Comment by samkerzhnerman** [comment]
> Both `user_id` and `news_id` are not addable or editable.
> Make sure to check the checkboxes.

So I may uncheck "Browse" to hide them, but other checkboxes should be checked, correct?
As far as I remember I did that when tried to fix things but it didn't help - but tomorrow I will let you know for sure.

**Comment by DrudgeRajen** [comment]
Related to #2788

**Comment by samkerzhnerman** [comment]
This is to inform that I checked boxes (read,edit,add,delete) in BREAD for news_id and user_id and I was able to assign comments to news and users successfully. Thank you for your help and thank you for developing such a great product.
![scn-20181004-122729-5xvlb](https://user-images.githubusercontent.com/39809841/46465379-1d643980-c7d1-11e8-9b07-a14904ae77bc.png)
![scn-20181004-122945-z9954](https://user-images.githubusercontent.com/39809841/46465423-379e1780-c7d1-11e8-9bb9-572d55c44413.png)
