### ISSUE TITLE
Can't login to admin-panel

### ISSUE THREAD

**Issue by berrymoor** [thedevdojo/voyager#36]
Always get error:

**BadMethodCallException in Controller.php line 107:** Method [hasTooManyLoginAttempts] does not exist.

_laravel on local host with running MAMP PRO_

**Comment by fletch3555** [comment]
@berrymoor, Is this vanilla Voyager, or did you add it to an existing project?

hasTooManyLoginAttempts() is defined in the Trait: \Illuminate\Foundation\Auth\ThrottlesLogins

Are you using Auth in your project?

**Comment by marktopper** [comment]
Closed due to inactivity.
