### ISSUE TITLE
Return items from menu("example") just array to template

### ISSUE THREAD

**Issue by cpreston321** [thedevdojo/voyager#3600]
## Version information

 - Laravel: v5.6.#
 - Voyager: v1.1.^
 - PHP: 7.*

## Description of problem
So when I use menu('example') it will create the html for it but there is no way to get the items in array passed to template, so I can use the array with items from menu to create my own list. TCG\Voyager\Models\Menu::display(); 

## Proposed solution
TCG\Voyager\Models\Menu::display("name", false); or something that I can just get the items from array. I used my own solution for a while but would like it to be implemented 

`// Check to see if they only want the data comming from menu`
`if($type && !is_string($type)) {`
 `    return $menu->parent_items->sortBy('order');`
`}`

**Comment by fletch3555** [comment]
I don't really understand what you're trying to solve.  `Menu::display()` already takes a 2nd parameter which is the Blade view path to use when rendering the menu.  Why do you need the menu as an array?

**Comment by emptynick** [comment]
This will be possible when https://github.com/the-control-group/voyager/pull/3571 is merged.
