### ISSUE TITLE
Settings list is empty

### ISSUE THREAD

**Issue by gultyayev** [thedevdojo/voyager#3605]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

Created setting is displayed empty though it has 2 fields.

## Steps To Reproduce
1. Create setting with name Socials
2. Open Socials
3. See the empty list
4. Repeat steps 2 and 3 until you understand that nothing changes

## Expected behavior
Should display possible options

## Screenshots
![screen shot 2018-10-06 at 13 46 25](https://user-images.githubusercontent.com/22374911/46570569-cac08400-c96e-11e8-9214-6293c1f47955.png)
![screen shot 2018-10-06 at 13 46 34](https://user-images.githubusercontent.com/22374911/46570571-cb591a80-c96e-11e8-9af4-7295d612dc6e.png)

## Additional context
Idk what caused that problem. There are no errors in logs.

**Comment by emptynick** [comment]
I can't recreate what you describe.
Can you tell us which values you use exactly? Name, key, type, group?

**Comment by gultyayev** [comment]
@emptynick there is a second image below. It's a screenshot from my DB with created but yet not shown settings.

**Comment by gultyayev** [comment]
I just tried to recreate this situation. So I just removed the rows with "Socials" and recreated it. Now it's not shown again. However, if I do create a new setting group with other name than "Socials" then it works at it should. I can't understand what's wrong with this name

**Comment by emptynick** [comment]
Sorry, did not see your second image.
I can't reproduce this behaviour, also with `Socials` as the group-name.

**Comment by gultyayev** [comment]
Solved the problem 🤣 That was an AdGuard which was hiding the content of "social buttons".
