### ISSUE TITLE
Image not showing - After install Voyager with dummy

### ISSUE THREAD

**Issue by mehadihasan** [thedevdojo/voyager#3607]
- Laravel: 5.7.8
 - Voyager: 1.1
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
After login Images are not showing. In Screenshots Admin avatar not showing.

## Screenshots
![voyegar](https://user-images.githubusercontent.com/6083507/46575475-7a314100-c9d7-11e8-82ca-560333b332c4.png)

**Comment by fletch3555** [comment]
Please search issues here before opening a new one.  That has been mentioned numerous times.

In short,
1. Make sure your APP_URL is set properly (i.e. it includes a port number if that's how you access your site)
2. Make sure the storage symlink exists at `<project root>/public/storage` and points at `<project root>/storage/app/public`

**Comment by mehadihasan** [comment]
Yes, now working! There was no port number before.
Sorry for my mistake.
