### ISSUE TITLE
Error Removing Image

### ISSUE THREAD

**Issue by AlterwebStudio** [thedevdojo/voyager#3608]
## Version information

 - Laravel: v5.6.38
 - Voyager: v1.1.5
 - PHP: 7.2
 - Database: MySQL 5.7.21

## Description
Removing media from multiple image gallery. 

## Steps To Reproduce
1. Create new BREAD
2. Set one of the fields to multiple image type
3. Create new Post and Upload photo to gallery (JPG)
4. Try to remove it using the "x" icon in left bottom corner of photo
5. The error message says "Error removing image"

## Expected behavior
I'm expecting removing a photo from server and set the field value to NULL if no another photos are stored in it.

## Screenshots
![snimka obrazovky 2018-10-06 o 23 44 36](https://user-images.githubusercontent.com/34649105/46576063-12243000-c9c2-11e8-94a9-610590586dc6.png)

**Comment by bsubramanian-a** [comment]
Hello @emptynick @fletch3555,
I am going to work on this issue. Please let me know if this is already resolved and needs to be fixed. 
Thanks,
Karthik

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3240
