### ISSUE TITLE
How to make users view...

### ISSUE THREAD

**Issue by kkkasio** [thedevdojo/voyager#3609]
Hello friends, your work is incredible .. an extraordinary time gain .. now I have a big question in the head, how to create the view of the common user?

should I do it inside the admin panel myself?

or should I create it outside the tool? I searched a lot and did not see anything related. Would you have something to show?

Thank you, Brazil souvenirs.

**Comment by fletch3555** [comment]
First off, please make use of our issue templates. They help make sure the appropriate info is provided.

Second, I'm not sure what you mean by "view for the common user".  Could you explain further?

Third, this question is probably best asked in our Slack group.  We try to reserve github issues for actually issues in the project code and feature requests.

**Comment by kkkasio** [comment]
> First off, please make use of our issue templates. They help make sure the appropriate info is provided.
> 
> Second, I'm not sure what you mean by "view for the common user". Could you explain further?
> 
> Third, this question is probably best asked in our Slack group. We try to reserve github issues for actually issues in the project code and feature requests.

Sorry friend, for the inconvenience. I'll use the stack!

**Comment by emptynick** [comment]
Then I will close this.
