### ISSUE TITLE
First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by DrudgeRajen** [thedevdojo/voyager#3610]
## Version information
 - Laravel: 5.5.*
 - Voyager: ^1.1
 - PHP: 7.2
 - Database: Postgress 9.5.3

## Description

When a bread with **select dropwdown input type** is created and **if kept options field empty** **then the browse feature of voyager will not work.** 

## Steps To Reproduce
1. Create New Table with at least one field.
2. Create new Bread for that table and keep the input type as select dropdown and left empty the options for that rows
3. Try to browse the newly created bread. 

## Expected behavior
It should browse the bread.

**Comment by DrudgeRajen** [comment]
#1157 #2464

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3637
