### ISSUE TITLE
How to create new permissions

### ISSUE THREAD

**Issue by kh3kh3kh3** [thedevdojo/voyager#3615]
In addition to browse, viewing, adding, editing, deleting, I would like to add some more permissions as I see it or every body to see. I get help documentation. Ask for help on this issue, or suggest a solution
![untitled](https://user-images.githubusercontent.com/44015298/46715422-1c784f80-cc8a-11e8-9a92-21d712c53d31.png)

**Comment by fletch3555** [comment]
Please use the issue templates we've provided. It guarantees you're providing the basic info we need to troubleshoot issues, including version information.  If you find it doesn't apply to your question, then your question is likely best asked in our slack group instead.

As for your question, just add BREAD to the permissions table and create new entries there.  Alternatively, you can add it directly to the database (or via migrations/seeders).
