### ISSUE TITLE
How to sort relationship results

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3617]
## Description
There is no documentation on how to control the order of data in the select control. 

For example:
I have a me_device_types table with the columns **id, me_device_type** and **order**.

In my BREAD for me_devices, I have the relationship setup as shown here:
![image](https://user-images.githubusercontent.com/6446167/46739740-dc53a580-cc66-11e8-8edf-142139afcae4.png)

I want the result sorted by **order**

How can I do this?

**Comment by rrbotelho** [comment]
if you click in the table header it will be reordered

or you can override the controller, configure it in bread builder https://voyager.readme.io/docs/bread
extends TCG\Voyager\Http\Controllers\VoyagerBaseController and override the index method

**Comment by ghost** [comment]
Sorry for not being more clear. I have no problem getting the data table sorted correctly:
![image](https://user-images.githubusercontent.com/6446167/46762599-1e97d980-cc9d-11e8-8cdf-bc57b59741ff.png)

But the select control on the "Add Equipment" form lists the items in order of entry (by id, I'm assuming), not the sort order set in the order field. 
![image](https://user-images.githubusercontent.com/6446167/46762739-982fc780-cc9d-11e8-965e-1894fa45740c.png)

I'm trying to control the order of the pulldown.

**Comment by rrbotelho** [comment]
in this case, you have to order in formfields/relationship.blade.php , you can override this file and order query by the field you want to. You can use the collection method "sortBy('key')" https://laravel.com/docs/5.7/collections#method-sort

$query = $model::all()->sortBy('display_name');

**Comment by emptynick** [comment]
@rrbotelho its not that easy to sort by a relationship. See https://laracasts.com/discuss/channels/eloquent/order-by-on-relationship

**Comment by rrbotelho** [comment]
its different, when you are inside this file, voyager search in each table. Take a look in the file.
I tried this before send it to you.

**Comment by ghost** [comment]
Thank you. I will work with it.

**Comment by sergiocastrovale** [comment]
@rrbotelho @cyclonebt did you guys reach any conclusion? I'm also needing to order a list of subcategories by name while editing a category and I have no clue where that is done.

**Comment by rrbotelho** [comment]
@sergiocastrovale do you know how to override a view? relationship are "mounted" in formfields/relationship.blade.php , inside this file you have each relationship (belongTo, belongToMany ...). You can sort here.

**Comment by sergiocastrovale** [comment]
@rrbotelho isn't that going to sort _after_ I have my result set (as in, it's not an SQL orderBy)?

**Comment by rrbotelho** [comment]
no, because in the relationship.blade.php, voyager does a search in model from relation.
![captura de tela 2018-10-23 as 16 35 01](https://user-images.githubusercontent.com/7795458/47385886-a4764480-d6e1-11e8-9110-2651cfdd0d2f.png)

look at line 34

**Comment by sergiocastrovale** [comment]
@rrbotelho ah, great, thanks for the info!

**Comment by raquelfreitas** [comment]
I'm dealing with a similar situation, but I need to sort by different fields within different belongsTo relationships. Is there a way to override a view for each case or any other solution for this?

**Comment by sergiocastrovale** [comment]
@raquelfreitas is right ... this solution would only work if we had all our tables following that `display_name` field, right? Any idea @rrbotelho?

**Comment by rrbotelho** [comment]
i think you can use multiple sortBy like ->sortBy('key1')->sortBy('key2'), or you can do some logic like 
if(table == 'table1){
sort query with the corresponding key
}else ...

**Comment by raquelfreitas** [comment]
I was also thinking about double sorting it, but I was hoping someone had a better solution. 
Thank you!

**Comment by rrbotelho** [comment]
in my tests i have the users table that have two belongsToMany relationship, roles and companies, roles is sorted by 'display_name', and companies is sorted by 'company_name' . In this case it is kind different from double sorting, because it will sort just the table that have this column. Maybe with if you can verify which table is and then sort by the column you want to.
