### ISSUE TITLE
AJAX POST to URL external

### ISSUE THREAD

**Issue by eroberto17** [thedevdojo/voyager#3619]
## Version information

 - Laravel: v5.5.43
 - Voyager: v1.1
 - PHP: 7.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:

From a blade view, I send a post request to an external url:

<script>
    $(document).ready(function () {
        $("#btnSend").click(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({               
                url: 'https://www.anses.gob.ar/autoconsultas/expedientes.php',
                type: 'POST',
                 dataType: 'html', 
                data: {expediente:$("#expediente").val(),captcha:$("#captcha").val(),tipo:$("#tipo").val()},
                success: function (result) {
                    alert('success');
                }
            });
        });
    });
</script>

I know this works from my local server, without laravel or voyager. But when I run this in a blade view I get Status Code: 403 Forbidden
Some help? Also probe sending a request to a controller, and from the guzzle implement driver, but this does not send the request, just access the url. Thank you in advance.

**Comment by fletch3555** [comment]
This has nothing to do with Voyager.  I don't even see how it would even involve Laravel since it's all client-side
