### ISSUE TITLE
Adding a new column using migrations causes an "undefined offset" error

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#362]
Adding a new column using migrations causes an "undefined offset" error when submitting the edit form in the database editor page, as if it doesn't recognize the newly added column.

![dowdnload](https://cloud.githubusercontent.com/assets/8501654/21073316/6d89c3d8-bee3-11e6-85ca-53a58325c6f8.png)

**Comment by handiwijoyo** [comment]
This should fixed by #518
