### ISSUE TITLE
voyager cms categories and subcategories

### ISSUE THREAD

**Issue by meher993** [thedevdojo/voyager#3622]
## Version information

 - Laravel: v5.6.29
 - Voyager: 1.1.7
 - PHP: 7.2.10
 - Database: MySQL 8.0.12

## Description of problem
I need a help for voyager cms categories and subcategories :
I want the work to be as follows When selecting a label in the Categories entry, the subcategories input only comes with the subcategories of the selected label .

**Comment by fletch3555** [comment]
Voyager does not provide a way to make one field's values dependent on another.  Doing this would have to be completely custom, and not something we can directly support.

Others have asked about this in the past, so it's possible someone has done it before.  I would recommend asking in our Slack group to see if someone else can help you.

**Comment by meher993** [comment]
Thank you for your interaction. I found a very good way to do this and I will publish it in a video on YouTube soon.

**Comment by vonec** [comment]
still waiting for the video :)

**Comment by daniellealfreitas** [comment]
Still waiting for the video :D

**Comment by d3turnes** [comment]
@daniellealfreitas

How create 2 or 3 select dependent with ajax

2 select
![2 select](https://raw.githubusercontent.com/d3turnes/storage/master/example1/add_new.png)

3 select
![3 select](https://raw.githubusercontent.com/d3turnes/storage/master/example2/add_new.png)

[see this examples](https://github.com/d3turnes/dependent-dropdown-with-voyager)

**Comment by d3turnes** [comment]
> still waiting for the video :)

How create 2 or 3 select dependent with ajax

2 select
![2 select](https://raw.githubusercontent.com/d3turnes/storage/master/example1/add_new.png)

3 select
![3 select](https://raw.githubusercontent.com/d3turnes/storage/master/example2/add_new.png)

[see this examples](https://github.com/d3turnes/dependent-dropdown-with-voyager)

**Comment by daniellealfreitas** [comment]
thanks. i will have a look soon.
