### ISSUE TITLE
"None" value in dropdown is not showing up in relationship field (type cast problem)

### ISSUE THREAD

**Issue by sstolz** [thedevdojo/voyager#3625]
## Version information

 - Laravel: v5.6.34
 - Voyager: v1.1.3
 - PHP: 7.2
 - Database: PostgreSQL 10.5

## Description
Default value to "None" not working on relationship field (BelongTo) despite the fact that the field is not required.

## Steps To Reproduce
Add a relationship (BelongTo for instance) with the BREAD screen. In data creation screen, "None" is not showing up in the dropdown list.

## Expected behavior
Get "None" option displayed.

## Additional context

My field is not required in my migration file (nullable) and was not declared with Voyager database tool.

If you look at 
https://github.com/the-control-group/voyager/blob/0e66c48cd5c199eb9cdbe59c317f5a38a549346d/resources/views/formfields/relationship.blade.php#L35

`$row->required` should be an integer but it seems that when the required field is populated from model analysis the field is a boolean and not an integer.

Perhaps code should be `@if((int)$row->required === 0)` instead ? (working in my case by modifying the blade template with that code).

Dump of `$row`

```
<!-- object(TCG\Voyager\Models\DataRow)#258 (26) {
  ["table":protected]=>
  string(9) "data_rows"
  ["guarded":protected]=>
  array(0) {
  }
  ["timestamps"]=>
  bool(false)
  ["connection":protected]=>
  string(5) "pgsql"
  ["primaryKey":protected]=>
  string(2) "id"
  ["keyType":protected]=>
  string(3) "int"
  ["incrementing"]=>
  bool(true)
  ["with":protected]=>
  array(0) {
  }
  ["withCount":protected]=>
  array(0) {
  }
  ["perPage":protected]=>
  int(15)
  ["exists"]=>
  bool(true)
  ["wasRecentlyCreated"]=>
  bool(false)
  ["attributes":protected]=>
  array(14) {
    ["id"]=>
    int(51)
    ["data_type_id"]=>
    int(7)
    ["field"]=>
    string(36) "session_belongsto_video_relationship"
    ["type"]=>
    string(12) "relationship"
    ["display_name"]=>
    string(5) "Video"
    ["required"]=>
    bool(false)
    ["browse"]=>
    bool(false)
    ["read"]=>
    bool(true)
    ["edit"]=>
    bool(true)
    ["add"]=>
    bool(true)
    ["delete"]=>
    bool(true)
    ["details"]=>
    string(158) "{"model":"App\\Video","table":"videos","type":"belongsTo","column":"video_id","key":"id","label":"title","pivot_table":"companies","pivot":"0","taggable":"0"}"
    ["order"]=>
    int(8)
    ["col_width"]=>
    int(100)
  }
  ["original":protected]=>
  array(13) {
    ["id"]=>
    int(51)
    ["data_type_id"]=>
    int(7)
    ["field"]=>
    string(36) "session_belongsto_video_relationship"
    ["type"]=>
    string(12) "relationship"
    ["display_name"]=>
    string(5) "Video"
    ["required"]=>
    bool(false)
    ["browse"]=>
    bool(false)
    ["read"]=>
    bool(true)
    ["edit"]=>
    bool(true)
    ["add"]=>
    bool(true)
    ["delete"]=>
    bool(true)
    ["details"]=>
    string(158) "{"model":"App\\Video","table":"videos","type":"belongsTo","column":"video_id","key":"id","label":"title","pivot_table":"companies","pivot":"0","taggable":"0"}"
    ["order"]=>
    int(8)
  }
  ["changes":protected]=>
  array(0) {
  }
  ["casts":protected]=>
  array(0) {
  }
  ["dates":protected]=>
  array(0) {
  }
  ["dateFormat":protected]=>
  NULL
  ["appends":protected]=>
  array(0) {
  }
  ["dispatchesEvents":protected]=>
  array(0) {
  }
  ["observables":protected]=>
  array(0) {
  }
  ["relations":protected]=>
  array(0) {
  }
  ["touches":protected]=>
  array(0) {
  }
  ["hidden":protected]=>
  array(0) {
  }
  ["visible":protected]=>
  array(0) {
  }
  ["fillable":protected]=>
  array(0) {
  }
}
 -->
```

**Comment by gmedaglia** [comment]
Something similar is happening to me, but in my case the field is a string ("0") instead of an int.

I'm using:
Laravel: v5.7
Voyager: v1.1.10
PHP: 7.2
Database: MySQL 5.6

The weird thing is that this is not happening in my local environment, so I'm wondering if this might be related to a php setting or something like that.

**Comment by erroric** [comment]
Probably wrong behaviour with handling "required" field value for relationship DataRow

1) In TCG\Voyager\Http\Controllers\VoyagerBreadController@addRelationship method: 
```
$newRow = new DataRow();
....
$newRow->required = 0;
```
2) But in TCG\Voyager\Models\DataType@updateDataType method:
```
$dataRow->required = boolval($requestData['field_required_'.$field]);
```

On create relationship its "required" value is set to "0", but on update data type relationship required value is mapped to boolean.
In database "data_rows.required" field has Boolean type, so ```$row->required === 0``` condition in  "voyager/resources/views/formfields/relationship.blade.php" always will be `false`.
