### ISSUE TITLE
set a dynamic object id to hidden input?

### ISSUE THREAD

**Issue by eiadghaith333** [thedevdojo/voyager#3634]
-Laravel Version: 5.5 latest
-Voyager Version: latest
-PHP Version: 7.1
-Database Driver & Version: Mysql 5.7.21

**Description:**
Need to give an object id or session id and set it to a hidden input .

thanks in advance

**Comment by emptynick** [comment]
Please use the issue template.

**Comment by eiadghaith333** [comment]
> Please use the issue template.

fixed it :)

**Comment by fletch3555** [comment]
@eiadghaith333

Thanks for updating the issue, but you'll need to provide much more information.

**Comment by eiadghaith333** [comment]
@fletch3555 

What i need is to store the id of current user that is currently logged in and using his bread , lets say that he 's adding new product, so his id will be stored in product user_id field , what i want is the ability to save his id in the hidden element that is listed in product bread  , so wouldn't do any extra code.

![2018-10-16 1](https://user-images.githubusercontent.com/34092513/47024488-74bbbf80-d16a-11e8-8382-ff0de435454e.png)

**Comment by emptynick** [comment]
Take a look at how we do it:
https://github.com/the-control-group/voyager/blob/b79a022db8b3f3e4366b4531e3720d423e2b9914/src/Models/Post.php#L25-L33

**Comment by eiadghaith333** [comment]
> Take a look at how we do it:
> [voyager/src/Models/Post.php](https://github.com/the-control-group/voyager/blob/b79a022db8b3f3e4366b4531e3720d423e2b9914/src/Models/Post.php#L25-L33)
> 
> Lines 25 to 33 in [b79a022](/the-control-group/voyager/commit/b79a022db8b3f3e4366b4531e3720d423e2b9914)
> 
>      public function save(array $options = []) 
>      { 
>          // If no author has been assigned, assign the current user's id as the author of the post 
>          if (!$this->author_id && Auth::user()) { 
>              $this->author_id = Auth::user()->id; 
>          } 
>   
>          parent::save(); 
>      }

OK i think i got you , thank you  !
