### ISSUE TITLE
Logo in sidebar is stretched to square

### ISSUE THREAD

**Issue by decowboy** [thedevdojo/voyager#3640]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.7

## Description

The logo in the sidebar (_.app-container .content-container .side-menu .navbar-header .navbar-brand img_) has both its width and height set to a fixed amount of pixels.
This causes the logo to be stretched to be square.

As a quick workaround, overriding height to be auto fixed the issue, since my logo's width is larger than its height.
Naturally, if the logo's height is larger than its width, one would need to set width to auto.

**Comment by fletch3555** [comment]
Can you test with setting `max-height: 100%`, `max-width: 100%`, and removing any explicit `height` or `width`?  If that works, would you mind opening a PR for it?
