### ISSUE TITLE
hasMany relationship doesn't give opportunity to add multiple related subjects

### ISSUE THREAD

**Issue by cuzboo** [thedevdojo/voyager#3643]
- Laravel: v5.7
 - Voyager: v1.1.7
 - PHP: 7.1

Hi guys.

I have POSTS and POST_IMAGES tables, models for them. I am making an example.

In post_images table I am saving post_id. I am trying to make hasMany relationship, but when I want to make new post it is giving me just the name of relationship, like on the image bellow.
Is it possible to add multiple images from my post form? I used Symfony Sonata admin and it was possible there, with Voyager I am not sure.
All tuts and docs are taking example of belongsTo that works fine, but this one is driving me crasy.

Thanks in advance.
![add](https://user-images.githubusercontent.com/34268795/47151706-c2573a00-d2da-11e8-803d-dbfcaf0f3ccf.png)
![bread relation](https://user-images.githubusercontent.com/34268795/47151707-c2573a00-d2da-11e8-908c-341fd3f03b78.png)

**Comment by adronitis** [comment]
It is weird that they won't allow you to multiple images inside the post, I am having the same issue.

**Comment by cuzboo** [comment]
It is not possible, I consulted them on slack. The only way to do this is to add them through rich textbox.
The other way is to make custom controller, or action, and to add it manually, in some cases it is possible to add custom form field.
It would be nice to have with hasMany relationship that multiple select field with possibility to create them directly from there like Sonata admin has, but even without it, it is one good admin panel.
Anyway, I am closing this issue.

**Comment by paddelboot** [comment]
I am having the same issue. I am creating a simple portfolio website with examples of my work, where every work entity should have many technologies (PHP, Git etc.) associated with it. Not sure if I understand the underlying problem correctly. Laravel models can handle a [many to many relationship](https://laravel.com/docs/5.8/eloquent-relationships#many-to-many), so why can't I do this from voyager's admin panel? Seems like a "deal breaker".
