### ISSUE TITLE
Add code-coverage reporting to phpunit configuration

### ISSUE THREAD

**Issue by fletch3555** [thedevdojo/voyager#3644]
We're seeing differences in phpunit output between local environments and the TravisCI test runner.  We should implement code-coverage reports to allow comparison of test runs(in sny environment), and to inform us on what needs more test coverage.

**Comment by MrCrayon** [comment]
@fletch3555 is this implemented or there is something missing?

**Comment by fletch3555** [comment]
Definitely completed
