### ISSUE TITLE
Cannot Add BREAD - Undefined variable: dataRow 

### ISSUE THREAD

**Issue by fosterscode** [thedevdojo/voyager#3646]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1
 - PHP: 7.1
 - Database: 10.1.36-MariaDB 

## Description

After I create a table using the database manager tool, and then go into BREAD tool and click add BREAD to this table, i get the Whoops error "Undefined variable: dataRow". Upon further inspection, I noticed that there is no record in the data_types table created for the new table I created.

I have tried adding a new table with a model, and without a model.

## Expected behavior
The BREAD add/edit screen should appear.

**Comment by yashiroiori** [comment]
Same problem

![image](https://user-images.githubusercontent.com/17031855/47203492-28c57200-d346-11e8-8133-d164110201f6.png)

**Comment by AntoJ22** [comment]
I have the same problem:


![problem](https://user-images.githubusercontent.com/44287011/47204567-a6db4600-d351-11e8-9b2d-a72fd761b18c.PNG)

**Comment by antonio-solucweb** [comment]
I have the same problem:


![problem_capture](https://user-images.githubusercontent.com/44287011/47204767-2537e800-d352-11e8-9a3d-9910e94be62c.PNG)

**Comment by emptynick** [comment]
Is it Voyager 1.1.8?

**Comment by yashiroiori** [comment]
The problem are in line 301:
Other version:
<textarea id="json-input-{{ $data['field'] }}" class="resizable-editor" data-editor="json" name="field_details_{{ $data['field'] }}">@if(isset($dataRow->details)){{ $dataRow->details }}@endif</textarea>

Don't have if: <textarea id="json-input-{{ json_encode($data['field']) }}" class="resizable-editor" data-editor="json" name="field_details_{{ $data['field'] }}">{{ json_encode($dataRow->details) }}</textarea>

**Comment by fletch3555** [comment]
Sorry about that everyone.  It's related to my changes which we merged and released yesterday.  The changes from #3647 will fix it, but just need to be resubmitted on the correct branch.

We'll get this fixed and released very soon

**Comment by mrizkir** [comment]
My temporary solution is removed command. 

`<?php echo e(json_encode($dataRow->details)); ?>`

and then refresh. After refresh just put again

**Comment by antonio-solucweb** [comment]
> Is it Voyager 1.1.8?

Yes

**Comment by WaelMajdoub** [comment]
I have the same problem!
if I switch to older version it will work ?

**Comment by fletch3555** [comment]
Yes, this issue was introduced in 1.1.8, so 1.1.7 or lower would be fine.  We'll get out 1.1.9 with a fix for this soon

**Comment by Xoshbin** [comment]
I have updated to 1.1.9 still having this issue!!!

Edit:
I have deleted the users data type from data_rows table, now it's working.
Edit: my relationships not working after updating to 1.1.8 and then to 1.1.9

**Comment by AnasTHH** [comment]
Also after creating BREAD it's looking for table using "Display Name (Plural)"
url: admin/test
table: test
error:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db.tests' doesn't exist (SQL: select * from `tests` order by `created_at` desc)

**Comment by fletch3555** [comment]
@AnasTHH that doesn't sound related.  But the answer is that laravel convention is to have tables be named plural (i.e. `tests`).  Any variation from that requires modification to the model class (i.e. `$table = 'test';`)

**Comment by emptynick** [comment]
#3665

**Comment by Xoshbin** [comment]
After updating to 1.1.10 Still having relationships issue, When adding or editing a post the relationship dropdown is not working.

**Comment by emptynick** [comment]
Thats unrelated to this issue and should be solved in #3660 or #3661
