### ISSUE TITLE
Editing a markdown field

### ISSUE THREAD

**Issue by axeloz** [thedevdojo/voyager#3648]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.8
 - PHP: 7.1
 - Database: MariaDB

## Description
When using the Markdown type, the field content is incorrect when editing. 
For instance, I type `hello` in the Markdown form field and save the form. It is stored as `hello` into the database. 
But when editing, the markdown editor shows `<p>hello</p>`. 

## Expected behavior
Field content should be shown as stored into the database in order to respect the MD syntax.

**Comment by axeloz** [comment]
My bad, my dev added a mutator into the Model.

**Comment by axeloz** [comment]
But that leads to another question: now that the field is properly saved as Markdown into the database, how can I converti it on the front side to HTML? I was expecting Voyager to do it. I really don't want to override the edit-add view for this. Am I missing something?

Thanks

**Comment by axeloz** [comment]
Not very clean but working:

```
// into App\Models\Page.php
function getBodyAttribute($value) {
      if(strpos(Route::currentRouteName(), 'voyager') === false) {
          return Markdown::convertToHtml($value);
      }
      else {
          return $value;
      }
 }
```

**Comment by emptynick** [comment]
Why dont you call `Markdown::convertToHtml($post->body);` in your frontend?

**Comment by emptynick** [comment]
Closing as the issue seems resolved.

**Comment by axeloz** [comment]
Yeah, sure, my bad. Thanks.

**Comment by moathOSA** [comment]
i have exactly the same problem and I'm a beginner I can't solve it

**Comment by emptynick** [comment]
There is no unsolved problem here.
If you have any questions please ask in our Slack group.
