### ISSUE TITLE
PostgreSQL and Carbon issues - Trailing data

### ISSUE THREAD

**Issue by flythenimbus** [thedevdojo/voyager#3649]
# Please reopen this issue as this is directly related to Voyager.

## Version information
 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 5.2
 - Database: PostgreSQL 10

## Description
So apparently timestamps in Postgres are different than in MySQL (where I originally installed my laravel app in), and now I'm getting ` ErrorException Trailing data` error whenever I go to the browse view of any Model which has the `created_at` or `updated_at` fields visible. Saving data is also impossible due to this bug. Please note that I'm still running MySQL locally for now, but I will be transitioning to Postges soon.

This issue is happening only in Voyager's browse views and nowhere else.

## Steps To Reproduce
1. Use PostgreSQL
2. Go to any DataType which displays `created_at`
3. Get the exception

## Expected behavior
Be able to browse the data and save it normally.

## Screenshot 
https://screenshots.firefox.com/nAtRep03XH7fQgFe/

**Comment by fletch3555** [comment]
That stacktrace is pointing at the Laravel Model, which means it's related to the automatic date casting (the `$casts` array on the model class).  I don't see any reason this would be related to Voyager specifically.

It seems to be related to Laravel's assumed date format (which does not match what PG is returning).  There are numerous posts about this with a quick google search, with a variety of possible workarounds/fixes.  Specifically, https://github.com/laravel/framework/issues/16839, https://laracasts.com/discuss/channels/laravel/carbon-trailing-data-error, and others

**Comment by flythenimbus** [comment]
@fletch3555 Yeah, but this happens in the DataType model (when saving BREAD) as well and if a user that uses Postgres has to override your built-in classes every time they choose to use Voyager, then I'd say it's a pretty crappy thing to deal with.

**Comment by flythenimbus** [comment]
@fletch3555 Can you please reopen this? I fixed it for my models, but I can't be fixing it for the Voyager models as well. Thanks.
