### ISSUE TITLE
Undefined variable: dataRow (View:  bread/edit-add.blade.php)

### ISSUE THREAD

**Issue by midzil007** [thedevdojo/voyager#3650]
Hi, I have issues with  Add BREAD to this table. I created new table at tools/database without create model after that i tried tools/bread  Add BREAD to this table with this error:

ErrorException (E_ERROR)
Undefined variable: dataRow (View: /Users/michalnosil/Sites/voyager/vendor/tcg/voyager/resources/views/tools/bread/edit-add.blade.php)

THX

**Comment by emptynick** [comment]
Please search before opening new issues and use the issue-template.
Closing as this is a duplicate of #3646
