### ISSUE TITLE
Cannot browse BREAD - First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by rajeshdalsaniya** [thedevdojo/voyager#3654]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.8
 - PHP: 7.2.7 
 - Database: 5.7.21 - MySQL Community Server (GPL) 

## Description

After adding BREAD to the table if I click on BROWSE error coming.

## Steps To Reproduce
1. Go to BREAD
2. Add BREAD to this table and Save
3. Then in BREAD Click on Browse button
First parameter must either be an object or the name of an existing class (View: /Volumes/Develop/Web/Practice/silver-dc-backend-v1/vendor/tcg/voyager/resources/views/bread/browse.blade.php)

## Expected behavior
It should open Browse view

## Screenshots
![image](https://user-images.githubusercontent.com/16004654/47251979-20f6f200-d45a-11e8-9a53-2de00855c07c.png)

**Comment by FrankyJust** [comment]
Same error, but after different actions 
### Version information

- Laravel 5.6. latest
- Voyager 1.1 (latest release from one hour ago)
- PHP 7.1.16
- MySQL 5.7.21

### Details
I've followed the video tutorial on Adding Products. This went well until I added the first product. If I open then the menu Products the error occures.

**Comment by baturox** [comment]
I get same error to.

**Version information**

- Laravel 5.7. latest
- Voyager 1.1.9 (latest release from one hour ago)
- PHP 7.1.16
- MySQL 5.7.21

**Comment by emptynick** [comment]
As a quick workaround, go to the bread-settings for your table and simply put `{}` into all details-fields which are empty.
If they are already there, just hit "Save"

**Comment by FrankyJust** [comment]
Thx for workaround, worked for me

**Comment by rajeshdalsaniya** [comment]
I fixed the problem by updating function in /vendor/tcg/voyager/src/Models/DataRow.php
Line 64

FROM

```
public function getDetailsAttribute($value)
    {
        return json_decode(!empty($value) ? $value : '{}');
    }
```

TO

```
public function getDetailsAttribute($value)
    {
        return json_decode((!empty($value) && !$value === NULL) ? $value : '{}');
    }
```

**Comment by emptynick** [comment]
This will be fixed with #3662 (maybe with another approach then the current)

**Comment by FrankyJust** [comment]
the fix from rajeshdalsaniya is not sufficient, it gives then an error when clicking on Menu Users: Undefined property: stdClass::$type

**Comment by richard-313** [comment]
Hi,
in my case I added the brackets {} to created_at. thats it.
thanks @emptynick
