### ISSUE TITLE
Relationship not working after latest update 1.1.8

### ISSUE THREAD

**Issue by tommiekn** [thedevdojo/voyager#3656]
Hi, 

Have just updated from 1.1.7 to 1.1.8 and i am having now issues on all the model views in the admin.

Any model like user or the custom one i made give the following error:

`json_decode() expects parameter 1 to be string, object given (View: /resources/views/vendor/voyager/bread/browse.blade.php)`

the error line is below, apparently $row->details should be a string but an object get passed:

`<?php
                                    $options = json_decode($row->details);
                                    $display_options = isset($options->display) ? $options->display : NULL;
                                ?>`

I have tried to save again the bread associated to one table, and the error disappear in admin for that, but all the relationship in that table doesnt work anymore and gives empty result. I can only browser it as once i try to add or edit i get the error above again.

**Comment by tommiekn** [comment]
I noticed that this may be related to #3653

**Comment by emptynick** [comment]
Looks like you override that view.
You need to update the view to match our current version:
https://github.com/the-control-group/voyager/blob/1.1/resources/views/bread/browse.blade.php

**Comment by tommiekn** [comment]
No it happens anyway also if i revert to the original blade.

I have just tried to install the previous version 1.1.7 and everything works again as expected except the BREADS that gives error while trying to edit:

Trying to get property 'details' of non-object (View: /vendor/tcg/voyager/resources/views/tools/bread/edit-add.blade.php)

Error is referred to this part of the code:
`<textarea id="json-input-<?php echo e(json_encode($data['field'])); ?>" class="resizable-editor" data-editor="json" name="field_details_<?php echo e($data['field']); ?>"><?php echo e(json_encode($dataRow->details)); ?></textarea>`

**Comment by emptynick** [comment]
Yep, this one is now related to #3653 and will be fixed ASAP.

**Comment by tommiekn** [comment]
Ok so to exclude any issue related to my blades i have disabled all of them.

I dont see anymore that error on my views but i do see it on User view for example. 
See screenshot attached

On top, on my models i cant see anymore relationships, in browse page are empty, same for new or edit.

![screen shot 2018-10-20 at 14 49 04](https://user-images.githubusercontent.com/24386363/47255891-7beb1200-d477-11e8-8d33-05313fc6cda0.png)

Is this still part of #3653 ?

Thanks

**Comment by emptynick** [comment]
This is a problem with [pvtl/voyager-frontend](https://github.com/pvtl/voyager-frontend)
I filed an issue https://github.com/pvtl/voyager-frontend/issues/35

**Comment by tommiekn** [comment]
Thanks,

I am trying to revert to 1.1.7 then as i am in production here, everything seems to work except for the bread editor, if i try to edit a bread gives the following error. 

Any way i can solve that? Is due to update to 1.1.8 then downgrade to 1.1.7?
Should i just wait for 1.1.9 and new laravel frontend and dont use the breads meanwhile?

**Comment by emptynick** [comment]
Which error?
The second (`Trying to get property 'details' of non-object`) is fixed in 1.1.9 which is live.
But you have to wait for voyager-frontend to update.
Stick with 1.1.7 for now.

**Comment by tommiekn** [comment]
Sorry, forgot to attach the screenshot.
This error happens in 1.1.7 after i reverted back:

![screen shot 2018-10-20 at 15 47 44](https://user-images.githubusercontent.com/24386363/47256429-a42b3e80-d480-11e8-8f72-8c697a38c6a8.png)

**Comment by tommiekn** [comment]
I noticed this error happens only while i try to edit breads that have a relationship set.

**Comment by tommiekn** [comment]
@emptynick i have fixed the above replacing 1.1.7 blade files , that one and another. Just not sure why that happened, if i reverted with composer back to 1.1.7 shouldnt have changed that files as well?

**Comment by emptynick** [comment]
I'm honestly not sure how to properly downgrade.
When you have the correct version-constraint in your composer.json just rename the `voyager` folder `vendor/tcg/voyager` and run `composer update`

**Comment by rajanish93** [comment]
![image](https://user-images.githubusercontent.com/32562461/49940566-e4012600-ff05-11e8-9948-df0dbe9512f2.png)
i have also face some problem

**Comment by rajanish93** [comment]
plse give the solution

**Comment by emptynick** [comment]
@rajanish93 Thats unrelated to this issue.
Also it looks like you override the `user/edit-add` view with the generic `bread/edit-add` view.
We changed that view and you have to apply those changes as well.
As a side note: never change something in the `vendor` folder. Those files will just be overriden when the file was changed here.
