### ISSUE TITLE
Roles not being listed on Admin -> Users page.

### ISSUE THREAD

**Issue by DPerkunas** [thedevdojo/voyager#3659]
## Version information
 - Laravel: v5.7.8
 - Voyager: v1.1.9
 - PHP: 7.2.7
 - Database: MySQL 5.7.21 (On MAMP)

## Description
On Admin Panel -> Users , the column Role and Roles don't show the user's roles. I created an admin and a normal user. The role shows up when viewing individual profile, but not in list form.

Fresh install..

**Comment by emptynick** [comment]
This will be fixed in #3660 and #3661
