### ISSUE TITLE
PostgreSQL and Carbon issues - Trailing data

### ISSUE THREAD

**Issue by flythenimbus** [thedevdojo/voyager#3663]
## Version information
 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 5.2
 - Database: PostgreSQL 10

## Description
So apparently timestamps in Postgres are different than in MySQL (where I originally installed my laravel app in), and now I'm getting ` ErrorException Trailing data` error whenever I go to the browse view of any Model which has the `created_at` or `updated_at` fields visible. Saving data is also impossible due to this bug. Please note that I'm still running MySQL locally for now, but I will be transitioning to Postges soon.

This issue is happening only in Voyager's browse views and nowhere else.

## Steps To Reproduce
1. Use PostgreSQL
2. Go to any DataType which displays `created_at`
3. Get the exception

## Expected behavior
Be able to browse the data and save it normally.

## Screenshot 
https://screenshots.firefox.com/nAtRep03XH7fQgFe/ziggx.com

## Additional notes
I've posted this problem here a couple days ago and it was closed unfairly (imo). This issue happens in the DataType model when saving a BREAD, so this error is directly tied to Voyager too. If a user is forced to extend Voyager classes to fix bugs, then I don't really see the point of all this.

**Comment by fletch3555** [comment]
Opening a new duplicate issue is not the appropriate way to handle a previous issue being closed "unfairly".  Please keep discussion in the first issue

**Comment by flythenimbus** [comment]
@fletch3555 What discussion? You instantly closed that issue too and didn't bother to respond anymore?

**Comment by fletch3555** [comment]
I did respond, then you commented again, and I haven't had a chance to respond yet.  It's been  3 days, one of which was my girlfriend's birthday, and one my birthday, so please forgive me if I didn't meet your timeframes.

Seriously though. We do this for free in our spare time. All we ask for is a bit of patience and understanding.
