### ISSUE TITLE
Edit Add View Blade Template Sepration Proposal

### ISSUE THREAD

**Issue by rajeshdalsaniya** [thedevdojo/voyager#3664]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.8
 - PHP: 7.2.7
 - Database: 5.7.21 - MySQL Community Server (GPL)

## Description of problem

Right now Edit and Add BREAD functionality combined in edit-add.blade.php one view blade template file. This causing the issue because of if I just want to modify / override view template of add functionality then there is no way right not on modifying edit-add.blade.php file it comes as view for both ADD and EDIT which is not correct behavior. 

## Proposed solution
I propose the separation of view template file for ADD and EDIT like this
```
add.blade.php
edit.blade.php
```
So developer can easily override view for individual BREAD functionality.

## Alternatives considered
My suggestion is all BREAD view must be seprated so it will be easy to manage and will provide big place for customization for developer.

```
browse.blade.php
read.blade.php
edit.blade.php
add.blade.php
delete.blade.php
order.blade.php
```

## Additional context
![screen shot 2018-10-21 at 10 50 27 am](https://user-images.githubusercontent.com/16004654/47263430-32ee9880-d51f-11e8-88d2-6388dcbebdc4.png)

**Comment by emptynick** [comment]
In my eyes its correct behaviour to not duplicate code for the very same thing.
If you really want that, override the `edit-add.blade.php` (for a single BREAD or for all) and put something like this inside:
```
@if (!is_null($dataTypeContent->getKey())
    @include('edit.blade.php')
@else
    @include('add.blade.php')
@endif 
```

**Comment by emptynick** [comment]
Closing this.
Explanation + solution was provided.
