### ISSUE TITLE
Base table or view not found

### ISSUE THREAD

**Issue by AnasTHH** [thedevdojo/voyager#3665]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
after creating BREAD it's looking for table using "Display Name (Plural)"
url: admin/test
table: test
error:

## Steps To Reproduce
1. Go to ' Add BREAD to this table'
2. Click on 'Submit'
3. See error

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'larav_l.tests' doesn't exist (SQL: select * from tests order by created_at desc)

## Screenshots
![download](https://user-images.githubusercontent.com/15839954/47264834-2d00b380-d52f-11e8-86b7-b01812775e9e.png)

**Comment by AnasTHH** [comment]
It's a new install of voyager

**Comment by emptynick** [comment]
Thats an [Eloquent Model Convention](https://laravel.com/docs/eloquent#eloquent-model-conventions) and is unrelated to Voyager.

**Comment by pratiksh404** [comment]
you may have named your table singular(ie test) as a result when you hit browse bread option voyager end up looking for tests table which doesn't exist ... check your database once ...
