### ISSUE TITLE
Laravel Voyager: Undefined variable: dataRow when Add BREAD to this table!

### ISSUE THREAD

**Issue by cuongcx87** [thedevdojo/voyager#3666]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1
 - PHP: 7.2.2
 - Database: MySQL 5.7.19

**Comment by emptynick** [comment]
Please search before opening new issues.
This has been fixed in 1.1.8/9 and is a duplicate of https://github.com/the-control-group/voyager/issues/3646

**Comment by cuongcx87** [comment]
Thank you!
