### ISSUE TITLE
Can't create a BRED of new table

### ISSUE THREAD

**Issue by darana07** [thedevdojo/voyager#3669]
## Version information

 - Laravel: 5.6.*
 - Voyager: 1.1.9
 - PHP: 7.2
 - Database: MySQL 5.7

## Description:
After create a new table i want to add a BREAD for it, so when a click "Add new bread for this table" throws me "Undefined variable: dataRow" error.

## Additional context
![image](https://user-images.githubusercontent.com/19784904/47269399-4ba87f80-d51a-11e8-8a18-3a04831850d7.png)

**Comment by fletch3555** [comment]
Please search before opening issues.
