### ISSUE TITLE
Boolean column is varchar(255) in MySQL

### ISSUE THREAD

**Issue by wymedia** [thedevdojo/voyager#367]
Laravel Version: 5.3.26
Voyager Version: 0.10.0
PHP Version:
Database Driver & Version:

### Description:
Creating a database and setting a given column to boolean will create a varchar(255) in MySQL. Then looking back to the database table, the field (which is supposed to be a boolean) is now a varchar(255)

**Comment by marktopper** [comment]
What table are you talking about?

**Comment by wymedia** [comment]
Just a random table I create. In my example, I was creating a table video which had a boolean field so in the UI I'm putting the dropbox to 'Boolean'. Once you hit the button to create the table in MySQL, I noticed the column was a varchar(255) despite the fact that I selected a Boolean value.

**Comment by handiwijoyo** [comment]
@wymedia Yes that was a bug, It's already fixed here https://github.com/the-control-group/voyager/pull/380 Wait for next release to update via `composer update` or if you want the fix right now you can change composer to use `dev-master` version.
