### ISSUE TITLE
Voyager Create new product

### ISSUE THREAD

**Issue by cuongcx87** [thedevdojo/voyager#3670]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.9
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

Not show user_id input when create new product use relationship with users table.

## Screenshots
Products Bread
![1](https://user-images.githubusercontent.com/38089913/47269486-7b8e6c00-d588-11e8-81a4-c09f53528e13.png)

products table
![2](https://user-images.githubusercontent.com/38089913/47269488-80ebb680-d588-11e8-9b49-973f67a31fa8.png)
Result when create new product
![3](https://user-images.githubusercontent.com/38089913/47269489-847f3d80-d588-11e8-8222-5c31901648ee.png)

**Comment by fletch3555** [comment]
This is expected behavior.  When you add a relationship, it will show the defined relationship.  If that relationship depends on another field on that table (i.e. your `user_id` field), then it will hide that field as it is redundant.

**Comment by cuongcx87** [comment]
![4](https://user-images.githubusercontent.com/38089913/47270042-26565880-d590-11e8-98dc-257c6b560014.png)
In products list why show users?

**Comment by cuongcx87** [comment]
You can tell me to fix this? Thanks!
