### ISSUE TITLE
Translated Slug from post

### ISSUE THREAD

**Issue by eduAbreu** [thedevdojo/voyager#3675]
Hello, 

I have a few posts and just added yours multilanguage that is very easy to activate and use.
The issue is that I'm showing on the frontend the translated slug too, and when trying to open a post with the translated slug I get 404 even having that translated slug on the post.

Could you help me here, or at least guide me on the right direction.

Best Regards

**Comment by emptynick** [comment]
This will be possible once https://github.com/the-control-group/voyager/pull/3417 is merged.
Also, please use the issue-template.

**Comment by emptynick** [comment]
Closing as https://github.com/the-control-group/voyager/pull/3417 was merged (into 1.x, to be released in a future 1.2 release)
