### ISSUE TITLE
Laravel Voyager: Missing required parameters for [Route: voyager.user-roles.edit]

### ISSUE THREAD

**Issue by cuongcx87** [thedevdojo/voyager#3676]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.10
 - PHP: 7.2
 - Database: MySql 5.7

## Description

Missing required parameters for [Route: voyager.user-roles.edit...

## Steps To Reproduce
1. Go to Tools
2. Click on Database
3. Scroll down to  'user_roles' and click  Add BREAD to this table. Seer error 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'order clause' (SQL: select * from `user_roles` order by `created_at` desc)'.
4. Then add Timestamps to table user_roles.
5. Click  Browse BREAD  on 'user_roles'
6. See error 'Missing required parameters for [Route: voyager.user-roles.edit] [URI: admin/user-roles/{user_role}/edit].'

## Screenshots
![6](https://user-images.githubusercontent.com/38089913/47307905-65e97700-d65a-11e8-9a6f-937a320ba7fb.png)

![5](https://user-images.githubusercontent.com/38089913/47307414-25d5c480-d659-11e8-945d-11e525106fdd.png)

## Additional context
Thanks you every body!

**Comment by emptynick** [comment]
Thats both described [here](https://docs.laravelvoyager.com/troubleshooting/missing-required-parameter) and [here](https://laravel.com/docs/eloquent#eloquent-model-conventions)
Also, in my eyes there's no reason to add BREAD to this pivot-table.

**Comment by emptynick** [comment]
Closing

**Comment by valkedev** [comment]
Same error on fresh installation withou dummy data. Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: ~\tcg\voyager\resources\views\tools\database\index.blade.php)

**Comment by alwan-h** [comment]
> Same error on fresh installation withou dummy data. Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: ~\tcg\voyager\resources\views\tools\database\index.blade.php)

just change file vendor\tcg\voyager\resources\views\tools\database\index.blade.php in line 96

from

{{ route('voyager.bread.delete', ['id' => null]) }}

to

{{ route('voyager.bread.delete', ['id' => '']) }}

hope this helps

**Comment by MrCrayon** [comment]
Let's not resume closed issues, there is already an ~open~ more recent issue already addressed with linked PR. #4586 

@alwan-h that won't work with next Laravel release. 
This is the proper fix
https://github.com/the-control-group/voyager/pull/4587/files
