### ISSUE TITLE
No other issues encountered! Just need to add _use VoyagerUser;_ trait to User model, and modify/implement roles/permissions as needed by your project.

### ISSUE THREAD

**Issue by AjSheba** [thedevdojo/voyager#3678]
_Originally posted by @envision in https://github.com/the-control-group/voyager/issues/1202#issuecomment-305187600_

Hello "envision".
can you kindly state the steps you followed/taken.

Thanks.

**Comment by fletch3555** [comment]
Answer provided in Slack.

We try to keep github issues focused on bugs/new functionality specific to this package.  For help with 3rd-party integrations or doing non-standard things with Voyager, please ask in Slack.  If we determine it's a package bug, we may then ask you to open an issue here.

Also, we have issue templates for a reason.  They help us by encouraging you to provide necessary information about your environment.  Please use them.  If it doesn't seem like they fit your needs, your needs are likely best suited as a question on Slack first.
