### ISSUE TITLE
PDF Download / Export Feature Request Proposal

### ISSUE THREAD

**Issue by rajeshdalsaniya** [thedevdojo/voyager#3681]
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.10
 - PHP: 7.27
 - Database: 5.7.21 - MySQL Community Server (GPL)

## Description of problem

Right Now there is no option to download data in PDF or any other format. It will be really great if any button added or any hook will be created which provide feature that can help to export data in PDF or any other format like XLS, TXT etc. from BROWSE BREAD

## Proposed solution
I suggest two option to add exporting functionality of BROWSE BREAD
1. Add Export Button in BROWSE BREAD threw it user can export table data in document format like PDF, XLS etc
2. Create separate hook which add functionality as mention above.

## Alternatives considered
Right now there is no option available in voyager so I am using laravel package to download database  in pdf format

## Additional context
![image](https://user-images.githubusercontent.com/16004654/47340547-3cf9ce00-d6bc-11e8-8631-974db7f08ec4.png)

**Comment by fletch3555** [comment]
This has been requested before.  Right now, we have no plans to add export functionality.
