### ISSUE TITLE
Documentation for admin theme component

### ISSUE THREAD

**Issue by rizkiheryandi** [thedevdojo/voyager#3682]
Continue question on #1146 

I think that question closed with un-relevant or un-complete answer by @handiwijoyo 

I think this question means is :

"If the voyager dashboard design from a existing admin template, so he want to know what the template is it, maybe he want to use the other existing component by that admin template. BUT if voyager dashboard design build from scratch with Bootstrap 3.3.7, i think he will go for build custom css by himself for component he want"

That's it, and i have same question too like him

"If voyager dashboard design is builded from scratch, so it's a voyager own theme, please make the documentation for that, maybe about the general component, form component, layout or others"

Please answer :D

**Comment by fletch3555** [comment]
There is no admin theme for Voyager. It's 100% custom (as I stated in my comment there), and cannot be separated for use elsewhere (what the original question was asking).  @handiwijoyo's comment adds a suggestion for how to customize the template by adding CSS/JS through a documented means.  It's not directly related to the question, but still relevant.

**Comment by rizkiheryandi** [comment]
Okay, it's clear

So, maybe i wanna "document request" to the owner who related to the tambah trontend, to create the theme documentation for component or others if available

Thanks :D
