### ISSUE TITLE
validation with ajax with 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by eiadghaith333** [thedevdojo/voyager#3683]
Version information
-Laravel Version: 5.5 latest
-Voyager Version: latest
-PHP Version: 7.1
-Database Driver & Version: Mysql 5.7.21

#Description:
I have multiple inputs to add , and all inputs shouldn't be empty, i try to do the validation through ajax with post method , 
i do this:   added new route as below:
  
Route::post('/admin/accounts/create', ['uses' => 'HomeController@addExtraInfo']); 

when submit the form that it checked with javascript function as below: 

 var postURL = "/admin/accounts/create";
$('#submit').click(function(){
           $.ajax({  
                url:postURL,
                method:"POST", 
                data:$('#add_info').serialize(),
                type:'json',
 success:function(data)  
                {} }); 
});

The response told me so : 
http://127.0.0.1:8000/admin/accounts/create 405 (Method Not Allowed)

![2018-10-23 1](https://user-images.githubusercontent.com/34092513/47354547-ad5a1c80-d6c7-11e8-9654-76c3aba909d2.png)

Any idea about this .. thanx a lot :)

**Comment by fletch3555** [comment]
This is not a Voyager issue.  You've built a custom route, controller, and view, none of which is specific to Voyager.

Having said that, the error message already provides plenty of information.  405 Method Not Allowed tells you that that route is not expecting a POST request.  Next would be to check the routes to confirm that: `artisan route:list`.

That's as far as I can go.  If you need further assistance, please consider asking in larachat, laracasts forums, or any other laravel-focused site
