### ISSUE TITLE
Update to 1.1.10 Problems

### ISSUE THREAD

**Issue by vaggelis2018** [thedevdojo/voyager#3684]
## Version information

 - Laravel: v5.6 to 5.7
 - Voyager: v1.1.3 to 1.1.10
 - PHP: 7.2
 - Database: MardiaDB 10.3 and Mysql 5.7.20

## Description
Hello everyone, I just updated to laravel 5.7 and voyager updated to 1.1.10 from 1.1.3 version. Now i encounter several problems. The most serious is in this commit Tweaking usage of JSON "details" field (#3637) . Even if i update all custom pages and classes, how i can update safely the database on a live site?

## Steps To Reproduce
just make a simple composer update

**Comment by fletch3555** [comment]
We can't support custom views. That would lead to infinite possibilities.

If you have specific issues you need help with, please feel free to ask.  I'm going to close this for now though.
