### ISSUE TITLE
composer install errors - avoid packages

### ISSUE THREAD

**Issue by udartsev** [thedevdojo/voyager#3688]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1 (lastest from that repo)
 - PHP: 7.2.11
 - Database: Mysql 5.7.23

## Description
while
```
composer install
```
[package errors] 
```
Package **satooshi/php-coveralls is abandoned**, you should avoid using it. Use php-coveralls/php-coveralls instead.
Package **guzzle/guzzle is abandoned**, you should avoid using it. Use guzzlehttp/guzzle instead.
```

## Screenshots
![screenshot from 2018-10-24 12-00-15](https://user-images.githubusercontent.com/36134794/47419237-6bdb7700-d784-11e8-9de0-0b42381f14d1.png)

**Comment by emptynick** [comment]
Running `composer why guzzle/guzzle` gives
`satooshi/php-coveralls  v1.1.0  requires  guzzle/guzzle (^2.8 || ^3.0)`
Then running `composer why satooshi/php-coveralls` gives:
`codeclimate/php-test-reporter  dev-master  requires  satooshi/php-coveralls (^1.0)`
Looks like `codeclimate/php-test-reporter` is the root of both problems.
Nothing we can really do about it.

**Comment by fletch3555** [comment]
Looks like that package is deprecated: https://github.com/codeclimate/php-test-reporter

We should consider removing it (since I don't believe we're really using it anyway) or changing to a different package.
