### ISSUE TITLE
[Feature][Idea] about migrations problem

### ISSUE THREAD

**Issue by eymen-elkum** [thedevdojo/voyager#3696]
## Description of problem
refs: https://github.com/the-control-group/voyager/issues/204 , https://github.com/the-control-group/voyager/issues/3668 , https://github.com/the-control-group/voyager/issues/3510 , https://github.com/the-control-group/voyager/issues/2713 , and many others

## Proposed solution
When we make any change on our database by voyager , I think that the **MAIN PROBLEM IS** that we cannot detect our changes on the git repo so we cannot share the changes with the team developers.

What about save the metadata of our voyager tables in file format instead of save them at the database.

I suggest to serve the metadata over json files for example:

## data-types.json
```
[
    {
        "id": "1",
        "name": "users",
        "slug": "users",
        "display_name_singular": "User",
        "display_name_plural": "Users",
        "icon": "voyager-person",
        "model_name": "TCG\\Voyager\\Models\\User",
        "policy_name": "TCG\\Voyager\\Policies\\UserPolicy",
        "controller": "",
        "description": "",
        "generate_permissions": "1",
        "server_side": "0",
        "details": null,
        "created_at": "2018-10-24 11:52:47",
        "updated_at": "2018-10-24 11:52:47"
    },
    {
        "id": "2",
        "name": "menus",
        "slug": "menus",
        "display_name_singular": "Menu",
        "display_name_plural": "Menus",
        "icon": "voyager-list",
        "model_name": "TCG\\Voyager\\Models\\Menu",
        "policy_name": null,
        "controller": "",
        "description": "",
        "generate_permissions": "1",
        "server_side": "0",
        "details": null,
        "created_at": "2018-10-24 11:52:47",
        "updated_at": "2018-10-24 11:52:47"
    },
    ...
]
```

**Comment by fletch3555** [comment]
Yes, but that requires a complete rewrite of a majority of voyager's core functionality.

We're already planning exactly that for Voyager 2.0, but that's a long way off.
