### ISSUE TITLE
Hooks documentations

### ISSUE THREAD

**Issue by jpons14** [thedevdojo/voyager#3697]
# Hook installation documentation
Hello, can you please add some documentation about actions while the instaltion of a hook in runing? Thank you so much!
Cheers!

**Comment by fletch3555** [comment]
Hooks are a dependency of Voyager, not a core component.  You're looking for https://github.com/larapack/hooks (the actual Hooks functionality), or https://github.com/larapack/voyager-hooks (the wrapper package that makes it work in Voyager specifically)
