### ISSUE TITLE
Dimmers are not displaying

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#3700]
## Version information
 - Laravel: v5.6.*
 - Voyager: v1.1
 - PHP: 7.2

## Description:
Dimmers are not displaying. I didn't got any error. Just see "To view analytics you'll need to get a google analytics" text. 

my index.blade.php is same as voyager.
Also my dimmers.blade.php same as voyager's.
Vendor files are same too. 

I didn't found the differences. I am using dimmers in my all projects. Why it is not working right now? Any suggestion? (Can't saw default dimmers also. (Coming with dummy data dimmers))

**Comment by fletch3555** [comment]
Did you install voyager `--with-dummy`? 

Also, what do you see in `config/voyager.php`? [This](https://github.com/the-control-group/voyager/blob/1.1/publishable/config/voyager.php#L166)? Or [this](https://github.com/the-control-group/voyager/blob/1.1/publishable/config/voyager_dummy.php#L162)?

**Comment by aozen** [comment]
in config/voyager.php has this:
`'widgets' => [
            'App\\Widgets\\UserDimmer',
            'App\\Widgets\\ProductDimmer'
        ],`

I was created ProductDimmer.php with ProductDimmer class. this is the run code: 
`public function run()
    {
        $count = Product::count();
        $string = trans_choice('voyager::dimmer.user', $count);

        return view('voyager::dimmer', array_merge($this->config, [
            'icon'   => 'voyager-group',
            'title'  => "{$count} {$string}",
            'text'   => __('voyager::dimmer.user_text', ['count' => $count, 'string' => Str::lower($string)]),
            'button' => [
                'text' => __('voyager::dimmer.user_link_text'),
                'link' => route('voyager.users.index'),
            ],
            'image' => voyager_asset('images/widget-backgrounds/01.jpg'),
        ]));
    }`

same as user. But i just saw user's dimmer. Can't product's dimmer. 
Not displaying, not error. Just nothing. What should i change? If you can help i would be grateful.

**Comment by emptynick** [comment]
Please show the whole dimmer class.
Does your class extend Voyagers BaseWidget?
Did you implement the `shouldBeDisplayed()` method?

**Comment by jaolave** [comment]
> same as user. But i just saw user's dimmer. Can't product's dimmer.
Not displaying, not error. Just nothing. What should i change? If you can help i would be grateful.

Run: php artisan config:cache

**Comment by emptynick** [comment]
If you think that the config might be cached you wanted to say `php artisan config:clear`

**Comment by bonucci** [comment]
Add this to widgets voyager.php
```
 'widgets' => [
            'TCG\\Voyager\\Widgets\\UserDimmer',
            'TCG\\Voyager\\Widgets\\PostDimmer',
            'TCG\\Voyager\\Widgets\\PageDimmer',
        ],
```
