### ISSUE TITLE
Voyager Multilanguage: allow models have different locales without default language

### ISSUE THREAD

**Issue by Xoshbin** [thedevdojo/voyager#3703]
## Version information

 - Laravel: v5.7
 - Voyager: v1.10
 - PHP: 7.2
 - Database: [MySQL] [5.7]

## Description of problem

let's say I have a post model with different languages so sometimes I have a post that have to be translated from English to Kurdish, And sometimes I have a post just in Kurdish or I have a post just in English. So my default language is Kurdish but when I try to add a post just in English without Kurdish default language it asks fro the Kurdish language post. so instead of adding a new post it tries to edit a post "Translate a post"
the code I'm using:

```
$post = new Post;
$post = $post->translate('en');
$post->title = $title;
$post->save();
```

It gives back this error:

> Integrity constraint violation: 1048 Column 'foreign_key' cannot be null (SQL: insert into `translations` (`table_name`, `column_name`, `foreign_key`, `value`, `locale`, `updated_at`, `created_at`)

## Proposed solution
Allow adding posts for different languages without translations.

**Comment by emptynick** [comment]
You have to save your post first, otherwise there is no primary (foreign) key which the relationship can reference to.
