### ISSUE TITLE
Multilanguage "language-selection" in my Page BREAD doesn't work.

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3705]
## Version information

 - Laravel: v5.7.0
 - Voyager: v1.1
 - PHP: 7.1.3
 - Database: [MySQL]

## Description

i am trying to enable multilanguage in a model and i am using the TCG\Voyager\Traits\Translatable trait, but the language selector isn't working in the following bread.

## Here is the setting and the code
here is my model:
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Translatable;


/**
 * Class ContactUsDaysAndHours
 * @package App
 */
class ContactUsDaysAndHours extends Model
{
    use Translatable;
    /**
     * @var array
     */
    protected $fillable = ['hours'];

    protected $translatable = ['day'];
}


```
and here is my voyager.php settings:

```
    ''multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Set whether or not the admin layout default is RTL.
         */
        'rtl' => false,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'fr',
        ],
    ],
```

## Screenshots
![screenshot from 2018-10-29 13-55-46](https://user-images.githubusercontent.com/42116772/47648392-98c3cb80-db82-11e8-8ac8-904bf0fdba20.png)

**Comment by ghost** [comment]
@marktopper can you help me please ?

**Comment by emptynick** [comment]
You need to post more informations, like a screenshot of your BREAD, what you mean with "doesn't work" and so on.

**Comment by ghost** [comment]
@emptynick here you go, i couldn't find the language selection in the bread as in the voyager documentation they said "Now you will see a language-selection in your Pages BREAD." but i can't find it

**Comment by emptynick** [comment]
There's nothing?

**Comment by Essam34ML** [comment]
yes

**Comment by emptynick** [comment]
You said "Here you go" but there is nothing.
Please post a screenshot of your BREAD settings.

**Comment by ghost** [comment]
@emptynick 
![screenshot from 2018-10-29 14-08-08](https://user-images.githubusercontent.com/42116772/47648900-294edb80-db84-11e8-89d0-9f6053175233.png)

![screenshot from 2018-10-29 14-09-11](https://user-images.githubusercontent.com/42116772/47648942-497e9a80-db84-11e8-875f-d6c253e5048e.png)

**Comment by ghost** [comment]
i used php artisan config:cache after i changed in the config files of voyager ..  this solved the problem
