### ISSUE TITLE
Multilanguage and duplicate data

### ISSUE THREAD

**Issue by Crazyweedz** [thedevdojo/voyager#3706]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1
 - Database: [MySQL] [5.7.19] 

## Description

I have enabled multilanguage on my model and everythings seems work fine but when I read my model I have a duplicate data.

I use the default views and controllers, how to fix this problem?

-- I apologize for my bad english

## Steps To Reproduce
1. Go to 'Tools & Database'
2. Create a new table
3. Go to 'Tools a BREAD'
4. Click on 'Add BREAD to this table' on the table formerly created
5. Set an input to 'Rich Text Box' & Save
6. Enabled the multilinguage on this model a create a new entry
7. Read your newest entry.

## Screenshots
Green Highlight => Original data
Red Highlight => Duplicate data

![chrome_2018-10-29_17-43-49](https://user-images.githubusercontent.com/9811137/47666785-ba35af00-dba4-11e8-875e-f37e7ceaa8ed.jpg)
![chrome_2018-10-29_17-43-56](https://user-images.githubusercontent.com/9811137/47666786-ba35af00-dba4-11e8-8a2c-308f18c57d58.jpg)

**Comment by yakuter** [comment]
Hello Crazyweedz,
In your database, there must be a **translations** table. Can you check it about the translation of this post. If there is no duplicate content, then it means the problem is jus about your codebase.

**Comment by Crazyweedz** [comment]
Hello, thank you for your help.

Maybe my codebase is wrong, but the problem happen on fresh install of Voyager and Laravel.

When i go on the Route 'voyager.posts.show', problem still here and the duplicate data too.

I check translations table, there is no duplicate content.

I do not see what I could have done wrong

**Comment by yakuter** [comment]
Ok, this is a progress. Can you show your 'table test' model file content? I guess it is the only file you edited over fresh install.

**Comment by Crazyweedz** [comment]
Yes, sure. Here is it 

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Translatable;


class TableTest extends Model
{
    use Translatable;

    protected $translatable = ['nom'];
}
```

Yes, this is only file I edited. I want to reiterate that the problem only appears for Rich Text Box input type

In fact, I just followed the indications of the documentation

**Comment by yakuter** [comment]
Crazyweedz, you did everything fine, nothing is wrong with your work. 

When I checked my own multilingual website ([madoors.com.tr](https://www.madoors.com.tr)), I saw that there is the same problem on rich text box. However; this is just a problem about bread file which shows the content in admin. On the other hand, there is no mistake on overall system. I am going to try to find and fix this issue. Meanwhile you can start building your multilingual website just by ignoring this part. All the other system works fine. In fact until you told this error, I never noticed it on my own website :)

**Comment by Crazyweedz** [comment]
Ok, I'm just going to ignore it for now.

Thanks for your help and your work !

**Comment by yakuter** [comment]
Crazyweedz, I found the error and created a pull request. However if you want to quick fix, open the following file with editor.

`/vendor/tcg/voyager/resources/views/bread/read.blade.php`

Change the line number 103 from this:

`<p>{!! $dataTypeContent->{$row->field} !!}</p>`

to this:

`{!! $dataTypeContent->{$row->field} !!}`

Well, it seems like an unimportant change but when you remove paragraph tag (< p >), you will see the that your problem is solved ;)

#3714

**Comment by Crazyweedz** [comment]
Yakuter, you are the best !

Thanks for your help 👍

**Comment by yakuter** [comment]
Hmm the problem occurs again when you use ul list etc. So changing **paragraph** tag to **div** is a better solution. It works better for more html tags.
