### ISSUE TITLE
How to do a Custom Bread Controller?

### ISSUE THREAD

**Issue by lucasvm** [thedevdojo/voyager#3708]
Hello, i have created a new BREAD called Sells, the thing is , i dont want to use my db, i need to show everything from an external API, so i need a custom controller for this, now i need to know how to use a controller extending the current created view.

I have created inside HTTP/CONTROLLERS/SELLS/SellsController.php in this way:

```
<?php

namespace App\Http\Controllers\Sells;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request; 
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use TCG\Voyager\Database\Schema\Column;
use TCG\Voyager\Database\Schema\SchemaManager;
use TCG\Voyager\Database\Schema\Table;
use TCG\Voyager\Database\Types\Type;
use TCG\Voyager\Events\BreadAdded;
use TCG\Voyager\Events\BreadDeleted;
use TCG\Voyager\Events\BreadUpdated;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Models\DataRow;
use TCG\Voyager\Models\DataType;
use TCG\Voyager\Models\Permission;
use App\User;
use App\Role;

class SellsController extends VoyagerBreadController
{
   //***************************************
    //               ____
    //              |  _ \
    //              | |_) |
    //              |  _ <
    //              | |_) |
    //              |____/
    //
    //      Browse our Data Type (B)READ
    //
    //****************************************

    public function index(Request $request)
    {
        // MyCode

    }
}
```

And this is the error im getting:

Declaration of App\Http\Controllers\Sells\SellsController::index(Illuminate\Http\Request $request) should be compatible with TCG\Voyager\Http\Controllers\VoyagerBreadController::index()

**Comment by bugzbrown** [comment]
VoyagerBreadController does not expect to get a Request object in the index function.
I did that before and found out that :
`public function index() {` works
and
`public function index(Request $request) {` does not work
I am not sure what you need the bread controller for, but, you'll be facing other problems down the road if you are just using it to get your permission mapping.
You are better off creating a bread with the name Sells in straight up Voyager fashion and point the bread to your controller. This way you can override functionality without worrying about dataTypes and so forth.
I had a similar issue recently with Voyager and that seemed to be the best solution.

A note, you will most likely want to keep your controller at \App\Http\Controllers level. Voyager can get buggy when you put controllers in nested namespaces.

**Comment by emptynick** [comment]
If you have a class that extends another and you override a method, its signature of course needs to be the same.
If you need the request object, you could get it in the constructor and put it into a field.
