### ISSUE TITLE
 After composer update I got error

### ISSUE THREAD

**Issue by dyaskur** [thedevdojo/voyager#3712]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.10
 - PHP: 7.1.5
 - Database: mysql v 8.0.12

## Description

After I upgraded voyager from v1.1.7  to v1.1.10 I got this error

> json_decode() expects parameter 1 to be string, object given

in code:
`            $details                              = json_decode($row->details);`

## Steps To Reproduce
It's happen in all BREADs page.

## Screenshots
![screen shot 1440-02-21 at 4 02 54 pm](https://user-images.githubusercontent.com/9539970/47710998-be2a0580-dc66-11e8-9cb1-ce1e03693c88.png)

**Comment by DrudgeRajen** [comment]
Might be because of **cached view** try ```php artisan view:clear``` and reload.

**Comment by emptynick** [comment]
He is using custom views.
We changed Voyager to directly return an array instead of `json_decode` it everywhere.
There are quite a few issues with the same "problem"

**Comment by DrudgeRajen** [comment]
@emptynick 

> We changed Voyager to directly return an array instead of json_decode it everywhere.

the problem here is the view is custom which is the copy of voyager bread.blade.php. We have update voyager to directly return array instead of json_decode everywhere. So, the value here it got the object inside ```json_decode()``` . I think the custom views is not used properly.

**Comment by dyaskur** [comment]
@emptynick
 > We changed Voyager to directly return an array instead of json_decode it everywhere. 

I see, now fixed. Thanks you

@DrudgeRajen 
> I think the custom views is not used properly.

I just copied from vendor, am I wrong?

**Comment by emptynick** [comment]
If you didn't changed anything in your views until now, just copy them again.

**Comment by dyaskur** [comment]
@emptynick 
> If you didn't changed anything in your views until now, just copy them again.

I changed something but I already copied again with my changes. So the problem is solved. But I have question, the way I use Custom Views is not wrong, is it? I just copied from tcg/vendor to  local resource folder and then edit it.

**Comment by emptynick** [comment]
Thats one way to do it, so its not wrong.
But we can't guarantee that it wont break like it just did in future versions.

**Comment by dyaskur** [comment]
Okay thank you

**Comment by DrudgeRajen** [comment]
@emptynick It will obviously break if anyone has used view by copying it from original one since the way of fetching data is changed in newer versions.  So, if original view is copied then it should be replaced with new one.

**Comment by jniyaz** [comment]
@DrudgeRajen Thanks.
