### ISSUE TITLE
Following Advanced Installation

### ISSUE THREAD

**Issue by ludo1960** [thedevdojo/voyager#3719]
## Description
A clear and concise description of what is missing, incorrect, or needs clarification.

## Proposed location for change
A link or description of where, in your opinion, this change would best fit in our current documentation.

## Additional context
Any relevant links or other information to justify this change.

**Comment by ludo1960** [comment]
Following Advanced Installation, cos I've got laravel 5.7 already installed

I get as far as:

php artisan vendor:publish --provider=VoyagerServiceProvider
php artisan vendor:publish --provider=ImageServiceProviderLaravel5

From my root dir

Then ran composer update

Documentation stops there!

What do I do next?.

**Comment by emptynick** [comment]
Implemented in #3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/5e23e1c46d21d3b07ad8a5ee8f3fcc5e45b9d0d6.
