### ISSUE TITLE
Bugs in Larapack

### ISSUE THREAD

**Issue by FrankyJust** [thedevdojo/voyager#3721]
## Version information
 - Laravel: v5.6.33 and 5.7 latest
 - Voyager: v1.1
 - PHP: 7.2.7
 - Database: MySQL 5.7.21

## Description
It's not about a bug in Voyager itself, but in the packages from Larapack ('officially' supported on the website of Voyager with a link to Larapack). I've tried to install Voyager Hooks in different combinations of Laravel, but it can't get it to work. I've put an issue there (https://github.com/larapack/voyager-hooks/issues/24) but no reply at all. It seems that the developer doesn't maintain Voyager Hooks anymore... It's a bit frustrating in this way, and costs a lot of time, trying to get this working. 
Can you give a reply on this? Thx

**Comment by fletch3555** [comment]
Voyager Hooks is NOT officially supported by this team (though there is a lot of overlap).  I've added a comment there since this is unrelated to Voyager specifically.
