### ISSUE TITLE
Voyager + Rich Text box very bad bug problem.Immediatly fix it next update

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#3723]
## Version information

 - Laravel: v5.4.36
 - Voyager: v1.1.9
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

When I use "?>", "<script>", "some js variables functions php code too"  in my content Richtext editor and Clinet side crashed ! What is problem ? Why does a famous admin panel have such error? Why do voyager developers not see this error and do not find the solution?

## Steps To Reproduce
1. Create a new post and insert this code in a sample code <?php echo "example"; ?>
2. The code will be save in database but is not show correctly in edit post and client side

## Screenshots
![ice_screenshot_20181104-003051](https://user-images.githubusercontent.com/34381878/47957153-5a873b80-dfca-11e8-9daa-10626c97f7da.png)

**Comment by fletch3555** [comment]
That screenshot doesn't even look like Voyager.  What did you do to get this? Provide some code or a way we could reproduce your issue.

Also, your description provides no actual information and is just inflammatory claims.  If this was such a massive/glaringly obvious bug, don't you think there would be dozens of issues or complaints about this?

**Comment by nicat-eliyev** [comment]
This screenshot is my client side. some template. Do you understand what is problem?

**Comment by nicat-eliyev** [comment]
This is voyager bug!

**Comment by fletch3555** [comment]
This is your site's frontend... there is absolutely zero chance that this is caused by Voyager

**Comment by nicat-eliyev** [comment]
Rich Text box don't working correctly when i insert some php variables functions some Javascript codes write in content. both backend and client side not display correctly post. This is real screenshot for client side. and another problem when I edit post from admin panel voyager... rich text box do not execute data correctly from database

**Comment by nicat-eliyev** [comment]
{!! $post->body !!}  it is only helpful some Html codes... do not working if content includes some variables functions and. etc.

**Comment by nicat-eliyev** [comment]
And I'm searching some backend codes and find some filter methods. filtered php tags, script tags "preg_replace". this is not good solution if you think do it for security problems

**Comment by fletch3555** [comment]
When you provide information relevant to Voyager (not your site), I'll take this seriously.  Right now, it just seems like incoherent ramblings about things that aren't working for you (most of which have absolutely nothing to do with Voyager)

**Comment by nicat-eliyev** [comment]
Excatly ! Sorry for wrong information :( I made a mistake writing my own code.
`<meta name="description" content="{!! str_limit($post->body, 200) !!}" />` 
and add here strip_tags problem fixed. 
`<meta name="description" content="{!! str_limit(strip_tags($post->body), 200) !!}" />`
