### ISSUE TITLE
Voyager slug issue for arabic language

### ISSUE THREAD

**Issue by aliihaidar** [thedevdojo/voyager#3725]
## Version information
 - Laravel: v5.7.7
 - Voyager: v1.1.7
 - PHP: 7.1.19
 - Database: MySQL 8.0

## Description
I enabled multilanguage in voyager, and added "ar" for Arabic support. When I go to posts and click on the "ar" tab, when I enter title in arabic for example "مقال باللغة العربية", the output slug is "mqal-ballghh-alarbyh".

The arabic text is transformed to its equivalent translation found int the map_arabic() function in slugify.js

## Steps To Reproduce
1. Go to 'config/voyager.php'.
2. Set multilanguage enabled to true.
3. Scroll down and add "ar" to the locales array.
4. Go to posts
5. Click on the newly generated "ar" tab.
6. Enter post title in Arabic, for example "مقال باللغة العربية".
7. The output slug will not be in arabic characters, but rather in English.

## Expected behavior
It is expected especially in Arabic language, that the output is actual arabic characters.

**Comment by emptynick** [comment]
Please use the issue template and describe exactly what's wrong with the slug.
Are there characters missing, what do you put as your title and what do you expect to come out as the slug?

**Comment by aliihaidar** [comment]
Issue updated, please check. I am new here so excuse my misunderstanding.

**Comment by emptynick** [comment]
That's exactly what a slug is for. Slugs are used in URLs and therefore [can't contain](https://tools.ietf.org/html/rfc3986#page-11) arabic/turkish/some greek/... characters

**Comment by aliihaidar** [comment]
Thanks for the quick reply, but on the contrary, to enforce SEO properly, slugs for searches in arabic language must be in arabic characters, we can strip them from special characters, but they have to be in arabic, translating them to the current equivalent in English makes no sense. If you check any arabic blog on the web, they all have slugs in arabic characters. Is there a way to keep them arabic instead of the current transformation in the voyager framework?

**Comment by emptynick** [comment]
Currently its de-facto "forbidden" to use those chars in URL, see document above (even tho we live in 2018).
I dont know what you mean with "search", but slugs have nothing to do with searching.
You can disable slugging of course. Then just use an accessor/mutator and [str_slug()](https://laravel.com/docs/helpers#method-str-slug) for example.

**Comment by aliihaidar** [comment]
Thanks again. But do you mean this is forbidden in voyager in this case? Because I am trying to achieve whats shown in the example below (this is a valid link online):

https://www.elnashra.com/news/show/1256818/كلودين-عون-روكز-توقع-على-تعاليم-شرعية-وقانونية-واخ

**Comment by emptynick** [comment]
Again, see the document above.
Even tho its old, its still valid. And with that, those characters are "not allowed" in the whole www.
It might work, but it does not have to work.
Open that link in Internet Explorer or Edge.
It will result in `https://www.elnashra.com/news/show/1256818/%D9%83%D9%84%D9%88%D8%AF%D9%8A%D9%86-%D8%B9%D9%88%D9%86-%D8%B1%D9%88%D9%83%D8%B2-%D8%AA%D9%88%D9%82%D8%B9-%D8%B9%D9%84%D9%89-%D8%AA%D8%B9%D8%A7%D9%84%D9%8A%D9%85-%D8%B4%D8%B1%D8%B9%D9%8A%D8%A9-%D9%88%D9%82%D8%A7%D9%86%D9%88%D9%86%D9%8A%D8%A9-%D9%88%D8%A7%D8%AE`
And thats not really SEO-friendly.

**Comment by aliihaidar** [comment]
Makes more sense now. Thanks again for the great explanation.
