### ISSUE TITLE
Add field to user page

### ISSUE THREAD

**Issue by lucasvm** [thedevdojo/voyager#3726]
Hello

 I need to add new fields to user creation form.

 I have edited the edit-add.blade.php inside users folder, i can see the new field, also i have added it on db called nombre, then when i try to create the new user im getting:

 SQLSTATE[HY000]: General error: 1364 Field 'nombre' doesn't have a default value (SQL: insert into `users` (`name`, `email`, `password`, `role_id`, `settings`, `updated_at`, `created_at`) values (myname, test@test.com, $2y$10$KU4Hva0XjZOWwbzf5UA4C.Xqgg6kKu7b/DXsgwer2s2A2QXnIuUyy, 3, {"locale":"en"}, 2018-11-06 14:53:54, 2018-11-06 14:53:54))

Any ideas what im missing?

**Comment by fletch3555** [comment]
Please use the issue templates.

**Comment by lucasvm** [comment]
Ok, at this moment when trying to create a new BREAD based on my table im getting:

SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL: insert into `data_types` (`name`, `display_name_singular`, `display_name_plural`, `slug`, `icon`, `model_name`, `controller`, `policy_name`, `generate_permissions`, `details`, `description`, `server_side`, `updated_at`, `created_at`) value

I have created a new database with the id of course, then i got to Create Bread based on table.

**Comment by emptynick** [comment]
Looks like you removed auto-increment for `id` on the `data_types` table?!
(Just as a prevention: [here it is)](https://github.com/the-control-group/voyager/blob/1.1/migrations/2016_01_01_000000_create_data_types_table.php#L17)

**Comment by lucasvm** [comment]
Yes, already done, thank you!, just one more question is there a way to set up dependent users?, for example i need to have a business store and inside them sellers for only that store, can i create users by that one?

Example, my StoreUser:
Ebay
 -> Seller : Emptynick -> Dependent on StoreUser 1
Store:
Amazon
 -> Seller : Lucas -> Dependent on StoreUser 2

Is this possible? Multi-level hierarchical user system

**Comment by emptynick** [comment]
Closing as the original issue seems to be resolved.
Please ask further questions in our Slack group.
