### ISSUE TITLE
Analytics error: This user does not have access to property

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#3727]
## Version information

 - Laravel: v5.4.36
 - Voyager: v1.1.9
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Please help me ? What is problem here ? I already access this user but problem not fixed

## Screenshots
![ice_screenshot_20181107-004228](https://user-images.githubusercontent.com/34381878/48092966-80f5e280-e227-11e8-8aa4-555abd729b91.png)

**Comment by fletch3555** [comment]
That's a GA issue, not a Voyager one... Please make sure you've enabled the API access (pretty sure that's in our docs).

**Comment by nicat-eliyev** [comment]
Last night 3-4 hours I try it but not fixed. I don't understand what is happening. I already access everything but don't working

**Comment by nicat-eliyev** [comment]
problem fixed after enabling Tag manager Api and Google analytics reporting Api. Everything is working now

**Comment by emptynick** [comment]
So you did what @fletch3555 told you to do 3 days ago?!
