### ISSUE TITLE
Localization problem

### ISSUE THREAD

**Issue by NicolaeCasir** [thedevdojo/voyager#3728]
## Version information

 - Laravel: v**5.7.***
 - Voyager: v **^1.1**
 - PHP: **7.2.6**
 - Database: **MySQL - 10.3.7-MariaDB**

## Description

I have problems with localization. File: **seeders**
Tried to put files from vendor in **/resources/lang/packages/en/voyager/** but didn't help.

## Steps To Reproduce
1. Install Laravel 5.7
2. Install latest version of Voyager
3. Create admin account
4. Go to admin dashboard

## Expected behavior
To see clear text from translation file.

## Screenshots
[Check this](https://i.imgur.com/tplt7t4.png)

**Comment by fletch3555** [comment]
You're going to have to be more specific about what you changed.  This works perfectly fine out of the box.

Also, I'm not sure where you got that path from, but you should be using this: https://laravel.com/docs/5.7/localization#overriding-package-language-files (`package` would be `voyager` in this case)

**Comment by NicolaeCasir** [comment]
Strange. Just installed clean Laravel + Voyager and all works well. OK. Let's close it. I don't know why this happens. 
P.S. About overriding package language filles, i used method from Laravel 5.0. Anyway, tried from 5.7 and the same. 
I hope this happens only with me. Thanks for answer.
