### ISSUE TITLE
additional_attributes is not working at all

### ISSUE THREAD

**Issue by maxmadknight** [thedevdojo/voyager#3730]
## Version information
 - Laravel: v5.6.39
 - Voyager: v1.1.10
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
I have add additional_attributes according official docs and there is no output for them at all, i have fond 1 place of using it it is in database view, and even there it is not presented right

## Steps To Reproduce
1. Go to https://voyager.readme.io/docs/custom-relationship-attributes
2. Impliment this
3. No changes at all

## Expected behavior
Display addictional field

## Additional context
I have searched useage of this field over the voyager in found 1 place vendor/tcg/voyager/src/Http/Controllers/VoyagerDatabaseController.php:240

this function is relate to view databese table(in this case model), any other usage of this attribute i am not found so i thinks this functions is under development. and there are question why it is already in docs!?

**Comment by emptynick** [comment]
The page is called `Custom Relationship Attributes` because its for `Custom Relationship Attributes`.
Not for the Database or anything else
