### ISSUE TITLE
Routing any prefix and diferent menu

### ISSUE THREAD

**Issue by DanielKimmich** [thedevdojo/voyager#3731]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.9
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

How can I route many prefixes using Voyager::routes() in ./routes/web.php

example for admin, main, dev
Route::group(['prefix' => 'admin'], function () {
   Voyager::routes();
});

Route::group(['prefix' => 'main'], function () {
   Voyager::routes();
});

Route::group(['prefix' => 'dev'], function () {
   Voyager::routes();
});

and get a different menu for each prefix in ./dashboard/sidebar.blade.php

 {!! menu('admin', 'admin_menu') !!}
  {!! menu('main', 'admin_menu') !!}
  {!! menu('dev', 'admin_menu') !!}

## Expected behavior
for 'prefix' => 'admin'
      {!! menu('admin', 'admin_menu') !!}

for 'prefix' => 'main'
      {!! menu('main', 'admin_menu') !!}

for 'prefix' => 'dev'
      {!! menu('dev', 'admin_menu') !!}

**Comment by emptynick** [comment]
Please ask questions in our Slack group (as mentioned in the issue-template).
If you really need that, you'd have to [override the view](https://laravel.com/docs/packages#views) but we suggest doing this with roles/permissions.

**Comment by DanielKimmich** [comment]
Sorry, but I do not know how to go to the Slack group to ask my question

**Comment by DanielKimmich** [comment]
ready, I'm already registered in Slack
