### ISSUE TITLE
Missing required parameters for [Route: voyager.abonnements.edit]

### ISSUE THREAD

**Issue by Mr-k404** [thedevdojo/voyager#3732]
## Version information

    Laravel: v5.7
    Voyager: v1.1.10
    PHP: 7.2
    Database: MySql 5.7

## Description:

  

-  Go to Tools
-  Click on Database
-  Add abonnements table
-  Add BREAD to abonnements table.
-  Click Browse BREAD on abonnements  
-  Click Add New
-  Click save
-  See error "Missing required parameters for [Route: voyager.abonnements.edit] [URI: admin/abonnements/{abonnement}/edit]. (View: D:\laragon\www\lifefitness\vendor\tcg\voyager\resources\views\bread\partials\actions.blade.php) (View: D:\laragon\www\lifefitness\vendor\tcg\voyager\resources\views\bread\partials\actions.blade.php)"
![capture](https://user-images.githubusercontent.com/24232988/48146391-286d2680-e2b5-11e8-876e-8bcc14bad6d5.PNG)

**Comment by emptynick** [comment]
Please [read the docs](https://docs.laravelvoyager.com/troubleshooting/missing-required-parameter) and search before opening new issues.
