### ISSUE TITLE
How to change default text editor?

### ISSUE THREAD

**Issue by aozen** [thedevdojo/voyager#3734]
## Version information
 - Laravel: v5.6.*
 - Voyager: 1.1

## Description:
Hello there, i am currently trying to change tinymce editor. Regular one is using different version than i expected. In default voyager tinymce editor when we create table or other components, using pixels in width. 
But last version of tinymce editor its using percent(%). Also design is better than voyager version. 
How can i disable current tinymce and import new version of tinymce or another editor?
I need to change that immediately. I can take any advice. Thanks in advance.

**Comment by emptynick** [comment]
That would be a cusotm formfield which is covered in our docs.
Also please ask questions in our Slack-group (as recommended in the issue-template)

**Comment by nguyenhuu1404** [comment]
I can't remove tag p when use rich text box!

**Comment by emptynick** [comment]
Please dont post in irrelevant issues.
