### ISSUE TITLE
AccessDeniedHttpException

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#3741]
## Version information

- Laravel: v5.4.36
- Voyager: v1.1.9
- PHP: 7.2
- Database: [type] [version] (e.g. MySQL 8.0)

## Description

I created new guest role and dont give access for databes section. But when guest manually add example.com/admin/database this error happens. How to redirect for example (redirect to home) when this error happen?

## Steps To Reproduce
I try from handler.php
 `if ($exception instanceof \AccessDeniedHttpException) 
        {
            return response('Access Denied', 403)
                  ->header('Content-Type', 'text/plain');
        }` 
but this code dont help me.

## Screenshots
![ice_screenshot_20181109-232523](https://user-images.githubusercontent.com/34381878/48284042-c1e43600-e477-11e8-93bc-602bbc209da1.png)

**Comment by emptynick** [comment]
`instanceof` does not care for your namespace-uses, so you have to use the fully-qualified class.
Also this is completely unrelated to Voyager.
