### ISSUE TITLE
json_decode() expects parameter 1 OR property 'width' of non-object

### ISSUE THREAD

**Issue by malkafly** [thedevdojo/voyager#3743]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.10
 - PHP: 7.2.11
 - Database: MySql

## Description
My local version of Voyager is 1.1.7 and all works fine, but in production the version 1.1.8, 1.1.9, 1.1.10 and even 1.1.7 give me error when i enter on any browser or create BREAD section.

To be more clear, 

**Version 1.1.10:**
Error on Browser:  
`
json_decode() expects parameter 1 to be string, object given (View: /home3/painel20/public_html/resources/views/checklists/browse.blade.php)
`

**Versions 1.1.6 to 1.1.9**
older versions give me error on Create:
`
Trying to get property 'width' of non-object (View: /home3/painel20/public_html/resources/views/vendor/voyager/bread/edit-add.blade.php)
`

## Steps To Reproduce
1. Go to any BREAD pages created
2. Click on Browser or Create

## Expected behavior
Able to browser and create just like i`m on local version. 

## Additional context
The PHP of prodution and local are the same, there's any clue? i even tried to copy all local vendor, and nothing.

**Comment by emptynick** [comment]
Please search before opening new issues.
Same issue as https://github.com/the-control-group/voyager/issues/3712
In short: you are using custom views and we changed `options` to directly return an object instead of `json_decode` it everywhere.
You need to adapt this in your custom view.

**Comment by malkafly** [comment]
i have updated my local version, them my views. thanks!
