### ISSUE TITLE
Translate to Portuguese.

### ISSUE THREAD

**Issue by douglas-88** [thedevdojo/voyager#3747]
## Description
Good afternoon, I do not understand very well how that translates into Portuguese, can you explain me better?

**Comment by jehadja** [comment]
![image](https://user-images.githubusercontent.com/17106547/48368996-4b894300-e6c6-11e8-8ea2-d154d70226e2.png)
in admin make user locale  Portuguese

**Comment by douglas-88** [comment]
Many thanks !, I managed to translate a good part.
I just wanted to translate the menu items on the left, I looked inside the folder: vendor / tcg / voyager / publishable / lang / pt_br, and I did not find any strings to translate.

How do I translate the menu on the left for example ?
![captura de tela de 2018-11-12 17-42-03](https://user-images.githubusercontent.com/10869960/48371851-018f6580-e6a4-11e8-839a-72c0f0cca581.png)

**Comment by alnouirah** [comment]
**Make sure you have added the language you want in locales Property**

At the beginning you should go to the config/ Voyager.php file and add the language you want. And set the value of enabled property to true.
![1](https://user-images.githubusercontent.com/23138077/48402252-3a7b1900-e73c-11e8-905a-f89c6fc938d1.PNG)

Then from the admin panel go to Tools -> Builder Menus and click the Builder button.

To create a translation for any item from the list, click the Edit button for the item you want to translate
![2](https://user-images.githubusercontent.com/23138077/48402545-f1779480-e73c-11e8-9140-2f413d488ad1.PNG)

Finally select the language you want to translate from the list above and write the text you want.

![3](https://user-images.githubusercontent.com/23138077/48402735-69de5580-e73d-11e8-8ecf-44730c488111.PNG)

**Comment by douglas-88** [comment]
Got some more, but there are still things that did not translate, and why does not this image appear ?
![captura de tela de 2018-11-13 09-38-33](https://user-images.githubusercontent.com/10869960/48411553-fe8a8880-e728-11e8-93ff-d215763282e1.png)

**Comment by emptynick** [comment]
Those are translatable through the Bread-builder.
Please look around in Voyager a bit and get used to it.
The image is probably not displaying because of a missing storage-symlink.
Thats covered in the Laravel docs.
