### ISSUE TITLE
How to use existing voyager image uploading system on our manual image input 

### ISSUE THREAD

**Issue by rizkiheryandi** [thedevdojo/voyager#3748]
## Description
How to upload image from (my own html image input on my overriding bread view) with voyager existing configuration for uploading image, in my case is S3

I have added manually  `<input type="file" name="something"/>` on my override view of bread edit-add, and i override the controller too

But how the best practice to store my manual image input with existing voyager system for store image / file (like naming and file laying), instead of i make my own code for store file to S3 and the path to database.

**Comment by emptynick** [comment]
I'm not really sure what you are asking. So I think this is much better asked in our Slack group, also because its not an issue.
