### ISSUE TITLE
Overriding views partially work, strange!

### ISSUE THREAD

**Issue by lear2012** [thedevdojo/voyager#3752]
## Version information

 - Laravel: v5.7.13
 - Voyager: v1.1.10
 - PHP: 7.1
 - Database: [Mysql] [5.7.20]

## Description

My aim is to override some view files in voyager. Overriding only worked for index.blade.php
but for other templates, no. quite weird.

## Steps To Reproduce
1. Copy vendor/tcg/voyager/resources/views/index.blade.php to resources/views/vendor/voyager/index.blade.php.  And when i edited it, it worked
2. Copy vendor/tcg/voyager/resources/views/partials/ to resources/views/vendor/voyager/partials/.
And when i edited app-footer.blade.php in resources/views/vendor/voyager/partials/, nothing changed.
If i edited vendor/tcg/voyager/resources/views/partials/app-footer.blade.php, it worked.
The problem is that if i modified index.blade.php in resources/views/vendor/voyager/, it worked.
For other templates, no. quite weird.

Any help would be much appreciated!

## Expected behavior
Overriding on any templates in voyager can work.

## Additional context
i use swoole http server.

**Comment by emptynick** [comment]
The paths are looking good.
Please try `php artisan view:clear`

**Comment by lear2012** [comment]
i had tried, and also i did php artisan cache:clear, and delete the cache files in storage/framework/views, still not work :(

**Comment by amansatija** [comment]
i was able to override the footer view . using exactly what you described you have done 
i too have laravel 5.7
voyager 1.1.10
and php 7.2
i don't think there is any bug.... there must be some spelling mistake in the path or spelling mistake in the name of some file ... re check

**Comment by lear2012** [comment]
thanks @amansatija, i think i need to make a re-check. is it possible that there could be something to do with swoole?

**Comment by lear2012** [comment]
after the re-check, i did nothing with the code. however it worked after a night's sleep :)
i think it could be probably the cache problem, but im not sure if it is laravel's cache or 
yogager's. cause i had already explicitly clear the laravel's cache.
Anyway it is working now. By the way nice work of this project
