### ISSUE TITLE
broken link text

### ISSUE THREAD

**Issue by adrielwerlich** [thedevdojo/voyager#3753]
## Version information

 - Laravel: v2.0.1
 - Voyager: v1.1.10
 - PHP: 5.7
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
The links text appear to be broken

![image](https://user-images.githubusercontent.com/20656722/48669293-c0a2b100-eae8-11e8-9401-03c40af09004.png)

## Additional context
Just installed. Opened and the links were broken

**Comment by adrielwerlich** [comment]
solved...

I´ve just created a new database and run again the `php artisan voyager:install --with-dummy` command...

now the links appear to be normal !!

**Comment by emptynick** [comment]
Looks like you installed Voyager with a not supported app-locale and fallback locale.
