### ISSUE TITLE
Needed Dependent Dropdown

### ISSUE THREAD

**Issue by kashif-saleem** [thedevdojo/voyager#3756]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
Needed Dependent Dropdown for my first laravel voyager project.

**Comment by kashif-saleem** [comment]
How can I create dependent dropdown i have Schools, Branches and Students Bread, now i want to add student in which if i choose school from a dropdown then branches dropdown will get branches for that particular schools. How can i do that, I am new in laravel, any help will be appreciated.

**Comment by fletch3555** [comment]
This was answered in #3460.  Also, you didn't provide any version information, which is required as part of the template.
