### ISSUE TITLE
can not install in docker

### ISSUE THREAD

**Issue by shaunthegeek** [thedevdojo/voyager#3757]
## Version information

 - Laravel: v5.7.13
 - Voyager: v1.1.10
 - PHP: 7.1
 - Database: MySQL 5.7

## Description

voyager don't support docker very well. 

## Steps To Reproduce
1. add `php artisan voyager:install` to start.sh run by Dockerfile, such as https://github.com/sinkcup/laravel-demo/blob/master/docker/start.sh
2. docker build
3. docker run --env APP_ENV=production

## Expected behavior
install paused by ask "Do you really wish to run this command? (yes/no)"

## Screenshots
![image](https://user-images.githubusercontent.com/4971414/48848174-4622ab80-edde-11e8-8dad-c59497fdcb74.png)

## Additional context
I have hacked it:

```Dockerfile
RUN php artisan vendor:publish --tag dummy_content
RUN php artisan vendor:publish --tag voyager_assets
```

```start.sh
php artisan migrate --force
php artisan db:seed --force --class=VoyagerDatabaseSeeder
```

**Comment by emptynick** [comment]
I dont understand the problem.
There is no error.

**Comment by shaunthegeek** [comment]
If there is a ask for input, docker run will failed.
docker is a program, not a human. @emptynick

**Comment by ghost** [comment]
I'm having a similar issue trying to deploy my app using Laravel Forge.

**Comment by emptynick** [comment]
This question is asked when Laravel is in production mode.
Why do you put Laravel in production mode first and then install Voyager?

**Comment by shaunthegeek** [comment]
@emptynick If you try Docker, you will find there is no Database when docker is building.
So if some package need seed to database, you must install it when RUN.
The same docker image will RUN in any mode: local, testing, production.

**Comment by ghost** [comment]
Sorry @emptynick but I don't know the answer to your question. I'm afraid I'm new to Laravel, Forge and Voyager of course. On my development workstation the installation worked like a charm.But Forge deploys from my Git repository and puts Laravel in production mode I guess.

**Comment by noreff** [comment]
You can execute command in running container like this:

**`docker exec -i -t container_name /bin/bash`** than run what you want there. Or you can add localphp.env with different settings and run artisan commands which require database access with --env=localphp in the end. I'm currently running 2 laravel & voyager projects on docker instances and have no issues.

**Comment by emptynick** [comment]
Closing as #3897 was merged.
