### ISSUE TITLE
How to hide values on view?

### ISSUE THREAD

**Issue by lucasvm** [thedevdojo/voyager#3766]
Hello

 I have created a new Bread and everything is working good, i need to know how to hide some values from being listed on index view, for example i can see the id, i can see created at, i can see others value i dont need to list, is there a way to hide certain rows?

**Comment by emptynick** [comment]
I'm not sure I understand your question, but I think this is mentioned in our [docs](https://docs.laravelvoyager.com/core-concepts/bread-builder).
Also, please use the issue template. If its not an issue, its better asked in our Slack-group.

**Comment by lucasvm** [comment]
The issue is that i can see for example the id of the item in my view and dont want to show that number, also i dont want to show the created at row in the list, i can see all the values that are on the table but i need to show only some of them , not all.

**Comment by emptynick** [comment]
Yeah, then I understand you correctly and you should read our docs.

**Comment by lucasvm** [comment]
Ok, i have disabled them by using the Visibility mode to Browse disabled , i hope thats correct, i will check the docs anyway on that step.

**Comment by emptynick** [comment]
Thats the way, yes.
