### ISSUE TITLE
Pagination Search bar does not show database columns in "#search_key" dropdown

### ISSUE THREAD

**Issue by pamekar** [thedevdojo/voyager#3768]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.0
 - PHP: 7.1
 - Database: 10.1.22-MariaDB- Debian 9.0

## Description

When Server Side pagination is activated, the search functionality fails to work correctly. The Search key select drop down in the search bar shows "No Results Found". The `$searchable` variable returns as `null`.

`$searchable = $dataType->server_side ? array_keys(SchemaManager::describeTable(app($dataType->model_name)->getTable())->toArray()) : '';`

## Steps To Reproduce
1. Create a BREAD
2. Activate the "Server-side Pagination" option.
3. Try to perform a search.
4. The first field in the search bar reads "No Results Found".

## Expected behavior
The first field should provide a list of the database columns to make the search possible

## Screenshots
![invoice](https://user-images.githubusercontent.com/24904288/49167568-eecc9000-f335-11e8-8a72-0194fa04a841.jpg)

**Comment by emptynick** [comment]
Please fill in the version numbers, otherwise we are not able to help you.

**Comment by pamekar** [comment]
I've updated the numbers..

**Comment by emptynick** [comment]
`Database: [type] [version] (e.g. MySQL 8.0)` is in your case after Voyager the most important version number.

**Comment by pamekar** [comment]
> `Database: [type] [version] (e.g. MySQL 8.0)` is in your case after Voyager the most important version number.

I've updated that. Thanks you.

**Comment by pamekar** [comment]
So I traced back to `VoyagerBaseController.php` on this line

`$searchable = $dataType->server_side ? array_keys(SchemaManager::describeTable(app($dataType->model_name)->getTable())->toArray()) : '';`

I checked the `describeTable()`, then the `listTableDetails($tableName) `

I tried putting the raw table name (for instance `invoices`), and it worked.

The `$tableName` is gotten from the `$dataType->model_name` which returns the Eloquent model class of the bread (for instance, `App\Invoice`). 

I think the `SchemaManager` doesn't work with Eloquent, but with raw table name. 

### Suggestion

- We can add a separate column to store the raw table name, which can be referenced for this particular functionality
- We can create a function to return the raw table name when using the `$dataType->model_name`
- We can make `SchemaManager` work with Eloquent Models.

_I might be wrong with my conclusions, but what do we think?_

**Comment by emptynick** [comment]
`app($dataType->model_name)` gives an instance of your model and `getTable()` returns the name of the table as a string.
So that's not the problem.

**Comment by pamekar** [comment]
> So I traced back to `VoyagerBaseController.php` on this line
> 
> `$searchable = $dataType->server_side ? array_keys(SchemaManager::describeTable(app($dataType->model_name)->getTable())->toArray()) : '';`
> 
> I checked the `describeTable()`, then the `listTableDetails($tableName) `
> 
> I tried putting the raw table name (for instance `invoices`), and it worked.
> 
> The `$tableName` is gotten from the `$dataType->model_name` which returns the Eloquent model class of the bread (for instance, `App\Invoice`).
> 
> I think the `SchemaManager` doesn't work with Eloquent, but with raw table name.
> ### Suggestion
> 
>     * We can add a separate column to store the raw table name, which can be referenced for this particular functionality
> 
>     * We can create a function to return the raw table name when using the `$dataType->model_name`
> 
>     * We can make `SchemaManager` work with Eloquent Models.
> 
> 
> _I might be wrong with my conclusions, but what do we think?_

I was **Very Wrong** with my conclusion. The issue is with the prefix I added to my DB Tables.

The eloquent model returned the table name as `invoice`, instead of `mums_invoice`, where `mums_` is the prefix.

To solve this, I created a new database connection with `"prefix" => null`, and specified my `$table="mums_invoices"`, to make it return the required name to the `SchemaManager`.

The problem was solved by declaring the actual table name in my eloquent model.

Thank you.
