### ISSUE TITLE
Ajax sourced data for data Tables

### ISSUE THREAD

**Issue by pamekar** [thedevdojo/voyager#3769]
## Version information

 - Laravel: v5.6
 - Voyager: v1.1.0
 - PHP: 7.1
 - Database: 10.1.22-MariaDB- Debian 9.0

## Description of problem

The server side pagination for Browsing tables is not as flexible as the DataTable Ajax Server side solution. The page does not need a reload before giving search results. Results can be downloaded in different standard formats, with the help of a few buttons. Also, sorting is much more faster and efficient with DataTables.

## Proposed solution
DataTables has the ability to read data from virtually any JSON data source that can be obtained by Ajax. This can be done, in its most simple form, by setting the ajax option to the address of the JSON data source.

The ajax option also allows for more advanced configuration such as altering how the Ajax request is made.

## Alternatives considered
Data Table has proven to be the best alternative for handling table's data.

Your team has done an excellent work, and it saved me from a lot of stress. 
It'll be nice if you can add this feature to your next release.

**Comment by emptynick** [comment]
This has been requested quite a few times, but its not easy because of the various formfields.
Definitely nothing for 1.x

**Comment by pamekar** [comment]
Thanks for your response.

I hope one day, we'll find a work around..
