### ISSUE TITLE
How to extend a new action function?

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#377]
Add,Delete,Edit and View functions have been builded in voyager, how to add new action button in view for xxx module?

I know I can override any of the BREAD views by creating a new folder in resources/views/vendor/voyager/slug-name , but how to create new function? 

Is it possible override controller?

**Comment by marktopper** [comment]
You can overwrite controllers by changing the config value of `voyager.controllers.namespace` and then run `php artisan voyager:controllers`.

**Comment by jun283** [comment]
Hi marktopper 

Where to change config value of voyager.controllers.namespace?

Is it config/voyager.php, controllers section?

**Comment by marktopper** [comment]
Yep.

https://github.com/the-control-group/voyager/blob/master/publishable/config/voyager.php#L31

**Comment by Muhammadinaam** [comment]
Please check my answer

http://stackoverflow.com/a/41162875/5013099
