### ISSUE TITLE
Cant install in Laravel 5.7.14

### ISSUE THREAD

**Issue by jagroop** [thedevdojo/voyager#3772]
## Version information

 - Laravel: v5.7.14
 - Voyager: v1.1.10
 - PHP: 7.1
 - Database: MySQL 5.7

## Description

Cant  install Laravel voyager in in 5.7.14

## Steps To Reproduce
1. Run ```composer require tcg/voyager```

## Screenshots
![1](https://user-images.githubusercontent.com/12444128/49277003-32460c00-f4a6-11e8-942f-8227d8d177ce.png)

**Comment by emptynick** [comment]
No problem for me.
Please show us your composer.json

**Comment by fletch3555** [comment]
Also try `composer whynot tcg/voyager` and see why it blatantly ignores 1.1.4 through 1.1.10, some of which support 5.7

**Comment by yagoz** [comment]
Im having the same problem.
![captura de pantalla de 2018-11-30 16-38-30](https://user-images.githubusercontent.com/25851575/49310942-84932700-f4be-11e8-81a1-6eb7ff11ed18.png)

![captura de pantalla de 2018-11-30 16-38-58](https://user-images.githubusercontent.com/25851575/49310941-84932700-f4be-11e8-95d5-8d01406a7aa0.png)

![captura de pantalla de 2018-11-30 16-39-15](https://user-images.githubusercontent.com/25851575/49310940-84932700-f4be-11e8-8445-45975b3df850.png)

**Comment by jagroop** [comment]
@emptynick @fletch3555 still not working ,, here is content of composer.json

```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.3",
        "fideloper/proxy": "~4.0",
        "grafite/builder": "^2.5",
        "laravel/framework": "5.7.*",
        "laravel/horizon": "^2.0",
        "laravel/telescope": "^1.0",
        "laravel/tinker": "~1.0",
        "spatie/laravel-activitylog": "^3.1",
        "spatie/laravel-medialibrary": "^7.0.0",
        "spatie/laravel-permission": "^2.27",
        "themsaid/laravel-langman-gui": "^0.3.1",
        "tymon/jwt-auth": "dev-develop"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "laravel/dusk": "~3.0",
        "mockery/mockery": "~1.0",
        "phpunit/phpunit": "~7.0",
        "squizlabs/php_codesniffer": "^3.2"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
              "laravel/dusk"
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}

```

**Comment by fletch3555** [comment]
Yes, it was auto-closed since we merged a pull request that fixes it, however that change has not been released yet.  We'll get that out sometime this week

**Comment by jagroop** [comment]
@emptynick @fletch3555 , can you guys please release this fix ? ... I really want to use this package in my new setup and this issue is holding me from doing so ,, So please :pray:
