### ISSUE TITLE
How to create inline fields of relations

### ISSUE THREAD

**Issue by adrielwerlich** [thedevdojo/voyager#3776]
Hello there voyager commnity, I´m pretty new to using voyager, laravel and php, so pardon my lack of knowledge... I´m trying to create a inline list of documents and addresses related to one user (meaning, one user could have many addresses and documents).
I would like to have like a list of already registered documents and addresses to the user and also simultaneously have like a plus(+) button to be able to add new records for this same user
So my question is 
how to include a field like user has many addresses or user has many documents? How could one include this type of field? Inline?
Where I could find some examples?
Thanks...
God bless you all.... 😃

**Comment by fletch3555** [comment]
Please use our issue templates.  It prompts you to enter the information we need to troubleshoot issues.  If you find that information does not seem relevant to your issue/question, then you're likely asking a "how do I...?" question, which is best asked in our slack group.

**Comment by adrielwerlich** [comment]
ok...
