### ISSUE TITLE
Generate thumbnails when uploading in Media Manager

### ISSUE THREAD

**Issue by popiciulo** [thedevdojo/voyager#3782]
## Proposed solution
I would like that Laravel Voyager could auto-generate thumbnails when I upload photos with the Media Manager section.

**Comment by emptynick** [comment]
I think that'd be awful to configure, but we could implement an Event that fires for every file uploaded so you can control what you do with whatever files you like.

**Comment by emptynick** [comment]
Implemented in https://github.com/the-control-group/voyager/pull/3884 (merged into 1.x)
