### ISSUE TITLE
link image gallery to posts

### ISSUE THREAD

**Issue by bogdanfusea** [thedevdojo/voyager#3783]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Additional context
When i create a new post, besides the single-image filed that is now available, I would like to add a image gallery. This image gallery must generate automatically on multiple file upload, a thumbnails as well. 
Also it would be nice to have a relation between a post and its galleries. 
Thanks a lot

**Comment by emptynick** [comment]
Please use the issue-template.
If you want to ask a question, please use our Slack group.
Once you filled out all required information, we can reopen this issue.
