### ISSUE TITLE
I need add post view count . How it with Voyager ? Any example ? Or Anyone can help me ?

### ISSUE THREAD

**Issue by nicat-eliyev** [thedevdojo/voyager#3786]
## Description
A clear and concise description of what is missing, incorrect, or needs clarification.

## Proposed location for change
A link or description of where, in your opinion, this change would best fit in our current documentation.

## Additional context
Any relevant links or other information to justify this change.

**Comment by fletch3555** [comment]
You must fill out the issue template, not just leave it default.
