### ISSUE TITLE
problem accessing generic.exception string

### ISSUE THREAD

**Issue by Tazoeur** [thedevdojo/voyager#3788]
## Version information
 - Laravel: 5.7.15
 - Voyager: v1.1
 - PHP: 7.1.24
 - Database: MySQL(not relevant)

## Description
When trying to create a table (with option "Create model for this table?" set to "Yes, Please") and bad write permission, an exception is raised.
The error message contains the string accessor (generic.exception)

## Steps To Reproduce
1. sudo chmod 1110 app/
2. Create new table with "Create model for this table?" set to "Yes, Please"
3. click on "Create new table"

## Expected behavior
'generic.exception' should be replaced by 'Exception'

## Screenshots
https://i.imgur.com/8LTETwv.png

**Comment by fletch3555** [comment]
Is this a fresh install or did you upgrade at one point(even between patch versions)?

**Comment by Tazoeur** [comment]
it's a fresh install (composer require tcg/voyager)

**Comment by emptynick** [comment]
This is better opened as a PR.
The code:
https://github.com/the-control-group/voyager/blob/cd0f02030f7e26a7c74f0971714f6303b9848756/src/Traits/AlertsMessages.php#L56
