### ISSUE TITLE
Menu builder won't show item if it contains dashes in the URL

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#379]
- Laravel Version: 5.3.26
- Voyager Version: 0.10.2
- PHP Version: 5.6
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.19-MariaDB

### Description:
This is a strange issue, but if the url contains dashes (`-`), it doesn't show in the menu.
For example, creating a menu-item `/admin/products-config`, nothing shows in the menu, as soon as the dash is removed, product shows normally.

### Steps To Reproduce:

+ Create a menu item under Admin, add a dash to the url.  Nothing shows.
+ remove the dash, item now shows.

**Comment by handiwijoyo** [comment]
The menu slug need to match with BREAD slug. Make sure you have `products-config` as slug on your BREAD.

**Comment by victorpierredev** [comment]
It's not that the URL wasn't working, the item was simply not showing. But I can't see to reproduce it. 

I'll keep on testing and report if the problem persists.

The issue can be closed. And again, thanks for the awesome work!
