### ISSUE TITLE
Sort pictures after uploading a batch image

### ISSUE THREAD

**Issue by ertugruldege** [thedevdojo/voyager#3792]
## Version information

 - Laravel: v5.7
 - Voyager: v1.x
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description of problem

After adding a batch image, we can't sort the pictures we added. Can we do it with the Drag and Drop method?

## Additional context
I did it for my own project in an amateur way.
![screenshot_1](https://user-images.githubusercontent.com/26246843/49637071-6a54ce00-fa15-11e8-9597-251f84685e0d.png)

**Comment by fletch3555** [comment]
Version information is required

**Comment by emptynick** [comment]
This will be possible in version 1.2.
See (https://github.com/the-control-group/voyager/pull/3889).
