### ISSUE TITLE
auto-mount MENU

### ISSUE THREAD

**Issue by piterog** [thedevdojo/voyager#3795]
## Version information

 - Laravel: v5.7
 - Voyager: v1.10
 - PHP: 7.2

## Description of problem
Every time I install my project, I have to configure the whole menu again, there's no way that I can "save" the menu.

## Proposed solution
Build a exported seeder, to mount a menu with a command, like artisan menu:build

**Comment by emptynick** [comment]
This has been discussed very very often here already and is possible with 3rd party packages like `orangehill/iseed`.
I'm going to close this as a duplicate of https://github.com/the-control-group/voyager/issues/2553 for example.
