### ISSUE TITLE
View formfields/coordinates bug

### ISSUE THREAD

**Issue by gcolotti** [thedevdojo/voyager#3796]
## Version information
 - Laravel: v5.7.*
 - Voyager: v1.1.*
 - PHP: 7.1.3
 - Database: MySQL 5.7.20

## Description
The short div tag in views/formfields/coordinates is breaking all the elements before it.

## Steps To Reproduce
- Use vendor's coordinates field, in any view edit-add.
- Override any edit-add view, and include a coordinates field view.
- Simply replacing `<div id="map"/>` with `<div id="map"></div>` gets it to work perfectly.

## Additional Info
Tested in Chrome 71.0.3578.80, Opera 57.0.3098.91 and Firefox 63.0.3.

**Comment by emptynick** [comment]
This is better opened as a pull request.

**Comment by TheyCallMeSurf** [comment]
So the pull request its alredy made?

**Comment by gcolotti** [comment]
Sorry for being late with the pull request
