### ISSUE TITLE
Media manager section of admin panel shows errors in browser console but everything seems work well

### ISSUE THREAD

**Issue by Megumin2k17** [thedevdojo/voyager#3804]
Version information
-Laravel: v5.7.17
-Voyager:v1.1
-PHP: 7.2
-Database: MySQL v5.7

Description
Fresh instal of laravel and voyager. When I go to:
http://voyager/admin/media
In the console of browser an error accurs:
GET http://voyager/storage/users/ 403 (Forbidden)
also when as I navigate through folder here I get one more: 
GET http://voyager/storage/users/December2018/ 403 (Forbidden)

The picture wich I chosen as avatar is located here (Media Library > users > December2018) and displaying well and actions (delete, rename) with it are seem to working well. Why do I get this errors in browser console?

Also I noticed that this picture(my admin avatar) is duplicating (appear in two places/paths) in:
voyager\storage\app\public\users\December2018
and also in:
voyager\public\storage\users\December2018
Is it ok? Also same actions are apply to both of them.
 

1. install laravel via composer
2. install voyager via composer
3. config an .env in laravel, so I change next parameters:

APP_URL=http://voyager
DB_DATABASE=voyager
DB_USERNAME=root
DB_PASSWORD=

My server is accessable on http://voyager I use Open server.

4. past "php artisan voyager:install" to cmd and press enter
5. make an admin account via cmd  "php artisan voyager:admin admin@email.com --create"
6. I tried to config voyager\config\filesystems.php 

'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            // 'url' => env('APP_URL').'/storage',
            'url' => '/storage',
            'visibility' => 'public',
        ],
or 
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            //'url' => '/storage',
            'visibility' => 'public',
        ],

both ways produce same result for me. 

7. So here I go to http://voyager/admin/media and this is were an error accurs in my browser console

GET http://voyager/storage/users/ 403 (Forbidden)

Expected behavior
If an image displays well and actions are working why should this errors accur? I wont any errors

Additional context
As I wrote in description section, I am not sure if the same picture should apper on two diffrent paths.

**Comment by fletch3555** [comment]
The image in 2 paths is perfectly normal, as you've already shown from your `filesystems.php` snippet. Please refer to the laravel documentation for details on how that all works, but essentially `path/to/voyager/public/storage` is a symlink to `path/to/voyager/storage/app/public`.

As for why you get the 403 on `http://voyager/admin/users`, that's almost certainly because your webserver is configured to refuse directory listings. However the root problem is why it's trying to load that in the first place.

**Comment by Megumin2k17** [comment]
Woops! I was trying to say that the error accurs only in http://voyager/admin/media (Media Library > users > December2018) , not http://voyager/admin/users.  I did not understend what should I do to fix this console 403 error :C
Aww... I tried it on another PC and here is some screenshots what's going on, i dont think this is webserver's config fault

![error1](https://user-images.githubusercontent.com/25470574/49970643-22d3c200-ff80-11e8-9f8b-4b640e2b7087.jpg)
![error2](https://user-images.githubusercontent.com/25470574/49970644-22d3c200-ff80-11e8-9ec9-21940fe813ac.jpg)

**Comment by Megumin2k17** [comment]
emptynick's solution is working. fixed the errors. thanks.
