### ISSUE TITLE
Media: Error Uploading a file larger than 2MB

### ISSUE THREAD

**Issue by fargonse** [thedevdojo/voyager#381]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.2
- PHP Version: 7.0.3

### Description:
When I try to upload a file larger than 2 MB, it returns the following error:
Whoops, looks like something went wrong.
1/1
ErrorException in VoyagerMediaController.php line 226:
Undefined variable: path
in VoyagerMediaController.php line 226
at HandleExceptions->handleError('8', 'Undefined variable: path', 'D:\Proyectos\images\vendor\tcg\voyager\src\Http\Controllers\VoyagerMediaController.php', '226', array('request' => object(Request), 'success' => false, 'message' => 'fopen(D:\Proyectos\images\public): failed to open stream: Permission denied', 'e' => object(ErrorException))) in VoyagerMediaController.php line 226

**Comment by handiwijoyo** [comment]
@farogonzalo try to set `D:\Proyectos\images\public` directory permission to `777`

**Comment by fargonse** [comment]
I try and then tell you... I can upload the files smaller than 2mb without problems, are you sure that the permissions on the folder can affect? Thank you so much!!

**Comment by fargonse** [comment]
Sorry for mi english... I'm from Argentina

**Comment by handiwijoyo** [comment]
If the problem persist, you need to open your php.ini file and change maxupload size

**Comment by fletch3555** [comment]
The issue is most likely the server/php configuration.  Please check the php.ini file as @handiwijoyo suggested.

**Comment by fargonse** [comment]
@handiwijoyo @fletch3555 Thanks for your support! The problem was the configuration of the php.ini configuration. Excuse me for bothering you!

Regards!
