### ISSUE TITLE
Re-open #3806 [better description]

### ISSUE THREAD

**Issue by gcolotti** [thedevdojo/voyager#3810]
## Version information
Laravel: v5.7.*
Voyager: v1.1.*
PHP: 7.1
Database: MySQL

## Description
#3806 was closed and marked as a "duplicate". Sorry if the previous description was not clear enought, but it is not a duplicate. I will try to explain better.

In #3620, @ta-tikoma fixed #2125, allowing to use a 3rd lvl menu. Also, in this [comment](https://github.com/the-control-group/voyager/issues/2125#issuecomment-377687142) of the same issue post, @f0reclone added the missing CSS for #3620.

I added the custom JS and the CSS previously mentioned to custom js and css files, and 3rd menu items are now working like a charm. But there is still an issue: when you click in a 3rd lvl menu item (with 3rd lvl menu WORKING), the sidebar is refreshed (to get the content of the section of the desired menu item, i.e. voyager.posts.index) and the expanded items are collapsed again. This do not happen to 2nd lvl items: when you click a 2nd lvl item and the sidebar is refreshed, the 2nd lvl items remain expanded.

So dont get confused. The 3rd lvl menu is now showing and lets you access the items.
Hope it is clear enought now.

## Steps To Reproduce
- Build a 3rd level menu item
- Click on it and wait for the sidebar to refresh.

## Expected behavior
- 3rd level items remain expanded when you click on them to get the content for the main section.

## Additional context
First I thought it was due to the 'active' class in 'li' elements or any other missing class in 3rd lvl items, but is not (at least I couldn't find).

**Comment by fletch3555** [comment]
Please don't create new issues like this.  Instead, just edit and reopen the other one.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3855
