### ISSUE TITLE
the table name like vq_tests,with underline,the created BREAD can't open

### ISSUE THREAD

**Issue by nicolasmeng** [thedevdojo/voyager#3815]
- Laravel: v5.5
 - Voyager: v1.1
 - PHP: 7.1.13
 - Database: [mysql] [5.6] 

## Description
when I create a new table ,the table name like vq_tests,with underline.
Then I create BREAD ,but when I open the BREAD,the exception like this:
```
Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
This action is unauthorized.
Previous exceptions
```

If table name have no underline ,like tests ,everything is ok

## Steps To Reproduce

1. Go to 'setting->database'
2. Click on 'vq test-> Browse BREAD'
3. See error

**Comment by nicolasmeng** [comment]
I am sure it authorized
And I create table And BREAD many times.

**Comment by fletch3555** [comment]
Sounds like you never added the auto-generated permissions to your user's role...

**Comment by nicolasmeng** [comment]
> Sounds like you never added the auto-generated permissions to your user's role...

I did that

**Comment by MrCrayon** [comment]
I used many tables with underscores and never had any problem.
This issue refers to an old Voyager version so I'm closing it.

If after update you are still experiencing this problem please open another issue.
