### ISSUE TITLE
role and permission and  normal user login route

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [thedevdojo/voyager#3816]
hi i like to know with what package our method you are handling the role permission system
and what is the route for normal user login

**Comment by emptynick** [comment]
Please use the issue template and ask questions in our Slack group as stated in the issue template.

**Comment by darvishiyan-mahdi** [comment]
Where ia slack group that i need to ask there?

**Comment by emptynick** [comment]
Thats written in our Readme
