### ISSUE TITLE
Translated Images and Files for future

### ISSUE THREAD

**Issue by juvenisdevteam-burak** [thedevdojo/voyager#3817]
Hello Dear The Control Group,

That Voyager package has been a sick bomb for me to learn automation for administrating on Laravel. But there is some issues i have been encouraged in when i looked up that you have no features for Image or File translatable, but could be much more useful with those features could we add these on future ? or is there any way that i can may bypass(disable) the disabler of that.

Have a nice day.

Additional Information : 
Laravel 5.7.17
Voyager 1.1.10
Translatable grabbed from TCG\Voyager\Traits\(also works on other types but not on image nor files)

**Comment by emptynick** [comment]
Please use the issue-template and search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/2501
