### ISSUE TITLE
Can't delete PDF file 

### ISSUE THREAD

**Issue by MishaKolotov** [thedevdojo/voyager#3819]
## Version information

 - Laravel: 5.6
 - Voyager: 1.1
 - PHP: 7.1.3
 - Database: MySQL 8.0

## Description:

First of all, sorry for my bad English. it's not my first language.
I created a BREAD with some fields and one for upload a pdf.
In Database -> Field Name = pdf, DB Type = text
In BREAD ->Input Type = File 

When i upload pdf it's all ok, but after delete it and SAVE changes, it dont delete it. Voyager save "[]" in this field. If i  click on menu item, exept SAVE , it delete file without "[]" in field. 

I need to save NULL after click on "save"

Once again sorry for my bad explanation

## Additional context

![default](https://user-images.githubusercontent.com/31927159/50285523-845acb80-046d-11e9-8bd6-37a6f7780649.png)

**Comment by emptynick** [comment]
Looks like you faced this issue: https://github.com/the-control-group/voyager/issues/3397
which was fixed in https://github.com/the-control-group/voyager/pull/3521 and will be released with 1.1.11

**Comment by MishaKolotov** [comment]
@emptynick  oh, sorry for my question) 
This solution helps me, thank you very much
