### ISSUE TITLE
How to get the form fields to show them in the custumisez edit page ?

### ISSUE THREAD

**Issue by tryagain-3** [thedevdojo/voyager#3833]
## Description
I need a working way to get an array (or any other way) containing the form fields (which i already added them with the bread ) of my "reservations" content type cause I will need to do a lot of modification on the edit page of the "reservations " edit page

**Comment by emptynick** [comment]
Please use the issue-template and follow the instructions in it (...questions are better asked in our Slack group)
Also this is basic Laravel/Eloquent knowledge and can be found in our views.
