### ISSUE TITLE
menu helper function with locale (multilang)

### ISSUE THREAD

**Issue by alizadehmammadali** [thedevdojo/voyager#3835]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database:Mysql 5.7

Hello I want to return menus with translations as json.
I added  according to [documentation link](https://docs.laravelvoyager.com/core-concepts/multilanguage#eager-load-translations)
I tested like this 
`menu("frontend","_json",["locale"=>"en"]) ` but this is not working(It returns default language).How to get menus with language support with api. Model translate functions return empty json data
![2](https://user-images.githubusercontent.com/13322630/50416243-fef26500-0838-11e9-8851-47242465ed19.png)
 menu("frontend","_json") returns default language translations menus

**Comment by fr8ak2** [comment]
U should use on frontend mcamara/laravel-localization, go through loop and pass variable to locale. I think that will do the job.

**Comment by emptynick** [comment]
@min1mal Thats not correct.
The `menu()` method can't do that for you.
You'd have to fetch your MenuItems and translate them manually as described in our docs.

**Comment by alizadehmammadali** [comment]
I solved like this.Thanks
```
 $list = Menu::where('name', '=', "frontend")
                ->with(['parent_items' => function ($q) {
                        $q->select("id", "menu_id", "parent_id", "title", "url")->get()->translate("ru");
                        $q->with(['children' => function ($qq) {
                                $qq->select("id", "menu_id", "parent_id", "title", "url")->orderBy('order');
                            }]);
                    }])
                ->first();


        $response = [];
        $list     = $list["parent_items"];
        foreach ($list as $single)
        {
            $model                 = [];
            $model["title"]      = $single->getTranslatedAttribute('title');
            $model["url"]        = $single->getTranslatedAttribute('url');
         
            $children              = [];
            if (count($single->children) > 0)
            {
                foreach ($single->children as $c)
                {
                    $child["children_title"] = $c->getTranslatedAttribute('title');
                    $child["children_url"]   = $c->getTranslatedAttribute('url');
                    $children[]       = $child;
                }
                $model["children"] = $children;
            }

            $response[] = $model;
        }
        return $response;
```

**Comment by dkmanolov** [comment]
Or in your partials -> menu.blade.php (if you have such structure) for example you can call:
`$menu_item->getTranslatedAttribute('title', app()->getLocale(), 'en')`

**Comment by shlaing** [comment]
@alizadehmammadali 
Thanks for tip. I changed a bit.

``
$list = menu($slug,'_json');

        foreach ($list as &$single)
        {

            $single->title = $single->getTranslatedAttribute('title',$lang);
            if (count($single->children) > 0)
            {
                foreach ($single->children as &$c)
                {
                    $c->title = $c->getTranslatedAttribute('title',$lang);
                }
            }
        }

        $data = [
            'menu' => $list
]
