### ISSUE TITLE
The file "" does not exist

### ISSUE THREAD

**Issue by bryanezavala** [thedevdojo/voyager#3839]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.3
 - Database: MariaDB
- Storage: AWS S3

## Description

I'm trying to upload an image but I have:
{success: false, message: "The file "" does not exist", path: ""}

## Steps To Reproduce
1. Go to 'Media manager'
2. Click on 'Upload'
3. Select an image

## Screenshots

![image](https://user-images.githubusercontent.com/33789256/50428267-0ee36680-0884-11e9-8cd0-f5ba54b3bb07.png)
![image](https://user-images.githubusercontent.com/33789256/50428275-2ae70800-0884-11e9-8363-53c9469a2e68.png)

**Comment by emptynick** [comment]
There's already an issue similar to yours, please share your information there: https://github.com/the-control-group/voyager/issues/1711
