### ISSUE TITLE
v1.0 to v1.1 upgrade guide is missing.

### ISSUE THREAD

**Issue by garstas** [thedevdojo/voyager#3843]
## Description
In your [v1.1.0](https://github.com/the-control-group/voyager/releases/tag/v1.1.0) release you mentioned upgrade guide link, but it returns 404.

## Proposed location for change
https://voyager.readme.io/docs/10-to-11

## Additional context
Page is not found.

**Comment by emptynick** [comment]
Whoops.
Its in our new documentation [here](https://docs.laravelvoyager.com/getting-started/upgrading).
Changed the link in the release.

**Comment by garstas** [comment]
> Whoops.
> Its in our new documentation [here](https://docs.laravelvoyager.com/getting-started/upgrading).
> Changed the link in the release.

Thanks. I wonder why noone asked/noticed that before :open_mouth:

Oh, by the way, could you please update images there? They are broken)

**Comment by emptynick** [comment]
Which images where? I see all of them.

**Comment by garstas** [comment]
> Which images where? I see all of them.

I think you just load them from cache. https://blobscdn.gitbook.com/ seems to be down, so images are not loaded too. Temporary problem, i think. You can close the issue)
