### ISSUE TITLE
The "read more" link does not hide the text and overlaps with those in the next row.

### ISSUE THREAD

**Issue by davidcmg** [thedevdojo/voyager#3844]
## Version information

 - Laravel: v5.7.19
 - Voyager: v1.1.10
 - PHP: 7.2
 - Database: MySql 5.7

## Description

The "read more" link does not hide the text and overlaps with those in the next row.

## Steps To Reproduce
Browsing any browse.blade.php page. It's not an overwritten page.

## Screenshots

![imagen](https://user-images.githubusercontent.com/18193792/50482030-ee7eed80-09e4-11e9-81a5-f9de1b0456e9.png)

**Comment by emptynick** [comment]
That's a know problem and because of that readmore was removed completely in https://github.com/the-control-group/voyager/pull/3671

**Comment by fletch3555** [comment]
Closing since it's resolved in 1.x (in preparation for a 1.2 release)
