### ISSUE TITLE
[Duplicate] Cant install in laravel 5.7.14

### ISSUE THREAD

**Issue by jagroop** [thedevdojo/voyager#3847]
[Issue 3772](https://github.com/the-control-group/voyager/issues/3772)

When you guys are planning to release this fix , can you please suggest a workaround if this release going to take a while ?

I find no better option other then Laravel voyager.

Thanks

**Comment by emptynick** [comment]
Just run `composer require tcg/voyager:1.1.x-dev` for now.
You can "downgrade" to `^1.1` easily later.

**Comment by fletch3555** [comment]
Not an issue with the project.  Questions like this should be asked in Slack or on the original issue/PR.

**Comment by jagroop** [comment]
@emptynick Thanks for the help :+1:

**Comment by jagroop** [comment]
@fletch3555 Well ...  i really don't enjoy creating duplicate issues , Original issue was closed without resolving the problem . I already asked question in original issue , But never heard back from you , I understand how open source work and i respect your contribution , Thanks , Peace :+1: :100:
