### ISSUE TITLE
Voyager won't use custom User model

### ISSUE THREAD

**Issue by artchik** [thedevdojo/voyager#3849]
## Version information
 - Laravel: v5.7.19
 - Voyager: v1.1.10
 - PHP: 7.2.1
 - Database: MySQL

## Description
Cannot get Voyager to use a custom User model. Tried with setters and events. When using the App\User directly, the setters and events work, but when trying to create/update users in Voyager, it appears to my custom user class.

## Steps To Reproduce
Tried the following two solutions:
1.  In config/voyager.php
'namespace'                    =>  App\User::class,

2. In boot method of AppServiceProvider 
Voyager::useModel('User', \App\User::class);

## Expected behavior
Voyager will use the App\User model for things such as setters, events, etc. E.g. when creating a new user in Voyager, it will emit the saving event that's defined in App\User

**Comment by emptynick** [comment]
Please change the Model in the user-bread. That should work.

**Comment by artchik** [comment]
That worked. Can't believe I missed it.
