### ISSUE TITLE
After change table for login, I cannot login with that.

### ISSUE THREAD

**Issue by Pakinwet** [thedevdojo/voyager#3853]
## Description
Hi, I can't login but I've checked, it don't have an error and can't redirect to dashboard page. So, I'd like to ask you about this, Have you ever encountered a problem like this?

I using :)
Laravel Version: 5.7
Voyager Version: 1.1
PHP Version: 7.2

## Proposed location for change
App/User.php
<img width="1275" alt="screen shot 2561-12-29 at 12 57 12" src="https://user-images.githubusercontent.com/9396436/50534076-83aaef00-0b69-11e9-922d-b6ecfd73dbff.png">

## Additional context
I followed the instructions in issues #2568 , #934 and #3565

**Comment by fletch3555** [comment]
Please follow our templates.  Version information is required.

**Comment by Pakinwet** [comment]
I using :)
Laravel Version: 5.7
Voyager Version: 1.1
PHP Version: 7.2

**Comment by Pakinwet** [comment]
You have any document or example for me?

**Comment by Pakinwet** [comment]
I've checked and debug files

VoyagerAuthController.php result 1 row

<img width="935" alt="screen shot 2561-12-29 at 17 32 32" src="https://user-images.githubusercontent.com/9396436/50537255-f0d17b00-0b8f-11e9-9f7e-0008b6114a35.png">

VoyagerAdminMiddleware.php result 0 row

<img width="936" alt="screen shot 2561-12-29 at 17 29 25" src="https://user-images.githubusercontent.com/9396436/50537191-55d8a100-0b8f-11e9-9279-1c6b7c1182b8.png">

**Comment by Pakinwet** [comment]
I can solve problem this issue set $primaryKey in User.php

Thx :)

**Comment by emptynick** [comment]
Please close your issue if it is solved.
