### ISSUE TITLE
CSRF vulnerability

### ISSUE THREAD

**Issue by tchenu** [thedevdojo/voyager#3854]
## Version information

 - Laravel: v5.7.*
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MariaDB 10.1.37

## Description

There is a CSRF security vulnerability that allows you to delete a parameter.

## Steps To Reproduce
1. It is necessary to open a link of this type to a connected administrator :

http://[DOMAIN]/admin/settings/[SETTING_ID]/delete_value

## Expected behavior
A CSRF token would have to be added to correct this security vulnerability.

## Additional context
A malicious attacker can use this vulnerability for various attacks depending on the available settings.

**Comment by emptynick** [comment]
Instead of using this "vulnerability" the user could just go to the settings and delete each and every setting, because he has permissions to do this.
I see how this is false behaviour, but if the user has permission to use settings, expect them to do so.

**Comment by tchenu** [comment]
@emptynick We are obviously talking about a person who does not have the permissions to do so.

The goal of a CRSF flaw is to bypass permissions restrictions through a victim, in this case an administrator.

https://en.wikipedia.org/wiki/Cross-site_request_forgery

Laravel recommends us to use this CSRF token, let's use it. :smiley:

**Comment by emptynick** [comment]
Ah yeah, now I know what you mean, sorr, didn't read properly.
Not really sure how we should solve that tho.
Probably make it a POST request

**Comment by thibeaultchenu** [comment]
![screenshot_20181229_130815](https://user-images.githubusercontent.com/17689143/50538134-d3d68100-0b6a-11e9-82ec-032f1e9d9fcb.png)

As with content deletion, a form in popup form with a CSRF token :smiley:

**Comment by tchenu** [comment]
![screenshot_20181229_130815_censored](https://user-images.githubusercontent.com/17689143/50538142-0bddc400-0b6b-11e9-9298-5865f7858252.jpg)

As with content deletion, a form in popup with a CSRF token :smiley:
