### ISSUE TITLE
Inconsistent class naming for model creation.

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#386]
- Laravel Version: 5.3.26
- Voyager Version: 0.10.2
- PHP Version: 5.6
- Database Driver & Version: mysql Ver 15.1 Distrib 10.1.19-MariaDB

### Description:

When creating  a model from the database manager, the naming of the class is inconsistent. Example:

- Created a table uploaded_files
- A model was created with the class name `Uploaded_files`
- When trying to create the BREAD functionality (without changing any of the default options), the section "Model Name" shows the pre-filled option `App\UploadedFile`, which is fine.
- But then I get the following error:
`Class App\UploadedFile does not exist`

Clearly, the BREAD component is expecting `Camel Casing`, while the model creator is using `Snake Case`.

And because it adds to the `data_types` table before hitting this error, if I correct the class name manually, I also have to remove the entry from `data_types` in order to run it again.

### Steps To Reproduce:
+ Create a Database with the option to create module checked as "yes".
+ Enable BREAD with default values.
+ Class does not exist error is thrown.

**Comment by handiwijoyo** [comment]
Duplicate #355
