### ISSUE TITLE
Where's HasRelationships.php  (disapears from Traits after composer update)

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#3861]
## Version information
 - Laravel: v5.7
 - Voyager: v1.1.11
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
After composer update file HasRelationships.php in /vendor/tcg/voyager/src disapears

## Steps To Reproduce
composer update

## Expected behavior
i use my own model with Voyager relationship
Example

```
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\HasRelationships;

class Catproduit extends Model
{
    use HasRelationships;

    protected $table = 'catproduits';
    protected $fillable = ['nom', 'slug'];

    public function parentId()
    {
        return $this->belongsTo(self::class);
    }
}
```
After composer update, i got this error:
`include(/SRV_APP_PATH/vendor/composer/../tcg/voyager/src/Traits/HasRelationships.php): failed to open stream: No such file or directory`

**Comment by emptynick** [comment]
Its has been removed from 1.1.11 because it is completely useless, undocumented and there's no point in using it.
Also, as the issue-template suggests, please ask questions in our Slack group.
