### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EmirT** [thedevdojo/voyager#3862]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.11
 - PHP: 7.2.10
 - Database: [MySQL] [8.0.13] 

## Description

it's been 4 hours reading and trying to solve this " Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `translations` add unique `translations_table_name_column_name_foreign_key_locale_unique`(`table_name`, `column_name`, `foreign_key`, `locale`))"

I have followed "https://laravel-news.com/laravel-5-4-key-too-long-error" and also updated MySql. 
Deleted Voyager and then tried install again (with and without dummy data). Cleared cache etc.

Don't know what else I can do so I need some's help, please. 

Why am i getting this "too long name" problem after updating MySql ?

**Comment by emptynick** [comment]
Please search before opening new issues.
There are solutions all over our [closed issues](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+1000+bytes).
