### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EmirT** [thedevdojo/voyager#3866]
## Version information

 - Laravel: v5.7
 - Voyager: v1.0.11
 - PHP: 7.2.1
 - Database: [MySql] [8.0.13]

## Description
I am so disappoint with Voyager. Yesterday I spend 5 hours to figure out your "Translate table name too long" problem. 
And now I am facing  `{{` Voyager::image( $product->image ) }} ` doesn't` work. 
It shows as `<img` src="http://etecom/[&quot;products\\January2019\\kg7niqTj1QGHB1FXAx0R.jpg&quot;]" `style="width:100%">` which i believe is wrong link ?

I am spending more time to solve your bugs than focusing on my project !
Please don't close this case just saying "read the other cases" since yesterday I have been reading...

Please provide a clear indicate or help so I can continue my project.

Thanks.

**Comment by emptynick** [comment]
Please provide more information.
`Voyager::image()` does not return what you said above.

**Comment by EmirT** [comment]
Thank you for your reply, I just find a solution.  I went to BRED and clicked for edit. I changed from "multiple images" to "images" (only) and then uploaded images again and it work. 
I gave you small tip, if you put (!) marks on the most issued areas such as this (image) and indicate all the problems & solution suggestions maybe you can get more people to interest with voyager. I continue using it but I wouldn't recommend voyager to people who is willing to take their time for solution a part from their work.
