### ISSUE TITLE
Upload in Sub-directory

### ISSUE THREAD

**Issue by fargonse** [thedevdojo/voyager#387]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.2
- PHP Version: 7.0.13

Hello! It is me again! I need a little help

### Description:
The assets do not work when I upload the project to a subdirectory. None of them

### Steps To Reproduce:
- I copy the contents of the PUBLIC  folder to PUBLIC_HTML/APPS/TEST folder on my hosting
- I create a INST folder with the instalation files, in the same level that the PUBLIC_HTML folder
- In the index.php in PUBLIC_HTML/APPS/TEST folder, i change the lines with the data of "require" and "$ app" being as follows:
     require __DIR__.'/../../../test/bootstrap/autoload.php';
     $app = require_once __DIR__.'/../../../images/bootstrap/app.php';
- I edit app/Providers/AppServiceProvider.php, appending to the "register" function the following line:
     $this->app->bind('path.public', function(){return base_path().'/public_html/apps/images';});

Help me!

Thanks and sorry for the inconvenience

**Comment by fargonse** [comment]
Even uploading the entire installation into the same folder, I can not get it to take the assets

**Comment by marktopper** [comment]
Have you tried modifying the assets path in the config?

https://github.com/the-control-group/voyager/blob/master/publishable/config/voyager.php#L43

**Comment by fargonse** [comment]
Yes ... I tried putting relative routes, entire routes and I did not get it to work ... :(

**Comment by farogonzalo** [comment]
evidentemente es un error de cómo yo estoy configurando las rutas. Si en el archivo Config, pongo la URL pública como ruta de ASSETS, los encuentra y funciona, pero no funcionan las rutas de users, pages, posts, etc... Sigo tratando y luego les comento

**Comment by fargonse** [comment]
Obviously it is a mistake of how I am configuring the routes. If in the Config file, I put the public URL as the ASSETS path, it finds them and it works, but the routes of users, pages, posts, etc do not work ... I keep trying and then I comment

**Comment by handiwijoyo** [comment]
Try to create symbolic link from "public_html/yourfolder" to "storage/app/public"

**Comment by marktopper** [comment]
Closed due to inactivity.
