### ISSUE TITLE
"Trying to get property 'type' of non-object"

### ISSUE THREAD

**Issue by priyag597** [thedevdojo/voyager#3871]
when try to edit admin profile i am facing this issues 

I checked into database as well in edit column 1 was already  there . 
 
Fixed by steps bewlow:

Go to phpmyadmin
find "user_belongsto_role_relationship" && "user_belongstomany_role_relationship" at field column
Chang from "0" to "1" in Edit column

**Comment by emptynick** [comment]
Please use the issue template. Otherwise we are not able to help you.

**Comment by priyag597** [comment]
Laravel Version: 5.7.14
Voyager Version: 1.1.1
PHP Version: 7.2

"Trying to get property 'type' of non-object"   when I trying to edit admin user I am getting this issues , i had gone through the already raised https://github.com/the-control-group/voyager/issues/3159 solution but it is same as it was .

find "user_belongsto_role_relationship" && "user_belongstomany_role_relationship" at field column
Chang from "0" to "1" in Edit column 

I found this solution but it dosent work for me.

**Comment by priyag597** [comment]
https://github.com/the-control-group/voyager/issues/2431#issuecomment-451375112

I got this issues as well but i didnt get any response on it .please help me out

**Comment by priyag597** [comment]
please reply somebody

**Comment by priyag597** [comment]
why dont you reply @emptynick 
i have just got an stuck .

**Comment by emptynick** [comment]
You still did not provide the necessary informations from the issue-template.
For example the steps to reproduce.
Because you linked to an issue which was about upgrading...did you upgrade?
Are you sure you are on 1.1.1?

**Comment by vaggelis2018** [comment]
Updated to 1.1.1 would fix the issue i had the same problem. Just check if you have override the controller

**Comment by priyag597** [comment]
## Version information

 - Laravel: v5.7.14
 - Voyager: v1.1.11
 - PHP: 7.2
 - Database: 10.1.37-MariaDB

## Description

![image](https://user-images.githubusercontent.com/46341574/50757931-bd28dc00-1286-11e9-8c8c-c6ea66a0eab0.png)

1. When I am trying to view users on click users sidebar nav 
2. And admin user profile when I try to edit (path= "right side click on avtar ->click on profile ->Edit my profile -> error  ")
 I am getting following this error

## Steps To Reproduce
Steps to reproduce the behavior:
1. Go to 'login into admin'
2. Click on 'users nav sidebar'
4. See error  Trying to get property 'type' of non-object

## Screenshots
If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/46341574/50760804-c0c06100-128e-11e9-9e87-8d811cb247b9.png)


## Additional context
Steps to reproduce the behavior:

Go to admin login 
click on "Tools" 
select "database" 
scroll down 
Users ->edit bread
see the error in screen shot 

![image](https://user-images.githubusercontent.com/46341574/50761425-5c060600-1290-11e9-8652-bbccaf0ea91d.png)

**Comment by priyag597** [comment]
> Updated to 1.1.1 would fix the issue i had the same problem. Just check if you have override the controller

Version information
Laravel: v5.7.14
Voyager: v1.1.11
PHP: 7.2
Database: 10.1.37-MariaDB
"tcg/voyager": "^1.1" this is my version current version ,I had override controller as well 

Description
When I am trying to view product on click product sidebar nav
I am getting following this error

"Too few arguments to function TCG\Voyager\Models\DataRow::sortByUrl(), 0 passed in C:\xampp\htdocs\mfscl_website\storage\framework\views\af0f59f74b7ead321b3661535f5bd10077a2c768.php on line 61 and exactly 2 expected (View: C:\xampp\htdocs\mfscl_website\resources\views\vendor\voyager\products\browse.blade.php) "

Steps To Reproduce
Steps to reproduce the behavior:

Go to 'login into admin'
Click on 'product nav sidebar'
See error 
Screenshots

![image](https://user-images.githubusercontent.com/46341574/50765526-2a933780-129c-11e9-94ce-47f963a9fe7b.png)

**Comment by vaggelis2018** [comment]
If you override the controllers you have to check the new ones

**Comment by kevinho2018** [comment]
I had same problem and I solved it this way. First, you need to find table "data_rows". Then replace the column details in filed "user_belongsto_role_relationship" with this.
`“{“model”:“TCG\\Voyager\\Models\\Role”,“table”:“roles”,“type”:“belongsTo”,“column”:“role_id”,“key”:“id”,“label”:“display_name”,“pivot_table”:“roles”,“pivot”:“0”}”`

I don't know why, but column "details" originally content something like this :`“{“\model\”:“TCG\\\\Voyager\\\\Models\\\\Role”,“\table\”:“\roles\”,“\type\”:“\belongsTo\”,“\column\”:“\role_id\”,“\key\”:“id”,“label”:“display_name”,“pivot_table”:“roles”,“pivot”:“0”}”`
This will cause the problem "Trying to get property 'type' of non-object".

**Comment by priyag597** [comment]
> I had same problem and I solved it this way. First, you need to find table "data_rows". Then replace the column details with this.
> `“{“model”:“TCG\\Voyager\\Models\\Role”,“table”:“roles”,“type”:“belongsTo”,“column”:“role_id”,“key”:“id”,“label”:“display_name”,“pivot_table”:“roles”,“pivot”:“0”}”`
> 
> I don't know why, but column "details" originally content something like this :`“{“\model\”:“TCG\\\\Voyager\\\\Models\\\\Role”,“\table\”:“\roles\”,“\type\”:“\belongsTo\”,“\column\”:“\role_id\”,“\key\”:“id”,“label”:“display_name”,“pivot_table”:“roles”,“pivot”:“0”}”`
> This will cause the problem "Trying to get property 'type' of non-object".

 In "user_belongsto_role_relationship " ?
thank you so much 

btw this work in my case , I tried yours but i nthg had reflect 
 $options = json_decode($row->details);
                if ( $options->type == 'belongsTo' ) {
                    $relationshipField = @$options->column;
                    $keyInCollection = key($dataType->{$bread_type . 'Rows'}->where('field', '=', $relationshipField)->toArray());
                    array_push($forget_keys, $keyInCollection);
                }

**Comment by emptynick** [comment]
> Fixed by steps bewlow:

> Go to phpmyadmin
find "user_belongsto_role_relationship" && "user_belongstomany_role_relationship" at field column
Chang from "0" to "1" in Edit column

Thats not by default. Please don't change things because its fun.

**Comment by iuliansafta** [comment]
@priyag597 you have to pay attention when seeding data into the data_row table. I took over a project that it has the same issue as you. I found that at seeding data it has a json string :
 
`'{"model":"TCG\\\Voyager\\\Models\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}'` 

After I dug up a bit into voyager model I found out that they are using an attribute `setDetailsAttribute` which is encoding "details" field to json. So instead of using a string as json you may use an array at seeding database: 
`[
                'model' => 'TCG\\Voyager\\Models\\Role',
                'table' => 'roles',
                'type'  => 'belongsToMany',
                'column' => 'id',
                'key' => 'id',
                'label' => 'display_name',
                'pivot_table' => 'user_roles',
                'pivot' => 1,
                'taggable' => 0
]`

Hope it helps you :)

**Comment by priyag597** [comment]
and i tried all solution 
trying to edit bread 

step 
1.click on bread
2.edit users bread 

![image](https://user-images.githubusercontent.com/46341574/51980516-44e4bd80-24b6-11e9-93c7-51c95adc36fb.png)

**Comment by priyag597** [comment]
while saving user this error is visible
![image](https://user-images.githubusercontent.com/46341574/51980686-cccac780-24b6-11e9-9e45-90216de09843.png)

**Comment by henryonsoftware** [comment]
@iuliansafta your solution not correct with `v1.2.*`.
After so many trying and I found that the voyager [document](https://docs.laravelvoyager.com/v/1.1/getting-started/upgrading) not correct.

Document: `{"model":"TCG\\Voyager\\Models\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1"}`

My solution:
`{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1"}`

Bonus my seeder file:
```
array (
    'id' => 94,
    'data_type_id' => 3,
    'field' => 'user_belongstomany_role_relationship',
    'type' => 'relationship',
    'display_name' => 'Roles',
    'required' => 0,
    'browse' => 1,
    'read' => 1,
    'edit' => 1,
    'add' => 1,
    'delete' => 0,
    'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"user_roles","pivot":"1"}',
    'order' => 11,
),
```

Voyager: `v1.2.*`

Hope it helps you!

**Comment by emptynick** [comment]
The document is correct, but it's about upgrading 1.0 to 1.1 and this issue is about upgrading 1.1 to 1.2

**Comment by yoonwaiyan** [comment]
My problem with this error solved by correcting the value that's imported from an exported CSV file via SQL import. 

The error message basically tells you that the relationship config in your "details" column in your data rows that defines relationships between two models is somehow not identified as an object, which is basically data formatting issue which explains the few solutions above works for their case.

For my case it's because my value has only one forward slash instead of two. The model definition with two slashes is correct(based on the value I inspect using Sequel Pro): 
```
{"model":"TCG\\Voyager\\Models\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}
```

**Comment by lurchpop** [comment]
I couldn't get the data formatted correctly so I just deleted the user_belongsto_role_relationship & user_belongstomany_role_relationship rows direct from the db, then I rebuilt the relationship in the bread UI. What a hassle
