### ISSUE TITLE
Generate Migrations For Voyager-Created Models

### ISSUE THREAD

**Issue by PatrickL789** [thedevdojo/voyager#3872]
I was playing with Voyager and I just realized that with what I was doing, what I created using the Voyager GUI (models, breads, etc...) did not translate to migrations. So, when I turned off my development server or when I move to a production server, everything I did was gone. So, now I have to redo all that stuff. 

Is there any way to save what I have done in the Voyager control panel so I don't have to redo it all when I move to production? And if not, when can we expect this feature? I had thought that this would be a given. But, I guess not.

**Comment by adilimudassir** [comment]
orangehill/iseed to create seeders and Xethron/migrations-generator to generate migrations have been  doing a good job for me

**Comment by bolechen** [comment]
+1

**Comment by fletch3555** [comment]
This has been requested numerous times, but the maintainers don't have time (or a good way) to build it.  You'd be surprised how complex that request really is.  We're dependent on the community to provide pull requests.

Having said that, it's already in progress in #2604, so I'm going to close this.

**Comment by DrudgeRajen** [comment]
I had written a **[package](https://github.com/DrudgeRajen/voyager-deployment-orchestrator)** for creating the seeder by listening the BREAD events. I am also planning to add migration feature on it.
