### ISSUE TITLE
[Feature] Install voyager with dummy data with the exception of post and pages

### ISSUE THREAD

**Issue by nanadjei** [thedevdojo/voyager#3882]
I have used voyager for some time now and I have encountered a couple of use-cases where I needed migrations and seeds for settings, menu, roles, permissions etc without *post and pages*. Can anyone help with any simple way of getting those two tables out anytime I seed my db or it would be nice if after a fresh installation I can do `php artisan voyager:install --with-dummy-without-post-and-pages`

**Comment by fletch3555** [comment]
Just copy those migrations/seeders into your project from `vendor/tcg/voyager/.....` manually
