### ISSUE TITLE
[BUG] Created BREAD returns a blank page

### ISSUE THREAD

**Issue by VincentvanTil** [thedevdojo/voyager#3886]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.11 (latest)
 - PHP: 7.2.9
 - Database: MYSQL 15.1

## Description

When I create the BREAD option for certain tables, it works perfectly fine. However, when I create one for my products table and then I click on products in the menu, all I get is a blank page with Voyager's menus gone. Just a white screen. We think somehow products might return a blade.php that is empty but we don't know how to figure out if that is wrong and what page it returns. We can't Dump & Die (DD) to figure it out. If that's not the error then we don't know what could give back a blank screen.

This is only with the products bread option. Whenever I make one for my carts table, it works perfectly fine.

## Steps To Reproduce
I have no clue how to reproduce this step for others

## Expected behavior
What I want to happen is a crud where I can view my products, just like any other crud

## Screenshots

![knipsel](https://user-images.githubusercontent.com/43572377/51040876-db5d4780-15b8-11e9-85ee-2a51e81e17df.PNG)

## Additional context
This error was not present before. We deleted the CRUD a while ago and now when trying to remake it it suddenly returns blank

**Comment by fletch3555** [comment]
Voyager does not have any functionality related to "products" so this is almost certainly a misconfiguration or something in your app. Please check the BREAD settings for products and make sure the controller field is set properly (or left blank for the default)

**Comment by VincentvanTil** [comment]
Sorry for the confusion. I meant that I have a table in my database named “products”. The bread creator automatically links to the App/Product file like it’s supposed to and I leave the controller empty. 

It works for all other tables in my database. But when I try to create a bread for my “products” table all it returns when I click on “Products” in the voyager menu is a white page.

**Comment by andrijdavid** [comment]
Same issue here.

Version information
----
Laravel: v5.8
Voyager: v1.2.2
PHP: 7.3.2
Database:  MariaDB 10.3.12

**Comment by mallardduck** [comment]
@andrijdavid & @VincentvanTil - Are you guys still working on this and experiencing the same issue? I had a similar problem a few times but believe I haven't seen it since testing a fix for #3623

**Comment by MrCrayon** [comment]
Since this refers to an old Voyager version I'm closing it. 

If you are still experiencing this problem please: 
 - Update to last release.
 - Check if there is a view that overrides default one. 
 - Check app logs for errors. 

If nothing solves please open another issue.
