### ISSUE TITLE
Relationships field display label?

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#389]
- Laravel Version:5.3.16
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version:

### Description:
One-to-One relationship field to  another table is working, In Edit view, I can drop down select, the field display label value.

But in the browser,read view, the field display key value( id),  Is it possible display label value in Browser view and read view?

**Comment by karandatwani92** [comment]
Yes, this is required. For now i'm doing it by creating custom view and creating a relationship in model and calling it from view thus showing label.
 View code:
@elseif($row->type == 'select_dropdown')
  @if ($data->{$row->field} && isset($options->relationship))
    {{ $data->category->name}}
  @endif

**Comment by sidis405** [comment]
#715

**Comment by marktopper** [comment]
This seems to have been fixed
