### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vladsavch** [thedevdojo/voyager#3892]
SQLSTATE[HY000]: General error: 1832 Cannot change column 'role_id': used i
  n a foreign key constraint 'users_role_id_foreign' (SQL: ALTER TABLE users
  CHANGE role_id role_id INT DEFAULT NULL)

https://i.imgur.com/cckouQ1.png

voyager version: 1.1
laravel version: 5.4

help me, please

**Comment by emptynick** [comment]
Please search before opening new issues.
Duplicate of #3071

**Comment by vladsavch** [comment]
Does not help

**Comment by vladsavch** [comment]
https://ibb.co/QF74Vgd - image bug
