### ISSUE TITLE
Create Custom Controller Without Database Table

### ISSUE THREAD

**Issue by siddiqlm** [thedevdojo/voyager#3895]
## Version information
 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1
 - Database: MySQL 8.0

## Description
I want to create a page in Laravel Voyager admin which doesn't require any database table (to validate a JSON schema). Only the admin user should be able to access this page. To set permissions for this page, I'm assuming I need to include this page in BREAD list. How can I achieve this?

I tried [this](https://stackoverflow.com/questions/48743770/how-to-create-custom-controller-in-laravel-voyager) to create a custom controller. But how do I include this controller in BREAD list (only 'Add page' as I am not saving anything)?

## Steps To Reproduce
1. Create a custom controller as given in the above link
2. Open the BREAD LIST page

## Expected behavior
A new controller should be listed down in the BREAD

**Comment by emptynick** [comment]
Please ask questions in our Slack group.
