### ISSUE TITLE
submit save button in add inserting multiple rows in case double click  [BUG]

### ISSUE THREAD

**Issue by mohamedaitbella** [thedevdojo/voyager#3896]
## Version information

 - Laravel: v 5.7.19
 - Voyager: v1.1.11
 - PHP: 7.2.11
 - Database: mysql  Ver 14.14

## Description

when i'm trying  to add record if double click save button 
the record is inserted according to number of clicks 
## Steps To Reproduce
1. in any record
2. click add new [record product for example]
3. insert inpute fields
4. multiple click on the save button

## Expected behavior
normally  it should only add one record  no matter the number of clicks on save button

## Screenshots
![bug1](https://user-images.githubusercontent.com/29753809/51387234-9a6bb280-1b25-11e9-8470-c7008632a3fa.png)

**Comment by emptynick** [comment]
I'm quite sure this will be fixed in https://github.com/the-control-group/voyager/pull/3890

**Comment by mohamedaitbella** [comment]
thank you  @emptynick  , should I upgrade to 1.x or what  ??

**Comment by fletch3555** [comment]
1.x is a branch used as a staging area for a future v1.2.0 release.  We're planning to release it soon, but don't have a set date.  I would recommend waiting for the official release.

**Comment by mohamedaitbella** [comment]
thank you @fletch3555  for your prompt reply
what is your suggestion to fix this till 1.2.0 is released, should I override all my controllers or just change vendor (i know that it's a no no but the next release 1.2.0 will have the same changes ) , i have a deadline to deliver this project thanks again

**Comment by emptynick** [comment]
Voyager 1.2 removed Ajax validation so this shouldn't be a problem anymore.
