### ISSUE TITLE
[BUG] composer.json broke by voyager install

### ISSUE THREAD

**Issue by shaunthegeek** [thedevdojo/voyager#3901]
## Version information

 - Laravel: v5.7.19
 - Voyager: v1.1.11
 - PHP: 7.2.10

## Description

`composer.json` broke by voyager install.

## Steps To Reproduce
1. Go to Laravel project directory
2. run `php artisan voyager:install`
3. run `git diff composer.json`

## Expected behavior
> No newline at end of file

## Screenshots
![image](https://user-images.githubusercontent.com/4971414/51427352-0dfae600-1c32-11e9-8ed8-9c68b76b711f.png)

**Comment by fletch3555** [comment]
Uhh...... what?

**Comment by fletch3555** [comment]
Please explain your issue, because there's no error or anything in your screenshot

**Comment by fletch3555** [comment]
I'm closing this since the source of your complaint is actually in the larapack/hooks repo.
