### ISSUE TITLE
[BUG] In 1:N relationships the label of related table is not shown in browse mode, instead id is shown

### ISSUE THREAD

**Issue by codealliance** [thedevdojo/voyager#3902]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

In create and edit screen i see the dropdown as supposed to be. The label and ids are resolved. In browse mode i see the ID of the related table instead of the label

## Steps To Reproduce
i have a attribute (TypeName) of type INT(11), BREAD Type is select_dropdown and optional details are:
`{
 "relationship": {
        "key": "id",
        "label": "name"
    }
}`
   
in the Model of the table i have the method:

`public function typeCompany()
{
return $this->belongsTo(CompanyType::class,'id');
}`

## Expected behavior
I would except the browse view to show  the label ('name') column of the relatted table like in create and edit mode 

## Additional context
I checked the blade code and i don't get what i see there fully:
this is the place where i would expect things to happen, but since there is obviously no 'options' section in the field details it doesn't work. But i would expect the code to handle the options of the dropdown:

'@elseif($row->type == 'select_dropdown' && property_exists($row->details, 'options'))
 {!! isset($row->details->options->{$data->{$row->field}}) ?  $row->details->options->{$data->{$row->field}} : '' !!}
'
so this code is executed, which leads to a plain id instead of the label of the related table:
'@else
@include('voyager::multilingual.input-hidden-bread-browse')
<span>{{ $data->{$row->field} }}</span>
@endif'

**Comment by emptynick** [comment]
You are using an undocumented feature there, why?
Please use the normal relationship instead.

**Comment by codealliance** [comment]
hi, how dou you mean that?
i use everything from here:
https://voyager.readme.io/docs/relationships

**Comment by fletch3555** [comment]
We're not updating the "readme.io" docs and have since switched (https://docs.laravelvoyager.com/).  Please make sure you're referencing the latest by accessing the docs through our website.

**Comment by codealliance** [comment]
thanks for quick reply
my fault
