### ISSUE TITLE
[BUG] can not search equals 0

### ISSUE THREAD

**Issue by shaunthegeek** [thedevdojo/voyager#3904]
## Version information

 - Laravel: v5.7.19
 - Voyager: v1.1.11
 - PHP: 7.2.10
 - Database: MySQL 5.7.24

## Description

search one column equals 0, failed.

## Steps To Reproduce
1. run `php artisan voyager:install --with-dummy`
2. open local voyager web [/admin/posts](http://laravel-demo.localhost/admin/posts)
3. edit some posts, change "Featured" to 1 
4. search by equals 1, it's fine. URL: [/admin/posts?key=featured&filter=equals&s=1](http://laravel-demo.localhost/admin/posts?key=featured&filter=equals&s=1)
5. search by equals 0, failed. URL: [/admin/posts?key=featured&filter=equals&s=0](http://laravel-demo.localhost/admin/posts?key=featured&filter=equals&s=0)

## Expected behavior
search by equals 0, should return posts which featured=0

## Screenshots
![image](https://user-images.githubusercontent.com/4971414/51437666-21628b80-1cdc-11e9-831b-95504c2bbca9.png)
![image](https://user-images.githubusercontent.com/4971414/51437751-94b8cd00-1cdd-11e9-89fc-0e79051f1fd5.png)
![image](https://user-images.githubusercontent.com/4971414/51437754-a306e900-1cdd-11e9-8e64-4459ac3ed879.png)

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3905
