### ISSUE TITLE
Radio Button in BROWSE and READ pages only show the value[BUG]

### ISSUE THREAD

**Issue by yueyanzhao** [thedevdojo/voyager#3907]
- Laravel: v5.7
 - Voyager: v1.1.11
 - PHP: 7.2.11
 - Database: MySQL5.7.14

## Description
In RREAD.
When I use a Radio Button just like:

{
    "default" : "1",
    "options" : {
        "1": "XXX",
        "2": "YYY"
    }
}
In the ADD and EDIR pages, it will show me the "Radio Button" UI.
But in the BROWSE and READ pages, it just show me "1" or "2" (the values).

I haven't found some issues like that in the issues list.
Can i have another way to make it beautiful?

Thanks.

Another issue  has been closed，https://github.com/the-control-group/voyager/issues/1272

**Comment by yueyanzhao** [comment]
@emptynick it's ok, thank you. But why the code not in the voyager resource?

**Comment by emptynick** [comment]
Because I didn't open my PR yet.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/d720bb3d15217348069f305e05705446f992a619
