### ISSUE TITLE
Update to latest bootstrap version

### ISSUE THREAD

**Issue by kaxterzz** [thedevdojo/voyager#3908]
## Version information

 - Laravel: 5.7
 - Voyager: latest version
 - PHP: 7.1.2
 - Database: MySQL 5.1

First of all I'm a big fan of voyager and big thanks for all the contributors. I know that Voyager use Bootstrap version 3.3.7 and it's great but I want to use the latest version of bootstrap in my project. I tried to change the bootstrap part of the app.css and adding latest bootstrap css in the master layout. It almost looks good but there are some misalignments in the page. Any workarounds for this ?

It'll be better if you could update to the latest version of the bootstrap in a future release.

**Comment by emptynick** [comment]
Laravel itself ships with Bootstrap 4 for you to use.
This is completely independant to what Voyager uses.
Also, this has been requested various times. For example in https://github.com/the-control-group/voyager/issues/3347

**Comment by kushalgandhi009** [comment]
I want to update the admin panel theme to Bootstrap 4 based. But as Voyager is based on Bootstrap 3, I don't see a way to do it. Anyone did this before?

**Comment by emptynick** [comment]
I dont really see a reason why you would want to do that.

**Comment by emptynick** [comment]
Closing as wontfix (at least for Voyager 1)

**Comment by pajtai** [comment]
@emptynick Bootstrap 3 is dead. Can this be reopened?

https://github.com/twbs/release
