### ISSUE TITLE
Can't upload photos via the (TinyMCE)

### ISSUE THREAD

**Issue by evgeny92** [thedevdojo/voyager#3914]
## Version information

 - Laravel: v5.5
 - Voyager: v1.1
 - PHP: 7.0
 - Database: MySQL5.7.24

## Description

Some days I struggle with one question. I do not insert photos from my computer for posts and content (TinyMCE). Those, when adding a photo, nothing happens; it works only if I insert a link with a photo

## Screenshots
<p align="center"> 
  <img  src="https://i.ibb.co/VDpTC3b/2019-01-24-21-15-38.png" width="90%">
</p>

**Comment by remindbg** [comment]
Whats your APP_URL in the .env?

**Comment by evgeny92** [comment]
APP_URL=http://voyager
I installed voyager with dummy, but in posts and pages I can’t add pictures to the editor, after that i created a new bread for example portfolio, and there I can upload pictures using the editor

**Comment by remindbg** [comment]
Is that the url that you are working on? Are you sure its not different or for example localhost:8000?

**Comment by evgeny92** [comment]
With url all right

**Comment by mihaiconstantin** [comment]
Are there any updates on this?

**Comment by raymondugv** [comment]
I'm having the same issue @@. When I click the button which should show up file selector, it not response. But it work when paste a link to it. That's weird !.

**Comment by shazimali** [comment]
i am getting same issue.When I click the button which should show up file selector, it not response. But it work when paste a link to it. That's weird !. what is the solution for this problem? i don't want to recreate existing bread. is there any other solution for this?

**Comment by Liam-PVTL** [comment]
I wrote a dirty work-around for people still experiencing this issue - 

In config/voyager.php add an additional JS file
`
    'additional_js' => [
        'js/tinymce.js',
    ],
`

Then create your tinymce.js file with the following code (adjust to your needs of course): 


```
function tinymce_init_callback(editor)
{
  editor.remove();
  editor = null;

  tinymce.init({
    menubar: false,
    selector:'textarea.richTextBox',
    skin_url: $('meta[name="assets-path"]').attr('content')+'?path=js/skins/voyager',
    min_height: 450,
    resize: 'vertical',
    plugins: 'link, image, code, table, textcolor, lists',
    extended_valid_elements : 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
    file_picker_callback: function (cb, value, meta) {
      var input = document.createElement('input');
      input.setAttribute('type', 'file');
      input.setAttribute('accept', 'image/*');

      /*
        Note: In modern browsers input[type="file"] is functional without
        even adding it to the DOM, but that might not be the case in some older
        or quirky browsers like IE, so you might want to add it to the DOM
        just in case, and visually hide it. And do not forget do remove it
        once you do not need it anymore.
      */

      input.onchange = function () {
        var file = this.files[0];

        var reader = new FileReader();
        reader.onload = function () {
          /*
            Note: Now we need to register the blob in TinyMCEs image blob
            registry. In the next release this part hopefully won't be
            necessary, as we are looking to handle it internally.
          */
          var id = 'blobid' + (new Date()).getTime();
          var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
          var base64 = reader.result.split(',')[1];
          var blobInfo = blobCache.create(id, file, base64);
          blobCache.add(blobInfo);

          /* call the callback and populate the Title field with the file name */
          cb(blobInfo.blobUri(), { title: file.name });
        };
        reader.readAsDataURL(file);
      };

      input.click();
    },
    toolbar: 'styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table | code',
    convert_urls: false,
    image_caption: true,
    image_title: true,
  });
}
```

**Comment by MrCrayon** [comment]
It would be better to check browser console and report any error, I can't reproduce it.

**Comment by MrCrayon** [comment]
Closed for inactivity.

If you are still experiencing this problem please update and open another issue reporting any console error.
