### ISSUE TITLE
Storage Issue AWS EC2

### ISSUE THREAD

**Issue by jashanpj** [thedevdojo/voyager#3917]
![screen shot 2019-01-25 at 10 23 48 pm](https://user-images.githubusercontent.com/42855222/51782335-8ee34180-214c-11e9-8749-88db8a8c2a7a.png)
##Version
Laravel Framework 5.7.22
PHP 7.1.16 
## Description

Avatar is not loading in voyager deployed in aws ec2. storage/user/default.png file is returning a 404 error.
When I checked the directory such a file doesn’t exist. Then I manually created and tested, still the 404. I think some kind of permission problem with read/write.

How can I fix the issue?

![screen shot 2019-01-25 at 10 23 48 pm](https://user-images.githubusercontent.com/42855222/51782360-eed9e800-214c-11e9-9158-f5abf58e9684.png)

**Comment by emptynick** [comment]
Please fill out the version informations, especially Voyagers.
There was a fix recently to this problem.

**Comment by jashanpj** [comment]
> Please fill out the version informations, especially Voyagers.
> There was a fix recently to this problem.

Laravel Framework 5.7.22
PHP 7.1.16 
Voyager - v1.1.11

this is what composer.json says
"require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "tcg/voyager": "^1.1"
    },

**Comment by emptynick** [comment]
That's not the whole Voyager version. It's written in the footer

**Comment by jashanpj** [comment]
> That's not the whole Voyager version. It's written in the footer

- v1.1.11

**Comment by emptynick** [comment]
Did you update from a previous version, or did you install 1.1.11 fresh?

**Comment by jashanpj** [comment]
> Did you update from a previous version, or did you install 1.1.11 fresh?

I installed fresh.

**Comment by emptynick** [comment]
Try to run `php artisan vendor:publish --tag=voyager_avatar`
But I'm a bit confused by the double-slash. Check your storage-config.

**Comment by jashanpj** [comment]
Yes the issue is fixed, 
I set the permission 775 to the root folder
then run the `php artisan vendor:publish` command.
