### ISSUE TITLE
[Question] Helm icon customization

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#392]
Any way to customize the omnipresent helm icon without changing the core package files? 

Loading pages, menu, etc all have the helm icon and it would be beneficial to let users select another icon to match their needs.

Thanks!

**Comment by marktopper** [comment]
You mean the loading image?

**Comment by victorpierredev** [comment]
@marktopper yeah, the helm itself. I know it's the voyager icon but it would be nice to allow users to set their own. Just food for thought. 

Cheers.

![helm](https://cloud.githubusercontent.com/assets/4654583/21228526/18f0818c-c2ac-11e6-931e-7339ea880db4.png)

**Comment by marktopper** [comment]
I have wrote this into my todo list. 👍 
Will keep you posted.

**Comment by victorpierredev** [comment]
I see that this has been implemented, so I'll close the issue.

Great work!
