### ISSUE TITLE
[BUG] The relationship value is not saved

### ISSUE THREAD

**Issue by bvasylchuk** [thedevdojo/voyager#3920]
## Version information

 - Laravel: v5.6.0
 - Voyager: v1.1.11
 - PHP: 7.2.8
 - Database: MySQL 5.7.21

## Description

If the field is a Relationship "Belongs To", the value selected in dropdown is not stored in the database. If this field is made ordinary (manually enter the ID in the text field), then the entered value is saved in the database.

## Steps To Reproduce
1) Create a table "Departments" with columns: id (integer), parent_id (integer, FK to id), title (varchar).
2) Go to setting BREAD for this table
3) Make the Relationship "Belongs To" for the column perent_id
Department Belongs To Departments 
Model: App\Department
Which column from Department is used to reference the Departments: parent_id
Display the Departments: title
Store the Departments: id
4) Go to the menu item and create two entries. In this case, for the second record, select first item as parent.

## Expected behavior
In the database for the second entry in the parent_id column, the ID of the first entry is saved.

## Screenshots
Table:
![image](https://user-images.githubusercontent.com/42098555/51802523-904b6180-2253-11e9-9f82-f2dc6e1a11e3.png)
Relationship:
![image](https://user-images.githubusercontent.com/42098555/51803002-75c7b700-2258-11e9-944b-6ef8deef8c6d.png)
Model:
![image](https://user-images.githubusercontent.com/42098555/51803329-7b270080-225c-11e9-8427-384cdb933b79.png)
First record:
![image](https://user-images.githubusercontent.com/42098555/51802646-d0f7aa80-2254-11e9-886d-5f27fc2b7756.png)
Adding second record:
![image](https://user-images.githubusercontent.com/42098555/51802704-4794a800-2255-11e9-9fc6-e166afd4041c.png)
After saving: 
![image](https://user-images.githubusercontent.com/42098555/51802747-90e4f780-2255-11e9-9010-747e88e7c1a0.png)

## Additional context

parent_id not saved to database. If you do not use the relationship, but simply enter the ID in the text field - the entered value will be saved. But I need a relationship to work.

In the case when it is not self-relation, but a similar relationship, but with a different table, the bug is exactly the same.

**Comment by fletch3555** [comment]
That looks like it _should_ work. I know Voyager used to have issues with self-referential relationships, but I think that got fixed.  Only thing jumping out at me is that laravel naming convention would have that BelongsTo relationship named singularly, so `department` instead of `departments`. I don't think it'll fix it, but go ahead and try just in case.

**Comment by emptynick** [comment]
Please post a screenshot of all bread settings for that table

**Comment by bvasylchuk** [comment]
> Please post a screenshot of all bread settings for that table

I realized what I did wrong. I didn't mark the Add and Edit for parent_id column. Thank you!

**Comment by trippo** [comment]
It' not very clear but on "belongs to" relations you must set the field available on edit and add as the relations field. In this case departments must have the same permission of parent_id field so edit = 1 and add =1.
