### ISSUE TITLE
[BUG] voyager lost search params when sort

### ISSUE THREAD

**Issue by shaunthegeek** [thedevdojo/voyager#3923]
## Version information

 - Laravel: v5.7.13
 - Voyager: v1.1.11
 - PHP: 7.1
 - Database: MySQL 5.7

## Description

we can search in browse index page, so URL contains query string, but when I click one column to sort, voyager will lost search params.

## Steps To Reproduce
1. run `php artisan voyager:install --with-dummy`
2. open local voyager web [/admin/posts](http://laravel-demo.localhost/admin/posts)
3. Tools->BREAD->Edit BREAD for posts table->open "
Server-side Pagination"
4. search by status=published, it's fine. URL: [/admin/posts?key=status&filter=equals&s=published](http://laravel-demo.localhost/admin/posts?key=status&filter=equals&s=published)
5. click "Created At" to sort

## Expected behavior
after sort, voyager should not lost search params.

## Screenshots

![image](https://user-images.githubusercontent.com/4971414/51954891-df280f80-247c-11e9-9df0-2c9a76077281.png)

**Comment by emptynick** [comment]
Fixed in #3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/262385658fd0709f1bcac997800f41299ed206e7
