### ISSUE TITLE
I want customize admin login page and login process

### ISSUE THREAD

**Issue by priyag597** [thedevdojo/voyager#3925]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: mariadb 

## Description

i want customise voyager admin login page how to do dat i want to add dropdown 
should i make custom or make changes in current page 
how this login page work
i added filed in view login page add 
if i want fetch data in dropdown so what to do ?? in bread i need to create relationship den ??
can i have to know in which file i had confused in flow 

## Steps To Reproduce
1. Go to 'login page'

**Comment by priyag597** [comment]
can sumbody help me out ??

**Comment by emptynick** [comment]
As stated in our issue-template, please ask questions in our Slack group.

**Comment by priyag597** [comment]
Can i have url of your slack group

**Comment by emptynick** [comment]
Its in our readme

**Comment by mohsenuss91** [comment]
@priyag597  in web.php there is something like:

`Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});`

So I guess it's a function called routes() in the     Voyager class !

**Comment by fletch3555** [comment]
@mohsenuss91, please don't comment on old closed issues.  It provides very little value as the issue was likely related to an older version
