### ISSUE TITLE
[Bug] Uploading PDFs through BREAD form corrupts file.

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#393]
- Laravel Version: 5.3.26
- Voyager Version: 0.10.2
- PHP Version: 5.6
- Database Driver & Version: mysql Ver 15.1 Distrib 10.1.19-MariaDB

### Description:

I can update PDF fine through the media manager, but if I do through a form generated by the BREAD component, the PDF gets corrupted. Images and Doc files seems to work without issues.

![voyager_failed_pdf](https://cloud.githubusercontent.com/assets/4654583/21186987/5b47ddd2-c1e4-11e6-9b75-91ee5dda2a89.png). 

### Steps To Reproduce:

- Create a table + Bread. Select one of the fields as `files`.
- Go to form, upload PDF file.
- Check file through file system or Voyager Media Manager.
- PDF does not open.

**Comment by marktopper** [comment]
Fixed in #394

**Comment by victorpierredev** [comment]
Awesome man!

**Comment by marktopper** [comment]
Will release version `v0.10.4` later today with the fix.
