### ISSUE TITLE
[BUG] Route [voyager.theme.index] not defined.

### ISSUE THREAD

**Issue by DerekBuntin** [thedevdojo/voyager#3933]
## Version information

I opened this issue at Voyager Hooks https://github.com/larapack/voyager-hooks/issues/28

Hooks Version: ^1.0
Voyager Version: 1.1.10
Laravel Version: 5.7.24
PHP Version: >=7.1.3
Description:
Themes and redirect hooks give the same error:

Route [voyager.theme.index] not defined.

Steps To Reproduce:
Try and access admin after logging in and the system gives a 500 error message.

NOTE:

Hooks Version: ^1.0
Voyager Version: 1.1
Laravel Version: 5.7.24
PHP Version: >=7.1.3

I have another project on the same local system running earlier versions of voyager and the two hook packages that work with Laravel 5.7.24.

UPDATE:

I updated the working project from Voyager 1.1 to 1.1.10 and this issue appeared.

**Comment by fletch3555** [comment]
Voyager does not provide any "theme" routes, so this is not a Voyager issue.  If that route comes from a specific hook, then you should contact the creator of that hook.
