### ISSUE TITLE
One product, multiple images

### ISSUE THREAD

**Issue by marcellopato** [thedevdojo/voyager#3935]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 5.2.21

## Description:
How can I upload multiple images to one single product? Should I use pivot table? product_id field on image table? image_id on product table?

## Additional context
I want to register a product and upload multiple images to it on the same page using Voyager. How can I do it, please?

Thankyou

**Comment by emptynick** [comment]
As the issue-template suggest, please ask questions in our Slack group.
Also, there is a `Multiple Images` formfield which you can use.
Its described in our docs.

**Comment by marcellopato** [comment]
Yeah, sure, I saw it later today.
Thanks!
