### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huhu2323** [thedevdojo/voyager#3936]
## Version information

 - Laravel: v5.7.*
 - Voyager: v1.1.*
 - PHP: 7.2
 - Database: MySQL 5.7.21

## Description

After updating a user, error occurs 

` Illegal string offset 'locale'`

in vendor\tcg\voyager\src\Models\User.php

$cast was declared
it throws an error in this line 
  `
public function getLocaleAttribute()
    {
        // $settings = json_decode($this->settings);
        return $this->settings['locale'];
    }
`

thanks

**Comment by edleman** [comment]
I changed to
$settings = json_decode($this->settings);
return $settings->locale;

**Comment by huhu2323** [comment]
Looks like App\User needs to be updated
