### ISSUE TITLE
Illegal string offset 'locale'

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#3937]
I'm Getting Error in the Below Code Block 
 /**
     * Get the value of an attribute using its mutator.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return mixed
     */
    protected function mutateAttribute($key, $value)
    {
        return $this->{'get'.Str::studly($key).'Attribute'}($value);
    }
 
    /**
     * Get the value of an attribute using its mutator for array conversion.
     *
     * @param  string  $key
     * @param  mixed  $value
     * @return mixed
     */
    protected function mutateAttributeForArray($key, $value)
    {
        $value = $this->mutateAttribute($key, $value);
 
        return $value instanceof Arrayable ? $value->toArray() : $value;
    }
![screenshot 248](https://user-images.githubusercontent.com/22276302/52393685-440ee580-2acd-11e9-8395-dfe333eb71e2.png)

**Comment by emptynick** [comment]
Please use the issue template, otherwise we are not able to help you.
This can be reopened once the required informations are updated.
