### ISSUE TITLE
[BUG] Illegal string offset 'locale'

### ISSUE THREAD

**Issue by edleman** [thedevdojo/voyager#3938]
## Version information

 - Laravel: v5.7.*
 - Voyager: v1.1.*
 - PHP: 7.2
 - Database:5.7

## Description

After updating a user, error occurs

` Illegal string offset 'locale'`

in vendor\tcg\voyager\src\Models\User.php

## Screenshots
![screenshot_15](https://user-images.githubusercontent.com/47397760/52395846-6c004800-2ad1-11e9-8d51-b83a036d7a2f.png)

**Comment by emptynick** [comment]
Please show us your user-model (`app/User.php`).
Maybe you are using casts in it which would override our casts.

**Comment by edleman** [comment]
07.02.2019, 22:22, "Christoph Schweppe" <notifications@github.com>:Please show us your user-model (app/User.php).
Maybe you are using casts in it which would override our casts.

**Comment by edleman** [comment]
![screenshot_25](https://user-images.githubusercontent.com/47397760/52716093-d9bfde80-2fbf-11e9-8849-30d99117397f.png)

**Comment by bagaskarawg** [comment]
In my case, you only need to remove the `protected $casts = ...` section of the code and it worked just like @emptynick suggested :)

**Comment by nhnajibullah** [comment]
You need add settings column to casts 
`protected $casts = [
        'email_verified_at' => 'datetime',
        'settings' => 'json'
];`

It's worked on me

**Comment by cristianmarint** [comment]
@NHNajibullah  pretty simple solution,thanks.

**Comment by cristianmarint** [comment]
@NHNajibullah pretty simple solution,thanks.

**Comment by emptynick** [comment]
Looks like you guys figured it out. Closing.

**Comment by rowild** [comment]
Total newbie here! Working through the tutes, but got stuck at this error. Can someone tell me_
- how to add the settings to casts?
- If that is at all a good idea, because it seems that it will be overwritten on the next update?
Thank you!

**Comment by emptynick** [comment]
This was taken care of in #3909 especially commit https://github.com/the-control-group/voyager/pull/3909/commits/56e72e668a7c124f69172dbac1f12ba3bdad7272
Be aware that this will force you to remove the settings-cast again when upgrading to 1.2
