### ISSUE TITLE
[SEVERE BUG] Illegal string offset 'locale'

### ISSUE THREAD

**Issue by subooom** [thedevdojo/voyager#3940]
## Version information

 - Laravel: v5.7.25
 - Voyager: v1.1
 - PHP: v7.1.3
 - MySql: 15.1 Distrib 10.1.36-MariaDB, for Win32 (AMD64)

## Description
The Bug starts occurring when trying to update the user's profile and affects every `/admin` route registered in the app.

## Steps To Reproduce
1. Setup Laravel
2. composer require tcg/voyager
3. php artisan voyager:install
4. php artisan voyager:admin xy@gmail.com --create
5. Go to profile and change profile avatar and hit save.

## Expected behavior
The avatar to change.

## Screenshots
![image](https://user-images.githubusercontent.com/18305059/52442113-77dc2080-2b4a-11e9-9fec-05eaa8f2781a.png)
![image](https://user-images.githubusercontent.com/18305059/52442163-90e4d180-2b4a-11e9-94e7-c8297382f5cc.png)

## What I have tried
`dd()` -ing `$this->settings` in the `getLocalAttribute()` function on `TCG\Voyager\Models\User.php` like 
![image](https://user-images.githubusercontent.com/18305059/52442635-c8a04900-2b4b-11e9-9ea1-113e2da9de21.png)
gives:
![image](https://user-images.githubusercontent.com/18305059/52442243-c12c7000-2b4a-11e9-92e3-a91dfa9ab855.png)
Tried to json_decode it but it still doesn't work.
You can do `dd(json_decode($this->settings)->locale)` and it gives 'en'.

**Comment by emptynick** [comment]
Please fill out the exact versions. This feature was working for month, so there might be a change in laravel

**Comment by subooom** [comment]
> Please fill out the exact versions. This feature was working for month, so there might be a change in laravel

I have updated my question.

**Comment by citrtech** [comment]
As of 3 days ago, the default `App\User` model now includes a casts array to cast the `email_verified_at` attribute. Make sure it also casts `settings` as array, as it overrides the casts array on `TCG\Voyager\Models\User`.

```php
class User extends \TCG\Voyager\Models\User
{
    protected $casts = [
        'email_verified_at' => 'datetime',
        'settings' => 'array',
    ];
}
```

**Comment by happytodev** [comment]
@citrtech's solution works, but don't forget to launch a php artisan cache:clear after this modification. Sometimes it could not work just with code modification.
