### ISSUE TITLE
How to add an external vue plugin to a custom page in Voyager ?[Feature]

### ISSUE THREAD

**Issue by hazem-taha** [thedevdojo/voyager#3945]
I checked issue #2352 but was not related.

I have a custom page in voyager admin, and need to include an external vue plugin to that page ? I've been searching for many days but did not find an answer

What I tried is:
- npm intall --save vue-fullcalendar
- included a new JS file in my .blade file with the below content
require('vue-full-calendar');
```
Object.defineProperty(Vue.prototype, '$FullCalendar', { value: FullCalendar });
Vue.use(FullCalendar)
```
- used `<full-calendar></full-calendar>` in my `.blade` file but getting the below

`[Vue warn]: Unknown custom element: <full-calendar> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by emptynick** [comment]
Please use a proper issue template. If none does suit your needs, its probably not an issue and should be asked in our Slack group.
I know you already did that, but I think you should ask in a more generic Laravel/Vue group/chat.

**Comment by hazem-taha** [comment]
I searched and asked in more than group but all asked me to get back to the package (voyager) authors.
why there is no guidelines for achieving my case ? or the current voyager version is not optimized for that ?

**Comment by fletch3555** [comment]
There's no guidelines for it because you're literally the first person to ask for it

**Comment by dredix84** [comment]
I know this has been closed for over a year, however, I have the same issue where I am trying to extend the functionality of the admin panel by adding a custom component. I was able to a copy of the compiled js and css to the public folder, however, when I load the page and click to expand the menu, I get the error.
`Uncaught TypeError: Cannot convert object to primitive value`

![image](https://user-images.githubusercontent.com/2334674/80666686-00562200-8a6b-11ea-997c-ac94655d0f71.png)

**Comment by MrCrayon** [comment]
@dredix84 it's an old issue and, as also said above, best place to ask questions is Voyager Slack chat not github.
Github issues are reserved for bug reports and feature requests.
