### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3948]
## Version information

 - Laravel: v5.7.x
 - Voyager: v1.1.x
 - PHP: 7.2
 - Database: mysql 14.14 ( Distrib 5.7.24)
## Description

Throwing exception instead of showing error for "**Integrity constraint violation**".

## Steps To Reproduce
1. Go to 'Roles'
2. Click on 'CreateRole'
3. Go to 'Users'
4. Assign the newly created role
5.Go to 'Roles'
6.Try to delete the newly created role (which was assigned to user in step 4)
## Expected behavior
Some error message I am excepting like "assigned roled cannot be deleted" (It may be a featuere as well) when tried to delete the role which was assigned to user already.

## Screenshots
![image](https://user-images.githubusercontent.com/45282852/52785518-3255b100-307e-11e9-9ac0-ca0fa1fae4fc.png)

**Comment by emptynick** [comment]
If Voyager would cover all possible exceptions, it would be a few GB in size.
Instead, create exception-handlers as you'd do in normal Laravel.
