### ISSUE TITLE
[BUG] Delete button in view page not working.

### ISSUE THREAD

**Issue by winex01** [thedevdojo/voyager#3949]
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.2.11
 - Database: MySQL 5.7.24

## Description

All delete button in view page not working

## Screenshots
![1](https://user-images.githubusercontent.com/23657442/52809441-31973c00-30cb-11e9-941e-60b45a33ed16.png)

**Comment by d3turnes** [comment]
overide view "resources\views\vendor\voyager\bread\read.blade.php" and change line 16
class="btn btn-danger" ==> class="btn btn-danger delete"

**Comment by winex01** [comment]
thanks, i tried and it worked.
