### ISSUE TITLE
Custom Relationship attribute not working on hasOne?

### ISSUE THREAD

**Issue by blitzen12** [thedevdojo/voyager#3951]
Let's say I have Orders table and Payments table,

Order.php
`/**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function payments()
    {
        return $this->hasOne('App\Model\Payment');
    }`

Payment.php
`/**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function order()
    {
        return $this->belongsTo('App\Model\Order');
    }`

I created a bread for orders table and trying to create relationship with payments but I custom attribute from payment to be displayed.

I added the ff code in Payment.php
`public $additional_attributes = ["test"];
public function getTestAttribute(){
   return "test"
}
`

When I create a relationship from Order bread I cannot see the custom attribute I added in Payment.php

Can anyone tell me if I miss something or is this a possible bug?

**Comment by emptynick** [comment]
Please use the issue template otherwise we are not able to help you.
This can be reopened once the required informations are provided
