### ISSUE TITLE
Hi, have trouble fter upload at production.

### ISSUE THREAD

**Issue by malayakvl** [thedevdojo/voyager#3954]
Create symlink at server, http://joxi.ru/YmEnR3ps0gRkV2

All uploader images showing
But when i try to upload new image i didn't receive any error and didn't upload photo.
When i open media - page show loading and now error, at consolereceive error - Server error

Try to create folder - it create but no ith original name< for example test it create folder undefined/test

Please any help

**Comment by malayakvl** [comment]
$storageItems = $storage->listWith(['mimetype'], $dir); this line give an error {
    "message": "Server Error"
}

**Comment by malayakvl** [comment]
Hi again, change file system parameters to 
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => '',
        ],
media start working, upload ok, but can not create folder in media, it send folder name /undefined/folder_name

**Comment by malayakvl** [comment]
Return error when i try to create folder via media

**Comment by emptynick** [comment]
Please use the issue template and ask questions in our Slack group.
This can be reopened once the required informations are provided.
