### ISSUE TITLE
hasOne custom attribute not showing

### ISSUE THREAD

**Issue by blitzen12** [thedevdojo/voyager#3956]
## Version information

 - Laravel: 5.7.19
 - Voyager: 1.1.11
 - PHP: 7.2
 - Database: MySql 5.7

Let's say I have Orders table and Payments table,

Order.php
`/** * @return \Illuminate\Database\Eloquent\Relations\HasOne */ 
public function payments() { return $this->hasOne('App\Model\Payment');
 }`

Payment.php
`/** * @return \Illuminate\Database\Eloquent\Relations\BelongsTo */ 
public function order() { return $this->belongsTo('App\Model\Order');
 }`

I created a bread for orders table and trying to create relationship with payments but I need to display the  custom attribute from payment.

I added the ff code in Payment.php
`public $additional_attributes = ["test"]; 
public function getTestAttribute(){ return "test" } 
`

When I create a relationship from Order bread I cannot see the custom attribute I added in Payment.php

Can anyone tell me if I miss something or is this a possible bug?

**Comment by kamilkozak** [comment]
Same issue here.  Did you deal with the problem?

**Comment by kamilkozak** [comment]
I figured it out, the custom attribute is not visible in the drop-down list in the relationship settings, but I manually entered it in the data_rows table in the details column under the label key. Now it works, but when I save BREAD, the field is overwritten and stops working again.

**Comment by MrCrayon** [comment]
Make sure you scroll down the list for me it appears as last option.
Following instructions in https://voyager-docs.devdojo.com/customization/custom-realtionship-attributes:
![Schermata da 2019-09-14 13-45-03](https://user-images.githubusercontent.com/6875243/64907735-adf00d00-d6f6-11e9-9799-20f842dd8ec8.png)

**Comment by parsa25eng** [comment]
Hi. you should delete and recreate the BREAD for Payment so as the title of additional field become visible for you.

**Comment by MrCrayon** [comment]
Please update Voyager and if you are still experiencing the problem open  another issue
