### ISSUE TITLE
[BUG] $this->role is NULL

### ISSUE THREAD

**Issue by alkhachatryan** [thedevdojo/voyager#3958]
I got an strange bug.

I have an big DB (650k+) and connected it with Voyager.

What I did:

1. Installed Voyager
2. Created admin
3. Tried to browse admin (SUCCESS)
4. Tried to browse Database (FAIL)

**I have an error in VoyagerUser Trait**
![image](https://user-images.githubusercontent.com/22774727/53011318-8e8f4b00-3459-11e9-8d65-98e20f8e4584.png)

When I dump the $this->role before IF statment - I see admin role object, it's ok. But on the next line (IF line) I get this error. Actually 2 times this functions works when I open Database page, so the first time I have an ROLE object and the second time I have NULL.

**What I did:**
I did a bad thing and added two lines of code (It's commented now)
![image](https://user-images.githubusercontent.com/22774727/53011521-fcd40d80-3459-11e9-95e4-c59839733720.png)
When I remove these lines I get an error, when I enable it - every thing is perfect.

What is the problem? How can I refactor it so I dont have to write a code in the vendor?

**Comment by alkhachatryan** [comment]
![image](https://user-images.githubusercontent.com/22774727/53011927-fe520580-345a-11e9-953d-57cd34518b54.png)

I tried to override this function in my User model, but I get the same error if I remove my code from the vendor trait. 
Any other solutions?

**Comment by emptynick** [comment]
I honestly have no idea what your problem is.
Please use the issue template so we might understand you better.

**Comment by alkhachatryan** [comment]
@emptynick 
https://github.com/the-control-group/voyager/issues/3962

**Comment by emptynick** [comment]
Then I'm going to close this one.
