### ISSUE TITLE
Doubt Display and Filter Category

### ISSUE THREAD

**Issue by alcir-junior-caju** [thedevdojo/voyager#3961]
Hello, I'm looking to display the category name and a field to filter by category posts.

I can do this via json parameters or it is necessary to override the Administrator files.

Thank you.

![screenshot from 2019-02-19 14-20-27](https://user-images.githubusercontent.com/6674417/53034473-fc377900-3451-11e9-8ed0-7634a30ad563.png)

**Comment by emptynick** [comment]
Please use the issue template and ask questions in our Slack group.
This can be reopened once the required informations are provided.
