### ISSUE TITLE
Delete button does not delete anything on view pages(crud)

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3964]
## Version information

 - Laravel: v5.7.27
 - Voyager: v1.1.11
 - PHP: 7.2.12

## Description
When installing the dummy Voyager data, I click on any post or pages, click on "view button". On the next next( the view page), I see 3 buttons:
-Edit
-Delete
-Return to list

Upon clicking on "Delete", no deletion script runs. It seems that the button is not linked to any controllers.

I do not remember having this issue in previous versions.

**Comment by emptynick** [comment]
Please search before opening issues.
Fixed yesterday in https://github.com/the-control-group/voyager/pull/3955
