### ISSUE TITLE
ST_AsText does not exist

### ISSUE THREAD

**Issue by mohd-aidi** [thedevdojo/voyager#3966]
hi, can anyone help me on this one problem.

i get this error mentioning about ST_AsText does not exist when i try to go to the pages listing that have coordinate field.

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION mydb.ST_AsText does not exist (SQL: select ST_AsText(location) AS location from `pages` where `id` = 1 limit 1) (View: mypath/resources/views/vendor/voyager/partials/coordinates-static-image.blade.php) (View: mypath/resources/views/vendor/voyager/partials/coordinates-static-image.blade.php)

## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.126
 - Database: mysql 5.5

is this because of my mysql version?

**Comment by emptynick** [comment]
Will likely be your MySQL version, yes.
5.5 was released 8 years ago (and is now EOL).
If I remember correctly, Laravel requires at least 5.6

See https://dev.mysql.com/doc/refman/5.5/en/gis-format-conversion-functions.html

**Comment by mohd-aidi** [comment]
@emptynick it would be much work if i need to upgrade my mysql. it in the server and many applications using it. btw thank you.

**Comment by emptynick** [comment]
Then the answer is dont use coordinates.
Or override/recreate the coordinates formfield to use the available methods.

**Comment by mohd-aidi** [comment]
@emptynick thank you for the suggestions.
