### ISSUE TITLE
Menu builder route parameter issue?

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#3969]
## Version information

 - Laravel: v5.7.27
 - Voyager: v1.1.11
 - PHP: 7.2
 - Database: 5.7.19

## Description
On this page:
/admin/menus/1/builder

When trying to link a page to the menu builder and add my route as:
Link type: Dynamic route
Route for the menu item: voyager.users.{user}.edit
Route parameters (if any): {"user":"users.id"}

click on "save"

I get a #(dash) in the menu builder block, it seems that my route is incorrect or not recognised.

I tried various solutions as:

Link type: Dynamic route
Route for the menu item: voyager.users.{user}.edit
Route parameters (if any): null

Link type: Dynamic route
Route for the menu item: voyager.users.{user}.edit
Route parameters (if any): {"user":"voyager.users.{user}"}

I cannot get it to create the correct url.

Could you please tell me if this is a bug or me inputting the route incorrectly?

Thank you

![1](https://user-images.githubusercontent.com/6231274/53204654-71f73c80-362c-11e9-9e11-12471702a6bb.png)
![2](https://user-images.githubusercontent.com/6231274/53204656-728fd300-362c-11e9-9aa0-30d7d52cecf7.png)

**Comment by emptynick** [comment]
There is no route named `voyager.users.{user}.edit`.
There is only `voyager.users.edit` with a parameter for the ID.
Also, please ask questions in our Slack group.

**Comment by Benoit1980** [comment]
Sorry not sure I understand, what is the slack group please? I cannot find a good forum for voyager. I tried DevDojo but it is packed with spam. thanks

**Comment by Benoit1980** [comment]
by the way I have noticed that you have no info on your website on how to pass parameters from your "Route parameters (if any)" text area to the route for menu items. It would have been great to have some kind of example. In my case, I simply want to create a new button on the left side of the admin panel for the users to access their profile(as they don't see the links top right). For this to work, the user id has to pass somehow into the url. I was hoping that I could do this easily but it is not the case. Whatever I write in the parameters break the page.

**Comment by emptynick** [comment]
Because its a Laravel feature, not Voyager.
See https://laravel.com/docs/5.7/routing#named-routes
As you wont get any dynamic variables into the JSON, why dont you create a simple route which redirects to the page you want?

**Comment by Benoit1980** [comment]
yes, the problem when you start using Voyager is that you do not know what Voyager can do to replace any functionalities in Laravel. I understand that you guys know what it does and what it does not but for us, it is difficult. You see a json field, but behind the scenes you are not 100% sure about what it does, there is so much code to analyze. Also, Would you have a url where people can get help with Voyager please? I cannot find a community in forums.

Thank you.

**Comment by fletch3555** [comment]
As already mentioned, the Slack group is the most effective means of contacting us.  There's a link to join in the project README file

**Comment by Benoit1980** [comment]
Oh I see!!!! I now understand what you mean by slack...I just could not understand what you meant. I typed slack forum and went on so many other websites. Thanks I have just registered.
