### ISSUE TITLE
Cannot upload files using image library

### ISSUE THREAD

**Issue by cadmicro** [thedevdojo/voyager#397]
- Laravel Version: 5.3
- Voyager Version: v0.10.3
- PHP Version: 5.6
- Database Driver & Version:

### Description:

I just cannot upload files/folders locally using the Media page on the admin panel...

When I add a folder, I cannot find the folder locally on the FTP. 

The images that are currently in media are located in ./storage/posts and /pages and /users...
So, when I create a folder it should be creating a folder in my ./storage/ folder right?

And when I upload an image into an existing folder like /posts/ the file is not uploaded to the server, and the resource is missing on the media library page, so the image appears like:

![screencapture-cmswebapp-azurewebsites-net-admin-media-1481737528842](https://cloud.githubusercontent.com/assets/24463380/21193723/3e83f5fc-c1fb-11e6-87c3-350423ba3610.png)

And the file is NOT uploaded on the FTP server...

I checked the config/voyager.php for:

    'storage' => [
        'subfolder' =>'public/', // include trailing slash, like 'my_folder/'
    ],

So, it should be uploading to the public folder in /storage but it is not???

This is just not making sense, please someone help me out here.

**Comment by marktopper** [comment]
Does this happens for both images and text files?

**Comment by cadmicro** [comment]
Hello,

Yes, this happens for both images and text files. I just tested uploading a text file, and when I try to view it, it shows 404 not found page.

![screencapture-cmswebapp-azurewebsites-net-admin-media-1481738352012](https://cloud.githubusercontent.com/assets/24463380/21194242/35f57d50-c1fd-11e6-9028-2054e9722511.png)

The url generated is:  {website.com}/storage/posts/1c52bdae8bad70e82da799843bb4e831.txt
(I just substituted my website URL)

This file does not exist in my ./storage/posts/ folder.

**Comment by marktopper** [comment]
Okay just a few things:

1. Does the `public/storage` folder exists?
2. Does the text and/or image files actually exists in `storage/public/posts`?

**Comment by cadmicro** [comment]
1. Yes the public/storage folder exists, and so does storage/public/ 
2. Well the original image files that come preinstalled with the package exist in the storage/posts/ - but not in storage/public/posts does not exist.

**Comment by marktopper** [comment]
I meant `/storage/app/public/posts`, can you check that path for your files, and see if you can find the file `1c52bdae8bad70e82da799843bb4e831.txt`?

**Comment by cadmicro** [comment]
Hey Mark.

Yes, why is this file structure so overly complicated.... I think this information should be more clear on your documentation.

Yes the files are appearing in my /storage/app/public/posts

However the links being generated in the admin panel are incorrect and cannot be previewed in the admin panel...

The links being  generated for example are:
{website.com}/storage/posts/1c52bdae8bad70e82da799843bb4e831.txt

When the links should be:
{website.com}/storage/app/public/posts/1c52bdae8bad70e82da799843bb4e831.txt

How do I fix this issue?

**Comment by marktopper** [comment]
It's following the stanards for Laravel.

About your issue, if you can access `{website.com}/storage/app/public/posts/1c52bdae8bad70e82da799843bb4e831.txt` from the browser, you should be able to access `{website.com}/public/storage/posts/1c52bdae8bad70e82da799843bb4e831.txt` as well.

And if this is the case, you might want to change the settings of your domain to use `{website.com}/public` as the domain root folder.

This will fix your issue, and is not really a issue with the package, but with your setup.

If you need more help fixing this, please let me know what operation system you use on your server hosting the site.

Also I would recommend the videos about getting started with Laravel by Laracasts.
Link: https://laracasts.com/series/laravel-5-from-scratch

Hope you get your issue fixed.

**Comment by cadmicro** [comment]
Hey Mark,

Okay I understand.

I would appreciate some help getting this fixed.

I am running on the Microsoft Azure hosting for my website. 

In the normal laravel setup the /public folder holds all of the files, however I initially modified my setup and moved all of the files out of the public folder so it is empty and unused at the moment.

![image](https://cloud.githubusercontent.com/assets/24463380/21229294/2375ea0e-c2af-11e6-82a1-5613a746f628.png)

I followed that by modifying my bootstrap autoload.php and app.php locations out of the /public folder into the following, by modifying my index.php file.

require __DIR__.'/bootstrap/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';

**Comment by marktopper** [comment]
You must setup your domain to use the `public` folder as the domain-root instead of `wwwroot` (which might be the default if I'm not wrong).

For fully understanding of running Laravel on Microsoft Azure I have found those guides:
- http://blog.qbotx.com/basic-laravel-5-on-microsoft-azure-part-1/
- http://blog.qbotx.com/laravel-5-on-azure-part-2/
- http://blog.qbotx.com/laravel-5-on-azure-part-3/

The important one for your case it in [part 1](http://blog.qbotx.com/basic-laravel-5-on-microsoft-azure-part-1/) (the `Public Directory` section)

Hope this helps out.

**Comment by Jaquedeveloper** [comment]
In my case I have a subfolder in my website and the files are not being uploaded. To enter the system one should go to www.mywebsite.com/system/admin. 

I've started the development locally, no issues. But once I uploaded it to the server and try to upload files, it goes wrong. Even to show the files that were uploaded locally it fails. There's no app folder, the configuration in the voyager.php file storage setting is to 'public'. If I change it to public_html/system/, it stops showing the files I've uploaded while in localhost... it doesn't even shows a url... 

I've created public folder under public_html and also in my root folder, no success... I do also have a storage folder under system, which is where my local uploads are. I do also have another folder, storage, under public_html, but no files are being uploaded to there. If I upload a file, it looks for 

http://www.mywebsite.com/storage/services/December2016/KJTl0xfFa7Rnec5QLuii.jpg, for example, where servicos is a table I've created via admin panel... but the file is not being uploaded to this location. I can't find the file... I've adjusted the permissions but still can't find it.
Also, for the older files, which I've uploaded locally, if I type:

http://www.rituaisdoego.pt/system/storage/ 

I can find them, under each model folder... but the new files are not being uploaded to there or anywhere. How can I fix this?

**Comment by rocichy** [comment]
The same problem I have on my hosting
I solved this problem:

-Redirect the domain to the main directory 

.htaccess

```
<IfModule mod_rewrite.c>
   RewriteEngine On 
   # enable symbolic links
   Options +FollowSymLinks
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteCond %{REQUEST_FILENAME} !-l
   RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```
Next
Create file /public/symlink.php
```
<?php
$target = '../storage/app/public';
$link = 'storage';
symlink($target, $link);
?>
```
Call this file
domian.com/symlink.php
I can not access the console :(

I have not tested it yet but the images are working :)

**Comment by imzo15** [comment]
I had the same problem, I was able to work fine with file uploads locally but I wasnt able to see the files on my server, had to modify .env.
From
APP_URL=http://localhost:8000
To
APP_URL=http://mydomain.com
Hope this helps someone, since I was struggling with this for more than 2 days until I came to realize the solution.

**Comment by cardinalwebma** [comment]
ln -s /path/to/laravel/storage/app/public /path/to/public/storage

**Comment by cardinalwebma** [comment]
php artisan storage:link
