### ISSUE TITLE
Multilinugal translations not working

### ISSUE THREAD

**Issue by abdulwahid** [thedevdojo/voyager#3971]
## Version information

 - Laravel: v5.6.39
 - Voyager: v1.1.11
 - PHP: 7.2
 - Database: mysql  Ver 14.14 Distrib 5.7.24,

## Description

I want to use Multilanguage feature. I followed exact steps mentioned in documentation here https://docs.laravelvoyager.com/core-concepts/multilanguage

But it doesn't provide translations in result set.

I have a table named **practice_areas**
Here is the model **PracticeArea**: 

```
namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Translatable;

class PracticeArea extends Model
{
    use Translatable;

    protected $translatable = ['name', 'description', 'slug'];

    protected $table = 'practice_areas';

    protected $guarded = ['id'];
}
```

The configurations in **config/voyager.php**:
```
    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Set whether or not the admin layout default is RTL.
         */
        'rtl' => false,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'es',
        ],
    ],
```

Here is the translations table:
![translations-table](https://user-images.githubusercontent.com/4362643/53298061-caefec00-3849-11e9-9baa-cee7d7b8d478.png)

And it contains the translations for **Practice Area** id **1**.
![translation-records](https://user-images.githubusercontent.com/4362643/53298064-d2af9080-3849-11e9-9231-8758bfc8c1ba.png)

But when i try to fetch **Practice Areas** with **Translations**, it doesn't provide **translations** in result set.
![dd-result](https://user-images.githubusercontent.com/4362643/53298065-d5aa8100-3849-11e9-82f6-05bedc76bbc1.png)

Am i missing something or doing something wrong. Some help will be much appreciated.

**Comment by emptynick** [comment]
Please show us the code you use to get the results

**Comment by abdulwahid** [comment]
@emptynick Here is the code 

```
$practiceAreas = PracticeArea::with('translations')->get();
dd($practiceAreas);
```

**Comment by emptynick** [comment]
That's only one part on how to get translations.
It's all mentioned in the docs

**Comment by abdulwahid** [comment]
@emptynick I have tried other methods as well, but no luck. All provides empty result set in translations relation.

**Comment by emptynick** [comment]
What are "other methods"?

**Comment by nathan-io** [comment]
emptynick, not sure why it would matter if and how he tried to get translations, if the below returns an empty result set:

```
$practiceAreas = PracticeArea::with('translations')->get();
dd($practiceAreas);
```

Never the less, in our case, the issue was in our db. 

We use snake case for MySQL table names, but the values in `table_name` column used _-_ rather than ___.

I only caught this after reviewing the `translations` table contents after seeing the details from OP's post and getting an empty `translations` result set myself using Tinker. 

After I changed the values in `translations.table_name`, all of our translated values started coming through.

**Comment by nathan-io** [comment]
emptynick, not sure why it would matter if and how else he tried to get translations, if the below returns an empty result set:

```
$practiceAreas = PracticeArea::with('translations')->get();
dd($practiceAreas);
```

Never the less, in our case, the issue was in our db. 

We use snake case for MySQL table names, but the values in `table_name` column used - rather than _.

I only caught this after reviewing the `translations` table contents subsequent to reproducing the empty result set described by the OP over a Tinker session on another instance of the same project. 

After I changed the values in `translations.table_name`, all of our translated values started coming through.

Leaving this comment for the benefit of anyone who does this in the future, it can be an easy mistake to make. This bug wasn't OP's fault either, this is from the original developer.

**Comment by emptynick** [comment]
Well, true, didn't notice that the tables are different.
Odd, but its fetched through `$model->getTable()` here:
https://github.com/the-control-group/voyager/blob/dcffeb6f10b93bfc383851ea4ca2b48381b3f04b/src/Translator.php#L74
Probably needs some more digging.

**Comment by nathan-io** [comment]
> its fetched through `$model->getTable()`

Sorry, are you saying that it _should_ have taken the correct value "practice_areas" as table name, since that's the `$table` value defined in our `PracticeAreas` model, rather than the actual value of  the `translations.table_name` table columns?

Were the hyphenated/incorrect table name values in `translations.table_name` derived and filled by Voyager, or are those values populated using a Voyager user's input? 

If the former, there could be an issue with the way Voyager is determine table names when populating this field.

**Comment by emptynick** [comment]
`$model->getTable()` is a Laravel function.
And the call I mentioned above is how it is written to the database.

If I get some proper steps to reproduce I could dig some deeper.

**Comment by 109digital** [comment]
Seems all that would be necessary to reproduce is to create a class:

```
class SomeModel extends Model
{
    use Translatable;

    protected $translatable = ['somefield'];

    protected $table = 'some_model';
}
```

Then add some values to the `translations` table, and see if the saved value in `translations.table_name` is "some_model" or "some-model".

**Comment by nathan-io** [comment]
Seems all that would be necessary to reproduce is to create a class:

```
class SomeModel extends Model
{
    use Translatable;

    protected $translatable = ['somefield'];

    protected $table = 'some_model';
}
```

Then add some records to the `translations` table, and see if the saved value in `translations.table_name` is "some_model" or "some-model".

**Comment by emptynick** [comment]
Tested. It saves `some_model`

Are the translations seeded or manually created?

**Comment by nathan-io** [comment]
They were not seeded. Not sure if they were created through Voyager UI, or via phpMyAdmin (this was several months ago, and that dev is unavailable).

I searched the codebase and the entire db for "practice-areas", and found nothing related to the model. Everything looks in order.

I also checked history of our `App\PracticeArea.php` and confirmed that `protected $table = 'practice_areas'` in all versions.

Just looks like a typo during manual record creation. Will keep an eye out as we add more translations this week, to ensure that it continues storing the correct value in `table_name`.

**Comment by abdulwahid** [comment]
I created the records from Admin Panel, it stored them with hyphen "-" instead of under score "_". 
Not sure why.

@emptynick Any possible reason why it would store records with `-` instead of `_` in `translations.table_name`.

**Comment by emptynick** [comment]
Absolutely no. Can you still reproduce it or is it saving properly now?

**Comment by abdulwahid** [comment]
Yes, i have just reproduced it again. We have an entity `PracticeAreaCategory`, the table name mentioned in Model is `protected $table = 'practice_area_categories';` 

From Admin Panel, on route `admin/bread/practice_area_categories/edit`, i can see the value of `Table Name` field is set to `practice_area_categories`. But when i created new Practice Area Categories, it stored data in  `translations.table_name` table as `practice-area-categories`.

**Comment by nathan-io** [comment]
He's absolutely right, I got the same result when I used the edit-add UI to create a new `PracticeAreaCategory`. It has two translatable attributes, and I provided a value for both.

Here are the `translations` records created: 
![3f4890973703b083dbcf3e53ba360c16](https://user-images.githubusercontent.com/25315716/53390982-f7e3f200-3962-11e9-8c1d-f501d4b8694a.png)

The behavior is the same when creating a new `PostCategory`. I haven't tried other models.

I do see in `/src/Translator.php`:

```
        $translation->fill([
            'table_name'  => $this->model->getTable(),
           ....
```
and then in Laravel's `Model.php`:

```
    public function getTable()
    {
        if (! isset($this->table)) {
            return str_replace(
                '\\', '', Str::snake(Str::plural(class_basename($this)))
            );
        }

        return $this->table;
    }
```

The only thing I noticed is that `Str::snake` doesn't convert - to _, so if for some reason the return value of `Str::plural` is hyphenated, it will be stored that way. 

Example simulating the operation of `Str::snake`:

```
$delimiter = "_";
$str = strtolower(preg_replace('/(.)(?=[A-Z])/u', '$1'.$delimiter, "practice-area-categories"));
echo $str;  // Result: practice-area-categories
```

Surely there's some misconfiguration in our application, though everything does seem to be in order. 

Any idea where could we look next?

**Comment by emptynick** [comment]
That replacement only kicks-in if `this->table` isn't set, but it is.
Can you set some `debug()` (with debugbar) lines into the translator and see what happens at which point?
I'm really not able to reproduce it in any way.

**Comment by nathan-io** [comment]
Thanks, I will try that if this is not the issue:

We have a custom `VoyagerBaseClass.php`. In it, I found:

```
$dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();
   ...
$table_name = $dataType->slug;
  ...
            foreach ($request->input('translations', []) as $column_name => $item) {
                if($item != null){
                    Translation::updateOrCreate(
                        [
                            'table_name' => $table_name,
                            'column_name' => $column_name,
                            'foreign_key' => $data->id,
                        ],
```

That seems ... not right.

**Comment by nathan-io** [comment]
Solved by changing `$dataType->slug` to `$dataType->name` in our custom `VoyagerBaseController.php`.

```
>>> $dataType = Voyager::model('DataType')->where('slug', '=', "practice-area-categories")->first();
=> TCG\Voyager\Models\DataType {#3272
     id: 9,
     name: "practice_area_categories",
     slug: "practice-area-categories",
     display_name_singular: "Practice Area Category",
     display_name_plural: "Practice Area Categories",
...
```

Thank you.

**Comment by fletch3555** [comment]
Glad to see you figured it out @nathan-io.  Good find

**Comment by futureeducationbr** [comment]
I have the issue here. My translation didn't work. 

    $posts = Post::join('categories', function ($join) {
            $join->on('categories.id', '=', 'posts.category_id');
        })->where('categories.parent_id','2')->withTranslations()->get(['posts.created_at','posts.slug','posts.title','categories.name']);

**Comment by fletch3555** [comment]
Please don't comment on closed issues, especially after over a year. Just open a new issue
