### ISSUE TITLE
[Feature] Tags input

### ISSUE THREAD

**Issue by osc2nuke** [thedevdojo/voyager#3972]
## Version information
* Laravel: 5.7
* Voyager: latest version
* PHP: 7.1.2
* Database: MySQL 5.1

Tags input BREAD form-field like:
Bootstrap Tags plugin

https://youtu.be/-Fjl7Yp3jfs

**Comment by emptynick** [comment]
Same as in your other issues: please use the issue-template.
This can be reopened once the required informations are provided.
