### ISSUE TITLE
[BUG] Nested menu with link in parent doesn't work

### ISSUE THREAD

**Issue by wvffle** [thedevdojo/voyager#3973]
## Version information

 - Laravel: v5.7.26
 - Voyager: v1.1.11
 - PHP: 7.3.2
 - Database: MariaDB 10.3.12

## Description

With this structure the `Users` menu works only as a category.
![image](https://user-images.githubusercontent.com/13330620/53395342-e241ed00-39a1-11e9-8e9b-b73404c4d60d.png)

## Steps To Reproduce
1. Move any menu entry into `Users` entry
2. Go to dashboard
3. Try to open user list

## Expected behavior
When clicked on the name of the category it should open user list and when near the arrow, it should only expand user category

**Comment by emptynick** [comment]
Thats how bootstrap dropdowns work.
I think that's a `wontfix`.

**Comment by fletch3555** [comment]
Agreed with @emptynick.  There's not much we can do about this one.
