### ISSUE TITLE
[Feature] Remember Me

### ISSUE THREAD

**Issue by CupOfTea696** [thedevdojo/voyager#3976]
Could a remember me checkbox be added to the login page? Or, optionally, a setting in voyager's config to enable the remember me checkbox that's disabled by default?

**Comment by scrlkx** [comment]
A checkbox to remember me is interesting to me as well. Can we implement?

**Comment by emptynick** [comment]
I guess we only need the checkbox itself. Code is already implemented:
https://github.com/the-control-group/voyager/blob/51e9ea7e3e19c73f29414dcddc90337f302bab04/src/Http/Controllers/VoyagerAuthController.php#L38
