### ISSUE TITLE
[BUG] Uploading stops in Media manager

### ISSUE THREAD

**Issue by mhmelshaaer** [thedevdojo/voyager#3978]
## Version information

 - Environment: Production
 - Laravel: v5.5.*
 - Voyager: v1.1
 - PHP: 7.2
 - Database: 5.6.43 - MySQL Community Server (GPL)
  - post_max_file_size =40 MB
 - upload_max_file_size = 40 MB
 - memory_limit = -1

## Description

Any file uploading that is greater than approximately 1.7MB, the uploading stops after that, giving no errors in the browser console. How do I know that it stops uploading? using network speed watcher. However, file and image uploading works fine anywhere else, whether in the admin panel or in the main website. Also, it's working fine on my local machine(Ubuntu 16.04 - php 7.2 - MySQL-5.7.25-0ubuntu0.16.04.2).

## Steps To Reproduce
1. Go to 'Media manager'
2. Click on 'Upload'
3. Select any file (ex: image), with size greater than 1.9.
4. You will see the uploading green bar starts growing till it suddenly stops.

## Screenshots
![laravel-voyager](https://user-images.githubusercontent.com/25831762/53677684-b8980700-3cbc-11e9-8815-f64958cb6b0c.png)

**Comment by emptynick** [comment]
What are your php.inis `upload_max_file_size` and `post_max_size`?

**Comment by mhmelshaaer** [comment]
I've updated the version info section with those variables, would you check. I would remind you that uploading is working anywhere else and also no errors is thrown.

**Comment by emptynick** [comment]
You have any errors in your browser-console?

**Comment by mhmelshaaer** [comment]
No errors no warnings.

**Comment by mhmelshaaer** [comment]
@emptynick any help !?

**Comment by emptynick** [comment]
Not really. Anything in your logs? Either laravels or phps?

**Comment by mhmelshaaer** [comment]
Nothing

**Comment by emptynick** [comment]
Then I honestly have no idea how I could help you

**Comment by emptynick** [comment]
Did you try with v1.2?

**Comment by mhmelshaaer** [comment]
No, I will try this.

**Comment by tnylea** [comment]
@MouhammedElshaaer Any update on this? Were you able to solve it?

Additionally, are you using local storage or are you using s3 storage?

**Comment by mhmelshaaer** [comment]
Nothing really, cause we are working on v1.1. Since we are in staging, I just can't upgrade now. Also, the issue is not reproduced locally so, I have to wait for now, but I will update here any changes when upgrading. 
For the storage part, I'm using local storage.

**Comment by fletch3555** [comment]
I seriously doubt this is related to Voyager in any way.  Most likely it's a configuration issue with your server (php and/or webserver).  This answer should help shed some light on why @emptynick asked about those php.ini values before: https://stackoverflow.com/a/578226

**Comment by mhmelshaaer** [comment]
If it's an issue with the server configurations, there would be an issue in the uploading generally, which is not the case, as I mentioned in the description,

> However, file and image uploading works fine anywhere else, whether in the admin panel or in the main website.
