### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aamirkhan37557** [thedevdojo/voyager#3981]
I am using laravel 5.8 and installed laravel voyager package on it.
i created database table and name Products and then i add it to the bread  and it is also shown in the sidebar menu but when i clicked on it it give me an error an authorized action although i assign priviliges from roles to bread it 
![screenshot-localhost-2019 03 03-21-27-44](https://user-images.githubusercontent.com/24594319/53712348-5691eb80-3dfb-11e9-8adc-57cb3c4f7efe.png)
![screenshot-localhost-2019 03 03-21-27-44](https://user-images.githubusercontent.com/24594319/53712359-60b3ea00-3dfb-11e9-9535-974f0b53921f.png)

**Comment by emptynick** [comment]
PLease use the issue template, otherwise we can't help you.
This can be reopened once the required informations are provided.
