### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by developr007** [thedevdojo/voyager#3982]
$ php artisan voyager:install --with-dummy

Publishing the Voyager assets, database, and config files

Copied Directory [\vendor\tcg\voyager\publishable\assets] To [\public\vendor\tcg

\voyager\assets]

Copied Directory [\vendor\tcg\voyager\publishable\database\seeds] To [\database\

seeds]

Publishing complete.

Publishing complete.

Migrating the database tables into your application

Migration table created successfully.

Migrating: 2014_10_12_000000_create_users_table

Migrated:  2014_10_12_000000_create_users_table

Migrating: 2014_10_12_100000_create_password_resets_table

Migrated:  2014_10_12_100000_create_password_resets_table

Migrating: 2016_01_01_000000_add_voyager_user_fields

Migrated:  2016_01_01_000000_add_voyager_user_fields

Migrating: 2016_01_01_000000_create_data_types_table

Migrated:  2016_01_01_000000_create_data_types_table

Migrating: 2016_05_19_173453_create_menu_table

Migrated:  2016_05_19_173453_create_menu_table

Migrating: 2016_10_21_190000_create_roles_table

Migrated:  2016_10_21_190000_create_roles_table

Migrating: 2016_10_21_190000_create_settings_table

Migrated:  2016_10_21_190000_create_settings_table

Migrating: 2016_11_30_135954_create_permission_table

Migrated:  2016_11_30_135954_create_permission_table

Migrating: 2016_11_30_141208_create_permission_role_table

Migrated:  2016_11_30_141208_create_permission_role_table

Migrating: 2016_12_26_201236_data_types__add__server_side

Migrated:  2016_12_26_201236_data_types__add__server_side

Migrating: 2017_01_13_000000_add_route_to_menu_items_table

Migrated:  2017_01_13_000000_add_route_to_menu_items_table

Migrating: 2017_01_14_005015_create_translations_table

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access

violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL:

alter table `translations` add unique `translations_table_name_column_name_forei

gn_key_locale_unique`(`table_name`, `column_name`, `foreign_key`, `locale`))

  at C:\wamp64\www\guardstores\vendor\laravel\framework\src\Illuminate\Database\

Connection.php:664

    660|         // If an exception occurs when attempting to run a query, we'll

format the error

    661|         // message to include the bindings with SQL, which will make th

is exception a

    662|         // lot more helpful to the developer instead of just the databa

se's errors.

    663|         catch (Exception $e) {

  > 664|             throw new QueryException(

    665|                 $query, $this->prepareBindings($bindings), $e

    666|             );

    667|         }

    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or acce

ss violation: 1071 Specified key was too long; max key length is 1000 bytes")

      C:\wamp64\www\guardstores\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PD

OStatement.php:119

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Sp

ecified key was too long; max key length is 1000 bytes")

      C:\wamp64\www\guardstores\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PD

OStatement.php:117

  Please use the argument -v to see more details.

**Comment by emptynick** [comment]
Please use the issue-template and search before opening new issues.
Closing as a duplicate.

**Comment by developr007** [comment]
I searched but i did n't get any solution.I have also tried adding Schema::defaultStringLength(191); to AppServiceProvider::boot(), which did not correct the issue.

please help

**Comment by emptynick** [comment]
https://github.com/the-control-group/voyager/issues?q=is%3Aissue+Specified+key+was+too+long%3B+max+key+length+is+1000+bytes+is%3Aclosed
Also, you issue is different (1000 bytes against 767 bytes).
And without the version informations and the issue template, we can't help you.
