### ISSUE TITLE
[BUG] overriding VoyagerBreadController

### ISSUE THREAD

**Issue by steveadamsfixedit** [thedevdojo/voyager#3986]
- Laravel: v5.7.28
 - Voyager: 1.x-dev 6e0e556
 - PHP: 7.2.13
 - Database: MySQL 8.0.12 for osx10.13 on x86_64

## Description
I'm attempting to override the VoyagerBreadController and receiving " ReflectionException (-1)
Class app\Http\Controllers\Voyager\ProductsController does not exist" error.

## Steps To Reproduce
1. I copied vendor/tcg/voyager/src/Http/Controllers/VoyagerBreadController.php to app/Http/Controllers/Voyager/ProductsController.php
2. changed the namespage in app/Http/Controllers/Voyager/ProductsController.php to "namespace App\Http\Controllers\Voyager;" and the class declaration to "class ProductsController extends \TCG\Voyager\Http\Controllers\VoyagerBaseController"
3. ran 'php artisan config:cache" and 'php artisan serve'
4. edited the BREAD for the products table and added in the controller as \app\Http\Controllers\Voyager\ProductsController, saved the changes
5. Visited http://localhost:8000/admin/products and received the "Class app\Http\Controllers\Voyager\ProductsController does not exist" error.

## Expected behavior
I expected to see the app/Http/Controllers/Voyager/ProductsController.php loaded and functional

My products controller:
namespace App\Http\Controllers\Voyager;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use TCG\Voyager\Database\Schema\SchemaManager;
use TCG\Voyager\Events\BreadDataAdded;
use TCG\Voyager\Events\BreadDataDeleted;
use TCG\Voyager\Events\BreadDataRestored;
use TCG\Voyager\Events\BreadDataUpdated;
use TCG\Voyager\Events\BreadImagesDeleted;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;

class ProductsController extends VoyagerBaseController
{

**Comment by RapSherlock** [comment]
do you want to custom some bread controller or overriding voyager controller ?

**Comment by rioaguspermana** [comment]
4. edited the BREAD for the products table and added in the controller as \app\Http\Controllers\Voyager\ProductsController, saved the changes.

try to remove "\\" in "\app"

**Comment by emptynick** [comment]
Leading `\` shouldn't matter. It is necessary and will be added if it isn't there.
Try running `composer dump-autoload` and try again.
Also I'm not 100% sure, but your namespace is `App\...` and you tell Voyager to use `app\...`

**Comment by rioaguspermana** [comment]
i'm already try it and it was causing from the '\\'
![image](https://user-images.githubusercontent.com/22311760/53865353-8de1e180-4021-11e9-999b-8b170fbce3b3.png)

**Comment by emptynick** [comment]
Keep in mind he is using 1.2 right now.
It changed so that a leading `\` is automatically added if it isn't there already.

**Comment by rioaguspermana** [comment]
sorry for misleading, its correct the error is causing from the `app\...`.
i'm already test it with the same version.

**Comment by steveadamsfixedit** [comment]
Thank you all for the input. From your contributions I was able to diagnose and resolve the issue. It is accurate that the \ preceding App in the Controller declaration of the edit BREAD page does not matter. It works either way, with or without.

 I did have to capitalize the "A" in App to match the namespace in the controller...AND declare the class in the actual controller with an include of the original voyager controller as follows:

use TCG\Voyager\Http\Controllers\VoyagerBreadController;

class ProductsController extends VoyagerBreadController
{

As a side note of interest and an area siting the lack of documentation between Voyager version 1.1 and 1.2, I would like to make a note...the VoyagerBaseController is the actual controller I was trying to override and not the VoyagerBreadController

**Comment by emptynick** [comment]
https://docs.laravelvoyager.com/customization/overriding-files#using-custom-controllers
It's the same for both versions.

**Comment by steveadamsfixedit** [comment]
@emptynick 
I wasn't talking about the general docs on overriding the Voyager controllers, I was specifically talking about how the structure of the Base and Bread controllers changed with version 1.1  -- as noted here:
https://stackoverflow.com/questions/48743770/how-to-create-custom-controller-in-laravel-voyager
