### ISSUE TITLE
Move voyager models and actions arrays to config file 

### ISSUE THREAD

**Issue by progamer** [thedevdojo/voyager#3990]
## Description of problem

Keeping the definition of these models inside Voyger class will make it hard for developers to overided their functionlity. 
## Proposed solution
I suggest moving these models and actions arrays to a config file, so overriding them become much easier also, I found that you implement "addAction", "replaceAction" functions I think  "removeAction" function is a need .

**Comment by emptynick** [comment]
Configs are hard to maintain and have a lot more disadvantages.
Models are overridable as per our docs and to remove an action, why dont you just ungrant/delete the corresponding permission?

**Comment by c4b60fd4** [comment]
good!

**Comment by progamer** [comment]
I had a use case where I need to apply Model Cache for Menu Model
I think having models in the config file will give developers a way to apply such think

**Comment by emptynick** [comment]
If you change the model through a config file or through the UI doesn't make any difference technically.
Its more inconvenient actually.

**Comment by emptynick** [comment]
Closing.
