### ISSUE TITLE
[BUG] Trying to get property of non-object telescope in voyager

### ISSUE THREAD

**Issue by prakhargvp** [thedevdojo/voyager#3991]
## Version information

 - Laravel: v5.7.21
 - Voyager: v1.1
 - PHP: 7.1.3
- Telescope: 2.0
## Description

When setting up environment from local to production it's showing error.

## Screenshots
![Screenshot from 2019-03-09 07-41-26](https://user-images.githubusercontent.com/7056772/54064863-d2969400-423e-11e9-824f-8614928ac12d.png)

**Comment by emptynick** [comment]
Why do you use telescope inside voyager/admin route group?
I don't really wonder that this is failing.

**Comment by prakhargvp** [comment]
I don't do anything i just install telescope as per the instruction given at laravel docs and its working fine in local environment but when i change environment from local to productions its showing error.

**Comment by emptynick** [comment]
Nonetheless this looks very similar to https://github.com/the-control-group/voyager/issues/3868

**Comment by gkmk** [comment]
**\TCG\Voyager\Models\User** **breaks the Laravel Gates**
Permissions from Voyager try to load them from their database definitions which overwrites the Gate check from Laravel.
Just got the same thing with Laravel Horizon

**Comment by gkmk** [comment]
Ok so looks like Policies are prioritized over Gates and Voyager registers User model policy. This causes for Voyager permissions to be checked instead of checking for actual Gate.
Easiest fix is to create your own user policy `php artisan make:policy -m User UserPolicy`
Inside the UserPolicy add your permission name function or in my case 
`public function viewHorizon(User $user)`

**Comment by spkm** [comment]
@gkmk thanks that did the trick for telescope too!

**Comment by winex01** [comment]
@gkmk thanks this works for me.

**Comment by CharlieEtienne** [comment]
@gkmk Should I copy and paste Voyager's UserPolicy methods in it ? And should I overwrite defaut value in User BREAD with `App\Policies\UserPolicy` as well ? Will I loose user permissions ?

**Comment by fletch3555** [comment]
@CharlieEtienne just extend the Voyager UserPolicy class and add the method
