### ISSUE TITLE
[BUG] menu dropdown not working properly on firefox ESR 52.8

### ISSUE THREAD

**Issue by Fenweldryn** [thedevdojo/voyager#3995]
## Version information
 - Laravel: v5.7
 - Voyager: v1.2
 - PHP: 7.3.1
 - Database: MySQL 10.1.37
 - Firefox ESR 52.8

## Description

Sometimes clicking on a menu dropdown does nothing and console throws "ReferenceError: event is not defined app.js:1:597237"

## Steps To Reproduce
1. Go to admin dashboard main page
2. Click on tools while its closed (opens the menu, works)
3. Click on tools again to close menu (does nothing, throws error)
4. Click on tools again (still does nothing, throws error)
5. Refresh page and click again (works)

## Expected behavior
Dropdown to open and close.

## Additional context
Might be a compatibility issue with my old version of firefox while trying to close a menu that is open. I can't update it because I'm bound to company browser updates and this is the lastest available version of firefox here. Managed to install chrome 72 and it works just fine there. I can't count on it because the users have only firefox preinstalled.

**Comment by emptynick** [comment]
This has already been fixed in https://github.com/the-control-group/voyager/pull/3992

**Comment by Fenweldryn** [comment]
awesome!
how to I get it? I recently updated from 1.1 to 1.2 but I did not get the hotfix. Do I have to wait for another update?

**Comment by Fenweldryn** [comment]
nevermind, it was a simple edit, managed to get it working now! Thanks!

**Comment by janainadcacaca** [comment]
Pass your solution if you want, because we have the same problem!

**Comment by Fenweldryn** [comment]
I just followed the mentioned issue and checked whta was the modification they made. 
They simply changed "event" to "e" in line 125 of file resources/assets/js/app.js.
For this temporary fix make sure to change the app.js on publishable/assets/js/app.js

https://github.com/the-control-group/voyager/pull/3992/files

**Comment by emptynick** [comment]
Released in 1.2.2. Just update and clear your browser-cache.
