### ISSUE TITLE
[BUG]Code editor field is not translatable

### ISSUE THREAD

**Issue by OscarFCN** [thedevdojo/voyager#3996]
Hi, I'v realized that if you have a code editor field, this is not translatable. 

I have a case in which could be insteresting getting it translatable. I have a client that needs to put a different form in every post that they get from other platform. So I decided to create this field as code editor in the admin because they copy the entire code of the form and paste it in to the post admin.

What do you think?

**Comment by emptynick** [comment]
From the issue-template.
> The following information is required for bug reports.  Issues without it will be closed without response 

This can be reopened once the required informations are provided.
