### ISSUE TITLE
[Question] - Website does not working if don't use "php artisan serve" command ?

### ISSUE THREAD

**Issue by garungabc** [thedevdojo/voyager#3997]
> Website is not working if don't use ```php artisan serve``` command ?
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2

## Description:
After install Voyager success, I have run ```php artisan serve```, I access to http://mydomain.local:8000/admin/login, all is ok. But if don't use ```php artisan serve```, website return a error message is "Failed to load resource (404 not found) " 2 files app.js (admin/assets/js/app.js) and app.css (admin/assets/jcss/app.css). So, where is this issues, router or anything else ? 

## Additional context
I also find some solutions, but all is not what I want.

**Comment by emptynick** [comment]
From the issue-template.
> IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST

The answer is simply that no http-server exists if you don't run `php artisan serve`.
Also, this is not Voyager related.
