### ISSUE TITLE
[BUG] admin > user list > view button

### ISSUE THREAD

**Issue by ynizon** [thedevdojo/voyager#3998]
Hello, i have found a bug.
When you click on view button from user list in admin, you have an error.
The bug is here:
https://github.com/the-control-group/voyager/blob/1.2/resources/views/bread/read.blade.php
Line 82 : 
@if (!empty(json_decode($data->{$row->field})))
                                        @foreach(json_decode($dataTypeContent->{$row->field}) as $item)
need to be:
@if (!empty(json_decode($dataTypeContent->{$row->field})))
                                        @foreach(json_decode($dataTypeContent->{$row->field}) as $item)

Thanks to fix it

**Comment by emptynick** [comment]
From the issue-template.
> The following information is required for bug reports.  Issues without it will be closed without response 

This can be reopened once the required informations are provided.

**Comment by ynizon** [comment]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.1
 - PHP: 7.2
 - Database: MySQL 8

## Description

When you click on view button from user list in admin, you have an error in the template file.
data is undefined.

## Steps To Reproduce
Steps to reproduce the behavior:
1. Go to 'admin > user list'
2. Click on 'view button'
3. See error

## Expected behavior
You should see user description.


## Additional context
I give you the fix. You just add it on your next release...

**Comment by ynizon** [comment]
> From the issue-template.
> 
> > The following information is required for bug reports.  Issues without it will be closed without response
> 
> This can be reopened once the required informations are provided.

i have added all details in my previous comment. Can you reopen ?

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/commit/4ee291ff24a43a56bec5009601f7ce874b725838
