### ISSUE TITLE
Suggestion for eval usage

### ISSUE THREAD

**Issue by ryun** [thedevdojo/voyager#4]
On thing that caught my eye while browsing the code was the usage of eval in the `BreadController`.
I'm sure there are other options, but you may instantiate the classes with:

``` php
$dataTypeContent = (new $dataType->model_name)->find($id);
```

**Comment by tnylea** [comment]
Thanks for the suggestion. I'll do some testing and then add this functionality in there if all is working well. I'll keep you posted.

Thanks again!

**Comment by marktopper** [comment]
Seems to be fixed.
