### ISSUE TITLE
[Feature] Exclude other tables in the database list

### ISSUE THREAD

**Issue by ledikari** [thedevdojo/voyager#4002]
## Version information
 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1.13
 - Database: mysql/sql

## Description of problem
is it possible to add a feature to hide/do not include/exclude in the tables database list inside voyager database menu? the issue is that if voyager is deployed in a live server all the tables is included in the list, and it felt dangerous/and loads slow most of the time.

Well we can alter the Database page, but how about the Bread list and other parts? 

## Proposed solution
Have a class that has an array that contains tables that can be viewed in voyager or a button in the UI that can hide the unwanted tables.

**Comment by emptynick** [comment]
Did you read the docs as suggested in the other issue?

**Comment by ledikari** [comment]
well I have read the documentation and I can manage to overwrite the views. But it is becoming tedious. Or maybe I am missing something?

**Comment by emptynick** [comment]
[Yes](https://docs.laravelvoyager.com/getting-started/configurations#database) you missed something

**Comment by ledikari** [comment]
ohh i see, i missed something. 

sorry about that. thanks.
