### ISSUE TITLE
[BUG] ReflectionException (-1) Class App\City does not exist

### ISSUE THREAD

**Issue by IamYogeshChauhan** [thedevdojo/voyager#4005]
## Version information

 - Laravel: v5.1
 - Voyager: v1.2.1
 - PHP: 7.0.9
 - Database: [MySQL] [5.0.12] 

## Description

ReflectionException (-1)
Class App\City does not exist

## Steps To Reproduce
1. Go to 'MySQL database', and create table 'cities' using table structure in below-given screenshot 01
2. Visit Voyager admin and Click on 'Database'
3. Look for  to 'cities' and click on 'Add bread to this table'

## Expected behavior
Bread should be created after submitting bread details. How to rectify the error using voyager control panel?  

## Screenshots
1. MySQL database "cities" table structure 
![screenshot-localhost-2019 03 15-00-23-19](https://user-images.githubusercontent.com/7150054/54386301-a5266c00-46be-11e9-9809-945d12c5f8b1.png)

2. Table structure screenshot at voyager panel
![screenshot-localhost-8000-2019 03 15-00-24-20](https://user-images.githubusercontent.com/7150054/54386126-4a8d1000-46be-11e9-8a63-59046ca3ab46.png)

3. Create bread option 
![screenshot-localhost-8000-2019 03 15-00-25-01](https://user-images.githubusercontent.com/7150054/54386134-4cef6a00-46be-11e9-954e-56920df6d63e.png)

4. Error after clicking on Submit at "Add BREAD to this table"
![screenshot-localhost-8000-2019 03 15-00-26-56](https://user-images.githubusercontent.com/7150054/54386142-5082f100-46be-11e9-98ed-a96c83c728d7.png)

**Comment by emptynick** [comment]
I don't really understand what you think the bug is.
The BREAD says your model is `App\City` which does not exist.

**Comment by fletch3555** [comment]
Not a bug. You just need to create the model (or select the option to have Voyager do it for you when creating the BREAD)

**Comment by IamYogeshChauhan** [comment]
> Not a bug. You just need to create the model (or select the option to have Voyager do it for you when creating the BREAD)

It resolved my issue, but now it's throwing an error "Illuminate \ Database \ QueryException (42S22)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'order clause' (SQL: select * from `countries` order by `created_at` desc)" as my table does not have "created_at" column.  Any solution?

**Comment by emptynick** [comment]
https://laravel.com/docs/eloquent#eloquent-model-conventions
Also, your php/laravel/mysql versions are very old. You shouldn't be able to install Voyager at all.

**Comment by odion-cloud** [comment]
> I don't really understand what you think the bug is.
> The BREAD says your model is `App\City` which does not exist.

hello sir i am also having same issue after i upgraded my composer and i got this error

**Comment by fletch3555** [comment]
This has been closed for 10 months.  If you're having an issue, please open your own or ask in slack.  Feel free to link to this one if it's relevant.
