### ISSUE TITLE
Returns 404 For all Pages in Copied Project

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4007]
## Version information

 - Laravel: v5.5
 - Voyager: v1.2.2
 - PHP: 7.2.11
 - Database: MySQL 8.0

## Description
I have copied the project from the production server to the local machine and reconfigured everything to use it on the local environment. Login and Dashboard works fine but it gives 404 page for everything else.

## Steps To Reproduce
1. Setup Laravel Project with Voyeger
2. Copy the entire project with the database to another machine
3. Configure everything and Login in the system.
4. Check for everything is working or not.

## Expected behavior
The project should work in local machine as working in production server

## Additional context
My Project has lots of BREAD built inside it and REST API also, so i don't want to build everything from scratch. please help.

**Comment by fletch3555** [comment]
You likely just missed some configuration.  Reproduction steps should be as specific as possible (think like you're telling a blind person how to get somewhere). Right now, your directions say "copy" but don't say where, and "configure" but don't say what or how

**Comment by lohchansiang** [comment]
Did you use xampp for the local environment? 
i face the same issue when using xampp, but its working after i use laravel `php artisan serve`

**Comment by Ademking** [comment]
Same problem when using xampp.. i updated the APP_URL but it's not working - Error 404
i think the sidemenu is not using relative url( not using APP_URL variable)
maybe i'm wrong 🤔

**Comment by Ademking** [comment]
#4008

**Comment by vkiranmaniya** [comment]
> You likely just missed some configuration. Reproduction steps should be as specific as possible (think like you're telling a blind person how to get somewhere). Right now, your directions say "copy" but don't say where, and "configure" but don't say what or how

Thanks for your reply.
I just zipped the directory containing the entire project and downloaded in the local machine. after that, I've setup Laragon (i'm not using XAMPP) and installed the database copied from server. as part of the configuration, i also configured the project's .enc file and database configs. Now the Project supposed to work exactly as on the server, but only dashboard URL works. Everything else goes to 404 page.

**Comment by vkiranmaniya** [comment]
> Same problem when using xampp.. i updated the APP_URL but it's not working - Error 404
> i think the sidemenu is not using relative url( not using APP_URL variable)
> maybe i'm wrong 🤔

Yup, I also aspect the same situation that the APP_URL variable in the .env file is not being used.
