### ISSUE TITLE
Call to undefined method TCG\Voyager\Voyager::canOrFail()

### ISSUE THREAD

**Issue by vipinyadav10** [thedevdojo/voyager#4013]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2.2
 - PHP:  7.2.13
 - Database: [type] [version] (MySQL 5.7.25)

## Description:
I have created a custom controller for voyage admin named "Import" and created a custom permission in database i.e "browse_import". When I use Voyager::canOrFail('browse_import'); I got an fatal error with message "Call to undefined method TCG\Voyager\Voyager::canOrFail()"

## Additional context
https://ibb.co/7bHnR6n

**Comment by emptynick** [comment]
Please read the upgrade-guide.

**Comment by vipinyadav10** [comment]
Thank you information.

**Comment by prakhargvp** [comment]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.2.7
 - PHP: 7.2
 - Database: mysql

## Description


> The left side links are not working after upgrading voyager

![Screenshot from 2019-09-26 00-51-30](https://user-images.githubusercontent.com/7056772/65632676-e0074600-dff7-11e9-9222-b60aef5b2c98.png)

> After upgrading voyager its showing error on opening men builder 

![Screenshot from 2019-09-26 00-47-37](https://user-images.githubusercontent.com/7056772/65632678-e09fdc80-dff7-11e9-9b3b-b29481125eb1.png)
