### ISSUE TITLE
controller for custom item menu

### ISSUE THREAD

**Issue by miladrezaei-ai** [thedevdojo/voyager#402]
- Laravel Version: 5.3
- Voyager Version: 0.10.2
- PHP Version: 7.0.10
- Database Driver & Version: 

### Description:
I cannot find the controller. I created a table ( products ) . After that, I created BREAD and added it to menu. I created products folder in \resources\views\vendor\voyager for view.

I cannot find the controller of it. Where is the controller? I want to pass some variables to views. Do I have to create controller with php artisan make:controller or there is a difference in Voyager admin controller?

**Comment by Muhammadinaam** [comment]
Check my answer:

http://stackoverflow.com/a/41162875/5013099

**Comment by marktopper** [comment]
It uses the `VoyagerBreadController` for bread by default for all created BREAD 🍞

You can however overwrite the route to go to a custom controller instead.

```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::controller('products', '\App\YourController');
});
```
