### ISSUE TITLE
Voyager "File" types get deleted for "text" sql type 

### ISSUE THREAD

**Issue by ryanm352** [thedevdojo/voyager#4020]
## Version information
 - Laravel: v5.7
 - Voyager: v1.2.2
 - PHP: 7.1.3
- MySQL: 5.6.41-84.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
Creating BREAD and using SQL type "text" with a voyager "file" type causes an issue where the previously saved upload file will be erased if any edits on the data are saved. This causes issues with mysql < 5.7 as json types don't exist (gatorhost servers)

To re-create:
--------------
Define a database table, with a columns:
"title" as "varchar"
"brochure" as "text" (json type not avail in mysql < 5.7) (gatorhost)
Add BREAD and define the BREAD type "brochure" as "File". Save.

Add an item to your new bread including a file.
Save.
Re-edit bread item, edit "title" only. Save.
Previously saved file updates as "[]"

## Fix:

``
vendor/tcg/voyager/src/Http/Controllers/ContentTypes/File.php
``

line 16: **return null instead of json_encode([]);**
``
if (!$this->request->hasFile($this->row->field)) {
            return null;
}
``

**Comment by cotiga** [comment]
Same probleme on Laravel 5.8 and Voyager 1.2.2
Thanks for your code, work fine ;)

**Comment by fletch3555** [comment]
Fixes should be submitted as pull requests, or with an explicit request that someone else submit the PR if you don't feel experienced enough to do so yourself.  Otherwise we'll just wait for you to submit it and it'lll get lost/forgotten about.

**Comment by cotiga** [comment]
PR #4156
thank you ryanm352 again
