### ISSUE TITLE
Where are posts and pages at frontend? [BUG]

### ISSUE THREAD

**Issue by cosinus90** [thedevdojo/voyager#4023]
## Version information

 - Laravel: v5.8.7
 - Voyager: Latest. Just installed. I don't know where to fetch the version.
 - PHP: 7.2.13
 - Database: MySQL 5.5.57 (e.g. MySQL 8.0)

## Description

Ok, I don't think that it's a bug, just an obscurity. I installed Voyager --with-dummy and I can see 3 sample posts and 1 sample page in admin area. For example, first post has slug lorem-ipsum-post, and as soon as Voyager supports slugs for posts and pages I expect that it provides showing them at frontend. But what is the url for this sample post?
domain.com/lorem-ipsum-post
domain.com/post/lorem-ipsum-post
domain.com/posts/lorem-ipsum-post
all return 404.
I can't imagine the bug in such a basic functionality, probably I don't understand something.

I installed Voyager on clear Laravel installation
(composer create-project --prefer-dist laravel/laravel blog)
accoring this instruction
https://docs.laravelvoyager.com/getting-started/installation
and I added Service provider.

**Comment by emptynick** [comment]
https://docs.laravelvoyager.com/getting-started/what-is-voyager

**Comment by cosinus90** [comment]
https://devdojo.com/tutorials/working-with-voyager-on-the-front-end

For those who will google it.
