### ISSUE TITLE
[BUG] Need also to publish seed when manually installing

### ISSUE THREAD

**Issue by djobel** [thedevdojo/voyager#4024]
## Version information

 - Laravel: v5.8.7
 - Voyager: v1.2.1
 - PHP: 7.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Could you please update the voyager documentation in the manual installation section ?
The user also need to publish voyager seed, otherwise he got error : VoyagerDatabaseSeeder does not exists.

**Comment by emptynick** [comment]
That's pretty much exactly what
`php artisan vendor:publish --provider=VoyagerServiceProvider`
from step 1 does?

**Comment by djobel** [comment]
No, in my case it did nothing.
You need to use : php artisan vendor:publish --provider=seed

**Comment by fletch3555** [comment]
`seed` is not a valid "provider"... so that should do nothing.

@emptynick is correct. Publishing with VoyagerServiceProvider will publish everything that Voyager intends to publish.

**Comment by emptynick** [comment]
Corrected in https://github.com/the-control-group/voyager/commit/62df0ef6281e94994fc676436592e44c85c6c1ff
