### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by franckitho** [thedevdojo/voyager#4025]
## Version information

 - Laravel: 5.4
 - Voyager: 1.2.2
 - PHP: 7.3

## Description

Can't insert image on new post (tiny editor)

## Steps To Reproduce
1. Go to 'admin panel and post section '
2. Click on 'new post or edit post'
3. Click on insert image

## Screenshots
![image](https://user-images.githubusercontent.com/33814441/54868350-e20ff400-4d8b-11e9-8262-c3d8371eb077.png)
![image](https://user-images.githubusercontent.com/33814441/54868357-f5bb5a80-4d8b-11e9-804c-2e17921fa374.png)
![image](https://user-images.githubusercontent.com/33814441/54868366-04097680-4d8c-11e9-9e89-c96c0c64422d.png)
![image](https://user-images.githubusercontent.com/33814441/54868374-14215600-4d8c-11e9-94d1-3c2e67e82d72.png)

**Comment by emptynick** [comment]
Do you have any console errors?
I'm quite sure this is some kind of misconfiguration.
Also, I assume you are not really using Laravel 5.1?

**Comment by franckitho** [comment]
> 
> 
> Do you have any console errors?
> I'm quite sure this is some kind of misconfiguration.
> Also, I assume you are not really using Laravel 5.1?

Sorry i use 5.4 laravel ^^
no console error 
i follow all step configuration on https://docs.laravelvoyager.com/getting-started/installation

**Comment by emptynick** [comment]
Then I guess you also read that we don't support 5.4 in Voyager 1.2?
That notice is still there for people who have auto-discover off.

**Comment by franckitho** [comment]
i try with laravel 5.8 and 5.7, I can't insert image
