### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by abaritci** [thedevdojo/voyager#4026]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description of problem

We are using Voyager for our Admin dashboard. Also we need to translate the admin dashboard with Armenian language. We added the translations files in **/resources/lang/vendor/voyager/am**.Some features we can translate but we can not change the logged in user locale from Admin dashboard.All locales read from lang folder of vendor voyager( **getLocales()** function )

## Proposed solution
Can we add new translation languages files and commit it.

## Alternatives considered
Can we change the getLocales function of Voyager.php file and use it.

## Additional context
Are you tried to add Armenian translation language in voyager.

**Comment by emptynick** [comment]
Why don't you submit your translations as a PR instead?
That way you will also be able to select AM

**Comment by abaritci** [comment]
Do you approve it then?

**Comment by emptynick** [comment]
Of course, why shouldn't we?

**Comment by abaritci** [comment]
Ok.
I will translate all files in Armenian and after finishing it will create new branch(I cloned the voyager in my local side already), commit it and create Pull Request.
Thanks

**Comment by abaritci** [comment]
Hello.
I finished the translation of Armenian language but can not push my codes with seperate branch in your repository.I need accesses.How can I add my changes then?
Thanks

**Comment by emptynick** [comment]
In your own personal fork. From there you can open a pull request

**Comment by emptynick** [comment]
Closing as #4028 was merged.
