### ISSUE TITLE
[BUG] Multi-language fields cannot remember old input upon file submit.

### ISSUE THREAD

**Issue by normangoh** [thedevdojo/voyager#4035]
Laravel 5.8
Voyager 1.2.2

Description
When filling up multi language fields on add/edit page, the old values does not returned upon submit action when there are other error messages in the bag.

Steps to reproduce
1 - Use posts (dummy) or manual created BREAD with multi language fields.
2 - Key in data inside the multi language fields.
3 - Click form submit and purposely left out a few other required fields to make sure form will return to edit/add page to see if old values are remembered and return inside the multi language fields.

**Comment by normangoh** [comment]
I managed to resolve this bug by using the template override from the vendor resource.

May I know how can I share my solution to the community? I am thinking that the other users out here might be facing the same issues as well.

**Comment by classiebit** [comment]
...

**Comment by MrCrayon** [comment]
If you confirmed it's a bug and you found a solution you can open a PR so your code can be merged and fix it for everybody.

I remember in previous versions forms were validated on submit with an ajax call so page was not reloaded, I'm not sure when that changed.

**Comment by MrCrayon** [comment]
Probably here https://github.com/the-control-group/voyager/commit/d1e50a416d3eec0151965667f3b1daf1ebc667bb

**Comment by andrey-helldar** [comment]
I also met this bug.

I enter a knowingly long message (53 characters with 50 allowed):
![2019-04-24_21-42-20](https://user-images.githubusercontent.com/10347617/56685283-43ecb200-66da-11e9-9589-e07e5f2f49c7.png)

And see this:
![2019-04-24_21-44-34](https://user-images.githubusercontent.com/10347617/56685365-772f4100-66da-11e9-9b98-f89bb8810ada.png)

Search in files resulted in an error source.
Now the [code is written](https://github.com/the-control-group/voyager/blob/1.2/resources/views/formfields/text.blade.php#L4) like this:
```php
//...
value="{{ $dataTypeContent->{$row->field} ?? old($row->field) ?? $options->default ?? '' }}">
```

It will be correct like this:
```php
value="{{ old($row->field, $dataTypeContent->{$row->field} ?? $options->default ?? '') }}">
```

This behavior is found in different form fields.
