### ISSUE TITLE
Images not saving to the public folder

### ISSUE THREAD

**Issue by MikeDynamic** [thedevdojo/voyager#4037]
Hi, 

I am running the latest laravel build with the latest voyager version and the latest homestead local setup. 

Everything is working perfectly except for the storage of media. 
Currently the images are being stored in storage/app/public/pages.......

I am running an out of the box voyager install and it is not picking up the images from the storage folder, however if I copy and past the images into the main public folder then everything works. However I need the images to automatically be saved where they can be accessed with ease, link in the voyager intro video :) 

Currently my filesystems.php shows storage as: 
```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/public/images',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],
```
and my voyager.php : 

 ```
   'storage' => [
        'disk' => env('FILESYSTEM_DRIVER', 'public'),
    ],
```

I am not sure why it did not work right out of the box. 

Thank you

**Comment by fletch3555** [comment]
Voyager is supposed to store them under storage/app/public, because that's what your default "disk" (`public`) is telling it to do (`storage_path('app/public')`).  However, your public directory should also have a symlink called `storage` that points to `storage/app/public`, which allows it to work.

In short, just delete anything you have at `public/storage` then run `php artisan storage:link`

**Comment by fletch3555** [comment]
I should also mention that our issue template is required for this project.  If you're simply asking a question that doesn't seem to fit the template, it's likely better asked in slack

**Comment by MikeDynamic** [comment]
Thank you @fletch3555 . I have joined the slack group
