### ISSUE TITLE
Datatable server side in Browse

### ISSUE THREAD

**Issue by Muhammadinaam** [thedevdojo/voyager#404]
In browse view, please add functionality of server side loading of datatable data to improve performance on large tables.

**Comment by marktopper** [comment]
The performance should be okay for most tables.

How big are your tables?

**Comment by fletch3555** [comment]
I'm not sure what you mean by "server side loading".  If you're referring to pagination of the data, there is already an open issue for this (#81)

**Comment by marktopper** [comment]
Closed due to inactivity.
