### ISSUE TITLE
[BUG] Call to a member function relationLoaded() on null

### ISSUE THREAD

**Issue by gruz** [thedevdojo/voyager#4041]
## Version information

 - Laravel: vv5.8.7
 - Voyager: v1.2.2
 - PHP: 7.2.4
 - Database: Postgres  11.1

## Description

I can create a role-less user an Voyager and when I try to login as this user, I get the error:
```
Call to a member function relationLoaded() on null
```
I tried with a fresh laravel-voyager install. 

Yes, I checked this https://github.com/the-control-group/voyager/issues/2451
But it's not an upgrade, the class for the user controller is set to

 ```TCG\Voyager\Http\Controllers\VoyagerUserController```

## Steps To Reproduce
1. Login as an admin
2. Create a user and don't enter any role
3. Logout and try to login as the newly created user.

## Expected behavior
For a user which has role but has no backend permission it's redirected to the web-site root. Should work this way as well

**Comment by minhdanh** [comment]
I'm seeing this as well. Looks like when a user (not admin) update his/her profile, his/her role is also updated with empty value. After that this error is showing.

**Comment by WuHuaJi0** [comment]
I was meet the same issue.
