### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by RussoMusso** [thedevdojo/voyager#4046]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL

## Description of problem

Hey there. I am new to voyager and laravel, but I am pretty sure that I want to learn it. So my problem is that I made in Admin Front-End panel in Media section Folder named Album where I uploaded some pictures. Everything is okay. But I want to ask you how it's possible to display those images into foreach loop?? How can I get those images??

For posts this worked:

@foreach($posts as $post)
    
        <img src="{{ Voyager::image( $post->image ) }}" />
    
@endforeach

How I need to change this one???

**Comment by emptynick** [comment]
As the issue-template suggest, please ask questions in our Slack group.
As for your question: thats simple [filesystem ](https://laravel.com/docs/filesystem) stuff.
