### ISSUE TITLE
[BUG] Admin menu not showing in Internet Explorer

### ISSUE THREAD

**Issue by xaviqv** [thedevdojo/voyager#4047]
## Version information

 - Laravel: v5.5
 - Voyager: v1.2.2
 - PHP: 7.3
 - Database: MySQL 8.0

## Description
Admin menu elements are not loading with Internet Explorer 11 due to the usage a backtick that contains a multiline string in views > menu > admin_menu.blade.php

![image](https://user-images.githubusercontent.com/25639840/55153120-f409e200-5151-11e9-835d-0a70f59ce7b7.png)

## Steps To Reproduce
Open admin route with Internet Explorer 11

## Additional context
https://stackoverflow.com/questions/42493557/javascript-backtick-multiline-string-not-working-in-internet-explorer

**Comment by emptynick** [comment]
The database tool is also using this syntax:
https://github.com/the-control-group/voyager/blob/9101761b2f821d239c1e05015a52d5982c53a5cd/resources/views/tools/database/vue-components/database-table-editor.blade.php#L113
Is that not working as well?

**Comment by xaviqv** [comment]
It's not working. I can't see the page content only with Internet Explorer, but it works fine in Chrome. It seems that this syntax is being used in some other files i Voyager:

![image](https://user-images.githubusercontent.com/25639840/55154381-fae62400-5154-11e9-9b40-5fca4489887c.png)

**Comment by normangoh** [comment]
I just tested with IE11 today and indeed the admin side menu after login is not showing. It seems like the template literals is not supported by IE.

Is there any way to fix it?
