### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by partovi1011** [thedevdojo/voyager#4050]
hello guys
today i goto my voyager and when i go to my menu like products or everything i get this error
"Class 'TCG\Voyager\Actions\ConfirmAction' not found "
i have oppened Action folder but i cant found ConfirmAction
anyone can halp me?

**Comment by emptynick** [comment]
Please use the issue template.
Also, there's no built-in ConfirmAction, so its a misconfiguration from your side (see the docs for more information).
