### ISSUE TITLE
[BUG] Hypocritical multilingual support

### ISSUE THREAD

**Issue by number201724** [thedevdojo/voyager#4052]
I spent 2 hours debugging, why I did not refresh the language file manually, switching the language in laravel does not refresh the language information until I see the following code

`class MenuItemsTableSeeder`

```

$menu = Menu::where('name', 'admin')->firstOrFail();

        $menuItem = MenuItem::firstOrNew([
            'menu_id' => $menu->id,
            'title'   => __('voyager::seeders.menu_items.dashboard'),
            'url'     => '',
            'route'   => 'voyager.dashboard',
        ]);
        if (!$menuItem->exists) {
            $menuItem->fill([
                'target'     => '_self',
                'icon_class' => 'voyager-boat',
                'color'      => null,
                'parent_id'  => null,
                'order'      => 1,
            ])->save();
        }
```

WTF? holy shit

```

$menuItem = MenuItem::firstOrNew([
            'menu_id' => $menu->id,
            'title'   => __('voyager::seeders.menu_items.dashboard'),
            'url'     => '',
            'route'   => 'voyager.dashboard',
        ]);

__('voyager::seeders.menu_items.dashboard')

__('voyager::seeders.menu_items.dashboard')

__('voyager::seeders.menu_items.dashboard')

```

This is a fake multi-language support, he deceived us, it does not enable dynamic multi-language switching

**Comment by number201724** [comment]
When I switch from Chinese to English in user settings

![5](https://user-images.githubusercontent.com/7903677/55292440-b04afd00-541d-11e9-993a-9fcfbb426c06.png)

**Comment by emptynick** [comment]
Please watch your tone. This is not acceptable.
Also, the issue template is required.
If you want to translate menu items, then translate them through the UI. Easy
