### ISSUE TITLE
[BUG] The embedded youtube video at landing page not work correctly

### ISSUE THREAD

**Issue by luisintosh** [thedevdojo/voyager#4054]
## Description
When I visited the website https://laravelvoyager.com/ and clicked on intro video, this isn't functional. It needs an "h" in the iframe URL.

## Steps To Reproduce
1. Go to https://laravelvoyager.com/
2. Click on the play button

## Screenshots
![Imgur](https://i.imgur.com/3lKsFBK.png)

**Comment by emptynick** [comment]
Fixed. Thanks!
