### ISSUE TITLE
[BUG]user_belongsto_role_relationship is returning an empty set.

### ISSUE THREAD

**Issue by jeremiahsherrill** [thedevdojo/voyager#4055]
## Version information

 - Laravel: v5.8.9
 - Voyager: v1.2
 - PHP: 7.3.3
 - Database: 5.5.60-MariaDB

## Description

Adding roles to user fails, relation?search=&type=user_belongsto_role_relationship&page=1 returns an empty set. 

## Steps To Reproduce
1. Go to 'users'
2. Click on 'add or edit'
3. Scroll down to 'roles and try to add'
4. No roles load, inspect element to see error in inspector

## Expected behavior
add one of 12 roles to user

**Comment by emptynick** [comment]
> No roles load, inspect element to see error in inspector

Are you going to tell us which error?

**Comment by jeremiahsherrill** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) relation?search=&type=user_belongsto_role_relationship&page=1

Fresh install with roles created

**Comment by emptynick** [comment]
> ... returns an empty set.

> the server responded with a status of 404 (Not Found) relation?

Which of it?

**Comment by jeremiahsherrill** [comment]
search=&type=user_belongsto_role_relationship&page=1 returns an emptyset, chrome respond with 404 not found on that. 

Route::get($dataType->slug.'/relation', $breadController.'@relation')->name($dataType->slug.'.relation');

When this queries roles, it says there are no roles.  Yet there are roles.  Works locally on php 7.1, same version, doesn't work on server.   All other aspect of voyager work on remote server, except this.

**Comment by fletch3555** [comment]
You can't both get a 404, AND a response of an empty set.... so which is it? Screenshots of the network tab may be helpful

**Comment by emptynick** [comment]
The only reason why this line kicks in:
https://github.com/the-control-group/voyager/blob/5e175637fca405577f3b7a06ee029ec339686406/src/Http/Controllers/VoyagerBaseController.php#L680
Is because there are no `editRows` **or** the field which is passed does not exist.
Did you untick any of the fields from the user-BREAD or removed an entry?

**Comment by jeremiahsherrill** [comment]
I did not, just did a fresh migrate and voyager install and getting the same results.

**Comment by jeremiahsherrill** [comment]
Brand New Install

Centos OS 7 
Php 7.3.3 
same as above

The only thing in this is voyager and laravel, everything is as shipped. 

Failed to load resource: the server responded with a status of 404 (Not Found)
relation?type=user_belongsto_role_relationship&page=1:1 Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:1 GET http://10.253.1.8/admin/users/relation?type=user_belongstomany_role_relationship&page=1 404 (Not Found)
send @ app.js:1
ajax @ app.js:1
transport @ app.js:1
o @ app.js:1
i.query @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
r.trigger @ app.js:1
r.open @ app.js:1
r.toggleDropdown @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
(anonymous) @ app.js:1
dispatch @ app.js:1
g.handle @ app.js:1
3app.js:1 GET http://10.253.1.8/admin/users/relation?type=user_belongsto_role_relationship&page=1 404 (Not Found)
send @ app.js:1
ajax @ app.js:1
transport @ app.js:1
o @ app.js:1
i.query @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
r.trigger @ app.js:1
r.open @ app.js:1
r.toggleDropdown @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
(anonymous) @ app.js:1
dispatch @ app.js:1
g.handle @ app.js:1
app.js:1 GET http://10.253.1.8/admin/users/relation?type=user_belongstomany_role_relationship&page=1 404 (Not Found)
send @ app.js:1
ajax @ app.js:1
transport @ app.js:1
o @ app.js:1
i.query @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
r.trigger @ app.js:1
r.open @ app.js:1
r.toggleDropdown @ app.js:1
(anonymous) @ app.js:1
i.invoke @ app.js:1
i.trigger @ app.js:1
(anonymous) @ app.js:1
dispatch @ app.js:1
g.handle @ app.js:1
3app.js:1 GET http://10.253.1.8/admin/users/relation?type=user_belongsto_role_relationship&page=1 404 (Not Found)

**Comment by jeremiahsherrill** [comment]
MariaDB [mcms]> select * from roles
    -> ;
+----+-------+---------------+---------------------+---------------------+
| id | name  | display_name  | created_at          | updated_at          |
+----+-------+---------------+---------------------+---------------------+
|  1 | admin | Administrator | 2019-04-02 19:01:56 | 2019-04-02 19:01:56 |
|  2 | user  | Normal User   | 2019-04-02 19:01:56 | 2019-04-02 19:01:56 |
+----+-------+---------------+---------------------+---------------------+

MariaDB [mcms]> select * from users;
+----+---------+----------+---------------------------------+-------------------+-------------------+--------------------------------------------------------------+----------------+----------+---------------------+---------------------+
| id | role_id | name     | email                           | avatar            | email_verified_at | password                                                     | remember_token | settings | created_at          | updated_at          |
+----+---------+----------+---------------------------------+-------------------+-------------------+--------------------------------------------------------------+----------------+----------+---------------------+---------------------+
|  1 |       1 | Jeremiah | test@email.com   | users/default.png | NULL              | $2y$10$p693VG5V4FfKb8BNL6fm1O12EBWdinhUapqoSy.Jk07N2tyYaj3czu | NULL           | NULL     | 2019-04-02 19:02:52 | 2019-04-02 19:02:52 |
|  2 |       1 | jason    | test2@email.com | users/default.png | NULL              | $2y$10$VIIMArlyplWbrbsUvzAHp121276fHsJx19QIJn7xhLOqKvCZE5.hFm | NULL           | NULL     | 2019-04-02 19:03:52 | 2019-04-02 19:03:52 |
+----+---------+----------+---------------------------------+-------------------+-------------------+--------------------------------------------------------------+----------------+----------+---------------------+---------------------+

MariaDB [mcms]> select * from user_roles
    -> ;
+---------+---------+
| user_id | role_id |
+---------+---------+
|       1 |       1 |
+---------+---------+
1 row in set (0.00 sec)


Both accounts where created using php artisan voyager:admin your@email.com --create  neither inserted anything into user_roles table, so I thought that was the problem so i created a new entry for my user. Still does not work.

**Comment by jeremiahsherrill** [comment]
I found one difference, when I dd($options) under the edit-add.blade file.   Under Options


This server it works 

 +"model": "TCG\Voyager\Models\Role"
  +"table": "roles"
  +"type": "belongsTo"
  +"column": "role_id"
  +"key": "id"
  +"label": "display_name"
  +"pivot_table": "roles"
  +"pivot": "0"
  +"taggable": "0"


Server where it is not working

  +"model": "TCG\Voyager\Models\Role"
  +"table": "roles"
  +"type": "belongsTo"
  +"column": "role_id"
  +"key": "id"
  +"label": "display_name"
  +"pivot_table": "roles"
  +"pivot": 0


The difference being taggable.

**Comment by emptynick** [comment]
Again, there are only 2 reasons why that method would return 404:
https://github.com/the-control-group/voyager/blob/5e175637fca405577f3b7a06ee029ec339686406/src/Http/Controllers/VoyagerBaseController.php#L646
Set a `dd($dataType->editRows);` just **before** this line, and:
https://github.com/the-control-group/voyager/blob/5e175637fca405577f3b7a06ee029ec339686406/src/Http/Controllers/VoyagerBaseController.php#L647
Set a `dd($row);` directly **after** this line.
Post both results here please.
If the first returns an empty collection - thats bad.
If the second doesn't do anything - thats bad aswell.
If the latter is the case, please add `dd($dataType->rows);` before the `foreach (...)` (line 645)

**Comment by jeremiahsherrill** [comment]
dd($dataType->editRows); is doing nothing
I put in a string of gibberish to see if it was even seeing it and it does. 

$dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();
        dd($dataType->editRows);
        werwerwer
        foreach ($dataType->editRows as $key => $row) {

**Comment by jeremiahsherrill** [comment]
It's not just dd var_dump($dataType->editRows) doesn't post anything either.

**Comment by emptynick** [comment]
Then please add `dd($dataType->rows);` before the `foreach (...)` (line 645) and post the whole output.
And a screenshot of the whole bread-settings for the users table (something like http://localhost/admin/bread/users/edit)

**Comment by jeremiahsherrill** [comment]
No output, I don't even think the relation function is being called, I added a new attribute to it and nothing broke.   I know dd() works throughout other sections, but not in relation or most of VoyagerBaseController.php.    

https://imgur.com/a/s7ts26M

**Comment by jeremiahsherrill** [comment]
Whatever is supposed to call relation is not calling it, I deleted the entire function and nothing changed, I deleted everything is VoyagerBaseController just to verify I was working in the right file and everything broke as it should.  I am completely flumoxed

**Comment by jeremiahsherrill** [comment]
Could this be a file permissions problem?   I am having serious file permissions problems with my server?

**Comment by jeremiahsherrill** [comment]
It did turn out to be a permissions problem. Was able to resolve.

**Comment by webroottech** [comment]
ErrorException
Undefined property: stdClass::$scope
http://localhost/moto/public/admin/users/relation?method=add&page=1&type=user_belongsto_role_relationship

**Comment by webroottech** [comment]
if ($options->scope && $options->scope != '' && method_exists($model, 'scope'.ucfirst($options->scope))) {

                    $model = $model->{$options->scope}();

                }

**Comment by webroottech** [comment]
this is causing the error. How do I resolve it

**Comment by emptynick** [comment]
Please don't comment on completely unrelated issues.
