### ISSUE TITLE
Table deletion doesn't work if table name is a MySQL keyword. Tested 'match', 'union' and 'join' tested

### ISSUE THREAD

**Issue by sadart** [thedevdojo/voyager#4056]
## Version information
 - Laravel: v5.5.39
 - Voyager: v1.2.2
 - PHP: 7.2.15
 - Database: MySQL 5.7.25-0ubuntu0.18.04.2 (Ubuntu)

## Steps To Reproduce
1. Go to http://[SERVER-IP]/admin/database
2. Click on Create a table
3. Enter 'match' in table name field
4. Add a columm 'name'
5. Click on 'Create New Table'
6. You will be taken back to http://[SERVER-IP]/admin/database page
7. Click the Delete button corresponding to the 'match' table
8. An error will flash at the top right corner of the screen 'Exception: An exception occurred while executing 'DROP TABLE match SQLSTATE[42000]. Syntax error or access violation: 1064. You have an error in your SQL syntax; check the maual that corresponds to your MySQL server version for the right syntax to use near 'match' at line 1

## Expected behavior
The 'match' table should have been deleted.

## Screenshots

![Screenshot from 2019-04-03 16-51-19](https://user-images.githubusercontent.com/2045059/55499955-ba941380-5636-11e9-9f2c-4c10bbbb199e.png)

![Screenshot from 2019-04-03 16-51-23](https://user-images.githubusercontent.com/2045059/55499922-a4865300-5636-11e9-948e-c0cd940933ca.png)

## Additional context
The issue stems from the fact the 'match' is a MySQL keyword. Other keywords like 'join' and 'union' were used and the same error cropped up.

**Comment by emptynick** [comment]
Don't use reserved keywords then?

**Comment by sadart** [comment]
> Don't use reserved keywords then?

Of course. Obvious reply. I dug in and realized the issue falls out of scope from voyager. The issue comes from doctrine, hence, that is where I was supposed to raise the issue.

Thanks.
