### ISSUE TITLE
Input file error

### ISSUE THREAD

**Issue by ikromovpro** [thedevdojo/voyager#4065]
## Version information

 - Laravel:5.5.45
 - Voyager: v1.2.*
 - PHP: 7.2
 - Database: Mysql 14.14

## Description

File input after update  database filename remove

## Screenshots
![1](https://user-images.githubusercontent.com/38875348/55668825-3e910a00-5888-11e9-8b1a-17458112c914.png)
![2](https://user-images.githubusercontent.com/38875348/55668827-3fc23700-5888-11e9-8e01-1ea08a85ef49.png)
![3](https://user-images.githubusercontent.com/38875348/55668828-3fc23700-5888-11e9-8ceb-714a37781b14.png)

## Additional context
Sorry my bad english.

**Comment by cotiga** [comment]
Look here
https://github.com/the-control-group/voyager/issues/4020

**Comment by ikromovpro** [comment]
thanks
