### ISSUE TITLE
View [admin_menu] not found.

### ISSUE THREAD

**Issue by farizree** [thedevdojo/voyager#4066]
## Version information

 - Laravel: v5.5
 - Voyager: v1.2
 - PHP: 7.1.3
 - Database: [MySQL] [10.1.38] 

## Description

when I try to upgrade voyager to 1.2 I got a error in admin login.
View [admin_menu] not found. (View: /Applications/XAMPP/xamppfiles/htdocs/farizree/vendor/tcg/voyager/resources/views/dashboard/sidebar.blade.php)

## Screenshots
![Screenshot 2019-04-06 at 22 37 10](https://user-images.githubusercontent.com/25852713/55671643-8cc00080-58bc-11e9-9ebe-71211dd59871.png)

**Comment by emptynick** [comment]
Neither `dashboard/sidebar.blade.php` or `admin_menu` is included in the login-view.
Also, `admin_menu` is not included in `dashboard/sidebar.blade.php` in version 1.2.
Did you override any of those views?

**Comment by henryonsoftware** [comment]
Me too when trying upgrade from `1.1.*` to `1.2.*`

**Comment by impsart** [comment]
@farizree 
Try clearing your Laravel cache. That worked for me.

**Comment by farizree** [comment]
> 
> 
> @farizree
> Try clearing your Laravel cache. That worked for me.

it works, after try php artisan view:clear 😃 😃 😃 
thank you 💃

**Comment by henryonsoftware** [comment]
@faghihi this issue should be close

**Comment by mattrabe** [comment]
> @farizree
> Try clearing your Laravel cache. That worked for me.

Like this: `php artisan view:clear`

More info on cache-clearing commands: https://tecadmin.net/clear-cache-laravel-5/
