### ISSUE TITLE
Home page route not working on server.

### ISSUE THREAD

**Issue by maliknabdul** [thedevdojo/voyager#4067]
## Version information

 - Laravel: v5.8
 - Voyager: v#.#.#
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
On the local, the home page is working fine and loading with custom template home.blade. But on the server, the home page is not loading with home.blade. It is showing the content for the home page but it is not loading with proper the formatting. You can see here what I mean.

This is not loading with the proper format.
https://unionflooringcompany.theportlandcompany.com/

But

https://unionflooringcompany.theportlandcompany.com/page/home is working fine.

**Comment by emptynick** [comment]
This is not a Voyager related problem
