### ISSUE TITLE
Path not found

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4069]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MYSQL
## Description

Once i customize views, I want to create new link , it give me error, path not found.
<a href="{{ route('voucher-details/getCategories') }}" >
                    new link
                </a>
Here is path
Route::get('voucher-details/getCategories', ['uses' => 'VoucherController@selecttype']);
## Steps To Reproduce
1. copy views files to views/vendor/voyager/....
2. go to read.blad.php and create new link
3. create route for that in web.php

**Comment by emptynick** [comment]
Not a Voyager problem.
