### ISSUE TITLE
jQuery Cookie JS not found in /vender/tcg/assets/js

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#407]
- Laravel Version: 5.3.x
- Voyager Version: ^0.9.18
- PHP Version: 7.0.4
- Database Driver & Version:

### Description: jquery cookie js not found in /vender/tcg/assets/js ...
I've just update to the latest release of Voyager, but then I found jquery.cookie.js is missing in the assets.

### Steps To Reproduce:

**Comment by marktopper** [comment]
Please let me know the following:

1. Do you have the file `PROJECT/vendor/tcg/voyager/publishable/assets/js/jquery.cookie.js`?
2. Do you have the file `PROJECT/public/vendor/tcg/voyager/assets/js/jquery.cookie.js`?

**Comment by handiwijoyo** [comment]
Voyager `v0.9.18` is kinda old and a lot of changes were made on newer version, try to update it to `v0.9.35` instead. Or if you use it on new project kindly use `v0.10.*`

**Comment by marktopper** [comment]
Closing due to missing response.
