### ISSUE TITLE
Dropzone.js implementation

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4070]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP:7.3
 - Database: mysql

## Description of problem

I search too much on google but could not found how to integrate [Dropzone.js](https://www.dropzonejs.com/) in voyager for multiple images?

## Proposed solution
I want to integrate drag and drop images feature in voyager

## Alternatives considered
just like here https://www.dropzonejs.com/

**Comment by emptynick** [comment]
Use the media-picker.
