### ISSUE TITLE
View [admin_menu] not found. 

### ISSUE THREAD

**Issue by VinceGee** [thedevdojo/voyager#4074]
## Version information
 - Laravel: v5.7.28
 - Voyager: v1.2
 - PHP: 7.3.1
 - Database:  MySQL 10.1.37

## Description
I was developing on my desktop, but because I now want to sync with another app, so  I moved the project to HTDOCS. So i moved the project to htdocs, Did `composer install,` then `php artisan key:generate`, then `php artisan cache:clear`. and my front-end was working. 

But when I try to access the /admin, the login view is coming up fine. the problem comes when I try to view the dashboard or any other view with an /admin prefix. 

## Screenshots
![show](https://user-images.githubusercontent.com/14182249/55882708-45c85880-5ba5-11e9-92c0-00c72684ed70.png)

PS: I have already tried [this](https://github.com/the-control-group/voyager/issues/4066)
i.e.
`php artisan view:clear `
`php artisan cache:clear`
`php artisan config:cache`

and still no change. I also overwrote some views, but no views related to menus
![show2](https://user-images.githubusercontent.com/14182249/55883447-a4420680-5ba6-11e9-9daf-c87260e8aff4.PNG)

**Comment by emptynick** [comment]
Edit: Sorry, just saw you already tried those steps.
Nonetheless: this view was removed in 1.2 and you need to adapt your code accordingly.

**Comment by VinceGee** [comment]
yeah tried those, with no luck...

I also thought since I was overwriting the view, what if I don't overwrite the menu, so I deleted my view....and the menu came up with no menu items:

![show3](https://user-images.githubusercontent.com/14182249/55933823-f75f9c00-5c2e-11e9-8a19-bf3aec1f2931.png)

also tried overwriting it with `{!! menu('admin', 'my_menu') !!}` as mentioned [here](https://docs.laravelvoyager.com/core-concepts/menus-and-menu-builder) but the menu items are appearing as an unOrdered list

**Comment by VinceGee** [comment]
Also opened the original sidebar.blade.php located in `\vendor\tcg\voyager\resources\views\dashboard` and copied the code that echoes the menu, i.e. `<div id="adminmenu">
            <admin-menu :items="{{ menu('admin', '_json') }}"></admin-menu>
        </div>`

menu still comes out blank as image above

**Comment by michaelisip** [comment]
Have you solved this issue? We're currently having this issue too.

**Comment by emptynick** [comment]
Just revert the custom changes made to the menu/sidebar/master views to what Voyager delivers and recreate custom changes made before.

**Comment by VinceGee** [comment]
Yep that did it, deleting all the custom changes I made restored the menu. Thanks ;)

**Comment by hhhormean** [comment]
> Also opened the original sidebar.blade.php located in `\vendor\tcg\voyager\resources\views\dashboard` and copied the code that echoes the menu, i.e. `<div id="adminmenu"> <admin-menu :items="{{ menu('admin', '_json') }}"></admin-menu> </div>`
> 
> menu still comes out blank as image above

thanks it works

**Comment by bedus-creation** [comment]
I got the same problem and solved by
```
php artisan view:clear
```
