### ISSUE TITLE
BREAD Image Field should not modify uploaded image

### ISSUE THREAD

**Issue by gkmk** [thedevdojo/voyager#4078]
## Version information
 - Laravel: v5.8.*
 - Voyager: v1.2
 - PHP: 7.2

## Description of problem
When we upload large images to admin panel (over 10K pixels width and 20MB), the server overloads and even times out.

## Proposed solution
Dont process images unless specifically specified in the [image field options](https://docs.laravelvoyager.com/core-concepts/bread-builder#image)

**Comment by emptynick** [comment]
We do this to orientate images uploaded from various sources.
Overloading/timeout sounds like a server problem to me.

**Comment by gkmk** [comment]
I still think this should be optional. Its administration panel so admins should know what they are uploading. 
The server tries to allocate 600+ MB RAM per image upload. I think this is a problem. The only solution now is to get bigger servers or switch to file data type which will increase costs and require re-coding.

**Comment by emptynick** [comment]
I'd suggest to use Imagick instead of GD.
Open `config/image.php` and change `driver` accordingly.
It should consume much less memory.

**Comment by gkmk** [comment]
@emptynick Ill try that and compare memory usage.

**Comment by gkmk** [comment]
Imagick seems to be much better, no buffer errors reported so far. Thanks for the recommendation!

If possible to have that post image processing as option in the json that would still be good i think.

Thanks
