### ISSUE TITLE
Uncaught ReferenceError: Vue is not defined in admin_menu.blade.php

### ISSUE THREAD

**Issue by lorenzhahaha** [thedevdojo/voyager#4079]
## Version information

 - Laravel: v5.8.10
 - Voyager: v1.2.3
 - PHP: 7.2.8
 - Database: MySQL 8.0

## Description:
I have just updated my Voyager in its latest version. After doing so, I keep on getting this error regarding the sidebar (Note: I have overridden the sidebar.blade.php and created my own in my resources/views and have used the **admin_menu** as its style). It was working well when I use the downgraded version and now I don't know what might seem to be the problem. The picture below will show the screenshot of the sidebar after updating and also the error.

![Sidebar issue in the updated Voyager version](https://user-images.githubusercontent.com/20533942/56050798-63511a00-5d7f-11e9-81ce-f987708ea61f.png)

Moreover, I have tried using the **default** and **bootstrap** style and not the **admin_menu** and there was no problem there. Below are the screenshots.

![Bootstrap style of the sidebar](https://user-images.githubusercontent.com/20533942/56051156-5680f600-5d80-11e9-92b3-ac042261ff3c.png)
![Default style of the sidebar](https://user-images.githubusercontent.com/20533942/56051113-39e4be00-5d80-11e9-98af-8ebe2a89a654.png)

## Additional context
This is how I implement it on my end according to the documentation.

![Implementation for the sidebar using admin_menu](https://i.ibb.co/JynTwCP/Implementation.png)

And lastly, I have already tried removing all of the caches through **php artisan view:clear** but it still doesn't work. 

Sorry for a very detailed report since I really can't compose properly as to what is standard. Advance gratitude for all the understanding and support guys!

**Comment by emptynick** [comment]
Probably the same as https://github.com/the-control-group/voyager/issues/4074
> Just revert the custom changes made to the menu/sidebar/master views to what Voyager delivers and recreate custom changes made before.

**Comment by lorenzhahaha** [comment]
Thank you. It was fixed now. I will close the issue now sir @emptynick.
