### ISSUE TITLE
[Feature] Different menu for roles.

### ISSUE THREAD

**Issue by wvffle** [thedevdojo/voyager#4086]
## Description of problem

Custom admin menu for roles.

## Proposed solution
Connect roles to menu types in the builder.

## Additional context
I've tried to check for users role and display another menu in `sidebar.blade.php` like this:
```blade
        <div id="adminmenu">
          @if (app('VoyagerAuth')->user()->hasRole('reception'))
            <admin-menu :items="{{ menu('reception', '_json') }}"></admin-menu>
          @else
            <admin-menu :items="{{ menu('admin', '_json') }}"></admin-menu>
          @endif
        </div>
```

But I ran into a problem where the links were not working. I had to remove the check for `$menuName` in `src/Models/Menu.php` as follows and it works now but with any update I'd have to do it again :<

```php
        if ($type == '_json') {
            $items = static::processItems($items);
        }
```

**Comment by fletch3555** [comment]
The full issue template is required, including version number.

This has been requested numerous times, and almost always ends in an answer to use permissions and a single menu since permissions are already tied to roles

**Comment by ghost** [comment]
Please help me
I am having issue with roles how can I prevent admin from being edit self or to make any other user super admin. Admin should not even able to delete the super admin user.  I am using voyager 1.2 with laravel 5.8

**Comment by emptynick** [comment]
This is not the place to ask for this.
See https://github.com/the-control-group/voyager/issues/3852

**Comment by danielorkae** [comment]
i've added a pull request to solve this feat.
see: https://github.com/the-control-group/voyager/pull/4107

**Comment by emptynick** [comment]
Closing.
Please see the discussion on why here: https://github.com/the-control-group/voyager/pull/4107

**Comment by nuhu-ibrahim** [comment]
Follow the link [here](https://nuhuibrahim.com/blog/using-multiple-menu-builder-in-laravel-voyager) to see my solution that is permanent to this problem.
