### ISSUE TITLE
Migration avoids Primary Auto Increment Key

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4088]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MySQL 5.6.39

## Description
I Recently migrated the Laravel App from Local Development Environment to Production Server. I Performed Migration and it was done without any error. But Migration does not add Primary Auto Increment Key. However, I solved it by manually adding Primary Key from the database server, But it should be reported as unexpected behavior. 

## Steps To Reproduce
1. Create a Laravel Project in Local Env. and make 1 or 2 dummy tables with migration.
2. Copy that project and host it on production environment
3. Setup Database and configure .env file
4. Run **php artisan:migrate** command
5. Go to Database server and check the structure.

## Expected behavior
The Database structure should be the same as defined in migration

## Additional context
I have solved that issue by manual restoration on the database. I'm using Voyager as BREAD builder. maybe it's causing the issue.

**Comment by fletch3555** [comment]
I'm failing to see how this is related to Voyager.... Voyager does nothing specific with migrations; that's all default Laravel functionality.  If you're failing to get auto-incrementing primary keys created with your existing migrations, then either there's a bug in Laravel/Elequent, or (much more likely) you have an issue with your migrations.  However, neither of these are related to Voyager at all.

**Comment by emptynick** [comment]
Closing as it seems to be not Voyager related.
