### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4090]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1
 - Database: [type] [version] (e.g. MySQL 8.0)  Server version: 5.5.5-10.1.26-MariaDB (XAMPP MySQL)

## Description

After registering new user. Admin is able to control that user's role and permission but admin is able to edit super user already in the users table or may provide self or to any user the role of super user which should not be done. Please explain this or with code how can I achieve that. I am new to Laravel.

## Steps To Reproduce
1. Go to 'Dashboard'
2. Click on 'Users Menu'
3. Click on Edit or Delete
4. See If admin is login, admin not able to edit,delete super user also admin must not be able to provide self or to any user super user role.

## Expected behavior
User table displaying all users, admin, super user. So if admin is login admin is not able to provide any other user or to self the role of super user or delete super user. But Super user can do everything only admin is restricted to super role.

## Screenshots
![1](https://user-images.githubusercontent.com/49336866/56347751-97469800-61e2-11e9-8dcf-e7452e46dc6a.jpg)
![2](https://user-images.githubusercontent.com/49336866/56347760-9ada1f00-61e2-11e9-9f20-14e9924b0051.jpg)

## Additional context
NO, please just help me out of the above problem.

**Comment by emptynick** [comment]
Not a bug.
You already asked in our Slack group and will get help there.
