### ISSUE TITLE
[BUG]The structure of menu items in some child elements is not preserved.

### ISSUE THREAD

**Issue by Dos771** [thedevdojo/voyager#4092]
## Version information

 - Laravel: v5.5.44
 - Voyager: v1.1.3
 - PHP: 7.1
 - Database: MySQL 5.7

## Description

Hello everyone, May you give a hint? 
When I try to change the order in some menu item, after saving and refreshing the page, it returns to the previous position. 
It is not with all the menu items on the site but only in some places.
In the screenshot, I clearly marked before and after.

## Steps To Reproduce
1. I go menu, menu name: public
2. Create a menu item or drag an existing item, and assign the third child subcategory.
3. I update the page
4. Those elements that have changed are put in their places, as it was before.

## Expected behavior
All menu items after dragging should keep their current positions.

## Screenshots
https://kazmuno.kz/storage/FAR/save1.png - Before
https://kazmuno.kz/storage/FAR/save2.png - After

## Additional context
1)The most interesting thing: The database maintains the correct order for which changed through drag and drop in the order column.
2) I tried to create, delete, change the menu name, it still goes down.
3) Tried to manually change the order in the database column, also without results.
4) Cleared the cache, also useless
5) Tried to make a similar or different structure to the menu item in Russian, you can look at the screenshot: "Учебно-методический комплекс дисциплин" Always the first
6) Not only with these elements, sometimes it happens with other menu elements.

**Comment by Dos771** [comment]
I added in the file admin.blade.php to the cycle items-> `@foreach ($items->sortBy('order') as $item)`
did the same on the side of my template `@foreach ($items->sortBy('order') as $item)`  

Now it works correctly

**Comment by fletch3555** [comment]
Pull Requests are welcomed.  I have no idea what you changed since you only provided a single line with no context

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4083
