### ISSUE TITLE
[Suggestion] Primary keys in voyager migrations

### ISSUE THREAD

**Issue by ptr2null** [thedevdojo/voyager#4094]
I really like this admin package, but **why bigInteger?** in tables?

I'd had to change something in the user-table of laravel and changed the primary key to `smallIncrements`. While migration with Laravels artisan, it threw an error and I've narrowed it down that a foreign key to the pk of the user table was typed as `bigInteger`.

I don't want to discuss any performance wars about it, which is bullsh** nonetheless. However actually I was baffled that the primary keys in all of voyagers tables have at least the size of an normal integer - 32 bit. For [roles table](https://github.com/the-control-group/voyager/blob/1.2/migrations/2016_10_21_190000_create_roles_table.php) even 64-bit! ***Seriously?*** Who in this world makes 18.4 quintillion roles (!) in production?
There are use cases which need more than a 32-bit integer, even more than 64-bit. But not for security roles. 

Thus I had to change those to realistic types. Why?
Programmers should use what is needed and not using the maximum for everything. IMO it is a lazy attitude and leads to bad code. That those big numbers were used just for the sake of simplicity is not an argument in the programming world.

I would strongly suggest to change these types. I can pull the changes if you want to review it.

**Comment by emptynick** [comment]
Simple answer: because [Laravel did it](https://github.com/laravel/framework/pull/26472).
We had to adapt a [few migrations](https://github.com/the-control-group/voyager/pull/3974/commits/d65495460a050f7b85de374e17bbb4ced511ccaa) because the roles pivot-table references user-id.
It would simply fail when installing Voyager.
If you want to change it, you can.
Laravel allows you to override package-migrations by simply copying them into `database/migrations` (keeping the filename)

**Comment by fletch3555** [comment]
Everything that @emptynick said.

Also, I would caution you to watch your tone. I understand the frustration, but lashing out at devs that do this for the community (and receive no compensation) is a very good way to make us all want to quit and kill the project entirely.  You don't have to agree with every decision we make, but I strongly urge you to calmly seek understanding before letting emotion take over.  99+% of the time, there will be a completely logical reason behind that decision, and it's not infrequently out of our control.
