### ISSUE TITLE
[BUG] Can't delete uploaded files from BREAD form without browse_media permission

### ISSUE THREAD

**Issue by MrCrayon** [thedevdojo/voyager#4095]
## Version information

 - Laravel: v5.8.3
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MariaDB 10.3.12

## Description
Can't delete uploaded files from BREAD form without browse_media permission

## Steps To Reproduce
1. Install Voyager
2. Create a BREAD with one image or file field (Pages can be used if voyager has been installed with-dummy)
2. Remove browse_media permission from current role
3. Create an entry for BREAD with an image or file
4. Edit the entry and try to remove image or file

## Expected behavior
The image or file should be cleared from the entry and removed from file system.

## Screenshots
![Schermata da 2019-04-22 10-53-01](https://user-images.githubusercontent.com/6875243/56492856-50f87e00-64ed-11e9-8641-91c237d7c7d1.png)

## Additional context
This is because voyager uses VoyagerMediaController to remove attachments for all BREAD so right now the only way to let a user delete a previously uploaded image/files is grant that user browse_media permission that gives complete access to all media gallery.
I think this should be handled by VoyagerBaseController.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4113 (merged into 1.x)
