### ISSUE TITLE
[Feature] Change File upload method to Ajax.

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#410]
I know that this would add complexity to the file uploader, but especially for images it makes more sense to have it uploading by Ajax so a preview can be shown without refreshing the page.

**Comment by marco-solare** [comment]
Hey @marktopper I implemented that a couple of times with pure js and angular 1.x
It might be a nice feature to create image galleries quickly and easily.
maybe when 1.0 is out the door let's talk about it, I could do at least the frontend part I guess

**Comment by handiwijoyo** [comment]
Close this issue for now. Please reopen the issue if you want to continue it.
