### ISSUE TITLE
jQuery File Upload - album feature

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4101]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MYSQL 8

Multiple image upload process should be optimized,jQuery File Upload should be used to see upload progress and see thumbnail at the same time

## Proposed solution
jQuery File Upload should be used to see upload progress and see thumbnail at the same time

any suggestions?

**Comment by emptynick** [comment]
Thats all implemented when using the media-picker.

**Comment by shafiqkr18** [comment]
There is no drag & drop feature in media-picker. It is not the same as drop zone
