### ISSUE TITLE
How to increase the quality of uploaded images in settings section

### ISSUE THREAD

**Issue by sarxan26** [thedevdojo/voyager#4105]
## Version information

 - Laravel: v5.8.14
 - Voyager: v1.2.3
 - PHP: 7.3.2
 - Database: [MySQl] [5.7.25] (e.g. MySQL 8.0)

## Description:
Is there any way how to increase the quality of uploaded images in settings section?

**Comment by NurdaKz** [comment]
https://docs.laravelvoyager.com/core-concepts/bread-builder#image

{
    "quality" : "100%",
}

**Comment by sarxan26** [comment]
Thanks for your response, but where to add this param

**Comment by sarxan26** [comment]
Thanks for your response, but as you can see in this attached photo, this paramets field is only for radio buttons and dropdowns and it's not accepting quality option.
![DD](https://user-images.githubusercontent.com/5292115/56941886-604c7c80-6b28-11e9-9c1f-02738f4ab084.PNG)

**Comment by NurdaKz** [comment]
YOUR_DOMEN/admin/bread

click on the button to edit the required table. 

![image](https://user-images.githubusercontent.com/50044259/56941928-79a9f480-6b39-11e9-9dfb-b5aa40046b87.png)

Надо зайти в BREAD  /admin/bread, затем нажать РЕДАКТИРОВАТЬ (для нужной таблиц) 

В нужном поле, в колонке "Дополнительные сведения" добавить этот код:
`{`
`"quality" : "100%"`
`}`

**Comment by sarxan26** [comment]
Yeah, but the settings table is not displayed there.
