### ISSUE TITLE
User with 'editor' role can't modify his profile

### ISSUE THREAD

**Issue by MIntranet** [thedevdojo/voyager#4109]
## Versions
 - Laravel: v5.7
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
I've created a user with "Editor" role. When user tries to edit his profile (for example wants to change password) the 'role' and 'roles' fields are updated with 'null' and user gets 503 error.

## Steps to reproduce
 - Add new Role (Editor) with access to 'users' but no access to 'roles'
 - Add a user account (role: Editor)
 - Log into that account
 - Modify your password
 - Save

**Comment by emptynick** [comment]
Did you upgrade from 1.1 or another version?

**Comment by MrCrayon** [comment]
Just tried on a fresh install and I cannot reproduce the issue.

As @emptynick said it looks like there is some left over from previous versions.
What's the output of:
```shell
php artisan route:list
```
for voyager.users.update line.
There should be: TCG\Voyager\Http\Controllers\VoyagerUserController@update

**Comment by MIntranet** [comment]
I've made a clean install of 1.2.3 (removed vendor and 'composer install').

For voyager.users.update I've got: TCG\Voyager\Http\Controllers\VoyagerBaseController@update 
So I think the problem is the VoyagerBaseController instead of VoyagerUserController. The only question is: why?

**Comment by MrCrayon** [comment]
Because removing vendor and redoing composer install is not a clean install.
If you are coming from an older version you should follow upgrade guides, this is from 1.1 to 1.2:
https://docs.laravelvoyager.com/getting-started/upgrading

**Comment by MIntranet** [comment]
That solves it. Thank you. 
[User BREAD](https://docs.laravelvoyager.com/getting-started/upgrading#user-bread) needed a controller update.
