### ISSUE TITLE
All files from media Can't be found after upload to hosting

### ISSUE THREAD

**Issue by NicolaeCasir** [thedevdojo/voyager#411]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.2
- PHP Version: 7.0
- Database Driver & Version: MYSQL VERSION - 5.6

### Description:
Failed to load resource: the server responded with a status of 404 (Not Found)

After i uploaded my site to hosting, he cant find images... files are successful uploaded but....

U can see this here: http://art-fire.de

I use images in this mode:
`<img src="{{ asset($test->img) }}" alt="SomeTitle">`

**Comment by ghost** [comment]
What happens if you do `{{ Storage::url($test->img) }}`?

**Comment by NicolaeCasir** [comment]
`<img src="/storage/works/December2016/l0DWpBg33u9DYohZ1Sig.jpg" alt="Artfire Work">`

And anyway wasnt found. I think problem is in /public/storage (symbolic link), on shared hosting i can not create symbolic link((

**Comment by AlirezaMirghasemi** [comment]
me too , after upload my project on shared host , when upload some file , my file wont upload any where.
please help me 
tnx :*

**Comment by handiwijoyo** [comment]
Can you run `php artisan storage:link` ?

**Comment by AlirezaMirghasemi** [comment]
yes but is say : 
The system cannot find the path specified.
The [public/storage] directory has been linked.
my project directory like attached img
![dir](https://cloud.githubusercontent.com/assets/19419828/21300661/25e82dec-c5bb-11e6-8d16-ccadac430a6f.png)

**Comment by handiwijoyo** [comment]
I see that your folder structure is different from default Laravel. Try using default laravel, and point your host root folder to `/public_html/public` . If that work, you can restructure your folder, at least you know what you are doing.

**Comment by AlirezaMirghasemi** [comment]
Beacuase of my shared host i most use this structure,doesn't have any solution for using current structure ?

**Comment by handiwijoyo** [comment]
You can move your laravel app folder to outside/parent of `public_html` then delete the `public_html` folder and create an new link from public to public_html
```
rm -rf public_html
ln -s laravel/public/ public_html
```

**Comment by NicolaeCasir** [comment]
@handiwijoyo, when i run `php artisan storage:link` i get `[ErrorException]                                                                                                                                                                                   
  is_file(): open_basedir restriction in effect. File(/opt/php-7.0/bin/php) is not within the allowed path(s): (/home/u101704751:/tmp:/var/tmp:/opt/php-7.0/pear:/usr/local/bin:/etc/pki/tls/certs)`

**Comment by NicolaeCasir** [comment]
P.S. In 2 days i will buy hosting from godaddy. They have symbolic links. I will try and hope all will work fine!

**Comment by marktopper** [comment]
Symbolic links are required to get Voyager's storage files to work.

**Comment by fletch3555** [comment]
@NicolaeCasir, the error you posted seems to be an issue with running PHP on the command-line, not an issue with creating symlinks.
