### ISSUE TITLE
Undefined variable: usesSoftDeletes 

### ISSUE THREAD

**Issue by pfndesign** [thedevdojo/voyager#4114]
## Version information
 - Laravel: v5.7.28
 - Voyager: v1.2
 - PHP: 7.2.10
 - Database: mysql 10.1

## Description
after installing voyager with dummy data on my project when I want to use pages like posts, users, category this error appears

**Comment by emptynick** [comment]
Please provide more information, like a screenshot of the error-page and the steps to reproduce.

**Comment by pfndesign** [comment]
screenshot : https://imgur.com/SW4JGPh
steps : install voyager with dummy data
2 - login
3 - go to posts tabs
4 - error

**Comment by jjasspper** [comment]
I have this error as well. I only have this issue when loading posts per category.

**Comment by jjasspper** [comment]
We found a solution, in your Controller change the `Voyager::view('voyager::bread.browse', compact('your params'))` to `Voyager::view('voyager::posts.browse', compact('your params'))`.

The error is something you can't make much out of, so it might be good to change the error message..

**Comment by BOLYAC** [comment]
@jjasspper dosn't work for me 🤕

**Comment by emptynick** [comment]
For the records. The variable is defined here:
https://github.com/the-control-group/voyager/blob/d506a352b5db9b170dfbb49fab1a8118fbdd580a/src/Http/Controllers/VoyagerBaseController.php#L50
And passed to the view here:
https://github.com/the-control-group/voyager/blob/d506a352b5db9b170dfbb49fab1a8118fbdd580a/src/Http/Controllers/VoyagerBaseController.php#L141

If you have a custom controller (which is NOT in your steps to reproduce) just define it as false.
