### ISSUE TITLE
The requested URL /admin was not found on this server. 

### ISSUE THREAD

**Issue by tyndouf** [thedevdojo/voyager#4116]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: [Mysql] [ 5.6.37] 

## Description:
I got the following error message when accessing /admin route 
 The requested URL /admin was not found on this server. 

I have mode rewrite enabled .

Here is my .htaccess file content of my public folder 👍 
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

In advance thank you for your help.

**Comment by minhdanh** [comment]
What is the output when you run `php artisan route:list`?

**Comment by tyndouf** [comment]
php artisan route:list
+--------+-----------+--------------------------------------+-----------------------------------+------------------------------------------------------------------------+----------------+
| Domain | Method    | URI                                  | Name                              | Action                                                                 | Middleware     |
+--------+-----------+--------------------------------------+-----------------------------------+------------------------------------------------------------------------+----------------+
|        | GET|HEAD  | /                                    |                                   | Closure                                                                | web            |
|        | GET|HEAD  | admin                                | voyager.dashboard                 | TCG\Voyager\Http\Controllers\VoyagerController@index                   | web,admin.user |
|        | GET|HEAD  | admin/assets                         | voyager.assets                    | TCG\Voyager\Http\Controllers\VoyagerController@assets                  | web            |
|        | POST      | admin/bread                          | voyager.bread.store               | TCG\Voyager\Http\Controllers\VoyagerBreadController@store              | web,admin.user |
|        | GET|HEAD  | admin/bread                          | voyager.bread.index               | TCG\Voyager\Http\Controllers\VoyagerBreadController@index              | web,admin.user |
|        | GET|HEAD  | admin/bread/delete_relationship/{id} | voyager.bread.delete_relationship | TCG\Voyager\Http\Controllers\VoyagerBreadController@deleteRelationship | web,admin.user |
|        | POST      | admin/bread/relationship             | voyager.bread.relationship        | TCG\Voyager\Http\Controllers\VoyagerBreadController@addRelationship    | web,admin.user |
|        | PUT       | admin/bread/{id}                     | voyager.bread.update              | TCG\Voyager\Http\Controllers\VoyagerBreadController@update             | web,admin.user |
|        | DELETE    | admin/bread/{id}                     | voyager.bread.delete              | TCG\Voyager\Http\Controllers\VoyagerBreadController@destroy            | web,admin.user |
|        | GET|HEAD  | admin/bread/{table}/create           | voyager.bread.create              | TCG\Voyager\Http\Controllers\VoyagerBreadController@create             | web,admin.user |
|        | GET|HEAD  | admin/bread/{table}/edit             | voyager.bread.edit                | TCG\Voyager\Http\Controllers\VoyagerBreadController@edit               | web,admin.user |
|        | POST      | admin/categories                     | voyager.categories.store          | TCG\Voyager\Http\Controllers\VoyagerBaseController@store               | web,admin.user |
|        | GET|HEAD  | admin/categories                     | voyager.categories.index          | TCG\Voyager\Http\Controllers\VoyagerBaseController@index               | web,admin.user |
|        | POST      | admin/categories/action              | voyager.categories.action         | TCG\Voyager\Http\Controllers\VoyagerBaseController@action              | web,admin.user |
|        | GET|HEAD  | admin/categories/create              | voyager.categories.create         | TCG\Voyager\Http\Controllers\VoyagerBaseController@create              | web,admin.user |
|        | GET|HEAD  | admin/categories/order               | voyager.categories.order          | TCG\Voyager\Http\Controllers\VoyagerBaseController@order               | web,admin.user |
|        | POST      | admin/categories/order               | voyager.categories.order          | TCG\Voyager\Http\Controllers\VoyagerBaseController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/categories/relation            | voyager.categories.relation       | TCG\Voyager\Http\Controllers\VoyagerBaseController@relation            | web,admin.user |
|        | GET|HEAD  | admin/categories/{category}          | voyager.categories.show           | TCG\Voyager\Http\Controllers\VoyagerBaseController@show                | web,admin.user |
|        | PUT|PATCH | admin/categories/{category}          | voyager.categories.update         | TCG\Voyager\Http\Controllers\VoyagerBaseController@update              | web,admin.user |
|        | DELETE    | admin/categories/{category}          | voyager.categories.destroy        | TCG\Voyager\Http\Controllers\VoyagerBaseController@destroy             | web,admin.user |
|        | GET|HEAD  | admin/categories/{category}/edit     | voyager.categories.edit           | TCG\Voyager\Http\Controllers\VoyagerBaseController@edit                | web,admin.user |
|        | GET|HEAD  | admin/categories/{id}/restore        | voyager.categories.restore        | TCG\Voyager\Http\Controllers\VoyagerBaseController@restore             | web,admin.user |
|        | GET|HEAD  | admin/compass                        | voyager.compass.index             | TCG\Voyager\Http\Controllers\VoyagerCompassController@index            | web,admin.user |
|        | POST      | admin/compass                        | voyager.compass.post              | TCG\Voyager\Http\Controllers\VoyagerCompassController@index            | web,admin.user |
|        | GET|HEAD  | admin/database                       | voyager.database.index            | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@index           | web,admin.user |
|        | POST      | admin/database                       | voyager.database.store            | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@store           | web,admin.user |
|        | GET|HEAD  | admin/database/create                | voyager.database.create           | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@create          | web,admin.user |
|        | PUT|PATCH | admin/database/{database}            | voyager.database.update           | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@update          | web,admin.user |
|        | DELETE    | admin/database/{database}            | voyager.database.destroy          | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@destroy         | web,admin.user |
|        | GET|HEAD  | admin/database/{database}            | voyager.database.show             | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@show            | web,admin.user |
|        | GET|HEAD  | admin/database/{database}/edit       | voyager.database.edit             | TCG\Voyager\Http\Controllers\VoyagerDatabaseController@edit            | web,admin.user |
|        | GET|HEAD  | admin/hooks                          | voyager.hooks                     | Larapack\VoyagerHooks\Controllers\HooksController@index                | web,admin.user |
|        | POST      | admin/hooks                          | voyager.hooks.install             | Larapack\VoyagerHooks\Controllers\HooksController@install              | web,admin.user |
|        | DELETE    | admin/hooks/{name}                   | voyager.hooks.uninstall           | Larapack\VoyagerHooks\Controllers\HooksController@uninstall            | web,admin.user |
|        | GET|HEAD  | admin/hooks/{name}/disable           | voyager.hooks.disable             | Larapack\VoyagerHooks\Controllers\HooksController@disable              | web,admin.user |
|        | GET|HEAD  | admin/hooks/{name}/enable            | voyager.hooks.enable              | Larapack\VoyagerHooks\Controllers\HooksController@enable               | web,admin.user |
|        | GET|HEAD  | admin/hooks/{name}/update            | voyager.hooks.update              | Larapack\VoyagerHooks\Controllers\HooksController@update               | web,admin.user |
|        | POST      | admin/login                          | voyager.postlogin                 | TCG\Voyager\Http\Controllers\VoyagerAuthController@postLogin           | web            |
|        | GET|HEAD  | admin/login                          | voyager.login                     | TCG\Voyager\Http\Controllers\VoyagerAuthController@login               | web            |
|        | POST      | admin/logout                         | voyager.logout                    | TCG\Voyager\Http\Controllers\VoyagerController@logout                  | web,admin.user |
|        | GET|HEAD  | admin/media                          | voyager.media.index               | TCG\Voyager\Http\Controllers\VoyagerMediaController@index              | web,admin.user |
|        | POST      | admin/media/crop                     | voyager.media.crop                | TCG\Voyager\Http\Controllers\VoyagerMediaController@crop               | web,admin.user |
|        | POST      | admin/media/delete_file_folder       | voyager.media.delete              | TCG\Voyager\Http\Controllers\VoyagerMediaController@delete             | web,admin.user |
|        | POST      | admin/media/files                    | voyager.media.files               | TCG\Voyager\Http\Controllers\VoyagerMediaController@files              | web,admin.user |
|        | POST      | admin/media/move_file                | voyager.media.move                | TCG\Voyager\Http\Controllers\VoyagerMediaController@move               | web,admin.user |
|        | POST      | admin/media/new_folder               | voyager.media.new_folder          | TCG\Voyager\Http\Controllers\VoyagerMediaController@new_folder         | web,admin.user |
|        | POST      | admin/media/remove                   | voyager.media.remove              | TCG\Voyager\Http\Controllers\VoyagerMediaController@remove             | web,admin.user |
|        | POST      | admin/media/rename_file              | voyager.media.rename              | TCG\Voyager\Http\Controllers\VoyagerMediaController@rename             | web,admin.user |
|        | POST      | admin/media/upload                   | voyager.media.upload              | TCG\Voyager\Http\Controllers\VoyagerMediaController@upload             | web,admin.user |
|        | POST      | admin/menus                          | voyager.menus.store               | TCG\Voyager\Http\Controllers\VoyagerBaseController@store               | web,admin.user |
|        | GET|HEAD  | admin/menus                          | voyager.menus.index               | TCG\Voyager\Http\Controllers\VoyagerBaseController@index               | web,admin.user |
|        | POST      | admin/menus/action                   | voyager.menus.action              | TCG\Voyager\Http\Controllers\VoyagerBaseController@action              | web,admin.user |
|        | GET|HEAD  | admin/menus/create                   | voyager.menus.create              | TCG\Voyager\Http\Controllers\VoyagerBaseController@create              | web,admin.user |
|        | POST      | admin/menus/order                    | voyager.menus.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/menus/order                    | voyager.menus.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@order               | web,admin.user |
|        | GET|HEAD  | admin/menus/relation                 | voyager.menus.relation            | TCG\Voyager\Http\Controllers\VoyagerBaseController@relation            | web,admin.user |
|        | GET|HEAD  | admin/menus/{id}/restore             | voyager.menus.restore             | TCG\Voyager\Http\Controllers\VoyagerBaseController@restore             | web,admin.user |
|        | PUT|PATCH | admin/menus/{menu}                   | voyager.menus.update              | TCG\Voyager\Http\Controllers\VoyagerBaseController@update              | web,admin.user |
|        | GET|HEAD  | admin/menus/{menu}                   | voyager.menus.show                | TCG\Voyager\Http\Controllers\VoyagerBaseController@show                | web,admin.user |
|        | DELETE    | admin/menus/{menu}                   | voyager.menus.destroy             | TCG\Voyager\Http\Controllers\VoyagerBaseController@destroy             | web,admin.user |
|        | GET|HEAD  | admin/menus/{menu}/builder           | voyager.menus.builder             | TCG\Voyager\Http\Controllers\VoyagerMenuController@builder             | web,admin.user |
|        | GET|HEAD  | admin/menus/{menu}/edit              | voyager.menus.edit                | TCG\Voyager\Http\Controllers\VoyagerBaseController@edit                | web,admin.user |
|        | POST      | admin/menus/{menu}/item              | voyager.menus.item.add            | TCG\Voyager\Http\Controllers\VoyagerMenuController@add_item            | web,admin.user |
|        | PUT       | admin/menus/{menu}/item              | voyager.menus.item.update         | TCG\Voyager\Http\Controllers\VoyagerMenuController@update_item         | web,admin.user |
|        | DELETE    | admin/menus/{menu}/item/{id}         | voyager.menus.item.destroy        | TCG\Voyager\Http\Controllers\VoyagerMenuController@delete_menu         | web,admin.user |
|        | POST      | admin/menus/{menu}/order             | voyager.menus.order               | TCG\Voyager\Http\Controllers\VoyagerMenuController@order_item          | web,admin.user |
|        | GET|HEAD  | admin/pages                          | voyager.pages.index               | TCG\Voyager\Http\Controllers\VoyagerBaseController@index               | web,admin.user |
|        | POST      | admin/pages                          | voyager.pages.store               | TCG\Voyager\Http\Controllers\VoyagerBaseController@store               | web,admin.user |
|        | POST      | admin/pages/action                   | voyager.pages.action              | TCG\Voyager\Http\Controllers\VoyagerBaseController@action              | web,admin.user |
|        | GET|HEAD  | admin/pages/create                   | voyager.pages.create              | TCG\Voyager\Http\Controllers\VoyagerBaseController@create              | web,admin.user |
|        | GET|HEAD  | admin/pages/order                    | voyager.pages.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@order               | web,admin.user |
|        | POST      | admin/pages/order                    | voyager.pages.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/pages/relation                 | voyager.pages.relation            | TCG\Voyager\Http\Controllers\VoyagerBaseController@relation            | web,admin.user |
|        | GET|HEAD  | admin/pages/{id}/restore             | voyager.pages.restore             | TCG\Voyager\Http\Controllers\VoyagerBaseController@restore             | web,admin.user |
|        | DELETE    | admin/pages/{page}                   | voyager.pages.destroy             | TCG\Voyager\Http\Controllers\VoyagerBaseController@destroy             | web,admin.user |
|        | PUT|PATCH | admin/pages/{page}                   | voyager.pages.update              | TCG\Voyager\Http\Controllers\VoyagerBaseController@update              | web,admin.user |
|        | GET|HEAD  | admin/pages/{page}                   | voyager.pages.show                | TCG\Voyager\Http\Controllers\VoyagerBaseController@show                | web,admin.user |
|        | GET|HEAD  | admin/pages/{page}/edit              | voyager.pages.edit                | TCG\Voyager\Http\Controllers\VoyagerBaseController@edit                | web,admin.user |
|        | POST      | admin/posts                          | voyager.posts.store               | TCG\Voyager\Http\Controllers\VoyagerBaseController@store               | web,admin.user |
|        | GET|HEAD  | admin/posts                          | voyager.posts.index               | TCG\Voyager\Http\Controllers\VoyagerBaseController@index               | web,admin.user |
|        | POST      | admin/posts/action                   | voyager.posts.action              | TCG\Voyager\Http\Controllers\VoyagerBaseController@action              | web,admin.user |
|        | GET|HEAD  | admin/posts/create                   | voyager.posts.create              | TCG\Voyager\Http\Controllers\VoyagerBaseController@create              | web,admin.user |
|        | GET|HEAD  | admin/posts/order                    | voyager.posts.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@order               | web,admin.user |
|        | POST      | admin/posts/order                    | voyager.posts.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/posts/relation                 | voyager.posts.relation            | TCG\Voyager\Http\Controllers\VoyagerBaseController@relation            | web,admin.user |
|        | GET|HEAD  | admin/posts/{id}/restore             | voyager.posts.restore             | TCG\Voyager\Http\Controllers\VoyagerBaseController@restore             | web,admin.user |
|        | DELETE    | admin/posts/{post}                   | voyager.posts.destroy             | TCG\Voyager\Http\Controllers\VoyagerBaseController@destroy             | web,admin.user |
|        | GET|HEAD  | admin/posts/{post}                   | voyager.posts.show                | TCG\Voyager\Http\Controllers\VoyagerBaseController@show                | web,admin.user |
|        | PUT|PATCH | admin/posts/{post}                   | voyager.posts.update              | TCG\Voyager\Http\Controllers\VoyagerBaseController@update              | web,admin.user |
|        | GET|HEAD  | admin/posts/{post}/edit              | voyager.posts.edit                | TCG\Voyager\Http\Controllers\VoyagerBaseController@edit                | web,admin.user |
|        | GET|HEAD  | admin/profile                        | voyager.profile                   | TCG\Voyager\Http\Controllers\VoyagerUserController@profile             | web,admin.user |
|        | POST      | admin/roles                          | voyager.roles.store               | TCG\Voyager\Http\Controllers\VoyagerRoleController@store               | web,admin.user |
|        | GET|HEAD  | admin/roles                          | voyager.roles.index               | TCG\Voyager\Http\Controllers\VoyagerRoleController@index               | web,admin.user |
|        | POST      | admin/roles/action                   | voyager.roles.action              | TCG\Voyager\Http\Controllers\VoyagerBaseController@action              | web,admin.user |
|        | GET|HEAD  | admin/roles/create                   | voyager.roles.create              | TCG\Voyager\Http\Controllers\VoyagerRoleController@create              | web,admin.user |
|        | GET|HEAD  | admin/roles/order                    | voyager.roles.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@order               | web,admin.user |
|        | POST      | admin/roles/order                    | voyager.roles.order               | TCG\Voyager\Http\Controllers\VoyagerBaseController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/roles/relation                 | voyager.roles.relation            | TCG\Voyager\Http\Controllers\VoyagerBaseController@relation            | web,admin.user |
|        | GET|HEAD  | admin/roles/{id}/restore             | voyager.roles.restore             | TCG\Voyager\Http\Controllers\VoyagerBaseController@restore             | web,admin.user |
|        | DELETE    | admin/roles/{role}                   | voyager.roles.destroy             | TCG\Voyager\Http\Controllers\VoyagerRoleController@destroy             | web,admin.user |
|        | PUT|PATCH | admin/roles/{role}                   | voyager.roles.update              | TCG\Voyager\Http\Controllers\VoyagerRoleController@update              | web,admin.user |
|        | GET|HEAD  | admin/roles/{role}                   | voyager.roles.show                | TCG\Voyager\Http\Controllers\VoyagerRoleController@show                | web,admin.user |
|        | GET|HEAD  | admin/roles/{role}/edit              | voyager.roles.edit                | TCG\Voyager\Http\Controllers\VoyagerRoleController@edit                | web,admin.user |
|        | PUT       | admin/settings                       | voyager.settings.update           | TCG\Voyager\Http\Controllers\VoyagerSettingsController@update          | web,admin.user |
|        | GET|HEAD  | admin/settings                       | voyager.settings.index            | TCG\Voyager\Http\Controllers\VoyagerSettingsController@index           | web,admin.user |
|        | POST      | admin/settings                       | voyager.settings.store            | TCG\Voyager\Http\Controllers\VoyagerSettingsController@store           | web,admin.user |
|        | DELETE    | admin/settings/{id}                  | voyager.settings.delete           | TCG\Voyager\Http\Controllers\VoyagerSettingsController@delete          | web,admin.user |
|        | PUT       | admin/settings/{id}/delete_value     | voyager.settings.delete_value     | TCG\Voyager\Http\Controllers\VoyagerSettingsController@delete_value    | web,admin.user |
|        | GET|HEAD  | admin/settings/{id}/move_down        | voyager.settings.move_down        | TCG\Voyager\Http\Controllers\VoyagerSettingsController@move_down       | web,admin.user |
|        | GET|HEAD  | admin/settings/{id}/move_up          | voyager.settings.move_up          | TCG\Voyager\Http\Controllers\VoyagerSettingsController@move_up         | web,admin.user |
|        | POST      | admin/upload                         | voyager.upload                    | TCG\Voyager\Http\Controllers\VoyagerController@upload                  | web,admin.user |
|        | GET|HEAD  | admin/users                          | voyager.users.index               | TCG\Voyager\Http\Controllers\VoyagerUserController@index               | web,admin.user |
|        | POST      | admin/users                          | voyager.users.store               | TCG\Voyager\Http\Controllers\VoyagerUserController@store               | web,admin.user |
|        | POST      | admin/users/action                   | voyager.users.action              | TCG\Voyager\Http\Controllers\VoyagerUserController@action              | web,admin.user |
|        | GET|HEAD  | admin/users/create                   | voyager.users.create              | TCG\Voyager\Http\Controllers\VoyagerUserController@create              | web,admin.user |
|        | POST      | admin/users/order                    | voyager.users.order               | TCG\Voyager\Http\Controllers\VoyagerUserController@update_order        | web,admin.user |
|        | GET|HEAD  | admin/users/order                    | voyager.users.order               | TCG\Voyager\Http\Controllers\VoyagerUserController@order               | web,admin.user |
|        | GET|HEAD  | admin/users/relation                 | voyager.users.relation            | TCG\Voyager\Http\Controllers\VoyagerUserController@relation            | web,admin.user |
|        | GET|HEAD  | admin/users/{id}/restore             | voyager.users.restore             | TCG\Voyager\Http\Controllers\VoyagerUserController@restore             | web,admin.user |
|        | GET|HEAD  | admin/users/{user}                   | voyager.users.show                | TCG\Voyager\Http\Controllers\VoyagerUserController@show                | web,admin.user |
|        | PUT|PATCH | admin/users/{user}                   | voyager.users.update              | TCG\Voyager\Http\Controllers\VoyagerUserController@update              | web,admin.user |
|        | DELETE    | admin/users/{user}                   | voyager.users.destroy             | TCG\Voyager\Http\Controllers\VoyagerUserController@destroy             | web,admin.user |
|        | GET|HEAD  | admin/users/{user}/edit              | voyager.users.edit                | TCG\Voyager\Http\Controllers\VoyagerUserController@edit                | web,admin.user |
|        | GET|HEAD  | api/user                             |                                   | Closure                                                                | api,auth:api   |
|        | GET|HEAD  | arrilot/load-widget                  |                                   | Arrilot\Widgets\Controllers\WidgetController@showWidget                | web            |
+--------+-----------+--------------------------------------+-----------------------------------+------------------------------------------------------------------------+----------------+

**Comment by minhdanh** [comment]
The routes look good. So I suspect that mod rewrite not working correctly.
What is the apache config for the directory of the site?
Does it work if you use PHP built-in webserver instead: `php artisan serve --port=8080`?

**Comment by fletch3555** [comment]
Not a Voyager issue.  Please ask questions in our Slack group
