### ISSUE TITLE
[BUG] Missing storage symlink + Error rename(F:\Voyager\Project\Voyager\public\storage,storage_old): Access is denied. (code: 5)

### ISSUE THREAD

**Issue by ssAlixss** [thedevdojo/voyager#4120]
Hi 
Error in Panel Admin

> Missing storage symlink We could not find a storage symlink. This could cause problems with loading media files from the browser.

when i click on Button (fix it)

Affer Error

> rename(F:\Voyager\Project\Voyager\public\storage,storage_old): Access is denied. (code: 5)

Why ??

**Comment by emptynick** [comment]
Please use the issue template.
This can be reopened once the required informations are provided

**Comment by ssAlixss** [comment]
What do i do ؟
