### ISSUE TITLE
[Feature] table filtration

### ISSUE THREAD

**Issue by omarkadd** [thedevdojo/voyager#4123]
## Version information

 - Laravel: v5.8.15
 - Voyager: v1.2.6
 - PHP: 7.1.3
 - Database: MYSQL V.5.7.24

datatables provide a multiple filtration to the table which cannot be done in voyager.
filtration could re-draw tables as the user need.(like the images attached) 
adding printing to tables and exporting as excel or pdf or word 
## Proposed solution
add support for multiple  filtration and advanced search 
add exporting feature to the tables 
![maxresdefault (1)](https://user-images.githubusercontent.com/26447067/59913885-c915ee00-9421-11e9-855b-bc23a6c59458.jpg)
![maxresdefault](https://user-images.githubusercontent.com/26447067/59913886-c915ee00-9421-11e9-8bf5-42949a342387.jpg)

**Comment by fletch3555** [comment]
Not enough information provided.  This can be reopened once it has been updated to be a complete thought.  If brainstorming ideas, feel free to use our Slack group.
