### ISSUE TITLE
Accidentally deleted Tools menu

### ISSUE THREAD

**Issue by marcellopato** [thedevdojo/voyager#4125]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description:
I accidentally deleted the Tools menu and can´t get it back.
Can anyone help me?

**Comment by MrCrayon** [comment]
You can get what you need from here:
https://github.com/the-control-group/voyager/blob/1.2/publishable/database/seeds/MenuItemsTableSeeder.php

**Comment by fletch3555** [comment]
Questions should be asked in Slack, not here.
