### ISSUE TITLE
Route not defined(after deleting a table)[BUG]

### ISSUE THREAD

**Issue by michalakis** [thedevdojo/voyager#4126]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MySQL 10?

## Description

1. I created a table in the database through voyager, I called it Media so it may have clashed with the media component in voyager
2.then i created the bread
3.When I would go to view/edit the bread it wouldnt scroll down, it was very strange
4.I deleted the bread and the table called media
5.I create a new table called assets
6.When I click to save the bread it gave an error
7.now I cant access tools->database I get this error

```
Route [voyager.assets.index] not defined. (View: C:\Users\com2go\Desktop\code\socialmanager\vendor\tcg\voyager\resources\views\tools\database\index.blade.php)
```

**Comment by michalakis** [comment]
made a new installation of laravel, installed voyager

created one database table, on the second one i got the same error as above

```
ErrorException (E_ERROR)
Route [voyager.assets.index] not defined. (View: C:\Users\com2go\Desktop\code\socialmanager\vendor\tcg\voyager\resources\views\tools\database\index.blade.php)
Previous exceptions
Route [voyager.assets.index] not defined. (0)
```

```
  * @return string
     *
     * @throws \InvalidArgumentException
     */
    public function route($name, $parameters = [], $absolute = true)
    {
        if (! is_null($route = $this->routes->getByName($name))) {
            return $this->toRoute($route, $parameters, $absolute);
        }
 
        throw new InvalidArgumentException("Route [{$name}] not defined.");
    }
 
    /**
     * Get the URL for a given route instance.
     *
     * @param  \Illuminate\Routing\Route  $route
     * @param  mixed  $parameters
     * @param  bool   $absolute
     * @return string
     *
     * @throws \Illuminate\Routing\Exceptions\UrlGenerationException
     */
    protected function toRoute($route, $parameters, $absolute)
    {
        return $this->routeUrl()->to(
```

**Comment by btechn01** [comment]
Did you tried `php artisan optimize:clear` ?

**Comment by emptynick** [comment]
Unfortunately `assets` is a route used and generated by Voyager.
So this will conflict with your BREAD named `assets`.
We will rename this.
