### ISSUE TITLE
Roles not working

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#414]
- Laravel Version: 5.3.16
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version:

### Description:
I created user aaa, and role bbb, I assigned some modules BRAVD permit to role bbb,

then I login by user aaa, I can not see anything, system always redirect to home page

**Comment by handiwijoyo** [comment]
The role must have `browse_admin` permission to be able access admin site.

**Comment by jun283** [comment]
yes, It is working now
