### ISSUE TITLE
Help on Bread

### ISSUE THREAD

**Issue by zokhidovm** [thedevdojo/voyager#4144]
I have two tables:
- Drivers
- Points
And one table for registering points for Drivers (Table named:entries).
I have created a relationship (BelongsTo) and now it enables me to select point name from dropdown list.

When I pick a point name for driver, I want respective points to be inserted into entries table (point column). Could you help with that?

Thanks in advance

![Capture](https://user-images.githubusercontent.com/26684660/57906487-07baf600-782f-11e9-9c6a-2df0c036e1e5.PNG)
![Capture1](https://user-images.githubusercontent.com/26684660/57906489-07baf600-782f-11e9-9fea-ffa22cf1319e.PNG)
![Capture2](https://user-images.githubusercontent.com/26684660/57906491-07baf600-782f-11e9-8829-f125efdf00c5.PNG)
![Capture3](https://user-images.githubusercontent.com/26684660/57906492-08538c80-782f-11e9-9663-b0f141f27db6.PNG)

**Comment by emptynick** [comment]
Please use the issue template and follow the instructions, especially this part:
> IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST
