### ISSUE TITLE
Don't show all database fields on overview page: howto

### ISSUE THREAD

**Issue by wymedia** [thedevdojo/voyager#415]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.4

### Description:
The posts table contains more fields (in the database) then the overview posts page show (it only shows title, image, status, created_at, seo_title, featured fields). 

How can this be done for other tables as well? Is there some checkbox you need to click in order to decide if you want to display it in the overview page for that model?

**Comment by marktopper** [comment]
You must modify the published view `resources/views/vendor/voyager/browse.blade.php` file and add the columns you want.

**Comment by marktopper** [comment]
You can make a custom view for any bread you wish, just like it is for `posts`.

You can try copy the folder `resources/views/vendor/voyager/posts` to ex. `resources/views/vendor/voyager/products` in order to make custom layout for the listing of the `products` table bread.

**Comment by fletch3555** [comment]
@marktopper, I believe @wymedia was talking about how only certain fields are visible in the Browse view, not adding custom displays to the view.

@wymedia, you can do this by opening the Database editor, creating a BREAD for the table you wish to limit.  In the BREAD editor, you can uncheck the Browse checkbox for any fields you don't want visible in that view.  Same goes for Read and Edit/Add.
