### ISSUE TITLE
Multi language relation

### ISSUE THREAD

**Issue by osc2nuke** [thedevdojo/voyager#4150]
The concept i am thinking about is simple relation ships.
Unless i miss something in put "each" translation into one table, it does not feel right.

perhaps default laravel simplicity could help.

I am a producal coder.
I take for example a product id, get the id and look for the same id on the products_description table.

Laravel offer me several solutions  to retrieve me data based on the giving "id".

I have my concerns in the **front-end** with voyager to retrieve data via a link like:
https://yoursite.com/product/{slug}
https:/yoursite.com/categorie/{slug}

Sure can do same for a post.

I am curious if we can get an extended "course" in it of perhaps a good documentation.

I admit, i should have better knowledge of the overall concept of laravel with voyager.

But i also must say, beside laravel is pretty "loose type" , it does not mean that it can give best practice.
 Just curious!

**Comment by emptynick** [comment]
https://github.com/the-control-group/voyager/issues/3972#issuecomment-467105728

**Comment by osc2nuke** [comment]
@emptynick emptynick

Can you give an example of how to talk to the group?
I like the strict guideline, yet i am offered to put my issue or Q via GitHub.
I would like to be advised in where i explicitly i go wrong.
I want to learn how it works.
