### ISSUE TITLE
Create relations between tables

### ISSUE THREAD

**Issue by wymedia** [thedevdojo/voyager#416]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.4

### Description:
How can I create a relation between a video table and a category table using Voyager. I know how to do in plain Laravel but not in Voyager

**Comment by m1guelpf** [comment]
@wymedia Can you link me to a tutorial about how to do it in plain laravel?

**Comment by wymedia** [comment]
It is pretty well documented [here](https://laravel.com/docs/5.3/eloquent-relationships)

**Comment by marktopper** [comment]
We have a [documentation](https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-relationships) as well.
