### ISSUE TITLE
[BUG] Implicit Binding Route make VoyagerBaseController:show method break

### ISSUE THREAD

**Issue by BrunoMira** [thedevdojo/voyager#4164]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2.3
 - PHP: 7.3.4
 - Database: MySQL 8.0

## Description

Every time I try to view a model in Voyager Admin, I get an error. I think this happens because I set it up in Laravel to implicitly bind the model on routes with parameters. This parameter matches the parameter that Voyager generates on the routes, so the Voyager show method receives an object instead of an int.

## Steps To Reproduce
(P.S. in this example I'll use Professor for the model name, but you can use any other)

1. Make sure that your model uses SoftDeletes Trait or have the deleted_at property
2. Go to App/Providers/RouteServiceProvider and in boot() method, insert ` Route::model('professor', Professor::class);` 
3. So every time you call some Route with a param 'professor', it gives you the Object
4. Go to Admin Voyager and create a BREAD for table professors
5. try to access admin/professors/1 (the route created by Voyager for view one professor)
6. See error 
> Property [deleted_at] does not exist on this collection instance.

## Expected behavior
When I try to view a record in Voyager Bread, it throws an exception about 'trying to access a nonexistent property in the Collection'. This happens because in my project, I create an Implicit Binding for my Professor model, so every time I pass to a route a param (for example, teacher), Laravel gives the object instead of the Id. In VoyagerBaseController: :show method, it expects to receive an id, so in my case, when the code runs `$dataTypeContent = call_user_func ([$model, findOrFail ', $id])`, it returns a Colletion instead of an Object and on the next line: `if ($dataTypeContent-> deleted_at) {` it wraps because a collection doesn't have the deleted_at property

## Screenshots
![Professor-model](https://user-images.githubusercontent.com/17881524/58358774-c3df7680-7e56-11e9-8bb0-8fa317fef158.png)
![route-list](https://user-images.githubusercontent.com/17881524/58358775-c4780d00-7e56-11e9-9bbc-6afde5053121.png)
![route-provider](https://user-images.githubusercontent.com/17881524/58358776-c4780d00-7e56-11e9-9a73-ee4841622de0.png)
![exception](https://user-images.githubusercontent.com/17881524/58358777-c4780d00-7e56-11e9-86b7-57ada1339a13.png)
![professor-data](https://user-images.githubusercontent.com/17881524/58358778-c4780d00-7e56-11e9-9148-f346e6480140.png)

**Comment by fletch3555** [comment]
How are your routes defined? Are they explicitly defined, or are they the default ones generated by Voyager?  The Voyager routed usually have an "id" parameter, not a "professor" one, so this really shouldn't impact anything.

Though I'm curious why you're doing that instead of just typecasting your controller method argument as a "Professor" object.  What do you view as the benefit to doing it this way?

**Comment by BrunoMira** [comment]
@fletch3555, I didn't explicitly define the voyager routes, the "professor" is the name generated for the parameter (e.g. foo/bars/2 , the route will be foo/bars/{bar}). But you got me, I didn't know that i don't need to define the `Route::model('professor', Professor::class);`, I just need to define the type in the method.

@fletch3555, Thanks to clarify that for me.
