### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kiukishenkaec** [thedevdojo/voyager#4166]
## Version information

 - Laravel: v5.8.18
 - Voyager: v1,2
 - PHP: 7.3.5
 - Database: PostgreSQL 9.5

## Description

When updating a record, the file data is overwritten, although I do not delete it or upload a new file.

## Steps To Reproduce
1. Uploading a file ( http://prntscr.com/nu3c44 )
2. Save ( http://prntscr.com/nu3cgw )
3. I'm fine! Information about the file is ( http://prntscr.com/nu3cz5 )
4. I do not edit anything and do not change anything. Click "save" again ( http://prntscr.com/nu3cgw )
5. File data is lost ( http://prntscr.com/nu3dw6 )

## Expected behavior
If I do not delete or upload a new file, the data on the previously uploaded file should remain as is.

**Comment by emptynick** [comment]
Please use english so everyone can understand you.
Even google-translate will do.
This can be reopened once your issue-description is in english.

**Comment by kiukishenkaec** [comment]
I rewrote the question with the help of an interpreter. 
Help please with this question.
Thanks in advance for any help!
