### ISSUE TITLE
Image upload from frontend

### ISSUE THREAD

**Issue by abdul191993** [thedevdojo/voyager#4171]
i am using voyager as cms in my web along with another front-end.
when i upload image from the front-end it is not visible in voyager and when i upload image from voyager it is not visible in front-end .
because voyager uploads images like app.com/storage/postes/May2019/image but my upload path is app.com/storage/posts/image so how can i handle this issue in my application.
this is my code for image upload.
![Capture1](https://user-images.githubusercontent.com/47178064/58745638-a3be4180-846c-11e9-950a-49f4f8fd6678.PNG)

**Comment by emptynick** [comment]
Please use the issue-template and follow its instructions.
This can be reopened once all required informations are provided.
