### ISSUE TITLE
Admin menu not showing in 1.2.4 [BUG]

### ISSUE THREAD

**Issue by egidiusmengelberg** [thedevdojo/voyager#4179]
## Version information

 - Laravel: v5.8.19
 - Voyager: v1.2.4
 - PHP: v7.2
 - Database: MariaDB v10.1.29 (e.g. MySQL 8.0)
 - I'm using google chrome.

## Description

After installing voyager version 1.2.4 I didn't see the admin menu. After reinstalling a couple of times, I decided to try the version before commit #4064. This commit changed the menu to a vue component. After I installed version 1.2.3 the menu was there again. The weird thing is that it does work in Microsoft Edge.

## Steps To Reproduce
1. Install voyager version 1.2.4.
2. Login.
3. Missing the menu.

## Expected behavior

I expect to see the menu.

## Screenshots
v1.2.4:

![Screenshot_1](https://user-images.githubusercontent.com/22946100/58763512-e7dc3f80-855b-11e9-8d31-4e23bdeac2c2.png)

v1.2.3:

![Screenshot_2](https://user-images.githubusercontent.com/22946100/58763524-02aeb400-855c-11e9-9f67-f111cfb75aee.png)

## Additional context
I didn't modify or change anything during installation. This happens after a documentation described installation without any additional packages. The routes work fine. It't just that the menu is not showing.

**Comment by emptynick** [comment]
Did you clear your browser cache?
Do you have any errors in the browser console?

**Comment by egidiusmengelberg** [comment]
Oh wow, force reloading the page didn't work. Clearing my cookies did. Seems a bit weird but thanks.

Sorry for the hassle...

**Comment by chadpriddle** [comment]
Same issue here. In chrome doing a hard reload worked.

https://superuser.com/questions/721692/google-chrome-clear-cache-for-specific-website
