### ISSUE TITLE
Authentication redirects back to login page frequently.

### ISSUE THREAD

**Issue by allenjd3** [thedevdojo/voyager#418]
- Laravel Version: 5.3.16
- Voyager Version: dev-master 2fff01c

### Description: 
Authentication redirects back to login page frequently.

### Steps To Reproduce: 
When I navigate around the admin panel usually only clicking 2 links on the sidebar, I often get redirected back to the login page. Sometimes I can just manually put in the url of where I was trying to go and it will work correctly. Sometimes I have to log in again in order to continue.

**Comment by marktopper** [comment]
Sounds like you have a problem with your sessions.

The issue might however not be with Voyager, but with your setup and Laravel.

Can you please run `php artisan make:auth` and try login on the frontend, and click around there to confirm wether or not the issue is with Voyager or Laravel.

**Comment by allenjd3** [comment]
It doesn't seem to make a huge amount of difference when I login using the default authentication scaffolding. I'm using artisan serve and an sqlite database.

**Comment by karandatwani92** [comment]
Yea,i checked lifetime but it's happening and very frustrating,

**Comment by FredrikOseberg** [comment]
Hi, did you reset migrations? I had the same problems when trying to add a foreign key constraint to the posts model which resulted in all the permissions, menu items and data-rows that live in the database to reset as well. Running voyager install again on the command line solved this for me.

**Comment by marktopper** [comment]
According to @allenjd3's response I must assume this is a problem with the configuration and Laravel.

Please ask the geeks at [Laravel/Framework](https://github.com/laravel/framework).
