### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eksiugur** [thedevdojo/voyager#4181]
ErrorException (E_ERROR)
could not find driver (View: /home/yenibirsitecom/public_html/vendor/tcg/voyager/resources/views/login.blade.php)

Screenshot fail : https://i.hizliresim.com/Xb2QmD.png

**Comment by fletch3555** [comment]
Please follow our issue template. It prompts you to provide information like version numbers that are necessary for us to assist you.

Also, while I appreciate you providing a screenshot of the error, it would help if the image itself didn't throw a 403 error.  Please either upload the image directly to the issue or use a common image hosting service like imgur.com

This can be reopened once it has been edited to provide the necessary information
