### ISSUE TITLE
Create BREAD doesn't save fields [BUG]

### ISSUE THREAD

**Issue by chadpriddle** [thedevdojo/voyager#4182]
## Version information
 - Laravel: v5.5.*
 - Voyager: v1.2.4
 - PHP: 7.0
 - Database: MySQL 5.7.25

## Description
Create new BREAD doesn't save fields

## Steps To Reproduce
Create new table, add BREAD, save BREAD. Click on edit BREAD and the fields are blank. Click on new menu item that BREAD creates and error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'inventory.timeclocks' doesn't exist (SQL: select * from `timeclocks` order by `created_at` desc)

## Screenshots
<img width="1467" alt="Screen Shot 2019-06-05 at 7 50 14 AM" src="https://user-images.githubusercontent.com/5265683/58966356-05312980-8767-11e9-8b2b-5e1bec6f2d87.png">

**Comment by fletch3555** [comment]
Are you certain the table exists and is accessible by the database user your app is using?

**Comment by sqreele** [comment]
Help me, please!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test.boards' doesn't exist (SQL: select * from `boards` order by `created_at` desc)

voyager admin can't open borwseBREAD error now.

**Comment by fletch3555** [comment]
I'll ask again... are you certain the table exists?

**Comment by chadpriddle** [comment]
Yes. I solved the problem by declaring the table name in the model

**Comment by fletch3555** [comment]
That question was mostly directed at @sqreele, but thanks for confirming @chadpriddle.  I'll close this now.

**Comment by sqreele** [comment]
@fletch3555  thank you,
I confirmed  table already and create the model.
