### ISSUE TITLE
[BUG] RTL version still not working

### ISSUE THREAD

**Issue by AmirEdward** [thedevdojo/voyager#4183]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MariaDB 10.1

## Description
The RTL Style is messy, last related issue i saw said it will be fixed in version 1.2 which i'm using but it is not fixed , is this going to be fixed soon ?? or is there another version which is working ?

## Steps To Reproduce
1. Go to 'Config/App.php' and change the local to 'ar'
2. Got to the admin panel ('website.com/admin')
3. See error

**Comment by AmirEdward** [comment]
Solved the issue by adding 'rtl'=>true in config/voyager.php multilingual array,  which is not exist by default or documented in version 1.2 so i didn't know that i can add manually
closing

**Comment by emptynick** [comment]
There's no option `rtl` in the config file because it doesn't exist anymore.
If RTL is used or not is simply based on the locale you've chosen in your user-profile/app configuration.

**Comment by AmirEdward** [comment]
> There's no option `rtl` in the config file because it doesn't exist anymore.
> If RTL is used or not is simply based on the locale you've chosen in your user-profile/app configuration.

That's not totally correct ,, when i added the option 'rtl'=>true in the multilingual array of voyager config file it fixed the issue with the `rtl` styles, i had my application locale to 'ar' the admin panel style was messy yes it was `rtl` but messy, when i added this options it was fixed, but still there is a problem with the user menu, the buttons under the menu is not working even when the menu is not expanded, i hope this get fixed soon

**Comment by fletch3555** [comment]
@AmirEdward, if that's the case, please reproduce it in a fresh laravel/voyager project (no overridden views or anything), and submit that code, ideally with screenshots, in a new issue and we'll take a look.

**Comment by loverdeveloper** [comment]
@fletch3555 @AmirEdward
https://gist.github.com/abdumu/77287635e282f1bb733b84360b95af66#file-laravel-voyager-admin-rtl-css
