### ISSUE TITLE
tinymce- can not modify tinymce plugin settings to add plugins

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4188]
- Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
I want to modify tinymce default features. I want to add below things

- add new plugin, for example media plugin

- write js function to check, if characters (not words) exceeds 50, it will show alert to user to stop typing

## Steps To Reproduce
1. make field type rich text editor in bread
2. Go to voyager_tinymce.js and add media plugin
3. add js function to check characters count
4. see result , you will not find media plugin to insert video link

## Expected behavior
I want to see my new added plugins 

## Screenshots
see result , you will not find media plugin to insert video link

## Additional context
I tried all possible ways but no luck.example

- [GIT](https://github.com/the-control-group/voyager/pull/3145)

- init_instance_callback

- [GIT2](https://github.com/the-control-group/voyager/issues/1945)

- I also override views and wrote custom function for tinymce editor, but this time it could not found plugins folders and was expecting plugin.js files which does not exists

what else i can do??

**Comment by btechn01** [comment]
I got this problem too after update from 1.2.2 to newer and i fix this issue using external plugin,
First u have to download all plugins u need or as i use yarn add tinymce and copy plugins to public folder and override tinymce init as below,
```
function tinymce_init_callback(editor) {
    editor.remove();
    editor = null;
    tinymce.init({
        menubar: false,
        selector: 'textarea.richTextBox',
        skin_url: $('meta[name="assets-path"]').attr('content') + '?path=js/skins/voyager',
        min_height: 600,
        resize: 'vertical',
        plugins: 'print preview searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern help code textcolor',
        extended_valid_elements: 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
        file_browser_callback: function (field_name, url, type, win) {
            $('#upload_file').trigger('click');
        },
        toolbar: 'formatselect | bold italic strikethrough | forecolor backcolor | link image media | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent | ltr rtl | removeformat | code',
        convert_urls: false,
        image_caption: true,
        image_title: true,
        content_css: "/css/app.css",
        valid_elements: 'div[*],p[*],span[*],ul[*],li[*],ol[*],hr,br,img[*],i[*],em,table[*],tr[*],td[*],th[*],sup[*],sub[*],strong[*],b,h1[*],h2[*],h3[*],h4[*],h5[*],h6[*],small[*],a[*], svg,path',
        valid_children: '+li[span|p|div]',
        content_style: '.mce-annotation { background: #fff0b7; } .tc-active-annotation {background: #ffe168; color: black; }',
        external_plugins: {
            'print': '/tinymce/plugins/print/plugin.min.js',
            'preview': '/tinymce/plugins/preview/plugin.min.js',
            'searchreplace': '/tinymce/plugins/searchreplace/plugin.min.js',
            'directionality': '/tinymce/plugins/directionality/plugin.min.js',
            'visualchars': '/tinymce/plugins/visualchars/plugin.min.js',
            'visualblocks': '/tinymce/plugins/visualblocks/plugin.min.js',
            'autolink': '/tinymce/plugins/autolink/plugin.min.js',
            'fullscreen': '/tinymce/plugins/fullscreen/plugin.min.js',
            'media': '/tinymce/plugins/media/plugin.min.js',
            'template': '/tinymce/plugins/template/plugin.min.js',
            'codesample': '/tinymce/plugins/codesample/plugin.min.js',
            'charmap': '/tinymce/plugins/charmap/plugin.min.js',
            'pagebreak': '/tinymce/plugins/pagebreak/plugin.min.js',
            'hr': '/tinymce/plugins/hr/plugin.min.js',
            'anchor': '/tinymce/plugins/anchor/plugin.min.js',
            'nonbreaking': '/tinymce/plugins/nonbreaking/plugin.min.js',
            'insertdatetime': '/tinymce/plugins/insertdatetime/plugin.min.js',
            'toc': '/tinymce/plugins/toc/plugin.min.js',
            'advlist': '/tinymce/plugins/advlist/plugin.min.js',
            'wordcount': '/tinymce/plugins/wordcount/plugin.min.js',
            'imagetools': '/tinymce/plugins/imagetools/plugin.min.js',
            'textpattern': '/tinymce/plugins/textpattern/plugin.min.js',
            'help': '/tinymce/plugins/help/plugin.min.js',
        }
    })
}

```

**Comment by shafiqkr18** [comment]
I found the solution, you need to add like this..(keep tinymce folder in public folder)
<script type="text/javascript" src="{{ asset('/tinymce/tinymce.min.js') }}"></script>
    <script type="text/javascript">
        console.log('{{ asset('/tinymce/') }}');
        tinymce.baseURL = "{{ asset('/tinymce/') }}";
        tinymce.suffix = '.min';
        tinymce.init({
then rest of the code

**Comment by emptynick** [comment]
Closing as this issue seems to be resolved.
We don't supply all plugins by default (of course) so you have to add it by yourself.
