### ISSUE TITLE
Output user tables on view

### ISSUE THREAD

**Issue by covecove1** [thedevdojo/voyager#419]
- Laravel Version: 5.3
- Voyager Version: 0.10.4
- PHP Version: 7

Hi,

How can we output rows from a table to a view?
Also, how can we output random row's selected columns to a view every time a button is pressed (refreshing that part in real time, not the whole page). 

Thanks in advance

**Comment by marktopper** [comment]
You can do this using [models](https://laravel.com/docs/5.3/eloquent) or [query builder](https://laravel.com/docs/5.3/queries).
