### ISSUE TITLE
[BUG] Route [voyager.assets] not defined.

### ISSUE THREAD

**Issue by tmdan** [thedevdojo/voyager#4190]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

After upgrading from version 1.2.4 to version 1.2.6. I got an error.
`Route [voyager.assets] not defined.`

**Comment by tmdan** [comment]
I found the reasons. The problem was that the template was overridden by master.blade.php.

**Comment by acecx** [comment]
how to fix it?

**Comment by tmdan** [comment]
> how to fix it?

If you want to quickly solve the problem, just delete the old master.blade.php from resources->views->vendor->voyager  that overrides the base master.blade.php, or or just update this file to a new one.

**Comment by shlaing** [comment]
@tmdan , No it doesn't fix.

**Comment by sabayazid** [comment]
Faced the same issue with Admin Page.  **Route [voyager.assets] not defined.**
Using Voyager 1.2.7 solved the issue for me.

**Comment by shabbarabbas** [comment]
I fix this by clear my view cache using below command
`php artisan view:clear`
