### ISSUE TITLE
[BUG]  Error while loading images

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4192]
## Version information

 - Laravel: v5.8.0
 - Voyager:The latest
 - PHP: 7.3
 - Database: MariaDB 10.3.15 

## Description

In admin panel not showing any image including admin's default image. Browsers responding like this : "Failed to load resource: the server responded with a status of 404 (Not Found)"  for all images. 

## Steps To Reproduce
1. Go to 'Settings' in admin panel
2. Add new Image setting and click on 'Add new Setting'
3. Open DevTools -> Console
5. You can the exact error here: http://ecopart.uz/  

## Expected behavior
I want to see image on the screen that is it.

## Screenshots
![image](https://user-images.githubusercontent.com/40025822/59255719-edb4dd80-8c4b-11e9-9b11-5a5bbef4a21a.png)

**Comment by shagal-sajid** [comment]
In the root of your laravel project, Change APP_URL  from 'http://localhost' to 'http://localhost:8000' in case if you are using port 8000.
![image](https://user-images.githubusercontent.com/33257942/59258940-7d5f8980-8c56-11e9-8142-dd911076e6d5.png)

**Comment by KhurshidYakubov** [comment]
Ok. Thank you. It is working now :)
