### ISSUE TITLE
No query results for model [App\User] after trying to add new user on a fresh install

### ISSUE THREAD

**Issue by cubouyaka** [thedevdojo/voyager#4193]
- Laravel: v5.7.28
 - Voyager: v1.2
 - PHP: 7.2.19
 - Database: mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

Hello everyone I'm trying to use Laravel Voyager for a Laravel project but I cannot create an admin user .. I tried both installation (--with-dummy and without) but in both case I have the same error : When I try `php artisan voyager:admin 'user@email.com' --create` this result in 'Aborted' directly. When I'm trying `php artisan voyager:admin 'user@email.com'` then I've got the error `Illuminate\Database\Eloquent\ModelNotFoundException  : No query results for model [App\User].`. 
I checked and I have a file named App\User.php (but it doesnt extends Model which may be the problem ?) : 
```
<?php
namespace App;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```
I couldn't find a solution for this problem, even if I saw multiple post about it, looks like people solved this problem easily but I don't .. 

Can someone help me ? Thanks!

**Comment by fletch3555** [comment]
Did you follow the install steps in our docs?  Looks like you didn't run `artisan voyager:install` since that would've overridden the parent class of your User model.  However, that likely wouldn't be the cause for your specific issue.  For that, it's likely an autoloader issue.

Try running `artisan voyager:install`.

If it still doesn't work, run `composer dump-autoload`

**Comment by cubouyaka** [comment]
Yes i followed the steps of the docs, without any problems. Yes I tried to run `artisan voyager:install` (also tried the same with option `--with-dummy` but still doesn't work). The install works well, but the `php artisan voyager:admin` still doesn't work (exactly the same as before).

I tried to run `composer dump-autoload` which works fine but didn't fixed the problem..

**Comment by fletch3555** [comment]
Please try manually changing your User model so it `extends TCG\Voyager\Models\User` then try again.  You're not losing anything since Voyager's User model class already `extends Authenticatable` (https://github.com/the-control-group/voyager/blob/1.2/src/Models/User.php#L10)

**Comment by cubouyaka** [comment]
Yes I tried this also before, and I just retried it but it doesn't change anything, I still have the same error .. (When I say I retried, I made the changes then re-run `composer dump-autoload`, then `php artisan voyager:install` and finally `php artisan voyager:admin user@email.com --create` (and also `php artisan voyager:admin  user@email.com` to be sure I have the same error than previously, which is the case)

**Comment by JoseGeorges8** [comment]
What was the solution for this? I am getting the same error...

**Comment by usafLhb** [comment]
Hello  when  i try  to  create  an  admin after  i  created voyager  composer  i  receive a  message  that  the  name  is  aborted ,i  tried  with  php artisan voyager:admin your@email.com --create also with php artisan voyager:admin--create but  none  of this work  .. can  someone help  me please

**Comment by fletch3555** [comment]
This has been closed for nearly a year now.  Please ask questions on slack, and report bugs as new issues instead of commenting on closed issues.  This ensures we have all the necessary information to help you.
