### ISSUE TITLE
[BUG] Showing Date format in BREAD Index rather then Date it self.

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4195]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: v7.1.3
 - Database: MySQL 5.7.24

## Description

Voyager Index View is showing Date format rather than date.

## Steps To Reproduce
1. Go to the Database and create a table containing at least one date datatype column.
2. Go to BREAD Builder and Create bread for the newly created table. For the date column, provide below json to optional details.
`{
    "format": "Y-m-d"
}`
3. Save the Bread and you will found that BREAD link in Menu. Browse that bread.
4. Create new Record by clicking **Add New** Button at the top.
5. Browse data and you will be able to figure out the bug.

## Expected behavior
The field should show date, instead of showing format provided in BREAD.

## Screenshots
![image](https://user-images.githubusercontent.com/22276302/59414779-d575c780-8ddf-11e9-8fe2-92e601ae7c60.png)
![image](https://user-images.githubusercontent.com/22276302/59414825-eb838800-8ddf-11e9-968e-13060bd371bd.png)
![image](https://user-images.githubusercontent.com/22276302/59414838-f4745980-8ddf-11e9-849f-442cc71df708.png)

## Additional context
Is it requires to provide the format of date while creating the new BREAD on the table? It has the same behavior in BREAD Single item View.

**Comment by fletch3555** [comment]
The Date field uses Carbon::formatLocalized() which calls strftime() under the hood.  So make sure your format string matches that. If it doesn't match, it'll show the characters as literals, which I believe is what is happening in your case.

https://www.php.net/manual/en/function.strftime.php

I think the change to localized dates was fairly recent, so we may need a docs update.

**Comment by emptynick** [comment]
Judging by the thumbs-up I think this solved your problem?
If not, let us know. Closing.
