### ISSUE TITLE
Multiple files problem [BUG]

### ISSUE THREAD

**Issue by magyar** [thedevdojo/voyager#4196]
## Version information
 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.3

## Description
I added a custom field (multiple files) in the pages. I added files and saved. No problem, but when I want to attach a new file, old files remove

## Steps To Reproduce
1. Add custom field (multiple files) in the pages 
2. To attach a some files
3. Save page
4. Edit this record and try to attach files else
5. Open again and you will see only new files

## Screenshots
![2019-06-13_17-46-02 (2)](https://user-images.githubusercontent.com/2011413/59444181-0ff25b00-8e06-11e9-8899-16a1f127ef50.png)

## Additional context
for fix you can change the method insertUpdateData()
vendor/tcg/voyager/src/Http/Controllers/Controller.php
`insertUpdateData() {
/*
             * merge ex_images and upload images
             */
            if (($row->type == 'multiple_images' || $row->type == 'files') && !is_null($content)) {
                if (isset($data->{$row->field})) {
                    $ex_files = json_decode($data->{$row->field}, true);
                    if (!is_null($ex_files)) {
                        $content = json_encode(array_merge($ex_files, json_decode($content)));
                    }
                }
            }
}`

**Comment by Braiani** [comment]
Hey. Would you mind to make a PR with this solution?

**Comment by yazux** [comment]
i have this problem to. But you don't right. If you have the same problem, you need change "files" to "file" in your comment. So you get that:

> if (($row->type == 'multiple_images' || $row->type == 'file') && !is_null($content)) {
                 if (isset($data->{$row->field})) {
                    $ex_files = json_decode($data->{$row->field}, true); 
                    if (!is_null($ex_files)) {
                        $content = json_encode(array_merge($ex_files, json_decode($content)));
                    }
                }
            }


if you want solve the problem right now, you need:

1. Change your config file config/voyager.php:

> 'controllers' => [
    'namespace' => 'App\\Http\\Controllers\\Voyager',
]

Then run php artisan voyager:controllers, Voyager will now use the child controllers which will be created at App/Http/Controllers/Voyager

2. in file App\Http\Controllers\Voyager\VoyagerBaseController.php copy 3 functions:
1) "update" from TCG\Voyager\Http\Controllers\VoyagerBaseController.php
2) "store" form  TCG\Voyager\Http\Controllers\VoyagerBaseController.php
3) "insertUpdateData" from  TCG\Voyager\Http\Controllers\Controller.php

3. In file App\Http\Controllers\Voyager\VoyagerBaseController.php change function "insertUpdateData"
change line  

> if ($row->type == 'multiple_images' && !is_null($content))

to 

> if (($row->type == 'multiple_images' || $row->type == 'file') && !is_null($content))

4. Profit!

**Comment by Gicminos** [comment]
Hi, I am not sure if this issue is related, probably not, but I cannot find the multiple files type at all in my bread:
![no_multiple_files](https://user-images.githubusercontent.com/9993624/68802784-79e18b80-0656-11ea-84ea-9b97944988c1.png)

Did I understand wrongly the meaning of the issue or it is something completely different? Sorry and thank you!

**Comment by yazux** [comment]
Hello! You can use type «File» to load multiple files, but bug in issue an exist in this method.I wrote step by step how you can fix problem without update Voyager.
