### ISSUE TITLE
Compatibility with laratrust.

### ISSUE THREAD

**Issue by jer3m01** [thedevdojo/voyager#4198]
## Version information
 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description:
I am trying to create a project using Voyager and [Laratrust](https://laratrust.santigarcor.me/) as it has a deeper permission system. Only thing is that I don't know a clean way to disable the feature in Voyager.

Are there already built in ways to do so, if not how would you recommend I remove Voyager's roles and permissions? 
I don't mind creating a fork of the project.

Thanks, any help is appreciated!
jer3m01.

**Comment by fletch3555** [comment]
Questions like this are much better asked in Slack.  There's no good way to decouple Voyager's role/permission system.
