### ISSUE TITLE
[BUG] Can't find images from settings

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4199]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB 10.3.15

## Description

I am adding images to the settings in order to show them on another page. Admin panel is showing all images. But when I want to load them on another page , I am receiving  404 (Not found) error.

## Steps To Reproduce
1. Go to the Settings
2. Add any image with the key
3. Load it on another page using `<img src="<?= setting('site.key');?>" alt="">`

## Expected behavior
I want to see images.

## Screenshots
![image](https://user-images.githubusercontent.com/40025822/59549385-2b7c7380-8f76-11e9-9cd5-d0706e94b670.png)

**Comment by fletch3555** [comment]
Any image uploaded through Voyager needs to be displayed using `Voyager::image($image)`

**Comment by KhurshidYakubov** [comment]
Thank you very much)))
