### ISSUE TITLE
Charset problem with database or html?

### ISSUE THREAD

**Issue by iAyubAnsari** [thedevdojo/voyager#4201]
## Version information

 - Laravel: v5..8
 - Voyager: v1.2
 - PHP: 7.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

I am using dummy voyager data to create my blog. whenever i post bengali font (বাস ভাঙচুর কর�) it always end up like the question mark . how can i overcome it?

## Screenshots
(https://user-images.githubusercontent.com/20745499/59564966-d4a49600-906a-11e9-9d88-194e0fbdcccf.png)

**Comment by fletch3555** [comment]
I'm fairly certain we just use UTF-8, so it shouldn't be a problem.  Do you know what the utf8 character code is for the character that's not displaying?

**Comment by iAyubAnsari** [comment]
Actually sorry sir, I was unable to solve the problem that's why I posted it here. After searches I use mb_substr() instead of substr() to solve my problem.
Thank you sir
