### ISSUE TITLE
Custom relationship attribute and ajax search

### ISSUE THREAD

**Issue by snowket** [thedevdojo/voyager#4202]
Hello

I`m using custom relationship attribute ex : full_name as described in docs .
when creating bread i`m using full_name as display column , relationship is belongsToMany so , i have multiselect with ajax search . but when trying to search getting error 
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'where clause' (SQL: select count(*) as aggregate from `players` where `full_name` LIKE %asd%)`
i cant use name or surname as relationship display column ( as you now there can be duplicates in names and surnames too )
see below images . 
what can i do to fix it ? 

`protected $translatable = ['first_name', 'last_name', 'text'];

    public $additional_attributes = ['full_name'];

    public function getFullNameAttribute()
    {
        $locale = app()->getLocale();
        $firstName = $this->getTranslatedAttribute('first_name', $locale);
        $lastName = $this->getTranslatedAttribute('last_name', $locale);
        return $firstName . ' ' . $lastName;
    }`
![image](https://user-images.githubusercontent.com/5967630/59660075-b5b41a00-91b8-11e9-9188-b63e3b5514c2.png)
![image](https://user-images.githubusercontent.com/5967630/59660115-cb294400-91b8-11e9-8592-dd36537bba4d.png)

**Comment by snowket** [comment]
POSSIBLE FIX
add this json as relationship details `{"model":"App\\Player","table":"players","type":"belongsToMany","column":"id","key":"id","label":"full_name","label_custom":"last_name","pivot_table":"poll_questions","pivot":"1","taggable":"0"}`
and edit VoyagerBaseController@relation to
```
    public function relation(Request $request)
    {
        $slug = $this->getSlug($request);
        $page = $request->input('page');
        $on_page = 50;
        $search = $request->input('search', false);
        $dataType = Voyager::model('DataType')->where('slug', '=', $slug)->first();

        $rows = $request->input('method', 'add') == 'add' ? $dataType->addRows : $dataType->editRows;
        foreach ($rows as $key => $row) {
            if ($row->field === $request->input('type')) {
                $options = $row->details;

                $skip = $on_page * ($page - 1);

                // If search query, use LIKE to filter results depending on field label
                if ($search) {
                    $label = $options->label_custom ? $options->label_custom : $options->label;
                    $total_count = app($options->model)->where($label, 'LIKE', '%'.$search.'%')->count();
                    $relationshipOptions = app($options->model)->take($on_page)->skip($skip)
                        ->where($label, 'LIKE', '%'.$search.'%')
                        ->get();
                } else {
                    $total_count = app($options->model)->count();
                    $relationshipOptions = app($options->model)->take($on_page)->skip($skip)->get();
                }

                $results = [];
                foreach ($relationshipOptions as $relationshipOption) {
                    $results[] = [
                        'id'   => $relationshipOption->{$options->key},
                        'text' => $relationshipOption->{$options->label},
                    ];
                }

                return response()->json([
                    'results'    => $results,
                    'pagination' => [
                        'more' => ($total_count > ($skip + $on_page)),
                    ],
                ]);
            }
        }

        // No result found, return empty array
        return response()->json([], 404);
    }
```

**Comment by rohankhudedev** [comment]
@emptynick , Given above is fix by @snowket works. This issue is also with `belongsTo` relationship.
