### ISSUE TITLE
local.ERROR: Route [voyager.assets] not defined.

### ISSUE THREAD

**Issue by support-site** [thedevdojo/voyager#4203]
1.6
local.ERROR: Route [voyager.assets] not defined. (View: .../vendor/tcg/voyager/resources/views/master.blade.php)

**Comment by bendo01** [comment]
after composer update this error occurs

**Comment by SAM-AEL** [comment]
try reinstalling voyager. seems like [voyager.assets] is an invalid route on latest voyager. not sure  about your version. and i got same error as "Route [voyager.assets] not defined" when my admin routes where defined on any custom route except web.php.

**Comment by shlaing** [comment]
@SamSolomonOfficial No, It doesn't work. Any update?

**Comment by shlaing** [comment]
Clear the cache. It should works

**Comment by shabbarabbas** [comment]
I fix this by clear my view cache using below command
`php artisan view:clear`
