### ISSUE TITLE
How to translate belongs-to relationship in voyager laravel admin

### ISSUE THREAD

**Issue by amminvention** [thedevdojo/voyager#4204]
I am using voyager admin laravel that includes its own translations table and I have two tables categories and products that have a relationship, each product belongs to a category. Now when I fill products data and switch between languages category field doesn't change, it shows me always the default language. any help?

**Comment by fletch3555** [comment]
Issue template is not optional.  This can be reopened once the necessary information is provided.  Also, as noted in the template, questions are best asked in slack.
