### ISSUE TITLE
syntax error, unexpected ':', expecting '(' [BUG] 

### ISSUE THREAD

**Issue by leonmekic** [thedevdojo/voyager#4206]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1.25
 - Database: MySQL 5.7.23

## Description
I get an syntax error, unexpected ':', expecting '(' when i try to override edit-add.blade 
I did all the correct steps, I made a directory vendor/voyager/news/edit-add.blade
I copied the blade from voyager directory and i did not change the blade. this is unusual because I already extended a few views in the same manner.

## Steps To Reproduce
1. Make a new directory vendor/voyager/news/edit-add.blade
2. Go to voyager admin panel an try to add new 'news'
3. See error

## Expected behavior
I expect to get a regular form for inserting new data

<img width="1440" alt="Screenshot 2019-06-18 at 21 49 51" src="https://user-images.githubusercontent.com/42568923/59714927-0ce6d880-9213-11e9-85df-d5e059603ed8.png">
<img width="414" alt="Screenshot 2019-06-18 at 21 49 30" src="https://user-images.githubusercontent.com/42568923/59714929-0ce6d880-9213-11e9-8783-598219bc325b.png">
<img width="819" alt="Screenshot 2019-06-18 at 21 58 02" src="https://user-images.githubusercontent.com/42568923/59715492-4409b980-9214-11e9-927a-c4cf6f1c2021.png">

**Comment by leonmekic** [comment]
This happens when i try to extend a edit-add view
I just make a directory and copy the edit-add file from voyager (did not make any changes in the view) and it throws me an error

**Comment by fletch3555** [comment]
Issue template is not optional.  Please fill out all of the requested information, then this can be reopened.

**Comment by leonmekic** [comment]
@fletch3555 Sorry for lack of information at first

**Comment by leonmekic** [comment]
> Issue template is not optional. Please fill out all of the requested information, then this can be reopened.

@fletch3555 Sorry for the lack of information at first

**Comment by fletch3555** [comment]
What file did you copy from? Because that's definitely not the default BREAD edit-add file: https://github.com/the-control-group/voyager/blob/1.2/resources/views/bread/edit-add.blade.php#L195

**Comment by leonmekic** [comment]
![Screenshot 2019-06-19 at 07 24 38](https://user-images.githubusercontent.com/42568923/59738961-6c6cd480-9263-11e9-8f12-47525cfdbb8b.png)
I copied it from here. The file with random letters and number is not generated by me.
I deleted the file with random letters and it worked. 
Thanks for the help and time. :)

**Comment by fletch3555** [comment]
The "file with random letters and number" is a cached view.  Make sure you always clear the view cache (`artisan view:clear` I believe) as part of your view troubleshooting steps.
