### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4210]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB 10.3.15

## Description of problem

I have a request form in my website. And I have "Requests" on my admin panel menu.Can I get all requests from database and see them by clicking "Requests" menu item.

## Alternatives considered
For example, 
this is request button:
![image](https://user-images.githubusercontent.com/40025822/59843415-f7d48b80-9371-11e9-941b-282fd5dc0ae3.png)

And this one is a request from. when you click continue, all your data which you filled,  go to the database 
![image](https://user-images.githubusercontent.com/40025822/59843578-484be900-9372-11e9-8fa6-aa92ad610757.png)

Finally, I want see all Requests like a list in my admin panel.

Can I do such feature using Voyager ? 
If yes, I am open and eager to any advices.

**Comment by fletch3555** [comment]
That's literally what this package does.  Just create a `Requests` BREAD following our docs, then when the record is created from your frontend form, it'll be visible in Voyager at `/admin/requests`
