### ISSUE TITLE
Media Picker input type control do not save images in database

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4211]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MySql

## Description
I have one fields Images in database, the type is text. In bread i wanted to keep input type as media picker to manage multiple uploads. When i save record, the database table is empty [] , although images are uploading to storage folder and media manager properly. How i can Upload & reuse images in this case? also i need to save it in database so that later i can display it.

## Steps To Reproduce
1. Go to  database, create tests tables, add a field images with type text
2. Click on BREAD and select media picker control type for images field
3. save and then try to upload images. 
4. Check your database table and images will be [] only

## Expected behavior
Images array should be in db

any issue?

**Comment by shafiqkr18** [comment]
Does anyone have fixed this issue?

**Comment by emptynick** [comment]
You have to select the images you want to save in the DB by double clicking them
