### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by yanwuguangjun** [thedevdojo/voyager#4213]
at  voyagerBaseController.php
`  

          if ($search->value != '' && $search->key && $search->filter) {
                $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
                $search_value = ($search->filter == 'equals') ? $search->value : '%'.$search->value.'%';
                $query->where($search->key, $search_filter, $search_value);
            }

            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'desc';
                $dataTypeContent = call_user_func([
                    $query->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }
`

should  do  someting like this

 ```
if ($search->value != '' && $search->key && $search->filter) {
                $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
                $search_value = ($search->filter == 'equals') ? $search->value : '%' . $search->value . '%';
                $query->where($search->key, $search_filter, $search_value);
            }

        /**
          * watch there
          **/
           if (!empty($request->sqlQuery)){
                $query->where($request->sqlQuery);
            }
          /**
          * watch there
          **/

            if ($orderBy && in_array($orderBy, $dataType->fields())) {
                $querySortOrder = (!empty($sortOrder)) ? $sortOrder : 'desc';
                $dataTypeContent = call_user_func([
                    $query->orderBy($orderBy, $querySortOrder),
                    $getter,
                ]);
            } elseif ($model->timestamps) {
                $dataTypeContent = call_user_func([$query->latest($model::CREATED_AT), $getter]);
            } else {
                $dataTypeContent = call_user_func([$query->orderBy($model->getKeyName(), 'DESC'), $getter]);
            }
```
then  we can 

```
    public function update(Request $request, $id)
    {
        
            $request->merge([
             'sqlQuery'=>['author_id'=>app('VoyagerAuth')->user()->id]
            ]);
        
        return parent::update($request, $id);
    }

```

or  let  search  is  array search

**Comment by fletch3555** [comment]
I'll be honest, I barely have any idea what you're asking for/suggesting... But at first glance, `sqlQuery` makes zero sense as the name for that key.  You're not actually passing it SQL, much less a query object.  Second, by adding it to the request object, you also open it up to url injection, which is bad.

If you explain what you're trying to do, there's likely a better way.  I'd recommend asking that question in Slack

**Comment by yanwuguangjun** [comment]
my  english  not  very well but  i'm not jokeing  please try to  read the  code  again

**Comment by yanwuguangjun** [comment]
it's  not  about request  just query  some condition ,  i just want it  more easy
