### ISSUE TITLE
Translations not working after altering a table

### ISSUE THREAD

**Issue by vsvp21** [thedevdojo/voyager#4214]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.1.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
Voyager translations are not working after altering a table. I had altered two tables and after that translations stopped working

## Steps To Reproduce
1. Create table
2. Create Bread
3. Delete some columns from voyager -tools-database-table
4. Try to change Locale

**Comment by fletch3555** [comment]
Steps to reproduce are not specific enough.  If you could PR a test showing it failing, that would help identify the cause

**Comment by MrCrayon** [comment]
Please provide a test as asked or at least be more specific on what do you mean by _not working_, do you have an error?

**Comment by MrCrayon** [comment]
Closing because information requested was not provided.
