### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4215]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB 10.3.15

## Alternatives considered

I have enabled multilingual function and everything is working fine(in admin panel). I can easily add text for 3 languages. And now I want to see translated texts on my landing page by clicking buttons.

## Additional context
this is admin panel side. From there I can add three translated texts for one post:
![image](https://user-images.githubusercontent.com/40025822/59910375-2bbfb780-942b-11e9-9276-76691aed59e1.png)

And by clicking on this three buttons. I want switch to this language. 
![image](https://user-images.githubusercontent.com/40025822/59910592-abe61d00-942b-11e9-8b19-ceac14d2d8f9.png)

How can I do this ? Any suggestions pleace.

**Comment by fletch3555** [comment]
Questions are best asked in slack per the issue template.  We reserve github issues for bug reports and feature requests
