### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vinuchacko** [thedevdojo/voyager#4219]
## Version information

 - Laravel: v5.8
 - Voyager: v0.11
 - PHP: 7.1
 - Database:MySQL 8.0

## Description

I installed laravel and voyager using composer. It worked on my localhost. And I really love voyager. Nice work.
But when I deploy my laravel website to a live server, some issues found.
Issue : Images uploaded using voyager is not showing .

When I check , I found images stored to webisteurl/storage/app/public
And images reads from websiteurl/public/storage/

My filesysem.php look like

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => public_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => public_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
        ],

And I follows  this link to install laravel on my server
https://www.youtube.com/watch?v=6g8G3YQtQt4

## Expected behavior
Can you suggest a way to solve this.. I tried lots of way.

## Screenshots
http://prntscr.com/o4vqjh

**Comment by evgeniy-bublik** [comment]
Is symbolic link created?
php artisan storage:link

**Comment by fletch3555** [comment]
Please search before posting, and ask questions in Slack.  This has been reported many many times (https://github.com/the-control-group/voyager/search?q=images+not+working&type=Issues there's no error message to search, so this and variations on it should provide a number of results).

What @evgeniy-bublik said is likely correct.  Another potential issue is not having your APP_URL set correctly (i.e. it should have the domain (including port if not 80/443) that you access the site at).  If you need further assistance, please ask in Slack

**Comment by vinuchacko** [comment]
**Fixed**
The problem was - public/storage already exist - so that symlink not worked.
So I removed public/storage then run php artisan storage:link.
Now it working.
Closing this .
