### ISSUE TITLE
Problem with BREAD for table with 14k+ rows.

### ISSUE THREAD

**Issue by serzhiio** [thedevdojo/voyager#422]
Looks like, BREAD is not adopted for big tables (14k+ rows).
Voyager loads all rows on one page, it's a disaster.

**Comment by marktopper** [comment]
Your welcome to make a pull request fixing this.

**Comment by tnylea** [comment]
This has been updated in the latest `0.10.6` version. Users can now check if they want to do server side pagination in the BREAD editor 👍
