### ISSUE TITLE
Class 'TCG\Voyager\VoyagerServiceProvider' not found

### ISSUE THREAD

**Issue by smartcoder01** [thedevdojo/voyager#4222]
Probably happened many times, but please explain, I beg you.

`Class 'TCG \ Voyager \ VoyagerServiceProvider' not found`

I have the / vendor folder in the root, and I have a folder with in the laravel project which is in /public_html/site.сom/vendor.

There is an installation in / vendor to the root.

How to install a voyager in the c / laravel folder

thanks

**Comment by emptynick** [comment]
Please use the issue template.
This can be reopened once the informations are provided.
