### ISSUE TITLE
[BUG] Class 'TCG\Voyager\VoyagerServiceProvider'

### ISSUE THREAD

**Issue by smartcoder01** [thedevdojo/voyager#4223]
## Version information

 - Laravel: v5.8.24
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL

## Description

In ProviderRepository.php line 208:
Class 'TCG\Voyager\VoyagerServiceProvider' not found

## Steps To Reproduce
1. Go to terminal
2. Write composer require tcg/voyager
3. add your application URL in the APP_URL variable
3. Write php artisan voyager:install
4. getting an error

## Expected behavior
I watched the instructions, I thought it would be installed.

## Additional context
I have the / vendor folder in the root, and I have a folder with in the laravel project which is in /public_html/site.сom/vendor.
There is an installation in / vendor to the root.
How to install a voyager in the c / laravel folder

**Comment by t0rjan** [comment]
bro, https://github.com/the-control-group/voyager/issues/2773

**Comment by t0rjan** [comment]
bro,may be  u can try 5.5 of Laravel.

**Comment by t0rjan** [comment]
You can use a clean Laravel 5.8 to do a test to determine if there is a problem with your own use.

**Comment by smartcoder01** [comment]
the issue was solved by reinstalling composer
