### ISSUE TITLE
How do I remove the DB tables and fields Voyager created before removing it via composer?

### ISSUE THREAD

**Issue by GalacticSun** [thedevdojo/voyager#4229]
I want to remove Voyager from my Laravel installation.
I'm going to do this with Composer, which is fine.
But how can I ensure all the tables and fields it created in the DB are gone, as well?
Thanks.

**Comment by fletch3555** [comment]
Voyager doesn't have an "uninstall" process, so you'll have to do it yourself.  Every app is different, so we would never be able to know what tables should be deleted.  I assume you know what tables your app uses, so you should be able to just delete the rest.  The only tables required by Voyager are `data_types` and `data_rows` 

Also, the issue template is required and questions like this are best asked on our slack.

**Comment by GalacticSun** [comment]
I'm talking about the ones it created, obviously not the ones it knows nothing about...  (like the avatar field in the users table, etc).

It would be as simple as having the equivalent of a migration down() type function like any migration.  The reverse of what it created when installing it...  Would be nice to have.

**Comment by fletch3555** [comment]
They're all created by laravel migrations.... so you should already be able to do that.

**Comment by GalacticSun** [comment]
Would be much tidier if the project creators did it because they are the ones who know what they added and where...  We're not all as intimately familiar with the original Voyager migration file as the Voyager devs are and where Voyager makes its changes to the DB, nor should we have to hunt through your code and our DB to undo those changes.  Of course developers are responsible for their own DB changes and additions after the initial migration, but if you're going to create multiple fields and tables for us, at least provide us with an elegant solution to back those changes out.  Not that unreasonable of a request, really.

**Comment by fletch3555** [comment]
That's my point though, it's already there... https://github.com/the-control-group/voyager/tree/1.2/migrations

**Comment by GalacticSun** [comment]
How do I roll those back, though, when they are multiple migration steps back?  They are on "batch" 8 in my migrations table, but I'm up to 12.  Should I use `php artisan migrate:rollback --step=4` and then re-run batches 9-11 after that?  Or is there a way to rollback only that batch?

**Comment by fletch3555** [comment]
I don't really have a solid answer for you.  That's laravel functionality.  Whether you choose to "down" the migrations or manually delete tables, or create your own migrations that "up" what the "down" would've done, is completely up to you.

**Comment by GalacticSun** [comment]
Well, I ended up doing this: https://stackoverflow.com/questions/30287896/rollback-one-specific-migration-in-laravel
Definitely should be easier, though.
