### ISSUE TITLE
[BUG] adding custom action buttons

### ISSUE THREAD

**Issue by gavinj1999** [thedevdojo/voyager#4235]
## Version information

 - Laravel: v 5.8.26
 - Voyager: v1.2.6
 - PHP: 7.2.14
 - Database: MySql 5.7.25

## Description

I followed the docs to add an action button here https://docs.laravelvoyager.com/customization/action-buttons When browsing BREAD I get this error;

`"Route [my.route] not defined. (View: /Users/gavinjones1/Documents/mamp/newlara/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) (View: /Users/gavinjones1/Documents/mamp/newlara/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) "`

## Steps To Reproduce
1. Follow steps at https://docs.laravelvoyager.com/customization/action-buttons
2. Brows any BREAD view

## Expected behavior
I would expect to see the new button

**Comment by fletch3555** [comment]
`my-route` is just an example.  You have to change that to a route name in your app.
