### ISSUE TITLE
[BUG] the app.locale is not taken into account

### ISSUE THREAD

**Issue by fredckl** [thedevdojo/voyager#4236]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2
 - PHP: 7.1
 - Database: [mysql] [5.7]

## Description

If change locale in config.app to "fr", the locale not working in Voyager.
The value is always "en"

Thank's for your help

## Steps To Reproduce
1. change app.locale = "fr" value in config->app.php
2. In VoyagerUserController check value with config('app.locale') = "en"

**Comment by vince83110** [comment]
Voyager uses the locale set for the user connected :

See here : https://github.com/the-control-group/voyager/blob/ada53be172f4b32ee13e52da969fb0ba7804311f/src/Http/Middleware/VoyagerAdminMiddleware.php#L21

Be sure you set the correct lang for your user, you can edit the profile.

**Comment by fletch3555** [comment]
As @vince83110 said, Voyager will prefer the locale defined for the user.  If the user does not have one set, it _should_ use the app.locale.
