### ISSUE TITLE
[BUG] TinyMCE error 

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4239]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: #.#
 - Database: MariaDB 10.3.15

## Description

When I add some text and put image in textbox using BREAD's Rich Text Box, all content of texbox appearing like source code(with html tags)

## Steps To Reproduce
1. Add text , img  and customize them 
2. Get them on your content
3. See your content with tags like source code

## Expected behavior
I want get my content without tags

## Screenshots
![image](https://user-images.githubusercontent.com/40025822/60577344-9ad8cc80-9d98-11e9-92dd-8099c6367524.png)
 
this is how i get them: 
![image](https://user-images.githubusercontent.com/40025822/60577832-919c2f80-9d99-11e9-8e05-fba30e96c170.png)

How can I fix this?

**Comment by fletch3555** [comment]
https://laravel.com/docs/5.8/blade#displaying-data

Please ask questions in slack.
