### ISSUE TITLE
Edit my profile: UnauthorizedHttpException in Voyager.php line 104:

### ISSUE THREAD

**Issue by jun283** [thedevdojo/voyager#424]
- Laravel Version: 5.3.16
- Voyager Version: 0.11
- PHP Version:
- Database Driver & Version:

### Description:
if user (not in admin role) go to [Edit my profile],  get error:

UnauthorizedHttpException in Voyager.php line 104:
..................

I think this user not permit  to edit user model, then I change the user`s role to enable edit user model,
then  the user can edit 'my profile', but  just change [id] in url, this user can change any other user`s profile also,

**Comment by marktopper** [comment]
So you use Voyager admin panel for enabling users to edit their own profile?
This is ment as a admin panel, for admins.

So instead you would have to make a `edit profile` page on your front-end instead of giving users access to the admin panel.
