### ISSUE TITLE
Allow tagging in Belongs To Many relationship is not workin

### ISSUE THREAD

**Issue by shafiqkr18** [thedevdojo/voyager#4240]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database:MySQL 8.0

## Description
I want to use **ALLOW TAGGING** in **Belongs To Many relationship**. There are two issues i am facing

- I can not type new word to save , it only work for existing tags

- when i press enter key, it submit form instead of saving new tag

- It allow me to save duplicate tags as well.

- Even if new one is saved, it disappear from the box

## Steps To Reproduce
1. Go to BREAD and add relationship
2. create belongs to many relationship with pivot table
3. save it and come to entry form
4. you will see all above issues

## Expected behavior
I want to enter free text and it should save and keep in the box. also i do not want it to save duplicate same text.

**Comment by shafiqkr18** [comment]
Is anyone using Allow Tagging? Is it work for you?

**Comment by zzzaaa** [comment]
Repeated for me. I can enter only 2 chars, then I see long XHR request with full-html page result instead of JSON.
related to #4039

**Comment by shafiqkr18** [comment]
I think its not related to #4039 because i do not see any error in console. and yes i lose focus after typing 2 characters. Also the solution showing on vendor\tcg\voyager\resources\assets\js\app.js line 102 will apply then on each post request which i do not want to.

**Comment by emptynick** [comment]
Still the symptoms are the same, that's why I'm going to close this one.
