### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by nhytros** [thedevdojo/voyager#4255]
## Version information

 - Laravel: v5.8.27
 - Voyager: v1.2.2
 - PHP: PHP 7.3.6-1+0~20190531112640.39+buster~1.gbp6131b7 (cli) (built: May 31 2019 11:26:40) ( NTS )

 - Database: mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 

## Description:
I would like to use OpenStreetMap instead of Google Maps. It is possible to add this functionality? Thanks.

**Comment by fletch3555** [comment]
You can create your own field type and do whatever you need
