### ISSUE TITLE
Voyager Loader and font awesome are not displaying after hosting in cpanel [BUG]

### ISSUE THREAD

**Issue by rajaduraioec** [thedevdojo/voyager#4257]
I have uploaded my laravel voyager project on cpanel's subdomin. But Voyager loader and font awesome are not working after production. 

Laravel Version 5.8
Voyager 1.2 

I have modified env file App URL and avatar is displaying. 

I have tried copying font.css file from vendor directory to public/css and linked it in Voyager config as additional css.

But still no luck. Please help me to resolve this

![image](https://user-images.githubusercontent.com/51479352/60946112-fa8c2600-a30a-11e9-99b2-fca2329ea22a.png)

![image](https://user-images.githubusercontent.com/51479352/60946034-cdd80e80-a30a-11e9-9788-6e18e3101f40.png)

**Comment by fletch3555** [comment]
Please use the issue template in the future else you risk it being closed without response.  In this particular case, you provided the necessary information, so I'll let it slide

**Comment by rajaduraioec** [comment]
@fletch3555 Please how to do that?. This is the first time I am posting issues on Github. Can I modify now?

**Comment by emptynick** [comment]
Please show us the logs (both Laravel and PHP)

**Comment by ilearnbydoing** [comment]
I am facing the similar issue voyager-assets giving 500 error.
any help appreciated.

**Comment by emptynick** [comment]
The information I requested above are still necessary.

**Comment by ilearnbydoing** [comment]
Hi @emptynick thanks for quick reply here is the excerpt of log.

`[2019-11-02 06:54:27] local.ERROR: Call to undefined function Illuminate\Filesystem\finfo_file() {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Illuminate\\Filesystem\\finfo_file() at /home/confech9/public_html/domain.tld/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:323)
[stacktrace]
#0 /home/confech9/public_html/domain.tld/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Illuminate\\Filesystem\\Filesystem->mimeType('/home/confech9/...')
#1 /home/confech9/public_html/domain.tld/vendor/tcg/voyager/src/Http/Controllers/VoyagerController.php(85): Illuminate\\Support\\Facades\\Facade::__callStatic('mimeType', Array)`

the error occurs when I moved from VestCP to Cpanel.

**Comment by emptynick** [comment]
From that message you can see that you are missing the `finfo` PHP extension

**Comment by ilearnbydoing** [comment]
@emptynick thankyou so much I fixed the issue.

thanks
