### ISSUE TITLE
[Feature] use display_name in column filter

### ISSUE THREAD

**Issue by G3z** [thedevdojo/voyager#4258]
## Version information

 - Laravel: v5.8.27
 - Voyager: v1.2.6
 - PHP: 7.3
 - Database: [MysQL] [5.7.18] (e.g. MySQL 5.7)

## Description:
when using server pagination a handy searchable filter is displayed with all the columns for the current table/model.
Wouldn't it be better to use the row's display name ? 
This way column headers and search filters should have matching names

**Comment by fletch3555** [comment]
PR welcome

**Comment by emptynick** [comment]
Implemented in https://github.com/the-control-group/voyager/pull/4284
