### ISSUE TITLE
[BUG]Instillation issue - 

### ISSUE THREAD

**Issue by scriptophobia** [thedevdojo/voyager#4259]
## Version information

 - Laravel: v5.8.28
 - Voyager: v#.#.# -- Latest
 - PHP: 7.2.18
 - Database: MySQL 10.1.40-MariaDB (e.g. MySQL 8.0)

## Description

Unable to install Voyager on a fresh install of Laravel

## Steps To Reproduce
1. Installed Laravel
2. Ran `composer require tcg/voyager`
3. Updated .env file
4. Ran php artisan voyager:install
5. Error received: There are no commands defined in the "voyager" namespace.

## Expected behavior
Installation of Voyager to complete

## Additional context
I've installed Voyager in the past but now doing so on a new server with Centos installed and CWP (if it makes a difference).

**Comment by emptynick** [comment]
Please [search](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+There+are+no+commands+defined) before opening new issues.
I'm sure you'll find an answer in the other issues.
