### ISSUE TITLE
Customization work has been lost on Google App Engine.

### ISSUE THREAD

**Issue by guigawhata** [thedevdojo/voyager#4260]
- Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 

## Description:
Once I publish my app on Google App Engine, I can no longer view my custom routes, controllers, and views.

## Additional context
![Captura de tela em 2019-07-12 16-25-10](https://user-images.githubusercontent.com/26773799/61153456-ad9e8000-a4c1-11e9-8863-75e5c7b299ea.png)

During the Deploy process, Composer installs Voyager, but it comes as standard and all my customization work has been lost.

**Comment by guigawhata** [comment]
Someone? Please help me!

**Comment by emptynick** [comment]
Would be nice if you could tell what you did/changed so other people searching might get an answer.
