### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jhonaikerf** [thedevdojo/voyager#4262]
## Version information
 - Laravel: v5.7
 - Voyager: v1.2.6
 - PHP: 7.2
 - Database: MySql 5.7.24

## Description
403 This action is unauthorized.
I can enter the dasboard but I can not enter any item of the menu, since I get the error.
I think it's because of the authorize function, since I'm using a custom guard as specified in the document.

## Steps To Reproduce
1. Go to Dashboard
2. Click on Users
3. See error

**Comment by fletch3555** [comment]
Make sure your user's role has the appropriate permissions assigned

**Comment by jhonaikerf** [comment]
Yes, my user have all permissions. Is the default admin.
I had to change the default guard through a middleware for the Voyager routes.

**Comment by niels-numbers** [comment]
I had the problem after changing my default guard to 

```
  $this->app->singleton('VoyagerAuth', function () {
            return  \Auth::guard('admin');
        });
```
One has to change the default guard in `config/auth` to `admin`. 

It does currently not work to use a voyager guard other then the default guard, see #4334

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4384 (merged into 1.x)
