### ISSUE TITLE
Unable to modify columns of the tables which are created using seeding.[BUG]

### ISSUE THREAD

**Issue by mmkumr** [thedevdojo/voyager#4265]
After installing voyager I have initialized users and other tables using seeding. Then when I am trying to modify the data then it staying unchanged. When I am adding new data and modifying, it works correctly.

**Comment by emptynick** [comment]
Issue template is required. This can be reopened once the requested information is provided.

**Comment by mmkumr** [comment]
issue template?

**Comment by emptynick** [comment]
The part you deleted before you entered your text
