### ISSUE TITLE
Blank white page

### ISSUE THREAD

**Issue by ibrahimsayedahmad** [thedevdojo/voyager#4266]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2
 - PHP: 7.2.12
 - Database: [MariaDB] [10.1.37] (e.g. MySQL 8.0)

## Description:
Voyager is working perfect on local server but when upload to web server it just gives a blank white page.

**Comment by bplace** [comment]
Got the same issue on my local server :
Voyager 1.1
PHP 7.3.7 
MariaDB 10.2.25

Apache log reports : _AH00052: child pid xxx exit signal Bus error (10)_

Commenting in app.php line 
`App\Providers\RouteServiceProvider::class,`
allows the app the run.

**Comment by emptynick** [comment]
Unfortunately there is no way we can help you with so little information.
I'd suggest to ask in our Slack group as I'm quite sure it's some kind of misconfiguration.

**Comment by emptynick** [comment]
As mentioned before we can't help without further information.
Please update the issue and this can be reopened. Or, even better, ask in our Slack group.
