### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4267]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB 10.3.15

## Description

I have uploaded my project to the server(not to local one). And It is not showing any images on the site as well as Voyager admin panel.

## Steps To Reproduce
1. Go to https://ecouz.uz/
2. Open Console 
3. See error

## Expected behavior
I want to see images.

## Screenshots
this is how error looks like
![image](https://user-images.githubusercontent.com/40025822/61206993-660c3400-a70d-11e9-81de-c4f984d75d31.png)

this is my  .env file
![image](https://user-images.githubusercontent.com/40025822/61207057-8dfb9780-a70d-11e9-8110-80d5175d840a.png)

this is my public_html folder content in Panel
![image](https://user-images.githubusercontent.com/40025822/61209349-f26d2580-a712-11e9-9aee-ae7a3e383397.png)

**Comment by fletch3555** [comment]
Your APP_URL is wrong in your .env file.  I'm sure you can figure out what it should be

**Comment by KhurshidYakubov** [comment]
@fletch3555  I have chanched APP_URL to APP_URL=https://ecouz.uz/  .  And it is giving another error:

![image](https://user-images.githubusercontent.com/40025822/61217761-da54d080-a729-11e9-8e7a-02832870141f.png)
