### ISSUE TITLE
[BUG] PDO and MSSQL issue

### ISSUE THREAD

**Issue by marcellopato** [thedevdojo/voyager#4271]
## Version information

 - Laravel: v5.8.*
 - Voyager: v^1.2
 - PHP: v^7.1.3
 - Database: [MSSQL] [2017] 

## Description

PDO issue

## Steps To Reproduce
Install a new Laravel app, connect to MSSQL 2017 SERVER and install Voyager.

## Expected behavior
Clean install

## Additional context
Here's some code:

`Migrating the database tables into your application
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2016_01_01_000000_add_voyager_user_fields
Migrated:  2016_01_01_000000_add_voyager_user_fields
Migrating: 2016_01_01_000000_create_data_types_table
Migrated:  2016_01_01_000000_create_data_types_table
Migrating: 2016_05_19_173453_create_menu_table
Migrated:  2016_05_19_173453_create_menu_table
Migrating: 2016_10_21_190000_create_roles_table
Migrated:  2016_10_21_190000_create_roles_table
Migrating: 2016_10_21_190000_create_settings_table
Migrated:  2016_10_21_190000_create_settings_table
Migrating: 2016_11_30_135954_create_permission_table
Migrated:  2016_11_30_135954_create_permission_table
Migrating: 2016_11_30_141208_create_permission_role_table
Migrated:  2016_11_30_141208_create_permission_role_table
Migrating: 2016_12_26_201236_data_types__add__server_side
Migrated:  2016_12_26_201236_data_types__add__server_side
Migrating: 2017_01_13_000000_add_route_to_menu_items_table
Migrated:  2017_01_13_000000_add_route_to_menu_items_table
Migrating: 2017_01_14_005015_create_translations_table
Migrated:  2017_01_14_005015_create_translations_table
Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table

   PDOException  : SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute

  at /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:52
    48|      * {@inheritdoc}
    49|      */
    50|     public function getServerVersion()
    51|     {
  > 52|         return PDO::getAttribute(PDO::ATTR_SERVER_VERSION);
    53|     }
    54| 
    55|     /**
    56|      * {@inheritdoc}

  Exception trace:

  1   PDO::getAttribute()
      /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:52

  2   Doctrine\DBAL\Driver\PDOConnection::getServerVersion()
      /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:467

  Please use the argument -v to see more details.`

What now?

**Comment by fletch3555** [comment]
Voyager does not currently support MSSQL
