### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by thanhphonglx98** [thedevdojo/voyager#4273]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1
 - Database: MySQL 8.0

## Description

Can't upload images to share hosting

## Steps To Reproduce
1. Go to 'media'
2. Click on 'upload' button
3. See error:  the "" file does not exist or is not readable. voyager upload file

## Screenshots
![image](https://user-images.githubusercontent.com/53063480/61496764-68111400-a9e7-11e9-8a76-eaf418551326.png)

**Comment by emptynick** [comment]
We can't help you with so little information.
Please post logs from both Laravel and PHP.
This is very likely a misconfiguration on your server (for example max upload size etc.)

**Comment by emptynick** [comment]
Closing until we have more information.
