### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4274]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB 10.3.15)

## Description of problem

I don't show the posts. If there is no transaltion for them. For example, let's imagine  on my website I have a news block which i can add them in 2 languages. Every time I don't have avaliable content in 2 languages. So in some cases  I add news only with one language. And if i switch my website to English the content of this post will appear empty(only image). I want feature like , if didn't add the tranlation for this post don't show it on that language at all.  

## Additional context
this is the news block in Russian there I didn't add the tranlation in English
![image](https://user-images.githubusercontent.com/40025822/61529381-9d931d00-aa3a-11e9-88f0-83063d45f802.png)

As you see here we have only image without text, because I didn't add a translation. I want that If I don't add translation for the post easily don't show it on English page. show it only on Russian page
![image](https://user-images.githubusercontent.com/40025822/61529474-d59a6000-aa3a-11e9-8448-714c5afbd89b.png)

**Comment by emptynick** [comment]
Not sure what the "feature" would look like.
I think you have to implement that yourself in your front-end by filtering the results.
Also, we have a `whereTranslation` method where you could search for entries `!= ''`

**Comment by KhurshidYakubov** [comment]
@emptynick can you show the usage of `whereTranslation ` method by some examples ?

**Comment by emptynick** [comment]
```
$result = YourModel::whereTranslation('title', '!=', '', ['en'], false);
```
`$result` will then only contain results where a title in english is given.

**Comment by KhurshidYakubov** [comment]
Your example will be helpful. But let me explain one more time and get the answer. 
So, I want feature like this:
If title is not given in english, don't show this post when I switch Locale to english.  
II think that at this time I have explained it  more clearly)

**Comment by emptynick** [comment]
That is exactly what the line above does.
I still don't see the feature and therefore close this.
If you have further questions please ask in our Slack group.
