### ISSUE TITLE
[BUG] all commands in COMPASS is not working

### ISSUE THREAD

**Issue by vonsogt** [thedevdojo/voyager#4275]
## Version information

 - Laravel: v5.8.29
 - Voyager: v1.2.6
 - PHP: 7.3.7
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

The path in Environment on Windows not working at website which configuration file i should change?

## Steps To Reproduce
1. Go to 'Tools/Compass'
2. Click on 'Commands'
3. Scroll down to 'Any commands'
4. Run Command
5. See error

## Screenshots
![image](https://user-images.githubusercontent.com/35516476/61573562-30839400-aadb-11e9-9811-9348ab1414ce.png)

## Additional context
'xxx' is not recognized as an internal or external command,
operable program or batch file.

**Comment by fletch3555** [comment]
PHP is not on your system path. Just add it

**Comment by vonsogt** [comment]
> PHP is not on your system path. Just add it

I added it but, not working from web and working for CMD/Git bash
![image](https://user-images.githubusercontent.com/35516476/61574532-4dc05e80-aaeb-11e9-920c-395bac7441b9.png)

**Comment by emptynick** [comment]
Normally you have to restart your computer.

**Comment by fletch3555** [comment]
Did you restart the webserver (looks like xampp to me)?

**Comment by vonsogt** [comment]
It's still same,
I do restart my computer and XAMPP too

![image](https://user-images.githubusercontent.com/35516476/61600823-e6c2b700-ac5c-11e9-94c8-ebb83fc2e2b3.png)

Still not working

**Comment by vonsogt** [comment]
And yeah another project like "laravel-admin" cannot run any commands from Front End like this

> Starting backup...
Dumping database laravel_admin_ppat...
Backup failed because The dump process failed with exitcode 1 : General error : '"mysqldump"' is not recognized as an internal or external command,
operable program or batch file.

Really weird? any missing configuration on my computer
I'm using:
- Laravel installer : 2.1.0

to make new project then require any project from GitHub

**Comment by fletch3555** [comment]
> General error : '"mysqldump"' is not recognized as an internal or external command

That's 100% saying you don't have mysql installed OR the command is not available on your system path.  Nothing to do with Laravel or whatever package you were using, and especially nothing to do with Voyager.  Since you're using xampp, my guess is it's just not on your path

**Comment by vonsogt** [comment]
> > General error : '"mysqldump"' is not recognized as an internal or external command
> 
> That's 100% saying you don't have mysql installed OR the command is not available on your system path. Nothing to do with Laravel or whatever package you were using, and especially nothing to do with Voyager. Since you're using xampp, my guess is it's just not on your path

I did import my new path. Still not working and i have test the command in CMD/Git Bash it works

![image](https://user-images.githubusercontent.com/35516476/61767149-77d89000-ae0d-11e9-98e8-06ff1507de00.png)

**Comment by vonsogt** [comment]
What you can conclude from this code, it's same like voyager project too

https://justpaste.it/3izh5

@fletch3555

**Comment by fletch3555** [comment]
I don't know what to tell you.  That specific message has absolutely nothing to do with Voyager.  It's stating that the command does not exist or is otherwise inaccessible at runtime

**Comment by egyjs** [comment]
i have the same issue ,, any one can fix this?

**Comment by d3turnes** [comment]
i have the same issue ,, any one can fix this?

**Comment by seo-broweb** [comment]
@el3zahaby , @d3turnes , @vonsogt I had a similar issue in docker on linux. I fix it like this: in voyager/src/Http/Controllers/VoyagerCompassController.php i pass full_path for php bin file instead just 'php' :
`$process = new Process('cd '.base_path().' && ' . config('voyager.php_bin_path') . ' '.$command.$args)
`
The reason of issue: symfony Process object don't have access to all env variables of system.
For details: https://github.com/symfony/symfony/issues/18847
Sorry my english, brothers)

**Comment by vonsogt** [comment]
> @el3zahaby , @d3turnes , @vonsogt I had a similar issue in docker on linux. I fix it like this: in voyager/src/Http/Controllers/VoyagerCompassController.php i pass full_path for php bin file instead just 'php' :
> `$process = new Process('cd '.base_path().' && ' . config('voyager.php_bin_path') . ' '.$command.$args) `
> The reason of issue: symfony Process object don't have access to all env variables of system.
> For details: [symfony/symfony#18847](https://github.com/symfony/symfony/issues/18847)
> Sorry my english, brothers)

Not working for windows user maybe
![image](https://user-images.githubusercontent.com/35516476/63659782-81269500-c7dd-11e9-881b-039a696dd0db.png)

and when I change the path to this:
`$process = new Process('cd '.base_path().' && C:\\xampp\\php\\php.exe artisan' . config('voyager.php_bin_path') . ' '.$command.$args);`
will return this error:
![image](https://user-images.githubusercontent.com/35516476/63659807-bb903200-c7dd-11e9-8a35-67524baa1bbc.png)

**Comment by fletch3555** [comment]
@seo-broweb, Please don't recommend editing files under `vendor`

**Comment by seo-broweb** [comment]
@fletch3555 , I did not recommend it, where i say about vendor? You can do fork or pull request.

**Comment by fletch3555** [comment]
Many of our users are novice, so while you didn't suggest it explicitly, you gave a file path that will exist locally only under vendor, so many will naively make that change as if it were your suggestion.

We prefer recommending that changes be opened as pull requests so everyone can benefit.  The exception to this is changes that meet a very unique use-case.

**Comment by MrCrayon** [comment]
With #4856 now `Artisan::call` is used for all Compass commands.

If you are still experiencing problems please open another issue.
