### ISSUE TITLE
Usage of rich text box in voyager

### ISSUE THREAD

**Issue by ahmedlab311** [thedevdojo/voyager#4278]
## Version information

 - Laravel: v5.4
 - Voyager: v2.0
 - PHP: 7.0
 - Database: [MySQL] [5.1.73] 

## Description

when i use rich text box in voyager admin panel, it is correct but in front end side it appear as symbol. how can solve this?

## Screenshots

![Firefox_Screenshot_2019-07-21T04-19-20 843Z](https://user-images.githubusercontent.com/40799079/61608098-ce00d400-ac51-11e9-9bea-75fa947f7fd7.png)
![Firefox_Screenshot_2019-07-21T04-19-43 494Z](https://user-images.githubusercontent.com/40799079/61608099-ce00d400-ac51-11e9-9372-071a3ac01fef.png)

**Comment by Braiani** [comment]
Make sure you're using the correct interpolation on your blade file:
> {!! $variable !!}

**Comment by emptynick** [comment]
That's exactly the problem.

**Comment by ahmedlab311** [comment]
> 
> 
> Make sure you're using the correct interpolation on your blade file:
> 
> > {!! $variable !!}

Tank you very much
