### ISSUE TITLE
BREAD ordered field initialization.

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4279]
## Version information

 - Voyager: v1.2

## Description:

Hi!

I already asked this question earlier, but they did not understand me correctly.

I have a BREAD model with a ordered field. When creating a record of this model, do I need to initialize this field manually or Voyager has automatic initialization mechanism? I can't find answer in documentation.

Thank u!

**Comment by emptynick** [comment]
The issue template is required when opening new issues and it prompts you to ask questions in our Slack group.
Did you try it?
If its not mentioned in the docs it likely won't do what you want.
Mutator is the magic word here.
