### ISSUE TITLE
Model name confusion

### ISSUE THREAD

**Issue by paddelboot** [thedevdojo/voyager#4280]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 14.14

## Description
I am trying to create a database table with BREAD. But the table columns are **not shown in the BREAD editor screen**, and when trying to browse the BREAD, I get an **error message because of a non-existant model name** (using a model name `Referenz`, voyager is looking for `Referenzs`, adding the plural "s" for some reason).

## Steps To Reproduce
1. Create a table with the name `referenzen` using the database manager. Do not chose the option to automatically create a model. 
2. Go to the command line and do: `php artisan make:model Referenz`, which is the singular form of "Referenzen". 
3. Add BREAD to the database table using the BREAD editor. Fill in the model name (`App\Referenz`) and the Singular/Plural fields.

In the BREAD editor screen of the database table, no columns are shown. If I click "Browse BREAD" in the table overview, I get the error `Base table or view not found: 1146 Table 'db.referenzs' doesn't exist`.

## Expected behavior
Voyager using the model `App\Referenz` as noted in the BREAD options of that table. Showing database columns in BREAD editor.

## Screenshots
Details from the BREAD editor screen when adding the BREAD to the table:
![Bildschirmfoto vom 2019-07-22 20-38-56](https://user-images.githubusercontent.com/632353/61656766-c5e07d00-acc1-11e9-97e8-3fdf3e3d3a66.png)

No database columns are shown when trying to edit BREAD:
![Bildschirmfoto vom 2019-07-22 20-47-27](https://user-images.githubusercontent.com/632353/61656866-f45e5800-acc1-11e9-9d1c-5825d02b1e0f.png)

## Additional context
Similar issue, maybe: https://github.com/the-control-group/voyager/issues/355

**Comment by emptynick** [comment]
That's not related to Voyager, but a naming convention of Laravel. See https://laravel.com/docs/5.8/eloquent#eloquent-model-conventions

**Comment by paddelboot** [comment]
>By convention, the "snake case", plural name of the class will be used as the table name unless another name is explicitly specified.

I was under the impression that we did explicitly specify the table name? I mean, Laravel wouldn't have to "assume" it's name, adding an "s".

So in short: database tables must be in English, because of the naming convention?

**Comment by paddelboot** [comment]
Never mind, I just passed the table name to my model:

`protected $table = 'referenzen';`
