### ISSUE TITLE
Menu builder showing items after they were deleted.

### ISSUE THREAD

**Issue by paddelboot** [thedevdojo/voyager#4285]
## Version information
    Laravel: v5.8
    Voyager: v1.2
    PHP: 7.2
    Database: MySQL 14.14

## Description:
After deleting an admin menu item, it is still shown in both the admin menu and the page builder tree. Running `artisan cache:clear` and/or `artisan view:clear` did not resolve the issue. Trying to delete the item again from the menu builder tree results in a 404 Error page.

If I edit an existing menu item and save, the "phantom items" are gone. So I assume it's some kind of caching issue.

**Comment by Braiani** [comment]
Maybe it's a browse caching. Try to refresh your browser cleaning the cache (Major browser is crtl + F5).

**Comment by MrCrayon** [comment]
@paddelboot which version of Voyager are you using exactly?
It's a known bug solved in #4083, so starting from v1.2.4 it should be solved.

**Comment by emptynick** [comment]
Unfortunately we don't have the full Voyager version number, so I'm going to assume its below 1.2.4.
If its 1.2.5 upwards, please let us know.

**Comment by paddelboot** [comment]
It was 1.2.2, updating right now.
