### ISSUE TITLE
[BUG] i uploaded my vayager to the server on 000webhost but all the images is broken how to solve this 

### ISSUE THREAD

**Issue by Lucife9695** [thedevdojo/voyager#4286]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

**Comment by emptynick** [comment]
From the issue template:
>  The following information is required for bug reports.  Issues without it will be closed without response

**Comment by Lucife9695** [comment]
@emptynick please i really need help for this

**Comment by fletch3555** [comment]
Then provide the required information

**Comment by Lucife9695** [comment]
@fletch3555 which required information? sorry i am new to github

**Comment by tusharsinhparmar** [comment]
Try two options
1) Run "php artisan storage:link" command
Or
2) Add port in your .env file
    Ex. APP_URL=http://localhost:8000
    or what ever your host and port
