### ISSUE TITLE
Images not showing in server (000webhost)

### ISSUE THREAD

**Issue by Lucife9695** [thedevdojo/voyager#4287]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
i already uploaded my laravel project with voyager to 000webhost server but the image all come out broken and i uploaded file is not able to download says(file not found). I put my APP_URI; my server what i did for my localhost but image still broken  but the file can upload 

## Screenshots
![image](https://user-images.githubusercontent.com/40648578/61791296-2e5b6580-ae4c-11e9-9968-27899c369760.png)

**Comment by fletch3555** [comment]
As stated in #4286, just edit the issue and provide the required information

**Comment by bcmarcos03** [comment]
Im struggling with this also... and my texts are all voyager::seeders.settings........

**Comment by tusharsinhparmar** [comment]
Try two options
1) Run "php artisan storage:link" command
Or
2) Add port in your .env file
    Ex. APP_URL=http://localhost:8000
