### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lucife9695** [thedevdojo/voyager#4288]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description

I uploaded my laravel with voyager to 000webhost, in my localhost i was able to view/download my file and image. After i post it to the server the image in avatar and uploaded is not showing.
I already configure my .env file with the APP_URI below website.

## Steps To Reproduce
1. Go to https://lkcfesnotification.000webhostapp.com
2. Click on 'enter'
3. 
4. Error was no avatar image even if i upload it

## Expected behavior
It should able to view my image and download my uploaded file 

## Screenshots
1)my content file
![image](https://user-images.githubusercontent.com/40648578/61795929-0ae9e800-ae57-11e9-8f40-fe4c5df92d25.png)
2)My uploaded image, file and avatar not viewing 
![image](https://user-images.githubusercontent.com/40648578/61796029-379dff80-ae57-11e9-86cd-c6e9fe75cf6b.png)
3) my storage path
![image](https://user-images.githubusercontent.com/40648578/61796122-61efbd00-ae57-11e9-9be3-a3898081f47e.png)
4) my .env File
![image](https://user-images.githubusercontent.com/40648578/61796185-7d5ac800-ae57-11e9-8a8b-3b1bcf451992.png)
5) My website detail
![image](https://user-images.githubusercontent.com/40648578/61796217-8d72a780-ae57-11e9-96e7-93f24ce99f2b.png)

## Additional context
This i my school project and i need to submit this next week monday pls do help thank in advance if anyone can help me

**Comment by fletch3555** [comment]
Please show the contents of your `/public_html` directory

**Comment by Lucife9695** [comment]
![image](https://user-images.githubusercontent.com/40648578/61816740-8fe8f780-ae7f-11e9-86ba-671325d9659b.png)
this is my public_html

**Comment by DaLooK** [comment]
Your image is accessible with the following link:
`http://lkcfesnotification.000webhostapp.com/storage_old/users/July2019/ZJuiL2kmeQrbudVOazVK.webp`

But your voyager instance is generating this link:
`http://lkcfesnotification.000webhostapp.comstorage/storage_old/users/July2019/LPuebc2SHyDUrhVvka2I.jpg`

As you can see, the link is not generating correctly by the **.comstorage/storage_old**

My guess is that you _**config/filesystems.php**_ is not correctly configured. Maybe try using the following code in the public disk configuration
```
'public' => [
    'driver' => 'local',
    'root' => storage_path('app/public'),
    'url' => env('APP_URL').'/storage_old',
    'visibility' => 'public',
],
```

**Comment by Lucife9695** [comment]
@DaLooK  the file will show in my media but when i upload a new file the image broke again and when i download my file it says file not found below is the image
![image](https://user-images.githubusercontent.com/40648578/61821983-19ea8d80-ae8b-11e9-81a6-f821e55ae726.png)

**Comment by DaLooK** [comment]
@Lucife9695 Can you show your **_config/filesystems.php_** file

**Comment by Lucife9695** [comment]
![image](https://user-images.githubusercontent.com/40648578/61822470-2a4f3800-ae8c-11e9-9d04-a4569bfe8dba.png)
![image](https://user-images.githubusercontent.com/40648578/61822493-36d39080-ae8c-11e9-9987-d5adb29a6663.png)

The file is uploaded but they do not display
@DaLooK

**Comment by Lucife9695** [comment]
@DaLooK forget to include in description that when i upload to the server i chg the /public to /public_html just in case if any related

**Comment by fletch3555** [comment]
I see no reason for renaming the `public` directory like that, but it should be fine as long as you tell laravel about it by overriding `public.path` (googling that should give plenty of results)

**Comment by Lucife9695** [comment]
@fletch3555 u mean change in app service provider and in index.php?

**Comment by fletch3555** [comment]
You should only have to set it once, but yes, the change should go in a serviceprovider

**Comment by Lucife9695** [comment]
@fletch3555 i already added that in appservice provider it does not work. then i bind in the public_html  index.php this error come out
![image](https://user-images.githubusercontent.com/40648578/61922777-2dcde680-af94-11e9-9756-ec122739af7c.png)

**Comment by fletch3555** [comment]
Well you haven't shared what you put in appserviceprovider, so I can't say for certain, but that error indicates you did something wrong.  `/opt/awex-pages:/storage/........` (note the colon, `:`, after `awex-pages`)

**Comment by Lucife9695** [comment]
@fletch3555 
public function register()
{
    $this->app->bind('path.public', function() {
        realpath(base_path().'/public_html');
    });
}
I added then it work for me but then the image i uploaded is not showing up

**Comment by Lucife9695** [comment]
OK IT WORK NOW !!!!!!!!!!!! i just  rename my storage and login to my page click fix it and then all file can upload now and view and download thx for help me
