### ISSUE TITLE
Redirecting to default old admin prefix after login even changing route prefix in web.php

### ISSUE THREAD

**Issue by irshadalijan** [thedevdojo/voyager#4289]
## Version information

 - Laravel: v5.8.x
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MYSQL

## Description

I updated the route prefix from default 'admin' to 'backend'
Route::group(['prefix' => 'backend'], function () {
    Voyager::routes();
});

but as i logged out and tried to login again then after successful login it still redirects to 'admin' route. While if i hard code url like app_url/backend then i am shown the admin panel.

## Steps To Reproduce
1. changed the routes prefix in web.php
2. logged out from current logged in application
3. it redirects to new route login page
4. when i logged in now it redirects me to old 'admin' route which is not available anymore.

## Expected behavior
After changing routes prefix in web.php it should redirect me to my changed route after successful login

**Comment by fletch3555** [comment]
That _shouldn't_ be possible, since everything in Voyager should be using named routes.  Do you have a `user.redirect` config set in `config/voyager.php`? (https://github.com/the-control-group/voyager/blob/1.2/src/Http/Controllers/VoyagerAuthController.php#L54)

**Comment by irshadalijan** [comment]
Yes, now fixed. I didn't know that we have to set it on multiple places. 
After changing route prefix in web.php one must have to change user.redirect in config/voyager.php as well.
Thanks for your response i will close the issue.

**Comment by fletch3555** [comment]
Thanks for confirming.  Glad you have it working now
