### ISSUE TITLE
[BUG]Menu Builder Items in third level don't sort

### ISSUE THREAD

**Issue by mf0wzi** [thedevdojo/voyager#4293]
The menu builder don't sort items in view if they are nested in level three the value change in the database but  the menu don't sort

**Comment by emptynick** [comment]
From the issue template:
> The following information is required for bug reports.  Issues without it will be closed without response

Also:
https://github.com/the-control-group/voyager/pull/4186

**Comment by mf0wzi** [comment]
I Manage to solve it by adding sortBy('order'), like so
@foreach ($items->sortBy('order') as $item)

in the foreach loop for the menu builder and the front end menu in Voyager v1.2.6
