### ISSUE TITLE
how do i auto generate ID using bread

### ISSUE THREAD

**Issue by atish-shakya** [thedevdojo/voyager#4296]
## Version information

 - Laravel: v5.8.29
 - Voyager: v1.2
- PHP: #7.3.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
How can I auto generate ID using voyager bread. can it be done using 'optional details'

**Comment by fletch3555** [comment]
Per the issue template, questions should be asked in slack. We need quite a bit more information, and slack provides a much faster communication style.
