### ISSUE TITLE
How to use video attribute in bread as input type equal to file 

### ISSUE THREAD

**Issue by shaileshmaurya17** [thedevdojo/voyager#4297]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

**Comment by emptynick** [comment]
From the issue template:
> The following information is required for bug reports.  Issues without it will be closed without response

And
> IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST
