### ISSUE TITLE
How to validate the data before input in database?

### ISSUE THREAD

**Issue by raoasifraza1** [thedevdojo/voyager#430]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7.0.9
- Database Driver & Version: Mysql & 7.0.9-

### Description:
How to validate the input data before insert in database.

### Steps To Reproduce:
When create the new database table and also add BREAD. How to validate the form when open for insert data into database.

**Comment by marktopper** [comment]
In your BREAD under `Optional Details` for your field, enter the following using Laravel's validation rules.

```
{
    "validation": {
        "rule": "required|min:20"
    }
}
```

**Comment by raoasifraza11** [comment]
Thanks @marktopper
