### ISSUE TITLE
belongsTo Relationship has error - access violation: 1064

### ISSUE THREAD

**Issue by d3turnes** [thedevdojo/voyager#4301]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2.6
 - PHP: 7.1.26
 - Database: MySQL 5.7.24

## Description

Hi all.
I have a categories table (id, parent_id, name, slug, order, created_at, updated_at),
i do Relationship with bread (category_blongsto_category_relationship)

stdClass Object
(
    [model] => App\Category
    [table] => categories
    [type] => belongsTo
    [column] => parent_id
    [key] => id
    [label] => name
    [pivot_table] => 
    [pivot] => 0
    [taggable] => 0
)

when i add or edit an category, call request ajax admin/categories/relation?type=category_belongsto_category_relationship&method=edit&page=1
server return 
{
	"message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0' at line 1 (SQL: select * from `categories` offset 0)",
    "exception": "Illuminate\\Database\\QueryException",
}

File: VoyagerBreadController.php
Method: relation
Line: 557

$relationshipOptions = app($options->model)->take($on_page)->skip($skip)->get(); // Error

$relationshipOptions = app($options->model)->take($on_page)->get(); // OK

**Comment by MrCrayon** [comment]
I think the problem is that there should be LIMIT before OFFSET like:
```mysql
select * from categories limit 50 offset 0
```
I'm not sure why it's not there, what's the value for $on_page?

**Comment by d3turnes** [comment]
hi.

the value for $on_page default is 50

**Comment by MrCrayon** [comment]
It's very strange, on fresh install with dummy data I changed Categories adding the relationship on parent_id, when I go on edit I have the same ajax call:
```
Request URL: http://voyager-clean.mc/admin/categories/relation?type=category_belongsto_category_relationship&method=edit&page=1
Request Method: GET
Status Code: 200 OK
```
But no error and the logged query is:
```
[2019-08-01 13:23:32] local.INFO: select * from `categories` limit 50 offset 0  
```

I'd suggest you to try on a fresh install with the steps described above to see if you still have the same error.

You can log all queries adding in AppServiceProvider:
```php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

    public function boot()
    {
        DB::listen(function($query) {
            Log::info(
                $query->sql,
                $query->bindings,
                $query->time
            );
        });
    }
```

**Comment by MrCrayon** [comment]
Did you extend or change anything?
Because the line you changed is not where you said it was:
https://github.com/the-control-group/voyager/blob/f3b69172e2f20297183476a1a841561fa84256f4/src/Http/Controllers/VoyagerBaseController.php#L683

**Comment by d3turnes** [comment]
ok thank you! problem solve
