### ISSUE TITLE
How do I add the custom admin page to the permission?

### ISSUE THREAD

**Issue by goophps** [thedevdojo/voyager#4303]
Laravel Version: v5.8
Voyager Version: v1.2
PHP Version: 7.3

Help me. I've been searching for days, not knowing what to do with it.

How do I add new views or actions to the permissions in the figure below that has nothing to do with a BREAD view?

![image](https://user-images.githubusercontent.com/49714224/62161590-25392f80-b349-11e9-96ca-88d6cf32f003.png)

**Comment by emptynick** [comment]
The answer has already been answered on Slack, and, as the issue templates suggest, questions shouldn't be asked in issues.

**Comment by goophps** [comment]
> Slack已经回答了答案，并且正如问题模板所示，问题不应该在问题中提出。

I searched Slack for a long time, but couldn't find the answer. Can you tell me the link to the answer?
