### ISSUE TITLE
Action buttons are not controlled by permissions

### ISSUE THREAD

**Issue by goophps** [thedevdojo/voyager#4304]
Laravel Version: v5.8
Voyager Version: v1.2

My own action button, how do I add permissions? https://docs.laravelvoyager.com/customization/action-buttons . I checked the documentation and didn't know how to add permissions.

Then I found out why

![image](https://user-images.githubusercontent.com/49714224/62166232-d395a280-b352-11e9-9ae9-e5051582eacd.png)

**Comment by emptynick** [comment]
This is only for mass-action what you aren't looking for right?
Even if you use mass-actions - you could still use `shouldActionBeDisplayedOnDataType()` to hide it on whatever condition you want.
And, as said before, questions should be asked on Slack.
