### ISSUE TITLE
Files getting removed from DB when no new files are uploaded

### ISSUE THREAD

**Issue by jagroop** [thedevdojo/voyager#4305]
## Version information

 - Laravel: v5.8.30
 - Voyager: v1.2.6
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

Files getting removed from DB when no new files are uploaded , I know there is already a closed issue addressing the same problem https://github.com/the-control-group/voyager/issues/4020 and a Pull requests that fixes this problem https://github.com/the-control-group/voyager/pull/4158 . But i am using latest version of Laravel Voyager , This issue still exist

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to Settings
2. Add a Video file in settings under any group
3. Try Updating other fields except video file
4. The file will be removed

## Expected behavior
Existing File should not be removed if i am not selecting new file.

## Video recording

https://www.loom.com/share/a7e97fab05b0451db86b5fbd2b37fef5

**Comment by MrCrayon** [comment]
@jagroop I can reproduce the bug, fix it's easy, check PR.

**Comment by Diaa-Boraq** [comment]
any update on this issue, or pointer how can I override it or fix it? I'm still losing files on edit and dont know how to fix it. Thanks

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4309 (merged into 1.x)
