### ISSUE TITLE
how can i create auto generate ID using bread in VOYAGER.

### ISSUE THREAD

**Issue by atish-shakya** [thedevdojo/voyager#4308]
## Version information

 - Laravel: v5.8.17
 - Voyager: v1.2.6
 - PHP: 7.3.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description of problem
How can I create auto generating unique ID using Bread .

## Proposed solution
I want to create a new ID which can be auto generated with unique ID. I want to know if it can be created using bread.

**Comment by emptynick** [comment]
Question (partly) answered on Slack.
Please follow the issue template and ask questions only there.
