### ISSUE TITLE
Footer not on right side

### ISSUE THREAD

**Issue by raoasifraza11** [thedevdojo/voyager#431]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7.0.9
- Database Driver & Version: mysql & 7.0.9

### Description:
Footer not set on right side

### Steps To Reproduce:
Footer section is on left side in my system.
```
<footer class="app-footer">
    <div class="site-footer-right">
        Made with <i class="voyager-heart"></i> by <a href="http://thecontrolgroup.com" target="_blank">The Control
            Group</a> - {{ Voyager::getVersion() }}
    </div>
</footer>
```

I've fix with float-right:
```
<footer class="app-footer">
    <div class="site-footer-right float-right">
        Made with <i class="voyager-heart"></i> by <a href="http://thecontrolgroup.com" target="_blank">The Control
            Group</a> - {{ Voyager::getVersion() }}
    </div>
</footer>
```

**Comment by ghost** [comment]
Did you add something to the footer because the next by default is on the right? It's also `text-align:right` which is pushing the text to the right side of the footer

**Comment by raoasifraza11** [comment]
I don't change any front-end styling. Let me check it again by fresh
installation.

**Comment by raoasifraza11** [comment]
Okay Done @brandy I checked it footer is on right place.
