### ISSUE TITLE
[BUG] Multiple Images Field, Cannot delete image

### ISSUE THREAD

**Issue by ostrichegret** [thedevdojo/voyager#4315]
## Version information

 - Laravel: v5.8.30
 - Voyager: v1.2.6
 - PHP: 7.2.3
 - Database: MySQL 8 8.0.15

## Description

Cannot delete uploaded images on Multiple Images Field

## Steps To Reproduce
1. Install Laravel and Voyager
2. Create table 'test'
3. column test_id = int, test_name = varchar 190, test_gallery = text
4. Create BREAD on test table: test_id = text_field, test_name = text_field, test_gallery = Multiple Images
5. Input record on test
6. Add test name and put 2 images on test_gallery, submit
7. Edit the field and try to remove the images on test_gallery = Fail, add image still works. 

## Expected behavior
It should be able to delete the uploaded images on multiple images field

## Screenshots
Header:
Provisional headers are shown
Accept: */*
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Origin: http://127.0.0.1:8000
Referer: http://127.0.0.1:8000/admin/test/1/edit
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
X-CSRF-TOKEN: qkwcuvofk0gUul7oSq644wL3b87XluIg1VqG9sCP
X-Requested-With: XMLHttpRequest
slug: test
filename: test\August2019\oHM45IsWkl2bOllHEAtP.jpg
id: 
field: test_gallery
multi: true
_token: qkwcuvofk0gUul7oSq644wL3b87XluIg1VqG9sCP

Response:
{"data":{"status":400,"message":"Field does not exist"}}

**Comment by emptynick** [comment]
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4095

**Comment by ostrichegret** [comment]
@emptynick the browser media permission is set.

Header:
Provisional headers are shown
Accept: /
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Origin: http://127.0.0.1:8000
Referer: http://127.0.0.1:8000/admin/test/1/edit
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
X-CSRF-TOKEN: qkwcuvofk0gUul7oSq644wL3b87XluIg1VqG9sCP
X-Requested-With: XMLHttpRequest
slug: test
filename: test\August2019\oHM45IsWkl2bOllHEAtP.jpg
id:
field: test_gallery
multi: true
_token: qkwcuvofk0gUul7oSq644wL3b87XluIg1VqG9sCP

The header sent by client got issue,
the id; field is empty

I tried to manualy set the id on voyagermediacontroller and it works


`<img src="http://localhost:8000/storage/test/August2019/Zuha9qVl6EaahjUyrDGs.jpg" data-file-name="test\August2019\Zuha9qVl6EaahjUyrDGs.jpg" data-id="" style="max-width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:5px;">`

data-id is empty

**Comment by emptynick** [comment]
In that case it looks like you didn't set your `test_id` field to be the primary key for your model.

**Comment by ostrichegret** [comment]
@emptynick 

already set it:
app/test.php
```

<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Traits\Resizable;

class Test extends Model
{
    //
    use Resizable;

    public $timestamps = false;
    protected $primaryKey = "test_id";
    protected $table = 'test';

}

```

Database
```

CREATE TABLE `test`  (
  `test_id` int(10) NOT NULL AUTO_INCREMENT,
  `test_name` varchar(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `test_gallery` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  PRIMARY KEY (`test_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;
```

is voyager looking for hardcoded 'id' rather than $primaryKey?


`<img src="{{ Voyager::image( $image ) }}" data-file-name="{{ $image }}" data-id="{{ $dataTypeContent->test_id }}" style="max-width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:5px;">
            `

I changed $dataTypeContent->id to $dataTypeContent->test_id and it works,
Is there a helper to get $primaryKey ?

found it:
`<img src="{{ Voyager::image( $image ) }}" data-file-name="{{ $image }}" data-id="{{ $dataTypeContent->getKey() }}" style="max-width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:5px;">`


After some search
some code on voyager already use
$dataTypeContent->getKey()

and there are still code use hardcoded $dataTypeContent->id

https://github.com/the-control-group/voyager/pull/4317
