### ISSUE TITLE
Parent menu no more clickable after adding submenu

### ISSUE THREAD

**Issue by TnCoders** [thedevdojo/voyager#432]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.5
- PHP Version: 7
- Database Driver & Version:

### Description:
After i add a menu as a submenu to another menu the parent menu is no more clickable.

**Comment by fletch3555** [comment]
I have a feeling this was done on purpose (specifically for the Tools menu), though that doesn't mean it can't be added.

**Comment by akazorg** [comment]
closing this issue, menu is working with the expected behavior.
