### ISSUE TITLE
Pass classname or style to special column

### ISSUE THREAD

**Issue by loverdeveloper** [thedevdojo/voyager#4321]
## Version information

Laravel Version: 5.8
Voyager Version: Latest
PHP Version: 7.3
Database Driver & Version: 10.3.3-MariaDB & MySQL 5.7
Server version: 10.3.3-MariaDB-log - mariadb.org binary distribution
Database client version: libmysql - 5.6.34

## Description

I search every where and i can't find my answer, how i can pass a class name to a special column,
i need a column with bigger number than other.
ex: something like this **8**/2

**Comment by emptynick** [comment]
Please follow the issue template and ask questions in our Slack group.
