### ISSUE TITLE
Custom relationship attributes, how to make it work?

### ISSUE THREAD

**Issue by marvix** [thedevdojo/voyager#4324]
I did as the docs, but the new attribute still missing, how to fix it?

in the model
![image](https://user-images.githubusercontent.com/3768431/62716754-567dc380-ba0b-11e9-9106-1e73a51efecd.png)
![image](https://user-images.githubusercontent.com/3768431/62716886-8d53d980-ba0b-11e9-828a-e49dca8b9876.png)

The docs do not say where to select the custom attribute.

Thanks,

**Comment by emptynick** [comment]
This is indeed documented in the last sentence of that docs article.
Also, the issue template is required and prompts you to ask questions in our Slack group.
