### ISSUE TITLE
Loading failed for ... /voyager-assets?path=js/app.js ?

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#4327]
## Version information
 - Laravel: v5.6.39
 - Voyager: v1.2.6
 - PHP: 7.2.14my
 - Database: MySQL Server version 5.7.25 

## Description
I was upgrading from v1.1.10 to v1.2.6 and now the page is not loading (the wheel spins forever).

## Steps To Reproduce
1. Upgrading from v1.1.10 to v1.2.6
2. Removed `public/vendor/tcg/voyger` folder
3. Removed `assets_path`from `config/voyger.php`
4. Add controllers ` php artisan voyager:controllers`
4. Modify  `App/Http/Controllers/Voyager/VoyagerController.php` 
```
  public function index()
  {
    return view('admin.index');
 }
```
4. Point to this blade:

```
@extends ('voyager::master')

@section('content')
Hallo
@endsection
```
4. Load Admin Page
5. See error

## Expected behavior
Render page in finite time.

## Screenshots
This is how it looks when I open `http://member-nlp.test/admin`. There is no menu loaded or anything, just a wheel spinning:
![image](https://user-images.githubusercontent.com/1765602/62790575-b0de5900-bacb-11e9-8487-61c19176315f.png)

This is the shown by the inspector, showing that `js/app.js` could not be loaded (i have not mentioned that file in `config/voyager.php`:
![image](https://user-images.githubusercontent.com/1765602/62790751-00bd2000-bacc-11e9-8d0c-ceb7e009a57a.png)

## Additional context
When I change the index method in `App/Http/Controllers/Voyager/VoyagerController.php` like this: 

```
public function index()
{
  return 1;
}
```
Then  `http://member-nlp.test/admin` will return sucessfuly 1.

**Comment by emptynick** [comment]
The path to the assets contains `%3Fv%3D2` which translates to `?v=2` which the controller can't find.
Where does it come from?

**Comment by niels-numbers** [comment]
Oh true, I forgot that I overwrote  the `master.blade` by `/resource/views/vendor/voyager/master.blade`. Removed the `?v=2` and now its working. Thanks a lot!!!
