### ISSUE TITLE
Error validation roles

### ISSUE THREAD

**Issue by d3turnes** [thedevdojo/voyager#4329]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2.6
 - PHP: 7.1
 - Database: MySQL  5.7.24

## Description
Posible bug, add rules validation bread Roles return text plain 

`{
"errors": {
"name": [
"The Name has already been taken."
]
}
}`

## Steps To Reproduce

1. Go to 'Tools\Bread\roles'
2. Edit Bread Roles
3. Add rule validation field name

`{
    "validation": {
        "rule": "required|unique:roles,name"
    }
}`

and field display_name

`{
    "validation": {
        "rule": "required"
    }
}`

4. Click on 'submit button'

then

1. Go to 'Roles'
2. Click on 'Add new'
3. Fill form with Name: admin Display Name: something 
4. Click on 'submit button' 
4. See error text-plain

`{
"errors": {
"name": [
"The Name has already been taken."
]
}
}`

## Screenshots
![role1](https://user-images.githubusercontent.com/32837544/62833258-0b96c280-bc3c-11e9-88c5-f4e174e240a7.png)

submit button

![role2](https://user-images.githubusercontent.com/32837544/62833260-0df91c80-bc3c-11e9-9db3-3d8834795f94.png)

**Comment by emptynick** [comment]
Is this a bug report?

**Comment by d3turnes** [comment]
return response()->json(['errors' => $val->messages()]);

**Comment by d3turnes** [comment]
![role1](https://user-images.githubusercontent.com/32837544/62833258-0b96c280-bc3c-11e9-88c5-f4e174e240a7.png)

submit button

![role2](https://user-images.githubusercontent.com/32837544/62833260-0df91c80-bc3c-11e9-9db3-3d8834795f94.png)

**Comment by emptynick** [comment]
I still don't know if this is an issue report.
Please fill out the issue template completely.

**Comment by classiebit** [comment]
It's an issue. I'm getting the same issue. 

When we add unique column validation in Roles bread, it gives unique column validation error even in case of updating the roles. 

It should be applied when updating the role, only in case of- 

if(current_role_name != edited_role_name)
    apply_unique_column_validation_rule

@emptynick

**Comment by d3turnes** [comment]
the same occurs bread users with validation

**Comment by d3turnes** [comment]
@classiebit Solved
[see result here](https://github.com/the-control-group/voyager/blob/bffcbf59091d6ec84ec67ae438c9684a2a9c9af8/src/Http/Controllers/VoyagerRoleController.php)

Step 1
Edit file routes/web.php and add
![step1](https://user-images.githubusercontent.com/32837544/63265674-73798880-c28e-11e9-9e48-458b7d69c3a2.png)
Step 2
Copy file from voyager/src/Http/Controllers/VoyagerRoleController.php to app\Http\Controllers\Voyager\RoleController (change namespace)

method update
![step2a](https://user-images.githubusercontent.com/32837544/63265688-7a080000-c28e-11e9-965d-39c33a0a25f8.png)

method store
![step2b](https://user-images.githubusercontent.com/32837544/63265697-7eccb400-c28e-11e9-8353-93be631c512f.png)

**Comment by fletch3555** [comment]
@d3turnes, no need to mess with routes.  Just create a new controller, extending the default one from Voyager, then go into the BREAD editor for the one you want to change (i.e. Roles) and change the "Controller" field to the FQCN of your new controller.

As for the change, pasting screenshots of your code doesn't really help identify what the change is.  Please either upload a diff, or open a PR if you believe it should be included in the package code.

**Comment by d3turnes** [comment]
@fletch3555 thank you!

[You can see changes here](https://github.com/the-control-group/voyager/compare/1.2...d3turnes:patch-5)

**Comment by d3turnes** [comment]
@fletch3555 
when go into BREAD editor (Roles) and change the Controller (i.e App\Http\Controllers\Voyager\RoleController) dont load the new Controller, only occurs with BREAD Roles.

**Comment by emptynick** [comment]
Fixed in #4351 (merged into 1.x)
