### ISSUE TITLE
Select All checkbox does not update the input[name=ids] value

### ISSUE THREAD

**Issue by ajcastro** [thedevdojo/voyager#4330]
## Version information

 - Laravel: 5.8.31
 - Voyager: v1.2.6
 - PHP: 7.2
 - Database: MySQL
## Description

IDs are not being set on `input[name=ids]` when using the `Select All` checkbox. 
Making the ids in mass-action is only empty string.

## Steps To Reproduce
1. Add a mass-action for example `Disable`. Any mass-action will do.
```php
<?php

namespace App\Actions;

use TCG\Voyager\Actions\AbstractAction;

class Disable extends AbstractAction
{
    public function getTitle()
    {
        return 'Disable';
    }

    public function getIcon()
    {
        return 'voyager-x';
    }

    public function getPolicy()
    {
        return 'read';
    }

    public function getAttributes()
    {
        return [
            'class' => 'btn btn-md btn-grey',
        ];
    }

    public function getDefaultRoute()
    {
        // no need for route
    }

    public function massAction($ids, $comingFrom)
    {
        dd($ids);
        // Do something with the IDs
        return redirect($comingFrom);
    }
}
```

2. Inspect element on the mass-action button and find the `input[name=ids]`.

3. Check the `Select All` checkbox and the input's value will not update.

![image](https://user-images.githubusercontent.com/4918318/62833578-baa2c080-bc73-11e9-8f7d-d1d1d2ad2a95.png)

**Comment by ajcastro** [comment]
Quick Fix:
Paste this in your `custom.js`

```js
$(function () {
    $('.select_all').click(function () {
        var ids = []
        if ($(this).is(':checked')) {
            $('[name=row_id]').each(function (i, el) {
                ids.push(el.value)
            })
        }
        $('input[name=ids]').val(ids.join(','))
    })
})
```

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4370 (merged to 1.x)
