### ISSUE TITLE
Allow to have non-default admin guard

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#4334]
## Version information
 - Laravel: v5.6.39
 - Voyager: v1.2.6
 - PHP: 7.2.14my
 - Database: MySQL Server version 5.7.25 

## Description of problem
Creating a separate admin table has been requested multiple times (#2572,#2534,#2568, #3398, #2002). 
One of many concerns was the following:

> If Voyager admin's can not be separated from default user table , then one has to use something like \Auth()->guard('normal') instead of \Auth() in the whole application because the default guard is already used by Voyager.

(from #2572) or in other words

> I have 3 user types in my project; customers, business admins and the app admins. I using a multiple authentication system for the project and I would like to leave laravel's default user authentication and User model for customer authentication.

(from #2002)

In #3968 emptynick created the possibility to use a custom guard. This is a great improvement. However, even if one creates a custom admin guard, one is forced to use this as the default guard for the whole application (otherwise you  get issues like #4264 or #4333). But this forces every developer who uses `voyager` to rewrite in his application `\Auth()->guard('normal')->user()...`. 

In short, we can change the Laravel admin guard, but then we are forced to set this guard as the default one.

## Proposed solution
Lets make it work that people can set any voyager admin guard - without forcing user to use it as default guard.  This avoids conflicts and is a full fix to #2572,#2534,#2568, #3398, #2002, #4264, #4333

I would propose the following changes:

1. The guard provided in `VoyagerAuth` has to be set (if provided) in VoyagerAuthController so that voyager admin can login even with non-default voyager guard
2. The method `authorize` in  `Voyger/Http/Controllers/Controller` has to be overwritten (by 1 line) in order to make
```
// via controller
$canViewPost = $this->authorize('read', $post);
``` 
work with non-default voyager guard.

Changes 1. & 2. are very easy and I don't see any conflicts with it.

The major change would be, that `@can` could not be used in the view files anymore, because it relates to the default user guard.

So one had to change the docs https://voyager-docs.devdojo.com/core-concepts/roles-and-permissions 

from 

```
// via user object
$canViewPost = $user->can('read', $post);
$canViewPost = Auth::user()->can('read', $post);
```

to 

```
// via user object
$canViewPost = $user->can('read', $post);
$canViewPost = app('VoyagerAuth')->user()->can('read', $post);
```

And in all blades one would need to replace 

`@can(..)`

by 

`@if (app('VoyagerAuth')->user()->can(..)` 

Do you think this is acceptable? If so, I would gladly create a PR for that.

**Comment by niels-numbers** [comment]
I found a much cleaner solution that I will propose tomorrow.

**Comment by emptynick** [comment]
I think I'd prefer to have a blade directive to handle it.

**Comment by niels-numbers** [comment]
@emptynick hi, how exactly would you handle it with a blade directive?

I thought it might be best to just change the default auth dynamically in `VoyagerAdminMiddleware` and the guard in VoyagerAuthController. Then everything should work and one can still use `@can..`. I would create a PR tomorrow, since its really just 2 lines.
