### ISSUE TITLE
Bootstrap Datetime Picker is not working with Voyager 

### ISSUE THREAD

**Issue by shaileshmaurya17** [thedevdojo/voyager#4337]
Added new package from [https://packagist.org/packages/components/bootstrap-datetimepicker](url) But its not working instead voyager default date picker is showing.

I think there is some conflict between Bootstrap Datetime Picker and voyager(App.js) .

error path:- \voyager-assets?path=js%2Fapp.js:1 jQuery.Deferred exception

**Comment by emptynick** [comment]
The issue template is required when opening issues.
