### ISSUE TITLE
Showing/Hiding formatted date (browse.blade.php)

### ISSUE THREAD

**Issue by sblombliz** [thedevdojo/voyager#4339]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.1
 - Database: mysql 14.14

## Description:
I've noticed (maybe it's me that i'm using it wrong) that the date showed in the browse page is always in the timestamp format (y-m-d), i've try to put the format in the option of the bread but if i use 
`{
    "format": "%d/%m/%Y"
}`
it will show me always a date (current date) also on NULL field.

to Fix it, i edited /tcg/voyager/resources/views/bread.blade.php (line 158, 159)
Instead of:

```
@elseif($row->type == 'date' || $row->type == 'timestamp')
  {{ property_exists($row->details, 'format') ? \Carbon\Carbon::parse($data->{$row->field})->formatLocalized($row->details->format) : $data->{$row->field} }}
```

I put:

```
@elseif($row->type == 'date' || $row->type == 'timestamp')
    @if (!empty($data->{$row->field}))
        {{ property_exists($row->details, 'format') ? \Carbon\Carbon::parse($data->{$row->field})->formatLocalized($row->details->format) : $data->{$row->field} }}
    @endif
```

Sorry for any mistakes, it's the first time that i'm writing in GitHub.

**Comment by MrCrayon** [comment]
Sorry for the delay.
This was an actual bug and should have been fixed with #4443
If you still experience this problem you can open another issue.
