### ISSUE TITLE
Replacing user primary key breaks 2017_11_26_015000_create_user_roles_table

### ISSUE THREAD

**Issue by tyson-nw** [thedevdojo/voyager#4340]
## Version information
 - Laravel: v5.8.31
 - Voyager: v1.2.6 
 - PHP: 7.2
 - Database: sqlite3

## Description
If I have a renamed primary key 2017_11_26_015000_create_user_roles_table migration breaks

## Steps To Reproduce
1. Change User migration to
`
public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->uuid('uuid')->primary();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestampsTz();
        });
    }
`
2. update User model
`
	protected $primaryKey = 'uuid';
	public $incrementing = false;
`
3. run `php artisan migrate:fresh`
`
Migrating: 2017_11_26_015000_create_user_roles_table

   Doctrine\DBAL\Schema\SchemaException  : There is no column with name 'id' on table 'users'.

  at /var/www/test.tabletopstock.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php:82
    78|      * @return \Doctrine\DBAL\Schema\SchemaException
    79|      */
    80|     public static function columnDoesNotExist($columnName, $table)
    81|     {
  > 82|         return new self(
    83|             sprintf("There is no column with name '%s' on table '%s'.", $columnName, $table),
    84|             self::COLUMN_DOESNT_EXIST
    85|         );
    86|     }

  Exception trace:

  1   Doctrine\DBAL\Schema\SchemaException::columnDoesNotExist("id", "users")
      /var/www/test.tabletopstock.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php:658

  2   Doctrine\DBAL\Schema\Table::getColumn("id")
      /var/www/test.tabletopstock.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:877

  Please use the argument -v to see more details.
`

## Expected behavior
Having changed everything necessary to use a custom Id column as per Laravel's guidelines Voyager still works.

**Comment by marcelosantos89** [comment]
Hello, 
This error is ocurring because Voyager Migrations use the column ID as reference in the table users_roles as seen here in the migration: 

File: 2017_11_26_015000_create_user_roles_table.php
`$type = DB::connection()->getDoctrineColumn('users', 'id')->getType()->getName();`
 `$table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');`

You probably need to change this core migration from voyager for that to work.

**Comment by fletch3555** [comment]
@orien2k is correct.  Overriding migrations is simple.  Just create one in the default migrations directory with the exact same file name, and include the changes you need.
