### ISSUE TITLE
BREAD translation

### ISSUE THREAD

**Issue by jleei** [thedevdojo/voyager#4341]
## Version information

 - Laravel: v5.8
 - Voyager: latest
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
A clear and concise description of what the problem is.  Please also explain why this doesn't fit into the defined issue templates

## Additional context

![ddd](https://user-images.githubusercontent.com/1852808/63002442-85cb7f00-bea8-11e9-8c44-f1dc4868c66f.png)

how to translate these column names?
thanks

**Comment by emptynick** [comment]
As per the issue template, questions should be asked in our Slack group.
