### ISSUE TITLE
actual m_link_type value of any menu is not selected

### ISSUE THREAD

**Issue by nixprosoft** [thedevdojo/voyager#4349]
## Version information

 - Laravel: latest
 - Voyager: latest
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
m_link_type field of the menu edit popup is always `url` option selected

## Steps To Reproduce
1. Go to Menu constructor
2. Open any item, change type to `route`, set the route value and save.
3. Reopen item
4. See route value and m_link_type field nomore dynamic.
5. If you save now, you will loose route value.

## Expected behavior
m_link_type select box must be `route` value, if route is set.

## Screenshots
![2019-08-20_14-40-14](https://user-images.githubusercontent.com/5313478/63344208-91abbb00-c358-11e9-8e03-0c23eb3e3cc8.png)

**Comment by fletch3555** [comment]
I guess I don't follow what you're saying...

You edit a menu item and change the value to "Dynamic" and save.  You then reopen it and it doesn't show "Dynamic"..?

**Comment by nixprosoft** [comment]
Yep. The field is empty.20 авг. 2019 г. 17:22 пользователь Eric Fletcher <notifications@github.com> написал:I guess I don't follow what you're saying...
You edit a menu item and change the value to "Dynamic" and save.  You then reopen it and it doesn't show "Dynamic"..?

**Comment by emptynick** [comment]
I think this is related to https://github.com/the-control-group/voyager/issues/4365 and was fixed in https://github.com/the-control-group/voyager/pull/4369

Please let us know if it wasn't fixed in 1.3 (after it is released of course)
