### ISSUE TITLE
I followed the INSTALLATION ,after I installed ,I got NotFoundHttpException

### ISSUE THREAD

**Issue by mcwz** [thedevdojo/voyager#435]
- Laravel Version: 5.3
- Voyager Version: 0.10.5
- PHP Version:5.6.15
- Database Driver & Version: mysql 5.7.9

**Comment by Jaquedeveloper** [comment]
Did you installed laravel correctly?

**Comment by mcwz** [comment]
@Jaquedeveloper I'm sure I have installed laravel correctly . I can see laravel welcome page . I also created a test controller , it worked well too.

**Comment by handiwijoyo** [comment]
Try to run php artisan vendor:publish

**Comment by fletch3555** [comment]
Please verify that your `routes/web.php` file contains an line for `Voyager::routes();`

**Comment by mcwz** [comment]
@Jaquedeveloper @handiwijoyo @fletch3555 I found the problem , because I use homestead for my development environment ,and after I create a new sites , I forget to run vagrant privision . Thank you !
