### ISSUE TITLE
Show Files in relationship

### ISSUE THREAD

**Issue by loverdeveloper** [thedevdojo/voyager#4350]
Hi i need a custom relationship,
i have a users table that every user has a file in files table 
i store file name in name column
i need show download button in users BREAD.
How i can do this?
`NO SLACK PLEASE`

**Comment by fletch3555** [comment]
Slack is preferred, but I'm assuming there's a reason for your request not to use slack... Feel free to post in DevDojo forums instead: https://devdojo.com/forums/category/voyager.  You could also ask in the larachat slack, laravel discord, or laracasts forums if any of those work better for you.

We're really trying to keep github focused on code issues, not help requests.
