### ISSUE TITLE
How to make BREAD assessor in relationship fields?

### ISSUE THREAD

**Issue by dfikeda** [thedevdojo/voyager#4354]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.2.11

## Description:
How to make BREAD assessor in relationship fields?

https://voyager-docs.devdojo.com/customization/bread-accessors
The manual does not include or does not work the operation of BREAD Assessor in the relationship fields, for example gender_id in the table user takes by relationship the gender on table genres, but I can not implement BREAD assessor for it.

**Comment by HappyLDE** [comment]
Same here. This was a deal breaker for me: TWO YEARS AGO. Today I installed Laravel Voyager to see, and, it's not done yet? Let me get this straight. Every other developer can make a simple crud admin in 1h top. We need crud for relationships !

**Comment by AndrewHnidets** [comment]
@dfikeda Are you looking for [this](https://voyager-docs.devdojo.com/customization/custom-realtionship-attributes)?

**Comment by emptynick** [comment]
That sounds exactly like what they are looking for, and it exists for longer than that.
Also @HappyLDE this is an open source project, if you find a missing feature: implement it and submit it as a PR for everyone to profit.
