### ISSUE TITLE
 Invalid or unexpected token

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4358]
## Version information

 - Laravel: v5.8.23
 - Voyager: v1.2
 - PHP:7.1.3
 - Database: [MySQL] [5.7.27]

## Description

As i  am logging into my admin account. Voyager loader keep processing. 
and getting error in console as : -

"Uncaught SyntaxError: Invalid or unexpected token" -> voyager-assets
"Uncaught ReferenceError: Vue is not defined" -> admin

## Screenshots

https://snipboard.io/aQb4C7.jpg

**Comment by fletch3555** [comment]
And what is the content of that file? Can you paste that path into the browser and see? If not, take a look at the network tab of your dev tools and find that request, then look at the response.
