### ISSUE TITLE
Voyager Broken menu builder

### ISSUE THREAD

**Issue by alessiow** [thedevdojo/voyager#4359]
- Laravel Installer 2.1.0
 - Voyager: v0.11
- PHP 7.2.19 
 - mysql:  8.0.16

Hello guys.
Suddenly my Menu Builder is empty and i can not change the navbar to the left. Can you help me please? Thank you! :)

[ https://imgur.com/Xt0hsYF](url)

**Comment by emptynick** [comment]
Please fill out the rest of the issue template.
Those information are crucial for us to help you.
This can be re-opened once you filled out the rest.
