### ISSUE TITLE
Voyager Menu Builder Broken

### ISSUE THREAD

**Issue by alessiow** [thedevdojo/voyager#4360]
Laravel Installer 2.1.0
Voyager: v0.11
PHP 7.2.19
mysql: 8.0.16
Hello guys.
Suddenly my Menu Builder is empty and i can not change the navbar to the left. Can you help me please? Thank you! :)

Steps To Reproduce

1. Go to Menu Builder
2. Nothing showin up

Expected behavior
As always, i except to see an editor for my navbar site.

Screenshots
https://imgur.com/Xt0hsYF

**Comment by fletch3555** [comment]
As with all technology, it will only do what you tell it to do, though you may not realize you were telling it to do that.

In short, we don't have enough information to help you.  If the page is showing up correctly (but simply missing data), then it's quite likely the data doesn't actually exist (check the menus and menu_items tables in your database).  It's also possible that your app simply doesn't think it exists (have you overridden the Menu or MenuItem models?)  Of course, I'm just speculating.  What did you change before this happened?

Also, are you actually using v0.11? If so, specifically what version? 0.11.14 is the latest in that series and is over 2 years old at this point (and officially unsupported).

**Comment by alessiow** [comment]
Hello :) I had a backup of the platform. Now the Menu builder works ! Maybe
i deleted the data from database , but now it works just  fine!

Il giorno gio 5 set 2019 alle ore 01:51 Eric Fletcher <
notifications@github.com> ha scritto:
