### ISSUE TITLE
i want to make my welcome view multilingual 

### ISSUE THREAD

**Issue by hussainabuhajjaj** [thedevdojo/voyager#4362]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2.*
 - PHP: 7.2
 - Database: [mysql] [version] (e.g. MySQL 8.0)

## Description:
Hello my friend , i tried to make my welcome view multilingual put nothing happens and when i use the the loaders in the controller  it gave me this error. 

## Additional context
Method Illuminate\Database\Eloquent\Collection::getTranslatedAttribute does not exist.
![error](https://user-images.githubusercontent.com/33667887/63913420-21302880-ca41-11e9-8bba-948a0f6ccd86.PNG)

**Comment by fletch3555** [comment]
The error message tells you exactly what the problem is.  `getTranslatedAttribute()` is a method on the model, not on a collection of models.  `->all()` returns a collection
