### ISSUE TITLE
Correct display of fields in the MenuItem editor does not work

### ISSUE THREAD

**Issue by godless66613** [thedevdojo/voyager#4365]
- Laravel: v 5.8.33
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MySQL 8.0

When I go to the menu item editor it displays me this:

![изображение](https://user-images.githubusercontent.com/44669466/64008771-6d519a80-cb1f-11e9-8ccd-ece8bdae952f.png)

And the database stores completely different information.
According to the code inspector, we see that the information is correct, but it does not display correctly.
The icon field replaces and substitutes the value from the title field

It all happened when I enabled multilingual and now if I update, the menu itself will be thrown in the menu on the left in the admin panel

When I disabled multilingual the form looks like this:
![изображение](https://user-images.githubusercontent.com/44669466/64016579-07b9da00-cb30-11e9-856a-37b4aa48db4f.png)
Everything works as it should

**Comment by MrCrayon** [comment]
I can confirm the behavior, I tracked it down to #4157 PR.

@Xmk @emptynick I think we will have to find another solution to fix #4072 and #4152.

**Comment by emptynick** [comment]
Fixed in https://github.com/the-control-group/voyager/pull/4369 (merged into 1.x)
