### ISSUE TITLE
How to validate 'unique' using JSON in optional field

### ISSUE THREAD

**Issue by raoasifraza11** [thedevdojo/voyager#437]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7.0.9
- Database Driver & Version: 7.0.9

### Description:
How to validate unique name such as validate require or maximum.
`{
    "validation": {
        "rule": "required| max:100"
    }
}`

### Steps To Reproduce:
When I use as per Laravel Validation rules is used but got error 
`{
    "validation": {
        "rule": "required|unique:country|max:100"
    }
}`

Error is this:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'country' doesn't exist (SQL: select count(*) as aggregate from `country` where `country` = Pakistan)`

**Comment by handiwijoyo** [comment]
Please make sure you have table named country

**Comment by raoasifraza11** [comment]
@handiwijoyo I've a table but it's give an error.

**Comment by marktopper** [comment]
Voyager simply uses the Laravel validation system.

So please refer to [the documentation](https://laravel.com/docs/5.3/validation#rule-unique).

Also your error is `Table 'country' doesn't exist`, so please ensure that the table name is correct and in the same database as the rest of your Voyager application.

I bet that the table is called `countries`, and not `country`.
