### ISSUE TITLE
Model Class does not exist. Please create Model before creating relationship.

### ISSUE THREAD

**Issue by hussainabuhajjaj** [thedevdojo/voyager#4371]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2.*
 - PHP: 7.3
 - Database: [mysql] [version] (e.g. MySQL 8.0)

## Description

i am trying to make a simple relationship between two tables from voyager the relation is has many colors and every time i tried to make it it shows this message (Model Class does not exist. Please create Model before creating relationship.) already i have the models

**Comment by asannikov** [comment]
still the same problem. Solution is to fill the field "Fully Qualified Model Name (ex. App\Category)". It has to be required, but user still able to keep it empty and this is cause of the error.
