### ISSUE TITLE
Create relation between menu_item and permissons

### ISSUE THREAD

**Issue by niels-numbers** [thedevdojo/voyager#4372]
## Version information
 - Laravel: v5.6.39
 - Voyager: v1.2.6
 - PHP: 7.2.14my
 - Database: MySQL Server version 5.7.25 

## Description of problem
If one has multiple custom pages A,B,C,D,... and one wants that every user with permission X has no access do A,B,C,D,... then there is no quick way to hide these menu items.

If one has 10 custom pages that belong in a certain responsibility area, then its cumbersome to create 10 extra permissions `browse_slug_A`, `browse_slug_B`, ... permissions and allocate them to the specific roles (as explained in https://github.com/the-control-group/voyager/pull/4368)

## Proposed solution
Create a new column to the `menu_items` table called `permission_id`. This creates a hasMany relation: A permission model hasMany menu_item models. 

Then one would add in the MenuItemPolicy, that a user would have access to a menu item, if he has a permission that is related to the menu item.

When creating a new menu item, a parent permission could be selected:
![image](https://user-images.githubusercontent.com/1765602/64109421-c28be700-cd7f-11e9-8588-896dbb98bec8.png)

## Additional context
Let me know what you think about it. If you like it, I would create a PR for this.

**Comment by fletch3555** [comment]
At this point, I'm not sure we're looking to add any more features to this version of voyager.  Instead, we're switching our efforts to building out 2.0

**Comment by niels-numbers** [comment]
Alright
