### ISSUE TITLE
Why is it slow

### ISSUE THREAD

**Issue by chang1314** [thedevdojo/voyager#4374]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2
 - PHP: 7.2

## Description

I followed the process to complete the installation and ran successfully,But I found that the page loaded slowly without any data,My operating system is Windows +laravel/homestead,Is there any way to speed up the program

**Comment by AmirHome** [comment]
Hi i need to Add server side pagination to datatables

[https://github.com/the-control-group/voyager/issues/81](https://github.com/the-control-group/voyager/issues/81)

**Comment by MrCrayon** [comment]
@AmirHome he said he tried without data. 

@chang1314 slow is subjective, for some 2 seconds can be slow for some other 0.5 is slow. 
Speed can also depend on a lot of things. 

I suggest you to use Chrome to audit which part of the process is taking time. 

In general voyager is not designed to be used as front end so it's not particularly fast.

**Comment by DevBodin** [comment]
This probably isn't a Voyager-related issue. Laravel Homestead is typically much slower on Windows, particularly when dealing with larger applications. If you haven't yet, you might want to try enabling NFS in your Homestead configuration and see if that helps.
