### ISSUE TITLE
Role -> Add New returns an error page

### ISSUE THREAD

**Issue by daimalkogaz** [thedevdojo/voyager#4375]
I have just installed voyager and everything seems to be working perfectly except the Add New Role function which is just returning an error.
![voyager_err](https://user-images.githubusercontent.com/52038506/64232677-11aa5700-cefb-11e9-9408-01ebcd2cb6b0.jpg)

**Comment by youssef3wi** [comment]
even add Bread.. its seems that voyager not yet been updated with laravel 6

**Comment by fletch3555** [comment]
Please note that the issue template is not optional.  Version numbers help us properly identify and reproduce your issue.
