### ISSUE TITLE
Not creating thumbs in subfolders

### ISSUE THREAD

**Issue by Aldo-f** [thedevdojo/voyager#4378]
## Version information
 - Laravel: v5.8.32
 - Voyager: v1.2.6
 - PHP: 7.3.8
 - Database: Ver 15.1 Distrib 10.2.26-MariaDB, for Linux (x86_64) using readline 5.1

## Description
When using [media picker](https://voyager-docs.devdojo.com/bread/introduction-1/media-picker) to upload files it does not create thumbnails in a subfolder.

Also when creating an image with thumbnails, they disappear when moving the image to a subfolder. 

## Steps To Reproduce
https://i.imgur.com/4efbL2X.jpg 

## Expected behavior
Create thumbs 

## Additional context
```
// images options for creating thumbs
{
    "max": 30,
    "min": 0,
    "expanded": false,
    "show_folders": true,
    "show_toolbar": true,
    "allow_upload": true,
    "allow_move": true,
    "allow_delete": true,
    "allow_create_folder": true,
    "allow_rename": true,
    "allow_crop": true,
    "allowed": [],
    "hide_thumbnails": false,
    "quality": "70%",
    "thumbnails": [
        {
            "type": "crop",
            "name": "cropped-large",
            "width": 900,
            "height": 750
        },
        {
            "type": "crop",
            "name": "cropped-medium",
            "width": 600,
            "height": 500
        },
        {
            "type": "crop",
            "name": "cropped",
            "width": 300,
            "height": 250
        },
        {
            "type": "resize",
            "name": "medium",
            "width": 900,
            "upsize": true
        },
        {
            "type": "resize",
            "name": "small",
            "width": 450,
            "upsize": true
        }
    ]
}
```
-----
Please add this in the bug report template:
```
// check versions:
php artisan --version
composer show tcg/voyager
php -v
mysql --version
```

**Comment by stephane-monnot** [comment]
Same here : 
 - Laravel Framework 6.3.0
 - Voyager: v1.3.0
 - PHP 7.2.19-0ubuntu0.19.04.2 (cli) (built: Aug 13 2019 11:45:23) ( NTS )
 - mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Upload_path should be `/dolls/752/`
![image](https://user-images.githubusercontent.com/6066368/67479508-328c5e80-f699-11e9-87dd-90f7b6f03677.png)
