### ISSUE TITLE
Custom MenuItem model translation fields not working

### ISSUE THREAD

**Issue by daav7713** [thedevdojo/voyager#4379]
## Version information

 - Laravel: v5.6.#
 - Voyager: v1.1.#
 - PHP: 7.1
 - Database: MySQL 5.7

## Description

I want to translate the route and url fields of the MenuItem model, create my own model and extend it from the MenuItem model, but by adding the title, route and url fields to the $ translatable field, it only allows you to add the translation of the title field, the others keep them with the default language value without translation

## Steps To Reproduce
https://imgur.com/a/SpXw4dZ
## Expected behavior
Be able to translate the route and url field

**Comment by Braiani** [comment]
Please, fill the issue template correctly. We need the complete information to provide a properly support.

**Comment by daav7713** [comment]
Its ok now?

**Comment by fletch3555** [comment]
@daav7713 are you certain that Voyager is using your custom model? I don't believe we've ever tested translating extra fields on the menu items, so I can't guarantee that would ever work

**Comment by daav7713** [comment]
Hi, yes im sure, i already tested.

**Comment by MrCrayon** [comment]
@daav7713 menu items are not normal bread items, you'll need to change blade template for those fields to be translatable. 
Check menus/builder.blade.php

Also translating urls means you'll need to manage new routes, depending on what's your purpose you might have more luck trying to make datatype slug translatable or something like that.
Keep in mind it's not going to be easy.

**Comment by daav7713** [comment]
Thank you @MrCrayon  I managed to solve the problem with the advice you gave me.
