### ISSUE TITLE
How to hidden database tables from the admin panel?

### ISSUE THREAD

**Issue by raoasifraza11** [thedevdojo/voyager#438]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7.0.9
- Database Driver & Version: 7.0.9

### Description:
I have try this for hidden the database table from admin panel but it's not work any one help me out what did i wrong.

### Steps To Reproduce:
I use this as per documentation
`
/*
    |--------------------------------------------------------------------------
    | Database Config
    |--------------------------------------------------------------------------
    |
    | Here you can specify voyager database settings
    |
    */

    'database' => [
        'tables' => [
            'hidden' => ['users', 'roles'], // database tables that are hidden from the admin panel
        ],
    ],
`

**Comment by ghost** [comment]
It hides it from the Database Tools, so if you go to `http://url.com/admin/database` your table won't be able to be edited there, however it will still show in the sidebar if you dont remove it from the menu builder

**Comment by raoasifraza11** [comment]
Okay got it, Thanks @brandy 👍
