### ISSUE TITLE
The DELETE method is not supported for this route. Supported methods: GET, HEAD, POST.

### ISSUE THREAD

**Issue by elieobeid7** [thedevdojo/voyager#4383]
latest version of laravel and voyager, trying to delete the dummy data

![Screenshot from 2019-09-06 02-36-11](https://user-images.githubusercontent.com/660142/64390864-2dbf0d00-d04f-11e9-9a48-d7defba3f35c.png)

**Comment by fletch3555** [comment]
The issue template is not optional.  Also, Voyager does NOT yet support Laravel 6.  It's a mystery to us why composer is allowing it.
