### ISSUE TITLE
Dashboard crashes after removing Posts

### ISSUE THREAD

**Issue by giokaxo** [thedevdojo/voyager#44]
I've removed Posts table from database manager and dashboard crashed. 

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.posts' doesn't exist (SQL: select count(*) as aggregate from `posts`)

There is no views when i publish vendor files. and no option to customize dashboard view.
Would be good if you make possible to publish views

**Comment by fletch3555** [comment]
I noticed this as well.  #23 covers the request to publish views (as well as controllers and models)

**Comment by marktopper** [comment]
This have been fixed and will be out in the next release tag.

**Comment by parth-vora-7** [comment]
I also get this error. Has it been released yet or not?

**Comment by fletch3555** [comment]
@xparthx, this issue was closed 6 months ago.  Please open your own issue or ask in our Slack group.
