### ISSUE TITLE
Data from wrong table in bread

### ISSUE THREAD

**Issue by AlexDukachev** [thedevdojo/voyager#440]
- Laravel Version: 5.3
- Voyager Version: 0.10.x
- PHP Version: 5.6
- Database Driver & Version: MySQL

I have 3 table: videos, video_cat and video_categories. How can I add multiple dropdown to bread for database “videos”? With save selected categories in table “video_cat”.

Tables description on docs: https://docs.google.com/document/d/1gqI6VUuKLulM5mahbk0u9LFNuiE8fMBr-H6-nty_TdM/edit?usp=sharing

**Comment by marktopper** [comment]
Please read the documentation on BREAD relationships.

https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-relationships

**Comment by marktopper** [comment]
Reopened after chatting with @AlexDukachev on Skype.

It seems like there is an issue with has-many relations support.
Will check it out.

**Comment by AlexDukachev** [comment]
Are there any ideas? It needs this implementation.

**Comment by fletch3555** [comment]
@marktopper or @AlexDukachev, is this still a problem in v0.11.*? If not, please close this issue.
