### ISSUE TITLE
Voyager::setting() error when calling in a config file

### ISSUE THREAD

**Issue by SayDevz** [thedevdojo/voyager#4400]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1
 - Database: MySQL5.7

## Description

Getting and error Using $this when not in object context when calling Voyager::setting('site.elastic_host','127.0.0.1') in elastic search config file.

## Screenshots
<img width="1226" alt="Screen Shot 2019-09-10 at 3 08 51 PM" src="https://user-images.githubusercontent.com/18522102/64591676-f64cb980-d3dc-11e9-9501-edcc498a66d4.png">

**Comment by emptynick** [comment]
Configs are loaded in a very early state when loading.
Imagine setting your database-host through Voyager settings, which requires a database-connection - this can't work.
