### ISSUE TITLE
When admin edits profile, 'role_id' value get replaced by 'null' in users table.

### ISSUE THREAD

**Issue by dakshimC** [thedevdojo/voyager#4401]
## Version information

 - Laravel: v6.0.1
 - Voyager: v1.2.7
 - PHP: 7.3
 - Database: MariaDB 10.3.16 (e.g. MySQL 8.0)

## Description

I was not able to access the admin panel, after updating my profile from 'Edit my profile' button. On further debugging, It seems the 'role_id' under 'users' table get blank/ null after updating user profile.

## Steps To Reproduce
1. Go to 'Profile'
2. Click on 'Edit My Profile'
3. Scroll down and click on 'Save' button
4. It will redirect you to home page and admin panel is inaccessible

## Expected behavior
After saving the profile, it should redirect backs or go to admin panel dashboard, and role_id should remain as previous one.

## Screenshots
http://prntscr.com/p44zcg

**Comment by emptynick** [comment]
This is what this part of the code prevents:
https://github.com/the-control-group/voyager/blob/015c517a1e52ee93a6f83a24a601f50cb0b92cf1/src/Http/Controllers/VoyagerUserController.php#L18-L24
Did you change the controller for the user-bread?

**Comment by dakshimC** [comment]
@emptynick, I'm not using custom controller for the user bread,

I have tried recreating the bug in fresh setup, but unable to do so. so I think there might be some issue with my project itself.

Some facts about the project which have issue, 

- I have migrated it from Laravel 5.6 to Laravel 6.0.1
- I have migrated it from Voyager 1.1.10 to 1.1.12 than to 1.2.7
- I then created a custom controllers namespace to override a controller for another bread using [these steps](https://voyager.readme.io/docs/using-custom-http-controllers).

**Comment by MrCrayon** [comment]
@dakshim you probably didn't follow upgrade instructions for voyager.
Check the release list and make sure you apply all suggested instructions for all releases since 1.1.10.

**Comment by emptynick** [comment]
> I'm not using custom controller for the user bread,

and

> I then created a custom controllers namespace to override a controller 

contradict a bit.

**Comment by MrCrayon** [comment]
@emptynick maybe he used a custom controller but not for users.

I'm pretty sure he started with an old voyager version where users didn't have a dedicated controller and when he updated he didn't change database to set VoyagerUserController to manage users BREAD.

**Comment by dakshimC** [comment]
@MrCrayon & @emptynick , Thanks for active help.
I have missed the step of setting controller in User Bread as mention [here](https://voyager-docs.devdojo.com/getting-started/upgrading).

After following the required step, the app is working as expected.
