### ISSUE TITLE
translation's table's index name is too long so it wont install

### ISSUE THREAD

**Issue by hosghf** [thedevdojo/voyager#4402]
hi
during the installation i have this error:

Illuminate\Database\QueryException : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table transla tions add unique translations_table_name_column_name_foreign_key_locale_unique(table_name, column_name, foreign_key, locale))

**Comment by emptynick** [comment]
Please fill out the issue template and [search ](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+max+key+length+is+1000+bytes+)before opening issues.
