### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by rfeugenio** [thedevdojo/voyager#4405]
## Description

The foreign keys are blank upon submission of the form.

Illuminate\Database\QueryException
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'client_id' cannot be null (SQL: insert into `matters` (`name`, `client_id`, `lawyer_id`, `contact_person`, `status`, `updated_at`, `created_at`) values (Cadman Ochoa, ?, ?, Pariatur Cupidatat, Iure nostrum ullamco, 2019-09-12 10:34:04, 2019-09-12 10:34:04))

## Screenshots
![image](https://user-images.githubusercontent.com/6788944/64777301-79604200-d58c-11e9-816f-b2b8f9763bd4.png)

**Comment by Yeeooow** [comment]
on the error page you can see the data is in the request, but not sent/added to the database

**Comment by Yeeooow** [comment]
@rfeugenio I have been experiencing the same issue, seemingly random, but I think Ive got it.  I noticed this happened after re-ordering the  BREAD items (using the drag & drop).  The realtionship must be/sit BELOW the reference column.  E.g. we have a `user` and `post` table, the `post` table has a 
`user_id` that relates back to the `user` table.  The relationship you make in the BREAD (post table)  should visualy sit below the `user_id` column.

Hope that helps

**Comment by emptynick** [comment]
First, Laravel 6 is not yet supported. Please see our readme.
Also, the issue template is required when opening a new issue.
This can be reopened once the required information are provided.

**Comment by filipe-union** [comment]
@Yeeooow thanks for the accurate hint. I was experiencing exactly the same error and reordering the fields (placing the reference column above the relationship) as you mentioned fixed it.
