### ISSUE TITLE
Validation Form Voyager 1.2

### ISSUE THREAD

**Issue by jonipohan** [thedevdojo/voyager#4407]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1.3
 - Database: MySQL 5.7

## Description
Hi All,

So the case is after I submit the blank form with intention to test the validation, I got return error message in json instead of show the error message below the text box. Am I missing something in order to show the error message in each respective text box?

## Expected behavior
THere should be error message below each text box.

## Screenshots
![image](https://user-images.githubusercontent.com/15310725/64807768-1c7e7f00-d5c0-11e9-8032-43d1b1e70c9e.png)
So in this steps, I will submit the blank form.
![image](https://user-images.githubusercontent.com/15310725/64807839-43d54c00-d5c0-11e9-8dd5-ba63a54266a4.png)
I got this as return.
![image](https://user-images.githubusercontent.com/15310725/64807880-594a7600-d5c0-11e9-9af0-ece7474bef20.png)
this is my code. RequestValidator only return array of validations needed.

Kindly need your help with this

**Comment by MrCrayon** [comment]
~~Duplicate of #4366 and #3494.~~
(I don't know why I assumed  you had this error while in settings.)

Looks like you are using a custom controller.
Some time ago support for validation through ajax call was removed #3890 so, unless you want to restore it, you have to check how VoyagerBaseController manage it's validation response and copy it.

**Comment by MrCrayon** [comment]
Closed for inactivity. 

If you are still experiencing this problem you can open another issue.
