### ISSUE TITLE
ErrorException in UrlGenerator.php

### ISSUE THREAD

**Issue by raoasifraza11** [thedevdojo/voyager#441]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7.0.9
- Database Driver & Version: 7.0.9

### Description:
I got this error after login how can i fix this?
`
ErrorException in UrlGenerator.php line 314:
Route [voyager.posts.index] not defined. (View: /Users/raoasifraza/Documents/webprojects/uni-admissions/vendor/tcg/voyager/resources/views/index.blade.php)
`

### Steps To Reproduce:
I have a view index.blade.php in resources directory. Why this error coming?

**Comment by marktopper** [comment]
Please share the response of the command `php artisan route:list` with us

**Comment by raoasifraza11** [comment]
![screen shot 2016-12-25 at 5 02 58 pm](https://cloud.githubusercontent.com/assets/18229291/21471043/38977b1a-cac4-11e6-9cee-a493a013181a.png)
@marktopper here is the `route:list` screen shot.
**2/2** Exception Error!
![screen shot 2016-12-25 at 5 10 19 pm](https://cloud.githubusercontent.com/assets/18229291/21471061/1da9a57a-cac5-11e6-8db0-efb9a9ac0781.png)
**1/2**
![screen shot 2016-12-25 at 5 10 34 pm](https://cloud.githubusercontent.com/assets/18229291/21471062/1fbceeda-cac5-11e6-80b3-df328efee942.png)

**Comment by fletch3555** [comment]
@raoasifraza11,

The `voyager.posts.index` route does not exist.  Did you delete the Posts database/table/bread?

Also, what page are you seeing this on? Just the dashboard page (landing page after login)?

**Comment by raoasifraza11** [comment]
I'm seeing all other pages except dashboard page.
