### ISSUE TITLE
Posts users pages not showing 

### ISSUE THREAD

**Issue by ikramooe** [thedevdojo/voyager#4410]
- Laravel: v6.0.1
 
## Description:
i just installed voyager  and i'm getting this dashboard 
![Capture](https://user-images.githubusercontent.com/31781110/64913936-98580300-d749-11e9-93ec-a0acd0149376.PNG)
the posts , users pages are not showing 
could anyone help

**Comment by stefanriest** [comment]
I guess Laravel 6.0.1 is not supported yet

**Comment by fletch3555** [comment]
Voyager does not currently support laravel 6.
