### ISSUE TITLE
View::share for Custom Controller

### ISSUE THREAD

**Issue by stefanriest** [thedevdojo/voyager#4411]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.7
 - PHP: 7.3
 - Database: MYSQL 5.7

## Description:
The main problem is, i dont want to copy paste allways the function from the VoyagerBaseController.php

Its just - ugly. And if it change i need to Bugfix it on every file.

```
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\VoyagerBaseController;

class ClientController extends VoyagerBaseController
{
 
    /**
     * Add Custom Data to Client Controller Bread
     */
    public function show(Request $request, $id) {


        return Voyager::view(View::share('userdata', \App\User::all()));

    }

```

The Controller should only give some custom data to the same view.
Additional Data.

Is there any solution for?

**Comment by stefanriest** [comment]
Update, nobody got an idea?

**Comment by emptynick** [comment]
The issue template asks you to ask question in our Slack group.
We try to reserve the issue section to issues only.
