### ISSUE TITLE
something wrong with the dashboard

### ISSUE THREAD

**Issue by ikramooe** [thedevdojo/voyager#4418]
## Version information

 - Laravel: v5.7
 - Voyager: v1.2.7

so i just installed laravel 5.7 and this is what i get in the dashboard  
![Capture](https://user-images.githubusercontent.com/31781110/64976931-b8ef9c80-d8b2-11e9-9599-95064ad770f1.PNG)

when i think it should look like this 
![voyager](https://user-images.githubusercontent.com/31781110/64977048-eb999500-d8b2-11e9-8da3-2d4a9a72a76e.png)

can anyone help !!!!!

**Comment by MrCrayon** [comment]
You'll have that only if you install --with-dummy.
Anyway to have that you need  to change widget section in your config/voyager.php, you can check https://github.com/the-control-group/voyager/blob/015c517a1e52ee93a6f83a24a601f50cb0b92cf1/publishable/config/voyager_dummy.php#L147
