### ISSUE TITLE
Use Multiple images like WordPress , Dropzone.js

### ISSUE THREAD

**Issue by mohdeleiwa** [thedevdojo/voyager#4419]
Can you assist me for custom post form on Voyager , i want to upload images use multiple file or media picker  on voyager to select more than one ,and add the links of files on post, like WordPress, or october cms , or used dropzone.js
every post has field for main image  and field for multi image store path of images or files on every record,
or if use default multiple file can i show image not only file name?

**Comment by emptynick** [comment]
As the issue-template suggests, please ask questions in our Slack-group.
All that is supported by Voyager, you just have to use it.

**Comment by mohdeleiwa** [comment]
Yes I did , I asked questions in Slack-group.
Thank you
