### ISSUE TITLE
Undefined variable: actions

### ISSUE THREAD

**Issue by nony22** [thedevdojo/voyager#4420]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7.3.3 (cli)
 - Database: mysql  Ver 14.14 Distrib 5.5.62, for debian-linux-gnu (x86_64) using readline 6.3

## Steps To Reproduce
1. Go to 'dashbord'
2. Click on 'users'
3. See error Undefined variable: actions (View: /opt/lampp/htdocs/kusa.es/vendor/tcg/voyager/resources/views/bread/browse.blade.php)

## Expected behavior
I am trying to access users from dashboard and I receive this error. On my local i have same version of voyager and is working but on my server (Ubuntu 14) I receive this eror, Database is the same on local and server.

## Screenshots
![screen](https://user-images.githubusercontent.com/55444824/65043529-56061000-d95b-11e9-91d4-09a83aca6fb8.png)

**Comment by MrCrayon** [comment]
My bet is your server is not fully updated, actions is defined in VoyagerBaseController so there is no way you can have that error unless file is outdated or you are using a custom controller.
Since you say your local version is working I'd opt for the first one.

**Comment by V-Orbit** [comment]
i have the same issue, and i'm sure that i'm using the newest version of VoyagerBaseController, as i've freshly installed voyager on a newly created server

here's my UserController declaration

`class UserController extends \TCG\Voyager\Http\Controllers\VoyagerBaseController`

**Comment by MrCrayon** [comment]
You should extend `VoyagerUserController` for your `UserController`, otherwise you'll need to implement the security measures present in that controller yourself.

Anyway you should check the content of your `vendor\tcg\voyager\src\Http\Controllers\VoyagerBaseController.php` 
https://github.com/the-control-group/voyager/blob/ef38774d927103975583f86d2d1a41ab2289a34d/src/Http/Controllers/VoyagerBaseController.php#L126
https://github.com/the-control-group/voyager/blob/ef38774d927103975583f86d2d1a41ab2289a34d/src/Http/Controllers/VoyagerBaseController.php#L169

**Comment by V-Orbit** [comment]
> 
> 
> You should extend `VoyagerUserController` for your `UserController`, otherwise you'll need to implement the security measures present in that controller yourself.
> 
> Anyway you should check the content of your `vendor\tcg\voyager\src\Http\Controllers\VoyagerBaseController.php`
> 
> https://github.com/the-control-group/voyager/blob/ef38774d927103975583f86d2d1a41ab2289a34d/src/Http/Controllers/VoyagerBaseController.php#L126
> 
> https://github.com/the-control-group/voyager/blob/ef38774d927103975583f86d2d1a41ab2289a34d/src/Http/Controllers/VoyagerBaseController.php#L169

both lines are present in the file... and the weird matter is this error outputs only for a couple index views, as many others works. dunno what i'm doing wrong...

**Comment by MrCrayon** [comment]
Try `@php dd($actions) @endphp` at the start of your template, if that gives error check which controller is passing data to the view.

**Comment by V-Orbit** [comment]
solved, it was a bad controller customization 
tnx for help! @MrCrayon :-)
