### ISSUE TITLE
"Allow Tagging" Not Working Showing voyager-asset error Cannot read property 'id' of undefined 

### ISSUE THREAD

**Issue by f24aalam** [thedevdojo/voyager#4421]
## Version information

 - Laravel: v^6.0
 - Voyager: v^1.2
 - PHP: 7.3

## Description
After Creating belongsToMany Relationship with AllowTagging Feature, In create route tags not showing after creating it, after reloading the dropdown showing the tags, 
in browsers console it showing Cannot read property 'id' of undefined

## Screenshots
![image](https://user-images.githubusercontent.com/20462189/65052096-a6936280-d987-11e9-84ab-5fb475c2ffb0.png)

**Comment by fletch3555** [comment]
That's because Voyager doesn't support 6.0 yet
