### ISSUE TITLE
Can't browse BREAD

### ISSUE THREAD

**Issue by stephenmorton** [thedevdojo/voyager#4422]
PHP 7.3.8
Laravel V6
MySQL V 8

When using voyager to create a database, it creates it fine. Then I can create the bread for it fine. When I then go to browse bread, it says database does not exist, even though I made the model manually, confirmed table is infact in the database and did migrations. Can also see the model in app/modelname.php
Using homestead, not sure if it is another issue with that.

Error I get
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.departments' doesn't exist (SQL: select * from `departments` order by `created_at` desc)

Stack Trace
vendor/laravel/framework/src/Illuminate/Database/Connection.php
error at line 655
            throw new QueryException(

**Comment by stephenmorton** [comment]
I also tried by selecting the option for voyager to create the model it's self when creating db table in voyager. Even though says success (again, can see model in file system and table in db), voyager still gives the same error when I try to browse bread). I wonder if this is another homestead issue, file system incompatible with voyager or something)

**Comment by stephenmorton** [comment]
Issue, looks like a homestead issue again, so I have done a fresh install of laravel+mysql etc not using homestead, and now I get another issue after creating database, adding bread to it and then trying to browse the bread for this table.
PHP 7.3.8
Laravel V6
MySQL V 8
Now, I get this error
Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voyager.testtables' doesn't exist (SQL: select * from `testtables` order by `created_at` desc)
If this now a Laravel V6 issue, is voyager not compatible with laravel v6
I can see the table has been created in the databse and the model file is in the filesystem.

**Comment by emptynick** [comment]
Laravel just requires you to follow some simple [conventions](https://laravel.com/docs/eloquent#eloquent-model-conventions).
That's not related to Voyager.
Also, we do not yet support Laravel 6 (see our readme)

**Comment by stephenmorton** [comment]
Thanks emptynick, Ok, tried again keeping to conventions, but same issue. Ok, must just be a Laravel 6 issue. I'll track the project and re try when it is supported. Thanks.
