### ISSUE TITLE
Image not showed when deploy to Heroku

### ISSUE THREAD

**Issue by hulauwa** [thedevdojo/voyager#4425]
Hello,

I have problems with storages. When I run local, the images and storage data is displayed, seems to be oke. 
![image](https://user-images.githubusercontent.com/38100098/65311414-7d0e4d00-dbba-11e9-8c97-a90da2adec64.png)

However when I deployed it to Heroku. The image can't be found. 
![image](https://user-images.githubusercontent.com/38100098/65311501-a62edd80-dbba-11e9-8ce5-c8c74aacf7ee.png)

As you see the image link change from
http://localhost:8000/admin/voyager-assets?path=js%2Fapp.js
to 
http://cattien.herokuapp.com/admin/voyager-assets?path=js%2Fapp.js

But It couldn't found :((( I have tried a lot of way but It does work. 
As what I know It could be caused by the file system config
![image](https://user-images.githubusercontent.com/38100098/65311633-f0b05a00-dbba-11e9-9d3e-dc8de44c5e34.png)

PLEASE HELP ME!!! :((( THANK YOU ALL

**Comment by emptynick** [comment]
Please use the issue template.
This can be reopened once the requested information is provided.

**Comment by hulauwa** [comment]
I dont understand what you're means

**Comment by MrCrayon** [comment]
He means that when you open an issue there are things written, one of those is this:
```
<!--- The following information is required for bug reports.  Issues without it will be closed without response --->
```
If you want people to take their time to try help you you need to take your time to read and give all informations requested.

Anyway the link you wrote is not of a missing file, the missing files are in storage/.
You need to check if the symlink storage exists in your public folder and that is correctly pointing to ../storage/app/public
