### ISSUE TITLE
Call to undefined method TCG\Voyager\Voyager::canOrFail()

### ISSUE THREAD

**Issue by prakhargvp** [thedevdojo/voyager#4440]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.2.7
 - PHP: 7.2
 - Database: mysql

## Description

> The left side links are not working after upgrading voyager

![Screenshot from 2019-09-26 00-51-30](https://user-images.githubusercontent.com/7056772/65632676-e0074600-dff7-11e9-9222-b60aef5b2c98.png)

> After upgrading voyager its showing error on opening men builder 

![Screenshot from 2019-09-26 00-47-37](https://user-images.githubusercontent.com/7056772/65632678-e09fdc80-dff7-11e9-9b3b-b29481125eb1.png)

**Comment by emptynick** [comment]
The answer is the same as in https://github.com/the-control-group/voyager/issues/4013 where you commented.
Please read the upgrade guide.
