### ISSUE TITLE
Can't crop images

### ISSUE THREAD

**Issue by teomanofficial** [thedevdojo/voyager#4444]
- Laravel: v5.6
 - Voyager: v1.2
 - PHP: 7.2

I want to crop images instead of resize. But when I use "crop" option it does nothing.. 

Here is my options

```
{
    "crop": {
        "width": 270,
        "height": 270
    },
    "quality": "80%",
    "upsize": true
}
```

**Comment by MrCrayon** [comment]
Maybe crop works only for thumbnail, I see in the example code is used for that.
src/Http/Controllers/ContentTypes/MultipleImage.php

**Comment by teomanofficial** [comment]
@MrCrayon but that would be little useless. its force users to create two images, one for resized dummy image and another cropped one

**Comment by MrCrayon** [comment]
It's usefull when thumbnails are needed and that's when usually crops are applied but every app is different so this clearly doesn't satisfy your needs. 
You can still use a custom controller extend the base one and crop the image before is passed to the parent.

**Comment by emptynick** [comment]
Definitely not a bug.
Its not mentioned anywhere in the docs that this feature exists.
