### ISSUE TITLE
Voyager menu builder More nested levels

### ISSUE THREAD

**Issue by mf0wzi** [thedevdojo/voyager#4445]
## Version information

 - Laravel: v5.8.#
 - Voyager: v1.2.7
 - PHP: 7.1
 - Database: MySQL 5.7.26] 

## Description of problem
I am building a Project to Create a dynamic Dashboard dashlets, And I am using the menu builder to level the dashlets under each other if required and noticed that the menu builder only have 5 levels of nestable elements. 

Please is there any way to add more levels by using the  
$('.dd').nestable({
            expandBtnHTML: '',
            collapseBtnHTML: ''
        });
![Screenshot_2019-10-02 PP Builder](https://user-images.githubusercontent.com/30725615/66032794-b6c24a80-e50e-11e9-9b02-6492a1eeae87.png)

**Comment by fletch3555** [comment]
More than 5 levels in a menu sounds insane to me... perhaps there's a better design solution to your problem?  As for implementation, if you were to add these through a seeder, you can add whatever you want.  It's stored as a standard relational tree structure (self-referential table with a parent_id field)

In regards to the feature request, I'm not sure there's any code that's actually limiting it to 5, but I haven't looked that closely.  We can look at increasing it (or removing the restriction entirely if feasible).

**Comment by emptynick** [comment]
Nestable2 maxDepth property just defaults to 5 and we don't set that property.

**Comment by mf0wzi** [comment]
Thank you
