### ISSUE TITLE
bread problem in new project

### ISSUE THREAD

**Issue by masoudmansory** [thedevdojo/voyager#4448]
## cant create new bread
 - Laravel: v5.8.*
 - Voyager: v1.2

## Description

after : create new table > create new bread
<br>
cant view bread
## view scrin shot
https://filebin.net/89ukrqyi81tkv52b/bread.png?t=f6mh1wqe

**Comment by emptynick** [comment]
The issue template is not optional.
This can be reopened once the required information is provided.
