### ISSUE TITLE
Missing storage symlink

### ISSUE THREAD

**Issue by taist24** [thedevdojo/voyager#4449]
## Version information

 - Laravel: v5.8.*
 - Voyager: ^v1.2
 - PHP: 7.2
 - Database: [MySQL] [8.0] (e.g. MySQL 8.0)

## Description
I have pushed my code to production i.e on server. I was working on local and saved my work in git repo. All I did was git clone my repo and imported my database. When I opened the admin panel the images were missing and I had a warning alert specifying "Missing storage symlink". So I created the symlink using php native cmd symlink(). Now the images are loaded but I still have the alert showing up in the dashboard.

My app path is: **/var/www/html/gorham**
Laravel files are inside this path: **/var/www/html/gorham/core**
And Laravel public folder files are inside this path: **/var/www/html/gorham**

##Screnshot
![image](https://user-images.githubusercontent.com/41575890/66214068-9f39bc00-e6de-11e9-9c26-c56079358de3.png)

![image](https://user-images.githubusercontent.com/41575890/66214287-09526100-e6df-11e9-869c-b45af9ffdbfe.png)

![image](https://user-images.githubusercontent.com/41575890/66214334-238c3f00-e6df-11e9-8335-766dcdad2893.png)

![image](https://user-images.githubusercontent.com/41575890/66214387-3d2d8680-e6df-11e9-8088-beca006af7e9.png)

**Comment by emptynick** [comment]
Definitely not a bug.
There are some things wrong with your paths.
Your .env file will be accessible through the web and so on.
As this is a question, please ask it in our Slack group, or even better in a more generic Laravel forum/chat like Larachat or Laracasts.
