### ISSUE TITLE
Database update problem

### ISSUE THREAD

**Issue by crrack** [thedevdojo/voyager#445]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.5
- PHP Version: 7.0.10
- Database Driver & Version: 5.7.14

### Description:
When i want do some changes in database in save a get error.
I try only save with no changes and some error. 
I try instal clear laravel and voyager and some error. 
![voyager_database_bug2](https://cloud.githubusercontent.com/assets/23639276/21485482/6d5f5f80-cba4-11e6-82d0-8bb5baec04bd.png)

I working on localhost.
Sorry for bad english. I´m from Czech

**Comment by sarath-c-sandwich** [comment]
Is that a fresh install or upgraded from v.0.9?
Did you migrated database schema yet?
`php artisan migrate`

**Comment by Muhammadinaam** [comment]
In latest version, Voyager 0.11 this error looks like the image below. Error is in DatabaseQueryBuilder.php at line 159:

Line 159 in above file looks like below
`'key'      => $request->key[$index],`

**Solution** Replace above line with:
`'key'      => isset($request->key[$index]) ? $request->key[$index] : '' ,`

_**DEVELOPERS:** Please make necessary changes and commit in the code_

![bug1](https://cloud.githubusercontent.com/assets/22542738/21633855/9b6c0cf8-d274-11e6-8460-1a2179570b3b.png)

**Comment by marktopper** [comment]
Voyager 0.11 is still under development and is not ready for usage yet

**Comment by handiwijoyo** [comment]
#518 fixed this
