### ISSUE TITLE
Class BooksController does not exist

### ISSUE THREAD

**Issue by Zeshan316** [thedevdojo/voyager#4450]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2 as i've followed from docs.
 - PHP: 7.3.9
 - Database: [Mysql] [10.4.6-MariaDB] (e.g. MySQL 8.0)
- OS [Mac]

## Description

I have created a books table, moved to BREAD, create model, controller and other attributes, this saved successfully.
I got BOOKS Menu in sidebar after clicking this occurs.
**Class BooksController does not exist**

## Steps To Reproduce

1. 1. Go to table create
2. then add new table
3. add BREAD for this
4. after click this newly created menu

## Expected behavior
I have created a books table then moved to BREAD it create model and controller, this saved successfully.
I got BOOKS Menu in sidebar after clicking this occurs.
**Class BooksController does not exist**

## Screenshots
https://prnt.sc/pexmbg

**Comment by emptynick** [comment]
Voyager does not create a controller for you.
Instead it uses a default controller.
If you, at some point, need a custom controller, you have to create it.
Until then just leave the conroller field empty.
