### ISSUE TITLE
Can't install voyager

### ISSUE THREAD

**Issue by komeyl-dev** [thedevdojo/voyager#4452]
> cont install voyager

## Version information

 - Laravel: v6.0
 - Voyager: v^1.2 
 - PHP: 7.2
 - Database: MySQL

==>Error
`composer require tcg/voyager
Using version ^1.2 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v6.1.0
    - Conclusion: don't install laravel/framework v6.1.0
    - tcg/voyager 1.x-dev requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0|~6.0.0 -> satisfiable by laravel/framework[v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4], illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4].
    - tcg/voyager 1.2.x-dev requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.0 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.1 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.2 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.3 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.4 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.5 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.6 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - tcg/voyager v1.2.7 requires illuminate/support ~5.5.0|~5.6.0|~5.7.0|~5.8.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: laravel/framework[v6.0.0, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.1, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.2, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.3, v6.1.0].
    - Can only install one of: laravel/framework[v6.0.4, v6.1.0].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.16|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.17|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.28|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.33|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.34|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.35|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.36|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.37|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.39|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.40|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.41|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.43|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.5.44|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.6.x-dev|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.1|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.10|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.11|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.12|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.13|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.14|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.15|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.16|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.17|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.19|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.20|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.21|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.22|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.23|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.24|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.25|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.26|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.27|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.28|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.29|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.3|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.30|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.31|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.32|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.33|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.34|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.35|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.36|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.37|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.38|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.39|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.4|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.5|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.6|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.7|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.8|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.6.9|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.17|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.18|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.19|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.1|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.10|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.11|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.15|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.20|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.21|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.22|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.23|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.26|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.27|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.28|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.3|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.4|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.5|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.6|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.7|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.8|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.7.9|don't install laravel/framework v6.1.0
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.11|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.12|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.14|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.15|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.17|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.18|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.19|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.20|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.22|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.24|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.27|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.28|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.29|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.3|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.30|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.31|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.32|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.33|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.34|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.35|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.4|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.8|don't install laravel/framework v6.1.0
    - don't install illuminate/support v5.8.9|don't install laravel/framework v6.1.0
    - don't install illuminate/support v6.0.0|don't install laravel/framework v6.1.0
    - don't install illuminate/support v6.0.1|don't install laravel/framework v6.1.0
    - don't install illuminate/support v6.0.2|don't install laravel/framework v6.1.0
    - don't install illuminate/support v6.0.3|don't install laravel/framework v6.1.0
    - don't install illuminate/support v6.0.4|don't install laravel/framework v6.1.0
    - Installation request for laravel/framework (locked at v6.1.0, required as ^6.0) -> satisfiable by laravel/framework[v6.1.0].
    - Installation request for tcg/voyager ^1.2 -> satisfiable by tcg/voyager[1.2.x-dev, 1.x-dev, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7].

Installation failed, reverting ./composer.json to its original content.
`
==>composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by emptynick** [comment]
Please read our readme and search before opening issues.

**Comment by komeyl-dev** [comment]
@emptynick Please send **id** answer issues

**Comment by anthonyivol** [comment]
@emptynick you definitely should put this : 

Laravel Admin & BREAD System (Browse, Read, Edit, Add, & Delete), supporting Laravel 5.5, 5.6, 5.7 and 5.8!

here :

https://voyager-docs.devdojo.com/getting-started/installation
