### ISSUE TITLE
Extend with an empty var.

### ISSUE THREAD

**Issue by creadivteam** [thedevdojo/voyager#4454]
## Version information

 - Laravel: v6.0.3
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MySQL

## Description

You can't extend default slugify char maps because you try to merge with an empty var.

## Solution
Fix the condition before merge default map with the one you provide.
![Annotation 2019-10-07 130829](https://user-images.githubusercontent.com/26057287/66303397-9970f000-e903-11e9-9506-147d8efb6c14.png)

**Comment by fletch3555** [comment]
This would be much better suited as a pull request.

**Comment by MrCrayon** [comment]
@creadivteam I'm no familiar with that part of code but what you posted as **solution** is what the code looks like right now.
Should we remove `!` like this?
```diff
-           if (!this.settings.map) {      // Load extra character map translator
+           if (this.settings.map) {      // Load extra character map translator
                $.extend(this.chars, this.settings.map);
            }
```

Can you propose a PR?
