### ISSUE TITLE
tinymce's map

### ISSUE THREAD

**Issue by really4you** [thedevdojo/voyager#4458]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3

## Description

tinymce version default is 4.9.2,Map plug-in is not supported,How to upgrade TinyMCE or how to use map plug-ins ?thanks！

**Comment by really4you** [comment]
![image](https://user-images.githubusercontent.com/17646890/66365672-66d8fd00-e9c0-11e9-8d0e-4ac436120557.png)
like this ,but tinymce's version<5 do not support

**Comment by emptynick** [comment]
As the issue-template suggests, please ask questions in our Slack group.
