### ISSUE TITLE
Datatable ordering broken on browse with no checkboxColumn

### ISSUE THREAD

**Issue by mattrabe** [thedevdojo/voyager#4459]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.2.7
 - PHP: 7.2.8
 - Database: MySQL 5.7.8

## Description

Pull request #4151 introduced the setting of a new variable named `$showCheckboxColumn`, which is set within bread.browse view. If this var is `false`, then the first column of checkboxes is not displayed. This works well and is nice. However, before this variable is set in the view, the Controller assumes that the checkbox column is present, by adding `+ 1` to the index of the `orderColumn` at VoyagerBaseController.php::64. This means that when the Delete & Mass Delete actions are not present for a user, their client-side sorting will always be incorrect, since datatables will be trying to sort on the wrong column.

## Steps To Reproduce
1. Set the `order_column` for a DataType. Make sure that it also has the `delete` permission turned **ON** for your user role.
1. View the BREAD browse in a browser. Observe that ordering is correct, and the `order_column` you specified is "selected" by default.
1. Now turn **OFF** the `delete` permission for your user role on that DataType.
1. Look at the BREAD browse in a browser again.
1. *Observe that ordering is incorrectly happening on the column AFTER the one you specified as `order_column`.*

## Expected behavior

Ordering should work on `order_column` independent of `delete` permission

## Screenshots

![Screen Shot 2019-10-07 at 6 02 55 PM](https://user-images.githubusercontent.com/1786783/66366974-f1bce780-e92d-11e9-8561-c0212bd23d64.png)

**Comment by MrCrayon** [comment]
Just one clarification: as far as I can see this bug has always been there since ordering was introduced with #3781.
#4151 has really nothing to do with the bug itself that is assuming checkbox columns is always present in VoyagerBaseController.

**Comment by mattrabe** [comment]
You are correct, @MrCrayon - this seems to have pre-dated PR4151. Sorry to have pointed the blame there!

**Comment by MrCrayon** [comment]
@mattrabe no problem :wink:

**Comment by emptynick** [comment]
Closing as https://github.com/the-control-group/voyager/pull/4460 was merged.
