### ISSUE TITLE
Class 'TCG\Voyager\Traits\Cache' not found

### ISSUE THREAD

**Issue by yasir-pasha** [thedevdojo/voyager#4462]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1
 - Database: MySQL

## Description

I am facing this issue when the cache is enabled from the config.

## Steps To Reproduce
First, enable the cache from config. Then run `php artisan config: cache` and `php artisan config: view`
1. Go to dashboard

## Screenshots
[Screenshot](http://prntscr.com/pga14u)

**Comment by emptynick** [comment]
That's not Voyager code, so we can't help you on this one.

**Comment by fletch3555** [comment]
Also, please don't modify vendor code.  It'll just get overwritten next time you update
