### ISSUE TITLE
Undefined variable: searchable

### ISSUE THREAD

**Issue by arafathusayn** [thedevdojo/voyager#4467]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2.7
 - PHP: 7.3.9
 - Database: MySQL 5.7.27

## Description

I had overridden the view file for users table in `resources/views/vendor/voyager/users/browse.blade.php` with these codes: https://gist.github.com/arafathusayn/4d42671300269529fd3afc424546f3a0

In that file, I didn't change any php variable found in the previous view file inside the vendor directory. Then I removed `vendor/` directory and ran `composer install` again. Now if I navigate to browse users from the browser, I get:

```
ErrorException (E_ERROR)

Undefined variable: searchable (View: /<my_directories>/resources/views/vendor/voyager/users/browse.blade.php)

Previous exceptions
Undefined variable: searchable (0)
```  

Could you please let me know where the issue is?

**Comment by arafathusayn** [comment]
It seems like there are some breaking changes in voyager controller and views after I ran `composer update`. I was able to fix it.

**Comment by AmrAlfoly** [comment]
i have the same problem , can you please tell how did you fixed it

**Comment by arafathusayn** [comment]
@AmrAlfoly, you need to copy the blade templates again from ./vendor/tcg/...
