### ISSUE TITLE
Laravel 6.x support

### ISSUE THREAD

**Issue by amargoCactus** [thedevdojo/voyager#4469]
## Description of problem
Voyager supports laravel 6.x?

**Comment by amargoCactus** [comment]
Was that a yes or no?

**Comment by fletch3555** [comment]
That was a "please read the issue template so you're not wasting everyone's time".  You created a "feature request" issue, with nothing but a question, when the template clearly states `IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST`.

On top of that, it's a question that's easily answered through a number of means:

1. Project README file: https://github.com/the-control-group/voyager/blob/1.2/README.md
2. ~Docs:~ (can't seem to find the page, but at the very least, it used to be in there)
3. Search for existing issues/PRs requesting it: https://github.com/the-control-group/voyager/search?q=%22laravel+6%22&unscoped_q=%22laravel+6%22&type=Issues
4. Just try it and see what composer gives you...?
  a. Or just check dependencies at https://packagist.org/packages/tcg/voyager

**Comment by amargoCactus** [comment]
Okay, i'm sorry, i didn't notice.
