### ISSUE TITLE
Heroku Amazon s3 “Image source not readable” on upload error

### ISSUE THREAD

**Issue by faizananwerali** [thedevdojo/voyager#4477]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: v7.2.18
 - Database: Cleardb MySQL (e.g. MySQL 8.0)

## Description

Few days ago I started using laravel with voyager and deployed on heroku server. since heroku uses ephemeral filesystem so I was force to use amazon s3 services. The problem is whenever I upload a image on media manager in my voyager app it gives "Image source not readable" error message but at the same time shows images perfectly. I can only reproduce this error when I'm uploading a image/file or cropping a image. I thought this might be amazon policy issue but I've added policy to allow it still did not work.

**Block public access (bucket settings)**

```
Block all public access
Off
    Block public access to buckets and objects granted through new access control lists (ACLs)
    Off
    Block public access to buckets and objects granted through any access control lists (ACLs)
    Off
    Block public access to buckets and objects granted through new public bucket policies
    Off
    Block public and cross-account access to buckets and objects through any public bucket policies
    Off
```

**Bucket policy editor**

```
{
    "Version": "2012-10-17",
    "Id": "Policy1************",
    "Statement": [
        {
            "Sid": "Stmt1************",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::my_bucket_name/*"
        }
    ]
}
```

## Steps To Reproduce
1. host laravel voyager at heoku and setup amazon s3.
2. Upload Picture in media manager or any file uploader.

## Expected behavior
It should show these errors. it show upload normally like they do in local public folder.

## Screenshots
*Upload Error Image:*

[![Upload Error Image][1]][1]

*Crop Error Image:*

[![Image Crop Error Image][2]][2]

  [1]: https://i.stack.imgur.com/X4ggS.png
  [2]: https://i.stack.imgur.com/zfUW7.png

**EDIT 1**
==========

So I debugged it in vendor directory and turns out it's Intervention\\Image\\Exception\\NotReadableException error in vendor\tcg\voyager\src\Http\Controllers\VoyagerMediaController.php

_vendor\tcg\voyager\src\Http\Controllers\VoyagerMediaController.php_ file

    public function crop(Request $request)
    {
        // Check permission
        $this->authorize('browse_media');

        $createMode = $request->get('createMode') === 'true';
        $x = $request->get('x');
        $y = $request->get('y');
        $height = $request->get('height');
        $width = $request->get('width');

        $realPath = Storage::disk($this->filesystem)->getDriver()->getAdapter()->getPathPrefix();
        $originImagePath = $realPath.$request->upload_path.'/'.$request->originImageName;

        $e = [];
        try {
            if ($createMode) {
                // create a new image with the cpopped data
                $fileNameParts = explode('.', $request->originImageName);
                array_splice($fileNameParts, count($fileNameParts) - 1, 0, 'cropped_'.time());
                $newImageName = implode('.', $fileNameParts);
                $destImagePath = $realPath.$request->upload_path.'/'.$newImageName;
            } else {
                // override the original image
                $destImagePath = $originImagePath;
            }

            Image::make($originImagePath)->crop($width, $height, $x, $y)->save($destImagePath);

            $success = true;
            $message = __('voyager::media.success_crop_image');
        } catch (Exception $e) {
            $success = false;
            $message = $e->getMessage();
            $errors['originImagePath'] = $originImagePath;
            $errors['destImagePath'] = $destImagePath;
            $errors['exception'] = get_class($e);
            $errors['file'] = $e->getFile();
            $errors['code'] = $e->getCode();
            $errors['line'] = $e->getLine();
            $errors['trace'] = $e->getTrace();
        }

        return response()->json(compact('success', 'message', 'errors'));
    }

Post Response _http://localhost/voyager/public/admin/media/crop_

    {
      "success": false,
      "message": "Image source not readable",
      "errors": {
        "originImagePath": "//Capture1.PNG",
        "destImagePath": "//Capture1.cropped_1570987211.PNG",
        "exception": "Intervention\\Image\\Exception\\NotReadableException",
        "file": "D:\\wamp64\\www\\voyager\\vendor\\intervention\\image\\src\\Intervention\\Image\\AbstractDecoder.php",
        "code": 0,
        "line": 346
      }
    }

How do I solve this?

**Comment by MrCrayon** [comment]
Can you try if #4428 fixes your problem?

**Comment by faizananwerali** [comment]
Tried [4428](https://github.com/the-control-group/voyager/pull/4428) but it didn't work.
One thing I've notice that the problem is with png, jpg, gif and svg.
Webp uploading and cropping is working fine and so is bmp.
No problem with other file types other than these four image types

Also I tried in different environment.
Localhost:
disk - public - works fine
disk - s3 - gives error "Image source not Readable"

Heroku:
disk - public - doesn't work because of their [ephemeral](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem) system
disk - s3 - same problem as localhost

**Comment by faizananwerali** [comment]
I've asked this question on [stackoverflow](https://stackoverflow.com/questions/58342214/heroku-laravel-voyager-amazon-s3-image-source-not-readable-on-upload-error) as well with bounty. Hoping that some genius will solve my misery.

**Comment by faizananwerali** [comment]
Also Image gets written successfully in s3 bucket and I can also access these images in media manager but I still get error when upload and it doesn't even crop image.
I think the problem is which exist in both cases is "_$image->save($realPath.$file, ($details->quality ?? 90));_" is his 90% compression which fails.

I've tried both image driver *gd* and *imagick* extension but still it doesn't work.
Now I am just looking to avoid compression to avoid this error.

**Comment by MrCrayon** [comment]
What's $originImagePath for an image that is working?

**Comment by faizananwerali** [comment]
Oh wait I did it wrong.
Actually only upload function is working for both bmp and webp.
Cropping bmp gave same "Image source not readable" error.
Can't crop webp because it MIME type becomes text/plain.

**Upload JSON**
_webp_
`{"success":true,"message":"Successfully uploaded new file!","path":"0bb83114d47e4ca0a9fa5a9ea6a16530.webp"}`
_bmp_
`{"success":true,"message":"Successfully uploaded new file!","path":"Capture_1.bmp"}`
_png_
`{"success":false,"message":"Image source not readable","path":""}`
_jpg_
`{"success":false,"message":"Image source not readable","path":""}`
_svg_
`{"success":false,"message":"Image source not readable","path":""}`
_gif_
`{"success":false,"message":"Image source not readable","path":""}`


**Crop JSON**
_webp_
Can't crop because it MIME type becomes text/plain.
_bmp_
`{"success":false,"message":"Image source not readable","originImagePath":"\/\/Capture.bmp"}`
_png_
`{"success":false,"message":"Image source not readable","originImagePath":"\/\/2Capture_2.PNG"}`
_jpg_
`{"success":false,"message":"Image source not readable","originImagePath":"\/\/scan 1.jpg"}`
_svg_
`{"success":false,"message":"Image source not readable","originImagePath":"\/\/kiwi.svg"}`
_gif_
`{"success":false,"message":"Image source not readable","originImagePath":"\/\/giphy.gif"}`


I also tried to remove double forward slashes from originImagePath variable in crop function.
`$originImagePath = trim($originImagePath,"\/");`
It also didn't work

**Comment by faizananwerali** [comment]
Unless I debug every single line of code I'm shooting in dark.

**Comment by MrCrayon** [comment]
I think you have to understand where is the problem first, is it a problem loading the image or in the path to the image?

The $originImagePath looks odd to me, I would try to add a check with:
```php
File::exists($originImagePath)
```
If that's false than the problem might be that.
At that point I would hard code a value that I know is correct for an image already uploaded and see if the cropping works.

**Comment by fredriksundstrom** [comment]
@faizananwerali I'm currently at the exact same spot as you, both with localhost (Homestead) and Heroku. It's been about a month, did you get anywhere with this?

**Comment by faizananwerali** [comment]
Nope. I tried another clouds storage (Google buckets) to see if this error persist and it did. I tried localhost on xampp, localhost on wamp, linux shared hosting, windows shared hosting and heroku. Error persist on each one of them. Windows hosting being worse, can't even read image path properly because windows follow backslash path and linux follow forward slash path.

**Comment by fredriksundstrom** [comment]
I don't know why it didn't work for you @faizananwerali, but I actually did try fix #4428 and it did the trick. Overriding the VoyagerMediaController was a bit of a process, tho, and during that process I had a bunch of false positives where I thought I had overridden it correctly. But anyway, the fix actually does fix this issue for me.

I can see that the fix wasn't included in any release, fails all the checks etc, so @MrCrayon do you know what the next step would be for that fix?

**Comment by MrCrayon** [comment]
@fredriksundstrom that PR it's failing the upload test, so that's not a good sign.
It could be that upload works in remote storage but not local or it could be a quirk from the test, I'll try to check it when I can.

**Comment by faizananwerali** [comment]
I fixed it here 
https://github.com/the-control-group/voyager/pull/4565

**Comment by AbdulazizFayez** [comment]
Hi, is this issue fixed? because i can see that master is not yet updated with this.

I'm having the same issue where media doesn't read s3 images, right now i'm doing a work around using lumen API to get the images with token and it's taking some time to work on every time

Appreciate if this issue is fixed, because this will save a lot of our time using custom methods.

Thank you for your time and efforts.

**Comment by MrCrayon** [comment]
No, as you can see this issue is still open there is a PR #4565 that has not be merged yet.

What you can do is test PR #4565 and report your results with your enviroment so that it can be merged sooner.

**Comment by AbdulazizFayez** [comment]
I see. actually, i just found out that my issue is not related to this

My images are not showing on media manager because, (I'm using AWS S3 and filesystem is pointing to to the correct storage). 

I think my issue it seems to be related to the "media manager" not hashing the content that is being uploaded, unlike BREAD, where contents uploaded are hashed and they're read successfully. 

So since my issue is with the media manager, any advice on where i can enforce hashing on media manager? I'm not sure if this is a bug or does it need to be enabled/disabled.

Thank you.

**Comment by MrCrayon** [comment]
@AbdulazizFayez if it's not related please open another issue explaining what's the problem.
If you have problems with images not updating, that's a know problem, even if I think there is no issue opened, I posted a work around in our Voyager Slack chat to solve that.
