### ISSUE TITLE
Column not found error in menu builder

### ISSUE THREAD

**Issue by taiwanleaftea** [thedevdojo/voyager#4481]
## Version information

 - Laravel: v6.0-6.3
 - Voyager: v1.x-dev 68e206a (this version is installed by composer require tcg/voyager)
 - PHP: 7.3.10
 - Database: 10.3.18-MariaDB

## Description

Column not found error, during update any menu item in menu builder.
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column '/admin/menus/1/item' in 'field list' (SQL: update `menu_items` set `color` = #000000, `parameters` = null, `/admin/menus/1/item` = ?, `menu_items`.`updated_at` = 2019-10-16 13:31:45 where `id` = 4) 

## Steps To Reproduce
1. Install new laravel project
2. Install voyager via "composer require tcg/voyager"
3. Create database and run voyager installer
4. Go to Menu buider and open admin menu in builder
5. Edit any menu item and click update

## Additional context
I made some work around and the problem is, that VoyagerMenuController.php calls $request->except(['id']), which returns this array:
array:12 [▼
  "_method" => "PUT"
  "_token" => "BsI4vToB2x1WK5qu4HylB3DOxnGRmQ6lbM0FmzYG"
  "title" => "Roles"
  "type" => "route"
  "url" => null
  "route" => "voyager.roles.index"
  "parameters" => "null"
  "icon_class" => "voyager-lock"
  "color" => "#000000"
  "target" => "_self"
  "menu_id" => "1"
  "/admin/menus/1/item" => null
]
So I made custom MenuController, which extends VoyagerMenuController and overrides method prepareParameters($parameters) and adds this code:
foreach ($parameters as $key => $value) {
     if (Str::startsWith($key, '/admin/menus/')) {
          unset($parameters[$key]);
     }
}
With this addition I can save the menu item, but I'm not sure, that it's best way to avoid this bug.

**Comment by taiwanleaftea** [comment]
Updated voyager to 1.3.*, the problem still exists

**Comment by emptynick** [comment]
Works perfectly fine for me.
Do you have multi-language enabled or something?

**Comment by taiwanleaftea** [comment]
Nothing special is enabled. It's a fresh install of laravel and voyager with default settings.

**Comment by MrCrayon** [comment]
Can't reproduce on fresh install:
- Laravel: v6.3
- Voyager: v1.x-dev
- PHP: 7.3.10
- Database: 10.3.17-MariaDB

```
array:11 [▼
  "_method" => "PUT"
  "_token" => "YvS29UI8mLxukHb2xK3fPadOV3JInFKxPKovoz99"
  "title" => "Roles"
  "type" => "route"
  "url" => null
  "route" => "voyager.roles.index"
  "parameters" => "null"
  "icon_class" => "voyager-lock"
  "color" => "#000000"
  "target" => "_self"
  "menu_id" => "1"
]
```

With multilingual enabled
```
array:13 [▼
  "_method" => "PUT"
  "_token" => "YvS29UI8mLxukHb2xK3fPadOV3JInFKxPKovoz99"
  "i18n_selector" => "on"
  "title_i18n" => "{"en":"Roles"}"
  "title" => "Roles"
  "type" => "route"
  "url" => null
  "route" => "voyager.roles.index"
  "parameters" => "null"
  "icon_class" => "voyager-lock"
  "color" => "#000000"
  "target" => "_self"
  "menu_id" => "1"
]
```

**Comment by taiwanleaftea** [comment]
Maybe it depends of web server and his config? I use nginx/1.10.3 with this config:

    server {
       listen 80;
       server_name laravel;

    error_page 404 = /index.php;

    error_log /home/laravel/www/logs/laravel.error.log;
    charset utf8;
    index index.php;

    root /home/laravel/www/laravel/public/;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    location ~* \.(jpg|jpeg|gif|css|png|js|ico|html|woff2)$ {
        access_log off;
        expires max;
        log_not_found off;
    }

    if (!-d $request_filename)
    {
        rewrite ^/(.+)/$ /$1 permanent;
    }

    if (!-e $request_filename)
    {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* \.php$ {
        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 128k;
        fastcgi_read_timeout 300;
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    }

**Comment by MrCrayon** [comment]
> Maybe it depends of web server and his config? I use nginx/1.10.3 with this config:

Yes, I think you are getting url as get parameter to index.php, you can verify it printing:
```php
dd($request->fullUrl());
```
You should probably remove:
```
if (!-d $request_filename)
{
    rewrite ^/(.+)/$ /$1 permanent;
}

if (!-e $request_filename)
{
    rewrite ^/(.*)$ /index.php?/$1 last;
    break;
}
```

**Comment by taiwanleaftea** [comment]
Yes, it's because of the second one:

    if (!-e $request_filename)
    {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }
