### ISSUE TITLE
Can't save BelongsTo relationship

### ISSUE THREAD

**Issue by taiwanleaftea** [thedevdojo/voyager#4482]
## Version information

 - Laravel: v6.0-6.3
 - Voyager: v1.x-dev 68e206a / 1.3.x-dev 09c1153
 - PHP: 7.3.10
 - Database: 10.3.18-MariaDB

## Description

I can select items from related table (BelongsTo relationship), but when I save relationship information is not saved.

## Steps To Reproduce
1. Install new laravel project
2. Install voyager via "composer require tcg/voyager"
3. Create database and run voyager installer
4. Create two tables (i.e. pages and offers), add nullable offer_id column to pages table.
5. Create models for those tables.
6. Add some rows to the offers table, and add record to pages table with offer selected. offer_id will not be saved.

## Additional context
I've tried different versions of voyager. Version 1.x-dev c9dd5a8 saves BelongsTo relationship, but in this version the relationship cannot be removed. I can select "None" in dropdown list, but the column will not be updated.

**Comment by MrCrayon** [comment]
Can't reproduce on fresh install:
- Laravel: v6.3
- Voyager: v1.x-dev
- PHP: 7.3.10
- Database: 10.3.17-MariaDB

Are you positive you are using a fresh install and you didn't just update?
On fresh install with-dummy I create a new user and can successfully assign or remove a role to that user.

**Comment by taiwanleaftea** [comment]
> Are you positive you are using a fresh install and you didn't just update?

Yes, it's fresh install without dummy

> On fresh install with-dummy I create a new user and can successfully assign or remove a role to that user.

Yes, when I create a new user, I can assign the role to him, but when I try to assign the same belongs to relationship for another table, it doesn't work. My table has the same nullable field as role_id in users table. ~The only difference is, that user BREAD controller uses own add-edit.blade, and my table uses a default one. 
So IMO the problem is somewhere in blade.~

**Comment by taiwanleaftea** [comment]
Also users has the own controller, which contains:

    $request->merge([
           'role_id' => Auth::user()->role_id,
           'user_belongstomany_role_relationship' => Auth::user()->roles->pluck('id')->toArray(),
     ]);

**Comment by MrCrayon** [comment]
That's only to prevent users to change their role.

**Comment by taiwanleaftea** [comment]
Output from dd($request->all()) in update method of VoyagerBaseController:

     array:18 [▼
         "_method" => "PUT"
         "_token" => "TODzhnRbwmBUkThh35TvieQsLmCKiaZeX3Z8rlvF"
         "gift_id" => "1"
         "offer_id" => "8"
         skipped
     ]

BREAD settings for the relationships:

<img width="1084" alt="ffff" src="https://user-images.githubusercontent.com/13335635/66991130-c2457200-f0c7-11e9-9bf6-d7a2b8726edc.png">

**Comment by MrCrayon** [comment]
If you are trying with v1.2.7 that's not going to work, you need to move offer_id and gift_id after the realtionships.
With 1.x or 1.3 should work.

**Comment by taiwanleaftea** [comment]
It's 1.3.x-dev 09c11530ceacffadeb82cb85ad59d72125c9c7e0
Which was installed with this setting in composer.json "tcg/voyager": "1.3.*"

**Comment by taiwanleaftea** [comment]
One more thing. 

        dd($data);
        $data->save();

In public function insertUpdateData($request, $slug, $rows, $data) of Controller class gives following output:

<img width="369" alt="Снимок экрана 2019-10-17 в 11 14 40" src="https://user-images.githubusercontent.com/13335635/66995651-a9d95580-f0cf-11e9-914c-02a87caaefff.png">

**Comment by MrCrayon** [comment]
I'm a bit lost, you are using 1.3.x so I think what's not working for you now is removing belongsto relationship once set, correct?

If that's what you are debugging the screenshot is what I would expect.

What's the value of offer_id and gift_id before and after the update?

**Comment by taiwanleaftea** [comment]
No, I can't save belongsto relationship. I made following changes in  insertUpdateData:
1. added $row->details->type !== 'belongsTo' check

            if (!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox') {
                // if the field is a belongsToMany relationship, don't remove it
                // if no content is provided, that means the relationships need to be removed
                if (isset($row->details->type) && $row->details->type !== 'belongsToMany' && $row->details->type !== 'belongsTo') {
                    continue;
                }
            }

2. Commented out continue, so this if can be removed

            // Value is saved from $row->details->column row
            if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                //continue;
            }

Added this

                if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                    $content = $request->{$row->field};
                }

to 

            if (is_null($content)) {

                // If the image upload is null and it has a current image keep the current image
                if ($row->type == 'image' && is_null($request->input($row->field)) && isset($data->{$row->field})) {
                    $content = $data->{$row->field};
                }

                // If the multiple_images upload is null and it has a current image keep the current image
                if ($row->type == 'multiple_images' && is_null($request->input($row->field)) && isset($data->{$row->field})) {
                    $content = $data->{$row->field};
                }

                // If the file upload is null and it has a current file keep the current file
                if ($row->type == 'file') {
                    $content = $data->{$row->field};
                    if (!$content) {
                        $content = json_encode([]);
                    }
                }

                if ($row->type == 'password') {
                    $content = $data->{$row->field};
                }

                if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                    $content = $request->{$row->field};
                }
            }

Now I can assign and also remove belongsto relationship. ~I'll test it now with user-role BREAD.~
With user BREAD is also Ok.

**Comment by MrCrayon** [comment]
You are trying to fix something that doesn't need fixing.

Unless you have a custom view you will never get any data from this:
```php
            if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                $content = $request->{$row->field};
            }
```
That field is always null because is not present in the standard view to be sent.

Are you using custom views?

**Comment by taiwanleaftea** [comment]
No, I have fresh install. I've only added a few tables to the default DB, and set relationship as shown above. Nothing more.

Here is output from: 

    // POST BR(E)AD
    public function update(Request $request, $id)
    {
        dd($request->all());

<img width="312" alt="Снимок экрана 2019-10-17 в 12 44 45" src="https://user-images.githubusercontent.com/13335635/67002452-39850100-f0dc-11e9-92cd-7d9ba9958113.png">

Output from 

    public function insertUpdateData($request, $slug, $rows, $data)
    {
        dd($data);

<img width="302" alt="Снимок экрана 2019-10-17 в 12 52 25" src="https://user-images.githubusercontent.com/13335635/67002910-258dcf00-f0dd-11e9-89a9-a1c6f39e9b55.png">

both offer_id and gift_id are null. If thus were set before and I'm trying to change, here are old values.

As I understand, at this step $data must contain values for gift_id and offer_id from request to save it.

        if (isset($data->additional_attributes)) {
            foreach ($data->additional_attributes as $attr) {
                if ($request->has($attr)) {
                    $data->{$attr} = $request->{$attr};
                }
            }
        }

        dd($data);
        $data->save();

        // Save translations
        if (count($translations) > 0) {
            $data->saveTranslations($translations);
        }

but both are null.


<img width="228" alt="Снимок экрана 2019-10-17 в 13 00 35" src="https://user-images.githubusercontent.com/13335635/67003492-5a4e5600-f0de-11e9-9295-239d6020399c.png">

**Comment by taiwanleaftea** [comment]
When I try to edit user, the last output contains correct role_id

<img width="312" alt="Снимок экрана 2019-10-17 в 13 17 44" src="https://user-images.githubusercontent.com/13335635/67004442-9d112d80-f0e0-11e9-939d-e71cff006ef3.png">

**Comment by MrCrayon** [comment]
AHHHHHHHHHHHHHH
I should have notice earlier... you need to check edit and add for offer_id and gift_id in BREAD configuration and you are set.

Basically when you are in insertUpdateData foreach is only for $rows ($dataType->editRows or addRows if you are creating) so everything else is ignored.

Be sure to revert any changes you made to vendor files.

**Comment by MrCrayon** [comment]
Also dd($data); you were using inside insertUpdateData is showing you the current model data, the data you sent for update is in $request.

**Comment by taiwanleaftea** [comment]
> I should have notice earlier... you need to check edit and add for offer_id and gift_id in BREAD configuration and you are set.

Yes, now it works, thanks. I understand the idea now. I thought, that thus settings only to show/hide them in forms.

> Also dd($data); you were using inside insertUpdateData is showing you the current model data, the data you sent for update is in $request.

As I understand the first (at the beginning) contains model from DB, an the last one the data from request, which will be saved.

**Comment by MrCrayon** [comment]
> As I understand the first (at the beginning) contains model from DB, an the last one the data from request, which will be saved.

Here it contains model from DB:
```
public function insertUpdateData($request, $slug, $rows, $data)
{
    dd($data);
```
