### ISSUE TITLE
INCORRECT view action button icon

### ISSUE THREAD

**Issue by SayDevz** [thedevdojo/voyager#4486]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.7
 - PHP: 7.1
 - Database: MySQL

## Description

It seems that the default action view button icon is missing. "search" instead of voyager-eye
<img width="1112" alt="Screen Shot 2019-10-17 at 11 59 22 PM" src="https://user-images.githubusercontent.com/18522102/67026388-36206280-f13a-11e9-8796-e20cee74756e.png">

**Comment by emptynick** [comment]
This is better opened as a pull request

**Comment by fletch3555** [comment]
You're going to have to be much more specific about what this is supposedly fixing.  Looking at the 1.3 branch, I don't see anything wrong with the icon

**Comment by SayDevz** [comment]
My bad I thought i was using 13 it was in 1.2.7. But i think it should be fix in 1.2 ver.
