### ISSUE TITLE
SQLSTATE[HY000]: General error: 1364 Field 'pagination' doesn't have a default value

### ISSUE THREAD

**Issue by omarkadd** [thedevdojo/voyager#4500]
## Version information

 - Laravel: v6.3.0
 - Voyager: v1.3
 - PHP: 7.3.1
 - Database: MySql 5.7

## Description

i created a new table in the database using the admin/database
after that i wanted to add a bread to it without changing anything in the bread just submitting it this error is happening
SQLSTATE[HY000]: General error: 1364 Field 'pagination' doesn't have a default value

## Screenshots
![Annotation 2019-10-23 121658](https://user-images.githubusercontent.com/26447067/67377922-12707880-f58f-11e9-8c2f-8b1998f06726.png)

**Comment by MrCrayon** [comment]
Do you have a _pagination_ field in your table?

**Comment by omarkadd** [comment]
no!! this error comes and goes without reason and some times i refresh the error doesn't appear

**Comment by fletch3555** [comment]
A SQLSTATE error comes from the database, not Voyager or even Laravel... which means the database seems to think your table has a field named `pagination`.  There's not much we can do here other than tell you to double-check your database

**Comment by omarkadd** [comment]
but there isn't the table only has a couple or columns like name id and some stuff as shown in the image there is no pagination and i searched my sql and the quires sent there is no pagination at all

**Comment by omarkadd** [comment]
well i found out where the pagination is it is in a voyager table called data_types it has a field called  pagination not sure what to do now lol
![Annotation 2019-11-05 131052](https://user-images.githubusercontent.com/26447067/68203153-de08ad80-ffcd-11e9-8aa6-d79b522c3eac.png)
 i deleted the column pagination from the table the bread worked after that iam not sure what happened but i think this issue is closed by deleting pagination column from table  data_types

**Comment by MrCrayon** [comment]
_pagination_ column is not normally present in _data_types_, maybe you added it to try something and then forgot about it :grin:

**Comment by adrianloh128** [comment]
i know im late but might be helpful to others, this problem occur when you export import your table, the primary key in the voyager table is removed, so you need to add the primary key in the voyager default tables and auto increment

for example: 
SQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value (SQL:
insert into `data_types` (`name`, `display_name_singular`, `display_name_plural`,
`slug`, `icon`, `model_name`, `controller`, `policy_name`, `generate_permissions`,
`details`, `description`, `server_side`, `updated_at`, `created_at`) values (hdept,
Hdept, Hdepts, hdept, , App\Hdept, , , 1, {"order_column":null, "order_display_column":null,
"order_direction":"asc", "default_search_key":null}, , 0, 2019-03-04 12:56:29,
2019-03-04 12:56:29))

the voyager default table data_types in your db dont have auto increment enabled
