### ISSUE TITLE
Code Editor field - language selection not working

### ISSUE THREAD

**Issue by dralyuk** [thedevdojo/voyager#4501]
## Version information

 - Laravel: v6.3.0
 - Voyager: v1.3.0
 - PHP: 7.3.9
 - Database: MySQL 8

## Description
Language selection in Code Editor field not working

## Steps To Reproduce
1. Set field type to Code Editor in BREAD
2. Pass argument {"language": "js"}

## Screenshots
https://prnt.sc/pna0tc
https://prnt.sc/pna0jp
Console error https://prnt.sc/pna0y4

**Comment by MrCrayon** [comment]
I didn't try but it should be:

resources/assets/js/voyager_ace_editor.js
```diff
+	ace.config.set("basePath", $('meta[name="assets-path"]').attr('content')+"?path=js/ace/libs");

	// Create an ace editor instance
	var ace_editor = ace.edit(ace_editor_element[i].id);
```
webpack.mix.js
```diff
-.copy('node_modules/tinymce/themes/modern', 'publishable/assets/js/themes/modern');
+.copy('node_modules/tinymce/themes/modern', 'publishable/assets/js/themes/modern')
+.copy('node_modules/ace-builds/src-noconflict', 'publishable/assets/js/ace/libs');
```

Of course this should be submitted as PR but if you need it working now you can fork voyager and use your fork until is fixed.
