### ISSUE TITLE
Updated to 1.3 = Route [voyager.media.remove] not defined

### ISSUE THREAD

**Issue by hirbod** [thedevdojo/voyager#4506]
## Version information

 - Laravel: v6.4.0
 - Voyager: v1.3.0
 - PHP: 7.3.1
 - Database: MariaDB

## Description

Route [voyager.media.remove] not defined. (View: /home/vagrant/code/resources/views/vendor/voyager/users/edit-add.blade.php)

## Steps To Reproduce
1. Go to Users
2. Click on edit
3. See error

## Expected behavior
I want to edit the user in the admin panel

**Comment by emptynick** [comment]
`/home/vagrant/code/resources/views/vendor/voyager/users/edit-add.blade.php` is a custom view. 
Without seeing it there's no chance we can help you.

**Comment by MrCrayon** [comment]
route was changed in #4113

```blade
                $.post('{{ route('voyager.'.$dataType->slug.'.media.remove') }}', params, function (response) {
```

If you have custom views you should always check if something was changed in the original to keep yours updated.

**Comment by hirbod** [comment]
Thanks @MrCrayon, that fixed my issue. Haven't worked on that particular project for more then 4 months, totally forgot about the custom view.
