### ISSUE TITLE
Rename title folder in Media

### ISSUE THREAD

**Issue by jackphuongvu** [thedevdojo/voyager#4508]
![image](https://user-images.githubusercontent.com/23715737/67636546-5c958900-f904-11e9-8f21-3bf813685714.png)
---
It will be more great if we have renaming folder in Media.

## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

**Comment by emptynick** [comment]
First, the issue template is required when opening issues.
You can just rename folders like you can rename files.
