### ISSUE TITLE
Missing menu items on production

### ISSUE THREAD

**Issue by gawelkot** [thedevdojo/voyager#4512]
## Version information

 - Laravel: v1.2
 - Voyager: v6.0
 - PHP: 7.3
 - Database: MySQL

## Description

I've got the problem with voyager after moving it to production server. I' ve copied the database from local server. On the production I can see all breads, tables etc. but i don't see new menu items in voyager panel. Anyone can help?

In my database I' ve got new menu-items but they are not visible in panel. Thanks for any answers.

**Comment by MrCrayon** [comment]
You mixed up Laravel and Voyager versions and they both have a third number (v1.2.7), it would be useful to have it.

Said that it could be a problem with permissions: check if the user has permission to browse that bread; or it could be a cache problem: clear cache.

**Comment by emptynick** [comment]
The menu-items are cached. When you just merge your tables together, it won't refresh the cache.

**Comment by gawelkot** [comment]
Thank you :)
`php artisan cache:clear`
This command helped.

**Comment by emptynick** [comment]
Then I'll close this.
