### ISSUE TITLE
Problem BelongTo relationship

### ISSUE THREAD

**Issue by jltrevizon** [thedevdojo/voyager#4513]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.7
 - PHP: 7.2
 - Database: mysql

## Description:
When creating a field of type "BelongTo" and added to BREAD, in edit mode it is not possible to indicate if the field is required, in version 1.2.6 the validation rule was added in the field of the relationship and it worked perfectly .
## Additional context
When it was in 1.2.6 it worked, upgrade to 1.2.7 now it doesn't work.
I have removed the BREAD and created it again and it still doesn't work.

**Comment by MrCrayon** [comment]
It should work again in 1.3

**Comment by MrCrayon** [comment]
This should work in v1.3.0, if not please open another issue.
