### ISSUE TITLE
Class VoyagerAuth does not exist

### ISSUE THREAD

**Issue by nestle49** [thedevdojo/voyager#4517]
- Laravel: v5.8
 - Voyager: v1.3
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 5.7)

## Steps To Reproduce
1. Go to admin panel
2. Fill in login and password 
3. Click on login
4. See error "Class VoyagerAuth does not exist (View:..."

composer update/dump-autoload.jpg executed at the root of the project and at the root of the voyager

what's wrong?

**Comment by emptynick** [comment]
You didn't read the upgrade guide.

**Comment by nestle49** [comment]
> You didn't read the upgrade guide.

From 1.2 -> 1.3? Read
