### ISSUE TITLE
Menu Sorting

### ISSUE THREAD

**Issue by Muzamel** [thedevdojo/voyager#4521]
## Version information

 - Laravel: v5.7.28
 - Voyager: v1.2.6

## Description

I have problem when I try to save menu position with drag and drop in Menu.

## Steps To Reproduce
1. Drag menu for set order in same parent it returns saved message.
2. Reload the page then the order set back to the old position in admin panel & front-end too.

Please provide the proper solution

## Expected behavior
Menu order will be saved in set position .

## Additional context
Here on the  [Stack-Over-Flow](https://stackoverflow.com/questions/55731254/how-to-fix-menu-position-dont-save-in-laravel-voyager/58620513#58620513) another person have the same problem and my tried solution in answer too.

**Comment by MrCrayon** [comment]
Already fixed in v1.2.7 #4186

**Comment by emptynick** [comment]
Thanks.
