### ISSUE TITLE
tiny mce media(embed) option not activated

### ISSUE THREAD

**Issue by shazimali** [thedevdojo/voyager#4523]
i am using voyager version 1.26. i am using tiny mce rich text editor. i didn't get media(for embed video iframe) option in rich text editor. i also try to add media plugin in tiny mce by this code

function tinymce_init_callback(editor) {
  editor.remove();
  editor = null;
  tinymce.init({
      menubar: false,
      selector: 'textarea.richTextBox',
      skin_url: $('meta[name="assets-path"]').attr('content') + '?path=js/skins/voyager',
      min_height: 600,
      resize: 'vertical',
      plugins: 'print preview searchreplace autolink directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern help code textcolor',
      extended_valid_elements: 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
      file_browser_callback: function (field_name, url, type, win) {
          $('#upload_file').trigger('click');
      },
      toolbar: 'formatselect | bold italic strikethrough | forecolor backcolor | link image media | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent | ltr rtl | removeformat | code',
      convert_urls: false,
      image_caption: true,
      image_title: true,
      content_css: "/css/app.css",
      valid_elements: 'div[*],p[*],span[*],ul[*],li[*],ol[*],hr,br,img[*],i[*],em,table[*],tr[*],td[*],th[*],sup[*],sub[*],strong[*],b,h1[*],h2[*],h3[*],h4[*],h5[*],h6[*],small[*],a[*], svg,path',
      valid_children: '+li[span|p|div]',
      content_style: '.mce-annotation { background: #fff0b7; } .tc-active-annotation {background: #ffe168; color: black; }',
      external_plugins: {
          'print': 'http://localhost:8001/tinymce/plugins/media/plugin.min.js'
      }
  })
}

but i am not getting media embed option in tiny mce skin.

**Comment by emptynick** [comment]
The issue template is not optional.
This can be reopened once the required informations are provided.

**Comment by shazimali** [comment]
> The issue template is not optional.
> This can be reopened once the required informations are provided.

i didn't understand your rply ......... what you mean?
