### ISSUE TITLE
Voyager logo is not stop spinning 

### ISSUE THREAD

**Issue by nony22** [thedevdojo/voyager#4524]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP: 7,3.1
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

After composer update and npm update i can not see the dashboard anymore, the voyager logo is not stoping to spin. I try to access users and i have same issue. I receive in console 'Vue is not defined'. Vue is working on my site, only on voyager route is not working.

## Steps To Reproduce
1. Go to 'login page'
2 After successful login i receive Vue is not defined

## Screenshots

![Untitled](https://user-images.githubusercontent.com/55444824/67983498-17839680-fc25-11e9-9ec1-e738a418aab8.png)
![Untitled1](https://user-images.githubusercontent.com/55444824/67983499-17839680-fc25-11e9-9a73-8331ccf81632.png)
![Untitled2](https://user-images.githubusercontent.com/55444824/67983500-17839680-fc25-11e9-8065-d994438a00bf.png)

**Comment by MrCrayon** [comment]
There is a syntax error in app.js, so the problem is there.
Since original app.js doesn't have any syntax error I must ask: did you change anything in voyager vendor folder?

**Comment by nony22** [comment]
Thank you for your quick response . It was from my google chrome browser, with Mozilla is working perfectly. I will mark this as closed
