### ISSUE TITLE
Bread is not affected by database column name changes

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#4528]
Hello,

I am using the version 1.3.

I have created a database and columns. Upon adding the column names, I generated a BREAD. The problem is that some of my columns have a few spelling issues. I changed the column names again, updated the database but the BREAD still shows the old names.

How can I update the BREAD names as well please? If there is no automation in your script for this, where is the BREAD file saved per model please?

Thank you.

**Comment by Benoit1980** [comment]
Ok got it, you have to change the data in the database column "data_rows", am I correct?

Thank you.

**Comment by emptynick** [comment]
The issue template is required when opening new issues.
This can be reopened once all informations are provided.
