### ISSUE TITLE
Issues with caching menu/settings

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#4529]
Finding a couple of issues with caching inside voyager:

1. Settings: Voyager::setting('site.does-not-exists')
If you call setting for something that doesn't exists the whole settings get flushed. This can happen multiple times on the same request. This is the problem code causing it:
```
if ($globalCache) {
	// A key is requested that is not in the cache
	// this is a good opportunity to update all keys
	// albeit not strictly necessary
	Cache::tags('settings')->flush();
}
```

2. Menu display. 
- caching is never a hit when the menu doesn't exists and null it returned due to how the [remember method](https://github.com/laravel/framework/blob/6.x/src/Illuminate/Cache/Repository.php#L379)

Doing it manually worked using has() but couldn't eager load the menu items. 
```
if (\Cache::has($cacheName)) {
	$menu = \Cache::get($cacheName);
} else {
	$menu = static::where('name', '=', $menuName)->first();
	\Cache::put($cacheName, $menu, $cacheTime);
}
```

**Comment by emptynick** [comment]
The issue template is required when opening new issues.
This can be reopened once all informations are provided.
