### ISSUE TITLE
Issue with caching setting that doesn't exist

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#4530]
## Version information

 - Laravel: v6.4.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: Mysql 10.4.5-MariaDB

## Description
If you call Voyager::setting('site.does-not-exists') for something that doesn't exists the whole settings get flushed. 

This can happen multiple times on the same request. 

## Steps To Reproduce
1. Add Voyager::setting('site.does-not-exists')

## Expected behavior
Check settings once - save false cache. 

## Additional context
This is the problem code causing it:
```
if ($globalCache) {
	// A key is requested that is not in the cache
	// this is a good opportunity to update all keys
	// albeit not strictly necessary
	Cache::tags('settings')->flush();
}
```

**Comment by fletch3555** [comment]
Given the comment you included in your snippet, it looks like it's behaving as expected.  Why is this an issue? Sounds like you should just add the missing setting, or change the code that's looking for the missing one.

**Comment by emptynick** [comment]
There's a condition checking if `setting_cache` is null, and it's not nulled at any point.
So `flush` will only be called once per request.
I just checked it by adding a `debug('Settings-cache flushed')` below `Cache::tags('settings')->flush();`
and called a non-existing setting.
