### ISSUE TITLE
BREAD relationships not working when using custom named primary keys

### ISSUE THREAD

**Issue by parg0** [thedevdojo/voyager#4532]
## Version information

 - Laravel: v5.6
 - Voyager: v1.3
 - PHP: 7.2.23
 - Database: MariaDB 10.4.8

## Description

Relationships not working when using custom named primary keys in tables.

## Steps To Reproduce
1. Create 2 tables: 'venues' (with 'venue_id' as primary key), 'users_venues' pivot table (user_id, venue_id)  
2. Set venue_id as protected $primaryKey in App\Venue model
3. Create BREAD for 'users' table: Belongs to many 'venues', and set 'users_venues' as pivot table
4. Visit Users page where you can find the SQL error from the malformed query:

select venues.*, users_venues.user_id as pivot_user_id, users_venues.**venue_venue_id** as **pivot_venue_venue_id** from venues inner join users_venues on venues.venue_id = users_venues.**venue_venue_id** where users_venues.user_id = 1

## Expected behavior
Following query should be generated:
select venues.*, users_venues.user_id as pivot_user_id, users_venues.**venue_id** as **pivot_venue_id** from venues inner join users_venues on venues.venue_id = users_venues.**venue_id** where users_venues.user_id = 1

**Comment by MrCrayon** [comment]
I don't think it can be considered a bug more like a feature request.

I explain, you are using everything non standard:

- primary key non standard, it should be _id_ (Voyager can manage that)
- pivot table non standard, it should be _user_venue_ (Voyager can manage that)
- key in the pivot table not standard, they should be venue_venue_id and user_user_id (but judging by the query I think you are using id for users as primary key). (Voyager can't manage that)

There is an option to manage non standard primary keys and pivot table when you create relationship but no option to select non standard keys in the pivot table, so you can't really expect it to work.

**Comment by parg0** [comment]
I see. Thanks for clarifying this. But I think that you are wrong on one account, I am looking at the default voyager setup of tables _users_ and _rolls_. The pivot table '_user_roles_' there is using 'user_id' and 'role_id' as a key, not _**user_user_id**_ & _**role_role_id**_. 

And once the pivot table is renamed per convention to _singular_plural_ and the primary keys of the master tables are named _id_, the relationship works as intended. 

Just dropping this here for history purposes.

**Comment by MrCrayon** [comment]
I refer to Laravel standards https://laravel.com/docs/6.x/eloquent, Voyager is developed using Laravel but might have in the past not followed completely Laravel standards.

That Voyager pivot table is not standard, it should have been _role_user_: singular in alphabetical order.

Standard keys in pivot tables are: ```$singular_name_of_table.'_'.$primary_key```
The primary key in _users_ is _id_ that makes _user_id_ the standard key for pivot table.

If your primary key in _users_ is _user_id_ the standard key in pivot table is _user_user_id_.

Hope this clarify :grin:
