### ISSUE TITLE
Form Fields conditions

### ISSUE THREAD

**Issue by Benoit1980** [thedevdojo/voyager#4533]
Hello,

My apology if this is already part of Voyager 1.3, but I cannot find it.
Most people when creating CRUD forms like to have for example a form with:

Do you speak another language?
['YES', 'NO']

If 'YES' is select, then show another field with:
Please input the names of the languages you know.

I looked in your docs but cannot find anything related to input form fields conditions.

Thank you.

**Comment by MrCrayon** [comment]
There is not such feature.
You can easily implement it extending edit-add template and adding the JavaScript magic part.

**Comment by Benoit1980** [comment]
Thanks, I was hoping there was a setting that enables me to do it from your framework directly.
I will have to check how to edit the views.

Thanks again.

**Comment by emptynick** [comment]
Also as in your other issue, please use the issue template.

**Comment by Benoit1980** [comment]
> Also as in your other issue, please use the issue template.

I am not sure what you mean by that sorry. Could you please elaborate. Thank you

**Comment by MrCrayon** [comment]
@FreddyCrugger when you open an issue there are things written, you need to read that and fill data requested.

**Comment by Benoit1980** [comment]
> @FreddyCrugger when you open an issue there are things written, you need to read that and fill data requested.

Thanks for your help.(Merci Monsieurs Crayon :-))
