### ISSUE TITLE
Laravel Voyager Date: Not Showing

### ISSUE THREAD

**Issue by rsecor** [thedevdojo/voyager#4534]
## Version information

 - Laravel: v6.4.1
 - Voyager: v1.3.0
 - PHP: 7.3.11
 - Database: mysql  Ver 15.1 Distrib 10.3.18-MariaDB

## Description
Date is being treated as DateTime in Edit screens but correctly in List screens.

## Steps To Reproduce
See images for details.

## Expected behavior
I expect that "date" be treated differently from "datetime" where "date" should only be the Year, Month, and Day, while "datetime" would be everything in "date" plus time "time".

## Screenshots
Database Fields showing them defined as "Date" 1
Example Record from list view showing dates correctly 2
Same Example Record from 2 in Edit mode showing the dates missing from the input boxes 3
Same Example Record from 2 in Edit mode with a calendar showing after clicking into the input box 4

## Additional context
<img width="996" alt="Screen Shot 2019-11-03 at 11 07 47" src="https://user-images.githubusercontent.com/5085240/68088420-1a50d800-fe2d-11e9-9d5c-8ccc227c5aa8.png">
<img width="286" alt="Screen Shot 2019-11-03 at 11 06 52" src="https://user-images.githubusercontent.com/5085240/68088421-1a50d800-fe2d-11e9-940e-3b854e0aacee.png">
<img width="224" alt="Screen Shot 2019-11-03 at 11 06 39" src="https://user-images.githubusercontent.com/5085240/68088422-1a50d800-fe2d-11e9-8b0a-4f69d7d1eb72.png">
<img width="172" alt="Screen Shot 2019-11-03 at 11 06 23" src="https://user-images.githubusercontent.com/5085240/68088423-1a50d800-fe2d-11e9-9c47-cc8409631bc7.png">

**Comment by MrCrayon** [comment]
~~Maybe you missed to set field as Date in BREAD configuration, how is your BREAD configuration?~~

Are you using an accessor to format date?
Try to remove it and see if the problem persists.

In order for ```<input type="date" value="">``` to work value needs to be properly formatted, if you change that it's not going to recognize it.

You can set date format in BREAD details field or you can use an accessor only for browse view, both methods are explained in Voyager documentation.

**Comment by rsecor** [comment]
Either you are not understanding me or I am not understanding you.

In "default" Voyager, with no changes made to anything, I have 2 separate "date" fields, defined as date both in Voyager and in the database, that show up fine everywhere, including when only viewing a record through Voyager, but NOT when editing an individual record through Voyager.

In looking at the source on the record edit page it does show it as both a "date" type field and a value from the database:
```
 <div class="form-group  col-md-12 " >
   <label class="control-label" for="name">Date Start</label>
   <input type="date" class="form-control" name="date_start" placeholder="Date Start" value="2019-06-01">
</div>
```

**Comment by MrCrayon** [comment]
The only way I can reproduce what you see is if I select Timestamp in BREAD configuration.
Please notice is BREAD configuration that defines how data is shown not database configuration.

Can you check?

![Schermata da 2019-11-05 03-04-45](https://user-images.githubusercontent.com/6875243/68172787-22b62980-ff79-11e9-985f-90d519f77c8f.png)

**Comment by rsecor** [comment]
The fields are both "date" and "Date"!

<img width="514" alt="Screen Shot 2019-11-14 at 09 03 39" src="https://user-images.githubusercontent.com/5085240/68863616-bb595180-06bd-11ea-837e-e6719bc1545c.png">

**Comment by rsecor** [comment]
Every "date"/"Date" field there is in the install has the same issue.

**Comment by MrCrayon** [comment]
Are you using Safari?

**Comment by rsecor** [comment]
I take it there is an issue with Safari then.
Any other browsers that this does not work on?

**Comment by MrCrayon** [comment]
The issue with Safari is that it doesn't support `type="date"` yet, so a jQuery plugin is used instead https://github.com/the-control-group/voyager/blob/170eead9565e4af7f00086b3d98ac4073faad448/resources/views/bread/edit-add.blade.php#L172

That plugin is initialized the same as when you have timestamp so it shows also time, that can be changed but even in the plugin site `date` only doesn't work (it doesn't open anything for me).
https://eonasdan.github.io/bootstrap-datetimepicker/

So until we find a solution can't be fixed.

**Comment by MrCrayon** [comment]
@rsecor #4566 should fix your problem.
Keep in mind that while using datetimepicker for now you'll always get date as MM/DD/YYYY.
