### ISSUE TITLE
When trying to Add or Edit Posts getting infinite loading screen

### ISSUE THREAD

**Issue by Kukiezi** [thedevdojo/voyager#4537]
## Version information
 - Laravel: v6.4.1
 - Voyager: v1.3
 - PHP: 7.3
 - Database: PSQL 10.7## Description

After fresh installation of voyager with dummy data when I try to edit a Post or Add a new post I get loading screen and nothing more happens. Waited like 10 minutes and nothing loaded.

## Steps To Reproduce
1. Go to 'Admin Dashboard'
2. Click on 'Posts in left menu'
3. Click on  'Add New'
4. See loading screen forever

**Comment by fletch3555** [comment]
Did you check your browser console? Most likely you have a javascript error there

**Comment by Kukiezi** [comment]
Unfortunately no error to be seen which is even weirder for me. All other BREADS are working fine.

**Comment by MrCrayon** [comment]
Can you post a screenshot of your browse Console tab?
Also check Network tab if there is any 404 error and what's the response to the /admin/posts request.

**Comment by Kukiezi** [comment]
There is no error in network tab. Just infinite load time when trying to edit or add a post. 

To url http://streambuddy.test/admin/posts/1/edit response is:
![image](https://user-images.githubusercontent.com/32630534/68206705-b44f8680-ffcd-11e9-85d0-0ca9cede8fa4.png)

So seems like it returns the needed html, but preview is:
![image](https://user-images.githubusercontent.com/32630534/68206735-cb8e7400-ffcd-11e9-8410-ccafff3a286d.png)

The same thing for editing the post. No 404 or any other errors in console/network tab.

**Comment by MrCrayon** [comment]
There must be an error for app.js or another javascript, I can see font is not shown in breadcrumb either, I have no other explanation.

**Comment by Kukiezi** [comment]
I went to repo and copied file 'resources/views/posts/eddit-add.blade.php'. Switched it with mine and now it works. Well that was unexpected but now it works correctly. I wonder if I changed something earlier or just a weird bug. Anyway it is fixed now. thanks for trying to help!

**Comment by emptynick** [comment]
I think we can close this then.
