### ISSUE TITLE
[help:] Muliple Images Upload

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#454]
The image data_type is good but how can I modify multiple images upload?
In some scenarios user can upload more than one image. Imagine image Galleries. That should store image as array of string, is that right? Is there any method by default or should I override the View & Controller?

Thanks,

**Comment by sarath-c-sandwich** [comment]
The only way right now is override the view.

**Comment by marktopper** [comment]
How would you store the multiple images?

**Comment by TnCoders** [comment]
i think using a pivot table no ?

**Comment by sarath-c-sandwich** [comment]
I tried with different ways but that did not work well. I always upgrade to latest version on each release, so I don't want to customize the core one. Is there any suggestion?

**Comment by marktopper** [comment]
I think this should be a new field type that could be build into the core of Voyager.

**Comment by sarath-c-sandwich** [comment]
@marktopper is this new field type already added to the core of Voyager?

**Comment by davodavodavo3** [comment]
maybe close this enhancement, we have multyple images field
