### ISSUE TITLE
SoftDeletes Restore button conditional on browse view no longer per-row

### ISSUE THREAD

**Issue by mattrabe** [thedevdojo/voyager#4540]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.3.0
 - PHP: 7.2.8
 - Database: MySQL

## Description

Restore button does not show correctly on Browse view for SoftDeletes models. Conditional for whether Restore button shows is based only the the first row, and is applied to all rows (instead of checking per-row). Easily explained by a code change (detailed below)

## Steps To Reproduce
1. Create a SoftDeletes model, add at least 3 rows to the model
1. Go to Browse view for that model
1. Delete the SECOND row
1. Click "Show Deleted" toggle so that you are viewing soft-deleted records
1. **Observe that Restore button does NOT show for any row**
1. Now delete the FIRST row.
1. Click "Show Deleted" toggle so that you are viewing soft-deleted records
1. **Observe that Restore button shows to ALL rows, even though only the first 2 were deleted**

## Expected behavior

Restore button should only show for rows with a non-null `deleted_at`, Delete button should show for the inverse.

## Additional context

This appears to have been caused by moving `shouldActionDisplayOnDataType` in 3b461e9f2d7f4821fcbb020aaaa72a5ccbd6d858. When that function was running in the view partial, it was called for each row, but now in the Controller it is called only once for the whole model, and `$dataTypeContent->first()` is explicitly passed. RestoreAction depends on being able to check for `$this->data->deleted_at` per row: https://github.com/the-control-group/voyager/blob/1.3/src/Actions/RestoreAction.php

If we want to run this in the Controller (which seems sensible for more than one reason), we may need to pass the $actions result as a "row" on $dataTypeContent.

I'd be glad to make a patch for this since it will very soon affect a client project-in-progress, but would love to hear from @MrCrayon since he created pull request #4151 which includes the above commit, as well as @emptynick @fletch3555 . Any initial thoughts on my suggested approach or approach in general?

**Comment by MrCrayon** [comment]
I'll check better tomorrow but I think the problem is that shouldActionDisplayOnDataType method should not contain a check on data about the single record, that should go in the policy check:
https://github.com/the-control-group/voyager/blob/ef38774d927103975583f86d2d1a41ab2289a34d/src/Actions/RestoreAction.php#L39

If we change that everything else can stay as it is, I think.

**Comment by MrCrayon** [comment]
Hey @mattrabe any news on this?
I stand by my view that `shouldActionDisplayOnDataType` should contain only checks on DataType, as the name suggests.
I have a couple of ideas on how to solve it but I was under the impression you were working on it.

I could propose a PR if you didn't work on it yet or have a look at your solution.

**Comment by mattrabe** [comment]
@MrCrayon Thanks for the ping. I agree with your assessment and appreciate the input. I have not started to work on a fix for this. This *will* affect a currently-under-dev client project for me, so it will become critical, but we are currently pre-production so just have been working on other features.
