### ISSUE TITLE
I want to call actions buttons with Ajax call

### ISSUE THREAD

**Issue by ikramulmustafa** [thedevdojo/voyager#4548]
## Version information

 - Laravel: v6.0
 - Voyager: v1.3
 - PHP: 7.2
 - Database: aurora-Mysql 5.6

## Description

i want to append actions of the specific model by ajax call?
How can i do that? anyone Help?

Actually I am trying to create datatable and then use filter and then append data base on filter through ajax call?
i want to append actions buttons also? can anyone help how to call them in js

**Comment by MrCrayon** [comment]
As it says in template while you are opening an issue
> IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST

We prefer to keep github issue for bug reports or feature requests.
