### ISSUE TITLE
Status 500 - removing uploaded file

### ISSUE THREAD

**Issue by livrosroberto** [thedevdojo/voyager#4549]
## Version information
 - Laravel: v6.5.0
 - Voyager: v1.3.0
 - PHP: 7.3.11
 - Database: MYSQL 15.1 10.4.8 MariaDB

## Description
I can't remove upload files while editing a bread. It's returning 500 status

I noticed 2 things: 

First: while images' paths are stored in database between brackets [path/to/image.jpg] files are stored between brackets and braces {[path/to/file.dpdf]}

The data-file-name html attribute is assign to original file name, but the files are stored with a automatically generated name.

## Steps To Reproduce
1. Create a database
2. Create a BREAD
3. Put a file field on BREAD
4. Create a register
5. Edit a register
6. Click on "X" mark to remove file

![voyager](https://user-images.githubusercontent.com/57421839/68491787-e6f5bb00-0229-11ea-98dd-3302ed42533a.PNG)

Thanks!

**Comment by MrCrayon** [comment]
Thank you for your report, when I introduced the removal of file from file system I only tested it with images.

You can try:
 ~https://github.com/MrCrayon/voyager/commit/7ecbfbe76824d65f4bbce5bd4977d93daaa65bda~

~I'd like to introduce some tests before I submit it as PR.~

PR #4550

**Comment by livrosroberto** [comment]
Thank you.
Your fix works just fine!

**Comment by mweikat** [comment]
Hi, I ran composer update but stiil get this error... 

composer.json:

"tcg/voyager": "v1.3.*"

Thanks for u reply

**Comment by MrCrayon** [comment]
@mweikat #4550 is not merged yet, and after that you'll have to wait next release unless you use dev branch.

**Comment by mweikat** [comment]
> @mweikat #4550 is not merged yet, and after that you'll have to wait next release unless you use dev branch.

Thanks for reply
