### ISSUE TITLE
Tinymce modify settings before initilized

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#4551]
## Version information
- Laravel: v6.4.0
- Voyager: v1.3.0
- PHP: 7.2
- Database: Mysql 10.4.5-MariaDB

## Description of problem
Tinymce is missing the paste plugin to clean this up automatically. For some reasons the HTML below completely breaks Laravel if it's echoed in blade. We have admin users who copy text from Word into the html editor.  

## Proposed solution
Understand that not everybody needs the paste plugin so we need a way of modifying tinymce options before it's initilized. The tinymce_setup_callback function is unable to add plugins after tinymce has been loaded. 

I've [seen examples](https://github.com/the-control-group/voyager/issues/1945#issuecomment-415986744) where you can completely remove the editor and re-initialise it but this is not ideal because tinymce is already slow enough loading once. 

## Additional context
```html
<p><!-- [if gte mso 9]><xml>
 <w:LatentStyles DefLockedState="false" DefUnhideWhenUsed="true"
  DefSemiHidden="true" DefQFormat="false" DefPriority="99"
  LatentStyleCount="276">
  <w:LsdException Locked="false" Priority="72" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful List Accent 5"/>
  <w:LsdException Locked="false" Priority="73" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Grid Accent 5"/>
  <w:LsdException Locked="false" Priority="60" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="61" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light List Accent 6"/>
  <w:LsdException Locked="false" Priority="62" SemiHidden="false"
   UnhideWhenUsed="false" Name="Light Grid Accent 6"/>
  <w:LsdException Locked="false" Priority="63" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Shading 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="64" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Shading 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="65" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium List 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="66" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium List 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="67" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 1 Accent 6"/>
  <w:LsdException Locked="false" Priority="68" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 2 Accent 6"/>
  <w:LsdException Locked="false" Priority="69" SemiHidden="false"
   UnhideWhenUsed="false" Name="Medium Grid 3 Accent 6"/>
  <w:LsdException Locked="false" Priority="70" SemiHidden="false"
   UnhideWhenUsed="false" Name="Dark List Accent 6"/>
  <w:LsdException Locked="false" Priority="71" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Shading Accent 6"/>
  <w:LsdException Locked="false" Priority="72" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful List Accent 6"/>
  <w:LsdException Locked="false" Priority="73" SemiHidden="false"
   UnhideWhenUsed="false" Name="Colorful Grid Accent 6"/>
 </w:LatentStyles>
</xml><![endif]--></p>
<p class="MsoNormal">Text copied from MS Word with hidden code causing a white page in Laravel.&nbsp;</p>
```

**Comment by MrCrayon** [comment]
You can use:
```javascript
function tinymce_init_callback(editor)
{
  editor.remove();
  editor = null;

  tinymce.init({
//your configuration
  });
}
```

**Comment by MrCrayon** [comment]
I didn't notice at first that you were already aware of that solution, I don't know of any other way that this can be done but I also didn't investigate too much.
If you find a solution let us know.

I think for now, if you don't want to use the callback, the only way you can solve is:

- fork voyager
- edit voyager_tinymce.js
- recompile assets
- use the new app.js in your app

You can do that by overriding VoyagerController@assets or changing it in the route.

**Comment by howdu** [comment]
@MrCrayon cheers yeah I didn't like that way and no way of adding plugins easily. 

Not sure why there's a jquery csrf-token shouldn't really be in the tinymce js file. 
https://github.com/the-control-group/voyager/blob/1.3/resources/assets/js/voyager_tinymce.js#L14

I forked the repo, removing tinymce and reduced app.js from 2.2MB to 1.5MB. 
Then installed tinymce 4.9.6 so I can have full control over the plugins by compiling it myself into a separate file. 

Simple added tinymce to the top and few changes.
```
import tinymce from 'tinymce/tinymce';

// Theme
import 'tinymce/themes/modern/theme';

// Plugins
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/code';
import 'tinymce/plugins/table';
import 'tinymce/plugins/textcolor';
import 'tinymce/plugins/lists';
import 'tinymce/plugins/paste';

window.tinymceDefaults = {
  menubar: false,
  selector:'textarea.richTextBox',
  skin_url: $('meta[name="assets-path"]').attr('content')+'?path=js/skins/voyager',
  min_height: 600,
  resize: 'vertical',
  plugins: 'link, image, code, table, textcolor, lists, paste',
  extended_valid_elements : 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
  file_browser_callback: function(field_name, url, type, win) {
    if(type =='image'){
      $('#upload_file').trigger('click');
    }
  },
  toolbar: 'styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table | code',
  convert_urls: false,
  image_caption: true,
  image_title: true,
  init_instance_callback: function (editor) {
    if (typeof tinymce_init_callback !== "undefined") {
      tinymce_init_callback(editor);
    }
  },
  setup: function (editor) {
    if (typeof tinymce_setup_callback !== "undefined") {
      tinymce_setup_callback(editor);
    }
  }
};

$(document).ready(function(){

  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
  });
});

```
resources/views/vendor/voyager/formfields/rich_text_box.blade.php
```
<textarea class="form-control richTextBox" name="{{ $row->field }}" id="richtext{{ $row->field }}">
    {{ old($row->field, $dataTypeContent->{$row->field} ?? '') }}
</textarea>
@section('tinymce_init')
<script type="text/javascript">
$(document).ready(function() {
  tinymce.init($.extend({}, window.tinymceDefaults,  {
    selector: 'textarea.richTextBox'
  }));
});
</script>
@endsection
```

resources/views/vendor/voyager/master.blade.php
```
@hasSection('tinymce_init')
    <script type="text/javascript" src="{{ asset(mix('js/voyager_tinymce.js'')) }}"></script>
    @yield('tinymce_init')
@endif
```

**Comment by mgevorg** [comment]
> ## Version information
> * Laravel: v6.4.0
> * Voyager: v1.3.0
> * PHP: 7.2
> * Database: Mysql 10.4.5-MariaDB
> 
> ## Description of problem
> Tinymce is missing the paste plugin to clean this up automatically. For some reasons the HTML below completely breaks Laravel if it's echoed in blade. We have admin users who copy text from Word into the html editor.
> 
> ## Proposed solution
> Understand that not everybody needs the paste plugin so we need a way of modifying tinymce options before it's initilized. The tinymce_setup_callback function is unable to add plugins after tinymce has been loaded.
> 
> I've [seen examples](https://github.com/the-control-group/voyager/issues/1945#issuecomment-415986744) where you can completely remove the editor and re-initialise it but this is not ideal because tinymce is already slow enough loading once.
> 
> ## Additional context
> ```
> <p></p>
> <p class="MsoNormal">Text copied from MS Word with hidden code causing a white page in Laravel.&nbsp;</p>
> ```
I have some problem(Tinymce is missing the paste plugin to clean this up automatically. For some reasons the HTML below completely breaks Laravel if it's echoed in blade. We have admin users who copy text from Word into the html editor.), could you help me to modify tinymce(not for free)?

**Comment by MrCrayon** [comment]
@howdu you might be interested in this PR #4727 

Please leave a review if you test it.
