### ISSUE TITLE
translation in voyager

### ISSUE THREAD

**Issue by mhd-yasser-haddad** [thedevdojo/voyager#4554]
- Laravel: v6.2
 - Voyager: v1.3
 - PHP: 7.2
 - Database: MySQL

## Description of problem
I am trying to translate the bread for a table in my database I already translated the title of the columns in the bread editor(from the tools) but when I am opening the bread page (that is related to that table) the radio button is showing two languages but it is not changing the language when I click on it, what can I do so that I can change the column names to the language??

## Proposed solution
I edited the bread and translated the columns in the display name field

## Additional context
https://drive.google.com/open?id=1yDfq-_Ox2lK1pAex2l0EuhKtVXDH4cxturl
![Capture](https://user-images.githubusercontent.com/44609144/68595780-cf753700-04a2-11ea-9500-7bfad882c5ef.PNG)

like in the photo above (the link) when I click on the AR the start time and the endTime won't translat the arabic language That is the thing that I am trying to do.

**Comment by MrCrayon** [comment]
You can drag and drop the picture to attach it here.

I'm not sure I understand your problem, I can't see the picture, but can you try to change the language in your profile settings and check if you see the right translation?

**Comment by mhd-yasser-haddad** [comment]
@MrCrayon I just edited the post and attached a picture
when I am changing the language from the user profile every thing is translated perfectly but this button isn't working in both languages 
I mean when the locale is Arabic this button isn't changing the language or the table fields to English, and when the locale is English the button won't change the language to Arabic.
Can I make this button translate the title and the name of the fields in the the table??

**Comment by MrCrayon** [comment]
That button it's only for choosing which language you are using to enter your translations it's not meant to switch global language as far as I know.

**Comment by MrCrayon** [comment]
You can implement a button that updates language set in user table and refresh the page.

**Comment by mhd-yasser-haddad** [comment]
@MrCrayon 
you mean that this button can't change the main titles of the page???
only the content of the table?

**Comment by MrCrayon** [comment]
Yes, if you want everything translated you need to change the language the platform is displayed for and that's the language in user settings.

As you can see when you use that button menu don't change, and also button labels don't change.

**Comment by mhd-yasser-haddad** [comment]
@MrCrayon 
Thank you for your help.
