### ISSUE TITLE
Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by projectneokevin** [thedevdojo/voyager#4556]
## Version information

 - Laravel: v6.0
 - Voyager: v1.3
 - PHP: 7.2.19
 - Database: MySQL 5.7

## Description

I have tried to create a new project and then install Voyager, and so far it has not presented any errors during the installation, but when everything is finished, I enter compass and I get that error.

ErrorException
Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP)
http: //voyager.test/admin/compass

## Screenshots
![image](https://user-images.githubusercontent.com/32402277/68628635-c4240a80-04a6-11ea-940d-1ea38b7d8bc7.png)
 
Thanks!!!

**Comment by MrCrayon** [comment]
You get that error just going to compass page?

**Comment by MrCrayon** [comment]
It would be also useful to see where exactly the error is happening, is it here?
Line 101 of `Symfony/Component/Console/Terminal.php`?

Are you using Windows 10?

**Comment by projectneokevin** [comment]
Just following the tests, when I create a new table in the database, and select the option that will create the model, create the table but not the model and I get an error:

Exception: Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP).

Then it redirects to the same page of creation of the table, but the table has already been created in the database, and if you try to create it it shows an error indicating that the table already exists.

And yes, I use Windows 10.

![error modelo](https://user-images.githubusercontent.com/32402277/68696066-e5860480-0541-11ea-957b-d79f0dcb638e.png)

**Comment by MrCrayon** [comment]
It's a bug in Symfony, needs to be fixed upstream. 
https://github.com/symfony/symfony/issues/34341

**Comment by joey2017** [comment]
it's not work for windows 10 but work well on linux(centos7) or mac os

**Comment by emptynick** [comment]
https://github.com/symfony/symfony/releases/tag/v4.3.8 has a fix merged.

**Comment by neapolis79** [comment]
just to confirm: i had the same problem after creation of a model from the compass tool. 
I launched a composer update and then sympfony was update to 4.3.8 that fixed for me the issue

**Comment by MrCrayon** [comment]
Since this was not a Voyager bug and has been fixed upstream we can close this.
