### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by mhd-yasser-haddad** [thedevdojo/voyager#4558]
- Laravel: v6.2
 - Voyager: v1.3
 - PHP: 7.2
 - Database: MySQL

## Description of problem
1- I want to change the filter fields and the filter operation in the search bar that the voyager provides.
what I want to do exactly is to control the fields that are shown in the chosing fields like in my example I have a lot of fields in this like (radacctid, username, locationID, startTine, endTime) and I only want the user to search for these fields(username, startTime, endTime) can anybody tell me how to hide the other fields from being searched for, I already did hide the other fields from (browse, update, edit) from the BREAD, what can I do to solve my problem? should override the view or there is another way?

2- And the searching option there is only (contain, =) is there any other way to edit these too?

3- Can I have the option to search for two fields at the same time??

## Proposed solution
As I typed above, I already did hide the other fields from (browse, update, edit) from the BREAD

## Additional context
here is a picture of the search bar and the
![123](https://user-images.githubusercontent.com/44609144/68691728-e38d6700-057c-11ea-9aa7-7da3fa3f89e3.PNG)
 fields that I want to change

**Comment by MrCrayon** [comment]
Voyager doesn't currently support such feature. 
The way you can do it is: 
- overriding browse template to manage what you see and index method to change how search is done. 
- use client side pagination and datatable

**Comment by mhd-yasser-haddad** [comment]
Thank you for your answer.
