### ISSUE TITLE
I can't filter results on Select2 

### ISSUE THREAD

**Issue by livrosroberto** [thedevdojo/voyager#4561]
## Version information
 - Laravel: v6.5.0
 - Voyager: v1.3.0
 - PHP: 7.3.11
 - Database: MYSQL 15.1 10.4.8 MariaDB

## Description
When trying to filter a select2 results I'm getting "the results could not be loaded". I have a custom attribute in my relationship which is a result of 2 collumns of my model. eg. "id - description".

If I remove my custom attribute on Bread relationship the select2 filter works just fine.

## Steps To Reproduce
1. Create a custom attribute on the model
eg. 
    public $additional_attributes = ['full_grupo_conta'];

    public function getFullGrupoContaAttribute()
    {
         return "{$this->grupo_razao} - {$this->descricao_grupo}";
    }

2. Create a relationship
3. Select the custom attribute on the relationship and save
4. Add new register on BREAD
5. Try to filter select2 results

![Capturar](https://user-images.githubusercontent.com/57421839/68879960-1f453f80-06e9-11ea-9046-7661e67f5871.PNG)

![Capturar2](https://user-images.githubusercontent.com/57421839/68880071-59aedc80-06e9-11ea-9635-7531877ea337.PNG)

![Capturar3](https://user-images.githubusercontent.com/57421839/68880074-5d426380-06e9-11ea-80a3-61d1bb5d75d7.PNG)

Thanks!

**Comment by MrCrayon** [comment]
It should be fixed in #4562
