### ISSUE TITLE
Soft Delete: Restore button disapear when browse multiple page data

### ISSUE THREAD

**Issue by adiavt** [thedevdojo/voyager#4564]
## Version information

 - Laravel: v5.8.35
 - Voyager: v^1.2
 - PHP: 7.3.9
 - Database: mysql  Ver 15.1 Distrib 10.4.6-MariaDB

## Description
I have a bunch of data, when i browse that data, it shows pagination and when i tried to show the deleted data, the "restore" button disapear, i can't restore my deleted data.

## Steps To Reproduce
1. Go to Browse my data that using "soft deleted", for example: "categories"
2. Click on "Show Deleted"
3. The data that have been deleted did not include "Restore" action button

## Expected behavior
The data that have been deleted should come with "Restore" action in each row so i can restore my deleted data.

## Screenshots
This is the my data that have been deleted, and showing when i click the "Show Deleted" button.
![image](https://user-images.githubusercontent.com/55221140/68926184-db713980-07bf-11ea-9a74-7e9892f798a6.png)

## Additional context
I have added checking to distinguish the data that have been deleted do not mix with all the data that haven't deleted yet. So when i click "Show Deleted" only the deleted data showing as expected. Then the problem is the data does not include the "Restore" action only show the regular action like "View", "Edit" and "Delete"

**Comment by MrCrayon** [comment]
This is probably a duplicate of #4540  
You can try if #4563 solves the problem.

**Comment by MrCrayon** [comment]
@adiavatarsolution did you try with #4563 ?

**Comment by MrCrayon** [comment]
This issue is probably a duplicate and already solved and since we didn't receive any feedback I'm closing this one.

If you are still having this problem after update please open another issue.
