### ISSUE TITLE
These credentials do not match our records cant login with account default

### ISSUE THREAD

**Issue by trunganhvu** [thedevdojo/voyager#4567]
## Version information

 - Laravel: v6.5.0
 - Voyager: v 1,3
 - PHP: 7.3.11 
 - Database: Ver 14.14 Distrib 5.7.27

## Description

i follower https://www.itsolutionstuff.com/post/laravel-5-create-quick-backend-admin-panel-tutorialexample.html but last step is login is fail 

## Steps To Reproduce
1. Go to my project
2. Click on teminal php artisan migrate, composer require tcg/voyager, php artisan voyager:install --with-dummy
3. Scroll down to of couse localhost run but i used admin@admin.com / password 
4. See error These credentials do not match our records.

## Screenshots
![Screenshot from 2019-11-18 12-18-27](https://user-images.githubusercontent.com/37219817/69026477-95a1b480-09fd-11ea-872c-c14631065eda.png)

**Comment by MrCrayon** [comment]
I hardly doubt it's Voyager bug, why did you follow a three years old post instead of official documentation?

Anyway check in your database and if there is no  admin@admin.com user create it again:
https://voyager-docs.devdojo.com/getting-started/installation

If there is, remove it and create it.

**Comment by emptynick** [comment]
Looks like you already have users in your table.

>NOTE: Please note that a dummy user is only created if there are no current users in your database.

**Comment by MrCrayon** [comment]
@trunganhvu did you already have users as @emptynick suggested?
