### ISSUE TITLE
SECURITY: Unauthenticated Path Traversal

### ISSUE THREAD

**Issue by lanhhuyet510** [thedevdojo/voyager#4568]
## Version information

Laravel: 5.8
Voyager: 1.3, 1.2, 1.1, 1.x, 2.x
Php: 7.1.3
Mysql: 10.1.40

## Description

This vulnerability can give to anyone power of download every file in the system without authentication. This means, .env file of your application will be exposed for everyone.

## Steps To Reproduce

[[Redacted]]

## Additional context

Fixed in pull #4569

**Comment by emptynick** [comment]
I just edited your issue so it's not visible to everyone.
The next time please get in touch through email or slack and let us know in private.

**Comment by lanhhuyet510** [comment]
> I just edited your issue so it's not visible to everyone.
> The next time please get in touch through email or slack and let us know in private.

I've tried to contact via your homepage contact but didn't receive any response. 
Noted that and next time for new issues I will report through email or slack.
