### ISSUE TITLE
Media Directories & Files MisMatchToken exception

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#457]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.11
- PHP Version:
- Database Driver & Version:

### Description:
 500 Request Error on 
+ admin/media/directories
+ admin/media/files

What's wrong with these? Is that permission of directories or what?

![screenshot 270](https://cloud.githubusercontent.com/assets/1330852/21535923/70a0dcb2-cdae-11e6-8401-cccaaaece140.png)

**Comment by sarath-c-sandwich** [comment]
Problem might caused from CSRF middleware, it's throw MisMatchToken exception.

**Comment by sarath-c-sandwich** [comment]
Even in the Local does not work. I am using Window 10, Wamp Server. I logged in as the Administrator.

Is it the problem of Symlink() or permission access on the MediaController?

**Comment by marktopper** [comment]
Please open the requests that gives status code 500 and see what the response is.
Also turn on debugging first for better support.

**Comment by sarath-c-sandwich** [comment]
@marktopper 

1. I put those URI to the exception in VerifyCsrftToken Middleware, then it work properly well. But I don't feel secure when I do that.
2. In MenuBuilder also have problem with CsrfToken to verify.

It works well when I added to exception

<img width="702" alt="screen shot 2017-01-31 at 3 32 34 pm" src="https://cloud.githubusercontent.com/assets/1330852/22457665/42d97046-e7cb-11e6-8586-b984f9a6791a.png">

**Comment by marktopper** [comment]
That should not really be a issue any more when it comes to the menu builder do to [this line](https://github.com/the-control-group/voyager/blob/master/resources/views/menus/builder.blade.php#L189).

Is it possible you could try get the `dev-master` version and test that out?

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue following the 1.0 release, please open a new issue.
