### ISSUE TITLE
On update a relations, data  not save

### ISSUE THREAD

**Issue by golbanstefan** [thedevdojo/voyager#4572]
## Version information

 - Laravel: v6.0.1
 - Voyager: v1.3
 - PHP: 7.2
 - Database: MySQL

## Description

On update a relations, data not save,
all BREADS don't  save data on update, 2 projects same problem.

## Steps To Reproduce
See images for details.

## Screenshots
![gitlab_report_voyager](https://user-images.githubusercontent.com/37143621/69241507-9e35ee80-0ba7-11ea-87e0-6889ad0989b0.png)
![voyager2](https://user-images.githubusercontent.com/37143621/69241599-c9b8d900-0ba7-11ea-952b-d95a28065f7d.png)
On update I select GOLBAN STEFAN
![voyager3](https://user-images.githubusercontent.com/37143621/69241896-67aca380-0ba8-11ea-97aa-2251ace53e88.png)
After save get null
![voyager4](https://user-images.githubusercontent.com/37143621/69241901-69766700-0ba8-11ea-812b-40bed4212259.png)

## Additional context
I changed `public function insertUpdateData` method 
was : 
```php  // Value is saved from $row->details->column row
            if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                continue;
            } 
```
now:
```php  // Value is saved from $row->details->column row
            if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
                $data->{$row->details->column}=$request->get($row->field);
                continue;
            }
```
# Thank you very much for the work you do for the community

**Comment by MrCrayon** [comment]
You are not telling us when you started having the problem, so I'll try to read your mind let's see if I can get it right :grin: 

- You started having the problem after update from v1.2.7 to v1.3.0
- you don't have edit checked for resident_id OR you have a custom relationship view

**Solution:**
check edit for resident_id
AND
update your custom relationship view, if you have it, and apply this change #4439

You should also revert any change you did in vendor.

If I didn't get it right you'll have to give us more informations.

**Comment by golbanstefan** [comment]
![voyage5](https://user-images.githubusercontent.com/37143621/69260726-05b06600-0bc9-11ea-82b8-a6cd502c8166.png)
All is checked, I think the problem start on update, before update everything worked fine.
If need other information I will give.
Thanks in advance

**Comment by MrCrayon** [comment]
As mentioned in my previous comment the usual three places where you can cause this problem are: 

- BREAD configuration
- Relationship view
- `insertUpdateData`

BREAD configuration looks ok, now you need to check the other two things.

Of course if you extedend or altered other files problem might be somewhere else.

**Comment by j3p0n** [comment]
i have some problems, new instalations of voyager 1.3.0

**Comment by j3p0n** [comment]
working now, thanks Mr. MrCrayon for help, make sure field is checked on EDIT or ADD
![Annotation 2019-11-22 012256](https://user-images.githubusercontent.com/13654041/69365436-e8fa5800-0cc6-11ea-8eaa-5c95bc9026c3.png)

**Comment by MrCrayon** [comment]
@golbanstefan did you solve the problem?

If not try to:

- remove `/vendor/tcg/voyager`
- run a `composer install` (to be sure you don't have any code changed in vendor)
- check you didn't override relationship view
- check you didn't override Controller insertUpdateData method
