### ISSUE TITLE
Menu item url translate

### ISSUE THREAD

**Issue by tufkan1** [thedevdojo/voyager#4575]
## Version information
 - Laravel: v5.8.*
 - Voyager: v1.3.*
 - PHP: 7.2
 - Database: [MySQL]

## Description of problem
Voyager Menu item translate url

**Comment by MrCrayon** [comment]
https://github.com/the-control-group/voyager/issues/4379

**Comment by tufkan1** [comment]
I'm not good at Laravel, Can you send me an example?

**Comment by MrCrayon** [comment]
Nobody is born good at Laravel :grin: , if you need this feature take the chance to improve your knowledge.
I don't have any example for this other than the advice I gave in the other issue. 
You can check how to extend a Voyager Model in Voyager documentation then you'll probably have to extend VoyagerBaseController so you can check slug in translations.

I didn't put much thought on this so I'm not sure this is the best way to do it but you can try. 

P. S. 
Keep in mind slugs and translations should stay unique, if you have many datatypes it would probably be better to append datatype id like: /admin/slug-12/edit/3
