### ISSUE TITLE
Error "Call to undefined method stdClass::getTranslatedAttribute()" when add field options with Hook Theme

### ISSUE THREAD

**Issue by d3turnes** [thedevdojo/voyager#4579]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.3.0
 - PHP: 7.1.30
 - Database: MySql 5.7.24

## Description

Hi, installed Hook Theme and add options 
Error "Call to undefined method stdClass::getTranslatedAttribute()"

## Steps To Reproduce
1. php artisan hook:install voyager-themes
2. Inside the resources/views/themes/my-theme/options.blade.php file you can now add a new field as simple as:
{!! theme_field('text', 'title') !!}
3. open route "admin/themes/options/my-theme"
4. See error:
Call to undefined method stdClass::getTranslatedAttribute() (View: E:\backup\projects\xampp\laragon\showcase\vendor\tcg\voyager\resources\views\formfields\text.blade.php) (View: E:\backup\projects\xampp\laragon\showcase\vendor\tcg\voyager\resources\views\formfields\text.blade.php) (View: E:\backup\projects\xampp\laragon\showcase\vendor\tcg\voyager\resources\views\formfields\text.blade.php)

**Comment by MrCrayon** [comment]
You should report it in [voyager-themes](https://github.com/thedevdojo/voyager-themes) repo, but I don't think it's mantained.

**Comment by d3turnes** [comment]
[It's works for me](https://github.com/pinocks/voyager-themes/pull/1/commits/901529c1097ef342cf555f40ec73e0be22403fef)

ok from > v1.2.6 laravel-voyager

**Comment by MrCrayon** [comment]
@d3turnes if you tested and it works you can try opening a PR in the proper repository.
