### ISSUE TITLE
docs / configuration

### ISSUE THREAD

**Issue by kobius77** [thedevdojo/voyager#458]
https://the-control-group.github.io/voyager/docs/v0.10/#getting-started-configuration

says

> With a new install of voyager you will have a new configuration file located inside at **config/app.php**

where it probably should say **config/voyager.php**

**Comment by sarath-c-sandwich** [comment]
Did you run this command to force Voyager publishing the configuration file?

If you migrate from 0.9 to 0.10 run this command
`php artisan vendor:publish --provider="TCG\Voyager\VoyagerServiceProvider" --force`

Or if you are fresh install run this command
`php artisan vendor:publish --tag=voyager_assets --force`

**Comment by kobius77** [comment]
this is just an issue in the docs - everything working fine.

please read again - it's about the sentence quoted.. ;)

**Comment by fletch3555** [comment]
@drahdiwaberl, if you'd like to open a PR for this, I'm more than happy to let you have credit for the commit!

**Comment by kobius77** [comment]
thanks for the heads up @fletch3555, didn't realize the docs were in the repo either..

still new to all this git-stuff.. forked, edited, commited in my fork - but how to create a PR over here now? when i click "new PR" i can only compare.. :(

that's my commit fwiw: e86daef23dd405af1efd7e2e332c785c4d720855

**Comment by kobius77** [comment]
ok.. got it.. kind of.. ;)

**Comment by fletch3555** [comment]
Perfect, thanks!  It's been merged
