### ISSUE TITLE
User Activity Log is not available in voyager

### ISSUE THREAD

**Issue by shazimali** [thedevdojo/voyager#4581]
i need to get logged in user activity log in laravel voyager

**Comment by MrCrayon** [comment]
Voyager dispatches an Event everytime you do something, you can listen at them and log user activity.
https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/src/Http/Controllers/VoyagerBaseController.php#L408

**Comment by fletch3555** [comment]
As @MrCrayon said, we provide events you can listen to if you need this functionality.  We don't currently have any plans to add such a feature into Voyager directly.

**Comment by shazimali** [comment]
@fletch3555  thanks for suggestion.
