### ISSUE TITLE
Custom multiple select field with REST API data overrides default multiple select field

### ISSUE THREAD

**Issue by G00sfraba** [thedevdojo/voyager#4585]
## Version information
 - Laravel: v5.7.*
 - Voyager: v1.1.12
 - PHP:  7.2.20
 - Database: 10.1.43-MariaDB

## Description:
This will need some side info in order to explain my problem in detail, so please bare with me :)

I want to create a custom multiple select field with data coming from REST API. SO:

First: I created My REST API consumer and call it like this: `RestAPIConsumer::getData()`
This gives me a JSON array of data.
Second I want each of the rows from the JSON data to be an option in a multiple select field, so I create a "custom field" like this:

```
class SelectMultipeFromAPIRepository extends AbstractHandler
{
    protected $codename = "Select Multiple from API";
    

    public function createContent($row, $dataType, $dataTypeContent, $options)
    {
        $gamesSelectOptions = RestAPIConsumer::getData()
        
        return view("formfields.select_multiple_api", [
            "row" => $row,
            "options" => $gamesSelectOptions,
            "dataType" => $dataType,
            "dataTypeContent" => $dataTypeContent
        ]);
    }
    
}
```

So far all is good - I register it in the service provider like so:
```
    public function register() {
           Voyager::addFormField(SelectMultipeFromAPIRepository::class);
    }

```
And then I add the view:
```
@php
$dataTypeContent->{$row->field} = json_decode($dataTypeContent->{$row->field})
@endphp
<select class="form-control select2" name="{{ $row->field }}[]" multiple>
    @if(isset($options->options))
        @foreach($options->options as $key => $label)
                <?php $selected = ''; ?>
            @if(is_array($dataTypeContent->{$row->field}) && in_array($key, $dataTypeContent->{$row->field}))
                <?php $selected = 'selected="selected"'; ?>
            @elseif(!is_null(old($row->field)) && in_array($key, old($row->field)))
                <?php $selected = 'selected="selected"'; ?>
            @endif
            <option value="{{ $key }}" {!! $selected !!}>
                {{ $label }}
            </option>
        @endforeach
    @endif
</select>
```

I can see the view in the BREAD editor, but when I submit data for that model I get an SQL error for array to string conversion:

> Illuminate \ Database \ QueryException
> Array to string conversion (SQL: insert into `buletines` (`title`, `status`, `type`, `certifications`, `change_notes`, `other`, `games`, `multigames`, `games_meta`, `multigames_meta`, `updated_at`, `created_at`) values (, draft, online, , , , online, , , , 2019-11-27 07:18:46, 2019-11-27 07:18:46))

So I decided to debug the flow and saw that the default multiple selection field is handled in the voyager controller based on `$codename` like so:
```

 /********** SELECT MULTIPLE TYPE **********/
            case 'select_multiple':
                return (new SelectMultiple($request, $slug, $row, $options))->handle();
```

But **My custom multiple selection** field always enters the default:
```
          /********** ALL OTHER TEXT TYPE **********/
            default:
                return (new Text($request, $slug, $row, $options))->handle();
```

Then I checked the default handler for the default multiple select field and I saw that it has a `$name` property which of course was missing from the documentation, but I decided to add it to my custom field never the less, so I changed my field to:

```
class SelectMultipeFromAPIRepository extends AbstractHandler
{
    protected $codename = 'select_multiple';
    protected $name = 'Select Multiple from API';

```
Perfect - now my field is shown in the BREAD editor and IT IS WORKING!!!!!

**But I can't see the default multiple select field any more, and I can't use it :(**

So my issue is that the process for adding a custom multiple select field either doesn't handle this type of field properly in the switch - case handler, or it completely overrides the default multiple select field and makes it unusable.

Please advise how I can bypass this problem and have both normal - default select multiple field, and a custom REST API multiple select field.

**Comment by G00sfraba** [comment]
![изображение](https://user-images.githubusercontent.com/1669800/69703544-47299f80-10fa-11ea-958a-78384a833879.png)
![изображение](https://user-images.githubusercontent.com/1669800/69703685-a7204600-10fa-11ea-925b-801796b3244c.png)
![изображение](https://user-images.githubusercontent.com/1669800/69703810-eb134b00-10fa-11ea-9f7a-df0e56371595.png)

**Comment by MrCrayon** [comment]
When you create a custom formfiled you can have your custom template and manage data passed to it, unfortunately managing data sent was not included as functionality but is treated as text as you saw.

In your case you can cleanly override getContentBasedOnType to add your option and encode your data before is saved, something like:

```php
public function getContentBasedOnType(Request $request, $slug, $row, $options = null)
{
    if (($row->type == 'your_custom_codename') {
        return (new YourCustomSelect($request, $slug, $row, $options))->handle();
    }

    return parent::getContentBasedOnType($request, $slug, $row, $options)
}
```

Personally I'm not liking where you put your API call, I would have probably used the normal select_multiple and inject the data in VoyagerBaseController edit and create methods.

Something like:
```php
public function edit(Request $request, $id)
{
    $view = parent::edit($request, $id);

    $dataTypeContent = $view['dataTypeContent'];
    //Call API, put  your data in $dataTypeContent and put it back in $view

    return $view;
}
```

Maybe there are better ways, this is my two cents.

**Comment by MrCrayon** [comment]
Also are you sure you need to call RestAPIConsumer::getData() everytime?

Consider saving it in db, you won't need a custom multiselect anymore and your data is cached for how long you choose.

**Comment by G00sfraba** [comment]
> In your case you can cleanly override getContentBasedOnType to add your option and encode your data before is saved, something like:
> 
> ```
> public function getContentBasedOnType(Request $request, $slug, $row, $options = null)
> {
>     if (($row->type == 'your_custom_codename') {
>         return (new YourCustomSelect($request, $slug, $row, $options))->handle();
>     }
> 
>     return parent::getContentBasedOnType($request, $slug, $row, $options)
> }
> ```

Initially this was my exact wish. I like the idea of overriding `getContentBasedOnType` but where and how. I don't want to put any custom code inside the tcg vendor folder. Maybe I didn't fully understand the concept behind this override and how to use it. Can you give me a bit more context to it.

PS: Little late but you mean to override this method inside the resource controller of my model? Or i got that also wrong :D

As for the non cahe-able Rest API calls- that is a story for another day with a lot of back-ground. Just assume I have to consume an API every time and there is a very good chance, that the data could be different every time

**Comment by MrCrayon** [comment]
The only way you should change vendor is using a fork, override controller as per documentation:
https://voyager-docs.devdojo.com/customization/overriding-files

**Comment by G00sfraba** [comment]
Thanks for the Help!

I have overriden the `getContentBasedOnType `function in my Resource controller which extends the voyager base controller, and the rest is as per the documentation for the custom fields!.

We can close this
