### ISSUE TITLE
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]

### ISSUE THREAD

**Issue by pakistanimoon** [thedevdojo/voyager#4586]
## Version information

 - Laravel: v6.6.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: [PgSql] [9.6] (e.g. MySQL 8.0)

## Description

I just installed fresh voyager and it installed successfully, everything is openable but when i clicked on Database menu from admin panel it display's error as following.

![image](https://user-images.githubusercontent.com/5585103/69747985-2b111700-1169-11ea-8b41-174451defc30.png)

## Steps To Reproduce
1. install voyager version 1.3
2. login to admin panel with admin user
3. open database menu from left side menu bar

## Expected behavior
![image](https://user-images.githubusercontent.com/5585103/69748108-74f9fd00-1169-11ea-8aab-63690caff22c.png)

## Screenshots
all screen shots attached.

## Additional context
I solved this error by following these steps.
each of these steps solved my problem but i don't know which one is best.
1. open following file 
_projectfolder\vendor\tcg\voyager\routes\voyager.php_

Add **?** infornt of `{id}` as `{id?}` at following line

`Route::delete('{id}', ['uses' => $namespacePrefix.'VoyagerBreadController@destroy',  'as' => 'delete']);
`
OR

2. open following file 

`projectfolder\vendor\tcg\voyager\resources\views\tools\database\index.blade.php`

replace `['id' => null]` text with `''` in following line

`<form action="{{ route('voyager.bread.delete', ['id' => null]) }}" id="delete_bread_form" method="POST">`

These steps solved my problem but which one is right one i don't know and why it exist in latest version but not in old also don't know

**Comment by mweikat** [comment]
I have the same problem

**Comment by MrCrayon** [comment]
Odd it was not giving me any error :thinking: 
Anyway fixed in #4587 

Thanks for the detailed report.

**Comment by eletec** [comment]
Hi Voyager team
I got same error with a fresh install voyager last available version 
php 7.2.18
mysql 5.7.26
wamp
windows 10

Just install default without dummy
All is ok except wen I try to access database module i get this error 

Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: C:\wamp64\www\osim\vendor\tcg\voyager\resources\views\tools\database\index.blade.php)
http://127.0.0.1:8000/admin/database

I made only one change in db configuration 

'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',

otherway I get the konwn error key is too long...

Any idea ?

**Comment by MrCrayon** [comment]
@eletec please read my previous comment

**Comment by eletec** [comment]
The proposed fix does'n fix for me : same eror message

pakistanimoon  solution seems ok

**Comment by MrCrayon** [comment]
@eletec please check again if you applied fix correctly, if you still have the problem can you show me where is the error in index.blade.php and also line 232?
![Schermata da 2019-11-28 05-41-25](https://user-images.githubusercontent.com/6875243/69777996-f4f08900-11a2-11ea-89f9-2ed7fd54956d.png)

**Comment by eletec** [comment]
index.blade changes

`96   <form action="#" id="delete_bread_form" `method="POST">`

232  $('table .bread_actions').on('click', '.delete', function (e) {
                id = $(this).data('id');              
                name = $(this).data('name');

                $('#delete_bread_name').text(name);
               $('#delete_bread_form')[0].action = '{{ route('voyager.bread.delete', '__id') }}'.replace('__id', id);
               
                $('#delete_bread_modal').modal('show');`

I can edit / create / delete bread

I got error directly accessing database module ( I suppose id is not defined at this step)

Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: C:\wamp64\www\osim\vendor\tcg\voyager\resources\views\tools\database\index.blade.php)

I clear all laravel caches, restart server

**Comment by eletec** [comment]
error detail 

`
Illuminate\Routing\Exceptions\UrlGenerationException::forMissingParameters
:17
C:\wamp64\www\osim\vendor\laravel\framework\src\Illuminate\Routing\Exceptions\UrlGenerationException.php:17




















<?php

 

namespace Illuminate\Routing\Exceptions;

 

use Exception;

 

class UrlGenerationException extends Exception

{

    /**

     * Create a new exception for missing route parameters.

     *

     * @param  \Illuminate\Routing\Route  $route

     * @return static

     */

    public static function forMissingParameters($route)

    {

        return new static("Missing required parameters for [Route: {$route->getName()}] [URI: {$route->uri()}].");

    }

}
`

**Comment by pakistanimoon** [comment]
Can anyone help, my solutions mentioned above are not correct? because i am working on project after applying solution number 2, should i wait for update or continue with it?

**Comment by MrCrayon** [comment]
@pakistanimoon first thing you shouldn't change anything inside vendor other than for testing.

You can:

- ADVISED: Downgrade Laravel to v6.5.2 until this gets fixed in Voyager.
- Use your fork with fix untill this gets fixed in Voyager.

Said that as for your changes, you shouldn't change route definition and I'm quite sure the empty string is not supposed to work and it might not work in a future Laravel release if it gets fixed.

Can you try #4587?
I'm not sure why is not working for @eletec, it's working fine for me.

**Comment by hirbod** [comment]
#4587 fixes the issue for me. Just upgraded to Laravel 6.6 and Voyager's Database crashed for me. Was about to write an issue but I can use this patch for now until it gets resolved.

**Comment by rsecor** [comment]
I have the same issue and see the changes from https://github.com/laravel/framework/pull/30659/files are already in my system.

"laravel/framework": "^6.0"
"tcg/voyager": "^1.3"

Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: $HOME/laravel/vendor/tcg/voyager/resources/views/tools/database/index.blade.php)

From Telescope...
ErrorException
Trying to get property 'name' of non-object

**Comment by afrooseh** [comment]
go to 'vendor/tcg/voyager/resources/views/tools/database/index.blade.php' line 96 write:
`<form action="#" id="delete_bread_form" method="POST">`

**Comment by rsecor** [comment]
That works... thanks.
Do we have an idea when this will be put into the newest version?

**Comment by MrCrayon** [comment]
#4587 it's already merged and will be part of next release.

**Comment by neapolis79** [comment]
I have similar problem with Builder page for admin menu. i put the fix #4587 but with no result
![builder](https://user-images.githubusercontent.com/36012957/70632599-72021080-1c2f-11ea-8e2d-38977e0b8a78.JPG)

For fix this i downgraded laravel to 6.5.2 instead of laravel 6.7.0

**Comment by MrCrayon** [comment]
@neapolis79 as you said it's similar but not the same, there is another PR for that #4606.
And yes downgrading Laravel is the easiest work around until next Voyager version is realeased

**Comment by neapolis79** [comment]
ok just to know i override builder.blade.php view with the fix you referred and works also with laravel 6.7.0 thanks

**Comment by skys215** [comment]
> #4587 it's already merged and will be part of next release.

Are there any planning on releasing next update? When it will be?
Thanks.

**Comment by clemkake** [comment]
it is definitely not wise to edit any vendor package, because we all know that things are going to be really messy on the next update. 
I am also working on a fix.

**Comment by clemkake** [comment]
![image](https://user-images.githubusercontent.com/11903584/70823967-22763d00-1e07-11ea-9a41-f1460da92dbf.png)

well adding another condition to it works!

**Comment by johncarlson21** [comment]
following

**Comment by doubleprincez** [comment]
Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}]. 

This is what i'm receiving from a fresh voyager installation with dummy data, installed 22nd Dec 2019

the error seems to be connected with tcg/voyager/resources/views/menus/builder

```
    <form action="{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '__id']) }}"
                          id="delete_form"
                          method="POST">
```

**Comment by MrCrayon** [comment]
@doubleprincez please read previous comments or search in issues #4623

**Comment by loooping-old** [comment]
> ## Version information
> 
>     * Laravel: v6.6.0
> 
>     * Voyager: v1.3.0
> 
>     * PHP: 7.2
> 
>     * Database: [PgSql] [9.6] (e.g. MySQL 8.0)
> 
> 
> ## Description
> 
> I just installed fresh voyager and it installed successfully, everything is openable but when i clicked on Database menu from admin panel it display's error as following.
> 
> ![image](https://user-images.githubusercontent.com/5585103/69747985-2b111700-1169-11ea-8b41-174451defc30.png)
> ## Steps To Reproduce
> 
> Steps to reproduce the behavior:
> 
>     1. install voyager version 1.3
> 
>     2. login to admin panel with admin user
> 
>     3. open database menu from left side menu bar
> 
>     4. See error
> 
> 
> ## Expected behavior
> 
> ![image](https://user-images.githubusercontent.com/5585103/69748108-74f9fd00-1169-11ea-8aab-63690caff22c.png)
> ## Screenshots
> 
> all screen shots attached.
> ## Additional context
> 
> I solved this error by following these steps.
> each of these steps solved my problem but i don't know which one is best.
> 
>     1. open following file
>        _projectfolder\vendor\tcg\voyager\routes\voyager.php_
> 
> 
> Add **?** infornt of `{id}` as `{id?}` at following line
> 
> `Route::delete('{id}', ['uses' => $namespacePrefix.'VoyagerBreadController@destroy', 'as' => 'delete']); `
> OR
> 
>     1. open following file
> 
> 
> `projectfolder\vendor\tcg\voyager\resources\views\tools\database\index.blade.php`
> 
> replace `['id' => null]` text with `''` in following line
> 
> `<form action="{{ route('voyager.bread.delete', ['id' => null]) }}" id="delete_bread_form" method="POST">`
> 
> These steps solved my problem but which one is right one i don't know and why it exist in latest version but not in old also don't know

THANK U SO MUCH

**Comment by MrCrayon** [comment]
@loooping It's strange that you just installed 1.3.0 when 1.3.1 is available, please update it's fixed in last release.

**Comment by hanhabesha** [comment]
on voyager v1.3.2  these trick works for me [here](https://voyager-docs.devdojo.com/troubleshooting/missing-required-parameter)

**Comment by lesichkovm** [comment]
BTW. This also happens if the value for your primary key is NULL, which indicates a problem with your data. The message is misleading.
