### ISSUE TITLE
Only one option available for a belongsTo relationship

### ISSUE THREAD

**Issue by damms005** [thedevdojo/voyager#4589]
- Laravel: v5.8.35
 - Voyager: v1.3.0
 - PHP: 7.2
 - MySQL 5.7

## Description

When editing a `Model-A` that has a belongsTo relationship with `Model-B`, only one item from `Model-B` is available for selection.

## Steps To Reproduce
1. Add bread to `Model-A` and `Model-B`
2. Edit `Model-A` bread to have a belongsTo relationship with `Model-B`
3. Edit an existing record in `Model-A`
4. Only a record in `Model-B` is available to select from dropdown

## Expected behavior
When editing the belongsTo field in `Model-A`, it should bring option for all available records in `Model-B`

**Comment by MrCrayon** [comment]
Your problem means that ajax call for some reason is not working.
By design, since loading with ajax was introduced, only selected value is fetched at start all other values  are loaded with an ajax call.

Check your browser console to find any error.

**Comment by damms005** [comment]
Thanks for the quick response.

I'll need some help figuring out how to re-publish the asset files (js/css) so I can catch-up with any missing updates that should have done that ajax thingy you mentioned

I have checked [VoyagerServiceProvider and it seems like I can only re-publish contents of the `dummy_content`, `database`, and `config` folders](https://github.com/the-control-group/voyager/blob/1.3/src/VoyagerServiceProvider.php#L243). How can I re-publish voyager these voyager assets? (which I guess will contain the ajax feature)

**Comment by MrCrayon** [comment]
You shouldn't need to publish them because they are taken directly from vendor with `voyager-assets?path=`

You should normally only add a custom.js and custom.css and not touch the base ones.

But anyway publishing just means copying so you can copy them from `vendor/tcg/voyager/publishable/asset`.

**Comment by damms005** [comment]
I do not use any `custom.js` nor `custom.css` files. I suggested the assets publishing because I was not aware of the `voyager-assets?path=` asset handling until now.

I was curios about the assets publishing because my browser console did not show any errors, nor was there any `XHR` request in the `Network` tab of my browser's dev tools

**Comment by MrCrayon** [comment]
If you are not using custom templates that might have changed which files are loaded, or overriden assets method in VoyagerController try to clear your browser cache.

**Comment by MrCrayon** [comment]
Please let us know if you solved the problem so we can close the issue.

**Comment by damms005** [comment]
Thanks @MrCrayon for the tip regarding the update that fetches assets via `voyager-assets?path=`. The issue was indeed as a result of custom templates.
