### ISSUE TITLE
Voyager can't access uploaded image, even default avatar/post in admin panel

### ISSUE THREAD

**Issue by dixitaditya** [thedevdojo/voyager#459]
- Laravel Version: 5.3
- Voyager Version: v0.10.6
- PHP Version: 5.6
- Database Driver & Version:

### Description:
1. I was using voyager admin panel some version prior to 9.27 ...everything was fine images were being pulled from db to front end of my website(locally hosted XAMPP).

2. then with composer update..it updated to 9.27 and then i stopped getting any images pulled from db (though i didn't changed my code) even voyager admin panel was not able to show the images uploaded in "POST" section everything else like 'post body' 'post-title'were just working fine.

3.So i removed every link to tcg/voyager from everywhere like comoser.json then updated composer and App/config, even did "php artisan cache:clear" and "php artisan view:clear" and removed the dummy pages posts stored in both "storage/app/post"  and "public/storage" as per my knowledge there is no trace of Voyager 9.27 even i truncated the database

4. i  installed v.0.10.6 and even now things are not working and to my utmost surprise even admin panel is not able to pull the images.[ neither avatar nor any dummy post ,even generated link is not working]
![issue git](https://cloud.githubusercontent.com/assets/24824142/21542633/30ae4d10-cde5-11e6-8bb1-f14855cdf3a4.PNG).

![issue3](https://cloud.githubusercontent.com/assets/24824142/21542818/cbba51f4-cde6-11e6-950c-2ed1ff11081e.PNG)

5. On going through the folder on by one i realized that though voyager admin panel is uploading images to {Myapp}\storage\app\public\posts and files are even present there (however i am not able to access them through url in browser). and on other hand there is nothing in {myapp}\public\storage
![issue 2](https://cloud.githubusercontent.com/assets/24824142/21542724/e554ee04-cde5-11e6-9492-c0dafab20621.PNG)

and i believe that both voyager admin panel and even my app are pulling image through the  {myapp}\public\storage [in my app i am using and this was working in my previous version]

 `public function getPostImageUrl()
    {
        return "./storage/$this->image";
    }`

it appears that some link between those two folders is broken.

This is just not making sense, please someone help me out here.

**Comment by fletch3555** [comment]
Sounds like your symlink is broken.  Please delete /public/storage and run `php artisan storage:link` again.  This is a command that `php artisan voyager:install` calls under the hood to link the static assets (like images).

**Comment by dixitaditya** [comment]
Thanks .. It worked
