### ISSUE TITLE
[ASK] - BREAD and BelongsTo on a table with three primary keys

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4591]
- Laravel: v5.3
 - Voyager: v1.3
 - PHP: 7.3
 - Database: MySQL 8.0

Hi everyone, I have a Patient table with three primary keys (id, Name, Center) and another Therapies table that contains three foreign keys to the Patient table. How can I connect these two entities via BREAD to be able to insert a new record in the Therapies table?

I tried collating only one attribute at a time via the "BelongsTo" rule, but then I get lots of "None" values in the select.

Thanks for the tips guys

**Comment by MrCrayon** [comment]
You can't have three primary keys in a table.
If Therapy belongs to only one Patient, you can have a patient_id in your Therapy table and connect it with a BeolngsTo relationship.
If Therapy can be associated with more than one Patient you'll need a BelongsToMany relationship and a pivot table.

This is not specific of Voyager is how relationships works in Laravel.

If you have any question related to your integration with Voyager please ask in our Slack group.
