### ISSUE TITLE
Class VoyagerAuth does not exist

### ISSUE THREAD

**Issue by cgo34** [thedevdojo/voyager#4594]
- Laravel: v5.7
 - Voyager: v1.3 or ^1.2.7
 - PHP: 7
 - Database: mysql

## Description
Class VoyagerAuth does not exist

When i'm loggin in prod, in local all work properly

**Comment by fletch3555** [comment]
Did you try `composer dump-autoload`? If the file exists on the filesystem(which it does if you've done a `composer install` on that environment), then the issue is almost certainly your php/composer class autoloader cache
