### ISSUE TITLE
BelongsTo Dropdown doesn't keep old value when add/edit new record

### ISSUE THREAD

**Issue by livrosroberto** [thedevdojo/voyager#4596]
## Version information
 - Laravel: v6.5.0
 - Voyager: v1.3.0
 - PHP: 7.3.11
 - Database: MYSQL 15.1 10.4.8 MariaDB

## Description
We have two issues and I tried my best, but my self taught knowledge wasn't enough to fix the problem

BelongsTo Dropdown doesn't keep old value when add/edit new record

## Steps to reproduce the behavior:

SCENARIO A
1. Create a BREAD with a belongsTo relationship and other field with some validation rule
2. Go to add view to add a new record
3. Choose some value on dropdown (belongsTo)
4. force validation of some other field to fail
5. Click save button
6. Voyager will return to add view with validation error message and an empty dropdown 

SCENARIO B 
1. Create a BREAD with a belongsTo relationship and other field with some validation rule
2. Go to add view to add a new record
3. Fill out the form correctly
4. Click save button
5. Click edit button to edit the register saved in steps above
6. Change the dropdown (belongsTo) value
7. Change other field to force to fail validation 
8. Click save button
9. Voyager will return to edit view with validation error message and belongsTo dropdown will bring the value saved on step 4.

Much appreciated, and I'm sorry to not be able to fix this by myself!

ps. I tried everything I could with my little knowledge in relationship.blade.php

**Comment by MrCrayon** [comment]
I'm not near a computer right now but looking at the code I can confirm the bug. 
Try override relationships view and change this line
https://github.com/the-control-group/voyager/blob/e4fe256e32971c6c9554dea93c65973174257f02/resources/views/formfields/relationship.blade.php#L14
In
```
 $query = $model::where($options->key, old($options->column) ?? $relationshipData->{$options->column})->first();
```

**Comment by MrCrayon** [comment]
Or better as second argument of where
```
old($options->column, $dataTypeContent->{$options->column})
```

**Comment by livrosroberto** [comment]
Thanks @MrCrayon 

I had success changing 

https://github.com/the-control-group/voyager/blob/e4fe256e32971c6c9554dea93c65973174257f02/resources/views/formfields/relationship.blade.php#L34

to

```php
$query = $model::where($options->key, old($options->column, $dataTypeContent->{$options->column}))->get();
```

Can you please confirm that and make a PR, cause I'm don't know how to do it.

Much appreciated!
