### ISSUE TITLE
I have a problem when I want to run my project don't want to run and it's given me these errors

### ISSUE THREAD

**Issue by 1992abdo** [thedevdojo/voyager#4597]
![voyager](https://user-images.githubusercontent.com/44400041/69892206-62b3c680-1303-11ea-9e4e-389a363cffe6.JPG)

**Comment by MrCrayon** [comment]
Information asked in the issue template is not optional. 
Anyway it looks like you changed something in your template or added a custom javascript. 
You should have everything to debug the error.

**Comment by 1992abdo** [comment]
thanks, man I find the problem is in laravel-page-speed when I installed it gives me this error
