### ISSUE TITLE
problem when view a post

### ISSUE THREAD

**Issue by rockxsj** [thedevdojo/voyager#46]
I login as admin,when I want to view a post, eg:http://localhost:8000/post/latest-post. 
I will get the error message like this:
`Sorry, the page you are looking for could not be found.

1/1
NotFoundHttpException in RouteCollection.php line 161:`

**Comment by afsardo** [comment]
Yes, i found that problem aswell it's a minor thing.

I will send a PR as a proposal, since i do not know what behaviour the maintainers want.

**Comment by guahsu** [comment]
same problem here :D..

**Comment by allenjd3** [comment]
Same here- looks like it can't find the route. I could make a route but it's not obvious in the docs where it should point.

**Comment by Omazon** [comment]
same problem too

**Comment by fletch3555** [comment]
#49 was merged in 25 days ago and should resolve this issue.

Closing this for now.  If this is still an issue in the current release, please let me know and I'll reopen it.
