### ISSUE TITLE
Feature Request - Ajax autocomplete for Relationship fields

### ISSUE THREAD

**Issue by Muhammadinaam** [thedevdojo/voyager#460]
Right now, Voyager is using <select> tag for relationship fields. It loads all related objects as <option> tag in <select> tags.

It may cause problem when size of related model is very large i.e. it may cause problem in chrome when related model array is larger than 10,000. It may also decrease performance.

Voyager is using select2 jquery plugin and it supports remote loading of items through ajax.

Please make necessary changes.

**Comment by Muhammadinaam** [comment]
Will this feature be available in version 1.0?

**Comment by fletch3555** [comment]
This likely still needs to be implemented, but I'm going to close it so we can have a fresh start following the 1.0 release.

**Comment by desmax** [comment]
what's up with this?
