### ISSUE TITLE
Users list not loading

### ISSUE THREAD

**Issue by Kushelbek** [thedevdojo/voyager#4607]
Hi All! Ill have a problem with list of users.
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.1
 - Database:  MySQL 5.6

## Description

The list of users is not loaded(502 Bad Gateway). There are 4500 users in the database, what should I do? 

## Steps To Reproduce
Add 4k+ users to DB.

**Comment by MrCrayon** [comment]
Please provide full version v1.2.?

Do you have Server-side Pagination enabled in BREAD settings?
If not try if that solves the problem and let us know.

**Comment by Kushelbek** [comment]
> Server-side Pagination enabled

I'll enable Server-side Pagination, then all works.
Thanks you!
