### ISSUE TITLE
Backend keeps loading infinite

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4608]
## Version information

 - Laravel: v5.6
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL version 5.6.41

## Description
The Backend keeps loading(shows loader) after logging in. Nothing else works. It's just a fresh install on the server. Seems that it's a JS error caused infinitely loading view. Here is the screenshot. It shows failed to decode downloaded font, OTS parsing error.it's related to FontAwesome.

## Screenshots
![image](https://user-images.githubusercontent.com/22276302/70302145-4e4f5c80-1822-11ea-8a80-5f4741215641.png)

Here is the logs from console,
![image](https://user-images.githubusercontent.com/22276302/70302453-28768780-1823-11ea-8dda-4141b4e116ac.png)

**Comment by MrCrayon** [comment]
Looks like app.js is corrupted:
https://github.com/the-control-group/voyager/blob/1.3/publishable/assets/js/app.js

can you try to reupload it?

**Comment by vkiranmaniya** [comment]
Reuploaded file and ran the `php artisan vendor:publish` command once. Not working

**Comment by MrCrayon** [comment]
The publish command is not going to change anything because they are taken directly from vendor, but anyway if it's not a file problem we need to check where exactly the error is happening.

In Chrome console click on the error line, it will bring you to the source code of app.js, since file is minified that's not much useful untill you click on {} on the bottom left (it might take a while to generate the pretty print).
After that please report back what's the code causing the error.

**Comment by vkiranmaniya** [comment]
The DevTools prettier isn't working for the file at all. The formatted source shows the same as minified.
![image](https://user-images.githubusercontent.com/22276302/70310377-7dbb9480-1835-11ea-980f-451e474fa380.png)

**Comment by MrCrayon** [comment]
Your app.js is different from the one provided with Voyager v1.3.0, check number of columns:
![Schermata da 2019-12-06 10-18-50](https://user-images.githubusercontent.com/6875243/70311389-df6a0780-1811-11ea-9820-dd0d07b0686e.png)

If server file is ok, maybe you are still checking a cached version.
Try reloading with Disable cache checked in Network tab.

**Comment by emptynick** [comment]
I'm curious what that `content.js` file does when it `injects`.
That's not from Voyager.
What does it do?

**Comment by vkiranmaniya** [comment]
I've already disabled the cache when DevTools is open. Anyway let me download the app js file from repository and and put it there.

**Comment by MrCrayon** [comment]
@emptynick that's for sure it's from a Chrome extension.
@vkiranmaniya if it's still not working you might try to disable chrome extensions, now that I think about it I think someone else had problems with chrome extensions...

**Comment by vkiranmaniya** [comment]
I just downloaded the app.js from v1.3.0 Tag from repository and reuploaded it.

> I'm curious what that `content.js` file does when it `injects`.
> That's not from Voyager.
> What does it do?

The content js is just a script fro chat head. I also used it along with Voyager and never cause an issue before.
I just downloaded the app js from the repository release tag v1.3.0 and replaced it. Still doesn't work
@MrCrayon let me try with another system, to look up the infecting chrome ext.

**Comment by vkiranmaniya** [comment]
> @emptynick that's for sure it's from a Chrome extension.
> @vkiranmaniya if it's still not working you might try to disable chrome extensions, now that I think about it I think someone else had problems with chrome extensions...

I tried after disabling all the extensions. even on another system. You were right, The `inject` is coming from one of the extensions. but disabling the extension doesn't helped.

**Comment by MrCrayon** [comment]
Just to be clear where are you putting app.js in your server?

Because your file is still different, somewhere in the middle.

original file:
```, n._comment = /<!--(?!-?>)[\s\S]*?-->/,```
your file:
```, n._comment = //,```

From there it breaks, so it's either your file different or server applying some filter :thinking:

**Comment by vkiranmaniya** [comment]
Yup caught it. There was a middleware, for minify the HTML content. Here is the code.
```php
public function handle($request, Closure $next){
        $response = $next($request);
        $buffer = $response->getContent();
        if(strpos($buffer,'<pre>') !== false)
        {
            $replace = array(
                '/<!--[^\[](.*?)[^\]]-->/s' => '',
                "/<\?php/"                  => '<?php ',
                "/\r/"                      => '',
                "/>\n</"                    => '><',
                "/>\s+\n</"                 => '><',
                "/>\n\s+</"                 => '><',
            );
        }
        else
        {
            $replace = array(
                '/<!--[^\[](.*?)[^\]]-->/s' => '',
                "/<\?php/"                  => '<?php ',
                "/\n([\S])/"                => '$1',
                "/\r/"                      => '',
                "/\n/"                      => '',
                "/\t/"                      => '',
                "/ +/"                      => ' ',
            );
        }
        $buffer = preg_replace(array_keys($replace), array_values($replace), $buffer);
        $response->setContent($buffer);
        ini_set('zlib.output_compression', 'On'); // If you like to enable GZip, too!
        return $response;
    }
```

I just removed the minified for a while and it worked like a charm. I have one more question, If this code caused the issue, the same middleware also in another system doesn't affect the voyager app.js.

**Comment by MrCrayon** [comment]
No idea about that, maybe cached file?

If you are good here you can remove possible bug label and close the issue.
