### ISSUE TITLE
 ReflectionException (-1) Class App\Models\Order does not exist although It exists

### ISSUE THREAD

**Issue by EmanFateen** [thedevdojo/voyager#4609]
## Version information

 - Laravel: "5.7.*",
 - Voyager:  "^1.3"
 - PHP: "^7.1.3",
 - Database: MySQL

## Description

I'm Using Voyager recently and I made alot of breads all it working good, but Order table. Creating a bread fro this table through out the exception ReflectionException (-1) Class App\Models\Order does not exist although It exists. I can't handle it, also I can't understand why exactly this table do that? 

## Screenshot 
![1](https://user-images.githubusercontent.com/12045094/70338218-2a593e80-1855-11ea-8383-623d58031c00.JPG)
![2](https://user-images.githubusercontent.com/12045094/70338220-2af1d500-1855-11ea-90e6-137dbe188e0d.JPG)

**Comment by MrCrayon** [comment]
Can you show the Namespace of your Order class?
