### ISSUE TITLE
Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}].

### ISSUE THREAD

**Issue by justatom** [thedevdojo/voyager#4611]
## Version information

 - Laravel: v 6.6.2
 - Voyager: latest
 - PHP: 7.2.18
 - Database: MySQL 5.7.26

## Description

I just found a bug which is familiar issue of [https://github.com/the-control-group/voyager/issues/4586](url)

Screen Shot : 

## Steps To Reproduce

1. install voyager version 1.3
2. login to admin panel with admin user
3. Navigate to Tools -> Menu Builder -> hit the green Builder button

## Expected behavior
[http://tinyurl.com/u9yeq7v](url)

## Screenshots
[http://tinyurl.com/ryoedx7](url)
(Sorry I don't know how to post image)

## Additional context
I thought this is familiar with [https://github.com/the-control-group/voyager/issues/4586](url)
So I open 
ProjectFolder\vendor\tcg\voyager\resource\views\menus\builder.blade.php
and Edit line 44 from
`<form action="{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '__id']) }}" id="delete_form" method="POST">`
to
`<form action="#" id="delete_form" method="POST">`

and line 282 from
`$('#delete_form')[0].action = '{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '']) }}/' + id;`
to
`$('#delete_form')[0].action = '{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '__id']) }}/'.replace('__id', id);`

and it worked.

**Comment by emptynick** [comment]
You already found the original issue.
Closing as a duplicate
