### ISSUE TITLE
Missing required parameters for [Route: voyager.score-table.edit] [URI: admin/score-table/{score_table}/edit]. (View: /app/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)

### ISSUE THREAD

**Issue by georak** [thedevdojo/voyager#4612]
### Version information
 - Laravel: v6.6.2
 - Voyager: latest
 - PHP: 7.4
 - Database:MySQL 8.0

## Description
Try to create one table without "id" or without primary key column and you will get next error

Missing required parameters for [Route: voyager.score-table.edit] [URI: admin/score-table/{score_table}/edit]. (View: /app/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)

### Steps to reproduce the behavior:
1. create table without column "id" or add to your Eloquent Model the next line
> protected $primaryKey = null;
2. create bread
3. browse to this bread

**Comment by MrCrayon** [comment]
That's not a bug it's a requirement. 
If you want to use a CRUD/BREAD system you need a primary key the system can use to reference your resources.
