### ISSUE TITLE
Missing required parameters for [Route: voyager.menus.item.destroy]

### ISSUE THREAD

**Issue by shahidaali** [thedevdojo/voyager#4623]
## Version information

 - Laravel: v6.7.0
 - Voyager: v1.2.2
 - PHP: 7.2.14
 - Database: MySQL 5.7.24

## Description

I got this error on my fresh installation.
`Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}]. (View: D:\wamp64\www\laravel\smarttownship\vendor\tcg\voyager\resources\views\menus\builder.blade.php)`

## Steps To Reproduce
1. Go to 'Menu Builder'
2. Click on 'Builder' option for any menu
3. See error

## Expected behavior
I fixed this issue by adding optional {id?} parameter instead of required {id} in `[URI: admin/menus/{menu}/item/{id}]`
in vendor\tcg\voyager\routes\voyager.php
` Route::delete('{id?}', ['uses' => $namespacePrefix.'VoyagerMenuController@delete_menu', 'as' => 'destroy']);`
Instead of
` Route::delete('{id}', ['uses' => $namespacePrefix.'VoyagerMenuController@delete_menu', 'as' => 'destroy']);`
This error was produces due to passing empty value for {id} in `tcg\voyager\resources\views\menus\builder.blade.php` on line no 282.

`$('#delete_form')[0].action = '{{ route('voyager.menus.item.destroy', ['menu' => $menu->id, 'id' => '']) }}/' + id;`

Hope this will be fixed in future releases.

## Screenshots
![image](https://user-images.githubusercontent.com/14015943/70794432-70675280-1dbf-11ea-9ef1-c95f1b0b64bc.png)

**Comment by MrCrayon** [comment]
Fix is already merged #4606
As a quick workaround untill a new version of Voyager is released you can downgrade Laravel.
