### ISSUE TITLE
Err 403 on ajax relation request when editing a model

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4629]
## Version information

 - Laravel: v6.7
 - Voyager: v1.3.x-dev
 - PHP: 7.4.0
 - Database: MySQL 8.0.18

## Description

Bread editing of a model.
When clicking on the dropdown to select the related model for the association (belongs_to in my case), the dropdown displays message `The results could not be loaded`.
When inspecting the request, it appears that it results in a 403.
The URL is `http://localhost:8000/admin/text-blocks/relation?type=text_block_belongsto_socket_relationship&method=edit&page=1`

The results are correctly loaded on model creation.

## Steps To Reproduce
1. Create a bread with a belongs_to relationship
2. Insert a record for that model: select the related model in the dropdown
3. Edit the newly created model 
4. Open developer tools of your browser, network tab, filter only XHR
5. Click on the dropdown to select the related model
6. See message "The results could not be loaded" and the XHR 403 response in the debug tool.

## Expected behavior
The same results should be displayed when creating and editing a model.

## Screenshots
![voyager-bug-edit-relation](https://user-images.githubusercontent.com/5526263/70865498-a8f16280-1f5e-11ea-9796-174758e178c5.gif)

**Comment by MrCrayon** [comment]
Make sure Scope you just added is not the one causing the problem ~then you can try if this fixes it #4539.~

But I think the problem I solved there was on add not on edit :thinking:

If that doesn't work please post your BREAD configuration. 

Edit: 
I assumed you were using 1.3.0 but you are using dev. 
I think app.js is not updated in dev, so id is not passed and you have access denied. 
Permission checks has been introduced in #4539.

You'll need to compile app.js for now untill we fix compilation script.

**Comment by ghost** [comment]
It did not work in the first place, before I set up the scope with a custom controller. Disabled it to be sure, but the problem does not come from that custom controller.

Here's my bread configuration:

```
{
  "model": "App\\Socket",
  "table": "sockets",
  "type": "belongsTo",
  "column": "socket_id",
  "key": "id",
  "label": "name",
  "pivot_table": "banners",
  "pivot": "0",
  "taggable": "0"
}
```

Should I post the migrations of the model and the related one?

**Comment by MrCrayon** [comment]
Nope the problem is app.js, check my previous comment update.

**Comment by ghost** [comment]
OK. I'll try that. Just need to know how to compile it. I think I've seen something about that, whether in an issue or in the documentation, can't figure out...
Do I need to compile it in the vendor dir, or will it be in my resources dir?

EDIT: I've seen it here https://github.com/the-control-group/voyager/issues/4551#issuecomment-552109251 but you did not mention how to compile it (actually, it was for a forked repo)

**Comment by MrCrayon** [comment]
inside vendor/tcg/voyager
```
npm install
npm run prod
```
Before passing to next release remove voyager folder so you won't carry on all dependencies that need to be installed to compile assets.

**Comment by ghost** [comment]
I suppose next time the package will be updated via Composer, app.js will be fixed, so I won't have to do this again?

**Comment by ghost** [comment]
Had to clear cache then it's ok.

Thanks!

**Comment by MrCrayon** [comment]
> I suppose next time the package will be updated via Composer, app.js will be fixed, so I won't have to do this again?

Right

**Comment by MID904** [comment]
I have this version information:
Laravel: 7.0
Voyager: v1.4.x
PHP: 7.4.6
Database: MySQL 5.7.24

With exactly the same problem. I had checked the VoyagerBaseController and found that the request is not carrying the id. Is the app.js of this voyager's version ok?

**Comment by nehasharma1997** [comment]
I have follow the 
`
npm install
npm run prod
`
but still have the problem:

`relation?type=item_belongsto_item_relationship&method=edit&page=1 403 (Forbidden)`

`
(anonymous) | @ | VM129:1
  | send | @ | voyager-assets?path=js%2Fapp.js:1
  | ajax | @ | voyager-assets?path=js%2Fapp.js:1
`

**Comment by nehasharma1997** [comment]
Problem solve by clear browser cache.

**Comment by nixprosoft** [comment]
If problem exists only on "add" page, and field works correctly on "edit" page of existing item the problem is:
Possible, your model return 0 in "id" attribute instead of null.
