### ISSUE TITLE
Relation not working with model named `Banner`?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4630]
## Version information

 - Laravel: v6.7
 - Voyager: v1.3.x-dev
 - PHP: 7.4.0
 - Database: MySQL 8.0.18

## Description
I've got this relationship: Banner ----- belongsTo ----> Socket

When editing/creating a record with bread, the dropdown for the related model does not work at all. The message displayed is "Searching..." and nothing happens, the XHR is not even triggered.

- I've got the same relation with another model and it works fine.
- I have remove all fancy formfiels and let only text on the bread form, not better.
- I have created another class named Foo with the same characteristics (copy/paste) and it works.
- I've deleted the bread, re-created it, not working.
- I've compared models, migrations, bread configuration for both models, they're identical (names are appropriate though) one works, Banner doesn't.

## Steps To Reproduce
1. Create a new Laravel app: `composer create-project laravel/laravel test-voyager`
2. Install Voyager package: `cd test-voyager` && `composer require tcg/voyager 1.3.x-dev`
3. Set up a new database and edit `.env` appropriately
4. Create models and migrations: `artisan make:model Foo -m` and `artisan make:model Banner -m`
5. Edit the newly created files like so: https://gist.github.com/Arcesilas/a3ba78e8f1bb34e0e34148164a9d2f8e
6. Create the bread for the Banner model
7. Create a `belongsTo` relationship on the Banner bread to Foo model
8. Insert a new Foo (with bread or an SQL query)
9. Create a new Banner from BREAD: click on the Foo dropdown and see nothing happen.

Rename the table and the model to `front_banners` and `FrontBanner` and magic can happen again...

## Expected behavior
Dropdown should display results

## Possible cause

It seems in the JS that there is a `banner` object somewhere... Could they conflict?

**Comment by ghost** [comment]
Precision about the origin of the problem: if the slug is `banner`, then it does not work...
I wanted to have the slug be `banner` and the problem was here after I renamed everything to fit FrontBanner model...

EDIT: Feel free to close this issue whenever you like. I use another slug and it's all fine. However, it could be nice to have a list of forbidden slugs which conflict with some JS.

**Comment by MrCrayon** [comment]
I don't see banner anywhere in Voyager libraries included, can you confirm the problem still happens after you recompiled assets?

**Comment by ghost** [comment]
On a vanilla installation, after recompiling the assets, I find some results, I don't know if they're published or not. For example:

```
./node_modules/uri-js/rollup.config.js:31:	banner: "/** @license URI.js v" + packageJson.version + " (c) 2011 Gary Court. License: http://github.com/garycourt/uri-js */"
./node_modules/webpack/lib/BannerPlugin.js:43:				banner: options
./node_modules/webpack/lib/BannerPlugin.js:50:		const bannerOption = options.banner;
./node_modules/webpack/lib/BannerPlugin.js:51:		if (typeof bannerOption === "function") {
./node_modules/webpack/lib/BannerPlugin.js:52:			const getBanner = bannerOption;
./node_modules/webpack/lib/BannerPlugin.js:53:			this.banner = this.options.raw
./node_modules/webpack/lib/BannerPlugin.js:57:			const banner = this.options.raw
./node_modules/webpack/lib/BannerPlugin.js:58:				? bannerOption
./node_modules/webpack/lib/BannerPlugin.js:59:				: wrapComment(bannerOption);
./node_modules/webpack/lib/BannerPlugin.js:60:			this.banner = () => banner;
./node_modules/webpack/lib/BannerPlugin.js:66:		const banner = this.banner;
./node_modules/webpack/lib/BannerPlugin.js:109:						const comment = compilation.getPath(banner(data), data);
./node_modules/webpack/declarations/plugins/BannerPlugin.d.ts:12: * The banner as function, it will be wrapped in a comment
./node_modules/webpack/declarations/plugins/BannerPlugin.d.ts:26:	 * Specifies the banner
./node_modules/webpack/declarations/plugins/BannerPlugin.d.ts:28:	banner: BannerFunction | string;
./node_modules/webpack/declarations/plugins/BannerPlugin.d.ts:30:	 * If true, the banner will only be added to the entry chunks
./node_modules/webpack/declarations/plugins/BannerPlugin.d.ts:42:	 * If true, banner will not be wrapped in a comment
./node_modules/webpack/schemas/plugins/BannerPlugin.json:4:      "description": "The banner as function, it will be wrapped in a comment",
./node_modules/webpack/schemas/plugins/BannerPlugin.json:46:        "banner": {
./node_modules/webpack/schemas/plugins/BannerPlugin.json:47:          "description": "Specifies the banner",
./node_modules/webpack/schemas/plugins/BannerPlugin.json:58:          "description": "If true, the banner will only be added to the entry chunks",
./node_modules/webpack/schemas/plugins/BannerPlugin.json:78:          "description": "If true, banner will not be wrapped in a comment",
./node_modules/webpack/schemas/plugins/BannerPlugin.json:90:      "required": ["banner"]
./node_modules/webpack/schemas/plugins/BannerPlugin.json:96:      "description": "The banner as string, it will be wrapped in a comment",
./node_modules/sshpk/lib/formats/pem.js:76:	/* Begin and end banners must match key type */
./node_modules/sshpk/lib/formats/pem.js:222:	/* PKCS#1 type keys name an algorithm in the banner explicitly */
./node_modules/terser-webpack-plugin/dist/options.json:146:            "banner": {
./node_modules/terser-webpack-plugin/dist/index.js:278:              // Add a banner to the original file
./node_modules/terser-webpack-plugin/dist/index.js:279:              if (this.options.extractComments.banner !== false) {
./node_modules/terser-webpack-plugin/dist/index.js:280:                let banner = this.options.extractComments.banner || `For license information please see ${_path.default.posix.basename(commentsFile)}`;
./node_modules/terser-webpack-plugin/dist/index.js:282:                if (typeof banner === 'function') {
./node_modules/terser-webpack-plugin/dist/index.js:283:                  banner = banner(commentsFile);
./node_modules/terser-webpack-plugin/dist/index.js:286:                if (banner) {
./node_modules/terser-webpack-plugin/dist/index.js:287:                  outputSource = new _webpackSources.ConcatSource(`/*! ${banner} */\n`, outputSource);
./node_modules/codemirror/rollup.config.js:6:    banner: `// CodeMirror, copyright (c) by Marijn Haverbeke and others
./node_modules/select2/dist/js/select2.js:36:  // The inner file should be wrapped (by `banner.start.js`) in a function that
./node_modules/select2/dist/js/select2.full.js:36:  // The inner file should be wrapped (by `banner.start.js`) in a function that
./node_modules/select2/src/js/wrapper.start.js:36:  // The inner file should be wrapped (by `banner.start.js`) in a function that
./node_modules/bootstrap-switch/package.json:128:    "js:build": "npm-run-all js:build:dir -p js:build:base js:build:min -s js:build:banner",
./node_modules/bootstrap-switch/package.json:129:    "js:build:banner": "headr dist/js/bootstrap-switch.js -o dist/js/bootstrap-switch.js --version --homepage --author --license && headr dis
```

So, I installed a new project, recompiled the assets in voyager before installation, created the migrations, models and BREAD like in my description and the problem still appears.

Then I edit the bread and **only** change the slug from `banners` to something else (`bannieres` for example) and the relation works correctly when adding a new Banner item via BREAD.

**Comment by MrCrayon** [comment]
Files in node_modules are only used for compilation, just wanted to verify and I'll try to reproduce the problem

**Comment by MrCrayon** [comment]
Disable add block or whitelist the site, looks like they don't like the word banner.

**Comment by ghost** [comment]
You're right! I did not notice the "badge" on the µBlock icon!!
Sorry for the unrelated issue, thanks for your help!

**Comment by MrCrayon** [comment]
np, I actually had a very similar problem with different words when I was building a platform managing landing pages and advertisement campaigns I just didn't think about it at start.
