### ISSUE TITLE
Allow to use accessor for order display column

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4632]
## Description of problem
When ordering Bread Items, we can only choose an existing column. If we want to use some extra criteria to choose how to order the items, we must remember their values or open another window/tab, take notes, whatever.
For example, I want to order the burgers presented on the menu of a restaurant. I may want to have more information than the name: the name and the price, maybe a limit date. It would help the user to order items, depending on different criteria: basically based on the price, then the name, but maybe I want a burger to have more visibility, so I would push it on top based on lower sales.

## Proposed solution
Allow to use an accessor instead of a column. The accessor would return a string which would be displayed instead of the value of a column.

## Alternatives considered
An alternative would be to store the required data in a column, which would be updated with the required information. Not really satisfiable for such a simple thing as display information.

**Comment by MrCrayon** [comment]
Would this one #4429 solve the problem?

**Comment by ghost** [comment]
Honestly, yes. And honestly, I did search. Obviously, I did not find it. Maybe I forgot to search in PRs and only search in issues... Sorry for that.

**Comment by MrCrayon** [comment]
Honestly search could be much better in github so np :wink:

**Comment by MrCrayon** [comment]
BTW I asked for changes for that PR because I like the idea but not the implementation, but maybe the author is busy right now because he didn't reply so maybe I'll step in in a near future.
