### ISSUE TITLE
Refused to apply style from 'https://vroumtest.000webhostapp.com/admin/voyager-assets?path=css%2Fapp.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled

### ISSUE THREAD

**Issue by abdelkadergelany** [thedevdojo/voyager#4635]
![Untitled](https://user-images.githubusercontent.com/52650657/70949487-1e0c8700-2088-11ea-8309-0e948a4d0310.png)

## Version information

 - Laravel: v6
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: [Mysql] [version] (e.g. MySQL 5.0.12)

## Description

Everything is working fine on localhost. but after deployment on production webserver. I am getting the error. 

## Steps To Reproduce
1. Go to 'install voyager on localhost'
2. Then 'deploy on production server' (in my case 000.webhostapp.com)
3. And 'try to login'
4. You will see the CSS does not apply. you can observe from the screenshot on the left you have the actual output on the right you have the error shown by the console. and in the console, you can see the error (...because its mime type...etc..)

## Expected behavior
I was expecting everything to display just like on the localhost. But the CSS does not apply

## Additional context
Everything works perfectly on localhost

**Comment by MrCrayon** [comment]
You'll need to provide some more informations: 
 - How the content looks like for that file? 
 - How the response headers look like? 
 - What are the other errors? 

Also please always provide full versions like 1.3.0

**Comment by abdelkadergelany** [comment]
> You'll need to provide some more informations:
> 
> * How the content looks like for that file?
> * How the response headers look like?
> * What are the other errors?
> 
> Also please always provide full versions like 1.3.0

I provided more details. Thanks

**Comment by MrCrayon** [comment]
> I provided more details. Thanks

Not the informations I asked, you need to check in Network tab.

**Comment by abdelkadergelany** [comment]
> > I provided more details. Thanks
> 
> Not the informations I asked, you need to check in Network tab.

My network tab is empty. 
My Response Header:

content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Tue, 17 Dec 2019 08:18:54 GMT
server: awex
status: 200
x-content-type-options: nosniff
x-request-id: 4d3a06e3275735d67cbc57c6fadd2a20
x-xss-protection: 1; mode=block

My Request Header:

:authority: vroumtest.000webhostapp.com
:method: GET
:path: /admin/voyager-assets?path=css%2Fapp.css
:scheme: https
accept: text/css,*/*;q=0.1
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,fr;q=0.8
cookie: _ga=GA1.2.1246130429.1571720651; _gid=GA1.2.939893480.1576529622
referer: https://vroumtest.000webhostapp.com/admin/login
sec-fetch-mode: no-cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36


Query string parameter:
path: css/app.css

**Comment by MrCrayon** [comment]
It's quite unlikely this problem is related to Voyager, more probably some problem with configuration or some strange server setup. 

Said that if you want to solve it you'll need to be more proactive debugging this. 

You only provided informations about one point out of three asked.

**Comment by abdelkadergelany** [comment]
problem solved.it was due to some blank line i left in my helpers class
