### ISSUE TITLE
Facade\Ignition\Exceptions\ViewException SQLSTATE[HY000] [1045] Access denied for user

### ISSUE THREAD

**Issue by kalikim** [thedevdojo/voyager#4639]
i have laravel project i tried hosting it on a shared hosting but i keep getting this error, kindly help

Facade\Ignition\Exceptions\ViewException
SQLSTATE[HY000] [1045] Access denied for user 'dbuxxxxxx'@'infongws-eu10.clienthosting.eu' (using password: YES) (View: /homepages/12/d4295015629/htdocs/xxxxxx/vendor/tcg/voyager/resources/views/login.blade.php)

log message : No Database connection yet in VoyagerServiceProvider loadAuth()

**Comment by fletch3555** [comment]
That error message isn't making any sense to me... are you making database calls directly from your view file?

The "log message" line makes a little more sense, though I'm not sure how it got that far without the database connection being setup.  This tells me that either your database connection info is missing (from config/database.php, or .env), or something about it is wrong

**Comment by MrCrayon** [comment]
Please provide all informations requested in issue template. 
Then you can reopen the issue or create a new one.
