### ISSUE TITLE
Class VoyagerAuth does not exist (View: **/vendor/tcg/voyager/resources/views/master.blade.php)

### ISSUE THREAD

**Issue by ayazdev** [thedevdojo/voyager#4642]
- Laravel: v5.6.*
 - Voyager: v1.3.*
 - PHP: 7.2.11
 - Database: MySQL 5.0.12

## Description

After updating voyager from 1.2 to 1.3 I am getting getting an error. Here is exception 

`Class VoyagerAuth does not exist (View: /var/www/html/****/vendor/tcg/voyager/resources/views/master.blade.php` 

## Steps To Reproduce
1. Update voyager 1.2 to 1.3
2. Create Admin through command
3. Go To /admin/login
4. Put email and password 
5. See errors

## Expected behavior
You will get an exception as following 
`Class VoyagerAuth does not exist (View: /var/www/html/****/vendor/tcg/voyager/resources/views/master.blade.php)`

## Screenshots
Here is screenshot 

https://imgur.com/RbX48ER

**Comment by MrCrayon** [comment]
There is no VoyagerAuth in master.blade.php for v1.3.0:
https://github.com/the-control-group/voyager/blob/v1.3.0/resources/views/master.blade.php

It looks like some of your files are not updated.

Can you try to remove vendor/tcg folder and run `composer install`?

**Comment by ayazdev** [comment]
@MrCrayon I solved it by using below command 
`php artisan view:clear`

**Comment by MrCrayon** [comment]
oh yes, I forgot about cache!

Good, we can close here.
