### ISSUE TITLE
Voyager version 1.0 bootstrapValidator is not a function on admin

### ISSUE THREAD

**Issue by developer2-wis** [thedevdojo/voyager#4672]
## Version information

 - Laravel: v5.5.33
 - Voyager: v1.0.14
 - PHP: 7.1.14
 - Database:  MySQL 8.0

## Description:
I am using Voyager admin for my Laravel Website http://mllmconcepts.webindiasolutions.co.in/.
I am facing an issue on feild validation. Voyager says "The <fieldname> field is required" always even if the feild is not empty.
When I check the console, it shows "Uncaught TypeError: $(...).bootstrapValidator is not a function".
I dont know where is come from.

Also validateBread is failed.(Returns validations errors as ajax responce)

## Additional context
Here I include a screenshot :
 https://prnt.sc/qj6dd9
https://prnt.sc/qj6vms
https://prnt.sc/qj6vqh

**Comment by MrCrayon** [comment]
Please fill the actual versions you are using for Laravel, Voyager and PHP with all three numbers.

**Comment by developer2-wis** [comment]
> Please fill the actual versions you are using for Laravel, Voyager and PHP with all three numbers.

 - Laravel: v5.5.33
 - Voyager: v1.0.14
 - PHP: 7.1.14
 - Database:  MySQL 8.0


Updated -- Sorry for the missing

**Comment by MrCrayon** [comment]
> * Voyager: v1.0.14
> Updated -- Sorry for the missing

No problem, unfortunately that's a quite old version, two years old, and I'm unable to test it.

The best thing you could do is trying to update your platform gradually in a locale enviroment following all upgrade guides.

If for some reason you can't upgrade I would start checking if you changed something when this problem started.
I don't think bootstrap-validator was ever used in this package but I might be wrong, maybe you have a custom view?

**Comment by developer2-wis** [comment]
> > * Voyager: v1.0.14
> >   Updated -- Sorry for the missing
> 
> No problem, unfortunately that's a quite old version, two years old, and I'm unable to test it.
> 
> The best thing you could do is trying to update your platform gradually in a locale enviroment following all upgrade guides.
> 
> If for some reason you can't upgrade I would start checking if you changed something when this problem started.
> I don't think bootstrap-validator was ever used in this package but I might be wrong, maybe you have a custom view?

**Thank you** for your replay. I am updated my version and now it is working fine.
