### ISSUE TITLE
Laravel Model Loggable

### ISSUE THREAD

**Issue by alkhachatryan** [thedevdojo/voyager#4676]
## Description of problem
Hello colleagues! We are using the Voyager in our big project back office.
We have a 20 data-managers, who works on multiple BREAD structures - Posts, Media files, Documents, etc.
So we decided to track  them and see which person worked on which model, what did and how.

## Proposed solution
I created the package, which will log in the files and in DB the BREAD changes from current user.
Checkout the table structure, so you can understand the way logger works (user ID can be null, because other cron jobs or daemons can modify the data).
![image](https://user-images.githubusercontent.com/22774727/71782741-ff4e4000-2ff6-11ea-9184-ff7d79a7b5e4.png)

## Additional context
This is the package I created for Laravel:
https://github.com/alkhachatryan/laravel-loggable

Check it out please, and let me know, do we need it included in Voyager so I can start PR creation

**Comment by fletch3555** [comment]
Looks interesting, but I don't see us adding it to Voyager directly.  Perfect candidate for a Hook though!

**Comment by Emerica** [comment]
https://github.com/yajra/laravel-auditable
We ended up using this for others trying to do similar things.

**Comment by alkhachatryan** [comment]
@Emerica  you cannot compare Yajra's and my package, be cause they are very different

**Comment by alkhachatryan** [comment]
@emptynick @marktopper @tnylea @akazorg 
What you think about it?

**Comment by alkhachatryan** [comment]
@fletch3555 
Looks like you have some bug here:
![image](https://user-images.githubusercontent.com/22774727/71811968-6f100980-308f-11ea-8300-c97a323fac97.png)

As my package name in composer json is:     "name": "alkhachatryan/laravel-loggable",

**Comment by MrCrayon** [comment]
@alkhachatryan where is that error coming from?

**Comment by marktopper** [comment]
Its from larapack.io? However, I do believe your package has nothing with Voyager too do, larapack.io is meant for Voyager packages only.
Voyager packages, unlike normal Composer packages, must **NOT** include a `/` sign in the package name in composer.json, instead call it something like `voyager-loggable`.

**Comment by alkhachatryan** [comment]
Thanks, will do, @marktopper
