### ISSUE TITLE
Lowercase table on server losting 'bread'

### ISSUE THREAD

**Issue by hermesalvesbr** [thedevdojo/voyager#4679]
## Version information

 - Laravel: v5.8
 - Voyager: v1.3
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

When I was developing on my computer I made the tables with the first letter capitalized, when going up to the server was giving error.

My computer: Table
On server: table

## Steps To Reproduce
1. Go to 'Breads'
2. There is no bread made for the table as it is now written in lowercase

## Screenshots
![Captura de Tela 2020-01-06 às 22 58 43](https://user-images.githubusercontent.com/379850/71862301-20d32880-30d8-11ea-879d-b25831a62bac.png)
![Captura de Tela 2020-01-06 às 22 55 37](https://user-images.githubusercontent.com/379850/71862304-216bbf00-30d8-11ea-880b-a7e35907c303.png)
![Captura de Tela 2020-01-06 às 22 59 33](https://user-images.githubusercontent.com/379850/71862323-38aaac80-30d8-11ea-80ec-894dea85463e.png)

## Additional context
I have changed in mysql to accept tables written in upper or lower case, but I think there is something in Voyager that does not allow to be insensitive.

**Comment by MrCrayon** [comment]
> ## Version information
> * Laravel: v5.8
> * Voyager: v1.3

Please fill all three version numbers like v1.3.1
I'm guessing you are using some version of Windows (case insensitive) in your local machine and a Linux distro (case sensitive) in your server.

If you check with PHPMyAdmin or some other tool your database in your server are tables lowercase?

Voyager manage case sensitive tables just fine as fas as I can tell, I think someway your tables were lowercased when you copied your database from local to server.

This works on Linux:
![Schermata da 2020-01-07 03-44-38](https://user-images.githubusercontent.com/6875243/71864454-19277a00-3100-11ea-9a36-4a72cf1da52d.png)

**Comment by hermesalvesbr** [comment]
Hi,

I'm using Mac Os Catalina(Table), yes, the table on server(table) are lowercase. 

Laravel Framework 5.8.35
 "pvtl/voyager-forms": "^0.4.1",
        "tcg/voyager": "^1.3"

How can i change on voyager the Table for table?

**Comment by MrCrayon** [comment]
> How can i change on voyager the Table for table?

In your database `data_types.name` and `permissions.table_name`

If that fixes it please close the issue.

**Comment by hermesalvesbr** [comment]
Thank you very much. That's works.
