### ISSUE TITLE
Plan whether to implement Ldap Authentication？

### ISSUE THREAD

**Issue by dizzying** [thedevdojo/voyager#468]
Ldap Authentication is very useful in enterprise.

The package is awesome:

https://github.com/Adldap2/Adldap2-Laravel

**Comment by handiwijoyo** [comment]
@dizzying is there any feature you want to use from Adldap2?

**Comment by dizzying** [comment]
My company Deploy Windows Active directory as the user account system, Users can use same account to log in many systems, like email, NAS, video surveillance, etc.
If voyager can implement Ldap Authentication, then the system that base voyager can use same user account system.
thx.

**Comment by marktopper** [comment]
Well, it might already work with authentication using the package that you provided, however then permissions and list of users will not work out of the box.
However I'm open for pull requests that makes it possible to extend Voyager in a way that makes it possible for you to add customize it for your usage.

> Note: Please note that I can not quarante what I just said, since I have never actually tried it. This is just from reading the documentation.

**Comment by fletch3555** [comment]
Currently Voyager requires the built-in Laravel Auth scaffolding, so it will not support LDAP authentication.  If someone wishes to implement this, I think it would best be done as a [Hook](https://larapack.io/).  Closing for now

**Comment by jeremiahsherrill** [comment]
It would be awesome if this support ldap

**Comment by Baysen** [comment]
Would like this as well, since we would be using it for company internal services and the users are used to being able to login with their Windows credentials.
> however then permissions and list of users will not work out of the box.

They don't need to. Users usually already are in groups in LDAP. If you could just clone them and then give them permissions manually, it would be more than sufficient.

**Comment by jeremiahsherrill** [comment]
Should anyone ever come across this, voyager works perfectly with adldap2/adldap-laravel 

- Create Your Install
- php artisan make:auth
- composer require adldap2/adldap2-laravel
-  https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction // draw the rest of the owl

**Comment by jomisa** [comment]
> Should anyone ever come across this, voyager works perfectly with adldap2/adldap-laravel
> 
> * Create Your Install
> * php artisan make:auth
> * composer require adldap2/adldap2-laravel
> * https://adldap2.github.io/Adldap2-Laravel/#/auth/introduction // draw the rest of the owl

Voyager version: 1.3
Laravel version: 6.18.3

Thats right!!!!! but two things to keep in mind:

1. No need to run "php artisan make:auth" voyager does the job

2. adldap2 (active directory) needs an "objectguid" column (its an guid, 36 char) in users table, so add that column to users table
`ALTER TABLE users ADD objectguid varchar(36) NULL;`
