### ISSUE TITLE
Call to undefined method stdClass::getKey() 

### ISSUE THREAD

**Issue by Sanswan** [thedevdojo/voyager#4681]
## Version information

 - Laravel: v6.10.0
 - Voyager: v1.3.1
 - PHP: 7.2.26
 - Database:  MySQL 5.7.28
- Ubuntu 18.04.1

## Description

Call to undefined method stdClass::getKey() (View: /var/www/*****************/html/planning/vendor/tcg/voyager/resources/views/formfields/image.blade.php)

vendor/tcg/voyager/src/../resources/views/formfields/image.blade.php:5

data-file-name="{{ $dataTypeContent->{$row->field} }}" data-id="{{ $dataTypeContent->getKey() }}"

## Additional context
When i click on block content in admin page i get this error.
the image are showing and the frontend page is working. 
i only get this error 

i don't understand the error!

**Comment by MrCrayon** [comment]
Very strange error, we will need some more informations: 
 - Is this a new install or you just updated?
 - Did you override some templates or controllers? 

 - Try to copy that blade file and put it into:
 `{your_app_folder}/resources/views/voyager/formfields/`
Then put a `@php dd($dataTypeContent) @endphp` before the line causing the error and report the first line of the output.

**Comment by Sanswan** [comment]
**Is this a new install or you just updated?**

Yes this is a new installation, i have did Composer create-project laravel/laravel planning.
then i have make the installation from the original voyager documentation with composer.

On the moment that i install the page-blocks it just works ok and don't get any error. 

**Did you override some templates or controllers?**

thats a good question when i do the voyager installation butt don't install the page blocks everything works fine.

**Try to copy that blade file and put it into:**

i while try that soon
thanks

**Comment by MrCrayon** [comment]
What's the address where you get the error?

**Comment by fletch3555** [comment]
Wait, you said you're using page blocks... are you referring to this package? https://github.com/pvtl/voyager-page-blocks

If it works before installing it, and is broken after, then the issue is likely with that package.  We don't manage that package, so you would need to contact them.  If they're able to reproduce it and identify the cause in our code, they can report it here (or provide a PR to fix it)

**Comment by henryonsoftware** [comment]
I got same problem, when I go to admin and edit theme

**Comment by MrCrayon** [comment]
@henryonsoftware There is no `theme` in Voyager, unless you created a BREAD from a themes table or you are using:
https://github.com/thedevdojo/voyager-themes

If the latter same thing @fletch3555 said applies to you.

**Comment by Sanswan** [comment]
@fletch3555 Thanks i while make a issue for that package. on there GitHub page.

**Comment by henryonsoftware** [comment]
@Sanswan @MrCrayon Finally I found the problem.
v1.3.0 released this PR https://github.com/the-control-group/voyager/pull/4317
They change from `id` to `getKey()`, so the `$dataTypeContent` must be an Model Object to get the primary key by method `getKey()`

If you send the object is not an instance of Model Object, this error with be shown.

Hope this helps!

**Comment by Sanswan** [comment]
@henryonsoftware Thanks for your comment, i already have make that change now i am facing a other issue :) mb_strlen() expects parameter 1 to be string, array given. browse.blade.php on line 185. so i am now try to fix that!
