### ISSUE TITLE
Relationship query filter to get specific data

### ISSUE THREAD

**Issue by yasir-pasha** [thedevdojo/voyager#4682]
## Version information

 - Laravel: v6.10.0
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: [MariaDB] [10.4]

## Description

I got an option get specific type users through relationship. For example create a relationship products bread with users table. When I try to create a product the relationship get all users. But I want to get only users that has specific role.

**Comment by fletch3555** [comment]
Questions about how to implement something should be asked in slack, not here.  This is mentioned in the issue template.

Please check the docs (both Laravel and Voyager) for query scopes
