### ISSUE TITLE
get_class() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by Sanswan** [thedevdojo/voyager#4683]
**Version information**

 - Laravel: v6.10.0
 - Voyager: v1.3.1
 - PHP: 7.2.26
 - Database: MySQL 5.7.28
 - Ubuntu 18.04.1
**Description**

In admin panel the button Users give me this error

get_class() expects parameter 1 to be object, string given (View: /var/www/**********************/html/planning/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:4
vendor/tcg/voyager/src/../resources/views/bread/partials/actions.blade.php:4

** Expected behavior**
$class = get_class($action);

Is this a problem in the new version of voyager ( 1.3 ) ?

**Comment by MrCrayon** [comment]
Please check https://github.com/the-control-group/voyager/issues/4398

**Comment by Sanswan** [comment]
@MrCrayon Thanks i have make the changes to the blades, everything is working.

**Comment by insology** [comment]
@Sanswan how you solved the issue?
