### ISSUE TITLE
Trying to integrate voyager with chatter but I get an error to create chatter_discussion bread

### ISSUE THREAD

**Issue by TommyRoy776** [thedevdojo/voyager#4684]
## Version information
 - Laravel: v5.5.48
 - Voyager: v1.3.1
 - PHP: 7.4.1
 - Database: MySQL 5.7.28

## Description
I set the model name as devdojo\chatter\Models\Discussion in Voyager bread then I got this error 

`ReflectionException`` thrown with message "Class devdojo\chatter\Models\Discussion does not exist"
Stacktrace:
#62 ReflectionException in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Container\Container.php:752
#61 ReflectionClass:__construct in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Container\Container.php:752
#60 Illuminate\Container\Container:build in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Container\Container.php:631
#59 Illuminate\Container\Container:resolve in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Container\Container.php:586
#58 Illuminate\Container\Container:make in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:732
#57 Illuminate\Foundation\Application:make in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:110
#56 app in C:\Users\roy12\camplus2\vendor\tcg\voyager\src\Models\DataType.php:99
#55 TCG\Voyager\Models\DataType:updateDataType in C:\Users\roy12\camplus2\vendor\tcg\voyager\src\Http\Controllers\VoyagerBreadController.php:97
#54 TCG\Voyager\Http\Controllers\VoyagerBreadController:store in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#53 call_user_func_array in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:54
#52 Illuminate\Routing\Controller:callAction in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:45
#51 Illuminate\Routing\ControllerDispatcher:dispatch in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Route.php:212
#50 Illuminate\Routing\Route:runController in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Route.php:169
#49 Illuminate\Routing\Route:run in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Router.php:658
#48 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\tcg\voyager\src\Http\Middleware\VoyagerAdminMiddleware.php:26
#46 TCG\Voyager\Http\Middleware\VoyagerAdminMiddleware:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#43 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:68
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#34 Illuminate\Session\Middleware\StartSession:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#25 Illuminate\Pipeline\Pipeline:then in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Router.php:660
#24 Illuminate\Routing\Router:runRouteWithinStack in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Router.php:635
#23 Illuminate\Routing\Router:runRoute in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Router.php:601
#22 Illuminate\Routing\Router:dispatchToRoute in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Router.php:590
#21 Illuminate\Routing\Router:dispatch in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\fideloper\proxy\src\TrustProxies.php:56
#18 Fideloper\Proxy\TrustProxies:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:30
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:46
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:149
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:102
#3 Illuminate\Pipeline\Pipeline:then in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\Users\roy12\camplus2\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in C:\Users\roy12\camplus2\public\index.php:55
#0 require_once in C:\Users\roy12\camplus2\server.php:21
`

## Screenshots
![problem](https://user-images.githubusercontent.com/53387849/72123970-1364ab00-3331-11ea-86e9-541f1ab611b9.PNG)

**Comment by MrCrayon** [comment]
You need to input the correct Namespace, try with:
`DevDojo\Chatter\Models\Discussion`

**Comment by TommyRoy776** [comment]
Yeah, I fixed my problem thx
