### ISSUE TITLE
Media picker breadcrumbs bug

### ISSUE THREAD

**Issue by prokhorenko-vladyslav** [thedevdojo/voyager#4685]
## Version information

 - Laravel: v6.9.0
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: MySQL 5.6

## Description

In media manager, when got to folder then back using breadcrumbs and go to this folder again path become incorrect.

## Steps To Reproduce
1. Go to 'Media'
2. Click on any folder and go to subfolder
3. Click on previous folder breadcrumb
4. Go to this folder again
4. See on the path

## Additional context
To fix this problem need go to the /vendor/tcg/voyager/resources/views/media/manager.blade.php -> method "setCurrentPath" and add after "this.current_folder = this.basePath+path.join('/');" next line "this.current_folder += "/";"

**Comment by MrCrayon** [comment]
Thanks for reporting this, can you submit a PR?
