### ISSUE TITLE
How to search for Chatter discussion id in Bread search bar  

### ISSUE THREAD

**Issue by TommyRoy776** [thedevdojo/voyager#4688]
## Version information

Laravel: v5.5.48
Voyager: v1.3.1
PHP: 7.4.1
Database: MySQL 5.7.28

## Description of problem
I integrate Voyager with Chatter and created Chatter discussion bread and Chatter post bread.
I want to get all post from a specific discussion. Any way to do it?

Screenshot:
![chatter](https://user-images.githubusercontent.com/53387849/72196091-e8875f00-33e3-11ea-9b03-8ac91b888962.PNG)

**Comment by MrCrayon** [comment]
As the issue template says questions should be asked on Voyager Slack group, in the right channel. 

We prefer to keep github for bug reports and feature requests.
