### ISSUE TITLE
select dropdown relationship not show name field

### ISSUE THREAD

**Issue by md3e** [thedevdojo/voyager#469]
- Laravel Version: 3.5.#
- Voyager Version: 0.10.7
- PHP Version:
- Database Driver & Version:

### Description:
Hi

from dropdown relationship can select name of field, but for browse datatable just showing field id.
Please advise.;

Attached picture.
![skincut](https://cloud.githubusercontent.com/assets/23514728/21575972/dda224ba-cf52-11e6-8f48-2668be72170e.png)

**Comment by handiwijoyo** [comment]
The browse view need to display correct relationship value instead of key value. I will add this to todo list

**Comment by sidis405** [comment]
#715

**Comment by marktopper** [comment]
This seems to have been fixed
