### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by moh6mmad** [thedevdojo/voyager#4691]
Since yesterday when i deploy the site, menu goes like this but everything is fine in local
Any idea?
![image](https://user-images.githubusercontent.com/6563436/72206412-46747f00-3496-11ea-9297-f764587e56c9.png)

**Comment by moh6mmad** [comment]
This is page source on internet after deployed:
![image](https://user-images.githubusercontent.com/6563436/72206422-64da7a80-3496-11ea-8c39-ff46bdf3cfb9.png)
This is how the source looks on local:
![image](https://user-images.githubusercontent.com/6563436/72206424-699f2e80-3496-11ea-9023-6ef397c2ce64.png)

**Comment by MagedAhmad** [comment]
Try to delete `public/storage` folder then run `php artisan storage:link`

**Comment by moh6mmad** [comment]
Hey. The issue is printing JSON in source not storage lol

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.

**Comment by moh6mmad** [comment]
Any idea to resolve this?

**Comment by fletch3555** [comment]
@Mohamm6d, per @emptynick's comment, you need to supply the required information.  Without it, we have no way of knowing what version of Voyager/Laravel/etc you're using for example.  This makes testing and research very difficult for us, which is why we require it or we can't help
