### ISSUE TITLE
Sort ascending with server-side pagination. 

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#4693]
- Laravel: v6.10.1
 - Voyager: v1.3.1
 - PHP: 7.2.25
 - Database: mariadb 10.3.20

## Description
Sort ascending doesn't work it always defaults to descending. 

## Steps To Reproduce
1. Go to BREAD 
2. Click on Server-side Pagination
3. Sort via column in ascending order.
4. Default sort is descending order. 

## Screenshots
<img width="1131" alt="Screenshot 2020-01-12 at 08 39 54" src="https://user-images.githubusercontent.com/533658/72216297-26d16b00-3517-11ea-853b-ee2f3a84cf12.png">

## Additional context
Problem is because the order_direction is never used. 
`$sortOrder = $request->get('sort_order', $dataType->order_direction);` 

https://github.com/the-control-group/voyager/pull/4690/commits/ae8f0f1819d8331ef33e3a29c160d51384a5d605

**Comment by MrCrayon** [comment]
Fixed in #4557 needs to be merged.

That fix you posted is not going to work for both server and client side ordering.
