### ISSUE TITLE
Creating Custom Bulk Action for DataType

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4695]
## Description
I Created new Custom Bulk action for datatype as given,
1. Copied the **resources/views/partials/bulk-delete.blade.php** and pasted it into the new file named **resources/views/partials/bulk-process.blade.php**. I slightly modified the code inside the file. I modified the Route, Script, and appearance of the button.
2. I've used the code block given into the **resources/views/bread/browse.blade.php**
```php
@if($dataType->modal_name == 'App\Order')
    @include('voyager::partials.bulk-process')
@fernandonicacio 
```
But it doesn't work.

How to create new Custom Bulk action?

**Comment by MrCrayon** [comment]
As the issue template says

> IF YOU'RE POSTING A QUESTION ABOUT HOW TO USE VOYAGER, PLEASE CONSIDER ASKING IN SLACK FIRST

**Comment by vkiranmaniya** [comment]
@MrCrayon I'm apologetic, But slack is full of users and i can't get in. So i've posted the question here. Buy the way I solved out the query and it's working fine.

**Comment by MrCrayon** [comment]
@vkiranmaniya thanks, I'll tell Voyager Slack admins to check.
Good you solved but you can create bulk actions with method explained here:
https://voyager-docs.devdojo.com/customization/action-buttons
check at the end.

**Comment by fletch3555** [comment]
Slack's free tier(which we're on) does not have a user limit as far as I'm aware.  There shouldn't be anything like that denying your login.  For example, Larachat currently has nearly 30000 users in the default announcement channel.  Our default general channel has only 3500.

**Comment by vkiranmaniya** [comment]
@fletch3555 I think you should move on [https://mattermost.com/](MatterMost), It's open source and self-hosted alternative of slack.

**Comment by fletch3555** [comment]
That may be true, but we haven't had any issues with our current platform.  Switching adds complexity and confusion for our users, for what we perceive to be minimal benefit.
