### ISSUE TITLE
the url of menu_items will not be loaded correctly if my website is not on root directory

### ISSUE THREAD

**Issue by taoyu65** [thedevdojo/voyager#470]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
my website is not on root directory and i logged in, the url of menu_items will not be loaded correctly, so i found the problem and add method url() , this can be fixed.
![image](https://cloud.githubusercontent.com/assets/18646762/21576440/735c3de8-cee4-11e6-8c09-ebf36b7aec5f.png)

**Comment by handiwijoyo** [comment]
@taoyu65 Hi, thanks man. It will be wonderful if you can open a PR for this.
