### ISSUE TITLE
Too long to login admin

### ISSUE THREAD

**Issue by meesudzu** [thedevdojo/voyager#4700]
## Version information

 - Laravel: v5.8
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: MySQL 5.7

## Description

Too long to take login. I have check in console and see "Unchecked runtime.lastError: The message port closed before a response was received."

## Steps To Reproduce
1. Go to /admin
2. Login

**Comment by MrCrayon** [comment]
That error is most likely unrelated to Voyager as it is the time it takes for login that can depend from multiple factors.

Try disabling your browser extensions and see if that error goes away, as for the speed as said it depends from many factors and Voyager as little to do with it.

**Comment by MrCrayon** [comment]
@meesudzu of you solved please close the issue.
