### ISSUE TITLE
voyager admin panel menu icons not appeared 

### ISSUE THREAD

**Issue by farghalyReine** [thedevdojo/voyager#4706]
## Version information

 - Laravel: v6.10.1
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description of problem

After i create new menus in voyager admin panel icons not appeared 
![image](https://user-images.githubusercontent.com/60061206/72681024-8eb02480-3ac8-11ea-9d49-dd56074df3ef.png)

![image](https://user-images.githubusercontent.com/60061206/72681037-9ff93100-3ac8-11ea-9224-28841e664c55.png)

note when i click on "Voyager Font Class" hyper link it refer to http://localhost/admin/compass#fonts 
not 
http://localhost/myproject/admin/compass#fonts 

thanks in advance

**Comment by MrCrayon** [comment]
How is this a feature request? 

Anyway informations requested like Voyager version are not optional. 

Fill the data requested and try to be more clear about what you are doing and what's the problem.
I can see preesistent menu icons are shown, so it's quite probable you are doing something wrong.

**Comment by farghalyReine** [comment]
> How is this a feature request?
> 
> Anyway informations requested like Voyager version are not optional.
> 
> Fill the data requested and try to be more clear about what you are doing and what's the problem.
> I can see preesistent menu icons are shown, so it's quite probable you are doing something wrong.

thanks for your concern 
the standard menu icons is appear but the created menus like sliders - facts - services .... etc not appear and i don't know why ?

**Comment by fletch3555** [comment]
What have you set for those icon values in the menu item? Please provide a screenshot of the menu editor

**Comment by farghalyReine** [comment]
> What have you set for those icon values in the menu item? Please provide a screenshot of the menu editor

![image](https://user-images.githubusercontent.com/60061206/72682812-e73bed80-3ad9-11ea-8f69-a3c80f140dfd.png)

**Comment by fletch3555** [comment]
No, that's the BREAD editor, and that field sets the icon at the top of the BREAD pages, as well as the default value for the menu when BREAD is created.  If you change it later, you also have to change it directly in the menu editor

**Comment by farghalyReine** [comment]
> No, that's the BREAD editor, and that field sets the icon at the top of the BREAD pages, as well as the default value for the menu when BREAD is created. If you change it later, you also have to change it directly in the menu editor

thanks :D it fixed now 
i hope have a good day :D
