### ISSUE TITLE
Override vendor\tcg\voyager\src\Http\Controllers\Controller.php method insertUpdateData()

### ISSUE THREAD

**Issue by PeterPan73** [thedevdojo/voyager#4708]
## Version information

 - Laravel: v5.8
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: MySQL 8.0

## Description of problem

How I can override vendor\tcg\voyager\src\Http\Controllers\Controller.php method insertUpdateData?
Does anyone have a solution?

**Comment by emptynick** [comment]
Please ask questions in our slack group (as you already did).

**Comment by PeterPan73** [comment]
When I write no one answers me. Please do not close this issue/question.
