### ISSUE TITLE
[Discussion] Use intervention/imagecache to create derived images

### ISSUE THREAD

**Issue by oschettler** [thedevdojo/voyager#471]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.7
- PHP Version: 7.0.14

### Curent implementation:

Currently, there is a means to create derived images on save, using a JSON structure to configure the desired image derivatives. This is [described in the documentation](https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-additional-field-options) and implemented [in the Controller class](https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L132).This works well for images that are managed through a BREAD interface, e.g. as part of posts or pages. 

### Problematic use case:

It cannot be used for images that are imported from an external source, e.g. product images. For these cases however, thumbnails can be created on the fly, using the [capability of imagecache](http://image.intervention.io/use/url) to access derived images through a specifically formatted URL `/imagecache/<format>/<image-path>`. 

In my website, there are now two competing mechanisms to arrive at derived images: 

* On *save* for BREAD-managed images
* On *access,* for images acquired through other sources

### Proposed solution:

I wonder if it would make sense to replace all of Voyager's derive-image-on-save mechanics with an integration of Imagic Imagecache. Specifically, we would use [their URL-based manipulation](http://image.intervention.io/use/url). This seems to be the more general and flexible solution:

* *General,* because I can create derivative images for both kinds of images. 
* *Flexible,* because I can add new derived image formats as my site requires them, without re-saving all images.

Best of all, the Voyager code to create derived images on *save* could be removed. 

What do you think?

**Comment by fletch3555** [comment]
Forgive me as I'm not very familiar with this library/functionality.

Does this generate the images on-the-fly (as in, on each request)? Or does it cache images somehow?  If it generates it on each request, this could cause issues (though that would easily be fixed with a simple site-wide caching layer, CDN or otherwise).  Overall, I actually like the idea.  Just a few details to work out.

**Comment by marktopper** [comment]
Just to be clear, what you want to achieve is a way to create a post with a image, and then use the URL based manipulation for this image.

Am I correct? Then I can look into it.

**Comment by fletch3555** [comment]
Closing due to age.  We're going to be completely refactoring all image upload/manipulation/etc functionality soon anyway.
