### ISSUE TITLE
Model view controller customization according to complex requirements

### ISSUE THREAD

**Issue by voxsync458** [thedevdojo/voyager#4710]
## Version information

 - Laravel: v5.8.*
 - Voyager: v1.2.2
 - PHP: 7.1.3
 - Database: phpMyAdmin

## Description:
I am using voyager in my site. It is very helpful for basic CRUD/BREAD operations but i want to customize few BREADs according to the user requirements. All BREADs are creating on database and vendor level so it will create problem when i will deploy my site to server. Because local and server database is different that's why it will create problem. Please guide me how can i customize BREADs without dependency on database and vendor. Thanks

**Comment by MrCrayon** [comment]
As the issue template says questions should be asked in Voyager slack chat. 

Short answer: nothing changes on vendor, it's all on db and you'll need to sync that. 
How to do it is up to you, maybe someone on Slack already found a solution.
