### ISSUE TITLE
Class 'App\Actions\[ActionClassName]' not found

### ISSUE THREAD

**Issue by amandalevin6** [thedevdojo/voyager#4714]
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.3.0
 - PHP: 7.3.10
 - Database: MySQL

## Description:
I would like to have an action to export data.  I already created the function in my controller and added the route.  I have created my action file under:

 /app/actions/CSVExport.php 

Here are the first few lines of the file:
```
<?php

namespace App\Actions;

use TCG\Voyager\Actions\AbstractAction;

class CSVExport extends AbstractAction
{
    public function getTitle()
    {
        return 'Export';
    }
```
Then I added the following line to /app/providers/AppServiceProvider.php  in the boot function:

`        Voyager::addAction(\App\Actions\CSVExport::class);
`

When I open the bread index page, I get the following error:

> Class 'App\Actions\CSVExport' not found

I don't see any other steps in the documentation to add an action and my previously added actions work if I comment out my new line in AppServiceProvider.php.  Did I miss something?

**Comment by MrCrayon** [comment]
Voyager is looking for the class but it's not finding it, try:
```
composer dump-autoload
```
If that doesn't work double check all your spellings.

Since you are not reporting this as a bug, and most probably isn't, for any other inquiry about this please join Voyager slack chat.

**Comment by amandalevin6** [comment]
Thank you! That was what I was missing.  In the future, I will post on slack.
