### ISSUE TITLE
Cannot type anything on the password section while creating user from CLI

### ISSUE THREAD

**Issue by sarik-k** [thedevdojo/voyager#4717]
## Version information

 - Laravel: v6.9.0
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: MYSQL 5.7.24

## Description

Cannot type anything on the password section while creating user from CLI. If pressed enter without any input, it asks for Confirm Password and when pressed entered again, it says wrong password. 

## Steps To Reproduce
1. Enter this in CLI: `php artisan voyager:admin your@email.com --create`
2. Type your name
3. Try to type the password, nothing happens.

## Expected behavior
I should have been able to enter the password to create a user.

## Screenshots
I don't think it's required.

## Additional context
None.

**Comment by fletch3555** [comment]
Password prompts do not display the characters as you type.

**Comment by sarik-k** [comment]
Oh! Well, learnt something new today I guess. Thanks!
