### ISSUE TITLE
ReflectionException in Container.php line 749: Class TCG\Voyager\Models\Product does not exist

### ISSUE THREAD

**Issue by pcbimon** [thedevdojo/voyager#472]
- Laravel Version: 5.3
- Voyager Version: 0.10
- PHP Version: 5.4
- Database Driver & Version:

### Description:
After pressing Bread to create tables in the database. I get an error "ReflectionException in Container.php line 749:
Class TCG\Voyager\Models\Product does not exist"

**Comment by wtfz** [comment]
If you follow the tutorial from the video, I think you missed the 's' at the end of 'App\Product' in Model Name. Delete the table, make a new one and change to 'App\Products' while adding BREAD. Take a look at issue #355.

**Comment by fletch3555** [comment]
Voyager does not ship with a "Product" model, so I assume this is a model you're creating for yourself.  Based on that, when creating the BREAD, you should set the model class path to something under the "App" namespace (App\Product for example)
