### ISSUE TITLE
The images I upload to the library are not shown

### ISSUE THREAD

**Issue by RoylerMarichal** [thedevdojo/voyager#4725]
## Version information

 - Laravel: v6.0.0
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
After activating the Exif extension in Laragon, it allows me to upload images to the library but once they are not shown, it only gives me the name and size but I don't see them

**Comment by emptynick** [comment]
The information from the issue template are not optional.
This can be reopened when the requested information are provided.
