### ISSUE TITLE
New Created Models And Tables Not Working BREAD UI Bug

### ISSUE THREAD

**Issue by TnCoders** [thedevdojo/voyager#473]
I Created a new Table Name "Sports" and then I added bread to that Table I changed the default App Model name from 'App\Sport' to 'App\Sports' I enabled Server Side pagination, then I gave the admin that permission to view Sports menu after adding it to menu builder. and then when I navigate to Sports menu all I have is this.
![voyager_breadproblem](https://cloud.githubusercontent.com/assets/24681177/21578553/5f9098bc-cf85-11e6-994b-e52e4521047f.PNG)

**Comment by TnCoders** [comment]
@thedevdojo  When i disabled server side pagination it worked
![bread_twice](https://cloud.githubusercontent.com/assets/24681177/21578606/841e5794-cf87-11e6-972f-cd442844fb6f.PNG)
![row](https://cloud.githubusercontent.com/assets/24681177/21578607/841eead8-cf87-11e6-844d-cd2e95cc0eec.PNG)
Now the field is displayed twice even if i have only 1 'sport' filed in the database

**Comment by marktopper** [comment]
Please share the content of the `data_types` and the `data_rows` tables.

**Comment by fletch3555** [comment]
@TnCoders, please respond to @marktopper's request or close this issue.

Thanks!
