### ISSUE TITLE
Is it possible to add image formfield to BREAD without the corresponding field in the database?

### ISSUE THREAD

**Issue by keradan** [thedevdojo/voyager#4730]
## Version information

 - Laravel: v6
 - Voyager: v1.3
 - PHP: 7.4
 - Database: MySQL 8.0

## Description of problem
I don't need special field in database for image, because I will store files by id of model (or other fields like slug) in the filename. So I can't add formfield in BREAD.

## Proposed solution
It would be great to have the ability to add a formfield, without reference to the database field.

I know that I can change generated bread views and use a custom controllers, but I will have a lot of models with images, so I do not want to overwrite all that files. Thanks a lot.

**Comment by fletch3555** [comment]
Per the issue template, questions should be asked in slack.

Having said that, no, not really.  You have a few options.  Either add the field anyway and pre-fill it, or build a custom form field to do exactly what you want.

I'm happy to continue the discussion in slack if needed.

**Comment by keradan** [comment]
In voyager docs I found how to add a custom formfield:
https://voyager-docs.devdojo.com/customization/adding-custom-formfields

This just ads new type of field in select box, but i need to add not type, but field. Shure I can add some field in DB, but the whole point of the question is how to avoid this
