### ISSUE TITLE
Icon in menu not updated if i change icon in Bread

### ISSUE THREAD

**Issue by sereja76** [thedevdojo/voyager#4731]
## Version information
 - Laravel: v6.2
 - Voyager: v1.3
 - PHP: 7.1.3
 - Database: MySQL 5.7.23

## Description

When i make bread and not set icon - its ok, but if i update and set some voyager icon - this icon still not visible in menu.

## Steps To Reproduce
1. I make bread without icon (set empty)
2. Try update bread and set some icon
3. Icon in menu not updated

**Comment by fletch3555** [comment]
Yes, that's correct.  The icon field in the BREAD configuration is for the top of the BREAD pages, whereas the icon field in the menu editor is for the menu entry.  We simply default the menu value to the BREAD value upon creation.

We intentionally decoupled them to allow them to be separate if you wanted.
