### ISSUE TITLE
Using customizing users table name

### ISSUE THREAD

**Issue by KoVaLsKy2010** [thedevdojo/voyager#4732]
## Version information

 - Laravel: v6
 - Voyager: v1.3
 - PHP: 7.1
 - Database: [type] [version] (e.g. PGSQL 10.0)

## Description of problem
I have not USERS table, but in my special project there laravel_users and laravel_roles
I can't install Voyager, because it not using standart Laravel models and ignore in App\User
`protected $table = 'laravel_users';`

## Proposed solution
Add configure for setting table names before( or for ) installing Voyager

**Comment by fletch3555** [comment]
Please follow the "advanced" install procedure and you'll be able to update it: https://voyager-docs.devdojo.com/getting-started/installation#advanced

**Comment by KoVaLsKy2010** [comment]
Thank You!
But how to change using "roles" and 'user_roles" table name?

**Comment by MrCrayon** [comment]
I guess you can override roles method in your User model. 

https://github.com/the-control-group/voyager/blob/1.3/src/Traits/VoyagerUser.php
