### ISSUE TITLE
Fetch page object using translated slug.

### ISSUE THREAD

**Issue by uwejan** [thedevdojo/voyager#4733]
according to `https://voyager-docs.devdojo.com/core-concepts/multilanguage#get-translated-value`
i can fetch language of certain page with. `$page = Page::where('slug', $slug)->withTranslations(['en'])->get();` but doing the same thing for same page for another language still return the original page values. `$page = Page::where('slug', $slug)->withTranslations(['tr'])->get();`
am i getting it wrong?

**Comment by MrCrayon** [comment]
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

If you think it's a bug please provide all information requested in the template and this can be reopened.
