### ISSUE TITLE
Missing required parameters for [Route: voyager.locksaccount.edit]

### ISSUE THREAD

**Issue by nicktan147** [thedevdojo/voyager#4734]
## Version information

 - Laravel: v6.14
 - Voyager: v1.3
 - PHP: 7.2
 - Database: MYSQL 5.6

## Description

Unable to add/view, the moment I open up the page, it shows this error. Even though in the DB, it is successfully created.

## Steps To Reproduce
1. Create Table
2. Create BREAD
3. Add new data
4. Boom!

## Expected behavior
Should show properly

## Screenshots
![create_table](https://user-images.githubusercontent.com/7764638/73807449-78fc6800-4807-11ea-9570-98f2ab665a97.JPG)
![error](https://user-images.githubusercontent.com/7764638/73807452-7e59b280-4807-11ea-8940-b33bfc0801e1.JPG)

**Comment by MrCrayon** [comment]
Laravel will assume you are using `id` as primary key, if you use a non standard name you need to set it in your model.

If that was not the problem you can reopen this issue.
