### ISSUE TITLE
Computed properties / mutators

### ISSUE THREAD

**Issue by jannejava** [thedevdojo/voyager#4737]
## Description of problem
I currently store all prices in cents without VAT for practical reasons. When the user is editing a record I would like them to just enter prices in EUR (VAT included) and Voyager transform the input to cents before writing it to the DB.

## Proposed solution
Some way to define a mutation of a property or that Voyager could "read" Elqoeunt accessors or mutations like ordinary DB-field (maybe way to complicated ;-)). 

## Alternatives considered
I tried to solve this by a dummy field in DB (this was presented to the user, the actual price hidden) and Eloquent event listeners keeping the real field updated, but it felt hacky and not a clean way to do it.

The closest, I found, is maybe custom form fields together with BREAD accessors, but this does not solve the problem of transforming the input before storing it into the DB.

An other option is to create and hard code a entire custom view, but that will most likely break at next big update of Voyager.

I am aware the there are mutators in Eloquent and that you maybe can override a field, but the problem is the rest of the app is expecting in cents and without tax. 

## Additional context
Anyway, thanks for creating this awsome project. :-)

Is this something of interest somebody others, already solved, or has this been discussed?

**Comment by emptynick** [comment]
See https://voyager-docs.devdojo.com/customization/bread-accessors
Also, the issue template is required, even for feature requests.

**Comment by jannejava** [comment]
Bread accessors, how could I miss that? Sorry. Fixed the templating too.
