### ISSUE TITLE
Problems with the "BelongTo" relationship

### ISSUE THREAD

**Issue by Emmanuel-Reynoso** [thedevdojo/voyager#4738]
Hi, first thanks for your help.

## Version information
 - Laravel: v6.2
 - Voyager: v1.3.1
 - PHP: 7.3.10
 - Database: MySQL

## Description of problem
I have problems with the "BelongTo" relationship. I have records in the "estado_actividads" table.

I don't understand what I'm missing. 

![1](https://user-images.githubusercontent.com/32149800/73979573-2ad18c80-490d-11ea-8e96-632c37786693.png)

## Alternatives considered
- Delete the table and create it again.
- I made a relationship with the "User" table and it works correctly.
- Delete the relationship and create it again.

## Additional context
![2](https://user-images.githubusercontent.com/32149800/73980007-1fcb2c00-490e-11ea-9138-643d65f7ceb1.png)

![3](https://user-images.githubusercontent.com/32149800/73980019-2659a380-490e-11ea-95c0-2724634cff86.png)

![4](https://user-images.githubusercontent.com/32149800/73980037-2b1e5780-490e-11ea-8e16-5688810973cb.png)

**Comment by MrCrayon** [comment]
Please take a screenshot of ajax call request and response content to see if all data is passed and if there is an error. 

Voyager version should be three numbers, it looks like you have 1.3.1, please verify and update it in your first comment.

**Comment by Emmanuel-Reynoso** [comment]
> Please take a screenshot of ajax call request and response content to see if all data is passed and if there is an error.
> 
> Voyager version should be three numbers, it looks like you have 1.3.1, please verify and update it in your first comment.

Hi MrCrayon

You're right, now I correct the version. I have the screenshots here. What do you think?

![5](https://user-images.githubusercontent.com/32149800/73993690-b65d1480-4931-11ea-8ac4-d104ba79be5a.png)

![6](https://user-images.githubusercontent.com/32149800/73993694-bbba5f00-4931-11ea-9539-cb0bfb857ed5.png)

**Comment by MrCrayon** [comment]
I don't see anything wrong, can you show the content of `estado_actividads` table?

You could try to lowercase `Estado` column in `estado_actividads` table, just to see if that's the problem.

**Comment by Emmanuel-Reynoso** [comment]
I tried and it's the same. And it shows me errors.

Apparently he can't find it. Am I failing to make the connection?

![7](https://user-images.githubusercontent.com/32149800/73999877-e8c43d00-4944-11ea-994f-81780578bab4.png)

![8](https://user-images.githubusercontent.com/32149800/73999883-eb269700-4944-11ea-9c1a-eaaf5f59d2b2.png)

**Comment by MrCrayon** [comment]
What's in your model `ListaDeActividad`? Did you define relationships there?

Your naming looks like a nightmare to debug, if this is a new application I strongly advise you to change all names to use lowercase and follow Laravel conventions, like use `estado_id` instead of `Estado` even better use english words internally like state_id or status_id, ActivityState, ActivityList etc.

What you are doing might work but it also might cause problems and it's not going to make your life easier.

**Comment by Emmanuel-Reynoso** [comment]
I want to thank you for your time. 

The problem is that all the names are capitalized. About using English, you're right and it's simpler.

Again, thank you.

**Comment by MrCrayon** [comment]
> The problem is that all the names are capitalized.

Was that the problem or this is about my advice? 

If you still didn't solve you can debug it overriding VoyagerBaseController relation method. 

https://voyager-docs.devdojo.com/customization/overriding-files
