### ISSUE TITLE
Media Picker Thumbnail path bug

### ISSUE THREAD

**Issue by tabaktoni** [thedevdojo/voyager#4748]
## Version information

 - Laravel: ^5.8
 - Voyager: 1.2.6
 - PHP: ^7.1.3

## Description:
On upload  [VoyagerMediaController ](https://github.com/the-control-group/voyager/blob/d43c8dec2c09beb8ed9aeae61725fb0420b7ef86/src/Http/Controllers/VoyagerMediaController.php#L304). path generated in this concatenation is not correct. File name is appended to string without / and path have // before name, so at the end thumbnail is stored in parent folder when storing in bread/subfolder.

I fixed it localy adding this line to clean first / from client sent upload_path. That remove // problem:
`$str = ltrim($request->upload_path, '/');`
and add / before name.
`$thumbnail->save($realPath . $str . '/' . $name . '-' . ($thumbnail_data->name ?? 'thumbnail') . '.' . $extension, ($details->quality ?? 90));
`

## Additional context
I don't know is this already fixed, if not i can send pull request with this bug fixed.

## How to reproduce
1. Create bread that use Media Picker with thumbnail option type resize
2. Open that bread as user and create subfolder
3. Upload image in subfolder
Thumbnail will be uploaded in parent folder, if you create bred/1sub/2sub and upload it will be stored in bread/1sub/ and not 2sub.

**Comment by emptynick** [comment]
I'm quite sure that this has been fixed in the latest versions.
Please upgrade Voyager and test again.

**Comment by tabaktoni** [comment]
Updated to latest it work fine.
