### ISSUE TITLE
Error when submitting Category without parent_id

### ISSUE THREAD

**Issue by wtfz** [thedevdojo/voyager#475]
- Laravel Version: 5.3
- Voyager Version: 0.10.7

### Description:
Error shows 'Incorrect integer value' at parent_id when editing/adding category without parent_id.

### Steps To Reproduce:
1. Go to Categories menu
2. Click on Edit to any categories or Add New
3. Click Submit without parent_id

**Comment by marktopper** [comment]
In the current `master` branch you should be able to add the following to the breads *Additional Options* to be able to leave the field empty.

```
{
    "null": ""
}
```

Meaning that a empty string will become a `null` value.

Also for better support of this follow #496
