### ISSUE TITLE
Media Manager File Limit

### ISSUE THREAD

**Issue by Kevoniat** [thedevdojo/voyager#4752]
## Version information

 - Laravel: v6.2
 - Voyager: v#.#.#
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Media Manager File upload Limit is not in sync  with my server 
## Screenshots
![image](https://user-images.githubusercontent.com/40288341/74213189-26d3a080-4c66-11ea-98b6-2cf03bc5ba42.png)

## Additional context
I have my server configured to upload file up to 2GB, however, the media manager is limiting me to only  256 MB.
if I upload  using the file input type it's works fine

**Comment by Kevoniat** [comment]
Hi I Save that  was close however, I'm having this issue I can't upload files over 256 MB using the media Manger, however, it works  if I use a file input tag

**Comment by Kevonia** [comment]
Ok so the problem is with dropzone-js it had a default max file size of 256 Mib
