### ISSUE TITLE
Validation Blocking select files over 256 M Media Picker

### ISSUE THREAD

**Issue by Kevonia** [thedevdojo/voyager#4755]
## Version information

 - Laravel: 6.0
 - Voyager: 1.2
 - PHP: 7.3
- server: nginx
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

 When trying  uploading Video file  over 256 MB  a javascript toast message as File size too Big, however, my  php.ini file has my mu max_upload_size at 3 GB

## Steps To Reproduce
1. Go to  Media 
2. Click on Upload
3. select a file over  256 MB 

## Expected behavior
The video should be uploaded to the server 
## Screenshots
![image](https://user-images.githubusercontent.com/11888704/74246769-0c73e400-4cb3-11ea-8043-8645a74af404.png)

## Additional context
If I create a bread using a file input  tag the file is upload successfully

**Comment by Kevonia** [comment]
![image](https://user-images.githubusercontent.com/11888704/74247075-84daa500-4cb3-11ea-8849-1fd5f89771a5.png)
a better look at the image

**Comment by emptynick** [comment]
There's also post_max_size which might be set to 256Mib in your case.

**Comment by Kevonia** [comment]
hmm, what's wried is if a change the media picker to a input file type the upload works

**Comment by emptynick** [comment]
Probably because the form with a file input is multipart/form-data (no idea honestly).
Does it help?

**Comment by Kevonia** [comment]
well, the file input is working I can upload file up to 3 GB  which in my php.ini, guess I'm just gonna have to remove the media picker option

**Comment by emptynick** [comment]
I wrote a possible solution above. Did you try that?

**Comment by Kevonia** [comment]
will Trying in a few, not around my development PC ATM.

**Comment by Kevonia** [comment]
Ok so the problem is with dropzone-js it had a default max file size of   256 Mib
