### ISSUE TITLE
Bug after upgrade from 1.3.0 to 1.3.1  $requestData['field_details_'.$relationship] = json_encode($relationshipDetails);

### ISSUE THREAD

**Issue by hermesalvesbr** [thedevdojo/voyager#4756]
## Version information

 - Laravel: Laravel Framework 5.8.35
 - Voyager: v1.3.1
 - PHP: PHP 7.2.26
 - Database: MySQL 5.7.28
## Description

Whe i try to create a relationship BelongsTo show a error message
`ErrorException (E_NOTICE)
Undefined index: field_details_pedido_belongsto_poste_relationship`

## Steps To Reproduce
1. Go to 'Bread'
2. Click on 'Create a relationship'
3. Choose belongsTo 
4. Click on save

## Expected behavior
Before update was working ok.

## Screenshots
![Captura de Tela 2020-02-11 às 16 17 28](https://user-images.githubusercontent.com/379850/74271667-0e0dce00-4cec-11ea-8ce9-8d19a78d1c78.png)
![Gravação de Tela 2020-02-11 às 16 32 46](https://user-images.githubusercontent.com/379850/74271874-6775fd00-4cec-11ea-8c38-9e01d4d0633d.gif)

## Additional context
Try to clear the cache on the laravel, try to clear the browser cache. I even exclude the bread and create it again, but the error persists.

**Comment by emptynick** [comment]
Judging by the height of you scrollbar it looks like you have a lot of fields in that BREAD.
Check your php.inis max_input_vars config.

**Comment by hermesalvesbr** [comment]
max_input_vars => 4000 => 4000
; How many GET/POST/COOKIE input variables may be accepted
 max_input_vars = 4000

**Comment by hermesalvesbr** [comment]
`# php -i | grep 'max_input_vars'
max_input_vars => 10000 => 10000
# php -i | grep 'post'
enable_post_data_reading => On => On
post_max_size => 512M => 512M
`

**Comment by hermesalvesbr** [comment]
This work for me, after restart the server. 

 php artisan vendor:publish --tag=voyager_assets --force
