### ISSUE TITLE
Voyager default database name can not fetched with laravel 6 

### ISSUE THREAD

**Issue by skydev2020** [thedevdojo/voyager#4757]
## Version information

 - Laravel: v6.2
 - Voyager: v1.3
 - PHP: 7
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

After fresh install of Laravel 6, again installed Voyager following the guidelines.
And I updated the DB_DATABASE = <mycustomdb> but it keeps connecting with 'laravel'

## Steps To Reproduce
1. Install Laravel 6.2 (Latest as of today)
2. Update .env file: DB_DATABASE = <custom db>
3. Install Voyager 1.3 (Latest as of today)
3. php artisan serve
php artisan serve And, visit the URL http://localhost:8000/admin in your browser.
Facade\Ignition\Exceptions\ViewException
SQLSTATE[HY000] [1049] Unknown database 'laravel' (View: D:\xampp\htdocs\learnon\vendor\tcg\voyager\resources\views\login.blade.php)
http://127.0.0.1:8000/admin/login

## Screenshots
![image](https://user-images.githubusercontent.com/57546027/74308639-b8aade80-4d36-11ea-9087-db9552716d95.png)

**Comment by fletch3555** [comment]
Voyager definitely doesn't hard-core the database name anywhere, so my guess is that you have cached configs.  Please run `artisan config:clear`

**Comment by skydev2020** [comment]
Thanks for your answer @fletch3555 .
I have one more question. How can I use Voyager admin panel to allow all users to login but with limited features/menus?
I want to build a app where every user can login but limited menus/features.

**Comment by fletch3555** [comment]
Assign your users to a role that has the `browse_admin` permission and they'll be able to log into Voyager.  The rest of their access is determined by the other permissions assigned to that role.

Under the hood, Voyager just uses Laravel's auth system (specifically policies).  So you can tie into that with any customizations you need to make.  New permissions are stored in the database in case you need to create anything custom.  New BREAD created through the UI will automatically create a base set of permissions, so manually creating them is often not required.

**Comment by skydev2020** [comment]
@flamerecca 
Thanks for your answer. But when I edit the role/submit. It doesn't update the roles, but it doesn't produce any error on the website/console.
I created the new Role with some permission, it correctly create the role with specified permissions.
But when I try to update the permission it doesn't.
Any idea?

Updating Role with new permissions.
https://prnt.sc/r20t2n
After update
https://prnt.sc/r20teb
But after re-open the role
https://prnt.sc/r20tpd

**Comment by fletch3555** [comment]
I've seen other reports of this, but not sure offhand what the fix was.  Take a look around for similar complaints.

Is there anything in the laravel log file?

**Comment by skydev2020** [comment]
Nothing in Laravel Log, Ok. I will look around

**Comment by MrCrayon** [comment]
@skydev2020 here there is the solution for roles not updating permissions #4668 

Since I guess your original issue was solved we can close this.
