### ISSUE TITLE
Uploaded images like the site logo does not load and gives a notFoundHttpException

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#476]
Voyager version 0.10.7
PHP v5.6
Laravel: 5.3

An image url like this:

http://localhost:8080/storage/settings/January2017/SBwIPd9HDzCQI0UVHGY3.jpg

which is uploaded as the site logo from the settings page, gives me that Laravel error message:

NotFoundHttpException in RouteCollection.php line 161:

**Comment by fletch3555** [comment]
Did you upgrade from Voyager v0.9.*, or fresh install of v0.10.*?  If upgrade, did you follow the upgrade instructions in the documentation?

Please run `php artisan storage:link`.  If that states a symlink already exists, please delete the link at `public/storage` and run it again.  Once that link exists, please verify that that file exists at that path.

**Comment by hazem1taha** [comment]
That command 
`php artisan storage:link`
fixed the issue.

Thanks.

**Comment by estebangallego** [comment]
Thanks!
php artisan storage:link worked

**Comment by revtechbhav** [comment]
same issue is getting, image path is not getting, above solutions are not usefull to me , please suggest me , how to resolve this

**Comment by handiwijoyo** [comment]
@revtechbhav Please open new issue including you error
