### ISSUE TITLE
Allow general users to login to backend

### ISSUE THREAD

**Issue by skydev2020** [thedevdojo/voyager#4761]
Voyager just allows the admin user login to the backend, But I want to make all users can login to backend with limited features/menus. Is Voyager capable to do this?

**Comment by fletch3555** [comment]
Issue template is not optional.  Also, I believe I answered this question for you on another issue.

Please ask questions in slack instead of github. We try to reserve this space for project code issues and feature requests

**Comment by skydev2020** [comment]
@fletch3555 Which channel should I use for voyager?

**Comment by skydev2020** [comment]
@fletch3555 can you send me an invitation to skydev2020@outlook.com please?

**Comment by fletch3555** [comment]
I expect it'll be obvious once you look, but questions And requests for help should be asked in the #help channel

**Comment by fletch3555** [comment]
The link is available in our readme

**Comment by skydev2020** [comment]
Is this the slack channel? https://laravel-voyager.slack.com/
or which one. I just can't find the proper channel.

**Comment by skydev2020** [comment]
I found thanks
