### ISSUE TITLE
Update from to Bootstrap 4 because Bootstrap 3 EOL happend

### ISSUE THREAD

**Issue by pajtai** [thedevdojo/voyager#4762]
## Version information

 - Laravel: v6
 - Voyager: v1.3.1

## Description of problem

Voyager is built on Bootstrap 3. Bootstrap 3 is no longer supported as of `2019-07-24` https://github.com/twbs/release , so things should be updated to Bootstrap 4.

## Proposed solution
Update components and dependencies to Bootstrap 4

## Additional context
Voyager is awesome! Thank you!

**Comment by sergiooak** [comment]
Bootstrap 4 is not on the plans, there is a card on "v2.0 planning" saying that the plan is to [migrate to **Tailwind CSS**](https://github.com/the-control-group/voyager/projects/6#card-19846896).

And I agree with it 100%, Tailwind will turn Voyager more "style agnostic" making branding easier and significantly reducing bundle size, also, bye-bye jQuery dependency!

**Comment by pajtai** [comment]
@sergiooak Thanks for the update! Tailwind would be awesome.
I'll close this.
