### ISSUE TITLE
Media Manager

### ISSUE THREAD

**Issue by vitormicillo** [thedevdojo/voyager#4765]
Hi folks, this is not a BUG is just a question
Is there a way to limit some features of the media manager to the admin user only?
For example, only the admin can delete files.

This may be a suggestion for the next versions of the voyager.

## Version information
 - Laravel: v6.15.1
 - Voyager: v1.3.1
 - PHP: 7.3

**Comment by emptynick** [comment]
As the issue-template suggests, please ask questions in our Slack group.
