### ISSUE TITLE
Voyager::image helper returns old url

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4769]
## Version information

 - Laravel: v5.8
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL

## Description
Then i call Voyager::image helper to retrieve the thumbnail, It returns the old base url(APP_URL). It was working fine. It broked after we change domain name, migrated the website to another domain. I change APP_URL in .env file, Cleared the configuration cache by running `php artisan config:cache`
## Steps To Reproduce
1. Open the .env file and change APP_URL
2. Clear the configuration cache3. Call the Voyager::image() helper and dd() the output

## Expected behavior
It should reflact the APP_URL from .env file after changing

**Comment by vkiranmaniya** [comment]
Meanwhile, I found workaround to this issue.
I used asset() helper as,
```php
asset('storage/' . $product->getThumbnail($image, 'thumbnail-md')) //working
//Voyager::image($product->getThumbnail($image, 'thumbnail-md'));
```
I think there is issue with `image()` helper function

**Comment by emptynick** [comment]
I am 100% certain there is nothing wrong with `Voyager::image`.
It simply calls `Storage::disk(config('voyager.storage.disk'))->url($file)` so I think there is something wrong with the disk you configured for Voyager.

**Comment by vkiranmaniya** [comment]
@emptynick I didn't make any changes to the disc configuration. The Application is running with default configurations. So the app should behave normally as aspected but it didn't.

**Comment by vkiranmaniya** [comment]
here is the `config`
```php
'storage' => [
    'disk' => env('FILESYSTEM_DRIVER', 'public'),
],
```
in config/voyager.php file. It's untouched after publish vendor. so `Voyager::image()` helper should work normally. My concern is, I changed the  `APP_URL` in `.env` but `Voyager::image()` helper is still taking the older one. I also cleared application cache and configuration cache.

**Comment by alfrandhy** [comment]
![Screenshot from 2020-05-10 06-43-23](https://user-images.githubusercontent.com/18322339/81487676-b69ae200-9289-11ea-92c7-528b6fbec0fd.png)
Sorry Guys can Help Me,

Why my url is multiple like that

**Comment by MrCrayon** [comment]
@alfrandhy please don't comment in unrelated issues with questions. 
If you need help with your Voyager integration you can join Voyager Slack chat.

**Comment by dsaha1656** [comment]
I am having the same issue, 

additionally i noticed `route('route_name')` also produce old url.

please have a look.

**Comment by emptynick** [comment]
`route()` is a Laravel method. We can't fix that here.
My opinion still stands - we simply call Laravel methods/functions.
There is a very very high chance something is cached that shouldn't.

Closing
