### ISSUE TITLE
Problem when deploy to internet

### ISSUE THREAD

**Issue by xans-me** [thedevdojo/voyager#477]
I got the problem when i deploying my project with Voyager Package, But when i look on admin page
i got the page with style.

<img width="1263" alt="screen shot 2017-01-01 at 10 00 59 pm" src="https://cloud.githubusercontent.com/assets/23119469/21581658/f7ed16a6-d06d-11e6-981e-b704117bc3e4.png">

**Comment by tnylea** [comment]
@arogant7000 Can you open up your developer tools and look at the console and share the error message with me. The CSS file does not seem to be loading from the correct location.

**Comment by taoyu65** [comment]
i got same problem because you didn't put voyager on the root directory, you can set a new value with "assets_path" in the voyager.php under config path. By the way check issue #470

**Comment by xans-me** [comment]
@tnylea : I don't know how can i set up that's.. But i will send the capture of my developers tools.
<img width="1274" alt="screen shot 2017-01-02 at 3 28 59 pm" src="https://cloud.githubusercontent.com/assets/23119469/21586167/3cfc4388-d100-11e6-98cc-2dba3db9ab6e.png">

**Comment by xans-me** [comment]
@taoyu65 : so, how can I manage this? Please help me 😥

**Comment by taoyu65** [comment]
@arogant7000 find voyager.php in the config file, open it you will see assets_path , I dont know what's your project path anyway set a new value for assets_path like "assets_path" => "/parent's folder name of your voyager/vendor/tcg/voyager/publishable/assets"  because all the resources under that path, You can move to your resources to anywhere you want then set assets_path properly ,hopefully this can help u out

**Comment by xans-me** [comment]
Thank you,  i will try that first

**Comment by marktopper** [comment]
Closed due to missing update from @arogant7000.

Please ping me to reopen if this is still an issue.

**Comment by xans-me** [comment]
sorry, i don't understand, i still low skill
@marktopper

**Comment by handiwijoyo** [comment]
@arogant7000 there are videos tutorial here https://devdojo.com/series/laravel-voyager-010/ follow the tutorial first until your project working, and you can make changes after that.
