### ISSUE TITLE
Generate page and post

### ISSUE THREAD

**Issue by MISTERPOTE** [thedevdojo/voyager#4771]
Hi everybody,

I can create a page and a post but i don't understand where i can see it in the frontend ?
They are in my database.

Thank you :)

**Comment by MrCrayon** [comment]
Please read issue template

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

I also suggest you to read Voyager documentation
https://voyager-docs.devdojo.com/getting-started/what-is-voyager
