### ISSUE TITLE
Image source not readable when uploaded through Media Manager (with AWS S3)

### ISSUE THREAD

**Issue by AbdulazizFayez** [thedevdojo/voyager#4772]
## Version information

 - Laravel: v5.7
 - Voyager: v1.3.1
 - PHP: 7.0
 - Database: MySQL 5.7

## Description

**A clear and concise description of what the bug is:**

My images are not showing on media manager when i upload them, I'm using AWS S3 and filesystem is pointing to to the correct storage).  

After researching and going back and forth testing, i realized that my issue is related to the "media manager" not hashing the content that is being uploaded, because unlike BREAD, contents uploaded through BREAD are hashed (not sure if there are other attributes added to the files when they're uploaded) and hence they're accessible and read successfully (as seen below):

![image](https://user-images.githubusercontent.com/16557490/74909926-47cd8b80-53f4-11ea-9fcf-62618fec19af.png)

So since my issue is with the media manager, any advice on where i can enforce hashing? (assuming it could solve the problem) I'm not sure if this is a bug or does it need to be enabled/disabled. 

I've been searching around half a days without any avail.

-Note: on my localhost, media uploaded (to S3) can be accessible, but when on production, contents uploaded are having 'access denied' (again, when i upload content through bread to S3, it is  accessible and can be read -name are hashed- as image above).. but i cannot do the same on media manager.

## Steps To Reproduce

Added S3 requirements to filesystem, once success, deploy the site to production

1. in Production go to Media Manager and upload.
2. Once you upload it will show blank and wont be accessible (you can see the error):

![image](https://user-images.githubusercontent.com/16557490/74911707-21115400-53f8-11ea-9920-5eabdb274896.png)

Reminder, the images you that you can see are actually uploaded through BREAD.

I also tested uploading in root directory:

![image](https://user-images.githubusercontent.com/16557490/74910352-4781c000-53f5-11ea-9825-75123f05f97d.png)

Clicking on the "Public URL" give me this:

![image](https://user-images.githubusercontent.com/16557490/74910378-58cacc80-53f5-11ea-8e5c-84431b75a798.png)

## Expected behavior
I expect that Media Manager to upload and view images just like BREAD.

## Screenshots
Done.

## Additional context
Reminder, on localhost this does not happen and i confirm that APP_URL is directed to the site i am hosting on..file system is set to s3 from env.

My Technical environment:
Windows 10 Pro
Wamp 3.1.8 64bit
Php 7.0

Thanks.

**Comment by MrCrayon** [comment]
>  realized that my issue is related to the "media manager" not hashing the content that is being uploaded

Are you talking about random name generation?

Does this happen with all images you upload with Media Manager?

Make sure filenames are all lowercase and don't contain spaces, that's the first thing I would check.
