### ISSUE TITLE
Media library does not display folders from storage/public while accessing it in CRUD view

### ISSUE THREAD

**Issue by anibdas** [thedevdojo/voyager#4773]
I upload a folder(nested folders) of images manually into **storage/app/public** folder.

All the folders and images into nested folders appears well when seen from media library of Admin Interface.

![image](https://user-images.githubusercontent.com/47399813/75034006-3bb7fb80-54d2-11ea-8930-68e8acee7525.png)

Next I created a bread and assigned a field "**media picker**".

While picking the image from the field, the folders are not visible here. Also adding new folder from the CRUD is also doesn't seem to be working.

![image](https://user-images.githubusercontent.com/47399813/75034132-88033b80-54d2-11ea-9d07-3db465fd0c11.png)

Is there any settings that needs to be done to get this work?

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened once the requested informations are provided.
