### ISSUE TITLE
Media library does not display folders from storage/public while accessing it in CRUD view

### ISSUE THREAD

**Issue by anibdas** [thedevdojo/voyager#4774]
## Version information

 - Laravel: v5.7.28
 - Voyager: v^1.2
 - PHP: 7.2
 - Database:MySQL 8.0
## Description

I upload a folder(nested folders) of images manually into storage/app/public folder.

All the folders and images into nested folders appears well when seen from media library of Admin Interface.

![image](https://user-images.githubusercontent.com/47399813/75034846-1b893c00-54d4-11ea-82f0-c98b7ed2be2b.png)

Next I created a bread and assigned a field "media picker".

While picking the image from the field, the folders are not visible here. Also adding new folder from the CRUD is also doesn't seem to be working.
![image](https://user-images.githubusercontent.com/47399813/75034880-2e037580-54d4-11ea-8f79-519351becb12.png)

## Expected behavior
Images should be visible from the root of storage/app/public folders even in CRUD view

**Comment by emptynick** [comment]
1.2 is quite old already. There were a lot of fixes to the media picker in 1.3.
Nonetheless the media-picker has a parameter `base_path` which defaults to the bread-slug and not the root folder of the public disk.

**Comment by anibdas** [comment]
is there a way to not default it to base_path of bread-slug but root of the storage ?

**Comment by emptynick** [comment]
It's a parameter. Set it to whatever you want.
You'll find everything in the docs.

**Comment by anibdas** [comment]
Thanks a lot. This was definitely a helpful support indeed.
