### ISSUE TITLE
Can't select multiple files in media picker

### ISSUE THREAD

**Issue by ADavid25** [thedevdojo/voyager#4775]
## Version information

 - Laravel: v6.12.0
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: MySQL 14.14

## Description

In the documentation of the media pickers says theres is an attribute to limit or require a min/max amount of files that can be selected, but when I try to select another file, it just substitute the previous one.

## Steps To Reproduce
1. Create a media picker
2. Don't add any optional details in the BREAD

## Expected behavior
I expected to be able to select multiple files.

**Comment by emptynick** [comment]
Just set the max attribute to a very high number.
The docs need to be corrected, 0 does not mean infinite.

**Comment by ADavid25** [comment]
@emptynick Thanks man, you were right. Works as expected
