### ISSUE TITLE
Good configuration but can't call data

### ISSUE THREAD

**Issue by MISTERPOTE** [thedevdojo/voyager#4777]
Hi everybody,

 - Laravel: v5.8.37
 - Voyager: v1.2.2
 - PHP: 7.3.12
 - Database: MySQL 5.6.35 on phpMyAdmin

I have a problem with post and pages.
This is my code :

**Web.php**
`// ADMIN
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

// PAGES
Route::get('{slug}', 'PagesWebSiteController@show');

// Post : get all
Route::get('/', function () {
    $posts = App\Post::all();
    return view('home', compact('posts'));
});

// Post : single
Route::get('blog/{slug}', function($slug){
	$post = App\Post::where('slug', '=', $slug)->firstOrFail();
	return view('blog', compact('post'));
});
`

**app\Page.php**
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Page extends Model
{
    public static function findBySlug($slug)
    {
        return static::where('slug', $slug)->first();
    }
}
`

**app\Post.php**
`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
}
`

**PagesWebSiteController.php**
`<?php

namespace App\Http\Controllers;

use App\Page;
use Illuminate\Http\Request;

class PagesWebSiteController extends Controller
{
    public function show($slug)
    {
        $page = Page::findBySlug($slug);
        return view('page.show', ['page' => $page]);
    }
}`

This is my error for pages : (http://localhost:8000/test)
Trying to get property 'title' of non-object (View: /Users/Max/Desktop/Projects/myproject/resources/views/page/show.blade.php)

This is that i see on : http://localhost:8000/blog/test
{{ $post->title }}
{!! $post->body !!}

Thank you very much.

**Comment by MrCrayon** [comment]
The issue template is not optional when opening issues.
This can be reopened once the requested informations are provided.

By the way it's a custom route that calls a custom view, how is this related to Voyager?

**Comment by MISTERPOTE** [comment]
Sorry about he issue template.
I'm not sure to understand the question.
Voyager has installed on my current project and i create a root for the pages and a root for the blog with the posts.

**Comment by MrCrayon** [comment]
My point is that you are trying to access data stored in database, I don't see anything related to Voyager in your code except for the fact that you used Voyager to insert db data.
So, in my opinion, your problem is not related to Voyager.

By the way it looks like you are passing `$page` to the view that uses `$post`:

> return view('page.show', ['page' => $page]);

> {{ $post->title }}
