### ISSUE TITLE
If user hasn't access to specific page, they can still see the corresponding menu item in menu

### ISSUE THREAD

**Issue by avag-sargsyan** [thedevdojo/voyager#4778]
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: e.g. MySQL 8.0.17

## Description

Thanks for the nice Laravel Admin Package!
It seems you don't check if the user have access to a specific page before showing the corresponding menu item in the menu. 

## Steps To Reproduce
1. Create a custom role with limited permissions.
2. Create a user with that role.
3. If logged in with that user menu items will be visible which bread items the user hasn't access (will get `403` error).

## Expected behavior
The user sees menu items based on their role permissions.

## Screenshots
n/a

## Additional context
n/a

**Comment by MrCrayon** [comment]
That's quite an old version.
I don't know if permission checking was not yet implemented for menu items or your particular version had a bug. 

Anyway we can't provide support for such an old version. 
Please update following all upgrade guides and if you are still experiencing any problem you can open a new issue or ask in Voyager Slack chat.

**Comment by fletch3555** [comment]
`n/a` for the "steps to reproduce" is not valid.  Please provide a response there.

More information is needed. Is this a automatically created from BREAD creation, or a custom menu entry? If the latter, how is Voyager supposed to know what permission to check?

Also, please update as mentioned by @mrcrayon

**Comment by avag-sargsyan** [comment]
Thanks for the response! 

@fletch3555  I have edited my question. 

> More information is needed. Is this a automatically created from BREAD creation, or a custom menu entry?

The menu is automatically created from BREAD creation.

@MrCrayon, yes, it's an old version, but it seems the functionality doesn't exist in the latest version also. Please correct me if I'm wrong.

Thanks.

**Comment by fletch3555** [comment]
This is the policy that does it: https://github.com/the-control-group/voyager/blob/1.3/src/Policies/MenuItemPolicy.php
