### ISSUE TITLE
admin menu not displaying on new installation

### ISSUE THREAD

**Issue by Kayrah87** [thedevdojo/voyager#4786]
## Version information

 - Laravel: v6.17.1
 - Voyager: v1.3.1
 - PHP: 7.2.24
 - Database: MySQL 8.0 

## Description
On a fresh install, logging in as either a newly created admin user or the dummy admin@admin.com user, the sidebar admin menu does not render.
The grey bar appears with the username and avatar in under the voyager logo, but there are no options.

## Steps To Reproduce
1. Install Laravel
2. Composer require tcg/voyager & install as per instructions
3. php artisan voyager:admin ... --create
4. Log in
5. See error

## Expected behavior
Side menu displays admin menu icons as per the pre-built admin menu.

## Screenshots
![image](https://user-images.githubusercontent.com/6371001/75381236-52928f80-58d0-11ea-9241-7f0e0edb99ee.png)

## Additional context
dd'ing `menu('admin')`  gives a list of the correct options unformatted, but when used with `<admin-menu>` doesn't render

**Comment by MrCrayon** [comment]
Do you have any error in browser console?

**Comment by Kayrah87** [comment]
Chrome console shows no errors at all. /storage/logs/laravel.log reveals no errors either.

**Comment by Kayrah87** [comment]
By way of an update, a deep dive into the code reveals that vue was failing to compile the template because the server I was using had headers preventing unsafe-eval.
The error message is as below:
`[Vue warn]: It seems you are using the standalone build of Vue.js in an environment with Content Security Policy that prohibits unsafe-eval. The template compiler cannot work in this environment. Consider relaxing the policy to allow unsafe-eval or pre-compiling your templates into render functions.`

to resolve I changed the header to `add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:";`

The security.conf file where this was contained was generated by nginxconfig.io so anyone using this source please check `/etc/nginx/nginxconfig.io/security.conf` for this header.

The only other way around this would be for the templates to be precompiled in a future version of voyager to avoid requiring unsafe-eval.

**Comment by MrCrayon** [comment]
Thank you for the update!

Shouldn't that error show up in Chrome console?

So that we know where to ask people to look at in the same situation.

**Comment by Kayrah87** [comment]
The error I experienced was a Vue error, and required the installation of the [Vue.js DevTools extension in Chrome](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?utm_source=chrome-ntp-icon). The plain console does not show the Vue related error at all.

**Comment by oneWaveAdrian** [comment]
> to resolve I changed the header to `add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval' blob:";`
> 
> The security.conf file where this was contained was generated by nginxconfig.io so anyone using this source please check `/etc/nginx/nginxconfig.io/security.conf` for this header.

Thanks @Benaal for finding this, was looking for a solution to my problem as well -> did the trick, would therefore +1 the precompile idea
Using Laravel 7 on php7.2 with Nginx
