### ISSUE TITLE
Doc: how to create a many to many?

### ISSUE THREAD

**Issue by realtebo** [thedevdojo/voyager#4787]
I have Users, table and BREAD
I have Groups, table and BREAD

Now I need to create an HasMany, where A Group HasMany Users.

Must I create before migration for the pivot table? Which fields does it needs? What If my pivot table need an addition column ? like 'isAdmin', because every group can also have many admins
If not, how to create from GUI (and how to execute migration on production server later?)

**Comment by fletch3555** [comment]
Issue template is not optional.  Also, per the issue template, questions should be asked in Slack.

**Comment by realtebo** [comment]
Sorry, where are slack infos ? I am not able to find any link to forum, slacks, or  other.

**Comment by realtebo** [comment]
Slack is the worst way to give user supports. A forum. A question/answer website, but not slack...
