### ISSUE TITLE
Saving settings without uploading an file

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/voyager#4789]
Laravel Version: 6.1
Voyager Version: 1.1
PHP Version:7.2
Database Driver & Version:MySQL

Description:

Similar problem as described [here](https://github.com/the-control-group/voyager/issues/3059) but with file uploads rather than image uploads.

Settings of type **file** in /admin/settings get a NULL-value if no file is uploaded but other values are updated.

Since there is no upload the field for eg site_file never get posted, and since it's not existing in the request it gets emptied somehow.

Regards,

Bobby

Steps To Reproduce:
Create a new filed in Settings and set it to type File
Upload a site.file under /admin/settings
Click submit
When page reloaded, click submit again
Uploaded site.file value has disappeared.

**Comment by MrCrayon** [comment]
Version 1.1 is very old.
Please update Voyager to last release and if you are still experiencing that problem open another issue.
