### ISSUE TITLE
Cannot change user default role - Not null violation

### ISSUE THREAD

**Issue by kingIZZZY** [thedevdojo/voyager#4793]
Laravel: v6.17.1
Voyager: v1.3.1
PHP: 7.2
Database: postgresql 10

## Description
Trying to change a User's default role from one to another results in exception: `Illuminate\Database\QueryException
SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint DETAIL: Failing row contains (null, CustomRole1, user1@local, null, $2y$10$7f7Mqw7U/VGppNM3ySCITunHDWiUf6V0Sjkq5REKWZ.WqdgDhWXPe, AGyJlt2JffwItu7NOke1R54BsYv9US4hG6ndxF6wVeNrThfremh1tYUcruIJ, 2020-02-28 14:07:57, 2020-02-28 14:39:37, users/default.png, 2, {"locale":"en"}). (SQL: update "users" set "id" = ?, "role_id" = 2, "updated_at" = 2020-02-28 14:39:37 where "id" = 3)`

## Steps To Reproduce
1. Go to a User's edit page ex. http://127.0.0.1:8000/admin/users/3/edit
2. Click on Default Role field dropdown
3. Choose another role than the one that was set before, and then Save
4. See the above exception

## Expected behavior
It should successfully change role from one role to another role, and not result in broken flow / exception.

**Comment by MrCrayon** [comment]
Uncheck id field in BREAD configuration and let us know if that solves the problem.

Since users have a custom view changing BREAD configuration might cause problems like the one you are experiencing.
