### ISSUE TITLE
voyager image problem

### ISSUE THREAD

**Issue by necatisen** [thedevdojo/voyager#4794]
Laravel Version: LAST
Voyager Version: LAST
.PHP Version: 7.2
Database Driver & Version: MySql

Hi, I installed Voyager on the server, but the icons are not displayed on the server.There is no such problem in Local.
I also get an error on the server while uploading the images. I request your urgent help !!!

https://hizliresim.com/qym2dV 
https://hizliresim.com/yjAnGM
https://hizliresim.com/NG9bLk

**Comment by MrCrayon** [comment]
Please provide actual versions installed. 

Did you check if php_fileinfo extension is enabled?

**Comment by fletch3555** [comment]
As @MrCrayon said, `LAST` is not a valid version number.  Also, that error message is self-explanatory (or at least easily searchable).

**Comment by necatisen** [comment]
> Lütfen kurulu gerçek sürümleri sağlayın.
> 
> Php_fileinfo uzantısının etkin olup olmadığını kontrol ettiniz mi?

@MrCrayon No, I did not look at the file you specified. I'm a novice, can you explain in a little detail? 

Laravel Sürüm: 6.0
Voyager Sürüm: 1.3
.PHP Sürüm: 7.2
Veritabanı Sürücüsü ve Sürüm: MySql

**Comment by necatisen** [comment]
> As @MrCrayon söyledi, `LAST`geçerli bir sürüm numarası değil. Ayrıca, bu hata mesajı açıklayıcıdır (veya en azından kolayca aranabilir).

Laravel Sürüm: 6.0
Voyager Sürüm: 1.3
.PHP Sürüm: 7.2
Veritabanı Sürücüsü ve Sürüm: MySql

@fletch3555  I researched the error, I wrote here because I could not find a solution. 

I skipped adding the picture for the icon problem. 

https://hizliresim.com/7QVMdW
https://hizliresim.com/qym2dV
https://hizliresim.com/NG9bLk

**Comment by necatisen** [comment]
> Please provide actual versions installed.
> 
> Did you check if php_fileinfo extension is enabled?

Laravel Version: 6.0
Voyager Version: 1.3
.PHP Version: 7.2
Database Driver & Version: MySql

@MrCrayon  With this answer, I solved it with two problems. Thank you so much. 

I have an administrative official issue left. The path in the env file is correct, but the reason is not visible. I have only 1 problem left. 

https://hizliresim.com/E2z8Vn
https://hizliresim.com/qym2dV
https://hizliresim.com/NG9bLk

Is there any other extension I need to enable extra? I shared the active ones in the extension below.
https://hizliresim.com/8X9ZZ7

**Comment by MrCrayon** [comment]
Your APP_URL should have https.
If that doesn't solve please join Voyager slack chat for further questions.

**Comment by necatisen** [comment]
> Your APP_URL should have https.
> If that doesn't solve please join Voyager slack chat for further questions.

@MrCrayon  Thanks. Can you send me a link to join the group please?

**Comment by MrCrayon** [comment]
https://github.com/the-control-group/voyager/blob/1.3/README.md
