### ISSUE TITLE
Voyager menu display

### ISSUE THREAD

**Issue by ahmedalouini1** [thedevdojo/voyager#4797]
## Version information

 - Laravel: v6.0
 - Voyager: v1.3
 - PHP: 7.3.7
 - Database:  MySQL 8.0

## Description:
hello  i want to  display the admin panel  with sidebar and navbar in a new page that i have created i have added @extends('voyager::master'), i have also added a menu element with a static route  but there is a porblem with the display: 
![Screenshot_3](https://user-images.githubusercontent.com/36577665/75628890-8675f980-5bdd-11ea-8b97-c2095eb31ea5.png)

**Comment by emptynick** [comment]
Please ask questions in our slack group.

**Comment by ahmedalouini1** [comment]
how to join the slack groupe ?

**Comment by MrCrayon** [comment]
https://github.com/the-control-group/voyager/blob/1.3/README.md
