### ISSUE TITLE
BREAD Return Null or Empty Value

### ISSUE THREAD

**Issue by engrmahe** [thedevdojo/voyager#4799]
## Version information

 - Laravel: v 6.12
 - Voyager: v 1.3
 - PHP: 7.3.5
 - Database: MySQL 5.7.26  [type] [version] (e.g. MySQL 8.0)

## Description
BREAD Return Null or Empty Value. i explain all my scenario. 

## Expected behavior
1. its shows error 
SQLSTATE[HY000]: General error: 1364 Field 'B_peru' doesn't have a default value (SQL: insert into `book8v`.`branch_approval` (`updated_at`, `created_at`) values (2020-03-02 20:20:33, 2020-03-02 20:20:33)) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1364 Field 'B_peru' doesn't have a default value (SQL: insert into `book8v`.`branch_approval` (`updated_at`, `created_at`) values (2020-03-02 20:20:33, 2020-03-02 20:20:33)) at C:\\wamp64\\www\\book8\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:669)
First error Solution : i added one Line at Model : `protected $table = 'book8v.branch_approval';(Datatabe.tablename)`
then error clear. 

**Current Error :**
**2. Error. Now its shows as BREAD. Edit/Add return view EMPTY.**
I think some connection issues. But i cant do this. 

## Screenshots
![image](https://user-images.githubusercontent.com/4426372/75716369-0e9af280-5cf5-11ea-8558-511aad810437.png)

**Comment by MrCrayon** [comment]
Please edit your first post with full version, there is v1.3.0 and v1.3.1

From your error looks like you didn't configure your BREAD. 
Please check your BREAD configuration (Tools -> BREAD) and take a screenshot.

**Comment by engrmahe** [comment]
Tools ---> BREAD. 
![image](https://user-images.githubusercontent.com/4426372/75747172-3bc1c200-5d42-11ea-9384-afe36596c81e.png)

2. BREAD --> branch Approval --> Edit.
part1.
![image](https://user-images.githubusercontent.com/4426372/75747266-788db900-5d42-11ea-84ec-8d069eb1ea9d.png)

Part2:
![image](https://user-images.githubusercontent.com/4426372/75747299-8a6f5c00-5d42-11ea-9580-94292f951b2c.png)

See the above Part-2; Image, Table shows empty; 
The above issue that didnt fetch the table frorm DB. After Creating the BREAD. 
issue that View or DB ?

What can i do this type of error ?

**Comment by MrCrayon** [comment]
You probably changed something after creating BREAD and/or there is some problem with your names.

Save yourself some headaches and follow Laravel standards for naming tables, columns etc.
https://laravel.com/docs/6.x/eloquent#eloquent-model-conventions

After you changed that, delete that BREAD and create it again.

**Comment by engrmahe** [comment]
i delete and re-create; No response for that. Same issue. 

Table name and column name are user define, What is the issue i read that.

**Comment by MrCrayon** [comment]
> **Save yourself some headaches and follow Laravel standards for naming tables**, columns etc.

Your table name should be `branch_approvals`, if you used that you would't have set this:

```protected $table = 'book8v.branch_approval'```

and your BREAD would be working, remove chained database name from `$table`.

**Comment by engrmahe** [comment]
Yes, I removed that still shows the same error. Some error in model or View Controller.

**Comment by engrmahe** [comment]
i have some issues at database engine section. (Typographical Error). 
problem solved. 

i read your Docs more than 40 Times.

Thanks all Voyager Team.

**Comment by engrmahe** [comment]
> You probably changed something after creating BREAD and/or there is some problem with your names.
> 

> > Save yourself some headaches 

and follow Laravel standards for naming tables, columns etc.
> https://laravel.com/docs/6.x/eloquent#eloquent-model-conventions
> 
> After you changed that, delete that BREAD and create it again.

You are right.
