### ISSUE TITLE
Hi, I am new with voyager I am installing voyager when I run the php artisan voyager:install command get this error (Symfony\Component\Console\Exception\CommandNotFoundException]     There are no commands defined in the "storage" namespace)

### ISSUE THREAD

**Issue by Ziaullah-Mommand** [thedevdojo/voyager#48]

**Comment by DanVeira** [comment]
Have you added the Voyager service provider as well as the Image Intervention service provider to the config/app.php file in the `'providers' => [` array?

**Comment by adriaanzon** [comment]
The `storage:link` command that gets called [here](https://github.com/the-control-group/voyager/blob/59cdc717435d67ddb880deeadd47306dc0bf0841/src/VoyagerCommand.php#L77)  was added in Laravel 5.3.  Are you using Laravel 5.2 or older?

**Comment by ramdrupal7** [comment]
i am  using 5.2 laravel Adriaanzon , same error i am getting while install voyager.

**Comment by mommand** [comment]
I installed the laravel 5.3 but still I have the same problem, and I added the service provider as well.
![screen shot 2016-11-02 at 10 59 36 am](https://cloud.githubusercontent.com/assets/4653953/19918750/81ae0a60-a0eb-11e6-861f-e45abae6c017.png)

And this is the error
![screen shot 2016-11-02 at 11 01 37 am](https://cloud.githubusercontent.com/assets/4653953/19918783/ce946130-a0eb-11e6-8211-14cf4c952923.png)

**Comment by Jeroen-G** [comment]
1. Run `composer dump`
2. Run `artisan --version` and see it is 5.3
3. Run `artisan` and check if, near the end of the list, a command called `storage:link` is present.
   If not, something _really_ weird is going on, and likely the installation of the Laravel core failed to install that command.

**Comment by debeniter86** [comment]
The same error am getting. My laravel version is 5.2.45

 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "storage" namespace.

**Comment by Jeroen-G** [comment]
You need Laravel 5.3

**Comment by momin-riyadh** [comment]
@mommand just ensure you have installed **php version 5.6.4** and laravel 5.3 on your machine , then follow the instruction from voyager github doc. I had same problem  ......... to now i resolve it

**Comment by fletch3555** [comment]
Closing as inactive.  If this is still an issue in 5.3, please let me know and I'll reopen.

**Comment by umercvision** [comment]
Using Laravel v5.3 ... Can't login using admin credentials : User : admin@admin.com Password : password ... it seems not migrating ADMIN table.

**Comment by cloudbluedigital** [comment]
I still have this problem,

> storage
>   storage:link         Create a symbolic link from "public/storage" to "storage/app/public"

> Laravel Framework version 5.3.16

> λ php -v
> PHP 7.0.13 (cli) (built: Nov  8 2016 13:45:28) ( ZTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```
        /*
         * Package Service Providers...
         */

        TCG\Voyager\VoyagerServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,
```

But I am getting same error as the author, why?
