### ISSUE TITLE
Customize datatype BREAD to limit user scope

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4800]
## Description of problem
I want to create a data type that has the ability to limit the user scope. (i.e. only the creator can read, edit, update, delete data from it.) Consider a case given. I have 3 roles
1) Administrator
2) User
3) Seller
now, there is a datatype named <b>product</b>. I want the product can only be modified by the seller who created it. However, the Administrator has full control over it.

## Proposed solution
1. I modified the `tcg/voyager/resources/views/tools/bread/edit-add.blade.php` as given, (after line 120)
```php
<div class="col-md-2 form-group">
    <label for="is_user_scoped">Apply User Scope?</label><br>
    <?php $checked = (isset($dataType->is_user_scoped) && $dataType->is_user_scoped == 1) || (isset($is_user_scoped) && $is_user_scoped); ?>
    <input type="checkbox"
        name="is_user_scoped"
        class="toggleswitch"
        data-on="{{ __('voyager::generic.yes') }}"
        data-off="{{ __('voyager::generic.no') }}"
        @if($checked) checked @endif >
</div>
```

2. modified the database schema of table <b>data_types</b> little bit and added the new <b>TINYINT</b> column named <b>is_user_scoped</b> to store either 1 or 0 and gave it a default value 0.

3. modified the `tcg/voyager/Models/DataType.php` and added the newly created column name <b>is_user_scoped</b> into `$fillable` array, and added the code into <b>updateDatatype()</b> method as given,
```php
if(isset($requestData['is_user_scoped'])){
    $requestData['is_user_scoped'] = 1;
}
```
I tried to run without this code, but the line `$this->fill($requestData)->save()` returned error that model was trying to insert value `on` into column `is_user_scoped`. So i applied weird path there. 

<b>Note: I need suggestion on this, why checkbox does not convert value `on`/`off` to 1/0</b>

4. created the new table named <b>products</b> with model as <b>Product</b>. The idea is, when we want to apply user scope, we should have <b>user_id</b> column to store the id of the user who created it.

5. modified the `VoyagerBaseController.php` and added code after line 70 as given below,
```
$query = $model::select('*');
if($dataType->is_user_scoped == 1 && Auth::user()->role->id == 3){
    $query->where(['user_id' => Auth::user()->id]);
}
```
checked the datatype to determine should it be scoped to the user or not. I have statically checked the role for now but i'll try to add relationship input there before creating pull request.

## Prerequisites
All datatype which is going to be user scoped, must have user_id column for ownership determination.

**Comment by emptynick** [comment]
This all can be done with a simple [scope](https://voyager-docs.devdojo.com/bread/introduction#scope-browse-results) already.
The demo also shows exactly what you are trying to do (without the admin-part)

**Comment by vkiranmaniya** [comment]
@emptynick so, if I want the admin to be able to view all, may I use as given?
```php
public function scopeCurrentUser($query) {
        return Auth::user()->role->id == 1 ? $query : $query->where('author_id', Auth::user()->id);
}
```

**Comment by vkiranmaniya** [comment]
Got an error as
```
General error: 1364 Field 'author_id' doesn't have a default value (SQL: insert into `products` (`name`, `min_order_qty`, `grade`, `packaging_type`, `packaging_size`, `type`, `slug`, `description`, `updated_at`, `created_at`) values (Anup's Sample Oil, 6000 LTR, 2D, Barrel, 1, Gasoli
```

**Comment by emptynick** [comment]
Thats a different problem.

Closing as this feature already exists.
