### ISSUE TITLE
Uploaded image is not appearing on Voyager

### ISSUE THREAD

**Issue by KhurshidYakubov** [thedevdojo/voyager#4804]
## Version information

- Laravel: v5.8
- Voyager: v1.2
- PHP: 7.3
- Database: MariaDB 10.3.15

## Description

Uploaded image is not appearing on Voyager admin Panel 

## Expected behavior
I want to see images which will be uploaded from the form of view  [https://example .uz/join](url) in
[https://example.uz/admin/requests](url) 

Here is my code:

`
<form method="post" action="{{ route('rcont.store') }}" enctype="multipart/form-data">

    @csrf

    <div class="form-group">
        <label>3x4 Фото*</label>
        <input type="file" id="myfile" name="img" >
    </div>

    <div class="form-group text-center">
       <input type="submit" name="add" class="btn btn-primary submit-btn" value="Отправить " />
    </div>

</form>
`

## Screenshots

![image](https://user-images.githubusercontent.com/40025822/75856207-aee83880-5e15-11ea-88fd-bb791376451e.png)

![image](https://user-images.githubusercontent.com/40025822/75856264-ce7f6100-5e15-11ea-9e33-ca6726d65a80.png)

## Additional context
How can I see uploaded images in Voyager? Please help.

**Comment by emptynick** [comment]
As this is a custom form this is not a Voyager related problem.
So please ask questions like this in our Slack group.
