### ISSUE TITLE
Hi there! pleace add support to laravel 7

### ISSUE THREAD

**Issue by renamate** [thedevdojo/voyager#4807]
## Version information

 - Laravel: v7.0.4
 - Voyager: v1.3.1
 - PHP: 7.2.19

## Description of problem
Problem 1
    - Conclusion: remove laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.3
    - Conclusion: don't install laravel/framework v7.0.2
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - tcg/voyager 1.3.x-dev requires illuminate/support ~5.5|~6.0

## Proposed solution
     Pleace give support to laravel 7

**Comment by jessekanner** [comment]
bump

**Comment by emptynick** [comment]
https://github.com/the-control-group/voyager/issues/4805
