### ISSUE TITLE
Route [voyager.posts.edit] not defined

### ISSUE THREAD

**Issue by avadis** [thedevdojo/voyager#4809]
- Laravel: v5.8.37
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: Ver 14.14 Distrib 5.7.26, for osx10.10 (x86_64) 

After 1 week work with voyager admin i got this errors. i dont know why this happened!

`Route [voyager.posts.edit] not defined. (View: /Applications/MAMP/htdocs/avadis-laravel/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php) (View: /Applications/MAMP/htdocs/avadis-laravel/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)`

**Comment by MrCrayon** [comment]
Since it looks like you already realized it's not a bug but probably something you changed I'm labeling this as questions and as issue template states question should be asked on Voyager Slack chat.
