### ISSUE TITLE
laravel voyager image upload issue on share hosting

### ISSUE THREAD

**Issue by odion-cloud** [thedevdojo/voyager#4810]
## Version information

 - Laravel: v5.8.
 - Voyager:  v1.3.1
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
please i  need help !!!!
after i complete my laravel voyager project,i host the website on share hosting 'whogohost.com'
everything works fine the image i isset before uploading to share hosting is working fine but when i try to update the photo on share hosting the image broke,i have tried all i can it not working ,
please help guys

**Comment by MrCrayon** [comment]
As the issue template says questions should be asked on Voyager Slack chat. 
Also you are not providing any useful information to help you. 
Say what you tried, prepare screenshots, logs and ask on Voyager Slack chat.
