### ISSUE TITLE
Exemple personalized bread without loop

### ISSUE THREAD

**Issue by Burotica** [thedevdojo/voyager#4817]
## Version information
 - Laravel: v6.18.0
 - Voyager: v1.3.2
 - PHP: 7.3.8
 - Database: 5.7.26

## Description of problem
Hello

I'm looking for an example of bread read.blade.php and edit-add.blade.php which doesn't use a loop.
I would like to build them entirely.

Best regard

**Comment by emptynick** [comment]
As the issue template suggests, please ask questions in our Slack group.
