### ISSUE TITLE
Front End Best Practices or Samples?

### ISSUE THREAD

**Issue by ScottPhillips** [thedevdojo/voyager#482]
I know it's slightly out of the project scope, but is there any sample code, examples, or best practices for displaying the BREAD tables on the front end? Even if just for posts or pages as a starting point for developers to use... 

Thanks (and loving voyager).

**Comment by fletch3555** [comment]
I'm not sure what you mean by "displaying the BREAD tables on the front end".  Could you elaborate on what you're trying to do?

**Comment by ScottPhillips** [comment]
If I wanted to show a list of pages or posts to anonymous users on the index page of a website, and for them to have the ability to click on them and read the page or post.

**Comment by fletch3555** [comment]
I'm sorry, that definitely goes beyond the scope of Voyager.  You can accomplish that through normal Laravel functionality.  Your front-end will need it's own controller and views, and can make use of the models from Voyager.
