### ISSUE TITLE
Voyager are too slow in server Hosting

### ISSUE THREAD

**Issue by ousid** [thedevdojo/voyager#4824]
## Version information

 - Laravel: v6.2
 - Voyager: v^1.3
 - PHP: 7.3.11
 - Database: MySQL 8.2

## Description
After deploy laravel app with voyager as an admin dashboard, the loading of the view are too slow and if i opened two pages in the same time it can't be displayed both.

any suggestion 

**Note**: i use server side rendering in all the models.

**Comment by fletch3555** [comment]
If you're going to claim Voyager is slow, please provide evidence.

I'm not saying it's lightning fast, but if it were truly that slow, we'd see tons of people complaining about it.  Most likely, it's something to do with your configuration.

**Comment by ousid** [comment]
this is my second project with voyager and it's slow just in the server but in local it's OK
i will record a video to you and show you 
![voyager-image-slow](https://user-images.githubusercontent.com/21012933/76761783-53f8fe80-6790-11ea-8386-f616cfc051a7.png)

**Comment by ousid** [comment]
[here is a link](https://drive.google.com/open?id=1z6GY42LFVxlGMb980a17GONCSNVKXDII)

**Comment by fletch3555** [comment]
Can you show the network tab instead of the performance tab? I can't really tell what's going on in that screenshot

**Comment by ousid** [comment]
yeah sure
![networktab](https://user-images.githubusercontent.com/21012933/76764336-ea2f2380-6794-11ea-830f-033d4697eb22.png)

**Comment by MrCrayon** [comment]
As far as I can see those are all static files that should be cached by your browser and if they are slow on download that's on your server not Voyager.

**Comment by ousid** [comment]
@MrCrayon  Any Suggestions? 
i will be appreciated

**Comment by MrCrayon** [comment]
I'm not sure, to confirm you can upload a big image in your public folder, try to download it and see what's the download speed, if it's slow you can only change provider to fix it.

You probably already know and you have it set like that for testing but just in case you didn't notice you have "Disable cache" checked in your browser.

**Comment by ousid** [comment]
yeah i see,
thank's for your help guys.
i will figure out what's going on and trying to fix it :)
