### ISSUE TITLE
Media Folder - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Peabo83** [thedevdojo/voyager#4827]
## Version information

 - Laravel: v5.8.37
 - Voyager: v1.3
 - PHP: 7.1.33
 - Database: MySQL 5.7.29

## Description
This is more of a problem than a bug. I've been tasked with fixing a voyager install. The /admin/media loads fine but when some (not all) folders are selected I get the following console error and I get a spinning loading icon:

voyager-assets?path=js%2Fapp.js:1 TypeError: Cannot read property 'length' of undefined
    at a.eval (eval at Ka (voyager-assets?path=js%2Fapp.js:1), <anonymous>:3:8100)
    at a.e._render (voyager-assets?path=js%2Fapp.js:1)
    at a.r (voyager-assets?path=js%2Fapp.js:1)
    at pn.get (voyager-assets?path=js%2Fapp.js:1)
    at pn.run (voyager-assets?path=js%2Fapp.js:1)
    at hn (voyager-assets?path=js%2Fapp.js:1)
    at Array.<anonymous> (voyager-assets?path=js%2Fapp.js:1)
    at Xe (voyager-assets?path=js%2Fapp.js:1)

Screenshot of error: https://imgur.com/BbXqsxf

## Additional context
I've moved the build away from a stand alone server to AWS and the problem persists. The build was originally Voyager 1.2.X and I updated it to 1.3 in hopes of fixing this issue, with no luck. After extensive google-foo, messing with file permissions and a long review of issues on this gitlab, I've been unable to find anyone with a similar issue or a something that lead me to a solution. I've looked through all error logs that I'm aware of and have not found anything relevant or related. I'd really appreciate it if someone could even just give me a hint as to what the issue might be.

Thank you, whoever you are, for taking a moment and reading this.

## Steps To Reproduce
Sadly, I don't think its possible without the specific build I'm working with. 

##Update
I've continued to bash my face on this and I've found something relevant. I can open and view a folder in /admin/media just fine until the folder contains a .PNG file, and that's when it throws the above error.

**Comment by Peabo83** [comment]
##Fix

On the off chance someone stumbles upon this with the same issue, open up /vendor/tcg/voyager/resources/views/media/manager.blade.php and look for the following bit around line 141:

`<div v-if="selected_files.length > 1" class="right_none_selected">`

the value of 'selected_files.lengh' can be null, and is where the error comes from. Create a copy of manager.blade.php to /resources/views/vendor/voyager/media (you may need to create new directories to do this). This file will now override the vendor file, I've changed the above line to the following:

`<div v-if="selected_files.length !== null" class="right_none_selected">`

I hope this helps someone!

**Comment by MrCrayon** [comment]
@Peabo83 I don't really think that **if** `selected_files` can be null your change is a solution, you have the same if just 4 lines below the one you are changing.
```php
<div v-if="selected_files.length > 1" class="right_none_selected">
    <i class="voyager-list"></i>
    <p>@{{ selected_files.length }} {{ __('voyager::media.files_selected') }}</p>
</div>
<div v-else-if="selected_files.length == 1" class="right_details">
```

I don't really see how selected_files can be undefined since it's initialized as empty array and reset as empty array, only operation done on it is push.

I can't reproduce the problem with a PNG, what's the result of ajax call to `/admin/media/files` when you enter that folder?
