### ISSUE TITLE
Add another text editor to body in bread

### ISSUE THREAD

**Issue by Umid-Berdiev** [thedevdojo/voyager#4829]
## Version information

 - Laravel: v5.8.0
 - Voyager: v1.3.0
 - PHP: 7.3
 - Database: PostgreSQL 12

## Description:
I want to user be able to chose text editor for page's body creation. So I want to add grapesjs editor so user could select which editor to use for body creation
## Additional context
I want to get body editor selectable, for example: 
"default": "option1",
    "options": {
        "option1": "Rich Text Box",
        "option2": "GrapesJs"
    }

**Comment by emptynick** [comment]
No one is holding you back from doing so.
Everything else [here](https://voyager-docs.devdojo.com/customization/adding-custom-formfields)
