### ISSUE TITLE
Language Seletor not showing on new bread operations

### ISSUE THREAD

**Issue by Eptech-Danish** [thedevdojo/voyager#4831]
## Version information

 - Laravel: v6.2
 - Voyager: v1.2
 - PHP: 7.3.5
 - Database: MySql 5.7

## Description

Whenever I created new bread it does not show language selector on top of table of new menu neither on update add or create page, I'm searching this to resolved but failed.
kindly guide where to handle this issue so I could work further on voyager!

## Steps To Reproduce

1. create new table
2. create bread and add fields
3. working behavior is fine but not language selector not showing

## Expected behavior
I want language selector on my new created bread operations

## Screenshots
this one is new bread not showing language selector
![image](https://user-images.githubusercontent.com/62466503/77225202-e03f6300-6b8e-11ea-905a-d1c52aa0e3c0.png)

this one is default post bread which is working fine

![image](https://user-images.githubusercontent.com/62466503/77225221-006f2200-6b8f-11ea-9e6d-b8455d24c006.png)

## Additional context
Kindly help me out

**Comment by emptynick** [comment]
What did you do to get it working?

**Comment by Eptech-Danish** [comment]
I create table of events and add bread on it as voyager instructions... my bread is working fine adding updating deleting but issue is I need language selector on all pages to save record in different languages.

Regards,

![image](https://user-images.githubusercontent.com/62466503/77225291-960ab180-6b8f-11ea-8408-3813e6e77874.png)

![image](https://user-images.githubusercontent.com/62466503/77225293-9dca5600-6b8f-11ea-8343-4d323f93430a.png)

**Comment by emptynick** [comment]
https://voyager-docs.devdojo.com/core-concepts/multilanguage

**Comment by Eptech-Danish** [comment]
Thanks a lot! it worked.

**Comment by emptynick** [comment]
Please check the docs before opening issues.

**Comment by Eptech-Danish** [comment]
Hi, 
 As I tested, It shows language selector but not working functionally... I have added multiple language field names while creating bread but its not working...

![image](https://user-images.githubusercontent.com/62466503/77225533-d10de480-6b91-11ea-8da2-d74a7a6f364c.png)

**Comment by MrCrayon** [comment]
@Eptech-Danish you need to change language in your profile, language selector is only to input translations.
If you have any other question please ask in Voyager Slack chat.

**Comment by Eptech-Danish** [comment]
@MrCrayon Thanks I'm on it!
