### ISSUE TITLE
Translations don't work

### ISSUE THREAD

**Issue by futureeducationbr** [thedevdojo/voyager#4832]
- Laravel: v7
 - Voyager: v1.4
 - PHP: 7.4.2
 - Database: MySQL 5.7.26

I have the issue here. My translation didn't work.

$posts = Post::join('categories', function ($join) {
        $join->on('categories.id', '=', 'posts.category_id');
    })->where('categories.parent_id','2')->withTranslations()->get(['posts.created_at','posts.slug','posts.title','categories.name']);

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
Also, this is clearly a question, not a possible bug.

**Comment by futureeducationbr** [comment]
Also didn't work with any Model.
