### ISSUE TITLE
google analytics problem 

### ISSUE THREAD

**Issue by PoulaHelmy** [thedevdojo/voyager#4833]
## Version information

 - Laravel: v6
 - Voyager: v1.4
 - PHP: 7
 - Database:  (e.g. MySQL 8.0)

## Description

make all steps in google console and voyagar dashbourd and the buttun of google analytics appear but with error's

![image](https://user-images.githubusercontent.com/43091492/77259666-c6d01100-6c8b-11ea-8b49-33456a960498.png)

![image](https://user-images.githubusercontent.com/43091492/77259701-144c7e00-6c8c-11ea-9a6c-cb1641d0ad13.png)

**Comment by NourhanMS** [comment]
same issue

**Comment by emptynick** [comment]
Analytics won't work from localhost.
Otherwise everyone could copy your ID from your html source, add it to a localhost page and see your results.

So not a bug but intended by Google with a good reason.

**Comment by NourhanMS** [comment]
thank you for informing me
