### ISSUE TITLE
Product with many images from the second table

### ISSUE THREAD

**Issue by yakushenkovpaul** [thedevdojo/voyager#4835]
Hi! Thanks a lot for your soft!
I want to make the relationship: products "HAS MANY" images.

There are 2 MYSQL TABLES:

Products: id, title, description and etc
Images: id, product_id, main, sort and etc

I need to have the bred for the product and ability to edit images through it, how can I do this?

ps: I can't use "multiple images field" because I will update my tables via the 3third party script, but I should provide the interface to edit them.

**Comment by MrCrayon** [comment]
Please ask questions in Voyager slack chat.
