### ISSUE TITLE
Changing the order of menu items does not work

### ISSUE THREAD

**Issue by bkz-aladin** [thedevdojo/voyager#4837]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.3.14
 - Database: MariaDB 7.4.1

## Description
When I change the order of the menu items nothing changes and I get this error : **Trying to get property 'model_name' of non-object {"userId":1,"exception":{}}**

## Expected behavior
I would like to succeed in changing the order of my menu. HELP PLEASE

**Comment by MrCrayon** [comment]
1.4 has not been released yet, correct version is probably 1.4.x-dev.
That problem should be already fixed with #4834, run composer update.

**Comment by hmorejong** [comment]
@MrCrayon updated to the latest commit but also having the same issue as described in here. I've realized that rolling back the route update at voyager's routes file line 64 it does fix it for me.

`Route::post('order', ['uses' => $namespacePrefix.'VoyagerMenuController@order_item', 'as' => 'order']);`

**Comment by MrCrayon** [comment]
@hmorejong can you explain what you changed?
That line is already in the merged PR:
https://github.com/the-control-group/voyager/blob/fba3257f39cbdf1490b96f9b9b3f41f9b7e0c1c0/routes/voyager.php#L64


Edit
I see the difference but `order_item` is used in the template, maybe you didn't update that
https://github.com/the-control-group/voyager/blob/fba3257f39cbdf1490b96f9b9b3f41f9b7e0c1c0/resources/views/menus/builder.blade.php#L291

**Comment by hmorejong** [comment]
@MrCrayon just double-checked that line, I had it, but it is working now. I'm thinking the routes files were cached probably, before running composer update. I try to stay up to date with the latest changes. Anyway, the error is gone. Thanks for confirming that!
