### ISSUE TITLE
ERROR: Call to a member function count() on array (View: ...voyager\dimmers.blade.php)

### ISSUE THREAD

**Issue by gbesoain** [thedevdojo/voyager#4839]
## Version information
 - Laravel: v6.5.2
 - Voyager: v1.3.2
 - PHP: 7.2.3
 - Database: 10.1.30-MariaDB

## Description
Call to a member function count() on array (View: ...voyager\dimmers.blade.php)

## Steps To Reproduce
1. Login
2. See error

## Expected behavior
Login into voyager admin without error

**Comment by gbesoain** [comment]
Error is not present on Voyager: 1.3.1

**Comment by gbesoain** [comment]
Error was locally introduced

**Comment by jetrodn** [comment]
Run `optimize:clear` after you update voyager from 1.3.1 to 1.3.2 or higher.

You've got cached views from old version
