### ISSUE TITLE
Media picker not generating thumbnails

### ISSUE THREAD

**Issue by ADavid25** [thedevdojo/voyager#4840]
## Version information

 - Laravel: v6.16.0
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: MySQL 14.14

## Description

I'm using do spaces, locally the media picker generates the thumbnails perfectly, but in the server I get an error

## Steps To Reproduce
1. Follow the documentation to generate thumbnails in the media picker
2. Upload a picture using the media picker

## Expected behavior
Image is uploaded perfectly, but I expected to also see the thumbnails in the media manager

## Screenshots
![Screen Shot 2020-03-25 at 4 53 50 PM](https://user-images.githubusercontent.com/52672275/77598680-ae483c80-6ebf-11ea-85be-c99912555cf7.png)

**Comment by MrCrayon** [comment]
The error clearly says it's a problem with your server configuration.
