### ISSUE TITLE
Run any command in Compass get Error

### ISSUE THREAD

**Issue by nuocgansoi** [thedevdojo/voyager#4841]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database: MariaDB 10.1.44

## Description
"Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /vendor/tcg/voyager/src/Http/Controllers/VoyagerCompassController.php on line 74"

## Screenshots
![Capture123eqw](https://user-images.githubusercontent.com/21351524/77645805-f46fcf80-6f95-11ea-8a5a-97c61a6dcb68.PNG)

**Comment by MrCrayon** [comment]
Related https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#process

If you have time please try to change this method:
https://github.com/the-control-group/voyager/blob/4756930366db51458799f0f34b9f633139b9b039/src/Http/Controllers/VoyagerCompassController.php#L21

Remove everything inside the try block except the last two lines and uncomment them.

```php
            try {
                Artisan::call($command . $args);
                $artisan_output = Artisan::output();
            } catch (Exception $e) {
```

**Comment by emptynick** [comment]
I think we can just wrap the parameter in `[]` like we do here now:
https://github.com/the-control-group/voyager/blob/4756930366db51458799f0f34b9f633139b9b039/src/Commands/InstallCommand.php#L97

**Comment by MrCrayon** [comment]
Doesn't work for me
```php
$process = new Process(['cd '.base_path().' && php artisan '.$command.$args]);
```

![Schermata da 2020-03-26 14-02-15](https://user-images.githubusercontent.com/6875243/77649675-8b269700-6f6a-11ea-98f9-c2638a23db52.png)

Using Artisan::call works for the ones I tried but I have no idea why it was commented, there is probably a reason. :thinking:

**Comment by leighlatham123** [comment]
> Related https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#process
> 
> If you have time please try to change this method:
> https://github.com/the-control-group/voyager/blob/4756930366db51458799f0f34b9f633139b9b039/src/Http/Controllers/VoyagerCompassController.php#L21
> 
> Remove everything inside the try block except the last two lines and uncomment them.
> 
> ```
>             try {
>                 Artisan::call($command . $args);
>                 $artisan_output = Artisan::output();
>             } catch (Exception $e) {
> ```

Hi,

Not wanting to hijack this thread, but this workaround allowed my command to run as expected for the one i attempted 'route cache clear' - just wondering what this means for those of us impacted? 

Is this the 'fix' that is waiting to be applied for this bug?
Is this a sufficient work around until we have the chance to upgrade?

Thanks for your help.

**Comment by emptynick** [comment]
There was a fix merged recently. #4856
