### ISSUE TITLE
Custom Dashboard Controller breaks the css 

### ISSUE THREAD

**Issue by rhaider-dev** [thedevdojo/voyager#4843]
## Version information

 - Laravel: v6. 2
 - Voyager: v1.3.2
 - PHP: 7.2
 - Database:  MySQL 8.0

## Description:
I have followed the steps to override a controller using the documentation provided in my case it is the VoyagerController. But, it breaks all the css. Gives a 404 error-voyager assets not found. 

## Additional context
I want to make a custom dashboard with some variables that will be passed through controller.

**Comment by emptynick** [comment]
Like the issue template suggest, please ask questions in our slack group.
