### ISSUE TITLE
VoyagerController overriding issue

### ISSUE THREAD

**Issue by rhaider-dev** [thedevdojo/voyager#4844]
## Version information

 - Laravel: v6.2
 - Voyager: v1.3.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description
Overriding the VoyagerController leads to css not found. 

## Steps To Reproduce
1.Copy all the codes from VoyagerController.php to MyController.php
2. Added AppServiceProvider class in the register method.
$this->app->bind(VoyagerController::class, MyController::class);

## Expected behavior
Expected to have a custom dashboard controller

## Additional context
I want to pass some variable into the dashboard. It passes the variable value successfully. But, all the voyager css are gone.

**Comment by emptynick** [comment]
Same as your other issue. Not a bug but a question.
