### ISSUE TITLE
Target class [App\FormFields\NumberFormField] does not exist

### ISSUE THREAD

**Issue by lyongdee** [thedevdojo/voyager#4847]
## Version information
 - Laravel: v6.18.3
 - Voyager: v1.3.2
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
I do like this.
https://voyager-docs.devdojo.com/customization/adding-custom-formfields

But error:
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\FormFields\NumberFormField] does not exist.

**Comment by MrCrayon** [comment]
That's a basic Laravel error unlikely to be Voyager related.
Double check class name, namespace and where you put your class.

**Comment by MrCrayon** [comment]
Also as far as I know only Voyager 1.4, not released yet, works with Laravel 7 and v1.3.# is not a valid version.

**Comment by lyongdee** [comment]
@MrCrayon I'm using Laravel v6.18.3 and voyager v1.3.2

**Comment by lyongdee** [comment]
@MrCrayon I double-checked the class name, but the error still exists.

**Comment by lyongdee** [comment]
It's OK.
