### ISSUE TITLE
import and relations of fields

### ISSUE THREAD

**Issue by Emmanuel-Reynoso** [thedevdojo/voyager#4848]
## Version information

 - Laravel: v6.5.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database: MySQL

## Description of problem

Hello and thank you for your help. I have my laravel/voyager application ready. My problem is that I have to import 8000 records. When I imported the tables into the database (by MySQL), I didn't know how to relate the fields.

For example:

![aux_item](https://user-images.githubusercontent.com/32149800/77991140-772bbe00-72f9-11ea-82dc-6438c5a38bca.png)
![doc_certi](https://user-images.githubusercontent.com/32149800/77991143-785ceb00-72f9-11ea-98eb-f8dbded2e7a4.png)
![doc_certi2](https://user-images.githubusercontent.com/32149800/77991146-785ceb00-72f9-11ea-8473-6c54fbb4739b.png)
![aux_item2](https://user-images.githubusercontent.com/32149800/77991147-78f58180-72f9-11ea-96ca-d180615dba10.png)

The "item" field in the "doc_certifications" table is related to "aux_items" in the "item" field. The records I have to import already have "item" assigned.

I don't know how to import the records, at the same time that they are related. 

There are several related fields and I feel lost.

## Proposed solution
I really looked and didn't find a smart solution. I was about to use "Macro Recorder" and load one record at a time.

## Alternatives considered
That's a lot of tables with more records. I only showed one as an example.

## Additional context
It will be an import of several tables. In the future it would not be necessary to do it again.

**Comment by MrCrayon** [comment]
This is not a feature request it's a question, please ask questions in Voyager Slack chat.
