### ISSUE TITLE
Belongs to many relation removed when editing user

### ISSUE THREAD

**Issue by ericappcomm** [thedevdojo/voyager#4849]
## Version information

 - Laravel: v7.1.0
 - Voyager: v1.3
 - PHP: 7.3.15
 - Database: 10.3.22-MariaDB-cll-lve

## Description:
I've added a belongs-to-many relationship to the user bread.
First I made a simple pivot tabel company_user
![Screenshot 2020-04-01 at 11 39 23](https://user-images.githubusercontent.com/17049658/78122756-797f3c80-740d-11ea-884c-f585f79bb393.png)

Then added the relation to the user(=medewerker) and company(=bedrijf) bread:
![Screenshot 2020-04-01 at 11 41 15](https://user-images.githubusercontent.com/17049658/78122934-b8ad8d80-740d-11ea-821b-842ebfe4c6dc.png)
![Screenshot 2020-04-01 at 11 41 51](https://user-images.githubusercontent.com/17049658/78122990-cc58f400-740d-11ea-9135-02fd2fc9ddff.png)

I've added the user to a company in the company-edit-page:
![Screenshot 2020-04-01 at 11 43 06](https://user-images.githubusercontent.com/17049658/78123116-fc07fc00-740d-11ea-8623-94a871d6df52.png)

Then opening the user-edit-page
When save the user the relation to the company has gone. 
The record is removed from the company_user table.
In the users edit-page the company is not shown.
Can this be the reason why it is deleted?
And how kan I make the company visible in the user-edit page?

**Comment by MrCrayon** [comment]
Please provide full Voyager version https://github.com/the-control-group/voyager/issues/4836#issuecomment-602634849

~Did you set relationship also in user BREAD?~
~If yes~ can you see that relationship while editing user?

Users have a custom template so that might be the problem.

**Comment by ericappcomm** [comment]
Fixed:
Added code to custom users/edit-add.blade.php:
```
<div class="form-group">
	<label for="companies">COMPANIES</label>
	@php
		$dataTypeRows = $dataType->{(isset($dataTypeContent->id) ? "editRows" : "addRows" )};                                
		$row     = $dataTypeRows->where("field", "user_belongstomany_company_relationship")->first();
		$options = $row->details;
	@endphp
	@include("voyager::formfields.relationship")
</div>
```
