### ISSUE TITLE
Please add support sqlsrv driver.

### ISSUE THREAD

**Issue by wattanar** [thedevdojo/voyager#485]
I've try to use voyager with mssql 2008 with sqlsrv driver and i found problem about table info and bread. I try to fix that with add sqlsrv case in DBSchema.php like this

```
 case 'sqlsrv':
    $query = "SELECT table_name FROM information_schema.tables";
    break;
```
after add sqlsrv case i can create table but still error when create bread or view table info. 

Thank you, btw voyager is a good one laravel backend.

**Comment by fletch3555** [comment]
We need to support this, as it's one of the DBMS that Laravel supports OOTB ([5.3](https://laravel.com/docs/5.3/database#introduction), [5.4](https://laravel.com/docs/5.4/database#introduction), [5.5](https://laravel.com/docs/5.5/database#introduction)).  @marktopper, @tnylea, @akazorg 

We're certainly open to pull requests

**Comment by akazorg** [comment]
We should work on that.

**Comment by renamate** [comment]
hello, any new about this? thanks!

**Comment by ledikari** [comment]
please re-open this. This is a valid concern.

**Comment by fletch3555** [comment]
It's not closed...?

**Comment by marcellopato** [comment]
Any news about it? I am getting this error:

```
Migrating the database tables into your application
Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table

   PDOException  : SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute

  at /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:52
    48|      * {@inheritdoc}
    49|      */
    50|     public function getServerVersion()
    51|     {
  > 52|         return PDO::getAttribute(PDO::ATTR_SERVER_VERSION);
    53|     }
    54| 
    55|     /**
    56|      * {@inheritdoc}

  Exception trace:

  1   PDO::getAttribute()
      /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:52

  2   Doctrine\DBAL\Driver\PDOConnection::getServerVersion()
      /Users/marcellopato/Sites/class/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:467

  Please use the argument -v to see more details.

```
