### ISSUE TITLE
Fill related data within BREAD

### ISSUE THREAD

**Issue by d-cell** [thedevdojo/voyager#4854]
## Version information

 - Laravel: v6.18.3
 - Voyager: v1.4.x-dev
 - PHP: 7.4
 - Database: MariaDB 10.4.12

## Description:
I have a Posts bread to create posts on my website. Posts have a lot of images, so i would like to store image links in separate table. Is it possible to add/choose the images in Posts bread, but save them in related table for images?

## Additional context
In other words, is it possible within bread, change its related data?

**Comment by MrCrayon** [comment]
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
