### ISSUE TITLE
Markdown editor not working

### ISSUE THREAD

**Issue by moathOSA** [thedevdojo/voyager#4855]
- Laravel: v6
 - Voyager: v1.4
 - PHP: 7.3

## Description
when I styling my text in the content field ex #anypost when I publish the post its still appear like this "#anypost" , its must appear as a bold text but its not 

## Screenshots
![image](https://user-images.githubusercontent.com/60176683/78403457-10621980-7605-11ea-959b-587bbbb840cf.png)

**Comment by emptynick** [comment]
It's a markdown editor, so it generates markdown and not HTML.
If you want html use the wysiwyg editor or get a converter to convert markdown to html.
