### ISSUE TITLE
[Help Wanted] Upload multiple file using Voyager Uploader

### ISSUE THREAD

**Issue by ousid** [thedevdojo/voyager#4857]
## Version information

 - Laravel: v6.3
- Voyager: v1.3
 - PHP: 7.2
 - Database: MySQL 8.2

## Description
I'm using voyager as an admin panel and i want to use File Uploader outside voyager on the same project.

any Help i will be appreciated.

**Comment by emptynick** [comment]
Please ask questions in our Slack group.
