### ISSUE TITLE
Displaying category name in the posts listing page in the admin side

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#486]
I need to add a column containing the name of the post category in the posts listing table.
I need to accomplish this in the following screen:

![untxitled](https://cloud.githubusercontent.com/assets/8501654/21638054/495793e4-d272-11e6-8e32-2c40761b4516.png)

I've overridden the posts browse template but I'm trying to get the user record that in relationship with that post record, I can't accomplish this with the use of the **$data** variable.

The only way I know is to query the other model in the template but I think this is a bad way.

Thanks.

**Comment by sidis405** [comment]
#715

**Comment by marktopper** [comment]
This seems to have been solved
