### ISSUE TITLE
am getting this error 

### ISSUE THREAD

**Issue by hussainabuhajjaj** [thedevdojo/voyager#4865]
## Version information

 - Laravel: v6.2
 - Voyager: v1.3
 - PHP:7.2
 - Database: [mysql]  (e.g. MySQL 8.0)

## Description

I am trying to save my data form and there is an image and I got this error.
Intervention\Image\Exception\NotSupportedException
Reading Exif data is not supported by this PHP installation.

**Comment by chadpriddle** [comment]
Looks like you dont have the correct PHP modules installed in your PHP version
