### ISSUE TITLE
Call php artisan cache:clear made sidebar menu disapear forever

### ISSUE THREAD

**Issue by zmj888** [thedevdojo/voyager#4868]
## Version information

 - Laravel: v6.18.3
 - Voyager: v1.3.2
 - PHP: 7.4
 - Database: [Postgresql] [12]

## Description

Call php artisan cache:clear made sidebar menu disapear forever.

## Steps To Reproduce
1. Call 'php artisan cache:clear'
2. See error

**Comment by MrCrayon** [comment]
> See error

There is no way for us to know what's happening if you don't post the error.

**Comment by devstack-be** [comment]
I don't have any problem with the following command 

> Call 'php artisan cache:clear'
