### ISSUE TITLE
Cant Create Users In The Specified Table

### ISSUE THREAD

**Issue by agent2020** [thedevdojo/voyager#487]
- Laravel Version: 5.3
- Voyager Version: 0.10.7
- PHP Version:
- Database Driver & Version:

### Description:
i cant have the new user created in the table created, it keeps using User Table Instead of Admin Table, please how do i fix this

'user' => [
'add_default_role_on_register' => true,
'default_role' => 'user',
'admin_permission' => 'browse_admin',
'namespace' => App\Admin::class,

### Steps To Reproduce:
when i run
php artisan voyager:admin user@mymail.com --create

**Comment by cloudsben** [comment]
You don't want to use Users Table? isn't it?

**Comment by agent2020** [comment]
Yes I don't want too I want to use a custom model and table

**Comment by handiwijoyo** [comment]
You should modify config/auth.php instead when using custom model:
```
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
```

Or inside your user model add: 
```
protected $table = 'admins';
```

**Comment by marktopper** [comment]
Closing this since I have just created a pull request for it.

Pull #541
