### ISSUE TITLE
Unable to install Voyager 1.3.2 on Laravel 7.4

### ISSUE THREAD

**Issue by mjomble** [thedevdojo/voyager#4872]
## Version information
 - Laravel: v7.4.0
 - Voyager: v1.3.2
 - PHP: 7.4.4
 - Database: irrelevant
 - Composer: 1.10.1

## Description
Installing `tcg/voyager` installs unstable version `1.x-dev` and installing `tcg/voyager:1.3.2` fails.

## Steps To Reproduce
1. composer global require laravel/installer
2. laravel new .
3. composer require tcg/voyager

```
Using version ^1.3 for tcg/voyager
.....
  - Installing tcg/voyager (1.x-dev 7af8ae1): Cloning 7af8ae189d from cache
```

4. composer require tcg/voyager:1.3.2

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tcg/voyager 1.3.2 -> satisfiable by tcg/voyager[v1.3.2].
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - tcg/voyager v1.3.2 requires illuminate/support ~5.5|~6.0 -> satisfiable by illuminate/support[5.5.x-dev, 5.6.x-dev, ....., v6.7.0, v6.8.0].
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v7.4.0
    - don't install illuminate/support v5.5.0|don't install laravel/framework v7.4.0
    - don't install illuminate/support v5.5.16|don't install laravel/framework v7.4.0
.....
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.4.0
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.4.0
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.4.0
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.0) -> satisfiable by laravel/framework[v7.4.0].


Installation failed, reverting ./composer.json to its original content.
```

## Expected behavior
I expected `composer require tcg/voyager` to install Voyager 1.3.2 without any errors.

**Comment by emptynick** [comment]
Please search before opening new issues.
Duplicate of #4812, #4807, #4805 and possibly a few more.

**Comment by mjomble** [comment]
I actually made several searches using terms like "1.x-dev", "composer", "illuminate" etc, but didn't find anthing relevant to my problem.

To be fair, the search for "composer" did have #4802 in the results, but I overlooked it as the documentation already says that Laravel 7 is supported: https://voyager-docs.devdojo.com/getting-started/prerequisites even though it seems this will actually be added in a future release.
So I didn't suspect lack of Laravel 7 support to be the cause of the problem.

I also looked at the "Similar to 4 existing issues" that GitHub suggested based on the title, but it gave me issues like #4259, #3564 and #141 which weren't very relevant.

**Comment by fletch3555** [comment]
That documentation is for v1.4, which has not been officially released yet.  Sorry for the confusion.  The same page for v1.3 shows Laravel 7 is not supported: https://voyager-docs.devdojo.com/v/1.3/getting-started/prerequisites.

If you're ever curious about versions, you can look at packagist, which is where composer pulls it's information from: https://packagist.org/packages/tcg/voyager.  The right sidebar lists all available versions (`dev-` prefix or `-dev` suffix indicate git branches, not actual released versions.  For just released versions, you can always check our releases: https://github.com/the-control-group/voyager/releases

**Comment by mjomble** [comment]
> That documentation is for v1.4, which has not been officially released yet.

Ah, strange. Shouldn't the website by default show the documentation for the latest stable release, instead of an unreleased future version?

**Comment by fletch3555** [comment]
Yes it should.  We got ahead of ourselves a bit.  The intent was to release 1.4 last week when this version of the docs was released, but we had an influx of security issues to fix first
