### ISSUE TITLE
Voyager 1.4 bread problem. Target class does not exist.

### ISSUE THREAD

**Issue by mikolajborowski** [thedevdojo/voyager#4874]
## Version information
 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: v7.4
 - Database: local sqlite

## Description
Im faceing problem when i click Tools -> bread -> {any table} -> add BREAD to this table -> { im createing bread } -> submit -> see error. 
BindingResolutionException
Target class [App\UserRole] does not exist.
It pops up to any table.

## Steps To Reproduce
1. Go to Tools
2. Go to bread
3. Click add BREAD ... to any table 
4. Create bread
5. Click submit 
6. See error

## Screenshot
![image](https://user-images.githubusercontent.com/36244604/78549695-10c80380-7803-11ea-8534-2748af408f2f.png)

## Additional context
Only things i have done, are create laravel project, and add voyager to it. When i try to add bread, it does not work. Rest of voyager functionalities like menu builder work.

**Comment by emptynick** [comment]
The BREAD builder does not create models.
Only the database tool creates one if you create a new table and select "Create model".

So you just have to create the model, either by running `php artisan make:model YourModel` or by using the database tool.

**Comment by odeke** [comment]
I believe you should reopen this. I followed the same steps as @mikolajborowski  said, and even selected "Create model" while making the table. 
Afterwards I tried to make bread, and it failed because of a missing model. 
It only worked after I manually run `php artisan make:model MyModel`

**Comment by sokratesli** [comment]
Is this problem already fixed. I still get the error. I created the models manualy (`php artisan make:model YourModel`).

**Comment by ahmadalzoabi** [comment]
excuse me @mikolajborowski.
 How did I fix the problem. it faced me?

**Comment by kamel7dz** [comment]
Illuminate\Contracts\Container\BindingResolutionException
Target class [App\Product] does not exist.
probleme in laravel 8

**Comment by Rafkurit** [comment]
@mikolajborowski 
@kamel7dz 
If you are using a newer version of Laravel: 
When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

**Comment by Khaldi-Anouar** [comment]
Hello,
This happened to me when I changed a table name (from host/admin/database/{table}).
When changing a table name don't forget to change the model file name and the model class name.
Hope this helps!

**Comment by AvishkaWeebadde** [comment]
> @mikolajborowski
> @kamel7dz
> If you are using a newer version of Laravel:
> When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

This is the solution. I faced with the same problem due to my carelessness. This fixed it. Thanks.

**Comment by kalikim** [comment]
> @mikolajborowski
> @kamel7dz
> If you are using a newer version of Laravel:
> When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

This worked like magic thanks for this

**Comment by Etienne-Dgs** [comment]
Hello, 

After creating the Table I managed to move it in my Models thanks to config (voyager.php) : 

'models' => [
        'namespace' => 'App\\Models\\',
    ],

I had quite the same issue, resolved it by adding the right directory in the namespace of my Model file, just that : 

namespace App\Models;

**Comment by Mariam-Naz** [comment]
> @mikolajborowski
> @kamel7dz
> If you are using a newer version of Laravel:
> When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

Thank you so much it works for me!!

**Comment by pheaborey** [comment]
> @mikolajborowski @kamel7dz If you are using a newer version of Laravel: When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

I solved it Thanks

**Comment by dhairya-desai** [comment]
I am still facing the same issue . can anyone help me to solve??

**Comment by bpincaro** [comment]
> @mikolajborowski @kamel7dz If you are using a newer version of Laravel: When making BREAD, use **App \ Models \ Your_Model** - instead of App \ Your_Model

This worked for me!
Thanx

**Comment by devloVinci** [comment]
When making BREAD, use **App\Models\your_model** ,
  **AND** in file App\Models\your_model write after (`namespace App\Models;`) :
   **`$namespace = 'App\Models';`**
