### ISSUE TITLE
The results could not be loaded

### ISSUE THREAD

**Issue by xtent1405** [thedevdojo/voyager#4877]
- Laravel: 7.4.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database: phpmyadmin5.0.2

Hi I'm relatively new to laravel and came across this voyager admin panel. I decided to use it for my homework. (I'm a 15 year old High School student btw.) Everything's working fine but after I created a relationship between Answers table & Questions table, it says "The results could not be loaded". I also checked the pre-created user and roles table, it also states the same thing. I didn't change anything in this part. I followed the https://voyager.devdojo.com/academy tutorial. Please help I'm very new to laravel and voyager. I really like using it. Thanks guys

![Screenshot (121)](https://user-images.githubusercontent.com/63296468/78675779-1feca580-7918-11ea-897d-44cae51a8661.png)
![Screenshot (122)](https://user-images.githubusercontent.com/63296468/78675787-22e79600-7918-11ea-9148-aa50cb579d96.png)
![Screenshot (123)](https://user-images.githubusercontent.com/63296468/78675795-2549f000-7918-11ea-8476-7543c34cb783.png)
![Screenshot (124)](https://user-images.githubusercontent.com/63296468/78675801-2713b380-7918-11ea-8ef5-9555bd7b40eb.png)
![Screenshot (125)](https://user-images.githubusercontent.com/63296468/78675810-2b3fd100-7918-11ea-913d-f015fd6f35e7.png)

Thanks again guys more power!

**Comment by emptynick** [comment]
I doubt that you are using Voyager 1.3 as only 1.4 is compatible with Laravel 7.
Please check and correct the correct version either by looking in the footer or running `composer show tcg/voyager`

**Comment by xtent1405** [comment]
@emptynick Hi sir yes its voyager 1.4. my bad i'll edit it

**Comment by xtent1405** [comment]
@emptynick What do I need to do to fix my issue sir? Thanks for the response and your time sir.

**Comment by MrCrayon** [comment]
Since 1.4 is still in development you probably installed it while there was a bug, you can try to remove tcg folder inside vendor and run
```shell
composer update
```

If you want to check what's exactly the problem, it could be a good way to learn how to debug IMHO, you can:
 - Open developer tools in your browser
 - Go in Network tab
 - Try to open a relationship (options are loaded with an ajax call)
 - You should see a call with an error, click on it and open the sub tab Response to see error stack trace.

You should be able to see the full error stack trace also in `storage/logs/`

**Comment by xtent1405** [comment]
@MrCrayon Thanks sir for the reply. I'll try it in a while, hopefully it works. Thanks for being helpful. I'll let you know.

**Comment by xtent1405** [comment]
@MrCrayon Hi sir this happened, although im still waiting for the retrying.
![image](https://user-images.githubusercontent.com/63296468/78687841-2cc4c580-7927-11ea-89e7-ccb8eb2e4055.png)

**Comment by xtent1405** [comment]
@MrCrayon hi sir I saw this error. I checked the users/roles relationship, same error sir.
![image](https://user-images.githubusercontent.com/63296468/78693667-26861780-792e-11ea-8be9-5b9a0746c4f5.png)
Here is the line 860 of my file 
![image](https://user-images.githubusercontent.com/63296468/78694001-9e544200-792e-11ea-8bc1-cfd9a0e81f24.png)

**Comment by xtent1405** [comment]
@MrCrayon @emptynick I just want to know if its possible to use an older version of voyager if ever? and what do i need to do to use a more stable version?

**Comment by xtent1405** [comment]
@MrCrayon Composer update finally worked sir. Thanks!
