### ISSUE TITLE
[Feature] multi-language

### ISSUE THREAD

**Issue by cloudsben** [thedevdojo/voyager#488]
I wanna translate Dashboard to Chinese, how can I do.

I can not find lang folder in project.

**Comment by fletch3555** [comment]
This is not currently possible, though there are numerous other issues already requesting this functionality.  I'm going to close this one for now.

**Comment by wangxiaomo** [comment]
@cloudsben you can check [voyager i18n-zh](https://github.com/wangxiaomo/voyager/tree/i18n-zh) 

i translate most words in chinese and i use it with my local product. hope it will help you.

**Comment by cloudsben** [comment]
@wangxiaomo Thanks a lot !

**Comment by Enyelber** [comment]
Hello, as I set it to take the other language and not the default language?
