### ISSUE TITLE
Error still show up after successfully restored a post

### ISSUE THREAD

**Issue by mrdeeds88** [thedevdojo/voyager#4880]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MySQL 5.5.5-10.4.12-MariaDB

## Description

I create a new Post model extends the Voyager Post, and then I add SoftDeletes to the new Post model. The restore function works fine but it still shows an error message: "Sorry it appears there was a problem restoring this Post". 

I do the same thing to User model, and the restore function works perfectly.

I try to dump the $res variable in VoyagerBaseController.php (line 511) and the result is true for the User, null for the Post.

My Post model looks like this:

_namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends \TCG\Voyager\Models\Post
{
    use SoftDeletes;
}_

## Steps To Reproduce
1. Add deleted_at field to the posts table
2. Add Post model extends Voyager Post, change the model name of Post bread to "App\Post"
3. Delete then restore the post
4. See error: "Sorry it appears there was a problem restoring this Post"

## Expected behavior
It should show "Successfully restored post"

## Screenshots
![image](https://user-images.githubusercontent.com/2483279/78878063-fa78ac80-7a7b-11ea-9706-44d9281ac0a6.png)

**Comment by emptynick** [comment]
Do you use a scope in the Posts BREAD?

**Comment by MrCrayon** [comment]
The problem is here where result of `save` is not returned:
https://github.com/the-control-group/voyager/blob/deea8d1399822a3aaa2a0817ae913885e42436ed/src/Models/Post.php#L30

You can temporarly fix it overriding save method in your model:
```php
    public function save(array $options = [])
    {
        // If no author has been assigned, assign the current user's id as the author of the post
        if (!$this->author_id && Auth::user()) {
            $this->author_id = Auth::user()->getKey();
        }

        return parent::save();
    }
```
