### ISSUE TITLE
Model's additional attributes no longer show up in a relationship's display select list

### ISSUE THREAD

**Issue by tjebe** [thedevdojo/voyager#4882]
## Version information

 - Laravel: v7.5.2
 - Voyager: v1.4.0
 - PHP: 7.2.28
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

Model's additional attributes no longer show up in a relationship's display select list.

## Steps To Reproduce
1. Create new relationship
2. Click on "Display the [tablename]"
3. Select list no longer contains additional attributes from model

## Expected behavior
Select list should contain additional attributes as well.

## Proposed Solution
In file <b>resources/views/tools/bread/edit-add.blade.php</b>, the addition of lines 617-619 performs an empty object check that takes care of additional attributes.

<pre>
    616                     var options = $.map(data, function (obj, key) {
    617                         if($.isEmptyObject(obj)) {
    618                                 obj = {};
    619                         }
    620
    621                         obj.id = key;
    622                         obj.text = key;
    623
    624                         return obj;
    625                     });
</pre>

**Comment by MrCrayon** [comment]
@tjebe thanks for reporting this, I added you as coauthor for PR.
Next time fill free to open PR yourself. :+1:
