### ISSUE TITLE
I can not create and edit POST Voyage 1.4

### ISSUE THREAD

**Issue by arhitektorr** [thedevdojo/voyager#4883]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2
 - Database: [type] [version] (e.g. MeriaDB 10.3)

## Description

The database has been moved from another site. made Bread to an existing news table. Problem with editing and adding

![4444](https://user-images.githubusercontent.com/63448959/79107021-4e390d80-7d7c-11ea-9961-f4d4fbc2ce18.JPG)

**Comment by MrCrayon** [comment]
You are most probably missing something in your new Database or messed up ids for `data_types`.
Check that `data_types.id` for `posts` in your new database is the same as the old one and then verify that `data_rows` for posts are there with correct `data_type_id`.

If you can't solve please post screenshots of your `data_types` table and `data_rows` table with `data_type_id` for `posts`.

**Comment by arhitektorr** [comment]
@MrCrayon  
![1](https://user-images.githubusercontent.com/63448959/79109022-39f70f80-7d80-11ea-9bd8-2a48c948483a.JPG)
![2](https://user-images.githubusercontent.com/63448959/79109024-3a8fa600-7d80-11ea-9599-b459615b1aae.JPG)
![3](https://user-images.githubusercontent.com/63448959/79109026-3b283c80-7d80-11ea-9c4e-4d92a9cdcad0.JPG)

**Comment by MrCrayon** [comment]
posts table was not needed, you need to check **_data_rows_** table where **_data_type_id = 23_**

**Comment by arhitektorr** [comment]
How to do this, I did not understand what exactly to check? And How

**Comment by MrCrayon** [comment]
execute this query:
```SQL
SELECT * FROM `data_rows` WHERE `data_type_id` = 23;
```

**Comment by arhitektorr** [comment]
@MrCrayon  ![666](https://user-images.githubusercontent.com/63448959/79111009-5ac16400-7d84-11ea-8fcb-e67a76daf51b.JPG)

**Comment by MrCrayon** [comment]
You are using Voyager default **posts/edit-add** view that has some hardcoded fields since it's just demo content.
To be more specific **body** field is required if you are using that template
https://github.com/the-control-group/voyager/blob/55d6d0445bb8fbcbf9f9cec26685ead9b7f8443b/resources/views/posts/edit-add.blade.php#L124

You can add a **body** field to your table, change your **fulltext** field name to **body** or use your custom view for posts as explained in Voyager documentation.

**Comment by arhitektorr** [comment]
@MrCrayon Thanks! It helped, the problem, as you said, was in the field that did not match the one specified in the template.
