### ISSUE TITLE
Cant see profile images, and preview or see thumbnails media after uploading in media manager

### ISSUE THREAD

**Issue by pro-cms** [thedevdojo/voyager#4885]
## Version information

 - Laravel: v 7.
 - Voyager: latest
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

I uploaded the profile but it still show no image, i go to media manager and try to upload image file , it is uploaded but cant view the the file
## Steps To Reproduce
1. Go to 'media'
2. Click on '.upload image
![d(5)](https://user-images.githubusercontent.com/57701433/79134156-e9020e00-7db5-11ea-908d-74c7149dc3b8.png)
![d(4)](https://user-images.githubusercontent.com/57701433/79134159-eacbd180-7db5-11ea-82c5-e577f11f64f2.png)
![d(3)](https://user-images.githubusercontent.com/57701433/79134162-eb646800-7db5-11ea-8dc1-0287758e863e.png)

'

**Comment by MrCrayon** [comment]
Please edit your first post with actual versions (ex. 1.4.0)

Check APP_URL in your. env file.

**Comment by pro-cms** [comment]
Thanks, I made an error in .env with APP_URL, Be blessed guys your doing impressive things

> Please edit your first post with actual versions (ex. 1.4.0)
> 
> Check APP_URL in your. env file.
