### ISSUE TITLE
MIssing <div> in views/menus/builder.blade.php

### ISSUE THREAD

**Issue by londoh** [thedevdojo/voyager#4887]
## Version information

 - Laravel: v7
 - Voyager: v1.4
 - PHP: 7.3
 - Database:mariadb 10.3

## Description

There's a missing ,div> tag in views/menus/builder.php
https://github.com/the-control-group/voyager/blob/1.4/resources/views/menus/builder.blade.php#L93
This means that the textarea for route params doesnt show up

## Steps To Reproduce
1. Go to admin/menus/1/builder
2. Click on the 'Edit' link for Dashboard
3. Notice there is no textarea to edit route params

## Expected behavior
That  there should be a textarea to edit route params

## Proposed solution
adding the following at L93 will fix the problem
`                        </div>
                        <div id="m_parameters">`

## Problem and Proposed Solution as per attached screenshots
![Voyager-EditMenuItem-NoParamsField](https://user-images.githubusercontent.com/801398/79253012-73ac4100-7e7a-11ea-9835-47741025af94.jpg)
![Voyager-EditMenuItem-NoParamsDiv](https://user-images.githubusercontent.com/801398/79253019-77d85e80-7e7a-11ea-8f32-f744ba78708e.jpg)
![Voyager-EditMenuItem-WithParamsField](https://user-images.githubusercontent.com/801398/79253035-7d35a900-7e7a-11ea-8c3b-bb1e7f04acd3.jpg)
![Voyager-EditMenuItem-WithParamsDiv](https://user-images.githubusercontent.com/801398/79253043-7f980300-7e7a-11ea-9fc0-c140a39bd9bf.jpg)

**Comment by emptynick** [comment]
I'm not sure I fully understand.
A static URL does not have route parameter, only a route does.

So it should be hidden when `Static URL` is selected and shown when `Route` is.

**Comment by londoh** [comment]
ahha - you are of course correct!
I dunno how I missed that.
closing due to stoopidity
