### ISSUE TITLE
How to push project with Voyager Admin panel to github or live server.?

### ISSUE THREAD

**Issue by omaralalwi** [thedevdojo/voyager#4888]
first of all , thank you very much for your great job..
after I finish project I make git push to github then to live server but when I make composer install or update in server , this command delete all relationships and functions in Category model and some Voyager Setting, any way to solve this problem.

**Comment by emptynick** [comment]
From the issue template:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

**Comment by Buthaina94** [comment]
did you solve the problem? I have same one
