### ISSUE TITLE
Menu Icon doesn't appear

### ISSUE THREAD

**Issue by fernandbong** [thedevdojo/voyager#4890]
## Version information

 - Laravel: v7.1.1
 - Voyager: v1.3
 - PHP: 7.2.5

## Description
Not all menu icons appear, only display the first menu after I make BREAD while the second does not appear. And it happens repeatedly in each even menu. 

## Screenshots
![Capture](https://user-images.githubusercontent.com/40467314/79370394-c79f4e80-7f7c-11ea-88c8-bb1cd7bf5c63.PNG)
![Capturee](https://user-images.githubusercontent.com/40467314/79370404-cb32d580-7f7c-11ea-86b4-2b54cad7b95d.PNG)

**Comment by fernandbong** [comment]
sorry if my english is not good

**Comment by emptynick** [comment]
Please post a screenshot of both the shops and coupons bread settings.

**Comment by fernandbong** [comment]
@emptynick 
![bread coupon](https://user-images.githubusercontent.com/40467314/79375108-4ba80500-7f82-11ea-8b22-7f58df978c92.PNG)
![bread shop](https://user-images.githubusercontent.com/40467314/79375110-4cd93200-7f82-11ea-800b-eb9e440c1856.PNG)

**Comment by MrCrayon** [comment]
Did you set the icon after creating BREAD?

Menu item is created after creating BREAD, if you don't set icon on BREAD creation menu item will be created without icon and it will not be updated even if you add the icon in BREAD setting.

To solve your problem edit the menu and add the icon.

You can verify if it works creating a new BREAD with the icon set, if that doesn't work there could be a bug but it's quite unlikely.

**Comment by MrCrayon** [comment]
Closing this since there was no feedback.
