### ISSUE TITLE
Target class [VoyagerController] does not exist

### ISSUE THREAD

**Issue by Morgul21** [thedevdojo/voyager#4892]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2
 - Database: MariaDB 10.4.11

## Description:
After installation,going in the admin section always return Target class [VoyagerController] does not exist
Even manually adding the controller won't resolve this.
![Cattura](https://user-images.githubusercontent.com/40770929/79481492-dedb4c00-800f-11ea-97cb-231a2cc9a07c.PNG)

**Comment by emptynick** [comment]
I'm not sure how we should help you without any information at all.
Please provide the requested information from the issue template.

**Comment by bappi2016** [comment]
I am also having this issue right now.

**Comment by MrCrayon** [comment]
That error means it's not getting the namespace while initializing routes.
What's the content of your voyager config file for `controllers.namespace`?

**Comment by Morgul21** [comment]
> 
> 
> That error means it's not getting the namespace while initializing routes.
> What's the content of your voyager config file for `controllers.namespace`?

This is the content namespace of config/voyager.php. Seems there's anything wrong to me
`   'controllers' => [
        'namespace' => 'TCG\\Voyager\\Http\\Controllers',
    ], `

In web.php I've also added the Voyager Facades class,that seems was missing,but it didn't resolve anything 

```
use TCG\Voyager\Facades\Voyager;

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```

**Comment by MrCrayon** [comment]
You shouldn't need to add the Facade because it should be already registered by Voyager service provider.
I think that's the coolprint and voyager config is not merged either since VoyagerServiceProvider is not registered.

To confirm you can put in web.php:
```php
dd(config('voyager.controllers.namespace'));
```

It's probably going to be empty.

To solve try from console:
```shell
php artisan config:clear
composer dump-autoload
```

**Comment by Morgul21** [comment]
> 
> 
> You shouldn't need to add the Facade because it should be already registered by Voyager service provider.
> I think that's the coolprint and voyager config is not merged either since VoyagerServiceProvider is not registered.
> 
> To confirm you can put in web.php:
> 
> ```
> dd(config('voyager.controllers.namespace'));
> ```
> 
> It's probably going to be empty.
> 
> To solve try from console:
> 
> ```shell
> php artisan config:clear
> composer dump-autoload
> ```


Thank you so much for your help, it worked!
