### ISSUE TITLE
I can't upload or show pictures in Laravel Voyager.

### ISSUE THREAD

**Issue by itsred1e** [thedevdojo/voyager#4893]
## Version information

 - Laravel: v7.0
 - Voyager: v^1.4
 - PHP: 7.25

## Description

I push my project to Heroku, locally it works perfect but in Heroku, the pictures are not showing

## Screenshots
![image](https://user-images.githubusercontent.com/62271319/79561302-08908380-80a1-11ea-9a48-81b9384db0b9.png)
![image](https://user-images.githubusercontent.com/62271319/79561489-586f4a80-80a1-11ea-9015-ecfb1f9c2951.png)
![image](https://user-images.githubusercontent.com/62271319/79561544-6ae98400-80a1-11ea-869c-5f9b4a80435c.png)
![image](https://user-images.githubusercontent.com/62271319/79561577-79d03680-80a1-11ea-8a64-9115662ebd84.png)
![image](https://user-images.githubusercontent.com/62271319/79561610-894f7f80-80a1-11ea-9a65-3e082bc0d3ec.png)

**Comment by MrCrayon** [comment]
Please don't use `v^1.4` report the actual version installed not the one required.

Did you set the correct APP_URL?

What's the url of one of the missing images?

**Comment by itsred1e** [comment]
![image](https://user-images.githubusercontent.com/62271319/79573952-51ebcd80-80b7-11ea-8cc7-bdb343c8beca.png)
![image](https://user-images.githubusercontent.com/62271319/79573963-56b08180-80b7-11ea-9369-3c47160af6a4.png)

Yes, I add it as a parameter in Heroku, for the version what should I do please?

**Comment by MrCrayon** [comment]
> Yes, I add it as a parameter in Heroku, for the version what should I do please?

You should be able to see it in the footer
![Schermata da 2020-03-23 15-33-22](https://user-images.githubusercontent.com/6875243/77327549-b0719600-6d1b-11ea-9d65-cae2da02b820.png)
Or run in console
```shell
composer show tcg/voyager
```

Also please answer:
> What's the url of one of the missing images?

**Comment by MrCrayon** [comment]
Url of missing image looks ok, most probably there is a problem with your storage configuration.
Default configuration is:
```php
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

What's set as storage disk in voyager config file?

**Comment by itsred1e** [comment]
> ```shell
> composer show tcg/voyager
> ```

![image](https://user-images.githubusercontent.com/62271319/79579945-31744100-80c0-11ea-9512-d28a2e4b6e53.png)

**Comment by itsred1e** [comment]
> Url of missing image looks ok, most probably there is a problem with your storage configuration.
> Default configuration is:
> 
> ```
>         'public' => [
>             'driver' => 'local',
>             'root' => storage_path('app/public'),
>             'url' => env('APP_URL').'/storage',
>             'visibility' => 'public',
>         ],
> ```
> 
> What's set as storage disk in voyager config file?

i have to like that 


`'public' => [

            'driver' => 'local',

            'root' => storage_path('app/public'),

            'url' => env('APP_URL').'/storage',

            'visibility' => 'public',
        ],
`

**Comment by itsred1e** [comment]
![image](https://user-images.githubusercontent.com/62271319/79580643-35549300-80c1-11ea-9a26-11f6e8d91fff.png)

**Comment by MrCrayon** [comment]
> i have to like that

that's not in voyager config file.

**Comment by itsred1e** [comment]
> > i have to like that
> 
> that's not in voyager config file.

sorry I don't understand

**Comment by MrCrayon** [comment]
> What's set as storage disk in voyager config file?

`/config/voyager.php`

https://github.com/the-control-group/voyager/blob/f4e6775364a00716a85b8f0fdfe729df68a47913/publishable/config/voyager.php#L58

**Comment by itsred1e** [comment]
![image](https://user-images.githubusercontent.com/62271319/79585199-5c15c800-80c7-11ea-9f45-ad8672743d72.png)

**Comment by MrCrayon** [comment]
Now you'll need to recreate the symlink that was created when your configuration was not set correctly.
You can probably remove `/public/storage` symlink and let voyager recreate it or you can run:
```shell
php artisan storage:link
```

**Comment by itsred1e** [comment]
![image](https://user-images.githubusercontent.com/62271319/79587267-3211d500-80ca-11ea-8341-f06ae548f3aa.png)
i remove it and i run it still same problem

**Comment by MrCrayon** [comment]
You might want to have a look here #575

**Comment by fletch3555** [comment]
Yeah, I haven't used Heroku in a VERY long time, but I believe the filesystem is readonly, so you're expected to use some form of cloud storage (S3 or similar).  Without that, Voyager will never fully work on Heroku.

**Comment by MrCrayon** [comment]
https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted
