### ISSUE TITLE
Unable to see my web-socket dashboard after insllation of laravel websocket. getting error Trying to get property 'name' of non-object

### ISSUE THREAD

**Issue by aly-abdelkader-iut-cse-4301** [thedevdojo/voyager#4894]
## Version information

 - Laravel: 7.0
 - Voyager: 1.4
 - PHP: 7.3.2
 - Database: [MySQL] [5.3] 

## Description

I installed laravel-voyager on a fresh project, after which I installed Laravel web socket. But when I am  trying to access my websocket dashboard, it is throwing  the error:"Trying to get property 'name' of non-object"; This error is thrown by vendor\tcg\voyager\src\Policies\BasePolicy.php:86 (line 86).But if i replace the line 86 by just returning true I can access my websocket dashboard
If i dd( $dataType) of vendor\tcg\voyager\src\Policies\BasePolicy.php of line 83, it returns me null.
if I dd($action) it returns "viewWebSocketsDashboard"

## Steps To Reproduce
1. install a fresh laravel project '...'
2. install websocket '....'
3. brwose to websocket dashboard  'http://127.0.0.1:8000/sockets'

## Expected behavior
it was suppose to display my websocket dashboard

**Comment by fletch3555** [comment]
You haven't actually said what package you're using... Having said that, we can't guarantee compatibility between voyager and any specific package.  Something about that package or how you're using it is using a model that is registered in Voyager's BREAD system, which means it's automatically associating the model with the `BasePolicy` for Voyager's permissions system.

**Comment by aly-abdelkader-iut-cse-4301** [comment]
I am using beyondcode/laravel-websockets

**Comment by sioannides** [comment]
I have the same issue...any solution on this?

**Comment by abdelkadergelany** [comment]
> I have the same issue...any solution on this?

I had to Modify the fuction **checkPermission(User $user, $model, $action)** found at (vendor\tcg\voyager\src\Policies\BasePolicy.php)
to this:
![Annotation 2020-05-06 113833](https://user-images.githubusercontent.com/52650657/81141342-29584480-8f8e-11ea-9ac3-9a3dd552dc6a.png)

**Comment by MrCrayon** [comment]
I would not advice to change anything under vendor unless it's just for a temporary test. 

You can create your own user policy extending `\TCG\Voyager\Policies\UserPolicy`, add `viewWebSocketsDashboard` method and assign it in users BREAD settings.

**Comment by abdelkadergelany** [comment]
Yes that was for a temporary solution since I could not find better solution. I tried to google it without success

**Comment by bigbenbeer** [comment]
> I would not advice to change anything under vendor unless it's just for a temporary test.
> 
> You can create your own user policy extending `\TCG\Voyager\Policies\UserPolicy`, add `viewWebSocketsDashboard` method and assign it in users BREAD settings.

How would one go about doing this, I am faced with the same problem?

**Comment by fletch3555** [comment]
@bigbenbeer you would do exactly what is said in the comment you quoted.

If you have further questions, please ask in our slack group.  We discourage commenting in closed issues.
