### ISSUE TITLE
How can i add PDF Download to voyager dashboard ?

### ISSUE THREAD

**Issue by robertkingkira** [thedevdojo/voyager#4895]
**## Version information**
 - Laravel: v6.2.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL

**## Description:**
I know this was asked before , but I'm not asking you to add this feature , i just want to know what exactly i need to do to implement this for myself , like which file do i need to edit that would be the most important thing and then how can i edit them whithout breaking anything ?

**Something like this:**
![voyager-pdf](https://user-images.githubusercontent.com/46875103/79634450-b4ea6c80-816a-11ea-936f-e2bb1012c694.png)

**Comment by MrCrayon** [comment]
As the issue template states: 
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

**Comment by robertkingkira** [comment]
It was just a question , and i didn't even know about this SLACK , thanks for nothing.
