### ISSUE TITLE
CSRF Token Missmatch when trying to login

### ISSUE THREAD

**Issue by D4nyi** [thedevdojo/voyager#4896]
## Version information
 - Laravel: v6.18.8
 - Voyager: v1.4.1
 - PHP: 7.4
 - Database(server): mysql  Ver 14.14 Distrib 5.7.29,
 - Database(developement): MariaDB 10.4.11 database server, mysql 5.5.5,
- OS(server): Ubuntu 16.04.6 LTS, Nginx 1.10.3, Digital Ocean hosting,
- OS(developement): Win10, WinNMP (latest), Nginx 1.17.7

## Description
(I'm new in PHP, Laravel world.)
I just simply run through the installation guid on [here](https://voyager-docs.devdojo.com/getting-started/installation) and seeded the DB with dummy data.  
On my machine everything works well but when I did it on the server I got 419 HTTP response with a message of 'Page Expired'.  
The thorwn exception is an Illuminate\Session\TokenMismatchException with a message of 'CSRF token mismatch'.

I searched for this problem, here in the issues and other forums, tried to search as a Laravel related problem too. One issue from [here ](https://github.com/the-control-group/voyager/issues/113) said a fresh installation fixed it. I deleted the package, database tables and every file, that it created during the installation, but it did not work. 
I tried to delete the old sessions on the server, exclude the 'admin/*' utl path yet nothing happened, the problem still remains.

## Expected behavior
I would like to get any information that could help me out of this problem.

## Screenshots
![Jegyzet 2020-04-18 131546](https://user-images.githubusercontent.com/26221466/79636265-bd48a480-8176-11ea-8039-2e17824f8007.png)

**Comment by MrCrayon** [comment]
You didn't explain why you think this is a Voyager problem, I'm quite sure that if you create a form that sends data to a controller you'll have the same problem.
As also said in the other issue it's most probably a server configuration problem. 
Check if your `/storage/framework/sessions` contains your sessions and it's writable.

**Comment by D4nyi** [comment]
My apologies, turned out there's something wrong with the server and it's not generating any sessions.
Yet I don't know why, because write permissions are added to the folders and the configurations are the same as in development where everything works fine.

Anyways, Thank You!
