### ISSUE TITLE
Write image record to privot table?

### ISSUE THREAD

**Issue by arhitektorr** [thedevdojo/voyager#4897]
- Laravel: v. 7.0
 - Voyager: v. 1.4
 - PHP: 7.2

Hello! I have a table of posts where my posts are stored. And the pictures to the records are stored in the images table. ('id', 'news_id', 'post_image'). In Bread to posts, there is an image upload form. How to make the image of this form written to the images table when adding a record?
![888](https://user-images.githubusercontent.com/63448959/79913511-65d35e80-842c-11ea-9ff9-9f3413ef2d8e.JPG)

**Comment by MrCrayon** [comment]
As the issue template states: 
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

**Comment by arhitektorr** [comment]
@MrCrayon I do not quite understand you. Can you help in solving this problem?

**Comment by MrCrayon** [comment]
You need to join our Slack chat and ask there.
You can find the link to join in Voyager Readme.

**Comment by arhitektorr** [comment]
@MrCrayon  https://app.slack.com/?
