### ISSUE TITLE
Date and DateTime default value 

### ISSUE THREAD

**Issue by liban0148** [thedevdojo/voyager#4898]
## Version information

 - Laravel: v7.5.2
 - Voyager: v1.4.0
 - PHP: 7.2
 - Database: MySQL 5.7

## Description of problem
Like most other text formfields can we use carbon fonction like now() for the default value of date and timestamp
## Proposed solution
use carbon function to compute a default value for datetime  based formfields

**Comment by MrCrayon** [comment]
As the issue template states: 
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
