### ISSUE TITLE
Error: "array_key_exists() expects parameter 2 to be array, null given"

### ISSUE THREAD

**Issue by dubeyrohit** [thedevdojo/voyager#4915]
I'm receiving error when uploading image in media.
as error showing in image

![Screenshot](https://user-images.githubusercontent.com/21987601/80788406-a0fd2c80-8ba6-11ea-8a32-487aefa6274a.png)

**Comment by MrCrayon** [comment]
Information requested in issue template are not optional.

**Comment by dubeyrohit** [comment]
> Information requested in issue template are not optional.
@MrCrayon 

I haven not written anything new for voyager. I'm using everything of voyager.
I'm getting this error directly when trying to upload image in media.

HERE IS STORAGE SETTING IN VOYAGER.PHP FILE
```
'storage' => [
        // 'disk' => env('FILESYSTEM_DRIVER', 'public'),
        // 'disk' => 'public',
        'subfolder'=>'/public/storage/',
    ],
```
HERE IS MY DISK SETTING IN FILESYSTEMS.PHP
```
 'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```

if any one can help with it. how to fix this

**Comment by fletch3555** [comment]
As @MrCrayon said, the issue template is not optional.  This includes all version numbers

**Comment by dubeyrohit** [comment]
Then,
What do you suggest @MrCrayon 
Should i override the media controller & write my own media upload functionality.

**Comment by dubeyrohit** [comment]
The problem was in the line
$file = $request->file->storeAs($request->upload_path, $name.'.'.$extension, $this->filesystem);
in VoyagerMediaController.php -> upload().

The param $this->filesystem was null.

Solution.
Followed @gbrits, @marktopper comment in #535
I override the The VoyagerMediaController -> upload() & replace the above line

**Comment by fletch3555** [comment]
That's foolishly naive fix for this.  If you look at the constructor, you'll see that `$this->filesystem` is set to the value of the `voyager.storage.disk`, which is set to `public` by default.

So, that tells me either you didn't follow the installation instructions and don't have a Voyager config file, or you changed/deleted that specific config.

Looking at your previous comment, I can see that you commented out the disk line and added a subfolder entry... why would you do this?  What prompted you to add a config key there? It's certainly not in our docs
