### ISSUE TITLE
Uploading Images on Voyager

### ISSUE THREAD

**Issue by ruisilva981** [thedevdojo/voyager#4919]
**Version information:**
 - Laravel: v 6.18.11
 - Voyager: v 1.4.1
 - PHP: v. 7.4.3

**Description:**
I can´t upload images to my project, this happens:

![vy](https://user-images.githubusercontent.com/49878780/80961073-0bf66f80-8e02-11ea-9b6a-3f4095b9b949.JPG)

![image](https://user-images.githubusercontent.com/49878780/80961191-4fe97480-8e02-11ea-99f6-b8c6d5521965.png)

Fixing the symlink directly on voyager, creates a folder in the wrong path I think, instead of create in public_html->storage

![image](https://user-images.githubusercontent.com/49878780/80961437-e4ec6d80-8e02-11ea-8fa7-08b457e833a7.png)
![image](https://user-images.githubusercontent.com/49878780/80961487-f6ce1080-8e02-11ea-8e75-52baeffac683.png)
![image](https://user-images.githubusercontent.com/49878780/80961580-24b35500-8e03-11ea-842b-4808dc9f3722.png)
![image](https://user-images.githubusercontent.com/49878780/80961601-3268da80-8e03-11ea-9d37-8da6a4dd74d4.png)

**Comment by MrCrayon** [comment]
`public_html` is not the standard Laravel `public` folder.
Did you make appropriate adjustments?

**Comment by ruisilva981** [comment]
On localhost, everything worked fine. But when I host the project into a server, that error happened.
When I fix the symlink on voyager, that folder public_html is created into my project folder (bdcompany).
So, probably is something wrong with the system of storage.

**Comment by fletch3555** [comment]
As @MrCrayon said, this is an issue with your non-standard laravel setup, not Voyager.  You need to tell laravel how to find your "new" `public` directory

**Comment by ruisilva981** [comment]
Any recommendation to solve that?

**Comment by fletch3555** [comment]
It's well documented and easily found with a simple search.  Try something like "laravel on shared hosting"

**Comment by ruisilva981** [comment]
Solved. Thanks for the help @fletch3555 and @MrCrayon !!

**Comment by isepulveda78** [comment]
How did you solve it?
