### ISSUE TITLE
Validation on Relationships

### ISSUE THREAD

**Issue by tommiekn** [thedevdojo/voyager#4920]
## Version information
 - Laravel: v6
 - Voyager: v1.4
 - PHP: 7.4
 - Database: maria

## Description
I have a Bread with a couple of Relationships, everything works fine.
These relationships needs to be validated as required as the fields they refer are "not null", so i have added a validation to "Relationship details":

`{
    "validation": {
        "rule": "required"
    }
}`

This way if i don't select anything in the Relationship dropdown in the new/edit entry of that table, it gives error, however, if i do select something from the dropdown it doesnt remove the error. Aka i can't submit the form if i keep the validation json.

If i remove the validation json, i can submit the form with no errors and without selecting anything from the dropdowns, that cause an error laravel wise because that fields is saved as not null in the database.

Any way to figure this out?

Thanks

**Comment by MrCrayon** [comment]
You are probably setting validation in the wrong field, check this:
https://github.com/the-control-group/voyager/pull/4729/files

**Comment by tommiekn** [comment]
Thanks figured out, had to validate the field in bread and not the relationship.

Thanks!
