### ISSUE TITLE
Media Upload in Windows Environment storing path with backward slash

### ISSUE THREAD

**Issue by Engr-Rowshan** [thedevdojo/voyager#4924]
## Version information
 - Laravel: v6.2
 - Voyager: v1.4
 - PHP: 7.2.6
 - Database: MariaDB 10.1.33
- OS : Windows 10 Pro - 64 bit

## Description
When you upload any media, including settings site logo or background image in site or admin area, the path for the file is using backward slash "\" instead of forward slash "/". For this when the asset url generating from db record are creating ugly url. ex: **https://example.com/storage\settings\may2020\xyz.jpg**
instead the correct should be
**https://example.com/storage/settings/may2020/xyz.jpg**

## Steps To Reproduce
1. Use windows platform
2. Use XAMPP Virtual Host
3. Login to admin panel
4. Upload site logo into settings
5. See the source code of the image path or watch the record into phpmyadmin into the table settings

## Expected behavior
The path should be used Forward "/" into the url for every environment independently, Because browser use it as standard. 

## Screenshots
![sc](https://user-images.githubusercontent.com/8403337/81447998-74957180-919f-11ea-98a5-5ff305ae8e41.JPG)

## Additional context
Not tested in Linux environment, but with knowledge expecting that this is a Windows Env Only Issue

**Comment by emptynick** [comment]
When using the suggested way (`Voyager::image()`) it will work properly.

**Comment by fletch3555** [comment]
The stored path is a filesystem path, not a URI path, which is why it's "backwards".  As @emptynick said, use the suggested method of rendering images and it'll work just fine.
