### ISSUE TITLE
Any possible way to remove/delete admin login page? or somehow protected page?

### ISSUE THREAD

**Issue by mohamm6d** [thedevdojo/voyager#4926]
- Laravel: v7
 - Voyager: latest
 - PHP: 7.3
 - Database: MySQL 8.0

I would delete the login page under the admin route! is there any possible way? Then only admin will be available for users have access and not by trying from admin/login

**Comment by MrCrayon** [comment]
From issue template: 
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
