### ISSUE TITLE
Editable live table like in Excel in Laravel Voyager

### ISSUE THREAD

**Issue by 1001-it-solutions** [thedevdojo/voyager#4928]
Hello,

how can we create an editable live table like those from Excel?
Here is an example for bootstrap editable table: https://mdbootstrap.com/docs/jquery/tables/editable/

**Comment by emptynick** [comment]
From the issue template:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

Also, the issue template is not optional when opening issues.
