### ISSUE TITLE
Order button persist even if Order display column is set to -- None --

### ISSUE THREAD

**Issue by SneakyGerald** [thedevdojo/voyager#4930]
## Version information

 - Laravel: v7.10.3
 - Voyager: v1.4.1
 - PHP: 7.2.29
 - Database: MySQL 15.1

## Description

When I update Order display column in my bread settings and I set it to `-- None --` then Order button still shows. Seems bread does update `"order_display_column":""` and it excepts `"order_display_column":null` to not show Order button. If I change `""` to `null` in MySQL then button disappears.

## Steps To Reproduce
1. Go to any bread configuration
2. Click on Order display column selection box
3. Choose -- None -- option
4. Go to bread browse view and then Order button still shows up, if you click it error is thrown.

## Expected behavior
Order button should not be shown.

## Screenshots
Bread browse view:
![image](https://user-images.githubusercontent.com/26321350/81597773-8c027380-93c6-11ea-9bf6-8a35360bb0f9.png)

DB settings:
![image](https://user-images.githubusercontent.com/26321350/81597869-afc5b980-93c6-11ea-931c-3f79bd1237e8.png)

**Comment by MrCrayon** [comment]
You need to change `Order column` to None.

**Comment by SneakyGerald** [comment]
As far as I saw in browse view `Order column` is not the only column for the required condition:

>     @if(isset($dataType->order_column) && isset($dataType->order_display_column))
>         <a href="{{ route('voyager.'.$dataType->slug.'.order') }}" class="btn btn-primary btn-add-new">
>             <i class="voyager-list"></i> <span>{{ __('voyager::bread.order') }}</span>
>         </a>
>     @endif

Both have to be set to show the button. In my case, only 1 is set to order the query result shown in the page.

**Comment by MrCrayon** [comment]
Yes, they are both used, should work with both and actually work for me.

This is what's saved in db if I change Display Column to None:
```json
{"order_column":"title","order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}
```
I see also scope is saved as empty string in your screenshot, did you disable `ConvertEmptyStringsToNull` Middleware?

P.S.
Thanks to your report I found a way to use automatic ordering and at the same time hide the order button for manual ordering :grinning:

**Comment by SneakyGerald** [comment]
> I see also scope is saved as empty string in your screenshot, did you disable ConvertEmptyStringsToNull Middleware?

Yeap, I think thats why it is saving "", but anyway is `isset` returning true when ""? Seem so, because the button shows. Is there any way to workaround it?

> Thanks to your report I found a way to use automatic ordering and at the same time hide the order button for manual ordering 

:) I'm using it in the same way.

**Comment by MrCrayon** [comment]
> but anyway is isset returning true when ""? Seem so, because the button shows.

Empty string means variable is set as empty string.
For that check would probably be better to use `!empty` since an empty string would not be usable anyway and 0 is not a valid field name.

>  Is there any way to workaround it?

You could use ConvertEmptyStringsToNull only in that route.

**Comment by SneakyGerald** [comment]
Ok, thank you I will try it.

**Comment by emptynick** [comment]
We could just use `!empty()` instead of `isset()`
