### ISSUE TITLE
Can't update table in any BREAD

### ISSUE THREAD

**Issue by TranTheTuan** [thedevdojo/voyager#4936]
## Version information

 - Laravel: 6.10.1
 - Voyager: v1.4
 - PHP: 7.4.2
 - Database: MariaDB 10.4.11

## Description

whenever I try to edit any data in any table, it returns ErrorException explode(): Empty delimiter

## Steps To Reproduce
1. Go to /admin/users
2. Click on update on one user
3. Make some edit

## Expected behavior
Update successfully.

## Screenshots
![image](https://user-images.githubusercontent.com/25614672/81766554-9163d900-9500-11ea-8348-24228e46d7b1.png)

**Comment by MrCrayon** [comment]
Error is happening in a Middleware that is neither part of Voyager or Laravel standard installation, so I'm not sure why you think this is a Voyager bug.

**Comment by MrCrayon** [comment]
I'm closing it for now, if you can explain why this should be a Voyager bug feel free to reopen it.
Also please while opening an issue fill the whole Voyager version, currently: 1.4.0, 1.4.1 or 1.4.2
