### ISSUE TITLE
multilanguage orwhere

### ISSUE THREAD

**Issue by bilisim** [thedevdojo/voyager#4939]
## Version information

 - Laravel: v7
 - Voyager: 1.4.1
 - PHP: 7.3
 - Database: 10.1.45-MariaDB

## Description of problem

no problem in using whereTranslation('title', 'LIKE', "%{$query}%") but orwhere doesn't work for multiple languages, Can't a function like "orWhereTranslation" be written?

## Solutions

>$this->serach_text = $serach_text;
>    		$posts = Post::withTranslations('category')
>    			->whereTranslation('title', 'LIKE', "%{$serach_text}%")
>          ->orWhere(function ($query) {
>            $query->whereTranslation('body', 'LIKE', "%{$this->serach_text}%");
>          })
>    			->where(
>    				[
>    					'status' => $this->is_publish,
>    				]
>    			)->paginate($this->blog_default_pagination);

**Comment by emptynick** [comment]
You can just use `orWhere` with a closure. E.g.:
```
$x = Model::whereTranslation(...)->orWhere(function ($query) {
   $query->whereTranslation(...);
});
```

But if I understand your question you could also just pass the locals you want to search in as an array.

**Comment by bilisim** [comment]
> You can just use `orWhere` with a closure. E.g.:
> 
> ```
> $x = Model::whereTranslation(...)->orWhere(function ($query) {
>    $query->whereTranslation(...);
> });
> ```
> 
> But if I understand your question you could also just pass the locals you want to search in as an array.

thanks for your answer but unfortunately it didn't work

> $posts = Post::whereTranslation('title', 'LIKE', "%{$query}%")
>           ->orWhere(function ($query) {
>             $query->whereTranslation('body', 'LIKE', "%{$query}%");
>           })
>     			->where(
>     				[
>     					'status' => $this->is_publish,
>     				]
>     			)->paginate($this->blog_default_pagination);

error output;

> ErrorException
> Object of class Illuminate\Database\Eloquent\Builder could not be converted to string

**Comment by bilisim** [comment]
is there anyone who can help please?

**Comment by emptynick** [comment]
There are too many $querys.
But as this feature already exists I'm going to close this.
