### ISSUE TITLE
important task SQL injection in all model bread

### ISSUE THREAD

**Issue by mrgiant** [thedevdojo/voyager#4943]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database:MySQL 8.0

## Description

there is SQL injection in all model bread

## Steps To Reproduce
1- write link /admin/users
2- add parameters like that (/admin/countries?filter=contains&key=%5C&s=1)
3- it display SQLSTATE[42S22]: Column not found: 1054 Unknown column '\' in 'where clause' (SQL: select * from `countries` where `\` LIKE %1% order by `created_at` desc)

**Comment by emptynick** [comment]
You can do a lot to make Voyager fail, but as long as you can not manipulate the query to return data you are not allowed to see I don't consider this as a bug or security concern.

**Comment by mrgiant** [comment]
it's dangerous to pass the value directly to query without parameters

**Comment by mrgiant** [comment]
I like Voyage so much we here to improve not to make fail

**Comment by MrCrayon** [comment]
Appreciate any input but value is not passed directly to query, is passed to Laravel query builder that takes care of sanitization.
You can join Voyager Slack group and if you have any proof that anything can be injected please contact us there.

**Comment by mrgiant** [comment]
ok I understood but can you make at least validation that makes sure if there any problem or any value or column wrong just return null it better than return error

thank you for your great work.
