### ISSUE TITLE
Scoping relationships Belongs To Many  search Bug

### ISSUE THREAD

**Issue by mrgiant** [thedevdojo/voyager#4949]
## Version information

-  Laravel: v7.10
- Voyager: v4.1, v4.1.x-dev
- PHP: 7.3
- Database: [mysql] [5.7.19] (e.g. MySQL 8.0)

## Description

When applying Scoping relationships to Belongs To Many relationships it will work except if we search we will not get a value that we search it

## Screenshots
![scope1](https://user-images.githubusercontent.com/8033419/82688439-f38fad00-9c69-11ea-9ec7-397c474a7796.PNG)

![scope2](https://user-images.githubusercontent.com/8033419/82688454-fa1e2480-9c69-11ea-848a-0fac0435307b.PNG)

**Comment by MrCrayon** [comment]
That message means there is an error in the request. 
Please open browser developer tools in network tab and check what's the error.
If you don't have debug enabled check in your logs.

**Comment by mrgiant** [comment]
Hello MrCrayon
Yes there are errors

![error1](https://user-images.githubusercontent.com/8033419/82765819-056c7e00-9e2b-11ea-873b-8b4a59c9f8f7.PNG)

![error2](https://user-images.githubusercontent.com/8033419/82765929-0eaa1a80-9e2c-11ea-87c7-9b185f53febc.PNG)

![error3](https://user-images.githubusercontent.com/8033419/82765933-12d63800-9e2c-11ea-9d83-bef6df24ad38.PNG)

**Comment by emptynick** [comment]
Then I guess it was fixed in https://github.com/the-control-group/voyager/pull/4875

**Comment by mrgiant** [comment]
for me still not work I checked it now

**Comment by emptynick** [comment]
What did you check?

**Comment by mrgiant** [comment]
above issues, you told me it fixed

**Comment by mrgiant** [comment]
thank you its fixed now I replace Voyager Base Controller code with new Voyager Base Controller code
