### ISSUE TITLE
Failed to Migrate when use UUID as primary key User table

### ISSUE THREAD

**Issue by berviantoleo** [thedevdojo/voyager#4950]
## Version information

 - Laravel: v7.10.3
 - Voyager: v1.4.1
 - PHP: 7.2
 - Database: MySQL 8.0

## Description

Failed to Migrate when use UUID as primary key User table. I got this error:

```
 SQLSTATE[HY000]: General error: 3780 Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'user_roles_user_id_foreign
' are incompatible. (SQL: alter table `user_roles` add constraint `user_roles_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on
delete cascade)
```

## Steps To Reproduce
1. Fresh Install Laravel
2. Update migration of user to uuid (id) as primary key
3. Install Voyager
4. Do `php artisan voyager:install`

## Expected behavior
Should be compatible when different type.

**Comment by fletch3555** [comment]
If you're going to change the type of that field, you're going to have to change the type of any fields that reference it.  Just copy the migrations to your migrations directory and change the fields you need and migrate again.

We can't account for every field type you may use, so we provide a default compatible with laravel's default user ID field.  Any change from there is an exercise for the user.
