### ISSUE TITLE
Bread: A table was not found

### ISSUE THREAD

**Issue by ugurtasar** [thedevdojo/voyager#4951]
## Version information
 - Laravel: latest
 - Voyager: latest
 - PHP: 7.3.12
 - Database: mariadb 10.4.10

## Steps To Reproduce
1. Go to http://localhost/admin/database/create
**Fill like:**
Table name: 'project'
Create model for this table?: 'Yes, please'
2. Click on 'Create New Table'
3. Click on 'Add BREAD to this table'
4. Scroll down
5. Click on 'Submit'
6. Go to http://localhost/admin/project

> Table name seems 'projects' on bread, but real table name is 'project'

Screenshot:
http://prntscr.com/smihku

Extras:
When try to create 'projects' table, it success.
I want to use spesific table names without 's'
Maybe i missed some steps, i don't know.

**Comment by emptynick** [comment]
You might want to follow [eloquents naming conventions](https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions)

**Comment by ugurtasar** [comment]
Thank you.
