### ISSUE TITLE
Problem instalation in laravel 7

### ISSUE THREAD

**Issue by mikipalm** [thedevdojo/voyager#4952]
PS C:\AppServ\www\restaurantes\web> composer require tcg/voyager
Using version ^1.4 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager 1.4.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2
.4.3, 2.5.0, 2.5.1, 2.4.x-dev].
    - tcg/voyager 1.x-dev requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4
.3, 2.5.0, 2.5.1, 2.4.x-dev].
    - tcg/voyager v1.4.0 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.
3, 2.5.0, 2.5.1, 2.4.x-dev].
    - tcg/voyager v1.4.1 requires intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, 2.4.1, 2.4.2, 2.4.
3, 2.5.0, 2.5.1, 2.4.x-dev].
    - intervention/image 2.4.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your
system.
    - intervention/image 2.5.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - intervention/image 2.5.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - intervention/image 2.4.3 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - intervention/image 2.4.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - intervention/image 2.4.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - intervention/image 2.4.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your syst
em.
    - Installation request for tcg/voyager ^1.4 -> satisfiable by tcg/voyager[1.4.x-dev, 1.x-dev, v1.4.0, v1.4.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\AppServ\php7\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
PS C:\AppServ\www\restaurantes\web>

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened when the requested information are provided.

**Comment by Anyantd** [comment]
@mikipalm Same problem for me , have you found a solution ?

**Comment by emptynick** [comment]
https://laravel.com/docs/7.x#server-requirements

**Comment by Anyantd** [comment]
@emptynick @mikipalm I just uncommented this "extension=fileinfo" in php.ini and everything is working now :)

**Comment by mikipalm** [comment]
> @mikipalm Same problem for me , have you found a solution ?

Yes I upgraded localhost server.
