### ISSUE TITLE
Compass dissappear on AWS

### ISSUE THREAD

**Issue by Trillo7** [thedevdojo/voyager#4954]
## Version information

 - Laravel: v7
 - Voyager: v1.4
 - PHP: 7.3
 - Database: AWS MySQL

## Description
So on localhost I have this cool Compass setting which would be very useful for me on AWS, so I intalled voyager and deployed it on AWS and it just isn't there.
Localhost: https://i.imgur.com/K6THOcR.png
AWS: https://i.imgur.com/I1plMcE.png

## Steps To Reproduce
1. Go to 'Voyager admin'
4. See compass isn't there on aws instance

**Comment by emptynick** [comment]
Not a bug but intention. Compass is automatically disabled when env changes to production.
You can set the config option `compass_in_production` to true tho.
