### ISSUE TITLE
Media Manager Allowed types issues

### ISSUE THREAD

**Issue by mrgiant** [thedevdojo/voyager#4956]
## Version information

- Laravel: v7.10
- Voyager: v4.1, v4.1.x-dev
- PHP: 7.3
- Database: [mysql] [5.7.19] (e.g. MySQL 8.0)

## Description

we specific Allowed types in voyager.php config file but when uploading CSS file it displays "This mimetypes is not allowed"

- below our allowed_mimetypes

 'allowed_mimetypes' => [
            "image/jpeg", "image/png", "image/bmp","image/svg+xml","application/zip","application/json","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","text/html","application/vnd.ms-fontobject","font/sfnt","application/vnd.ms-fontobject","image/gif","text/x-asm","application/pdf","application/x-pointplus","text/css"
        ],

**Comment by fletch3555** [comment]
Please identify what mimetype your file is being uploaded as.  This may be something on your end, our end, or an upstream dependency.

**Comment by mrgiant** [comment]
CSS file

**Comment by fletch3555** [comment]
"CSS File" is not a mime type...

**Comment by mrgiant** [comment]
we use this text/css for css file

**Comment by fletch3555** [comment]
Is that the mimetype that Voyager is seeing when you upload?

**Comment by mrgiant** [comment]
yes

**Comment by MrCrayon** [comment]
Please add `dd($request->file->getMimeType());` here: 
https://github.com/the-control-group/voyager/blob/cbf9ceed421e6153323f659d502b5694b16c0b3b/src/Http/Controllers/VoyagerMediaController.php#L212

Try to upload and report the result.

**Comment by mrgiant** [comment]
When we upload image svg we got 

![e2](https://user-images.githubusercontent.com/8033419/83040774-b2741000-a050-11ea-8429-64a9502012f2.PNG)

when we upload css or js we got 

![e3](https://user-images.githubusercontent.com/8033419/83040849-cb7cc100-a050-11ea-880d-5be0653ef255.PNG)

and also if we upload PHP file we got "text/plain" so if we want to allow only css and js without allow PHP how we can do ?

**Comment by MrCrayon** [comment]
We use mimetype provided by your chosen Filesystem adapter, so not much we can do there.
You could allow `text/plain` and extend  VoyagerMediaController upload method to implement your custom verifications before you call `parent::upload ($request)`

**Comment by mrgiant** [comment]
Noted with thanks.
