### ISSUE TITLE
View action in 1.3 not working

### ISSUE THREAD

**Issue by ceswebmaster** [thedevdojo/voyager#4957]
- Laravel: v5.8.38
 - Voyager: v1.3 (happened in 1.2 as well and upgraded to see if changed)
 - PHP: 7.4
 - Database: MySQL
 - Server: Localhost/MAMP
 - Browser: Chrome and Firefox

## Description
None of the **View** buttons next to records in the lists open the record to view. Instead it opens a new window to **about:blank#blocked**. Tried looking in the actions.blade.php file for an indication on what but can't seem to figure it out. This is for all types (pages, posts, users, and any made with BREAD). All other actions work as expected. 

## Steps To Reproduce
1. Go to admin/pages
2. Click on View
4. See about:blank#blocked page

## Expected behavior
It should open up the record in a new page I'd imagine - I haven't seen it working yet.

**Comment by emptynick** [comment]
Never heard of this before.
Which browser are you using? Are there any messages in the browser console?

**Comment by ceswebmaster** [comment]
Using updated Chrome, checked console logs and nothing other than a couple broken image paths. I just tried Firefox and the about:blank page doesn't show but the View button does nothing. Console log in Firefox is the same. I also have the Laravel debugging toolbar at the bottom but nothing reported there. 

View path is listed as href="//"

**Comment by ceswebmaster** [comment]
Would using a port have any impact on this? It doesn't for the Edit button but perhaps there is an issue grabbing the view path because I'm in my local environment using :8000. I tried **dd($action->getRoute($dataType->name))** and it returns **'javascript;'**. Though it's unclear if that is coming from the View action or the Delete action.

**Comment by MrCrayon** [comment]
Ports shouldn't matter. 
100% is something from the code and not Voyager. 
Since you upgraded from 1.2 I guess it's an old project, did you develop it or someone else did it? 

You should do a `dd($action)` and check where is the class, it might be custom.

**Comment by ceswebmaster** [comment]
Thanks for the suggestion will check that out. I am using this:
https://github.com/gruz/multi-tenancy-voyager-tries

**Comment by ceswebmaster** [comment]
Bingo. Its using TenantViewAction which overrides the button. Commenting out that code resulted in the View action working as intended. Will look into why but this is all set, thank you for suggesting that.
