### ISSUE TITLE
can't see users 

### ISSUE THREAD

**Issue by ikramooe** [thedevdojo/voyager#4958]
So when i log into the admin account i can't see the users details 
and i can't even create a new user 
--->
## Version information
 - Laravel: v5.8.35
 - Voyager: v1.2.2
 - PHP: 7.4
 - MySQL 8.0

## Description
![Capture](https://user-images.githubusercontent.com/31781110/83330867-5993ba00-a292-11ea-9489-891458437e66.PNG)
![Capture1](https://user-images.githubusercontent.com/31781110/83330880-74662e80-a292-11ea-9710-ecfdc5c17146.PNG)

**Comment by emptynick** [comment]
That's not really enough information, so let's start with the things from the issue template like `Steps to reproduce` and so on.

**Comment by MrCrayon** [comment]
v1.2.2 was released more than one year ago, it's unlikely you just installed it so unless you had this bug for one year you need to check what has been changed to cause it.

That version is not supported so there is really no point on keeping this issue open but if you need help to find out what's wrong and make it work again you might try to ask in Voyager Slack group.
