### ISSUE TITLE
media picker  files not showing 

### ISSUE THREAD

**Issue by ikramooe** [thedevdojo/voyager#4960]
Hello , i'm posting this a an issue because it used to work fine
in general  i have a table named events with an attribute named gallery 
i created a bread for that table  and choose media picker as the type of that attribute 

on media i created folders and each folder has the name of an event 
usually i used to add files  into the folders  and have the URL in the gallery attribute 
something like this 

![image](https://user-images.githubusercontent.com/31781110/83358346-283eeb00-a373-11ea-9ac3-12f21b3f9070.png)
![Capture](https://user-images.githubusercontent.com/31781110/83358435-ce8af080-a373-11ea-8c55-cb032dd92d2b.PNG)

but now it doesn't work anymore
ANY HELP ????
--->
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.4
 - MySQL 8.0

**Comment by emptynick** [comment]
What exactly is not working?
Please, use the issue template.
It helps us better understand your problem

**Comment by ikramooe** [comment]
well  what's not working is the media picker 
i have an attribute gallery  of the type media picker 
example :  
event named photography 
i created a folder on media  named photography  and when i add files to that folder   i get the URL  in the gallery attribute of that event  
as shown in the picture above 

but currently it's not working meaning  when i add files to the folder photography  i don't get the URL's in the gallery attribute

**Comment by emptynick** [comment]
Can you post a screenshot of the media-picker with files "picked"?

**Comment by ikramooe** [comment]
![image](https://user-images.githubusercontent.com/31781110/83360634-ef0e7700-a382-11ea-8202-3a6dcf3a9efa.png)

![image](https://user-images.githubusercontent.com/31781110/83360640-fafa3900-a382-11ea-9e79-744ca03bc850.png)

![image](https://user-images.githubusercontent.com/31781110/83360645-0b121880-a383-11ea-8b7e-e331a1ce55eb.png)

the videos are shown  the three other pictures i deleted them previously  
but it used to work perfectly without any issue 
is there a way to link the folder  to the media picker attribute 

or another way to create a gallery 
because   
this 
![image](https://user-images.githubusercontent.com/31781110/83360698-76f48100-a383-11ea-9c61-318cc2298582.png)


only allows me to choose one file

**Comment by emptynick** [comment]
You are mixing some things here.
But here are some tipps:
1. You really should update to 1.3. The upgrade-path is quite easy and there were some massive changes to the media-picker
2. The media picker allows you to pick as many files as you want as long as your options are right (`min`, `max`, ...)
3. The media-picker also has an option to show your images as real images instead of URLs. See the docs
4. In the second picture of your last post there is not a single file picked. You selected it, but not picked it. Think about the media-picker as your file explorer. If you click it once, it's selected but not opened (or any other action). Double click it.

**Comment by ikramooe** [comment]
thank you for your answer 
about the media picker 
can you please take a look 
i don't know if this is the right way to do it  
i select an image by double-clicking on it  and i can only choose one 
 
![image](https://user-images.githubusercontent.com/31781110/83361044-fbe09a00-a385-11ea-9056-1717232aa033.png)

i already tried to tweak the parameters but it didn't work 

![image](https://user-images.githubusercontent.com/31781110/83361091-537f0580-a386-11ea-9413-09622f9f9e50.png)

**Comment by ikramooe** [comment]
whenever i double click on another image it just substitutes the old one

**Comment by emptynick** [comment]
Closing in favor of https://github.com/the-control-group/voyager/issues/4961
