### ISSUE TITLE
media picker select multiple files 

### ISSUE THREAD

**Issue by ikramooe** [thedevdojo/voyager#4961]
on media picker i cannot select multiple files 
i double click on a file to select it and when i try to select another it just substitutes the previous one 

## Version information
 - Laravel: v5.8.38
 - Voyager: v1.3
 - PHP: 7.4
 -MySQL 8.0

## Steps To Reproduce
- create a Bread on a table 
- add media picker attribute 
-try to add multiple files 
-you'll see that only file is allowed 

## Screenshots

![Capture](https://user-images.githubusercontent.com/31781110/83363326-fb9dca00-a398-11ea-802d-7e239e33ae56.PNG)

**Comment by emptynick** [comment]
Where did you put those options?

**Comment by ikramooe** [comment]
it's working thank you
