### ISSUE TITLE
withTrashed() not working properly on show and edit

### ISSUE THREAD

**Issue by elnur-ibr** [thedevdojo/voyager#4963]
## Version information

 - Laravel: v7.12.0
 - Voyager: v1.4.1
 - PHP: 7.2.19

## Description
Softdelete does not work properly in both methods "show" and "edit" of "TCG\Voyager\Http\Controllers\VoyagerBaseController". And interrupts adding scope to model.

```
....
// Use withTrashed() if model uses SoftDeletes and if toggle is selected
if ($model && in_array(SoftDeletes::class, class_uses_recursive($model))) {
    $model = $model->withTrashed();
}
if ($dataType->scope && $dataType->scope != '' && method_exists($model, 'scope'.ucfirst($dataType->scope))) {
    $model = $model->{$dataType->scope}();
}
...
```

`$model = $model->withTrashed();` returns instance of `"Illuminate\Database\Eloquent\Builder"` instead of Model instance. As follows `method_exists($model, 'scope'.ucfirst($dataType->scope)` returns false. It should be as follows.

```
....
// Use withTrashed() if model uses SoftDeletes and if toggle is selected
if ($model && in_array(SoftDeletes::class, class_uses_recursive($model))) {
    $model->withTrashed();
}
if ($dataType->scope && $dataType->scope != '' && method_exists($model, 'scope'.ucfirst($dataType->scope))) {
    $model->{$dataType->scope}();
}
...
```

**Comment by MrCrayon** [comment]
@elnur-ibr Thanks for reporting it, I hope my PR fixes it also in all the other methods.
