### ISSUE TITLE
Capturing photo through webcam

### ISSUE THREAD

**Issue by srigurubyo** [thedevdojo/voyager#4965]
## Version information
 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2.5
 - Database: sqlite3

## Description:
Control for capturing photo through webccam

## Additional context
I am not able to find any filed type or control to capture photo using webcam of my laptop.  Example use-case is student registration process at the school requires photo to be captured.

Any help is greatly appreciated.

**Comment by MrCrayon** [comment]
Create a custom view for image upload and then put your code there.
How to code that part is outside Voyager scope but there are plenty of tutorials online like [Taking still photos with WebRTC](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Taking_still_photos)

**Comment by srigurubyo** [comment]
Great, thanks for your guidance and help here.
