### ISSUE TITLE
Image management

### ISSUE THREAD

**Issue by Quetoin** [thedevdojo/voyager#4967]
## Version information

 - Laravel: v6.2
 - Voyager: v1.4
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
Hi everyone, I have a problem with the images path. To begin with, even the avatar is not displayed.
The file path is not right as you can see in the screenshots.
I tried to find a way to change the filepath in the config file but I could not find it anywhere.
For the avatar it's not a big problem but when I want to add a picture in a DATABASE, the file path is never right.

I'm sorry if it's not the right place to post this, or the right way, i'm quite new to all this.

Thanks in advance for your help !

Have a great day,
Quentin

[Images removed]

**Comment by emptynick** [comment]
I removed your images because you are exposing all your secrets.
You should configure your server to point to `/public` by default as described in [laravels docs](https://laravel.com/docs/7.x#configuration)

**Comment by Quetoin** [comment]
Sorry, thought I didn't show everything.
Thanks for your answer. However, it doesn't work :(
I tried a lot of different things because I'm not the only one with this problem.

I could display the avatar by pointing my server to /public.
But i still cannot display the images i uploaded via the admin panel.

I tried this : 
<?php 
      $file = (json_decode($product->image))[0]->download_link;
  ?>
 {{ Voyager::image($file) }}
Returns an error : "Trying to get property 'download_link' of non-object"

Tried this : 
<img src="{{ asset('storage/'.json_decode($product->image)[0])}}">
Returns : "Object of class stdClass could not be converted to string"

And this : 
$file = asset((json_decode($product->image)));
 {{ Voyager::image($file) }}
Returns : preg_match() expects parameter 2 to be string, array given

I'm out of options for now, i'll keep digging.
Thanks for the help !

**Comment by emptynick** [comment]
> I could display the avatar by pointing my server to /public.

Which is definitely a security problem.
Visit `your.url/.env` and you will see your .env file being exposed to the public.

**Comment by Quetoin** [comment]
@emptynick  isn't it what you told me to do ??

> You should configure your server to point to `/public` by default as described in [laravels docs](https://laravel.com/docs/7.x#configuration)

Sorry but i'm looking for the solutions for hours now and it still doesn't work :(
I guess i'll just do it differently then

**Comment by Quetoin** [comment]
I figured it out ... nothing wrong with my server or Voyager::image .. just that it was in a loop and some elements didn't have an image so I got strange errors.
Thanks for your help, helped me go forward !
