### ISSUE TITLE
Browse page: Sorting alphabets is case-sensitive

### ISSUE THREAD

**Issue by cmc0912** [thedevdojo/voyager#4968]
Tried sorting text column at browse page. Click column header, it sorts alphabets in case-sensitive manner. May I ask how to sort without case-sensitive? PS: this happens at voyager 1.4.1
e.g.(when sorted):
row 1: Alex
row 2: Boa
row 3: anson
row 4: barbie

should be:
row 1: Alex
row 2: anson
row 3: barbie
row 4: Boa

**Comment by MrCrayon** [comment]
From issue template:
> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
