### ISSUE TITLE
Selecting Image using Image Picker does not update thumbnail until clicking another image

### ISSUE THREAD

**Issue by ajduff14** [thedevdojo/voyager#4969]
## Version information
 - Laravel: v7.11.0
 - Voyager: v1.4.1
 - PHP: 7.3.13
 - Database: [MySQL 5.7.22 (e.g. MySQL 8.0)

## Description
Note that this is a UI bug, when double clicking, or clicking an image & adding selected the thumbnail appears not to update, when selecting save, functionality works as expected. The issue being that when selecting images in the image picker, the thumbnail above does not update until selecting another image, which is not expected behaviour.

## Steps To Reproduce
1. Log into admin portal
2. Assign an image picker field to a BREAD model
3. Upload multiple images.
4. Select one of the images to save
5. Click back & forth between multiple images and try to add them to thumbnail

## Expected behavior
When double clicking, or selecting an image & selecting "add all selected" using an image picker, the thumbnail above will update.

## Screenshots
Please see GIF...

![Image Picker UI Bug](https://user-images.githubusercontent.com/7086583/83743683-f79cd100-a652-11ea-84b3-796e7a14f036.gif)

**Comment by emptynick** [comment]
I can confirm that.
Interesting no one else noticed this before.
Will look into it!

**Comment by emptynick** [comment]
That was an easy one: https://github.com/the-control-group/voyager/pull/4970
