### ISSUE TITLE
Docs Site Down .

### ISSUE THREAD

**Issue by rahmatputrawiranata** [thedevdojo/voyager#4972]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

**Comment by emptynick** [comment]
We are aware of that.
Unfortunately we can't do anything about that right now.
You can see the docs here on Github as well.

**Comment by emptynick** [comment]
It's available again
