### ISSUE TITLE
Media Picker is always expanded even when setting "expanded":false

### ISSUE THREAD

**Issue by josecsm** [thedevdojo/voyager#4984]
## Version information
 - Laravel: v 7.13
 - Voyager: v1.4.1
 - PHP: 7.3.19
 - Database: MAriaDB  10.4.13

## Description
I'm setting {"expanded":false} in the attributes of any Media Picker BREAD field and when I enter the edit page, it's always expanded.

I have even modified the vendo/tcg/.../views/formfields/media_picker.blade.php and hardcoded
:expanded="false"
with no luck

## Steps To Reproduce
1. create a Media Picker field
2. add as attribute
{
   "expanded":false
}
3. Save BREAD configuration
4. Enter BREAD and edit object

## Expected behavior
The media picker should be closed. It only closes when you press the close button

**Comment by emptynick** [comment]
Interestingly `expanded` is a data-attribute, not a prop which it should be to function.
