### ISSUE TITLE
how can i create a child database automatically after filling a row from the parent table ?

### ISSUE THREAD

**Issue by GacemBekhira** [thedevdojo/voyager#4991]
## Version information

 - Laravel: v7.13.0
 - Voyager: v1.4.1
 - PHP: 7.4.0
 - Database: MAriaDB 10.4.13

## Description

i m setting a database of plane with seats
the relations ships between plane to seats : has many
the relations ships between seat to plane : belongs To

## Steps To Reproduce
1. create a BREAD for plane
2. create a BREAD for seats
3. create relation in plane ,of 'has many ' with seats
4. create relation in seats,of 'belongs to  ' with plane

## Expected behavior

i want to create 300 seats automatically once a row in plane table is created manually
also the seats codes are  predefined like form 1-300 ascendant

**Comment by fletch3555** [comment]
Per our issue template:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
