### ISSUE TITLE
Image not displaying on hasMany Relationship 

### ISSUE THREAD

**Issue by AbdulRafay** [thedevdojo/voyager#4993]
Hi,

I have created two tables, `browsers` and `tabs`.  Browsers `hasMany` tabs. I have a image field in tabs table which i want to display on browsers list view, but its showing the image path as string, 

![image](https://user-images.githubusercontent.com/614883/85908731-bfdb1080-b82f-11ea-8d81-8487d23ceed3.png)

is there any field attribute that i can set to display it as image on related bread?

**Comment by AbdulRafay** [comment]
@emptynick It would be nice if you explained why you added invalid tag and closed it.

**Comment by emptynick** [comment]
You'll find the answers in the issue template you deleted when you opened this issue

**Comment by fletch3555** [comment]
For posterity: https://raw.githubusercontent.com/the-control-group/voyager/1.4/.github/ISSUE_TEMPLATE/bug_report.md
