### ISSUE TITLE
Reading Exif data is not supported by this PHP installation.

### ISSUE THREAD

**Issue by ritechoice23** [thedevdojo/voyager#4996]
**Intervention\Image\Exception\NotSupportedException
Reading Exif data is not supported by this PHP installation.**
i always get the above error anytime i tried to upload image from the admin, i am using a local host, laravel 7, php 7.4.7.

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
Also you will find the solution by searching our issues or on Google.
