### ISSUE TITLE
Adding Icon on Bread doesn't update on Menu links

### ISSUE THREAD

**Issue by resuta566** [thedevdojo/voyager#4997]
## Version information

 - Laravel: v6.16.0
 - Voyager: v1.4.1
 - PHP: 7.3.11
 - Database: MariaDB 10.4.13-MariaDB-1:10.4.13+maria~bionic-log 

## Description

Adding Icon from an already created BREAD doesn't update automatically on the menu.

## Steps To Reproduce
1. Created BREAD don't put Icon.
2. Edit Bread then put an icon.

## Expected behavior
Automatically updated the menu icon.

Maybe this isn't a bug but a future feature?

## Screenshots
<a href="https://ibb.co/z580yRs" target="_blank"><img src="https://i.ibb.co/z580yRs/Screenshot-from-2020-07-01-16-47-40.png" alt="Screenshot-from-2020-07-01-16-47-40" border="0"></a> <a href="https://ibb.co/ykj31x3" target="_blank"><img src="https://i.ibb.co/ykj31x3/Screenshot-from-2020-07-01-16-48-15.png" alt="Screenshot-from-2020-07-01-16-48-15" border="0"></a>

**Comment by emptynick** [comment]
Not a bug but intention.
See https://github.com/the-control-group/voyager/issues/4731
