### ISSUE TITLE
there are two relations in bread the lower one work only

### ISSUE THREAD

**Issue by digitalduty** [thedevdojo/voyager#4999]
![2020-07-03_1155](https://user-images.githubusercontent.com/48782200/86434814-676eac00-bd24-11ea-9094-a92461f07f2d.png)

## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.3
 - Database:  MySQL 8.0

## Description:
A clear and concise description of what the problem is.  Please also explain why this doesn't fit into the defined issue templates

**Comment by emptynick** [comment]
Not sure how we possibly could help you with only a screenshot.

**Comment by digitalduty** [comment]
I have **stock_in** table that have relation with _isbn_ column form **book** table and with _route_ from **stock_in_route** table. In the bread of **stock_in** , the lower order position column work (ie. if isbn column is lower than route column in stock_table bread order, the route column work with dropdown. if route column is lower than isbn column in stock_table bread order, the isbb column work with dropdown.
![2](https://user-images.githubusercontent.com/48782200/86438618-f41d6800-bd2c-11ea-9729-7a2d7831ea7f.png)
![1](https://user-images.githubusercontent.com/48782200/86438623-f5e72b80-bd2c-11ea-85a5-990ebd0cff0c.png)

**Comment by digitalduty** [comment]
thank @emptynick , it is ok now.
