### ISSUE TITLE
Missing required parameters vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php

### ISSUE THREAD

**Issue by prolaxu** [thedevdojo/voyager#5000]
Missing required parameters for [Route: voyager.posts.edit] [URI: admin/posts/{id}/edit]. (View: /root/riseoncode/esasto_dataEntry/vendor/tcg/voyager/resources/views/bread/partials/actions.blade.php)
## Version information

 - Laravel: v7.18.0
 - Voyager: v1.4
 - PHP: v7.4
 - Database: MySQL 

## Description

i just add new database and create bread now it occers.

## Expected behavior
![err](https://user-images.githubusercontent.com/54370052/86448426-bd236400-bce4-11ea-9bce-5165d9dbefd2.png)

**Comment by prolaxu** [comment]
Someone  please help me out.

**Comment by emptynick** [comment]
https://voyager-docs.devdojo.com/troubleshooting/missing-required-parameter
