### ISSUE TITLE
Using Azure Active Directory

### ISSUE THREAD

**Issue by mrahmadt** [thedevdojo/voyager#5004]
Hello Team

I'm building an cooperate open source application that will use Azure AD for authentication (or Google), the users (plus Admin) must use Azure AD to authenticate (I'm using Socialite to manage the authentication).

My question is it possible with Voyager to use Socialite/Azure AD for the authentication of the admins? (I'm planning to build separate 2 Laravel projects, one for the front-end(no voyager) and second one for the admin(voyager).

**Comment by emptynick** [comment]
As the issue template states, please ask questions in our Slack group.
