### ISSUE TITLE
Missing icon and image in Admin

### ISSUE THREAD

**Issue by digitalduty** [thedevdojo/voyager#5006]
## Version information

 - Laravel: v7
 - Voyager: v1.4
 - PHP: 7.3
![2020-07-09_1200](https://user-images.githubusercontent.com/48782200/87000901-2c64f080-c1dc-11ea-81eb-aafbdb95e157.png)

 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
A clear and concise description of what the problem is.  Please also explain why this doesn't fit into the defined issue templates

**Comment by fletch3555** [comment]
The FULL issue template is not optional... please make sure to follow it.

As for your issue, it's throwing 500 errors, so check your laravel logs.

**Comment by digitalduty** [comment]
Thank @fletch3555 , I fond error in laravel logs that show cundefined function funtciton finfo_file(). I install it and it work now.
