### ISSUE TITLE
error file_put_contents()

### ISSUE THREAD

**Issue by alihan-dev** [thedevdojo/voyager#5007]
## Version information

 - Laravel: v7
 - Voyager: v1.3
 - PHP: 7.3
 - Database: MySQL 8.0

I am getting this kind of error in voyager setup and I could not find a solution. Can you help me?

![Ekran Resmi 2020-07-09 11 57 56](https://user-images.githubusercontent.com/16866994/87019572-74cfde80-c1db-11ea-9c85-032d2bd2d67b.png)

I made many attempts about this error, but I could not find a solution. You can access the stackoverflow location here.
https://stackoverflow.com/questions/62801389/laravel-voyager-setup-error-file-put-contents

**Comment by ousid** [comment]
>The problem is that the host is not supporting "exlusive locks". I had this problem with Vagrant on a Ubuntu host. Then you can fix it like described here: https://stackoverflow.com/a/35743592/2707570 If you have the problem on a remote server you need to contact the provider and ask why exclusive locks are not supported.

See [this](https://stackoverflow.com/questions/47921408/laravel-file-put-contents-exclusive-locks-are-not-supported-for-this-stream) thread on StackOverflow it may help you with your problem.

**Comment by fletch3555** [comment]
This is not a Voyager problem.  As you can see in the output you shared, it's an incompatibility between League/Flysystem (used by Voyager), and your system configuration.
