### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::total does not exist

### ISSUE THREAD

**Issue by kenzotenma016** [thedevdojo/voyager#5011]
## Version information

 - Laravel: v7.14.1
 - Voyager: v1.4
 - PHP: 7.3
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

File: browse.blade.php [ line: 268 ]
   `Illuminate\Database\Eloquent\Collection $dataTypeContent->total()`
Exception
   Method Illuminate\Database\Eloquent\Collection::total does not exist

## Steps To Reproduce
1. Enabled server-side pagination on one of the BREADS and ran into this issue.

**Comment by MrCrayon** [comment]
When you enable server side pagination VoyagerBaseController should pass to the view `$dataTypeContent` as `Illuminate\Pagination\LengthAwarePaginator ` that has total method.

Can you debug starting from here if `$getter` is set as `paginate`?
https://github.com/the-control-group/voyager/blob/af4f090adb96d043c887bbc8ddad4dd24fbbd7d0/src/Http/Controllers/VoyagerBaseController.php#L46

**Comment by kenzotenma016** [comment]
That's on me. Really sorry about that. I completely forgot that I was overriding the browse.blade.php file for this dataType and had modified `$dataTypeContent`
