### ISSUE TITLE
change color to datatable text

### ISSUE THREAD

**Issue by carlos0424** [thedevdojo/voyager#5015]
## Description of problem

hello, everyone 

How can I change the color of the text to black of the related datatable since this gray color wears out the view a lot?

I hope your help and the possible route of modification since I am new in the subject

![Captura de pantalla de 2020-07-16 19-46-21](https://user-images.githubusercontent.com/17084389/87736981-5b143580-c79f-11ea-8736-8aed5cc64dd9.jpg)

**Comment by fletch3555** [comment]
Per the issue template:
```
<!---
QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
--->
```

Also, the rest of the template is not optional.
