### ISSUE TITLE
Hi @marktopper, I never know the request got the segment method as i a newbie. I appreciate that tips. Thank you!

### ISSUE THREAD

**Issue by djes240285** [thedevdojo/voyager#5018]
Hi @marktopper, I never know the request got the segment method as i a newbie. I appreciate that tips. Thank you!

I took your approach. In general, everything would be cool. But I have one problem. I can't figure out how to solve it.
This applies to this section of code:
***********
- remove index from the resource
```
    Route::resource('books.book-pages', $namespacePrefix.'VoyagerBreadController',
    [
        'except' => 'index'
    ]);
```

- point resource index to the controller method
`Route::get('books/{book}/book-pages', 'BookPageController@index')->name('books.book-pages.index');`
***********

For saving - books/{book}/book-pages/create I have a problem.
Form action="...." leads just the same to index -  books/{book}/book-pages/
after saving leads me to - admin/book-pages/
and this is a fail and incorrect work generally.

Can you tell me  how to solve it? Thank you!!!

**Comment by emptynick** [comment]
As the issue template suggests, please ask questions in our Slack group.
