### ISSUE TITLE
Rich Text Editor Bug

### ISSUE THREAD

**Issue by mustafaabduljalil** [thedevdojo/voyager#5020]
I used rich text editor and inserted data to database successfully but the inserted data display in datatable with html tags ?!!!

**Comment by mustafaabduljalil** [comment]
I think you should reply to me not closed the issue without answer or clear my misunderstand , one of ur roles to reply to me because u r one of the Contributor of voyager !! @emptynick

**Comment by emptynick** [comment]
The issue template you deleted when creating this issue will answer why it was closed
