### ISSUE TITLE
why my image size(above 1000 width) increase after uploading in bread?

### ISSUE THREAD

**Issue by behzadnet91** [thedevdojo/voyager#5024]
## Version information

 - Laravel: v7.18.0
 - Voyager: v1.4.1

## Description

when i want to upload an image to my site(the image which is above 1000width) the size of the image increase automatically.
what should i do ?
i am looking forward to checking the answer.
thank you in advanec.

**Comment by ousid** [comment]
can you specify where the upload happens or provide a code at least?

if you want to upload an image inside the voyager admin panel you can set roles in the bread model and control them

for more info, you can check the [docs](https://voyager-docs.devdojo.com/bread/introduction-1/images)

**Comment by behzadnet91** [comment]
I upload image here with size 200KB in breadEdit Mypage( image box)
![1](https://user-images.githubusercontent.com/56478963/89121531-f3ffbc00-d4d4-11ea-98e2-c40c839b95f2.jpg)
after uploding 
**When i save image in my website the size of that image change in 110KB automatically**
![2](https://user-images.githubusercontent.com/56478963/89121571-2c06ff00-d4d5-11ea-8fdb-49b58a5ca42c.jpg)
i dont use any roles in bread.

**Comment by MrCrayon** [comment]
Currently all images are processed and saved again to fix orientation and apply modification if set in configuration.
This can cause the image saved on your server to be bigger than the one uploaded depending on compression.
There is not currently any setting to elave the image untouched but you can override the content type handler and apply your logic.

https://github.com/the-control-group/voyager/blob/1.4/src/Http/Controllers/ContentTypes/Image.php
