### ISSUE TITLE
Edit user profile shows all locales, it's better to show only supported languages in the config file

### ISSUE THREAD

**Issue by seddik** [thedevdojo/voyager#5028]
## Version information

 - Laravel: v7.21.0
 - Voyager: 1.4
 - PHP: 7.3
 - Database: mysql 5.7.31

## Description

Edit user profile shows all locales, it's better to show only supported languages in the config file.

## Steps To Reproduce
1. Go to 'Dashboard > users > edit'

## Expected behavior
Local dropdown should show only supported languages in config/voyager.php

## Screenshots

![image](https://user-images.githubusercontent.com/6674347/89074112-ac155380-d373-11ea-80c9-9c8bb668b423.png)
![image](https://user-images.githubusercontent.com/6674347/89074193-dbc45b80-d373-11ea-920a-f4b2d660442c.png)

## Additional context
-

**Comment by emptynick** [comment]
But those locales are supported.
There are corresponding language files for each language displayed in there.

You are mixing localization and multi-language here

**Comment by seddik** [comment]
Sometimes you want to limit your user to some specific languages, do you think it's a good feature, in my case I'll just override `add-edit.blade.php` in my users folder to achieve that. is it good to limit localization to some specific languages.

**Comment by MrCrayon** [comment]
Sure you can decide to limit which locales to show but I don't think that's something Voyager should do by default. 

P. S
Not much important for this issue but as a good practice when you are opening an issue please specify the actual version you have installed.

**Comment by seddik** [comment]
@emptynick I've set my version to master, my mistake, I've forgotten that the latest branch is 1.4.

**Comment by seddik** [comment]
@emptynick  can I at least create a PR for that, in config/voyager.php

` 'multilangual'=> ... user_locales => [
...
]`
