### ISSUE TITLE
Cannot create BelongsTo relation

### ISSUE THREAD

**Issue by asteinarson** [thedevdojo/voyager#5036]
## Version information
 - Laravel: v7.23.0
 - Voyager: v1.4.2
 - PHP: 7.4.3
 - Database: MySQL 8.0

## Description
I cannot create a relation of type **Belongs To**, since the dropdown for column selection remains empty.

I want to connect the new table **comment** with the existing table **user**, with the field **user_id** (on **comment**). 

## Steps To Reproduce 
1. Create a new table **comment** with fields: id INTEGER, user_id INTEGER, comment TEXT.
2. Add BREAD to it (I select **id** for order).
3. Refresh BREAD page and click the **Create a relationship** button.
Top line (of dialog) now shows: Comment | BelongsTo | Post | App\Post 
(I filled in the model field manually, but it doesn't change anything if left empty). 
4. The dropdown on the next line (_Which column from the Comment is used to reference the Post?_) is left empty.

## Expected behavior
The dropdown should show the fields of the Comment table to select from (id, user_id, comment).

## Screenshots
![VoyagerCommentRelationship](https://user-images.githubusercontent.com/8819538/89547396-fc723280-d805-11ea-8842-17203c8d5a4c.png)
![VoyagerTableComment](https://user-images.githubusercontent.com/8819538/89547603-41966480-d806-11ea-98f7-04abd3961a00.png)

Thanks for looking into this or advising ho to solve it.

**Comment by emptynick** [comment]
Sounds like a naming problem.
Please follow [laravels naming conventions](https://laravel.com/docs/7.x/eloquent#eloquent-model-conventions) and see if that helps

**Comment by asteinarson** [comment]
Yes, that was it. Thanks for quick response.
