### ISSUE TITLE
Route [voyager.pages.index] not defined.

### ISSUE THREAD

**Issue by parthavmiyani** [thedevdojo/voyager#5037]
- Laravel: v7.23.2
 - Voyager: latest
 - PHP:  7.4.8
 - Database: MySQL 

ERROR: Route [voyager.pages.index] not defined. (View: C:\Users\Parth\Desktop\Code\LARAVEL\voyager\vendor\tcg\voyager\resources\views\dimmers.blade.php)

i tried php artisan voyager:install
didn't work

thank you!!

**Comment by emptynick** [comment]
That is not really enough information to help you.
Please use the steps from the issue template.
Also latest is not a Voyager version

**Comment by parthavmiyani** [comment]
Laravel: v7.23.2
Voyager: 1.4
PHP: 7.4.8
Database: MySQL



ERROR: Route [voyager.pages.index] not defined. (View: C:\Users\Parth\Desktop\Code\LARAVEL\voyager\vendor\tcg\voyager\resources\views\dimmers.blade.php)


web.php:
Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


i tried php artisan voyager:install
didn't work

thank you!!
