### ISSUE TITLE
How add append attribute to TCG\Voyager\Translator collection?

### ISSUE THREAD

**Issue by kolyayurev** [thedevdojo/voyager#5044]
## Version information

 - Laravel: v7.20
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MariaDB 10.6

## Description of problem
I have model Product with append attribute, how i can add this attribute to TCG\Voyager\Translator collection?

**Comment by emptynick** [comment]
From the issue template:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
