### ISSUE TITLE
 change the width of the navigation panel

### ISSUE THREAD

**Issue by disney1993** [thedevdojo/voyager#5048]
- Laravel: v7.*
 - Voyager: v1.4*
 - PHP: 7.2.19
 - Database: MySQL 5.7.24
![panel](https://user-images.githubusercontent.com/26549202/90704124-453dd880-e255-11ea-8d52-47d8ae9716ef.png)

I need to know if it is possible to modify the width of the navigation panel to be able to correctly display items with a long name. 
**translated from spanish with google, sorry for the spelling. 
In advance thank you very much for the help.

**Comment by emptynick** [comment]
As the issue template suggest, please ask questions in our Slack group.
