### ISSUE TITLE
It keeps redirecting to my Laravel app instead of Voyager Dashboard

### ISSUE THREAD

**Issue by maxillarious** [thedevdojo/voyager#5050]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2.5
 - Database: [MySQL] [5.7]

## Description

After login in it redirects to my Laravel app.

## Expected behavior
It's was meant to redirect to Voyager dashboard.

**Comment by emptynick** [comment]
Did you assign permissions to your user as described in our docs?

**Comment by maxillarious** [comment]
Yes

**Comment by maxillarious** [comment]
I just fixed it.

I had a column in the users table "Usename".
i just deleted it and that was how i fixed it.

now everything is working i just need to find a way to add the "username" column back.
