### ISSUE TITLE
SQLSTATE[28000] [1045] Access denied for user 'username'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by imran300** [thedevdojo/voyager#5055]
Hello Voyagers,
I try to upload laravel Voyager to my Cpanel and I `get the error
SQLSTATE[28000] [1045] Access denied for user 'username'@'localhost' (using password: YES)

I have put the DB credentials into .env file and the credentials are correct but i do get this error. Why?

help is required if someone can help me.
Thanks.
![Capture](https://user-images.githubusercontent.com/7050400/91638624-37910b80-ea2a-11ea-887a-3a98e154b75e.JPG)

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
Also, this is not a Voyager issue.
