### ISSUE TITLE
admin:252 Uncaught ReferenceError: Vue is not defined at admin:252

### ISSUE THREAD

**Issue by maxillarious** [thedevdojo/voyager#5058]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2.5
 - Database: [MySQL] [5.7] 

## Description

I get this error when ever i deploy my laravel app and till now my menu hasn't displayed but on my local machine there is no error.

**NOTE:** I have a separate table for admins

## Screenshots
![error_one](https://user-images.githubusercontent.com/55750927/91664037-653a8b00-eae4-11ea-9a8b-45b598e09b59.png)

![error_three](https://user-images.githubusercontent.com/55750927/91663043-446f3700-eade-11ea-9b2f-0369e2f3330c.png)

**Comment by emptynick** [comment]
Would be useful to see the whole message from screenshot number 1.
But it might be a problem with one of your extensions. Try disabling them or open Voyager in incognito, clear your browser cache and try again.

**Comment by maxillarious** [comment]
I just changed the screenshot number 1.

As for the extensions i disabled all of them still i get same error and my menu has not yet displayed.

I also open Voyager in an incognito tab still the same error and my menu has not yet displayed.

I also did the browser cache path still same error and my menu has not yet displayed

**Comment by wecojo** [comment]
Please is there any way i can use Voyager without the need for media manager?

if possible i'll delete some files.

**Comment by maxillarious** [comment]
So @emptynick is there any solution available.

**Comment by maxillarious** [comment]
@emptynick i just fixed it.

The problem was not coming from Voyager, it was coming from spatie/laravel-cookie-consent.

As soon as i removed the [package(spatie/laravel-cookie-consent)](https://github.com/spatie/laravel-cookie-consent) with its config file and middleware my problem was solved.

So i think there is a problem with one of there JavaScript file that was interferring with Voyager.
