### ISSUE TITLE
How can I create Chat with user in Voyager Bread  in E-commerce

### ISSUE THREAD

**Issue by Shaykhnazar** [thedevdojo/voyager#5062]
## Version information

 - Laravel: v7.2.5
 - Voyager: v1.4.1
 - PHP: 7.3
 - Database: [MySQL] [5.6] (e.g. MySQL 8.0)

## Description of problem

I have this situation I am currently creating an e-commerce site and I need to create a question and answer opportunity with the user via admin (manager) chat. The front of the project is built in the Laravel blade and admin panel Voyager

[detailed question in StackOverflow](https://stackoverflow.com/questions/63681710/private-chat-room-with-admin-and-user-in-laravel-e-commerce)
[It is my chat room bread ](https://prnt.sc/u9etup)
I want to see when I clicked Action Messages this room in the actions column

**Comment by emptynick** [comment]
As the issue template suggest, please ask questions in Slack.
