### ISSUE TITLE
Adding autoload file in composer.json messes up Font Icons and voyager-loader image

### ISSUE THREAD

**Issue by pmavila** [thedevdojo/voyager#5066]
## Version information
 - Laravel: v7.22.4
 - Voyager: v1.4.2
 - PHP: 7.2
 - Database: Mysql 14.14

## Description
Adding autoload file in composer.json messes up Font Icons and voyager-loader image

## Steps To Reproduce
1. Add helpers file under autoload in composer.json 
`
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
       "files": [
            "app/helpers.php
       ]
    },
`
2. Successfully run `composer dump-autoload`. No errors.
3. Refresh admin page. All menu icons and voyager-loader icon not loading. Fonts could not be loaded properly.

## Expected behavior
Additional autoload files should not affect asset paths.

**Comment by MrCrayon** [comment]
I cannot think of  a reason why autoload would interfere with loading assets unless you have something in your helpers file that conflicts with Voyager helpers.

Try removing everything from your helpers file, if that does not work try with:

1. Create new Laravel project
2. Install Voyager
3. Change composer and add an empy helpers file

Can you still reproduce the problem with these steps?

**Comment by MrCrayon** [comment]
Closed for inactivity
