### ISSUE TITLE
Voyager on Cloud (AWS EB) Cant Connect to Database 

### ISSUE THREAD

**Issue by resuta566** [thedevdojo/voyager#5069]
## Version information

 - Laravel: v6.16.0
 - Voyager: v1.4
 - PHP:7.2(7.4 on AWS)
 - Database: MySql 8.10.0

## Description

The Deployment is successful but I can't access to my laravel app, then when I access laravel.log I got this error

`[2020-09-08 17:23:01] production.ERROR: No Database connection yet in VoyagerServiceProvider loadAuth()`

## Steps To Reproduce
1. Deploy Laravel to aws

Related to #4045

## Expected behavior
Voyager will connect to the DB

**Comment by emptynick** [comment]
Like I already said in Slack and the other issue, that's just a warning, not an error.
Check your logs if there are any other errors
