### ISSUE TITLE
personilize textarea

### ISSUE THREAD

**Issue by AlirezaMirghasemi** [thedevdojo/voyager#507]
- Laravel Version: #.#.#
- Voyager Version: 0.10.7

### Description:
how can i personalize textarea in bread?
i want add option to reach text
![firefox_screenshot_2017-01-08t04-07-20 138z](https://cloud.githubusercontent.com/assets/19419828/21747234/4f8e8118-d575-11e6-8ca6-fc38f3949d55.png)
area

**Comment by marktopper** [comment]
You wish to modify the rich text editor?

**Comment by AlirezaMirghasemi** [comment]
yes exactly !

**Comment by marktopper** [comment]
This should of cause be possible.

Open for pull requests, else I might look into it.

**Comment by lednhatkhanh** [comment]
Hey, I is there any way that I can install a rich text editor of my own choice? Thank you.

**Comment by fletch3555** [comment]
@lednhatkhanh, this issue has been untouched for 3 months.  Please open your own issue for that request.  This is to enable customization of the RTE that we currently use/

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please create a new issue
