### ISSUE TITLE
Request Multiple BREAD for one table

### ISSUE THREAD

**Issue by hexters** [thedevdojo/voyager#5071]
## Version information

 - Laravel: v8
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MySql 8

## Description of problem

I need create BREAD which support [Laravel Single Table Inheritance
](https://github.com/jonspalmer/single-table-inheritance)

## Proposed solution
One table can create multiple BREAD with different Model

**Comment by MrCrayon** [comment]
Duplicate of #1926
