### ISSUE TITLE
image is not shown in media when i upload one

### ISSUE THREAD

**Issue by emadalslahi** [thedevdojo/voyager#5075]
when i try to upload image using normal upload ( ex: post image ) or using media 
it is not shown after i upload it , 
althow i uploaded to disck successfully
here is .env file:
![image](https://user-images.githubusercontent.com/41680195/92768791-078a2680-f3a1-11ea-8b9e-ed0db599614c.png)
here is media :
![image](https://user-images.githubusercontent.com/41680195/92768881-1a9cf680-f3a1-11ea-9938-fb4e4d63b3ab.png)

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened once the required informations are provided.

**Comment by emadalslahi** [comment]
can i get the help i need ?!

**Comment by emptynick** [comment]
When we get the required informations from the issue template, yes.
