### ISSUE TITLE
Base table or view not found error occurred when using tables without an "s" in the name

### ISSUE THREAD

**Issue by maurin88** [thedevdojo/voyager#5077]
## Version information

 - Laravel: v8.1.0
 - Voyager: v1.4.0
 - PHP: 7.4.10
 - Database: MySQL 8.0.21

## Description

Tablenames without a "s" at the end will not work with voyager. They alway produce the error:

Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'demo.demotable**s**' doesn't exist (SQL: select * from `demotable**s**` order by `id` asc)

## Steps To Reproduce
1. Create a table without an "s" at the end of the tablename. For example: demotable. In other languages then english, names in plural often do not have an "s" at the end. 
2. Create a bread
3. Try to browse the table. 
4. Because the table has no "s" at the end of the name, an table not found error will occur.

## Expected behavior
Browse the table like other tables with an S at the end. I had no problems using voyager with a table name like "clients" for example. but the german word "mitarbeiter" fails. I know, that voyager has a multilanguage feature, but this is only a workaround to this bug.

## Additional context
Also i have encountered a problem with CamelCase notation. DemoTables will create a demo_tables which is not recognized in the BREAD. Maybe this error is related to the first problem.

**Comment by fletch3555** [comment]
Laravel naming conventions expect tables to be plural (generally, ending with an 's').  Since Voyager is built on top of Laravel, we make the same assumptions.  To fix this, you have to tell laravel what the table name should be, by adding the `$table` property to your model class.
