### ISSUE TITLE
I can't create new admin

### ISSUE THREAD

**Issue by hdliyu** [thedevdojo/voyager#5079]
after installing voyager without dummy data,i tried to create my own user with this:

php artisan voyager:admin user@email.com --create
After this command, I got this:

 Enter the admin name:
 >

  Aborted.  
I can't enter name.

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened when the required informations are provided.

**Comment by hdliyu** [comment]
> after installing voyager without dummy data,i tried to create my own user with this:
> 
> php artisan voyager:admin [user@email.com](mailto:user@email.com) --create
> After this command, I got this:
> 
> Enter the admin name:
> 
> > 
> 
> Aborted.
> I cant enter name.
> 
> can anyone help me solve it, really appreciate.

**Comment by hdliyu** [comment]
> after installing voyager without dummy data,i tried to create my own user with this:
> 
> php artisan voyager:admin [user@email.com](mailto:user@email.com) --create
> After this command, I got this:
> 
> Enter the admin name:
> 
> > 
> 
> Aborted.
> I can't enter name.
