### ISSUE TITLE
getting errors when run some artisan commands

### ISSUE THREAD

**Issue by emadalslahi** [thedevdojo/voyager#5080]
When you try to run artisan command as 
php artisan config:cache or some other related command from *compas* page of voyger tools 
it shows this error 
avatar is not there in master layout of voyger?  

![20200913_213423](https://user-images.githubusercontent.com/41680195/93070544-a9eb2800-f687-11ea-8b61-d602f51af5bf.jpg)

**Comment by emptynick** [comment]
From the issue template:

> The following information is required for bug reports.  Issues without it will be closed without response
