### ISSUE TITLE
can't add admin user into database

### ISSUE THREAD

**Issue by hdliyu** [thedevdojo/voyager#5082]
- Laravel: v7.28.1
 - Voyager: v1.4
 - PHP: 7.4.0
 - Database: MySQL 8.0

after install voyager without dummy , I run `php artisan voyager:admin your@email.com --create` throw a error:
 Enter the admin name:
 >

  Aborted.

## Screenshots
![image](https://user-images.githubusercontent.com/13653157/93151758-58967380-f72f-11ea-9f66-e8e9e739198a.png)

**Comment by MrCrayon** [comment]
This is a bug in PHP 7.4.0 on Windows so you either update to 7.4.1 or downgrade to 7.3.

There is nothing we can change in Voyager to make it work.
For more info
https://github.com/laravel/framework/issues/31859
https://bugs.php.net/bug.php?id=78883
