### ISSUE TITLE
After login To Voyager Via phone number , It Keeps redirecting to my application homepage.

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#5083]
## Version information

 - Laravel: 7.25
 - Voyager: 1.4
 - PHP: 7.4

## Expected behavior
login into voyager admin panel
.

**Comment by fletch3555** [comment]
"last version" is not a valid version.  Please be specific when opening issues.  Voyager doesn't provide a "phone number login" out of the box, so I can only assume you've changed some things, though we have no way of knowing what.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/39881649/93274568-5b42a880-f7c3-11ea-8afd-933dd7d3433c.png)
@fletch3555  sorry sir,  i have  changed it
my project doesn't support emails , only phone numbers.
so i modify this function , and it works in the beginning
but after remigrate it keeps redirect to my home application

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/39881649/93274855-04899e80-f7c4-11ea-80da-3532bfa8a134.png)
and this is my routes file

**Comment by MrCrayon** [comment]
Redirect to homepage after login means you don't have right permissions.
Check user has a role assigned with browse_admin.
