### ISSUE TITLE
Blade view for rich text field on description tag

### ISSUE THREAD

**Issue by d0minium** [thedevdojo/voyager#5085]
Laravel Version: 7.0
Voyager Version: v1.4
PHP Version: 7.4.16
cpsrvd 11.90.0.9
Database client version: libmysql - 5.6.43
PHP my admin : 4.9.5

I'm using voyager in a laravel 7 shopping app for the description of all products.

I want to output the field for the description of the product

 @section('description', {!! $item->description !!} ) 
create an syntax error, unexpected '<', expecting ')' (View

and 

for the facebook share
meta property="og:description" content="{!! $item->description !!}"

When I use {!! $item->description !!} in the body, no problem. But in the tag the output always read the p tag and all style form the description. I try html_entity_decode and htmlspecialchars_decode but still got all the html tag outputting in the html tag.

I feel there's a quick or maybe it's just not possible?

Thanks for any help I can get

**Comment by fletch3555** [comment]
Issue template is not optional.  This can be reopened once the required information is provided.

**Comment by d0minium** [comment]
???? whats the info required???

**Comment by MrCrayon** [comment]
![Schermata da 2020-09-17 08-30-59](https://user-images.githubusercontent.com/6875243/93428672-2a946900-f8c0-11ea-856d-3d7d2192cb56.png)

**Comment by d0minium** [comment]
![description1](https://user-images.githubusercontent.com/23002231/93489330-60901800-f8d5-11ea-95cd-bcbfa6694836.JPG)
![description2](https://user-images.githubusercontent.com/23002231/93489331-6128ae80-f8d5-11ea-9004-46017e7a0943.JPG)
![description3](https://user-images.githubusercontent.com/23002231/93489333-6128ae80-f8d5-11ea-883d-2c5abc299333.JPG)

**Comment by d0minium** [comment]
its ok it's now fix. Thanks

**Comment by emptynick** [comment]
Nonetheless, questions should be asked in our Slack group.

You are looking for `strip_tags()`
