### ISSUE TITLE
Automatique slugify

### ISSUE THREAD

**Issue by lamispa** [thedevdojo/voyager#5086]
Hello, while working on the post tab I found out that it's possible to automatically slugify the post title.

Is there anyway I can do that to my own tabs? 

Something like this : 

![produ](https://user-images.githubusercontent.com/71466427/93523382-e25e6080-f92a-11ea-8c21-928e340580a2.PNG)

**Comment by emptynick** [comment]
As the issue template suggests, please ask questions in our Slack group.

Also, you'll find the answer in our docs
