### ISSUE TITLE
problem with logging in to admin panel  (419 PAGE EXPIRED) 

### ISSUE THREAD

**Issue by Omar-Abdelrady** [thedevdojo/voyager#5088]
## Version information

 - Laravel: v8
 - Voyager: v*
 - PHP: 7.4
 - Database: [SQL] [version] (e.g. MySQL 8.0)

I am unable to log in. I am seeing error PAGE EXPIRED 419 
![image](https://user-images.githubusercontent.com/53657884/93688507-9c3e0400-fac6-11ea-9ed7-f6166ca1a431.png)

**Comment by fletch3555** [comment]
419 is a CSRF error, typically masking a session error.  Confirm that your session config is correct, filesystem permissions are correct, etc.  Plenty of resources online about troubleshooting these issues.  99.9% sure it's not directly related to Voyager.

**Comment by dportalesr** [comment]
Make sure you're not setting `SESSION_SECURE_COOKIE` to `true` in development (if your localhost is not served through https). Also make sure your session cookie name (`SESSION_COOKIE`) has no strange characters or spaces.

**Comment by Omar-Abdelrady** [comment]
I changed the name of the project and did not change it in .env 
Thank you for your cooperation
