### ISSUE TITLE
How to add custom option to menu

### ISSUE THREAD

**Issue by Pavel-Mukha** [thedevdojo/voyager#5090]
## Version information

 - Laravel: v7
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MySQL 5.7.28

## Description:
How to add custom option to menu item, like image url or something else?

**Comment by emptynick** [comment]
As the issue template suggests, please ask questions in our Slack group.

**Comment by Pavel-Mukha** [comment]
Where is this slack group?

**Comment by emptynick** [comment]
You can find the invitation link in our readme
