### ISSUE TITLE
Es posible hacer override sobre TCG\Voyager\Http\Controllers\ContentTypes\Image

### ISSUE THREAD

**Issue by antoniourraca** [thedevdojo/voyager#5095]
Es posible hacer override sobre TCG\Voyager\Http\Controllers\ContentTypes\Image?

Un saludo y gracias de antemano

**Comment by sarjo** [comment]
No explicas mucho que quieres hacer pero quizás con esto resuelvas tu problema
https://voyager-docs.devdojo.com/customization/adding-custom-formfields

**Comment by antoniourraca** [comment]
Hola me gustaría poder cada vez que se sube campo tipo imagen convertirlo a webp con una cwebp

**Comment by antoniourraca** [comment]
y también las miniaturas o imágenes recortadas

**Comment by MrCrayon** [comment]
Please ask questions in Voyager slack group. Github is reserved for bug reports and feature requests.
