### ISSUE TITLE
cann't install on laravel 6.18.40

### ISSUE THREAD

**Issue by yannnaingoo** [thedevdojo/voyager#5097]
## Version information

 - Laravel: v6.18.40
 - Voyager: v1.4
 - PHP: 7.2
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

  Problem 1
    - Conclusion: don't install tcg/voyager v1.4.2
    - Conclusion: don't install tcg/voyager v1.4.1
    - Conclusion: remove league/flysystem 1.1.3
    - Installation request for tcg/voyager ^1.4 -> satisfiable by tcg/voyager[v1.4.0, v1.4.1, v1.4.2].
    - Conclusion: don't install league/flysystem 1.1.3
    - tcg/voyager v1.4.0 requires league/flysystem ~1.0.41 -> satisfiable by league/flysystem[1.0.41, 1.0.42, 1.0.43, 1.0.44, 1.0.45, 1.0.46, 1.0.47, 1.0.48, 1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.0.57, 1.0.58, 1.0.59, 1.0.60, 1.0.61, 1.0.62, 1.0.63, 1.0.64, 1.0.65, 1.0.66, 1.0.67, 1.0.68, 1.0.69, 1.0.70].
    - Can only install one of: league/flysystem[1.0.41, 1.1.3].
    - Can only install one of: league/flysystem[1.0.42, 1.1.3].
    - Can only install one of: league/flysystem[1.0.43, 1.1.3].
    - Can only install one of: league/flysystem[1.0.44, 1.1.3].
    - Can only install one of: league/flysystem[1.0.45, 1.1.3].
    - Can only install one of: league/flysystem[1.0.46, 1.1.3].
    - Can only install one of: league/flysystem[1.0.47, 1.1.3].
    - Can only install one of: league/flysystem[1.0.48, 1.1.3].
    - Can only install one of: league/flysystem[1.0.49, 1.1.3].
    - Can only install one of: league/flysystem[1.0.50, 1.1.3].
    - Can only install one of: league/flysystem[1.0.51, 1.1.3].
    - Can only install one of: league/flysystem[1.0.52, 1.1.3].
    - Can only install one of: league/flysystem[1.0.53, 1.1.3].
    - Can only install one of: league/flysystem[1.0.54, 1.1.3].
    - Can only install one of: league/flysystem[1.0.55, 1.1.3].
    - Can only install one of: league/flysystem[1.0.56, 1.1.3].
    - Can only install one of: league/flysystem[1.0.57, 1.1.3].
    - Can only install one of: league/flysystem[1.0.58, 1.1.3].
    - Can only install one of: league/flysystem[1.0.59, 1.1.3].
    - Can only install one of: league/flysystem[1.0.60, 1.1.3].
    - Can only install one of: league/flysystem[1.0.61, 1.1.3].
    - Can only install one of: league/flysystem[1.0.62, 1.1.3].
    - Can only install one of: league/flysystem[1.0.63, 1.1.3].
    - Can only install one of: league/flysystem[1.0.64, 1.1.3].
    - Can only install one of: league/flysystem[1.0.65, 1.1.3].
    - Can only install one of: league/flysystem[1.0.66, 1.1.3].
    - Can only install one of: league/flysystem[1.0.67, 1.1.3].
    - Can only install one of: league/flysystem[1.0.68, 1.1.3].
    - Can only install one of: league/flysystem[1.0.69, 1.1.3].
    - Can only install one of: league/flysystem[1.0.70, 1.1.3].
    - Installation request for league/flysystem (locked at 1.1.3) -> satisfiable by league/flysystem[1.1.3].

**Comment by MrCrayon** [comment]
We cannot know what's the problem.
~Something is preventing~ Voyager v1.4.2 ~to be installed and v1.4.0~ had a fixed reference for `league/flysystem`.

If I were you I'd update PHP and try again since it will be EOL in two months anyway.

Edit
Problem is fixed in v1.4.x-dev and v1.4.3 when released

**Comment by fletch3555** [comment]
The issue is that you have a specific version of league/flysystem required (either in your composer.json or from another package), but Voyager needs a different version.  This causes contention.  If you don't have that package locked at a specific version (i.e. `1.1.3`, not `^1.1` or `1.1.*`) in your composer.json, then delete your composer.lock file and try again.

**Comment by yannnaingoo** [comment]
> We cannot know what's the problem.
> Something is preventing Voyager v1.4.2 to be installed and v1.4.0 had a fixed reference for `league/flysystem`.
> 
> If I were you I'd update PHP and try again since it will be EOL in two months anyway.

I updated php version 7.2 to 7.3 but cann't install voyager

**Comment by yannnaingoo** [comment]
> The issue is that you have a specific version of league/flysystem required (either in your composer.json or from another package), but Voyager needs a different version. This causes contention. If you don't have that package locked at a specific version (i.e. `1.1.3`, not `^1.1` or `1.1.*`) in your composer.json, then delete your composer.lock file and try again.

I tried like that but  issue is same before

**Comment by yannnaingoo** [comment]
I have been try to  install by upgrade laravel 7 but cann't install.

**Comment by samuelwei** [comment]
I can confirm this issue for laravel versions newer then 6.18.40. To me it looks like the latest stable version of voyager requires league/flysystem: ~1.0.41 (https://packagist.org/packages/tcg/voyager#v1.4.2) but the laravel 6 framework league/flysystem: ^1.1 (https://packagist.org/packages/laravel/framework#v6.20.16)

**Comment by MrCrayon** [comment]
@SamuelWei that's accurate, I thought it was fixed in `1.4.2` but it's only fixed in dev with merged https://github.com/the-control-group/voyager/pull/5068.
@yannnaingoo untill `1.4.3` is released you'll need to require `1.4.x-dev` setting `minimum-stability`dev in `composer.json`

**Comment by samuelwei** [comment]
> @SamuelWei that's accurate, I thought it was fixed in `1.4.2` but it's only fixed in dev with merged #5068.
> @yannnaingoo untill `1.4.3` is released you'll need to require `1.4.x-dev` setting `minimum-stability`dev in `composer.json`

My problem is, that I need to update laravel due to a security issue (https://github.com/advisories/GHSA-3p32-j457-pg5x and https://github.com/advisories/GHSA-x7p5-p2c9-phvg) but don't want to install an unstable version of voyager for production usage. Would it be possible to release 1.4.3 with newer dependencies (+ bugfixes) and have the new features in a 1.4.4 release?

**Comment by MrCrayon** [comment]
@SamuelWei we don't have much man power to manage that but you can fork Voyager and apply #5068 or any other fix you want, so you have total control of what to update.

I'm closing this since fix is already merged.

**Comment by samuelwei** [comment]
@MrCrayon Can't you just release a new Version with the fix, since your last Release is Jun 2020.
