### ISSUE TITLE
I cannot goto login page

### ISSUE THREAD

**Issue by thychanarith** [thedevdojo/voyager#5098]
## 1.4

 - Laravel: v7.28
 - Voyager: v1.4
 - PHP: 7.4.3
 - Database: MySQL

## Description

[Mon Sep 28 16:38:11 2020] 127.0.0.1:53700 Closing

When I create new user then I'm logout I try to login again it not got to login page it show Laravel Wellcome page

**Comment by MrCrayon** [comment]
When you create a new user make sure that it has a role assigned with `browse_admin` permission.
