### ISSUE TITLE
Single login page for different role

### ISSUE THREAD

**Issue by rinze24** [thedevdojo/voyager#510]
Since we can add different role; and provide a default landing page for every role.

**Comment by marktopper** [comment]
Please explain what you want to archive.

**Comment by rinze24** [comment]
change sample.com/admin/login to sample.com/login
and acquire what role is being authenticated
so that we can redirect them in a landing page, like sample.com/(role)

**Comment by handiwijoyo** [comment]
@rinze24 sample.com/login on most website is for non-admin login (ex: customer login). And sample.com/admin/login is specific for admin to manage website content.
