### ISSUE TITLE
Can not remove translation field

### ISSUE THREAD

**Issue by danimax82** [thedevdojo/voyager#5100]
## Version information

 - Laravel: v6
 - Voyager: v1.3.1
 - PHP: 7
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
I have a 4 text field in post with translations , default language - ru, second language - ua. 
First, I filled in all 4 fields with text and translation, everything is ok
but then we decided that there was enough text in only 2 fields
The default language is deleted and edited, and the second one can be edited, but not deleted

sorry for my english, i think you understand me
please tell me how you can solve this?

**Comment by MrCrayon** [comment]
As the issue template suggests:

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST

You can find the link to join in the readme.
