### ISSUE TITLE
Question: so the dummy Post and Page Models are useless?

### ISSUE THREAD

**Issue by sprklinginfo** [thedevdojo/voyager#5106]
Hi,
I'm testing out Voyager now to see if I can use it for my app. Installed with dummy data but I am not sure what Posts/Pages are there for. Also came across this article: [Working with Voyager on the Front-end](https://devdojo.com/tnylea/working-with-voyager-on-the-front-end). Confused why the author has to create a Post Model as we already have Post Model from the voyager. Is everything in Voyager can be only be seen by a user with 'browse_admin' permission? thx.

**Comment by MrCrayon** [comment]
From issue template

> QUESTIONS ABOUT HOW TO USE VOYAGER SHOULD BE ASKED IN SLACK FIRST
