### ISSUE TITLE
New menu added on sidebar has no href on it.

### ISSUE THREAD

**Issue by psandoval2003** [thedevdojo/voyager#5113]
## Version information

 - Laravel: v8.10.0
 - Voyager: v1.4.x-dev
 - PHP: 7.3
 - Database: MariaDB 10.4.14

## Description
New menu added on sidebar has no href on it. but json output has link url on it.

## Steps To Reproduce
1. Go to Tools, Menu Builder, add menu named admin2, add menu items with links.
2. Create a copy of vendor\tcg\voyager\resources\views\dashboard\sidebar.blade.php override to resources\views\vendor\voyager\dashboard\sidebar.blade.php
3. Edit resources\views\vendor\voyager\dashboard\sidebar.blade.php and add 1 line to show second menu admin2:
![code](https://user-images.githubusercontent.com/71888180/95989804-1e3cf680-0e01-11eb-8b22-0dd60b3d2ad9.PNG)

## Expected behavior
show a second menu. To later add a condition according to the user's role.

## Screenshots

![imagen_menus_voyager](https://user-images.githubusercontent.com/71888180/95988404-3ca1f280-0dff-11eb-9f28-f500bbf3641f.PNG)
![imagen_menus_voyager_admin2](https://user-images.githubusercontent.com/71888180/95988426-44619700-0dff-11eb-849b-7659d8dfc2d0.PNG)
Menu admin2 without href:
![imagen_menus_voyager_admin2_missing_href2](https://user-images.githubusercontent.com/71888180/95988880-e97c6f80-0dff-11eb-91bd-51429c02d0c8.PNG)
comparing menus admin and admin2 elements:
![imagen_menus_voyager_admin2_missing_href](https://user-images.githubusercontent.com/71888180/95988438-46c3f100-0dff-11eb-879b-8ae06df97e9a.PNG)

**Comment by emptynick** [comment]
The `menu` function only treats a menu to work properly with the menu when it's named `admin`.
That's why you don't get hrefs.
You are better off manipulating the return-value from `menu('admin', '_json')`.

**Comment by psandoval2003** [comment]
@emptynick Thanks you soooo muuuuch for your quickly answer, I'v been stuck 2 days and I can't make it work, Could you help me with a little guidance or steps about how can I manipulate de return-value? I'd really be very grateful!

**Comment by emptynick** [comment]
Instead of passing the menu-items directly to the menu:
`<admin-menu :items="{{ menu('admin', '_json') }}" />`
You can take the return-value from `menu(...)` and manipulate it:
```php
@php
$items = menu('admin', '_json')->filter(function ($item) {
    return $user->hasPermission('..'); // Your permission check
});
@endphp

<admin-menu :items="{{ $items }}" />
```

**Comment by psandoval2003** [comment]
@emptynick THANKSSSSS YOU VERY MUCH!!

I could not implement your solution 100% because it gave me errors that I can't understand and my intention is not to bother you, but your answer gave me an idea to do what I need. For now... my solution rather ugly, because **I'm not a developer**, but at the least it works until I learn to develop, Laravel framework and voyager.

Here is what i did:

        <div id="adminmenu"> 
            @if (Auth::user()->hasRole('user'))
            
            
            @php // Custom Menu for Role: User
        
            $items = menu('admin2', '_json');
            @endphp
            <ul class="nav navbar-nav">
            @foreach($items as $itemm)

            @php
            echo "<li class=>
            <a target='_self' href=".$itemm['url'].">
            <span class='icon ".$itemm['icon_class']."'></span> 
            <span class='title'>".$itemm['title']."</span></a>
            </li>";
            @endphp

            @endforeach
            </ul>
            @endif
            
            
            @if (Auth::user()->hasRole('admin'))
            <admin-menu :items="{{ menu('admin', '_json') }}"></admin-menu>
            
            @endif
        </div>
