### ISSUE TITLE
Platform Mssql doesn't exist

### ISSUE THREAD

**Issue by edbertsherlo** [thedevdojo/voyager#5125]
Hi I'm new to Laravel Voyager. I know there are some options for laravel with sql server. 

Here I'm getting "Platform Mssql doesn't exist" Error.

Help me How to solve this?

**Comment by fletch3555** [comment]
Issue template is not optional.  Had you followed it, you would know that questions should be asked in slack, not here.

Having said that, Voyager does not currently support Microsoft SQL Server
