### ISSUE TITLE
Voyager Installation on existing laravel website

### ISSUE THREAD

**Issue by awaisjafar1** [thedevdojo/voyager#5127]
Version information

 - Laravel: v8.0
 - Voyager: latest version
 - PHP: latest
 - Database: MySQL 8.0

Description:
I want to install voyager on my existing eCommerce website but when I add the voyager in the same database, an error is occurred and the auth tables on the website merge with the voyager tables.

**Comment by fletch3555** [comment]
"latest" is not a valid Voyager or PHP version.  Please provide the actual version you're using.

Also, you'll need to provide much more information for us to help you.  What error are you getting? Is there a stacktrace? Exactly what steps did you perform leading up to the error?  What have you tried to do to debug this?

**Comment by riyastir** [comment]
To get PHP version : php -v
To get Voyager version : Check your composer.json
