### ISSUE TITLE
RTL Admin Panel Template

### ISSUE THREAD

**Issue by sinaboromand** [thedevdojo/voyager#513]
Hi , would you please make RTL version of admin dashboard panel ?

**Comment by marktopper** [comment]
Working on it #789

**Comment by marktopper** [comment]
I am not much familiar with RTL designs, could use some help figuring out where to place what.
Could you help me on Slack?

**Comment by sinaboromand** [comment]
Hi , first tnx for your attention.

1 - sidebar place on right edge od screen
2 - text alignment and directions right to left
3 - tables columns right to left

i think laravel 5.3 boilerplate rtl version is great , but if you guys do
same job that would be aweesomeee .

Again thank you for everything .

**Comment by marktopper** [comment]
What about the login page, would the sidebar needs to be moved to the left side there?

**Comment by marktopper** [comment]
I have got some progress now, please see the pull request at #789 and come with feedback. Thanks 🎉

**Comment by sinaboromand** [comment]
@marktopper i think login page is ok , coz the sidebar is already on right 👍

**Comment by marktopper** [comment]
I have already moved it around, does that seems like a problem @sinaboromand?

**Comment by mohamedryan** [comment]
Why RTL feature not merged with Voyager 0.11.5 Master @marktopper ?

**Comment by marktopper** [comment]
It's not ready for a release yet.

**Comment by mohamedryan** [comment]
i'm sorry , but when it will be ready for a release @marktopper ? because i want to add this feature in a project .

**Comment by marktopper** [comment]
Soon I hope, however if you want to use it now you can update the `composer.json` file to use `dev-feature/rtl-support` and then run `composer update`.

If you do, please let me know any issues you found so I can fix it, you are also more than welcome to do some pull requests with fixes and optimizations for it.

**Comment by mohamedryan** [comment]
@marktopper : Thank you mark ^^, and if i found any issues i will let u know ;)

**Comment by fletch3555** [comment]
Closing as duplicate of #789.  Please use #789 for further discussion

**Comment by the94air** [comment]
Hi, @marktopper . I appreciate your hard work on the rtl version of voyager and I just want to point out that there are a cool package called [rtlcss](https://www.npmjs.com/package/rtlcss). The creator but a lot of time on it and it can handle all the hard work of converting the css to RTL. I tired it out with bootstrap 4(using webpack) and it worked perfectly. You can find every thing in rtlcss.com. Thanks.

**Comment by fletch3555** [comment]
This issue has been closed for a year now....

**Comment by the94air** [comment]
Yea, I know 😀

**Comment by the94air** [comment]
It is perfectly converted to RTL
![voyager](https://user-images.githubusercontent.com/18303390/38087382-84129128-3360-11e8-9347-c1fccce9e7e3.png)

**Comment by vahid-vahid** [comment]
@marktopper  thank you sooooooo much

**Comment by vahid-vahid** [comment]
@marktopper But I have some problems
the most important is that in RTL mode, the user drop down menu does not work

**Comment by v01061374** [comment]
![capture](https://user-images.githubusercontent.com/18301748/40587304-adcef96a-61e2-11e8-941d-bdb526d2cbbe.JPG)

Also All uploaded files are like this photo and the path is not set correctly

**Comment by fletch3555** [comment]
@v01061374, please open your own issue. This has been closed for over a year now
