### ISSUE TITLE
Changing Admin Background Image problem

### ISSUE THREAD

**Issue by AlbertSigsbert** [thedevdojo/voyager#5130]
## Version information

 - Laravel: v7.24
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MySQL 5.7.24 

## Description
Changing Admin Background Image leads to Intervention\Image\Exception\NotSupportedException
                                                                          Reading Exif data is not supported by this PHP installation

## Steps To Reproduce
1. Go to admin
2. Click on settings
3.Click on admin
4. Scroll down to Admin Background Image
5. Click choose file
6. Select an image in my case a jpg image(2.32MB)

## Expected behavior
To change the background image of admin login page.

**Comment by MrCrayon** [comment]
As the error already suggests it's something you'll have to fix in your server configuration not a Voyager issue.
https://github.com/Intervention/image/issues/658
