### ISSUE TITLE
Cant change a admin background image

### ISSUE THREAD

**Issue by AlbertSigsbert** [thedevdojo/voyager#5133]
version information
Laravel: v7.24
Voyager: v1.4
PHP: 7.3
Database: MySQL 5.7.24
Description:
Cant change a admin background image

Additional context
Admin Background Image change result to Intervention\Image\Exception\NotSupportedException
**Reading Exif data is not supported by this PHP installation.**
##Please help if it is another error causing it and how can i fix it

**Comment by fletch3555** [comment]
Still not a bug.  Please stop spamming issues when we've already responded to your others.

Duplicate of #5130 and #5132
