### ISSUE TITLE
Missing required parameters for [Route...]

### ISSUE THREAD

**Issue by AngelSani** [thedevdojo/voyager#5134]
## Version information

 - Laravel: v7.28.4
 - Voyager: v1.4.2
 - PHP: 7.2
 - Database: MySQL 14.14

## Description

This problem only happen in a specific BREAD, of a model called 'Review', I do have in the table of the database a primary unsigned auto increments key called id, I mention this because you explained this was the solution, so I don't know why is happening, this only happens in browse

## Steps To Reproduce
1. Go to the menu
2. Click on the "Reviews" segment
3. See error

## Expected behavior
Well I expected the browse view

## Screenshots

![Screen Shot 2020-10-30 at 3 41 17 PM](https://user-images.githubusercontent.com/71098336/97762955-5150dc80-1ac7-11eb-809d-98804dbc3dfe.png)

## Additional context
The same problem happens with another Model called VideoReview, wih the same especifications

**Comment by emptynick** [comment]
Voyagers routes are all prefixed with `voyager.` so this doesn't look like a Voyager route.
There is either a custom action with a wrong route or a third party plugin injecting another route.

**Comment by AngelSani** [comment]
Yes, it was a custom action that worked with an older version of voyager, I changed it and it work. Thank you so much for the help.
