### ISSUE TITLE
belongsTo relationship is not saving the value

### ISSUE THREAD

**Issue by sajjadalis** [thedevdojo/voyager#5135]
Version information
 - Laravel: v8.0
 - Voyager: v1.4
 - PHP: 7.4.4
 - Database: MySQL 5.7.19

## Description

I have 2 models. Job and Organization. Job belongsTo Organization and Organization hasMany jobs. This is the relationship.

When i create relationship inside Jobs BREAD. It works fine and i can see all organizations in Select Dropdown (while creating new job). I select one Organization and Submit the job. but it doesn't save the value inside database and organization_id is set to Null (when organization_id field is nullable). If field is not nullable. It gives this error.
`SQLSTATE[HY000]: General error: 1364 Field 'organization_id' doesn't have a default value`

Similar issue with user_id and newspaper_id. column (same relationship with Job). I can see all users and newspapers listed in Select Dropdown but they're not saving to database.
`SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value`

Job model have multiple belongsToMany relationships with other models and all of them are working fine. Only issue with belongsTo relationship.

![screenshot](https://i.imgur.com/KUlyH94.png)

![ss](https://i.imgur.com/cs1mkz2.png)

![ss](https://i.imgur.com/KZ2gw1O.png)

**Comment by MrCrayon** [comment]
First thing your organization relationship is not set  correctly, reference column should be `organization_id` not `id`.
If it's still not saving verify that `organization_id` field in BREAD settings has edit and add checked.
Since it's saving the value in that field if edit and add are not checked whatever you send will be ignored.

Let us know if that solves the problem.

**Comment by sajjadalis** [comment]
Yes. It was add and edit issue for `organization_id` field in BREAD setting. I unchecked all options for `organization_id` (and for newspaper_id and `user_id`). Thanks for the help. It looks all good.

That relationship reference was a mistake before taking screenshot. I deleted relationship after making some changes to migration table and then added it back.
