### ISSUE TITLE
repository 'https://github.com/the-control-group/voyager.git.git/' not found

### ISSUE THREAD

**Issue by maya-hamdan** [thedevdojo/voyager#5136]
## Version information

 - Laravel: v8.12
 - Voyager: v1.4
 - PHP:  7.4.5

## Description

I'm trying to download voyager in a fresh created Laravel project and it keeps showing this error 
I tried to downloading other packages to see if it is a slow internet connection problem but it downloaded just fine

## Screenshots
![image](https://user-images.githubusercontent.com/60289981/97817647-70f22b80-1ca6-11eb-8fbe-3717cf2cd39c.png)

## Additional context
```
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 2 updates, 0 removals
  - Downloading tcg/voyager (1.x-dev 5753a2c)
 0/1 [>---------------------------]   0%  - Downloading tcg/voyager (1.x-dev 5753a2c)
  - Downloading tcg/voyager (1.x-dev 5753a2c)
  - Downloading tcg/voyager (1.x-dev 5753a2c)
    Failed to download tcg/voyager from dist: OpenSSL SSL_read: Connection was reset, errno 10054
    Now trying to download from source
  - Syncing tcg/voyager (1.x-dev 5753a2c) into cache
 1/1 [============================] 100%

  [RuntimeException]
  Failed to execute git clone --mirror "https://***:***@github.com/the-control-group/voyager.git.git" "C:/Users/user/AppData/Local/Composer/vcs/https---github.com-th
  e-control-group-voyager.git/"

  Cloning into bare repository 'C:/Users/user/AppData/Local/Composer/vcs/https---github.com-the-control-group-voyager.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/the-control-group/voyager.git.git/' not found
```

**Comment by emptynick** [comment]
You'll have to provide some information from your `composer.json`.
It definitely shouldn't be `https://github.com/the-control-group/voyager.git.git/` but `https://github.com/the-control-group/voyager.git`

**Comment by maya-hamdan** [comment]
this is my composer.json what kind of info ?

![image](https://user-images.githubusercontent.com/60289981/97844505-d587a780-1cf3-11eb-8b7b-207850cad7b6.png)

**Comment by MrCrayon** [comment]
Do you have a `repositories` section?
It should be at the end of composer.json

**Comment by BassamLB** [comment]
after installing new laravel up, you should set the database in .env and run the migration before running composer require tcg/voyager.

**Comment by MrCrayon** [comment]
@BassamLB that's actually only needed before running install.

**Comment by BassamLB** [comment]
@MrCrayon well this way worked for me. I tried what you suggested but it gave errors as mentioned by @maya-hamdan, this way I was able to install voyager with no errors.

**Comment by MrCrayon** [comment]
@BassamLB your error was most probably not the same as a git error has nothing to do with database.

Anyway this reminds me that since we didn't get feedback from op I can assume he solved it in some way so I'm closing this issue.
