### ISSUE TITLE
storage driver sftp, Exception "This driver does not support retrieving URLs."

### ISSUE THREAD

**Issue by kolyayurev** [thedevdojo/voyager#5140]
## Version information

 - Laravel: v8.12.3
 - Voyager: v1.4
 - PHP: v7.4.3
 - Database: MySQL 5.7

## Description
When i use sftp storage driver, and go to admin panel i get RuntimeException "This driver does not support retrieving URLs." 

But went i test this code, all work fine and i not get Exception.
`$exists = Storage::disk('sftp')->exists('users/default.png');`

Code below, return Exception 
`$exists = Storage::disk('sftp')->url('users/default.png');`

## Steps To Reproduce
1. add to config "filesystems"
'sftp' => [
            'driver' => 'sftp',
            'host' => '192.168.11.111', // my sftp serverip
            'username' => 'username',
            'password' => 'password',
]
2. set in .env file FILESYSTEM_DRIVER=sftp
3. clear config cache
4. go to admin panel
5. get Exception

## Screenshots
![image](https://user-images.githubusercontent.com/56155627/98573911-5b918880-22c8-11eb-8d82-ff92c4433fb1.png)
![image](https://user-images.githubusercontent.com/56155627/98575518-59302e00-22ca-11eb-8e72-63bac86fcf02.png)

![image](https://user-images.githubusercontent.com/56155627/98575424-41f14080-22ca-11eb-909f-a8bb8b802f73.png)

**Comment by kolyayurev** [comment]
My question in laravel https://github.com/laravel/framework/issues/35159

**Comment by MrCrayon** [comment]
Sadly I can only give you the same answer you recevied in Laravel/framework.
You need URLs to display images and other things you save in your storage and that driver does not support it.

Not a Voyager issue and nothing we can do our side.
