### ISSUE TITLE
Can't create admin user

### ISSUE THREAD

**Issue by mervinz** [thedevdojo/voyager#5144]
## Version information

 - Laravel: v8.12
 - Voyager: v1.4
 - PHP: 7.4.3
 - Database:  MySQL 8.0.22

## Description

I have installed voyager successfully in a new project however, am unable to create admin user account.  The below error is displayed when I try to access the admin panel.

BadMethodCallException
Call to undefined method App\Models\User::hasPermission() 

## Steps To Reproduce
1. composer require tcg/voyager
2. php artisan voyager:admin your@email.com --create

## Screenshots
![illuminate](https://user-images.githubusercontent.com/10119297/99401837-b3984280-28f9-11eb-8db0-0f9daf0403c5.png)
![forwardcall](https://user-images.githubusercontent.com/10119297/99402786-c8290a80-28fa-11eb-88c5-067d67a2de15.png)

**Comment by ryancatlin** [comment]
Have you ran `php artisan voyager:install`?

**Comment by Pangroms** [comment]
Hi all, I do have the exact same issue. (First time I’m using voyager)

I did run `php artisan voyager:install --with-dummy`

When trying to create new admin account:
```
BadMethodCallException
Call to undefined method App\Models\User::setRole()
```
The user is indeed created with a role_id set up to null instead of 1 (admin). 

When trying to access the login panel :
```
BadMethodCallException
Call to undefined method App\Models\User::hasPermission()
```

My info :
Laravel 8.15
Voyager: v1.4 
PHP: 7.4.12

**Comment by mervinz** [comment]
> Have you ran `php artisan voyager:install`?

Hello @ryancatlin , Yes I have followed the installation steps. I have tried in a new project  using **laravel  breeze** for auth scaffolding and voyager works fine.
However, when I use **laravel Jetstream** this error occurs.

**Comment by MrCrayon** [comment]
> Call to undefined method App\Models\User::hasPermission()

Means Voyager has not been properly installed.

If you are installing Voyager 1.4.2 on Laravel 8, Voyager is not going to find User model and you should see this message at the end of install process:

> Unable to locate "User.php" in app or app/Models.  Did you move this file?
> You will need to update this manually.  Change "extends Authenticatable" to "extends \TCG\Voyager\Models\User" in your User model

To solve the problem you need to follow instructions or install dev branch, to be noted that Laravel 8 is still not fully supported and there are problems with seeders.

If that does not help we can reopen this issue.
