### ISSUE TITLE
How can i add buttons to filter and set content dataTable

### ISSUE THREAD

**Issue by Shaykhnazar** [thedevdojo/voyager#5149]
## Version information

 - Laravel: v8.15
 - Voyager: v1.4
 - PHP: 7.4.5
 - Database: [PostgreSql] [12.0] (e.g. MySQL 8.0)

## Description of problem

I want to add filter links like buttons above DataTable. Filter links need to generate from the Relationship field group here [Browse blade](https://prnt.sc/vpmb9q). And self Groups bread here [This bread related to Clients bread](https://prnt.sc/vpmctk).

**Comment by ousid** [comment]
Hey, @Shaykhnazar 

Have you looked at Override views, models or controllers in the voyager docs?

You can add a custom action button too.

See: [Overriding files](https://voyager-docs.devdojo.com/customization/overriding-files#using-custom-controllers) section and [Action Buttons](https://voyager-docs.devdojo.com/customization/action-buttons#action-buttons) section for more info.

**Comment by MrCrayon** [comment]
Voyager allows you to create custom views in which you can add javascript and buttons to add functionalities to DataTables.
You can find how to create such filters in DataTables documentation.
