### ISSUE TITLE
No Way to Permanently Delete a Soft Deleted Item?

### ISSUE THREAD

**Issue by awcodes** [thedevdojo/voyager#5155]
Is there no way natively to permanently delete a model that has been soft deleted?

I'm sure I'm just missing it, but I'm not seeing it. Any guidance would be appreciated.

Thank you for the awesome package.

**Comment by MrCrayon** [comment]
That's not supported by Voyager since it might defeat the purpose of having soft delete enabled.
If you need it for your use case you can add a custom action as described in Voyager docs and use `forceDelete()`.
