### ISSUE TITLE
No estan funcionando las traducciones en los campos que tienen LANG

### ISSUE THREAD

**Issue by Alex-Santos1** [thedevdojo/voyager#5159]
No están funcionando las traducciones, por ejemplo en la vista de Login

<p>{{ __('voyager::login.signin_below') }}</p>

Hay alguna manera de corregirlo?

Así mismo cual es la función del "getTranslatedAttribute"  porque no traduce o hay que hacer un cambio o configuración? por ejemplo el nombre a mostrar de las tablas $row->getTranslatedAttribute('display_name')

Saludos

**Comment by fletch3555** [comment]
Inglés, por favor
