### ISSUE TITLE
Making category's parent_id field as a dropdown, where to set the relationship method ?

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#516]
The `TCG\Voyager\Models\Category` class is located in the vendor directory, which is not advised to edit.

What is the best way to solve/accomplish this this?
btw: I've  overridden the category/browse.blade.php file to display the parent category's name.

![categories/browse.blade.php](https://cloud.githubusercontent.com/assets/8501654/21764251/c851feae-d66a-11e6-9b4b-af5878e66908.png)

**Comment by antranapp** [comment]
You can take a look at this pull request https://github.com/the-control-group/voyager/pull/496 , feel free to improve the code if you think it can be done better :)  

P.S.: since it is a open source project, you can edit all files to suit your needs :)

**Comment by hazem1taha** [comment]
Do you mean that I edit the packages' files located in the vendor directory locally? as you know, running `composer update` command will remove these changes I made.

**Comment by antranapp** [comment]
I hope the pull request will be merged soon. In the mean time, you can edit the bread for category model to use your category model in your app. Now you can make change to category model in App namespace

![screen shot 2017-01-11 at 23 11 06](https://cloud.githubusercontent.com/assets/478757/21868534/77343600-d853-11e6-8f23-604b5df8c512.png)

**Comment by hazem1taha** [comment]
Great!
Thanks @peacemoon , but when updating a category to get a null parent_id instead of a relationship, it doesn't work and the parent_id is not updated and not set as null.

I can add a category with a `null` parent_id, update it to get a parent category, but it can't be updated to get a null parent_id.

**Comment by antranapp** [comment]
pull request is merged now. If you get the code from master, category dropdown should work.

**Comment by marktopper** [comment]
Closed since it merged
