### ISSUE TITLE
Laravel Voyager doesn't allow me to create relationships between tables.

### ISSUE THREAD

**Issue by sambhavp96** [thedevdojo/voyager#5160]
I have this weird issue in Laravel voyager. And I don't know how I can properly explain it.
Basically, as an example, I have two tables, provinces and cities, with one-to-many relationships where a Province has many cities. I tried to add this relationship to the bread for the Cities table. However, it doesn't show me the columns for the Province table, which means that I cannot select the displaying or the storing columns.
![Screenshot 2020-12-11 195230](https://user-images.githubusercontent.com/40562292/101914141-fe9d3100-3beb-11eb-88d2-6618a9d8c164.png)
And although I can technically create the relationship without selecting any columns, no data from the provinces table is shown when I try to add new data to the cities table. 
![image](https://user-images.githubusercontent.com/40562292/101914963-175a1680-3bed-11eb-900b-df2302e3b026.png)

(And yes, I do have data in my provinces table)
![image](https://user-images.githubusercontent.com/40562292/101915190-60aa6600-3bed-11eb-801f-20049b92e56b.png)

Also, I only used these two tables as an example. The issue exists when I try to add relationship between other tables as well. In fact, even the default User-Role relationship seems to have the same issue. Meaning, when I try to add a new user it doesn't give me any roles to select.
![image](https://user-images.githubusercontent.com/40562292/101915438-bd0d8580-3bed-11eb-9d42-f81b1f5982c6.png)

The weirdest thing to me is that this issue only exists in production. Everything is working fine in the localhost. I am posting this here as a last resort. I tried researching this issue, but can't seem to find anything on it.

**Comment by MrCrayon** [comment]
I think there is an ajax call to get the list of options, so you might want to check your browser console and network tab.

Also please provide information requested while creating an issue

**Comment by fletch3555** [comment]
Issue template is not optional.  Please feel free to reopen after providing necessary information.

**Comment by giangtdt97** [comment]
i have the same problem and don't know how to deal with
