### ISSUE TITLE
Unespected orderBy behaviour

### ISSUE THREAD

**Issue by ilfungo** [thedevdojo/voyager#5166]
## Version information

 - Laravel: v 8.17.2
 - Voyager: v 1.4.2
 - PHP: v 7.4.10
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description
Default order by give SQLSTATE[23000]: Integrity constraint violation: 1052 when using eloquent join. 

## Steps To Reproduce
if you write in a model something like 
        return Auth::user()->hasRole('user') ? $query
                                                ->where('employees.client_id', Auth::user()->client_id)
                                                ->join('employees', 'formations.employee_id', '=', 'employees.id')
                                                : $query;
you get
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in order clause is ambiguous (SQL: select * from formations inner join employees on formations.employee_id = employees.id where employees.client_id = 111 order by created_at desc)
if I add a orderBy (in the code) or set an orderBy in a bread I get
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'created_at' in order clause is ambiguous 
(SQL: select * from `formations` inner join `employees` on `formations`.`employee_id` = employees`.`id` where `employees`.`client_id` = 111 order by `employees`.`created_at` desc, `created_at` desc)

## Expected behavior
Adding an order by in a Model should remove the original one?

**Comment by fletch3555** [comment]
Why are you adding joins in a model...? If you're going to use Eloquent, then use Eloquent.  If you want to use the QueryBuilder, then use the QueryBuilder.  Don't mix them.

Your issue has nothing to do with `orderBy`, and everything to do with the fact that you're joining a table that has a `createdBy` field to another table that has a `createdBy` field, so MySQL doesn't know how to resolve that.

Not a Voyager problem.
