### ISSUE TITLE
how to use the rtl version of voyager

### ISSUE THREAD

**Issue by farshadff** [thedevdojo/voyager#5168]
hi and thanks for this great package . i wanted to use the persian rtl of this package i saw that there are some translation files for farsi language but when i change these fields in `config/voyager.php` :
```
  'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => true,

        /*
         * Select default language
         */
        'default' => 'fa',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            'fa',
        ],
    ],
```
this makes model translatable and bread . but i want the whole admin panel to be rtl and in persian language . is it possible to have that ? and if not i am ready to translate and help with that . thanks in advance

**Comment by emptynick** [comment]
The issue template is pretty clear what to do with "How do I...?" questions.
Nonetheless, you'll find a lot answer in [our issues](https://github.com/the-control-group/voyager/issues?q=is%3Aissue+in%3Atitle+rtl+is%3Aclosed)

**Comment by farshadff** [comment]
i am sorry @emptynick  i find no ther community to ask this question . but i wanted to know if voyager has this feature or not because when i set the default local to `ar` for example and when i enter the admin panel its still ltr and there is nothing about it on the documenation sorry if my question was so basic or on wrong place .
