### ISSUE TITLE
BUG: Uploading text or some other type of file in image field

### ISSUE THREAD

**Issue by Muhammadinaam** [thedevdojo/voyager#517]
In controller.php, function insertUpdateData() (please see the code below):

Following line is being executed before validation i.e. (before this line $this->validate($request, $rules, $messages);) 
**$content = $this->getContentBasedOnType($request, $slug, $row);**

**This causes error when user tries to upload text file in place of image. 

**Solution**
Validation should come first before trying to save data.**

`public function insertUpdateData($request, $slug, $rows, $data)
    {
        $rules = [];
        $messages = [];

        foreach ($rows as $row) {
            $options = json_decode($row->details);

            if (isset($options->validation)) {
                if (isset($options->validation->rule)) {
                    

                    if( strpos(strtoupper($options->validation->rule), 'UNIQUE') !== false )
                    {
                        $options->validation->rule = str_replace('unique:'.$slug, '', $options->validation->rule);

                        $explodedRules = explode('|', $options->validation->rule);

                        $explodedRules[] = \Illuminate\Validation\Rule::unique($slug)->ignore($data->id);

                        $rules[$row->field] = $explodedRules;

                        
                    }
                    else
                        $rules[$row->field] = $options->validation->rule;

                }

                if (isset($options->validation->messages)) {
                    foreach ($options->validation->messages as $key => $msg) {
                        $messages[$row->field.'.'.$key] = $msg;
                    }
                }
            }

            $content = $this->getContentBasedOnType($request, $slug, $row);

            if (is_null($content)) {
                if (isset($data->{$row->field})) {
                    $content = $data->{$row->field};
                }
                if ($row->field == 'password') {
                    $content = $data->{$row->field};
                }
            }

            if ($row->type == 'select_multiple') {
                $data->{$row->field}()->sync($content);
            } else {
                $data->{$row->field} = $content;
            }

            //date adjustment
            if (isset($options->validation->rule))
            {
                if( strpos(strtoupper($options->validation->rule), 'DATE') !== false )
                {
                    if( $data->{$row->field} != '' )
                        $data->{$row->field} = \Carbon\Carbon::parse($data->{$row->field})->format('Y-m-d H:i:s');
                    else
                        $data->{$row->field} = null;
                }
            }
            //end date adjustment
        }

        $this->validate($request, $rules, $messages);

        $data->save();

        return $data;
    }`

**Comment by handiwijoyo** [comment]
You may want to change Input type to File instead of Image.

![image](https://cloud.githubusercontent.com/assets/4060094/21842294/a6361558-d818-11e6-92fd-655b1892fa5d.png)

It's already do the validation before saving the data.
```
$this->validate($request, $rules, $messages);
$data->save();
```

**Comment by Muhammadinaam** [comment]
No, I actually want to upload image. But If by mistake, i select a text file instead of image, then Laravel should show validation message that ** field must be an image **. But instead of doing this, Voyager shows some strange exception.

**Comment by handiwijoyo** [comment]
Put validation to your optional json on image column:
```
{
"validation": 
    {
        "rule": "required|image"
    }
}
```

**Comment by Muhammadinaam** [comment]
I think, i should explain more clearly.



**1.** I selected image field in BREAD editor.

**2.** I put following validation in JSON:

`{
"validation": 
    {
        "rule": "required|image"
    }
}`

**3.** Then to check if validation is working or not. I intentionally uploaded text file instead of image.

Please follow the above steps to see what happens.

**It raises exception** - It is a BUG.

THe bug is In function insertUpdateData() in controller.php,

This function should perform validation first and then perform other functions. But this function executes following line before performing validation:

`$content = $this->getContentBasedOnType($request, $slug, $row);`

**It raises exception** - It is a BUG.

**Comment by handiwijoyo** [comment]
I got the point, the file uploaded before the validation.

**Comment by akpotter** [comment]
Is it also doable adding file restriction when people select?
In Image or File upload function.

Such as :
\<input type="file" name="{{ $row->field }}" accept="image/gif, image/jpeg, image/png, image/bmp" \>

Thx.

**Comment by marktopper** [comment]
@akpotter, could be. We are open for pull requests.

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue following the 1.0 release, please open a new issue and we will look into it.
