### ISSUE TITLE
Default settig of allowed_mimetypes could lead to arbitrary file upload

### ISSUE THREAD

**Issue by soulfoodisgood** [thedevdojo/voyager#5174]
## Version information

 - Voyager: before 1.4

## Description

Default upload file type of media is '*',media file type are commented, which means attacker with /admin access permission(any role) can upload php shell and execute. You can try uploading this https://github.com/flozz/p0wny-shell

https://github.com/the-control-group/voyager/blob/5753a2c39fba82a8a10497efa2d38c2bb213103f/publishable/config/voyager.php#L226

## Steps To Reproduce
1. Login https://foo.bar/admin
2. Click on 'media'
3. Upload any php web shell in 'media'
4. Access the web shell with /storage/foo_path/shell.php

## Expected behavior
Default setting should be only accept media type as you commented 
  'allowed_mimetypes' => [
          'image/jpeg',
          'image/png',
          'image/gif',
          'image/bmp',
          'video/mp4',
        ],

**Comment by MrCrayon** [comment]
I agree it would be better to have a more conservative default setting.

@soulfoodisgood Would you like to open a PR?

@emptynick @fletch3555 what are your thoughts?

**Comment by fletch3555** [comment]
I'm good with restricting it.  As long as it's configurable
