### ISSUE TITLE
Undefined index: en on media picker

### ISSUE THREAD

**Issue by farshadff** [thedevdojo/voyager#5179]
- laravel 8
- voyager 1.4

#Description
just enable 2 locales on admin and create a bread with a field with `mediapicker` add some media and submit this is the error :
```
Undefined index: en
```

**Comment by fletch3555** [comment]
Looks like possibly the same issue as #3196, #3089, #3265, #1013, #3181, #3187, etc

Please provide the stacktrace from this error.  Also, 1.4 is not a valid version.  Please provide the full version (output of `composer show tcg/voyager`)

**Comment by farshadff** [comment]
versions : * 1.x-dev this is what i get as the output but in my composer its like this : 
```
        "tcg/voyager": "^1.4"
```
i just write the version from that

**Comment by MrCrayon** [comment]
Closing this since information requested was not provided.
