### ISSUE TITLE
Install of tcg/voyager failed

### ISSUE THREAD

**Issue by bilalgungor** [thedevdojo/voyager#5181]
## Version information

 - Laravel: v8
 - Voyager: v1.4
 - PHP: 8.0
 - Database: Mysql

## Description

When I run the "composer require tcg / voyager" command I get this error.

## Screenshots

![Adsız](https://user-images.githubusercontent.com/51353769/103358532-da37c480-4ac6-11eb-8694-91c549a5d908.png)

**Comment by fletch3555** [comment]
As the error states, you don't have the `git` command on your system path.

Everything else works because you're not using dev versions for those.  Composer will do a `git clone` when grabbing dev versions.
