### ISSUE TITLE
issue with command : php artisan voyager:install --with-dummy

### ISSUE THREAD

**Issue by msariyaz** [thedevdojo/voyager#5184]
## Version information

 - OS: MacOS Catalina
 - Laravel: v8.x
 - Voyager: v1.4.2
 - PHP: 8.0
 - Database: XAMPP for 8.0.0-2 (Apache + MariaDB + PHP + Perl) phpMyAdmin 5.0.4

## Description

Hello everyone,
I am facing this issue which is displayed in this image. How we can solve this problem? Thanks.

## Error Text Message
Doctrine\DBAL\Driver\PDO\Exception 

  SQLSTATE[HY000] [2002] No such file or directory

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
     14▕ final class Exception extends PDOException
     15▕ {
     16▕     public static function new(\PDOException $exception): self
     17▕     {
  ➜  18▕         return new self($exception);
     19▕     }
     20▕ }
     21▕ 

      +48 vendor frames 
  49  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

## Screenshots
<img width="857" alt="Ekran Resmi 2020-01-03 23 27 22" src="https://user-images.githubusercontent.com/5264220/103488272-5100f480-4e1c-11eb-8601-4e1b9d7e6ba0.png">

**Comment by MrCrayon** [comment]
This is a problem with your database configuration not Voyager issue.
You can try to change db host from localhost to 127.0.0.1 and restart the server.
