### ISSUE TITLE
Update the NPM packages and especially Bootstrap to V5

### ISSUE THREAD

**Issue by devhoussam** [thedevdojo/voyager#5191]
I hope **voyager** team try to update the **NPM packages** to latest version and rebuild the **UI Admin theme** based on `Bootstrap `the New version `V5`

**Comment by fletch3555** [comment]
Updating npm packages requires a significant time for testing.  If there's a specific version of a package that you need for whatever reason, we welcome pull requests.  If you're not comfortable making the change yourself, feel free to open an issue mentioning specific versions and justification for the update (i.e. you need to use another library that only supports the newer version).

Bootstrap 5 on the other hand will likely not be supported.  Voyager 2 is already well underway and is a rewrite utilizing tailwindcss
