### ISSUE TITLE
Route to home page from custom action

### ISSUE THREAD

**Issue by dmitrymaslov99** [thedevdojo/voyager#5197]
## Version information

- Laravel: v8.21.0
- Voyager: v1.4
- PHP: 7.4.11
- Database: MySQL 5.7.26

## Description:
Create your own action button: https://voyager-docs.devdojo.com/customization/action-buttons
How to translate to another page (not voyager)?
Gives an error message: https://flareapp.io/share/pPv4vn65

`    
public function getDefaultRoute()
    {
        return route('/welcome');
    }
`

**Comment by emptynick** [comment]
As the issue template suggest, please ask questions in our Slack group.
Also, `/welcome` is a URL, not a route.

**Comment by dmitrymaslov99** [comment]
Okay, I'll duplicate it. And how can I do it?
