### ISSUE TITLE
Multiple Files/Images

### ISSUE THREAD

**Issue by AlexDukachev** [thedevdojo/voyager#52]
Hi. Could you add the ability to upload multiple files and images?

**Comment by sarath-c-sandwich** [comment]
I have the same questions. how to modify the upload form with multiple images upload?

**Comment by marktopper** [comment]
It should already be possible to add multiple files add once.

**Comment by sarath-c-sandwich** [comment]
@marktopper what about storing images as an array of String? eg: image galleries.

**Comment by fletch3555** [comment]
@uchsarath, this issue has been closed for nearly a month and your question is unrelated to the original.  Please open a new issue if you still have questions/comments
