### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded in file

### ISSUE THREAD

**Issue by farshadff** [thedevdojo/voyager#5202]
i want to add coordinates to my events model so here is what i have done so far .
i have added the migration like below :  
```
    public function up()
    {
        Schema::table('events', function (Blueprint $table) {
            $table->geometry('coordinates')->nullable(); i even tried point too but yet same problem
        });
    }
```
and in the bread option i select the coordinates for that 

![image](https://user-images.githubusercontent.com/17511289/105543906-9889ea80-5d0f-11eb-862c-6f89a92919a8.png)

and added the spatial on my model : 
```
    use Spatial;
    protected $spatial = ['coordinates'];
```
and now in my controller  i retrieve the event and send it to a view  simply like below : 
```

  public function show(Event $event)
    {
        return view('events.show', compact('event));
    }
```
but when i visit the event page i get this error : 
```
Error encoding model [App\Models\Event] with ID [1] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded (View: C:\wamp64\www\pwa\resources\views\events\show.blade.php)
```

**Comment by MrCrayon** [comment]
This error is in your frontend not Voyager.
Please verify if it's working when you view your Event record in Voyager.

If that does not work you can reopen this issue reporting the error if that works you need to check how Voyager manage the data:
https://github.com/the-control-group/voyager/blob/1.4/resources/views/formfields/coordinates.blade.php

**Comment by farshadff** [comment]
@MrCrayon is there any special function to use when you want to return coordinates in your api ?? like voyager::image or some thing ?? because i think its because i want to return it in api and show it in json format . this is my api json resource :
```
   'created_at' => $this->created_at
    'publish_at' => $this->publish_at,
   'coordinates' => $this->coordinates,
```
and on admin panel yes it shows the coordiantes

**Comment by farshadff** [comment]
ok for any one facing this problem i used the below function on the model and it solved problem for me : 
```
            'coordinates' => $this->getCoordinates(),
```
