### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by dk009dk** [thedevdojo/voyager#5205]
## Version information

 - Laravel: v^8.12
 - Voyager: v^1.4.0
 - PHP: 7.4.13

## Description:
Installation  
https://github.com/the-control-group/voyager.git not found

![err](https://user-images.githubusercontent.com/60841968/106034734-44a94800-60f9-11eb-9d8d-ada61230815b.JPG)

**Comment by dk009dk** [comment]
### USING
`composer require tcg/voyager:1.4.x-dev`


![err2](https://user-images.githubusercontent.com/60841968/106035776-7d95ec80-60fa-11eb-9d73-3b8c4bbea104.JPG)

**Comment by fletch3555** [comment]
That's saying "git" was not found, not that the voyager repo was not found (especially since you're in it..)

You either need to use a released version (i.e. not `<whatever>-dev`), or install git on your system
