### ISSUE TITLE
use voyager in lumen framework ?

### ISSUE THREAD

**Issue by ehsan9ir** [thedevdojo/voyager#5207]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description:
A clear and concise description of what the problem is.  Please also explain why this doesn't fit into the defined issue templates

**Comment by fletch3555** [comment]
Template is not optional.  Also, as noted in the template, questions should be asked in our slack group.

Beyond that, no, that won't work
