### ISSUE TITLE
Tools/Database cannot be created when set voyager path to "/"

### ISSUE THREAD

**Issue by ahmadsyamim** [thedevdojo/voyager#5208]
## Version information

 - Laravel: v8.25.0
 - Voyager: 1.x-dev e9160b7
 - PHP: 7.4.11
 - Database: MySQL 5.7

## Description

When set voyager path to "/",
Tools/Database cannot be created.

## Steps To Reproduce
1. Set voyager path to "/" eg: http://myvoyager.net/
2. Set routes/web.php to 
```
//not working
Voyager::routes();

Route::group(['prefix' => 'admin'], function () {
    // Voyager::routes();
});

//working <-- if disabled this routes, will not working
Route::group(['prefix' => 'admon'], function () {
    Voyager::routes();
});
```

## Expected behavior
Database can be created 

## Additional context
-

**Comment by MrCrayon** [comment]
@ahmadsyamim when you create a database table POST action should be to `/database` not `database/create` as per your PR.
It looks to me you have some javascript error that's preventing to send POST action to the right path.

Can you check your browser console for errors?

**Comment by MrCrayon** [comment]
Closing because no feedback was provided.
