### ISSUE TITLE
Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at'

### ISSUE THREAD

**Issue by vannderr** [thedevdojo/voyager#521]
- Laravel Version: 5.3.29
- Voyager Version: 0.10.8
- PHP Version: 7.0.3
- Database Driver & Version: MySQL  5.6.25

### Description:

I kept getting this error, when trying to edit a user profile:
    Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at'

Tried lots of things.

Like changing all migration files in \vendor\tcg\voyager\publishable\database\migrations\ 
This:
  $table->timestamps();
into:
   $table->nullableTimestamps('updated_at')->useCurrent();   
   $table->nullableTimestamps('created_at')->useCurrent();

And experiments with CURRENT_TIMESTAMP...

But nothing worked.
So eventually I hacked this file:
   \vendor\tcg\voyager\src\Http\Controllers\Controller.php

I added  this:

   if ($content == '1970-01-01 00:00:00')  $content = null;

to 

`/********** TIMESTAMP TYPE **********/
  case 'timestamp':
	if ($request->isMethod('PUT')) {

		$content = gmdate('Y-m-d H:i:s', strtotime($request->input($row->field)));

		//-------------------------------------------------------------
		// $content: '1970-01-01 00:00:00' can break update queries:
		//     SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' 
		// Setting to null instead avoids this problem:
		
		if ($content == '1970-01-01 00:00:00')  $content = null;

		//-------------------------------------------------------------
	}
	break;
`
Eh voilá - no more problems. :-)

But of course this is a very ugly and primitive hack....  
If anyone has a more elegant solution, let me know?

**Comment by handiwijoyo** [comment]
Please update your users BREAD to prevent updating created_at column like so:

![image](https://cloud.githubusercontent.com/assets/4060094/21840286/3b4bd38a-d80f-11e6-83af-598016043f38.png)
