### ISSUE TITLE
Route [voyager.prdatatable.index] not defined. (View: ... vendor\tcg\voyager\resources\views\tools\bread\index.blade.php)

### ISSUE THREAD

**Issue by Bag-byte** [thedevdojo/voyager#5211]
## Version information

 - Laravel: v8.12
 - Voyager: v1.4
 - PHP: 7.3.26
 - Database: 5.0.4

## Description

Symfony\Component\Routing\Exception\RouteNotFoundException
Route [voyager.prdatatable.index] not defined. (View: C:\xampp\htdocs\test\vendor\tcg\voyager\resources\views\tools\bread\index.blade.php)

## Screenshots

![2021-02-02_11h57_44](https://user-images.githubusercontent.com/76419054/106569470-fe674500-654d-11eb-866d-1cb2bcf8c147.png)

**Comment by fletch3555** [comment]
Issue template is not optional.  Please provide more information or we cannot help you

**Comment by MrCrayon** [comment]
Closing because no feedback was provided
