### ISSUE TITLE
I can't instal Voyager

### ISSUE THREAD

**Issue by ADJAMGBA** [thedevdojo/voyager#5212]
## Version information

 - Laravel: 5.5
 - Voyager: v1.4
 - PHP: 7.0.0
 - Database: [type] [version] (e.g. MySQL 8.0)

Helo Developpers, 

Can you help me for this issuse ? i'm new in laravel and voyager. 
I know it' version probleme but i don't know how to resolve it. 

Thanks 

<img width="679" alt="Capture d’écran 2021-02-03 à 11 13 42" src="https://user-images.githubusercontent.com/69654653/106734869-d215fc00-6613-11eb-88b1-7ff613f7ed54.png">

**Comment by emptynick** [comment]
Upgrade your Laravel version.
Voyager does at least require Laravel 6.
Laravel 5.5 was released nearly 3 years ago.

I don't think there is any way for you to get Voyager to install on L5.5 except installing a really old version what I absolutely would not recommend.

**Comment by ADJAMGBA** [comment]
thanks !
