### ISSUE TITLE
Trying to get property 'name' of non-object (View: PATH\vendor\tcg\voyager\resources\views\dimmers.blade.php)

### ISSUE THREAD

**Issue by MarkusKuhfuss** [thedevdojo/voyager#5216]
## Version information

 - Laravel: v8.26.1
 - Voyager: v1.4.0
 - PHP: 7.4
 - Database: [MySql] [5] (e.g. MySQL 8.0)

## Description

After upgrading Laravel to 8 i got this error when open Voyager Dashboard after login! Then i upgraded Voyager to 1.4 but still got this error.

## Screenshots
![dimmers](https://user-images.githubusercontent.com/12268460/107050995-34196180-67cc-11eb-9c4b-0fd18e7a8aaf.jpg)

**Comment by NielsHamelink-web** [comment]
Just updated as well. I got the same error while logging into the admin.

- Laravel: v8.27.0
- Voyager: v1.4.0
- PHP: 7.4

**Comment by theriftlab** [comment]
I also had this issue and could only work around it by going into `config/voyager.php` and commenting out any widgets in `dashboard.widgets` that I wasn't using & had no data for.

**Comment by MrCrayon** [comment]
That error means you have some widget in your `voyager.php` that does not have a corresponding BREAD.

**Comment by MrCrayon** [comment]
Duplicate of #5193
