### ISSUE TITLE
Laraver Voyager encodes / to %5C

### ISSUE THREAD

**Issue by Stelikas** [thedevdojo/voyager#5229]
I connected S3 DigitalOcean Spaces with my Laravel App using Voyager as an admin panel, the upload works fine although it encodes the slash into backslash as "%5C" and i get a 404 error, although when i change manually the link from "%5C" to "/" it works fine. 
Also Voyager Media in admin panel displays the images just fine

Example link: domain.fra1.digitaloceanspaces.com/users%5CFebruary2021%5CRNGgPrQ9o2jNIuqhroFZ.png

Any possible solutions?

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened once the required informations are provided.
