### ISSUE TITLE
Get exception after creating BREAD for any table.

### ISSUE THREAD

**Issue by Flancy** [thedevdojo/voyager#5232]
## Version information

 - Laravel: v8.27.0
 - Voyager: v1.x-dev
 - PHP: 7.4.2
 - Database: MySQL 5.7.26

## Description

Within creating BREAD to the table through voyager functionality, i have got the bug - i guess it about request to plural table name, but i might be wrong.
It's pretty basic and MAIN functionality of Voyager, so i still dont know, why other developers did not report of that. Please check it out!

## Steps To Reproduce
1. Go to the section 'Create New Table', creating some table, done;
2. Then we go to the section 'Create BREAD' to create the BREAD for our created new table, looks like created, but it NOT;
3. If you wanna browse, edit/show that new BREAD, then we get an exception;
4. See error in screenshot

## Screenshots
**1-Step** ![1](https://downloader.disk.yandex.ru/preview/e8532877e97b4be6d52c5ab114d2fa57f42cfa51e3e9586eb02462240dc6ca5e/602a7bff/XmAZaBnB-ZHqzHzK55wqpkKwARnGQWfdaigGizCWqzZ0RcfVP5QsoVPEHyyrzCh3Xm8M0khVI9DbvoGsvbMIGg%3D%3D?uid=0&filename=1.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)
**2-Step** ![2](https://downloader.disk.yandex.ru/preview/a344831bf1454d550ee686023eb072e5825f8191ae6cfdfb0ce8e598686e2dfe/602a7c96/7WluoSclGfMspCrnEY86L9bMio_D4zDKkEUb3GCv8VZtDY5hLIEy-lEIZ_caqT0cdRYm-0K2vWaqXkM0zMgo5Q%3D%3D?uid=0&filename=2-3.jpg&disposition=inline&hash=&limit=0&content_type=image%2Fjpeg&owner_uid=0&tknv=v2&size=2048x2048)
**3-Step** ![3](https://downloader.disk.yandex.ru/preview/2e21b9bd9a5c9873414c4bc1e1dc73433b1958e0be3501fa757082e98ad97903/602a7cb7/7GNL59QFYSkBciwtaoHLnZlffzDVpUSRqmW3XTyqfdh8pAZwGQI1okiY0DkzQRwy6CTznPXleoPRUU1I6pvpwg%3D%3D?uid=0&filename=4.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&owner_uid=0&tknv=v2&size=2048x2048)
**4-Step** ![4](https://downloader.disk.yandex.ru/preview/4d7906e31cefa905a57654367a9e5b0eaa87d70ad548a6f9af2ec3ccd70f3392/602a7cd1/_2olxHew6BpQcmzGwM0DACnNfPQW7ECKasK60mZt5PkMTE9M6CVs5UV1Ni1nAeKF6dV41SGuIRFXiKcTZwgFag%3D%3D?uid=0&filename=5.jpg&disposition=inline&hash=&limit=0&content_type=image%2Fjpeg&owner_uid=0&tknv=v2&size=2048x2048)

**Comment by MrCrayon** [comment]
Voyager follows Laravel conventions and table names should be plural.
If you are using a singular name for a table you'll need to specify that in your model.
All of this is more about Laravel standards then Voyager.
