### ISSUE TITLE
how to add progress bar for laravel 7 voyager "edit-add.blade.php"

### ISSUE THREAD

**Issue by HadiZareZadeh** [thedevdojo/voyager#5237]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database: MariaDB 10.4.13
 - Cpanel: 90.0.12
 
## Description:
I'm trying to have a progress bar for my "edit-add.blade.php" from voyager breads. I've overridden blades as I want to. everything works fine, except the ajaxForm that I'm using for the progress bar. I've searched about it (maybe not enough), but couldn't find anything useful, nor in your docs. any suggestions?

**Comment by emptynick** [comment]
Please read and follow the issue template.

**Comment by ashkan1996** [comment]
> Please read and follow the issue template.

I'm not sure if this is a bug-report OR a feature request. plus, couldn't find anywhere to ask! I don't know what you're trying to say.

**Comment by HadiZareZadeh** [comment]
> Please read and follow the issue template.

@emptynick 
I'm not sure if this is a bug-report OR a feature request. plus, couldn't find anywhere to ask! I don't know what you're trying to say.
