### ISSUE TITLE
[Enhancement] Publish Profile and other assets

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#524]
- Laravel Version:  5.3.28
- Voyager Version: "^0.10.7"
- PHP Version: 7.0
- Database Driver & Version:  15.1 Distrib 10.1.20-MariaDB

### Description:
Allow for the publication of the profile __edit__ / __show__ views as to allow for user modifications.
E.g. At the moment, the profile shows the user picture and a banner, but nothing else. By publishing the assets, developers would be able to modified as needed, adding sections such as "about me", "address", etc.

`vendor/tcg/voyager/resources/views/profile.blade.php`

![profile](https://cloud.githubusercontent.com/assets/4654583/21814627/e5982976-d727-11e6-9f24-7df402b3670b.png)

**Comment by victorpierredev** [comment]
I've noticed the following line, which apparently doesn't do anything:
[<p>{{ Auth::user()->bio }}</p>](https://github.com/the-control-group/voyager/blob/b48e0f08799e23317f13137fad5a158cc29f43c9/resources/views/profile.blade.php)

Maybe I'm missing something?

**Comment by handiwijoyo** [comment]
You can override all of voyager views by copy the view file to your `resources/views/vendor/voyager/` which is `resources/views/vendor/voyager/profile.blade.php` in your case

**Comment by victorpierredev** [comment]
Hi @handiwijoyo , thank you for your reply! Great to know. But maybe it would make sense to allow it to be publishable along with the other resources? Just a suggestion.

Thanks again!

**Comment by handiwijoyo** [comment]
We need to make sure just override the needed file, and let us use the rest from Voyager vendor files, it will take the benefit when update the package via `composer update`. We also don't want to bloated our resources with untouched files.
