### ISSUE TITLE
the query always appears

### ISSUE THREAD

**Issue by huantransuper** [thedevdojo/voyager#5240]
## Version information

 - Laravel: v.8
 - Voyager: v^1.4
 - PHP: 7.4
 - Database:  MySQL 8.0

## Description

I see in every request when using voyager has a query "select
   *
from
   information_schema.tables
where
   table_schema = 'your-database'
   and table_name = 'data_types'
   and table_type = 'BASE TABLE' "
can you please explain more for me???

**Comment by MrCrayon** [comment]
Please read issue template

**Comment by huantransuper** [comment]
@MrCrayon I have updated
