### ISSUE TITLE
Image Size flexibility

### ISSUE THREAD

**Issue by ashandilya** [thedevdojo/voyager#5242]
## Version information

 - Laravel: v5.8.38
- Voyager: v1.2
- PHP: 7.3
 - Database: MySQL 8.0

## Description

Unable to set image flexibility as per screen size. Every time, I set dimension on an image, it does not act accordingly.

## Screenshots
![Vysor Bug](https://user-images.githubusercontent.com/30520154/108685499-3bee3b00-751a-11eb-8592-7a097a847bcc.PNG)

**Comment by MrCrayon** [comment]
I have no idea how this is related to Voyager, that looks like a frontend custom page that Voyager does not manage.

Please explain how is this a Voyager bug and we can reopen it.

P.S.
Voyager 1.2 is a really old version an update is highly recommended.
