### ISSUE TITLE
Ukrainian translation files are missing.

### ISSUE THREAD

**Issue by Oleksii-T** [thedevdojo/voyager#5247]
## Version information

 - Laravel: v7.30.4
 - Voyager: v1.x-dev e9160b7
 - PHP: 7.4
 - Database: MySQL 5.7.29

## Description

seeders.php and compass.php files are missing from Ukrainian translation.

## Steps To Reproduce
1. require tcg/voyager.
2. install voyager.
3. set the default app language as uk.
3. go to domain/admin.

## Expected behavior
Side menu and other UI elements must be in Ukrainian.

## Screenshots
![Screen Shot 2021-03-02 at 2 24 16 PM](https://user-images.githubusercontent.com/47926157/109648211-08875e00-7b63-11eb-9c1a-7ec9e2fade6b.png)

**Comment by emptynick** [comment]
Definitely not a bug.
Feel free to send in your translations as a PR
