### ISSUE TITLE
Uploading profile avatar throws invalid date format for created_at

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#525]
Laravel Version: 5.3.28
Voyager Version: "^0.10.7"
PHP Version: 7.0
Database Driver & Version: 15.1 Distrib 10.1.20-MariaDB

### Description:
```SQL
QueryException in Connection.php line 770:
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' at row 1 (SQL: update `users` set `name` = Vpakg, `created_at` = 1970-01-01 00:00:00, `updated_at` = 2017-01-10 21:58:36, `avatar` = users/January2017/juwCrMpGrVcbM9IPS5UT.png where `id` = 1)
```

### Steps To Reproduce:
+ Brand new installation. 
+ Trying to upload a profile picture previously used with another voyager instance. 
+ Throws error.

**Comment by victorpierredev** [comment]
Sorry, just noticed that it's the same issue as #521 .
I'm closing this one.

**Comment by handiwijoyo** [comment]
Please see my answer at #521
