### ISSUE TITLE
A table was not found

### ISSUE THREAD

**Issue by xtent1405** [thedevdojo/voyager#5259]
NEW TO LARAVEL
 - Laravel: v8.32.1
 - Voyager: v1.4
 - PHP: 8.0.2
 - Database: MySQL 10.4.17

## Description
Hi I'm currently a high school student who's trying out laravel admin panel for the first time, I created an Admin table, then created its bread. When I tried clicking the admin part, there's an issue stating: `Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'adminpanel.admins' doesn't exist (SQL: select * from `admins` order by `created_at` desc)`. I have no idea on how to figure it out pls help me.
## Steps To Reproduce
1. Create a new laravel app and install voyager.
2. Create a new database in voyager called "admin"
3. Create a bread
4. Then the error showed up. :/

## Expected behavior
I was expecting it to just work just like in the video, https://www.youtube.com/watch?v=CGALfsrpZb8&list=PL_UnIDIwT95NureFNedKN9_GA6UOiS2ox&index=8

**Comment by MrCrayon** [comment]
As the issue template says, if you have a question you should ask on Voyager slack channel not here.

Voyager is based on Laravel so there is were you should start when you have problems, in your case you are not following Laravel naming standards.
https://laravel.com/docs/8.x/eloquent#table-names
