### ISSUE TITLE
.datetimepicker(); is not a function

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#526]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.8
- PHP Version: 
- Database Driver & Version: MariaDB
- jQuery Version: v2.1.4

### Description: $('.datepicker').datetimepicker(); is not a function

Is it the problem of jQuery version?

**Comment by akazorg** [comment]
@uchsarath, make sure you published voyager assets.

The default folder points to: ```public/vendor/tcg/voyager/assets/js/datetimepicker/bootstrap-datetimepicker.min.css```. Check for that file, if it's not listed, publish assets and it should be ok.
Good luck.

**Comment by sarath-c-sandwich** [comment]
Thanks @akazorg  that works now.

**Comment by akazorg** [comment]
Cool @uchsarath, I'm glad for you :)
