### ISSUE TITLE
Relationship display label use the models cast attributes

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#5263]
Selecting the relationship label 'Display the' you're limited to only database columns. 

E.g  to display a users full name I manually edit the relationships json details 'label': 'full_name' in the database to make it work.
```
protected $appends = [
        'full_name'
];

public function getFullNameAttribute()
{
    return trim($this->title . ' ' . $this->firstname . ' ' . $this->lastname, ', ');
}
```

**Comment by emptynick** [comment]
That is pretty much exactly what [this feature](https://voyager-docs.devdojo.com/customization/custom-realtionship-attributes) is made for.

**Comment by howdu** [comment]
Ooops sorry I must be going blind

**Comment by howdu** [comment]
@emptynick sorry off topic but saves creating a new issue/feature request.... without modify code I couldn't see a way of validating a field using laravel [custom validation](https://laravel.com/docs/8.x/validation#custom-validation-rules).

https://voyager-docs.devdojo.com/bread/introduction#validation
