### ISSUE TITLE
Call php artisan cache:clear made sidebar menu disappear

### ISSUE THREAD

**Issue by soni-jinendra** [thedevdojo/voyager#5264]
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Steps To Reproduce
1. Go to login page after running php artisan cache:clear command in terminal
2. Login with admin user
3. See error

## Expected behavior

Sidebar has completely gone, while my intent was just to clear cache.

## Screenshots
![clear cache sidebar 2](https://user-images.githubusercontent.com/8654859/111575676-e9c8ce80-87d4-11eb-840b-714a8e7a5930.JPG)
![clear cache sidebar](https://user-images.githubusercontent.com/8654859/111575678-eaf9fb80-87d4-11eb-87fc-878d46dfddf1.JPG)

**Comment by rohankhudedev** [comment]
Please fix the `APP_URL` in `.env` file. By default `APP_URL` will be `http://localhost`. In voyager `APP_URL` must match with running port on default port 8000. Hence `APP_URL` will be `http://localhost:8000`.
