### ISSUE TITLE
Custom validation rule for a field

### ISSUE THREAD

**Issue by howdu** [thedevdojo/voyager#5265]
It would be great to have a way of setting custom [validation rules](https://laravel.com/docs/8.x/validation#custom-validation-rules) to a field without overwriting the controller.
https://voyager-docs.devdojo.com/bread/introduction#validation

E.g 
```
{
    "validation": {
        "rule": "required",
        "custom_rule": "App\Rules\DateWithinFinancialYear|App\Rules\SlugUniqueForCategory",
        "messages": {
            "required": "This :attribute field is a must."
        }
    }
}
```

**Comment by MrCrayon** [comment]
There is no need to override Controller, create a custom rule and apply it like any other rule.

**Comment by howdu** [comment]
Please could you give example because I can only make it work with default laravel validation.

E.g using a custom validation rule 
```
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\Rule;

class DateWithinFinancialYear implements Rule
{
    /**
     * Determine if the validation rule passes.
     *
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    public function passes($attribute, $value)
    {
        return false; // always fail for testing
    }

    /**
     * Get the validation error message.
     *
     * @return string
     */
    public function message()
    {
        return 'The :attribute must be ....';
    }
}
```

Update the field details:
```
{
    "validation": {
        "rule": "required|DateWithinFinancialYear",
        "messages": {
            "required": "This :attribute field is a must."
        }
    }
}
```

Throws error:
Method Illuminate\Validation\Validator::validateDateWithinFinancialYear does not exist.

**Comment by MrCrayon** [comment]
```php
// in Provider boot method

//Custom validation rule
Validator::extend('date_with_financial_year', function ($attribute, $value, $parameters, $validator) {
    //your checks
}, 'custom message');
```
```json
{
  "validation": {
    "rule": "required|date_with_financial_year",
  }
}
```

**Comment by howdu** [comment]
Awesome thanks that's exactly what I needed. It's not in the laravel 8 documentation but exists in the [older ones](https://laravel.com/docs/4.2/validation#custom-validation-rules) so might be worth adding it into the voyager documentation.
