### ISSUE TITLE
Browser show 404 page not found when create Bread

### ISSUE THREAD

**Issue by edmargomes** [thedevdojo/voyager#5267]
## Version information

 - Laravel: v8.12
 - Voyager: v1.4
 - PHP: 8
 - Database: MariaDB 10.5

## Description
When I change the name of the admin menu to another name and try to create a Bread, I get the error 404 

## Steps To Reproduce
1. Go to 'Tools/Menu Builder'
2. Edit the admin menu
3. Change the name to admin test for example
4. Click on 'Tools/Bread' and create a new Bread

## Expected behavior
The expectation was that he would return to the Breads listing page with the Bread created 

## Screenshots
![BreadErrorSave](https://user-images.githubusercontent.com/6574942/111826059-fe858f00-88c6-11eb-9904-3990f35254c6.gif)

## Additional context
My suggestion is that there is a field in the bread creation to choose which menu we want to insert the bread in

**Comment by emptynick** [comment]
The admin menu is tightly coupled into Voyager and hardcoded in some places and should never be renamed.
There's no reason to do that.

**Comment by edmargomes** [comment]
But it is allowed to edit in the interface.

So you should block editing his name, the edit button had to be disabled or editing his name disabled.

**Comment by emptynick** [comment]
There are reasons to rename the menu (temporary to switch with another name). Also you are able to completely break everything from compass - but we don't restrict that.
But I guess we would be open for a PR showing a warning when the menu is `admin`
