### ISSUE TITLE
Error 500 when order BREAD

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#5268]
## Version information
 - Laravel: v8.1.2
 - Voyager: v1.4.2
 - PHP: 7.4.14
 - Database: MySQL 5.7

## Description
In a simple model (without relationship), I encounter an 500 error when I want to order the items
ERROR : Unknown column 'parent_id' in 'field list'
The Model don't have a parent_id field

## Screenshots
See error after reordering
![capt-ecran 2021-03-20 à 17 03 10](https://user-images.githubusercontent.com/16390911/111876710-462c1980-89a0-11eb-85e3-ba4e6797126e.jpg)

**Comment by cotiga** [comment]
I added the "parent_id" field in the DB and it's OK
Why we can add the ORDER function when this field doesnt exist and it is necessary?

**Comment by emptynick** [comment]
This is the only place where any data is set when ordering (and there is no hardcoded `parent_id`):
https://github.com/the-control-group/voyager/blob/1.4/src/Http/Controllers/VoyagerBaseController.php#L854

Any chance you can post the whole stacktrace? You might find more information in the network tab of your browser.

**Comment by cotiga** [comment]
Thank you Emptynick
I delved deeper and realized that the controller was using the updateOrder syntax while it must be update_order, also in the Router.
I use an up-to-date Fork, I need to control it all
Sorry for the inconvenience
