### ISSUE TITLE
admin/menus/2/order  response 500 error

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#527]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.8
- PHP Version: 
- Database Driver & Version: MariaDB

### Description:
Failed to load resource: the server responded with a status of 500 (Internal Server Error) on admin/menus/2/order  when I tried to reorder the menu builder.

I tried to move the location of Menu Item in admin dashboard. Then it could not save the new order to db because my Ajax post method could not access route: admin/menus/2/order

![screenshot 284](https://cloud.githubusercontent.com/assets/1330852/21840984/e7baa36e-d812-11e6-8b83-49efff63fa23.png)

**Comment by handiwijoyo** [comment]
@uchsarath Can you provide more details of the error?

**Comment by sarath-c-sandwich** [comment]
Hi @handiwijoyo something also going wrong in Media, I am not really sure whether that caused from Middle Access Token or what.

![screenshot 285](https://cloud.githubusercontent.com/assets/1330852/21841125/77a93ef4-d813-11e6-84b1-6a7c89699ba3.png)

**Comment by handiwijoyo** [comment]
It's hard to tell if you just show us 500 error. Could you find what file that causing the error? You can check the log file `storage/logs/laravel.log`

**Comment by fletch3555** [comment]
Closing as inactive.
