### ISSUE TITLE
Trying to get property 'body' of non-object

### ISSUE THREAD

**Issue by donchoborisov** [thedevdojo/voyager#5276]
## Version information

 - Laravel: v7.0
 - Voyager: v1.4.2
 - PHP: 7.3.#
 - Database: Mysql

## Steps To Reproduce
1. I am trying to get the data from the Pages table and show in my view on the front and I am hardcoding the id like its shown on my code below:

Route::get('/about', function() {
$id = 2;
 $page1 = App\Page::where('id','=', $id)->first();
    return view('pages.about',compact('page1'));
});

2. When I am selecting with App\Page::all() everything is working fine im getting the data and showing on the front. But when i put WHERE im getting the error below:

4. Trying to get property 'body' of non-object

## Expected behavior
I use to test my queries before this way and its working just fine. Is this a bug or I am doing something wrong?

**Comment by MrCrayon** [comment]
You are accessing the database with your model so Voyager does not play any part on this.
Said that if you are searching for primary key it usually better to use:
```php
$page1 = App\Page::find($id);
// or better
$page1 = App\Page::findOrFail($id);
```
For anything else do some debugging and if you can't solve ask in some more generic Laravel forum.
