### ISSUE TITLE
The validation was not working

### ISSUE THREAD

**Issue by xx10n31y** [thedevdojo/voyager#5277]
## Version information

 - Laravel: v6.20.19
 - Voyager: v1.x-dev
 - PHP: 7.3
 - Database: [MySQL] [5.7] 

## Description

The validation use max validator but that was not working
![1](https://user-images.githubusercontent.com/57975788/113248758-2544bc00-92f0-11eb-8121-77e93a665003.png)

## Steps To Reproduce
1. Setting the validations use the `Bread`
2. Go on the relative create/update page
3. The `rank` column is a signed tinyint in MySQL, and max is 127
4. Input 256 to the rank form, then throw a exception, so the validation is not working

## Expected behavior
The `max` validator should get back the error message  but that just throw a exception

## Screenshots
![1](https://user-images.githubusercontent.com/57975788/113248758-2544bc00-92f0-11eb-8121-77e93a665003.png)

![2](https://user-images.githubusercontent.com/57975788/113249231-ef540780-92f0-11eb-9235-f0e9743432b9.png)

**Comment by MrCrayon** [comment]
Validation is managed by Laravel.
As you are writing it validator has no way to know if you want to apply `max` rule as a string or number so it's applying it as a string counting characters.

You need to add integer or numeric to force the rule as number.

**Comment by xx10n31y** [comment]
> Validation is managed by Laravel.
> As you are writing it validator has no way to know if you want to apply `max` rule as a string or number so it's applying it as a string counting characters.
> 
> You need to add integer or numeric to force the rule as number.

Thanks for your responded. I added an `integer` into the `rule`, but also not working. So only to use the `max` attribute.
```json
{
    "validation": {
        "rule": "required|integer|min:0|max:200",
        "messages": {
            "required": "This :attribute field is a must.",
            "max": "This :attribute field maximum :max."
        }
    },
    "max": 100
}
```

**Comment by Loukili-Rachid** [comment]
Doing an inline validation will work properly 
Ex
```
{
    "validation": {
        "rule": "required|between:3,255|string"
    }
}
```
