### ISSUE TITLE
How to manage Created_by and Updated_by in table

### ISSUE THREAD

**Issue by pratiktops** [thedevdojo/voyager#5278]
## Version information

 - Laravel: 8
 - Voyager: Release v1.4.2
 - PHP: 7.3
 - Database: mysql

## Description

I have created new table called Product with below fields.
id,
name,
description,
product_category_id,
created_by,
updated_by,
Voyager Timestamp,
Voyager Softdelete,

How can I manage created_by on create  and updated_by on edit feature.

**Comment by emptynick** [comment]
As the issue template suggests, please ask questions in our Slack group.
