### ISSUE TITLE
Backup BREAD database?

### ISSUE THREAD

**Issue by ghuser655** [thedevdojo/voyager#5284]
## Version information
Not applicable

## Description of problem
I'm new to Laravel and Voyager and am developing a test app to increase my skills. Two times now I have lost my Voyager BREAD content. One time I messed up my database and had to roll it back, and one time I accidentally ran `artisan migrate:fresh`. Subsequently all my custom settings and BREAD content disappeared twice. (Although I am extremely grateful my menus did not disapear.)

## Proposed solution
A simple way to back up your BREAD database. Does not even need to be there in production environments, but just having the option to get back your BREAD settings in case you mess up would be very helpful for people new to the framework.

## Alternatives considered
Maybe some way to export the BREAD content manually, and then import it? JSON?

**Comment by fletch3555** [comment]
Voyager does not provide this feature and we do not plan to add it in the v1 stream.  There are a number of existing solutions that generally target the deployment process, but should meet your needs.  They've been mentioned many many times here in github issues, as well as in our slack group.  They all essentially generate laravel seeders from the database values.

Having said that, v2 is currently in development and includes a change to store Voyager system data (e.g. BREAD config) in json files as opposed to the database.  I believe this solves your problem as well.
