### ISSUE TITLE
is there any stable version of voyager?

### ISSUE THREAD

**Issue by karandatwani92** [thedevdojo/voyager#529]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.8
- PHP Version:5.6.16
- Database Driver & Version: mysql 5.7.9

### Description:
So many bugs: auto logout, unable to add entry using bread, unable to edit profile and many more in a fresh install.

Personally i like voyager comparing to other similar packages but this have so many bugs now a days makes it unusable.

**Comment by handiwijoyo** [comment]
Voyager is still on development, we expect some features to be added before we release v1.0
