### ISSUE TITLE
BREAD with the same model several times

### ISSUE THREAD

**Issue by paqstd-dev** [thedevdojo/voyager#5298]
**Is it possible to create BREAD with the same model several times?** 

For example, I have a table of products that has a field "gift" (bool). Need to make a separate menu item where all entries will be "gift" = false, and separately where "gift" = true. Is it possible? I did not find any information. Need help!

**Comment by paqstd-dev** [comment]
Could you describe the reason for closing the issue?

**Comment by emptynick** [comment]
The issue template has the answer why it was closed

**Comment by fletch3555** [comment]
In short, questions should be asked in slack.  We reserve github issues for bugs and features
