### ISSUE TITLE
Unable to Login to Admin

### ISSUE THREAD

**Issue by faraz-purelogics** [thedevdojo/voyager#53]
Hello,

I am new to Voyager, i have installed it as you directed in the documentation, its installed successfully, but when i try to login with default credentials admin@admin.com/password then i get following error.

![image](https://cloud.githubusercontent.com/assets/1137918/19899818/44818cba-a083-11e6-863d-8154db415ea8.png)

Thanks,
Faraz

**Comment by afsardo** [comment]
What version of laravel are you using it on?

Edit: Ok i actually noticed it in the screen 5.2

**Comment by berrymoor** [comment]
same problem..

**Comment by jun283** [comment]
5.2, same problem.

**Comment by ooocrniooo** [comment]
Here is a solution for this problem..

Change in: vendor/tcg/voyager/src/Controllers/VoyagerAuthController.php

`public function postLogin(Request $request){
        $authenticated = false;
        $this->validate($request, [
            $this->loginUsername() => 'required',
            'password' => 'required'
        ]);

```
    // If the class is using the ThrottlesLogins trait, we can automatically throttle
    // the login attempts for this application. We'll key this by the username and
    // the IP address of the client making these requests into this application.
    $throttles = $this->isUsingThrottlesLoginsTrait();


    if ($throttles && $this->hasTooManyLoginAttempts($request)) {
        return $this->sendLockoutResponse($request);
    }

    $credentials = $this->getCredentials($request);


    if (Auth::attempt($credentials, $request->has('remember'))) {
        $authenticated = true;
    }

    if($authenticated){
        return $this->handleUserWasAuthenticated($request, $throttles);
    }

    // If the login attempt was unsuccessful we will increment the number of attempts
    // to login and redirect the user back to the login form. Of course, when this
    // user surpasses their maximum number of attempts they will get locked out.
    if ($throttles) {
        $this->incrementLoginAttempts($request);
    }

    return redirect($this->loginPath())
        ->withInput($request->only($this->loginUsername(), 'remember'))
        ->withErrors([
            $this->loginUsername() => $this->getFailedLoginMessage(),
        ]);
}`
```

**Comment by faraz-purelogics** [comment]
Yes its laravel 5.2 i have checked it in laravel 5.3.\* and its working fine in that version but not in 5.2
And ooocrniooo solution also worked in 5.2 but after login avatar and profile image is not showing.

**Comment by ooocrniooo** [comment]
you must set manually a symlink to the storage path, after that your image path will be correct.

**Comment by filipsobol** [comment]
@faraz-purelogics As @ooocrniooo suggested, try to manually set a symlink (php artisan storage:link), but make sure you run console with admin rights.

**Comment by marktopper** [comment]
Sadly - we do not support Laravel 5.2.
Could however, if many people need this feature for Laravel 5.2, it could be implemented.

**Comment by jafarchoupan** [comment]
i take this error in login voyager dashbord for first time :These credentials do not match our records.
admin@admin.com and password input ...help me guys thanks

**Comment by fletch3555** [comment]
@jafarchoupan, this issue has been closed for a year and a half.  Please ask for help on our Slack group instead.
