### ISSUE TITLE
Bug display name when create BREAD for table

### ISSUE THREAD

**Issue by VoDuyNghia** [thedevdojo/voyager#5307]
Currently, I am researching voyager. But I have a problem that the display name of fields, I have set the field name in BREAD to be Vietnamese (Picture 1), but when I go to the blog list page, the field name is taken from the field of blog table (image 2).

![image](https://user-images.githubusercontent.com/46209046/117236480-f66fb780-ae52-11eb-924c-4a41ebd228ea.png)

![image](https://user-images.githubusercontent.com/46209046/117236510-05ef0080-ae53-11eb-99de-bc004145a8e4.png)

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
This can be reopened when the require information is provided.
