### ISSUE TITLE
Bug display name when create BREAD for table

### ISSUE THREAD

**Issue by VoDuyNghia** [thedevdojo/voyager#5308]
## Version information

- Laravel: v8
- Voyager: v1.4
- PHP: 7.4
- Database: MySQL 5.7.26

## Description

But I have a problem that the display name of fields, I have set the field name in BREAD to be Vietnamese (Picture 1), but when I go to the blog list page, the field name is taken from the field of blog table (image 2).

## Steps To Reproduce
1. Go to voyager BREAD for blog
2. Change display name by vietnameses ( Image 1)
3. Save and go to list blog
4. Display name field still by english (Image 2)

## Expected behavior
1. Go to voyager BREAD for blog
2. Change display name by Vietnamese 
3. Save and go to list blog
4. Display name field still by Vietnamese

## Screenshots

![image](https://user-images.githubusercontent.com/46209046/117236480-f66fb780-ae52-11eb-924c-4a41ebd228ea.png)

![image](https://user-images.githubusercontent.com/46209046/117236510-05ef0080-ae53-11eb-99de-bc004145a8e4.png)

**Comment by emptynick** [comment]
Do you have multilanguage enabled and did you switch to another locale when changing the display names?

**Comment by VoDuyNghia** [comment]
Yes. I'm using translate. But I changed Vietnamese but it only show by english

**Comment by MrCrayon** [comment]
@VoDuyNghia did you change locale in your profile?
The locale selector you see on top works mostly only to switch locale while you are editing.

**Comment by VoDuyNghia** [comment]
Ok. It work. Tks <3
