### ISSUE TITLE
Improve Voyager tables

### ISSUE THREAD

**Issue by abdgad** [thedevdojo/voyager#531]
Hello,
I have some suggestions to better organize and handle Voyager tables.
Currently, tables that are required for Voyager to function, let's call them Core Tables, are mixed with other tables. This creates two main problems:
1. The user can accidentally delete or modify one of these tables and the app will break.
2. Collision: Voyager uses common table names. This can cause collision if Voyager is installed in an existing app that relies on similar table names.

**Suggestions:**
- We need to identify the core tables that Voyager relies on, and make them immutable so the user won't accidentally make a breaking change. The current way to do this is to add them in Voyager config database.tables.hidden by default.
- To fix collision, we need a prefix to distinguish Voyager tables from the rest. Maybe something like: _voyager_menus_

I believe these are the current Core Table:
- data_rows      
- data_types     
- menu_items     
- menus                         
- permission_role
- permissions              
- roles          
- settings       
- users

**Comment by akazorg** [comment]
If you decide to change this, perhaps you should consider on having these table names defined on a config file, so we could name them -.+

**Comment by abdgad** [comment]
@akazorg the table names will be defined in the corresponding model. No need to define them in the config.

**Comment by akazorg** [comment]
@abdgad you're right.

**Comment by fletch3555** [comment]
This is being tracked elsewhere.  Closing due to age and inactivity.
