### ISSUE TITLE
Add Ckeditor instead CodeMirror

### ISSUE THREAD

**Issue by VoDuyNghia** [thedevdojo/voyager#5310]
## Version information

- Laravel: v8
- Voyager: v1.4
- PHP: 7.4
- Database: MySQL 5.7.26

## Description of problem
Present, Voyager use make editor of CodeMirror. I see it less feature-rich than Ckeditor 

## Proposed solution
Can we add more ckeditor?

**Comment by fletch3555** [comment]
Voyager uses ace editor, not CodeMirror.

Also, we're not planning to make this change.  Voyager v2 already has significant changes in this area, and we're not putting much effort into feature changes for the v1 stream right now.

Finally, there are licensing implications to using CKEditor:
https://ckeditor.com/pricing/
https://ckeditor.com/legal/
https://ckeditor.com/wysiwyg-editor-open-source/
https://softwareengineering.stackexchange.com/questions/228472/include-gplv2-licensed-data-in-mit-licensed-project
