### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#5313]
## Version information

 - Laravel: v7.29
 - Voyager: v^1.4
 - PHP: 7.2.25
 - Database: MySql 5

## Description
I had weird slug issues in project, so i started a new project with clean laravel installation. clean voyager, and recreating all tables and BREADS in voyager.

I cant access any bread, even the ones created with dummy data., they all result in a syntax error

`syntax error, unexpected ')'`

`::Composer\Autoload\includeFile
vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php:113`

I haven't edited any files other than .env. I haven't created any front end files. Everything has been done in voyager. When installing voyager i received seeder errors and had to add "database/seeders" line to composer.json to successfully install voyager.

**Comment by emptynick** [comment]
Both Laravel 7 and PHP 7.2 are EOL.
Not sure if there is any code that is incompatible with PHP 7.2 but you might want to check that.

**Comment by Philwn** [comment]
Upgraded to php 7.3... it was a headache and caused several errors/issues but after a couple of hours its finally working.

And the great news is it solved this syntax error.

Thanks!

**Comment by emptynick** [comment]
Very good. Closing.
