### ISSUE TITLE
New post XSS vulnerability

### ISSUE THREAD

**Issue by antimech** [thedevdojo/voyager#533]
- Laravel Version: 5.3.28
- Voyager Version: 0.10.7
- PHP Version: 7.1.0
- Database Driver & Version: SQLite ?

### Description:
Why this package have XSS? I was surprised that it is!

### Steps To Reproduce:
Add new post:
![image](https://cloud.githubusercontent.com/assets/13885653/21850678/f2b3e262-d835-11e6-89bf-634ca7cc6324.png)
Click "Create new post". And click "View" on the post. Result:
![image](https://cloud.githubusercontent.com/assets/13885653/21850777/6712f4ae-d836-11e6-98a1-9bfbc6c05d2c.png)
![image](https://cloud.githubusercontent.com/assets/13885653/21858968/1f0f03ea-d855-11e6-93f5-9c5ac9ad71f3.png)

### This trick not working on main screen:
![image](https://cloud.githubusercontent.com/assets/13885653/21859074/7bf53e8a-d855-11e6-8607-c2d7a4a5296f.png)

**Comment by cloudsben** [comment]
![image](https://cloud.githubusercontent.com/assets/1283779/21856795/358dc7b0-d85e-11e6-8216-e3dce7a0aaee.png)
I do not have this problem

**Comment by fergthh** [comment]
@cloudsben What version of Voyager you have?

**Comment by m1guelpf** [comment]
@fergthh 
Quote from issue body:
"Voyager Version: 0.10.7"

**Comment by antimech** [comment]
@cloudsben I have updated issue in details.

**Comment by fergthh** [comment]
Thanks @m1guelpf, I've seen that. My question was addressed to @cloudsben, to see if they were the same version.

**Comment by sarath-c-sandwich** [comment]
I don't have any problem on my current version, 0.10.8 you can upgrade to latest version and republish assets again.

**Comment by cloudsben** [comment]
@fergthh  
![image](https://cloud.githubusercontent.com/assets/1283779/21882895/70231752-d8e7-11e6-9e6b-fb4206e6b4ae.png)

**Comment by antimech** [comment]
@uchsarath 
![image](https://cloud.githubusercontent.com/assets/13885653/21890578/8a5f39aa-d8f8-11e6-89b9-7f721d99aa20.png)
The same...

**Comment by antimech** [comment]
@uchsarath Works for me! Thanks!

**Comment by marktopper** [comment]
@antimech: Have this issue been fixed by updating?

**Comment by antimech** [comment]
@marktopper Yes. Thanks! Where can I find commit fixes the issue? I would like to know how to filter only the `<script>` for my blog, not `<p> <html>` etc.

**Comment by marktopper** [comment]
Not sure where it was.
Sorry @antimech.

/closed since it's fixed in `v0.10.8`.
