### ISSUE TITLE
Install Voyager

### ISSUE THREAD

**Issue by sathiyasangar** [thedevdojo/voyager#5332]
**While installing voyager** 

**composer require tcg/voyage**r

Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+EQLP28T+2021-05-19+0506
to retrieve a token. It will be stored in "C:/Users/srsn/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

Please give a solution

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
Please provide the required information, then this can be reopened.

**Comment by ravatsinh** [comment]
fetching same issue 
![image](https://user-images.githubusercontent.com/2891293/119249825-6dc67a80-bbb9-11eb-8dde-b61d9dba908e.png)
