### ISSUE TITLE
 Uploading images on shared web server does not work

### ISSUE THREAD

**Issue by kelvindominguez1595** [thedevdojo/voyager#5338]
When I upload the voyager / laravel project by ftp and put the path in the ENV it loads the images that I uploaded locally but when I want to upload more it only saves the name but not the images, I am uploading to a shared web server with a normal cpanel, IT DOES NOT HAVE TO EXECUTE COMPOSER COMMANDS

[Image error](https://ibb.co/xhmfnw9)

**Comment by emptynick** [comment]
The issue template is not optional when opening issues.
Also, you will find a lot of solutions when searching our issues for shared hosting.
