### ISSUE TITLE
permission role not added when creating bread

### ISSUE THREAD

**Issue by dmarman** [thedevdojo/voyager#534]
- Laravel Version: 5.3
- Voyager Version: 0.10.8
- PHP Version: 5.6.20
- Database Driver & Version: mySQL - 5.6.20

Permissions not generated when submitting new bread. I have to run `php artisan db:seed --class=PermissionRoleTableSeeder` to complete table `permission_role`.

Is this normal?

I followed the installation in the docs.

**Comment by marktopper** [comment]
Try upgrade Voyager and see if this still happens for you.

**Comment by Flobbos** [comment]
I have the same problem described above. Just upgraded to version 0.10.16 and the permissions are still not generated when creating bread. :-(

**Comment by marktopper** [comment]
`v0.10.x` is no longer being developed.
I recommend upgrading to `v0.11`.

**Comment by dmarman** [comment]
installing a fresh Laravel and Voyager project give same error. Using `"tcg/voyager": "^0.11.3"`

**Comment by marktopper** [comment]
Did you have any errors or warnings when running the installation first time?

**Comment by Flobbos** [comment]
I am also still running into this problem in 0.11.4 after a flawless installation. Running php artisan db:seed --class=PermissionRoleTableSeeder fixes the issue.

**Comment by Iphoning** [comment]
Have the same issue. Please add this to the documentation. I'm a new to voyager and it costs me a few hours to find out what's wrong!

**Comment by fletch3555** [comment]
@Iphoning, this has been closed for 6 months.  Please open your own issue if needed
