### ISSUE TITLE
Image not showing after deployed into Hostinger

### ISSUE THREAD

**Issue by Tzerkee** [thedevdojo/voyager#5340]
## Version information

 - Laravel: 8.43.0
 - Voyager: ^1.4
 - PHP: 7.3.5
 - Database: MySQL 10.4

## Description:
I have a problem displaying my uploaded images, but I already have a symbolic link from `/public/storage` directory, pointing at `/storage/app/public`.

![image](https://user-images.githubusercontent.com/45502311/119850835-7a8ff900-bf40-11eb-9239-2d6698e5d87d.png)

![image](https://user-images.githubusercontent.com/45502311/119852339-cb542180-bf41-11eb-9a84-a52b6beadf3b.png)

All uploaded images are stored and can be displayed in `/storage/app/public` (inside Hostinger hpanel)

![image](https://user-images.githubusercontent.com/45502311/119854341-9517a180-bf43-11eb-9e17-65bfb11c9c08.png)

But it just won't show up the images and the image URL returns 404.....

![image](https://user-images.githubusercontent.com/45502311/119853894-2d615680-bf43-11eb-8efe-008dce5bdcdf.png)

Anyone can help me? :( Thank you so much

**Comment by fletch3555** [comment]
You don't have the right symlink.  You say you have `public/storage`, but what you show is `public/public`.  Just rename the symlink to storage and you should be fine

**Comment by Tzerkee** [comment]
`public` means link to the `public` folder inside `storage/app`, this probably is Hostinger file directories management staff?

![image](https://user-images.githubusercontent.com/45502311/119930953-0b9fb800-bfb3-11eb-9a26-f9dd4340edd5.png)

However, the actual name is shown in FTP server which is `storage`

![image](https://user-images.githubusercontent.com/45502311/119930581-49e8a780-bfb2-11eb-9fee-c7da68fdfe46.png)
