### ISSUE TITLE
There is a syntax error in VoyagerBaseController

### ISSUE THREAD

**Issue by kr-vishal** [thedevdojo/voyager#5345]
## Version information

 - Laravel: v6.20
 - Voyager: v1.x-dev
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

There is a syntax error in VoyagerBaseController.php

## Steps To Reproduce
Please migrate to v1.x-dev

## Expected behavior
There is a comma at the end of the function argument at line number **112**

## Screenshots
Please find the screenshot for your reference
![error](https://user-images.githubusercontent.com/22003873/120384241-f3bf8f80-c336-11eb-9acc-087d6da54976.png)

**Comment by fletch3555** [comment]
https://github.com/the-control-group/voyager/issues/5323
