### ISSUE TITLE
> The issue template is not optional.

### ISSUE THREAD

**Issue by 18322233491** [thedevdojo/voyager#5348]
> The issue template is not optional.
> This can be reopened once the required informations are provided.

i didn't understand your rply ......... what you mean?

_Originally posted by @shazimali in https://github.com/the-control-group/voyager/issues/4523#issuecomment-552887775_

**Comment by 18322233491** [comment]
how to solve?

**Comment by emptynick** [comment]
When you click `New issue` you are presented with our issue template that you have to fill out.
Otherwise issues will be closed (as stated in the template).
