### ISSUE TITLE
Wanna override TCG\Voyager\Http\Controllers@getContentBasedOnType function

### ISSUE THREAD

**Issue by cloudsben** [thedevdojo/voyager#535]
I wanna realize multiple upload image, so need override, 

> TCG\Voyager\Http\Controllers@getContentBasedOnType function

I don't want to Edit voyager project, how can I override in App/Http/Controllers ?

Thanks a lot!

**Comment by akazorg** [comment]
You can publish Voyager controllers on your local app, and edit the methods you desire.
Check Voyager docs: (https://the-control-group.github.io/voyager/docs/v0.10/#getting-started-configuration). Also, check voyager config file. It work's great.

**Comment by sarath-c-sandwich** [comment]
Really nice @akazorg but 
Can you share us an example? Duplicated the path. Let say we want to duplicate the tcg/voyager/src/http/controller/VoyagerMediaController.php ?

**Comment by cloudsben** [comment]
@akazorg you meaning I must copy all `TCG\Voyager\Http\Controllers` in my `App\Http\controllers`, but  I just wanna edit one controller file, and edit just one method

any other pathway?

**Comment by cloudsben** [comment]
@uchsarath Copy all of Voyager controllers into `App\Http\Controllers`, and edit voyager config file. It works for me, but this is not I want it.

![image](https://cloud.githubusercontent.com/assets/1283779/21882736/d462a0f8-d8e6-11e6-9cb8-0d171078006d.png)

 I wanna override like view template

![image](https://cloud.githubusercontent.com/assets/1283779/21882818/21877430-d8e7-11e6-8604-c4162301749d.png)

**Comment by sarath-c-sandwich** [comment]
Thanks @cloudsben  and what I want is the same as you. I want to override only one controller not a whole.

**Comment by akazorg** [comment]
Hello @uchsarath @cloudsben, all working now?
You can update just the controller you want, by writing the method you want to replace.
All voyager controllers are extending the ones in the vendor folder, so you're not overwriting them.
Hope it helps.

**Comment by marktopper** [comment]
There was a bug here, it is fixed in `master` #512 
Tagging a new version later today.

Then you can either overwrite controller namespace by changing the value of the config key `voyager.controllers.namespace` or by swapping out a single controller by adding the following to your `AppServiceProvider` in the `register ` method:
```
$this->app->bind(VoyagerBreadController::class, MyBreadController::class);
```

**Comment by cloudsben** [comment]
@akazorg @marktopper  Thanks a lot!

**Comment by sarath-c-sandwich** [comment]
Thanks @akazorg  & @marktopper  this is really nice. Work well.

**Comment by cloudsben** [comment]
@marktopper  I wanna override this controller in App/Http/Controllers/Controller.php

> project/vendor/tcg/voyager/src/Http/Controllers/Controller.php

how can I write in AppServiceProvider‘s register method? like this? 

> $this->app->bind(Controller::class, Controller::class);

Thanks a lot help me!

**Comment by marktopper** [comment]
That controller is within your own application, you can just open it at `app/Http/Controllers/Controller.php`.

For more information visit [Laravel's Documentation](http://laravel.com/docs).

**Comment by cloudsben** [comment]
Hello sir @marktopper, I mean I just wanna override `project/vendor/tcg/voyager/src/Http/Controllers/Controller.php`'s `getContentBasedOnType` method into `App/Http/Controllers/Controller.php`

or cover `project/vendor/tcg/voyager/src/Http/Controllers/Controller.php` file into `App/Http/Controllers/Controller.php`

how can I write in AppServiceProvider‘s register method? 

Thank you very much!

**Comment by marktopper** [comment]
You can not do that, it only works for the main controllers, not the controllers it extends.

But what would you like to overwrite form there?

**Comment by cloudsben** [comment]
@marktopper  I just rewrite `getContentBasedOnType` method in `project/vendor/tcg/voyager/src/Http/Controllers/Controller.php`

for the moment, this is the only pathway!

Thank you very mush!

**Comment by marktopper** [comment]
I only see the usage in the [`VoyagerSettingsController.php`](https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/VoyagerSettingsController.php#L54).

So why don't you just overwrite that controller?

**Comment by marktopper** [comment]
Ohh, I see that it's also used in `Controller.php` for the method `insertUpdateData`.

Which is used in `VoyagerRoleController.php` and `VoyagerBreadController.php`.

**Comment by cloudsben** [comment]
@marktopper Just as you say, Controller.php@insertUpdateData method use getContentBasedOnType, I upload multiple files need rewrite getContentBasedOnType switch type == 'image', and foreach it.

But, It does not matter, I think I do not upgrade version is a good way!

**Comment by marktopper** [comment]
We are open for pull requests that makes it possible to updates multiple files for BREAD as a new field option.

**Comment by cloudsben** [comment]
@marktopper Hi, Sir. You meaning is upload multiple files feature is already design?  Actually, I'm already implementing upload multiple files features.

**Comment by marktopper** [comment]
Voyager is not designed for uploading multiple files at once, but we would really like to see this as a core feature in Voyager. So maybe you could do a pull request for this feature instead of customizing Voyager.
Will also make it easier for you to upgrade to newer versions of Voyager without having to worry about you custom code.

**Comment by gbrits** [comment]
Just wanted to add a tear-away instruction note for anyone who may come upon this page looking to create a controller to override a specific Voyager controller.

1.) Copy the desired controller into your controllers folder, such as VoyagerBreadController.php.
2.) You can then rename it, such as **MyBreadController.php**
3.) Inside, be sure to change the namespace to `namespace App\Http\Controllers;`
4.) Also, be sure to change class extension declaration to extend the Voyager controller, as it has some additional helpers (such as getSlug) already in it:
```
class MyBreadController extends \TCG\Voyager\Http\Controllers\Controller
```
5.) Add or update any methods as required.
6.) Lastly, go into your **AppServiceProvider.php** and add in the class declarations:
```
use TCG\Voyager\Http\Controllers\VoyagerBreadController;
use App\Http\Controllers\MyBreadController;
```
then inside of the register method, add in the bind as mentioned by @marktopper above:
```
public function register()
{
     $this->app->bind(VoyagerBreadController::class, MyBreadController::class);
}
```

**Comment by vicmans** [comment]
Another way to override a Controller by using the `voyager:controllers` command, in these controllers you can do the same that @gbrits but without change the `AppServiceProvider.php`

After of calling the command the controllers look at this:
```
<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerController as BaseVoyagerController;

class VoyagerBreadController extends BaseVoyagerController
{
    //
}
```

- Copy the content from the original controller in `vendor/tcg/voyager` to the namespace App\Http\Controllers\Voyager
- Change the extends to \TCG\Voyager\Http\Controllers\Controller
- Example:
- `class VoyagerBreadController extends \TCG\Voyager\Http\Controllers\Controller`
- Add or Edit the original methods

To the VoyagerBreadController result this:
````
<?php

namespace App\Http\Controllers\Voyager;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use TCG\Voyager\Database\Schema\SchemaManager;
use TCG\Voyager\Events\BreadDataAdded;
use TCG\Voyager\Events\BreadDataDeleted;
use TCG\Voyager\Events\BreadDataUpdated;
use TCG\Voyager\Events\BreadImagesDeleted;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\Traits\BreadRelationshipParser;

class VoyagerBreadController extends \TCG\Voyager\Http\Controllers\Controller
{
    //// METHODS
```

**Comment by fletch3555** [comment]
Please don't comment on closed threads that have been untouched for so long.

Also, we don't recommend anyone use the `voyager:controllers` command as it only causes issues with upgrades.
