### ISSUE TITLE
sidebar localization does not work

### ISSUE THREAD

**Issue by albayenes** [thedevdojo/voyager#5354]
## Version information

 - Laravel: v8.45.1
 - Voyager: v1.4.2
 - PHP: 7.4
 - Database: MySQL 5.7

## Description

I enabled multilanguage support for Voyager. In admin panel, translations work correctly in many places but sidebar and navigation menu do not show translations in selected language. They are always in English. 

## Steps To Reproduce
1. Enable mutilanguage support
2. Go to admin panel
3. Change language of the user other than English
3. Check sidebar and navigation menu language
4. See the error

## Expected behavior
Sidebar and navigation menu must be shown user language

## Screenshots

![image](https://user-images.githubusercontent.com/87531/120893190-953a3000-c61a-11eb-9b4e-5a4c1fd91e33.png)

![image](https://user-images.githubusercontent.com/87531/120894143-a0438f00-c61f-11eb-9683-8516e0ea45ef.png)

**Comment by emptynick** [comment]
The menu items don't contain all translations by default.
The easiest way is to run `voyager:install` with the wanted locale set.
Another way is to run the menu seeder again (after clearing the menu_items table)
And you can also simply translate them in the menu builder.
