### ISSUE TITLE
Database - Field Validation

### ISSUE THREAD

**Issue by thebitrock** [thedevdojo/voyager#536]
https://owncloud.canopus.ga/index.php/s/lIHAgNrzVlTKviE
- Laravel Version: 5.3.29
- Voyager Version: 0.10.8
- PHP Version: 7.0.14
- Database Driver & Version:

### Description:
can't delete when name with '/'
https://owncloud.canopus.ga/index.php/s/lIHAgNrzVlTKviE

### Steps To Reproduce:
https://owncloud.canopus.ga/index.php/s/lIHAgNrzVlTKviE

**Comment by Frondor** [comment]
Either the table name should be `rawurlencode()` or `alpha_dash` rule must be added to that field's validation.

**Comment by marktopper** [comment]
We are open for pull requests

**Comment by Frondor** [comment]
To be honest, I spent like 2 hours trying to implement `rawurlencode()` without success. So I guess I'll help with the validation :smile: it sounds like the way to go, a table shouldn't be named `/yo/bitch/`

**Comment by marktopper** [comment]
I agree.

@pogorelchuk: Did you create your table using Voyager or did you build it directly from Laravel or in your database manager tool?

**Comment by marktopper** [comment]
Closed due to missing response.
