### ISSUE TITLE
I can't add image in settings menu.

### ISSUE THREAD

**Issue by volkankocaali** [thedevdojo/voyager#5361]
## Version information

 - Laravel: v8.46.0
 - Voyager: v1.4.2
 - PHP: 7.4.3

## Description

I can't add image in settings menu. When I check the storage files, the settings folder is created outside of public. how can i solve this problem.

## Additional context

![storage](https://user-images.githubusercontent.com/41877138/121509424-4c55f300-c9ef-11eb-8277-e8442be6aa1f.PNG)
![settgs](https://user-images.githubusercontent.com/41877138/121509435-4eb84d00-c9ef-11eb-8004-eed4bf5b7998.PNG)
![stadsa](https://user-images.githubusercontent.com/41877138/121509702-98a13300-c9ef-11eb-985d-75b1d6ed937e.PNG)

**Comment by MrCrayon** [comment]
Check your storage configuration

**Comment by volkankocaali** [comment]
My storage settings are as they should be

```
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
        ],

    ],
```

**Comment by MrCrayon** [comment]
If you are using laravel/laravel 8.5.19 and up you'll need to change disk configuration in `config/voyager.php` and set it as `public`.
You can read the explanation here: https://github.com/the-control-group/voyager/issues/5362#issuecomment-860007292

Let us know if that solves the problem.

**Comment by hamitdaylak** [comment]
when will the problem be solved?

**Comment by emptynick** [comment]
This is fixed. See above
