### ISSUE TITLE
Media not show image after upload if location out side public folder

### ISSUE THREAD

**Issue by aroon9002ahmed** [thedevdojo/voyager#5362]
## Version information

 - Laravel: v8.46.0
 - Voyager: v1.4
 - PHP: 7.4
 - Database:MySQL 

## Description

Media not show image after upload if location out side public folder

APP_URL=http://localhost:8000

filesystem:
```

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'endpoint' => env('AWS_ENDPOINT'),
            'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
        ],

    ],
```

## Screenshots
if upload outside public folder
https://s1.im.ge/2021/06/10/N1p8.jpg

if upload inside public folder
https://s1.im.ge/2021/06/10/NOCX.jpg

**Comment by emptynick** [comment]
Not sure I understand you.
The public folder is the only folder that is accessible from your browser.

**Comment by aroon9002ahmed** [comment]
there 2 folders inside media
check this screenshot
https://s1.im.ge/2021/06/11/NyDL.jpg

**Comment by volkankocaali** [comment]
I had the same problem. 
I solved the problem by making the FILESYSTEM_DRIVER value in the env file public.

And don't forget to `php artisan optimize`

**Comment by diegodeluca** [comment]
I found an unorthodox solution, maybe can help.
In \config\filesystems.php i changed from 
`public_path('storage') => storage_path('app/public'),`
to
`public_path('storage') => storage_path('app'),`
deleted (if present) the storage symlink in public folder
regenerate the symlink in public folder with `php artisan storage:link`

Obviously it will affect the whole application, so you must check all the places where you used the symlink

**Comment by pro-cms** [comment]
Hellow, simply go to filesystem , look at the local drive , update root path to app/public
i.e change from
 
**'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],**

to 
 **'local' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
        ],**
your problem should be fixed

**Comment by aroon9002ahmed** [comment]
Thank you @pro-cms

**Comment by MrCrayon** [comment]
@aroon9002ahmed @pro-cms
It would be better to leave filesystem config untouched and change voyager config file to use `public` storage.

An explanation on what's happening:
Voyager config file defines which storage to use like this:
```php
'storage' => [
    'disk' => env('FILESYSTEM_DRIVER', 'public'),
],
```
Since FILESYSTEM_DRIVER was not defined by default in Laravel the public storage was used, but in Laravel 8.5.19 the default value was added.

https://github.com/laravel/laravel/commit/c5d38d469a447d6831c3cf56d193be7941d6586f#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8c

@emptynick @fletch3555 should we change voyager config file and just set `public` or any other idea?

**Comment by emptynick** [comment]
Yeah I think we can do that

**Comment by pro-cms** [comment]
@aroon9002ahmed @MrCrayon @emptynick  #5364 is the best solution , thank you
