### ISSUE TITLE
IMAGES

### ISSUE THREAD

**Issue by diegodeluca** [thedevdojo/voyager#5364]
## Version information

 - Laravel: v8.46.0
 - Voyager: v1.4.0
 - PHP: 7.4.5
 - Database: mysql

## Description

Uploaded image not displaying
Profile image not showing

## Steps To Reproduce

1. laravel new myproject
2. edited .env file
3. composer require tcg/voyager
4. php artisan voyager:install
5. php artisan voyager:admin your@email.com --create (inserted name and password)
6. php artisan serve
7. Logged in: 127.0.0.1:8000/admin
8. Uploaded an image in media section
9. Image not displaying

## Expected behavior
I expected to view the image in the media folder and as profile picture

## Screenshots
Uploaded an image in media section
![image](https://user-images.githubusercontent.com/7009270/121666760-e4181780-caa9-11eb-8ee4-5f6ec056a189.png)

**Comment by diegodeluca** [comment]
I forgot: if I try to change the avatar profile I have the same issue

**Comment by diegodeluca** [comment]
I detail my personal solution for a new project.

I think the images are uploaded in a "wrong" folder.
I didn't find the voyager default upload folder (TLDR), and because I'm starting a new project I applied an unconventional solution.

1. removed the storage simlink in public folder (if present)
2. in **config\filesystems.php** changed `public_path('storage') => storage_path('app/public'),` to `public_path('storage') => storage_path('app'),`
3. launched `php artisan storage:link`

**Comment by fletch3555** [comment]
Just curious, but what's the reasoning behind changing the filesystem config (i.e. removing `/public` from the path)?

**Comment by diegodeluca** [comment]
I've noticed that Voyager by default upload images inside storage/app but the symlink redirect to storage/app/public.
So I needed to modify the symlink and because I'm not so skilled and I don't know if it's possible to modify using CLI, I removed the symlink, modified the path in laravel settings and regenerated it.

My problem is that this package needs fixings to work but it's not explained how in the documentation. Even on a fresh new clean installation

**Comment by pro-cms** [comment]
Hellow, simply go to filesystem , look at the local drive , update root path to app/public
i.e change from
 **'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],**

to 
 **'local' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
        ],**
your problem should be fixed

**Comment by MrCrayon** [comment]
This should be fixed with #5364, for existing installations you'll need to change disk configuration in `config/voyager.php` and set it as `public`.
You can read the explanation here: #5362

**Comment by diegodeluca** [comment]
@pro-cms 
Sorry for the late answer but only now I've had the possibility to try the solution and it worked.
Thank you

**Comment by pro-cms** [comment]
@diegodeluca your always welcome
