### ISSUE TITLE
symlink(): No such file or directory. Fixed!!

### ISSUE THREAD

**Issue by joshuaunity** [thedevdojo/voyager#5366]
This is how I solved this issue, note that the "Fix it" notification still shows after this fix.

Make the following changes to you live app(that is your app online), I am using cPanel incase you want to know.

Add this in your web.php
Route::get('/link', function () {        
   $target = '/home/username/app_foler_name/storage/app/public';
   $shortcut = '/home/username/public_html/storage';
   symlink($target, $shortcut);
});

Now open a new tab and put in yourwebsitename.yourdomain/link

Incase you get the error below after doing the above steps:
Error: Call to undefined function Illuminate\Filesystem\finfo_file()
Go to Cpanel, go to "PHP selector"  and check the "fileinfo" option.

I also replaced my symbolic link in config/filesystem.php with the code below.
    'links' => [
      public_path('/home/username/public_html/storage') => 
     storage_path('/home/username/app_folder_name/storage/app/public'),
    ],

**Comment by MrCrayon** [comment]
https://github.com/the-control-group/voyager/pull/5367
