### ISSUE TITLE
Invalid datetime format: 1292 Incorrect datetime value

### ISSUE THREAD

**Issue by simondavies** [thedevdojo/voyager#537]
- Laravel Version: 5.3.29
- Voyager Version: #.#.#
- PHP Version: 7.1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.1.18-MariaDB 
- Running on Laravel Valet

### Description:
When I updated one of the dummy data posts, I got the following error:

`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' at row 1 (SQL: update `posts` set `author_id` = 1`

### Steps To Reproduce:
clean install of laravel, following the voyager install with dummy data, set up DB connection.  logged in and edit a post and tried to update.

**Comment by ergonomicus** [comment]
Same here...

`SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' at row 1`

**Comment by handiwijoyo** [comment]
Duplicate #521

**Comment by ergonomicus** [comment]
So, the fix is to edit BREAD? Seems like a bug to me...

**Comment by handiwijoyo** [comment]
Yeah, when you check edit on BREAD, it expect to have that field on posts edit page. Since our posts edit form doesn't has created_at input field it will save with empty string which will cause the error.
