### ISSUE TITLE
Composer lock file

### ISSUE THREAD

**Issue by Cyrille37** [thedevdojo/voyager#5371]
- Laravel: v8.x
 - Voyager: v1.4
 - PHP: 7.x

Hello. Is there a reason why `composer.lock` is not in the repository ?

Thanks.

**Comment by emptynick** [comment]
I think mainly because we support various versions of PHP and/or Laravel, which in return, require various sub-dependencies.
Adding a composer.lock might lock everything to one specific set of versions (which might fail for a lot people)

**Comment by Cyrille37** [comment]
Thanks. U've right, it's a big challenge :-)

**Comment by Cyrille37** [comment]
Related:
- [phpunit tests failed: missing laravel/legacy-factories #5372](5372)
