### ISSUE TITLE
Successfull Login Redirects user other than admin to the website root.

### ISSUE THREAD

**Issue by cybergears** [thedevdojo/voyager#5376]
## Version information
 - Laravel: v8.x
 - Voyager: v1.x-dev
 - PHP: 8.x
 - Database: [mysql] [5.0] 

## Description:
I have successfully installed voyager admin. I am also able to login as admin. I have created new roles lets say 5 roles with custom permissions set from the voyager admin dashboard. I have also created users for each custom role from the voyager admin dashboard. The problem is, when i try to login using other users details who have no admin role redirects the user to the website root and after that  url/admin also redirects user to the website's root.

I even created a route as follows 
Route::group(['prefix' => 'custom_role'], function () {
    Voyager::routes();
});

but still i get the same result. 
After that i gave additional role of admin to the custom role user and i was able to login but the custom user was able to perform all the tasks like admin does. I don't want the custom role users to perform the admin tasks.

Do i need to create separate dashboard for the other role users? 

Please help me with this issue. 
Thankyou!
Love from India

**Comment by cybergears** [comment]
Thankyou guys i found the solution, 
By default new user does not have the permissions to browse the admin. 
In the database , permission table has browse_admin key i just created a new entry in in permission_role table with the id of browse_admin key and the id of my custom role and i was able to login.

I will close this thread now.

**Comment by emptynick** [comment]
By default, when a user model is created, Voyager will assign the role set in the config to that user.
