### ISSUE TITLE
Unknown database type enum

### ISSUE THREAD

**Issue by angelkurten** [thedevdojo/voyager#54]
[Doctrine\DBAL\DBALException]

Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

**Comment by fletch3555** [comment]
Have you configured your Database as the documentation describes? Are you using MySQL? PostgreSQL? SQLite?

**Comment by angelkurten** [comment]
Use MySQL 5.7

**Comment by angelkurten** [comment]
vagrant@homestead:~/Code/fip$ php artisan voyager:install
Generating the default authentication scaffolding
Publishing the Voyager assets, database, and config files
Migrating the database tables into your application

  [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

`

**Comment by marktopper** [comment]
There is currently no support for `enum` for MySQL v5.7

You can see the issue at Laravel: https://github.com/laravel/framework/issues/1186

**Comment by marktopper** [comment]
This should work in the latest version of Voyager.
