### ISSUE TITLE
General error: 1364 Field 'username' doesn't have 

### ISSUE THREAD

**Issue by ahmetbarut** [thedevdojo/voyager#5400]
## Version information

 - Laravel: v8.x
 - Voyager: v1.4
 - PHP: 8.0
 - Database: [Mysql]

## Description:
Hi, I have a column named username in my users table. When I create a new user from Voyager the username is not added correctly. I added it from the template section, but it was not added. I did a search and couldn't find any results.

## Additional context
```php

                            <div class="form-group">
                                <label for="username">{{ __('username') }}</label>
                                <input type="text" class="form-control" id="username" name="username"
                                       placeholder="{{ __('username') }}"
                                       value="@if(isset($dataTypeContent->username)){{ $dataTypeContent->username }}@endif">
                            </div>
```

**Comment by pro-cms** [comment]
@ahmetbarut Make sure you have a username column in the database. 

then go to voyager tools----> Move to **bread**---->click edit on users bread---->go and look for **username section** and make sure to check the **BROWSE, EDIT, DELETE AND UPDATE** checkboxes and then save. 

This will kinda refresh the voyager bread system and your problem should be fixed.
![Capturedddddddddddddddddddddd](https://user-images.githubusercontent.com/57701433/125178560-0909c280-e1ef-11eb-83ef-b1ce945a1fcd.JPG)

**Comment by ahmetbarut** [comment]
Thanks @pro-cms. I solved the problem in another way. I'm closing the issue for now
