### ISSUE TITLE
Compass documentation link goes to wrong and unrelated domain

### ISSUE THREAD

**Issue by Correct-Syntax** [thedevdojo/voyager#5411]
### Laravel version

8.49.1

### PHP version

8.0.2

### Voyager version

1.x-dev

### Database

10.4.17-MariaDB - mariadb.org binary distribution

### Description

The links in the dashboard go to an unrelated site: https://laravelvoyager.com/

### Steps to reproduce

Just go to dashboard, under Settings>Compass and click the link to the docs, etc

### Expected behavior

Go to the actual site at https://voyager-docs.devdojo.com/

### Screenshots

![Screenshot 2021-07-28 094107](https://user-images.githubusercontent.com/60711001/127344201-ab93bbf1-6529-434b-bafd-ca1de554f7e9.png)

**Comment by emptynick** [comment]
Are you able to open a PR?

**Comment by bxmas13** [comment]
I found the same issue today and opened a PR.
