### ISSUE TITLE
Updating post throughs `updated_at` invalid date error.

### ISSUE THREAD

**Issue by victorpierredev** [thedevdojo/voyager#543]
Laravel Version: 5.3.28
Voyager Version: "^0.10.7"
PHP Version: 7.0
Database Driver & Version: 15.1 Distrib 10.1.20-MariaDB

### Description:
```php
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'updated_at' at row 1 (SQL: update `posts` set `author_id` = 1, `category_id` = 1, `seo_title` = , `excerpt` = This is the excerpt for the sample Post , `body` = <p>This is the body for the sample post, which includes the body.</p>
<h2>We can use all kinds of format!</h2>
<p>And include a bunch of other stuff.</p>, `meta_description` = Meta Description for sample post , `meta_keywords` = keyword1, keyword2, keyword3 , `updated_at` = 1970-01-01 00:00:00 where `id` = 2)
```
tried updating the BREAD visibility, but error still occurs. 

### Steps To Reproduce:
+ Open a `Post`
+ Save it.
+ Throws error.

**Comment by handiwijoyo** [comment]
@vpakg which BREAD visibility are you talking about?

**Comment by victorpierredev** [comment]
I meant this. Sorry, I should have been more clear.

![visibility](https://cloud.githubusercontent.com/assets/4654583/21932831/8bfec4f6-d970-11e6-977e-f5792d4700a5.png)

**Comment by handiwijoyo** [comment]
Try to use last version of Voyager to see if this fixed.

**Comment by victorpierredev** [comment]
Seems to be fixed. Thanks!
