### ISSUE TITLE
Larapack.io SSL certificate expired

### ISSUE THREAD

**Issue by lantonello** [thedevdojo/voyager#5434]
### Laravel version

8.55.0

### PHP version

7.4.12

### Voyager version

1.x-dev

### Database

MySQL 8.0

### Description

I have a fresh installation of Laravel and Voyager.
Everything works fine, I can log in to the admin panel and make all things.
When I go to install another package, I get the error:

![Captura de tela 2021-08-23 121339](https://user-images.githubusercontent.com/15302760/130480319-3fbca0e2-4f13-4564-9430-2656a397618d.png)

This error occurs with any package that I want to install.

### Steps to reproduce

Install a PHP package with composer

### Expected behavior

Successful install

**Comment by fletch3555** [comment]
We're aware.  We plan to remove hooks in the next version as we unfortunately no longer have control over larapack.

Having said that, this issue is caused by the addition of a repository added to your composer.json file.  You can simply remove that block and everything else should work as normal.

**Comment by lantonello** [comment]
@fletch3555 
Thanks a lot for your reply.
I have removed that block from my composer.json file and now I can install other packages with no problems.
