### ISSUE TITLE
Create new Bread Database

### ISSUE THREAD

**Issue by DevTheJul** [thedevdojo/voyager#5455]
### Laravel version

8.62.0

### PHP version

8.0.10

### Voyager version

newest

### Database

MysQl standart

### Description

Hey, evertime if i create a database, and then i would like to create bread and click after this on view bread this happend: 

`Illuminate\Database\QueryException
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'DBNAME.test' (SQL: select `test`.* from `tests` order by `created_at` desc)`

### Steps to reproduce

above

### Expected behavior

it would be a plesure, if you can help me

**Comment by pro-cms** [comment]
You gave the wrong name to the table, voyager is trying to select from table  test, go the Test model and add protected $table="your table name", or name your model and migration according to laravel standards.
