### ISSUE TITLE
Hooks aren't there

### ISSUE THREAD

**Issue by DevTheJul** [thedevdojo/voyager#5462]
### Laravel version

8.62.0

### PHP version

8.0.10

### Voyager version

newest

### Database

standart

### Description

Hey,

i don't have a hook site, where i can create and upload hooks

### Steps to reproduce

Just installled voyager

### Expected behavior

https://devdojo.com/devdojo/creating-a-voyager-hook here is standing that there is a hook settings but there is no setting O:

**Comment by fletch3555** [comment]
Hooks were removed in v1.5.0: https://github.com/the-control-group/voyager/releases/tag/v1.5.0
