### ISSUE TITLE
Promblem in Multiple Checkbox. count(): Argument #1 ($var) must be of type Countable|array

### ISSUE THREAD

**Issue by imsyuan** [thedevdojo/voyager#5478]
### Laravel version

8.53.1

### PHP version

8.0.9

### Voyager version

1.5.1

### Database

5.6

### Description

Getting TypeError when I using sample code in BREAD.

`count(): Argument #1 ($var) must be of type Countable|array, stdClass given (View: /var/www/html/vendor/tcg/voyager/resources/views/bread/browse.blade.php`

![截圖 2021-10-25 下午2 51 34](https://user-images.githubusercontent.com/8586464/138647988-2b15502f-ee58-4a1d-9e83-5537f69d19d1.png)
)

### Steps to reproduce

Put the sample code in BREAD 
`{
    "options": {
        "checkbox1": "Checkbox 1 Text",
        "checkbox2": "Checkbox 2 Text"
    }
}`

<img width="1296" alt="截圖 2021-10-25 下午2 50 59" src="https://user-images.githubusercontent.com/8586464/138648250-30763e09-a895-424d-b010-e61d6063545a.png">

### Expected behavior

fix it as below. add `true` into json_decode

file : `tcg/voyager/sources/views/bread/browse.blade.php` line 148 and line 149

```
@if (@count(json_decode($data->{$row->field}, true)) > 0)
    @foreach(json_decode($data->{$row->field}, true) as $item)
```

![截圖 2021-10-25 下午2 55 55](https://user-images.githubusercontent.com/8586464/138648866-67f5bac7-a0ac-4604-80b3-d344adfa99c9.png)

**Comment by emptynick** [comment]
Fixed in #5473
