### ISSUE TITLE
Custom submit button throws memory error

### ISSUE THREAD

**Issue by haexperts2020** [thedevdojo/voyager#5482]
### Laravel version

8.6.5

### PHP version

7.4

### Voyager version

1.5

### Database

MySQL 8

### Description

Browse to a bread page and click add or edit and get this error:

```
Symfony\Component\ErrorHandler\Error\FatalError: Allowed memory size of 536870912 bytes exhausted (tried to allocate 1875968 bytes) in file /var/www/tw/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesLayouts.php on line 134

#0 {main}
```

### Steps to reproduce

In the resource folder create views/vendor/voyager/bread/edit-add.blade.php

Copy and paste 

`@extends('voyager::bread.edit-add')
@section('submit-buttons')
    @parent
    <button type="submit" class="btn btn-primary save">Save And Publish</button>
@endsection`

### Expected behavior

Changes default submit button to say "Save and Publish"

**Comment by MrCrayon** [comment]
That's a Laravel limitation, you cannot override a template and extend from it at the same time.
It generates an infinite loop that makes you run out of memory.
