### ISSUE TITLE
Font Awesome missing

### ISSUE THREAD

**Issue by afsardo** [thedevdojo/voyager#55]
The font awesome icons used in "breadcrumbs" are missing.

![screenshot-2016-11-01-23 32 46](https://cloud.githubusercontent.com/assets/6538082/19911491/c8bb3d2a-a08b-11e6-88eb-876b2861afad.gif)

I have the solution for it going to send the PR.

**Comment by guahsu** [comment]
I see the other icon miss is left-menu > tools  (when mouse haver)

**Comment by akazorg** [comment]
Have you tried the latest version? Or maybe clear your browser cache?
I was experiencing that behavior, but now it's looking ok.

**Comment by afsardo** [comment]
The PR #56 should fix all those icons missing ;)

**Comment by guahsu** [comment]
thanks , I will check it again when I go home:)

**Comment by Omazon** [comment]
works, there is that add the folder font of fontawesome to the folder public\vendor\tcg\voyager\assets\fonts and then modify the file CSS public\vendor\tcg\voyager\assets\fonts\voyager\styles.css adding them them lines that appear in: https://github.com/afsardo/voyager/blob/d91e83411aab54fea5c2ae4929066c1477fef2b1/assets/css/style.css

I would recommend that this correction come already included in the download version or apply an update

**Comment by handelaar** [comment]
As of right now, Prev/Next buttons in object lists are still missing icons, because FontAwesome is still referenced for inclusion... nowhere.

**Comment by fletch3555** [comment]
@handelaar, this issue was closed 10 months ago.  If you still have issues, please open your own issue or ask on the Slack group's #help channel.
