### ISSUE TITLE
Delete event not firing when User is deleted from Voyager admin panel

### ISSUE THREAD

**Issue by moonvader** [thedevdojo/voyager#5504]
### Laravel version

6.17

### PHP version

7.4

### Voyager version

1.5.2

### Database

MySQL

### Description

In User model I want to run custom actions when user is deleted so I add this events using code below

```
    public static function boot()
    {
        parent::boot();

        static::deleted(function ($model) {
           someAction1();
        });

        static::saved(function ($model) {
            someAction2();
        });
    }
```

When I delete user from Voyager this actions are not being called. 
What am I doing wrong and are the any other way to run custom action when user is deleted from voyager admin panel?

### Steps to reproduce

Delete user from Voyager admin panel

### Expected behavior

deleted or deleting events are called

**Comment by emptynick** [comment]
Voyager uses `destroy` to delete multiple model instances at once.
This doesn't trigger the `deleted` event because the actual model is not retreived before.
But Voyager fires [BreadDataDeleted](https://github.com/the-control-group/voyager/blob/1.5/src/Events/BreadDataDeleted.php)

**Comment by moonvader** [comment]
Thank you,
in this case I need to add my custom listener? how can I access deleted user's id from it?

**Comment by howdu** [comment]
Add this into service provider e.g EventServiceProvider
Event::listen(\TCG\Voyager\Events\BreadDataDeleted::class, CustomDeleteListener::class);

Then create a listener class
```
<?php

use TCG\Voyager\Events\BreadDataDeleted;

class CustomDeleteListener
{
	/**
	 * Handle the event.
	 *
	 * @param  BreadDataDeleted  $event
	 * @return void
	 */
	public function handle(BreadDataDeleted $event)
	{
		if (!empty($event->dataType)) {
			switch ($event->dataType->slug) {
				case 'users':
					$request = app(Request::class);

					// custom logic

					break;
			}
		}
	}
}

```

More info on events: https://laravel.com/docs/8.x/events
