### ISSUE TITLE
Data is not inserting in related table

### ISSUE THREAD

**Issue by dev-paceglobal** [thedevdojo/voyager#5512]
### Laravel version

8.75.0

### PHP version

8.0.12

### Voyager version

1.5.2

### Database

8.0.27

### Description

Hey there I've some related tables and create relations according to the guide  [Voyger Doc](https://voyager-docs.devdojo.com/bread/relationships)  
![image](https://user-images.githubusercontent.com/92759590/148614453-7b940919-2982-40a7-9d88-c13308c50e70.png)
and this is how I created the table I don't know why this isn't works I use voyeger earlier I that's work pretty fine. 

### Steps to reproduce

I tried to recreate the relation but not that was not works
So I tried to create relations in other Breads but again I can able successfully create relations but When I Create a new record that was not hold relation table id.  

### Expected behavior

I want when I add the data in Medical Questionnaire Options with all data type_id attribute holds medical_questionnaire_type.id but it won't holds 

### Screenshots

![image](https://user-images.githubusercontent.com/92759590/148614783-f3fdb782-91f4-4a13-8ef2-79d65f99afbc.png)
![image](https://user-images.githubusercontent.com/92759590/148614633-4558dc41-3745-44d5-bfc4-46f3055f27d4.png)
![image](https://user-images.githubusercontent.com/92759590/148614673-4f1b4749-3572-48e9-baf8-9af4f719f50c.png)

**Comment by Dri372** [comment]
Hello, 

I get the same issue and do this quick workaround in vendor/tcg/voyager/src/Http/Controllers/Controller.php
see modifs commented with #B5512

I don't know enough Voager to test all cases bit it works for me.

```
        foreach ($rows as $row) {
dump($row);    
dump($row->type);    
            // if the field for this row is absent from the request, continue
            // checkboxes will be absent when unchecked, thus they are the exception
            if (!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox') {
                // if the field is a belongsToMany relationship, don't remove it
                // if no content is provided, that means the relationships need to be removed
                #B512 if (isset($row->details->type) && $row->details->type !== 'belongsToMany') {
                if (isset($row->details->type) && $row->details->type !== 'belongsToMany' && $row->details->type !== 'belongsTo') {	#B5512
dump("continue1");
dump($row->details->type);
dump($row->details->column);
			continue;
                }
            }

dump($row->type);    
if ($row->type == 'relationship') dump($row->details->type);
            // Value is saved from $row->details->column row
            if ($row->type == 'relationship' && $row->details->type == 'belongsTo') {
dump($row->details->column);    
                #B5512 continue;
	    }

            #B5512 $content = $this->getContentBasedOnType($request, $slug, $row, $row->details);
            if ($row->type == 'relationship' && $row->details->type != 'belongsToMany') {
		    $row->field = @$row->details->column;
dump("relationship row->field=".$row->field);
            }
            $content = $this->getContentBasedOnType($request, $slug, $row, $row->details);	#B5512
```

**Comment by dev-paceglobal** [comment]
@Dri372  Thanks alot friend it's work for me also 👍🏽
