### ISSUE TITLE
CSP non-secured content not loading when using SSL

### ISSUE THREAD

**Issue by itsvasugrover** [thedevdojo/voyager#5513]
### Laravel version

8.75

### PHP version

7.4.3

### Voyager version

1.5.2

### Database

MySQL 8.0.27

### Description

The TinyMCE is not loading as the necessary scripts are giving CSP errors. The file manager is also loading infinitely.

### Steps to reproduce

[1] Create a new project.
[2] Install voyager with dummy data.
[3] Make sure to serve securely.

### Expected behavior

Load TinyMCE editor and show File Manager without any errors.

### Screenshots

![error1](https://user-images.githubusercontent.com/41840203/148689126-0b040684-373f-4b07-95db-7ac094c69b80.png)
![error2](https://user-images.githubusercontent.com/41840203/148689151-c2204f9e-00fe-476b-9f61-247612bcb591.png)
![error3](https://user-images.githubusercontent.com/41840203/148689162-a6e150a7-1757-48a3-a485-56cb65cf2572.png)

### Additional context

When accessing the website via unsecured channel everything is loading normally but I have to disable the SSL for the whole website which I don't want.

I know that this helper function is giving us the links to the assets and I tried to resolve the problem via this but I was unable to get the desired result as no CSS and JS were loaded as MIME types were not assigned to them with my method.

`if (!function_exists('voyager_asset')) {
    function voyager_asset($path, $secure = null)
    {
        return route('voyager.voyager_assets').'?path='.urlencode($path);
    }
}`

**Comment by itsvasugrover** [comment]
Forcing URL to HTTPS in AppServiceProvider resolved the issue.

```
        if($this->app->environment('production')) {
            \URL::forceScheme('https');
        }
```

**Comment by fletch3555** [comment]
This is usually because laravel isn't seeing an HTTPS request.  Many reasons for that, but they all boil down to TLS terminating early (i.e. at cloudflare or similar) and not having trusted proxy configured properly
