### ISSUE TITLE
Unable to find file

### ISSUE THREAD

**Issue by zarasfara** [thedevdojo/voyager#5518]
### Laravel version

8.79.0

### PHP version

8.0

### Voyager version

1.5

### Database

5.7.33

### Description

Hello everyone. I deployed the project from github. When uploading a photo, it gives me an error "Unable to find file ()."  What to do? Everything works fine locally.

### Steps to reproduce

git clone from github

### Expected behavior

 Must upload photo

### Screenshots

![image](https://user-images.githubusercontent.com/85435988/151119483-f6f9c1a4-5cd2-4cf6-b057-683599f4b774.png)

**Comment by jcalistop** [comment]
I have a same problem.

**Comment by howdu** [comment]
Can only see part of the backtrace. How are you uploading the photo? Bread or media manager.

Also check folder write permissions: /storage/app/public

**Comment by mragwa** [comment]
did you find a solution I've a same problem
