### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by sahmadreza** [thedevdojo/voyager#5523]
### Laravel version

9.0

### PHP version

8.1.0

### Voyager version

1.5

### Description of problem

It is not possible to install on Laravel 9.

![image](https://user-images.githubusercontent.com/56578605/153446662-a3c98a4d-f8f8-4654-98a3-90a3208b3d85.png)

### Proposed solution

Laravel 9 support

**Comment by emptynick** [comment]
Already in the making here: https://github.com/the-control-group/voyager/tree/1.5-l9

**Comment by sahmadreza** [comment]
> Already in the making here: https://github.com/the-control-group/voyager/tree/1.5-l9

I installed this version. 

But now this error showed

```php
Class "League\Flysystem\Util" not found

TCG\Voyager\Http\Controllers\VoyagerController::assets
\vendor\tcg\voyager\src\Http\Controllers\VoyagerController.php
:86
```

```php

    public function assets(Request $request)

    {

            try {

Line 86  =>      $path = dirname(__DIR__, 3).'/publishable/assets/'.Util::normalizeRelativePath(urldecode($request->path));

                } catch (\LogicException $e) {
                     abort(404);
                }

```
https://flareapp.io/share/x7XYzqO5#share

**Comment by benja2111** [comment]
Create a laravel project with a old version.... 

Step 1 : "composer create-project laravel/laravel projet "8.*"
Step 2 : "composer require tcg/voyager"

Let's gooo !

**Comment by shellcod3** [comment]
> Create a laravel project with a old version....
> 
> Step 1 : "composer create-project laravel/laravel projet "8.*" Step 2 : "composer require tcg/voyager"
> 
> Let's gooo !

he talked about version 9 support. you say download version 8. are you stupid?

**Comment by yogesh-jgu** [comment]
> Already in the making here: https://github.com/the-control-group/voyager/tree/1.5-l9

when will it launch officially? I am a big fan of voyager and want to use it along with Laravel 9.
