### ISSUE TITLE
Accessors in model have influence to admin area BREAD fields

### ISSUE THREAD

**Issue by vobar** [thedevdojo/voyager#5555]
### Laravel version

> 8.x

### PHP version

> 7.4

### Voyager version

> 1.5

### Database

MariaDB

### Description

Accessors in model have influence to admin area BREAD fields

### Steps to reproduce

Accessors in model have influence to admin area BREAD fields
```
class Floor extends Model
{
    /**
     * Get the floor map file.
     *
     * @return \Illuminate\Database\Eloquent\Casts\Attribute
     */
    protected function file(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => '/svg/maps/'.$value,
        );
    }
}
```
![Screenshot_1](https://user-images.githubusercontent.com/4314201/159012444-322a8ad4-4f7b-4173-933c-09645d8e6f85.png)
![Screenshot_2](https://user-images.githubusercontent.com/4314201/159012479-c1958db8-d30e-4ce7-80a2-13058f42d187.png)
![Screenshot_3](https://user-images.githubusercontent.com/4314201/159012489-d155f884-e3fe-4b34-9ad7-0a29e5ee94e4.png)

### Expected behavior

Accessors do not crash admin bread?

**Comment by emptynick** [comment]
That is exactly what an accessor is made for and Voyager doesn't have any chance to bypass that behaviour.

**Comment by vobar** [comment]
Oh, thank's a lot! I need another way to do it =)
