### ISSUE TITLE
Missing translation 'contains' in browse.blade.php

### ISSUE THREAD

**Issue by toto975** [thedevdojo/voyager#5588]
### Laravel version

9

### PHP version

8.1.4

### Voyager version

1.6.x-dev

### Database

MySQL 8.0.28

### Description

Missing translation in browse.blade.php, in the select filter

### Steps to reproduce

Navigate to a bread

### Expected behavior

Display the translation of the word 'contains'

### Screenshots

![image](https://user-images.githubusercontent.com/104444110/165323464-189df36d-f400-4b8a-8773-30f0cd7b9d12.png)

### Additional context

In browse.blade.php, i changed
`<option value="contains" @if($search->filter == "contains") selected @endif>contains</option>`
by
`<option value="contains" @if($search->filter == "contains") selected @endif>{{ __('voyager::generic.contains') }}</option>`

And i had in the generic.php lang file
`	'contains'				 => 'contient',`

**Comment by emptynick** [comment]
We are open for PRs.
