### ISSUE TITLE
Create tags on the fly

### ISSUE THREAD

**Issue by BenjaminPiscart** [thedevdojo/voyager#5591]
### Laravel version

8.2.2

### PHP version

7.4

### Voyager version

1.2

### Description of problem

Is there a way to create on the fly, new tags when using a relationship "many-to-many" form field ?
I mean, I'm editing an object and adding exiting tags on it, but it the tag do not already exist, I got an error and it do not create a new tag and link it to the current object.

Screenshot: https://drive.google.com/file/d/1D4-lVUN5YN8zBJMUkr9wJaSC00WFH5YT/view?usp=sharing

### Proposed solution

Is there a way to create on the fly, new tags when using a relationship "many-to-many" form field ?
I mean, I'm editing an object and adding exiting tags on it, but it the tag do not already exist, I got an error and it do not create a new tag and link it to the current object.

Screenshot: https://drive.google.com/file/d/1D4-lVUN5YN8zBJMUkr9wJaSC00WFH5YT/view?usp=sharing

**Comment by emptynick** [comment]
Please ask questions in our Slack group.
Also, you'll find the answer in our documentation
