### ISSUE TITLE
Media library does not display folders while accessing it in CRUD view

### ISSUE THREAD

**Issue by toto975** [thedevdojo/voyager#5621]
### Laravel version

9.x

### PHP version

8.4.1

### Voyager version

1.5

### Database

MySQL 8.0.28

### Description

I think this bug https://github.com/the-control-group/voyager/issues/4774 is not resolved.

### Steps to reproduce

Here is the folder on the disk for the 'actualites' model :
![image](https://user-images.githubusercontent.com/104444110/175960495-a9b40f12-7adf-4bc9-9b67-62df66371f29.png)

In the media library, no problem, all folders and files are displayed
![image](https://user-images.githubusercontent.com/104444110/175960889-9f924693-3b72-4c17-9149-04fe361144b1.png)

But when i want to create a 'Actualite', only files appear in the media picker
![image](https://user-images.githubusercontent.com/104444110/175961281-c65e80f0-9b53-4c56-bf13-a70641bf6565.png)

### Expected behavior

Folders must appear in the media picker when creating/updating a model.

### Screenshots

When i check the json datas for media library and media picker, it's the same.
The files and folders are here

![image](https://user-images.githubusercontent.com/104444110/175962128-317902d7-c3db-4076-b460-7d0b1323aa26.png)

![image](https://user-images.githubusercontent.com/104444110/175962229-f645f8a3-8978-4c71-9313-7732766c7a1b.png)

So some problem for media picker in some javascript ?

**Comment by emptynick** [comment]
There's an option `show_folders` which the docs say is default `true` but from what I'm seeing its default `false`.
Try to set that to `true`.

**Comment by toto975** [comment]
It's already set to true
![image](https://user-images.githubusercontent.com/104444110/175964029-dbc75403-0c63-4ae3-a743-e59b90cd05aa.png)

If i set it to false, no folders appear in the media library and in the media picker.

**Comment by toto975** [comment]
In the media library browser source code, there is this tag :

```
<div id="filemanager">
                    <media-manager
                        base-path="/"
                        :show-folders="true"
                        :allow-upload="true"
                        :allow-move="true"
                        :allow-delete="true"
                        :allow-create-folder="true"
                        :allow-rename="true"
                        :allow-crop="true"
                        :details="{&quot;thumbnails&quot;:[],&quot;watermark&quot;:{}}"
                        ></media-manager>
                </div>
```
which is used by
```
<script>
    Vue.component('media-manager', {
        template: `<div>
...
```

In the the create/update view of a model with a media picker, this tag doesn' appear.

**Comment by emptynick** [comment]
You are mixing media manager and media picker here.
While both use the same views and JavaScript they can be configured independent.
Check the docs for the media picker

**Comment by toto975** [comment]
Thank you emptynick
I hadn't understood that it was necessary to put the parameters in the optional details of the media picker in the bread.

![image](https://user-images.githubusercontent.com/104444110/176147145-83137b3c-d5e7-43a6-b2af-5bab8b9c16fa.png)
