### ISSUE TITLE
invalid table name to query when using an underscore (`_`)

### ISSUE THREAD

**Issue by lamualfa** [thedevdojo/voyager#5630]
### Laravel version

9.18.0

### PHP version

8.1.7

### Voyager version

1.5

### Database

MYSQL 8.0

### Description

why voyager convert the table name from `bersama_point_section_3s` into `bersama_point_section3s`? in the bread settings, i've set the table name field to `bersama_point_section_3s`. voyager remove the underscore character before `3s`.

![image](https://user-images.githubusercontent.com/39755201/178112767-a3678660-c6e9-4f53-8054-ddfad7d2d7a6.png)

### Steps to reproduce

1. create a migration called `bersama_point_section_3s`.
2. create a model with the name `BersamaPointSection3`.
3. create a bread and then make sure the table name field is filled with `bersama_point_section_3s`. by default you don't need to change anything.
4. visit the bread page.
5. you'll get the table not found error because the voyager querying an invalid table name. voyager remove the underscore character from your table name. voyager will generate the table name for you.

### Expected behavior

- bread with a not dependent table name to another field except table name. 
- prevent voyager from parsing, sanitizing, or processing the table name field. like removing the underscore character from my table name.

### Screenshots

# bread settings
![image](https://user-images.githubusercontent.com/39755201/178112662-2e32fabf-9b78-4457-996a-bf1d6f30601a.png)

# the bread's data in table `data_types`
![image](https://user-images.githubusercontent.com/39755201/178112706-36b7c0df-04ce-4d43-bc4f-594b7d1fc7ec.png)

# the bread's menu item
![image](https://user-images.githubusercontent.com/39755201/178112736-70ded724-29b5-4a13-b931-6f913efbd0f9.png)

# table migration
![image](https://user-images.githubusercontent.com/39755201/178112856-6313619c-e2e8-4abf-9291-cf21cb5e9d79.png)

**Comment by emptynick** [comment]
Thats not Voyager.
Thats Laravel "guessing" the table name. See [here](https://laravel.com/docs/9.x/eloquent#table-names)

**Comment by lamualfa** [comment]
@emptynick ok thanks.
