### ISSUE TITLE
Add an option to provide a default value for the Media Picker formfield

### ISSUE THREAD

**Issue by christie-hill-za** [thedevdojo/voyager#5640]
### Laravel version

9.0

### PHP version

8.0.2

### Voyager version

1.5.2

### Description of problem

I would like to specify a default value for an instance of the media picker formfield in one of my models and there currently doesn't seem to be an option for it according to the [documentation page](https://voyager-docs.devdojo.com/bread/introduction-1/media-picker).

Some other fields have this option available in their BREAD configuration.

### Proposed solution

Add another customisation option to the BREAD settings for the Media Picker field that allows a default value to be specified.
`{
    "default": "path/to/default.jpg"
}`

### Alternatives considered

Don't set the field to required in the database settings and allow NULL. I will try to work on a PR for this in my spare time.

### Additional context

This setting does not seem to work with the Media Picker field.

![Screenshot 2022-07-25 at 12-40-04 Edit BREAD for posts table](https://user-images.githubusercontent.com/83393649/180758545-cbe69eb3-7ffa-4426-8d7d-0fe054222f8d.png)

**Comment by emptynick** [comment]
Use a BREAD accessor (for add in your case) to provide a default value.
I think putting a static path into the json options isn't really a good idea.
With the accessor you are able to do some more dynamic things.
