### ISSUE TITLE
Reading Exif data is not supported by this PHP installation.

### ISSUE THREAD

**Issue by Gemy8** [thedevdojo/voyager#5647]
### Laravel version

9.19.0

### PHP version

8.0.21

### Voyager version

1.6

### Database

mysql 8 

### Description

when i upload any photo using media manger or uploading any photo on sitting i got this error (Reading Exif data is not supported by this PHP installation.)

### Steps to reproduce

.

### Expected behavior

i think the voyager admin panel using extension exif and it missing 

### Screenshots
![1](https://user-images.githubusercontent.com/110743108/183264759-fe450e78-78a2-4bce-ac90-2a06b3c6dca7.JPG)
![2](https://user-images.githubusercontent.com/110743108/183264760-bf35fad7-930e-4675-bba3-296860bb4801.JPG)

**Comment by fletch3555** [comment]
You need to install/enable the appropriate php extension on your server.  I don't remember offhand if it's literally exif or imagegd or something else, but should be easily google-able

**Comment by emptynick** [comment]
You are missing the Fileinfo PHP extension which is required by Laravel: https://laravel.com/docs/9.x/deployment#server-requirements
