### ISSUE TITLE
Relationship result sorting

### ISSUE THREAD

**Issue by toto975** [thedevdojo/voyager#5648]
### Laravel version

9.7.0

### PHP version

8.1.4

### Voyager version

1.5

### Database

8.0.28

### Description

In a select dropdown relationship, datas are not sorting as defined in the sort option of the relationship

### Steps to reproduce

My Model : Parcours belongsto Cadre, with a sort on the name
![image](https://user-images.githubusercontent.com/104444110/207288212-f498f409-ea3a-46d7-99c2-531ebcfae661.png)

When adding a Parcour, the select dropdown loads datas 50 by 50
(I show the json results)
Page 1
![image](https://user-images.githubusercontent.com/104444110/183392391-5b712a9c-b7df-48e6-8a09-42453f25b099.png)
Page 2
![image](https://user-images.githubusercontent.com/104444110/183392751-16b102b8-f80b-45da-b424-cf571bdef575.png)
Page 3
![image](https://user-images.githubusercontent.com/104444110/183392817-d82c3b8f-6b47-4170-92fe-d7b835231965.png)

It seems that datas are sorted by id, then by name for Page 1 and 2
By name then by id on page 3.

### Expected behavior

The relation datas must be sorted by 'name' first, then take/limit and skip/offset.

In voyagerBaseController->relation, some changes since this fixe https://github.com/the-control-group/voyager/pull/4858 to include sorting
But sorting is done after take/limit and skip/offset.

For sample, line 928
`$relationshipOptions = $model->take($on_page)->skip($skip)->get();`
and line 945
`$relationshipOptions = $relationshipOptions->sortBy($options->sort->field);`

I tried
`$relationshipOptions = $model->get()->sortBy($options->sort->field)->take($on_page)->skip($skip);`

It's OK for Page 1, the first 50 datas are sorted by name, but next pages are empty.

I think there is some changes to do between line 911 and 947.

**Comment by ben-cheng565** [comment]
@toto975 Can I try to work this issue out?

**Comment by toto975** [comment]
Certainly you can
Great if you find the fix.

**Comment by toto975** [comment]
It's fixed with https://github.com/the-control-group/voyager/pull/5695
