### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by robertgdev** [thedevdojo/voyager#5658]
### Laravel version

9

### PHP version

8.1.2

### Voyager version

1.5.2

### Description of problem

The highest PHP version which composer.json supports is 8.0. Please add support for PHP 8.1

### Proposed solution

Update composer.json, make sure code still works with PHP 8.1

**Comment by phpmac** [comment]
pk http://www.dcatadmin.com/

**Comment by emptynick** [comment]
PHP 8.1 is now supported in version 1.6.0
