### ISSUE TITLE
https://voyager-cheatsheet.ulties.com/ ssl expired

### ISSUE THREAD

**Issue by phpmac** [thedevdojo/voyager#5664]
### Laravel version

9

### PHP version

8

### Voyager version

2

### Database

8

### Description

https://voyager-cheatsheet.ulties.com/ ssl expired

### Steps to reproduce

https://voyager-cheatsheet.ulties.com/ ssl expired

### Expected behavior

https://voyager-cheatsheet.ulties.com/ ssl expired

**Comment by howdu** [comment]
Contact them directly https://ulties.com/contact

**Comment by fletch3555** [comment]
@howdu is correct.  We don't own nor control that site.
