### ISSUE TITLE
Tablespace for table permission_role exists general error 1813

### ISSUE THREAD

**Issue by doubleprincez** [thedevdojo/voyager#5666]
### Laravel version

8.75

### PHP version

8.0

### Voyager version

^1.5

### Database

MySQL 8.

### Description

I just created a new project now and Voyager is the first package I installed so there is no way this can be an issue with another package. I will like to know what this error signifies when I ran ``` php artisan voyager:install --with-dummy ``` on a fresh installation

```  SQLSTATE[HY000]: General error: 1813 Tablespace for table '`laravel_app`.`permission_rol
e`' exists. Please DISCARD the tablespace before IMPORT (SQL: create table `permission_role` (
`permission_id` bigint unsigned not null, `role_id` bigint unsigned not null) default characte
r set utf8mb4 collate 'utf8mb4_unicode_ci') ```

### Steps to reproduce

-Create a fresh laravel project using ``` composer create-project laravel/laravel laravel_soontec_latest --prefer-dist 8 ```
-Install this packages by running  ``` composer require cyrildewit/eloquent-viewable dougsisk/laravel-country-state jorenvanhocht/laravel-share rtconner/laravel-likeable spatie/laravel-cookie-consent  spatie/laravel-sluggable ```  without configuring any of them.
-Configure your database connection in your .env
-Install voyager by simply running  ```composer require tcg/voyager```
-Run this command  ```php artisan voyager:install --with-dummy```

### Expected behavior

All migration table to be installed successfully and demo records created

### Screenshots

![Fullscreen capture 8292022 64417 PM bmp](https://user-images.githubusercontent.com/37469720/187252733-06f7729f-d38c-4161-8233-ecd7f9bc68d1.jpg)

**Comment by fletch3555** [comment]
I'm honestly not sure what caused you to get into that state, but there's nothing in Voyager that should be able to do that.  Voyager runs in Laravel, and as such uses Laravel's mysql driver (or whichever other package such functionality gets pulled in from as a dependency of Laravel).

That said, here's a StackOverflow post talking about the same issue and some possible solutions: https://stackoverflow.com/questions/15694168/error-tablespace-for-table-xxx-exists-please-discard-the-tablespace-before-imp

**Comment by doubleprincez** [comment]
I got it working by removing the table space from [https://unix.stackexchange.com/questions/212808/how-can-i-fully-remove-a-tablespace-from-mysql](Mysql database table.ibd file). Thank you.
