### ISSUE TITLE
Alerts Not Working

### ISSUE THREAD

**Issue by ahmetsmc** [thedevdojo/voyager#5669]
### Laravel version

9.18.0

### PHP version

8.1.4

### Voyager version

1.6.x-dev

### Database

5.7.39

### Description

I dont change any voyager settings but alerts not showing.

For example when the wrong password in login, successful message after create or other all alerts not showing.No this problem in different voyager project on same server. Why might this be happening?

- checked server session config
- tried reinstalling
- checked lang files

### Steps to reproduce

.

### Expected behavior

.

**Comment by Loukili-Rachid** [comment]
same pblm
also validation session

**Comment by howdu** [comment]
1. Do alert messages work ok elsewhere? E.g saving a standard Voyager form.

2. Have you upgraded from previous Laravel version? 
Check `app/Http/Kernel.php` that your $middlewareGroups contains StartSession::class AND ShareErrorsFromSession::class for 'web'.

3. Try install laravel-debugbar to see if the session message is being added ok.
https://github.com/barryvdh/laravel-debugbar
