### ISSUE TITLE
Undefined variable: dataTypeContent (View: C:\wamp\www\.....\edit-add.blade.php) when adding new record in a newly created table/bread.

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#567]
Voyager version: 0.10.9
Laravel Version: 5.3

When adding new record in a newly created table/bread.

![slides create](https://cloud.githubusercontent.com/assets/8501654/21955595/282ef79a-da77-11e6-8d94-09ee24c46fc0.png)

**Comment by marktopper** [comment]
Please remember to add version of Voyager and Laravel when creating an issue.

**Comment by hazem1taha** [comment]
@marktopper Sorry, I missed it, Done.

**Comment by marktopper** [comment]
Can you try get version `dev-master` and test it there?

**Comment by hazem1taha** [comment]
I tried it now but the problem still exists.

    "require": {
      "php": ">=5.6.4",
      "laravel/framework": "5.3.*",
      "tcg/voyager": "dev-master"
    },

**Comment by hazem1taha** [comment]
In addition to that there still some updates not added yet to the system for example the `parent_id` of the category is still text input not a dropdown select element.

![as21d](https://cloud.githubusercontent.com/assets/8501654/21956355/a805a1f2-da87-11e6-96c5-de9a38fe30a5.png)

**Comment by marktopper** [comment]
Just created a branch with a possible fix for your issue, can you try `dev-fix/567`?

**Comment by marktopper** [comment]
And in order to get that to show as a dropdown, you must set some additional JSON options for that BREAD field.

Try this json
```
{
    "default": "__null__",
    "null": "__null__",
    "options": {
        "__null__": "NULL"
    },
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
```

**Comment by antranapp** [comment]
or create a fresh installation
or remove all voyager database migration and run voyager:install again. (the migrations are copied from vendor folder to database folder)

**Comment by hazem1taha** [comment]
Thanks @marktopper 

I used that branch `dev-fix/567` and tried again but nothing changed.

**Comment by hazem1taha** [comment]
@peacemoon 
I'm already using the package with a fresh laravel installation.
Anyway I'll rerun the migrations and let you know if it solved the problem.

**Comment by marktopper** [comment]
Can you please send the content of the cached view that you can see in the exception?

**Comment by hazem1taha** [comment]
Here it is:

[Cached view contents](http://pastebin.com/cKe5XNSy)

**Comment by marktopper** [comment]
Seems like it could be an issue that is specific when using the `datetime` type.
```
<input type="datetime" class="form-control datepicker" name="<?php echo e($row->field); ?>" value="<?php echo e(gmdate('m/d/Y g:i A', strtotime($dataTypeContent->{$row->field}))); ?>">
```

Will try it out later, just on my way out for a birthday.

**Comment by hazem1taha** [comment]
@marktopper 

It is related to the `deleted_at` column, when I unchecked its `browse/edit/create/delete` checkboxes, the problem has gone.

Enjoy ur time.

**Comment by marktopper** [comment]
Pull #590 should have done the trick.

Tagging a new release later today.
