### ISSUE TITLE
Error 500 when make new BREAD

### ISSUE THREAD

**Issue by MuhhalimR** [thedevdojo/voyager#5691]
### Laravel version

8

### PHP version

8.1.10

### Voyager version

1.6

### Database

mysqlnd 8.1.10

### Description

When i make a new bread, it come out error with 500.

### Steps to reproduce

1. Make a new database
2.  Create bread
3. View in sidebar nav

### Expected behavior

Can use the view.

### Screenshots

<img width="959" alt="image" src="https://user-images.githubusercontent.com/61299752/201565583-bf075e9e-38b6-4757-8bc6-f0d191b88408.png">
<img width="960" alt="image" src="https://user-images.githubusercontent.com/61299752/201565989-0126e2a0-eb15-4ba3-ac30-6a46007cb18d.png">

this is after i create the bread.

**Comment by mtsakharov** [comment]
did you add your model in bread ?
