### ISSUE TITLE
Voyager wih the Laravel Telescope (Laravel Eco system, not only the Telescope)

### ISSUE THREAD

**Issue by lotjib** [thedevdojo/voyager#5693]
### Laravel version

9.40.1

### PHP version

 8.0.13

### Voyager version

1.6

### Description of problem

In the fresh project, when you install "tcg/voyager": "^1.6" & "laravel/telescope": "^4.9", your User model have extends \TCG\Voyager\Models\User, and the Telescope not work with it and show error. If you change to 'User' extends 'Authenticatable', the Telescope work, but Voyager not work :) It would be cool if you can do something with the model so that it works just

### Proposed solution

I wanted the 'tcg/voyager' to work with the 'laravel/telescope' and other laravel eco products immediately after installation. Thx!

**Comment by fletch3555** [comment]
Please describe the problem you're having, ideally with any error messages you see and where.  It may be easier to join our slack group to discuss further

**Comment by lotjib** [comment]
> Please describe the problem you're having, ideally with any error messages you see and where. It may be easier to join our slack group to discuss further

![image](https://user-images.githubusercontent.com/22413515/203018764-fe03add8-41ad-43f0-8413-8219f1f10149.png)
Telescope and all eco laravel system use auth gate
If User (model) extends Authenticatable is ok, and no errors, but Voyager is not work.
If User (model) extends '\TCG\Voyager\Models\User' - Voyager model, we have this error
![image](https://user-images.githubusercontent.com/22413515/203021357-d74e2c0e-7b28-4ae3-ad8c-fb59d5674362.png)
![image](https://user-images.githubusercontent.com/22413515/203021545-0cdef5af-c690-4260-8a9d-b8ac85aa81c7.png)

**Comment by fletch3555** [comment]
If you go through the entire Voyager install process (including leaving the user model extending the Voyager User class), and THEN change it to Authenticatable, there's no way this would be the error you get.  This looks like you're trying to install Voyager with the User class already changed to something else.

The Voyager User model extends Authenticatable anyway, so it really shouldn't matter unless Telescope requires that you extend from some other class (which AFAIK it doesn't).  In which case, you can just manually configure your User model to match what the Voyager User model is doing for you. https://github.com/the-control-group/voyager/blob/1.6/src/Models/User.php#L12

You'll have to troubleshoot further because this isn't the issue you think it is.  Make sure you go through the entire Voyager install process and THEN install telescope (or vice versa), don't try to install them in parallel.

**Comment by lotjib** [comment]
> If you go through the entire Voyager install process (including leaving the user model extending the Voyager User class), and THEN change it to Authenticatable, there's no way this would be the error you get. This looks like you're trying to install Voyager with the User class already changed to something else.
> 
> The Voyager User model extends Authenticatable anyway, so it really shouldn't matter unless Telescope requires that you extend from some other class (which AFAIK it doesn't). In which case, you can just manually configure your User model to match what the Voyager User model is doing for you. https://github.com/the-control-group/voyager/blob/1.6/src/Models/User.php#L12
> 
> You'll have to troubleshoot further because this isn't the issue you think it is. Make sure you go through the entire Voyager install process and THEN install telescope (or vice versa), don't try to install them in parallel.

Voyager work perfectly and I have installed it many times, and this time it is installed completely. And it was installed first!
Yeah i know, when Voyager User model extends Authenticatable, but other models, used in this model (on screenshot), methods get error :(
![image](https://user-images.githubusercontent.com/22413515/203053406-076ebdcc-728f-4dee-bfdb-3ee990fabf6d.png)
In any case, I will try to somehow solve this problem and write it off here.

**Comment by fletch3555** [comment]
Again, you're welcome go join our slack group for more assistance troubleshooting.

**Comment by lotjib** [comment]
> Again, you're welcome go join our slack group for more assistance troubleshooting.

Thank you! Someday I will join, unfortunately I can’t yet due to sanctions

**Comment by lotjib** [comment]
> Again, you're welcome go join our slack group for more assistance troubleshooting.

Ok, i fix this. I update the laravel user model as screenshot
![image](https://user-images.githubusercontent.com/22413515/203057145-f43de885-f3fb-45b7-8259-91dc4081914f.png)
Voyager work perfectly
![image](https://user-images.githubusercontent.com/22413515/203057526-ec527464-afcc-455f-85cf-5f6f0db8afe4.png)
Telescope work perfectly
![image](https://user-images.githubusercontent.com/22413515/203057667-0a714bc8-fd47-4113-8257-96a90c52a1be.png)
Horizon work perfectly (redis is offline :D)
![image](https://user-images.githubusercontent.com/22413515/203058338-7efc66c2-44a3-454c-b221-fab59a3a0e3d.png)

maybe add this manual to the instructions so that it works fine?)?)
