### ISSUE TITLE
Is there a way to install voyager without migrating tables?

### ISSUE THREAD

**Issue by Mugluck** [thedevdojo/voyager#57]
Yo, your admin looks awesome! One problem, I've already got a users table and what have you, so how do I integrate this with an existing structure. Starting from blank is not an option.

**Comment by afsardo** [comment]
I think what you should do is `vendor:publish` and remove the voyager `create_users_table` migration.

After that you can `artisan migrate` and `artisan db:seed`, if i'm not mistaken you are good to go ;)

**Comment by Mugluck** [comment]
Yeah, I that's a viable workaround. :)

**Comment by marktopper** [comment]
I'm wondering, why do you need to do this?

**Comment by fletch3555** [comment]
@marktopper. Not sure if you commented in the wrong issue or what, but I'll answer anyway.  For the reasons discussed in #58

**Comment by marktopper** [comment]
@fletch3555, was just wondering if @Mugluck had other reasons which we could think about when finding the _"perfect"_ solution 😄

**Comment by fletch3555** [comment]
Closing as #58 was merged in.

**Comment by marktopper** [comment]
Released in `v0.9.32`.
