### ISSUE TITLE
The command "voyager:install" does not exist.

### ISSUE THREAD

**Issue by elmarzouguidev** [thedevdojo/voyager#5721]
### Laravel version

9.46.0

### PHP version

8.1

### Voyager version

1.6

### Database

7

### Description

when i call voyager:install from Artisan facade like : 

`        public function voyagerInstall(bool $withDummy = false)
    {

        Artisan::call('voyager:install', [
            '--with-dummy' =>  $withDummy,
        ]);
    }`

it's throw this exception : 
`
Symfony
 \ 
Component
 \ 
Console
 \ 
Exception
 \ 
CommandNotFoundException
The command "voyager:install" does not exist.
`

### Steps to reproduce

no solution

### Expected behavior

no

### Screenshots

no

### Additional context

no

**Comment by rahat1994** [comment]
can you elaborate more on your problem? was it working on previous versions of Laravel?

Because Voyager is registering its commands only when the app is running in the console. in `VoyagerServiceProvider` 

```
        if ($this->app->runningInConsole()) {
            $this->registerPublishableResources();
            $this->registerConsoleCommands();
        }
```

you can easily run this command programmatically by including the command in the file: `app/Console/Kernel.php`

```
    protected $commands = [
        \TCG\Voyager\Commands\InstallCommand::class
    ];
```

**Comment by elmarzouguidev** [comment]
> can you elaborate more on your problem? was it working on previous versions of Laravel?
> 
> Because Voyager is registering its commands only when the app is running in the console. in `VoyagerServiceProvider`
> 
> ```
>         if ($this->app->runningInConsole()) {
>             $this->registerPublishableResources();
>             $this->registerConsoleCommands();
>         }
> ```
> 
> you can easily run this command programmatically by including the command in the file: `app/Console/Kernel.php`
> 
> ```
>     protected $commands = [
>         \TCG\Voyager\Commands\InstallCommand::class
>     ];
> ```

thanks brother
