### ISSUE TITLE
do not query 'select * from data_types' in api route.

### ISSUE THREAD

**Issue by devwithu** [thedevdojo/voyager#5723]
### Laravel version

8.83.27

### PHP version

 7.4.33

### Voyager version

1.6.0

### Description of problem

I have a site with high traffic in api call. 
I used voyager to manage admin contents. 
but I noticed that its running a single query more than millions of times in my api call. 
the query is select * from data_types

I want to do not query select * from data_types in my api route.

Please suggest how can I solve the issue.

i read #3396 , #5244. 

### Proposed solution

I want to do not query select * from data_types in my api route.

Please suggest how can I solve the issue.

i read #3396 , #5244. 

maybe cache,
or do not process some voyager logic(select * from data_types) for api route.

**Comment by devwithu** [comment]
vendor/tcg/voyager/routes/voyager.php
maybe this line 39. ....  foreach (Voyager::model('DataType')::all() as $dataType) {

**Comment by devwithu** [comment]
web.php
if(Str::contains(Request::getPathInfo(), '/admin')){
    Route::group(['prefix' => 'admin'], function () {
        Voyager::routes();
    });
}

and fix the problem. 
and now  do not  query 'select * from data_types' in api route

**Comment by fletch3555** [comment]
You should be caching your routes in a production environment, which would prevent that call from happening

**Comment by devwithu** [comment]
wow.  thank you very much @fletch3555 .
i didn't know about cache route.
i will study this.

https://laravel.com/docs/9.x/routing#route-caching
https://stackoverflow.com/questions/37878951/how-to-clear-laravel-route-caching-on-server

have a nice day.
