### ISSUE TITLE
error loading images and avatar

### ISSUE THREAD

**Issue by Marwahanem** [thedevdojo/voyager#5725]
### Laravel version

8

### PHP version

7

### Voyager version

1.4

### Database

8

### Description

i have some issues ,the avatar and all images didn't appear 
this screenshots to my code please check it and tell me how to solve it!!
https://prnt.sc/fZldMUQ4q3uI
https://prnt.sc/nXOJMbsS8BZQ

### Steps to reproduce

-

### Expected behavior

-

**Comment by jcalistop** [comment]
Try this:

1. Check your site in the .env file (http or https is important):
`APP_URL=https://yoursite.com`

2. Delete public/storage directory and re-create with this:
`php artisan storage:link`
(It is available in menu -> Compass -> Command)

Bye

**Comment by Marwahanem** [comment]
Thanks for your reply
the link of the site in the .env not correct , i change it and work
thank you so much
