### ISSUE TITLE
Invalid datetime format: 1292 Incorrect datetime value

### ISSUE THREAD

**Issue by Archakov06** [thedevdojo/voyager#573]
- Laravel Version: 5.3
- Voyager Version: 0.10
- PHP Version: 5.6.7
- Database Driver & Version: mysql

### Description:
If i update post in admin panel: http://site.dev/admin/posts/5

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' at row 1 (SQL: update `posts` set `category_id` = 2, `excerpt` = test , `meta_description` = , `meta_keywords` = 1970-01-01 00:00:00, `created_at` = 1970-01-01 00:00:00, `updated_at` = 5 where `id` = ?)

**Comment by fletch3555** [comment]
Please update your issue to include the full Voyager version.  There have been significant bugfixes between just 0.10.7 and 0.10.10(current).  If not on 0.10.10, please run `composer update` as well.
