### ISSUE TITLE
Deprecation warning for json_decode() for MenutItem model

### ISSUE THREAD

**Issue by marcomertenslv** [thedevdojo/voyager#5737]
### Laravel version

9.52.0

### PHP version

8.2.3

### Voyager version

1.6.0

### Database

MySQL 8.0

### Description

json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in ... vendor/tcg/voyager/src/Models/MenuItem.php on line 93

### Steps to reproduce

Setup voyager with Laravel 9, Valet and PHP 8.2. Have a look at tail -f storage/logs/php-deprecation-warnings.log 

### Expected behavior

The log file should contain deprecation warnings

**Comment by guilhermebillig** [comment]
Same problem here

**Comment by u01jmg3** [comment]
Dupe of #5603
