### ISSUE TITLE
storage path in localhost

### ISSUE THREAD

**Issue by mohammad6006** [thedevdojo/voyager#574]
my laravel is udner sub directory
`localhost:8080/subfolder/public`

I changed `assets_path` from `config/voyager.php` and asset problem solved 
but I cant address sub directory for storage folder
in `config/voyager.php` I changed subfolder but address is `localhost:8080/storage/subfolder`

I need to address subfolder before storage like this : `localhost:8080/subfolder/storage`

what should i do?
I use latest version of voyager and my localhost created by wampserver

**Comment by marktopper** [comment]
Change the subfolder for storage to `public`, then visit `localhost:8080/subfolder/public/storage`.

If that does not work, ensure that a symlink have been created.
You can run `php artisan storage:link` to create it.
