### ISSUE TITLE
Many-to-many fields show empty when browsing

### ISSUE THREAD

**Issue by antranapp** [thedevdojo/voyager#577]
- Laravel Version: 5.3.0
- Voyager Version: 0.10.10
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.7

### Description:
Considering theses database tables
product:
   - id: int
   - name: string
   - features: text // this needs to be added so that select_multiple field can be added to BREAD view

feature:
   - id: int
   - name: string

feature_product:
   - product_id: int
   - feature_id: int

I add select_multiple field for `feature`field in `product`table like this:
![screen shot 2017-01-15 at 16 54 19](https://cloud.githubusercontent.com/assets/478757/21963983/7a8e0496-db43-11e6-8dde-6d89dd6cac94.png)
In `product` model, I add the relationship to `features`:
````
    public function features()
    {
        return $this->belongsToMany(Feature::class);
    }
````

Now when I add a new `product`, the field `features` will be empty because we don't assign any value to this field while inserting https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L65

Now when we browse the `products` table, we will see that the `features` field will be empty. So this part of code https://github.com/the-control-group/voyager/blob/master/resources/views/bread/browse.blade.php#L38-L40 has no effect.
![screen shot 2017-01-15 at 17 06 47](https://cloud.githubusercontent.com/assets/478757/21964101/2090205c-db46-11e6-9223-f1e6542dbd76.png)

So, we need to investigate the code to show the features field in "browse view" again.

**Comment by fletch3555** [comment]
Closing due to age.  There have been significant changes since v0.10.10.  If this is still an issue after v1.0 is released, please create a new issue.
