### ISSUE TITLE
[BUG] Media Library Cursors Event

### ISSUE THREAD

**Issue by akazorg** [thedevdojo/voyager#580]
If you click to rename an image, and then use the keyboard cursors, the image will change on the background.
This JS popup really requires revision, on the menu it also fail sometimes.

![peek_bug_media 2017-01-16 06-16](https://cloud.githubusercontent.com/assets/34574/21972718/54ef21d2-dbb3-11e6-8a87-c434cd29c835.gif)

**Comment by akazorg** [comment]
Sending fix for this.

**Comment by marktopper** [comment]
Fixed in #588 

/closed
