### ISSUE TITLE
Cannot update a category which already has a parent category to get a no-parent category (parent_id = null)

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#581]
- Laravel Version: 5.3
- Voyager Version: 0.10.10
- PHP Version: 5.6
- Database Driver & Version: MySQL

**Description**:
When updating a category to get a null parent_id instead of a value, it doesn't work and the parent_id is not updated and not set as null.

Here is the content of the options field of the parent_id column in the BREAD

`
{
    "default": "__null__",
    "null": "__null__",
    "options": {
        "__null__": "Main"
    },
    "relationship": {
        "key": "id",
        "label": "name"
    }
}
`

and it is a dropdown input type.

**Steps To Reproduce**:

1. Add a category with a null parent_id.
2. update it to get a parent category.
3. update it to get a null parent_id. 

**Result**:  The update action has no effect  and the category is still with the parent category selected in step 2.

**Comment by antranapp** [comment]
Confirmed this is a bug. 
Anyone understands these 3 lines https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L56-L58 . Why do we set the value of the field back to previous value when the new content is `null`

**Comment by fletch3555** [comment]
I imagine that was done so that fields could be left blank to "not override old values".  Not sure if that has a purpose anymore.

**Comment by antranapp** [comment]
@fletch3555 thanks for pointing me out, will try to get a fix for this issue soon.

**Comment by antranapp** [comment]
@EngHazem can you test this fix https://github.com/the-control-group/voyager/pull/587 again?
