### ISSUE TITLE
Cannot install tcg/voyager dev-1.6-l10

### ISSUE THREAD

**Issue by kriit24** [thedevdojo/voyager#5880]
### Laravel version

v11.23.4

### PHP version

v8.3.11

### Voyager version

dev-1.6-l10

### Database

10.6.18-MariaDB-log

### Description

Cannot install

`Problem 1
    - Root composer.json requires tcg/voyager dev-1.6-l10 -> satisfiable by tcg/voyager[dev-1.6-l10].
    - tcg/voyager dev-1.6-l10 requires illuminate/support ~8.0|~9.0|~10.0 -> found illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but these were not loaded, likely because it conflicts with another require.
`

### Steps to reproduce

composer require --ignore-platform-reqs tcg/voyager dev-1.6-l10

### Expected behavior

to be installed

**Comment by bobbyiliev** [comment]
This happens because the Voyager dev-1.6-l10 is not compatible with Laravel 11.

Closing this issue as there is already a tracker for this here: https://github.com/thedevdojo/voyager/issues/5846
