### ISSUE TITLE
php artisan voyager:admin failes

### ISSUE THREAD

**Issue by kriit24** [thedevdojo/voyager#5881]
### Laravel version

v11.23.4

### PHP version

v8.3.11

### Voyager version

^1.7

### Database

10.6.18-MariaDB-log

### Description

php artisan voyager:admin kuno@projectpartner.ee failed

### Steps to reproduce

php artisan voyager:admin kuno@projectpartner.ee

error:

` Illuminate\Database\Eloquent\ModelNotFoundException 

  No query results for model [App\Models\User].

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:621
    617▕         if (! is_null($model = $this->first($columns))) {
    618▕             return $model;
    619▕         }
    620▕ 
  ➜ 621▕         throw (new ModelNotFoundException)->setModel(get_class($this->model));
    622▕     }
    623▕ 
    624▕     /**
    625▕      * Execute the query and get the first result or call a callback.

      +14 vendor frames 

  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

### Expected behavior

added a admin user

**Comment by bobbyiliev** [comment]
This happens because the Voyager 1.7 is not compatible with Laravel 11.

Closing this issue as there is already a tracker for this here: https://github.com/thedevdojo/voyager/issues/5846
