### ISSUE TITLE
I want to add upload multiple files features, add a new field option

### ISSUE THREAD

**Issue by cloudsben** [thedevdojo/voyager#595]
I wanna add a new field option, Name is Multiple Files, How about it?

![image](https://cloud.githubusercontent.com/assets/1283779/22020860/5ec0afb2-dcf5-11e6-9a5d-5cd36becaba1.png)

**Comment by handiwijoyo** [comment]
Yes, please to do so. You can open a pull request, so we can take a look. :)

**Comment by cloudsben** [comment]
@handiwijoyo Great! I will do it.

**Comment by sarath-c-sandwich** [comment]
@cloudsben  is this for the purpose of Multiple Images upload right?

**Comment by fletch3555** [comment]
Just a heads up, v0.11 includes a change to move the field types into their own view partials.  I strongly recommend making the change after that (create a branch from `release/v0.11`, commit changes, and PR back into `release/v0.11`).

**Comment by cloudsben** [comment]
@uchsarath yes， I'm already doing it.
![image](https://cloud.githubusercontent.com/assets/1283779/22102836/de6bea90-de73-11e6-9b8f-823e39d3a785.png)

**Comment by cloudsben** [comment]
@fletch3555 How can I contribute this project and test my code? Any documents?

**Comment by fletch3555** [comment]
Github has excellent documentation around how to contribute to open source projects.  I suggest reading that.

For this project specifically, you'll want to fork this repository, clone it to your local computer, create a branch to work on (in this case, you'll want to checkout the release/v0.11 branch first), make your changes and commit them, push them back up to github, and make a pull request to get them into this repository.  Then one of the collaborators will review it and add comments.

**Comment by cloudsben** [comment]
@fletch3555  I mean, how can I deploy my rewrite code and test on my local server. if a local test is good, then I can use GitHub flow open pull request.

like HOW TO CONTRIBUTE TO AN EXISTING COMPOSER PACKAGE!

Thanks a lot!

**Comment by fletch3555** [comment]
Unfortunately, I won't be able to help you with your personal development setup.  If you have specific questions, I recommend you join our slack group and ask on the #help channel.

**Comment by cloudsben** [comment]
@fletch3555 OK, Thank you anyway!

**Comment by sarath-c-sandwich** [comment]
@cloudsben I pulled the latest version but still don't know how to use your code. Can you give some instruction on to make it multiple image selections?

**Comment by cloudsben** [comment]
@uchsarath I have merged to version 0.11, but the latest version is 0.10.12 right now!

![image](https://cloud.githubusercontent.com/assets/1283779/22624495/2ff68dec-ebb8-11e6-9158-c84ba0fd6846.png)
