### ISSUE TITLE
How to Display a Voyager Setting in the front-end of site

### ISSUE THREAD

**Issue by psmedia90** [thedevdojo/voyager#597]
- Laravel Version: 5.3.29
- Voyager Version: 0.10.10
- PHP Version: 7
- Database Driver & Version:

### Description:
how to i display a Voyager setting in  a front-end view file of my   ##site

**Comment by fletch3555** [comment]
Our documentation seems to be lacking in that area, but there are numerous examples in Voyager's codebase.  Here's one that should be enough to answer your question: https://github.com/the-control-group/voyager/blob/master/resources/views/master.blade.php#L145

**Comment by psmedia90** [comment]
if you but that in a view that is not a voyager view it will on echo it out it shows nothing in the browser

**Comment by fletch3555** [comment]
That doesn't seem possible (though I'm not able to test it currently).  [Here is the function](https://github.com/the-control-group/voyager/blob/master/src/Voyager.php#L40) that `Voyager::setting()` calls.  Unless you mistype the key of the setting, or it otherwise doesn't exist, it should work perfectly fine.

**Comment by psmedia90** [comment]
what do I put in the blade view to get it to out put

or do i have to put something in my controller

**Comment by fletch3555** [comment]
This will get the value of the setting and store it in `$variable`:
`<?php $variable = Voyager::setting('your-setting-key', 'default-value'); ?>`

Then you just have to use that `$variable` however you need.

**Comment by psmedia90** [comment]
dos this go in the controller -> <?php $variable = Voyager::setting('your-setting-key', 'default-value'); ?>

**Comment by psmedia90** [comment]
`` <?php $variable = Voyager::setting('your-setting-key', 'default-value'); ?> ``

**Comment by fletch3555** [comment]
It can go wherever you need it to go.  If you put it in the controller, then you'll need to pass that value to the view.

Unfortunately, I can't provide any more support on this as we've gotten more into "how to use Laravel", than "how to use Voyager".  If you need further assistance, I recommend joining our slack group's #help channel. Here's the invite link if you're not already on there: https://voyager-slack-invitation.herokuapp.com/

**Comment by psmedia90** [comment]
thank you
 you have out a lot

PSMedia90

**Comment by yelabbassidev** [comment]
{{ setting('settingGroup.settingName') }}

**Comment by fletch3555** [comment]
@yourseft05, this has been closed for nearly 3 years... why?
