### ISSUE TITLE
can't edit fresh BREAD

### ISSUE THREAD

**Issue by kobius77** [thedevdojo/voyager#598]
- Laravel Version: 5.3
- Voyager Version: 0.10.10
- PHP Version: 7.1
- Database Driver & Version:

### Description:
clicking "Edit BREAD" on admin/database on newly created BREADs (which were not preconfigured) throws an error:

ErrorException in Container.php line 749:
Class App\Tablename does not exist (View: /home/alle/code/pos/vendor/tcg/voyager/resources/views/tools/database/edit-add-bread.blade.php)

also i'm getting am UnauthorizedHttpException when trying to access these BREAD-views (admin/Tablename).

### Steps To Reproduce:
just using the voyager frontend like a noob (which i actually am ;)), clicking the colorful buttons not knowing much about the inner workings.

**Comment by fletch3555** [comment]
When you created the BREAD, did you select the option to create the model as well?  If not, you need to manually create the model.

As for the UnauthorizedHttpException, you need to edit the `admin` Role and add rights to it for the new BREAD.

**Comment by kobius77** [comment]
yes, 'create model' was activated, though i didn't check if it actually did so. will do so asap..

(and suspected the authorization-thing would be seperate and i'd just had to rtfm ;))

**Comment by kobius77** [comment]
yes, a model (or a rather empty scaffold i suppose) is created in /app when creating a new table.

but since you ask for this:
it's not only happening for newly created tables. also if i take existing tables (like 'permissons') and 'add bread' i can't use the edit on that later on.

**Comment by fletch3555** [comment]
Closing as inactive.

@drahdiwaberl, if this is still a problem for you, please let me know and I'll reopen it.  Looks like you might just be missing permissions like I said before.
