### ISSUE TITLE
dashboard has 500 error after update 0.10.10

### ISSUE THREAD

**Issue by callect** [thedevdojo/voyager#601]
- Laravel Version: #.#.#
5.3
- Voyager Version: #.#.#
0.10.10

### Description:
I updated voyager from 0.10.7 to 0.10.10.
use command
`composer update`
then I login into dashboard I got error page.
"Call to a member function getAction() on null"
but other pages like '/admin/posts' is ok!

And how can i find the UPGRADING docs for 0.10.7 to 0.10.10.

**Comment by fletch3555** [comment]
Please provide the full stacktrace of the error.

**Comment by callect** [comment]
![qq 20170120092042](https://cloud.githubusercontent.com/assets/15102717/22131936/ca1c4156-def1-11e6-8bf7-76a08355c740.png)

I track the error find this `$currentRouteAction = app('router')->current()->getAction();`
`$currentRouteAction = app('router')->current() //result null` 

then i use `$routeName = Route::currentRouteName();` instead, but result is null again
i guess that way is not correctly, not really resolve problem.

**Comment by callect** [comment]
no problem with 0.11
