### ISSUE TITLE
cannot update a table when one field is unique

### ISSUE THREAD

**Issue by rabol** [thedevdojo/voyager#602]
- Laravel Version: 5.3.#
- Voyager Version: 0.10.11
- PHP Version: 7.1
- Database Driver & Version:

### Description:
When updating a table where one or more columns have 'unique' an SQL exception is thrown

### Steps To Reproduce:

create a new table: MyTest
id 
name - set key to Unique

save

edit the table, do not do anything, just hit 'Update table' and the following error occurs

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'mytest_name_unique' (SQL: alter table `MyTest` add unique `mytest_name_unique`(`name`))

**Comment by abdgad** [comment]
Thanks for the report. A fix is coming...

**Comment by Frondor** [comment]
Duplicated issue #478 there was a somehow failed PR in progress...

**Comment by fletch3555** [comment]
Please follow this bug on #478.  Closing this as a duplicate
