### ISSUE TITLE
My dummy tables do not get created on local install (MAMP)

### ISSUE THREAD

**Issue by bigfootcreative** [thedevdojo/voyager#604]
- Laravel Version: 5.3
- Voyager Version: Latest
- PHP Version: 5.6.28
- Database Driver & Version:

### Description:
Installing locally with Mamp
While trying to run 
**php artisan voyager:install --with-dummy**

I get errors. 
![screen shot 2017-01-18 at 6 00 25 pm](https://cloud.githubusercontent.com/assets/2649621/22086776/61b2708a-dda8-11e6-9b08-b48f37c96b91.png)

Any ideas or work around. My site url is using Mamp's host of http://voyager-laravel.dev:8888/

**Comment by marktopper** [comment]
Please run the following command and show the output:

```
php artisan voyager:install --with-dummy --verbose
```

**Comment by bigfootcreative** [comment]
Ran that command:

Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Copied Directory [/vendor/tcg/voyager/publishable/views] To [/resources/views/vendor/voyager]
Publishing complete for tag []!
Publishing complete for tag []!
Migrating the database tables into your application


  [Doctrine\DBAL\Driver\PDOException (2002)]
  SQLSTATE[HY000] [2002] No such file or directory


Exception trace:
 () at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
 Doctrine\DBAL\Driver\PDOConnection::__construct() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:116
 Illuminate\Database\Connectors\Connector->createPdoConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:56
 Illuminate\Database\Connectors\Connector->createConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
 Illuminate\Database\Connectors\MySqlConnector->connect() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:126
 Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() at n/a:n/a
 call_user_func() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:965
 Illuminate\Database\Connection->getPdo() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:949
 Illuminate\Database\Connection->getDoctrineConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/larapack/doctrine-support/src/DoctrineSupportServiceProvider.php:70
 Larapack\DoctrineSupport\DoctrineSupportServiceProvider->addDoctrineTypes() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/larapack/doctrine-support/src/DoctrineSupportServiceProvider.php:48
 Larapack\DoctrineSupport\DoctrineSupportServiceProvider->Larapack\DoctrineSupport\{closure}() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:746
 Illuminate\Container\Container->build() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:644
 Illuminate\Container\Container->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:709
 Illuminate\Foundation\Application->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:264
 Illuminate\Database\Connectors\ConnectionFactory->createConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:65
 Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:50
 Illuminate\Database\Connectors\ConnectionFactory->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:176
 Illuminate\Database\DatabaseManager->makeConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:68
 Illuminate\Database\DatabaseManager->connection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:186
 Illuminate\Database\Migrations\DatabaseMigrationRepository->getConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:154
 Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:515
 Illuminate\Database\Migrations\Migrator->repositoryExists() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:92
 Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:58
 Illuminate\Database\Console\Migrations\MigrateCommand->fire() at n/a:n/a
 call_user_func_array() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:508
 Illuminate\Container\Container->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:185
 Illuminate\Console\Command->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/tcg/voyager/src/Commands/InstallCommand.php:68
 TCG\Voyager\Commands\InstallCommand->fire() at n/a:n/a
 call_user_func_array() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:508
 Illuminate\Container\Container->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:817
 Symfony\Component\Console\Application->doRunCommand() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:116
 Symfony\Component\Console\Application->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/artisan:36


  [PDOException (2002)]
  SQLSTATE[HY000] [2002] No such file or directory


Exception trace:
 () at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 PDO->__construct() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 Doctrine\DBAL\Driver\PDOConnection->__construct() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:116
 Illuminate\Database\Connectors\Connector->createPdoConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:56
 Illuminate\Database\Connectors\Connector->createConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php:24
 Illuminate\Database\Connectors\MySqlConnector->connect() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:126
 Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}() at n/a:n/a
 call_user_func() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:965
 Illuminate\Database\Connection->getPdo() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:949
 Illuminate\Database\Connection->getDoctrineConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/larapack/doctrine-support/src/DoctrineSupportServiceProvider.php:70
 Larapack\DoctrineSupport\DoctrineSupportServiceProvider->addDoctrineTypes() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/larapack/doctrine-support/src/DoctrineSupportServiceProvider.php:48
 Larapack\DoctrineSupport\DoctrineSupportServiceProvider->Larapack\DoctrineSupport\{closure}() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:746
 Illuminate\Container\Container->build() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:644
 Illuminate\Container\Container->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:709
 Illuminate\Foundation\Application->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:264
 Illuminate\Database\Connectors\ConnectionFactory->createConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:65
 Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php:50
 Illuminate\Database\Connectors\ConnectionFactory->make() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:176
 Illuminate\Database\DatabaseManager->makeConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:68
 Illuminate\Database\DatabaseManager->connection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:186
 Illuminate\Database\Migrations\DatabaseMigrationRepository->getConnection() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php:154
 Illuminate\Database\Migrations\DatabaseMigrationRepository->repositoryExists() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:515
 Illuminate\Database\Migrations\Migrator->repositoryExists() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:92
 Illuminate\Database\Console\Migrations\MigrateCommand->prepareDatabase() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:58
 Illuminate\Database\Console\Migrations\MigrateCommand->fire() at n/a:n/a
 call_user_func_array() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:508
 Illuminate\Container\Container->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:185
 Illuminate\Console\Command->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/tcg/voyager/src/Commands/InstallCommand.php:68
 TCG\Voyager\Commands\InstallCommand->fire() at n/a:n/a
 call_user_func_array() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:508
 Illuminate\Container\Container->call() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:817
 Symfony\Component\Console\Application->doRunCommand() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/symfony/console/Application.php:116
 Symfony\Component\Console\Application->run() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /Users/gordiescott/Sites/Bigfoot Creative/Voyager Laravel CMS/laravel/artisan:36

**Comment by marktopper** [comment]
I bet you use `localhost` as hostname. Right?

If that is the case, try changing it to `127.0.0.1`.

**Comment by bigfootcreative** [comment]
It just stops working at **Migrating the database tables into your application**
Publishing the Voyager assets, database, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Copied Directory [/vendor/tcg/voyager/publishable/views] To [/resources/views/vendor/voyager]
Publishing complete for tag []!
Publishing complete for tag []!
Migrating the database tables into your application

**Comment by bigfootcreative** [comment]
My apology it fully runs but errors.

[Doctrine\DBAL\Driver\PDOException (2006)]
  SQLSTATE[HY000] [2006] MySQL server has gone away

[PDOException (2006)]
  SQLSTATE[HY000] [2006] MySQL server has gone away

[ErrorException]
  PDO::__construct(): MySQL server has gone away

**Comment by marktopper** [comment]
Please answer my question from before:

> I bet you use `localhost` as hostname. Right?
> If that is the case, try changing it to `127.0.0.1`.

**Comment by bigfootcreative** [comment]
I did change to 127.0.0.1 and was using localhost.

**Comment by bigfootcreative** [comment]
The errors are from after changing to 127.0.0.1

**Comment by marktopper** [comment]
Solved during Skype support.

The problem was the port number was incorrect.

/closed

**Comment by bigfootcreative** [comment]
I was using port 8888 and not 8889 for a Mamp install and Mark was great help.

**Comment by fimaruf** [comment]
I am still having the same issue, any help will be appreciated

**Comment by fletch3555** [comment]
@fimaruf, please do not comment on issues that have been closed for so long (~8 months in this case).  You can create your own issue or ask in our slack group.
