### ISSUE TITLE
Seperate database connection for the data_rows and data_tables to store in SQLight

### ISSUE THREAD

**Issue by garhbod** [thedevdojo/voyager#605]
I think being able to store the 2 tables in a SQLight file would make it easier to keep all the bread settings in sync between dev and production.

If it is possible having a config file(s) instead of a SQLight database might be better so that changes can be tracked

**Comment by marktopper** [comment]
You can use SQLite as your main database.

However, I'm open for other ideas for handling this.

**Comment by vaggelis2018** [comment]
What if we want to use them on other operations. Combining them or something like that. I can't think one reason for this but maybe some people do that already and if these tables will be transferred to separate database could lead to a mess or to more code for the same goal.

**Comment by fletch3555** [comment]
I don't really like the SQLite solution for the reasons @vaggelis2018 mentioned.  I wouldn't mind doing a table prefix or something, but we haven't come up with an easy way to do that yet

**Comment by handiwijoyo** [comment]
Close this because of inactive discussion. Will reopen this if you want to continue.
