### ISSUE TITLE
Menu Builder: update item TokenMismatchException

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#606]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.11
- PHP Version: 5.6.19
- Database Driver & Version: MySQL

### Description:
Reorder the menu item then it throw  **Session\MismatchTokenException**

I chained .fail() method to 
```
            $('.dd').on('change', function (e) {
                $.post('{{ route('voyager.menus.order',['menu' => $menu->id]) }}', {
                    order: JSON.stringify($('.dd').nestable('serialize')),
                    _token: '{{ csrf_token() }}'
                }, function (data) {
                    toastr.success("Successfully updated menu order.");
                }).fail(function(xhr, status, error) {
                    alert(xhr.responseText);
                });
            });
```

![untitled-1](https://cloud.githubusercontent.com/assets/1330852/22096868/7c6eed42-de50-11e6-93ca-b14c001f16b6.png)

![untitled-2](https://cloud.githubusercontent.com/assets/1330852/22096872/844b9dbc-de50-11e6-86ae-cdf97256f435.png)

**Comment by sarath-c-sandwich** [comment]
I check _token jQuery POST, and header token of the page, it's the same; I don't know why that kind of thing happen since v.10.9

**Comment by sarath-c-sandwich** [comment]
Temporary: I added the url to Exception in CsrfVerifyToken middleware. That's not a good idea, but it's okay to use.

<img width="678" alt="screen shot 2017-02-04 at 10 24 28 am" src="https://cloud.githubusercontent.com/assets/1330852/22615280/24bc6db0-eac4-11e6-9089-9d018c1600e5.png">

**Comment by marktopper** [comment]
I am using the latest version and I can not trigger this.
Can you try using `dev-master` and let us know?

Also do you have problems with your sessions?

**Comment by sarath-c-sandwich** [comment]
The latest version does not have more problem regard to this. 

Thanks for help.
