### ISSUE TITLE
Renaming fields with relationships get duplicated (The old one is not deleted from the data_rows table)

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#612]
- Laravel Version: 5.3
- Voyager Version: 0.10.11
- PHP Version: 5.6

Renaming fields with relationships get duplicated (The old one is not deleted from the data_rows table), so if I add a new record, I find the fields is duplicated and the old one is not removed.

**I don't know if this issue exists in fields with no relationships**

1. Add a field in a table with a relationship and add the relationship function in its model.
2. Rename this field from the database page.
3. Go and add a new record in that table, you'll find two inputs for that field.

**Comment by fletch3555** [comment]
@EngHazem, apologies for this taking so long to get to.  Can you confirm whether this is still an issue in the current version?

**Comment by handiwijoyo** [comment]
Close this due inactivity.
