### ISSUE TITLE
foreign keys

### ISSUE THREAD

**Issue by saintmim** [thedevdojo/voyager#613]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
Isn't it better that foreign keys to related rows be unsigned integers?

**Comment by fletch3555** [comment]
Agreed, I'm open to pull requests for this. (sorry for the delay)

**Comment by MrCrayon** [comment]
@fletch3555 can we close this?
As far as I can see all foreign keys are unsigned integers except for pages and posts that are kind of demo contents.

**Comment by fletch3555** [comment]
Yes
