### ISSUE TITLE
created_at and upload_at timestamp issue

### ISSUE THREAD

**Issue by Buyanbatu** [thedevdojo/voyager#618]
##- Laravel Version: 5.3.*
- Voyager Version: ^0.10.11
- PHP Version: 5.6.25
- Database Driver & Version: mysql & 5.7.14

### Description:
Hi, I have issue with Database tool and when i add bread in new table,  created_at and updated_at field's type shows text box with dropdown menu. from Database tool when i create new table i just use the new timestamps field button.

![voyager-bread](https://cloud.githubusercontent.com/assets/641682/22194049/ab1e2378-e0f4-11e6-9bd6-aa8e5673103f.PNG)

**Comment by psmedia90** [comment]
I am Having the same issue

**Comment by denbatte** [comment]
Started investigating and for future reference/help:
The key property of the timestamp type is empty.
![image](https://cloud.githubusercontent.com/assets/505196/24328879/39d0fb22-11f6-11e7-9c94-045e15412fd2.png)

**Comment by abdgad** [comment]
Closing this since v0.10 is no longer supported.
