### ISSUE TITLE
Adding a new input type in settings page (Color input type)

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#619]
I suggest adding a new input type (Color pallette input type), or adding all possible input types in the Setting Type dropdown menu, regardless of the compatibility factor.

Thanks.

**Comment by akazorg** [comment]
I'll create a PR for that.

**Comment by fletch3555** [comment]
@akazorg, was this ever created?

**Comment by akazorg** [comment]
This was not implemented yet

**Comment by akazorg** [comment]
PR sent: https://github.com/the-control-group/voyager/pull/1494
