### ISSUE TITLE
enum type is not supported by Doctrine, which is built into laravel.

### ISSUE THREAD

**Issue by Mugluck** [thedevdojo/voyager#62]
I don't know why I'm running into this now, but hey, Murphy's law! ;)

Getting a 
[Doctrine\DBAL\DBALException]
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

Research suggests that the Doctrine platform has never supported enum and never will given that people have reported the issue for years. Most solutions seem incredibly hacky. 

Anyways, for what it's worth, I'm dropping this here as I ran into it and don't have time to solve something that's clearly very complicated.

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/mysql-enums.html 
https://github.com/laravel/framework/issues/1346
https://github.com/laravel/framework/issues/1186
https://wildlyinaccurate.com/doctrine-2-resolving-unknown-database-type-enum-requested/

**Comment by arnaudbesnier** [comment]
I observed the same error with a real enum type in one of my existing Postgresql database.
And adding an enum using Laravel does not seem to create a real enum in the database.

**Comment by marktopper** [comment]
Is this still a issue? I have a solution for this which I can then go ahead an implement.

**Comment by Mugluck** [comment]
Yeah, to the best of my knowledge it is.

**Comment by marktopper** [comment]
Okay. I can do a Laravel package to solve this.
Can I ping you to test it?

**Comment by Mugluck** [comment]
Sure. No problem. I can test it out on a blank project, and on one of my development databases that really likes to trigger problems on me.

**Comment by marktopper** [comment]
Update to the latest version of Voyager and this have been fixed.

**Comment by AdrianKuriata** [comment]
@marktopper How it should work? I getting this error when i wanted to create some PR's for Voyager, but i can't do this. After install or clone fork with master branch Voyager not working, JS is not loaded and when i trying to install voyager, i getting this issue, i don't have idea how can i fix it...

**Comment by brazitech** [comment]
still a problem...it has not been fixed!! 3 years!!!

**Comment by fletch3555** [comment]
First off, please reference a calendar before mentioning the passage of time

This issue was closed nearly 18 months ago, and was referencing a much older version.  Voyager has changed SIGNIFICANTLY since this issue was opened.  If you're having an issue with Voyager, we welcome you to open your own issue or ask in our Slack group.
