### ISSUE TITLE
The created migration for the table contains only the increments and the timestamps

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#620]
- Laravel Version: 5.3
- Voyager Version: 0.10.11
- PHP Version: 5.6

As the title says, the feature of creating migration for the table generate a migration file which does not contain the fields created using the admin UI.

Example:

    public function up()
    {
        Schema::create('sliders', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
        });
    }

Thanks.

**Comment by abdgad** [comment]
I am currently working on improvements to the DB manager (see #603). It's still a work in progress. 
Hopefully when it's completed, we'll add full migration generation from the UI.

**Comment by fletch3555** [comment]
Migration creation has been disabled for nearly 4 months, but is on the roadmap.  Closing this for now.

**Comment by Kylegabriel** [comment]
Ive install fresh new laravel 5.3 and voyager but when I create new table the "Create new Migration for this table?" is not clickable not woking?

**Comment by jopcode** [comment]
still happend? laravel 5.5, voyager 1.0 :/

**Comment by fletch3555** [comment]
@jopcode, this issue has been closed for nearly a year.  This feature was removed well before 1.0 was even released.  I assure you this issue is not still happening because it can't, since the feature no longer exists.

**Comment by jopcode** [comment]
oh :C, thx @fletch3555
