### ISSUE TITLE
Can't install voyager on laravel 5.4

### ISSUE THREAD

**Issue by pjeutr** [thedevdojo/voyager#622]
- Laravel Version: 5.4.0
- Voyager Version: 0.10.11

### Description:
I know it's been just released, but are there more people trying to install on laravel 5.4? 
Getting the following error:

>   Problem 1
    - tcg/voyager v0.10.11 requires larapack/doctrine-support ^0.1.0 -> satisfiable by larapack/doctrine-support[v0.1.0].
    - Installation request for tcg/voyager ^0.10.11 -> satisfiable by tcg/voyager[v0.10.11].
    - Conclusion: remove laravel/framework v5.4.0
    - Conclusion: don't install laravel/framework v5.4.0
    - larapack/doctrine-support v0.1.0 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.0
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.0
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.0
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.0
    - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[v5.4.0].

### Steps To Reproduce:
composer create-project laravel/laravel blog
composer require tcg/voyager

I see larapack/doctrine-support has a 5.3.* dependancy, so that seems to be the problem.
But I don't know if there are alternatives, or why it is **exactly** needed

**Comment by rickmills** [comment]
I'd imagine that larapack/doctrine-support is being brought in to allow additional field types @pjeutr 

Might be worth opening an issue on https://github.com/larapack/doctrine-support as it'll need an update to work with 5.4, even if it is just a composer update.

**Comment by marktopper** [comment]
I have released `larapack/doctrine-support:v0.1.1` with Laravel 5.4 support.
There are still some issues with Voyager and Laravel 5.4.
You can see the progress at at PR #626

**Comment by pjeutr** [comment]
I used the branch @marktopper  created https://github.com/the-control-group/voyager/tree/laravel-54-support
Installing goes fine now. Didn't see any strange phenomena. But not all tests are succeeding

use this in you're composer.json to install the branch

    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/the-control-group/voyager"
        }
    ],      
    "require": {
        "tcg/voyager": "dev-laravel-54-support"

**Comment by injoyce** [comment]
![image](https://cloud.githubusercontent.com/assets/20395069/22626356/a5f46aba-ebee-11e6-801d-e5f57e4f21ba.png
Laravel Version: 5.4.0
Voyager Version: 0.10.12

Error occured, don't know why.

**Comment by marktopper** [comment]
`v0.11.0` just released with Laravel 5.4 support.
