### ISSUE TITLE
Wrong Post being deleted from BREAD files

### ISSUE THREAD

**Issue by saranshdhingra** [thedevdojo/voyager#624]
- Laravel Version: 5.3
- Voyager Version: 0.10.11
- PHP Version: 5.6.19
- Database Driver & Version:

## Description:
In the File **voyager/publishable/views/posts/browse.blade.php** at the bottom we have:
```
$('td').on('click', '.delete', function(e) {
            $('#delete_form')[0].action = $('#delete_form')[0].action.replace('__id', $(e.target).data('id'));
            $('#delete_modal').modal('show');
});
```
Consider a scenario that we click on the Delete action button but don't delete the post. Now the action attribute of the form has changed, so there is no **"__id"** string. There is an integer. So next time we click delete on any other post, the id is not substituted in the action attribute and we delete the wrong post unintentionally.

This is obviously replicated in any BREAD files we inherit by copying the posts folder.

While a permanent solution might be not to use something like **__id** and probably use id as a hidden parameter.
## A temporary solution:
```
$('td').on('click', '.delete', function(e) {
            var id=$(this).data("id"),
                action=$('#delete_form')[0].action;
            if(action.indexOf('__id')!=-1)
                $('#delete_form')[0].action = action.replace('__id', id);
            else
                $('#delete_form')[0].action = action.replace(/\d+$/, id);
            $('#delete_modal').modal('show');
});
```

**Comment by saranshdhingra** [comment]
I can submit a PR if anyone wants.

**Comment by fletch3555** [comment]
I'd rather not do a replace like you're doing.  The reason it's using `__id` is because the standard REST deletion route is `DELETE <domain>/[resource]/[id]`.  What I think I'd rather do, is to add an `onclick` event to the `close` button that changes it back to `__id`

**Comment by saranshdhingra** [comment]
Sure, that approach is acceptable as well, but just for my knowledge how is the **_replace_** used in my code insufficient?

**Comment by fletch3555** [comment]
Apologies for never answering @supernova13892.  I'm going to close this due to age.  Significant changes have occurred between v0.10 and now.  If this is still an issue following the 1.0 release, please open a new issue and we'll look into it.
