### ISSUE TITLE
theme not load correctly sometimes

### ISSUE THREAD

**Issue by mohammad6006** [thedevdojo/voyager#633]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.11

sometime theme not loaded correctly and you have to reload it

![download](https://cloud.githubusercontent.com/assets/553379/22304978/05da6126-e34f-11e6-8bcc-74660a3ea369.png)

**Comment by fletch3555** [comment]
Looks like it's not a "theme" issue.  That looks like a markup rendering error with the `data_types` table.  I'm not aware of anyone else having these issues.  Is this an intermittent issue, or does it happen every time?

**Comment by fletch3555** [comment]
I'm going to close this since it's been 6 months without any other reports of this that I'm aware of.
