### ISSUE TITLE
slugify auto fill just work for title

### ISSUE THREAD

**Issue by mohammad6006** [thedevdojo/voyager#636]
I created a products table with title field and slug 
`{"slugify": {"origin": "title"}}`
and it works perfect

but I created another table " groups "
and a field "name"
and slug:
`{"slugify": {"origin": "name"}}`
its not work and not auto fill slug field when I add new group

**Comment by akazorg** [comment]
Hello @mohammad6006, does it still happening?
I need to test that.

**Comment by marktopper** [comment]
@mohammad6006: Please ensure that you have published the latest assets and that your cache is cleared.

**Comment by biplavraut** [comment]
Hello @akazorg  I am also facing the same problem. Please can you explain more about slugify

**Comment by marktopper** [comment]
Closed due to missing response.

**Comment by tokkerbaz** [comment]
Hello @marktopper =) i have this issue too, but i see where is the problem in `slugify.js` at line 43:
`this.input = this.settings.input  || $(this.element).closest('form').find('input[name="title"]');`
thats why origin can only be title =))

**Comment by marktopper** [comment]
@tokkerbaz: Are you running the latest version of Voyager and have you republished the assets?

**Comment by tokkerbaz** [comment]
@marktopper yes =)) but only works with title

**Comment by marktopper** [comment]
// ping @akazorg

**Comment by akazorg** [comment]
Ok guys, tonight I'll take care of it. (L)

**Comment by akazorg** [comment]
This was fixed with #767. @marktopper you can close this issue.
