### ISSUE TITLE
Existing roles table thwarted installation

### ISSUE THREAD

**Issue by bonsai-srl** [thedevdojo/voyager#64]
I was unable to integrate to my project due to already having a roles table.  

I worked with migrations and seeding for a little while but gave up and started new.  I can afford a fresh install but I'm sure many people couldn't.

Perhaps voyager could work in its own namespace for these things to better integrate to existing applications.

Great tool, BTW, and many thanks!

**Comment by tnylea** [comment]
Closing because new issue has been added to support this: https://github.com/the-control-group/voyager/issues/1447

Thanks :)
