### ISSUE TITLE
[BREAD] API method for searching relationship entries in add/edit views (ajax & select2)

### ISSUE THREAD

**Issue by Frondor** [thedevdojo/voyager#642]
Actually, it takes `$relationshipClass::all()` entries which is not good at all for models with tons of entries.

We should be using `select2`'s capabilities to look for the entries via ajax instead of getting them all on page load.

**Comment by marktopper** [comment]
Good idea.

**Comment by morloderex** [comment]
I'll take a look at this.

**Comment by marktopper** [comment]
Thanks @morloderex.

**Comment by Muhammadinaam** [comment]
is someone working on this issue?

**Comment by fletch3555** [comment]
I'm going to close this issue since there have been massively significant changes between February and now.  We can revisit the request after 1.0 gets released if it's still an issue
