### ISSUE TITLE
Panel is not responsive

### ISSUE THREAD

**Issue by mustafat0k** [thedevdojo/voyager#643]
Why panel is dont responsive?

**Comment by mustafat0k** [comment]
You can interest next relase  for  5.4  version please

**Comment by fletch3555** [comment]
Please clarify your issue.  If your sole request is to have support for Laravel 5.4, we're working on it.

**Comment by mustafat0k** [comment]
What more do I explain. This panel hasnt own responsive  a design. Just i want next release added please. A few more pages are corrupted. ex:homepage...
 I enought only happened responsive. Have design fallacies but it's not that important. create/Edit/delete buttons not margin.Ridding on top. 

But i liked. Nice work  👍 

![2017-01-27_23-04-38](https://cloud.githubusercontent.com/assets/15256433/22385884/40ea5ab6-e4dd-11e6-9943-9c35d3214b7e.png)

But i liked. Nice work  👍 and you should  use different has own responsive table..

**Comment by marktopper** [comment]
We are open for pull requests on this.

**Comment by niradler** [comment]
I'm new to voyager if you can give some details on the front end and file structure  I can help with the design maybe add the option to support theme can be awesome as well

**Comment by marktopper** [comment]
@niradler: Will possibly add support for themes once we have released `v0.11` and the plugin system have been finished.

**Comment by Frondor** [comment]
Just addressed most issues regarding to layouts and responsiveness, including a config option to use `responsive` dataTable's extension https://github.com/the-control-group/voyager/pull/697#commits-pushed-6571d3b
I'll update the main post of that PR later

**Comment by fletch3555** [comment]
I'm going to close this for now since it's been 5-6 months.  We'll revisit styling as needed.
