### ISSUE TITLE
Media library does not render correctly in Safari 10.0

### ISSUE THREAD

**Issue by jannejava** [thedevdojo/voyager#644]
- Laravel Version: 5.3
- PHP Version: 7.0

### Description:
In Safari the media library does not render proper. The items are in a long row and the thumbnails are not visible. Works fine in Chrome

### Steps To Reproduce:
View media library on Safari 10.0
<img width="1773" alt="screenshot-2017-01-27 13-55-i3v03" src="https://cloud.githubusercontent.com/assets/543616/22371696/c3fe7832-e498-11e6-9d3b-a11dc5d102d0.png">

**Comment by fletch3555** [comment]
@thedevdojo, you use a Mac, right? Could you take a look?

**Comment by jannejava** [comment]
I am not a flexbox expert, so I could not solve it with flexboxes. Made a temporary fix by setting the items to a fixed width and inline-blocks and float. 

Also seems like the div holding the thumbnail needs to have a height to render properly in Safari.

**Comment by marktopper** [comment]
I always use Chrome on my Macbook, however just tested this and it is indeed a issue on Safari.

**Comment by handiwijoyo** [comment]
I can confirm that this issue didn't happen on Safari 11.0.x

![image](https://user-images.githubusercontent.com/4060094/34668165-b0a11756-f49e-11e7-84ec-fe1eb2dffe42.png)
