### ISSUE TITLE
Lock Screen

### ISSUE THREAD

**Issue by tomatoe45** [thedevdojo/voyager#649]
- Laravel Version: 5.3.*
- Voyager Version: latest
- PHP Version: 7.0

### Description:
Can you make lock screen for this app?

### Steps To Reproduce:

Users can lock their accnt for admin so they don't need to logout while they are on coffee break

**Comment by marktopper** [comment]
We are open for pull requests.

**Comment by fletch3555** [comment]
I'm not sure what the added benefit of this functionality would be.  Lock screens are great for OS's and hardware-specific applications, but a vast majority of web applications wouldn't see any benefit from a lock screen in that sense.  A user could just as easily stay logged into Voyager, and use their computer's lock screen for the coffee break.

But anyway, as @marktopper said, we're open to pull requests.  I would recommend you better outline your reasoning for this functionality (i.e. what problem it solves and why it's better than current alternatives) before spending a lot of time on this only to have it be rejected.

**Comment by marktopper** [comment]
Well I actually think I am gonna close this since it's not really related to Voyager.
You might just want to lock your machine instead.

However if you really want this, you can build it up as a hook (Voyager's plugin system) or comment back here for another reason to reopen it.

**Comment by tomatoe45** [comment]
I was just thinking if there is a lock screen it would be nice since it was an admin page area. the admin can lock the screen browser only for a coffee break not the whole computer. yeah i know its not a majority for this application although its an extra features.. btw this is very useful tool.. i love it.. it is very easy to navigate.. thanks for this tool.. keep it up..
