### ISSUE TITLE
Google Analytics embed to admin panel

### ISSUE THREAD

**Issue by basmaseyam** [thedevdojo/voyager#651]
- Laravel Version: 5.2
- Voyager Version: latest
- PHP Version:5.6
- Database Driver & Version:

### Description:
How to add google analytics client id to admin panel.

Steps i did:
Made an entry in settings database with google analytics id value. But nothing is shown on dashboard.

**Comment by marktopper** [comment]
Please share your setting here.

**Comment by basmaseyam** [comment]
![setting database](https://cloud.githubusercontent.com/assets/17016909/22466428/0f3efe82-e775-11e6-8948-36dae88ca4cb.png)

**Comment by basmaseyam** [comment]
![setting database](https://cloud.githubusercontent.com/assets/17016909/22466789/b3f34536-e776-11e6-8ef6-8cde3222be14.png)

**Comment by marktopper** [comment]
And what does the Dashboard show now?

**Comment by basmaseyam** [comment]
![screencapture-eliteminds-co-admin-1485866905042](https://cloud.githubusercontent.com/assets/17016909/22467402/5f0ad798-e779-11e6-87d3-d03f6763da1b.png)

**Comment by psmedia90** [comment]
I'm having the same problem

**Comment by nikkuang** [comment]
make sure you have added you current site to "Authorized JavaScript origins" in your client credentials

**Comment by psmedia90** [comment]
where's that at

**Comment by nikkuang** [comment]
Sorry, I just realize what I said was incomplete.It's on https://console.developers.google.com . On your google project under credentials you added.

![screenshot from 2017-02-04 06-37-25](https://cloud.githubusercontent.com/assets/6487764/22611403/466e54ec-eaa5-11e6-9251-b0ccd4afe5e9.png)

**Comment by SerjoA** [comment]
in this same window, goto dashboard and you have a button there enable api
search analytics and enable the api

**Comment by marktopper** [comment]
I have been creating a [guide](https://webman.io/blog/post/setup-google-analytics-for-laravel-voyager) for this.
