### ISSUE TITLE
larvel 5.4 not support

### ISSUE THREAD

**Issue by aemaddin** [thedevdojo/voyager#656]
- Laravel Version: 5.4.6
- Voyager Version: 0.10.11
- PHP Version:5.6.28
- Database Driver & Version: MySQL - 5.6.24

### Description:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tcg/voyager ^0.10.11 -> satisfiable by tcg/voyager[v0.10.11].
    - Conclusion: remove laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.6
    - tcg/voyager v0.10.11 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.6
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.6
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.6
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.6
    - Installation request for laravel/framework (locked at v5.4.6, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.6].

Installation failed, reverting ./composer.json to its original content.

### Steps To Reproduce:
laravel new blog
cd blog
composer require tcg/voyager

**Comment by odera89** [comment]
Same Problem! 👎

**Comment by Fisiu** [comment]
@marktopper What else needs to be done to support laravel 5.4?

**Comment by marktopper** [comment]
You can follow the pull request I have working on for Laravel 5.4 support #626

**Comment by l3est** [comment]
+1

**Comment by sireskay** [comment]
@thedevdojo Thanks for putting this awesome project together. Please let us know how we can help to help this support 5.4!

Thanks

**Comment by brazitech** [comment]
*1

**Comment by marktopper** [comment]
Supported in version `v0.11.0`.
Which is now released.
