### ISSUE TITLE
How to passing data from Voyager to the front-end page template interface?

### ISSUE THREAD

**Issue by medIdaoud** [thedevdojo/voyager#659]
- Laravel Version: 5.3.0
- Voyager Version: 0.10.*
- PHP Version: 7.0.10
- Database Driver & Version: mysql
# Description:
 i dont now  how to put the data in my new template  from  table created with database voyager

**Comment by sarath-c-sandwich** [comment]
Do you have Model? Then just use your Controller to create Model Object then pass it to View. What you do on Laravel, that's the same thing.

**Comment by medIdaoud** [comment]
thnx  @uchsarath

**Comment by sarath-c-sandwich** [comment]
@marktopper  just marked as solved.
