### ISSUE TITLE
What is the location of newly created table ?

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#66]
I would like to know what is the location of view files of newly created table. Although i have searched everywhere in tcg/voyager/src folder but i find nothing ?

**Comment by afsardo** [comment]
What do you mean? by "view files"

**Comment by MamunHoque** [comment]
@afsardo if you add publish view file to resources folder then this problem will solved.

**Comment by afsardo** [comment]
@MamunHoque Yes i tho that would be the case, but i just wanted to make sure that was the issue ;)

If it is then it's just a duplicated Issue that has been posted already many times ^^

**Comment by afsardo** [comment]
If it is then it's just a duplicated Issue that has been posted already many times ^^

**Comment by MamunHoque** [comment]
@afsardo  Yes and you need to add a feature so when new bread added you also publish that bread files to resources folder

**Comment by ghost** [comment]
@afsardo  "view files" mean if i create a new table then we can do CRUD operation in this table. There must be view files, controller and model. I find model but i didn't see view files.

**Comment by ghost** [comment]
@MamunHoque How can we publish bread files in resource folder ? Could you please explain

**Comment by marktopper** [comment]
Do you still need help?

**Comment by fletch3555** [comment]
Closing as inactive
