### ISSUE TITLE
how do i display the pages on my frontend

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#660]
how do i display the pages on my frontend ?

**Comment by sarath-c-sandwich** [comment]
Just create a new Model in your Laravel App

```
php artisan make:model Page
```
then replace your page_table_name in the page.php 
```
    protected $table = 'pages';
```
That Model will automatically connect to page table.

- Finally query data via controller by creating Model Object and pass it to view. That's all. 
- Follow this, it's the same process. https://laravel.com/docs/5.4/eloquent#defining-models

**Comment by ghost** [comment]
Thanks @uchsarath
