### ISSUE TITLE
Custom MenuItems not sorted by order

### ISSUE THREAD

**Issue by jannejava** [thedevdojo/voyager#662]
- Laravel Version: 5.3
- Voyager Version: latest
- PHP Version:7.1

### Description:

When using a custom template for menus, the MenuItems are not sorted by column "order"

### Steps To Reproduce:

1. Create a menu in menu builder. 

2. Change the sort order, move around.

3. Embed a custom menu into your template like this:

` {!! Menu::display('main', 'navbar.my-menu') !!}`

4. MenuItems are sorted by primary id

My solution:

I added ->orderBy to items() in Menu.php. Since I cannot see when you ever would like to have a menu ordered by ID?

     public function items()
     {
        return $this->hasMany(MenuItem::class)->orderBy('order');
     }

**Comment by marktopper** [comment]
Can you please try the `dev-master` version, should already have been fixed there.

Gonna pull out a new patch release soon.

**Comment by marktopper** [comment]
Closing for now, ping me if not fixed in `dev-master`.

**Comment by ItsRD** [comment]
I've got the same problem. tried dev-master, but it doesn't work.

**Comment by marktopper** [comment]
What is your problem @ItsRD?

**Comment by ItsRD** [comment]
I changed the order of the menu_items (those with a parent_id) and it doesn't effect the frontend.

**Comment by marktopper** [comment]
Will look into this once the new menu model is done which comes in `v0.11`.

**Comment by marktopper** [comment]
Closing this since `v0.11` is released.
