### ISSUE TITLE
Looking for plural table

### ISSUE THREAD

**Issue by bordmelo** [thedevdojo/voyager#664]
- Laravel Version: 5.3
- Voyager Version: 0.10.11
- PHP Version: 5.6.4

Description: When I add an existing table to BREAD, when I create the link in the builder and access menu it tries to communicate with the plural database but the table name is in the singular

![image](https://cloud.githubusercontent.com/assets/22230727/22468853/0dbd6cd8-e7b1-11e6-83e7-00d8a733eca6.png)

**Comment by MiguelOrdnz** [comment]
I got the same error, try adding this property to your table model.

`protected $table = 'chartter_discussion';`

The fact is that Eloquent by default considers that the table name is the plural of your models name. Please read:
https://laravel.com/docs/5.3/eloquent

**Comment by bordmelo** [comment]
@MiguelOrdnz Oh sorry I'm new to laravel, thank you very much.
