### ISSUE TITLE
I am not able to install Voyager

### ISSUE THREAD

**Issue by dagogoilamini** [thedevdojo/voyager#671]
- Laravel Version: 5.3
- Voyager Version:^0.10.11
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description: I cant install it on project ie voyager
Got this error 

C:\Users\Ilamini\Desktop\xampp\htdocs\BitcoinApp>php composer.phar require tcg/voyager
Using version ^0.10.11 for tcg/voyager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - intervention/image 2.3.9 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.8 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.7 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.6 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.5 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.4 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.3 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.10 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - intervention/image 2.3.0 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - tcg/voyager v0.10.11 requires intervention/image ^2.3 -> satisfiable by intervention/image[2.3.0, 2.3.1, 2.3.10, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9].
    - Installation request for tcg/voyager ^0.10.11 -> satisfiable by tcg/voyager[v0.10.11].

  To enable extensions, verify that they are enabled in those .ini files:
    - C:\USERS\ILAMINI\DESKTOP\XAMPP\PHP\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by nikkuang** [comment]
You need to have php fileinfo installed and enabled. 

http://php.net/manual/en/fileinfo.installation.php

**Comment by marktopper** [comment]
What @nikkuang said.

/closing

**Comment by flixmag** [comment]
Having the same issue... did all above, but not working. Question I would like to know to try fixing on my end. How does one change the php --ini loaded configuration location path?
