### ISSUE TITLE
SQL error when trying to enter data types with timestamps

### ISSUE THREAD

**Issue by redsoxfan2499** [thedevdojo/voyager#674]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.10
- PHP Version: 5.6.24
- Database Driver & Version:
mysql
### Description:
following tutorials on youtube. created a products data type with timestamps. but when I try to enter a new product. I leave the created update fields blank since I do not get a pop type bootstrap calendar and I assume that the timestamps will be saves automatically but getting SQL error:

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'created_at' at row 1 (SQL: insert into `products` (`name`, `description`, `created_at`, `updated_at`) values (Laravel Book, A book about Laravel development, , ))

if we have to enter a date for data types then I would assume a jquery calendar or some date formatting hints.  But I then try to enter a data as such:  02/02/2017 and get an error of:
Unexpected data found.
Unexpected data found.
Data missing

### Steps To Reproduce:
following tutorials on youtube. created a products data type with timestamps. but when I try to enter a new product. I leave the created update fields blank since I do not get a pop type bootstrap calendar and I assume that the timestamps will be saves automatically but getting SQL error:

BTW. in the database tool. the timestamps options are marked YES for NULL.

**Comment by redsoxfan2499** [comment]
So today more research. So when I have the created and updated fields marked as Date fields in the BREAD editor I do get a calendar view but of course in the DB it is marked as Timestamps so this does not work. I can leave the fields as Textboxes but I have to make sure that the time is formatted correctly as such:  2017-02-24 00:00:00	If I leave them blank, I get the SQL error. The field is not formatted correctly I get SQL error.  

So I would assume that if I chose the Created and Update fields in my datatype, I would not need to enter anything in the fields and upon submit, it would just save the item in the DB. As of right now, you have to enter a Timestamp formatted correctly or you will get an error. 

Thanks!

**Comment by marktopper** [comment]
Can you please share a screenshot of the database table `products` structure, the BREAD options for `products` and the error that happens.

**Comment by redsoxfan2499** [comment]
so for this example, I enter a name and price and leave the created and updated fields blank since they are timestamps in the database.
screenshots below:
![voy1](https://cloud.githubusercontent.com/assets/1205420/22627745/9fbdbfc2-eb8d-11e6-9c60-168bcb62e9f7.PNG)
![voy2](https://cloud.githubusercontent.com/assets/1205420/22627743/9fbc8e2c-eb8d-11e6-91b0-16ab18e801f1.PNG)
![voy3](https://cloud.githubusercontent.com/assets/1205420/22627744/9fbd8bc4-eb8d-11e6-9ac8-d39bd9fbb31a.PNG)
![voy4](https://cloud.githubusercontent.com/assets/1205420/22627746/9fbf969e-eb8d-11e6-8fd5-0c325eefc30b.PNG)
![voy5](https://cloud.githubusercontent.com/assets/1205420/22627751/e7f76f04-eb8d-11e6-9903-9a4e6f29c8e0.PNG)

**Comment by jac0b95** [comment]
I have same issue. Resolve it with adding this code to my Model.

`public function save(array $options = [])
    {
        if(!isset($this->created_at)) {
        	$this->created_at = date("Y-m-d H:i:s");
        }
        $this->updated_at = date("Y-m-d H:i:s");
        parent::save();
    }`

It's a little bit hacky but works.

**Comment by marktopper** [comment]
Indeed a hacky solution. But however a temporary fix.

**Comment by jac0b95** [comment]
I looked a little bit closer to this issue.

When I disable timestamps show in Create it works fine and in database there is right dates of create_at and update_at. Then on Edit we need to disable only update_at if we want be able to change created_at and generate new date for update_at.

Everthing is going about overrides.

If it's lame just ignore it but i hope it will help someone.

**Comment by Frondor** [comment]
Well, this is not a bug to me, when you're not using `timestamps` you have indeed to disable them in your models.
And also `$cast` the dates besides the normal ones `created_at`, `updated_at`, `deleted_at`, or you're gonna face another error like this one.

Simply add `public $timestamps = false;` to your models.

**Comment by oschettler** [comment]
I believe the problem lies in src/Http/Controllers/Controller.php where for timestamps it is not checked whether the input actually contains a value. I have prepared [a pull request](https://github.com/the-control-group/voyager/pull/729) that fixes this. 

For me, this fixes the error ...

````
QueryException in Connection.php line 770:
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1970-01-01 00:00:00' for column 'created_at' at row 1 (SQL: update `users` set `password` = XXX, `created_at` = 1970-01-01 00:00:00, `updated_at` = 2017-02-13 18:28:24, `avatar` = users/February2017/C1DXaKqmbgRtjLsBKs3T.jpg where `id` = 1)
````

... which I got when updating my avatar.
