### ISSUE TITLE
SQL error after creating new data type

### ISSUE THREAD

**Issue by redsoxfan2499** [thedevdojo/voyager#675]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.10
- PHP Version: 5.6.24
- Database Driver & Version:
mysql
### Description:
I create a new simple data type called Widgets. I am using 3 fields, ID, name and description. Saved table. then created BREAD and added the permission to my admin role. also added it to menu using menu builder. when I go to page with the correct slug admin/widgets I am getting this SQL error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'order clause' (SQL: select * from `widgets` order by `created_at` desc) 

I did not chose TIMESTAMPS this time as I was having problems with timestamps on my other ticket with the Products table/BREAD I created.

**Comment by redsoxfan2499** [comment]
Doing some research today, Looks like at VoyagerBreadController line 46 it calling the latest(). But the data type I created does not have timestamps. So I did a temporary fix changes this line:

`$dataTypeContent = call_user_func([$model->with($relationships)->latest(), $getter]);` 

to this since there are no TIMESTAMPS 

`$dataTypeContent = call_user_func([$model->with($relationships), $getter]);` 

now my widgets main browser view works.  

Of course this is a temporary fix, looks like their needs to be another else type statement with data types without any Timestamps????

**Comment by marktopper** [comment]
You must add the following to the `Widget` model.

```
protected $timestamps = false;
```

**Comment by redsoxfan2499** [comment]
thanks Mark, will do! 

thanks for all of your help!

**Comment by marktopper** [comment]
Always

**Comment by redsoxfan2499** [comment]
Mark, 

I just placed the code you suggested in the Widget model and got an error stating that is has to be public. 

![voy6](https://cloud.githubusercontent.com/assets/1205420/22627889/fa84320e-eb8f-11e6-8150-9267490587e5.PNG)


So I just replaced protected to public and now it works?  

Is this okay to keep it public?? 

`protected $timestamps = false; `

`class Widget extends Model
{
    public $timestamps = false;
}`

**Comment by marktopper** [comment]
Yea, of cause. My bad, should be public.
