### ISSUE TITLE
Can We assign roles to users

### ISSUE THREAD

**Issue by faraz-purelogics** [thedevdojo/voyager#68]
Hello,

How we can assign roles to users?

Thanks,
Faraz

**Comment by MamunHoque** [comment]
Yes, you can. you can set user role to the config file.

**Comment by faraz-purelogics** [comment]
How i can do that from config file?

**Comment by MamunHoque** [comment]
currently, user role will be added when you add news user. if you want to change default user role,  open config/voyager.php and modify as per your need.

**Comment by faraz-purelogics** [comment]
I want role drop down while add edit user

**Comment by MamunHoque** [comment]
If you want to do now then follow this instruction: 
1) Copy all files and folder from /vendor/tcg/voyager/src/views to /resources/views/vendor/voyager (you need to make a folder before)
2) Copy /resources/views/vendor/voyager/bread to /resources/views/vendor/voyager/users
3) Edit /resources/views/vendor/voyager/users/edit-add.blade.php add your need input filed. 

Understand?

**Comment by fletch3555** [comment]
That's not a great solution @MamunHoque.  The BreadController and it's views are meant to be dynamic.  Requests to add the ability to edit relations has already been requested a couple times.  My recommendation to @faraz-purelogics would be to build out that functionality and submit a PR, or be patient while someone else does it.

**Comment by Omazon** [comment]
It would be good idea to that basic functionality come included, as well as add category to the post, in the same way add role to create user, and that only the admin user can modify this option (it wouldn't make sense that a normal user can create administrators)

**Comment by Mix356za** [comment]
good idea for

**Comment by fletch3555** [comment]
v0.10 added the ability to change a user's role.
