### ISSUE TITLE
Media Manger issues and error

### ISSUE THREAD

**Issue by redsoxfan2499** [thedevdojo/voyager#680]
-Laravel Version: 5.3.30
-Voyager Version: 0.10.10
-PHP Version: 5.6.24
-Database Driver & Version:
-mysql

### Description:
Click on Media Manger in admin menu, it opens and just sits there and spins. Try to upload image, I get an red Whoopsie error screen, but have of the error is hidden off screen no matter how much I enlarge my browser window.

![voy9](https://cloud.githubusercontent.com/assets/1205420/22628632/ed38445c-eb9c-11e6-8ec6-809e581c4010.PNG)

### Steps To Reproduce:
go to Media section from admin menu.

**Comment by marktopper** [comment]
Please update to the latest Voyager version.
