### ISSUE TITLE
installation error: Class 'App\User' not found

### ISSUE THREAD

**Issue by rookie0** [thedevdojo/voyager#685]
- Laravel Version: 5.3.26
- Voyager Version: 0.10.13
- PHP Version: 5.6
- Database Driver & Version:

### Description:
when exec `php artisan voyager:install`
`PHP Fatal error:  Class 'App\User' not found in /path/to/project/vendor/tcg/voyager/src/VoyagerServiceProvider.php on line 58`
because app user model has been moved and `config('voyager.user.add_default_role_on_register')` default is `true` in `publishable/config/voyager.php`

### Steps To Reproduce:
just remove your app user model and run `php artisan voyager:install`

###Suggest
set config('voyager.user.add_default_role_on_register') default false 
vendor:publish before voyager:install and you can config what yourself

**Comment by marktopper** [comment]
If you do not wish to have your own user model, set the configuration to use `TCG\Voyager\Models\User`.
However, I do not see the point for removing your own user model.
