### ISSUE TITLE
After adding a new setting with type "file", I'm getting Array to string conversion (SQL: update `settings` set `value` = where `id` = 20) Error

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#687]
- Laravel Version: 5.3
- Voyager Version: 0.10.13
- PHP Version: 5.6

After adding a new setting with type "file", I'm getting this error when saving the settings form:

![err](https://cloud.githubusercontent.com/assets/8501654/22641629/2933d926-ec60-11e6-9380-5ea36804f45c.png)
btw: the changes are saved.

This error does not happen if I upload a file in that newly added setting when submitting the form.

I just wanna mention that pressing "add new setting" button without entering the name or the key of the setting does not throw any errors and create a new setting with empty key

**Voyager::setting('')**

**Comment by marktopper** [comment]
Seems like the file type does not work?
Testing it out myself to confirm.

**Comment by marktopper** [comment]
I can confirm that this bug happens. But it only happens when a file is not selected, meaning that it will happen in the two following cases:

- It will happen if there is no item and you do not add one
- It will also happen if there is a item, but you do not change it

**Comment by marktopper** [comment]
Just fixed this in #690.

Can you test it out using the `fix/issue-687` branch?

**Comment by hazem1taha** [comment]
Thanks @marktopper 

I'll test it and post the result.

**Comment by marktopper** [comment]
Thanks

**Comment by hazem1taha** [comment]
I tested it and it is working @marktopper
