### ISSUE TITLE
[Purpose of v0.12] Separation of config files

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#691]
*EDIT:* Move to `v0.12`

Currently we have one configuration file for Voyager.

For `v0.11` we will be having multiple files in the following structure:

```
- config
| - voyager
  | - database.php
  | - widgets.php
  | - storage.php
  | - user.php
  | - assets.php
```

**Comment by Webpicasso** [comment]
@marktopper: just my thoughts about this change: are you sure that voyager config can become so big that we need multiple files? Laravel has already enough files to load ... 
(BTW: you did an amazing job and I like voyager so much)

**Comment by marktopper** [comment]
Well, I see your point.
I just like to get this done before the configuration file gets to heavy.
I'm however open for a discussion on whether or not to separate things.

**Comment by Frondor** [comment]
You're supposed to `config:cache` on productions so the number of config files shouldn't be a problem.
Configs are better than querying DB for settings.

**Comment by marktopper** [comment]
The configuration files are not that big yet so I decided to move this to `v0.12`.

**Comment by handiwijoyo** [comment]
Any update about this? 

I will close this for now, since we are still not need this feature in the moment.
