### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by ctf0** [thedevdojo/voyager#696]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.13
- PHP Version: 7.0.15
- Database Driver & Version: MySQL 5.5.38

### Description:
- saving `user_id` as `uuid` doesnt work with the `voyager.users.show` route

- following the tutorial https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-relationships for trying to add a new relation bettwen a new model `article` and `user` through `author_id ` give error
```
SQLSTATE[HY000]: General error: 1364 Field 'author_id' doesn't have a default value
```

- console error once we enter a folder with images in media manager view.
```json
Request URL:http://localhost:8000/admin/%7B%7B%20selected_file.path%20%7D%7D
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:8000
```

- table altering
    - changing a field type from `Unique` to `none` doesnt get saved
    - altering a field order doesnt get saved

**Comment by Frondor** [comment]
> adding new field for the user table, then making it available through bread, become only available for read but not with add/edit/remove.

Yup, that's because `user` bread has its own view, overriding the default BREAD views.
This is most likely to change in the future #673 point 1

**Comment by marktopper** [comment]
I think we should remove the default `user` BREAD view for `v0.11`. Thoughts?

**Comment by ctf0** [comment]
any maybe clean up the view files more ex.
- get rid of the php code
- reformat the html to be more easier to reason with
- etc...

**Comment by ctf0** [comment]
@marktopper atm voyager media manager relay on the default storage, i believe it would better if we added a new attr under the storage array so the user can decide which disk he wants to use & maybe add an option to use multiple disks.

also added new error
> - commenting out `storage.subfolder` or using `public` disk, make the user avatar disappear.

**Comment by marktopper** [comment]
@ctf0: Wonderful idea.

```
'storage' => [
    'disk' => 'local',
    'subfolder' => 'public/'
],
```

I am more than open for pull requests on this one.

**Comment by marktopper** [comment]
About the error you are getting when commenting out the `storage.subfolder`. It is because there are no defaults for that configuration. Might however be added to avoid this.

**Comment by marktopper** [comment]
> * get rid of the php code
> * reformat the html to be more easier to reason with

We also indeed need some refactoring 👍

**Comment by ctf0** [comment]
the issue with `storage.subfolder` that its being called in the view files for the user avatars, which should be resolved from the `VoyagerMediaController`, so all the media files can follow the same rules.

disk option is added.

and new error
> - console error once we enter a folder with images in media manager view.

**Comment by marktopper** [comment]
There are more in it then that in order to get it to work, the controllers needs to actually use the disk.

Can you open a separate issue for that since it's a big issue.

**Comment by ctf0** [comment]
i actually solved everything, the latest commit is incomplete, i will add the rest now.

however i only have 2 issues

1- the console error
2- if we made a new disk like
```php
'another' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public/again'),
            'visibility' => 'public',
        ],
```
the images doesnt show up
![screen shot 2017-02-08 at 12 57 54 pm](https://cloud.githubusercontent.com/assets/7388088/22734423/4eb83bac-edfe-11e6-80d0-e8dc2c405f57.jpg)

not sure why yet.

**Comment by marktopper** [comment]
Ohh nice work @ctf0.

However there might be a need for another configuration to set the public path.

Since in this case it would probably need to be `/storage/another/xxx.png` instead of just `/storage/xxx.png`.

**Comment by ctf0** [comment]
actually if we used something else like `locale` or `public` we can upload a file to the root folder and the image will be served through `storage/xxx.png` as usual 😢

**Comment by marktopper** [comment]
However I still believe it would be a good idea to make it into a configuration, so that users can do it their prefered way.

```
'storage' => [
    'disk' => 'local',
    'folder' => 'public/',
    'public' => 'storage/'
],
```
> Files located in: `APP-ROOT/storage/app/public/xxx.png`.
> Files served in url as: `http://site.com/storage/xxx.png`.

Changing the `folder` just changes where the files are saved, and changing the `public` just changes where the system tries to serve it in the browser.

**Comment by marktopper** [comment]
So this is actually just the same as you did in https://github.com/the-control-group/voyager/issues/696#issuecomment-278296786

**Comment by ctf0** [comment]
that's why we have the symlink for the `app/storage` to do exactly that
> Files located in: APP-ROOT/storage/app/public/xxx.png.
> Files served in url as: http://site.com/storage/xxx.png.

also relaying solely on the file system disks is better than adding extra configs for voyage, because now the user can modify the data inside the single disk from anywhere without giving second thoughts & it makes maintainability easier and less learning curve through out the entire app.

**Comment by marktopper** [comment]
Good point @ctf0 👍

**Comment by marktopper** [comment]
I have added this to the milestone of `v0.11`.
Hopefully we can get those things done in time.

**Comment by marktopper** [comment]
Closing as all of this might have been done by now.

**Comment by ctf0** [comment]
@marktopper btw did those pass the test in ur build ?
> - changing a field type from Unique to none doesnt get saved
> - altering a field order doesnt get saved

also u have any release date for v0.11 ? maybe we can add a new tab to the website for announcements :1st_place_medal:

**Comment by marktopper** [comment]
`v0.11` is released :)

**Comment by marktopper** [comment]
Also I will have to remake the entire test for the database since it have been changed in `v0.11`

**Comment by ctf0** [comment]
awesome 👯  

**Update**
- <s>changing a field type from Unique to none doesnt get saved</s> **is fixed**
