### ISSUE TITLE
Pages Documentation Help ?? 

### ISSUE THREAD

**Issue by redsoxfan2499** [thedevdojo/voyager#698]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.12
- PHP Version: 5.6.24
- Database Driver & Version:
   mysql 
### Description:
This is not necessarily an issue but I am trying to figure out the pages system. I have watched the videos and the documentation and cannot figure out how to see any pages on the front end. So right now there is the Demo scurvy-page.   So I here is my base URL:  

http://localhost/voyager/public/ 

I have tried many different combos and cannot get to the page. In the admin section I can see the Edit/View mode of the page but cannot get to the page from a straight URL.

http://localhost/voyager/public/admin/scurvy-page 

http://localhost/voyager/public/scurvy-page

http://localhost/voyager/public/pages/scurvy-page

I am running under admin which has permissions to see everything. 

My assumption is since this was created under the Voyager system, it will use the Voyager routes. 

So I am looking for documentation on setting up pages and seeing them from the front-end. 

Do we need to setup our own Routes for each page we create under Voyager? Or does the pages use the current Voyager routes?  

Thanks in advanced for all the help!

**Comment by marktopper** [comment]
Here is a small gist with a sample of how to do this.

https://gist.github.com/marktopper/ad3f8048a1a7bf55a5fcc747745d92ec
