### ISSUE TITLE
request the document for using the voyager

### ISSUE THREAD

**Issue by donguyenha** [thedevdojo/voyager#7]
try to access to the website https://the-control-group.github.io/voyager/docs/index.html
and the return response say 
`Y'arr!!! These docs be coming soon!`

**Comment by noxify** [comment]
fixed? I can see the documentation.

**Comment by tnylea** [comment]
haha, yeah. I'm still working on the docs at the moment. Should be updated daily and I plan on getting a lot in there this week.
