### ISSUE TITLE
Other Language??

### ISSUE THREAD

**Issue by Omazon** [thedevdojo/voyager#70]
I like this admin, but, its have other language, spanish, francais, etc, not only english??

**Comment by afsardo** [comment]
That is a really big feature, maybe you can try and send a PR to motivate others working on it ^^, we need people to translate all things to those languages and normalise all views to conform with the selected language.

But definitely makes sense to make it happen ;) Cool suggestion.

**Comment by kristiandrucker** [comment]
I could translate it to Slovak but can you make a base English translation?

**Comment by marktopper** [comment]
I think we will wait until Laravel 5.4 is out, since it comes with a whole new way to do translations.

**Comment by mr0bles** [comment]
I can translate it easy to spanish if someone make the BASE.json

**Comment by marktopper** [comment]
Nice @mr0bles.
I'm currently working on the option to translate the BREAD 🍞, and after that I will go ahead and do a translation of the Voyager system itself. Then I will ping you @mr0bles.

**Comment by victorpierredev** [comment]
I'll be happy to help with Portuguese translations.

**Comment by jehanf** [comment]
Same here for French translations.

**Comment by marktopper** [comment]
You can follow my work on making the BREAD translatable at #561

**Comment by lucacalcaterra** [comment]
I can translate it in italian ...Very useful feature

**Comment by aak74** [comment]
I'll be happy to help with Russian translations.

**Comment by abdullahmaswadeh** [comment]
I can help with Arabic translation if you are planning to support RTL.

**Comment by marktopper** [comment]
We are working on RTL #789

**Comment by akazorg** [comment]
Closing issue, merged with #1370.

**Comment by phoorooz** [comment]
im here for persian translation

**Comment by fletch3555** [comment]
@mrarteh, please don't comment on issues that have been closed for so long (8 months in this case).

**Comment by almokhtarbr** [comment]
i'm here for arabic translation  , and thanks a lot for rtl support
