### ISSUE TITLE
Display Menu Builder Items as Parents and Children [Solved]

### ISSUE THREAD

**Issue by c0d3sling3r** [thedevdojo/voyager#701]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.13
- PHP Version:
- Database Driver & Version:

### Description:
I want to know if you've considered how to use `Menu` class to show parent menu items and children(if exists) for each of them?
I'm sticking on this for days.

**Comment by marktopper** [comment]
There are some main issues when it comes to the Menu builder. It does not make it easy enough to extend or use a custom view when there are subclasses.
I think the Menu class should be rewritten from scratch.

**Comment by c0d3sling3r** [comment]
I finally solved the problem. I put the `<?= Menu::display('main_menu', 'main_menu_view'); ?>` in `master.blade.php` file and put following in `main_menu_view.blade.php`:
```
<?php
    $var = "HI";
    $menu_items = array();
    for( $i = 0; $i < sizeof($items); $i++) {
        $menu_items[$i] = $items[$i];
    }
    $level = null;
    function menuOutput($array, $level) {
        $output = "<ul>";
        foreach ($array as $i) {
            if ($i->parent_id == $level) {
                $output = $output . "<li><a href='" . $i->url . "'>" . $i->title . "</a>" . menuOutput($array, $i->id) . "</li>";
            }
        }
        $output = $output . "</ul>";
        return $output;
    }
    echo menuOutput($menu_items, $level);
?>
```

**Comment by marktopper** [comment]
Does this works for a multi level menu?

**Comment by Frondor** [comment]
@marktopper shouldn't we use a package for this? There are a lot of `menu` packages...

**Comment by marktopper** [comment]
The menu class have been remade in `v0.11`.

**Comment by marktopper** [comment]
@Frondor: Also we could use a package for this in the future 👍
