### ISSUE TITLE
Ability to override relationship name

### ISSUE THREAD

**Issue by sidis405** [thedevdojo/voyager#703]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.13
- PHP Version: 7.0.8
- Database Driver & Version: Mysql 5.7.17

First things first, thank you for creating such a great tool.
As of now it is the best i've used (and i've had my fair share of attempts with admin tools).

Now, i have voyager working and property configured. Creating tables, models, BREAD and menus.
So far all good.

The issue i am having has to do with setting up the relationships on BREAD according to the documentation here https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-relationships .

According to this logic, if a have a User, and this user belongs to a Team model (whilst having a team_id in the user table) i would need to create a teamId() relationship.

And that does not sound quite right. I would also add that it's a bit counterintuitive as far as doing things the Laravel-way goes.

If i want to get the user's team, the relationship should be team() and not teamId(). 
After all i am getting back a Team instance from the relationship and not the id of that instance, which i can access with user->team->id().

I chased this all the way down to BreadRelationshipParser but i really don't want to mess with vendor code for obvious reasons.

Now, my question is: Is there a way to override the relationship name that Voyager expects to find on the model?
In this case from teamId() to simple team()?

best regards and thank you in advance

**Comment by marktopper** [comment]
I see, this should indeed be made into a configuration.
Maybe it could use a `method` value from the JSON parameters like this:

```
{
    "relationship": {
        "method": "team"
    }
}
```

**Comment by sidis405** [comment]
@marktopper Absolutely.
Also imagine not only relationships in the conventional sense but also computed and appended fields.

As of now, the package forces a convention that for large or existing projects becomes unsustainable.
In the current case, i'm implementing Voyager on a codebase with about 50 models that have 15-20 relations each.

There is no way i'm duplicating all those methods... :/

**Comment by sidis405** [comment]
I started slowly working on a local patch that might get me rolling for a bit and then if it becomes something solid i will certainly do a pull request but the whole mixup of snake_case and camel_case on BreadRelationshipParser is a bit of a show stopper.

**Comment by marktopper** [comment]
Would be awesome with a pull request for this @sidis405 🎉

**Comment by sidis405** [comment]
:) Yea i'd love to help. And now i'm also noticing that this logic is baked in a lot of places. Including blade files. Perhaps because of the way the datatype is saved.

Well, i need to get it working for my project one way or another as i really enjoy this package.
I'll make sure to share.

**Comment by antranapp** [comment]
@sidis405 this would be a huge improvement for voyager. looking forward to your pull request.

**Comment by sidis405** [comment]
@peacemoon Indeed it would be nice. All and all i slowly got it working with e correct relationships being shown but there are still some doubtful areas, say in BreadRelationshipParser where i don't see any support code for ManyToMany relationships making it present on Add/Edit but not on browse and read.
I added it but i would need to openly discuss with someone that is familiar with the file to see if i'm implementing in the spirit of the voyager logic.

**Comment by sidis405** [comment]
Okay i think i got something. 
If i make a quick pull request does someone wanna take a look at it for additional stuff we can add?

So far basically i have the following implemented :

- Override method name as @marktopper suggested
```
{
    "relationship": {
        "method": "team"
    }
}
```
- Applying relationship data, options and labels correctly on Browse, Read, Create, Edit
- Solve field name collision on ManyToMany Relationships by setting the options the following way
```
{
    "relationship": {
        "key": "sports.id",
        "label": "name",
        "method": "sports"
    }
}
```
I don't know how this worked before but it never worked for me correctly as the 'id' field was not unique

best
sid

**Comment by marktopper** [comment]
If you make a pull request I will test it out and do a review. 👍

**Comment by sidis405** [comment]
#715
