### ISSUE TITLE
Please update, it for laravel 5.4, I cannot use this on my project.

### ISSUE THREAD

**Issue by adityapandey9** [thedevdojo/voyager#704]
- Laravel Version: #.#.# 5.4
- Voyager Version: #.#.# 0.13.10
- PHP Version: 7.0.7
- Database Driver & Version: mysql

**Comment by renamate** [comment]
I have the same question some of these other packages already allow to use the latest version of Laravel:
https://github.com/appzcoder/laravel-admin

https://github.com/z-song/laravel-admin

https://github.com/LaravelRUS/SleepingOwlAdmin

https://github.com/z-song/laravel-admin

https://github.com/appzcoder/laravel-admin

**Comment by PwrSrg** [comment]
+1 for Laravel 5.4

**Comment by zietbukuel** [comment]
Check #626

**Comment by marktopper** [comment]
`v0.11` supports Laravel 5.4 and is set to have a estimated release date this sunday.

**Comment by miraage** [comment]
@marktopper is it safe to use release/v0.11 branch today for educational purpose?

**Comment by marktopper** [comment]
@miraage It is save, however there will still come breaking changes to it. So please notice that when updating to the latest commit of it.

**Comment by adityapandey9** [comment]
Thanks for the info. @marktopper

**Comment by kchat001** [comment]
Hi @marktopper,

I just wanted to ask when the release date for v0.11 is going to be, since I'm working on a Laravel 5.4 project right now and can't wait for it to be released.

Thanks

**Comment by marktopper** [comment]
@kchat001: A few days ;)

**Comment by DrudgeRajen** [comment]
+1 for laravel  5.4

**Comment by marktopper** [comment]
`v0.11.0` is released with Laravel 5.4 support.
