### ISSUE TITLE
Delete model when database table is deleted

### ISSUE THREAD

**Issue by filipsobol** [thedevdojo/voyager#71]
I'm not sure if it's intended or not, but when you delete database table from admin panel, model that was created with it is not deleted.

Edit:
Models are created using artisan make:model command, but there is no command to delete it. I guess it must be deleted from App folder directly.

**Comment by Laran01** [comment]
Models are created using artisan make:model command, but there is no command to delete it. I guess it must be deleted from App folder directly.

**Comment by marktopper** [comment]
I'm open for pull requests on this, as long as it does not require a model to be deleted.
Meaning that an option should be chosen wether or not to delete the model if existing.

**Comment by fletch3555** [comment]
I'm going to close this for now since it's so old.  We may revisit this after the 1.0 release.  In the meantime, if anyone wants to tackle it, we're certainly open to pull requests as @marktopper said
