### ISSUE TITLE
Google Analytic on a Voyager website

### ISSUE THREAD

**Issue by Fredmowitz** [thedevdojo/voyager#711]
Hi guys. 

Is there anyone of you kind souls who can tell me how I get Google Analytics integrated on my website? 
I use Voyager. 

Thank you for your advice and help. 

Best regards, 
Frederik

**Comment by sidis405** [comment]
Hey @Fredmowitz 

 - go to https://console.developers.google.com/ 
 - make an application
 - choose analytics API and create a Client ID.
 - head to Credentials (on the left side navigation)
 - Edit the token you just created and  make sure to add the URL(s) you will be running Voyager on.
 - disable adblock for the voyager page on your browser if you have it as it will block 

You should be good to go.

Best

**Comment by marktopper** [comment]
Thanks @sidis405. From this I have been creating a [blog post](https://webman.io/blog/post/setup-google-analytics-for-laravel-voyager).

**Comment by sidis405** [comment]
Great, man! That's awesome.
It's amazing how non intuitive and awkwardly documented the Google Dev Console is.

I'm sure this'll help a bunch of people :)

**Comment by marktopper** [comment]
Agreed, took me hours to get make my own client ID work 😂

**Comment by troix1** [comment]
@marktopper I followed your blog post which is great by the way, I do get that yellow button and I can log in but then I only get displayed a line of text instead of analytics: ```You are logged in as: ***@***.com```

Is it possible it needs some time to process and collect data?

**EDIT: It started working I was messing with adding/changing user privileges under User manager in Analytics**

EDIT2: I am still getting some errors, Analytics load but show no actual data. Console log:
```
admin:749 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at admin:749
admin:589 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at admin:589
admin:721 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at admin:721
admin:698 TypeError: Cannot read property 'map' of undefined
    at admin:660
(anonymous) @ admin:698

**Comment by marktopper** [comment]
@troix1: Please ensure that your user have read access to at least one Google Analytics site.
I had those issues when I logged in to a Google account without any Google Analytics sites.

**Comment by shrihub** [comment]
I had this same issue where even after adding analytics client ID in voyager, I was getting only this line "You are logged in as: ***@***.com" in the dashboard report section.  Actually, I had to enable google analytics API.

Go to https://console.developers.google.com -> select Library -> search for 'analytics' keyword -> click on 'Analytics API' -> click on Enable

![screen shot 2017-11-11 at 11 26 21 am](https://user-images.githubusercontent.com/4091734/32686831-eac37990-c6d3-11e7-9dcc-6a935687da96.png)
![screen shot 2017-11-11 at 11 26 36 am](https://user-images.githubusercontent.com/4091734/32686833-eb326bf2-c6d3-11e7-9fa3-7c5ff93ad1c4.png)
![screen shot 2017-11-11 at 11 28 32 am](https://user-images.githubusercontent.com/4091734/32686834-eba1e572-c6d3-11e7-8c77-2b2fb95a5cb2.png)

**Comment by marktopper** [comment]
@ShriHub This have been closed for quite a while, instead I prefer if you would open a new issue.
Thanks.

**Comment by ghost** [comment]
why this 
![as](https://user-images.githubusercontent.com/31731443/41447577-28312f58-7056-11e8-88b8-948649b9d183.PNG)

**Comment by fletch3555** [comment]
As mentioned in the comment directly above yours @AhmedElsaeedy, "This have been closed for quite a while, instead I prefer if you would open a new issue."
