### ISSUE TITLE
RESTful Nested Resource - Routing & View

### ISSUE THREAD

**Issue by ihsanberahim** [thedevdojo/voyager#713]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.13
- PHP Version: 7
- Database Driver & Version: Mysql 5.7

### Description:
I want to create a bread for book type and the pages.

Issue 1 - Routing & View (solved)
/admin/books - works
/admin/book-pages - works
/admin/books/{book_id}/book-pages/create - no idea
/admin/books/{book_id}/book-pages/{book_page_id}/edit - no idea

Issue 2 - [Filter dataTypeContent array](https://github.com/the-control-group/voyager/issues/714) (solved)

`$dataTypeContent` in `views/vendor/voyager/{slug}/browse.blade.php`

**Comment by ihsanberahim** [comment]
Lucky. I managed to do it.

1) modify routes/web.php
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    $namespacePrefix = '\\'.config('voyager.controllers.namespace', 'TCG\\Voyager\\Http\\Controllers').'\\';

    Route::resource('books.book-pages', $namespacePrefix.'VoyagerBreadController');
});
```

2) duplicate & modify
`views/vendor/voyager/posts`
 to  
`views/vendor/voyager/books`
and 
`views/vendor/voyager/book-pages`

3) use route
route('book.book-pages.index', Request::route('book'));
route('book.book-pages.create', ['book'=> Request::route('book')]);
route('book.book-pages.edit', ['book'=> Request::route('book'), 'book_page'=> $data->id]);

**Comment by marktopper** [comment]
Great that you got it to work.
I am closing the issue then.

**Comment by ihsanberahim** [comment]
Sorry @marktopper. I got 2nd issue "Filter dataTypeContent array"
