### ISSUE TITLE
Parent id category warning

### ISSUE THREAD

**Issue by turtuga** [thedevdojo/voyager#716]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.13
- PHP Version: 7.0.14
- Database Driver & Version: mysql 5.5.53
  
Parent id category warning

When I go to edit a category I have this warning
![1](http://i.imgur.com/X0R9TV3.png)

Now I change in models category 
`public function parent_id()`
to
`public function parentId()`
![1](http://i.imgur.com/6MM6b0w.png)

but selected value when I edit category is always NULL then I change this in blade template 
Line 104 `$selected_value = old($row->field);`
to 
`$selected_value = $dataTypeContent->parent_id;`

And now works this is an issue or I'm doing it wrong?

**Comment by marktopper** [comment]
Fixed in #717.

For now you can use `dev-fix-717` as version.
Will release a new version for you later today.
