### ISSUE TITLE
Error creating a new page

### ISSUE THREAD

**Issue by Omazon** [thedevdojo/voyager#72]
A clean installation,is not working create new page, error
Warning: 1265 Data truncated for column 'status' at row 1
![image](https://cloud.githubusercontent.com/assets/22031788/19955434/105a1e56-a147-11e6-9621-e29f84fbe26e.png)

**Comment by ClausMunch** [comment]
If you just either write INACTIVE or ACTIVE in the status field, it works.
It has something to do with the default value.

**Comment by Omazon** [comment]
If, works well, would recommend putting a dropdown for cases as well

**Comment by tnylea** [comment]
Thanks for pointing that out. Adding a project to store these fixes and will get them implemented soon. Checkout the project here: https://github.com/the-control-group/voyager/projects/1

Appreciate it 👍
