### ISSUE TITLE
BREAD Dropdown Issue

### ISSUE THREAD

**Issue by genleeshin** [thedevdojo/voyager#723]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.14
- PHP Version: 7.1
- Database Driver & Version: mysql 5.6

### Description:

When editing a BREAD, the dropdown always selecting the default value instead of the database column value

my json file for the dropwdown field:

{
    "default": "0",
    "options": {
        "0": "NO",
        "1": "YES"
    }
}

### Steps To Reproduce:

**Comment by saranshdhingra** [comment]
I have to agree, I saw this bug in a previous version, but didn't contribute here.
Today I pulled the code to replicate and help, but the bug isn't there(_fixed in a previous version perhaps?_)

I am using the same versions as yours and here are my screens:
## Dropdown JSON
![Dropdown JSON](http://image.prntscr.com/image/514b7c171e2343ffb568c3d0b4d41ed2.png)

## Product using default value
![Product using default value](http://image.prntscr.com/image/d51e522ead0c49d1a073d7191c34e7a9.png)

## Product not using default value
![Product not using default value](http://image.prntscr.com/image/1f3f6774d1a54fe5afd6167444accf0f.png)

Probably the only difference is, I created the **table**,**migration** and **model** from voyager panel itself. Could that be it?

**Comment by Frondor** [comment]
I've been improving the default values quite a lot for those fields. This has to be working as expected in v0.10.14 as @supernova13892 says.
There is another PR going to v0.11 branch, I think there are more improvements on that one. So yeah, check again that you're running latest version, and wait for v0.11

**Comment by genleeshin** [comment]
@supernova13892 and @Frondor, thanks for your reply, I have tried with a fresh install but the result is still the same, after inspecting the html source code I have found that voyager is changing my column name 'has_choice' to 'hasChoice', and this seems to be causing the problem. Also when trying to save it, database throwing an error saying 'has_choice' cannot be null.

**Comment by marktopper** [comment]
What @Frondor is saying is that this should be fixed in `v0.11`, switch should be released in a few days.

**Comment by marktopper** [comment]
Please use version `v0.11.0`.

**Comment by TomoGlavas** [comment]
I am having the same problem in v0.11.14! :(

**Comment by TomoGlavas** [comment]
The dropdown won't accept a null default value, unfortunately.

**Comment by fletch3555** [comment]
@TomoGlavas, please open your own issue instead of commenting on old issues

**Comment by venukommu** [comment]
@genleeshin - Could you please help to fix the same for dynamic Drop down instead of expected two values.  You can find more details in the another issue that i created few minutes back.
https://github.com/the-control-group/voyager/issues/2508

Thanks & Regards
Venu Kommu

**Comment by fletch3555** [comment]
@venukommu, please don't comment in issues that have been closed and untouched for so long.  If you already have an open issue, we'll get to it soon enough.  Please be patient
