### ISSUE TITLE
Trouble installing with dependencies L5.4 Voyager 0.10.14

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#724]
- Laravel Version: 5.4.11
- Voyager Version: 0.10.14
- PHP Version: 7.0.8
- Database Driver & Version: 

### Description:
I can't install voyager into a brand new laravel 5.4 app, I saw you were updating to work with 5.4 on 12th February so I waited. I recieve errors due to dependencies:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tcg/voyager ^0.10.14 -> satisfiable by tcg/voyager[v0.10.14].
    - Conclusion: remove laravel/framework v5.4.11
    - Conclusion: don't install laravel/framework v5.4.11
    - tcg/voyager v0.10.14 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.11
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.11
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.11
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.11
    - Installation request for laravel/framework (locked at v5.4.11, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.11].

### Steps To Reproduce:

composer create new laravel project.
composer require tcg/voyager

**Comment by jim1506** [comment]
I also received exactly the same problem

**Comment by marktopper** [comment]
Laravel 5.4 support will come along with `v0.11`.
It should hopefully be ready for release in just a few days.

You can follow up here: https://github.com/the-control-group/voyager/pull/718

**Comment by Promixius** [comment]
If you can't wait you can always run: 
composer require "tcg/voyager:dev-laravel-54-support"

**Comment by Philwn** [comment]
Thanks for the prompt replies, I read the issue the other day and thought it was coming in Sundays update so once it updated I tried, my bad. Look forward to trialling it in a few days.
