### ISSUE TITLE
dev 0.11 new text field in settings will fail

### ISSUE THREAD

**Issue by Promixius** [thedevdojo/voyager#728]
- Laravel Version: 5.4.x
- Voyager Version: 0.11.x
- PHP Version: 7.0
- Database Driver & Version: mysql 5.7

### Description:
Creating a new textarea or textfield will fail as it's missing a non optional field "details" which can not be left blank but it's not present on the form.
It will produce this message:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'details' cannot be null (SQL: insert into `settings` (`display_name`, `key`, `type`, `details`, `order`, `value`) values (Name, Key, text, , 10, ))`

Seems like either the field should have that field as nullable or if it's actually needed on these 2 types have the form updated to omit this error. 

### Steps To Reproduce:
Fresh Laravel and Voyager install
Attempt to create a text or textarea in the sittings page.

**Comment by Frondor** [comment]
Possible duplicate #706

**Comment by marktopper** [comment]
Please use version `v0.11.0`.
