### ISSUE TITLE
Problem with rename the App name

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#73]
I rename the App via 
`php artisan app:name Pollr`

When I install via voyager:install something wrong with service call. I checked in directory
Vendor\tcg\voyager\src\controllers
most of them still called App as the prefix, why not adapt to the new App Name?
`use {App}\Http\Requests;`
`use {App}\Http\Controllers\Controller;`

**Comment by marktopper** [comment]
I'm open for pull requests.

**Comment by followtheart** [comment]
Did we have the method getNamespace?
![qq 20161201082901](https://cloud.githubusercontent.com/assets/7168292/20777184/5581db1c-b7a0-11e6-91d6-2531ee44f8de.png)

**Comment by fletch3555** [comment]
Apologies. That was a typo that slipped past. It has since been resolved. If you run `composer update`, that should resolve it.

**Comment by followtheart** [comment]
It works, 😃 😃 😃
