### ISSUE TITLE
The field deleted_at is required and make a soft delete to the record when it is created

### ISSUE THREAD

**Issue by renamate** [thedevdojo/voyager#730]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.13
- PHP Version: PHP 7.1.1
- Database Driver & Version: innodb 5.6.32-79.0

### Description:
When I try to create a product that has the attribute deleted_at I get the following error:

> QueryException in Connection.php line 770:
> SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '' for column 'deleted_at' at row 1 (SQL: insert into `medicos` (`rut`, `dv`, `nombres`, `apellidoPaterno`, `apellidoMaterno`, `email`, `fono`, `deleted_at`, `especialidad`, `created_at`, `updated_at`) values (22345677, 6, asdasdasd, asdsadasd, asdasdasd, otro@otro.com, 45654645646, , asdasd, 2017-02-13 00:00:00, 2017-02-13 21:32:06))

And if I enter the date accordingly it is as if the record was deleted and I have to go to the database to set deleted_at  to null to see the record.
**Please I need help to solve this problem.**

### Steps To Reproduce:

1. Fresh installation of laravel and voyager
2. Creation of table in database with soft deleting
3. Create a BREAD for it
4. Enter data

Sorry for my English, I'm from Chile but I offer to translate Voyager into Spanish when the base translation is ready.

**Comment by Frondor** [comment]
Possible duplicate #706

**Comment by saranshdhingra** [comment]
I don't think this is voyager's fault in any way. If you simply want to get rid of this problem, uncheck the options in your BREAD.
Here is an example:
![Uncheck these options](http://image.prntscr.com/image/a2c5fe86205c4d249cb8183e05b4cbc4.png)

Another way might be to simply add the default of **deleted_at** to **null**.

**Comment by renamate** [comment]
I update using composer update 0.10.14 version and configure to this way the voyager BREAD:
![image](https://cloud.githubusercontent.com/assets/6330771/22941645/11bd33f8-f2c5-11e6-954a-72a432eb619c.png)

I suggest that this configuration could be by default when creating a BREAD that contains these attributes created_at, updated_at, deleted_at.

And maybe this fix the #674 issue too.

Thanks  @supernova13892

**Comment by Frondor** [comment]
It's a pretty straight forward configuration. You should't include `$timestamps` fields in your bread (add/edit) views anyhow. That logic have to be handled directly by eloquent.

**Comment by renamate** [comment]
ok thank @Frondor

**Comment by wael986** [comment]
Hi thank you it was really simple to get the soft delete working
the problem is that i cannot load the deleted items in the admin panel!!
i need to restore some items or edit them!!
[https://image.ibb.co/iQGFhb/deleted.png
](https://image.ibb.co/iQGFhb/deleted.png)
as u can see the table is empty but in the DB i already have some deleted products!
@Frondor  can u help plz

**Comment by fletch3555** [comment]
@wael986, please don't comment on very old closed issues.  This one in particular has been closed for nearly 9 months, and was opened against a MUCH older version of Voyager.
