### ISSUE TITLE
ErrorException in BreadRelationshipParser.php line 82: Trying to get property of non-object on existing Models

### ISSUE THREAD

**Issue by paperscissors** [thedevdojo/voyager#734]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.14
- PHP Version: 7.1.0
- Database Driver & Version: mysql 5.7.16

### Description:
I'm adding BREAD for some existing models. When Voyager tries to go to the Browse for any of the models I get the following error:

`ErrorException in BreadRelationshipParser.php line 82: Trying to get property of non-object`

On further investigation `$bread_data` on line 81 is returning null:
```
$bread_data = $dataType->browseRows->where('field', $field)->first();                
 $relationData = json_decode($bread_data->details)->relationship;
```

### Steps To Reproduce:

I do have `Cviebrock\EloquentSluggable\Sluggable` on these models as a trait, so maybe this is related?

**Comment by marktopper** [comment]
Please give us the full stacktrace.
