### ISSUE TITLE
Creating / updating a post doesn't update category

### ISSUE THREAD

**Issue by Oxbobby** [thedevdojo/voyager#748]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.15
- PHP Version: 5.6
- Database Driver & Version: MySQL, 5.6

### Description:
When I try to create / update a post, the category for that post doesn't get updated.

### Steps To Reproduce:
Fresh install of laravel 5.3, fresh install of voyager via composer require and seed data through voyager's seeder.

Go to admin -> post, try creating a new post and attach a category. In the database, the category is for a post is always NULL.

**Comment by Fisiu** [comment]
Edit posts BREAD and change `category_id` from `Text Box` to `Select Dropdown`.

I'm not sure where this is set in source code. It also should be adjusted to make it working with fresh installations.

**Comment by Frondor** [comment]
We clearly have problems with documentation :D

**Comment by marktopper** [comment]
I need to get working on the documentation, also since `v0.11` just got out.

**Comment by turtuga** [comment]
Fixed in v0.11
