### ISSUE TITLE
Make it possible to add custom form paremeters to the edit/add page

### ISSUE THREAD

**Issue by DaRkViRuS2012** [thedevdojo/voyager#75]
first of all thanks for this great job keep it up.
where can i edit the create new item page .
I am trying to build a restaurant admin page and i want to add a map to the edit page so i can set the latitude and longitude when i drag the marker.

**Comment by marktopper** [comment]
We are currently working on making it more extendable, however I will ensure that this becomes possible to modify in a way that allows you to add new form parameters to the edit/add page and rules for them as well.

**Comment by fletch3555** [comment]
Views can be overridden as described here: https://the-control-group.github.io/voyager/docs/v0.10/#customization-overriding-views
