### ISSUE TITLE
Empty required field returns error instead of prompting.

### ISSUE THREAD

**Issue by tollanes** [thedevdojo/voyager#753]
- Laravel Version: 5.3.30
- Voyager Version: 0.10.15
- PHP Version: 7.0.7
- Database Driver & Version: MySQL 5.5.49

### Description:
This is about he BREAD editor:
Don't know if it's intended, but I would expect to be asked to fill in the field if it's not set to "nullable". Wouldn't it be as simple as adding the "required" field in HTML if said field is not set to "nullable"? Don't know if this is intended or not added yet. But I think it would be a decent thing to have as its better to be safe than sorry. I guess this is a feature request more than a bug report.

### Steps To Reproduce:
Just leave a required field in the "add new" menu blank and then try to add, you will get a database error because it expected data.

**Comment by Frondor** [comment]
I think that's how Laravel works since 5.2 when they added `nullable` validation field.
Try to set up the validation rules for that field and use `nullable`.

**Comment by marktopper** [comment]
@Frondor is right, but we might need to documentate this.
