### ISSUE TITLE
Adding BREAD - Icon cannot be null

### ISSUE THREAD

**Issue by FrodeMMeling** [thedevdojo/voyager#756]
- Laravel Version: 5.4.12
- Voyager Version: dev-release/v0.11
- PHP Version:7.1.1
- Database Driver & Version: MySQL 5.7.17

### Description:
Try to add a BREAD for a very simple table. Only timestamps and a text name.
Generating BREAD causes this error:
[link to error](https://www.dropbox.com/s/kwznu5yny8hwvvq/Screenshot%202017-02-17%2012.26.30.png?dl=0)

Must be a bug, since icon is optional

### Steps To Reproduce:
Do not set icon when generating BREAD.

**Comment by marktopper** [comment]
I have now made a commit to the migrations for `v0.11` to enable making `icon` nullable.

Thanks for reporting.
