### ISSUE TITLE
Cannot add new field to User table

### ISSUE THREAD

**Issue by JohanIskandar** [thedevdojo/voyager#761]
Hi,
  
  I want to add a new field named mobile to the User table
  http://localhost:8000/admin/database/users/edit
  
   when I click update, I got the following error message

QueryException in Connection.php line 647:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mobile' in 'field list' (SQL: insert into `users` (`name`, `email`, `password`, `avatar`, `role_id`, `mobile`, `updated_at`, `created_at`) values (Evy, evy@gmail.com, $2y$10$mHaXvEqGfNYDjiSoP2cBkeIHV2u2Ha.JihcV1VmPNR4YKFPdqwvqm, users/February2017/CoL3lxgpfdF3eax0j1mz.jpg, 3, , 2017-02-18 05:43:49, 2017-02-18 05:43:49))

   Could anyone tell me how to resolve this issue, thank you.

regards,

Johan

**Comment by marktopper** [comment]
Please ensure that you have the column added `mobile` in your `users` table.
