### ISSUE TITLE
How do I properly output data from a field with a relationship using blade?

### ISSUE THREAD

**Issue by anderfernandes** [thedevdojo/voyager#762]
Hey, guys. 

I am having a problem trying to call a data field with a relationship using blade. I have followed the steps mentioned in the documentation (https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-relationships) still with no luck. I did exactly as instructed, but on my 'posts' table.

In a page I have a blade @foreach that displays the post fields. All the fields output data as expected, except the post author. I am calling the field using **{{ $posts->authorId()->name }}** and I get the following error:

> Undefined property: Illuminate\Database\Eloquent\Relations\BelongsTo::$name (View: /home/anderson/atom-projects/planeta-gundam/resources/views/blog/index.blade.php)

Am I doing something wrong? I'm using the latest version of Voyager (0.10.15) and Laravel 5.3. Thanks.

![screenshot_20170218_003717](https://cloud.githubusercontent.com/assets/4932608/23091072/fd034212-f572-11e6-967b-698f965a4966.png)

**Comment by marktopper** [comment]
Please read the Laravel documentations about relationships.

```
{{ $post->authorId()->first()->name }}
```

**Comment by Ahmed-Aboud** [comment]
i don't think you need to add the custom functions now you can $post->authorid->name simply now

**Comment by asharekh** [comment]
tried but says 
Trying to get property of non-object

**Comment by fletch3555** [comment]
This issue has been closed for 8 months now and was for a much older version.  Please open your own issue if you're having trouble

**Comment by isideas** [comment]
I have this problem too, I am new in voyager 1.0 and laravel 5.5.*, I solved in this way

in web.php

Route::get('/posts', function () {
    $posts = TCG\Voyager\Models\Post::all();
    return view('posts', compact('posts'));
});

Route::get('post/{slug}', function($slug){
   $post = TCG\Voyager\Models\Post::where('slug', '=', $slug)->firstOrFail();
  return view('post', compact('post'));
});

and use in view

{{ $post->authorId()->first()->name }}
