### ISSUE TITLE
Url for pages infrontend

### ISSUE THREAD

**Issue by miladrezaei-ai** [thedevdojo/voyager#763]
- Laravel Version: 5.4
- Voyager Version: 0.10.13
- PHP Version:
- Database Driver & Version:

Hi

I created a page in admin panel. I want to know what the url is. Do I have to create controller for this issue or there is a way to show this page in frontend.

Thank you. :)

**Comment by anderfernandes** [comment]
I'm sort of new to Voyager, but in my projects, I used a controller to get the data from the model and send it to my view. Works like a charm, even with the tables created in admin.

You could also use your favorite javascript library (React, Vue, Angular) to get data from an API you create. In Laravel 5.3, there's an API route file. Return the model you want in the Route::get method and boom! It works.

**Comment by miladrezaei-ai** [comment]
Hi

I know about controller and view . There are a menu named page in voyager admin panel ( your_website_url/admin/pages/create ) I meant this type of page . or for example posts .

My question was about this type of post or page.Not a simple page :)

I created a page or a post but I cannot show it on the frontend.

**Comment by anderfernandes** [comment]
You want to display a custom created menu on your frontend? I'm a little confused.
If that's what you want, the documentation explains it really well here: https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-menus

**Comment by miladrezaei-ai** [comment]
Hi

I dont want to load custom created menu on the frontend. I want to load post or page on the frontend. There are two menus on the sidebar. ( Post and Pages :: look at the attach please ). I created post and page and want to load them on the frontend but I dont know what the url is. 

My question is related to them. Is there any solution to get the url of post or page? For example I create a page named about us. How can I show it on the frontend?

![voyager-roles](https://cloud.githubusercontent.com/assets/315735/23095847/6c9b04c6-f626-11e6-911e-764d6e08d2e5.png)

**Comment by anderfernandes** [comment]
In my project I did this with a controller.
You can, let's say, create a view called **about.blade.php** create a **PageController**. Inside of this controller you can create an **about** function that returns the contents of your about us page from the page model. This controller function would look something like:

```
// Show About Page
    public function about()
    {
      // Get content of the about page from the model, feed Page::find with page id
      $about = Page::find(1);
     // Return view with the data
      return view ('about')->with('about', $about);
    }
```
 Then on your view you can print the content of the page using blade. For example, to print the page body you can do something like:

> {!! $about->body !!}

I'm still a beginner in the PHP/Laravel/Voyager world, but that's how I would do it.
