### ISSUE TITLE
Error when adding field to User table

### ISSUE THREAD

**Issue by JohanIskandar** [thedevdojo/voyager#764]
Hi,

  I think I didnot ask my question properly.When I tried to add field mobile to the User table as follows

<img width="1341" alt="addfield" src="https://cloud.githubusercontent.com/assets/1010323/23094165/617d8b40-f626-11e6-881c-032f86db61df.png">

  and when I click on the Update table, I got the following error message. Not sure, why has it got todo with user mail field

![image](https://cloud.githubusercontent.com/assets/1010323/23094178/b01e07e8-f626-11e6-8421-5059fe50e1df.png)

  Any recommendation would be valuable. thank you for your time.

regards,

Johan

**Comment by anderfernandes** [comment]
I wonder if your problem has something to do with https://github.com/the-control-group/voyager/issues/761.

**Comment by abdgad** [comment]
this issue will be fixed in v0.11 which will be released very soon.

**Comment by JohanIskandar** [comment]
Hi,

  How to download and use the latest development package. Can I just use composer update?
is there any specific name that I have to include in .json file, or there is anything else that I have to do, thanks,

regards,

Johan

**Comment by fishmad** [comment]
in your composer.json file

find this:
```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "tcg/voyager": "0.10.*"
    },
```
Change to
```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "tcg/voyager": "dev-release/v0.11"
    },
```

**Then re-run:** 
`composer update`
`php artisan voyager:install`

**Dont forget:**
`php artisan view:clear`
and clear your internet browser cache

**If you have previously published voyager assets to /resources you may need to force a copy/override.**
Just make sure you backup anything you have customised in your /resources folder before running this command.
`php artisan vendor:publish --tag=voyager_assets --force`

**Comment by marktopper** [comment]
`v0.11` have been released now.

**Comment by marktopper** [comment]
Please use version `v0.11.0`.

**Comment by vinci-a-kitchen** [comment]
But 0.11.9 still has the problem

**Comment by abdgad** [comment]
@vinci-a-kitchen Please open a new issue describing the problem in detail.
