### ISSUE TITLE
Failed opening required '\tcg\voyager\src/../helpers.php' 

### ISSUE THREAD

**Issue by fishmad** [thedevdojo/voyager#770]
- Laravel Version: 5.4.*
- Voyager Version: dev-release/v0.11 6503ffe
- PHP Version: 7.0.1.1
- Database Driver & Version: MYSQL mariandb-10.1.9

### Description:
![image](https://cloud.githubusercontent.com/assets/12012101/23096868/e0f4c93a-f679-11e6-9e29-3e4aa7604036.png)

**Issue:**
![image](https://cloud.githubusercontent.com/assets/12012101/23096865/c9331554-f679-11e6-919b-e1b11ca7e6be.png)

**this line**
![image](https://cloud.githubusercontent.com/assets/12012101/23096875/09b57662-f67a-11e6-9f04-8973b8656565.png)

**Change to:**
![image](https://cloud.githubusercontent.com/assets/12012101/23096870/f56c3a60-f679-11e6-8756-8388ee20a04d.png)

### Steps To Reproduce:
Composer update

**Comment by marktopper** [comment]
`v0.11` is released, please use the release instead of this branch, it's fixed there and this branch will soon be deleted.
