### ISSUE TITLE
Deploy voyager project in shared hosting:: Problem in assets path

### ISSUE THREAD

**Issue by biplavraut** [thedevdojo/voyager#773]
- Laravel Version: 5.3.*
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I am New in Laravel 5.3 So can you Please give me a proper instruction while uploading my Voyager Project in my shared hosting. My domain ll look like www.example.com/voyagerproject

**Comment by marktopper** [comment]
Please describe the issue.

**Comment by edisonr17** [comment]
i have a problem with assets path. It is working with php artisan serve but it isn't in htdocs folder of my lampp server

![image](https://cloud.githubusercontent.com/assets/7017442/23138725/fe20f90e-f776-11e6-8f85-7c82771dfd61.png)

**Comment by marktopper** [comment]
Run `php artisan vendor:publish`.
