### ISSUE TITLE
Class 'Menu' not found in vendor/tcg/voyager/resources/views/menus/builder.blade.php

### ISSUE THREAD

**Issue by justinbarkhuff** [thedevdojo/voyager#774]
- Laravel Version: 5.4
- Voyager Version: 0.11.0
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Running a nearly fresh install of Laravel 5.4 and Voyager 0.11 on Homestead. Getting an error when trying to access the "Builder" for the default "admin" menu.  This is is the offending URL:

<code>http://homestead.app/admin/menus/1/builder</code>

And here is the Exception:

<code>Class 'Menu' not found (View: /home/vagrant/myapp/vendor/tcg/voyager/resources/views/menus/builder.blade.php)</code>

### Steps To Reproduce:

1. Fresh laravel and voyager install
2. Login to Voyager
3. Visit the Menu Builder
4. Click the "Builder" button for the default "admin" menu
5. Ta-da!

**Comment by justinbarkhuff** [comment]
Until this is officially fixed, I've temporarily solved it by adding...

<code>'Menu' => TCG\Voyager\Models\Menu::class,</code>

...to my aliases array in config/app.php.

**Comment by marktopper** [comment]
Thanks for reporting, I will fix this. #776
I have just fixed this and it will be available in `v0.11.1` later today.

**Comment by freedom-shelby** [comment]
in the file vendor/tcg/voyager/src/VoyagerServiceProvider.php

add this 2 line

![screenshot_3](https://cloud.githubusercontent.com/assets/9838571/23103164/952377f6-f6c7-11e6-8c4f-43cdc34dbfd7.png)

After - composer dump-auto

May Help.

**Comment by marktopper** [comment]
This have been fixed in `v0.11.1`, which I just tagged.

**Comment by Benyaminrmb** [comment]
i got this error ! 

`
Route [voyager.users.index] not defined. (View: E:\Project\wamp64\www\laravel_news_afshar\vendor\tcg\voyager\resources\views\dimmers.blade.php) (View: E:\Project\wamp64\www\laravel_news_afshar\vendor\tcg\voyager\resources\views\dimmers.blade.php)

`
i added this line in to the my web.php file :

`
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
`

**Comment by marktopper** [comment]
@Benyaminrmb, open another issue

**Comment by maktibab** [comment]
seems not to be fixed in "tcg/voyager": "^0.11.14" ? I have the same issue.

**Comment by fletch3555** [comment]
@maktibab, as @marktopper said a couple weeks ago, please open another issue if you're having trouble.  Commenting on issues that have been closed for multiple months is not helpful.

**Comment by RyanAtregenio8** [comment]
@ArmSALArm thank you... no error now but when i execute , no result be found in front end, i said no new table or something .. 

 <?= Menu::display('main_menu'); ?>

How can i do ?

**Comment by fletch3555** [comment]
@RyanAtregenio8, this has been closed since February. If you still have issues, please open your own issue.

**Comment by RyanAtregenio8** [comment]
No its ok now i found the little problem
