### ISSUE TITLE
Photos do not show when the post after deploying

### ISSUE THREAD

**Issue by vulam8x** [thedevdojo/voyager#775]
Laravel Version: 5.3.30
Voyager Version: 0.10.13
PHP Version: 7.0.8
Database Driver & Version: Mysql 5.7.17

### Description:

- In my localhost: I made successfully upload photos and 
was displayed in the post by: **php artisan storage:link**

- When I made the web deploying to cpanel
 I'm copied everything inside public folders into pubic_html and my rest I move into a local directory and I changed public/index.php:
require __DIR__.'/../bootstrap/autoload.php';
$app = require_once __DIR__.'/../bootstrap/app.php';
to
require __DIR__.'/../local/bootstrap/autoload.php';
$app = require_once __DIR__.'/../local/bootstrap/app.php';

- Everything normal but i'm does not post photos on body insert/edit image! I think the error arising in the path storage_path when I move to **local** folder on server! 

My error: "Missing storage symlink
We could not find a storage symlink. This could cause problems with loading media files from the browser."

Please help me fix!

**Comment by marktopper** [comment]
Sounds like your server does not support the symlink method.
Then you should consider upgrading to `v0.11.0`, that adds support for directly added files to the public path instead of the storage path with symlink.

**Comment by kcpradyp** [comment]
I do have the similar issue.
Can you elaborate how it can be done without symlink??
