### ISSUE TITLE
install into existing database - is 'categories' migration needed?

### ISSUE THREAD

**Issue by Bulmer** [thedevdojo/voyager#777]
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.6.30-1 - (Debian)

**Comment by marktopper** [comment]
You can easily do this by doing the following before running the installation.

1.- Run `php artisan vendor:publish` to get the migrations published, then you can modify the migrations of your needs. In this case it is only `2016_02_15_204651_create_categories_table.php`. You can change the database table to be `voyager_categories`.
2.- To make Voyager work with this new table, make a `VoyagerCategory` model like this:
```
<?php
namespace App;
class VoyagerCategory extends \TCG\Voyager\Models\Category
{
    protected $table = 'voyager_categories';
}
```
Then in you `AppServiceProvider` add `Voyager::useModel('Category', VoyagerCategory::class);`

**Comment by Bulmer** [comment]
Thanks Mark, but i'm getting "Non-static method TCG\Voyager\Voyager::useModel() should not be called statically" using "Voyager::useModel('Category', VoyagerCategory::class);" in the AppServiceProvider.

**Comment by marktopper** [comment]
Use the facade `TCG\Voyager\Facades\Voyager`.

**Comment by Bulmer** [comment]
Ok, I tried the facade. I was unsure which method in AppServiceProvider to use it in but with boot() I get "Class App\Providers\VoyagerCategory does not exist" and using register() I get "Class voyager does not exist". The Model is supposed to go under App/ isn't it?

**Comment by marktopper** [comment]
Use \App\VoyagerCategory.

**Comment by Bulmer** [comment]
Thanks again. I did work that out earlier, then got stuck on some problems
with previous migrations and existing tables etc. All working now though.
Cheers.

**Comment by marktopper** [comment]
Glad to hear 🎉

**Comment by ckilb** [comment]
Have the same problem. I think it's quite common to already have a table names "categories", "translations" etc.. Voyager should not use generic tables names like that by default.

**Comment by fletch3555** [comment]
This has been closed for nearly a year.  Please don't revive long-dead issues.  You can open your own or post in our Slack group.  But in short, https://media1.giphy.com/media/RL0xU1daTlMoE/giphy.gif This has been requested/complained about numerous times.  We're looking for the best way to fix it, and just haven't found it yet.
