### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by debeniter86** [thedevdojo/voyager#78]
Got error while running : php artisan voyager:install
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "storage" namespace.

**Comment by putera** [comment]
Try run artisan cache:clear and then composer dumpautoload

**Comment by debeniter86** [comment]
I ran with artisan cache:clear and composer dumpautoload but no luck

**Comment by afsardo** [comment]
Did you add the VoyagerServiceProvider in `config/app.php` ?

**Comment by richievc** [comment]
Having Same Issue I tried clearing cache also ran php artisan vendor:publish this step is missing in the instruction how ever it did not work its a fresh install of laravel 5.2.\* is this only for 5.3 maybe I will try with 5.3

**Comment by fletch3555** [comment]
5.2 has a number of issues currently.  There have been minimal complaints from developers using 5.3.

Also, `php artisan vendor:publish` is not missing from the instructions.  It is run by the `php artisan voyager:install` command.

**Comment by Jeroen-G** [comment]
The install command only works on Laravel 5.3.

**Comment by fletch3555** [comment]
Closing as inactive.  Laravel 5.2 is not supported and not currently on our radar.
