### ISSUE TITLE
Installing Voyager, It cant find TCG\Voyager\VoyagerServiceProvider::class, Intervention\Image\ImageServiceProvider::class,

### ISSUE THREAD

**Issue by j-shelfwood** [thedevdojo/voyager#79]
When installing Voyager on my existing laravel application it gives me an error. 
```
[RuntimeException]                                       
  Error Output: PHP Fatal error:  Class 'App\Http\Control  
  lers\Controller' not found in /home/hawkleaf/Desktop/Pn  
  euGraph-V3/vendor/tcg/voyager/src/Controllers/VoyagerCo  
  ntroller.php on line 14  
```
Anyone know what this would mean? I did change the App namespace, but after changing it back (on the cnotroller itself) it doesnt work either

**Comment by j-shelfwood** [comment]
I had to go into the sourcecode and change the namespaces there.

**Comment by marktopper** [comment]
This seems to be an issue with Laravel's controller that have however been fixed.
