### ISSUE TITLE
Role not saved

### ISSUE THREAD

**Issue by oversoul** [thedevdojo/voyager#791]
- Laravel Version: 5.3
- Voyager Version: 0.11.1
- PHP Version:
- Database Driver & Version:
mysql

### Description:
role doesn't get saved.

### Steps To Reproduce:
users -> Add new -> save

**Comment by marktopper** [comment]
I have assigned this to me. I will fix this today before releasing `v0.11.2`.

**Comment by marktopper** [comment]
I figured out what was wrong.

Go to the database section and edit the BREAD for the `users` table and check `browse`, `read`, `edit`, `add` and `delete`. Then save and this works.

I have added this to further seeds at #799

**Comment by alirezamirsepassi** [comment]
Not working with browse, read, edit, add and delete enabled!

**Comment by fletch3555** [comment]
@alirezamirsepassi, please don't comment on issues that have been closed for so long.  If you have an issue, please open your own
