### ISSUE TITLE
If the database table column can be configured as searchable?

### ISSUE THREAD

**Issue by aiddroid** [thedevdojo/voyager#792]
- Laravel Version: 5.3.0
- Voyager Version: 0.10.7
- PHP Version:7.1.0
- Database Driver & Version: 5.6.0

### Description:
If the database table column can be configured as searchable in future?

**Comment by ctf0** [comment]
if u mean [scout](https://laravel.com/docs/5.4/scout) then yes u can for any newly made model or for the one included with package maybe "haven't tested"
```php
$this->app->bind(TCG\Voyager\Models\Post::class, App\Post::class);
```
https://the-control-group.github.io/voyager/docs/v0.10/#getting-started-configuration

**Comment by aiddroid** [comment]
@ctf0  I don't need a full text search, I just need a data filter on each column of BREAD grid.

**Comment by ctf0** [comment]
oh, okay my bad

**Comment by handiwijoyo** [comment]
Voyager `1.0` support column search when using server side pagination.
