### ISSUE TITLE
Create new table - missing functionallity

### ISSUE THREAD

**Issue by FrodeMMeling** [thedevdojo/voyager#793]
Laravel Version: 5.4.12
Voyager Version: dev-release/v0.11.1
PHP Version:7.1.1
Database Driver & Version: MySQL 5.7.17

### Description:
Voyager is missing 
- Prefilled primary key field
- button for adding timestamp fields
- button for adding primary field
- buttong for adding softdelete field

### Steps To Reproduce:
Just follow documentation for installing, but use 5.4.12 for laravel and v0.11.1 for voyager

**Comment by abdgad** [comment]
Currently you can add these fields manually.
Adding shortcuts is nice. I will see what I can do about them.

**Comment by FrodeMMeling** [comment]
Is this working now in latest version?

**Comment by abdgad** [comment]
At the moment, only a prefilled primary key column when creating a new table has been added (will be available when the next release is tagged).
