### ISSUE TITLE
I can't find the views generated by bread service

### ISSUE THREAD

**Issue by mustafa-qamaruddin** [thedevdojo/voyager#794]
- Laravel Version: 5.4.0
- Voyager Version: 0.11.1
- PHP Version: 7.0.13
- Database Driver & Version: mysql  Ver 14.14

### Description:
I can't find the views generated by the bread

### Steps To Reproduce:
I installed Voyager
I created a table
I created a bread
Now I want to copy the generated view into resources/vendor/voyager/slug-table in order to override it, but I can't find the original view generated by the bread service

I have run 
$ php artisan publish:vendor

**Comment by marktopper** [comment]
Voyager does not generate views, it by default uses the BREAD views for all tables.
https://github.com/the-control-group/voyager/tree/master/resources/views/bread

**Comment by mustafa-qamaruddin** [comment]
Thank you!

How do I override a controller?

I found this in documentation?
$this->app->bind(VoyagerBreadController::class, MyBreadController::class);

I suppose MyBreadController should inherit from VoyagerBreadController ?

**Comment by marktopper** [comment]
Its recommended to extend the Voyager controller :)

**Comment by mustafa-qamaruddin** [comment]
Thank you :)

**Comment by mustafa-qamaruddin** [comment]
I have inherited from the Voyager Controller, but all validations are not working. I would like to keep the way the validation worked when first generated by Bread.

I wonder if there is a way to override controllers and still maintain validations as before.

**Comment by marktopper** [comment]
Maybe the current controllers should be splitted into multiple smaller methods, that would make it easier for you to overwrite only what you wish to change.
I am open for pull requests for this.

**Comment by mustafa-qamaruddin** [comment]
Thank you! Where are the core validations located though? I may just follow the same pattern without reworking the whole validation on client and server side.

**Comment by marktopper** [comment]
Validations of BREAD fields are typed in as **JSON Options** in the BREAD field.

https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-bread-validation
