### ISSUE TITLE
All Validations Disappeared after Overriding Controllers

### ISSUE THREAD

**Issue by mustafa-qamaruddin** [thedevdojo/voyager#796]
-Laravel Version: 5.4.0
-Voyager Version: 0.11.1
-PHP Version: 7.0.13
-Database Driver & Version: mysql Ver 14.14

### Description:
I have inherited from the Voyager Controller, but all validations are not working. I would like to keep the way the validation worked when first generated by Bread.

I wonder if there is a way to override controllers and still maintain validations as before.

### Steps To Reproduce:
create new controller
inherit from voyager controller

**Comment by marktopper** [comment]
How about using the following controller
```
namespace App\Http\Controllers;
class CustomVoyagerBreadController extends \TCG\Voyager\Controllers\VoyagerBreadController
{
    // nothing here
}
```

Then I recommend only overwriting the things you need to overwrite.
Also this seems to be a issue with your way of overwriting, not really a issue with Voyager.
