### ISSUE TITLE
See post using the SLUG

### ISSUE THREAD

**Issue by Omazon** [thedevdojo/voyager#80]
is it possible to see the Post using the slug that the application requests that we put natively? without need of using another plugin as Sluggable

**Comment by tnylea** [comment]
@Omazon could you explain that a little more. When you say see the Post are you referring to viewing the post? Let me know. Thanks :)

**Comment by Omazon** [comment]
When you make a post, in the form it asks that we introduce a slug, and that's good, but when you see the list of post and click to view, as it seeks a route using the post slug, the question was, whether it was possible to see that post using the slug that voyager it create

**Comment by marktopper** [comment]
I think what @Omazon want, is to be able to show this page within the slug in the front-end.
However you have to implement this yourself since Voyager is only an admin panel.

**Comment by sosensible** [comment]
While that makes sense, it also makes sense to ask if anyone knows a route example to use for detecting the slug/item matches. We will be having slugs for different posts, pages, and other data content types. Does anyone have an example of how to do that in Laravel?

**Comment by fletch3555** [comment]
@sosensible, this issue has been closed for 6-7 weeks.  Please either open your own issue or join us on the slack #help channel (link to join is in Voyager's documentation)
