### ISSUE TITLE
Req advanced tuts for Pivot table

### ISSUE THREAD

**Issue by md3e** [thedevdojo/voyager#800]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.1
- PHP Version:
- Database Driver & Version:

### Description:
I want to request advanced tutorial how to make pivot table like this #616 
I try to made, unfortunately always getting error.

Please advise.

Thank you.

![2017-02-21_090640](https://cloud.githubusercontent.com/assets/23514728/23148365/d906794a-f817-11e6-8636-215b28a0c516.png)
![2017-02-21_092546](https://cloud.githubusercontent.com/assets/23514728/23148370/de661846-f817-11e6-8c57-15c9575fe70c.png)

**Comment by Codebreaker101** [comment]
I am also trying to implement this and are getting the same errors. Since I was not able to pinpoint the problem, I am in need of a guide to accomplish this.  It would be greatly appreciated!

**Comment by fletch3555** [comment]
More tutorials are in the works.  Closing this.

**Comment by mfprogrammer** [comment]
Trying to do the same, has this tutorial been released?

**Comment by fletch3555** [comment]
@mfprogrammer that's a question better asked on slack. This has been closed for 5 months
