### ISSUE TITLE
Avatar is not working, showing broken images

### ISSUE THREAD

**Issue by JohanIskandar** [thedevdojo/voyager#801]
- Laravel Version: 5.4.12
- Voyager Version: dev-release/v0.11"
- PHP Version: 7.1.0
- Database Driver & Version:

Hi,

  I am not sure why the avatar is broken. I recently just upgraded to the latest development version

![image](https://cloud.githubusercontent.com/assets/1010323/23150647/82b15d66-f827-11e6-8b0a-84c039282323.png)

I was wondering whether I have missed a step when upgrading it, it seems to me, no matter what image I picked for the avatar is not working. thank you

regards,

Johan

**Comment by VladDobrescu** [comment]
Check the symlink. Had the same issue in a vagrant-homestead environment, the `symlink` could not be made. If you're in the same boat (huehue), exit the box and run an `ln` command

**Comment by JohanIskandar** [comment]
Hi BlenderBro,

  Thanks for responding. I am not using Vagrant, just on my localhost (Mac OS). Could you point out how to do it, I mean the steps. Sorry, I am just a beginner. Thanks.

regards,

Johan

**Comment by VladDobrescu** [comment]
Open a terminal and cd into your project folder. Run `php artisan storage:link`. If that fails, read this #722

**Comment by marktopper** [comment]
Please use the released version of `v0.11.1` instead of the dev branch. This branch will be deleted soon.

**Comment by bab55z** [comment]
i tried everything but nothing works! please help needed. i'm runnnig v0.11.1 on laravel 5.4, (Windows)

**Comment by marktopper** [comment]
@bab55z: Please make a new issue with as many details as possible.

**Comment by sweggggg** [comment]
i just fresh install voyager, i still have the problem.

i tried php artisan storage:link in my project folder, it says "The "public/storage" directory already exists." still have the same problem

any solutions?

**Comment by sikhub** [comment]
@sweggggg You need to specify `APP_URL` in `.env` file

**Comment by apiaget** [comment]
I had the same problem and it is now resolved, all I did was replacing the following in my .env file :
```APP_URL=localhost:8000```
replaced by
```APP_URL=http://localhost:8000```
I was running Laravel 5.4.16 with voyager 0.11.8 that I installed by following your guide.
The network tab in chrome's dev tools was listing the error as : ```net::ERR_UNKNOWN_URL_SCHEME```

**Comment by rudiroed** [comment]
Yes me too, please help.
I have tried to change `APP_URL` run this `php artisan storage:link` but still not working for me.
I used Laravel and Voyager latest version.
Do you have any help for me to fix this issue?

Thank you.

**Comment by fletch3555** [comment]
@rudiroed, this issue has been closed for over 3 months, and the last comment over 2 months ago.  Please open your own issue or join our slack group and ask there.

**Comment by hafizhconan** [comment]
Just solved this:
Updated .env file:
APP_URL=http://localhost:8000

Fixed issue

dont forget to restart the server

**Comment by OctaneInteractive** [comment]
I'm also having this [same problem](https://github.com/the-control-group/voyager/issues/1362). I've gone through several different issues here ( #425, and #722 ), following the advice given, and none of those recommendations have worked.

**Comment by fletch3555** [comment]
@hafizhconan, restarting the server shouldn't be necessary.  Also, this issue was resolved quite a while ago.  We're glad you've solved your issue, but it's unrelated to the one here given that the solutions differ.

@OctaneInteractive, as has already been said, this has been closed for months.  Please open your own issues instead of jumping in on closed ones.

**Comment by sammagafu** [comment]
Images not displayed on production any help

**Comment by sikhub** [comment]
@code2913  You need to specify `APP_URL` in `.env` file

**Comment by sammagafu** [comment]
i did but its not working in production. and i cant fix simlink

**Comment by fletch3555** [comment]
@code2913, as I've already stated multiple times in this thread, this issue has been closed.  Please open your own or request help on the Slack group.

**Comment by RyanAtregenio8** [comment]
@apiaget Thank you sir i fix my problem..

when i do this .. 

APP_URL=http://localhost

to

APP_URL=http://localhost:8000

then restart server its ok now . thank you again

**Comment by sweetiefaithpaculanan** [comment]
Thank you @hafizhconan your solution solved my problem. 👍

**Comment by Globalvnet** [comment]
Hello 
I had the same issue with media library,uploaded images not shown in admin panel.
Solving issue  very simple
change in .env file
APP_URL=http://yoursitename

**Comment by almokhtarbr** [comment]
Just specify APP_URL in .env file

**Comment by isidorodasilva** [comment]
you need to specify 
APP_URL=http://localhost

to

APP_URL=http://localhost:8000
and restart your server

**Comment by fletch3555** [comment]
You do NOT need to restart your server after changing `APP_URL`

This issue has been resolved for months, and is now locked
