### ISSUE TITLE
Voyager's theme is not working

### ISSUE THREAD

**Issue by Rumsha001** [thedevdojo/voyager#802]
- Laravel Version: 5.4
I have followed every step but my page is looking like this.. please help asap
![page](https://cloud.githubusercontent.com/assets/25921234/23154291/e9ae2dee-f82e-11e6-8b34-9863e709bdb7.PNG)

**Comment by marktopper** [comment]
Open up the configurations and change the value of `assets_path` to start with `projects/testadmin/public`

**Comment by Rumsha001** [comment]
in which file do i have to set this?

**Comment by abdgad** [comment]
You need to configure your web server to use `/testadmin/public` as the document root.
If you are using XAMPP, search for "xampp vhost".

**Comment by Rumsha001** [comment]
ok now theme is running but all images are broken

**Comment by marktopper** [comment]
That is a better way to solve this. Thanks @abdgad

**Comment by Rumsha001** [comment]
avatar is broken

**Comment by Rumsha001** [comment]
![avatar missing](https://cloud.githubusercontent.com/assets/25921234/23156553/3f98e316-f839-11e6-8aaa-189e70c6c385.PNG)

**Comment by abdgad** [comment]
which version of Voyager are you using? And were you using an older version before?

**Comment by Rumsha001** [comment]
no.. its latest.. installed today

**Comment by Rumsha001** [comment]
i guess it is v0.10

**Comment by marktopper** [comment]
You can find the version on the Dashboard bottom right corner.

**Comment by troix1** [comment]
Does anyone know how to fix this? I'm having the same issue, my paths are missing "/public/" before "/storage/path/to/image", I'm using v0.10.11

**Comment by marktopper** [comment]
@troix1: Please follow the #834 guide I just created to help the masive amount of issues on this.
