### ISSUE TITLE
Can not find Storage symlink

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#804]
- Laravel Version: 5.3.30
- Voyager Version: 0.11.1
- PHP Version: 7
- Database Driver & Version:

This is running on laravel homestead on Mac OS X

### Description:
I created a new laravel 5.3 project, then installed voyager. on the dashboard I have a warning error:

Missing storage symlink
We could not find a storage symlink. This could cause problems with loading media files from the browser.
and a large 'Fix It' Button

If I click Fix It I receive a symlink() error.

I tried to resolve with php artisan storage:link but it failed as storage existed.

I scrapped the project and tsrated again with clean laravel 5.3. before installing voyager I ran php artisan storage:link. Then I installed voyager. Sublime shows the folders with arrows identifying the symlink, great stuff.

Log in to the dashboard, still have the error message and fix it button. Fix it button still fails.

Tried uploading new avatar but doesnt appear in dashboard. The image has appeared in storage/app/users/February2017 though.

Im out of ideas on how to fix this especially seen as though the symlink appears to exist?

**Comment by marktopper** [comment]
It sounds like your hosting does not support symlinks.

However there is a solution, you should open up the `filesystems.php` configuration file and and add a new disk with the following options.

```
'driver' => 'local',
'root' => public_path('storage'),
'url' => env('APP_URL').'/storage',
'visibility' => 'public',
```

Now set the newly created disk to be the disk that Voyager uses in the `voyager.php` configuration file.

> Only supported for `v0.11.x`

**Comment by Philwn** [comment]
It was a mistake on my part, I didn't ssh into my vagrant box therefore the symlink was created locally and not on my virtual machine. Silly mistake.
