### ISSUE TITLE
show stopper after successful login on master (@php not closed in app-footer.blade.php)

### ISSUE THREAD

**Issue by marco-solare** [thedevdojo/voyager#809]
- Laravel Version: 
   5.4.12
- Voyager Version: from composer:   
   Installing tcg/voyager (dev-master a6f3d28) Downloading: 100%
- PHP Version: 
   PHP 7.0.6 (cli) (built: Apr 29 2016 04:21:39) ( NTS )
- Database Driver & Version: 
   Server version: 10.1.13-MariaDB Homebrew

### Description:
show stopper after successful login (whoops)

want to be on the edge (don't want to stick to 5.3 therefore I'm using master branch through composer):

```    
   "repositories" : [
        {
            "type" : "vcs",
            "url" : "https://github.com/the-control-group/voyager"
        }
    ],
    "require": {
        [ ... ]
        "tcg/voyager": "dev-master"
    },
```
almost everything works fine, there seems to be one little "typo" within 
/vendor/tcg/voyager/resources/views/partials/app-footer.blade.php

```
@php $version = Voyager::getVersion(); @endif
```
should read:
```
@php $version = Voyager::getVersion(); @endphp
```

### Steps To Reproduce:
```
$ composer create-project laravel/laravel project_name
$ cd project_name
(put above repository and require-addition into composer.json)
$ composer install
(make changes to .env, add provider to config/app.php)
$ artisan voyager:install --with-dummy 
```
log in to http://project_name.dev/admin with standard credentials
=> after successful login:

```
Whoops, looks like something went wrong.
4/4 ErrorException in 1a6b6d64a0dee966d4eb034271f39ccf454db5df.php line 8: Parse error: syntax error, unexpected '<', expecting end of file (View: /Users/marco/Code/company/vendor/tcg/voyager/resources/views/partials/app-footer.blade.php) (View: /Users/marco/Code/company/vendor/tcg/voyager/resources/views/partials/app-footer.blade.php) (View: /Users/marco/Code/company/vendor/tcg/voyager/resources/views/partials/app-footer.blade.php) 
```

**Comment by abdgad** [comment]
Thanks for reporting the bug.

**Comment by marco-solare** [comment]
voluntarily, glad to contribute a bit ;)
will continue testing and using it, maybe switching between 0.11 and master branches
great work guys
