### ISSUE TITLE
theme not load correctly

### ISSUE THREAD

**Issue by yousseftdi** [thedevdojo/voyager#811]
- Laravel Version: 5.3
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
![image](https://cloud.githubusercontent.com/assets/25956834/23215134/37029d34-f909-11e6-9b07-6c6968c16671.png)

**Comment by Codebreaker101** [comment]
Check if your .**env APP_URL** is set correctly as well as **config/voyager.php** -> **_assets_path_**

Also go to the development tools (Ctrl + Shift + I) and check the url of the assets it's trying to load.

**Comment by marktopper** [comment]
Run `php artisan vendor:publish` and ensure that you have the port in the `APP_URL` environment.
