### ISSUE TITLE
FatalThrowableError after authentication

### ISSUE THREAD

**Issue by mikelmi** [thedevdojo/voyager#812]
- Laravel Version: 5.4.12
- Voyager Version: 0.11.2
- PHP Version: 7.0.13
- Database Driver & Version: mysql 5.7

### Description:
After submitting login form the error message appears:

```
FatalThrowableError in VoyagerUser.php line 53:
Call to a member function relationLoaded() on null
```

**Comment by sarath-c-sandwich** [comment]
Same issue here. I upgraded from Laravel v.5.3.* to v5.4.13


> HP Fatal error:  Call to a member function relationLoaded() on null in /vendor/tcg/voyager/src/Traits/VoyagerUser.php on line 53

**Comment by sarath-c-sandwich** [comment]
Solutions:

Go to your database > table **Users**

then add role_id  to adminId in my computer, I found role_id  in table user_roles and Admin is 1.

<img width="79" alt="screen shot 2017-02-24 at 10 13 33 pm" src="https://cloud.githubusercontent.com/assets/1330852/23308719/b37692f4-fade-11e6-91ae-6b5e93bd7282.png">

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue after the 1.0 release, please create a new issue
