### ISSUE TITLE
(user) images being referenced hardcoded through localhost

### ISSUE THREAD

**Issue by marco-solare** [thedevdojo/voyager#813]
- Laravel Version: 5.4.13
- Voyager Version: tcg/voyager (dev-master e3af559)
- PHP Version: PHP 7.0.6 (cli) (built: Apr 29 2016 04:21:39) ( NTS )
- Database Driver & Version: 10.1.21-MariaDB Homebrew

### Description:
images - at least user images - seem to be referenced hardcoded, example:
```
http://localhost/storage/users/February2017/h57fkMK3sy53wtaqpn7M.png
```
however, my current setup runs on valet, so I do have a dev-domain like
```
http://voyager.dev/
```
naturally, the web server (Caddy in this case, running on valet 1.1.22) can't find this resource as it would have to be referenced similar to this I guess:
```
http://voyager.dev/storage/users/February2017/h57fkMK3sy53wtaqpn7M.png
```
I guess

### Steps To Reproduce:
* install laravel 5.4 through composer
* add the repository and require ('dev-master') to composer.json 
* head your browser to ``` http://your-domain.dev/admin ```
* I only see a broken image in the upper left and upper right corner
* uploading is working without an error, however the pics will not show up afterwards (note also that the avatar does not show up in the table)

pics missing:
![bildschirmfoto 2017-02-22 um 23 59 17](https://cloud.githubusercontent.com/assets/1534749/23236817/090edc42-f95b-11e6-9410-4bfa9fddf291.png)

failed requests:
![bildschirmfoto 2017-02-23 um 00 00 30](https://cloud.githubusercontent.com/assets/1534749/23236848/2c7f77fe-f95b-11e6-9ca0-24fd498561d6.png)

**Comment by sarath-c-sandwich** [comment]
If you change APP_URL to current path in **.env** . To me, I used builtin web server
http://localhost:8000 as the APP_URL then it works.

APP_URL=http://localhost:8000

**Comment by marco-solare** [comment]
Prefect, that did the trick, thank you, closing it.
