### ISSUE TITLE
Create/edit BREAD not working with Postgres driver

### ISSUE THREAD

**Issue by hellkid** [thedevdojo/voyager#814]
- Laravel Version: 5.3
- Voyager Version: dev-master, 11.2
- PHP Version: 7.0
- Database Driver & Version: postgres

### Description:
Create/edit BREAD not working

QueryException in Connection.php line 770:
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "'field'"
LINE 1: SELECT column_name AS 'field',
^ (SQL: SELECT column_name AS 'field',
column_type AS 'type',
is_nullable AS 'null',
column_key AS 'key',
column_default AS 'default',
extra AS 'extra'
FROM information_schema.columns
WHERE table_schema = 'homestead'
AND table_name = 'embeds')

### Steps To Reproduce:
Fresh install with postgres driver
![2017-02-23 10-35-48](https://cloud.githubusercontent.com/assets/8776322/23249140/dd79f28e-f9b3-11e6-8f28-51b680fc01e5.png)

**Comment by abdgad** [comment]
Thanks for the report. The issue has been fixed in `dev-master`.
If there are any other issues with Postgres or other drivers, please don't hesitate to report them.
