### ISSUE TITLE
Images not showing up, Symlink works

### ISSUE THREAD

**Issue by troix1** [thedevdojo/voyager#815]
- Laravel Version:  5.3
- Voyager Version: v0.10.11
- PHP Version: 5.6
- Database Driver & Version: MySQL, 10.1.18-MariaDB-cll-lve - MariaDB Server

### Description:
Images not showing up in Voyager. Paths are missing "public/" before each image. Symlink is working and displaying all images on front end.

If I add "public/" in chrome Inspect before the image, the image shows up.

### Steps To Reproduce:
Project uploaded to shared hosting with default directory structure with 2 changed lines in ".htaccess":

DirectoryIndex public/index.php
RewriteRule ^ public/index.php [L]

### I do have to get this site working asap, so please help me.

**Comment by troix1** [comment]
After few hours of trying my Images are UPLOADED correctly now and displayed on frontend, but still not showing in admin panel, the path is wrong, it is missing "public/" before "storage/folder/image.jpg", I can't find anything in voyager.php to fix that. Any clues?

**Comment by marktopper** [comment]
Add `public` to the `visibility` path in the `public` disk at `config/flysystems.php`.

**Comment by troix1** [comment]
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
        ],

This is how my ```config/filesystems.php``` looks without any changes, visibility of the public disk is already set to public, or am I missing something? @marktopper

**Comment by marktopper** [comment]
Sorry, meant the [`url` part](https://github.com/laravel/laravel/blob/master/config/filesystems.php#L54). Which you do not seem to have.

Try add it and prefix it with `public/`.

**Comment by marktopper** [comment]
Would then be
```
'url' => env('APP_URL').'/public/storage',
```

**Comment by marktopper** [comment]
Let me know if this works for you.

**Comment by troix1** [comment]
Thanks for the quick reply. I added the line but it doesnt seem to do anything. I also ran ```php artisan config:clear``` ```cache:clear``` ```view:clear``` but nothing.

.env file:
```APP_URL=http://localhost```

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
            'url' => env('APP_URL').'/public/storage',
        ],

It is also weird because most of images are not even giving out errors in console log, the only ones I get error for, are the ones I upload through voyager, other ones just dont show up, my user avatar shows "Klemen Avatar" instead of a picture or an error.

**Comment by marktopper** [comment]
Will look into this in a moment. (_EDIT: A little busy right now, I will be back to you soon_)

**Comment by marktopper** [comment]
What is the URL that the site requests for the image, and what is the location for the image.
Also do you use any port other than 80?

_Sorry for the delay_

**Comment by troix1** [comment]
Take all the time you need, I just hope we can get this working, I'm kinda stuck.
The actual url is: klemen-lozar.com (it's my domain but I temporarily use it for this project),
URL:
```klemen-lozar.com/admin```
```klemen-lozar.com/admin/frontpages``` and any other BREAD that has images

the path to images is ```/public_html/public/storage/users``` or ```/public_html/public/storage/frontpages```

Port 80

Screenshots:
http://prntscr.com/eemuz1
http://prntscr.com/eemvfc

EDIT: The folder ```March2017``` in ```frontpages``` doesn't even exsist, I try to upload the file but it doesnt upload for some reason. However, other images from January,February are there but are still not displayed in admin panel as you see on screenshot above.

http://prntscr.com/eemwqp

**Comment by marktopper** [comment]
What happens if you upload a new image using the BREAD system?

**Comment by troix1** [comment]
I am currently away from computer, i will try few posibilities and report later

**Comment by marktopper** [comment]
Okay, no hurry. Just ping me when done.

**Comment by troix1** [comment]
Okay so, looks like instead of uploading the file to ```public/storage``` or rather ```/storage/app/public```, it uploads it to ```/storage/app/frontpages```, frontpages is one of my tables. Looks like I messed something up changing those files?

Screenshot:
http://prntscr.com/eez963

EDIT: I will try to unlink symlink and re create it and report here.

EDIT2: I did ```unlink storage``` and ```php artisan storage:link``` but when I upload through Voyager it still creates a new folder in ```storage/app``` instead of ```storage/app/public``` and this doesn't even begin to solve missing ```public/``` path at start of requested url.

I thought it might be something with subfolder not being set up but it looks fine i think.

    'storage' => [
        'subfolder' => 'public/', // include trailing slash, like 'my_folder/'
    ],

**Comment by troix1** [comment]
Good morning. :)
My project is due this week, could you please take a look when you have the time?

**Comment by marktopper** [comment]
Sorry, forgot about this issue.

**Comment by marktopper** [comment]
Just realized that you are using `v0.10.x`. Is there a specific reason for that?
That version have had a lot of issues with the storage system since it didn't used Laravel's Filesystem.

Could you consider upgrade to `v0.11.x` that uses Laravel's Filesystem?
I can help you over at Slack 😄

**Comment by troix1** [comment]
I have two instances of the same project on my host, one is Voyager ```v0.11.3```, one is Voyager ```v0.10.11``` , I have storage issues on both, but the ```v0.11.*``` also creates some database relation issues for me, I will deal with that later. All the info I provided to you was from the ```v0.11.3```.

I would love to talk it over at Slack but I really can't at my workplace, what about later, after 17:00, that is in 7 hours?

**Comment by marktopper** [comment]
@troix1: I will be on Slack most of the channel.

Okay, just to be clear since most of this thread is splitted between informations for both version of Voyager, please let me know the following:

1.- The URL of your admin dashboard (includeing ports, you may replace your domain with `****.com`)
2.- The full requested path for the file.
3.- The Laravel filesystem configuration
4.- Your APP_URL environtment (you may replace domain again with `****.com`).

**Comment by troix1** [comment]
Admin URL: ```***.com/admin```
Requested URL: ```src="/storage/users/January2017/Esal0SYtaoZdPZSJ2l8h.jpg"```
FULL file url: ```***.com/public_html/storage/app/public/users/January2017/Esal0SYtaoZdPZSJ2l8h.jpg```
APP_URL:  ```APP_URL=http://localhost```
Laravel filesystems.php:

    'default' => 'local',

    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'visibility' => 'public',
            'url' => env('APP_URL').'/public_html/public/storage',
        ],

        's3' => [
            'driver' => 's3',
            'key' => 'your-key',
            'secret' => 'your-secret',
            'region' => 'your-region',
            'bucket' => 'your-bucket',
        ],

    ],

**Comment by marktopper** [comment]
Please change the config of `filesystems.public.url` to be just `env('APP_URL').'/storage'`.
Then please try to run `php artisan vendor:publish` and let me know if that works.

Also make sure that `public/storage` is not already a folder (it have to be a symlink)

Looking forward for your response.

**Comment by marktopper** [comment]
Also, what is your Voyager storage configuration in `config/voyager.php`.

**Comment by troix1** [comment]
It is a symlink, this is how it is displayed in filezilla. http://prntscr.com/eglszq
Gonna edit that line in a second and report back. What do you mean with voyager storage config?

```'assets_path' => '/public/vendor/tcg/voyager/assets'```

    'storage' => [
        'subfolder' => 'public/',
    ],

**Comment by troix1** [comment]
I edited the Filesystems.php and ran the command - no changes.

Acctually, about the Requested URL, I might have been mistaken. It shows this: http://prntscr.com/eglvnb

**Comment by marktopper** [comment]
Can you try changing the `config/voyager.php`'s `storage` key to this:

```
'storage' => [
    'disk' => 'public',
],
```

That is the default for `v0.11.x`.

**Comment by troix1** [comment]
Okay finally changing something :) Now instead of blank src i get a wrong path, give me a few seconds.

```<img src="http://localhost/storage/users/January2017/Esal0SYtaoZdPZSJ2l8h.jpg" class="avatar" alt="Klemen avatar">```

Changed it to

```<img src="http://localhost/public_html/public/storage/users/January2017/Esal0SYtaoZdPZSJ2l8h.jpg" class="avatar" alt="Klemen avatar">```

Now the console says ```net::ERR_CONNECTION_REFUSED```

**Comment by troix1** [comment]
Got it to work.. 
public disk:
            'url' => '/public/storage',

**Comment by marktopper** [comment]
Can you see the file at: http://localhost/public_html/public/storage/users/January2017/Esal0SYtaoZdPZSJ2l8h.jpg

**Comment by troix1** [comment]
It works now, I probably copied the ```config/voyager.php``` from 0.10 to 0.11 to save time and messed this up... I'm glad it works now, thanks for everything! ;)

**Comment by marktopper** [comment]
You are welcome, and sorry for the delay of the replies.

**Comment by troix1** [comment]
[offtopic] also, do you have any idea why the related tables dont work in ```0.11.*``` ? Was there any change there?

**Comment by marktopper** [comment]
What table?

**Comment by troix1** [comment]
I have ```**.com/admin/frontpages```which is my sql table that doesn't have any relation to my other tables, works fine.

My other tables, for example ```**.com/admin/promos``` throw out an error, maybe my models got overriden when updating or something?
It also says this when I try to **create** a **new App/Promo** 
```Make sure to setup the appropriate relationship in the pageId() method of the App\Promo class.```

I should probably jsut re-do the model relationships and thats it?

**Comment by marktopper** [comment]
What is your BREAD settings for that table?

**Comment by marktopper** [comment]
Also, can you share the model `Promo`?

**Comment by troix1** [comment]
http://prntscr.com/egmame
Promo:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Promo extends Model
{
     public function page_id(){
        return $this->belongsTo(Page::class);
    }   
    public function page(){
        return $this->belongsTo('App\Page');
    }   
}

**Comment by marktopper** [comment]
In `v0.11` we changed the relationship names to be camelCase like `pageId` instead of `page_id`.

**Comment by marktopper** [comment]
Hope that helps.

**Comment by troix1** [comment]
Thanks again, you are a wizard!

**Comment by marktopper** [comment]
You are welcome 👍

**Comment by anglyeds** [comment]
Hi, I have the same issue occurred, 
![image](https://user-images.githubusercontent.com/11608000/27513582-015b74ee-599e-11e7-936d-05090e3951ca.png)

I tried to change storage -> public/storage. the problem still remain. 
can you please help me to look into it ?

Voyager Version: 0.11.14
laravel: 5.4
php: 5.6.4

**Comment by unknownFrequency** [comment]
My problem was that there was no "http://" appended before the path in voyager admin.. 
so:
<img src="http://{{ $user_avatar }}" class="avatar" alt="{{ Auth::user()->name }} avatar">

**Comment by unknownFrequency** [comment]
fixed it for me by adding http:// before the URL in .env file

**Comment by fletch3555** [comment]
@anglyeds, this issue has been closed for 3.5 months.  Please open your own or join the Slack group and post there.

**Comment by ismaeljoseph** [comment]
Hello Everyone I have this issue and solve it this way.
On linux/debian :
1- go the public folder and remove storage folder
2- re-create the symlink : php artisan storage:link

On windows :
1- install git for widows and with git-bach
2- go the public folder and remove storage folder
3- re-create the symlink : php artisan storage:link

And it solve all problem

Alternatively for windows , you can just remove the storage folder and use windows commande to recreate the symbolic link. exemple ( Mklink /d ...path\public\storage\ ...path\storage\app\public\ ).
But i never try this out.

god bless you all.
And it solve all problem

**Comment by sath26** [comment]
the correct solution for me has beeen adding :8000 to .env file APP_URL where initially there is only http://localhost

**Comment by Globalvnet** [comment]
change .env file APP_URL=http://yoursitename

**Comment by fletch3555** [comment]
@Globalvnet, please refrain from commenting in old CLOSED issues, especially when they've been closed for nearly a year and already have the exact solution you're proposing mentioned in a prior comment.

**Comment by moashraf** [comment]
sfdsf

**Comment by moashraf** [comment]
**# 'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage/app/public/',
            'visibility' => 'public',
        ],**

**Comment by moashraf** [comment]
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            **'url' => env('APP_URL').'/storage/app/public/',**
            'visibility' => 'public',
        ],

**Comment by hasibur-rashid** [comment]
1. delete '**storage**' shortcut folder from your project '**public**' directory or folder 
2. re-create the symlink using this command : **php artisan storage:link**
3. open 'filesystems.php' from config folder and change the following line 
for localhost
`'url' => env('APP_URL').'/WRITE YOUR PROJECT FOLDER NAME/public/storage',`
for live server
`'url' => env('APP_URL').'/public_html/public/storage',`

I think this solution is works fine for all of voyager user. Thanks.

**Comment by fletch3555** [comment]
@hasibcsepstubd, please read the comment immediately above yours....
