### ISSUE TITLE
Menu Builder can't create menu item with empty url

### ISSUE THREAD

**Issue by dimsanchuk** [thedevdojo/voyager#816]
- Laravel Version: 5.4.12
- Voyager Version: 0.11.2
- PHP Version: 5.6
- Database Driver & Version: MySQL

### Description:
I try to add menu item with empty url. This item should be parent for other items.

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'url' cannot be null`

**Comment by marktopper** [comment]
Can you try and test branch `fix/816`.
You can update composer to use `dev-fix/816` in order to test this.

If this works, I will merge it in and make a new release.

**Comment by dimsanchuk** [comment]
Yes, it works. Thanks.
