### ISSUE TITLE
Custom view - Retrieving model - Relationship

### ISSUE THREAD

**Issue by JohanIskandar** [thedevdojo/voyager#817]
Hi,

   I am aware that this might not the right place to ask the question, but I dont know where to ask questions. 

  I am a novice and started using Voyager. Currently, I am trying out the how to setup the relationship. But I dont understand "You can optionally add a new page_slug property to the relationships object in the BREAD details in order to display proper links to relationship records"

   Do I create a new field in Page table, I tried many things, now it is broken

![image](https://cloud.githubusercontent.com/assets/1010323/23276090/974d0264-fa3b-11e6-92dc-2f771bd4fd37.png)

    Any further instructions or videos are highly appreciated. Thank you.

regards,

Johan

**Comment by Frondor** [comment]
I think we need a new label "Can't understand" to the repo :D

Jokes aside, the `page_slug` property works only for generating links to that specific BREAD from others.
Let's see you have a `belongsTo` relation for `Post` and `Categories` where each post belongs to a single category. 
If you're viewing a `Post` in voyager you shall see a link to its `Category`, that link's URL is using the `page_slug` property you provided before to make the correct URL.

I hope that answers the question.

**Comment by fletch3555** [comment]
Closing since the question was answered
