### ISSUE TITLE
Unauthorized exception trying to access admin for custom model

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#819]
I can't seem to find anything about this in documentation.

I have created a table and used voyager to create migration, model etc. Created a Bread for it but cant seem to access admin to create or edit entries.

table is portfolio, given it a slug or portfolio in bread. When trying to access admin/portfolio i recieve following error:

UnauthorizedHttpException in Voyager.php line 181:

What am I missing?

**Comment by saltyeyes** [comment]
You might need to grant the admin role permission to access the new BREAD. On the Roles page, edit the admin role - if the checkbox next to Portfolio is unchecked, check it and save. :)

**Comment by Philwn** [comment]
That was it thank you
