### ISSUE TITLE
ErrorException in Voyager.php line 88: bread/edit-add.blade.php

### ISSUE THREAD

**Issue by georgejkollias** [thedevdojo/voyager#821]
- Laravel Version: 5.4.*
- Voyager Version: #.11.1
- PHP Version: 7.0.14
- Database Driver & Version:

### Description:

I have created a new DB table, and when i want to edit a record i get the following error:

ErrorException in Voyager.php line 88:

Undefined index: PRI (View: /vendor/tcg/voyager/resources/views/bread/edit-add.blade.php)

Is there anything that i am missing from the table for it to break?

CREATE TABLE `fixtures` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `home_team` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `home_team_score` int(11) DEFAULT NULL,
  `away_team` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `away_team_score` int(11) DEFAULT NULL,
  `game_day_details` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `buy_tickets` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `match_info` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  `round` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

### Steps To Reproduce:

Install New Laravel project
Install Voyager
Create New Database
Enter information
then edit it breaks.

**Comment by abdgad** [comment]
I will be working to fix this.
In the mean time, please go to: `Tools` > `Database` > Click on `Edit BREAD` for your table.
Uncheck all `Visibility` check boxes for the `Primary Key`. Hit `Submit`.
That should fix it for now.
