### ISSUE TITLE
No hidden input type

### ISSUE THREAD

**Issue by Codebreaker101** [thedevdojo/voyager#822]
- Laravel Version: 5.4.12
- Voyager Version: 0.11.2
- PHP Version: 5.6.28
- Database Driver & Version: MySQL  5.7.16

### Description:
In some of the demos and in the official documentation **hidden** field type is showed and mentioned. There is no option hidden when selecting Input Type in the latest version. Was this feature removed? 

### Steps To Reproduce:
Fresh install of Laravel and Voyager

**Comment by marktopper** [comment]
The whole database section was rewrote in `v0.11`. And therefor some things might have been forgotten, we will however get this back sooner or later.

**Comment by marktopper** [comment]
/ping @abdgad, we should maybe add a form field for this.

**Comment by abdgad** [comment]
I think @Codebreaker101 is referring to Hidden Input type for BREAD?

**Comment by marktopper** [comment]
Ohh, I see.

**Comment by Codebreaker101** [comment]
That is correct @abdgad. I got it working for the most part. I will make a PR when ready.

Also, I got an idea for custom input types that would be defined in the voyager config. It would make it a bit easier to customize the apprentice using partial views. Has this been considered previously?

**Comment by sikhub** [comment]
Pull request: https://github.com/the-control-group/voyager/pull/866

**Comment by sikhub** [comment]
@marktopper This one is resolved.

**Comment by marktopper** [comment]
Thanks @sikhub.

// Closed
