### ISSUE TITLE
The deleted columns still left on the posts table

### ISSUE THREAD

**Issue by ergxpr0xy** [thedevdojo/voyager#824]
- Laravel Version: 5.4.12
- Voyager Version: 0.11.2
- PHP Version:  5.6.15
- Database Driver & Version: 10.1.9-MariaDB

### Description:
The deleted columns still left on the posts table
e.g. i deleted seo_title columns via /database/posts/edit but the header still left there.

![2017-02-24 2](https://cloud.githubusercontent.com/assets/19571567/23309342/eea37246-fae0-11e6-82c0-40d4591756ec.png)
![2017-02-24 6](https://cloud.githubusercontent.com/assets/19571567/23309434/392f104a-fae1-11e6-8fec-28810217deac.png)

**Comment by abdgad** [comment]
Did you delete `seo_title` column from the table using phpMyAdmin? Does `seo_title` exist in phpMyAdmin?

**Comment by abdgad** [comment]
Thanks for reporting the issue. It has been fixed in `v0.11.3`. After you update, go to `Edit BREAD` for `Posts`, and just hit `Submit` without changing anything. That should fix it.
