### ISSUE TITLE
Missing `.blade` in file name of `app-footer.php`

### ISSUE THREAD

**Issue by wzulfikar** [thedevdojo/voyager#826]
- Laravel Version: 5.4.13
- Voyager Version: 0.11.2
- PHP Version: 7.1.0
- Database Driver & Version: MySQL

### Description:
the `.blade` is missing in `app-footer.php` which causes the footer not being rendered properly.

### Steps To Reproduce:
login to voyager admin and check the footer.

![screen shot 2017-02-25 at 3 59 26 am](https://cloud.githubusercontent.com/assets/7823011/23318949/8594edb4-fb0f-11e6-89c9-65cf96245ac4.jpg)

expected look of footer is:
![screen shot 2017-02-25 at 4 05 58 am](https://cloud.githubusercontent.com/assets/7823011/23318999/c4d8b1e0-fb0f-11e6-884f-a32cfdf8c946.jpg)

---

on my side, what I did to display the footer properly is to override voyager's footer by creating `app-footer.blade.php` inside `resources/views/vendor/voyager/partials/`. this is the code inside my new `app-footer.blade.php`:

```php
<footer class="app-footer">
    <div class="site-footer-right">
        @if (rand(1,100) == 100)
            <i class="voyager-rum-1"></i> Made with rum and even more rum
        @else
            Made with <i class="voyager-heart"></i> by <a href="http://thecontrolgroup.com" target="_blank">The Control Group</a>
        @endif
        @if ($version = Voyager::getVersion())
            - {{ $version }}
        @endif
    </div>
</footer>
```

**Comment by Webpicasso** [comment]
That's already fixed in #806
Please update to the latest voyager version

**Comment by abdgad** [comment]
You need to update to the latest version.

**Comment by wzulfikar** [comment]
Ok thanks :)
