### ISSUE TITLE
Adding new user from admin sets role_id as null, and it is not updatable from admin.

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#828]
- Laravel Version: 5.3
- Voyager Version: 0.11.2

As the title says,
here is the error when I try to login using the newly added user:

![image](https://cloud.githubusercontent.com/assets/8501654/23321115/9b54537a-fae6-11e6-822f-e24c39f83672.png)

updating that user to set a role does not take effect.

**Comment by marktopper** [comment]
Duplicate of #812

**Comment by marktopper** [comment]
Seems like your user is missing a `role_id`. I think that I should make sure that Voyager ensures that all users have a role, and assign the default role if not set.

**Comment by marktopper** [comment]
Or the user have a role that no longer exists.

**Comment by hazem1taha** [comment]
That is probably what is happening, the user is created with a null role_id.
