### ISSUE TITLE
A wrong folder called publicsettings is created in Storage instead of a path storage/app/public/settings

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#829]
- Laravel Version: 5.3
- Voyager Version: 0.11.2

As the title says, after the v0.11 update, I found this bug.
It can be tested by uploading any file from the settings page in the admin.

storage disk config:

`
    'storage'       => [
        'disk'      => 'public',
    ],
`
Thanks.

**Comment by akazorg** [comment]
This is sorted out? @EngHazem you can close it?

**Comment by marktopper** [comment]
I was now able to replicate this issue.

Will get this fixed.

**Comment by marktopper** [comment]
Fixed in #831.
Will be merging in and making a new release once TravisCI is done.
