### ISSUE TITLE
Change the generated filename of seeder files

### ISSUE THREAD

**Issue by jpcaparas** [thedevdojo/voyager#830]
- Laravel Version: 5.4
- Voyager Version: 0.11.2
- PHP Version: 7.1.1
- Database Driver & Version: 

### Description:

It would be nice to namespace or prefix the generated seeder files so they don't collide with existing seeder files. 

![](https://i.imgur.com/Cjw1T1Om.png)

### Steps To Reproduce:

This seeder files are generated when running `./artisan voyager:install`

**Comment by marktopper** [comment]
What is your idea here?
Maybe classes could be namespaced and files could be located inside a subfolder in the `seeds` folder.

**EDIT**: The same could possibly be done for migrations

**Comment by abdgad** [comment]
@marktopper  maybe just adding `Voyager` prefix to the file names would suffice. Or publish them to a special folder like you mentioned.

**Comment by jpcaparas** [comment]
+1 for the special folder. Let me know if you want me to take on this.

**Comment by carloquilala** [comment]
+1

Any update regarding this matter? I would love to see this enhancement soon... I'm good with the sub folder

**Comment by fletch3555** [comment]
+1 for the subfolder.  (Assuming it doesn't mess with autoloading at least)

**Comment by fletch3555** [comment]
Closing due to age for now.  We're still open to Pull Requests for this.  The only issue with the subfolder idea is that these classes aren't namespaced (by default at least), so you will still have name collisions.
