### ISSUE TITLE
Can't find keys for settings

### ISSUE THREAD

**Issue by wzulfikar** [thedevdojo/voyager#832]
- Laravel Version: 5.4.13
- Voyager Version: 0.11.3
- PHP Version: 7.1.0
- Database Driver & Version: MySql

### Description:
couldn't find list of keys used in setting, eg. `admin_icon_image`, `admin_title`, etc. thus keys are called using `Voyager::setting('admin_icon_image', '')`.

can anyone point me the link to documentation where above keys are being recorded? or is it not documented yet?

**Comment by marktopper** [comment]
You mean you want the predefined setting keys that Voyager uses.
For this you can check the seeder (that are run when installing with dummy data)

Seeder: https://github.com/the-control-group/voyager/blob/master/publishable/database/seeds/SettingsTableSeeder.php
