### ISSUE TITLE
Upload path return localhost

### ISSUE THREAD

**Issue by aldyanimayazar** [thedevdojo/voyager#839]
Hi guys, i was setup a new laravel install 5.4 and voyager latest. When i try to deploy this project on a server, i get one of annoying issue.

When i try to upload a logo on my domain.com/admin/settings , the image link are broken. When i inspect the element. The <img src="localhost" ( return localhost instead of mydomain.com ) i tried config/app and change url to mydomain.com but it's still doesn't work. How can i fix this ? 

Thanks,

**Comment by wiertar** [comment]
The solution is in #813.
