### ISSUE TITLE
Login Problem - Admin Panel Package for Laravel

### ISSUE THREAD

**Issue by momin-riyadh** [thedevdojo/voyager#84]
[Login Problem](http://stackoverflow.com/questions/40409360/voyager-admin-panel-package-for-laravel)
![Preview](http://i.imgur.com/ArWeWqV.png)

**Comment by fletch3555** [comment]
Dupe of #36 #42 #53 

It hasn't made it into the documentation yet, but PR #82 adds the 5.3 requirement.  Laravel 5.2 and below are not (currently) supported.

**Comment by azarzaza** [comment]
hi i am new for laravel when i install voyager it show a error and when i run the application @momin-ctg  error shows plz help 
![error](https://cloud.githubusercontent.com/assets/23259321/20004548/09e1fd9c-a2b3-11e6-884b-880c8e62b59c.jpg)

**Comment by marktopper** [comment]
@azarzaza: Please stick to the topic, your issue is related to #48, not this one.

**Comment by momin-riyadh** [comment]
@azarzaza just ensure you have installed php version 5.6.4 and laravel 5.3 on your machine , then follow the instruction from voyager github doc. I had same problem ......... to! now i resolve it

![composer_json](http://i.imgur.com/o950vRb.png)

**Comment by azarzaza** [comment]
yeah its resolve and i am new for github

**Comment by momin-riyadh** [comment]
Thanks @azarzaza anythings regards to git and github/bitbucket you can try [TUTORIALZINE](http://tutorialzine.com/2016/06/learn-git-in-30-minutes/)
