### ISSUE TITLE
BOOLEAN is missing in the database type dropdown list

### ISSUE THREAD

**Issue by DrewNeon** [thedevdojo/voyager#841]
- Laravel Version: 5.4.12
- Voyager Version: 0.11.3
- PHP Version: 7.0.14
- Database Driver & Version: mysql 5.7.17

### Description:
Please see this attached screenshot, can't find the BOOLEAN type there.
![2017-02-28 10 01 15](https://cloud.githubusercontent.com/assets/25809783/23388553/d5645114-fd9d-11e6-9f2c-fdc15c4bb66f.png)

### Steps To Reproduce:
Click Tools -> Database from the sidebar menu, click "Create New Table" button, click "Add New Column" button, then click the dropdown list under Type.

**Comment by DrewNeon** [comment]
BTW, is it possible to make VARCHAR the default choice of Type when adding new columns? Currently, TINYINT as the first option is default, but not that widely used comparing with VARCHAR, isn't it? It would be more user-friendly, right?

**Comment by Codebreaker101** [comment]
**BOOL** and **BOOLEAN** are aliases for **TINYINT(1)** 
https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html

**Comment by DrewNeon** [comment]
@Codebreaker101 Thanks!
