### ISSUE TITLE
choose custom bread controller like the model one

### ISSUE THREAD

**Issue by hugosvent** [thedevdojo/voyager#844]
### Description:
It would be great if we can choose custom BREAD controller just like we can choose custom model
![pasted image at 2017_02_28 11_40 pm](https://cloud.githubusercontent.com/assets/7149508/23414788/ae4015ce-fe0f-11e6-83d1-f8e57491628c.png)

**Comment by marktopper** [comment]
Currently this can be done by overwriting routes, however what is your ideas here?

**Comment by akazorg** [comment]
That would be handy @hugosvent. I think it might be easy to implement.

Right now, if you need to use a custom controller you can update routes. You know that?

**Comment by hugosvent** [comment]
My Ideas are, when creating BREAD, we can choose our custom controller like
Controller Name :
App\Http\Controllers\ProductCoffeeController

btw how can I overwrite routes? Do I just put it on top of Voyager::routes()?

**Comment by marktopper** [comment]
Under `Voyager::routes()` you can make overwrites like:
```
Route::get('/login', function () {
    return redirect('my-other-login-page');
});
```

Now the `/admin/voyager` will redirect instead.

**Comment by marktopper** [comment]
Pinging some of the good guys for their thoughts on this.

@thedevdojo @tnylea @abdgad @akazorg @handiwijoyo @Frondor @fletch3555

**Comment by abdgad** [comment]
Maybe something like this:

```php
$defaultController = $namespacePrefix.'VoyagerBreadController';

foreach (DataType::all() as $dataType) {
    $breadController = $defaultController;

    // if data type has set a custom bread controller
    if ($dataType->controller) {
         $breadController = $dataType->controller;
    }

    Route::resource($dataType->slug, $breadController);
}
```

**Comment by marktopper** [comment]
I like that approach @abdgad.

**Comment by akazorg** [comment]
I like that too @abdgad.

I think this feature is a must and most users will love it.
I can create a PR later for that.

**Comment by akazorg** [comment]
Preparing PR for this, in progress...
