### ISSUE TITLE
Dropdown Sidebar bug

### ISSUE THREAD

**Issue by Philwn** [thedevdojo/voyager#846]
"php": "7.1",
"laravel/framework": "5.3.*",
"tcg/voyager": "^0.11.3"
- Database Driver & Version: mariaDb 10.1.21

### Description:
When using the media section. The dropdown "tools" menu in the sidebar will expand but can not close, seems to only be when you browse into a folder within media though.

**Comment by Frondor** [comment]
I'm already working on it
