### ISSUE TITLE
How to create multiple registration form in each page?

### ISSUE THREAD

**Issue by icodejc** [thedevdojo/voyager#85]
hi,
I need to create multiple form in a page, to be filled out by the users.
Each year we had organized some activities. We need to create a page which contain some field -> **Activity name, date and time (this will be filled out by the admin)** and another separate form which include registers name, age and email address (this will be filled out by the user)

So i need to know is Voyager able to achieve this?

**Comment by handiwijoyo** [comment]
You need to create a new forms database. Then use that form data type in a page. See posts > category example.
