### ISSUE TITLE
How create new language?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#852]
- Laravel Version: 5.4
- Voyager Version: new
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
How i may change language ? I can translate. But i don't know how insert new language :) I try to have English and Russian version admin panel :)

**Comment by marktopper** [comment]
This is not yet supported, but we are heavily working on multilingual support #561 and i18n support.
For the i18n support, we are currently waiting for Laravel to support loading package specific JSON language files.
