### ISSUE TITLE
Error when trying to create bread

### ISSUE THREAD

**Issue by ockam** [thedevdojo/voyager#854]
- Laravel Version: 5.4.15
- Voyager Version: 0.11.3
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7.17

Running on latest Homestead

### Description:

When trying to create a bread (from the Database section), a MethodNotAllowedHttpException is raised. It look like the button submit a POST but the route is set to GET (line 98 in routes/voyager.php).

**Comment by ockam** [comment]
Just found this has been changed in  [e3af559](https://github.com/the-control-group/voyager/commit/eff19d9177fc6a821bb5039f7b9ee3772a050b37#diff-4e15e6eaf20a61957928187d96c0f2c5)

**Comment by marktopper** [comment]
@abdgad, would you be able to look into this?

**Comment by abdgad** [comment]
@ockam you're still having the issue?

**Comment by ockam** [comment]
@abdgad yes, the route has been changed to a GET while the button to create a bread submit a form POST...

**Comment by abdgad** [comment]
@ockam this is the button that creates bread: https://github.com/the-control-group/voyager/blob/v0.11.3/resources/views/tools/database/index.blade.php#L60
It's sending a GET request.

**Comment by ockam** [comment]
When inspecting the code in Devtool, this is what I see:

```
<div class="bread_actions">
<form action="//localhost:3000/admin/database/bread/user_positions/create" method="POST">
<input type="hidden" value="6tm8C4SaEkdWvOPqja8fV8DChjrUvZQAv9m5O3Gl" name="_token">
<button type="submit" class="btn-sm btn-default">
<i class="voyager-plus"></i> Add BREAD to this table
</button>
</form>
</div>
```

**Comment by abdgad** [comment]
@ockam it looks like Laravel is using old views. Make sure you update to the latest Voyager release, and try out: `php artisan view:clear`

**Comment by ockam** [comment]
That’s it! Should have thought about that. :(

Thanks!
