### ISSUE TITLE
Integrity constraint violation: 1048 Column 'url' cannot be null 

### ISSUE THREAD

**Issue by Ralkage** [thedevdojo/voyager#856]
- Laravel Version: 5.4.9
- Voyager Version: 0.11.3
- PHP Version: 7.1.1
- Database Driver & Version: MySQL

### Description:

There is no UI option to create sub-menu's. With the default dummy data created menu, there is a current sub-menu called "Tools" but no way to create your own sub-menu. As when I edited that menu, I get an option I cannot see when adding a New Menu Item.

![link-type](https://cloud.githubusercontent.com/assets/2059356/23526035/91c3ba7c-ff5e-11e6-85dc-b0a8d698ff61.jpg)

Link Type is basically missing.

![link-type-missing](https://cloud.githubusercontent.com/assets/2059356/23526067/b666dc60-ff5e-11e6-8507-ae3c266a37c8.jpg)

### Steps To Reproduce:

1. Log into the Admin CP.
2. Click on Tools.
3. Click on Menu Builder.
4. Click on Builder under the default admin menu label.
5. Click on New Menu Item.
6. Link Type is missing.
7. URL cannot be null (it should for sub-menu's)
8. ![i-want-to-believe](https://camo.githubusercontent.com/e03327a063a8106b8b1e98b7e47b9032d6e2d0b3/68747470733a2f2f72656e6465722e6269747374726970732e636f6d2f76322f6370616e656c2f393636393634392d3234353130373838365f342d73312d76312e706e673f7472616e73706172656e743d312670616c657474653d312677696474683d323436)

**Comment by Ralkage** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9669649-245107886_4-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by marktopper** [comment]
This have been fixed in `v0.11.4`.
#845
