### ISSUE TITLE
Remove Fadeout on error notifications

### ISSUE THREAD

**Issue by smick** [thedevdojo/voyager#858]
- Laravel Version: 5.4
- Voyager Version: 0.11.3
- PHP Version: 5.6.4

### Description:
When an operation errors out, the notification system displays the error and then fades out. If you do not mouse over the error quickly enough to pause the fadeout timer, it disappears. Error notifications should be dismissible, or there needs to be an error log that the user can access without having to navigate away from the current page. Currently if you miss the error notification the only option is to reproduce the error to see what the error was, which is not desirable.

### Steps To Reproduce:
Using the database tools, create a new table with an auto-incrementing primary key and leave 'nullable' unchecked. Submit. 

![image](https://cloud.githubusercontent.com/assets/168849/23526772/29d70254-ff48-11e6-9e16-359fa387b04f.png)

**Comment by abdgad** [comment]
What do you think about this? The tostr notification will fade out as usual, but the Bootstrap notification will stay there unless you dismiss it.
![db_errs](https://cloud.githubusercontent.com/assets/24955909/23570157/50458412-0063-11e7-96fc-743b865c9d1a.png)
