### ISSUE TITLE
How i may change HTML generate (menu)?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#863]
- Laravel Version: 5.4
- Voyager Version: New
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

```
        $menu = menu('main');
        dump($menu);
```
Where this HTML code generate? 
And how i may fix it, and use some CSS.

**Comment by dimsanchuk** [comment]
https://the-control-group.github.io/voyager/docs/v0.10/#core-concepts-menus

**Comment by Rishats** [comment]
I was read it. But i have some problem with this.
I create my_menu.
But when i try use it, i have problem.
**Class 'Menu' not found**


So i try to find default code, and change it for myself ^)

**Comment by Stormix** [comment]
Add this on top of your code : 
`use TCG\Voyager\Models\Menu;`
