### ISSUE TITLE
How to change the wheel animation during boot?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#869]
- Laravel Version: 5.4
- Voyager Version: new
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:
How i may change loading image?

**Comment by marktopper** [comment]
The setting for this is `admin_loader`.

**Comment by OmarTriguiwx** [comment]
where i can exactly find the admin_loader ?

**Comment by marktopper** [comment]
It should be on the settings page? Isnt it there?

**Comment by OmarTriguiwx** [comment]
I cant find it either in the voyager folder neither in the app.config file

**Comment by marktopper** [comment]
What about the settings table? See it there?

**Comment by OmarTriguiwx** [comment]
nothing is there ... the table is empty 
![capture](https://cloud.githubusercontent.com/assets/23701307/23769526/f6cac65c-050f-11e7-9385-e2e602eae5f2.PNG)

**Comment by marktopper** [comment]
Will be back with a solution tomorrow.

**Comment by OmarTriguiwx** [comment]
okey 👍  Thanks

**Comment by marktopper** [comment]
Okay, you have the following options when it comes to getting this setting.
First you can add the setting manually by going to `/admin/settings` and create the following setting.
<img width="443" alt="skaermbillede 2017-03-10 kl 09 33 09" src="https://cloud.githubusercontent.com/assets/2232539/23787924/9c51ab72-0574-11e7-8b4d-781b4b312241.png">

Second you can get all Voyager default settings by running the settings seeder.
```
php artisan db:seed --class SettingsTableSeeder
```
