### ISSUE TITLE
No columns being created in table

### ISSUE THREAD

**Issue by dsamurai** [thedevdojo/voyager#871]
- Laravel Version: 5.3.*
- Voyager Version: 0.1.0
- PHP Version:7.1
- Database Driver & Version:mariadb 10.1.19

### Description:
Database table columns not being created.. No timestamp field button. 

### Steps To Reproduce:
Just create a new table with fields.
![voyagerissue2](https://cloud.githubusercontent.com/assets/14809460/23585874/1566465a-019a-11e7-8795-7476a8d42698.PNG)
![voyagerissues3](https://cloud.githubusercontent.com/assets/14809460/23585875/158eb658-019a-11e7-9fbd-82e1d4dfa877.PNG)
![voyagerissue1](https://cloud.githubusercontent.com/assets/14809460/23585876/158f3dbc-019a-11e7-8808-90017f0dd4ad.PNG)

**Comment by abdgad** [comment]
After you add the columns, you need to click on `Update Table`. You should see a message saying: `The table was updated successfully`.
And you can add `Timestamp` field by adding a new column and choosing `TIMESTAMP` as its type.
Let me know if you're still having issues.
