### ISSUE TITLE
Sending more data to customized view (Edit & Add)

### ISSUE THREAD

**Issue by Xoshbin** [thedevdojo/voyager#878]
Is there anyway to to send more data to the view? let's say I have an orders table and order_details table, order_details table have order_id row relational to order's id. in the edit view of orders page I want to have order_details data that's connected to this order id.
If there's mo way to have these data relation in the page, where is the voyager controllers so I can edit it by myself? because I looked around the source code and I can't find a specific controller that's made for my tables. I already made relations between the two tables in the bread but I can receive only the data's from order table not order_details table. in the edit view.

**Comment by abdgad** [comment]
Can you please be more specific about which `edit` view you're speaking about. Please paste the url.

**Comment by Xoshbin** [comment]
@abdgad 
I mean edit-add.blade.php
[link](https://the-control-group.github.io/voyager/docs/v0.10/#customization-overriding-views)

**Comment by abdgad** [comment]
ping @marktopper

**Comment by Xoshbin** [comment]
For now I just solved it like this:

```
<?php 
use App\OrderDetail;
$OrderDetail = OrderDetail::where('order_id',$dataTypeContent->id)->get();
?>
```

in the edit-add.blade.php page

**Comment by gavinj1999** [comment]
I'd be interested to see a screenshot buddy.

**Comment by Xoshbin** [comment]
@gavinj1999 
![capture1](https://cloud.githubusercontent.com/assets/1606070/23662895/04ad283c-0362-11e7-81fa-36a8964eebf3.PNG)

**Comment by gavinj1999** [comment]
Thanks buddy.

**Comment by Xoshbin** [comment]
Welcome buddy

**Comment by fletch3555** [comment]
To add data to your view, you have a couple options.  Either override the controller and add the data there, use a [view composer](https://laravel.com/docs/5.4/views#view-composers), or break best-practices and get data directly within the overridden view (like you're currently doing).

**Comment by fletch3555** [comment]
Closing this for now.  We may revisit this as future functionality.
