### ISSUE TITLE
what model should i use ?

### ISSUE THREAD

**Issue by OmarTriguiwx** [thedevdojo/voyager#882]
Laravel Version: 5.4
Voyager Version: new
PHP Version: 7.1
Database Driver & Version: MySQL 5.7

### Description:
i was wondring if i have to change the user model for exemple add some  laravel eloquent relations should i add it in the app/User.php or in the vendor/tcg/src/models/User.php model ?

### Steps To Reproduce:
none

**Comment by sikhub** [comment]
Never change files in vendor folder! One of the reason is that you will rewrite custom files with composer update.
Good practice is that you create new model in your project folder.

**Comment by OmarTriguiwx** [comment]
even if i want to change some design of the voyager views  ?

**Comment by jarocks** [comment]
Is there a way to override the views provided by voyager? They don't seem to be included in the publishable files.

**Comment by OmarTriguiwx** [comment]
i don't think so .. you probably should modify the existing file in the publishable folder

**Comment by marktopper** [comment]
You can change swap the Voyager models with your own models.

```
// Use \App\User as the Voyager "User" model
Voyager::useModel('User', \App\User::class);
```
