### ISSUE TITLE
How do I deploy Laravel (Shared hosting) with Voyager

### ISSUE THREAD

**Issue by borjadub** [thedevdojo/voyager#883]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.4
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7

### Description:

Hi.

Sorry for my bad English.

I put the public folder (Laravel) files in the hosting root (public_html) and the Laravel components in the host root (/)

/ > /App /bootstrap ...

/Public_html > index.php, assets ... (Public folder Laravel)

I enter in mydomain.com/admin and it works fine, I access the panel without problems but when I upload images then they do not load and are not read correctly.

I think I did wrong when uploading the files.

Thanks.

**Comment by marktopper** [comment]
I found this guide for you.
https://medium.com/laravel-news/the-simple-guide-to-deploy-laravel-5-application-on-shared-hosting-1a8d0aee923e#.262dmhhz9
