### ISSUE TITLE
include voyager views

### ISSUE THREAD

**Issue by OmarTriguiwx** [thedevdojo/voyager#885]
Laravel Version: 5.4
Voyager Version: new
PHP Version: 7.1
Database Driver & Version: MySQL 5.7
### Description:
how can i include voyager theme in my main project ?

### Steps To Reproduce:
none

**Comment by abdgad** [comment]
In your views, you can use `@extends('voyager::master')`.
Take a look at: https://github.com/the-control-group/voyager/blob/master/resources/views/master.blade.php
