### ISSUE TITLE
Error upload SVG file

### ISSUE THREAD

**Issue by acidcrash2005** [thedevdojo/voyager#893]
- Laravel Version: 5.3
- Voyager Version: v0.10.11
- PHP Version: 5.6.4
- Database Driver & Version: 

### Description:
When I upload SVG file, with field type image, I get an Error `NotReadableException in Decoder.php line 20:
Unable to read image from file (D:\OpenServer\userdata\temp\phpFC49.tmp).`
Is it a possible to upload SVG files?

### Steps To Reproduce:

**Comment by lancepioch** [comment]
Labels: bug, question

**Comment by davodavodavo3** [comment]
Close this issue , Now you can upload all you need.

**Comment by fletch3555** [comment]
@davodavodavo3, just a note. When you submit bugfix PRs, please make sure to include a comment such as "fixes [issue number]", and it will automatically close the issue when merged.

Closing this.
