### ISSUE TITLE
I get error Failed to load resource: net::ERR_CONNECTION_REFUSED in firebug even though I successfully linked storage folder. This happens when retrieving images 

### ISSUE THREAD

**Issue by James7777** [thedevdojo/voyager#894]
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

**Comment by abdgad** [comment]
Please update the issue and include all necessary details.

**Comment by sikhub** [comment]
Did you set `APP_URL` in `.env` ?

**Comment by fletch3555** [comment]
Closing as inactive.  @James7777, if this is still an issue, please edit this and add a Description and Steps to Reproduce, and we'll reopen it.

Thank you.

**Comment by michaelwzk** [comment]
i have a problem,like this problem.
![image](https://user-images.githubusercontent.com/15699224/71607368-c0158e80-2bb3-11ea-8690-8418f49d8b38.png)
![image](https://user-images.githubusercontent.com/15699224/71607360-aecc8200-2bb3-11ea-9fb3-334dc62cfe4d.png)
