### ISSUE TITLE
[feature request] json editor in bread input type

### ISSUE THREAD

**Issue by ockam** [thedevdojo/voyager#895]
- Laravel Version: 5.4
- Voyager Version: 0.11.5

### Description:
Since the bread editor already use the Ace editor for BREAD options, an Input type for JSON data that also use it would be a nice addition.

**Comment by Frondor** [comment]
A json `formField`... Its possible (although we shouldn't use MySQL JSON dataType because its not widely supported yet) but, what would be a possible use case for it?

**Comment by ockam** [comment]
You could use it with a JSON or TEXT field, if you’re using an older version of MySQL.

We are currently using this pattern to store configuration for a survey’s questions table. Using JSON keeps the table simple and allow us to easily add custom settings for each type of question (much in the same way you’re storing options for BREAD).

**Comment by coseyo** [comment]
Yep, I agree with @ockam. I use json structure input but in fact it is text datatype in mysql. That is good for me.

**Comment by fletch3555** [comment]
I'm going to close this for now.  There have been significant changes since 0.11.5.  We can revisit it after 1.0 gets released

**Comment by sagynbek** [comment]
Hey there, we hopefully we got to v1.1. And it is good so far. 
What about this input type as JSON in BREAD?
