### ISSUE TITLE
Issue getting it to work, maybe due to apache

### ISSUE THREAD

**Issue by RPBTwisted** [thedevdojo/voyager#897]
- Laravel Version: 1.3.5
- Voyager Version: Latest
- PHP Version: 7.0.16
- Database Driver & Version: N/A

### Description:

I cannot access the application at all. I had it working previously with another Laravel installation, but the minute I tried to re-direct it to this one it stops working. I'm fairly new to Laravel, but because I manage the Apache server myself I may have to change something there too? I really don't know. I know that it might not concern Voyager too much but the friend I ask for help is away with their fiance for three months and I need this for my dissertation. I'd greatly appreciate some help if you can spare the time. 

### Steps To Reproduce:

Error shown: http://bennett-computing.co.uk/
Directory is set to Var/www/blog in the apache config
Document room is set to the public folder

**Comment by Codebreaker101** [comment]
Do  `php artisan route:list`.
Are your `admin/*` routes registered?

**Comment by RPBTwisted** [comment]
Oh, I got it working but I can't access the /admin page? http://bennett-computing.co.uk/admin

The default splash screen works but not the admin page? I literally had it set up using the make:auth login and have no changed anything besides setting this as my main project through apache

**Comment by Codebreaker101** [comment]
http://bennett-computing.co.uk/index.php/admin is saying that the route is not found. 
Run command `php artisan route:list` and post a screenshot of the routes.

**Comment by RPBTwisted** [comment]
https://gyazo.com/fde701bb806feb04bd0be3904e54d621

**Comment by Codebreaker101** [comment]
As you can see, the Voyager routes aren't registered. 

Do you have this code in `routes/web.php`
```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```

**Comment by RPBTwisted** [comment]
That could be why. It wasn't in the installation documentation haha. I'll have a look now.

**Comment by RPBTwisted** [comment]
Yeah, it shows an error on the site if you can see it. I'm assuming I need to set the default route too?  or?

**Comment by Codebreaker101** [comment]
Did you do a fresh install of Voyager or update from an older version? 

If you did upgrade follow these steps to upgrade database
https://the-control-group.github.io/voyager/docs/v0.10/#getting-started-upgrading-version-09-to-010

**Comment by RPBTwisted** [comment]
I did a fresh install

**Comment by RPBTwisted** [comment]
Any idea what that could be?

**Comment by Codebreaker101** [comment]
I see you got it working. Now do a couple more things 

1. Check this out https://laravel.com/docs/5.4/installation#pretty-urls. This will remove the index.php from url
2. Correctly set .ENV APP_URL. Currently it is pointing to localhost. 

This will fix your images not showing up. 

PS. change the email and password from defaults.

**Comment by RPBTwisted** [comment]
Wait? I got it working? I get page not found when I do anything on it haha.

**Comment by Codebreaker101** [comment]
http://bennett-computing.co.uk/index.php/admin/login

This link works fine. 
Index.php is the entry point of the application. Check my previous comment on how to 'hide' it as well as other notes. 
And you're good to go!

**Comment by wzulfikar** [comment]
@RPBTwisted for the record about registering voyager routes, it's actually written in voyager docs. 

https://the-control-group.github.io/voyager/docs/v0.10/

![screen shot 2017-03-11 at 6 41 39 pm](https://cloud.githubusercontent.com/assets/7823011/23822610/a7aac14a-068a-11e7-83c0-b85a2d9abc9a.jpg)

**Comment by fletch3555** [comment]
@RPBTwisted, this seems to have gotten off-track a little.  The routes are added by `php artisan voyager:install`, which is definitely in the docs.  Looks like you may not have run that.

Also, the reason `public/index.php` is required for it to work is because of how you have Apache configured, which is unfortunately outside the scope of what we can officially support here.
