### ISSUE TITLE
Missing storage symlink (Shared hosting)

### ISSUE THREAD

**Issue by borjadub** [thedevdojo/voyager#898]
- Laravel Version: 5.3.*
- Voyager Version: 0.10.14
- PHP Version: 5.6
- Database Driver & Version: MySQL 5.7

### Description:

Hello.

Sorry for my bad english.

I put my laravel project in shared hosting but they are an error in the panel admin:

```
Missing storage symlink
We could not find a storage symlink. This could cause problems with loading media files from the browser.
```

In shared hosting I can't use SSH to make symbolic link and with cron jobs it doesn't work.

cron job:
ln -s /storage/app/public /public_html/storage/

Thanks.

**Comment by Frondor** [comment]
This is not Voyager-related I'm afraid.

Create a route (make sure you're not using cached routes yet, and you have not a folder named "storage" in your `/public` folder, or the symlink won't be created) like this
```
Route::get('/install', function () {
	Artisan::run('storage:link');
  return redirect('/?done');
});
```
upload your site and then visit that route.

**Comment by borjadub** [comment]
Thanks @Frondor !

**Comment by olko404** [comment]
@Frondor , can you say why I have this mistake after visit route "domain-name.com/install".  


![1](https://cloud.githubusercontent.com/assets/20544156/26400641/a9ff2e92-408a-11e7-88a9-af44f635fffd.png)

I cleared cache, deleted storage folder in public and added this route:

```
Route::get('/install', function () {
	   Artisan::run('storage:link');
  return redirect('/?done');
}); 
```
