### ISSUE TITLE
Adding new table

### ISSUE THREAD

**Issue by tnylea** [thedevdojo/voyager#9]
Adding new table in voyager needs to make sure that the Primary ID has an auto_increment value otherwise you may receive an error when adding a new data type and not specifying an ID

**Comment by edmeehan-tcg** [comment]
+1 was getting an error when trying to add new entries into a table.

**Comment by filipsobol** [comment]
+1, I'm not able to find any option to add "auto_increment" value from admin panel.

Edit:
I noticed that ID in new tables has auto_increment value, but it's removed when table is updated.

**Comment by Laran01** [comment]
I noticed that ID in new tables has auto_increment value, but it's removed when table is updated.

**Comment by marktopper** [comment]
Seems to be fixed

Ping me if I'm wrong.
