### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by soly2014** [thedevdojo/voyager#90]
is there is rtl support

**Comment by mustafa-qamaruddin** [comment]
Any RTL support?

**Comment by marktopper** [comment]
Working on it #789

**Comment by marktopper** [comment]
I am not much familiar with RTL designs, could use some help figuring out where to place what.
Could you guys help me on Slack?

**Comment by mustafa-qamaruddin** [comment]
What is the slack channel for the project?

**Comment by marktopper** [comment]
https://voyager-slack-invitation.herokuapp.com/

**Comment by marktopper** [comment]
I have got some progress now, please see the pull request at #789 and come with feedback. Thanks 🎉

**Comment by lancepioch** [comment]
labels: enhancement, locale

**Comment by mbdwey** [comment]
Please close as duplicate of #789.

**Comment by fletch3555** [comment]
Agreed.

**Comment by loverdeveloper** [comment]
https://gist.github.com/abdumu/77287635e282f1bb733b84360b95af66#file-laravel-voyager-admin-rtl-css

**Comment by fletch3555** [comment]
@loverdeveloper that comment provides zero benefit since this has been closed for over a year and a half, and was related to a much older version.  Please don't comment on such old issues.
