### ISSUE TITLE
OneToOne relationship - unique and exclude

### ISSUE THREAD

**Issue by Codebreaker101** [thedevdojo/voyager#900]
- Laravel Version: 5.4
- Voyager Version: 0.11.5
- PHP Version: 7.0
- Database Driver & Version: MySQL

### Description:

I have an table that stores all of my RFID cards, and a table with my users that references the RFID card in one-to-one relationship. This works as expected. 

I need to build upon this and add two things

1. **Unique**
     When adding an RFID card to a user the dropdown should be filled only with those RFID cards that are not already assigned to a user

2. **Exclude**
     RFID table has an `enabled` column. I wish to exclude those RFID cards from the list that are disabled ( `enabled == 0` )

Is this possible without upgrading Voyager?

**Comment by fletch3555** [comment]
This is a Laravel question, not a Voyager one.  Just update your model's relationship to limit the results: https://laravel.com/docs/5.4/eloquent-relationships
