### ISSUE TITLE
Help Needed for to add where clause in user model

### ISSUE THREAD

**Issue by ashishshah-github** [thedevdojo/voyager#902]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.5
- PHP Version: 5.6.25
- Database Driver & Version: 5.7

### Description:
Hello,

can anyone let us know how to add where clause in either User model or VoyagerBreadController ? we need to display only specific role users on page ?

Thanks!

**Comment by fletch3555** [comment]
This is Laravel functionality, not a Voyager issue.  Please read the Laravel docs.

To point you in the right direction, you need to look into [`query scopes`](https://laravel.com/docs/5.4/eloquent#local-scopes).
