### ISSUE TITLE
Direct links

### ISSUE THREAD

**Issue by HeshamAlassaf** [thedevdojo/voyager#903]
Hello,

Sorry for the title but I didn't know how to describe it, what im trying to do is, let say I have a page called categories inside it there is a category called phones what i need it when i enter categories and click on phones category it directly sends me to products and display phones ? 

I hope this explains it.

**Comment by fletch3555** [comment]
That's a bit too specific for us to support package-wide.  You should be able to do so by overriding the category view(s) and adding the links yourself.
