### ISSUE TITLE
[Feature Request] Menu Builder Route Prefixes

### ISSUE THREAD

**Issue by maiorano84** [thedevdojo/voyager#906]
After playing around with everything since the last time I took a look, I wanted to check and see if this would be something that people might want.

As it stands, installing Voyager will drop a small bit of code into the Routes file with a nice Prefix that a developer can go in and change at their leisure. The problem is that after installation if somebody wants to change this prefix, all seeded admin menu items won't reflect the new change:

1. Install Voyager
2. Change the route prefix in routes/web.php to something else
3. Log into Voyager
4. Click a Menu Item

The only way a developer can change the route prefix is by first changing each menu item route by hand (*before* changing the prefix), and then adjusting the prefix in the routes file.

For new users, this approach may not seem apparent and could cause confusion when changing the prefix first and being presented with a NotFoundHttpException after clicking any of the admin menu items.

This can be remedied fairly easily by a few approaches:

1. Add an additional prompt during the installation process to allow the user to install Voyager on a nonstandard route with `admin` being the default
2. Add an optional `prefix` input under the Menu Editor that will prefix all **(?)** menu items with the designated menu prefix (should one exist)
3. Add an additional artisan command that will change the `routes/web.php` file as well as the seeded menu items to reflect the new change (ie: `voyager:routes:prefix`)

I see Item 1 being a good start, and perhaps the easiest in terms of getting Voyager set up with the desired routes.

I see Item 3 being more complicated to implement due to rewriting the `routes/web.php` reliably, but would ultimately streamline the prefixing process nicely

The only one I'm unsure about is Item 2, as this may have unintended consequences for users who want to include prefixed routes with external URLs in their menus.

Thoughts?

**Comment by fletch3555** [comment]
This has been discussed a few times in the past.  The method we've discussed in the past is to give menu items the option of storing a static URI or a route name.  So you could store the link as "admin.users.index" as your link, and it would render as "/admin/users".

I'm not sure if @marktopper has made any progress on this, so I'll let him respond.

**Comment by marktopper** [comment]
The menu builder already supports routes, however we still need to make the seeder for the menu items to use routes as well in order to solve this.
