### ISSUE TITLE
Error When Create New Category or Update Post Category 

### ISSUE THREAD

**Issue by aymann90** [thedevdojo/voyager#909]
- Laravel Version: 5.3.16
- Voyager Version: 0.11.#
- PHP Version:5.6
- Database Driver & Version:

### Description:
1-error when create new Category 
2-can't update Post Category

**Comment by fletch3555** [comment]
Please provide error messages

**Comment by aymann90** [comment]
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '_empty_' for column 'parent_id' at row 1 (SQL: insert into `categories` (`parent_id`, `order`, `name`, `slug`, `updated_at`, `created_at`) values (_empty_, 1, cat4, cat4, 2017-03-12 19:30:43, 2017-03-12 19:30:43))
