### ISSUE TITLE
Bug with category add

### ISSUE THREAD

**Issue by vladimirstempel** [thedevdojo/voyager#915]
- Laravel Version: 5.4
- Voyager Version: 11.6
- PHP Version: 5.6
- Database Driver & Version: MySql 5.5

### Description:
i found bug with categories, when you add first category, you need to add parent category, but its not exist and you get the error

### Steps To Reproduce:
1. Add new category
http://joxi.ru/MAj9jDRIPgbY2e
2. Fill all fields
http://joxi.ru/Vm6RVEkia5MNmZ
3. If you dont have any categories and dont choose parent category, you will get an error
http://joxi.ru/V2VgjJGH5zyQAv

**Comment by turtuga** [comment]
I created a PR https://github.com/the-control-group/voyager/pull/916

**Comment by vladimirstempel** [comment]
Thank you)
