### ISSUE TITLE
Voyager can't load the assets.

### ISSUE THREAD

**Issue by serkanguzel-fe** [thedevdojo/voyager#918]
- Laravel Version: 5.4.15
- Voyager Version: 0.11.16
- PHP Version: 7.0.1
- Database Driver & Version:

### Description:
I have started using voyager today, did a clean install with a new project, managed to login, but the images isn't loading up. 
![voyagerproblem](https://cloud.githubusercontent.com/assets/22130520/23863325/86edda90-0820-11e7-8658-7d10b71c4274.png)

i tried "php artisan storage:link" it didn't solved my problem.

**Comment by abacram** [comment]
Same for me, i'll be watching for this issue update.
It could be related to the symbolic link on public/storage folder?

Thanks!

**Comment by serkanguzel-fe** [comment]
Maybe, i tried to change the links in browser to reach some assets but it didn't work either, how can we change that symbolic links?

**Comment by abacram** [comment]
Ok, my problem was that i always worked with multiple environment and I usually do "php artisan:serve" with the port option.

If it's your case (same as me), just update your .env file with the port, like this:
`APP_URL=http://localhost:8050`

Or run php artisan:serve without the --port option.

Hope it helps!!!

**Comment by iMestav** [comment]
Change .env file in APP_URL variable with http://localhost to voyagertest.dev

**Comment by serkanguzel-fe** [comment]
changing the APP_URL didn't work, sorry :(

**Comment by serkanguzel-fe** [comment]
Ah, it worked now. Thanks.
