### ISSUE TITLE
Database Timestamp Helper Buttons

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#921]
- Laravel Version: 5.4.15
- Voyager Version: 0.11.6
- PHP Version: 7.1.1
- Database Driver & Version: MySQL / 10.1.21-MariaDB

### Description:
I think that we should add the helper buttons back to the database section that easily added the `updated_at` and `created_at` timestamp fields as well as the button to add the `deleted_at` timestamp field that existed back in `v0.10.x`.

**Comment by abdgad** [comment]
The current way the db manager works, adding such buttons require additional code to perform validation before adding the columns. I don't want these buttons to be added at the moment, as they are not necessary, and people can always add these columns manually, it's not a lot of work.
Will comeback to this only after core features are added and stable.

**Comment by abdgad** [comment]
Since a lot of people are asking for this, I will create a PR for it.
