### ISSUE TITLE
Delete Menu Translations when deleting a menu item

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#922]
- Laravel Version: 5.4.15
- Voyager Version: 0.11.6
- PHP Version: 7.1.1
- Database Driver & Version: MySQL / 10.1.21-MariaDB

### Description:
When a menu item is deleted, the translations for it are not deleted.

### Steps To Reproduce:
1. Turn on the multilingual system and ensure that you have at least 2 languages, your default language and another.
2. Then open up the `admin` menu builder and make a new menu item, be sure to enter a `title` for all of your languages.
3. Then delete the menu item.
4. The translations for that menu item does still exists in the `translations` table.

**Comment by akazorg** [comment]
Nice catch
