### ISSUE TITLE
merge tables 

### ISSUE THREAD

**Issue by mustafaabduljalil** [thedevdojo/voyager#927]
- Laravel Version: 5.4
- Voyager Version: 11
- PHP Version:5.6
- Database Driver & Version:mysql

### Description:

if i have already tables in my database can i merge it to voyager and there is tables in voyager i need it can i remove them ?

**Comment by abdgad** [comment]
Can you please explain what you mean by "merging" your tables into Voyager, and by removing Voyager tables? Please give us examples.

**Comment by mustafaabduljalil** [comment]
@abdgad in my project i have tables and i want to create admin panel to manage in these tables 
example i have company table i can create it in voyager ok
in voyager by default there is menu tables and anther table can i remove voyager's table that installed with it can i remove it and put my project's tables ??

**Comment by abdgad** [comment]
You can use your tables, just go to `Tools > Database`, and you should see them there. You can click on `Add BREAD to this table` for the tables you want to manage.
And you can remove menu items that you don't want. You can go to `Tools > Menu Builder` to do that.
**Note:** make sure to backup your database to avoid accidentally deleting it.

**Comment by abdgad** [comment]
@mustafaabduljalil if your questions have been resolved, please close the issue. Otherwise, tell us what else you need :)
