### ISSUE TITLE
Voyager basic

### ISSUE THREAD

**Issue by dotWaldemar** [thedevdojo/voyager#929]
Hello!
Voyager its a great job but i have a question. How i can use from voyager just a template and user permissions? Other i no need!

**Comment by marco-solare** [comment]
just install it to a freshly generated laravel5.4 app, run the migrations, use what you need (will be pretty self-explanatory if you are proficient with laravel).
You could also have a look at the implementation of the user permissions and use them (or get inspired by them to implement your own similarly)

**Comment by fletch3555** [comment]
Unfortunately we don't really have a way to strip Voyager down to the bare minimum.  At least, not to the extent you're requesting.  I'd hate to send you away from this project, but if all you need is permissions, I'm sure there are other packages that may be better suited for you/your needs.

If you really want to use Voyager, you'll have to manually strip out functionality.  We can't officially support that action, though if you run into issues, we should be able to help you determine what caused it.  In this case, I would recommend you join our Slack group (instructions in the project ReadMe), and post questions in the "help" channel.

Best of luck!
