### ISSUE TITLE
Database Buttons

### ISSUE THREAD

**Issue by iboldurev** [thedevdojo/voyager#931]
- Laravel Version: 5.4
- Voyager Version: 0.11.6
- PHP Version: 7
- Database Driver & Version:

### Description:

No shortcut keys on database
- + Add Timestamp Fields
- + Add Soft Delete Field

@marktopper

**Comment by abdgad** [comment]
Duplicate of #921

**Comment by abdgad** [comment]
Right now, you can manually add `created_at`, `updated_at`, `deleted_at` columns and set their type to `TIMESTAMP`.
