### ISSUE TITLE
login table

### ISSUE THREAD

**Issue by mustafaabduljalil** [thedevdojo/voyager#934]
- Laravel Version: 5.4
- Voyager Version: 11
- PHP Version:5.6
- Database Driver & Version:

### Description:
@abdgad 
how can i make admin login in another table instead of users table 
example : i created admins table it's attributes id,email,password i want admin login through this table instead of users table which it is already exits in laravel ??

thanks

**Comment by abdgad** [comment]
You can specify the table you want to use in the model by adding this:
```php
protected $table = 'admins';
```

However, I currently don't know the best way to extend Voyager's User model. One way is to do:
```php
class User extends \TCG\Voyager\Models\User
{
    protected $table = 'admins';
}
```

@marktopper can tell you more information.

**Comment by marktopper** [comment]
The login system uses the Voyager `User` model in order to login, however you can overwrite this as @abdgad told by creating your own class at:

`app/VoyagerUser.php`
```
<?php

namespace App;

class VoyagerUser extends \TCG\Voyager\Models\User
{
    protected $table = 'admins';
}
```

And then tell Voyager to use that model for the users.
```
Voyager::useModel('User', \App\VoyagerUser);
```

**Comment by mustafaabduljalil** [comment]
thank you so much :) 
@abdgad  @marktopper

**Comment by mustafaabduljalil** [comment]
i'm sorry it give me this error

![screenshot from 2017-03-14 15-08-49](https://cloud.githubusercontent.com/assets/14807431/23901995/28beae9c-08c8-11e7-8adf-ce84d8defde9.png)

**Comment by marktopper** [comment]
Can you please update your `composer.json` file to use `dev-use-user-model` as version for Voyager.
Then run a `composer update` and test this out again.

Please let me know wether or not it works, cause then I can merge this in and tag a new release.
Thanks for the report.

**Comment by mustafaabduljalil** [comment]
@marktopper 
i did what u said but give me same problem :(

**Comment by marktopper** [comment]
Okay. Once I get home I will look into this and notice you.

**Comment by mustafaabduljalil** [comment]
ok thanks for your efforts

**Comment by marktopper** [comment]
Sorry for the delay, have been busy.

**Comment by mustafaabduljalil** [comment]
ok no problem :)

**Comment by u01jmg3** [comment]
@marktopper: any progress with this?

I have created a separate `SiteEditor` user class as per your instructions but still Voyager is using the `User` model and therefore the `users` table.

`Voyager::useModel('User', \App\Models\SiteEditor::class);` has been added to `AppServiceProvider::boot()`.

**Comment by omzy** [comment]
Same issue as @u01jmg3 above. I am using Laravel 5.4 and cannot get this to work using a different users table called `admins`. It still tries to use the `users` table.

**Comment by omzy** [comment]
@marktopper do you have any suggestions for this?

**Comment by talas9** [comment]
Any updates with this issue because it would be wonderful if you can separate 'users' table from 'admins' table!

**Comment by handiwijoyo** [comment]
@marktopper solution should work. Close this for now.

**Comment by iwasherefirst2** [comment]
I have the same issue as stated in https://github.com/the-control-group/voyager/issues/934#issuecomment-286415632
