### ISSUE TITLE
The translations migration needs to get different file name

### ISSUE THREAD

**Issue by hazem1taha** [thedevdojo/voyager#938]
I'm using this package

https://github.com/barryvdh/laravel-translation-manager

which generates a migration file with the same name Voyager's translations table migration file has, I assume many users will face this issue.

Thanks.

**Comment by akazorg** [comment]
@abdgad your idea of prefixing tables with `voyager_table` sounds great.

For the breaking changes, we can write a migration for that?
Migration would:
1. drop foreign keys
2. rename tables, ex. `Schema::rename('menu', 'voyager_menu')`
3. create foreign keys back

However, if user added additional FK, it would break. Should we deal with this too, or let the users do it?

**Comment by lancepioch** [comment]
Labels: bug, refactor

**Comment by handiwijoyo** [comment]
Please create new issue for table prefix name. Close this due inactivity.
