### ISSUE TITLE
voyager admin panel Profile picture doesn't appear . and also when I edit user's profile . any help ?﻿

### ISSUE THREAD

**Issue by pappu2017** [thedevdojo/voyager#939]
- Laravel Version: 5.4
- Voyager Version: #.#.#
- PHP Version:7.1
- Database Driver & Version:

### Description:
voyager admin panel Profile picture doesn't appear . and also when I edit user's profile . any help ?﻿

**Comment by Frondor** [comment]
`php artisan storage:link`

**Comment by anderfernandes** [comment]
@pappu2017 In my project, I added the port to my "APP_URL" on my .env file and it worked. Remember to remove the port number when you deploy your app.

**Comment by pappu2017** [comment]
@Frondor  php artisan storage:link
The "public/storage" directory already exists.  

Profile picture doesn't appear. any help?

**Comment by pappu2017** [comment]
@anderfernandes I added the port to my "APP_URL" on my .env file, but it doesn't   work

**Comment by Frondor** [comment]
@pappu2017 because it surely is a folder, not a symbolic link (happens mostly on windows).
Delete `public/storage` manually and run the command.

**Comment by pappu2017** [comment]
@Frondor its working..
Thank you so much

**Comment by pappu2017** [comment]
In CRUDBooster admin panel How to implement categories and sucategories in one table? Can you show me with an example?

**Comment by Emmathem** [comment]
I added my listening port to my APP_URL in .env file and it works
http://localhost:2000

**Comment by fletch3555** [comment]
Yes, that is the solution that has been mentioned in literally dozens of issues like this one.  Please don't comment on issues that have been closed so long.  They're closed for a reason, and we're for a much older version anyway

**Comment by jairo821** [comment]
> @Frondor está trabajando .. 
> Muchas gracias .

veo que te resulto, mi pregunta es que comando ejecutaste

**Comment by jairo821** [comment]
> @ pappu2017 porque seguramente es una carpeta, no un enlace simbólico (ocurre principalmente en Windows). 
> Eliminar `public/storage`manualmente y ejecutar el comando.

que comando ejecuto despues?

**Comment by ghost** [comment]
> @ pappu2017 porque seguramente es una carpeta, no un enlace simbólico (ocurre principalmente en Windows). 
> Eliminar `public/storage`manualmente y ejecutar el comando.

que comando ejecuto despues
