### ISSUE TITLE
Delete an Images from MultipleImage Input Type return 500 internal server error

### ISSUE THREAD

**Issue by hugosvent** [thedevdojo/voyager#940]
Laravel Version: 5.4.10
Voyager Version: 0.11.7
PHP Version: 7.0.14
Database Driver & Version: MYSQL 5.7.17

### Description:
When I try to delete one of my multiple images input type. It does not do anything and just response with 500 internal server error.
Tried to look at the network call and it return 500 with

{data: {status: 500, message: "Trying to get property of non-object"}}

**Comment by hugosvent** [comment]
help @sikhub

**Comment by dragonbmt199** [comment]
![image](https://cloud.githubusercontent.com/assets/20114229/24589803/2781a4f6-180b-11e7-9059-ef878b3f7c92.png)
Me too. Need help!

**Comment by lancepioch** [comment]
Labels: bug

**Comment by hugosvent** [comment]
It's been fixed on the latest version.
@fletch3555 maybe can close this alrdy.

thank you
