### ISSUE TITLE
Modifying the backend, possible?

### ISSUE THREAD

**Issue by RPBTwisted** [thedevdojo/voyager#944]
- Laravel Version: Current
- Voyager Version: Current
- PHP Version: 7.10
- Database Driver & Version: N/A

Just curious, but how do you make changes to the panel itself. I'd like to add a menu to it that shows "all servers" for some game servers I have. It's literally just a piece of JS/PHP that'll pull server data, but I wanted this displayed on the Voyager backend as it makes no sense creating a panel from scratch to do this. Is it possible?

**Comment by Frondor** [comment]
First you'll need to get familiarized with Voyager's BREAD concept.

Then, please, read the docs https://the-control-group.github.io/voyager/docs/0.11/#customization-overriding-views

**Comment by RPBTwisted** [comment]
Just a quick add-on... Why does going here return the error that it returns? http://bennett-computing.co.uk/login 

That's the default laravel login framework but Voyager broke it?

**Comment by sarath-c-sandwich** [comment]
Please check your route first,
```
php artisan route:list
```
Do you see, /login available there? I don't find either /admin 
Check your .htaccess or nginx rewrite_rule

**Comment by RPBTwisted** [comment]
https://gyazo.com/f7e249431d750c50ca455d82f02fa080
https://gyazo.com/d7e342b9d24e64ebc81d4c15655e30e5

What does my .htacess need to look like ideally?

**Comment by fletch3555** [comment]
@RPBTwisted, are you still having issues?  Please follow @Frondor's directions to get started with adding a page to Voyager

**Comment by RPBTwisted** [comment]
Nah I got it, thank you!
