### ISSUE TITLE
Bootstrap menu builder

### ISSUE THREAD

**Issue by Ferrisbane** [thedevdojo/voyager#949]
- Laravel Version: v5.4.15
- Voyager Version: v0.11.7
- PHP Version: 5.6
- Database Driver & Version: mysql

### Description:
Using the bootstrap theme with the menu builder, any links in a sub-menu contain the bootstrap dropdown classes, stopping the link from working

### Steps To Reproduce:
Create menu
Add items
Move some items to be in a submenu
Display the menu using the bootstrap theme (`menu('menu-name', 'bootstrap')`)
Click the the item that is the dropdown
Try clicking on any links inside

**Comment by qodeanil** [comment]
Even i had faced same prob, but i fixed this issue by doing following stuff

1. Go to bootstrap.blade.php which is in the path vendor/tcg/voyager/resources/views/menu.bootstrap.blade.php

There you add the code 

  // With no Children Attributes
        if($item->children->isEmpty()) {
        $linkAttributes =  'class="no-class" data-toggle="no-toggle"';
        if(url($item->link()) == url()->current()){
        $listItemClass = 'dropdown active';
        }else{
        $listItemClass = 'dropdown';
        }
        }

This will work the menu, but rather than doing this, create your own nav.blade.php, add the entire code of bootstrap.blade.php along with above code

and call the menu  (menu('menu-name', 'nav'))

Your problem is solved

**Comment by qodeanil** [comment]
[nav.blade.txt](https://github.com/the-control-group/voyager/files/859261/nav.blade.txt)

**Comment by qodeanil** [comment]
[nav.blade (1).txt](https://github.com/the-control-group/voyager/files/859266/nav.blade.1.txt)

**Comment by fletch3555** [comment]
The menu is designed to not have working links on an entry with children.

**Comment by Ferrisbane** [comment]
That does not sound correct... if you add child items to a menu you should be able to click on the CHILD links.

**Comment by fletch3555** [comment]
You're correct, I misread the issue.  However, I was unable to reproduce the issue.  @akazorg, have you heard of any other reports of this?

**Comment by akazorg** [comment]
@fletch3555 not that I've heard about. 
I see this is related to the Boostrap menu only, maybe we could use @qodeanil solution.

**Comment by lancepioch** [comment]
Labels: possible bug, bugfix

**Comment by handiwijoyo** [comment]
Close due inactivity.
