### ISSUE TITLE
Error on new Voyager installation 

### ISSUE THREAD

**Issue by dsamurai** [thedevdojo/voyager#952]
- Laravel Version: 5.3.*
- Voyager Version: 0.1.1
- PHP Version:7.1
- Database Driver & Version:Mysql 5.7 / Maria DB 10.1.19

### Description:
On installing a fresh voyager admin package i get the same error on on the database trying both 5.3 and 5.4. The key too long error. Even after i used the recommended steps to counter this in 5.4 it still gave me an error kindly assist. 

### Steps To Reproduce:
Do a fresh install of voyager. 

All will be fine till i try thwe install command.

![error 1](https://cloud.githubusercontent.com/assets/14809460/23987554/3072dc0c-0a3b-11e7-8920-870aa687bcbd.PNG)

**Comment by dsamurai** [comment]
The line exists. Rather existed before @abdgad

**Comment by marco-solare** [comment]
Seems to be a known issue with some MariaDB Versions. Updating it to the latest version did the trick for me. 

However you should be able to resolve it in laravel by adding some four lines to your AppServiceProvider as described here:

https://laravel-news.com/laravel-5-4-key-too-long-error

See original documentation about index lengths on Laravel Docs here (search for "Index Lengths & MySQL / MariaDB" in your browser if you do not see it right away):
https://laravel.com/docs/master/migrations#creating-indexes

@marktopper Do we have some kind of FAQ section / common pifalls we could put findings like that  to avoid repetetive bugs on the same subject?

**Comment by dsamurai** [comment]
I did the fix, and tried to indicate on the screenshot and it still brought the key too long error. Will try upgrading Mariadb and see thank you for the suggestion @marco-solare

**Comment by marco-solare** [comment]
hmmm, strange. Hope you can get it resolved through an update of the database

**Comment by dsamurai** [comment]
Found a way round db error but now when i install without dummy data, the admin dashboard wont show up.

**Comment by abdgad** [comment]
@dsamurai please share a screenshot of the issue.

**Comment by dsamurai** [comment]
@abdgad here they are from fresh install on 5.3 without changing the key too long procedure steps
![1](https://cloud.githubusercontent.com/assets/14809460/24455134/290d3b40-1497-11e7-9d90-6f36fe9466d0.PNG)
![2](https://cloud.githubusercontent.com/assets/14809460/24455135/290fe9e4-1497-11e7-8229-988bdd62a4a2.PNG)
![3](https://cloud.githubusercontent.com/assets/14809460/24455136/293b96b6-1497-11e7-9f4d-b9de04c075a3.PNG)
![routes file](https://cloud.githubusercontent.com/assets/14809460/24455137/2948dc22-1497-11e7-8ca2-2a1e7a7e0ae5.PNG)
![views folder](https://cloud.githubusercontent.com/assets/14809460/24455138/294fc7e4-1497-11e7-9bdd-c4de80f4f443.PNG)
There is no dashboard admin blade file, the routes file does not contain admin routing.

**Comment by abdgad** [comment]
I don't understand how you found a workaround the db error if it's still popping up.
Take a look at [this](https://github.com/the-control-group/voyager/issues/901#issuecomment-287130500) to help you fix the db error.
After that, run `php artisan voyager:install`, you should not see any errors. Then go to `/admin` to view the admin dashboard.
