### ISSUE TITLE
"Color in RGB or hex (optional)" in menu builder not work in the menu button #help

### ISSUE THREAD

**Issue by renamate** [thedevdojo/voyager#955]
- Laravel Version: 5.4
- Voyager Version: 0.11.7
- PHP Version: 7.1.0
- Database Driver & Version: mysql 10.2.3-MariaDB-log

### Description:
hello the feature of "Color in RGB or hex (optional)" in menu builder not work in the menu button how can i make it work? thanks!

### Steps To Reproduce:
Create a new menu item
Set color
Then the color is not showing

**Comment by fletch3555** [comment]
Closing due to age.  If this is still an issue following the 1.0 release, please create a new issue and we'll look into it.
