### ISSUE TITLE
[Feature Request] Add Auth/Role for access to voyager

### ISSUE THREAD

**Issue by fletch3555** [thedevdojo/voyager#96]
Like many developers, I'd rather not give all site users access to edit my database (just for one example).  Perhaps we could add role-based authentication for Voyager pages.  The simple version would just be to require users have the "Admin" role to log in.  A more complex solution might add a Permissions page that lets you control access by role by feature (Database, Pages, Users/Roles, etc.)

Since Voyager already has authentication and roles defined, it doesn't seem to be much work to implement role-based authentication to Voyager.  Just add an "voyager-admin" (or something similar) role to the RoleSeeder and add a check for the role on voyager pages (good use for middleware? Perhaps Auth has a feature to do this easier?)

@tnylea your thoughts? I can probably get started on the "simple" solution above if you'd like.  Not sure I have time to run with a more complex solution right now.

**Comment by handiwijoyo** [comment]
I agree, and i've thinking about this for a moment. 

What i'm thinking is to provide role selection for each bread, so only allowed roles can acceess that data types, and also same implementation for admin menu, so it will only show for certain roles. 

And one more question come across my mind is do we really need role groups, then each role has many permission?

I don't know, maybe someone can offer more better solution?

**Comment by handiwijoyo** [comment]
@fletch3555 @tnylea I've created a feature that add developer column to users table. This allow us to hide menus, database & settings. I also create a new middleware to check if the user is a developer. 

You can find the commit here https://github.com/handiwijoyo/voyager/commit/4e62651dba4648ed64951df33f4982dcbbd4f1fa

Please give me your thought. I can add it to PR if you want.

**Comment by fletch3555** [comment]
Role-based permissions were added as part of v0.10. Closing this issue
