### ISSUE TITLE
BREAD not updating after upgrade to v0.11.7

### ISSUE THREAD

**Issue by cadmicro** [thedevdojo/voyager#960]
- Laravel Version: 5.4 (latest)
- Voyager Version: 0.11.7
- PHP Version: 7.1
- Database Driver & Version:

### Description:

Bread is saving, however when I reload the 'edit' page for adding an item, it shows only text inputs, instead of the select and other inputs I added on the bread...

This wasn't a problem before.

### Steps To Reproduce:

1. Create Database table.
2. Add Bread -> Add a select dropdown, with some JSON.
3. Add new database item to the Menu Builder, and add ROLE permissions.
4. Go to new page, and click "Add New"
5. The page has only textfields....
http://i.imgur.com/VlROdev.png

**Comment by abdgad** [comment]
Did you follow the upgrade guide: https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading

**Comment by sarath-c-sandwich** [comment]
Did you forced to upgrade assets?
```
php artisan vendor:publish --tag=voyager_assets --force
```
migrate table to make sure you are up to date with latest schemas.
`php artisan migrate`
Is it a fresh install or upgrade from version 0.10.* ?
