### ISSUE TITLE
ErrorException in MenuItem.php line 66: Undefined index: parameters (View: C:\xampp\htdocs\syntax\vendor\tcg\voyager\resources\views\menu\admin_menu.blade.php) 

### ISSUE THREAD

**Issue by farizree** [thedevdojo/voyager#962]
- Laravel Version: 5.3
- Voyager Version: 0.11
- PHP Version: 5.6.4
- Database Driver & Version:

### Description:
After I run my composer update into voyager 0.11 from 0.10 I found this error 
![image](https://cloud.githubusercontent.com/assets/25852713/24059003/e705ad9c-0b7f-11e7-9b07-ddd38d2ac759.png)

**Comment by abdgad** [comment]
The answer is in #958
Also, please follow the upgrade instructions [here](https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading-version-010-to-011).
