### ISSUE TITLE
Laravel 5.4 strict issues

### ISSUE THREAD

**Issue by yoramdelangen** [thedevdojo/voyager#966]
- Laravel Version: 5.4
- Voyager Version: 0.11.7
- PHP Version: 7.0.14
- Database Driver & Version: MySQL Ver 15.1 Distrib 10.1.20-MariaDB, for osx10.12 (x86_64) using readline 5.1

### Description:
We new installation from Laravel 5.4 by default Laravel comes with `database.connections.mysql.strict = true`. This cause all text fields to crash without a default value/not nullable if its not set in the insert statement.

**Comment by abdgad** [comment]
Mysql `text` fields cannot have a default value. And this is a Laravel issue. What can Voyager do to fix it?

**Comment by abdgad** [comment]
You can change non required fields to be `nullable` in order to avoid that issue.

**Comment by yoramdelangen** [comment]
But not fixing it isn't a proper solution aswel. I'm not sure in whats the best way for fixing it, but maybe someone has a good idea for it?

**Comment by abdgad** [comment]
If you set a field to be `not nullable`, then the database will force you to insert a value into that field. If you don't want to insert a value, then you can make the field `nullable`. Voyager can do nothing to fix this.
Do you have another suggestion?
