### ISSUE TITLE
how to display the dropdown menu in version 0.11.7 ?

### ISSUE THREAD

**Issue by farizree** [thedevdojo/voyager#967]
- Laravel Version: .5.3
- Voyager Version: 0.11.7
- PHP Version: 5.6.4
- Database Driver & Version:

### Description:

69/5000
I have a dropdown menu in the menu blogs, but can not appear.
![capture1](https://cloud.githubusercontent.com/assets/25852713/24075191/6cd521ea-0c49-11e7-9de7-c0492e4e5b72.JPG)
![capture](https://cloud.githubusercontent.com/assets/25852713/24075192/70b5a5be-0c49-11e7-9913-d2ccb605106f.JPG)

this is my script my_menu.blade.php
```
<ul class="nav navbar-nav">
    @foreach($items as $menu_item)
        <li class="dropdown"><a href="{{ $menu_item->url }}">{{ $menu_item->title }}</a></li>
    @endforeach
</ul>
```

**Comment by sarath-c-sandwich** [comment]
Can you var_dump that menu object? To check whether the object contains sub-menu object.

**Comment by abdgad** [comment]
Each `menu_item` has a `children` relationship, so you can use it to get sub menus.
You can take a look at the views [here ](https://github.com/the-control-group/voyager/tree/master/resources/views/menu)to get more ideas.
