### ISSUE TITLE
Model not creating 

### ISSUE THREAD

**Issue by azarzaza** [thedevdojo/voyager#97]
First of all thanks for great feature of voyager. 
now i am come to error. when creating a table with model, model doesn't created i was created the model as manually so fix this error

**Comment by cyberS7** [comment]
You just need choose the answer for question "Create model for this table?". Set it to "Yes, please"

**Comment by azarzaza** [comment]
yeah i am already choose that option still model cant be created 
i am searched the created model in source directory 
tcg\voyager\src\Models

but my model not created

**Comment by filipsobol** [comment]
Models are created using artisan make command, so they are placed in App/ directory.

**Comment by cyberS7** [comment]
Yes, they plased at App/ directory

**Comment by akazorg** [comment]
@azarzaza Are you using Laravel 5.3? Maybe it's an issue related to older versions.

**Comment by azarzaza** [comment]
yeah i am using laravel 5.3

**Comment by marktopper** [comment]
Is this still an issue in the latest version?

**Comment by fletch3555** [comment]
Closing as inactive.  @azarzaza, please let @marktopper or I know if this is still an issue and we can reopen this.

**Comment by marcio-machado-k** [comment]
Using Laravel 5.5.
Create the tables with the model option set to YES.
Create the breads.
When I go and try to create a BELONGS TO MANY relationship, I get:

"Model Class does not exist. Please create model, before creating the relationship."

What am I missing?

**Comment by fletch3555** [comment]
@marcio-machado-k, this issue has been closed for nearly a year. Please open your own issue.

**Comment by marcio-machado-k** [comment]
Sorry. Done it: https://github.com/the-control-group/voyager/issues/1843
