### ISSUE TITLE
Unknown column 'controller' in 'field list'

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#970]
- Laravel Version: New
- Voyager Version:  New
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:

When i try create some bred, i see this exception 
It worked, but i think i broke some configure :(

Update Failed Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'controller' in 'field list' (SQL: update `data_types` set `description` = , `updated_at` = 2017-03-19 13:52:15, `controller` = where `id` = 5)

http://www.screencapture.ru/uploaded/8b/ed/94/8beD9422.jpg  Problem screen
How i may fix it?

**Comment by abdgad** [comment]
run:
`php artisan vendor:publish`
`php artisan migrate`
