### ISSUE TITLE
[ASK] retrive data in other table using foreign key

### ISSUE THREAD

**Issue by hyugihc** [thedevdojo/voyager#971]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.7
- PHP Version: 7.1.*
- Database Driver & Version:

### Description:
I want to ask how to browse / retrieve data in other table using foreign key with voyager's BREAD. let say. I have pivot table, let call it transaction_tabel which is consist of customer_id (primary key on customer_table), and product_id (primary key on product_table). I want to show transaction_tabel BREAD with customer_name and product_name instead of its id. can I do that? thanks for your answer..

**Comment by georgenacouzi** [comment]
any info how that is done?

**Comment by fletch3555** [comment]
I'm not sure exactly what you're asking for, but the docs should point you in the right direction: https://the-control-group.github.io/voyager/docs/0.11/#core-concepts-bread-relationships

If you need further help, I recommend joining the #help channel in our Slack group (instructions for joining can be found in the project README file.
