### ISSUE TITLE
settings Type is file 

### ISSUE THREAD

**Issue by zanjs** [thedevdojo/voyager#973]
- Laravel Version: 5.4.*
- Voyager Version: 0.11.7
- PHP Version: 7
- Database Driver & Version:5.7

### Description:

settings page upload type is pdf

### Steps To Reproduce:

- settings add Type is file 

- upload file is pdf

![_20170320105154](https://cloud.githubusercontent.com/assets/12947276/24087555/6e2c34f8-0d5b-11e7-9e02-e3811c4f7299.png)

**Comment by Frondor** [comment]
Because its looking for an image... We clearly need to revamp the media manager.
I'd love to use Vue components so we can load the manager anywhere in a modal, and select the proper file(s).
I'll create a separated issue with some suggestions about a new file manager.

**Comment by zanjs** [comment]
@Frondor Thank you.

**Comment by fletch3555** [comment]
Closing this in favor of #980 and others to track Media Manager changes.
