### ISSUE TITLE
Update BREAD has no effect in CREATE

### ISSUE THREAD

**Issue by matedon** [thedevdojo/voyager#974]
- Laravel Version: 5.4
- Voyager Version: 0.11.7
- PHP Version: 7.0.15
- Database Driver & Version: mysql 14.14

### Description:
http://site.local/admin/place/create
The form remains old.

### Steps To Reproduce:
1. Create new table: place (Sure: the table is empty!)
2. Create new BREAD with default all input is a checkbox
3. Test if http://site.local/admin/place/create works: yes it is ok
4. Modify BREAD to set up suitable input types like Text or Richtext for the table keys
5. Save
5. Refresh /place/create but there are just checkboxes! :(

### Question
Please tell me: where are those BREAD settings stored in the system. I dig up the database and the project file structure but not found.

Thank you!

**Comment by matedon** [comment]
Ok. Furher investigation gave the result: BREAD settings stored in the DB "data_types" and "data_rows" table.
I have tried to create similar table names after delete the previous.
Somehow the deleted one stucked in these "data_" tables.

**Comment by abdgad** [comment]
To avoid this problem, you should delete `BREAD` before deleting the table from the Database.

**Comment by niyobobo** [comment]
No way that i can update my database views (like editing BREAD) without deleting it then recreate.
because i have created BREAD on my database table but later when i tried to make some change on it nothing really change to the actual layout of my db_table view
