### ISSUE TITLE
Populating panel-side pages in the menu?

### ISSUE THREAD

**Issue by RPBTwisted** [thedevdojo/voyager#976]
- Laravel Version: Current
- Voyager Version: Current
- PHP Version: 7.10
- Database Driver & Version:

How do you populate the menu pages made with the builder? I have a "servers" section in the menu, with "all servers" and "my servers" in the dropdown. The pages literally only need to have a PHP script running on each that I already have ready, but I don't know where the pages are to edit them. I have set up the BREAD for it, but that's all. Fairly new to this. It's all I need to finish my assignment, so I'm desperate even if it means paying for it to be done haha.

**Comment by RPBTwisted** [comment]
Essentially, I would like to assign the "All Servers" page of the Voyager panel to admins only and use my script to list every server, and on the "My Servers" I would use the same script but remove every server other than the ones I want people with the "user" role to be able to see? If that makes sense. 

If it takes someone doing it for me, I'll gladly get in touch with you privately and pay for it. My dissertation is due in soon. Ideally I should have just written it in raw PHP, but it's a little late now.

**Comment by abdgad** [comment]
Do `my servers` and `all servers` have associated tables in the database?

**Comment by RPBTwisted** [comment]
Yeah I've made two tables and associated them.

**Comment by RPBTwisted** [comment]
If it's easier I could just give you access via SSH

**Comment by abdgad** [comment]
You can `Edit BREAD` for those tables, and set a custom controller. In the controller, you can override the methods and customize them as you wish.
For example, the controller might look like this:
```php
<?php

namespace App\Http\Controllers;

use TCG\Voyager\Http\Controllers\VoyagerBreadController;

class ServersController extends VoyagerBreadController
{
    public function index(Request $request)
    {
        // Check permission
        Voyager::canOrFail('browse_all_servers');

        // Return a view that contains your PHP script
        return view('servers');
    }
}

```

In the corresponding `BREAD`, set the controller to be `\App\Http\Controllers\ServersController`.

**Comment by RPBTwisted** [comment]
I should mention that I'm **really** new to Laravel and Voyager. It's a confusing concept for me still :(

**Comment by abdgad** [comment]
Please go on Voyager slack for more help.

**Comment by RPBTwisted** [comment]
I am. Should I just post in general or?
