### ISSUE TITLE
install voyager within existed database

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#978]
Hi, 

I have already have lots of tables in my existing database and I want to add voyager as my administrator pages.

Before installing voyager, I already have a User table and it conflicts with voyager. 
Is it possible to change (or add a prefix) to a voyager's User table?

Here are the commands and errors:

`php artisan voyager:install`

`SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists`

Thank you.

**Comment by abdgad** [comment]
Voyager doesn't create the `users` table. There is probably another migration in `/database/migrations` that is trying to create it. You need to take a look at it.
And at the moment, you can specify a custom table by following steps in #934. However, you will need to modify some of Voyager's migrations manually as they currently have `users` table hard coded in them.
You can run: `php artisan vendor:publish`, and Voyager's migrations will be in `/database/migrations`. After modifying them, run `php artisan voyager:install`.

**Comment by mustafaabduljalil** [comment]
@abdgad
u said i should write protected $table="admins" in User model ok it's good but this model i use it with my exist users table and has relations with another tables so there will be error and conflict  right ?

**Comment by abdgad** [comment]
@mustafaabduljalil you can follow the method described in #934 and create a new Model. You don't have to call it `User`. You can call it `Admin`.
