### ISSUE TITLE
Media Manager revamp (2.0)

### ISSUE THREAD

**Issue by Frondor** [thedevdojo/voyager#980]
I think we have to improve the media manager, quite a lot if we want to provide better handling of file-related input fields.

### Why?
 - The main point is being able to select a file (or files) from _BREADs_ by simply browsing a list of files or upload a new one in the moment. Actually, you can only modify a file for a BREAD by uploading a new one, and "leave it blank" when editing the whole BREAD entry. **We can't use something like `required` validation rule on that field because of that**.
This is an example of what I'm talking about #973 

### How?
This is how I would address the project
 - Create 2 components: `media/Browser.vue` and `media/FileInput.vue` with the following API:

<table>
  <tr>
    <th colspan="4">Browser.vue</th>
  </tr>
  <tr>
    <th>Props</th>
    <th>Values</th>
    <th>Description</th>
    <th>Default</th>
  </tr>
  <tr>
    <td>selectable</td>
    <td>(string) <code>single</code>/<code>multiple</code></td>
    <td>If provided, an extra button will show up when selecting one (or more if its `multiple`) file to chose it, and set the input to the file's URL(s)</td>
    <td><code>null</code></td>
  </tr>
  <tr>
    <td>file-types</td>
    <td>(array) <code>[]</code></td>
    <td>If provided, the browser shall list only the given file types (for input modals mostly)</td>
    <td><code>[]</code></td>
   </tr>
  <tr>
    <td>accepts</td>
    <td>(array) <code>[]</code></td>
    <td>Used for file upload puproses, see <a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept" target="_blank">input</a> </td>
    <td><code>['jpg','png','gif']</code></td>
   </tr>
</table>

<table>
  <tr>
    <th colspan="4">FileInput.vue</th>
  </tr>
  <tr>
    <th>Props</th>
    <th>Values</th>
    <th>Description</th>
    <th>Default</th>
  </tr>
  <tr>
    <td colspan="4"><i>Since its kind of a wrapper for the browser, it accepts all props for <code>Browse.vue</code> plus some more. It doesn't shows the file browser by default, just opens a modal with it instead and displays selected files as thumbnails with controls</i></td>
  </tr>
</table>

 - Then call `Browser.vue` from `/admin/media` and `FileInput.vue` from `/{bread}/{create / edit}` (which can be a bit tricky at the moment of loading the js file once, the `formField` view should be able to `@push('scripts')` this file, but we have to realize how to handle multiple file fields.

Basically, `FileInput` component hides a text input with a "stringified" JSON that we `json_decode/encode` server-side for a list of files, depending if the field works for single or multiple files, and save it into DB just like that.
Internally, the `Browser` may calculate the directories (like a router) based on the file URL and open in that specific folder if a file was already chosen previously.

### Caveats:
 - A proper vue.js development implies the use of a build tool (like `laravel-mix`). We can't force every user to manually include our assets to their `webpack.mix.js` file so in that case, I think a new command `php artisan voyager:build` or something like that (we can even extend the current `voyager:install` to also compile assets) would be needed. Unless we want to provide a built-in bundle and simply use the publishing functions, to be honest, I'm not sure about it.

I'd like to know your thoughts and suggestions on this before getting hands dirty.

**Comment by abdgad** [comment]
At the moment I still don't know how the Media Manager works. Will take a look at it later.
For developing Vue components, we can use Blade (like in the [database](https://github.com/the-control-group/voyager/tree/master/resources/views/tools/database/vue-components) section).
Using that approach, we won't need a build tool. Also, they will be easy to include in the Views, we can create helper functions for that. And in case we ever need to switch to proper single file components, it won't be hard to migrate them.

**Comment by marktopper** [comment]
While doing this complete remake. I also recently found this [Finder](https://studio-42.github.io/elFinder/) that we maybe could get a lot of experience from. Their system reminds me a lot of the finder that is available on Mac.

According to handling the Vue.js development and allowing full flexibilty to the users, we should publish and build the Vue components as you say, but let anyone overwrite any component if possible.

**Comment by Frondor** [comment]
@abdgad I think you got reaaally confused about Vue and components. I was not talking about Blade at all.

@marktopper that library looks really good, but I think it would be a bit easier to implement our own media browser, instead of trying to adapt that one to our needs. Specifically talking about file inputs, input edition, thumbnails and such...

Also there's a contradiction on that about overwriting vue components. That's not possible if we provide the already-bundled js file. I think they can simply override the php view and provide their own libraries, but to be honest, I don't see the point to let users override specific components of the media manager interface.

If we provide the js bundle, then we may need to work with our own compilation script and commands, which is not a big deal but its something to take in mind.
I'm talking about `npm run dev` commands but instead of the ones at the project's root, we use a `package.json` on voyager's root. 
Now my question is, `laravel-mix` or `laravel-elixir-webpack`? Because mix comes with L5.4+, we have to be able to compile these assets also in previous versions. Which leads us to make probably `laravel-mix` a dependency of voyager.
And that leaves us clean road to keep migrating any other UI components to Vue (or similar) in the future, if needed.

I don't know of all this is possible yet, they are just ideas...

**Comment by abdgad** [comment]
@Frondor the database manager is built with Vue components, which are put inside Blade templates ([example](https://github.com/the-control-group/voyager/blob/master/resources/views/tools/database/vue-components/database-table-editor.blade.php)).
I know this approach isn't the best, but it doesn't require any build tools. And it can be easily migrated to Vue single file components.

**Comment by Frondor** [comment]
Now I think I get you! Hmm... Yes, that practice is not good at all.

**Comment by James7777** [comment]
Hi, I have successfully installed voyager but images are not showing. It says, permission denied(firebug). All image links are not working.
How can I go about this? It looks like storage folder is not accessible publically.

**Comment by denbatte** [comment]
I am fine with including it in the install as long as there's an option to only build.
e.g. ```php artisan voyager:install --build```

**Comment by handiwijoyo** [comment]
@Frondor Do you still up for this?

**Comment by Frondor** [comment]
@handiwijoyo Not really, I had started it last year but many subsequent api changes in merged PRs (which I didn't agree with) made me change multiple things in the code, many times, and stopped working on it :disappointed:

**Comment by fletch3555** [comment]
Apologies for that @Frondor.  That should be happening much less frequently now.  I've been personally handling the merging of all PRs, so there's less hands in the cookie jar, and more control over what kind if change goes where.

**Comment by Frondor** [comment]
There's othing to apologize @fletch3555 This is how open source works and got to accept every maintainer decisions.
As I can see, you all have done tons of progress on this regarding to `v1`, congratulations for that! I may re-engage in the future, when I update my 2 websites using Voyager to latest version, thus familiarizing more with the actual api.
