### ISSUE TITLE
How i may use media path?

### ISSUE THREAD

**Issue by Rishats** [thedevdojo/voyager#982]
Laravel Version: New
Voyager Version: New
PHP Version: 7.1
Database Driver & Version: MySQL 5.7
Localization: mcamara/laravel-localization - new

Description:
Hello guys. 
How i may use media path?

Now my storage folder there
D:\Program\OpenServer\OpenServer\domains\rishat.kg\storage\app\public\

When i had url like this - rishat.kg/public/ - slider worked but 
When I changed  my path to  rishat.kg
i have problem with 404 error. Because my jpg files not found. 
http://rishat.kg/storage/app/public/slider/images/1.jpg
D:\Program\OpenServer\OpenServer\domains\rishat.kg\storage\app\public\slider\ (some files jpg)

My slider is dynamic. He will be replenished in the admin panel(media). How in the given case should I be?

**Comment by marktopper** [comment]
Please provide the informations from #834, then I will open the issue again. 😄
