### ISSUE TITLE
first parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by Al-Kaiser** [thedevdojo/voyager#989]
- Laravel Version: 5.4.#
- Voyager Version: 0.11.7
- PHP Version:
- Database Driver & Version:

### Description:
Hello i got this error : **first parameter must either be an object or the name of an existing class**

when i just try to visit  **series page** (made by **## bread**)

please help me :+1:

**Comment by abdgad** [comment]
Please include the full error.

**Comment by Al-Kaiser** [comment]
ErrorException in 74bf346ea66264a1aae31d643cc24af9b55032e8.php line 41:
First parameter must either be an object or the name of an existing class (View: C:\xampp\htdocs\laravel\series\vendor\tcg\voyager\resources\views\bread\browse.blade.php)

**Comment by Al-Kaiser** [comment]
help?

**Comment by fletch3555** [comment]
@Al-Kaiser, Since that's a compiled view file, could you please provide us with line 41 (+/- 10 lines) from that file?

**Comment by Al-Kaiser** [comment]
@fletch3555 thanks found i forgot to add json code for relationships ><

`{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}` 

but after add this json code when try to open **/admincp/series** said 

> :ErrorException in Collection.php line 1440:
> Undefined index: name

but if i try to open **/admincp/series/create or edit** it's work fine and i have my relationship values

**Comment by justin-cook** [comment]
I also get this error (only on the view page) when I have a select dropdown type that does not have a relationship. If I uncheck my "select dropdown" in the bread options the view page no longer errors out.

**Comment by bealers** [comment]
I just had the same problem & it's easily fixed with a bit of [RTM](https://laravelvoyager.com/docs/0.11/#core-concepts-bread-relationships). The relationships need defining via the model and also the config in the bread set-up view

**Comment by lancepioch** [comment]
Labels: invalid

**Comment by emptynick** [comment]
This can be closed

**Comment by MohsinNadeem** [comment]
I am facing the same problem, Please explain solution.

**Comment by fletch3555** [comment]
@MohsinNadeem I seriously doubt it's the same error since this was from ~8 months ago and on a significantly older version of Voyager.  Please open your own issue for assistance

**Comment by moisesh18** [comment]
I went through this error when in my BreadSeeder, in "details" I put "null", instead of "{}". Basically this error appears, if column "details" in dataRows is different than json.
![image](https://user-images.githubusercontent.com/31388995/75413856-5af8c380-58ec-11ea-967e-187035b18dee.png)

**Comment by fletch3555** [comment]
@moisesh18, please don't comment on issues that have been closed for so long (nearly 3 years in this case).
