### ISSUE TITLE
BREAD pattern validation.

### ISSUE THREAD

**Issue by georgenacouzi** [thedevdojo/voyager#992]
- Laravel Version: 5.4.16

- Voyager Version: 0.11.7

How to validate an input based on a **regular expression?** 
what it the right syntax to put in **Optional Details**  while editing the BREAD ?

i already used:
`{
"validation": {
        "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
    }
}`

`{
   "type": "string",
   "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
}`

`{
    "validation": {
        "rule": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
    }
}`

and is there any way to do this outside the BREAD page on the admin panel?
thanks for the help

**Comment by georgenacouzi** [comment]
found it, it was silly but for the noobs like me :
`{
    "validation": {
        "rule": [
            "required",
            "regex:^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
        ],
        "messages": {
            "required": ":attribute is required.",
            "regex": "not a vaild pattern"
        }
    }
}`

**Comment by turtuga** [comment]
{
    "validation": {
        "rule": "regex:pattern"
    }
}

**Comment by georgenacouzi** [comment]
@turtuga 
i was reading in the documentation about overriding views, but i can't find this path:
resources/views/vendor/voyager/

do i have to create it?
thanks.

**Comment by turtuga** [comment]
You can do this on vendor/tcg/voyager/resources/views

**Comment by georgenacouzi** [comment]
thank you
