### ISSUE TITLE
Symlink Error in Shared Server

### ISSUE THREAD

**Issue by kcpradyp** [thedevdojo/voyager#997]
- Laravel Version: 5.3.*
- Voyager Version: 0.11.6
- PHP Version:5.6.4
- Database Driver & Version:

### Description:
my app is in production and i cant create symlink in my shared hosting. I have tried `php artsian storage:link` and works fine in local development environment but not in production sever. 

`error: symlink(): no such file or directory`

can  i do anything so that i can directly upload my files in public folder instead of storage\app folder

I have tried making disk in config/filesystems.php as

```
'voyager' => [
	        'driver' => 'local',
	        'root' => public_path('storage'),
	        'url' => env('APP_URL').'/storage',
	        'visibility' => 'public',
        ],
```
this too works in at local server and not in production server

**Comment by Frondor** [comment]
This issue does not relate to voyager.

See: https://github.com/the-control-group/voyager/issues/898
